### ISSUE TITLE
Cursor is not hidden during video playback

### ISSUE THREAD

**Issue by aproposnix** [FreeTubeApp/FreeTube#10]
Small papercut here. 

On Linux (Ubuntu 18.04) when I fullscreen a video, I would expect the cursor to auto-hide. This is not the case though as the cursor just sits on top of the video. It kind of annoying and distracting. 

Can someone test this on Windows or Mac?

**Comment by PrestonN** [comment]
I will be working on this in the morning.  Should be able to get it done before a new release tonight.

**Comment by PrestonN** [comment]
This has been fixed.  Will be included in the next release.  The plan is to build and release later tonight.
