### ISSUE TITLE
Release 0.3.X Beta Discussion

### ISSUE THREAD

**Issue by PrestonN** [FreeTubeApp/FreeTube#100]
Hey everyone!  Please leave your feedback for 0.3.X here.  I'd love to hear what you think about it!

To start off the discussion, I'd like to ask a few questions to the community.

I'd like to setup some sort of chat room for FreeTube discussion.  What's your favorite method of doing this?  This could be a form of IRC or a Riot chat room or something completely different.  Please keep the suggestions privacy based. :)

I'd like to work on a unique look for the video player in FreeTube.  Would you like a carbon copy of YouTube's player or something different?  If something different, please leave screenshots if you have any.

For this release, I just setup some pages on the [Wiki Page](https://github.com/FreeTubeApp/FreeTube/wiki).  Is there anything you'd like to see included in this page?

### What's Next?
Next up for FreeTube is looking to be exciting.  The team over at NewPipe seems to be close to getting their extractor ready for third party developers.  I will be working with them on implementing this into FreeTube and replacing the YouTube API entirely.

Implementing this will fix things that have already been solved by NewPipe such as 1080p+ support.  I think the best route for FreeTube is to work on other features in the mean time and then use the NewPipe Extractor to add 1080p+ support and other features.

While waiting, the plan is to try to work on some quality of life things for FreeTube, such as more settings for defaults and on improving the browser extension.  I'd love ideas towards this if you have any.

Thanks again for your support!  I really appreciate it! :)

**Comment by LexHimself** [comment]
Hi,

The app looks great so far! I really like the tor addition although it requires some effort from the user.  
My prefered method of chat is IRC. Discord is also an option, just set up a server and people can join it. With discord you can set up certain channels, might be more convenient.

Suggestions: 
- Use Tor2web instead of running tor. 
- Add an option to sort comments by likes instead of the default 'newest'
- Clearing the history and such should not require a restart, would it be possible to change this behaviour? 

Issues:
- Clicking on help will try to open the link in your default browser
![2018-06-03-165859_883x256_scrot](https://user-images.githubusercontent.com/12938372/40887891-b35cc3c2-674f-11e8-946f-969d3c79cbd8.png)
- Installation instructions for Tor on Mac require Homebrew.

Might encounter more, just a bit short on time recently :)

**Comment by big610** [comment]
Dropped by immediately after finding about Microsoft's purchase of GitHub, to see if I could still Sign In, Download & save a copy, without having to change over to a Microsoft Account.
Could you look into an Alternative Mirror, applying to, docs.microsoft, SourceForge, MajorGeeks, Softpedia?
Also I've been asked do you have plans for a 64-Bit macOS app?

**Comment by PrestonN** [comment]
To start off, I'd like to say that the first release of FreeTube Redirect for Firefox is now public.  There are still a few issues that I need to iron out, but you can check it our [here](https://addons.mozilla.org/en-US/firefox/addon/freetube-redirect/).  The Chrome release will most likely be postponed until I can get a Google account created without giving them my phone number.  I'll be working on getting this out as soon as I can.

Big post with answers coming up!

> Clicking on help will try to open the link in your default browser
> (Normal behaviour, i do not have a default browser set.)

This was the intended behavior, but I guess I didn't think about someone not having a default browser.  This idea is to have it link to the [Wiki](https://github.com/FreeTubeApp/FreeTube/wiki) page that way help information will always be up to date.  I'll change this slightly to make it more obvious in the next update.

> Installation instructions for Tor on Mac requires Homebrew.

The [package](https://www.npmjs.com/package/tor-request) that I'm using requires that the Mac is setup in this way.  I don't know of any other way to set it up with this current package but I can put a note on there that homebrew is required.

> Opens with 720p set. I need to click play or switch to 480p for it to play. Worked fine on a previous release.

I've noticed this too, but I haven't figured out the exact source of the problem.  It shouldn't have anything to do with youtube-dl being local as the links work fine when opened in a browser and this issue has been more recent since I've changed youtube-dl to run locally.  I plan on taking a closer look at this.

> Screenshots in the readme.md are outdated.

Opps, I had screenshots ready for the new release.  I'll get those updated tonight.

> Use Tor2web instead of running tor.

Please correct me if I'm wrong, but [tor2web](https://github.com/globaleaks/Tor2web) looks to be for access Onion sites without needing to be on the Tor network.  I'm not sure how this would be used for accessing the Tor network for API calls.

> Add an option to sort comments by likes instead of the default 'newest'
Clearing the history and such should not require a restart, would it be possible to change this behaviour?

These should be some good quality of life things that I'd like to work on for next release.  I'll keep these in mind.

> Place the logo to the left as before, looks better in my opinion.

I talked to a couple people about this actually.  My reasoning for having the logo on the right is that now the space on the left is open for navigation for when I can get around to working on back / forward functionality.  While right now the logo looks better on the left, I believe it will be better on the right when I get back and forward arrows up there.  I'm open to suggestions on this though.

> My prefered method of chat is IRC. Discord is also an option, just set up a server and people can join it. With discord you can set up certain channels, might be more convenient.

With FreeTube being a privacy based application, I don't think Discord is the best step forward for communicating with users.  What do you think about [Riot](https://about.riot.im/)?  It's similar to Discord but is more privacy friendly and has E2E Encryption.

> Could you look into an Alternative Mirror, applying to, docs.microsoft, SourceForge, MajorGeeks, Softpedia?

I've made some serious considerations about doing this.  I don't like Microsoft very much and I don't know of what changes will happen now that they have GitHub.  The problem right now is that FreeTube isn't big enough to make rash decisions like shutting down the GitHub repo and jumping ship to a new platform.  A vast majority of people that keep track of FreeTube probably won't move over with the project which could be detrimental to FreeTube's momentum.  I believe that the best idea with this is to switch to a new platform (most likely GitLab) and mirror commits / releases here on GitHub.  I plan on doing research over the following week to figure out how to get this working.

> Also I've been asked do you have plans for a 64-Bit macOS app?

I'm assuming this is talking about building a .dmg package.  My problem with this has been that I don't have access to a Mac so that I can make proper builds for it.  I think I can get access to a virtual machine which would allow me to do it but I'd rather have actual hardware to do testing on.  Until then I don't know when I'll be able to.  I'll keep an eye out for it.

**Comment by LexHimself** [comment]
> The package that I'm using requires that the Mac is setup in this way. I don't know of any other way to set it up with this current package but I can put a note on there that homebrew is required.
Please correct me if I'm wrong, but tor2web looks to be for access Onion sites without needing to be on the Tor network. I'm not sure how this would be used for accessing the Tor network for API calls.

I had not looked into the source yet. As i can see from the package used, it would be possibe to connect to a host running Tor and send the requests through there. Tor2Web would be a bad for this. 
Another issue that arrises is that a Tor connection sometimes can be unstable and requires a restart of the Tor client. Makes sense now and best to leave it as is. 

> While right now the logo looks better on the left, I believe it will be better on the right when I get back and forward arrows up there
Makes sense.

I have learned about Riot about 3 days back, did not have the time to look into it. From what i have seen it does look promising. The advantage it has over Discord, except from the encryption, is that an email address and phone number are optional, it has my vote. 

> I'm assuming this is talking about building a .dmg package

I have found some proposed solutions assuming you are using Linux: https://stackoverflow.com/questions/286419/how-to-build-a-dmg-mac-os-x-file-on-a-non-mac-platform
It think the user is referring to the following though: 
`    "make:darwin": "electron-forge make --platform=darwin --arch=x64",`

**Comment by Joseph65** [comment]
could you add support for playing in external player like mpv or vlc
scaled window and cpu use are a few advantages in using mpv.

**Comment by grrrrr** [comment]
> Use Tor2web instead of running tor.

These should never be used, you are placing your trust fully in the operator of the site who can see everything you do.   But as @ghost says it is of no use for this application as it's for accessing .onion addresses from clearnet

**Comment by PrestonN** [comment]
My plan is to make a proper announcement about a new Riot server alongside the next release.  The next release will be mostly bug fixes so hopefully I can get it out next week.  My schedule has been busy lately so it's been difficult to work on FreeTube.

I mentioned in my last comment about potentially moving to GitLab or something similar.  I've had some time to think about it and look at responses from other groups.  For now my plan is to continue focus on this GitHub repository.  I'm open to hearing anyone's thoughts though if you disagree with me.

The argument that I've seen (Even in privacy focused repositories) is that all of the code / discussion is already public and in the grand scheme of it means that it doesn't matter very much as to who owns the website that it's hosted on.  GitLab is also transitioning to Google web servers which would give little to no benefit to moving in a privacy perspective.  The last reason is simply because GitHub is the largest platform.  There is a much better chance of new users finding and getting involved with FreeTube.  It also means that there is a better chance of more people contributing towards the project (something FreeTube could really use).

> Opening the mini player will also allow the 720p video to start playing, perhaps it helps to troubleshoot.

I think I was able to figure out the issue.  When you load up a video, FreeTube will check the video URLs to make sure they are valid.  Sometimes a URL is given but will not load if you attempt to use it.  This would typically happen on newly uploaded videos so I would check and automatically switch the quality if the URL wouldn't work.  I believe it was being called too early and forced the player to not load the video for some reason.  I've added a delay to this check and seems to have fixed it.

> I have found some proposed solutions assuming you are using Linux: https://stackoverflow.com/questions/286419/how-to-build-a-dmg-mac-os-x-file-on-a-non-mac-platform
It think the user is referring to the following though:
"make:darwin": "electron-forge make --platform=darwin --arch=x64",

I appreciate the link.  My problem with doing that is that I wouldn't be aware of any problems or how to fix them if anything happened.  I'd like to have a Mac on hand to do testing with just to make sure.  For now I don't have plans on buying one so I'm going to just stick with the portable version for now.

> Found a bug in the channel view. If a channel does not have a banner set, somehow a default one is returned?

I think I remember seeing this before.  Should be a quick fix though.  I should be able to include that in the next patch release.

> Would you allow more themes to be added in the feature? This could be done as with the translation, just make a pull request, stating the theme name, and selecting if from a drop down menu in the settings for example.

There's actually been some discussion about this (#38).  In a nutshell, I have no problem adding more themes and I would include any with the project if the community wants to make some.  My problem right now is that there are other things that I should probably prioritize on working on before I start doing theme support.

> could you add support for playing in external player like mpv or vlc

This has been mentioned to me before.  It's possible but like the theme support I'd like to prioritize other things before I work on something like this.

**Comment by LexHimself** [comment]
` I've added a delay to this check and seems to have fixed it.`
Confirmed from my end. Thanks for the fast action on this one. 

`For now I don't have plans on buying one so I'm going to just stick with the portable version for now.`
Running OS X in a virtual machine would also be an option. Works the same as a real Mac. 

Can't wait for the Riot thing being set up :)

**Comment by PrestonN** [comment]
You guys are awesome.  We just hit 300 stars on GitHub!!  I'm very glad that I've been able to provide something useful and functional to the privacy community.  I learn a lot from staying involved with the community so I'm glad that I can give back to everybody.  Expect a patch release this weekend. :)

> Running OS X in a virtual machine would also be an option. Works the same as a real Mac.

Yeah I can probably do that.  I think I can get access to an ISO from somebody.  I'll try to do some testing and see what works out.

**Comment by dimqua** [comment]
Can you please add an option to disable auto-update checks?

**Comment by WK-M** [comment]
Is looping of a single video going to be available on next release?

**Comment by big610** [comment]
Add an option to, Play Back-To-Back, (without having to start next video), 
with an option to disable that plays just one video & stops.

**Comment by PrestonN** [comment]
> Can you please add an option to disable auto-update checks?

> Is looping of a single video going to be available on next release?

These will be in the next major release.  I'm planning on a "quality of life" theme for the next release which should include things like these.  Would love some suggestions for more if you have any. :)

> Add an option to, Play Back-To-Back, (without having to start next video),
with an option to disable that plays just one video & stops.

I would probably keep this off by default if I included this.  I'm assuming the idea is that it would play the first video in the recommendations section?  My only concern with doing this is that the recommendations might not be very relevant to what would ideally be played next (I believe I've seen multi part video series have the next episode several videos down instead of being at the top).  I'll keep this in mind though.

> I still notice app freezing.

What sort of freezes are you seeing?  This is the first time I've heard of this issue.

Quick Update on FreeTube progress:

Like I mentioned above, the next release will be themed around "Quality of Life".  So the idea is to have a lot of small but useful to make the app experience better.  Good examples would be disabling history and setting the default quality for videos.

To go along with this theme, I have been busy implementing Vue.js into FreeTube.  Vue.js is a powerful templating framework similar to Angular or React which allows views to intelligently hide and show while keeping things speedy.  The implementation is tiny (less than 300kb) and opens up a lot of doors for future features in FreeTube.  Features like tabs, back/forward navigation, and picture in picture will be much more possible with this implementation.  I could go into much more detail as to why this is a good thing, but FreeTube should overall feel much smoother overall once it's ready.  This will be a huge change in the back end so I'd like to have a couple of people help me out with testing if anyone will be available.  I will keep everyone up to date when I'm ready for testing.

**Comment by b4zz4** [comment]
search in html static?

wget --no-check-certificate "https://www.youtube.com/results?search_type=&search_query=${BUSQUEDA}&aq=f&page=${N}" -qO

**Comment by PrestonN** [comment]
> search in html static?
https://www.youtube.com/results?search_type=&search_query=search&aq=f&page=1
without Youtube API ...

This is something that's been mentioned a bit in the Matrix server, but I haven't talked about it too much on here.  The developer of Invidious has been working on an API that is similar to NewPipe's and is coming along nicely.  My plan is to use his API for FreeTube which will remove the need for YouTube's official API.  I already have his permission to use his server for the API calls but depending on the load I may run my own server to prevent extra server costs for him.

As for NewPipe's API, it looks like progress been put on hold for a little bit as they would rather focus on other things.  I 100% respect and understand this decision.  FreeTube will need to progress without it for now and I believe Invidious is the right direction for this.  If anything changes in the future I'll make an update here but this is what I'd like to do for now.

On a side note (and to get some discussion going), how has v0.3.2 been for everyone?  There were a lot of changes in the back end that should have gone unnoticed and if it feels like nothing much has changed then I would consider it a success.  It won't change much for now but future features will be much easier to implement because of it.

**Comment by LexHimself** [comment]
Regarding the new versions, they are lightning fast. 
I still encounter issues playing 720p video's, sometimes they just do not start playing at all. Selecting 480p will solve this issue. I did not do extensive testing, my system still runs on 3.0. The issue described occured in the past, was fixed, and was found again in the most recent build.

**Comment by TobiGr** [comment]
> As for NewPipe's API, it looks like progress been put on hold for a little bit as they would rather focus on other things.

I guess a proper API for NewPipe will come when NewPipe Extractor is stable and most YouTube features are implemented. As for now, I'd suggest you to take a look at https://github.com/joeferner/node-java. I am not 100% sure that it is compatible with this project, but it might worth a try ;) I didn't test it out, but I hope this can work. I expect it to be a bit slower than the current implementation, but it would minimize the need of YouTube API keys.

**Comment by PrestonN** [comment]
@TobiGr that is understandable.  I understand that there's a lot to work on with the NewPipe Extractor and that it will take some time.  I'm sure you guys have a large list of tasks to work on that may or may not involve working on the extractor as well.  I personally don't have a problem with being patient on some sort of API, but using YouTube's API has proven to not be very scalable for this type of project and I will need to find a solution soon as the project gets more popular.

The link you provided seems helpful, I appreciate it. :)

I'm still weighing my options on how to move forward.  It's at a point where I can't really keep throwing more keys at it.
