### ISSUE TITLE
Show 3-dots menu on mouse hover

### ISSUE THREAD

**Issue by Donkey-Doug** [FreeTubeApp/FreeTube#1000]
Currently the 3-dots icon is shown for every entry:

![image](https://user-images.githubusercontent.com/50382414/106369071-bb8b4e80-634e-11eb-8f22-3a026b20a90b.png)

I think it is cleaner to only reveal the 3-dots icon when the mouse hovers over an entry. However, I am uncertain how users with a touchscreen feel about such a change. I do not think a long press is currently implemented in freetube.

**Comment by Murciegalo** [comment]
Taking this one on

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Implemented in https://github.com/FreeTubeApp/FreeTube/pull/3954
