### ISSUE TITLE
Error in comments viewing

### ISSUE THREAD

**Issue by LYHyoung** [FreeTubeApp/FreeTube#1001]
When I click the 'Click to View Comments' button,

- "Error: Request failed with status code 404"

and

- "Failing back to Invidious API"

sign is being shown.

**Comment by stemy2** [comment]
Me too, and it happens with any instance set in the settings.

**Comment by LYHyoung** [comment]
Something must be wrong in recent update :(

**Comment by ZeikoFr** [comment]
Can confirm this issue is present in the last mainstream update.

After failing the app switch to invidious API and this API also fail (I know it's specific to invidious in this case)

**Comment by saideepesh000** [comment]
Guys, take a look at this, [Error loading subscribtion videos and comments](https://github.com/FreeTubeApp/FreeTube/issues/1021#issuecomment-774729075)

**Comment by randyrandersn** [comment]
Can confirm this issue too.  Basically nothing works for me.  Cannot view subscriptions, playlists, channels, videos.

Many of these errors : TypeError: Cannot read property 'title' of undefined

Looks like local API has been broken and fallback to invidious is failing.

I have tried all invidious instances in supplied link and none are working for me, from dozens of  different IP addresses across multiple VPN providers.

The closed issue #1021 is not the solution to this problem, fixing the underlying local API issue is.

**Comment by PrestonN** [comment]
Yes as was mentioned the issues here is related to the local API as both comments and now channel information has stopped working. I'm almost done with the channels issue and I'm hoping to look into the comments issue soon.

The channels problem should be it's own issue however and this issue needs to be about the comments problem only.

**Comment by LYHyoung** [comment]
OK. Thanks for the reply. :)
Let me know when the issues are resolved well.

**Comment by LYHyoung** [comment]
> Yes as was mentioned the issues here is related to the local API as both comments and now channel information has stopped working. I'm almost done with the channels issue and I'm hoping to look into the comments issue soon.
> 
> The channels problem should be it's own issue however and this issue needs to be about the comments problem only.
OK. Thanks for the reply. :)
Let me know when the issues are resolved well.

**Comment by LYHyoung** [comment]
> Yes as was mentioned the issues here is related to the local API as both comments and now channel information has stopped working. I'm almost done with the channels issue and I'm hoping to look into the comments issue soon.
> 
> The channels problem should be it's own issue however and this issue needs to be about the comments problem only.

OK. Thanks for the reply. :)
Let me know when the issues are resolved well.
