### ISSUE TITLE
Video loads indefinitely

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#1007]
**Behavior of the program**
When i try to play a video, the load icon is spinning but it loads indefinitly without transmitting any byte of video from youtube or invidious and the total video duration shows "0:00".

**Expected behavior**
The video is playing.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any video
2. Click on play

**Screenshots**
![Screenshot_20210202_105532](https://user-images.githubusercontent.com/22192600/106583664-3e71fc00-653d-11eb-87d8-e9acc73d1ff1.png)

**Environment Information (please complete the following information):**
 - OS: Debian 10
 - FreeTube version: v0.11.2 Bêta
 - Installation Method (If applicable): deb
 - Primary API Used: Invidious API if local API is failing

**Comment by GilgusMaximus** [comment]
Hi, does this still occur in the newest version? I had some problems before, but they were fixed with the 0.11.3

**Comment by PrestonN** [comment]
To add to this, does the issue also occur on the Invidious instance you're using? If that's the case, then there won't be anything we can do about it.

**Comment by Svallinn** [comment]
I haven't had such a problem in the latest versions
Since no extra information has been provided, I'll be considering this issue as stale and closing it.
