### ISSUE TITLE
Application Icon is too large on GNOME desktop

### ISSUE THREAD

**Issue by roymclellan** [FreeTubeApp/FreeTube#1008]
OS Name: Pop!_OS 20.10
OS Type: 64-bit
GNOME Version: 3.38.1

![Applications](https://user-images.githubusercontent.com/9967475/106614656-357b2d80-6531-11eb-8b4b-91df4e4ae3ac.jpg)
![Dock](https://user-images.githubusercontent.com/9967475/106614657-3613c400-6531-11eb-8743-75c733935e13.jpg)

**Comment by ChunkyProgrammer** [comment]
This issue should be fixed
