### ISSUE TITLE
Show UI elements as soon as they are loaded

### ISSUE THREAD

**Issue by fsondej** [FreeTubeApp/FreeTube#1014]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Now, when you click a video, you have to wait until everything is loaded, and then everything shows at once.

**Describe the solution you'd like to see implemented**
It would be smoother to do it just like youtube does:
first show blank UI, then start playing the video as soon as it's beginning is loaded, then show the thumbnails when they are loaded. 

**Describe alternatives you've considered**

**Screenshots**

**Additional context**
I know it's not a high priority, but in the future it would be nice to have.
It would make user experience much smoother and cause less impatience.

**Comment by saideepesh000** [comment]
Nice thing, this is what we call [Skeleton Loading](https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a).

**Comment by PrestonN** [comment]
This wouldn't be possible to do. All data is returned at the same time and not in separate pieces like what YouTube itself may do. There isn't a point in time where we only have partial data. We only have the data we need or none at all.

Because of this, this cannot be implemented.
