### ISSUE TITLE
Green shattered videos.

### ISSUE THREAD

**Issue by valetdepik** [FreeTubeApp/FreeTube#1015]
Hello, I'm using Freetube v0.11.2 Beta and after watching 1 or 2 videos, I encounter green videos instead of normal ones.
I think the problem occured since v0.9.0 or v0.9.1, something around these.
I did re-install an older version to be able to use it but I decided to update again and I still have this problem.
I don't seem to have the problem on my SolusOS.

**To Reproduce**
I open Freetube and click on any videos.

**Screenshots**
https://u.teknik.io/6x702.png

**Environment Information:**
 - OS: windows 10
 - FreeTube version: 0.11.2 Beta
 - Installation Method:  .exe
 - Primary API Used:  tried both Local API & Invidious API

**Additional context**
I can hit ctrl + R as many times as I want, it doesn't change a thing. I tried changing default format as well.

**Comment by Svallinn** [comment]
@valetdepik
Are you still experiencing this problem in the latest nightly version?

**Comment by Svallinn** [comment]
Closing, since there's been no response for a week.

**Comment by valetdepik** [comment]
Yes, sorry, I did not see the notification.
