### ISSUE TITLE
SponserBlock Support!

### ISSUE THREAD

**Issue by codewizkid** [FreeTubeApp/FreeTube#1017]
Hello again,

It would be great if you could find a way to implement an extension called, "SponserBlock for YouTube - Skip Sponsorships". This lets you not only block sponsor spots in the videos, but also into's and outro's, interaction reminders (like, subscribe etc.), also any unpaid or self promotion parts of the video that people don't want to see, like promoting a book or new merchandise. 

Link to the project: https://github.com/ajayyy/SponsorBlock

**Comment by PrestonN** [comment]
Duplicate issue. Please search for issues before creating a new one.

**Comment by codewizkid** [comment]
Sorry about that...
