### ISSUE TITLE
Playing existent google playlists

### ISSUE THREAD

**Issue by je-vv** [FreeTubeApp/FreeTube#1019]
I've seen other people requesting ability to import playlists, but I'm instead looking for the ability to play playlists from others on youtube.  Whenever I open a youtube playlist, there's no play button, and I have to go one by one over the items in the list...

**Comment by PrestonN** [comment]
I'm a little uncertain on what's being requested here. You can already play an existing playlist on YouTube. When you click on a Playlist, it will show you the videos within that list, if you play one of those videos, then you'll see the playlist along side the video you're watching and FreeTube will automatically go to the next video in that playlist. Optionally you can enable shuffling or you can even reverse a playlist.

If this is the functionality that you are requesting, then this issue should be closed. If you are requesting a different issue, then please clarify what it is that you are requesting.

**Comment by je-vv** [comment]
I'm missing a button to just play the list, which automatically goes one by one until the list finishes, but does not shuffle over again.  That's not available AFAIK.  Again, it's a single button to go over all items of the list, without having to reshuffle, neither to go an item one by one.  Such button exists on youtube, even by having the reshuffling unselected, if you play a list, it goes over all items automatically, you can pause, and later continue, and don't have to click on any item...  Reshuffling means going through the whole list all over again without limit, and that's not the purpose...

**Comment by PrestonN** [comment]
If you want to play through a playlist, you just need to select a video while viewing a playlist. There is no specific button to play all videos. Simply click on the first video and a playlist menu will show up with the video.

**Comment by je-vv** [comment]
That has never worked for me, perhaps it's a bug, not sure...  When finishing the 1st video of the playlist (or I'd supposed whatever video I select) freetube get in blank and freezes...  I have to kill it...

But just in case, this is what I was talking about:
![image](https://user-images.githubusercontent.com/10799432/107160257-d2d3c880-695a-11eb-938d-a4d1d84f6184.png)

See the "play all" button...

**Comment by PrestonN** [comment]
I'm well aware of what you're talking about. The button does not exist in FreeTube however the functionality is and the workflow is slightly different. Since this was the initial request and it exists, I will be closing this issue.

We can still talk about the other issue for a moment however. Is it with every playlist you try to play? Do you have a video example of the app crashing? If it's a certain playlist, linking the playlist here would be helpful.

Thanks.

**Comment by je-vv** [comment]
OK, I still think such button would be nice, because the current behavior is not that intuitive...

At any rate, yes, I was looking for the playlist I tried yesterday, which is way newer, but couldn't find it...  At any rate on this playlist:  PL0VS-9Oj4_bJg9dbXEwOPmXzY-vglnhpA, you can play the 2nd video fine.  But if you play the 1st, usally after playing the 1st it goes blank...  1st time it was so fast I didn't notice it was trying the 2nd one, but on trying again I just noticed it was trying to start the 2nd when it got in blank and got frozen...
