### ISSUE TITLE
Play all videos from subscriptions

### ISSUE THREAD

**Issue by Topping1** [FreeTubeApp/FreeTube#1022]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
It would be great to have the ability to play all the videos from your subscriptions one after the other. Currently you have to click each video individually.

**Describe the solution you'd like to see implemented**
A button named "play all". Optional: have an option to sort the videos by date, reverse date and maybe "random play all".

**Comment by PrestonN** [comment]
Duplicate of #629
