### ISSUE TITLE
Improper alignment

### ISSUE THREAD

**Issue by Mennaruuk** [FreeTubeApp/FreeTube#1023]
**Behavior of the program**
When expanding menu pane, listed items aren't properly aligned.

**Expected behavior**
Items should be properly aligned for a better look.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to FreeTube
2. Click on the hamburger icon
3. Check if items are aligned properly

**Screenshots**
(I drew yellow line for clarity.)
![alignment](https://user-images.githubusercontent.com/52135169/107599759-9ec50580-6bef-11eb-9c49-23a7efd1944b.png)

**Environment Information (please complete the following information):**
 - **OS:** Linux Mint (although this can be reproduced on every other distro, and other OS'es including Windows)
 - **OS Version:** 20.1 Ulyssa
 - **FreeTube version:** v0.11.2 Beta
 - **Installation Method (If applicable):** AppImage
 - **Primary API Used:** Local API

**Additional context**
I ❤️️ FreeTube

**Comment by saideepesh000** [comment]
Hey @Mennaruuk, I think it's expected because the icon(Most Popular) is itself larger than others, so it's pushing the text further
