### ISSUE TITLE
F5 keypress refresh

### ISSUE THREAD

**Issue by ckorder** [FreeTubeApp/FreeTube#1025]
Please implement F5 key press for refreshing:

the channel page your currently on
the video your currently watching and the connection broke (wifi / hotspot / vpn / proxy / what ever)
the subscription list

thanks.

**Comment by PrestonN** [comment]
It's a simple addition, however `Ctrl + R` already does the same thing. We could add a button that also refreshes the page as well which I imagine would be helpful.

**Comment by saideepesh000** [comment]
Duplicate #1005

**Comment by gaylie** [comment]
> It's a simple addition, however `Ctrl + R` already does the same thing. We could add a button that also refreshes the page as well which I imagine would be helpful.

Does `CTRL + R` still work? I keep trying, but nothing seems to reload for me.

EDIT: Ah, it only works on the Subscription, Trending, and Most Popular Pages, but not on videos.... odd.
