### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by sbstn87** [FreeTubeApp/FreeTube#103]
Hi,

maybe instead of making an AppImage, flatpak version would be better to distribute the app? Or a flatpak as an addition to the AppImage?

**Comment by PrestonN** [comment]
Between the 2, I had many more requests for AppImage than I did with Flatpak.  That reasoning alone made it more worthwhile to look into AppImage first.  Having said that, I have been messing around with the possibility of Flatpak (as well as Snap) for the future so keep an eye out for those.

**Comment by travankor** [comment]
fwiw, I haven't been able to get appimages to work on musl libc, while flatpak works fine since it bundles the application's libc.

(of course, the only reason I am interested in appimage/flatpak is to make electron apps work on musl libc :) )

**Comment by mat8913** [comment]
Hello, I'm currently in the process of making a flatpak. You can see what I've got so far at https://github.com/mat8913/flathub/tree/io.freetubeapp.FreeTube. I haven't added a .desktop file yet, but for now it can be run with `flatpak run io.freetubeapp.FreeTube`. 

When completed, I intend on publishing this to flathub. @PrestonN, would I have your permission to do so?

**Comment by mat8913** [comment]
Hello again, I've gotten the flatpak ready to submit to flathub. Please take a look at it here flathub/flathub#920.

**Comment by mat8913** [comment]
It's now on flathub, here's a link: https://flathub.org/apps/details/io.freetubeapp.FreeTube

**Comment by PrestonN** [comment]
Great!  Thank you for your help on that.  I'll be sure to include it on the website.  Closing this issue since this has been finished.
