### ISSUE TITLE
Removal of the black error messages or this needs some coding effort

### ISSUE THREAD

**Issue by Hx2-code** [FreeTubeApp/FreeTube#1030]
Can the black toast messages viewed when errors are encountered be disabled?

**Comment by saideepesh000** [comment]
Hey @Hx2-code , Could you show us the screenshot, btw error messages are meant to be shown to users otherwise u never go to know what's happened.

**Comment by GizDrak** [comment]
@saideepesh000 I bet he is getting the lame once I have been getting for a little over a week now that say. "TypeError: Cannot read property 'title' of undefined"

Here is a screenshot
[https://snipboard.io/9XhzpK.jpg](url)

**Comment by PrestonN** [comment]
This is a duplicate of #1021. You can enable RSS to remove the error messages for now until a fix is released.

**Comment by Hx2-code** [comment]
Thank you. You answered my issue before I observed the notifications.
