### ISSUE TITLE
No compatible source was found for this media. 

### ISSUE THREAD

**Issue by ByteEnable** [FreeTubeApp/FreeTube#1035]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
- [ ] Other. Please specify:
Playback

**Question**
Some video's fail to play due to a "No compatible source was found for this media." message.  Is this known?

https://ytprivate.com/watch?v=RBn1CDABM8U
https://youtu.be/RBn1CDABM8U

i found a similar issue on github here:
https://github.com/videojs/videojs-contrib-dash/issues/287

**Comment by GilgusMaximus** [comment]
Could you please provide new videos? The one you provided is set to private. No one can view it, even on YouTube, except for the owener

**Comment by ByteEnable** [comment]
Here is another one.  Plays in FF but not in Freetube.
https://youtu.be/vao_J5Cx-yE

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi @ByteEnable are u still experiencing this issue?
