### ISSUE TITLE
TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by Araborum** [FreeTubeApp/FreeTube#1036]
Hi all,

I am on v0.11.2 Beta and after updating to it, everything worked great. But now, when updating the subscription list, I get a handful of floating pop-ups: 'TypeError: Cannot read property 'title' of undefined'.

In addition, even when you click on a channel, the list of videos is empty, and the message states 'This channel does not currently have any videos'. Of course, that is not true and there are a ton of videos but nothing comes up.

Hope this helps, but do tell if I can help more somehow.

**Comment by PrestonN** [comment]
Update to v0.11.3
