### ISSUE TITLE
Video search on channel page always returning 0 results

### ISSUE THREAD

**Issue by orthand** [FreeTubeApp/FreeTube#1042]
**Behavior of the program**
Trying to search a channel always returns: "Your search results have returned 0 results"
Accompanied by this error message: "TypeError: Cannot read property 'contents' of undefined"

**Expected behavior**
Show channel videos that match the entered keywords.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any channel
2. Click on 'Search Channel' and enter keyword(s)
3. See error and "Your search results have returned 0 results" after confirming

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 Education, 20H2
 - FreeTube version: v0.11.3 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Additional context**
Not sure if this is just a beta bug from the API as there're older closed issues where this seemed to work. Though I'm not getting any results as well after falling back to the [Invidious API](https://github.com/iv-org/invidious/issues/1706#issuecomment-767291597).

**Comment by martinaware** [comment]
Same problem here. I can't even add a channel.

**Comment by peepopoggers** [comment]
i think it is to do with the invidious instance, they are releasing invidious.io domain soon i think

**Comment by orthand** [comment]
I've had some search requests that worked in the last few days though mostly still getting the above mentioned error so I'll still leave it open for now.

**Comment by PrestonN** [comment]
This has been fixed in dev /nightly builds. We had to update our extraction method due to changing API endpoints on YouTube's end. This will be included in the next release.
