### ISSUE TITLE
Keeping the "Subscriptions"/"Most Popular" reload button fixed while scrolling

### ISSUE THREAD

**Issue by orthand** [FreeTubeApp/FreeTube#1043]
**Describe the solution you'd like to see implemented**
Additionally to #1010 keeping the "Subscriptions"/"Most Popular" reload button fixed/static in the right corner while scrolling.

**Describe alternatives you've considered**
Adding a "scroll to top" arrow/button in the lower right corner could be an alternative (or an additional function in general). On touch devices with detachable keyboards this would help with excessive scrolling.

**Additional context**
I really like the timestamp idea from #1010 for the "Subscriptions" section. Though this would make the static field too large to keep it next to the reload button while scrolling and therefore interfere with the shown videos. I wouldn't want another bar on top that takes up more space so I thought of either
- trying to add the timestamp beneath the button
- only showing it when hovering over the reload button
- in addition to the second point: also show when (stationary) in the top position while there is still space above the videos.

**Comment by saideepesh000** [comment]
@PrestonN @GilgusMaximus can I work on it.

**Comment by GilgusMaximus** [comment]
Hi, 
so thanks for your ambition to help on this feature ! 
I'll go ahead and assign you to this issue.

One thing to keep in mind here is that we need some testing for different window sizes. Especially for very thin windows like below, either adjusting the size/placement of the reload button, or disabling the fixed position for scrolling might be a solution to avoid overlapping. If you need any input feel free to ask and open a PR where this can be discussed.

![image](https://user-images.githubusercontent.com/34301369/109392007-0bdbd900-791a-11eb-9607-446e83c79c11.png)


Best Regards,
Gilgus

**Comment by jasonhenriquez** [comment]
Communicated with @saideepesh000 over email and mutually agreed to transfer assignment on this issue.
