### ISSUE TITLE
Does youtube count a subscription thru freetube like a legit one ?

### ISSUE THREAD

**Issue by Janaue** [FreeTubeApp/FreeTube#1044]
Does youtube count a subscription thru freetube like a legit one . Ideally, I want to subscribe to channels thru freetube but dont want those to be counted by youtube. I dont have a youtube account.

Same question with video views: if I watch a video in freetube, does youtube count it as a real view ?

**Comment by fabianski7** [comment]
I think the answer is the same for both questions: no.

**Comment by GilgusMaximus** [comment]
Hi, as @fabianski7 mentioned, subscriptions are not tracked. This is purely local.
In regards to the views, one would have to test how YouTube counts views, but I would assume they are doing it through API accesses.

Therefore this was answered, and I am closing this now.
Best Regards,
Gilgus
