### ISSUE TITLE
Automatically switch between light and dark themes to match system

### ISSUE THREAD

**Issue by shbach** [FreeTubeApp/FreeTube#1046]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Right now the dark and light themes of FreeTube must be manually set.

**Describe the solution you'd like to see implemented**
Ideally there would be an option to match the system theme. e.g. if the system is using a dark theme, FreeTube will also use the dark theme. I have my system set to switch to a dark theme at night so automating this in FreeTube would be nice so it isn't the only app that is blinding white.

**Describe alternatives you've considered**
No alternatives. There are plenty of apps that have the option to match the system theme so this isn't an unheard of feature.

**Comment by GilgusMaximus** [comment]
Hi, so at the moment this is not really that nice to implement, due to the many different operating systems supported.
However if someone wants to find a general solution for it, we are open for PR's :)

**Comment by GilgusMaximus** [comment]
Going through all the issue I just realized this is a duplicate of #691 
Therefore closing this
