### ISSUE TITLE
Add option to open in "Fullwindow" by default

### ISSUE THREAD

**Issue by shbach** [FreeTubeApp/FreeTube#1047]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I'm currently using the "Privacy Redirect" browser extension to have YT videos links I click open in FreeTube. I prefer using the "Fullwindow" view as I think it is the cleanest and distraction free option. 

**Describe the solution you'd like to see implemented**
Right now whenever FreeTube opens I have to then manually click the "Fullwindow" button. Ideally FreeTube would have an option to open in "Fullwindow" view by default.

**Describe alternatives you've considered**
There is an "Enable Theatre Mode by Default" but I don't think it's the same thing and when I activate that option I don't think I notice a difference?

**Comment by saideepesh000** [comment]
Hey @shbach, there's already a PR for this and @PrestonN has to review it, it will get merged soon

**Comment by shbach** [comment]
@saideepesh000 That's close but what that PR does is open the video in fullscreen while I would prefer the option of "fullwindow"/["windowed fullscreen"](https://github.com/FreeTubeApp/FreeTube/pull/829) which is slightly different.

**Comment by toprak** [comment]
hey, when will we get it?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/5427
