### ISSUE TITLE
[Feature Request] MPRIS tag integration

### ISSUE THREAD

**Issue by AtlasC0R3** [FreeTubeApp/FreeTube#1051]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Somewhat. It's not that I don't like the current integration, it's just that I find it odd how it's only the title tag being used, with "Video Title - Freetube" instead of Firefox's full tag usage (title only being the video title, artist being the channel name, artwork being the thumbnail, etc).

**Describe the solution you'd like to see implemented**
Well, simply just some better MPRIS integration: the title should only be the video title, the author should be the channel name, the artwork should be a high quality version of the thumbnail, and maybe make it toggleable (for the users who don't want that).
And maybe the album name being the playlist name, if there is one.

**Describe alternatives you've considered**
well i would've tried implementing my own but i don't know how to javascript and stuff

**Screenshots**
![Firefox and FreeTube (aka Chromium apparently)'s MPRIS integrations](https://user-images.githubusercontent.com/39468657/108645512-01998500-74ab-11eb-9d64-f096930ed77c.png)
[A mobile screenshot of KDE Connect's MPRIS notification for Android, put as a link due to the screenshot taking up way more space than it should](https://user-images.githubusercontent.com/39468657/108645586-3d344f00-74ab-11eb-98db-6ff4f7147cc8.png)

**Additional context**
I don't have much else to say, really.

**Comment by PrestonN** [comment]
I never added more data to this mostly because for the life of me I couldn't figure out what I needed to change to make this happen. I finally found what was needed and made a change to include this. Please try out a nightly build when you get the chance and see is this works for you. I can't test and see if the thumbnail is working because GNOME has some issue with it apparently, though it should still show up for you.

If everything looks good, we can close this issue.

**Comment by AtlasC0R3** [comment]
It unfortunately did not work for me *(as in, nothing changed)*, maybe it's just my DE not liking it? I'm using Budgie, if that can help.
I tried installing the \*.deb package and running the \".AppImage executable, nothing changed.

**Comment by PrestonN** [comment]
Apologies for that. Could you please try another nightly build? It seemed to have been erroring out and I made a correction which seems to have fixed it. Let me know if this works out for you.

**Comment by AtlasC0R3** [comment]
I can confirm that it now works on my Windows installation.

![image](https://user-images.githubusercontent.com/39468657/109401330-0b444200-791c-11eb-8cce-4d5190899058.png)


(For reference, this is how it looked like)

![image](https://user-images.githubusercontent.com/39468657/109401354-3333a580-791c-11eb-883a-8f4d1a6f69ab.png)

I won't be able to test if it works on my Linux install *for now*, but I have a positive feeling that it'll work perfectly no matter what OS it's running on.

**Comment by PrestonN** [comment]
Agreed. It also works on GNOME so I think it's safe to close this issue. Thanks for helping with testing! :)

**Comment by AtlasC0R3** [comment]
Can confirm, it works nicely with Budgie (and KDE Connect)!
![image](https://user-images.githubusercontent.com/39468657/109440518-79772a80-7a2a-11eb-8929-51a085bd623d.png)
