### ISSUE TITLE
Ability to create bookmarks under different categories

### ISSUE THREAD

**Issue by Aikatsui** [FreeTubeApp/FreeTube#1052]
**Describe the solution you'd like to see implemented**
There's a playlist tab currently and we can add videos to playlist by tap on the star mark display on top right side on thumbnail.
You can enhance it or add separate bookmark tab to save videos under categories. eg: games, music.

That was mention on comment https://github.com/FreeTubeApp/FreeTube/issues/333#issuecomment-629852169 but the issue for different feature request

**Additional context**
See vivaldi browser for that.

**Comment by PrestonN** [comment]
We'll be revamping the tab to eventually allow this. This is already tracked elsewhere so I will go ahead and close this.
