### ISSUE TITLE
Some videoes have less quality options on Dash, then in browser or legacy mode. 

### ISSUE THREAD

**Issue by Sjano** [FreeTubeApp/FreeTube#1055]
**Behavior of the program**
Some videoes have less quality options on Dash, then in browser or legacy mode. 

**Expected behavior**
Web browser (firefox) has everything up to 1080p60
Legacy format has 360 and 720.
Dash format only have 360.

**Example video**
https://youtu.be/BgW3LYWkjuc

**Environment Information (please complete the following information):**
 Windows 10,
 - FreeTube version: 0,11,3 beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment]
Hi, so this unfortunately is a problem of the plugins we use. For long videos, as well as high resolution videos, YouTube usually only provides some qualities as mp4, but most as webm. And this exact format is yet to be supported over at the vhs plugin for VideoJS. 

I'm sorry that at the moment there is not much we can do here.
