### ISSUE TITLE
Videos from different platforms

### ISSUE THREAD

**Issue by grubeli** [FreeTubeApp/FreeTube#1059]
How hard is to implement other video platforms?

If I could subscribe and watch videos from different platforms would be amazing, for example from Vimeo, Twitch, Minds, lbry, bitchute, etc.
Many creators off-yt now, so it makes sense to support other platforms.
Also, there are several alternative video portals, having all videos in one place would make everything better

**Comment by PrestonN** [comment]
This is not going to happen as we'd like to focus on YouTube only. Adding more platforms adds a ton of complexity that we don't want to handle at this time.
