### ISSUE TITLE
Scroll bar very hard to see in dark theme

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#106]
When FreeTube (0.3.0 beta) is set to the dark theme the scoll bar becomes very hard to see as the difference in color between it and the area it can move in is very very slight.

It would be nice if we could have better contrast between the two

**Comment by LexHimself** [comment]
Never notices this, but i added an example from my gtk theme, perhaps the scrollbar background could be a bit lighter indeed. 

![2018-06-11-193503_1153x854_scrot](https://user-images.githubusercontent.com/40179434/41247732-3b386f84-6daf-11e8-97b0-c8b3f370bba5.png)

**Comment by PrestonN** [comment]
Hey there,

I can understand that being too difficult to see.  I've gone ahead and make it lighter.  Expect the change in the next release (hopefully soon).

Here's a preview in the mean time.

![screenshot from 2018-06-13 10-13-21](https://user-images.githubusercontent.com/9736046/41356782-94c32dd4-6ef2-11e8-8095-d9ff846d3ada.png)
