### ISSUE TITLE
Live chat not showing 

### ISSUE THREAD

**Issue by jilv220** [FreeTubeApp/FreeTube#1060]
**Behavior of the program**
The live chat is not loading during the live stream, only showing "livechat is enabled", but no chat loaded. 

**Expected behavior**
Load the live chat

**To Reproduce**
Find a live stream and watch the live stream.  

**Screenshots**
![image](https://user-images.githubusercontent.com/20714458/109028924-50544400-7690-11eb-9c61-765c0de0ec8c.png)

**Environment Information (please complete the following information):**
 - Manjaro KDE plasma 
 - 5.10.15-120-tkg-MuQSS (unlikely this issue is caused by kernel imo)
 - 0.11.3-1 (bin)  0.11.3-2 (build)
 - AUR
 - Local API

**Comment by jilv220** [comment]
Tried Flatpak version, still not working for me.

**Comment by PrestonN** [comment]
This is a known issue. We're waiting for an upstream fix before we can put the patch into FreeTube. If it takes too long then I may look into making the patch myself.

**Comment by jilv220** [comment]
Thank you for the reply !

**Comment by MPeti1** [comment]
@PrestonN can I ask who is being referred to as upstream here?
