### ISSUE TITLE
Privacy Redirect Extension only redirects youtube links to home page, not specifically linked video

### ISSUE THREAD

**Issue by ykhurshid** [FreeTubeApp/FreeTube#1061]
Whenever I try clicking a link to a video on my browser, instead of opening up that video in Freetube, It just shows me Freetube's home page view instead. When I disable the freetube integration, it redirects to the appropriate invidious link just fine. 

This means that it's probably not the extension itself that's bugged. I've tried switching from local API to invidious API and it had no effect.

I use arch btw and run Brave as my browser.

I'm running Freetube 0.11.3-2.

**Comment by tcrasset** [comment]
Hello!

This happens to me too on Google Chrome, however Firefox works fine.
Freetube  `v0.13.1 Beta`

I disabled all other extensions. 
I'm using Google Chrome 90 : https://whatismybrowser.com/w/3BXMMRF
I'm running Ubuntu 20.04.1, output of `uname -a`
```
Linux 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64
```

The Google Chrome console does have the correct link that I throw at it.
![Screenshot_20210601_094646](https://user-images.githubusercontent.com/25140344/120286218-4c067b00-c2be-11eb-8d5e-42ad5ca1ac05.png)

Do you have any logs that I could paste here to make it easier for you to debug ?

Don't hesitate to ask for any other info you might need.

**Comment by BobIsMyManager** [comment]
On the contrary of the comment above, it does not seem to work on firefox.
I am using Freetube `v0.15.1 Beta`, installed via `.rpm` package.

It doesnt work even on a fresh profile on firefox `95.0.1` on openSUSE Tumbleweed

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi is this still an issue. If so maybe reading the https://docs.freetubeapp.io/usage/browser-extension/ can help u out?

**Comment by BobIsMyManager** [comment]
> Hi is this still an issue. If so maybe reading the https://docs.freetubeapp.io/usage/browser-extension/ can help u out?

For me at least it seems to work as intended
