### ISSUE TITLE
Website certificate has expired. 

### ISSUE THREAD

**Issue by DDGo** [FreeTubeApp/FreeTube#1068]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
- [x] Other. Please specify: Website certificate.

**Question**
The certifcate used by the website on https://freetubeapp.io/ has expired yesterday and has not been renewed. This will mean anyone trying to visit the site will need to atleat temporarily exempt the site to be able to visit it. Can it be renewed?

**Comment by PrestonN** [comment]
Sorry about this! I renewed them a while back but something didn't update properly on the web server. This has been fixed.
