### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by tescker** [FreeTubeApp/FreeTube#1069]
Behavior of the program
Video status bar doesn't roll back after you change quality of the video.

Expected behavior
It should roll down after you change it.

To Reproduce
All steps to reproduce the behavior:
1. Go to 'Any video'
2. Click on 'Quality changing'
3. Change it at least more than 2 times

Environment Information:
 - OS: [Windows]
 - OS Version: [Windows 7]
 - FreeTube version: [0.11.3]
 - Installation Method: [.exe]
 - Primary API Used: [Local API]

**Comment by GilgusMaximus** [comment]
Hi,
so thanks for figuring out when this bug actually occurs. Beforehand we were tapping a bit in the darkness.
I'd close this issue in favor of the original issue #695 but ask you to add your findings over there if you want to. Otherwise I can also add them there :)

Best Regards,
Gilgus
