### ISSUE TITLE
User defined external player via share menu

### ISSUE THREAD

**Issue by Woodhousemelena** [FreeTubeApp/FreeTube#1079]
Wow, what a great piece of software. 

I wonder if it could be possible to implement a function where the user can specify an external player to which the URL can be parsed via the share button or a dedicated one. I have a handy application (IDOK) that allows to play a URL on my kodi setup connected to the TV. In fact I made a wrapper that contains the specifices of my kodi player and accepts a file or a url as input  It would be great if one could simply send the video to the TV  by pressing a button. 

Compare this to newpipe, that also supports this functionality specifically for KORE that basically does the same.

This could also be used to allow playback with any other video player accepting URL as input.  (VLC?)

**Comment by fabianski7** [comment]
https://github.com/FreeTubeApp/FreeTube/issues/418

**Comment by Woodhousemelena** [comment]
Sorry searched the wrong way and did not find previous requests
