### ISSUE TITLE
give a default file name and extension when exporting subscriptions

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#108]
Under Debian 9 when you export the subscriptions from settings you are prompted with file save dialog with the name field empty.     As the name field 

Suggestion:   create a filename with the correct file extension for the user.  

Ideally something like     `FreeTube-subscription-YYYYmmddhhmm.db`

**Comment by LexHimself** [comment]
The extension (.db) is automatically added, atleast under Arch Linux. 
I think it would be possible, but should be on low priority. 

While at it, might make auto backups weekly or monthly, or some feature like that?

**Comment by PrestonN** [comment]
This is actually very simple to do.  We're talking 2-3 lines of code easy.  I don't see why I couldn't include this in the next patch release.
