### ISSUE TITLE
Family Friendly Filter

### ISSUE THREAD

**Issue by sudolynx** [FreeTubeApp/FreeTube#1080]
FreeTube would be perfect if it had a family friendly filter.

This would make it much safer than default YouTube. A family friendly filter would block inappropriate, "adult" content.

Is this possible? Maybe a solution could be using an AI to analyze videos to see if they contain objectionable content.

**Comment by PrestonN** [comment]
YouTube doesn't provide any information in their results that we'd be able to use to determine if content is "family friendly" or not. Trying to figure this out using any other method would be way too many requests to YouTube and would get the user IP blocked pretty quickly.

Unfortunately this is not possible.
