### ISSUE TITLE
Unable to view comments sorted by newest first and for age-restricted videos

### ISSUE THREAD

**Issue by TimTree** [FreeTubeApp/FreeTube#1081]
**Behavior of the program**
On the current version of FreeTube (0.11.3), I am unable to view comments via local API:

* Sorted by newest first for some videos - `Error: Request failed with status code 500`
* At all for age-restricted videos - `TypeError: Cannot read property 'continuationContents' of undefined`

**Expected behavior**
Comments for the given videos should load without producing the above errors.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. These sample videos will not load comments sorted by newest first: [video 1](https://www.youtube.com/watch?v=kAJAViPWR_8), [video 2](https://www.youtube.com/watch?v=_PUEb8ppPbg), [video 3](https://www.youtube.com/watch?v=UbDDrT_lmmg)
2. Attempt to load comments from any video age-restricted by YouTube.

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.

**Environment Information (please complete the following information):**
 - OS: Windows, macOS, and Linux
 - FreeTube version: 0.11.3
 - Installation Method (If applicable): .exe, .dmg, .AppImage, AUR
 - Primary API Used: Local API

**Additional context**
I have submitted a [pull request](https://github.com/GilgusMaximus/yt-comment-scraper/pull/13) to yt-comment-scraper that may resolve this bug. The pull request note contains additional details behind the problem.

**Comment by PrestonN** [comment]
Comment module has been updated. Thanks again for the PR!
