### ISSUE TITLE
Video viewer count in most popular menu is incorrect most of the times

### ISSUE THREAD

**Issue by MPeti1** [FreeTubeApp/FreeTube#1085]
**Behavior of the program**
If you open the `Most Popular` menu on the left, about half or more of the videos will have incorrect viewer counts. You can see this by the count being less than 10 for videos of popular channels that have been released for some time.

**Expected behavior**
Viewer count is diplay correctly.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open Freetube
2. Click on `Most Popular` on the left sidebar
3. See problem

**Screenshots**
![image](https://user-images.githubusercontent.com/9215491/109776860-56ec3980-7c03-11eb-9cb0-3390bf884f5f.png)

**Environment Information (please complete the following information):**
 - OS: Windows 10
 - OS Version: 1903
 - FreeTube version: v0.11.3 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API (with fallback to Invidious enabled)

**Comment by GilgusMaximus** [comment]
Closing because this is related to invidious. Nothing we can do here

**Comment by MPeti1** [comment]
Is it? Since opening the issue I noticed that it happens there too, but isn't the Local API different from Invidious?

**Comment by PrestonN** [comment]
The Most Popular page is taken from an Invidious instance regardless of your API preference. As was mentioned, this is an issue with Invidious and not something that we can fix on our end.

**Comment by MPeti1** [comment]
> The Most Popular page is taken from an Invidious instance regardless of your API preference

Didn't know that, thank you!
Also, didn't want to make the question seem like "I know better", sorry for that.
