### ISSUE TITLE
Hide additional elements (Kids Safety)

### ISSUE THREAD

**Issue by opzor** [FreeTubeApp/FreeTube#1086]
I am trying to configure this app to be Safe for Kids 
and I am missing few options to accomplish this:

- Hide search bar
- Hide comments
- Hide video description area (about section?)
- Hide SHARE button under the video
- Hide UNSUBSCRIBE button under the video
- Hide LIVE streams
- Password protected settings
(i would like to prevent kids from disabling HIDE features by accidentally clicking on random stuff)

If you could implement ANY of the requested features it would be wonderful. Thanks.

**Comment by PrestonN** [comment]
Hiding different elements is pretty easy and simple to do, I'll mark this as a good first issue in case someone else would like to look into it ahead of me.

Password protecting the settings page would take a little bit more effort to do, but it isn't impossible. It isn't a priority for now, but I'd like to make it flexible to block either only the settings or the entire app. If someone else plans on working on this part then please let me know ahead of time so I can be involved.

**Comment by GilgusMaximus** [comment]
I'd also add encrypted local files to the list, because with these one would be able to add arbitrary elements to the profiles and settings

**Comment by ap971** [comment]
I can work on this issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
There is already an PR open for this one almost everything is implemented in it except for one feature https://github.com/FreeTubeApp/FreeTube/pull/1456#issuecomment-937927650

**Comment by ap971** [comment]
Since there's already a PR open with almost everything done there's no need for me to work on this issue. Thanks for letting me know!

**Comment by elshimone** [comment]
I think this ticket can be closed now?  I have checked the following features can be hidden, either through parental settings or distraction free settings:

Hide search bar
Hide comments
Hide video description area (about section?)
Hide SHARE button under the video
Hide UNSUBSCRIBE button under the video
Hide LIVE streams

Also #2907 addresses Password protected settings.  We could open another issue for encrypting the settings files, though I would be happy if my 9 year old could work around the parental controls in this app.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@elshimone u are correct this issue can be closed. I understand that u wouldnt mind ur child getting around that setting but from a privacy perspective we need to encrypt the password. 

Usecase ur sharing a PC with a whole household and just dont want someone to snoop on ur stuff. 

So yeah its best to open up an issue for that
