### ISSUE TITLE
Local API Error trying to fetch more videos from channel

### ISSUE THREAD

**Issue by orthand** [FreeTubeApp/FreeTube#1087]
**Behavior of the program**
When clicking the "Fetch more results" button on channel pages I get "Local API Error: Request failed with status code 404" and no new videos are loaded. Seems to only happen on channel pages, search etc is unaffected and works fine.

**Expected behavior**
Load additional videos from the channel.

**To Reproduce**
1. Go to any channel page
2. Scroll down and click on "Fetch more results"
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/62552927/110125895-20a9e800-7dc4-11eb-8b07-417fc30b63e9.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 Education, 20H2
 - FreeTube version: v0.11.3 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Comment by PrestonN** [comment]
This is already fixes in dev / nightly builds. This will be included in the next release.

YouTube changed their API endpoint for getting the next page so we had to update our methods to fix it.

**Comment by orthand** [comment]
My bad, thanks for the heads up!
