### ISSUE TITLE
AppImage fails to execute

### ISSUE THREAD

**Issue by evilSwanson** [FreeTubeApp/FreeTube#109]
When I try to execute the FreeTube-0.3.0-x86_64.AppImage I get the following error:

> /tmp/.mount_FreeTuWOP14X/AppRun: line 50: /tmp/.mount_FreeTuWOP14X/app/freetube: No such file or directory

I am on Kubuntu 18.04.

**Comment by toni0491** [comment]
The same happens to me on Antergos KDE Plasma

**Comment by PrestonN** [comment]
I'm going to ping @probonopd for this as I know that he's aware of this project and that he is heavily involved with the AppImage format.  Hopefully he will have a better idea as to fixing this issue.

This is something that I was able to reproduce myself.  In the past my AppImage builds seemed to be working fine but now I'm seeing this whenever I build.  I've tried using both electron-forge and electron-builder and the results are the same.  I've re-imaged my main system and tried to build on a Linux laptop that I own yet everything is having this issue.  It seems like this issue has come up before on other projects but their solutions didn't seem helpful for me.  I'll keep looking for a solution but in the mean time unfortunately I'll have to redirect users to one of the other builds available.

**Comment by probonopd** [comment]
While I am not an expert at electron-builder (@develar is), I have analyzed what is going wrong in this AppImage: It tries to run `$APPDIR/app/freetube` but the application is in `$APPDIR/app/FreeTube`.

This is how to manually fix it:

```
./FreeTube-0.3.0-x86_64.AppImage --appimage-extract

# Fix the bug
sed -i -e 's|APPDIR/app/freetube|APPDIR/app/FreeTube|g' squashfs-root/AppRun 

# Repackage AppImage
wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
chmod +x appimagetool-x86_64.AppImage 
./appimagetool-x86_64.AppImage squashfs-root/

# Test it
./FreeTube-x86_64.AppImage # works!
```

**Comment by LexHimself** [comment]
So for now a simple bash script after the build would fix the issue for the releases.
Would it not be possible to set an scr in the package.json like with the others? 

`    "make:appimage": "electron-forge make --platform=linux --targets=electron-forge-maker-appimage --src=/AppRun,`

Hard to find documentation on this, so i have taken it from the current package.json.

**Comment by PrestonN** [comment]
With the recent switch to electron-builder, I haven't had a need to rely on this fix anymore for releases.  Thanks again for your help with this @probonopd.  I apologize for not properly thanking you when I initially had this problem.

**Comment by probonopd** [comment]
Glad it is working for you now @PrestonN. Thanks for making AppImages 👍
