### ISSUE TITLE
Video format button (audio only toggle)

### ISSUE THREAD

**Issue by nicolnt** [FreeTubeApp/FreeTube#1091]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I use FreeTube mainly to reduce data consumption in an ecological concern (listenning to some content without video and not having to load YouTube's entire interface at every use). It's already awesome to be able to change the Default Video Format in the settings and directly below each video. However **it is a bit frustrating to go to the setting page to change mode and quality**. 

**Describe the solution you'd like to see implemented**
Get access to a audio-only toggle in the interface that is persistent (see 1st screenshot below).

**Describe alternatives you've considered**
There are two other options, but not as user-friendly and intuitive IMHO:

1. Persistent setting for the current session (YouTube's behavior). So that if I select a setting (quality and/or format) for a video, it would persist for the next videos of the current session. It would then reset to the Default Video Format and Default Quality when app is reloaded.
2. Move Default Video Format and Default Quality settings into the interface for easy access (see 3rd screenshot).

**Screenshots**
![Screenshot-1_toggle_audio_only](https://user-images.githubusercontent.com/12377588/110245282-cabf7680-7f62-11eb-89d8-792de2a6c65f.png)
![Screenshot-2_toggle_audio_only_settings](https://user-images.githubusercontent.com/12377588/110245290-cf842a80-7f62-11eb-8754-7a2adfdedba3.png)
![Screenshot-3_settings_in_header](https://user-images.githubusercontent.com/12377588/110245292-d1e68480-7f62-11eb-8df7-36580a42f3d6.png)

**Additional context**
If the toggle option is chosen, it's default settings could be redefined as such (see 2nd screenshot):

- Audio format : Defaut Quality
- Dash format: Defaut Quality
- Legacy format: Defaut Quality

**Thanks a lot for making this beautiful, useful, free and open source app**

**Comment by PrestonN** [comment]
It's already an option. It's the button in-between the share icon and the downloads icon. From there you can toggle which format you'd like to use.

We'll have to add more logic to save your format toggle for that session only, but it isn't difficult to do.

**Comment by nicolnt** [comment]
> It's already an option. It's the button in-between the share icon and the downloads icon. From there you can toggle which format you'd like to use.
> 
> We'll have to add more logic to save your format toggle for that session only, but it isn't difficult to do.

I know about this button but it is not as obvious as a toggle switch i my opinion. Also persistence is quite important for convenience and even more if auto-play is enabled (part of the video is going to be fetched for nothing before changing the setting again). At the time I actually find it more convenient to change the default format in the main settings than to do it for each video I'm playing.

If you actually decide to keep it as such and want to make the change persistent, check-out this other issue for UI improvement for this option #1092 

Thanks :smiley:

**Comment by BrainstormSurge** [comment]
Well for one it could be separated into it's own toggle icon next to the video icon similar to NewPipe's audio toggle feature. Could a be a music note icon as an example.

**Comment by nicolnt** [comment]
> Well for one it could be separated into it's own toggle icon next to the video icon similar to NewPipe's audio toggle feature. Could a be a music note icon as an example.

I was suggesting more of an easily reachable interface button so that it applies to the entire session, there already exists a switch that only applies for the current video being played (the one with the file icon next to the share button)

**Comment by jasonhenriquez** [comment]
Related to #2295
