### ISSUE TITLE
Publication date is not shown correctly in "Up Next" for some translations

### ISSUE THREAD

**Issue by chiak597** [FreeTubeApp/FreeTube#1094]
**Behavior of the program**
Publication date is not shown correctly for any video in "Up Next" section for some translations ("vor vor %" in German, "před před %" in Czech, "pred pred %" in Slovak)

**Expected behavior**
Publication date is OK ("1 month ago" in English) 
 
**To Reproduce**
Please add all steps to reproduce the behavior:
1. Switch to German, Czech or Slovak translation
2. Open any video
3. Scroll to "Up Next"
4. Publication date is broken

**Screenshot**
![image](https://user-images.githubusercontent.com/16289381/110253340-1a656880-7f8a-11eb-86fb-faacdfa63f7b.png)

**Environment Information (please complete the following information):**
 - OS: Debian
 - OS Version: Debian SID
 - FreeTube version: 0.12.0
 - Installation Method (If applicable): .deb
 - Primary API Used: Local API

**Additional context**
In seems that all languages where date pattern is at the end of the string are affected (e.g. "vor 1 Monat").

**Comment by chiak597** [comment]
Are you using Indivious API backend? For me, publication dates are displayed OK when using Local API but broken when using Invidious API. I guess you need to open new issue for that, since this one is for Local API.

**Comment by maboroshin** [comment]
Related: https://github.com/FreeTubeApp/FreeTube/issues/673
