### ISSUE TITLE
GPU accelleration on electron 12 ???? 

### ISSUE THREAD

**Issue by Woodhousemelena** [FreeTubeApp/FreeTube#1096]
In the update release notes it states :

_Updated to Electron v12

    This enables Video Acceleration for Linux users. Your GPU will now assist in watching videos, lowering CPU usage (Windows / Mac users already have this)_

Do we need to do anything else to enable this? I see even higher CPU usage on version 0.12 than on 0.11.3
It seems not to be enabled at all. AMD graphics.

**Comment by Generator** [comment]
On Archlinux i had to add some options to work with Hardware Decoding ``--use-gl=desktop --enable-features=VaapiVideoDecoder``  

I'm using Nvidia with libva-vdpau-driver-chromium (VDPAU backend for VA API), with original settings Hardware Decoding want's working.

Described here https://wiki.archlinux.org/title/Chromium#Hardware_video_acceleration

**Comment by neurodiverseEsoteric** [comment]
Is there a way to embed the options into the appimage or a hidden freetube config file, so that bash-history isn't flooded with the same command?

**Comment by neurodiverseEsoteric** [comment]
And would those flags keep my gpu from going over 60 degrees (celsius)?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi is this issue still valid?
