### ISSUE TITLE
(linux) New icon SVG is not transparent [freetube v0.12.0]

### ISSUE THREAD

**Issue by arrowgent** [FreeTubeApp/FreeTube#1097]
https://github.com/FreeTubeApp/FreeTube/blob/90d49053d85123cb267c6c300f6b4166a3396d9d/_icons/icon.svg
https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.12.0-beta

"Changes
New Icon for Windows / Mac / Linux systems. This Windows / Linux icon was created and used by the Papirus Icon Theme and is created by varlesh. The Mac icon is created by creepertron95. Thank you very much for the icons!"

previous .PNG scaled icons were transparent.
this is very apparent after updating to v0.12.0 and the icon background is white (when using a dark theme)

see:
https://raw.githubusercontent.com/FreeTubeApp/FreeTube/90d49053d85123cb267c6c300f6b4166a3396d9d/_icons/icon.svg
https://raw.githubusercontent.com/FreeTubeApp/FreeTube/90d49053d85123cb267c6c300f6b4166a3396d9d/_icons/.icon-set/icon_128x128.png

**Comment by PrestonN** [comment]
I'm aware it isn't transparent. The icon was designed that way. What's the actual issue? The icon looks fine to me even on a darker theme.

**Comment by arrowgent** [comment]
issue?

going from a longterm transparent icon to a white background? how is that not an issue?

if your decision is to use a white background eliminating transparency thats fine.  i have backup PNG

**Comment by gl-Gho** [comment]
please close the [issue](https://github.com/FreeTubeApp/FreeTube/issues) if your problem is solved
