### ISSUE TITLE
Auto subtitles are proposed but not displayed

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#1099]
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**
On some videos, auto-generated subtitles are not working despite being selectable via subtitles menu.

**Expected behavior**
Ability to see auto-subtitles when they are shown as available.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to some video (i honestly don't know what make it working on a video but not on another)
2. Click on 'subtitles'
3. Select 'auto-generated'

**Environment Information (please complete the following information):**
 - OS: Debian
 - OS Version: buster
 - FreeTube version: 0.12 beta
 - Installation Method (If applicable): deb
 - Primary API Used: invidious, but fallback to local if failing

**Additional context**

**Comment by GilgusMaximus** [comment]
Hi,
could you give me an example video where this happens?

Maybe the file Invidious provides is not properly formatted or cannot be downloaded correctly.

**Comment by Svallinn** [comment]
This has been fixed since https://github.com/FreeTubeApp/FreeTube/commit/3e8b137f676acefb1f7f98576820715d38b7efcb.
Closing.
