### ISSUE TITLE
Feature Request: Playlist / infinite playback

### ISSUE THREAD

**Issue by SpatiumPrinceps** [FreeTubeApp/FreeTube#11]
Hey, 

thank you for your great work! This piece of software was the last thing missing from ungoogleling my life. It works very well, I am just missing a way to play playlists or the infinite playback from youtube, so you can just let it run in the background and use it as an alternative music player.

Thank you already, keep going :+1:

**Comment by maxsandova** [comment]
+1 for some autoplay/autogenerated playlist.

**Comment by ivanhercaz** [comment]
Hi @PrestonN! This idea is very nice, I came here to suggest it, but I checked @SpatiumPrinceps already did it. However, I would like to know what is the status of this enhancement, any progress or is something planned to release yet? It's only curiosity, of course.

Thank you very much for your nice work with FreeTube!

**Comment by PrestonN** [comment]
Hey there.  You'll be pleased to know that the core functionality is finished and can be tested in the development branch.  There are still some things that I'm polishing up (both with playlists and with other features) so I wouldn't take everything as final.  I'm hoping to have an official release for it very soon so stay on the lookout for it. :)

**Comment by ivanhercaz** [comment]
Nice news @PrestonN! I am happy to read it :) If I have some free time I will test the development branch and report anything to you. I am waiting for this release with many impatience! One more time, good work with FreeTube :)

**Comment by ivanhercaz** [comment]
Awesome @PrestonN! I listened a entire music list and it works very nice! I didn't have problems with anything. If you need that someone test some specific issue you know or something else, tell me and I will try it :)

Thank you very much!

**Comment by ivanhercaz** [comment]
@PrestonN, one idea I have had is to make an option to filter if you are searching videos or lists.

**Comment by realpikolo** [comment]
Hi @PrestonN and really thanks for this wonderful app. Just started using it and very happy wit it.
I am using FreeTube player on Windows and works perfectly. Some videos are not working and also some playlists, but I can live with it.
There is just one thing I am missing, and it the option that I can see is available on https://invidio.us , and it the option to 'Autoplay next video'. Am I missing something? Or, is it an option to be included in next releases?
Love to avoid youtube 'cookieing' me and the advertisements.
Great work!!!

**Comment by PrestonN** [comment]
Hello.  Currently FreeTube will do this when viewing videos through a playlist.  Are you talking about allowing autoplay for all videos?  It can be done but I just want to make sure that is what's being asked.  If I end up doing something like that, it will likely be off by default.

**Comment by realpikolo** [comment]
> 
> 
> Hello. Currently FreeTube will do this when viewing videos through a playlist. Are you talking about allowing autoplay for all videos? It can be done but I just want to make sure that is what's being asked. If I end up doing something like that, it will likely be off by default.

Hi and thanks for replying!
Yes, I have tried playlists and some does not work, but some others do work and work like a charm, playing all the songs one after the other.
Other thing I used to do in YouTube is just play a video, and YouTube reproduces another related video when the first one ends. I guess that is the autoplay you mention. For instance when using https://invidio.us  in a browser you have the check box for 'Autoplay next video'. That's what I am not able to find in your FreeTube app.
Thanks again!

**Comment by econo202** [comment]
> Other thing I used to do in YouTube is just play a video, and YouTube reproduces another related video when the first one ends. I guess that is the autoplay you mention.

It might be helpful to know that [NewPipe](https://github.com/TeamNewPipe/NewPipe) works exactly the way you described.
