### ISSUE TITLE
Allow more than one instance of FreeTube to run

### ISSUE THREAD

**Issue by smh020** [FreeTubeApp/FreeTube#110]
the previous version was allowed to have more than one instance, but this new version doesn't allow it. Could you fix that?

**Comment by PrestonN** [comment]
The reason the new version does this has to do with the support for the new browser extension.  The extension forces another instance of FreeTube to open and then send the URL to your main window before closing itself.  There were issues with having this work alongside multiple instances in the way that I wanted to, so I had to make a limit of the amount of instances you could have.

To try to help out with this, I added the ability to open up videos in a new window by clicking on the 3 dots on the side of a video.  This should be similar to opening up several instances and I hope that this is a good enough substitute.  I tried to get it working in a better way but it's been taking up a lot of the little time that I have to work on FreeTube during the evenings so I'd like to leave it the way it is currently.  I hope this makes sense and I hope that you understand.
