### ISSUE TITLE
Local API Error (Click to copy): TypeError: Cannot read property 'title' of undefined - Similar to #1036

### ISSUE THREAD

**Issue by My-Random-Thoughts** [FreeTubeApp/FreeTube#1101]
I am getting similar error as #1036 using v0.12.0.
I've got just over 30 subscriptions, and 6 of them are having this issue.  In each case the channel logo, header image and text are missing, but the videos do load.

Running on Ubuntu 20.10 (5.8.0-44)

The screen shot below is for the channel "Babish Culinary Universe".  As you can see the left hand side is missing a lot of icons from the other broken channels.  The other missing ones include: Jeff Geerling, Lockpicking Lawyer

![Screenshot from 2021-03-09 21-47-33](https://user-images.githubusercontent.com/21334396/110542596-246d9f80-8121-11eb-9498-d38e46162257.png)

Thanks

**Comment by TimTree** [comment]
I too ran into this bug. It appears this error happens when there's more than 12 featured channels in the user's Channels tab.

When querying for featured channels when there's more than 12, the first 12 entries are `gridChannelRenderer`, and the 13th entry is `continuationItemRenderer`. I presume this bug can be resolved if we can figure out how to use the continuation token from `continuationItemRenderer` to get all the other featured channels.

**Comment by TimTree** [comment]
After further experimenting with the `yt-channel-info` module, I think I know how to fix this.

* In `yt-channel-info`, we'd need a new API function `getRelatedChannelsMore(continuation)`, which would grab additional chunks of 12 featured channels.
* `getChannelInfo(channelId)` would additionally return the continuation token for related channels.
* Within the FreeTube app, we'd add a "Fetch more results" button for featured channels.

As there's already code for handling continuations elsewhere in `yt-channel-info`, I am confident and willing to work on the fix.

@PrestonN, do you have any preference on how the API should be structured and named for handling the featured channel continuation?

**Comment by TimTree** [comment]
Pull request submitted in `yt-channel-info` to fix the bug. Once merged and the module is updated within the FreeTube app, we can work on adding the "Fetch more results" button for featured channels.

**Comment by ozars** [comment]
I built the app with @TimTree's patch. Seems like it fixes this issue (at least on Debian Bullseye).

Here is a quick walkthrough for anyone else who'd be interested in trying it out:
```
git clone https://github.com/TimTree/yt-channel-info --single-branch --branch get-related-channels-more
git clone https://github.com/FreeTubeApp/FreeTube
cd FreeTube
npm install ../yt-channel-info
npm install
npm run build
sudo dpkg -i build/freetube_0.12.0_amd64.deb    # for Debian

**Comment by manuee** [comment]
Thanks @TimTree for the PR to yt-channel-info, it got merged and there's even a new release that includes it:
https://github.com/FreeTubeApp/yt-channel-info/releases/tag/v2.1.0

I thought I would chip in my 2 cents to get this fixed :) https://github.com/FreeTubeApp/FreeTube/pull/1194

**Comment by manuee** [comment]
Running `v0.12.0-nightly-713 Beta` here, problem gone. Thank you all!

**Comment by My-Random-Thoughts** [comment]
The nightly has also fixed the issue for me, but left me with another issue.  From the original screen shot, the left hand column is missing the icons and labels for the affected channels.  The only way to get those back after this fix is to manually unsubscribe and resubscribe to them.  An export also does not include these "broken" channels.

The initial big has been fix, so I am happy  :)

**Comment by manuee** [comment]
> The nightly has also fixed the issue for me, but left me with another issue. From the original screen shot, the left hand column is missing the icons and labels for the affected channels. The only way to get those back after this fix is to manually unsubscribe and resubscribe to them. An export also does not include these "broken" channels.

I (on Ubuntu 20.04) did not encounter the problem mentioned here by @My-Random-Thoughts
