### ISSUE TITLE
Playlist video autoplay (in the sense of actually starting the video) setting to be different from "Autoplay Videos"

### ISSUE THREAD

**Issue by nicolnt** [FreeTubeApp/FreeTube#1103]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
The kind of behavior I look to reproduce is the following : being able to let playlist videos to start automatically, but not the other kind of video.
As of now, the only way to let a playlist play by itself is to enable both "Autoplay Playlists" and "Autoplay Videos", the issue is that I don't want other videos that are not part of a playlist to play automatically. This is expected behavior for me, and YouTube works like that.

**Describe the solution you'd like to see implemented**
Distinguish playlist video from other videos for the autoplay behavior.

**Describe alternatives you've considered**
Make "Autoplay Playlists" also autoplay playlist's videos so that I can let "Autoplay Videos" setting disabled for every other videos.
OR
Add a setting like "Autoplay Playlists Videos" that targets the situation described above specifically.

**Additional context**
I think that "Autoplay Playlists" should be renamed, because at this time it doesn't actually play playlist videos automatically, it just switches to the next one in queue.

**Comment by awscoder** [comment]
Yes please! I want to use the playlist feature like the watch later feature in YouTube. Currently going back and forth between the video and the playlist is cumbersome, a true Autoplay feature for the in-built playlist feature would eliminate this problem for me. Currently Autoplay only works to play recommended videos but I would like to use it for my saved videos playlist

**Comment by gybence** [comment]
Hi, I'd like to give this a shot, namely I'd add the separate toggle for playlist videos in the settings if that's ok.
However I noticed other issues related to the autoplay feature are also being worked on:
https://github.com/FreeTubeApp/FreeTube/issues/1181
https://github.com/FreeTubeApp/FreeTube/issues/4103
possible conflicts?

**Comment by jasonhenriquez** [comment]
I'm not sure when this was changed, but this issue was resolved. Only one of `Autoplay Playlists` or `Play Next Video` needs to be enabled for playlists to autoplay.
