### ISSUE TITLE
Editable hotkeys

### ISSUE THREAD

**Issue by EvilGremlin** [FreeTubeApp/FreeTube#1106]
I bet there are things that other people could add their ideas, but one most annoying thing for me personally is that ctrl+w closes window, as well as ctrl+q.
I'd much prefer ctrl+w to close current player and open subscriptions feed, and ctrl+q changed for something less prone to misclicks, like alt+x.

**Comment by GilgusMaximus** [comment]
This is already mentioned in #251 and #539
