### ISSUE TITLE
Local API Error (Click to copy): Error: Request failed with status code 429

### ISSUE THREAD

**Issue by Marekmoregta** [FreeTubeApp/FreeTube#1109]
I wanted to look at my subscriptions but suddenly this error appeared. Even if I click on the videos, this error will appear again.

I tried : Reinstalling, Change API, Change Proxy, Toggle RSS, Clear cache
But nothing worked

**Screenshots**
![7KFXjcG9Nu](https://user-images.githubusercontent.com/53852964/110951875-d7b6de00-8345-11eb-9ee7-f224e3199607.png)
![FreeTube_cisU3NeJQJ](https://user-images.githubusercontent.com/53852964/110951878-d980a180-8345-11eb-8d04-c71087a5b3f2.png)

**Environment Information**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: v 0.12.0 Beta
 - Installation Method:  .exe (Installer)
 - Primary API Used: Local API

**Comment by PrestonN** [comment]
Hello! Please see this [article](https://docs.freetubeapp.io/usage/common-issues/#429-errors) to learn more.
