### ISSUE TITLE
Open in HookTube does not work

### ISSUE THREAD

**Issue by probonopd** [FreeTubeApp/FreeTube#111]
It appends an extra string `;%20showVideoOptions(this.parentNode.previousSibling);` to the URL to be opened:

```
https://hooktube.com/watch?v=txt6sxV6X88;%20showVideoOptions(this.parentNode.previousSibling);
```

HookTube does not know what to do with that.

**Comment by PrestonN** [comment]
Thanks for catching that.  I guess I wasn't thinking when I was working on that.  The unnecessary parts of the string have been removed.
