### ISSUE TITLE
Watch age restricted vdeos

### ISSUE THREAD

**Issue by Sef1995** [FreeTubeApp/FreeTube#1110]
I am on the latest version of the FreeTube app on my Mac (Version 11.1) but when I try to watch an age restricted YouTube video it won't load. I don't know if this is a bug or a feature (request)?

**Comment by Svallinn** [comment]
v0.11.1 is **not** the latest version. Latest is v0.12.0
Also, I just tried out that specific version to see if anything is broken, it loads a age restricted video just fine.
Tested video: https://www.youtube.com/watch?v=LuZu9N53Vd0

Update the application first and see if the problem persists.
If it does, you'll need to provide more information.

**Comment by Sef1995** [comment]
Hey @Svallinn, thank you for your response. I was talking about my Mac OS X version, I am on the latest version of FreeTube. The last three days the explicit content was not working for me but now it seems to. I am closing this issue.
