### ISSUE TITLE
live broadcast

### ISSUE THREAD

**Issue by senolfndk** [FreeTubeApp/FreeTube#1111]
live stream does not open
![SharedScreenshot](https://user-images.githubusercontent.com/52818836/111074753-9a914e00-84f5-11eb-819b-958e547367cb.jpg)

**Comment by GilgusMaximus** [comment]
So we'll need a few more infos here than a stream is not work. What version of FreeTube are you using, which API etc..

Additionally the stream does work for me on the newest version. However you need to change the quality in the stream to make it work. It was mentioned somewhere already. But could be that this was in the Matrix channel and an issue tho

Best regards,
Gilgus

**Comment by senolfndk** [comment]
https://user-images.githubusercontent.com/52818836/111077173-93237200-8500-11eb-8f45-6c2f44131ef8.mp4

ok it works

**Comment by GilgusMaximus** [comment]
Great to hear. Yeah there is something going on with live streams. But atm we simply point to that error.
Thanks for checking that so quickly 👍

**Comment by senolfndk** [comment]
can you add dark theme to the base bar
![okok](https://user-images.githubusercontent.com/52818836/111077314-468c6680-8501-11eb-9d0c-7a418a6427ad.jpg)
