### ISSUE TITLE
Display bug at subscribe button 

### ISSUE THREAD

**Issue by sartamo** [FreeTubeApp/FreeTube#1123]
**Behavior of the program**
When you watch a video, you can see the subscribe button and the number of subscribers of this channel behind it. However, this number is falsely rounded and no M or K is shown. (e.g. 100 instead of 100K and 3 instead of 2.6M)

**Expected behavior**
The Subscribe button displays the number correctly

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Watch a video
2. The subscribe button shows the number of subscribers falsely (explained above)

**Screenshots**
![Subscribe_bug](https://user-images.githubusercontent.com/80825135/111464821-96497880-8721-11eb-9f39-3cc20313ae67.png) for a channel with 2.6M subscribers
![Subscribe_bug2](https://user-images.githubusercontent.com/80825135/111464833-9a759600-8721-11eb-9196-046244dc2bd3.png) for a channel with 290K subscribers

**Environment Information (please complete the following information):**
 - OS: Linux Mint
 - OS Version: 19.2
 - FreeTube version: Latest stable
 - Installation Method (If applicable): .AppImage
 - Primary API Used: Local API

**Additional context**
Note: When you use the Invidious API instead of the Local API, this error doesn't occur.
Another Note: You can still see the subscribers by clicking at the channel's icon

**Comment by GilgusMaximus** [comment]
Please update to the newest nightly build to fix this issue. It had to do with the way we tried to grab video data in different languages
