### ISSUE TITLE
colour rendering different from browser experience

### ISSUE THREAD

**Issue by yepyepyep4711** [FreeTubeApp/FreeTube#1131]
**Behavior of the program**
FreeTube's colour rendering is different from viewing in a browser, resulting especially in washed-out skin tones.

**Expected behavior**
Same rendering as vieweing in a browser.

**To Reproduce**
Please add all steps to reproduce the behaviour:
1. Open FreeTube. Go to https://www.youtube.com/watch?v=yF6QRzeAdZo . Note the rendering of Stephen's face.
2. Do the same in your browser (tested with Firefox, Vivaldi and Edge). Note the darker/warmer rendering.

**Environment Information (please complete the following information):**
 - OS: Windows 7
 - FreeTube version: 0.12.0 Beta, but existed in previous versions too
 - Installation Method : .exe
 - Primary API Used: Invidious API as per settings, but I get an "undefined" API error and "falling back to local API" when opening a video, so I guess local.

**Comment by GilgusMaximus** [comment]
Okay that is weird. For me they look identical.
Do you have both videos in the same resolution? FreeTube atm only starts at 720p not 1080p. 

However I noticed a different color scheme when watching 4k resolutions. Some videos become extremely bright, while they are not on YouTube

**Comment by yepyepyep4711** [comment]
> Do you have both videos in the same resolution? FreeTube atm only starts at 720p not 1080p.

In theory, yes, but that's assuming that FreeTube is actually displaying what it says it does. As we know this is not guaranteed https://github.com/FreeTubeApp/FreeTube/issues/791
It doesn't matter much, though. I can't see a difference in colours within FreeTube when viewing at different resolutions.

**Comment by My-Random-Thoughts** [comment]
I am also not seeing a difference, can you take a screen shot with both side-by-side as a comparison.

**Comment by yepyepyep4711** [comment]
> I am also not seeing a difference, can you take a screen shot with both side-by-side as a comparison.

Sure. This is what I see on YouTube:
![Stephen YouTube](https://user-images.githubusercontent.com/10447816/112538845-947e5580-8db0-11eb-8e6b-f956122fcecb.png)
This is what I see with FreeTube:
![Stephen FreeTube](https://user-images.githubusercontent.com/10447816/112538854-96e0af80-8db0-11eb-9c45-729ac88cae99.png)
And to confuse us even further, this is what I see when viewing with MPC-HC. It's similar to FreeTube but still different:
![Stephen MPC-HC](https://user-images.githubusercontent.com/10447816/112538859-98aa7300-8db0-11eb-93be-d94a2277f089.png)

**Comment by Svallinn** [comment]
Well technically, Electron uses Chromium.
Can you compare between the app and Chromium? (Google Chrome will **probably** display the same as Chromium, so you can use that too)

**Comment by yepyepyep4711** [comment]
> Well technically, Electron uses Chromium.
> Can you compare between the app and Chromium? (Google Chrome will **probably** display the same as Chromium, so you can use that too)

I'm using Vivaldi as a Browser, so that "YouTube" pic you see up there is already Chromium.

**Comment by Svallinn** [comment]
I just bumped electron to `12.0.5`
Can you download the latest automated build and check if anything changed?

**Comment by yepyepyep4711** [comment]
> Can you download the latest automated build (or the one in which it was bumped) and check if anything changed?
Happy to, but where? I only see the current 0.12.0 release.

**Comment by Svallinn** [comment]
https://github.com/FreeTubeApp/FreeTube/issues/1209#issuecomment-821880185

**Comment by yepyepyep4711** [comment]
It's all very confusing
This is the nightly (the rendering that I'd consider "off")
![Stephen 0 12 0 nightly](https://user-images.githubusercontent.com/10447816/116834494-ab3d7680-abbe-11eb-837d-22d3bbf5e609.png)
This is the 0.12.0 release
![Stephen 0 12 0](https://user-images.githubusercontent.com/10447816/116834495-ad073a00-abbe-11eb-852f-02e812910fab.png)

NB: the nightly is the portable version, so as not to mess with my installed regular version. However, it seems the portable version is not self-contained, as it knew my my history, my subscriptions and everything. Except for the rendering, there was no difference between the two. Clearly the portable was reading wherever the installed version saves its settings.

**Comment by Svallinn** [comment]
Correct, the portable exe is not self-contained, it saves the data in the same location

**Comment by yepyepyep4711** [comment]
> But I'm confused, 0.12.0 looks like it's much closer to Youtube then the examples you gave on Mar 25.

I totally agree. I can't explain it. I know for a fact that I didn't swap pictures by mistake, since the washed-out look in Free Tube was the whole reason for opening this issue. But now it looks like in my browser, at least with the current release, not the nightly. I really don't know what's happening here.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @yepyepyep4711 just checking in. Are u still experiencing this?
