### ISSUE TITLE
Add a setting for Picture-in-Picture video to always stay on top

### ISSUE THREAD

**Issue by VictorVow** [FreeTubeApp/FreeTube#1142]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
When I click "Picture-in-Picture" the mini player video pops-under, not on-top. Additionally, it does not have the setting "Keep Above Others" (KDE desktop), so even if it popped above the FreeTube window if I switched to a different window the mini player would be hidden again. 

**Describe the solution you'd like to see implemented**
An option in the General Settings saying "Picture-in-Picture defaults to stay on top?".

**Describe alternatives you've considered**
I can manually left-click the mini player to make it pop over FreeTube, and right-click the mini player in my taskbar then click the checkmark "Keep Above Others" but this setting is never rememebered and I have to do it every time I use PiP, even when watching the same video.

**Screenshots**
N/A

**Additional context**
Kubuntu 20.10

**Comment by mtekman** [comment]
I can attest that the PiP window stays on top in AwesomeWM

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Victor239 does this issue still occur for you?

**Comment by Victor239** [comment]
No it seems to be resolved now. Only remaining problem I have with PiP is that after being closed a new PiP window will open 0.5cm to the left, but that's a separate issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sounds like an upstream issue that we cant do anything about just like
