### ISSUE TITLE
Beta versions of FreeTube

### ISSUE THREAD

**Issue by gl-Gho** [FreeTubeApp/FreeTube#1149]
The Beta version of **freetube** should be renamed as `FreeTube-Beta` or  `FreeTube Beta` or anything else than just `FreeTube` with another icon maybe with grids, red-yellow stripes or a drop-shadow.

**Comment by PrestonN** [comment]
FreeTube in general is still a beta application, so adding special branding just for that distinction doesn't make sense at the moment. When we leave beta we can look into doing something like this but this isn't a priority.
