### ISSUE TITLE
Won't install in whonix, do I need a 32 bit compile?

### ISSUE THREAD

**Issue by JudgedbyWumup** [FreeTubeApp/FreeTube#115]
Error code :

Couldn't find any package by regex 'FreeTube_0.3.0_amd64.deb

**Comment by PrestonN** [comment]
Hey there,

Unfortunetely for Whonix you would need a 32 bit installation.  With a lot of distributions dropping support for 32 bit I don't think I'd be comfortable making official support for 32 bit at this time.  Having said that, it should be possible to build a 32 bit file if you'd like to do that.  Here are some quick instructions for doing that.

Clone down the project.
`git clone https://github.com/FreeTubeApp/FreeTube.git`

Install dependencies (Requires Node / NPM be installed on your system)
`npm install`

Install dev dependencies if needed
`npm install --only=dev`

Make the file
`npm run make`

This should create a .deb file in the `/out` folder that should work specifically for your system.
