### ISSUE TITLE
Korean character are not supported

### ISSUE THREAD

**Issue by Emmmmanuel** [FreeTubeApp/FreeTube#1151]
**Behavior of the program**
Some foreign caracter are not rendered well (in this case Korean caracter)

**Expected behavior**
I expect the caracter to be displayed instead of "야"

**To Reproduce**
The bug is always present.

**Screenshots**
![image](https://user-images.githubusercontent.com/81648909/113045903-ab9db880-919f-11eb-886e-e5364b20aab7.png)

**Environment Information (please complete the following information):**
 - OS: LinuxMint (Ubuntu)
 - OS Version: LinuxMint 20.1 cinnamon
 - FreeTube version: v0.12.0 Bêta
 - Installation Method (If applicable): FlatHub
 - Primary API Used: Local API

**Additional context**
none

**Comment by grrrrr** [comment]
On Debian 10 and freetube 0.12.0 the characters display correctly.   Do you have the relevant font packs installed on your OS?  `noto` can be a good catch all

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Checked with the same search query that was provided by the author and this doesnt seem to be an issue anymore. Let us know if it still is!
