### ISSUE TITLE
UI size changes rapidly, as if vibrating

### ISSUE THREAD

**Issue by sobornostea** [FreeTubeApp/FreeTube#1158]
**Behavior of the program**
The size of the UI changes rapidly, as if the window was vibrating

**Expected behavior**
I expect the UI not to change in size

**To Reproduce**
I tiled the window to the left and it happened, 
it disappears when you change the size of the window a bit.
I do not encounter this issue with other Electron Apps

**Screenshots**
Here is some footage
[Video footage](https://imgur.com/a/ed732wr)

**Environment Information (please complete the following information):**
 - OS: Arch
 - OS Version: N/A (rolling release)
 - FreeTube version: 0.12.0-3
 - Installation Method (If applicable): AUR
 - Primary API Used: Local API

**Additional context**
I am using KDE as my desktop environment

**Comment by linuxgirl22** [comment]
Just to add +1 ... Arch also (Anarchy), but latest appimage, and Mate desktop. 

I'd been about to post about search being broken, and seeing that Invidious has just today made a change to fix the search API (https://github.com/iv-org/invidious/pull/19220) ... while typing this, the judder has settled down itself, but the video didn't play until went back to subscription list and then clicked through again. Youtube seem to be changing a lot of things e.g. finding some RSS feeds won't work, as captcha needed.

**Comment by GilgusMaximus** [comment]
As @linuxgirl22 mentioned, this can happen when there is something wrong with the video playback. We had that in earlier stages a lot more, and especially when the invidious api was used primarily or as fallback.

Could you check whether that is the case @sobornostea ?

**Comment by sobornostea** [comment]
I do not use the Invidious API (primarily or as a fallback)
Here are my settings : 
![Screenshot_20210408_161818](https://user-images.githubusercontent.com/42158145/114042969-2c3a7400-9886-11eb-84a2-1563416e757c.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi @sobornostea are u still experiencing this?
