### ISSUE TITLE
music.youtube.com

### ISSUE THREAD

**Issue by 07416** [FreeTubeApp/FreeTube#1159]
**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify:

**Question**

Is music.youtube.com, the Google's streaming service, supported by Freetube?

example pages:

https://music.youtube.com/search?q=beatles
https://music.youtube.com/channel/UC2XdaAVUannpujzv32jcouQ

**Comment by GilgusMaximus** [comment]
It is not supported. We only support the default Youtube service, and likely will not support YouTube music.
