### ISSUE TITLE
Freetube shows a white page if video turns black for some seconds

### ISSUE THREAD

**Issue by Brueggus** [FreeTubeApp/FreeTube#1160]
**Behavior of the program**
When a video turns black for a few seconds in fullscreen, it stops. After closing fullscreen mode, Freetube only shows a white page.

**Expected behavior**
Video playback should continue.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Search for "sdWmm33VzBM" in Freetube
2. Start watching "Buying a $1 Wii from Japan" 
3. FF to 8:05
4. The video stops at ~8:11 and Freetube freezes

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.
![image](https://user-images.githubusercontent.com/37619/113470272-a0bf7e00-9454-11eb-8948-93179a4ab43d.png)

**Environment Information (please complete the following information):**
 - Arch Linux, XFCE
 - FreeTube version: 0.12.0
 - Installation Source: AUR 
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment]
Weird bug. It might be related to your Linux setup or Linux in general. On Windows the video is just playing fine. Do you have a vm or another device, with some other setup, where you could try that again?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could u reproduce this on another device?
