### ISSUE TITLE
Freetube not respecting the chosen video quality.

### ISSUE THREAD

**Issue by Abanoub8** [FreeTubeApp/FreeTube#1161]
Setting the video quality in the setting does not work.
It might be a problem where the new value is never saved,
or the player just ignores it, or maybe some other setting is conflicting with it,
i.e. some other option tells the player to choose the highest quality by default.

I would be happy to help, to solve the issue, I may be able to provide a patch
that solves the problem, upon confirmation that the problem really exists,
and if I am guided in the right direction to find the bug.

**Comment by GilgusMaximus** [comment]
Duplicate
