### ISSUE TITLE
FreeTube doesnt show you comments

### ISSUE THREAD

**Issue by 55JinS77** [FreeTubeApp/FreeTube#1162]
Behavior of the program
Cannot see the comments on a video
Local API error  (click to copy): TypeError:Cannot read property 'continuationContents' of undefined 

Expected behavior
Ability to view the comments.

To Reproduce
Please add all steps to reproduce the behavior:

    Go to a random video
    Click on "view comments"

Environment Information (please complete the following information):

    OS: EndeavourOS
    FreeTube version: v0.12.0 Beta
    Installation Method (If applicable): Arch AUR repository
    Primary API Used: both

**Comment by Angedestenebres** [comment]
Hello,

I have the error with the flatpak installation on Linux Mint.

**Comment by GilgusMaximus** [comment]
This error currently persists across all versions if your ip address is located in the european union. To avoid it until we found a fix, please use a VPN and choose a country outside of it
