### ISSUE TITLE
Unable to load comments [Windows 10, Local API]

### ISSUE THREAD

**Issue by CallOfJuarez** [FreeTubeApp/FreeTube#1165]
**Behavior of the program**
While video works just fine, when clicking on "Click to view comments", an error appears.

**Expected behavior**
Expected behavior is for the comments to load.

**To Reproduce**
1. Go to any video
2. Scroll down 
3. Click on "Click to view comments"

**Screenshots**
![Snímek obrazovky (23)](https://user-images.githubusercontent.com/81934509/113523318-74684680-95a7-11eb-958d-15cded5f1bdf.png)

**Environment Information:**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: v0.12.0 Beta
 - Installation Method: .exe
 - Primary API Used: Local API

**Comment by CallOfJuarez** [comment]
Just noticed that a lot of people are having this issue, although on different platforms, and that it has something to do with being in the EU.
Sorry 'bout that.

**Comment by linuxgirl22** [comment]
Just to add that I'm not sure it's about the EU ... I've tried various VPN servers, currently a swiss one, and can read yt comments via gtk-straw-viewer [now pipe-viewer]. No matter what I try re Freetube, I get the same error as OP. Running linux/anarchy/mate and latest Freetube appimage. Reading Invidious issues page, can see a lot is changing there, as yt shifts the goalposts.

**Comment by Woodhousemelena** [comment]
I've had this error for appx 2 weeks now. Normally these issues get fixed by an update but not on the last update I received.

running 0.12 beta, on Manjaro Linux with the AUR package. Yes I am in the EU.....

**Comment by linuxgirl22** [comment]
Can't edit my post, so just to clarify I'm in the UK.

**Comment by Tjodh** [comment]
I'm having the same issue starting about 2/3 weeks ago.

**Comment by GilgusMaximus** [comment]
I've tested some VPN servers from my provider and e.g. US American servers work fine. All European servers are hit by the new consent page. It might well be possible that Google simply slapped it on all European countries, regardless of the fact which are in the European union

**Comment by linuxgirl22** [comment]
That can very well be the case. @Svallinn fixed our module already. But it only works standalone. When used in Electron it does not work, because Electron, which is a browser, does it's own cookie management, due to implementing basic browser security features. So we are still figuring out how to get that cookie in.

Sounds great. :-)

**Comment by PrestonN** [comment]
I added a potential fix into the nightly builds. Please let me know if this works for everyone.

**Comment by linuxgirl22** [comment]
Thank you very much @PrestonN. Sorry for being the non-techie here, lol, but, although I've found where the builds are, I don't know what to do from there, eek.

**Comment by PrestonN** [comment]
All good! Click on the first build with the green check mark and scroll down where you'll see a list of binaries. Pick one that works for your system and that should give you the latest changes. More information can be found in [this](https://docs.freetubeapp.io/development/nightly-builds) article.

**Comment by linuxgirl22** [comment]
Just found https://github.com/FreeTubeApp/FreeTube/issues/1143 and have been able to download an appimage, yay. I chose /home/painter/Applications/FreeTube-0.12.0-nightly-686.AppImage. Unfortunately the same issues of error messages re comments plus no live chat comments.

**Comment by linuxgirl22** [comment]
Messages crossed over there, oops ... thank you for the link, and loving the new site/blog!

**Comment by linuxgirl22** [comment]
Sorry, somehow included my own appimage location in quoting the appimage version!

**Comment by PrestonN** [comment]
We've been talking about it for a while now, and the fix has been somewhat odd. For some reason it takes a while before the fix takes affect, but once it does there shouldn't be any more issues. This was sped up by uninstalling the app and deleting any leftover files though I don't exactly want to suggest others to do that.

**Comment by linuxgirl22** [comment]
That's a curious thing, lol. I'd removed the Freetube folder in config (already have a backup, plus it's nice and easy to import subs and tweak a few settings anyway), so will try keep opening the new appimage and see if things change.  :-)

**Comment by linuxgirl22** [comment]
Just to add some further feedback, incase that's helpful. :-)

With UK IP (via vpn), and if try swiss vpn IP, same error messages (sorry, privacy settings block uploading pictures, but I can summarise) 
... large number of subs/forcing RSS 
... local api error/status code 404 
... local api error, TypeError/ cannot read channelMetadatarenderer of undefined 
... falling back to invidious api 
... invidious api error/502 bad gateway/a padding to disable MSIE and Chrome friendly error page. 

If change to usa IP, far worse stream of the errors, and subs don't load.

**Comment by linuxgirl22** [comment]
Sorry, forgot to include, along with errors, unfortunately no comments or live chat. New feedback is all via using the latest nightly with the fix; yt seem to be making different changes more often right now!

**Comment by manuee** [comment]
Running `v0.12.0-nightly-713 Beta`. 
OS: `Ubuntu 20.04`

Not sure if its a related issue, but today I came across this Local API error:
`TypeError: Cannot read property 'forEach' of undefined`

It then falls back to Invidious which results in this error:
`undefined`

This is the video where I saw it in case someone wants to see if they can duplicate it:
https://youtu.be/4BLUv0J-h60

To see if it was just that video or all, I tried to load the comments on the previous video uploaded to the same YouTube channel, and it works fine, I then tried a few other random ones, and for all others the comments are loaded correctly... all except this one: https://youtu.be/ruvHa6Pc35E.

I tried from inside EU and outside EU, same result. It appears some video's comments load, some don't.

**Comment by linuxgirl22** [comment]
Saw something today too, reading round about various security stuff, and also not sure if it's related, but there was a comment saying querystrings now being stripped when appended to a YT url, and it's about google not wanting to share urls any more and stopping client-side. I double-up a few subs along with all article links in Liferea, and can't add any YT channel urls now, but invidious links tend to work, although often break and arrive e.g. the next day.  GTK-straw-viewer tends to bring comments through, but seems linked more to VPN's IP.

**Comment by linuxgirl22** [comment]
Just tried the test with the channel you referenced @manuee, and I can add feedback that I tried the first 7 videos and same error per video re comments ... 'continuationContents' error, falls back onto invidious api, 'undefined' errors, for each one. In UK using UK vpn IP, and have seen no change when try other countries/IPs.

**Comment by GilgusMaximus** [comment]
The problem here is not that it is not working, but that there simply are no comments and we do not account for that at the moment

**Comment by manuee** [comment]
Ow wow ok, well, thanks @linuxgirl22 for poking at this first of all, and glad to hear its a known issue, didn't thought about that possibility :)

Is there an issue to track the no-comments scenario @GilgusMaximus ? If not I will happily create one, if only to bring it into the light :)

**Comment by linuxgirl22** [comment]
@GilgusMaximus I can understand that, as videos themselves are working, this issue may not be seen to be high priority, but more 'quality of life'? It's not only comments and no live chats, but also search breaks too. The comments missing, beneath videos or during live videos, can be significant e.g. not able to read/learn further if studying something, or watching a technical solution or a distro review, and hoping to see if the solution worked, extra advice, or people's experience with a distro ... just some examples. 
With so much going on out in the world right now, the communication side feels of even more importance. Invidious used to be backup regarding broken comments, but that unfortunately isn't working now. Gtk-straw-viewer doesn't always bring comments through; 50% of the time, and I'm still puzzled how, lol, with everything that's going on. :-) 
It's getting worrying how broken things are, and I'm sure we all are concerned about many similar things online. Is there any possible way things can be fixed, or is the snippet I found on my reading round a valid indication of youtube ramping up blocking outer access? 

@manuee no problem; glad to add whatever I can, and thanks for your input. :-)

**Comment by GilgusMaximus** [comment]
@manuee Yes indeed #1040 already commented about it. 
@linuxgirl22 I do not experience any issues you are describing. For me everything works fine and I am located in Europe. So if something breaks from the new regulations I would encounter it quite quickly.

Personally I do not think it is worrying how broken things are. All of these projects are done by people in their free time. And in times such as these, people have other things to do and care about. Additionally no person is required to provide programs, everyone is doing it in their free time. 

About fixing this, you'd basically have to add a check whether data from the module is available or not. It is not too difficult to add, but atm we get so much support from the community with a lot of contributions, PrestoN currently doesn't have much free time and I am also getting back to university. So overall the pace will likely slow down even further for the next time. Unless we get more free time.

**Comment by linuxgirl22** [comment]
I was polite, not demanding, and actually made sure that my main focus was to ask if things are getting too bad for Freetube to continue. By all means, leave it; I'll look to something else. Remember others too may well be giving out a lot for free too, and have just as many difficulties, very possibly more.

**Comment by joyofdata** [comment]
FreeTube is awesome - the UI is even better than YouTube's. Thanks to everybody who spends time maintaining it! 
---
Regarding the described bug. I'd just like to bump it by mentioning that I also experience it. I'm working on Linux Mint 20.1 and am located in Germany.

**Comment by Svallinn** [comment]
This issue has been resolved in the latest automated build.
I recommend fetching one of those and running them.
For those who don't know how to do that, walkthrough here: https://github.com/FreeTubeApp/FreeTube/issues/1209#issuecomment-821880185

**Comment by joyofdata** [comment]
Phantastic - Thanks - Works like a Charm!
