### ISSUE TITLE
Video quality reverts back to Auto even tho manual input was given like 1080p, 720p and so on..

### ISSUE THREAD

**Issue by diggajupadhyay** [FreeTubeApp/FreeTube#1166]
When watching videos I find it pretty annoying that the video quality drops to very low quality. Setting Auto always reverts back to low quality. Also, manually setting quality eventually drops back to Auto for some reason.

If I select the quality to be 1080p then it should permanently set it to 1080p and never automatically change to any other quality. If it is the case of a network connection than it should have a behavior as YouTube where the loading button should be applied instead of dropping quality in the mid video and you have to change it every 2 mins.

Here is the steps even tho this might be pretty obvious.
1) Play any video
2) Manually select video quality
3) Watch it fall back to least video quality within a minute
4) Repeat with all the option including Auto, which never picks up a better quality

System:
 - OS: Fedora Linux
 - OS Version: 33
 - FreeTube version: 0.12.0 Beta 
 - Installation Method: Flathub

**Comment by GilgusMaximus** [comment]
Duplicate #595
