### ISSUE TITLE
Save Playlist

### ISSUE THREAD

**Issue by hyblocker** [FreeTubeApp/FreeTube#1170]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
The ability to save playlists seems to be missing. I'd like to save playlists in order to watch them later. If the feature is implemented the means to save a playlist should be better communicated to the end user.

**Describe the solution you'd like to see implemented**
A simple and clear button to save playlists

**Describe alternatives you've considered**
Saving videos is a workaround but playlists tend to get updated, defeating the purpose, and on the other hand, saving a playlist's videos manually is cumbersome

**Screenshots**
N/A

**Additional context**

**Comment by GilgusMaximus** [comment]
Duplicate of #312
