### ISSUE TITLE
"Mark as watched" videos not exported in History.db

### ISSUE THREAD

**Issue by orthand** [FreeTubeApp/FreeTube#1173]
**Behavior of the program**
To use FreeTube on another computer I've exported the history to a .db file to sync over the cloud. All the videos not watched but 'Mark[ed] as Watched' seem to be missing when importing the history.db on another device.

**Expected behavior**
All the videos displayed in the FreeTube 'History' section are exported in the history.db file.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Export History'
3. 'Import History' to new FreeTube instance (eg on another computer, for different a user, etc)
4. Only actually watched videos appear in history, Videos only 'Mark[ed] as Watched' are missing.

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 Education, 20H2
 - FreeTube version: v0.11.3 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Additional context**
I've seen ideas to enable a fully sync of all data so maybe this will be no problem anyway. Searching for similar reports didn't return anything so I hope this hasn't been reported yet and actually is a bug and not intended behaviour.

**Comment by GilgusMaximus** [comment]
That indeed is true. It seems like there is some information that has been left out when adding it via 'Mark as watched', which then in turn lead to insufficient data during importing the file. I'll take a look at it.

Also thanks for pointing this out, I just found another issue, that videos are added potentially multiple times. :)
