### ISSUE TITLE
Picture in picture window doesnt stay within the boundries of the screen

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1176]
**Behavior of the program**
When trying to enlarge the picture in picture window it disappears and doesn't come back until u close and reopen PIP.

**Expected behavior**
PIP window must stay within the boundaries of the screen.

**To Reproduce**

https://user-images.githubusercontent.com/73130443/114066426-4296fe80-988b-11eb-8696-1df87ce5c48a.mp4

**Environment Information (please complete the following information):**
 - OS: Windows 10
 - OS Version: 20H2
 - FreeTube version: v0.12.0-nightly-681 Beta
 - Installation Method (If applicable): portable
 - Primary API Used: local

**Comment by GilgusMaximus** [comment]
Hi,
do you happen to have a second monitor? From my experience having the pip close to the edge between these two can lead to it jumping to the other monitor.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi,
No i dont have a second monitor.

**Comment by Svallinn** [comment]
I'm pretty sure we can't do anything about this from our end.
PiP is an chromium/electron feature, we are simply using what we're given.
This is either a [`video.js`](https://github.com/videojs/video.js) issue (unlikely) or an [`electron`](https://github.com/electron/electron) issue (most likely), so try opening up an issue in those repositories.
