### ISSUE TITLE
Change the Theater mode icon

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1180]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
At this moment the Theater mode button outside the mediaplayer and the Fullwindow button inside the mediaplayer have the same icon. This can lead to confusion. The icon fits better in my opinion to Fullwindow because it does exacly what the icon says. The Theater mode does not. What happens when this issue #1177 is being implemented then u have 2 buttons with the same icon doing 2 different things.

**Describe the solution you'd like to see implemented**
Change the Theater mode icon to a icon that really represents Theater mode. See screenshot for YT implementation. 

**Describe alternatives you've considered**
None

**Screenshots**
![Capture](https://user-images.githubusercontent.com/73130443/114073797-357e0d80-9893-11eb-957c-001b7caff578.PNG)

**Additional context**
None

**Comment by GilgusMaximus** [comment]
Definitely a good idea. If someone wants to take over this, [here](https://github.com/FreeTubeApp/FreeTube/commit/7be4bf28f2174716b3ae8e739c3dcc350001c17a) is a commit by PrestoN when he added the loop button:

It should work similar to that.

**Comment by PikachuEXE** [comment]
How about this?
![Screen Shot 2021-04-20 at 14 41 22 ](https://user-images.githubusercontent.com/1018543/115349561-963c0d00-a1e6-11eb-9d3a-c42ba7ccebe2.png)

Icon is https://fontawesome.com/icons/window-maximize?style=solid
Or try to find an icon you see fit and start an instance to test it yourself?
The line I changed is
https://github.com/FreeTubeApp/FreeTube/blob/v0.12.0-beta/src/renderer/components/watch-video-info/watch-video-info.vue#L77

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
How about this icon i think it represents the behavioral of theater mode some what more.

https://icons8.com/icon/12365/maximize-window

**Comment by PikachuEXE** [comment]
From what I know this project use [Font Awesome](https://fontawesome.com)
I have no idea how to use external SVG files as icons
Would be easier to swap icon if the new one is from `Font Awesome`

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Well that is too bad. I checked the site and i find it really hard to find a icon on there that represents the behaviour of theater mode. I tried searching for "window" and "window width".

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah i found something what about this?

https://fontawesome.com/icons/rectangle-landscape?style=regular

**Comment by PikachuEXE** [comment]
Sorry to tell you that a "pro" icon requires paying ;)

**Comment by PikachuEXE** [comment]
Several icons that might work:

![image](https://user-images.githubusercontent.com/1018543/115490549-e4a5e600-a290-11eb-943d-fde4d812cc49.png)
![image](https://user-images.githubusercontent.com/1018543/115490662-1a4acf00-a291-11eb-93f0-49ca6bceb48f.png)
![image](https://user-images.githubusercontent.com/1018543/115491338-5894be00-a292-11eb-8c0f-e4931492b542.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is that icon u used the same as this one?
https://fontawesome.com/icons/tv?style=solid

> 
> 
> Several icons that might work:
> 

> ![image](https://user-images.githubusercontent.com/1018543/115490662-1a4acf00-a291-11eb-93f0-49ca6bceb48f.png)

**Comment by PikachuEXE** [comment]
The icons used are:
- [square](https://fontawesome.com/icons/square?style=solid)
- [tv](https://fontawesome.com/icons/tv?style=solid)
- [external-link-square-alt](https://fontawesome.com/icons/external-link-square-alt?style=solid)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I think the TV one will do. What do u think about it @GilgusMaximus?

**Comment by GilgusMaximus** [comment]
So, personally I think the TV Icon is fitting, but in my honest opinion, it would be most beneficial to add it to the player like it was suggested in the original issue. This will make it consistent and move player related setting to the player and leaves non player related settings and options down there

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Yes i thought u would said that. This will just be a temporarily fix so there is no confusion to be made between the icons. In that issue i also added another icon for turning off theater mode. So if that issue is implemented in the player the icon that is used in this issue will be used for enabling theater mode and the other one for disabling.

**Comment by GilgusMaximus** [comment]
As a temporary fix sure, if it does not require some major rework if you want to use the svg file.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The icon that is going to be used is this one

**Comment by PikachuEXE** [comment]
Done
https://github.com/FreeTubeApp/FreeTube/pull/1225

**Comment by peepopoggers** [comment]
Hey, coming from #1315, I think this icon is confusing; looks like fullscreen/tv-cast instead of theater mode.
It needs to be something that can imply width.

**Comment by peepopoggers** [comment]
![image](https://user-images.githubusercontent.com/72892531/119243517-5a86c100-bb5f-11eb-9da9-d6a22bb3957f.png)
Are these two worse in implied use?

**Comment by peepopoggers** [comment]
![image](https://user-images.githubusercontent.com/72892531/119243548-ac2f4b80-bb5f-11eb-87b1-a18f349da6b0.png)
Also thinking this might make sense too

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
#1177 is regarding implementing the integration of the button into the player. The icon should change when theater mode is enabled like described in the issue. In my opinion if we use this icon for enabling and the other one described in that issue for disabling it would look just fine.

**Comment by PikachuEXE** [comment]
Problem with 
https://fontawesome.com/icons/arrows-alt-h?style=solid is that 
there is no "reverse" icon for it
Otherwise I think it could look better than TV one (current)

Or we can consider
- https://fontawesome.com/icons/expand-arrows-alt?style=solid
- https://fontawesome.com/icons/compress-arrows-alt?style=solid

But then these might be confused with full window button icons

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Too bad there isn't a good reverse icon.

I agree that ur proposed icon would cause confusion.

**Comment by ralphocdol** [comment]
Even if you're into coding, this would still look close enough.

![Screenshot_20210603_201641](https://user-images.githubusercontent.com/31056871/120643599-e5bc5c80-c465-11eb-8f9c-aab7eacfd9de.png)

link: https://fontawesome.com/v5.15/icons/laptop-code?style=solid

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This doesnt have a reverse icon.

**Comment by PikachuEXE** [comment]
I think the current one looks better since the it's a TV which makes me think the display would become wider than normal.
Laptop one doesn't bring that feeling to me (even with those arrows).
