### ISSUE TITLE
Hide Picture in Picture button when u are in fullscreen

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1182]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
At this moment PIP button is not hidden when u are in fullscreen. In my opinion it doesn't need to be there if u are in fullscreen. I cant think of an use case that make sense for the button to be there. Why would u go fullscreen and then go into PIP?

I know YT also had the same implementation of Freetube but for a long time now they have it made hidden.
Just a assumption but I guess they maybe analyzed the amount of clicks when in fullscreen and saw that the percentage of people using clicking on it is low, so they made the button hidden. 

**Describe the solution you'd like to see implemented**
Hide the button when u are in fullscreen. See video.

**Describe alternatives you've considered**
None

**Video**

https://user-images.githubusercontent.com/73130443/114158708-871aac80-9914-11eb-909d-4ba145b5c590.mp4

**Additional context**
None.

**Comment by GilgusMaximus** [comment]
As long as it is working, I do not see why we should remove it. Someone else might use it and then we'd have to add it back in.
