### ISSUE TITLE
If I have some FreeTube instances (windows) open and I close one of them, all the others that I opened after it also close.

### ISSUE THREAD

**Issue by bob808** [FreeTubeApp/FreeTube#1183]
**Behavior of the program**
If I open for example 3 different windows, and I close the first one, all other windows close. If I open 5 windows, and I close the 3rd one, the 4th and 5th also close.
**Expected behavior**
If I open 5 different windows and I close the 3rd one, only it should close, with the 4th and 5th staying open

**To Reproduce**
Open a few windows and close one of the first ones, all succesive ones will also close.

**Screenshots**

**Environment Information (please complete the following information):**
 - OS: [Ubuntu]
 - OS Version: [Ubuntu 20.04]
 - FreeTube version: [v0.12.0 Beta]
 - Installation Method (If applicable): [.deb]
 - Primary API Used: [Invidious API]

**Additional context**

**Comment by GilgusMaximus** [comment]
The thing that is happening here is that electron is basically building a tree of windows. If you close a parent window, all child windows will close as well. Apparently you can do window management, but with tabs coming at some point, I am not too certain it would be useful at the moment to fiddle with that.

**Comment by bob808** [comment]
I tend to have more windows open and keep some videos for later. Ideally there'd be tabs for this. Not a deal breaker but would be nice to fix this at some point in the future.

**Comment by GilgusMaximus** [comment]
Yeah we have that on the table for the future and it was requested a lot. But we'll have to plan this accordingly cause combining this with other features such as dynamic playlists and similar, we need to settle for one design which we follow through
