### ISSUE TITLE
User-Agent (Strip it)

### ISSUE THREAD

**Issue by gvvng** [FreeTubeApp/FreeTube#1186]
User can be identified with user-agent (FreeTube/0.12.0)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) FreeTube/0.12.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36

**Comment by Svallinn** [comment]
Trust me, there's plenty of things that can be used to identify FreeTube that we have absolutely no control over because of Electron

**Comment by GilgusMaximus** [comment]
Additionally, if all users have the same user agent, then you are one of many. But as Svallin said. Due to electron the other side can even see how the application is named, so it is FreeTube.

**Comment by PeterDaveHello** [comment]
Not sure if we can simply set it to "FreeTube/version" so that there will at least be less information to share? (like OS platform)
