### ISSUE TITLE
Remember channel sorting type when going back to channel

### ISSUE THREAD

**Issue by peepo5** [FreeTubeApp/FreeTube#1188]
When you visit a channel, scroll to a video and visit it, if you navigate back to the channel it scrolls to the thumbnail of the video that you clicked. This works fine normally.

However, if you sort the videos by oldest or most popular, it does not remember that you changed this setting and it scrolls to the same location but in the newest category instead, going to a different place than it should. This is quite annoying when you just want to browse through old videos, and you have to change it everytime you go back to the channel.

A fix- In the same way the scroll location is stored, the sorting values could be stored with the page so it is remembered when it is revisited.

**Comment by chumpyy** [comment]
The same is true when filtering a channel by search terms. 

I would however say that the "sort by" oldest/most-popular is the more important of the issues as these are what are typically used when deciding whether to subscribe to a newly discovered channel.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing i favor of https://github.com/FreeTubeApp/FreeTube/issues/2446
