### ISSUE TITLE
Add playback controls to mini player

### ISSUE THREAD

**Issue by smh020** [FreeTubeApp/FreeTube#119]
could you enable things like playback speed and going forward and backward using the left and right keys?

**Comment by PrestonN** [comment]
I think that this functionality is going to be bundled with a different feature that I have planned.

My plan is to give the video player a more unique look to it that fits the rest of the application.  While doing this, I want to take the current controls below the video to be merged with the inline video controls.  I don't know when this will be out but it's definitely planned. :)

**Comment by dtpnk** [comment]
:+1: for a **playback speed** in the miniplayer

**Comment by PrestonN** [comment]
Closing as this has been implemented and will be included in the next release.
