### ISSUE TITLE
Picture-in-picture video garbled when resized too much

### ISSUE THREAD

**Issue by ParaSait** [FreeTubeApp/FreeTube#1190]
**Behavior of the program**
When watching a video in picture-in-picture mode (in a tiling window manager, qtile in my case) and resizing it beyond a certain threshold, moving the mouse over the video will cause the video to become momentarily garbled (see screenshots to see what I mean). Whenever not moving the mouse cursor over it, it becomes fine again.

**Expected behavior**
Video doesn't get garbled when moving the cursor around over it.

**To Reproduce**
1. Open the app in Qtile.
2. Go to any video.
3. Activate picture-in-picture mode, and have the video be tiled.
4. Grow the size of the tile beyond the maximum width and/or height that would be allowed in floating mode.
5. Move the mouse cursor around on the video.

**Environment Information (please complete the following information):**
 - OS: Arch Linux, qtile
 - FreeTube version: freetube-bin 0.12.0-3
 - Installation Method: AUR
 - Primary API Used: Local API

**Screenshots**
![freetube_garbled1](https://user-images.githubusercontent.com/5515059/114306103-0a85fa80-9adb-11eb-920f-ee586207f425.png)
![freetube_garbled2](https://user-images.githubusercontent.com/5515059/114306105-0bb72780-9adb-11eb-9031-0750fb17d315.png)

**Comment by Svallinn** [comment]
There's nothing we can do about this from our end.
This is either a [`video.js`](https://github.com/videojs/video.js) issue (unlikely) or an [`electron`](https://github.com/electron/electron) issue (most likely), so try opening up an issue in those repositories.
