### ISSUE TITLE
Next video goes out of fullscreen and Fullwindow on Autoplay

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1192]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
When autoplay is enabled and u watch a video in fullscreen or fullwindow the player doesnt stay in fullscreen or fullwindow when its switching to the next video.

**Describe the solution you'd like to see implemented**
When it switches to the next video the player must stay in fullscreen or fullwindow!

**Comment by SebTota** [comment]
What is the difference between fullscreen and fullwindow?

**Comment by Addictc** [comment]
Status update?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The PR is put on hold because of other priorities

**Comment by anonaddict** [comment]
I'd like to request the priority of this be re-assessed, this and the similar issue for PiP, theatre mode and fullscreeen(?) (whatever the mode is called you activate with s) are the only bugs I've run into the last couple months despite having freetube running >20 hours a day and they are a big turnoff

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2295
