### ISSUE TITLE
Option for buffering the whole video

### ISSUE THREAD

**Issue by Joshua-Ashton** [FreeTubeApp/FreeTube#1193]
**Important note**
Please check other open and closed issues for a similar feature request before proposing a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Is your feature request related to a usage problem (not a bug)? Please describe.**

Sometimes, when I am watching something my internet goes down.

This is really annoying and I can only watch up to what has been buffered so far which is about a minute or two around where I got up to.

**Describe the solution you'd like to see implemented**

I'd like an option to buffer the whole video from start to finish globally in the Settings menu.

Apologies if this has been asked before, I would have thought it would be a common request -- I looked in the Settings tab and didn't see anything and also had a quick scout of the issues under "buffer" and also didn't see anything though.

**Comment by GilgusMaximus** [comment]
Closing as this basically falls under #678
