### ISSUE TITLE
Duplicate quality settings [nightly-717]

### ISSUE THREAD

**Issue by orthand** [FreeTubeApp/FreeTube#1200]
**Behavior of the program**
Since switching to the last nightly: [Some](https://youtu.be/7B2PIVSWtJA) videos with 2:1 quality settings show duplicate values for 960p and lower.

![image](https://user-images.githubusercontent.com/62552927/114875701-d9206e00-9dfd-11eb-9c64-46b597963403.png)

Edit: Seems to affect normal ratios as well.
![image](https://user-images.githubusercontent.com/62552927/114902426-1bee4000-9e16-11eb-8448-05dae63c86ac.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 Education, 20H2
 - FreeTube version: v0.12.0-nightly-717 Beta
 - Installation Method (If applicable): setup-x64.exe 
 - Primary API Used: Local API

**Comment by PrestonN** [comment]
This is intended. The quality logic on nightly is a WIP and still needs to be finished. The multiple quality options you see are 60FPS variants and still needs to be labeled and handled before the next release.
