### ISSUE TITLE
TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by Sanek1512** [FreeTubeApp/FreeTube#1202]
I can't open the profile of these Russian channels:
- [Артём Матяшов](https://www.youtube.com/channel/UCJHS22_QyRowmNAaxoUd4dA)
- [Павел Шмачилин](https://www.youtube.com/user/Shmachilin)
- [Григорий Семёнов](https://www.youtube.com/channel/UCvUBwTp_GJtrOwqbU60OV5Q) 

When you log in to your profile, you will see: Cannot read property 'title' of undefined.

Environment Information:
 - OS Version: Windows 10
 - FreeTube version: 0.12.0
 - Installation Method: .exe
 - Primary API Used: Local API

![Image1](https://user-images.githubusercontent.com/47472361/114963867-a1223500-9ea8-11eb-8da1-93385e38ad1b.PNG)

![Image2](https://user-images.githubusercontent.com/47472361/114963948-c57e1180-9ea8-11eb-8496-13e41182f2e9.PNG)

**Comment by GilgusMaximus** [comment]
This has been fixed in the newest nightly build. Please check whether that applies here as well :)
