### ISSUE TITLE
Locale Preference: System

### ISSUE THREAD

**Issue by ovari** [FreeTubeApp/FreeTube#1205]
1. Please add a `System` preference to the `Locale Preference` drop-down, i.e. `Settings` → `General Settings` → `Locale Preference` → `System`.
2. Please make `System` the default `Locale Preference`.
3. In the event that the `System` locale translations are unavailable in FreeTube, please show the strings in `English (US)`.

What do you think?

Thank you

**Comment by GilgusMaximus** [comment]
This issue could be implemented by a new user, as it is potentially easy to do.
A quick google search lead me to this documentation page:

https://www.electronjs.org/docs/api/locales

If someone wants to get going with this and needs some help, feel free to ask :)

**Comment by milupol** [comment]
Hey I am new to Open Source and at the moment I'm also fairly new to electron and vue (I know what they are doing and get used for). But i want to try implementing this feature. Is that fine

**Comment by ovari** [comment]
Thank you for implementing. Is the label to "System Language" translatable? Thank you once again

**Comment by Svallinn** [comment]
No, not yet.
Thanks for reminding me of that.
One of us will implement that ourselves when we have the time (unless someone else does it first).

**Comment by ovari** [comment]
Perhaps this has been done here:
https://github.com/FreeTubeApp/FreeTube/commit/8e4fe4eacb2de6a831d11eed84a0d6a8104d5bba#diff-4eaadcc25bfbd7ab1ba912e36d5e1bcbab346cab59546a970df7546d5fb7a145R116

With the string now showing on Weblate at:
https://hosted.weblate.org/translate/free-tube/translations/hu/?checksum=43cef30db93cb0b1

Thanks to everyone for helping with this feature.
