### ISSUE TITLE
Privacy Redirect doesn't redirect Channel or Playlist links

### ISSUE THREAD

**Issue by vocux** [FreeTubeApp/FreeTube#1207]
I'm using the Privacy Redirect add-on in Firefox and it redirects YouTube video links to FreeTube just fine but doesn't redirect any other YouTube-links (I've tried channels and playlists so far). FreeTube comes up from minimized, so it seems to receive the link, but it doesn't display anything.
I'm using Windows 10. Tried local and Invidious API.
Is this a bug or not implemented yet?

**Comment by GilgusMaximus** [comment]
It definitely doesn't work correctly as also #1061 mentioned
Thanks for reporting this :)
