### ISSUE TITLE
Mobile app?

### ISSUE THREAD

**Issue by TheGamingCoderNoob** [FreeTubeApp/FreeTube#1210]
**Important note**
Please check other open and closed issues for a similar feature request before proposing a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Is your feature request related to a usage problem (not a bug)? Please describe.**
I use youtube on my phone all the time and i want to start using freetube
Please describe clear and concise of what the problem is. Ex. I'm always frustrated when [...]
**Describe the solution you'd like to see implemented**
Find an electron-like framework for Android/iOS and change some things around
Please give a clear and concise description of what you want to happen.

**Describe alternatives you've considered**
Are there other ways to solve the problem? Please give a clear and concise description of any alternative solutions or features you might have considered.
I see the apks online but I'm pretty sure  they're fake

**Screenshots**
Sometimes people have screenshots from mock-ups or other projects. Add them here.

**Additional context**
Add any other context about the feature request here.

**Comment by PrestonN** [comment]
https://docs.freetubeapp.io/faq/#do-you-plan-on-porting-freetube-to-other-platforms-android-ios-etc
