### ISSUE TITLE
Dockerfile with integrated build toolchain

### ISSUE THREAD

**Issue by Stig124** [FreeTubeApp/FreeTube#1213]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Please describe clear and concise of what the problem is. Ex. I'm always frustrated when [...]
Building dependencies can be a pain, especially if your Linux distro is missing huge pack of software
**Describe the solution you'd like to see implemented**
Please give a clear and concise description of what you want to happen.
I propose (and I'm already working on it) that a Dockerfile be in the repo with all the dependencies integrated for a final build without hassle of manually sourcing those
**Describe alternatives you've considered**
Are there other ways to solve the problem? Please give a clear and concise description of any alternative solutions or features you might have considered.

**Screenshots**
Sometimes people have screenshots from mock-ups or other projects. Add them here.
I already done something like this for the [brainflow repo](https://github.com/brainflow-dev/brainflow/blob/master/Docker/Dockerfile)
**Additional context**
Add any other context about the feature request here.
This not at all what was proposed in #355, the sole goal of this image is to facilitate building

**Comment by GilgusMaximus** [comment]
Thanks for putting it together. I'd assign you to the issue so it is clear this is being worked on :)

**Comment by Stig124** [comment]
I would have liked the Dockerfile to apply to local dev directory, but npm is a hell when you speak of dependencies. 
How that'll work is that it will clone your fork (or even separate repo) of of git then install the dependencies and build the excecutable, I know this is not as efficient as what I would like that to work

**Comment by GilgusMaximus** [comment]
Ah, so it will basically not run in dev mode, but only spit out the executable files?

**Comment by Stig124** [comment]
Exactly yes, this can be very helpful when you want to build rpm on deb-based machines for example
