### ISSUE TITLE
Search box doesn't handle channel type urls appropriately

### ISSUE THREAD

**Issue by Svallinn** [FreeTubeApp/FreeTube#1218]
**Behavior of the program**
Search box doesn't redirect channel type urls

**Expected behavior**
Search box should redirect channel type urls to the approppriate channel view

**To Reproduce**
1. Paste a channel type url into the search box
2. It assumes it's a search query just like any other

**Environment Information (please complete the following information):**
 - FreeTube version: development

**Additional context**
The way to properly fix this is to move the `handleYoutubeLink` function (present in the `src/renderer/App.js` file) to one of the Vuex stores, in order to make it accessible to the `top-nav` component as well
A few modifications to the function itself will also be necessary

https://github.com/FreeTubeApp/FreeTube/blob/78324ff775349b78ad52066d49e864b409cb3b0f/src/renderer/App.js#L298-L401

**Comment by PikachuEXE** [comment]
I just finished https://github.com/FreeTubeApp/FreeTube/pull/1221
Before I found this issue
I don't even remember why I started it
