### ISSUE TITLE
Comment replies shows the video's comments instead

### ISSUE THREAD

**Issue by MuffinLover42** [FreeTubeApp/FreeTube#1224]
**Behavior of the program**
Whenever you click "See replies" it shows the video's comments including the comment which you clicked.

**Expected behavior**
The replies of the comment are shown.

**To Reproduce**
1. Go to any video
2. Go to the comments
3. Find a comment with replies
4. Click "See replies"

**Screenshots**
![Bug](https://user-images.githubusercontent.com/50763425/115689052-3d39b980-a34b-11eb-8f1a-2654663fa4ca.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: v0.12.0 Beta
 - Primary API Used: Invidious with local fallback

**Additional context**
None.

**Comment by GilgusMaximus** [comment]
Could you please install the newest nightly version? A while back we had to do some changes to fix it for european users and maybe that also fixes your issue here, as I am personally not having this issue atm

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This issue does not occur on the latest nightly build v0.12.0-nightly-743 Beta.

**Comment by marvinwankersteen** [comment]
This error still exists for me.
- OS: Linux Mint 20.2
- FreeTube v0.13.2 Beta
- Primary API Backend: Local running Invidious 2021.07.31-c76bd7b

When I use the local API, no comments are loaded at all.

**Comment by ChunkyProgrammer** [comment]
> When I use the local API, no comments are loaded at all.

That issue should be fixed in the Nightly Builds.

You can find the nightly builds here
https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml
