### ISSUE TITLE
Player doesnt load M3U

### ISSUE THREAD

**Issue by YTW** [FreeTubeApp/FreeTube#1226]
Why does the player on freetube never play the M3U? youtube-dl manages fine without ever updating. I have to open the console and copy the M3U into VLC all the time.. so there is clearly not an issue with grabbing the stream.

**Comment by GilgusMaximus** [comment]
I am not sure what you mean with playing M3U? We use the DASH format to stream videos from YouTube.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please provide the information requested before
