### ISSUE TITLE
Video does not play when using wayland

### ISSUE THREAD

**Issue by serkam228** [FreeTubeApp/FreeTube#1227]
Artix Linux (openrc)
Using a package from aur "freetube"
WM: sway (xwayland disable)
Command to run: freetube --enable-features=UseOzonePlatform --ozone-platform-wayland

Launches and works without errors in the console and in the interface, but the video does not play. If you use x11 everything works

**Comment by Cactus158** [comment]
I think this is an issue with Electron, so there isn't much the FreeTube team can do about it. Personally I leave xwayland on because several apps that I use still don't directly support wayland.

**Comment by GilgusMaximus** [comment]
Usually these issues come from the wide variety of WM's on Linux and the compatibility with Electron. And from some threads I have read, basic support should have been added in Electron 12. If it does not work, then there is likely a problem with Electron still

**Comment by Cactus158** [comment]
Also, I would recommend using the freetube-git package, as it builds from the latest source, so if/when this is fixed you will get the update sooner.

**Comment by Cactus158** [comment]
It might be worth using the freetube-git package for a bit, as it builds from the latest source, so issues that you might have with that particular build might be fixed. The person maintaining that package doesn't seem to update the PKGBUILD much, so you might have to manually reinstall it, but it might help with the issue.

**Comment by Svallinn** [comment]
I'll be marking this as `invalid` and closing it, since there nothing to do on our end.
You can still discuss it here in case any changes occur regarding this issue.
