### ISSUE TITLE
add copy url to subscription video menu

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#123]
A second suggestion.

On the subscription page, I feel it would be useful to have a "copy url" option in the three dot menu for each video.

This could be helpful for people you copy the video to `youtube-dl` cli tool to download the videos.  At the moment you have to click into a video copy the URL and because there is no `back` button are forced to click the `subscripton` page again and then scroll to where they were.

**Comment by PrestonN** [comment]
This is a very quick and easy thing to include.  I will include this in the next release.

**Comment by PrestonN** [comment]
Added as of v0.3.2, closing.
