### ISSUE TITLE
Disable Hardware Media Key Handling

### ISSUE THREAD

**Issue by TheBirdsAreWatching** [FreeTubeApp/FreeTube#1230]
I personally find it quite annoying to have this enabled and was wondering how I could go about disabling the hardware media key handling. I've tried adding `--disable-features=HardwareMediaKeyHandling` but this didn't work. Am I missing something or is it not supported at all?

**Comment by GilgusMaximus** [comment]
There is a flag in electron which allows to stop this. We already had a request in the Matrix chat a few weeks ago. I am not sure tho whether that was added tho.
