### ISSUE TITLE
Custom playback speed option

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [FreeTubeApp/FreeTube#1238]
In current moment playback speed possible to be or 1.25 or 1.5. 
Please add more flexibility in playback speeds settings. It will be nice to have possibility to change playback speed with 0.1 steps. 
Also will be nice to change playback speed pointing to playback speed control and using mouse wheel.

**Comment by M09NST3R** [comment]
Agree, this is essential. I was about to try this app, but this is a deal breaker for me. I watch all YouTube videos on 2x because otherwise I could read the same content much faster and be more efficient that way. I wish there was a 2.5x setting.

**Comment by Svallinn** [comment]
@M09NST3R that's not what they just said, they said they want to turn the feature **that already exists** to have intervals of 0.1 steps, which is completely different
also, I'm not 100% sure if the official release already had this (probably does), but the latest automated build certainly does
![image](https://user-images.githubusercontent.com/41585298/116790599-979ded00-aaa4-11eb-8dd2-2e3cd896c6fa.png)

**Comment by M09NST3R** [comment]
> @M09NST3R that's not what they just said, they said they want to turn the feature **that already exists** to have intervals of 0.1 steps, which is completely different
> 
> also, I'm not 100% sure if the official release already had this (probably does), but the latest automated build certainly does
> 
> ![image](https://user-images.githubusercontent.com/41585298/116790599-979ded00-aaa4-11eb-8dd2-2e3cd896c6fa.png)
> 
> 

Great. Thank you. I read the post as if ONLY 1.25x and 1.5x were possible.

**Comment by GilgusMaximus** [comment]
I changed the title to make it more clear and in line with the idea of the post. Adding hundreds of possibilities will not be useful and sustainable. Adding an option to type the value directly will be much more useful and sustainable

**Comment by drcassar** [comment]
This would be a great feature have. Reducing the granulometry from 0.25 to 0.1 would work great for me.

For the future, I suggest a similar implementation to the Video Speed Controller extension (https://github.com/codebicycle/videospeed), where we can increase and decrease the playback speed by a defined value using keyboard shortcuts.

**Comment by alekksander** [comment]
i most frequently use 1.15 and 1.20 — both are unavailable in freetube currently. speed rates should be customizable (also their persistence between videos should be easily switchable without digging into settings)
