### ISSUE TITLE
List subscriptions alpahbetically ignoring case

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#124]
On the left sidebar in the main interface the list of subscribed channels is listed by case before alphabet.

Example

Currently channels show as

    A Channel
    B Channel
    D Channel
    c channel

When you have large list of subscriptions it makes more ideal to sort by alphabet ignoring case,  using about it should show like

    A Channel
    B Channel
    c channel
    D Channel

**Comment by PrestonN** [comment]
This is fixed in the rewrite.
