### ISSUE TITLE
No audio on any video

### ISSUE THREAD

**Issue by MPeti1** [FreeTubeApp/FreeTube#1242]
**Behavior of the program**
On opening and starting to play a video in FreeTube, it's audio should play too.

**Expected behavior**
The audio does not play.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open any video, either from history, subscriptions or search results
2. Start playing the video
3. Notice that sound does not play

note: these are probably not enough steps to reproduce the issue, but this is all I know what did I do. The error persists across runs of FreeTube, even if I kill FreeTube.exe and it's child processes and then try again.

**Screenshots**

#### Dev tools console logs, and also here you can see that the volume slider is at the maximum in the player:
![image](https://user-images.githubusercontent.com/9215491/116729865-3c51f900-a9d7-11eb-95a4-8096faab2a7a.png)

Also, [the bottom of the dev tools console logs](https://user-images.githubusercontent.com/9215491/116729994-6d322e00-a9d7-11eb-8138-4cf9aa489315.png). Only SourceMap warnings were left out between the 2 screenshots.

#### FreeTube does not show up as an audio producer in the Settings app's "audio router" menu
![image](https://user-images.githubusercontent.com/9215491/116728374-5be82200-a9d5-11eb-8bb0-37c93b31c9b9.png)

note: the reset button didn't fix the problem

#### FreeTube does not show up as an audio producer in the Volume Mixer under either of my audio devices

|||
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/9215491/116728602-a2d61780-a9d5-11eb-89cb-15824b2d328f.png) | ![image](https://user-images.githubusercontent.com/9215491/116728843-f47ea200-a9d5-11eb-8023-2600b04f29fb.png) |

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: v0.12.0
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Additional context**
Audio from other software works as expected.
Default audio device is set to the one that I actually use (verified by the fact that audio is working in other software, including Firefox).
I don't think this was always an issue with v0.12.0, I think it worked for some time, but something must have happened to it recently

**Comment by Svallinn** [comment]
Are you using the official release?
If so, try using the latest automated build instead.
Walkthrough here: https://github.com/FreeTubeApp/FreeTube/issues/1209#issuecomment-821880185

**Comment by MPeti1** [comment]
I'm using the official release.

v0.12.0-nightly-771: it's the same. got the idea to check what happens if I rename FreeTube.exe, in case it's something in my system, but renaming it to asd.exe and running it didn't bring back the audio either

**Comment by PrestonN** [comment]
I'd have to look into this more, but this feels more like an issue with your system and not an issue with FreeTube itself.

Having said that, I don't unfortunately have any suggestions as far as a fix. If it's possible to replicate on one of our systems then we can look into this further but if it isn't then there might not be much that we can do about this.

**Comment by MPeti1** [comment]
> I'd have to look into this more, but this feels more like an issue with your system and not an issue with FreeTube itself.

I can imagine that's the case, but can't confirm it or the opposite.
I haven't installed system updates since (and around) when this started, but I wasn't even able reboot for some time because there are a lot of things open that I need, so I don't know yet if this persists across reboots.
What I tried though is restarting the Audiosrv system service, which helps in the rare occasions when something goes wrong with thee system audio, but it didn't help now.

**Comment by GilgusMaximus** [comment]
Well this is definitely a system related problem. FreeTube should at least show up as audio source
If it does not, then there is a problem with the system registering it. Could you try the portable version instead of the installer? Maybe the installer has some sort of problem with something on your system / update or whatever. Windows is usually not that helpful when it comes to consistency

![image](https://user-images.githubusercontent.com/34301369/116825991-20468700-ab92-11eb-9c74-d6f1c51c589c.png)

**Comment by MPeti1** [comment]
It seems to be the same. No audio, and FreeTube not appearing in the volume mixer.

**Comment by MPeti1** [comment]
I've renamed %appdata%\FreeTube\ to try out a fresh profile, but it also is the same.
Do you have an idea how could I troubleshoot this? I'm at a bit of a loss here :/ I was writing here because it only happens with FreeTube, but at the same time I don't have any other electron apps installed which I could try if they can make any sound (I have Bitwarden, but AFAIK that can't make sounds)

**Comment by GilgusMaximus** [comment]
You could try some app from the list of electron apps : https://www.electronjs.org/apps?q=audio

I am also a bit lost here at the moment tbh. This is really a problem of Electron and less of FreeTube. If you test another app and it also does not work, I would suggest asking over at Electron what the problem could be.

**Comment by MPeti1** [comment]
Tried 2 apps from there, [Dusk Player](https://www.electronjs.org/apps/dusk-player) and [Museeks](https://www.electronjs.org/apps/museeks). Tried playing the same audio file with them (a simple mp3 file), and the former was able to play it, but the latter wasn't. An interesting thing though is that the latter has an option to select an audio output device, but the list for it is empty.
It seems it's an Electron issue, so I'll contact the Electron devs

**Comment by Svallinn** [comment]
Since this has been determined to be an upstream problem, I'll be closing this then.
You can continue to comment here to let us know on the status of the situation.

**Comment by MPeti1** [comment]
Managed to reboot and it's now working properly, so it was indeed an OS bug.
Sorry for the inconvenience!
