### ISSUE TITLE
Some live streams not loading "immediately"

### ISSUE THREAD

**Issue by rrrevin** [FreeTubeApp/FreeTube#1243]
Windows version 0.12.

"Live" stream does not work initially, but works in web browser. Freetube just displays the "loading" circle and that's it.. until you press "pause", then "play". After that the video loads.

ex: https://www.youtube.com/watch?v=B3wlAQtqynk
It happens for any live video on this channel : https://www.youtube.com/channel/UCwobzUc3z-0PrFpoRxNszXQ

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi are u still experiencing this issue. I couldnt reproduce this myself. The video did load on both API's. It only took a bit to load. 5-15 sec
