### ISSUE TITLE
"%" signs in translations do not change

### ISSUE THREAD

**Issue by MertComert** [FreeTubeApp/FreeTube#1244]
**Screenshots**
![Works correctly on subscriptions tab and channels](https://user-images.githubusercontent.com/69315360/116739355-3e7a7e80-a9fc-11eb-9329-a812cb5d0e2f.png)
![Doesn't work correctly in the upcoming videos section](https://user-images.githubusercontent.com/69315360/116739373-42a69c00-a9fc-11eb-8450-ca4542fbef43.png)

**Environment Information :**
 - OS: Pop_OS!
 - OS Version: Pop_OS! 20.10
 - FreeTube version: 0.12.0 Beta
 - Installation Method: FlatHub and Deb
 - Primary API Used: Local API

**Comment by Svallinn** [comment]
If you're using the latest official release (and not the latest automated build), it's possible that, at that moment in time, the Turkish translations were still incomplete.
If that's the case, try out the latest automated build.
Walkthrough here: https://github.com/FreeTubeApp/FreeTube/issues/1209#issuecomment-821880185

**Comment by Svallinn** [comment]
No communication for 20 days, closing as stale and, most likely, irrelevant.
Let us know if you wanna overturn that decision.
