### ISSUE TITLE
Video sometimes plays in the background with sound when exited

### ISSUE THREAD

**Issue by Sandyran** [FreeTubeApp/FreeTube#1246]
**Behavior of the program**
When I sometimes click on a video, and then press back, the sound of that video may play in the background. If you click on the same video again, the sound is still there in the background. It doesn't continue the video from the same point that the video in the background (the buggy one) is. This results in the sound of those videos being played and overlapped. The only way to stop it, is to close FreeTube.

**Expected behavior**
You click on any video. If you manage to press "back" at a certain point, that video might still play in the background.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Click on any video.
2. Click "back" or any similar buttons/functions as fast as you can.
3. The video might now still play in the background.

**Environment Information (please complete the following information):**
 - OS: Linux Mint.
 - OS Version: 20.1.
 - FreeTube version: 0.12.0 Beta.
 - Installation Method (If applicable): .deb.
 - Primary API Used: Local API.

**Additional context**
This doesn't happen all the time, but it has happen some times. Therefore, it may be hard to reproduce it.

**Comment by GilgusMaximus** [comment]
Yeah, I experienced this as well rarely. It happened mostly when I quickly went to a video and backwards. Seems like then electron is not properly closing everything and the streaming still continues.

**Comment by peepopoggers** [comment]
Same here, page loads after I close it. Happens when I switch fast.

**Comment by GilgusMaximus** [comment]
Yeah, it happened to me a while ago as well. I would assume some race conditions again. Probably the async code for loading the page not properly stopped before switching pages when reaaally trying to force it by fast switching

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Sandyran and @peepo5 is this still reproducable for u?

**Comment by Sandyran** [comment]
Hi, I haven't used FreeTube in a while, so I don't know.

**Comment by Sandyran** [comment]
Hi, @efb4f5ff-1298-471a-8973-3d47447115dc. I don't know. It has been a while since I last used FreeTube, so I can neither confirm not deny it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah okay. Thankyou for the quick response :)

I guess i'll just need to wait for @peepo5 response
