### ISSUE TITLE
Cannot zoom back out after zooming in (CTRL+ not working) [Electron issue]

### ISSUE THREAD

**Issue by peepopoggers** [FreeTubeApp/FreeTube#1247]
**Behavior of the program**
Cannot zoom back in after zooming out.
Most likely due to electronjs.

**Expected behavior**
Zoom out works only.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Use CTRL & MINUS
2. The window will size down
3. Now try and do CTRL & PLUS
4. It does not zoom back in

**Environment Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - FreeTube version: v0.12.0 Beta
 - Installation Method (If applicable): AppImage
 - Primary API Used: Local API ??

**Solution**
You can add a custom function w/ eventlistener that takes CTRL+ and zooms the page in when activated.

**Comment by GilgusMaximus** [comment]
You can use the Alt key and then the default browser bar at the top occurs. There go to View->Zoom In

Hope this helps :)

**Comment by peepopoggers** [comment]
My alt key is broken. Also its strage to be able to zoom in but not out. A function would make sense.

**Comment by PAI5REECHO** [comment]
Okay but why does the `Zoom Out` keybind (<kbd>Ctrl</kbd>+<kbd>-</kbd>) work but the `Zoom In` keybind (<kbd>Ctrl</kbd>+<kbd>+</kbd>) doens't work? This issue should be reopened.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> @efb4f5ff-1298-471a-8973-3d47447115dc can we re-open this issue? I'm facing the same problem where zooming back in doesn't work right now. I can try and tackle it just wanted to make sure it's documented :)

Done!
