### ISSUE TITLE
Import NewPipe subscription exports

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#125]
Could it be possible to get a feature that you allow users of NewPipe to export their subscriptions from there and either import or merge into FreeTube.

This would help a long way to making the most use of these two great programs

**Comment by tiotrom** [comment]
How's the progress with this? :)

**Comment by PrestonN** [comment]
This has been finished thanks to #234

**Comment by Slomo17** [comment]
> To add on to this, I think it would be pretty cool if we can have FreeTube and NewPipe sync together using Syncthing or something similar. This would take quite a bit of coordination with the NewPipe guys though so we could set everything up properly.

Syncing with Newpipe over Syncthing would be perfect, than there would really be no more reason to use a google account for youtube
