### ISSUE TITLE
Changing the color of the filter button when a filter is apply

### ISSUE THREAD

**Issue by e471wo** [FreeTubeApp/FreeTube#1251]
Hi, it's a stupid thing but each time I use the filter (for example find videos longer than 20 minutes), I totally forget there is a filter and so I m astonesh when I have to find something and only find video longer than 20 minutes after. 

Could be cool if the filter button could change color when it's used. (lets say red). And so we know if there is an active filter in the research result. 

thanks.

**Comment by GilgusMaximus** [comment]
Definitely a good idea. I do not use filters myself, but I can see that this might be a good visual clue.
An alternative would be to change the icon to make it more accessible as well

**Comment by PikachuEXE** [comment]
Implemented but not sure what effect should be used
https://github.com/FreeTubeApp/FreeTube/compare/development...PikachuEXE:feature/filter-change-indicator

![Screen Shot 2021-05-07 at 11 55 35 ](https://user-images.githubusercontent.com/1018543/117400121-96514200-af34-11eb-857a-e3ef9396bdd9.png)
![Screen Shot 2021-05-07 at 11 55 38 ](https://user-images.githubusercontent.com/1018543/117400131-99e4c900-af34-11eb-9e4f-a8f63de1b373.png)
