### ISSUE TITLE
Stats for nerds

### ISSUE THREAD

**Issue by MariasStory** [FreeTubeApp/FreeTube#1253]
**Important note**
No silimar request.

**Is your feature request related to a usage problem (not a bug)? Please describe.**
Need additional playback and stream info to debug performance problems

**Describe the solution you'd like to see implemented**
Please implement a statistics feature similar to the Youtube player "stas for nerds".
In particular, I am interested in dropped frames.

**Describe alternatives you've considered**
Kind of "information" tab in QMPlay2.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
U can definitely work on this @constraintAutomaton
