### ISSUE TITLE
Fetch more results - Local Api error #939 

### ISSUE THREAD

**Issue by tekblupace** [FreeTubeApp/FreeTube#1259]
**Behavior of the program**
Same as previously closed error #939

**Expected behavior**
No error

**To Reproduce**
Search for a video, then click on show more results

**Screenshots**

![image](https://user-images.githubusercontent.com/29518503/117412191-668e4400-af0c-11eb-8d5d-ce51106c3fad.png)

**Environment Information (please complete the following information):**
 - OS: Fedora
 - OS Version: 34
 - FreeTube version: v0.12.0 Beta
 - Installation Method (If applicable): Flathub
 - Primary API Used: Local API

**Additional context**

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
can confirm that this issue does not persist in the latest nightly build

**Comment by ChunkyProgrammer** [comment]
Just to confirm, this issue no longer occurs and can be closed?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@tekblupace please respond to the previous comment
