### ISSUE TITLE
Stuttering Video Experience on External Monitor

### ISSUE THREAD

**Issue by kojid0** [FreeTubeApp/FreeTube#1261]
I have a stuttering video experience on my external BenQ monitor, connected via HDMI. FreeTube plays videos nicely on my internal HP Envy Notebook, but when I move the window to the BenQ monitor, the video suttters a lot. Hardware Specification is very good (AMD 7 4000 Series)

OS: ZorinOS (Ubuntu 20.04) with FreeTube v0.12.0 Beta via FlatHub. Local API

**Comment by GilgusMaximus** [comment]
Could you try to install the newest nightly build from the Actions tab manually ? There were some changes in Electron, and Hardware acceleration as well, which might help you out. 

But in the last few weeks many different people on different distros, with sometimes quite special wm setups have experienced issues. So if it is an underlying problem with Electron and your setup, then we are not able to help much further than that

**Comment by kojid0** [comment]
I've tested the latest build, unfortunately no changes. The video is still stuttering. Do you know another Electron App which plays videos? If yes, I could try that one to test if stuttering is an issue of Electron or FreeTube.

**Comment by kojid0** [comment]
I currently don't have problems with stuttering anymore. Using v0.13.1 beta. Closing this issue.
