### ISSUE TITLE
getting native or closer to native

### ISSUE THREAD

**Issue by je-vv** [FreeTubeApp/FreeTube#1263]
It'd be great for FreeTube to become more of a multi platform native application, like Qt based, rather than being based on Electron, which in essence it's running on top of chromium.  Not as ideal, but still better than electron would be using Flutter.  Hopefully you can consider this as a future improvement.

**Comment by Svallinn** [comment]
https://docs.freetubeapp.io/faq/#electron-is-bad-please-use-something-else
While I **kind of** understand the Flutter argument, it would take an considerable amount of time and effort to port our current efforts from HTML/CSS/JS/Vue to Dart/Flutter.

For now, we'll be prioritizing the implementation of new features that provide parity to YouTube's features over porting the app to a more native and performant environment.
It could be something to be done in the future, but as it stands now, we don't exactly know when it'll happen.
