### ISSUE TITLE
Norwegian Bokmål locale missing

### ISSUE THREAD

**Issue by comradekingu** [FreeTubeApp/FreeTube#1275]
0.12.0 Beta
![bilde](https://user-images.githubusercontent.com/13802408/118100081-5a0b5f00-b3d6-11eb-8671-fd06a11ec60c.png)
Installed the amd64.deb

**Comment by GilgusMaximus** [comment]
It is in the newest nightly builds
It wasn't in the last release because quite a few texts were missing and the app was not fully usable due to that
