### ISSUE TITLE
Translatable blog

### ISSUE THREAD

**Issue by comradekingu** [FreeTubeApp/FreeTube#1277]
https://blog.freetubeapp.io
on
https://docs.freetubeapp.io ?

Happy to write release posts btw.

**Comment by GilgusMaximus** [comment]
The blog posts will not be translated as this is really not useful and most of the blog posts would probably end up with parts translated while the rest is not translated.

**Comment by PrestonN** [comment]
To add to this, the blog posts tend to be written pretty quickly and are usually published right after they're done, so none of them would end up translated even with our current setup. We'd likely have to wait a week or longer if we wrote them ahead of time and waited for translations to come through. This becomes more of a problem when longer blogs are released.

Our docs page could definitely be setup to accept translations though. I'll need some time to set that up however. There's a lot on our plates at the moment so it mat be a while. I'd rather track progress in that repository however.
