### ISSUE TITLE
Electron and Pulseaudio compatibility: Show the icon and name from Freetube instead of chromium

### ISSUE THREAD

**Issue by ElishaDaugherty** [FreeTubeApp/FreeTube#1279]
**Behavior of the program**
Freetube is displayed in pulseaudio as a Chromium browser. Although this is obvious, it is difficult to distinguish the difference between Freetube and any other program in Electron or chromium itself.

**Expected behavior**
The freetube app should display its own icon and name instead of using chromium one.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Play some sound and/or video on the chromium
2. While the chromium is still playing, run Freetube and play some video

**Screenshots**
[In the KDE Plasma pulseaudio applet
](https://user-images.githubusercontent.com/77898421/118157155-977ce600-b3f0-11eb-9016-4c9d0f6f664c.png)
[Pavucontrol (agnostic GUI for PA)](https://user-images.githubusercontent.com/77898421/118157200-a368a800-b3f0-11eb-8826-1dd818803b28.png)

if you prefer the CLI:
```
$ pactl list sink-inputs
application.icon_name = "chromium-browser"
                media.name = "Playback"
                application.name = "Chromium"
                native-protocol.peer = "UNIX socket client"
                native-protocol.version = "34"
                application.process.id = "2680"
                application.process.binary = "electron"
                module-stream-restore.id = "sink-input-by-application-name:Chromium"
```

**Environment Information (please complete the following information):**
 - OS: Linux (fedora)
 - OS Version: 33
 - FreeTube version: 0.12.0 beta
 - Installation Method (If applicable): AppImage
 - Primary API Used: Local API

**Additional context**
I don't know if this can be solved by the Freetube side itself, but I am creating this issue to keep up with the progress of this issue in upstream https://github.com/electron/electron/issues/27581

**Comment by toby63** [comment]
I also face this on other electron applications, so the link to the upstream issue of Electron that the reporter provided is correct:
https://github.com/electron/electron/issues/27581

You might still reopen this and mark it as "upstream" or "electron".
