### ISSUE TITLE
ability to mark subscribed channels and the whole subscription feed watched

### ISSUE THREAD

**Issue by bughit** [FreeTubeApp/FreeTube#1282]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
The idea is to only see new stuff in the feed. So there are two scenarios:

- When adding a new subscription you need to be able to
  - mark the whole channel watched
  - mark everything older than a particular video watched
- When viewing the aggregate subscriptions feed
  - mark everything watched

**Describe the solution you'd like to see implemented**
- mark subscriptions feed watched
- mark channel watched
- for a given video in a channel, mark older ones watched
- less important but nice to have: mark arbitrary multiple selections of videos watched

**Describe alternatives you've considered**
Marking individual videos watched is not workable if there are many.

**Comment by Randshot** [comment]
At the moment, marking a video as watched, is essentially adding them to the history playlist (if I am wrong, please correct me).
This means, that adding all videos from a channel to that playlist is unrealistic in my opinion, and then there is the issue of needing to fetch all videos of said channel, which could result in a lot of paging requests.
That being said, a new (visual) mechanism could be implemented, that, when you mark a channel as watched, internally adds the publish timestamp of the selected video/newest video to a list. FreeTube could then display any video older than that as watched (or hide them, if the setting is turned on), without needing to add all the videos to the history playlist.

Just my two cents on the issue :smile:

**Comment by orthand** [comment]
Have a look at #1088 where a few options have already been discussed

**Comment by Randshot** [comment]
@orthand Thanks for the reference. I see that you pretty much mentioned the way I described above, which tbh. is pretty easy to add, implementation wise.

**Comment by GilgusMaximus** [comment]
Yes, it basically would work like #1088 
It would not work that we mark all videos on a channel as watched. Then you would get ip blocked after a tiny percentage of videos from a larger channel and would have to do it multiple times and always be blocked for up to 48 hours without a VPN. 

So only for loaded videos this will be possible and then the selection mode of #1088 is basically the way to go. therefore i am going to close this issue in favor of #1088
