### ISSUE TITLE
Update volume percentage properly

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1285]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
The volume % number keeps changing when u hover over the slider. So lets say u put the volume at 20% and hover to 50 and go out of the volume the volume percentage will stay at 50 even if it is not 50. 

**Describe the solution you'd like to see implemented**
It is no problem to show 50 when u hover over it but when u go out of the volume and in the volume must say what the actual volume percentage is.

**Describe alternatives you've considered**
None.

**Screenshots**

https://user-images.githubusercontent.com/73130443/118402942-b29f5e00-b65b-11eb-8ad6-c84e5fa3a0a8.mp4

**Additional context**
None.

**Comment by PrestonN** [comment]
This volume indicator seems to have been included with an update to Video.js, so it wasn't something that we implemented ourselves. Having said that, it clearly doesn't look or work well with our themed player so we'll likely just hide it. As you can probably tell, it isn't actually changing your volume so it isn't too harmful at the moment. I'll get that hidden here shortly.

**Comment by PrestonN** [comment]
Should be hidden in the latest nightly build now.
