### ISSUE TITLE
Local API Error (Click to copy): TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by supracoralline** [FreeTubeApp/FreeTube#1288]
**Behavior of the program**

- FreeTube shows "TypeError: Cannot read property 'title' of undefined" when importing subscriptions using Local API (~~Invidious doesn't work, it just says "This will take a while"~~ Invidious works, just had to change the server).
- "TypeError: Cannot read property 'title' of undefined" is also shown when opening certain channels. This happened to 6+ channels that I opened.  Two examples are: Coolausdtin DR and A-Sketch MUSIC LABEL
- When subscribing to the channels that throws "TypeError: Cannot read property 'title' of undefined", they are listed on the top of the list without Channel picture and Channel Name/Title. 

**Expected behavior**
- Be able to subscribe and import subscriptions without experiencing "TypeError: Cannot read property 'title' of undefined"

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open FreeTube
2. Search for Coolausdtin DT or A-Sketch MUSIC LABEL (These two are just the 2 examples that I remember, it happened to 6+ channels. Let's call these channels "Bugged Channels" temporarily)
3. See Error (Error is also shown when importing a subscription file that contains a "bugged channel")

**Screenshots**
[imgur Screenshot Link](https://imgur.com/a/jw4L7yH)

**Environment Information (please complete the following information):**
 - OS: Windows 10 Pro x64 
 - OS Version: 10.0.19042 Build 19042
 - FreeTube version: v0.12.0 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Comment by supracoralline** [comment]
It seems to work fine with the Invidious API. This probably has something to do with the Local API.

**Comment by PrestonN** [comment]
This is already fixed in the nightly builds. I tested both channels you mentioned. They have the error in the live version like you mentioned, but do not occur anymore in the nightly builds. New release will hopefully be soon along with this fix.
