### ISSUE TITLE
Likes are no longer visible on comments

### ISSUE THREAD

**Issue by 7echLife** [FreeTubeApp/FreeTube#1290]
This bug was present when FreeTube 0.13 was released. It even happened in version 0.12 when 0.13 was released. 

Likes are supposed to be counted and visible on people's comments.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any video
2. Click on any video
3. Scroll down to the comments section
4. See error, every comment doesn't have a visible number of likes especially top comments with the most likes.

**Screenshots**
For some reason, GitHub can't read JPG screenshot files, but let's just say that there's no like number counter next to the like button on people's comments.

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.13
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I also saw this yesterday with Newpipe so i think YT changed something again

**Comment by 7echLife** [comment]
Oh yeah, I also saw that too. I thought I was going crazy. I'll still use both, but I'll probably use the desktop version in private browsing. Close the issue or keep this issue open?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Keep it open.

**Comment by 7echLife** [comment]
Ok

**Comment by GilgusMaximus** [comment]
most likely a new html element added somewhere. I'll take a look at it
