### ISSUE TITLE
Trending & Most Popular pages are not hidden in bottom bar, when in portrait view

### ISSUE THREAD

**Issue by senntore** [FreeTubeApp/FreeTube#1291]
**Behavior of the program**
When selected to hide Trending & Popular Videos from Distraction Free Settings in Settings, their icons is not hidden & still shows up in [...]More
**Expected behavior**
When selected to hide Trending & Popular Videos from Distraction Free Settings in Settings, their icons in bottom bar should be hidden just like it is hidden in the sidebar.
**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to Settings & enable Hide Trending/Popular Videos
2. Shrink the window's width to go in portrait view
3. In the bottom bar, select [...]More

**Screenshots**
Icons hidden in Sidebar
![Screenshot from 2021-05-18 07-48-12](https://user-images.githubusercontent.com/58325574/118581431-43d31980-b7af-11eb-96c3-a3eeffbe88a5.png)
Icons not hidden in Bottom bar
![Screenshot from 2021-05-18 07-48-02](https://user-images.githubusercontent.com/58325574/118581438-49306400-b7af-11eb-90a3-381ba0d35d7b.png)

**Environment Information (please complete the following information):**
 - OS: Pop OS!
 - OS Version: Pop OS! 20.10
 - FreeTube version: 0.13.0
 - Installation Method (If applicable): .deb
 - Primary API Used: Local API

**Additional context**

**Comment by ChunkyProgrammer** [comment]
I can do this one
