### ISSUE TITLE
Screen corruption on Fedora 33

### ISSUE THREAD

**Issue by ScrambleTheRamble** [FreeTubeApp/FreeTube#1292]
**Behavior of the program**
When launching the application I get significant screen corruption in the Electron window, as far as I can tell I can not disable hardware acceleration within the application so I can not exclude hw acceleration  causing this issue.

Example of screen corruption: [https://ibb.co/zVfKyt6](https://ibb.co/zVfKyt6)

**Expected behavior**
Clean interface

**To Reproduce**
Please add all steps to reproduce the behavior:
1.Launch app

**Screenshots**
[https://ibb.co/zVfKyt6](https://ibb.co/zVfKyt6)

**Environment Information (please complete the following information):**
 - OS: Fedora
 - OS ##
 - FreeTube version: 0.13.0
 - Installation Method (If applicable): Fedora Software Center
 - Primary API Used: Invidious API

**Additional context**
OS: Fedora 33 (Workstation Edition) x86_64 
Host: X570 AORUS ULTRA -CF 
Kernel: 5.11.20-200.fc33.x86_64 
Resolution: 2560x1440, 2560x1440 
DE: GNOME 3.38.4 
WM: Mutter 
CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz 
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 
Memory: 11106MiB / 32108MiB

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi is this still an issue for u?
