### ISSUE TITLE
Feature Request: Variable Playback Speed

### ISSUE THREAD

**Issue by ervinshiznit** [FreeTubeApp/FreeTube#13]
I love FreeTube! It's working great for me so far.

The only request I have is for a variable playback speed - some of the people talk way too slowly in some of the videos I like to watch.

**Comment by PrestonN** [comment]
Hey there.  This is on the current road map.  I can probably get this in to a new release next week.  Thanks for putting an issue here so I can track it.  Take care :)

**Comment by ervinshiznit** [comment]
Thanks!

**Comment by PrestonN** [comment]
This feature has been implemented.  Expect to see this in the next release. :)
