### ISSUE TITLE
Request: Portable Version (Windows)

### ISSUE THREAD

**Issue by PhillyMay** [FreeTubeApp/FreeTube#130]
I don't know how difficult it would be to deliver a portable version of Freetube, but it would be cool to have the ability to just use it without having to install it.

Another positive aspect is the "portability", so you can save it on a pendrive and use it on every windows pc in this world. 

Furthermore, you could personally save it in the cloud drive of choice and have it synced across all your windows pc (eg. if you use onedrive, its integrated right in your explorer. so it would "sync" your subs and all across pc, notebook, tablet etc.)

**Comment by PrestonN** [comment]
Hi there!

We actually provide portable versions in the form of `.zip` files over at the [release](https://github.com/FreeTubeApp/FreeTube/releases) section.  This should allow you to run FreeTube without installing it.  Having said that, settings and subscriptions will not be saved in that folder.  Maybe in the future I can allow users to pick their preferred location for these settings so that they can sync them together using their preferred method.

**Comment by rddim** [comment]
Check this [FreeTubePortable](https://github.com/rddim/FreeTubePortable/releases)
It's an online installer that will download the FreeTube-win32-x64-0.3.1.zip. It's packaged with a PortableApps.com launcher as a portable app.

**Comment by rddim** [comment]
FreeTube 0.3.2 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.3.2-dev1)

**Comment by rddim** [comment]
FreeTube 0.4.0 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.4.0-dev1)

**Comment by PhillyMay** [comment]
@rddim Thank you for your effort. I really appreciate your work.

**Comment by rddim** [comment]
@PhillyMay Thank you for the trust :) and sorry for the delay

FreeTube 0.4.1 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.4.1-dev1)

**Comment by rddim** [comment]
FreeTube  0.5.0 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.5.0-dev1)

**Comment by rddim** [comment]
FreeTube  0.5.1 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.5.1-dev1)

**Comment by PrestonN** [comment]
Hey there @rddim.  I really appreciate you keeping up with this.  I have added your Portable version to the README.  You're welcome to keep posting here for updates, but I will go ahead and close this issue so that I can clean up what still needs to be done.

Thanks again!

**Comment by rddim** [comment]
@PrestonN  great :) Thank you very very much. I will continue to posting here.

By the way FreeTube 0.5.2 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.5.2-dev1)

**Comment by rddim** [comment]
FreeTube 0.5.3 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.5.3-dev1)

**Comment by rddim** [comment]
FreeTube 0.6.0 Portable release [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.6.0-dev1)

**Comment by rddim** [comment]
FreeTube 0.6.1 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.6.1-dev1)

**Comment by rddim** [comment]
FreeTube 0.7.0 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.7.0-dev1)

**Comment by rddim** [comment]
FreeTube 0.7.1 Portable release [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.7.1-dev1)

**Comment by rddim** [comment]
FreeTube 0.7.2 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.7.2-dev1)

**Comment by rddim** [comment]
FreeTube 0.7.3 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.7.3-dev1)

**Comment by rddim** [comment]
FreeTube 0.9.0 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.9.0-dev1)

**Comment by rddim** [comment]
FreeTube 0.9.1 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.9.1-dev1)

**Comment by rddim** [comment]
FreeTube 0.9.2 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.9.2-dev1)

**Comment by rddim** [comment]
FreeTube 0.9.3 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.9.3-dev1)

**Comment by rddim** [comment]
FreeTube 0.10.0 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.10.0-dev1)

**Comment by rddim** [comment]
FreeTube 0.11.2 Portable released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.11.2-dev1)

**Comment by rddim** [comment]
FreeTube 0.11.3 in PortableApps.com Format released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.11.3-dev1)

**Comment by rddim** [comment]
FreeTube 0.12.0 in PortableApps.com Format released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.12.0-dev1)

**Comment by rddim** [comment]
FreeTube 0.13.0 in PortableApps.com Format released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.13.0-dev1)

**Comment by rddim** [comment]
FreeTube 0.13.1 in PortableApps.com Format released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.13.1-dev1)

**Comment by rddim** [comment]
FreeTube 0.13.2 in PortableApps.com Format released [here](https://github.com/rddim/FreeTubePortable/releases/tag/v0.13.2-dev1)

**Comment by rddim** [comment]
FreeTube 0.14.0 in PortableApps.com Format released [here](https://portableapps.com/node/64694)

**Comment by rddim** [comment]
FreeTube 0.17.1 in PortableApps.com Format released [here](https://portableapps.com/node/64694)

Important: Even if `SupportsUNC=` is set to `yes`, UNC will not work. To use it, you need to add the `--no-sandbox` command-line parameter, preferably to the `AdditionalParameters=`. Use it at your own risk!

**Comment by rddim** [comment]
FreeTube 0.18.0 in PortableApps.com Format released [here](https://portableapps.com/node/64694)
* Screenshots should be saved in `\Data\Screenshots` folder

**Comment by rddim** [comment]
FreeTube 0.19.0 in PortableApps.com Format released [here](https://portableapps.com/node/64694)
