### ISSUE TITLE
conflicts with 1password 

### ISSUE THREAD

**Issue by boistordu** [FreeTubeApp/FreeTube#1301]
> 	file /usr/lib/.build-id/13/070cd6d4401903dee7a42e402d150de4362b18 from install of freetube-0.13.0-1.x86_64 conflicts with file from package 1password-8.0.34-1.x86_64
> 	file /usr/lib/.build-id/3e/d503d7be965ab698b328fe3a69162a4efb5351 from install of freetube-0.13.0-1.x86_64 conflicts with file from package 1password-8.0.34-1.x86_64
> 	file /usr/lib/.build-id/45/f06cc2ff072fee7975d5ff2529e322a9f654a8 from install of freetube-0.13.0-1.x86_64 conflicts with file from package 1password-8.0.34-1.x86_64
> 	file /usr/lib/.build-id/5b/8864b69ddfe3bd034d5dbef9b814a8f9b59cbd from install of freetube-0.13.0-1.x86_64 conflicts with file from package 1password-8.0.34-1.x86_64
> 	file /usr/lib/.build-id/aa/3dcddb236dbafa5fed294576f1087f31d4303f from install of freetube-0.13.0-1.x86_64 conflicts with file from package 1password-8.0.34-1.x86_64
> 	file /usr/lib/.build-id/af/4374e54497edac9a84703037832fafb0d99308 from install of freetube-0.13.0-1.x86_64 conflicts with file from package 1password-8.0.34-1.x86_64
> 	file /usr/lib/.build-id/b4/fe1769dc0dbcd634d93f5ffd826d0354016f9e from install of freetube-0.13.0-1.x86_64 conflicts with file from package 1password-8.0.34-1.x86_64
> 	file /usr/lib/.build-id/f0/d8c634c19103e2e50b980cc1fb5cbacdc8d07c from install of freetube-0.13.0-1.x86_64 conflicts with file from package 1password-8.0.34-1.x86_64
> 	file /usr/lib/.build-id/f3/13677b4c4d959f49800be71689dc788f06ae94 from install of freetube-0.13.0-1.x86_64 conflicts with file from package 1password-8.0.34-1.x86_64

**Comment by Svallinn** [comment]
***Stop deleting the templates, fill them out properly***
I am incredibly tempted to close this as is for that alone.
But, on top of that, you simply copy pasted the error without telling us anything else, which makes it completely useless in terms of **actually identifying the problem**.
I'm closing this, open another issue and properly fill out the issue template, don't just delete it.
