### ISSUE TITLE
Allow the option to hide the "download" button, and have it hidden by default

### ISSUE THREAD

**Issue by rjdg14** [FreeTubeApp/FreeTube#1306]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
While it doesn't go against YouTube's service to create an API that is capable of displaying its content, it does go against YouTube's terms to download content from the service (unless there is a download button provided, which very few videos have). FreeTube has a button which can't be hidden that allows the user to do just that, and I find it a little unsettling since I would never want to use it.

**Describe the solution you'd like to see implemented**
I would like an option added in the settings menu that allows the user to hide the download button, much like it's possible to hide suggested videos and channel subscriber numbers. Additionally, I feel it would be wise for FreeTube to have it hidden by default, with a disclaimer warning users that the tool is to be used at their own risk if they turn it on.

**Describe alternatives you've considered**
There isn't really any alternative to my suggestion - you can currently choose not to download the videos but the button is still there.

**Screenshots**
Below are a couple of mockups I've made of how such a feature could look:

![FTSuggestion2](https://user-images.githubusercontent.com/73315260/119141580-582c4600-ba3d-11eb-8359-fe5dc82cc13c.png)
![FTSuggestion1](https://user-images.githubusercontent.com/73315260/119141585-58c4dc80-ba3d-11eb-87a4-412db94973df.png)

**Comment by Svallinn** [comment]
From my perspective, our approach does not break YouTube's ToC.
We simply provide a link to the video and/or audio streams that the user has to manually download ***if they wish to***, we don't provide a direct download link.
And even if we did, that wouldn't be a problem for most videos.
There's no need to feel unsettled in the least, so I'm closing this as a *won't fix*.
If any of the other members of the team would like to overturn this decision, they are free to do so.

**Comment by rjdg14** [comment]
Okay, fair enough. I know it would be quite easy to implement such a feature (maybe in the form of a "hide buttons under video" option) as these 4 buttons seem about the only thing which can't be hidden.

I'd agree that it's not a direct download - clicking on one of the options redirects you to an MP4 file on one of Google's servers in your default browser, and you would then have to right click to save the video. A direct download would probably be performed directly through the client, which FreeTube doesn't do.
