### ISSUE TITLE
Seperate Subscriptions for Each Profile

### ISSUE THREAD

**Issue by ShawnNogi** [FreeTubeApp/FreeTube#1309]
**Behavior of the program**
Adding or Deleting Channel Subscriptions applies it to every profile.

**Expected behavior**
Profiles are independent

**To Reproduce**
Subscribe to a channel or delete a channel and check other profiles to reproduce.

**Environment Information
v0.13.0 Beta
Windows 10

**Comment by GilgusMaximus** [comment]
You can remove channels from profiles via the profile manager. The channel must always be in the allchannels profile tho, as this is our basis for creating the profiles

**Comment by ShawnNogi** [comment]
> You can remove channels from profiles via the profile manager. The channel must always be in the allchannels profile tho, as this is our basis for creating the profiles

@GilgusMaximus 

I see. Would it make more sense to make the main profile invisible to the user and make them make a new profiel from the beginning . This confused me.

**Comment by GilgusMaximus** [comment]
Not really. We want the user to be able to view all channels he subscribed to. Also you can make other profiles the default so that they show up when you open the application.
