### ISSUE TITLE
Window title in English for all locales

### ISSUE THREAD

**Issue by ovari** [FreeTubeApp/FreeTube#1310]
**Behavior of the program**
Window title is in English, even though the language is set as `System Default` which is currently in Hungarian.

**Expected behavior**
`About - FreeTube` should be `Névjegy - FreeTube`.

`Subscriptions`, `User Playlists`, `History`, `Settings` also show in English in the window title instead of the `System Default` which is currently `Hungarian`.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Change the Language to anything other than English.

**Screenshots**
![kép](https://user-images.githubusercontent.com/17465872/119212181-fbdb2c00-baf9-11eb-8907-ac05837e382b.png)

**Environment Information:**
 - OS: Linux Mint
 - OS Version: Linux Mint 20.1 Cinnamon
 - FreeTube version: 0.13.0 Beta
 - Installation Method: FlatHub
 - Primary API Used: Not sure

Thank you

**Comment by ChunkyProgrammer** [comment]
Looks like it has to do with the "title" attribute being hardcoded here https://github.com/FreeTubeApp/FreeTube/blob/c8f6d4721a413403bf2fe4dac7d29291b71d25fb/src/renderer/router/index.js 
I can work on this issue
