### ISSUE TITLE
A whole bunch of improvements and suggestions

### ISSUE THREAD

**Issue by shakeyourbunny** [FreeTubeApp/FreeTube#1312]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
There are several things to suggest:
**Icons**
Square Icons: I'd really like to have an option to switch to square icons for the channels. Round icons irritate the living things out of me.

** General **
- allow a switch between square / round icons.
- enable a search / filter box where applicable: subscriptions, playlists, history, channel, (list of subscriptions), subscription manager
- make a toggle grid (icon) / list mode in subscriptions, playlists, history, channel, list of subscriptions, subscription manager

** Video Player **
- the "Up next Box" is too wide, there should be a button / ribbon to fold it to the right and back (I don not mean theater mode functionality)
- switch the icons in the lower right corner between text and symbols 
- the description box should always display the whole description and not cut off if it is longer than normal (eg PBS Spacetime channel)

** Log **
Have a button for opening the log with the true error messages.

**Comment by PrestonN** [comment]
Please make a separate ticket for each issue / feature request. It's much harder for us to track each request when they're piled on together like this.
