### ISSUE TITLE
When right of text is clicked, the search bar should not select all.

### ISSUE THREAD

**Issue by peepopoggers** [FreeTubeApp/FreeTube#1313]
When the search bar is clicked (when it has text in it), it selects all when you click on the text as it should. However, when clicking on the right of the text, it still selects all, when it would be better to navigate cursor to far right.

Example:
![image](https://user-images.githubusercontent.com/72892531/119241987-4b4d4680-bb52-11eb-86a7-136fd94e1ea5.png)
Should be:
![image](https://user-images.githubusercontent.com/72892531/119241993-556f4500-bb52-11eb-8c8b-41a8b32e5e7b.png)

However, when text itself is clicked, it should still be like this:
![image](https://user-images.githubusercontent.com/72892531/119242019-7d5ea880-bb52-11eb-86d9-6b950fdb27f7.png)

**Comment by Svallinn** [comment]
I'm confident enough to say that that kind of fine-grained behavior isn't possible to implemented.
If someone finds a way to do so, they can comment here and all reopen this if it truly works.

**Comment by peepopoggers** [comment]
@Svallinn Check out youtube search - it is like this

**Comment by GilgusMaximus** [comment]
You can do it, but this behaviour is completely subjective. Depending on the application / website you are coming from, this behaviour can be our way or your suggested way. And adding the additional complexity is really not worth it in such a subjective behaviour.

**Comment by Svallinn** [comment]
No, it isn't.
It doesn't automatically select all text when you click on top of it.

**Comment by peepopoggers** [comment]
You are missing the issue. its not meant to select all when you click to the right of it

**Comment by peepopoggers** [comment]
> > Check out youtube search - it is like this
> 
> No, it isn't.
> I just went to YouTube to check and it doesn't automatically select all text when you click on top of it.

strange, same for me now. i feel like this behavior makes editing annoying at most. You could add an - X - button to delete all if wanted
