### ISSUE TITLE
Import subscriptions file picker dialog filters the wrong file types

### ISSUE THREAD

**Issue by glubsy** [FreeTubeApp/FreeTube#1316]
**Behavior of the program**
When choosing to import subscriptions as .json or .opml, the modal file picker dialog window does not show any .json or .opml in the file list representation of the file system. Only .db files ("Database File") are selectable. 

**Expected behavior**
Files with extensions other than .db should be displayed and selectable for import.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to Settings -> Data Settings
2. Click on 'Import subscriptions' or 'Export subscriptions'
3. Click any button ***other than*** 'Import/Export Freetube (.db)'
4. The modal file picker dialog shows up but filters by file type "Database File" (.db) and does not show .json, .opml files (only .db files)

The import still works fine by renaming files to be imported as ".db" but it is a bit inconvenient. 

**Environment Information (please complete the following information):**
 - OS: Arch Linux
 - FreeTube version: 0.13.0 beta
 - Installation Method (If applicable): from the AUR (freetube-bin package)

**Additional context**
I suppose the patch should be applied around [these lines](https://github.com/FreeTubeApp/FreeTube/blob/6ccc7e9fa428199d9cc3f95aad7a5b82dcae1932/src/renderer/components/data-settings/data-settings.js#L217). Probably need to include more extensions.

**Comment by GilgusMaximus** [comment]
Closing as this is not a issue that is occurring. 

You are most likely missing the file extension on the actual file.

**Comment by glubsy** [comment]
My bad, you are correct. Sorry for the noise!

**Comment by GilgusMaximus** [comment]
Np, weird behaviour of other applications that they do not add that tbh.
