### ISSUE TITLE
Remove spellchecking for search

### ISSUE THREAD

**Issue by peepopoggers** [FreeTubeApp/FreeTube#1317]
Spellchecking is not needed as most things people will search will not be words, but names/nicknames.

Example:
![image](https://user-images.githubusercontent.com/72892531/119257284-79677080-bbbc-11eb-8f7d-b46073a7910a.png)

Can be removed  with 
spellcheck="false" in html element.

Fix:
![image](https://user-images.githubusercontent.com/72892531/119257321-a0be3d80-bbbc-11eb-9c60-5ad02d0a8948.png)

**Comment by peepopoggers** [comment]
btw, not really sure how this works, but would probably be an edit here in `src/renderer/components/top-nav.vue`
here:
![image](https://user-images.githubusercontent.com/72892531/119257453-322daf80-bbbd-11eb-88da-6595bc57afce.png)
with `:spellcheck = "false"` or something
but I am not sure how project is structured

**Comment by PikachuEXE** [comment]
@peepopoggers 
See #1346

**Comment by peepopoggers** [comment]
@PikachuEXE <<<3333

**Comment by peepopoggers** [comment]
if #1346 is accepted, this will be closed.

**Comment by peepopoggers** [comment]
Not pulled yet :L

**Comment by PikachuEXE** [comment]
@peepopoggers 
#1346 merged now

**Comment by peepopoggers** [comment]
:+1:
