### ISSUE TITLE
Subscribtion Layout+ Hide videos in subs

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#132]
Would it be possible to change the subscription layout to a grid instead of a list and also hide videos within the subscriptions tab?

**Comment by PrestonN** [comment]
This is actually something that I've had planned for a while.  Some of the behind the scenes stuff that I've been working on will make this possible.  This will also open up any other layouts that can be unique to FreeTube.

It sounds like you want a sort of blacklisting feature for videos.  In that case the issue for tracking is at #95.

**Comment by grrrrr** [comment]
@PrestonN do you plan on it being a user choice whether grid or list gets displayed?

**Comment by PrestonN** [comment]
Of course.  I don't know why I wouldn't.  Users would end up having a choice between grid, list, or any other layout that might be added.

**Comment by PrestonN** [comment]
Both of these requests are currently in the live release, so I will go ahead and close this issue.
