### ISSUE TITLE
Playlist: Fullwindow icon dissepears because of fullscreen 

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1327]
**Behavior of the program**
So the normal behavior is that when u go into fullscreen that the fullwindow button disappears. However when u are in a playlist watching a video in fullscreen and it skips to the next video. It will out of fullscreen but it doesnt show the fullwindow icon.

**Expected behavior**
When player is out of fullscreen the fullwindow icon must appear.

**To Reproduce**
Please see video.

**Link to video**

https://user-images.githubusercontent.com/73130443/119551917-acab2a80-bd89-11eb-80c7-efb1bf4c3962.mp4

**Screenshots**
None.

**Environment Information (please complete the following information):**
 - OS: [Win 10]
 - OS Version: [20h2]
 - FreeTube version: [v0.13.0-nightly-857 Beta]
 - Installation Method (If applicable): [Portable]
 - Primary API Used: [Local API]

**Additional context**
None.

**Comment by GilgusMaximus** [comment]
This is intended behaviour. As you cannot go from fullscreen to full window, it does not make sense to offer this option

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@GilgusMaximus I think u get me wrong. I know it is intended behavior that the fullwindow icon disappears when u are in fullscreen. But in this issue u from the 10th second of my clip u see that autoplay skips it to the next video. It goes out of fullscreen but the fullwindow icon does not come back.

**Comment by GilgusMaximus** [comment]
Yes that is true. But we can keep this closed, as the icon will reappear when you go into fullscreen and then out again. And as staying in fullscreen for autoplay is a request, this would not impact the actual usecase. But good catch that this happens. Never thought of this

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah that makes sense. Thanks for ur explanation :)
