### ISSUE TITLE
Video doesnt stay muted when autoplay is enabled

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1328]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
When u mute a video and it skips to the next video when autoplay is enabled, the video will get unmuted.

**Describe the solution you'd like to see implemented**
Remember the muted state. 

**Describe alternatives you've considered**
None.

**Video**

https://user-images.githubusercontent.com/73130443/119553032-b84b2100-bd8a-11eb-8e44-903c83d74a6c.mp4

**Additional context**
When turning the volume down to mute manually this doesn't happen. 

https://user-images.githubusercontent.com/73130443/119553142-e16bb180-bd8a-11eb-868f-cae11c82088b.mp4

**Comment by PikachuEXE** [comment]
See #1352 
@efb4f5ff-1298-471a-8973-3d47447115dc

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
just a quick question about this.

If autoplay is not enabled and i just mute a video in the way shown in my first example video will it still get enforced if i go to another random video?

**Comment by PikachuEXE** [comment]
Yes.
It's supposed to remember your last updated volume.
But there was a bug so that making the player muted does not make it remember.
"Remember your last updated volume" works for all video transitions, manual or autoplay.
