### ISSUE TITLE
Show amount of comment replies 

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1329]
**Is your feature request related to a usage problem (not a bug)? Please describe.**

So when u press on "View replies" on an comment that has allot of replies it will show u an X amount of replies. U scroll down a bit and there are more replies so u click on "Show more replies". It would be nice to have something like this.

"Show more replies 30 / 60"

Now the user know how many replies there still are and how many replies he already saw. I think this will be a good feature because there can be really interesting discussions in the comment section, but can also be really exhausting if there is allot to cover and u dont really know where the end is.

**Describe the solution you'd like to see implemented**
Implement an indicator for how many comments are loaded and are still to be loaded.

"Show more replies 30 / 60"

**Describe alternatives you've considered**
None.

**Screenshots**
None.

**Additional context**
None.

**Comment by GilgusMaximus** [comment]
This is not possible. We wanted this feature since the beginning, but the way YouTube's comment hook works, it does not provide the total amount of comments on a video

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lol just noticed this is a duplicate of my own issue #780
