### ISSUE TITLE
Show Live videos in the up next section

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1331]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
In regular YT live videos are being shown in the up next section but in Freetube not.

**Describe the solution you'd like to see implemented**
Implement live videos into the up next section.

**Describe alternatives you've considered**
None.

**Screenshots**
None.

**Additional context**
None

**Comment by GilgusMaximus** [comment]
Same as #1330

**Comment by GilgusMaximus** [comment]
Yeah all good. I am just marking this as 'Same, checking this.' Sorry for the confusion

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not an issue anymore.
