### ISSUE TITLE
Show topic playlist when searching

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1333]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
On youtube when u search for something (could be anything) it could show u a topic playlist created by YT. This isnt being shown in the search page in freetube.

**Describe the solution you'd like to see implemented**
Implement topic playlists from youtube in the search page.

**Describe alternatives you've considered**
None. 

**Screenshots**
None. 

**Additional context**
None.

**Comment by GilgusMaximus** [comment]
These playlists are not available to us
