### ISSUE TITLE
Go to channel from playlist page

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1334]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
At this moment it is not possible to go to the channel page from the playlist page.

**Describe the solution you'd like to see implemented**
Click on channel icon or name of the creator of the playlist to go to the channel page.

**Describe alternatives you've considered**
None.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/73130443/119561994-60fe7e00-bd95-11eb-8103-0ed5a58e18fe.PNG)

**Additional context**
Added a screen for the people that are not sure with what i mean with playlist page.

**Comment by PikachuEXE** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
See #1347

**Comment by jasonhenriquez** [comment]
It looks like #1347 has successfully implemented this behavior.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ur right i'll close this one.
