### ISSUE TITLE
Unable to see "share playlist" dropdown field in playlist page

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1336]
**Behavior of the program**
When a description of a playlist is too long the dropdown will be pushed out of reach.

**Expected behavior**
The dropdown should not be pushed out of reach because of the description. 

**To Reproduce**
See video.

**Link to video**

https://user-images.githubusercontent.com/73130443/119563478-1ed63c00-bd97-11eb-9829-2ad91311f05c.mp4

**Screenshots**
None.

Environment Information (please complete the following information):

    OS: [Win 10]
    OS Version: [20h2]
    FreeTube version: [v0.13.0-nightly-857 Beta]
    Installation Method (If applicable): [Portable]
    Primary API Used: [Local API]

Additional context
There maybe need to be a scroll bar implemented or something like "show more". see screen.
![Capture](https://user-images.githubusercontent.com/73130443/119563867-9f953800-bd97-11eb-9c4d-18fa3341d7d6.PNG)

**Comment by GilgusMaximus** [comment]
Note: Depends on screen / window height

**Comment by PikachuEXE** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
Care to share a few URLs of those playlists with long description?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> 
> 
> @efb4f5ff-1298-471a-8973-3d47447115dc
> Care to share a few URLs of those playlists with long description?

ofcourse :) here u go.

https://www.youtube.com/playlist?list=PL3-sRm8xAzY-556lOpSGH6wVzyofoGpzU
https://www.youtube.com/playlist?list=PL3-sRm8xAzY9sDilvaWjCwCI0TkUzYdOG

**Comment by PikachuEXE** [comment]
Not sure if #1358 can solve this issue...

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I think if u still can see all the options when u hover over "Share playlist", then it must be ok.

**Comment by PikachuEXE** [comment]
I think it really depends on the height
(I am too lazy to create an adaptive style for short heights...)
![image](https://user-images.githubusercontent.com/1018543/119962751-f4c08c00-bfd9-11eb-9458-73c5e58ad64e.png)
