### ISSUE TITLE
Apply search filter realtime after u searched for a something

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1338]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
In my opinion it would enhance the user experience when u apply a filter immediately when u click on it. The user can immediately asses the situation to see if they got the expected results. If not the user can remove the filter or add another filter to get the preferred results.

At the moment Freetube's implementation is like this. 
Freetube's input search terms > see results > apply filters > _**click on search box** >  **press enter to search**_ > see results

Possible future implementation.
input search terms >  press enter to search > apply filters and the page will get refreshed with the filters immediately. 

If u compare both you'll see that two step are not necessary anymore, but those two steps are crucial in my option to enhance user experience. 
U dont want the user to click on the search box and press enter or click on the search button all the time when they cant find something they want.

**Describe the solution you'd like to see implemented**
This would remove the filter icon from everywhere but the search page. Apply search filters after u click on them.

**Describe alternatives you've considered**
None.

**Video**

https://user-images.githubusercontent.com/73130443/119568372-f5b8aa00-bd9c-11eb-9aab-891ad8a2095a.mp4

**Additional context**
None.

**Comment by GilgusMaximus** [comment]
The problem with this is that we want to reduce traffic and requests to YouTube as much as possible. When you directly press on the search filter, that would fire a new search. So if you click a bit around you could potentially run into rate limiting rather quickly.

But I can see this added as a setting. If someone gets rate limited, then it is their own fault. So adding a help box next to the setting to make this clear will be required for a merge.

**Comment by PrestonN** [comment]
If the YouTube site itself does this then I'd be comfortable with the extra amount of requests going to them when it comes to rate limiting. The site itself would be making the same requests that we'd be making so there shouldn't be any problems with rate limiting in this regards. Having said this, we should still monitor it if implemented this way and see if it causes any problems. If so, then I'd prefer if the functionality stayed the way it is currently.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I dont see this request as viable anymore. Our current way of doing it allows the user to makes changes before applying and I think thats a good thing instead off making a request everytime a filter is applied
