### ISSUE TITLE
Any plans on bringing this to the iOS/Mac platform

### ISSUE THREAD

**Issue by HairyMilkshakes** [FreeTubeApp/FreeTube#134]
Hello,

Per title as I couldn't find an answer in the wiki/info page. Thanks!

**Comment by grrrrr** [comment]
There is a MacOS version already.  Take a look at FreeTube-darwin on the [releases] page(https://github.com/FreeTubeApp/FreeTube/releases)

**Comment by HairyMilkshakes** [comment]
Gotcha. Thanks!
