### ISSUE TITLE
Playlist page: Click on playlist thumbnail to watch all videos

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1340]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
The only way to start to watch the playlist from video one is to click on the first video in the list. There are playlists that are very long, so this would mean that when u are scrolling through the list and decided u like the content of the list, u need to scroll all the way up to start the playlist from the beginning. 

**Describe the solution you'd like to see implemented**
Click on the thumbnail of the playlist to start the playlist from the beginning. 

**Describe alternatives you've considered**
None.

**Screenshots**
![Screenshot (207)](https://user-images.githubusercontent.com/73130443/119575593-d32b8e80-bda6-11eb-848b-ac01fbea5512.png)

**Additional context**
None.

**Comment by PikachuEXE** [comment]
See #1361

**Comment by jasonhenriquez** [comment]
Looks like #1361 solves this.
