### ISSUE TITLE
[Feature request] Search bar needs a checkbox to search ONLY in subscriptions.

### ISSUE THREAD

**Issue by cocoonkid** [FreeTubeApp/FreeTube#1345]
### Please describe clear and concise of what the problem is. Ex. I'm always frustrated when [...]
---
I've a very narrow scope with my subs so when I search videos about a specific topic I'd like to have only results within my subscribed channels.
Having results returned from all of yt makes it very hard to do video research.
----
---
This would be an immense value-add for UX.
---
### **Describe the solution you'd like to see implemented**
---
A checkbox in the filter box to enable searching scoped to only subscriptions. This should be remembered over restarts.
---

**Comment by GilgusMaximus** [comment]
So, first of all, please use the issue template. It is there for a reason. 

Secondly, there is currently no way to implement that without the risk of rate limiting you instantly. If you load your let's say roughly 120 subs and then search for something in them and load 120 subs again and again, then you hit the rate limit instantly.

So sorry for that but that is currently not possible

**Comment by cocoonkid** [comment]
My apology. Considering this is a feature request and not an Issue I thought I don't need to use it.

On another note, wouldn't it be possible to just cache the titles of all playlist items temporary and just search through these with a filter?

I cannot currently see where the technical problem would be. But maybe I'm just ignorant :-)


Looking forward to a second check of the request.

**Comment by GilgusMaximus** [comment]
Well the only option we have would be to send a long search request with specifically all the subscribed channels as filters. This might work, although I am not so sure whether there is a limit to what YouTube allows. 

So it might be possible but it definitely is open to testing. if you want to open this feature request, please open a new issue with the template in use

**Comment by cocoonkid** [comment]
@GilgusMaximus  Thanks for the reply.

I will reopen the issue with the template after clearing a few more questions here okay?

I am not sure , probably I posed the question wrong.

I mean within my playlist  which is already in freetubes UI and within my subscriptions which are also already loaded, it would be really helpful to have a fuzzy search or a filter with a scope of ONLY these.
There doesn't have to be a a single request sent to youtube.


But right now it does always and only search on youtube again. Which I don't want, I have my favorites already in my playlist or subscription list. I only want to fuzz through their titles and maybe have a filter set before to only search from specific groups of subscriptions. BUT always search in the data that already exist. don't search youtube again.

If I phrased the feature request better now please let me know and I will create the request again with proper templating.

please lmk :-)

**Comment by cocoonkid** [comment]
I think this could even remove about 10-20% of "useless" requests going to various invidious instances.

**Comment by GilgusMaximus** [comment]
Search for playlists will come once playlists have their full implementation. The subscription page is only a small page of a few videos, adding a search there is a bit of an overkill imo
