### ISSUE TITLE
FreeTube 0.3.1 issues starting up

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#135]
As of about an hour ago I have started experiencing trouble starting up FreeTube 0.3.1 on Debian 0.9.4

I am noticing two things

1)  If it loads up as expected with all my subscriptions and dark theme set up it very quickly crashes

2) After 1, starting FreeTube results in it starting up for the first time but gets stuck on a pulsing icon on the subscription page and you can not select any of the other options.  Closing and reopening will result in either repeating this error or goes back to the error in 1 above

Removing ~/.conf/FreeTube and starting the program again results in it instantly quitting

**Comment by PrestonN** [comment]
I haven't heard of this issue so it's definitely strange.  However I'm not sure if deleting the config contents helped.  I would try to re-install it completely and if that doesn't work then we can delve deeper into this.

**Comment by grrrrr** [comment]
@PrestonN Appologies this was completely user error, I did not notice my disk was 100% full and that was what was causing the weird behavior.    I'll go ahead and close this and hang my head in shame
