### ISSUE TITLE
Playlist page: No user feedback on copy link

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1351]
**Behavior of the program**
On the playlist page when u go to share playlist and click on copy youtube/invidous link, the link will get copied, but the user doesn't get user feedback like the link has been copied.

**Expected behavior**
Receive the notification that the link has been copied.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to https://youtube.com/playlist?list=PLy6N_9yB8Qwy6LL0J7zLUyW8XNX-BPeDl
2. Hover above share playlist
3. Click on copy youtube/invidous link
4. No user feedback but u do get the link

**Link to video**

https://user-images.githubusercontent.com/73130443/119911710-5ab10300-bf49-11eb-9435-b2104ce6f06c.mp4

**Screenshots**
None.

**Environment Information (please complete the following information):**

- OS: [Win 10]
- OS Version: [20h2]
- FreeTube version: [v0.13.0-nightly-859 Beta]
- Installation Method (If applicable): [Portable]
- Primary API Used: [Local API]

**Additional context**
None.

**Comment by GilgusMaximus** [comment]
Well, the playlists are probably the part that has gotten the least love as it seems ^^'

Thanks for catching this. As this is rather easy to do, I'd welcome any new contributors to try this. If someone has any questions, feel free to ask

**Comment by no-comma** [comment]
I'm going to open a PR for this.
