### ISSUE TITLE
Featured Channels need own section like on yt

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1355]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
At the moment the Featured channels are just getting dumped in the about section.

**Describe the solution you'd like to see implemented**
It would be nice if they get their own tab just like on yt.

**Describe alternatives you've considered**
None.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/73130443/119922940-5512e780-bf60-11eb-8a02-c1768dfd57d5.PNG)

**Additional context**
None.

**Comment by GilgusMaximus** [comment]
Good point. We'll have to see how it will look in the future.

**Important**
Please do not implement this yet tho. Once I am done with all the PR's I want to get the community page done and I really do not want to have even more merge conflicts than I already have

**Comment by hollownights** [comment]
The Channels tab is a great way to discover new channels but also a great way to analyze what kind of channel you're interacting with right now. Definitely should be added.

**Comment by absidue** [comment]
Looks like YouRube removed the `Channels` tab on their end, thankfully because we scrape them from the home tab our stuff still works.

https://github.com/TeamNewPipe/NewPipeExtractor/pull/1127

**Comment by jasonhenriquez** [comment]
Safe to close then?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
YT moved this to the home page so i think its safe to close
