### ISSUE TITLE
Age restricted videos don't work anymore

### ISSUE THREAD

**Issue by Vocaloidfan2001** [FreeTubeApp/FreeTube#1368]
Age restricted videos do not work anymore, local and invidious API error occured

**Comment by arrowgent** [comment]
youtube api changed in april

youtube-dl & yt-dlc etc have the same issue


i dont think there is a way around it without providing cookie credentials

**Comment by Absolute-Arthur** [comment]
The problem just occured for me, yeah a Google account is needed for this kind of video.

Would it be possible to at least explain the problem on FreeTube when it occurs (instead of having an ambiguous "API error") and provide a link to YouTube for those who want?

**Comment by PrestonN** [comment]
Fix is already available. New release this weekend to push out to everyone.
