### ISSUE TITLE
No 4k, outside app can help

### ISSUE THREAD

**Issue by raygamerkt** [FreeTubeApp/FreeTube#1376]
Since no 1080+ resolutions video.js issue, and no hope for upgrade, this great app should consider at least small step for modern resolutions. Maybe another lib? I know too much changes, too long to develop :) ok, serious. Can You add one small feature making life easier and add possibility run youtube url in another program so I can just use dropdown menu and run that url in mpv player and watch 4k video? Now must copy YT url then open terminal and type mpv url. Just one click action will make dream come true, thx

**Comment by GilgusMaximus** [comment]
Well we provide 4k on some videos where mp4 4k is available.
It was mentioned that the plugin we use for VideoJs will support webm at some point in the future https://github.com/videojs/http-streaming/issues/970, but these guys are also busy and supporting a new video format is probably not so easy.

For now we will stick to VideoJS as we have so much other stuff to do and at some point in the future we also want to go for the v1.0 release. So messing around with it again is at least at the moment not an option. Sorry for that.

Best Regards,
Gilgus
