### ISSUE TITLE
Stuck on this Screen. Published on Jan 01, 1970

### ISSUE THREAD

**Issue by Schwarzeisc00l** [FreeTubeApp/FreeTube#1377]
![image](https://user-images.githubusercontent.com/78359804/120230981-18ddd080-c259-11eb-91ce-c0341ed21773.png)

**Comment by ChunkyProgrammer** [comment]
Do you remember how you got to that screen?

**Comment by Schwarzeisc00l** [comment]
> Do you remember how you got to that screen?

Any video i click. I did nothing and a proxy is not working.

**Comment by ChunkyProgrammer** [comment]
Ok, I can reproduce it. Your proxy is not set up correctly.

![image](https://user-images.githubusercontent.com/78101139/120232345-63435b00-c221-11eb-8c41-7949fc00bc80.png)

Does it ask if your proxy is set up correctly when you click "Test Proxy"?

**Comment by Schwarzeisc00l** [comment]
> Ok, I can reproduce it. I don't think your proxy is set up correctly.
> 
> ![image](https://user-images.githubusercontent.com/78101139/120232345-63435b00-c221-11eb-8c41-7949fc00bc80.png)
> 
> Does it ask if your proxy "is set up correctly?" when you click "Test Proxy"?

Is it related with me using a vpn?

**Comment by ChunkyProgrammer** [comment]
I think it's because you don't have a tor running on that port. Tor isn't built into FreeTube so you'd have to install Tor and set it up as a SOCKS5 proxy

**Comment by GilgusMaximus** [comment]
@Schwarzeisc00l please open a new issue and fill out the template for bug issues correctly. We have 0 information on what is happening and what your setup is, so I ask you to provide information in a new issue.

Thanks.
Best Regards,
Gilgus
