### ISSUE TITLE
Run with system version of Electron

### ISSUE THREAD

**Issue by Daystar1998** [FreeTubeApp/FreeTube#1378]
Per the [Arch Wiki](https://wiki.archlinux.org/title/Electron_package_guidelines) it is possible to run FreeTube or other Electron apps on Linux with the system version of Electron using a shell script.
```
#!/bin/sh
exec electron /path/to/appname/ "$@"
```
A working example for the [AUR download](https://aur.archlinux.org/packages/freetube-bin/):
```
#!/bin/sh
exec electron /opt/FreeTube/resources/app.asar "$@"
```

**Comment by GilgusMaximus** [comment]
While the concept is nice, this is probably not a very good idea. 
We had so many different problems with different Electron versions in the past that we really want to avoid anything that will interfere with that again. And if some dependencies break then this is not working anyways and the majority of people probably does not even have the option to enable this.

So if you specifically want to have this, I would suggest that you build FreeTube yourself. 

Best Regards,
Gilgus
