### ISSUE TITLE
add a "watched" indicator to videios on subscription section

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#138]
While the history section can be a little useful to have, I would like to suggest adding some form of indicator that a video in the subscription view.   At least for me my memory is terrible and remembering what I've watched from a long long list can be hard, having this indicator/mark/tag on the subscription page would be very helpful

**Comment by PrestonN** [comment]
This is easily doable.  However this won't be available to users who end up disabling their history so that has to be kept in mind.

**Comment by PrestonN** [comment]
This has been done.  Expect to see this in the next release.
