### ISSUE TITLE
Add Video Quality Setting To Be Changed Within Video UI

### ISSUE THREAD

**Issue by BrainstormSurge** [FreeTubeApp/FreeTube#1381]
Could put it next to the playback speed video interface. Very nicely implemented UI for that by the way. 

Could probably adapt said playback speed UI in that you hover over the video quality icon for a popup menu and you can switch to different video quality from there.

**Comment by GilgusMaximus** [comment]
This is already implemented?
![image](https://user-images.githubusercontent.com/34301369/120469684-f8219200-c3a2-11eb-9345-3307614dd4e2.png)

**Comment by BrainstormSurge** [comment]
You're right. Sorry, only just started using FreeTube. Can't see the forest through the trees I guess.
