### ISSUE TITLE
Foward & Rewind Not Working In PIP Mode

### ISSUE THREAD

**Issue by BrainstormSurge** [FreeTubeApp/FreeTube#1382]
This is of course referring to the rewind and forward done when pressing either the J or L key or the Left-Arrow or Right-Arrow key.

Not sure if both modes are being effected by the same bug but if so solving one could solve the other or at least help solve the other.

**Comment by GilgusMaximus** [comment]
They work in full-screen. You might have to click into the video again. Sometimes the app does not set the focus correctly. See #766 

For pip, we are not actively supporting this feature as it is the complete wild west. If someone wants to try this, first have to check whether it is possible at all, then we welcome any PRs. But otherwise this is not going to be implemented by us.

**Comment by BrainstormSurge** [comment]
> They work in full-screen. You might have to click into the video again. Sometimes the app does not set the focus correctly. See #766
> 
> For pip, we are not actively supporting this feature as it is the complete wild west. If someone wants to try this, first have to check whether it is possible at all, then we welcome any PRs. But otherwise this is not going to be implemented by us.

I just tested full-screen again with what you suggested. What's interesting is that Forward and Rewind will not work again for full-screen if you press the play/pause button in the bottom-left. However, it will if you click on the video screen itself to pause and play.

As for a website that you can Forward/Rewind in PIP mode you can check out BitChute.

**Comment by GilgusMaximus** [comment]
What OS are you on? If it is Linux please also specify DE and WM. We have several issues with different setups that are related to Electron.

If keyboard events are available in pip and someone wants to do that, go for it. But we are quite hesitant to put a lot of work in a feature that can change at any time with a new version and that has no defined standard.

**Comment by hollunder** [comment]
Wait, how can you say you are not supporting PIP if you have a button for exactly that in the playback controls?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please provide the additional information requested before
