### ISSUE TITLE
Add Forward & Rewind Customization In Settings

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#1383]
This is of course referring to the rewind and forward done when pressing either the J or L key or the Left-Arrow or Right-Arrow key.

Please add a section in Settings where you can change how long of a time-skip the Forward or Rewind is such as 5, 10, 15 and so on.

**Comment by jasonhenriquez** [comment]
I can work on this!

**Comment by GilgusMaximus** [comment]
Thanks for taking on this.
If you need some help, feel free to ask
