### ISSUE TITLE
Video doesn't start, shows 0 views, then moves to history as watched.

### ISSUE THREAD

**Issue by ChattyMatty** [FreeTubeApp/FreeTube#1384]
Error status code 429.

I click on a video to play, loads new video page, video is normal size, then blips to a thin bar about 1/4 size, time goes to 0, total views goes to 0, and then the video gets moved to history as if I watched it. The thumbnail shows in history as it should, but with 0 minutes/0 views. Rebooting sometimes helps, but often only for the first video played after rebooting. Really intermittent, doesn't happen all the time, but enough that I reboot several times a day trying to fix it.

Windows 10; i5 8600; 5700XT

**Comment by ChunkyProgrammer** [comment]
That's a "too many requests" error. Are you using a vpn/proxy?

**Comment by ChattyMatty** [comment]
Why yes, yes I am. Didn't think the try the simplest fix possible lol. I'll give that a whirl next time it happens, thanks.
