### ISSUE TITLE
Fetching more results yields `Local API Error` on Deb10

### ISSUE THREAD

**Issue by oakenduck** [FreeTubeApp/FreeTube#1385]
On opening the application, I go to Trending, and see no results; going to the Most Popular page, I do get results. On searching, I get zero results, and the `Fetch more results` option. Clicking it results in nothing except the popup stating `Local API Error: invalid continuation array`.

- OS: Debian
- Version: 10 (Buster)
- Client version: `v0.13.1 Beta`
- installation Method: FlatPak web store, then System Handler
- Primary API: invidious or local, same result.

This occurred right after installing and launching. It works well on my windows machine, that's why I'm trying it out on this media server as well.

**Comment by GilgusMaximus** [comment]
Can confirm that everything is working on windows. Again...

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi is this still an issue for u?
