### ISSUE TITLE
Looking at comments on a video with no comments shows an error

### ISSUE THREAD

**Issue by Absolute-Arthur** [FreeTubeApp/FreeTube#1386]
**Behavior of the program**
On a video with 0 comments, clicking on "Click to View Comments" shows the following API error:

Local API Error (Click to copy): TypeError: Cannot read property 'forEach' of undefined
Falling back to Invidious API
Invidious API Error (Click to copy): undefined

**Expected behavior**
I don't know. If something isn't already made, we could have one of the following:
- A less ambiguous toast message (ex: "There are no comments on this video")
- At the place of the list of comments, have a text explaining "No comments" or "0 comments"
- Simply show "No comments" instead of the "Click to View Comments" button when loading the page

**To Reproduce**
1. Go to a video with 0 comments on YouTube
2. Click on "Click to View Comments"
3. See error

**Link to video**
An example of a random videos with no comments (if you have trouble finding one):
https://www.youtube.com/watch?v=Bj-3M-KqZsI
https://www.youtube.com/watch?v=TGU0ln71jMk

**Screenshots**
![image](https://user-images.githubusercontent.com/61556875/120547372-4fe6ea00-c3f1-11eb-8b25-ea251a4bd46a.png)

**Environment Information:**
 - OS: Windows
 - OS Version: Windows 10 Family 20H2
 - FreeTube version: v0.13.1 Bêta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Additional context**
None

**Comment by ChunkyProgrammer** [comment]
I can fix this one
