### ISSUE TITLE
Little (x) Button To Quickly Clear Search Bar Of Text

### ISSUE THREAD

**Issue by BrainstormSurge** [FreeTubeApp/FreeTube#1387]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Usage. Less clicks means better UI. I've seen similar implementation where clicking the X button (whatever color such as red, black or white) will clear the search text and select the search bar.

One button and you're ready to type in your new search term.

Current way is to click the bar then use Backspace but this can feel annoying after a while compared to what can be done with one click of an X button.

**Describe the solution you'd like to see implemented**
Add an X button that will clear and select the search bar in one action/click. 

Best spot to put it for the current UI would be on the left side of the bar instead of next to the search arrow and filter buttons as that would start to make things cluttered there and would prevent accidental clicks that clear your current search.

--

Possible improvements would to be to add a couple hotkeys. One to clear text function while within the search bar or even while the FreeTube window is selected. The other to quickly navigate from anywhere to the search bar.

Possible clear function default hotkeys: [Ctrl]+[Backspace] or [Ctrl]+[Delete]

Possible hotkey for navigating to the search bar is: [Ctrl]+[Shift]+[F]

(I know hotkeys are not implement yet. These are future possibilities.)

**Describe alternatives you've considered**
Nothing that's as simple to implement or use. Anything more would be clunky.

**Screenshots**
![Searchbar Mockup](https://user-images.githubusercontent.com/26531295/120562327-6b3b0080-c3c3-11eb-8cad-2f09ae12bd93.JPG)

**Additional context**
I realize that #1392 was created as an improvement to mine. I'm no UI designer and only used MS Paint to create my mockup. Feel free to merge the issues if you feel it's applicable while adding anything that's not in the other together.

**Comment by GilgusMaximus** [comment]
Short notice. Please use the template we provide. Otherwise I will start to close your issues without warning.

**Comment by BrainstormSurge** [comment]
Okay. Sorry about that. I'll keep it in mind.

**Comment by PikachuEXE** [comment]
See #1392

**Comment by BrainstormSurge** [comment]
> Short notice. Please use the template we provide. Otherwise I will start to close your issues without warning.

I've updated the main post according to the feature request template.

**Comment by BrainstormSurge** [comment]
> See #1392

Thank you for this. I'm glad it wasn't that difficult to test out.

Nice mustache by the way.
