### ISSUE TITLE
Vids from certain channels not showing up in sub feed?

### ISSUE THREAD

**Issue by PaperOrb** [FreeTubeApp/FreeTube#1388]
I know this is an "issue" on youtube itself, and just recently noticed this in freetube itself. There's no notification bell in freetube, so how do we even go about changing this behavior?

freetube version: 0.13.0 beta appimage on ubuntu 20.04
preferred backend: invidious API, fetching vids via rss feed
all other settings: default

**Comment by ChunkyProgrammer** [comment]
Can you send a link to one of the videos that doesn't show up?

**Comment by PaperOrb** [comment]
> Can you send a link to one of the videos that doesn't show up?
Heya, the videos that won't show up are from JesseCox. I figure there's not much point linking it since none of his vids aside from his most recent one have shown up for me.

**Comment by GilgusMaximus** [comment]
You have to somewhat clear this issue out. Is your title now related to the actual question or not? 

After a quick look, all videos appear on the channel if you go it.

So please clarify this, else I will close this issue

**Comment by PaperOrb** [comment]
> You have to somewhat clear this issue out. Is your title now related to the actual question or not?
> 
> After a quick look, all videos appear on the channel if you go it.
> 
> So please clarify this, else I will close this issue

I edited the title so hopefully that clears up any confusion.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi @PaperOrb are u still experiencing this issue?
