### ISSUE TITLE
Clicking the FreeTube Logo on top left should bring you to the "home" discovery page

### ISSUE THREAD

**Issue by unholyN1** [FreeTubeApp/FreeTube#1391]
Not a bug, but a feature request.  But to emulate youtube's behavior, clicking the logo should redirect to a refreshed home page. This is functionality many people are used to and enjoy.

Youtube itself when you click the logo, brings you to a page where it displays, popular, trending, news, subscribes, movies, music, and lots of other 'discovery' content in an endless scroll list format.

Need a "home" page.

**Comment by GilgusMaximus** [comment]
First of all please use the templates provided to create any issue

Well the home page is the subscription page.

**Comment by ChunkyProgrammer** [comment]
I can do this one

**Comment by unholyN1** [comment]
Ok, apologies for not using the template!~
Yes if that is the case the logo linking to subscription page seems like a good solution.
