### ISSUE TITLE
Basic keyboard shortcuts to control the video player

### ISSUE THREAD

**Issue by hollunder** [FreeTubeApp/FreeTube#1395]
It is difficult to implement keyboard shortcuts worse than Youtube does, but even that is better than none.

Ideally keyboard shortcuts would have sensible defaults and would be configurable.
For a start I would be happy if at least the following would be available.

**Toggle playback (play/pause)**: space
**Toggle fullscreen**: f
This are the standard bindings for audio/video players.

**Volume up**: up arrow
**Volume down**: down arrow
**Skip video forward**: right arrow
**Skip video backward**: left arrow
This is what Youtube does, unless it doesn't. Youtube does something context-sensitive here that I bet no user understands, hence it should not be copied.
The sensible increments for these operations are debatable. I would like 3 dB steps for audio but most users are not familiar with dB, they have been trained to deal with "percent", even though that makes no sense and behaves differently in every application.
As for how much to skip, I'd say 5-10 seconds as a start, but users will likely want skipping by larger increments using a different key binding down the line.

**Comment by GilgusMaximus** [comment]
This is already implemented. All of it.
And the custom intervals will come later and have been requested numerous times already

**Comment by hollunder** [comment]
Funny, when I tried it none of that worked. Now it seems to work.
I also did not find what the shortcuts are or where to change them. Where do I find that?

**Comment by GilgusMaximus** [comment]
You can find them [here](https://docs.freetubeapp.io/usage/keyboard-shortcuts/)

The problem probably was that you did not focus into the video player. We have this issue for quite a while and yeah only thing we can recommend at the moment is to active click into the video if hotkeys should be used

**Comment by hollunder** [comment]
Thanks.
I added my 2c to a ticket describing the focusing issue but unfortunately my reproduction case did not work reliably either.
