### ISSUE TITLE
Emojis are replaced with � in Profile Previews

### ISSUE THREAD

**Issue by josem435** [FreeTubeApp/FreeTube#1396]
**Behavior of the program**
The profile preview gets replaced with a � if an emoji was used at the start of the profile name.

![image](https://user-images.githubusercontent.com/77453282/120892659-4cc54700-c607-11eb-8e8d-7e2c58fe70e1.png)

**Expected behavior**
The emoji to be normally displayed in profile previews. (Shown below is how it looks if you manually 'inspect element' and replace � with the emoji.)

![image](https://user-images.githubusercontent.com/77453282/120892681-623a7100-c607-11eb-854a-09f367e34960.png)

**To Reproduce**
1. Set a profile name to one which contains an emoji as the beginning character.
2. Observe that the � symbol appears in its place as the profile preview.

**Environment Information:**
```
OS: Microsoft Windows 10 Pro
OS Version: 10.0.19042 Build 19042
FreeTube version: Release 0.13.1 Beta
Installation Method: Windows x64 exe
Primary API Used: Local API
```

**Additional context**
It is possible to temporarily replace the � with the emoji by using 'inspect element' (as done above) but it doesn't persist through sessions.

**Comment by GilgusMaximus** [comment]
There was probably an encoding used that does not support emojis.

Definitely an interesting idea to make it look like this. Never thought of that.

**Comment by ChunkyProgrammer** [comment]
Pretty sure it's caused by this https://stackoverflow.com/questions/52526719/javascript-substring-without-splitting-emoji

**Comment by ChunkyProgrammer** [comment]
I can work on this one
