### ISSUE TITLE
Option to download video using a command-line program

### ISSUE THREAD

**Issue by Masacroso** [FreeTubeApp/FreeTube#1397]
This will be a very simple but powerful enhancement: the possibility to download directly a video using a command-line program like youtube-dl.

I use the aforementioned program to download youtube videos, what Im doing now is copying the link of the video using Freetube, then opening a terminal and using youtube-dl to download it. It will be very simple to add an option to directly download a video using some command-line program like youtube-dl.

**Comment by GilgusMaximus** [comment]
Yes that was an idea I added to the discussion in Matrix a few days ago.
I would imagine it fits to the share button on the watch page. 
![image](https://user-images.githubusercontent.com/34301369/120929329-f9c3c080-c6e8-11eb-8018-c7a7438b8b24.png)

Additionally a setting could be used to specify options. 
But I say this right away, a full graphical UI for downloading with yt-dl will not comes as we still plan to use Youtube Dl Material at some point as pointed out in #582

**Comment by Trung0246** [comment]
Hi, can https://github.com/streamlink/streamlink/ be added too alongside with youtube-dl and other command-line application?

**Comment by GilgusMaximus** [comment]
We will settle for one only. Because as mentioned above, we want an actual UI for this, so it is a bit pointless to add all the logic to allow custom clis similar to how custom video players can be added. But which one we add is up for debate. Depends on what is asked more

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/4446
