### ISSUE TITLE
Update dependencies to fix vulnerabilities

### ISSUE THREAD

**Issue by hollunder** [FreeTubeApp/FreeTube#1398]
**To Reproduce**
run `npm audit`
`npm audit fix` or `npm audit fix --force` are not able to resolve these issues.

**Environment Information (please complete the following information):**
 - OS: Arch
 - OS Version: rolling
 - FreeTube version: git

**Additional context**
8 vulnerabilities (1 low, 3 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'app-builder-lib@22.11.4',
npm WARN EBADENGINE   required: { node: '>=14.17.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '7.16.0' }
npm WARN EBADENGINE }

removed 7 packages, and audited 2166 packages in 14s

# npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
fix available via `npm audit fix`
node_modules/axios

markdown  *
Regular Expression Denial of Service - https://npmjs.com/advisories/1330
No fix available
node_modules/markdown

postcss  7.0.0 - 8.2.9
Severity: moderate
Regular Expression Denial of Service - https://npmjs.com/advisories/1693
fix available via `npm audit fix --force`
Will install vue-loader@16.2.0, which is a breaking change
node_modules/@vue/component-compiler-utils/node_modules/postcss
  @vue/component-compiler-utils  >=2.4.0
  Depends on vulnerable versions of postcss
  node_modules/@vue/component-compiler-utils
    vue-loader  15.5.0 - 15.9.7
    Depends on vulnerable versions of @vue/component-compiler-utils
    node_modules/vue-loader

underscore  1.3.2 - 1.12.0
Severity: high
Arbitrary Code Execution - https://npmjs.com/advisories/1674
No fix available
node_modules/binary-search-tree/node_modules/underscore
node_modules/nedb/node_modules/underscore
  binary-search-tree  *
  Depends on vulnerable versions of underscore
  node_modules/binary-search-tree
    nedb  *
    Depends on vulnerable versions of binary-search-tree
    Depends on vulnerable versions of underscore
    node_modules/nedb

**Comment by ChunkyProgrammer** [comment]
There's two drop-in replacements for nedb with security fixes that I'm aware of (i have not tested either).
https://github.com/rmanibus/nedb

https://github.com/yetzt/forked-nedb


https://github.com/louischatriot/nedb/issues/675

**Comment by GilgusMaximus** [comment]
So the problem with axios is that I do not see which module is depending on it. Because it simply shows a long string, which seems to be a hash or something and I cannot see from which module it comes. Because we are not using axios ourselves in FreeTube but only in the other modules.

For the other vulnerabilities, netdb seems to have a fix, but we need to check whether something breaks if we update

**Comment by hollunder** [comment]
One quick search showed me how to answer your question using your tools.

```
$ npm ls axios
freetube@0.13.1
├─┬ youtube-chat@ (git+ssh://git@github.com/IcedCoffeee/youtube-chat.git#3e20049c605e58a9de14c1df6d50cce7ca01d214)
│ └── axios@0.19.2
├─┬ yt-channel-info@2.2.0
│ └── axios@0.21.1
├─┬ yt-comment-scraper@4.0.4
│ └── axios@0.21.1
└─┬ yt-trending-scraper@2.0.0
  └── axios@0.21.1
```

**Comment by Svallinn** [comment]
- Replaced `nedb` package with `nedb-promises` (uses `@seald-io/nedb` internally)
- Replaced `markdown` package with `marked`
- Updated `webpack-dev-server` package to its `next` version (currently `4.0.0-beta3`)
- Forked `youtube-chat` package over to a scope in our control (`@freetube/youtube-chat`), updated the project's dependencies and then replaced it in the project
![image](https://user-images.githubusercontent.com/41585298/122651666-cee65d00-d129-11eb-80ed-fc3b73f24ce7.png)

Closing as solved.
