### ISSUE TITLE
Like button? 

### ISSUE THREAD

**Issue by via80HD** [FreeTubeApp/FreeTube#1399]
Howdy, I'm not sure if this has already been submitted but just in case, I'll put one in due a like button. I always feel bad for not being able to like the videos I watch (since likes help the creator in a way) so having a like button would be awesome. I know this might be impossible t though since the whole purpose is to watch without an account so Im not sure if there would even be a way, just wanted to throw it out there just in case. 👍

Thanks for all the hard work on this beautiful app, it's really appreciated! 🙏

**Comment by GilgusMaximus** [comment]
This is, as you already said, impossible
