### ISSUE TITLE
Enhancement: Ability to select region

### ISSUE THREAD

**Issue by aproposnix** [FreeTubeApp/FreeTube#14]
Currently there's no way to select the region. This results in the "Most Popular" category to not be very relevant (esp., language). 

I'm sure this is already on your to-do list but I'm putting here because it's kind of important. 

P.S. Can you tell me which region the application is coded for by default?  I've looked at the Most Popular list and compared it to YouTube's popular category and it totally doesn't match (tried multiple regions).

**Comment by PrestonN** [comment]
Yep.  This is definitely on the to-do list, but thanks for putting it here so I can track it better.

Something to keep in mind is that the Most Popular section isn't the same as YouTube's "Trending" section.  Whatever ends up on that page will always be different to what FreeTube shows.

The way that the Most Popular section works is that it grabs the most liked videos out of the list of videos that were uploaded in the past 2 days.  This is similar to how SkyTube does their Most Popular section and I used that while I made the feature.  The result is that both apps should show similar results for that section.  I don't believe region determines what gets shown, but I'll play around with it and see if it changes.

As far as I know, the YouTube API has no way of grabbing what's on the "Trending" section, but I could be wrong.  I'll definitely play around with region selection though, as I've seen this requested a couple of times already.

**Comment by Larivact** [comment]
>As far as I know, the YouTube API has no way of grabbing what's on the "Trending" section

https://stackoverflow.com/questions/30475309/get-youtube-trends-v3-country-wise-in-json

**Comment by aproposnix** [comment]
I know that [Minitube](https://github.com/flaviotordini/minitube) (another YouTube viewer) has this functionality.,, so I assume there is a way

I believe you could use the google top **playlists** - Not the trending. 

https://www.youtube.com/playlist?list=PLrEnWoR732-BHrPp_Pm8_VleD68f9s14-

Here's mintube and the Google top playlist (there are other playlists of course) for comparison. 

![selection_009](https://user-images.githubusercontent.com/6204273/37215911-a3b73936-23b9-11e8-9eec-be0806ad8170.png)


![selection_008](https://user-images.githubusercontent.com/6204273/37215918-ac0a5cd0-23b9-11e8-864d-cbac75510122.png)

**Comment by ivanhercaz** [comment]
Although [NewPipe](https://github.com/TeamNewPipe/NewPipe) is an Android app and taking in account that I don't know exactly how this feature should be developed, I would like to suggest you, @PrestonN, to take a look a how it avoid the restrictions by country.

Would be easier to develop a system that avoid this restriction or a system to select the country from where "you watch" the video? I understand that in the first case, what the system should do is: if in the country of origin is blocked, then set another country until the video will be available.

But, as I told you, I can think the theory but I don't know how to apply it :(

**Comment by omarroth** [comment]
The method you described for bypassing region blocks is actually how Invidious works behind the scenes. It cycles through a list of proxies until it finds one with correct info.

There are two issues currently with this approach:
- Quickly determining where a video is unblocked, since YouTube will not provide a list of allowed regions unless you are requesting from one where a video is unblocked
- Finding a list of proxies that consistently work in various regions

**Comment by PrestonN** [comment]
This has been implemented.  The user will be able to select their preferred region for viewing the `Trending` section.  Expect this to be included with the next release.
