### ISSUE TITLE
Groups for Playlists

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#1404]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
The playlist can be pretty long, so a way to add the videos to custom groups would be nice.

**Describe the solution you'd like to see implemented**
Two buttons could be added on top of the playlist page, like `All | Groups`.
- `All` will show all Videos in the list.
- `Groups` will show the groups instead and will offer a possibility to add/remove/edit groups.

In the `edit group` window, one can choose videos to add or remove to/from the group.
Could also include a search bar.

**Describe alternatives you've considered**
- #1403

**Comment by GilgusMaximus** [comment]
We will at some point implement a proper playlist system where you can create as many playlists as you like. This is not straight forward though, as changing it later could create massive problems and at the moment we have a bit of backlog with PR's to check and other fixes
