### ISSUE TITLE
suggestion for a mirror video feature on videos

### ISSUE THREAD

**Issue by RagglenLove** [FreeTubeApp/FreeTube#1406]
**Important note**
Please check other open and closed issues for a similar feature request before proposing a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Is your feature request related to a usage problem (not a bug)? Please describe.**

**Describe the solution you'd like to see implemented**
Sometimes, YouTube has videos that are mirrored, so I'm suggesting an option to mirror videos, so if the video source is mirrored, the user can un-mirror the video. I've done this in Firefox by installing this [add-on](https://addons.mozilla.org/en-US/firefox/addon/mirror-video/), so I'd like an similar option for FreeTube.

**Describe alternatives you've considered**

**Screenshots**
Here's a mock-up I've created to show the feature that I'm suggesting:
 
![Screenshot_2021-06-12_19-27-18(2)](https://user-images.githubusercontent.com/45503845/121775526-c618e880-cb77-11eb-8209-66a98d5419f7.jpg)

The mirror icon comes from [here](https://www.onlinewebfonts.com/icon/448875).

**Additional context**

**Comment by GilgusMaximus** [comment]
This is possible, but I am not fully aware of what the goal is. If a video is mirrored on YouTube, then that is, at least from my perspective, the way it was intended to be uploaded, except if it contains copyright infringements that the uploader tries to hide. 

In that case we are not endorsing such behavior by providing a way to unmirror it.

So over all I am not quite sure what the use case for this would be?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please provide the information requested in the previous comment.
