### ISSUE TITLE
PSA: Open Redirects in Eletron - Secuirty risk

### ISSUE THREAD

**Issue by aproposnix** [FreeTubeApp/FreeTube#141]
I'm just posting this for the developers of Freetube.  You should be aware of this vulnerability (if you don't know already).  

https://blog.bentkowski.info/2018/07/vulnerability-in-hangouts-chat-aka-how.html

tl;dr

> If you write an Electron app, make sure that the main window cannot be redirected to an external domain.

**Comment by PrestonN** [comment]
I appreciate the article, it was a good read.  While I believe that some Electron apps could be affected by this, I don't believe that this will be an issue for FreeTube.

Any and all links inside of FreeTube are sent to the browser which would remove the possibility of the author doing the same trick with FreeTube.  The only links that FreeTube handles are `freetube://` URLs sent from the browser extension.  Even then, FreeTube doesn't "redirect" anywhere.  FreeTube parses the link to try and get a video ID and allows you to watch that video.

Nothing to worry about :)
