### ISSUE TITLE
Is stub info kept for deleted/banned channels and videos?

### ISSUE THREAD

**Issue by Victor239** [FreeTubeApp/FreeTube#1416]
**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify: Functionality

**Question**
I searched and found that banned channels you're subscribed to don't get removed fully #555 which is good (though I'm not sure how much stub info is retained about the channel), but I'm not sure what happens if a channel is deleted instead. 

I also couldn't find any info on what happens to individual banned/deleted videos that are in your History/Playlist/Subs etc.

Finally regarding banned channels, what info is retained? Ideally the channel name, thumbnail and URL at least is (I presume these are all cached locally).

**Comment by GilgusMaximus** [comment]
Well it can obviously happen that Electron decides to cache something. But in regards to actual data we store, we only store references to the images and links. So obviously they get downloaded when viewed and what Electron does with them is up to Electron. But it could also happen that the image is still there on YouTube, but YouTube simply loads a different channel layout. E.g. if the account gets unbanned.

**Comment by Victor239** [comment]
Thanks, I've tested it now with deleting a channel to see too and am creating appropriate issues.
