### ISSUE TITLE
Sometimes select the timing or changing from 360p to 720p causes an error

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#1417]
**Behavior of the program**
**_Sometimes_** select the timing (or changing from 360p to 720p) of saved video broadcast causes `A network error caused the media download to fail part-way`.
  
**Expected behavior**
No error occurred and video continues to play.
  
**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open video broadcast
2. Try to change the timing
3. ?????
4. An error may have occurred 

**Link to video**
https://youtu.be/NIHgqBe50fo

**Screenshots**
![image](https://user-images.githubusercontent.com/34391398/122160779-32962f00-ce79-11eb-94d3-4aff3a2de76a.png)

**Environment Information (please complete the following information):**
 - OS: Windows 10 20h2 (19042.1055)
 - FreeTube version: 0.13.1 beta
 - Installation Method (If applicable): Portable
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment]
Well it looks like the streaming / quality plugin for VideoJS failed to load the provided links. Could be that there is a problem with the DASH file, which is unlikely though as it would happen much more often if that was the case. 

We'll need some more reports, but I am adding the third party label proactively already.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This probably got fixed by the DASH quality selection refactoring, closing.
