### ISSUE TITLE
Add a option to disable comments

### ISSUE THREAD

**Issue by dryluggage** [FreeTubeApp/FreeTube#1418]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I want to spend less time on yt/the internet and that would help

**Describe the solution you'd like to see implemented**
an checkbox to disable comments in the options

**Describe alternatives you've considered**

**Screenshots**

**Additional context**

**Comment by GilgusMaximus** [comment]
I don't understand. Comments are not loaded by default.

**Comment by peepopoggers** [comment]
#1656
