### ISSUE TITLE
Add a way to disable "tabbing" or opening new windows

### ISSUE THREAD

**Issue by dryluggage** [FreeTubeApp/FreeTube#1419]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I want to spend less time on yt/the internet and that would help

**Describe the solution you'd like to see implemented**
an option to disable opening links in new windows or opening new windows entirely

**Describe alternatives you've considered**

**Screenshots**

**Additional context**

**Comment by PikachuEXE** [comment]
See #1427
