### ISSUE TITLE
Dotmenu should close after an option is selected.

### ISSUE THREAD

**Issue by JonnyCodewalker** [FreeTubeApp/FreeTube#142]
Currently the dotmenu stays open for every video you click on. It would feel cleaner if it would close after an option was selected or the dotmenu of another Video is opened.
![screenshot from 2018-07-24 22-19-11](https://user-images.githubusercontent.com/30217573/43163899-2d4a7c4a-8f7f-11e8-9b5d-133ae7314ac9.png)

**Comment by K06RA** [comment]
Hmm, I wasn't able to reproduce that. What did you do exactly?

**Comment by PrestonN** [comment]
This should be fixed in the latest release, closing.
