### ISSUE TITLE
Open freetube desktop app whenever a youtube url was clicked

### ISSUE THREAD

**Issue by kojid0** [FreeTubeApp/FreeTube#1421]
**Describe the solution you'd like to see implemented**
I'd like to have FreeTube opened automatically whenever I click a youtube url-link in the browser. This is the standard behavior for some desktop apps, like zoom (when you click on a zoom url-link, it asks you if you want to launch the desktop zoom app).
It might need a small browser add-on to block loading youtube and ask to launch the desktop app instead.

**Describe alternatives you've considered**
Copy link in the browser and paste it into FreeTube.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It would be nice if it also recognises the url for example the signal desktop app

**Comment by PrestonN** [comment]
https://docs.freetubeapp.io/usage/browser-extension/
