### ISSUE TITLE
When viewing the channel page the channel name should be a hyperlink

### ISSUE THREAD

**Issue by Victor239** [FreeTubeApp/FreeTube#1422]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
To help ensure that stub info #1416 is kept for channels which get deleted/banned, or all their videos deleted/banned. 

**Describe the solution you'd like to see implemented**
On channel pages the channel name on individual videos are hyperlinks, but not the channel name in the title. 

![](https://i.imgur.com/AzJ4Ea3.png)

This means that if all the videos were deleted/banned then you can no longer lookup the URL of the channel, if you wanted to lookup the channel on archive sites such as archive.org or if there are other links to that channel across the web that could be used for searches. 

**Describe alternatives you've considered**
Not sure of any except noting down the URLs in a separate application.

**Screenshots**
See previous.

**Additional context**
N/A

**Comment by GilgusMaximus** [comment]
We won't provide this because it will be covered by #1414

**Comment by Victor239** [comment]
Ah cool, hadn't seen that one.
