### ISSUE TITLE
Deleted/banned channels that you're subscribed to should remain accessible 

### ISSUE THREAD

**Issue by Victor239** [FreeTubeApp/FreeTube#1423]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
After some testing it seems when a channel you're subscribed to is deleted/banned then you'll still see the channel name and thumbnail in the subscriptions sidebar, but trying to navigate to the channel will show errors and the channel will never load.

**Describe the solution you'd like to see implemented**
Instead more metadata for the channel should be saved locally (#1416), including the channel title (also being hyperlinked #1422), thumbnail and banner. It should still look like this, except with the videos being inaccessible and there should instead be an error message where the videos would be stating: "this channel is deleted/banned":

![](https://i.imgur.com/RkTvsLm.png)

This would also allow the user to be able to unsubscribe from these deleted/banned channels, which currently isn't possible.

**Describe alternatives you've considered**
N/A

**Screenshots**
See previous.

**Additional context**
It's very frustrating to have a channel you're subscribed to get deleted/banned, because right now you can't even view their old channel page and nor unsubscribe from it.

**Comment by GilgusMaximus** [comment]
It is frustrating, but we won't download more data to the users system just to provide it for banned channels. This will increase the disk footprint of the app massively and we do not want to do this. You can save the images at all time by right clicking on it.

If you want to preserve channels then you should look into other projects which allow you download channel data and pages which you can then display. 

You should still be able to unsubscribe from the profile view.

**Comment by Victor239** [comment]
Okay fair enough, I can see how saving the banners would store too much extra data. 

But the channel thumbnails on the other hand are already downloaded (since they're still accessible in the sidebar if you're subscribed to it), so viewing the channel page with only the thumbnail should be a possibility. 

It would then at least allow accessing the old URL of the channel once #1414 is implemented. It would also mean a better UX rather than the current error messages which aren't clear to end users about why the channel is now inaccessible.

**Comment by GilgusMaximus** [comment]
As I said. The images are not downloaded actively by us. You can check the FreeTube data directory. The images might lie in some of the cache files, but not as raw .png / .jpg files. But if they are not, then they will not load

**Comment by peepopoggers** [comment]
might as well download the entire internet
