### ISSUE TITLE
Suggestion to add a reload button to FreeTube

### ISSUE THREAD

**Issue by RagglenLove** [FreeTubeApp/FreeTube#1425]
**Is your feature request related to a usage problem (not a bug)? Please describe.**

**Describe the solution you'd like to see implemented**
Sometimes a video doesn’t load properly, maybe due to network issue or something is wrong with an Invidious instance, the solution to reload the video is to press the “Backward” and “Forward” buttons to reload the video, so I’m suggesting a “Reload” button to reload the video.

BTW, both the backward and forward buttons are labeled "Forward" in FreeTube v0.13.1 Beta.

**Describe alternatives you've considered**

**Screenshots**
Here's a mock-up I've created to show the feature that I'm suggesting:
![Screenshot_2021-06-18_09-32-48](https://user-images.githubusercontent.com/45503845/122497004-3d1d0980-cfdc-11eb-9392-eddc80908816.png)

**Additional context**

**Comment by ChunkyProgrammer** [comment]
Duplicate of #1005

**Comment by RagglenLove** [comment]
> Duplicate of #1005

Thanks, I actually searched for "reload button" on the search bar, couldn't find it.
