### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by thisisjustathrowaway** [FreeTubeApp/FreeTube#143]
Does FreeTube have compatibility with annotations?

**Comment by PrestonN** [comment]
Unfortunately, I can't see this being implemented.  I don't see a way to grab the annotations from a video URL and stream it to the user without using the official YouTube player.  There isn't much documentation of other projects doing this either.  If I ever find any updates I'll post here but I wouldn't expect to see this any time soon.

**Comment by ScriptForAll** [comment]
Sorry if I'm talking about something I don't know about but doesn't Invidious has a support for annotations in its native player? [Example](https://invidious.snopyta.org/watch?v=29-q7YnyUmY&iv_load_policy=1)

**Comment by GilgusMaximus** [comment]
As mentioned in #579 this seems to be easy to do. But requires a lot of adjustments here and there. So we'll push it of for now, as it is a lot of work and we are currently take a break from major development.
Also I am going to close this in favor of #579

**Comment by PrestonN** [comment]
I'm gonna reopen this as Annotations is a different feature compared to the Chapters support requested in #579.

Annotations are the old feature that YouTube had where creators could include popups with extra information even after a video was published.

With the new code base, this will be much easier to support in the future as we're now using the same player as Invidious, which is the player needed to include this functionality. We can look into it again at some point but as was mentioned it's a much lower priority.

**Comment by GilgusMaximus** [comment]
Ah okay. I missed the fine difference in there with the absence of the feature in newer videos.

**Comment by peepopoggers** [comment]
Annotations have been removed from youtube.
