### ISSUE TITLE
Download video option

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1434]
**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [x] Contribution
- [ ] Languages
- [ ] Setup
- [ ] Other. Please specify:

**Discussion**
So i was looking at this (see screen) and i thought that the list gets fast very long because all the options u can choose of.

![FreeTube_wWk5jfbACw](https://user-images.githubusercontent.com/73130443/122607186-b9a9f980-d069-11eb-8bd7-6c8eb641fb74.png)

So i thought maybe its better to have questions instead of a long list. I'd like to discus this idea, because im not sure if this is a smart thing to do.

For example:

1. What would u like to download

- Audio 
- Video 
- Captions
- Audio + video (iirc this is not a thing yet)

If u Chose for Audio, Video, Audio + video the next question will be

2. What quality u want to have for example 1080p / 47852kps (depends of what u chose of course)?

3. Optional next question if u chose video or video + audio in what fps u want to watch?

Next question will be (if more options available) 

4. What format do u want video/webm video/mp4 audio/webm audio/mp4?

Option next question could be 

5. Would also u want captions? y/n

if y then show all language options.

**Comment by orthand** [comment]
Another two ideas:
- Settings menu to select limited list entries
- Pop up window with full list and filter options to find the desired version

Both these ideas could be combined: An additional list entry after the selected list in the drop down named sth like "Additional formats" that opens the settings menu pop up with a column to fav/star the important list entries and also a download button or possibility to select multiple entries for downloading.

**Comment by GilgusMaximus** [comment]
#582
