### ISSUE TITLE
Inconsistent bahaviour of showing sponserblock segment color

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1439]
**Behavior of the program**
Title says it all.

**Expected behavior**
Consistency in showing the color.

**To Reproduce**
See video.

**Link to video**

https://user-images.githubusercontent.com/73130443/118561121-19a33c80-b75a-11eb-89a4-230a56615ffa.mp4

**Screenshots**
None.

**Environment Information (please complete the following information):**
- OS: [Win 10]
- OS Version: [20h2]
- FreeTube version: [v0.13.1-nightly-937 Beta]
- Installation Method (If applicable): [Portable]
- Primary API Used: [Local API]

**Additional context**
None.

**Comment by GilgusMaximus** [comment]
I would assume that the Sponsorblock data has to be loaded again and is not cached compared to the video and video data, so this is why it takes longer and is not included. But I would need the error output of the dev console to know more.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
it skips the sponser tho but it doesnt show the color. Knowing this would u still require output form the dev console?

**Comment by GurjinderSingh** [comment]
in some music videos non music part from Unpaid/Self Promotion or Interaction Reminder (Subscribe) not skipping.

watch?v=YgvDuXQeP_0

![image](https://user-images.githubusercontent.com/3470709/128989764-d5264141-0a1a-41a7-b7e7-c7f29752cf2a.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
i believe this is fixed by @MarmadileManteater because i cant reproduce it anymore
