### ISSUE TITLE
Always play video in Fullwindow

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1446]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
This is the same but as https://github.com/FreeTubeApp/FreeTube/issues/647 but for Fullwindow.

**Describe the solution you'd like to see implemented**
A toggle in the settings menu. When enabled videos will always play in Fullwindow mode.

**Describe alternatives you've considered**
None.

**Screenshots**
None.

**Additional context**
Check out https://github.com/FreeTubeApp/FreeTube/pull/954 to help with ur implementation.

**Comment by GilgusMaximus** [comment]
I am gonna close this as #1281 discussed this already and Seb is working on it
