### ISSUE TITLE
Vertical videos overflow out of the display

### ISSUE THREAD

**Issue by jarnokie** [FreeTubeApp/FreeTube#145]
See [https://youtube.com/watch?v=xCY9B8POq3A](https://youtube.com/watch?v=xCY9B8POq3A) for example. Videos should fit the display.

**Comment by PrestonN** [comment]
This is a known issue.  I should be able to get it fixed in the next release.

**Comment by PrestonN** [comment]
This should be fixed in the latest release, closing.
