### ISSUE TITLE
All videos are blocked? 

### ISSUE THREAD

**Issue by TMS-Namespace** [FreeTubeApp/FreeTube#1453]
In past 3-4 days,  suddenly FreeTube can't load any video,  giving invideos api error "likely blocked" for all videos without exception. 

Also tried to load them via VPN from servers around th world,  same issue. 

Meanwhile NewPipe on Android loads all videos without any issues. 

Anyone facing this also?

**Comment by ChunkyProgrammer** [comment]
I was able to watch a video using the kavin.rocks invidious instance.

**Comment by TMS-Namespace** [comment]
> I was able to watch a video using the kavin.rocks invidious instance.

 Worked great,  thx, did not thought about that..
