### ISSUE TITLE
Allow Sponsoring through GitHub?

### ISSUE THREAD

**Issue by martin-braun** [FreeTubeApp/FreeTube#1457]
**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [X] Other. Please specify: Sponsoring

**Question**
I'd like to Sponsor through GitHub to boost motivation for development (especially for syncing between NewPipe and FreeTube, no expectations, though), but I don't like to sign up in an external page. Is there a specific reason why you don't use GitHub's own sponsoring, @PrestonN?

**Comment by dennis1248** [comment]
I also thought about posting an issue about this a few days ago.

I would also like to support the FreeTube project. I gave in and linked Paypal to my debit account so I could donated to Elementary OS on Github and get access to their development builds. Might as well start making recurring donations to other projects I like or use.

Liberapay or Paypal would also be an acceptable way to accept donations outside of Github if you dislike the idea of Github/Microsoft getting 30% (?) of your donation. (Even though I then wouldn't be able to get a cool badge on my Github profile :cry:)

I would also donate not expecting anything in return. The donations serve to cover the cost of maintaining the FreeTube project and anything on top of that is an intensive to keep development going.

**Comment by StoppingBuck** [comment]
> since it doesn't have a large third party such as Microsoft leaching a sizable percentage of each donation.

Actually, according to Github's terms they don't currently take any cut of sponsorship donations to open-source projects. For Organizations, however, the cut is 10%.

Of course, this could all change in the future, but right now 100% of donations through Github Sponsors go to the project.

**Comment by PrestonN** [comment]
I can look into it if it's truly desired. Personally I do believe that Liberapay plus Cryptos solves all the major use cases for those wanting to donate but I'd be open to another platform as long as there's support for it and it makes sense for us to be present there.

**Comment by cocoonkid** [comment]
GH sponsors would be nice. 
Cryptos are a scam and super stressful to use. And I rather not support criminals in all honesty because that's the only use case besides speculation.
Liberapay looks good. But GH sponsors works way better for me too.  
Thanks for considering.

**Comment by martin-braun** [comment]
> Although I am of the opinion that Liberapay which FreeTube already uses is probably a better alternative since it doesn't have a large third party such as Microsoft leaching a sizable percentage of each donation.

If this would be the case, I wouldn't want to use GitHub Sponsoring, but I also heard Microsoft will not take any percent for open-source projects.

> I would also like to support the FreeTube project (and get a dope badge for it in return).

It's not just easier to donate though GitHub, but indeed you get a dope badge and can show off your support. It's a nice free return that could attract more people to donate. An external donate page is also another step that doesn't have to be required if going for GitHub Sponsoring.

> I can look into it if it's truly desired. Personally I do believe that Liberapay plus Cryptos solves all the major use cases for those wanting to donate but I'd be open to another platform as long as there's support for it and it makes sense for us to be present there.

Yes, would welcome this. I won't argue that Liberapay isn't the better choice, but for GitHub users it's not the easiest to donate. Think of it like selling a product, but it's your open-source product and you want sponsors. The method is the same, the least troublesome path with the smallest count of steps will cause the least resistance when people think about support your creation.

Giving more choices is an excellent conclusion.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing because the team isnt intrested in getting sponsered through GitHub

**Comment by EmileDirigera** [comment]
I hope it is okey to post here instead of opening a new issue, since this is on the same topic and someone related to what has been said here.

I would love to donate to this project but donations through Bitcoins is not viable for me. After reading this issue, I found that there is a website that solves this problem for me: https://liberapay.com/FreeTube/

You should perhaps consider updating the README with a link (to liberapay or something else) or an alternate way to donate.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@EmileDirigera Our Liberapay has been deprecated. We are currently looking into alternative ways for the community to support the project.
