### ISSUE TITLE
thank you, but im done

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#1459]
id like to thank the makers of the freetube app for having provided a up until recently, a smooth, private and native expirience, but recent updates have rendered my data more and more unstable until the most recent number jump.
which broke the entire setup entirely.
constant invidious api errors
freetube api errors
watch history not remembered
videos marked as watched not remembered after reload
not remembering channels i unsubbed from after reload
favorites gone
sometimes not remembering the zoom level
a complete reset of my data has not helped the most dire of errors

again, i like to thank the team for their effort at what they have achieved here, but my experience has been hindered enough that i have to seek an alternative, i might return at a later date, but until than, farewell and i wish the team all the success.

**Comment by cocoonkid** [comment]
The most recent update was awesome. YT changed something and if it will be fixed with the next update.

I cannot see any of the errors you are experiencing besides the4 day running local API error. And I run on 3 systems.

With all due respect. Your post is useless and doesn't belong here.

**Comment by ShawnNogi** [comment]
good luck finding an alternative lol

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is an issue board and not i want to complain board and telling ur life story board. U marked this as a discussion, but there is clearly nothing to discuss here. 

I don't know what ur use case is for using Freetube, but FreeTube is an open source desktop YouTube player built with privacy in mind. 

When having privacy in mind there are always compromises that have to be made, in terms of for example: user experience, features.

But the devs of Freetube do a heck of a great job maintaining and improving this application.

Even if there is an upstream problem that breaks Freetube, the devs cant do anything about it but wait for the upstream issue to be resolved. In all of the times this happened and the upstream issue has been resolved, the devs would almost immediately roll out an fix.

These sorts of compromises u have to make if ur going to FOSS route.

**Comment by peepopoggers** [comment]
Cry about it

**Comment by peepopoggers** [comment]
n1. it is in beta - a work in progress
n2. the local breaks were due to youtube's changes. there is a public fix available
n3. the invidious errors are due to there being a lack of stable invidious instances
n4. this is an issue board, not a mental issue board

**Comment by PrestonN** [comment]
The user already deleted their account, so there isn't much of a point in responding to it any more. The other comments here have already done a good job addressing it however.

If you ever have an issue, let us know and we'll do our best to address it. Even if we don't respond right away, it at least makes it available for someone else in the community to look at it and come up with a solution. That's the beauty of FOSS.

We also all do this in our free time, so solving urgent issues right away won't always be possible. We do what we can and we ask that you stay patient while we try to get a fix available in exchange for this free application while also not begging for donations to stay afloat. I'd consider that a fair trade off.
