### ISSUE TITLE
API

### ISSUE THREAD

**Issue by mendel3** [FreeTubeApp/FreeTube#146]
Is it possible to get an API for the current video playing, the current time in the video, etc for a rainmeter skin?

**Comment by PrestonN** [comment]
Hey there!

One of the features that's been requested was to have some sort of "Now Playing" notification to be shown in the Operating System's notification tray similar to how a music player does it.  I don't really use Rainmeter much but I believe that would work for what you want.  Please correct me if I'm wrong though.

**Comment by PrestonN** [comment]
I believe with newer versions of Electron, this shows up automatically when a video is playing, which should allow that information to be grabbed by other apps such as rainmeter.  Since the rewrite is using the latest version of Electron, this shouldn't be needed.
