### ISSUE TITLE
"Focus Search Bar" keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by ShadowOfGannicus** [FreeTubeApp/FreeTube#1463]
**Behavior of the program**
ALT+D keyboard shortcut does not switch focus to "Focus Search Bar".

**Expected behavior**
ALT+D keyboard shortcut does switch focus to "Focus Search Bar", as described on Keyboard Shortcuts list https://docs.freetubeapp.io/usage/keyboard-shortcuts/

**To Reproduce**
1. Open FreeTube
2. Hit Alt+D

**Environment Information:**
 - OS: Arch, KDE
 - FreeTube version: v0.13.2

**Comment by elig0n** [comment]
same issue with the same version on Linux.
d, alt+d, shift+d all detach the player into PIP mode

**Comment by yamabiiko** [comment]
Same issue on Gentoo, using Sway and the app image version of FreeTube

**Comment by deadenduser** [comment]
> ALT+D keyboard shortcut does not switch focus to "Focus Search Bar".

Have this same issue on Debian 10 + Openbox

> d, alt+d, shift+d all detach the player into PIP mode

Add Alt+Shift+D to that list

**Comment by deadenduser** [comment]
> ALT+D keyboard shortcut does not switch focus to "Focus Search Bar".

Having the same issue with FreeTube v0.14.0 Beta (.deb) on Debian 10

> d, alt+d, shift+d all detach the player into PIP mode

Add Alt+Shift+D to that list

**Comment by 0xConnorRhodes** [comment]
I'm experiencing this issue on macOS. Neither option+d nor command+d focus the search bar.
