### ISSUE TITLE
Searchbox must match theme settings

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1467]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
At this moment the searchbox is white even if another theme is enabled like dark theme.

**Describe the solution you'd like to see implemented**
Match theme setting.

**Describe alternatives you've considered**
None.

**Video**

https://user-images.githubusercontent.com/73130443/123651676-35026c80-d81b-11eb-9ae3-25b90f72e881.mp4

**Additional context**
None.

**Comment by peepopoggers** [comment]
Wait how was this not noticed!!!
I am blind

This is important issue.

**Comment by GilgusMaximus** [comment]
> 
> 
> Wait how was this not noticed!!!
> I am blind
> 
> This is important issue.

Good question

**Comment by peepopoggers** [comment]
This has been fixed in #1482
