### ISSUE TITLE
Remove white watch time indicator

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1469]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
In my opinion this can be removed, because

- U can see the time u are in the video in the bottom left corner.
- When u hover close to the indicator it will get covered up by the thumbnail preview.

**Describe the solution you'd like to see implemented**
Remove the indicator.

**Describe alternatives you've considered**
None.

**Screenshots**
![Screenshot (220)](https://user-images.githubusercontent.com/73130443/123658383-35056b00-d821-11eb-9a88-1af6e074d125.png)

![Screenshot (221)](https://user-images.githubusercontent.com/73130443/123658938-b52bd080-d821-11eb-8f1b-25c7ef917e1a.png)

**Additional context**
None.

**Comment by PikachuEXE** [comment]
#1478 
@efb4f5ff-1298-471a-8973-3d47447115dc
