### ISSUE TITLE
Integrate sponsorblock

### ISSUE THREAD

**Issue by Kreyren** [FreeTubeApp/FreeTube#1473]
Sponsorblock is an extension for firefox that allows skipping sections (sponsors, interaction reminders, self-promotions, etc..) in a video on youtube and invidious.

See https://sponsor.ajay.app/

Proposing it's integration in FreeTube

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sponserblock is integrated in freetube go to the settings menu and scroll to the bottom. Please close this issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Also this short notice. Please use the template Freetube provides. Otherwise the devs will start to close your issues without warning.

**Comment by Kreyren** [comment]
Thanks
