### ISSUE TITLE
Integrated onion-routing

### ISSUE THREAD

**Issue by Kreyren** [FreeTubeApp/FreeTube#1474]
I constantly have to change circuit to be able to use YouTube API without falling to invidious.

Proposing integrating integrated onion-routing e.g. how Tor Browser Bundle does it  -> to change the circuit until YouTube API passes

**Comment by ChunkyProgrammer** [comment]
I don't think this will be added https://github.com/FreeTubeApp/FreeTube/issues/1169#issuecomment-814269061

**Comment by Kreyren** [comment]
How else do you want to handle common blocks by YouTube API?

**Comment by arrowgent** [comment]
freetube has a proxy setting

use it for tor
setup your tor
route your traffic through tor

freetube does not require additional features to enable tor.

**Comment by Kreyren** [comment]
I am aware of proxy setting but the issue is that the circuit has to be changed when the connection gets blocked which is pita to do manually.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by GilgusMaximus** [comment]
As @ChunkyProgrammer pointed out, we are not going to bundle tor daemons. I am pretty sure there are solutions to your problem available, like automatically switching circuits and similar when used as proxy

**Comment by Kreyren** [comment]
@GilgusMaximus I am aware of those solutions, but those are sub-optimal since it requires to use the system Tor and writting script to switch the circuit when it blocks the user.

So my current experience is:
1. try video
2. change circuit
3. Repeat 1 and 2 (8 times on average)
4. Once the video is loaded, repeat 2 when it stops working (12 times on average)

This would be better if it was integrated in the client and it was doing that automatically

**Comment by GilgusMaximus** [comment]
yes it would be better, but will not do it and will not merge anything related. You can mess up too much and none of us a programmer with the knowledge and experience required to provide a perfect implementation of this.

**Comment by Kreyren** [comment]
perfect implementation is not a thing in this stage of development for this feature.I proposed a built-in tor client that can build a new circuit on demand which can be reviewed by the tor project as needed.
