### ISSUE TITLE
Add a way to force a certain quality even if it means that the video will buffer.

### ISSUE THREAD

**Issue by MuffinLover42** [FreeTubeApp/FreeTube#1481]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Often while watching programming videos or any video that has a lot of text which is important, the quality drops to get smoother playback; the problem is that when it drops the text becomes very hard to read.

**Describe the solution you'd like to see implemented**
A button or option that enables a "quality over smoothness" mode.

**Describe alternatives you've considered**
None.

**Screenshots**
None.

**Additional context**
None.

**Comment by GilgusMaximus** [comment]
We have had this issue so many times by now. VideoJS does some magic under the hood. We applied the quality selection as per documentation but it still does change the quality for some reason
