### ISSUE TITLE
Win64 portable not actually portable?

### ISSUE THREAD

**Issue by f4natix** [FreeTubeApp/FreeTube#1485]
I wonder why my Win64 portable Version stores its config files in %AppData%.
It seems the normal behaviour, so I don't do anthing wrong I guess. But this behaviour is NOT portable!
Also I didn't find an option or commandline parameter to change the storage path of the config files.
Is there something like that? - If not I suggest something like:

if exist "FreeTube\portable.mode" (set config storage to: "FreeTube\Profiles") else ( set config storage to: "%AppData%\FreeTube")

A Chromium like comandline (as it seems based on) would be fine to. But is less smart.

**Comment by Svallinn** [comment]
Read this
https://github.com/FreeTubeApp/FreeTube/issues/130
