### ISSUE TITLE
mpv player instead of the system Save dialog

### ISSUE THREAD

**Issue by AlexLevkovich** [FreeTubeApp/FreeTube#1486]
**Behavior of the program**
When I press Download Video button at bottom/right of the video player then it shows menu of choices for download (and it is ok), when I choose some item then it loads mpv video player.

**Expected behavior**
I expected to see the system Save dialog to choose the location and write the output file name.

**Environment Information (please complete the following information):**
 - OS: Arch
 - OS Version: the latest
 - FreeTube version: 0.13.2
 - Installation Method (If applicable): using repackaged deb provided by program's author
 - Primary API Used: Local API

**Comment by Svallinn** [comment]
I really have no idea what you're talking about.
The "Download video" button options open the respective link in the browser, it is not connected to the external player code at all.

**Comment by AlexLevkovich** [comment]
But it opens mpv on my system. Maybe it is because of my system's some file association or just KDE matter. It does not matter. What is the purpose of this? Like I said it would be wise to just open the system Save dialog here.

**Comment by GilgusMaximus** [comment]
There are other issues covering downloads
