### ISSUE TITLE
Freetube does not play the next video in a playlist when using the Invidious API

### ISSUE THREAD

**Issue by odinhb** [FreeTubeApp/FreeTube#1487]
**Behavior of the program**
Freetube plays the same video twice instead of moving on to the next in a playlist. After playing it the second time it stops altogether. (Nothing happens other than a message: `Playing next video`)
Whether I click next video manually or wait for one to finish + 5 seconds does not matter.

**Expected behavior**
I expect freetube to keep playing the next video in the playlist, whether it be on shuffle play or linear.

**To Reproduce**
Open a playlist. [for example this one](https://www.youtube.com/playlist?list=PLJQswUar8fW97sPan8J4dsIpNJpswqFZ-)
Play any video in it.
Click next, or scrub to just before the end + wait 5 seconds.
The alerts will tell you Freetube is trying to play the next video.
I get `Error: No video id found: undefined` and `{"error":"Video unavailable"}`.
(Click the video that should've been next in line. It'll work fine.)

**Environment Information (please complete the following information):**
 - OS: GNU/Linux 5.12.0-9.2-liquorix-amd64
 - OS Version: Kubuntu 20.04
 - FreeTube version: `freetube_0.13.2_amd64.AppImage`
 - Primary API Used: Invidious API (I tested on Local API, that fixed it)

**Comment by odinhb** [comment]
Note: While writing the issue I fixed it by switching to Local API.

**Comment by ChunkyProgrammer** [comment]
Was able to reproduce. I will take a look at this.
