### ISSUE TITLE
Api key selection.

### ISSUE THREAD

**Issue by haydenhughes** [FreeTubeApp/FreeTube#149]
It would be good if the `checkDefaultSettings` could go through each API key and check to see if a test request doesn't error. If there is an error then it would just select a different key to use. This would help prevent API errors like #147.

**Comment by PrestonN** [comment]
I can agree with this, however I think at this point time would be better spent on removing the API keys entirely.  The dev working on Invidious has been doing a great job on a YouTube API that scrapes the site and doesn't need any API keys.  I have already been given permission to use this API with FreeTube.  I would rather spend my time implementing this versus trying to dynamically use some API keys that I won't be using for much longer.  Hope this makes sense.
