### ISSUE TITLE
Unable to load comments

### ISSUE THREAD

**Issue by TimGl105** [FreeTubeApp/FreeTube#1490]
When clicking "Click to View Comments" on any video, there pop up these errors:
![image](https://user-images.githubusercontent.com/22817301/124272643-50cd8180-db3f-11eb-82fd-2e2caf669360.png)

1. Local API Error (Click to copy): TypeError: Cannot read property 'continuationContents' of undefined
2. Falling back to Invidious API
3. Invidious API Error (Click to copy): undefined

- OS: Kubuntu 20.04
 - FreeTube: 0.13.2.amd64.deb

**Comment by MininuxDev** [comment]
I have the same problem, `commentPageResponse.data` is always empty, even when comments are enabled
With the invidious api it seems to work

**Comment by rcchan123** [comment]
I have the same issue, I am on Ubuntu 21.04 using the flatpak version.

**Comment by hg4893ghege** [comment]
Same issue here. Win 10 Pro. Changing the API just makes any video page unable to load instead.

**Comment by Sbinnotto07** [comment]
Same issue here, changing API doesnt fix too.

**Comment by mritunjaymusale** [comment]
Same error when using local api that fallbacks to invidious, although when it's set to invidious explicitly instead of default local api, it works

**Comment by jasonhenriquez** [comment]
> Same error when using local api that fallbacks to invidious, although when it's set to invidious explicitly instead of default local api, it works

These are two separate issues that have been solved in the nightly builds. See https://github.com/FreeTubeApp/FreeTube/commit/13d73d279844e883421d1bb72ec6a8a516b66a89 and #1537, respectively.
