### ISSUE TITLE
Hide description element when description is empty

### ISSUE THREAD

**Issue by peepopoggers** [FreeTubeApp/FreeTube#1494]
**Behavior of the program**
When a description is empty FT still displays the empty box

**Expected behavior**
The element should not show when description is empty.

**To Reproduce**
1. Find a video with no description text
2. Element will still appear

**Screenshots**
![image](https://user-images.githubusercontent.com/72892531/124369129-7b632b80-dc60-11eb-8edd-8065886d8415.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can u provide a url of a video with an empty description?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
What about empty characters?

 ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ <--- like these

The description tab will still show and to our eye it will look like there is nothing but spaces in the description, so an empty description.

I know this is an edge case but its important to know if these will be filtered so the tab will remain hidden.

**Comment by peepopoggers** [comment]
I dont think youtube allows these characters. In such a case, it would be rare and it would be intended by the video creator.
It is hard to filter characters like these as there is many. It is good to just use the normal case of empty description.

**Comment by peepopoggers** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc
example video (don't ask how and why i found this):
https://youtu.be/8gBtbK5-9yY

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Youtube allows these characters i tested but i do agree with ur statement.

**Comment by GilgusMaximus** [comment]
I mean we can filter whitespace out. That should be no problem.
