### ISSUE TITLE
Black Flicker When Watching Videos

### ISSUE THREAD

**Issue by Smoejoe995** [FreeTubeApp/FreeTube#1495]
**Behavior of the program**
FreeTube flickers black every couple of seconds when watching a video. This happens on all videos I watch, making them unwatchable. 

**Expected behavior**
For the video to play clearly without any flickering.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Launch FreeTube
2. Play a video

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: v0.13.2
 - Installation Method (If applicable): .exe 
 - Primary API Used: Invidious API 

**Video of Issue**
https://www.youtube.com/watch?v=JmwyFwYus2c

**Comment by GilgusMaximus** [comment]
This is a invidious problem. On the local api this does not occur

**Comment by Smoejoe995** [comment]
I still face this issue when using local api

**Comment by GilgusMaximus** [comment]
The problem is we cannot replicate it. I run windows myself and I do not encounter any problems. If someone else can chip in here that would help

**Comment by Smoejoe995** [comment]
I fixed it by turning off hardware acceleration in Chrome.

**Comment by GilgusMaximus** [comment]
Okay interesting. Then it is an electron related problem on windows apparently

**Comment by the-overdriven** [comment]
Indeed, looks like it's electron issue. Running FreePipe with `--disable-gpu` param makes the flickering go away.
