### ISSUE TITLE
Error message while using Invidious API as the preferred backend

### ISSUE THREAD

**Issue by JustAnotherSupporter** [FreeTubeApp/FreeTube#1496]
While using the Invidious Instance "https://invidious.exonip.de" as the preferred backend I receive the following error code:

> If you read this message, you seem to be a well-intentioned developer wondering why you are getting an error from this api endpoint. Due to the fact that this api sends requests to youtube it leads to rate limiting. This endpoint has been abused many times in the past and has now been blocked in order to continue providing the service to users. We are sorry that you cannot use this api. If you are getting this error when browsing the instance on the web please report this to invidious@exonip.de!

If this issue is not worth reporting, or should be reported in another way, please let me know!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You just have to use another instance. Freetube can do nothing about the fact that its been blocked.

**Comment by JustAnotherSupporter** [comment]
Alright, thanks for the answer - thought that were the case, but were unsure if FreeTube were able to use other api's to that specific instance.
