### ISSUE TITLE
Adding exported Youtube Playlists (.csv) would be great!

### ISSUE THREAD

**Issue by firefoxlover** [FreeTubeApp/FreeTube#1497]
Love the program! After the last update everything works perfectly!

This feature would be great

Greetings

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1016

Also

Short notice. Please use the template Freetube provides. Otherwise the devs will start to close your issues without warning.
