### ISSUE TITLE
Add instance rating tooltip when hovering on like/dislike bar

### ISSUE THREAD

**Issue by peepo5** [FreeTubeApp/FreeTube#1498]
It would be useful knowing either the rating out of 5 or the percentage of people that liked a video vs didn't.
These stats are shown on invidious and would be useful as displayed below.
For x% vs x/5 I want to know your guys opinions.

**Describe the solution you'd like to see implemented**
Tooltip with rating:
![image](https://user-images.githubusercontent.com/72892531/124502295-1ec85380-ddbb-11eb-9266-36c9fd8c6246.png)

**Describe alternatives you've considered**
Put it in extra info in description #1475 (check my comment)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
U are not explaining why u think this would be useful.

By the way if u want to know opinions about an issue its better for visibility to use the template discussion.

**Comment by peepopoggers** [comment]
It allows easy comparisons between audiences and like/dislike ratios

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
In my opinion the like and dislike is enough of a comparison tho. Would like to here other options about this.

**Comment by peepopoggers** [comment]
Yes but seeing 45325 likes 3522 dislikes to 3524 likes to 557 dislikes is more confusing than like 95% to 98%

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
But the blue bar fixes this confusion (at least mine xD)

**Comment by peepopoggers** [comment]
not really, as it shows a static amount of pixels.
This is a very small addition, and is a pascal's wager.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> not really, as it shows a static amount of pixels.
> This is a very small addition, and is a pascal's wager.
> 

Yeah thats fair.

There need to be a check in place tho something like this:


if(likes != disabled) {
 calculateLikeRatio
}

**Comment by peepopoggers** [comment]
yepp

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The only way we can make this possible now is through PR #1982 but im not sure if we want that because newer videos will only have crowdsourced data.

Would u still like to see this implemented in combination with the API?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The only way we can make this possible now is through PR #1982 but im not sure if we want that because newer videos will only have crowdsourced data.

Would u still like to see this implemented in combination with the API?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing because it isnt possible with the current  version of FT
