### ISSUE TITLE
Improved Navigation Needed

### ISSUE THREAD

**Issue by aproposnix** [FreeTubeApp/FreeTube#15]
I've been using Freetube extensively over the weekend (I've been sick so I had a lot of time).  One of the most frustrating things for me has been the lack of navigation (esp., go back). 

It would be great if users could have a 'back' button (or keyboard shortcut to do this). 

Use Cases:

* User Opens "Most Popular" list of videos.  The user scrolls down through the list and clicks a video, after watching the video, the user clicks on the back button which takes him back to the "Most Popular" list to the point in the list he was looking. 
* User does a search. Scrolls through the results and then watches the video. After clicking on the back button it takes him back to his search query to the point in the list he was viewing.

**Comment by PrestonN** [comment]
This is definitely something I want to improve on.  This will be a more challenging one with how the app displays each screen but it's possible.  I'll need to play with this for a while so I can come up with a definitive solution.

Thanks for all of the issues you've been submitting.  It's very appreciated :)

**Comment by aproposnix** [comment]
I really hate to ask, but if you could bump up the priority of this it would be most appreciated.  This is massive papercut IMHO.

**Comment by PrestonN** [comment]
#223 was just merged which should improve this a bit.  Namely this will allow you to go back to the search screen after you have clicked on a video or playlist.  I won't close this issue just yet because this functionality could get fleshed out a little more in the future, but we're getting closer.

**Comment by P8ntBal1551** [comment]
+1 for the back button, and if you could - support for mouse back/forward buttons

**Comment by Archive5** [comment]
Add *Back* and *Forward* buttons. *Reload* button required as well

**Comment by Archive5** [comment]
Let jump to random page by long tap on back button same as web browsers

**Comment by aproposnix** [comment]
As there is a complete rewrite, I'll close this request. hopefully it'll make it into the new app :)

**Comment by PrestonN** [comment]
This is actually already in the rewrite. Feel free to try it out! :)
