### ISSUE TITLE
Videoplayback.mp4

### ISSUE THREAD

**Issue by LexHimself** [FreeTubeApp/FreeTube#150]
Hi,

Whenever i download a video through the player, it's filename will be saved as videoplayback.mp4. 
Can this be set to the video title instead by default? 

`header('Content-Disposition: attachment; filename="'.$title.'.mp3"');`
This is what i use in my php downloader, title is retrieved from the youtube api.

**Comment by PrestonN** [comment]
This is something that I have planned on doing, but in a slightly different manner.  While I'm aware that the video player has a download button, I wouldn't really consider that "proper" download functionality. This is why I don't advertise downloads as a feature.  The plan is to have a dedicated download section where you can pick sources and do format conversions as well.  This would end up being an "after stable" feature though.

**Comment by PrestonN** [comment]
Closing as downloads aren't supported for now.  Will allow renaming once fully supported.
