### ISSUE TITLE
Pausing video for a long time causes connection to fail and video to halt until reload

### ISSUE THREAD

**Issue by jcartner-young** [FreeTubeApp/FreeTube#1500]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
_Please describe clear and concise of what the problem is. Ex. I'm always frustrated when [...]_
It is a small niggle, but when I pause a video and leave for a long period of time (usually overnight) and try to continue playing it, the stream stops, an 'X' is presented in the middle of the video pane and playback is impossible unless I navigate away and back again. LKP is not always remembered when this happens, either.

**Describe the solution you'd like to see implemented**
_Please give a clear and concise description of what you want to happen._
I would like it if it could detect a dropped connection and simply re-establish it in the background and continue from the current video position.  Something akin to reloading the page to reconnect, but less drastic than downloading all content again?

**Describe alternatives you've considered**
_Are there other ways to solve the problem? Please give a clear and concise description of any alternative solutions or features you might have considered._
The only alternative at the moment is to navigate back then forwards, or navigate back to the page in some way, but this can result in the position within the video being lost.  Not sure what the pattern is to the position being lost, though.

**Screenshots**
_Sometimes people have screenshots from mock-ups or other projects. Add them here._

**Additional context**
_Add any other context about the feature request here._

**_Edit: Spelling & clarity_**

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Maybe issue #1005 and pr #1223 is related

**Comment by jcartner-young** [comment]
![image](https://user-images.githubusercontent.com/40523205/124627453-7b894400-de77-11eb-9fa2-d91f54ec1cf4.png)
(Screenshot for clarity)

**Comment by jcartner-young** [comment]
I have left a comment about this on another thread: https://github.com/FreeTubeApp/FreeTube/pull/1223#issuecomment-874865868

(Could be useful to view these linked thread in parallel.)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I never faced this problem and i often left my pc unattended for 8+ hours with the video on pause.

So in my opinion if this would happen to me i would like to see the following things in place.

1. A reload button
2. After the reloading is done the video starts playing from the last known position

**Comment by jcartner-young** [comment]
> I never faced this problem and i often left my pc unattended for 8+ hours with the video on pause.
> 
> So in my opinion if this would happen to me i would like to see the following things in place.
> 
>     1. A reload button
> 
>     2. After the reloading is done the video starts playing from the last known position

Hi. Thank you for your reply.

Hmmmm... It may well be my setup, then - Something I haven't checked, yet.

Could I ask:
Which OS and version are you running?
What video formats do you use?
What version of FreeTube do you use?

I'm on Linux Mint Tricia - v19.3, using Legacy formats and I am running v0.13.2 Beta of FreeTube.  I'm not using the Invidious API.

1. The reload button may have to suffice if connections silently drop and the connection state can't be read or determined;
2. I concur, that is what I would expect, too.  Or maybe a 'Continue from last position - xx:xx?' dialogue on refresh/revisit?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Im on win10, using dash formats and using the latest nightly build from beta 0.13.2

Im also using the local api

1. Maybe there have to be some kind of check in place. Not sure what the devs think of this.

2. I agree.

**Comment by jcartner-young** [comment]
Thank you.

I will try using DASH formats Instead.

Incidentally, do you know if there is a way of getting debug output or a log file?  I'm not getting any help or usage text in bash :/

Best regards.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Maybe enabling the developer tools, so u can read output from the dev console.

Ctrl + shift + I

**Comment by jcartner-young** [comment]
That worked.  Thanks.

Wow, so, it looks like it's a local web client wrapped in it's own browser?

Won't that just make it rather resource-heavy?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Are u talking about Electron?

**Comment by jcartner-young** [comment]
Yes.  I've experienced issues with solutions using Electron and various JS frameworks before.  Admittedly a while ago, now.  I'm an old programmer lol

**Comment by PrestonN** [comment]
There isn't much we can do about this unfortunately.

YouTube video URLs stay active for ~6 hours and refreshes after that time frame. We then have to make a new call to YouTube to get new URLs in order for the video to continue. Letting the video continue while you're away instead of pausing can help since when you come back the video will then be downloaded and can be played repeatedly, though the only real solution is by refreshing the page / adding a refresh button.

Since there's already issues related to those features, I'll go ahead and close this.
