### ISSUE TITLE
Offer optional menu item "Channels" instead of channel list in the UI

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#1506]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I subscribe to many channels and it would be useful to have a menu entry "Channels" instead of a long list in the UI.

**Describe the solution you'd like to see implemented**
- Add a seperate page for Subscribed Channels
- (optional) add a search bar for the channel page (would be very convenient)

**Describe alternatives you've considered**

-

**Screenshots**

-

**Additional context**

-

**Comment by GilgusMaximus** [comment]
So you mean something like a gallery view.
A neat possibility could be a toggle at the top which allows to switch between videos and channels
