### ISSUE TITLE
When clicking 'Load More' in the Playslists interface the viewport gets set to the top

### ISSUE THREAD

**Issue by cocoonkid** [FreeTubeApp/FreeTube#1507]
**Behavior of the program**
When clicking 'Load More' in the Playslists view the viewport gets set to the top and user has to scroll to the bottom again.

**Expected behavior**
When clicking 'Load More' in the Playslists view the viewport should be set to the viewport saved upon clicking the 'Load 
more"  button. Like it does in the subscriptions view.

**Comment by PikachuEXE** [comment]
Would be great if u can provide 1+ playlist(s) so we can reproduce and verify after fix

**Comment by cocoonkid** [comment]
@PikachuEXE  Not sure I understand the request. Provide a playlist?  I do not think this is playlist specific. Just add about 100 vids to the playlist and it can be reproduced no?

I'd love to help. Apology for sounding rude maybe :-)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Maybe u should do a screen recording of this bug.

**Comment by cocoonkid** [comment]
alright! will do so soon.

**Comment by GilgusMaximus** [comment]
@PikachuEXE he did not mean a playlist but the current favorites list on the left side bar

**Comment by cocoonkid** [comment]
compress
![Peek 2021-08-04 19-14](https://user-images.githubusercontent.com/43231640/128225240-10a09e45-48bc-4de8-bb1a-d1878ee50908.gif)
