### ISSUE TITLE
[Feature request] Port to Roku media streaming channel

### ISSUE THREAD

**Issue by e-t-l** [FreeTubeApp/FreeTube#1509]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
On Roku streaming devices (similar to Amazon Firestick, etc), there's only one official Youtube app, and it's painfully bogged down with constant ads. Roku is a closed-source OS, so jailbreaking it to run some sort of android or linux port isn't feasible. 

**Describe the solution you'd like to see implemented**
The Roku OS does support the development of [channels](https://developer.roku.com/docs/direct-publisher/getting-started.md) (like apps, for Roku). Officially published channels have to be vetted, and any sort of unofficial YT proxy would be immediately taken down, but "developer channels" that are unpublished can still be uploaded to individual Roku devices. Instead of being downloaded directly from the Roku Store, it would be a zip file that's hosted on GitHub, which users then upload to their device. There used to be a similar youtube scraping channel called [MyVideoBuzz](https://github.com/Protuhj/myvideobuzz), but it's unfortunately not working any more. (I've been messing with a fork of it a little to see if I could resurrect it by making it pull streams from invidious instances rather than directly from the youtube API, but I'm not a very experienced programmer and don't really know what I'm doing.) You folks may have better luck, either by forking MyVideoBuzz or simply making a FreeTube channel from scratch.

**Describe alternatives you've considered**
There are no alternatives. For myself and many other users, Roku isn't simply a PnP device but is actually built into the software of my smart tv. Switching to a different streaming platform would require buying a whole new tv.

**Comment by PrestonN** [comment]
Apologies, but this will not be happening.

Porting FreeTube to just about any other platform that isn't currently supported is going to require an extremely large rewrite and / or a separate app entirely just to be present on that platform. This team is already small enough and we already have to spend a lot of time managing and maintaining the current work load that we have. We simply do not have the resources to maintain more than what we're doing currently.

If you truly want something similar for your TV I would suggest getting an Android TV box and installing NewPipe or making a Kodi TV box and trying an [Invidious Plugin](https://github.com/TheAssassin/kodi-invidious-plugin).
