### ISSUE TITLE
where are all the settings, subscriptions, favorites, history and playlists stored?

### ISSUE THREAD

**Issue by 22i** [FreeTubeApp/FreeTube#151]
what directory what file?

**Comment by PrestonN** [comment]
Hello, you can find all of the files in the following locations:

Windows:
`%APPDATA%/FreeTube`

Mac:
`~/Library/Application Support/FreeTube/`

Linux:
`~/.config/FreeTube`

Each file is named as you would expect. `settings.db`, `subscriptions.db`, `history.db`, and so on.  Playlists are not stored yet as there is nothing to store but it will be located there as well when it is available.

**Comment by Wuanhe** [comment]
I used the appimage and don't have a ~/.config/FreeTube folder (ubuntu). Since the OS does no longer boot, and I deleted everything but home, is there anywhere else I can look to rescue my watched videos, favs and progress ?

**Comment by T-vK** [comment]
When installed via Flatpak on Linux: `~/.var/app/io.freetubeapp.FreeTube/config/FreeTube/`

**Comment by AtomicRobotMan0101** [comment]
APT
~/.config/FreeTube

FLATPAK
~/.var/app/io.freetubeapp.FreeTube/config/FreeTube
