### ISSUE TITLE
log-in

### ISSUE THREAD

**Issue by tarbear123** [FreeTubeApp/FreeTube#1510]
**Important note**
Please check other open and closed issues for a similar feature request before proposing a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Is your feature request related to a usage problem (not a bug)? Please describe.**
Please describe clear and concise of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like to see implemented**
i want the ability to log into my account

**Describe alternatives you've considered**
Are there other ways to solve the problem? Please give a clear and concise description of any alternative solutions or features you might have considered.

**Screenshots**
Sometimes people have screenshots from mock-ups or other projects. Add them here.

**Additional context**
Add any other context about the feature request here.

**Comment by ChunkyProgrammer** [comment]
https://github.com/FreeTubeApp/FreeTube/issues/144#issuecomment-408072780

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
just wanted to comment, damn u beat me xD

> 
> 
> [#144 (comment)](https://github.com/FreeTubeApp/FreeTube/issues/144#issuecomment-408072780)
