### ISSUE TITLE
Can't import subscriptions from YouTube

### ISSUE THREAD

**Issue by mj3ww2ypcj8f** [FreeTubeApp/FreeTube#1511]
**Behavior of the program**
When I click on the "Import YouTube (.json) button and add my subscriptions.json, nothing happens, no visible error or anything it just doesn't work

**Environment Information (please complete the following information):**
 - OS: Arch Linux
 - FreeTube version: v0.13.2 Beta
 - Installation Method: freetube-bin on the AUR
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment]
Please check the docs https://docs.freetubeapp.io/usage/importing-subscriptions/
let me know if that worked

**Comment by GilgusMaximus** [comment]
I am closing this in favor of #1542 because a discussion was done over there and a pr has been linked
