### ISSUE TITLE
Adding keywords in PR template in order to link an issue

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1512]
**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [x] Contribution
- [ ] Languages
- [ ] Setup
- [ ] Other. Please specify:

**Discussion**
In the PR template in the "Relate issue" section, contributes often add this issue number. However they forget to use the keywords in order to close the related issue. If this doesn't happen the PR gets merged but issue will stay open and clutter the backlog.

I think its better to add a few keywords (or just one) to the PR template, so u guys wont have to cleanup the backlog.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
An important question to ask is what do we do with PR's that make changes related to an issue but immediately not solve it? Just not link it? So the issue stay open until its actually solved by another PR.

**Comment by jasonhenriquez** [comment]
> An important question to ask is what do we do with PR's that make changes related to an issue but immediately not solve it? Just not link it? So the issue stay open until its actually solved by another PR.

I think this distinction should just be clarified in the PR template. Something to the effect of: 'If this pull request fully resolves the relevant issue, put "closes" before the issue number. Example: "closes #99999"'
