### ISSUE TITLE
Display bug on certain videos

### ISSUE THREAD

**Issue by ShawnNogi** [FreeTubeApp/FreeTube#1515]
Behavior of the program
When I view  video it appears to be off the screen with video info and comment link appearing to be moved to the right as well. 
![image](https://user-images.githubusercontent.com/39767738/125466476-f8d698d1-1327-4542-8c11-88128ce7cb60.png)

Reproduce:
Visit 
https://youtu.be/-7JTrLBD260

OS: Windows 10
FreeTube version: v0.13.2 Beta
Local Api Preferred

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I'm not able to reproduce this.

**Comment by GilgusMaximus** [comment]
Me neither, could it be that you have a second monitor that somehow creates this problem?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@ShawnNogi please respond to the previous question and if that is not the case and this is still a issue for u please provide additional information.
