### ISSUE TITLE
Add Toggle to Ignore Watch Progress Within Playlists

### ISSUE THREAD

**Issue by quantenzitrone** [FreeTubeApp/FreeTube#1522]
Problem Description:
When I have music playing in the background and the next song that autoplays is a song I have last time only heard until the middle, FreeTube starts playing from the middle, which is annoying. 

One nice solution:
Option to not save watched progress for music videos. 

Another possible solution:
Option to ignore saved progress in autoplay or playlist play.

**Comment by PrestonN** [comment]
There's not really anything we can do to differentiate between a music video and a non-music video. I would recommend just disabling the feature in your settings if you don't want FreeTube to save watch progress.

We could technically make this behavior specifically for playlists, though I'm not keen on having this be the default as I imagine most users wouldn't want this behavior. I would only accept this feature as a toggle.

**Comment by ChunkyProgrammer** [comment]
> There's not really anything we can do to differentiate between a music video and a non-music video. I would recommend just disabling the feature in your settings if you don't want FreeTube to save watch progress.
> 
> We could technically make this behavior specifically for playlists, though I'm not keen on having this be the default as I imagine most users wouldn't want this behavior. I would only accept this feature as a toggle.

Maybe a check to see if the uploader is a "verified artist" could be done?

**Comment by PrestonN** [comment]
I imagine that would still only apply for a subset of channels and would likely miss a large amount of them. Doing a check like would also mean that any non-music video that they release wouldn't have progress saved.

I'd rather not try to isolate these type of videos and suggest that the user simply disables the feature for all videos. It's likely not worth the effort and there's a strong possibility that no solution will be perfect for isolating these types of videos.

**Comment by jasonhenriquez** [comment]
Hi @quantenzitrone, would separation of settings by profile (#1996) fulfill your use case here adequately? If that were to be implemented, you could set your music profile to have the ignore watch progress setting enabled to achieve the same effect.

**Comment by quantenzitrone** [comment]
i don't know, I'm not using FreeTube anymore rn, should i close this issue then?

**Comment by jasonhenriquez** [comment]
That's fine, I think we'll keep this one closed unless other users express interest in such a feature for different use cases.

**Comment by deepspaceaxolotl** [comment]
I would appreciate this as a per-playlist option for music playlists, actually! I have a couple with long videos in it that I don't always finish before restarting the playlist from the beginning. Turning off watch progress isn't really an option since I need it for other videos.

**Comment by deepspaceaxolotl** [comment]
Wondering if this could be reopened? As I'd said earlier, it would be very useful for music playlists!

**Comment by deepspaceaxolotl** [comment]
Although, perhaps reopening #5917 might be better.
