### ISSUE TITLE
Playback crashes when bluetooth is turned off

### ISSUE THREAD

**Issue by Tiltowait2** [FreeTubeApp/FreeTube#1529]
**Behavior of the program**
I often connect an external speaker to bluetooth to do things like listen to podcasts while doing dishes, in the shower, etc.  When I come back to my computer I'm often not finished and want to watch the conclusion on my laptop speakers, as the bluetooth is too loud or I've left it in the kitchen, etc.  When I turn bluetooth off in Windows, the video stops playing and throws a "The media playback was aborted due to a corruption problem or because the media used features your browser did not support." error.  

**Expected behavior**
I expect the audio to switch seamlessly to the laptop's internal speaker, as happens when I watch Youtube videos on youtube.com.

**To Reproduce**
1. Connect an external speaker to bluetooth.
2. Start a video playing.
3. Turn off bluetooth in Windows settings.  

**Link to video**
All

**Screenshots**
N/A

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: 8.1
 - FreeTube version: v0.13.2 Beta
 - Installation Method (If applicable): exe
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment]
I have no idea about this topic. If someone with some experience could chip in to clarify how this could be related, I'd be very happy

**Comment by Tiltowait2** [comment]
No other software on my machine crashes when bluetooth is turned off.  It's only FreeTube.

**Comment by GilgusMaximus** [comment]
Okay, this could be a problem with Electron itself. Could you try some electron based software, e.g. another music player?
You can find a list of software over at electron: https://www.electronjs.org/apps

**Comment by LynHyper** [comment]
Going to chime in and say I'm facing a similar issue with bluetooth headphones, I'm using Museeks which is electron based and it's never had issues so I don't think it's electron, I think it's the video player in FreeTube.

If the headphones are disconnected after I pause a video and no other audio device exists, video playback will fail with no error; it just shows the very next frame after resuming playback and then nothing else, I think the video player in FreeTube is expecting an audio device, but, it won't look or connect to another one so video playback simply halts because of a lack no audio device to use.

**Comment by GilgusMaximus** [comment]
Okay thanks for the info.
So we basically have to look for a solution. Could be possible that VideoJS itself provides a possibility, if it is the player.

**Comment by LynHyper** [comment]
Correction,

In Museeks, disconnecting bluetooth headphones while a song was paused causes Museeks to not send any audio to the headphones when unpaused, electron could still be a cause or Museek and FreeTube treat audio devices similarly. My previous attempts involved removing and adding the headphones _before_ a song was played hence why this issue never occured before.

**Comment by Tiltowait2** [comment]
This still happens in v0.16.0 Beta. :(
