### ISSUE TITLE
Freetube Doesn't Show Subscriptions On Launch

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [FreeTubeApp/FreeTube#1532]
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**
Please write a clear and concise description of what the bug is.

**Expected behavior**
Please describe clear and concise what you expected to happen.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to '...' Freetube-Nightly-blahblahblah.AppImage
2. Click on '....' What I've Gone two (twice)
3. Scroll down to '....' Settings
4. See error Note that "hide active subscriptions is" turned OFF...I have to turn it on and back off for subscriptsion to show

**Link to video**
If you refer to a problem which occurs within a specific video, or a range of videos, please link at least one here.

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.
![Screenshot_20210719_202439](https://user-images.githubusercontent.com/577091/126257352-4771e15d-f7c2-4eef-9b66-62a996532442.png)

**Environment Information (please complete the following information):**
 - OS: [e.g. Windows, Mac, Ubuntu, Fedora, Arch, etc.] Manjaro
 - OS Version: [e.g. Windows 10, Ubuntu 20.04} There was a full system update a couple days ago, so I don't know
 - FreeTube version: [e.g. 0.9.0, Nightly build?] 13.1.966 or something
 - Installation Method (If applicable): [e.g. Portable, .exe, .deb, .AppImage, FlatHub]
 - Primary API Used: [Local API, Invidious API] Local

**Additional context**

**Comment by GilgusMaximus** [comment]
What happens when you press the refresh button?

**Comment by neurodiverseEsoteric** [comment]
For subscriptions?

**Comment by hsvallfors** [comment]
I have a similar issue, which is that the nighly shows "Trending" and "Most Popular" even though I turned them off. Toggling the setting in the menu works, but after starting it's wrong. I'm using v0.13.2-nightly-1006 Beta from deb.

**Comment by GilgusMaximus** [comment]
@hsvallfors please refer to #1504 

@neurodiverseEsoteric Ah, sorry, I misunderstood your problem.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is still happening to u in the latest nightly build?

**Comment by neurodiverseEsoteric** [comment]
It's an issue with the stable 14.x.x release

**Comment by neurodiverseEsoteric** [comment]
@GilgusMaximus hideActiveSubscriptions is set to false in settings.db

Sorry for the late replies...

**Comment by neurodiverseEsoteric** [comment]
It might be a rendering issue, because when I flip the "hide active subscriptions" setting on/off, the layout sort of that section in the sidebar sifts a little...

**Comment by neurodiverseEsoteric** [comment]
Another discovery: The app doesn't launch respecting "Hide Trending Videos" or "Hide Popular Videos" being switched on as well.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@neurodiverseEsoteric just checking in to make sure this is still an issue for u in v0.17.1

**Comment by BeatLink** [comment]
Not the author but I've been experiencing this issue and it seems to have been rectified
