### ISSUE TITLE
DASH format does not load

### ISSUE THREAD

**Issue by tiany4** [FreeTubeApp/FreeTube#1533]
**Behavior of the program**
DASH format doesn't work in any video I've tried.

**Expected behavior**
DASH format should load and quality higher than 720p should be available.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any video
2. Choose DASH format
3. The video reloads and immediately reloads again back to legacy

**Screenshots**
![image](https://user-images.githubusercontent.com/14116340/126347985-653d656f-cc20-4c45-b1e0-817f30322a6c.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10, latest update
 - FreeTube version: 0.13.2 Beta
 - Installation Method (If applicable): Portable
 - Primary API Used: Local API but have tried both

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hmm i tried to reproduce this but i cant.

**Comment by GilgusMaximus** [comment]
The error in the screenshot is from the Invidious API.

There was an error with dev mode not being able to play dash due to some weird bug after an update. The fix is already in the nightlies, so you could try the newest nightly version of the portable and check whether that fixed the problem

**Comment by tiany4** [comment]
> 
> 
> The error in the screenshot is from the Invidious API.
> 
> There was an error with dev mode not being able to play dash due to some weird bug after an update. The fix is already in the nightlies, so you could try the newest nightly version of the portable and check whether that fixed the problem

So I have tried the nightly build `v0.13.2-nightly-1005 Beta`. I am able to play dash. The quality tends to drop somewhat often, and it seems like videos do not go over 720p. Is that the correct behavior?

**Comment by GilgusMaximus** [comment]
Please see #595. These are all related to the same issue with the VideoJS plugin.

The 720p issue is not related tho. Videos, if available, should always go to 1080p with dash, some even > 1080p

**Comment by tiany4** [comment]
I messed around some more. I experience the same issue as the top screenshot if I choose https://yewtu.be as the instance, but https://invidious.snopyta.org does not have the same issue.

**Comment by GilgusMaximus** [comment]
No please don't. We are very well aware of it but no solution attempt from our side has yet worked as the plugin handling this or VideoJS can still do their own stuff under the hood.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @tiany4 can u try a nightly build and tell me if u still have this problem?
