### ISSUE TITLE
Full window shortcut

### ISSUE THREAD

**Issue by elig0n** [FreeTubeApp/FreeTube#1538]
**Describe the solution you'd like to see implemented**
Implement a shortcut key to toggle full-window mode. i.e. `w`

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Related comment from the dev:

https://github.com/FreeTubeApp/FreeTube/issues/814#issuecomment-735803400

**Comment by PrestonN** [comment]
We are currently using `S` as a keyboard shortcut for full window

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PrestonN this is not described in the documentation maybe thats the reason this issue was opened. i would recommend to add it to the docs https://docs.freetubeapp.io/usage/keyboard-shortcuts/
