### ISSUE TITLE
Contributes that open an issue but don't follow the provided template

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1541]
**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [x] Contribution
- [ ] Languages
- [ ] Setup
- [ ] Other. Please specify:

**Discussion**
I think that this is a real problem. Over the past few weeks i noticed allot of people opening bug reports or feature requests without following the template properly.

When the provided template isnt used its hard to understand why the contributor thinks its a good feature to implement or how to reproduce a bug or something like this.

Because this happens the devs need to ask this questions to really understand whats happening or what it is they want and why they want it.

This takes up allot of time for u guys.

In my opinion there need to be a rule or something that the template must be followed otherwise it just get closed or something.

in the contribution guidelines (readme) u cant find anything about following the template.

And in the readme of templates themself there is inconsistency.

> Also please leave all headers except this one in the issue, so that it is clear what belongs where.

I could only find this in the template of feature request. I cant find anything in the others.

Ofcourse there can be some value in the issue u opened up but it isnt that hard to describe it right?

**Comment by GilgusMaximus** [comment]
I mean yes. We have also debated this a bit in the past, but not so much recently. 
Imo it is good to enforce certain rules, but it would be even better if Github provided a way to lock text in issues. Like providing the template as a form that is filled in rather than a complete free text field

**Comment by ChunkyProgrammer** [comment]
Maybe adding this action could help? https://github.com/marketplace/actions/auto-close-issues

**Comment by GilgusMaximus** [comment]
Interesting. Thanks for the link !

**Comment by ChunkyProgrammer** [comment]
> template as a form that is filled in rather than a complete free text field

I just found this
https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
