### ISSUE TITLE
Loading even when there's enough data in the buffer

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#1548]
**Behavior of the program**
Video stops and show the loading icon, but the buffer is far from being empty.

**Expected behavior**
Video plays until buffer is actually empty.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any video
2. Play it

**Screenshots**
![Screenshot_20210726_134306](https://user-images.githubusercontent.com/22192600/126983741-4d4321ec-5cf6-4a0f-9582-e9bf038cb6f2.png)

**Environment Information (please complete the following information):**
 - OS: debian
 - OS Version: buster
 - FreeTube version: v0.13.2 Beta
 - Installation Method (If applicable): .deb
 - Primary API Used: both

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@stemy2 did https://github.com/FreeTubeApp/FreeTube/discussions/1885 fix it for u?

**Comment by peepopoggers** [comment]
node-ytdl-core is not fixed yet i think

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
If I right-click on “Show video statistics”, the info box shows that 3% of video is buffered and the loading bar shows a far ahead buffered duration, still the video playback hangs.

> is not fixed yet i think 

Yes, is not fixed yet. 

> we are using a temporary branch that fixes this issue

No, still Issue in FreeTube version: v0.16.0 Beta

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Still relevant

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @stemy2 @vk0xOrg we have migrated away from the dependency that presumably caused this issue. Could u test out [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds) to confirm this issue is resolved?

**Comment by stemy2** [comment]
Could you reopen the issue ? It happened again.
