### ISSUE TITLE
x86 (win xp) support + classic windows theme

### ISSUE THREAD

**Issue by shikulja** [FreeTubeApp/FreeTube#155]
need support x86 (winxp) because on weak laptops - playing video youtube problem (browsers require a lot of resources), this program is a good solution.
Also, I ask you to add the support of normal classic windows themes, they are familiar than an attempt to imitate android.

**Comment by PrestonN** [comment]
Hi there, unfortunately Electron does not support Windows XP, and I do not personally support 32 bit builds.  If you'd like a lightweight website, you should give https://invidio.us/ a try.

I could argue that the design is similar to modern Windows themes, which keeps it in line with other applications.  The goal was to make the design similar to YouTube to keep some familiarity when transitioning to FreeTube.  I don't plan on changing this, however I should have support for third party themes at some point in the future.

On a side note: I'd highly suggest that you move away from Windows XP.  It's long past support at this point.  If you can't upgrade your laptop, I would look at a lightweight Linux Distribution to get modern security and applications.
