### ISSUE TITLE
Add 600% Sound Volume-like functionality to FreeTube

### ISSUE THREAD

**Issue by RagglenLove** [FreeTubeApp/FreeTube#1551]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Sometimes, content creators on YouTube upload videos where the volume is too low. One such example is this video: https://www.youtube.com/watch?v=sRaXqaji8Ag.

**Describe the solution you'd like to see implemented**
I’d like to see SoundFixer-like functionality added to FreeTube. SoundFixer is a Firefox addon that allows you to increase the volume of a YouTube video past 100%, it is useful for videos where the volume is too low. Here’s the link to the addon: https://addons.mozilla.org/en-US/firefox/addon/soundfixer/

**Screenshots**
![Screenshot_2021-07-28_18-53-15](https://user-images.githubusercontent.com/45503845/127313067-b49d3715-9973-48db-ab9c-86ca8d0aa88b.png)
Screenshot of SoundFixer's interface.

**Comment by GilgusMaximus** [comment]
But you could also increase the volume of Freetube in the sound mixer of your OS and leave every other app as is.
Wouldn't that solve the problem?

**Comment by RagglenLove** [comment]
> But you could also increase the volume of Freetube in the sound mixer of your OS and leave every other app as is.
> Wouldn't that solve the problem?

Yes, but I have encountered issues with using my OS's sound mixer when I tried to increase the volume of a YouTube video on Firefox, if you pause or forward the video, the volume goes back to it's default low volume, which is why I installed SoundFixer to begin with.

Also, SoundFixer works on a per-video basis, so for example, if you are playing two videos, one with low volume and one with normal volume, switching in between the two videos, using my OS's sound mixer makes the video with the normal volume very loud, so using SoundFixer fixes this issue.

**Comment by GilgusMaximus** [comment]
Okay, but that is an issue with your operating system.
I am not too sure this would be very helpful for many people.
You could also use something like VLC as external player and have it's audio features, effects and more available

**Comment by NineXYZ** [comment]
For me this makes sense...
Using VLC is too complicated for only increasing the volume and at least in macOS there isn't a per app volume setting.

**Comment by RagglenLove** [comment]
Found a better alternative to SoundFixer, it's called 600% Sound Volume.
Here's the link to the addon: https://addons.mozilla.org/en-US/firefox/addon/600-sound-volume/

![Screenshot_2021-08-21_09-26-28](https://user-images.githubusercontent.com/45503845/130306425-c67f5073-fef5-4604-81b1-ea4b505e7fde.png)
Here's the inferface.

> For me this makes sense...
> Using VLC is too complicated for only increasing the volume and at least in macOS there isn't a per app volume setting.

I agree, FreeTube should natively have this kind of functionality, why make a user use something else? It seems counterintuitive to me and also, it makes FreeTube user friendly to un-technical people who may not know how to use their OS's sound mixer or VLC.

**Comment by arrowgent** [comment]
i agree here, id love a secondary GAIN booster to over 100% my audio

`LINUX`
already i have system audio set to 100%
in MPV i set my max to 150%, 100% being ideal, higher is a gain above normal and only needed rarely.
_many many many_ videos on FreeTube are quiet by comparison to 100% in MPV or in chromium

so id love a tool or feature built into Freetube to handle toggling higher audio output volume

maybe for comparison someone could look at open source GPL of VLC & MPV to see how they handle it?

**Comment by mxvin** [comment]
I propose changes on https://github.com/FreeTubeApp/FreeTube/blob/2be2301d92e37d13a4839ded1fc436836292b7d4/src/renderer/components/ft-video-player/ft-video-player.js#L1029-L1040

- adding gain function https://stackoverflow.com/posts/46264832 which is handle video DOM to AudioContext API
- adding that gain function to handle `( newVolume > 1 ) ? ` logic
- Videojs wise, i'm not quite sure how to elegantly handle this especially afaik videojs does not allow volume > 1.0 , so needs a bit hackaround on videojs UI side to make it accept >1 value (modification both videojs js+html)

Or, A Quick way, just make another button and slider outside videojs, and hook that to "gain volume" function independently.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
In v0.22.0 we have introduced support for YouTube's `Stable Volume` feature on the Local API. You can find this setting in the video player

Are the videos that were perceived as too quiet okay when you turn this setting on like this:


https://github.com/user-attachments/assets/aa99b494-c114-4715-9c21-c4444f02bcc1

**Comment by tintin67** [comment]
Freetube audio volume is definitely lower compared to Minitube after trying several videos to test this.  If Minitube can do this.  If Minitube can do this, this could be an added functionality in Freetube ?

**Comment by checktext00** [comment]
I also would like to see a 200% volume option (similar to VLC) without requiring leaving the FreeTube app

**Comment by ARipeAppleByYoursTruly** [comment]
Would still like to see a way of boosting volume past 100% at the end user side, Youtube's Stable Volume is not always available in every video

Also this issue should be reopened, or allow opening a singular new issue for discussion etc. New issues getting closed as duplicates of this one yet seeing no movement on whether this feature is planned or not is kinda a loose end, not to mention no response from OP

Maybe we need a call to action to have this feature finally be recognized as having some public interest? Might as well try. If the devs find this not adhering to guidelines, feel free to hide or delete this comment

<br>
<br>

If you as the user of Freetube is reading this, and want a feature where
- You have the control of boosting the video player's volume over 100%, because some videos are just that quiet, and
- Not depend on Youtube's Stable Volume that may or may not be there for the video you want to watch

Consider upvoting this comment to show that yes, we do want this feature in Freetube

And please don't add comments that echoes that same "I want this too", or "+1!" feeling. The devs are very adamant on marking similar comments as duplicates or spam, as seen in all the "video player can't play/got blocked" issues
