### ISSUE TITLE
Visual bugs

### ISSUE THREAD

**Issue by qweasddsaewq** [FreeTubeApp/FreeTube#1556]
**Behavior of the program**
1. Weird distorting visual glitch
2. Playing video becomes dark red for about one second then normal again for one second repeatedly

**Expected behavior**
Neither should be happening

**To Reproduce**
Distorting glitch:
- Automatically occurs and worsens before resetting randomly when a video is playing
- Happens when hovering mouse over a button when a video has loaded (can either be playing or paused, as long as it's started; happens in both fullscreen and non-fullscreen)
- In fullscreen, happens in every tab when hovering mouse over a button
Video's color bug: Happens when any video is playing

**Screenshots**
![1](https://user-images.githubusercontent.com/88226261/127733026-5c618057-65ac-4304-b43b-d0dab964c102.png)
![2](https://user-images.githubusercontent.com/88226261/127733030-269a798d-7fcf-4233-bdef-400457903e44.png)

**Video**
https://mega.nz/file/2dcwXJ4I#jB617i1lV2EjubSTL1K8aBwyZM96qZvO-yLZTBy7xb0
(File is too big to be uploaded)

**Environment Information:**
 - OS: Windows
 - OS Version: Windows 10 19043.1110
Windows Feature Experience Pack 120.2212.3530.0
 - FreeTube version: 0.13.2 beta
 - Installation Method (If applicable): Both portable and installed
 - Primary API Used: Invidious API; same problem with Local API

**Additional context**
Has happened since first installed/downloaded. Video's color bug did not happen for a few days after a OS reinstallation, however started occurring again after

**Comment by GilgusMaximus** [comment]
Only thing I could imagine here would be that hardware acceleration fails completely.

**Comment by PrestonN** [comment]
That's a new one that's for sure.

Issues like this tend to be difficult to pinpoint as the issue tends to be something outside of our control. Typically the issue could be something about your video drivers or hardware or something else entirely. I'd be curious if you have this issue on other Electron based apps before we try to dive too deep into figuring this out.

**Comment by GilgusMaximus** [comment]
As Preston mentioned, another Electron based application might reveal whether it is Electron itself.
Here is a list of possible Electron based apps if you do not have any others installed at the moment and would like to test this https://www.electronjs.org/apps

**Comment by qweasddsaewq** [comment]
It does have something to do with Electron, I suppose. I got the Youtube Music desktop app off of the above website and it has the same problems.
![Screenshot (24)](https://user-images.githubusercontent.com/88226261/128611168-3434432b-2437-46d3-9a4c-52615fa710a2.png)

**Comment by qweasddsaewq** [comment]
I managed to solve it by changing compatibility setting to a previous version.
