### ISSUE TITLE
Ubuntu 20.04.2 LTS FreeTube File Not Supported

### ISSUE THREAD

**Issue by AA-Coder-Beg** [FreeTubeApp/FreeTube#1561]
**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [X] Other. Please specify: 

**Question**
Why does FreeTube repeatedly fail to install on my Ubuntu machine? As stated in the title, my Ubuntu version is 20.04.2 LTS. I had tried both versions of the Linux download files, to which both stated that they "aren't supported". 

Someone had this same issue earlier, in July 2, with the same Ubuntu version, but they did what anyone in the CS field would hate: state that the problem has been fixed/figured out, without explaining how. 

Edit: By linux downloads, I meant both the Debian x64 and the Debian arm64 files

**Comment by ChunkyProgrammer** [comment]
Are you installing the deb file or a different one?

**Comment by AA-Coder-Beg** [comment]
> Are you installing the deb file or a different one?

I tried the regular deb 64-bit download, and the arm64 version of the deb download. I'll fix my post

**Comment by ChunkyProgrammer** [comment]
I found this post on stackoverflow that might help https://askubuntu.com/questions/1232868/problem-installing-deb-in-software-install-ubuntu-20-04

**Comment by GilgusMaximus** [comment]
I had no problems installing it on my Ubuntu 20 a few weeks ago. I downloaded the .deb file and it worked. But it was a clean install before, so there might be something in your configuration preventing the installation. @ChunkyProgrammer thanks for the link

**Comment by AA-Coder-Beg** [comment]
> I found this post on askubunutu that might help https://askubuntu.com/questions/1232868/problem-installing-deb-in-software-install-ubuntu-20-04

Thank you so much! I finally got FreeTube thanks to the gdebi package installer!
