### ISSUE TITLE
Keyboard Shortcut for Picture in Picture

### ISSUE THREAD

**Issue by ant0n-anon** [FreeTubeApp/FreeTube#1564]
No shortcut for picture in picture

**Describe the solution you'd like to see implemented**
Copy YT shortcut "i" for miniplayer (picture in picture)

**Describe alternatives you've considered**
Right now i have to alt tab and mouse click

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Related comment from the dev:

https://github.com/FreeTubeApp/FreeTube/issues/814#issuecomment-735803400

**Comment by PrestonN** [comment]
We already have `D` assigned as a keyboard shortcut for PiP.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PrestonN this is not described in the documentation maybe thats the reason this issue was opened. i would recommend to add it to the docs https://docs.freetubeapp.io/usage/keyboard-shortcuts/
