### ISSUE TITLE
Native PiP on macOS

### ISSUE THREAD

**Issue by ThatIsAPseudo** [FreeTubeApp/FreeTube#1566]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
The PiP mode currently implemented in FreeTube looks like it is not "native" on macOS, as it does not behave the same way as the one Safari or iina use. 
For now it is more like a floating window with an "always on top" mode which is repeated on every destkops and does not integrate properly with the system UI.

**Describe the solution you'd like to see implemented**
Here are the features of the "native" macOS PiP :
- snap video in a corner
- hide the video behind the border of the screen (see Safari's video below at 0:20)
- video actually follows the view when changing between desktops, instead of being kind of stuck to the desktop (which means there is no visual interruption of the video when swiping between desktops)
- does not hide notifications : when the video is snapped in the upper-right corner notifications will appear below it, as well as the notification center which automatically slides all widgets downward to fit with the video

Tbh I don't know if implementing such features is feasible since it must require access to the system UI API, which may not be accessible through Electron. I wanted to point these differences out though.

**Describe alternatives you've considered**
Using iina or Safari to watch youtube videos

**Screenshots**
(Videos not showing all features described previously, only points 1 and 2)

Here is Freetube's PiP behaviour :

https://user-images.githubusercontent.com/17936055/128530829-56bf9a26-3e48-4ab4-81b2-4ef93b4acb8a.mp4

and here is Safari's :

https://user-images.githubusercontent.com/17936055/128531760-7327dcf7-ee46-497d-a8c3-016a328bd360.mp4

**Additional context**
I found these Github repos : [BetterPiP](https://github.com/Capevace/BetterPiP) aimed at building a PiP feature for Firefox and Chrome when they didn't have one, it's based on [PiPHack](https://github.com/steve228uk/PiPHack). Maybe this could help.
By the way, Chrome and Firefox current PiP behave as FreeTube's one.

**Comment by GilgusMaximus** [comment]
Sorry, but we are not gonna implement a custom pip implementation. We are using the once Electron provides and that is it. Even if we added third party solution, it should be a solution that works for all operating systems

**Comment by ThatIsAPseudo** [comment]
Fair enough, thank you for clarifying.
