### ISSUE TITLE
libnss3.so is missing from the AppImage

### ISSUE THREAD

**Issue by Hund** [FreeTubeApp/FreeTube#1570]
I just downloaded the AppImage version 0.13.2 on my computer with Gentoo and was greeted with this when I executed the file:

```
$ ./freetube_0.13.2_amd64.AppImage 
/tmp/.mount_freetuMX4xJw/freetube: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

What's wrong?

**Comment by GilgusMaximus** [comment]
This should not be an issue with our app but a missing library on your system. 
https://github.com/symfony/panther/issues/7

**Comment by Hund** [comment]
I see. I'm not really experienced with alternative installation methods like AppImages. I assumed that everything that was needed would be included in the image itself.

Anyway. The missing package is named `dev-libs/nss` in Gentoo. Installing it solved the issue.

Thank you!
f
