### ISSUE TITLE
In small window, *** popup displays under video timeline

### ISSUE THREAD

**Issue by peepo5** [FreeTubeApp/FreeTube#1571]
![image](https://user-images.githubusercontent.com/72892531/128615261-14dcc168-add2-4b96-8b3d-f2ece040e0a7.png)

Some z-ordering issue

1. Make window small enough that three dots appears
2. Expand the menu and hover over a playing video
3. The menu will go behind the timeline

Latest vers.

**Comment by rwinkhart** [comment]
I believe this is fixed. I am not able to replicate this behavior in the latest version.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@peepo5 is it possible for u to also confirm this?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I can confirm that this bug doesnt persist anymore
