### ISSUE TITLE
Comments do not load "TypeError: Cannot read property 'continuationContents' of undefined"

### ISSUE THREAD

**Issue by Techngro** [FreeTubeApp/FreeTube#1574]
**Behavior of the program**
When I click on "click to view comments", the comments do not load and it gives multiple error messages.

**Expected behavior**
Comments should load

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any video
2. Click on 'click to view comments'
3. See error

**Link to video**
Happens on all videos

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7982763/128693181-40136f03-2557-42e9-9cef-d0f1617b5ae0.PNG)

**Environment Information (please complete the following information):**
 - OS: Windows 
 - OS Version: Windows 10
 - FreeTube version: v0.13.2 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment]
Use the nightly version please

**Comment by AA-Coder-Beg** [comment]
> Use the nightly version please

Can you send a link to the Nightly version? I'm having difficulty finding it.

**Comment by Techngro** [comment]
> > Use the nightly version please
> 
> Can you send a link to the Nightly version? I'm having difficulty finding it.

https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml
