### ISSUE TITLE
Link documentation in readme.md

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1586]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Everything is well documented in the readme but i didnt see any link to the documentation. The ways u can get to the documentation atm is trough ur website or in the about page in the application.

**Describe the solution you'd like to see implemented**
To keep this uniform i recommend to also add it in the readme.

https://docs.freetubeapp.io/

**Describe alternatives you've considered**
None.

**Screenshots**
None.

**Additional context**
None.

**Comment by comradekingu** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
https://github.com/FreeTubeApp/FreeTube/pull/1278/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R51 ?
