### ISSUE TITLE
Paragraphs in comments

### ISSUE THREAD

**Issue by orthand** [FreeTubeApp/FreeTube#1588]
**Behavior of the program**
Paragraphs in the comment section are missing.
![image](https://user-images.githubusercontent.com/62552927/129486188-af040e58-90d8-43da-928f-6c3b427a56cf.png)

**Expected behavior**
Comments include paragraphs to make them easier to read.
![image](https://user-images.githubusercontent.com/62552927/129486200-0625e267-76e7-44e2-9c8e-289c54325abe.png)

**Link to video**
Example pictures are from an [LTT video](https://www.youtube.com/watch?v=LFC2t5I_hLA).

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 Education, 20H2
 - FreeTube version: v0.13.2-nightly-1020 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Comment by ChunkyProgrammer** [comment]
I don't think I'll have time to work on this but for whoever does work on this: I think this issue is caused by #1342.
