### ISSUE TITLE
How do I stop the endless 404 errors that started popping up?

### ISSUE THREAD

**Issue by Tiltowait2** [FreeTubeApp/FreeTube#1590]
**Behavior of the program**
A few days ago, I started getting a ton of "Local API Error: (click to copy) Status code 404" errors.  When I click to copy, I just get "Status Code 404".  What causes these errors?  Has Youtube gone on another ban wave and banned some of my channels?  If so, how would I find out which ones, so I can remove them and stop these errors?

**Expected behavior**
I would like to know which channel doesn't exist on a 404 error.

**To Reproduce**
Click "refresh".  

**Link to video**
I don't know which ones are causing the problem; not enough information is available.  

**Screenshots**
n/a

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: 8.1
 - FreeTube version: v0.13.2 Beta
 - Installation Method (If applicable): exe
 - Primary API Used: Local API

**Comment by jasonhenriquez** [comment]
This is indeed occurring because of subscriptions to non-existing (likely banned or removed) channels. Although it may not always be possible to recover a channel name for every non-existing subscription, I am working on a fix that will replace all of those errors with a singular prompt that will allow the user to unsubscribe from all non-existing channels with one click.

**Comment by rootedetc** [comment]
Any updates on this? 
https://i.imgur.com/v1zfV0y.png

**Comment by jasonhenriquez** [comment]
@rootedetc [First my change to the local API to explicitly identify banned or removed channels has to be approved here.](https://github.com/FreeTubeApp/yt-channel-info/pull/46) Then I will make a PR in this repository to handle that case and allow users to unsubscribe from the non-existent channels that they subscribe to in a single button click.
