### ISSUE TITLE
Cannot load comments (Europe)

### ISSUE THREAD

**Issue by cihlarma** [FreeTubeApp/FreeTube#1595]
**Behavior of the program**
When trying to load comments on any video, an error occurs and no comments are loaded:

(Local API) "Error: Request failed with status code 405"
(Invidious API, tried with: yewtu.be, invidious.snopyta.org and vid.puffyan.us) "undefined"

**Expected behavior**
Comments are loaded when clicking on "Click to View Comments".

**To Reproduce**
1. Go on any video with comments enabled.
2. Click on "Click to View Comments".
3. Error appears, no comments are loaded.

**Environment Information (please complete the following information):**
 - OS: Debian
 - OS Version: Bullseye
 - FreeTube version: 0.13.2
 - Installation Method (If applicable): .deb
 - Primary API Used: Local API

**Additional context**
I am in Europe in case that makes any difference.

**Comment by ChunkyProgrammer** [comment]
Are you using the nightly version?

**Comment by cihlarma** [comment]
> **Environment Information (please complete the following information):**
> [...]
> FreeTube version: 0.13.2

No. :wink: Is this a known issue fixed in Nightly builds?

**Comment by cihlarma** [comment]
Actually, stupid question to ask. I've tried out the latest nightly build, all is working. I assume I ought to either use that build or wait for the next release to view comments in the app.
