### ISSUE TITLE
[MacOS Big Sour] Freetube window has disappeared during runtime.

### ISSUE THREAD

**Issue by cocoonkid** [FreeTubeApp/FreeTube#1596]
**Behavior of the program**

[MacOS] Freetube window has disappeared during runtime.
I restarted freetube but the window is still not appearing.
It is listed in the context-menu though.

**Expected behavior**
To see the freetube window.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Start freetube

MacOS Big Sour  11.5.1
Freetube 13.2. Beta

**Additional context**
It worked for months just today the issue appeared.

I tried reinstalling via brew  and also have restarted my macbook.

EDIT: I was able to triage the problem down to the settings.db

If I used the below settings.db it won't show me the view.

Now it works again and I will just manually set everything anew.

```
❯ cat settings.db
─────────────────────────────────────
{"_id":"autoplayPlaylists","value":false}
{"_id":"autoplayVideos","value":false}
{"_id":"backendFallback","value":true}
{"_id":"backendPreference","value":"local"}
{"_id":"barColor","value":true}
{"_id":"bounds","value":{"x":0,"y":872,"width":1,"height":28,"maximized":false}}
{"_id":"checkForBlogPosts","value":false}
{"_id":"defaultPlayback","value":"1.25"}
{"_id":"defaultQuality","value":"720"}
{"_id":"defaultVideoFormat","value":"dash"}
{"_id":"enableSearchSuggestions","value":true}
{"_id":"forceLocalBackendForLegacy","value":false}
{"_id":"hideActiveSubscriptions","value":true}
{"_id":"hideChannelSubscriptions","value":true}
{"_id":"hideCommentLikes","value":true}
{"_id":"hideLiveChat","value":true}
{"_id":"hidePlaylists","value":false}
{"_id":"hidePopularVideos","value":true}
{"_id":"hideRecommendedVideos","value":true}
{"_id":"hideTrendingVideos","value":true}
{"_id":"hideVideoLikesAndDislikes","value":true}
{"_id":"hideVideoViews","value":true}
{"_id":"invidiousInstance","value":"https://invidio.xamh.de"}
{"_id":"playNextVideo","value":false}
{"_id":"proxyVideos","value":false}
{"_id":"region","value":"de"}
{"_id":"uiScale","value":75}
{"_id":"useRssFeeds","value":true}
{"_id":"useSponsorBlock","value":true}
```

**Comment by RadLukas** [comment]
How did you fix it? I have the same issue.. Tried a lot of things (restarting, redownloading, older version etc.). Thanks in advance! Did you alter anything in settings.db? How do you access settings.db?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @cocoonkid just checking in. Is this still an issue for u on v0.17.1?
