### ISSUE TITLE
Correct Syntax for freetube://

### ISSUE THREAD

**Issue by Coderdude112** [FreeTubeApp/FreeTube#1598]
Hello!

I am developting an aplication and am woundering what the correct syntax for using freetube:// is.
I see that this is a thing due to commit 78324ff775349b78ad52066d49e864b409cb3b0f but I can't figure out how to use it.

Thanks for your help in advance

**Comment by PrestonN** [comment]
The correct syntax would be to simply include the YouTube / Invidious URL after the protocol handler. This is regardless of what type of URL it is. It will be sent to FreeTube and be handled from there. If FreeTube doesn't handle the URL properly, then it'd be an issue that we would have to fix.

Example use:

```
freetube://https://youtu.be/hKqVvXTanzI
```

Let me know if you have any further questions.

**Comment by Coderdude112** [comment]
Thanks!

One more thing, I can use the link you gave me if I put in my browser, but when I try and load it from electron I get the freetube homepage. This is what I'm using:

```js
require("electron").shell.openExternal("freetube://https://youtu.be/hKqVvXTanzI");
```

**Comment by PrestonN** [comment]
Hmm. I just attempted to run that line in a dev build and it seemed to run fine. What OS and installation method is your install of FreeTube? If the homepage is showing up, something might be going on with how FreeTube is handling the URL, but it's working on my end so I'm not sure.

**Comment by Coderdude112** [comment]
Well alright then.

I'm on Arch Linux using 0.13.2-1 Freetube from the AUR so that's probably what's going on. So...

**Comment by PrestonN** [comment]
Ahh, that might be it. We do not bundle the binaries that are put on the AUR and I believe the use with the `freetube://` protocol is something that the maintainers have not implemented. Having said that, if it worked in the browser then that kinda contradicts my statement. Could you attempt using a build that we bundle (Most likely Flatpak, based on your system) and see if that works any better?
