### ISSUE TITLE
Remove the kde dependencies from .deb

### ISSUE THREAD

**Issue by ilu33** [FreeTubeApp/FreeTube#160]
Somebody please remove the kde dependencies from the deb package - installing 30+ packages, basically the whole KDE, can really bugger up a non-kde system!

**Comment by PrestonN** [comment]
I actually don't use KDE, so I'm not sure as to why KDE dependencies would be included or how to get rid of them.  Hopefully someone else has some insight on this.

**Comment by ilu33** [comment]
Depends upon how you create the .deb package. Manually?
Or is this line involved:
`"make:linux:x86:deb": "electron-forge make --platform=linux --targets=deb --arch x64",`
?

**Comment by PrestonN** [comment]
Yes I do builds manually with electron-forge.  I have not added anything into my config files that would include these as dependencies.  The only thing that I can think of is that I might be using some dependencies that are dependent on the KDE tools, but I don't know which packages would be using them.

**Comment by ilu33** [comment]
Non of those mentioned.

**Comment by ilu33** [comment]
I think this is the culprit: [https://github.com/unindented/electron-installer-debian/blob/d6d70546997012f4e8743d38325c5a75eae0c9c2/src/dependencies.js] - its hardcoded - [insert random swearword]. You should open an issue there. In the meantime the only way is to change the control file per hand.
