### ISSUE TITLE
Clicking YouTube shorts links gives the error "Unknown YouTube url type, cannot be opened in app"

### ISSUE THREAD

**Issue by AllanDannUnder** [FreeTubeApp/FreeTube#1604]
When clicking YouTube Shorts links from external sources, instead of FreeTube loading the video, it gives the error "Unknown YouTube url type, cannot be opened in app". 

A quick way to fix this would be to redirect YouTube Shorts URLs to normal YouTube video URLs, as shown below:

* **YouTube Shorts URL:** https://youtube.com/shorts/MS82yTaKRjQ?feature=share
* **Converted YouTube video URL:** https://youtu.be/MS82yTaKRjQ

**Comment by ChunkyProgrammer** [comment]
I can take a look at this
