### ISSUE TITLE
Lessening of colors in utility buttons and across app

### ISSUE THREAD

**Issue by peepo5** [FreeTubeApp/FreeTube#1609]
## Previews
I have some opinions on the appearance of buttons on the video page.

In my opinion, the utility buttons should not be colored to the users config color. Instead they should be the same as the current 'star' background color. Also on hover they should not make the config color appear either.
IMO this just gives it a much cleaner look than the config color.

Preview with my squaring PR added + shadow change (#1607):
(border radius 22% with box-shadow config -> `0 0.8px 4px rgb(0 0 0 / 50%)`)
![image](https://user-images.githubusercontent.com/72892531/130700089-d61b7b44-a705-487f-871c-0333163a5b77.png)
^ My favorite design choice ^

For reference, above but without shadow change (IMO this vers looks worse):
![image](https://user-images.githubusercontent.com/72892531/130700457-a271b017-3083-4f7a-9d7b-bc0f050f7215.png)

Preview with current circle design
(box-shadow config -> `0 1px 2px rgb(0 0 0 / 50%)`)
![image](https://user-images.githubusercontent.com/72892531/130700198-07061c65-1a56-454d-92d8-8f09c7914bd8.png)

Preview with current circle design + shadow change
(box-shadow config -> `0 0.8px 4px rgb(0 0 0 / 50%)`)
![image](https://user-images.githubusercontent.com/72892531/130700279-44f16c98-cab9-40a6-aa5a-cd01700bac91.png)
IMO looks too bold if current circle design is kept for these buttons.

## For Reference 
Current design:
![image](https://user-images.githubusercontent.com/72892531/130700553-82a75845-1987-4677-8c14-948c757299a9.png)

Current design + #1607:
![image](https://user-images.githubusercontent.com/72892531/130700591-66ee6ce2-4724-4aa6-a1e4-57d14e1cbea1.png)

## Further Points

In my opinion in both the current circle design and square pr, the white icons blend in with the background color too much and the colors kind of mush together as there is not much contrast. Also this kind of "your config color goes everywhere" ui approach seems kind of tacky. In the above previews the simple, dark buttons look way better in terms of visibility and contrast. I made this an issue and not a pr because I would like feedback on the box-shadow and also if it is a good idea as I could be wrong :)

In addition, the square versions with the dark background color look really sleek and they go well with the design in total.

If you want to replicate, inspect and change css background color of icon buttons from accent color to --card-bg-color

**Comment by peepopoggers** [comment]
A change would also have to be made where the color inverses in cases such as light mode, which happens with the star so it should be easy to replicate. 
![image](https://user-images.githubusercontent.com/72892531/130701024-4ce50f8d-7bdc-42d1-9c54-b0f7d1b8e157.png)

**Comment by peepopoggers** [comment]
+ This could be a togglable option. If so, I think the light blue color should have the icons set to black like what happens with the bg color yellow like below.
![image](https://user-images.githubusercontent.com/72892531/130701136-3eb6eab5-5447-480e-a81f-666f9408a22e.png)
