### ISSUE TITLE
Tor broken with the appimage.

### ISSUE THREAD

**Issue by haydenhughes** [FreeTubeApp/FreeTube#161]
If you try to use tor with the appimage with tor it just constantly loads without doing anything. Just a guess but maybe appimage is blocking the connection? If I clone the repo and use `npm start` tor works as intended. BTW the distro Fedora 28. I haven't tried to replicate the issue on other distros.

**Comment by PrestonN** [comment]
I was able to reproduce the issue.  I will take a look and see what I can do.  I'll update here if I figure anything out.

**Comment by PrestonN** [comment]
This has been fixed and will be included in the next release.
