### ISSUE TITLE
Comments not loading

### ISSUE THREAD

**Issue by nigelpyjamas** [FreeTubeApp/FreeTube#1610]
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**
I've had this problem for about a month, maybe longer, and I don't see anyone mentioning it. I cannot view comments. I get "Error: Request failed with status code 405" then "Falling Back to Invidious API" then "Invidious API error (undefined)." I've tried different Invidious instances, to no avail.

This might be a coincidence, but I started having the same problem on my phone with NewPipe, but the problem disappeared a few weeks later with an update.

This problem appears on both my Linux and Windows machines.

**Expected behavior**
Comments load

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to a video
2. Click on "Click to view comments"
4. See error "Error: Request failed with status code 405" then "Falling Back to Invidious API" then "Invidious API error (undefined)."

**Link to video**
If you refer to a problem which occurs within a specific video, or a range of videos, please link at least one here.

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.

**Environment Information (please complete the following information):**
 - OS: [e.g. Windows, Mac, Ubuntu, Fedora, Arch, etc.]
 - OS Version: [e.g. Windows 10, Ubuntu 20.04]
 - FreeTube version: [e.g. 0.9.0, Nightly build?]
 - Installation Method (If applicable): [e.g. Portable, .exe, .deb, .AppImage, FlatHub]
 - Primary API Used: [Local API, Invidious API]

**Additional context**

**Comment by jasonhenriquez** [comment]
This issue was fixed on July 23rd (in 13d73d2). There have been approximately eight issues about this in the past (seven of which were duplicates of the original, #1490), albeit I can understand that they may be hard to find by looking at the front pages. [Currently, you can use the latest nightly build to use FreeTube with this fix](https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml). This fix will also be included in the next release. I am working with the team to find a better way to expedite these fixes for other users who are unaware or unfamiliar with this process.

**Comment by nigelpyjamas** [comment]
Sorry about that. Please believe me, I really tried searching this github before posting. I'm not sure why they didn't show up. The only one that showed up was one dating back to April, and since it says that the issue would be resolved in the next update (back in April), and that I did not experience that problem back then, I thought it might be a different problem.

I also tried to download a nightly build, but I'm new to Github and I am not very familiar with the interface. When I click on [ GitHub Actions](https://github.com/FreeTubeApp/FreeTube/actions?query=workflow%3ABuild) and click on the first one with a green checkmark, then click on one of the builds under "jobs", I am met with a list of actions, not files. Sorry about that noob stuff. I believe a direct link to nightly builds on the main page could help out newbies like me.

**Comment by jasonhenriquez** [comment]
@nigelpyjamas That's a good suggestion, I'll pass it over to the team. As for how to do it, you can click on any one of those titles (e.g., "Translated using Weblate (Ukrainian)").  On the new page, you can scroll down and see a section labeled "Artifacts" with downloadable links. Download the one suitable for your operating system, and you should be ready to go.

**Comment by nigelpyjamas** [comment]
Thank you so much. I still feel ashamed for not having found that the issue had appeared 7 times before. That is exactly what I was trying to avoid and I failed in the end. I had been waiting for more than a month just to be sure before finally making a github account and posting my problem, but this did not help after all.

Sorry about wasting your time. You can delete this whole issue if you'd like.

**Comment by jasonhenriquez** [comment]
It's all good and no reason to feel bad in the slightest. This is all just more evidence that our system for pushing important bug fixes, closing redundant issues, discovering closed issues, and finding what's already here is consistently not working for dozens of people. This is a deficiency of our own system that you've helped shown light on, and this issue has initiated a team discussion on the opacity. @nigelpyjamas Thank you for putting in the time to make this issue, and I hope you will stick around to keep helping & improving our service.

**Comment by nigelpyjamas** [comment]
Thank you so much for your kind words. I will definitely try to contribute more, and am really thankful to the FreeTube team for all their efforts in giving us back our privacy.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @nigelpyjamas was u able to download the nightly build or were u unable to find it. If i couldn't find it, i can make a screen recording for u.
