### ISSUE TITLE
Outdated Protocol

### ISSUE THREAD

**Issue by TheFloatingBrain** [FreeTubeApp/FreeTube#1611]
**Topic**

Outdated protocol

**Discussion**

The protocol for importing New Pipe Subscriptions appears to be outdated. I think New Pipe uses SQLite3 now instead of JSON to store this data, I don't see an option to export the list of subscriptions as JSON (only sqlite3 .db)

When doing so, categories/groups don't seem to be supported by FreeTube. It would be nice to have the option to put different categories into different profiles.

Also it would be nice to import playlists. I tried to write a script today to do this but it did not seem to work, I may have done it wrong but it seems to delete all but 2 playlists (Favorites, and whatever comes last) :(

You can see what I have attempted to do today here https://github.com/TheFloatingBrain/NewPipeToFreeTubeExportImportScripts

**Comment by TheFloatingBrain** [comment]
> 
> 
> NewPipe outputs the json file when you export
> ![Screenshot_20210825-212802_1](https://user-images.githubusercontent.com/78101139/130885320-a2f750e8-0689-4eca-97ed-178f196eb3ca.png) from the subscriptions page (see https://docs.freetubeapp.io/usage/importing-subscriptions/) but I do like the idea of being able to import the db file to get subscriptions & groups from NewPipe (i don't believe groups are included in the json file.) For importing playlists, custom playlists are not really a part of FreeTube at the moment besides the favorites

Thanks for the reply! Looks like I was looking in the settings menu, but yes. I found out about the unfortunate truth of NewPipe not saving your categories to the .json file a while ago when I used a json backup after spending hours meticulously categorizing my subs. Unfortunately I am unsure if the db file does this either, but it does contain way more info.

I tried to create a json file from the db file, but FreeTube did not accept it (I think this file). I made no attempt to make categories (I was curious if this could be done with the "service_id" field, uploaded here as .txt)

[subscriptions.txt](https://github.com/FreeTubeApp/FreeTube/files/7080919/subscriptions.txt)


Wish I had time to implement playlists for FreeTube, I wonder how long that would realistically take 🤔

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing because the main issue wasnt really an issue. Please create issues for the other things u requested as we dont prefer multiple requests in one issue. 

Note: Please check if there isnt already an open issue for the thing u like to request
