### ISSUE TITLE
Mod/Addon API?

### ISSUE THREAD

**Issue by TheFloatingBrain** [FreeTubeApp/FreeTube#1612]
**Topic**

Addon API

**Discussion**

Didn't want to make a full request of the feature, but wanted to discuss the possibility of interfacing with FreeTube at runtime via a mod/addon script so one can have access too the FreeTube api, and access the full features of the application, maybe just allow modules to be imported, don't design an API, and let people run addons interacting with the interfaces for existing modules? Basically just add an option for "import addon"

It may be helpful for things like what I have been trying to do https://github.com/TheFloatingBrain/NewPipeToFreeTubeExportImportScripts

Just a thought, I didnt hear about FreeTube until yesterday, but with all the things people probably want to interact with, and going through the source code, I thought it was an interesting idea

**Comment by absidue** [comment]
@TheFloatingBrain This won't give you a nice api to interact with but it does allow you to interact with freetube programatically at runtime.

As FreeTube is an electron app you can specify the `--remote-debugger-port=9222` command line option which means you can use the Chrome DevTools API. Selenium has support for this (check the docs for the selenium library for your programming language) although this will only allow you to interact with the chromium part of FreeTube.

If you would like to interact with the chromium part and the embedded nodejs instance you would be better suited with something like [Spectron](https://www.electronjs.org/spectron).

**Comment by absidue** [comment]
Hi @TheFloatingBrain

Unfortunately an addon/mod API is not possible in the way you want it.
The code that is distributed looks nothing like the source code. We would have to design a whole hacky API before people would even consider writing mods (which is definitely something we don't want to do). Even then you still wouldn't have the "full access" that you want. To write mods you would have to look at the compiled, bundled and optimised code, as it doesn't look like the source code.
You can think of it like asking to be able to change the ingredients in a cake after it has been baked.

It would be much better for you to PR features that you want in FreeTube and if we were to reject them for some reason, then you can always maintain your own custom build of FreeTube with the patches that you want.
