### ISSUE TITLE
A new way of subscribe using profiles

### ISSUE THREAD

**Issue by cjfloss** [FreeTubeApp/FreeTube#1615]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I find it a bit counter-intuitive to subscribe using multiple profiles.
My path to subscribe to a channel consists in searching for a channel, clicking on the channel, and hitting "subscribe".
The way FreeTube is right now, leads me to end up not using the multiples profiles, because I have to go to the top-right and change profile, and then clicking subscribe, this breaks the flow of adding a subscription.

**Describe the solution you'd like to see implemented**
I think a good solution is to have a kind of a dropdown combined with the subscribe button so when the user clicks the 'subscribe' button, he can select multiples profiles which to add the channel.

**Describe alternatives you've considered**

**Screenshots**
A quick rough sketch of what it may looks like
![A rough sketch](https://user-images.githubusercontent.com/5838486/130869943-bb2612ad-f671-448e-9989-bcd95598248a.png)

**Additional context**

**Comment by peepopoggers** [comment]
there could be a sub-button dropdown for this

**Comment by minhhang107** [comment]
Hi, I'd like to implement this feature.
I'm planning to do something like this
![subscribe](https://user-images.githubusercontent.com/55411709/143780002-c5bc3b35-a891-4c8c-8e04-fe29cc034bea.jpg)

Let me know what you think about this idea

**Comment by minhhang107** [comment]
@PrestonN I think the subscribe button should be kept separate so I revised the UI and added + button to show/hide the profiles.
Also in the Channel page, we also have the `Subscribe` button. Do you also want to add this feature to the Channel page as well?

![ezgif-3-54ba3e45b419](https://user-images.githubusercontent.com/55411709/144675814-ef69557b-8ca8-4eb2-9941-005d50cb1181.gif)

**Comment by PrestonN** [comment]
Hi @minhhang107!

Yes, please also make the change to the subscribe button in the channels page. Looks good so far!

**Comment by minhhang107** [comment]
Do you think it's better to create a component for the subscription or just directly add to the current code?

**Comment by peepopoggers** [comment]
looks good.

**Comment by drod3763** [comment]
I like this idea as the way Profiles work right now is too clunky, especially if you have a lot of subscriptions. Maybe the UI should also show any existing profiles the channel is attached to. I envision something like the profile icon being next to the name or something like that.
