### ISSUE TITLE
keyboard shortcut

### ISSUE THREAD

**Issue by kuldeeps-git** [FreeTubeApp/FreeTube#1618]
i am using free tube latest version in my Linux system and i am used of keyboard shortcuts ....
but when i try to use "**ALT + D** " shortcut for jump to search bar i can not run . it its not working  so please solve this problem if anyone can..

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi, I'll close this issue because this is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1463. Please leave a comment over there.
