### ISSUE TITLE
Command line search

### ISSUE THREAD

**Issue by qupear** [FreeTubeApp/FreeTube#1619]
Hi. I tried to search for such function in documentation and issues and didn't found an answer.

I am often opening FreeTube to search for some video and am not interested in loading subscriptions or trends.
I want to create a Windows batch file, something like this:
`Start "" "freetube.exe" "%s=""search query""`
So that after I fetch text to .bat, it will load FreeTube, and an app shows just search results in the fastest way.
Do you think that is a helpful feature?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/4446
