### ISSUE TITLE
No JSON option for subscriptions

### ISSUE THREAD

**Issue by kachapman** [FreeTubeApp/FreeTube#1620]
![Screenshot from 2021-08-28 11-28-32](https://user-images.githubusercontent.com/63679503/131225982-05048d9b-9d20-4a15-a8f3-9b3ac8c1778e.png)

Google Takeout doesn't give me the option to change the subscription file from CSV to JSON anymore.

**Comment by jasonhenriquez** [comment]
Hello, importing from CSV was added in #1543. [You can download the latest nightly build of FreeTube to use this feature.](https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml) This feature will also be in the upcoming release.
