### ISSUE TITLE
When quickly switching between two videos, the meta data of the first video will be loaded under the second video

### ISSUE THREAD

**Issue by Sandyran** [FreeTubeApp/FreeTube#1626]
**Behavior of the program**
When quickly clicking on a video you want to watch, and then clicking on a second video, the second video will have the meta data of the first video (video description, time stamps, etc.). The channel, however, will be the second channel (if the videos had different creators). This is similar to issue #1545.

**Expected behavior**
By quickly switching between two videos, the meta data of those videos, will get mixed (e.g. one video has the desciption of a different video).

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Click on a video.
2. Quickly click on a different video.
3. See error

**Screenshots**

*First video*
![Skjermbilde2](https://user-images.githubusercontent.com/31732894/131252007-b1517aa3-fa41-410e-bb98-a2a66fafeaf8.PNG)

*Second video*
![Skjermbilde3](https://user-images.githubusercontent.com/31732894/131252071-e9f31315-03fa-4637-8b80-616ff75060c9.PNG)

*Video with mixed meta data*
![Skjermbilde](https://user-images.githubusercontent.com/31732894/131252051-21a9d2c7-9914-4333-8228-b08f441c44f4.PNG)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.13.2
 - Installation Method (If applicable): .exe
 - Primary API Used: Invidious API

**Comment by jasonhenriquez** [comment]
Good catch! Hopefully we can solve both issues once we identify how exactly to get around this kind of issue.

**Comment by LynHyper** [comment]
Also reported on this issue here: https://github.com/FreeTubeApp/FreeTube/issues/1567

We should probably both close our issues since https://github.com/FreeTubeApp/FreeTube/issues/1545 exists and is the oldest out of the three, just to not duplicate issues.

**Comment by jasonhenriquez** [comment]
@LynHyper Good idea -- thanks for the suggestion!
