### ISSUE TITLE
Attempt to watch some videos, especially any watched one = infinite reload

### ISSUE THREAD

**Issue by PikachuEXE** [FreeTubeApp/FreeTube#1627]
**Behavior of the program**
Opening some videos would cause infinite reload 

**Expected behavior**
It should not reload infinitely

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Checkout `development`
2. `cd ~/Library/Application\ Support && rm -rf Electron` (Reset everything)
3. `npm ci`
4. `npm run dev` / `npm run debug` (I use debug one mostly)
5. Open a video (pick from trending is easiest)
6. Go back to video list
7. Open the same video again

**Link to video**
- https://youtu.be/62mGOYRbTDA

**Screenshots**
Screen capture:
https://user-images.githubusercontent.com/1018543/131316240-e15b75ce-94da-41e5-b082-d102d2cf5680.mov

**Environment Information (please complete the following information):**
 - OS: MacOS 
 - OS Version: MacOS 11.5.2 (20G95)
 - FreeTube version: Git SHA `9c38a1fdf556bf2599b659a868784886c7136e79`
 - Installation Method (If applicable): `npm install
 - Primary API Used: Local API

**Additional context**
I am reporting this coz I am trying to test #1578 locally but unable to

Edit 1: `npm ci` runs fine

**Comment by PikachuEXE** [comment]
Via checking out different commits and running the app locally
I think this is caused by d4953525b254d47ac91d54392f97e4e2418ea69b

**Comment by PikachuEXE** [comment]
This patch seems to solve it but I have no idea why:
```diff
From 5e01dde16294beab71b33ce900d60b766a482380 Mon Sep 17 00:00:00 2001
From: PikachuEXE <pikachuexe@gmail.com>
Date: Mon, 30 Aug 2021 17:57:18 +0800
Subject: [PATCH] Revert "Fix issue with videos not loading when running in dev
 mode"

This reverts commit d4953525b254d47ac91d54392f97e4e2418ea69b.
---
 src/renderer/views/Watch/Watch.js | 5 ++---
 1 file changed, 2 insertions(+), 3 deletions(-)

diff --git a/src/renderer/views/Watch/Watch.js b/src/renderer/views/Watch/Watch.js
index 273a30cb..ef73b043 100644
--- a/src/renderer/views/Watch/Watch.js
+++ b/src/renderer/views/Watch/Watch.js
@@ -1032,9 +1032,8 @@ export default Vue.extend({
           fs.mkdirSync('static/dashFiles/')
         }
 
-        fs.rm(fileLocation, () => {
-          fs.writeFileSync(fileLocation, xmlData)
-        })
+        fs.rmSync(fileLocation)
+        fs.writeFileSync(fileLocation, xmlData)
       } else {
         fileLocation = `${userData}/dashFiles/${this.videoId}.xml`
         uriSchema = `file://${fileLocation}`
-- 
2.33.0


```

**Comment by jasonhenriquez** [comment]
I was able to replicate this issue on my local `development` branch.

**Comment by peepopoggers** [comment]
Important issue needs to be looked at.

**Comment by PikachuEXE** [comment]
This makes testing video watching in development very annoying
Opened #1668

**Comment by lfom** [comment]
This started to happen with me once I have updated to v0.14.0. I tried changing the settings, nothing worked. Then I decided to backup the preferences file in ~/.config/FreeTube and deleted the files with "settings" and "preferences" in their names and it started to work fine. I think the reloaded is related to some problem when using Invidious API, either as a fallback or preferred API.

**Comment by peepopoggers** [comment]
Relevant: #1668
