### ISSUE TITLE
Fullwindow & Theater Mode Icons Disappear w/ Fullscreen Autoplay

### ISSUE THREAD

**Issue by jasonhenriquez** [FreeTubeApp/FreeTube#1629]
**Behavior of the program**
When watching a video in full screen with autoplay enabled, the full window and theater mode icons disappear from the media player after load of the next video. This problem will persist on all videos, even after switching between different routes, until full screen is entered and exited.

**Expected behavior**
After watching a video in full screen with autoplay enabled, the full window and theater mode icons will be visible and available as is normal.

**To Reproduce**
1. Turn on autoplay
2. Open a video in full screen
3. Skip to the end of the video and wait until the next video timer passes
4. The next video plays, full screen is exited, and finally the error occurs

**Screenshots**
Here is a picture of a video after the bug has struck.
![media-bar-wrong](https://user-images.githubusercontent.com/84899178/131601568-b02b4304-a120-44f6-971a-69474bd2ceaf.png)

**Environment Information (please complete the following information):**
 - OS: OpenSUSE
 - OS Version: Tumbleweed
 - FreeTube version: Latest nightly build
 - Installation Method (If applicable): Portable
 - Primary API Used: Local API

**Additional context**
It may be that vjs--full-screen-enabled or vjs-full-screen-enabled are erroneously still there. Maybe there needs to be explicit code for handling when full screen is on in beforeRouteLeave and beforeDestroy in ft-video-player.js.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Check out

https://github.com/FreeTubeApp/FreeTube/issues/1327

**Comment by jasonhenriquez** [comment]
Good catch @efb4f5ff-1298-471a-8973-3d47447115dc, it's basically the same issue.
