### ISSUE TITLE
Request: Default speed & hotkeys

### ISSUE THREAD

**Issue by linxoln** [FreeTubeApp/FreeTube#163]
It would be nice to be able to set a default playback speed and hotkeys to control speed.

Thanks

**Comment by PrestonN** [comment]
This is something that I should be able to include soon.  Hoping to add a lot of different settings for the next release.  What sort of hot keys would you expect for changing playback speed?  1-9 does video position like YouTube does so it will have to be something else.  Maybe + and - to increase/decrease playback speed?  Would like to hear some thoughts on this.

**Comment by omarroth** [comment]
+1 for using +/- for speed controls. Would it make sense to have hotkeys to change video quality?

There are also some hotkeys mentioned [here](https://support.google.com/youtube/answer/7631406) that I think would be nice to have, namely `/` for jumping to search. It also might be nice to have hotkeys for quickly switching to different pages, for example `Shift+S` could take you to your subscriptions page, although that's just my thoughts.

**Comment by ilu33** [comment]
/ is really awkward because it's shift-7 - that needs big hands which some people don't have. It's the worst shift combo possible. 
I would expect ctrl-f for search as it is everywhere else but that's fullscreen - huh? Ok so what about alt-s - that brings you to the url line in firefox and is kind of intuitive because search is at the position the url line would be.

**Comment by PrestonN** [comment]
This strictly depends on what keyboard layout you use.  For a lot of users, `/` is right next to shift and is very easy to hit.  I can understand it being troublesome if `/` requires `shift + 7` for you though.

I'm not sure about you, but to go to the URL for me in Firefox it is `Alt + D`, which is pretty close to what you use.  I think that would be a universally better option to go to the search box then `/` in this case.

**Comment by ilu33** [comment]
Alt-D opens file menu for me in Firefox - but I can see that alt-s opens history for you - well, it's a big world :-). No objections against alt-D.
You can check the / = shift-7 distribution on (https://medium.com/@mwichary/international-apple-keyboards-layouts-93437d7f9273). Especially the spanish layout leads to half the world* being affected. 
* Don't take "half the world" literal, I know about china and india :-D

**Comment by PrestonN** [comment]
Appreciate the article, gives a great visualization on what we're dealing with.

I think it's safe to say that we shouldn't be using any non letter or number as a shortcut for common functions to make sure that the shortcuts are actually useful to everyone.  I think `o` and `p` should be used for video speed and `Alt + D` should focus on the search bar.  That should work out the best for the most amount of people.

Ideally it would be nice to allow users to customize their own shortcuts, but let's do one thing at a time. ;)

**Comment by PrestonN** [comment]
Playback speed defaults, as well as the keyboard shortcuts to focus on the search bar and to change the current speed have been implemented.  Expect to see this in the next release. :)

**Comment by mak448a** [comment]
Hey @PrestonN, I know this is late, but could you change the hotkey to > and < because that's what the default youtube uses? Thanks!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@mak448a see https://github.com/FreeTubeApp/FreeTube/issues/2138#issuecomment-1073724876

**Comment by mak448a** [comment]
Will this ever be implemented though @efb4f5ff-1298-471a-8973-3d47447115dc ?
