### ISSUE TITLE
Export from YouTube is only csv

### ISSUE THREAD

**Issue by criagchome** [FreeTubeApp/FreeTube#1631]
I want to import my current playlists info FreeTube and have requested my Youtube subscriptions and videos to be exported.  However, there are no .json files in the downloads.

There are only .csv files.

Am I doing something wrong?

**Comment by jasonhenriquez** [comment]
Hello, importing subscriptions from JSON was added in #1543. [You can download the latest nightly build of FreeTube to use this feature.](https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml) This feature will also be in the upcoming release, which is likely to come out this weekend.
