### ISSUE TITLE
Add a Function To Make Freetube Always Synced With Youtube

### ISSUE THREAD

**Issue by hapatapa** [FreeTubeApp/FreeTube#1633]
I would like a way to make freetube always synced with youtube account like with the app called "Mytube" on the microsoft store

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I think such a feature makes no sense.

> FreeTube is an open source desktop YouTube player built with privacy in mind. Use YouTube without advertisements and prevent Google from tracking you with their cookies and JavaScript.

This will go against the believes of FreeTube.
With this feature u will defeat the main purpose of FreeTube and that is to let YouTube track u.

We try to minimize tracking, not make it easier for them to track you.

**Comment by peepopoggers** [comment]
@hapatapa you can import youtube subscriptions but whats the point of using a privacy focused app when you use youtube anyways?

**Comment by hapatapa** [comment]
'cause the file type for my subscriptions is not supported on freetube
(note that abonnements means subscriptions in french)
![image](https://user-images.githubusercontent.com/68708992/132110132-36137476-9585-4ff3-828b-2bd3bf552def.png)

**Comment by jasonhenriquez** [comment]
Downloading from CSV has been added in the new release @hapatapa! Check it out :)

**Comment by hapatapa** [comment]
Great!!!! 'cause i have a lot of subscriptions
