### ISSUE TITLE
Quality options missing except 720p and 480p

### ISSUE THREAD

**Issue by Futureknows** [FreeTubeApp/FreeTube#164]
I am on low bandwidth cell often and need 140p, 240p, 360p etc.

**Comment by PrestonN** [comment]
Hey there,

Unfortunately those qualities are adaptive formats and delivering them is a little more tricky than the current qualities which you can read more about [here](https://github.com/FreeTubeApp/FreeTube/issues/60#issuecomment-375529222).

Having said that, the developer of Invidious has these formats working by using a proxy through his site, which I have permission to use.  We need to be careful using this method as it will put a very heavy load on the bandwidth that the site has available which could potentially cause issues.  @omarroth will be slowly rolling this out to the users of Invidious soon. When the bandwidth issue is under control on his end, I can enable it for FreeTube as well.

**Comment by PrestonN** [comment]
Closing as this has been implemented and will be included in the next release.
