### ISSUE TITLE
Local directory link shows in picture-in-picture

### ISSUE THREAD

**Issue by peepopoggers** [FreeTubeApp/FreeTube#1640]
**Behavior of the program**
Shows a link where you click back to video player.

**Expected behavior**
No local directory link

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Pop-up any video

**Screenshots**
![image](https://user-images.githubusercontent.com/72892531/132108890-78da60d7-9e55-4eab-9e7c-fb3b093e5316.png)

 - FreeTube version: Nightly 0.14

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isnt happening anymore on the latest nightly build. Question is whether we leave this open because we eventually need to find a fix for it if we change the electron version again or just close it for now.

**Comment by peepopoggers** [comment]
I'm thinking like the above.
how about:
IF WE UPGRADE ELECTRON VERSION PLEASE FIX THIS

that should work :D

**Comment by PikachuEXE** [comment]
Tried this page with PIP with different browsers (all Chromium based):
https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API

## Vivaldi
Vivaldi | 4.2.2406.52 (Stable channel) (x86_64)
-- | --
Revision | 15706f801ff5b5ab0b97af359fe9b12707e81807
OS | macOS Version 11.6 (Build 20G165)
JavaScript | V8 9.3.345.19
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.99 Safari/537.36

![image](https://user-images.githubusercontent.com/1018543/135393387-33d84463-1611-4eb6-945d-87ee0a3e439e.png)


## Chrome 
Version 94.0.4606.61 (Official Build) (x86_64)
![image](https://user-images.githubusercontent.com/1018543/135393542-4a01522a-d5e3-443b-a685-68ed738629fd.png)


## Brave
Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)
![image](https://user-images.githubusercontent.com/1018543/135393665-4d078293-59e8-474b-a728-fd34a05fa0a8.png)

Version 1.30.86 Chromium: 94.0.4606.61 (Official Build) (x86_64)
![Screenshot 2021-09-30 at 1 40 19 PM](https://user-images.githubusercontent.com/1018543/135393813-ccdc6b54-0baa-444c-ac17-7a1aeb465aa9.png)

**Comment by PikachuEXE** [comment]
This is how it looks if upgrade to electron 15.x

![image](https://user-images.githubusercontent.com/1018543/135394889-92abf3bd-deea-49c8-9043-dabe1fdc8ec6.png)

**Comment by PikachuEXE** [comment]
@peepopoggers 
[15 was released 8 days ago](https://www.electronjs.org/releases/stable?version=15)
And it updated Chromium to 94 which I think is what changed the look of PiP player

**Comment by peepopoggers** [comment]
v15 will fix this v14 issue, yes?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Yes
