### ISSUE TITLE
[Bug] Video thumbnails are now smaller than the frame

### ISSUE THREAD

**Issue by altwarg** [FreeTubeApp/FreeTube#1641]
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**
Video thumbnails are now smaller than the frame after update to version 0.14.0-beta:

![image](https://user-images.githubusercontent.com/34391398/132116946-f43c7c01-bbf9-4ae7-8d85-a61de0a73c30.png)

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open subscriptions
2. See an issue

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 20H2
 - FreeTube version: 0.14.0-beta
 - Installation Method (If applicable): Portable via Scoop

**Comment by peepopoggers** [comment]
This looks strange. Are you sure you are using 0.14.0-beta because the popup button is meant to be in bottom left corner.

**Comment by peepopoggers** [comment]
Alright, nevermind it must be removed for some reason. I have the same issue with thumbnails.

**Comment by LynHyper** [comment]
Can confirm here, using Arch Linux, FreeTube v0.14.0, from FlatHub and I can observe this issue.

**Comment by peepopoggers** [comment]
Fixed :)
