### ISSUE TITLE
Channels list is empty

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#1642]
**Behavior of the program**
The channels list is empty even when there are channels i actually subscribed.

**Expected behavior**
The subscribed channels are present in the said list.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Upgrade to 0.14.

**Screenshots**
![Screenshot_20210905_103310](https://user-images.githubusercontent.com/22192600/132120678-58f6ff1f-17a9-4c9a-92ff-89c05dfc1032.png)

**Environment Information (please complete the following information):**
 - OS:  Ubuntu
 - OS Version: 21.04
 - FreeTube version: 0.14
 - Installation Method (If applicable): deb
 - Primary API Used: Local as primary, Invidious if local fails

**Additional context**

**Comment by ChunkyProgrammer** [comment]
![image](https://user-images.githubusercontent.com/78101139/132131962-e3157682-5ac7-4794-87bc-a9a35fa73f47.png)
I don't think this is the case but could you double check that "Hide Active Subscriptions" (Masquer les abonnements actifs)  is disabled?

It also looks like the translation isn't being done in the navigation bar. (It says Subscriptions instead of Abonnements, Trending instead of Tendance, etc.). I am not able to reproduce this in my configuration (Windows 10, exe, local api). If you could open the dev console (Ctrl + Shift + i) and share any errors that appear, it would be greatly appreciated.

**Comment by stemy2** [comment]
That it isn't the only problem, apparently. The app seems to ignore my own settings at every launch, but it comes back if i change one parameter.

For example, in the current case, the parameter "hide active subscriptions" was disabled, but enable then disable it brought me the channels list back.

**Comment by no-comma** [comment]
> If you could open the dev console (Ctrl + Shift + i) and share any errors that appear, it would be greatly appreciated.

I'm experiencing this issue on Arch, Flatpak, local, here are the errors I get:

![error](https://user-images.githubusercontent.com/82644961/132307507-a0e291f7-3bc8-47c1-8eb1-423559207266.png)

**Comment by 360fun** [comment]
Same on Mac OS, to show them just click on the top-left sandwich menu twice and they will re-appear: definitely a UI bug.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could u try out the latest nightly build?

**Comment by no-comma** [comment]
Works for me on nightly.

**Comment by 360fun** [comment]
On Mac still not showing :(

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> On Mac still not showing :(

Just to be sure u mean after downloading the latest nightly build the channels are still not showing?

**Comment by rebelcode-xr** [comment]
> > On Mac still not showing :(
> 
> Just to be sure u mean after downloading the latest nightly build the channels are still not showing?

yes, **freetube-0.14.0-nightly-1224** to be precise

**Comment by 360fun** [comment]
yes, **freetube-0.14.0-nightly-1224** to be precise

**Comment by jasonhenriquez** [comment]
@360fun If you don't mind, the next time you experience this error, can you press Ctrl+Shift+i and share any errors that appear on the dev console? Also share your OS please.

**Comment by 360fun** [comment]
I use Big Sur 11.6, now I've downloaded and tested this: `freetube-0.14.0-nightly-1227-mac.dmg`

Here's what the console shows when I open FreeTube (channels list is empty):

![image](https://user-images.githubusercontent.com/844090/134809968-c35bfaf6-c404-4c1e-ab9e-967acda60e66.png)
![image](https://user-images.githubusercontent.com/844090/134810043-f15b0a0e-7e06-48da-b265-bb05482f09b5.png)

**Comment by 360fun** [comment]
Bug still present in beta 0.15.0 😢

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hmm if u open the app. The channel list is empty right? 

Could u try to expand the channels list using the hamburger button in the top left corner and see if that changes anything

**Comment by 360fun** [comment]
> Hmm if u open the app. The channel list is empty right?
> 
> Could u try to expand the channels list using the hamburger button in the top left corner and see if that changes anything.
> 
> If u'll see the channel list appear then i can mark #1883 as a duplicate of this issue.

- channels list is empty with both Side Bar settings: minimized and expanded
- if the Side Bar is minimized and I expand it => channels appear
- if the Side Bar is expanded and I minimize it => channels appear

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Okay great thank you for ur input. I'll will mark the other issue as a duplicate of this one.

**Comment by 360fun** [comment]
Hope you'll manage to fix it soon, thanks! 🙏

**Comment by grrrrr** [comment]
If it is of any use to anyone, while a proper fix is found, I seem to have got the sidebar of channels working again by

1. Back up subscriptions, history and playlists
2. Quit FreeTube
3. delete or move the settings folder (~/.config/FreeTube)
4. Start FreeTube (it will be as if starting it for the first time)
5. import subscription, history and playlists

Where the channels was consistently empty each time I started FreeTube,  doing the above steps the sidebar contact list has been consistently working again.

**Comment by 360fun** [comment]
> If it is of any use to anyone, while a proper fix is found, I seem to have got the sidebar of channels working again by
> 
> 1. Back up subscriptions, history and playlists
> 2. Quit FreeTube
> 3. delete or move the settings folder (~/.config/FreeTube)
> 4. Start FreeTube (it will be as if starting it for the first time)
> 5. import subscription, history and playlists
> 
> Where the channels was consistently empty each time I started FreeTube, doing the above steps the sidebar contact list has been consistently working again.

Yeah! It works 😍 Thanks!!!

**Comment by arrowgent** [comment]
thinking this is left over config cruft from previous installs?
ive updated freetube since hell i dont know v0.5.0???? a long time ago

just doing the typical `sudo dpkg -i freetube.deb` upgrade path to upgrade the package software


it would be a serious pain to redo the work for all my 800+ subscriptions and custom profiles
so im hesitant to start backing up and trying to manage some config files...

**Comment by ChunkyProgrammer** [comment]
If you export your subscriptions as a freetube subscription file then it should keep your custom profiles and be a fairly quick import

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is this still an issue for anyone on v0.17.1?

**Comment by stemy2** [comment]
In my side, the problem is solved.
