### ISSUE TITLE
Enabling video scroll for volume prevents scrolling in the quality menu

### ISSUE THREAD

**Issue by LynHyper** [FreeTubeApp/FreeTube#1643]
**Behavior of the program**
If you enable the new setting for scrolling on a video to change the volume then you can't scroll within the "Select Quality" menu; it just changes the volume.

**Expected behavior**
The quality menu should be scrollable and be scrolled through without changing the volume.

**To Reproduce**
1. Enable scroll on video for volume change.
2. Go to any video.
3. Click on, or hover over, the quality button.
4. Try and scroll in the "Select Quality" menu, see the volume change and the quality menu list not move.

**Environment Information**
 - OS: Arch Linux
 - FreeTube version: 0.14.0 Beta
 - Installation Method: FlatHub
 - Primary API Used: Local API [Happens with both]

**Comment by jasonhenriquez** [comment]
@LynHyper Incredible job reporting these so quickly! We might ask you to test our nightly build a week before our next release.

**Comment by LynHyper** [comment]
I'd be happy to do beta testing if you think that would help!

**Comment by jasonhenriquez** [comment]
That would be great! We'll notify you here and/or [our Matrix channel](https://app.element.io/#/room/#freetube:matrix.org) before our next release.

**Comment by ChunkyProgrammer** [comment]
Fixed in #1650

**Comment by jasonhenriquez** [comment]
@LynHyper [Testing period has started!](https://github.com/FreeTubeApp/FreeTube/discussions/1773)
