### ISSUE TITLE
Unable to load videos in higher quality than 720p with DASH format

### ISSUE THREAD

**Issue by iSaluki** [FreeTubeApp/FreeTube#1645]
**Behavior of the program**
When watching a video, the highest quality available is always 720p (max). 1080p is set to the default and I am using the DASH format.
**Expected behavior**
I would expect the video to load in 1080p, but this doesn't happen and no option appears for it.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Locate a video with 1080p quality support 
2. Open it in FreeTube
3. Attempt to set quality to 1080p
4. Observe how 720p is the maximum quality avaliable.

**Link to video**
As an example: https://youtu.be/8NK1I6S_vFs
This video is available in 1080p+ on YouTube, but only up to 720p on FreeTube.

**Screenshots**
N/A

**Environment Information (please complete the following information):**
 - OS: Pop!_OS 21.04 (Ubuntu/Debian based)
 - OS Version: 21.04, Kernel: 5.11.0-7633-generic
 - FreeTube version: v0.14.0 Beta
 - Installation Method (If applicable): FlatHub. Updated this morning.
 - Primary API Used: Invidious API (I have tried local too, no change).

**Additional context**
I'm not completely sure, but I seem to recall watching a video in 1080p on FreeTube yesterday. This was the first day I was using it though, so I can't be too sure.

If you need any further information to help diagnose this issue, just let me know.

**Comment by jasonhenriquez** [comment]
Are the two available options "720p" and "360p" for you? Given how I cannot replicate this error, my hunch is that your DASH format is not working & is falling back to Legacy format, which does not support 1080p+ quality.

**Comment by iSaluki** [comment]
Yes, I'm seeing 360 and 720 as the available options. Do you have any suggestions on how I could fix this? Is there any data I can give you to help you figure out what the root cause of the issue is?

**Comment by jasonhenriquez** [comment]
Can you try manually setting it to DASH format under the "Change Video Formats" dropdown? If that doesn't work, please open Developer Tools with Ctrl-Shift-I and share what errors are popping up.

**Comment by iSaluki** [comment]
Here you go. As you suggested earlier, DASH is failing.

![Screenshot from 2021-09-05 17-27-35](https://user-images.githubusercontent.com/37915796/132134206-6e2eea87-18a1-4c93-b717-c67a6c39a6ce.png)

It appears that the format may be unsupported by my system. Is there a package containing support for DASH?

**Comment by peepopoggers** [comment]
I had this issue too. do local api preferred backend, default dash with 1080p default. try that.

**Comment by iSaluki** [comment]
> I had this issue too. do local api preferred backend, default dash with 1080p default. try that.

I have tried this, it didn't work. Restarted and everything after applying the changes.

**Comment by iSaluki** [comment]
Did some debugging, and after reinstalling and deleting the data directories, I found out that the problem was the fact I had "Proxy videos through Individuous" enabled. Thanks for your help!

**Comment by peepopoggers** [comment]
:+1:
