### ISSUE TITLE
Options for 1440p and 2160p should be added to default quality dropdown

### ISSUE THREAD

**Issue by peepopoggers** [FreeTubeApp/FreeTube#1647]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Options for 1440p and 2160p should be added to default quality dropdown.

**Screenshots**
![image](https://user-images.githubusercontent.com/72892531/132134490-cd5e9131-c926-4d68-a3b5-a1c0f9e11d7d.png)

**Comment by PrestonN** [comment]
Most videos won't have those options available due to [this](https://docs.freetubeapp.io/usage/common-issues/#videos-are-only-limited-to-1080p) issue, so I don't see a benefit in adding them for now.

**Comment by jasonhenriquez** [comment]
In that case, we should probably remove them as DASH quality options until that point.

**Comment by PrestonN** [comment]
I'm fine with the options showing up when the player allows it. My issue is that I'd be concerned with users setting their default to 1440p+ and then coming back here saying that it isn't working, not noticing that the player only displays up to 1080p. I wouldn't want to remove the options if it isn't hurting anything, I just don't want to highlight the issue.

**Comment by jasonhenriquez** [comment]
I get a "this is not supported" error when I try to click on higher quality levels than 1080p (for a video that provides it), but that may not be universal.

**Comment by peepopoggers** [comment]
@PrestonN 
![image](https://user-images.githubusercontent.com/72892531/132137508-26cbaa0d-dcb5-4a96-ba4c-4bdda416d35e.png)

**Comment by peepopoggers** [comment]
IMO just as many people trying to switch settings manually will complain as people that want to set default.

Use case: where videos support, 1440p is played so it has a crisper quality. If they do not support it then it will go down to 1080p.
Not introducing features due to people complaining (if anyone even notices) seems restricting.

**Comment by jasonhenriquez** [comment]
I think a good compromise would be to add a "Max supported quality" setting.

**Comment by darkralts** [comment]
> I'm fine with the options showing up when the player allows it. My issue is that I'd be concerned with users setting their default to 1440p+ and then coming back here saying that it isn't working, not noticing that the player only displays up to 1080p. I wouldn't want to remove the options if it isn't hurting anything, I just don't want to highlight the issue.

honestly i wouldve preferred if you added it then, because then i wouldnt have to come back and tell you to add it now. almost every 1440p video works for me but im cucked to 1080p because of this soy dropdown menu not having enough options. 720p isnt even HD by youtube standards anymore, its time to upgrade.

**Comment by darkralts** [comment]
for now do you at least know anything i can do in the config file to manually do this? its genuinely like, i cant even begin to describe it.
