### ISSUE TITLE
Please enable `An Open Source YouTube app for privacy` to be translatable

### ISSUE THREAD

**Issue by ovari** [FreeTubeApp/FreeTube#1653]
1. Please remove the full-stop in `An Open Source YouTube app for privacy.` to become `An Open Source YouTube app for privacy`
2. Please allow `An Open Source YouTube app for privacy` to be translatable.

![kép](https://user-images.githubusercontent.com/17465872/132141375-7888f113-2c9e-45ab-a2ee-94dbf1c27662.png)

What do you think?

Thank you

**Comment by peepopoggers** [comment]
I am not sure if this can be translatable, as it is outside the webslate in the app. Maybe I am wrong though :shrug:

**Comment by ovari** [comment]
@peepopoggers please accept the 2 merge requests to translate the FreeTube app. It can be automated; however, this manual method works. Thank you

**Comment by ovari** [comment]
@PrestonN please accept the 2 merge requests to translate the FreeTube app. It can be automated; however, this manual method works. Thank you

**Comment by peepopoggers** [comment]
@ovari don't spam pls.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Its better to discuss this over at #673
