### ISSUE TITLE
Please enable the description in flathub to be translatable

### ISSUE THREAD

**Issue by ovari** [FreeTubeApp/FreeTube#1654]
Please enable the description in flathub to be translatable. Please see the image below.

![kép](https://user-images.githubusercontent.com/17465872/132141471-228c4b1e-1cac-4599-bf56-97fb4ca9572f.png)

This would be similar to how `Video Downloader` shows

![kép](https://user-images.githubusercontent.com/17465872/132141512-d38e1812-6190-4d65-9775-513e98a5c23c.png)

What do you think?

Thank you

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Its better to discuss this over at #673
