### ISSUE TITLE
Add "Hide Comments" to Distraction Free Settings

### ISSUE THREAD

**Issue by peepopoggers** [FreeTubeApp/FreeTube#1656]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I am frustrated when monkey brain browses comments.
It would be a very useful addition for people that browse comments too much.

**Describe the solution you'd like to see implemented**
Adding a distraction free setting to hide comments element.

**Comment by peepopoggers** [comment]
#1456 <- this pr would close this issue

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
So...why exactly did u create this duplicate?

**Comment by peepopoggers** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc :crying_cat_face:
