### ISSUE TITLE
deb package installation fails on Debian testing

### ISSUE THREAD

**Issue by JosephKiranBabu** [FreeTubeApp/FreeTube#166]
The Debian package provided FreeTube_0.3.2_amd64.deb has a dependency called `libgconf2-4` which seems to be a transitional package which is now no longer available in Debian testing[1].

Please replace this with `libgconf-2-4`.

1. https://packages.debian.org/unstable/libgconf2-4

**Comment by PrestonN** [comment]
I don't really have much control over what dependencies are required on installation.  This should be handled automatically with Electron.  It's either that or it has to do with my machine that I make the builds from, which runs Ubuntu 18.04.  I'll update Electron for the next release and see if that fixes it.  If it doesn't then I'll try to leave a note about this somewhere.

**Comment by PrestonN** [comment]
This should be fixed as the issue was due to an older version of Electron.  I will go ahead and close the issue.
