### ISSUE TITLE
Opening a video on a new window with the scroll button stopped working at v0.14.0 Beta

### ISSUE THREAD

**Issue by psychogoat69** [FreeTubeApp/FreeTube#1666]
When clicking a video with the scroll button it only opens a white window that seems to keep loading forever

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @psychogoat69 this a an duplicate of issue https://github.com/FreeTubeApp/FreeTube/issues/1636

Please leave a comment over there.

**Comment by psychogoat69** [comment]
Alright

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
