### ISSUE TITLE
The `Back` and `Forward` buttons both have the tooltip/popup `Forward`

### ISSUE THREAD

**Issue by ovari** [FreeTubeApp/FreeTube#1671]
The `Back` and `Forward` buttons both have the tooltip/popup `Forward`.

![kép](https://user-images.githubusercontent.com/17465872/132492867-8453a6a2-a0f5-4ebb-aa2b-706e6f0ad9f4.png)

Thank you

FreeTube version 0.14.0 beta

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @ovari this is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1659

If u want u can leave a comment over there.
