### ISSUE TITLE
watched history error?

### ISSUE THREAD

**Issue by ghostlyentity** [FreeTubeApp/FreeTube#1674]
**Behavior of the program**
when watching a video or marking it as watched it occasionally does not end up in the watch history, as if it wasnt seen

**Expected behavior**
appear in watch history

**Environment Information (please complete the following information):**
 - OS: [Solus (same problem has been on endeavouros as well)
 - OS Version: [Solus 4.3]
 - FreeTube version: [v0.14.0-nightly-1164 Beta]
 - Installation Method (If applicable): [.AppImage]
 - Primary API Used: [Local API]

**Additional context**
i am honestly unsure how i should really address this problem, if it really is one that is, below is a cropped example of videos marked as watched and than later one of them not being in the list, apologies for the small crop, id like to not show certain videos in my watchlist, but i would not be opposed to sharing my db file if necessary. thank you in advance

![Screenshot from 2021-09-08 19-42-01](https://user-images.githubusercontent.com/86599520/132559289-c37ff831-3dfc-4cc9-aca0-db4362a1b400.png)
![Screenshot from 2021-09-08 19-42-23](https://user-images.githubusercontent.com/86599520/132559301-a1114080-ac52-404b-b186-0bc33816f55b.png)

**Comment by toby63** [comment]
Do you use multiple windows? 
This is a known problem, see #1504 and https://github.com/FreeTubeApp/FreeTube/issues/333#issuecomment-712753636.

**Comment by ghostlyentity** [comment]
i do not use multiple windows.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @ghostlyentity could u try the latest nighly build and report back if this still occurs.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@ghostlyentity please respond to the previous comment.
