### ISSUE TITLE
can't open new instances in new window

### ISSUE THREAD

**Issue by bob808** [FreeTubeApp/FreeTube#1676]
**Behavior of the program**
when I try to open a new window with the third mouse button the new window stays blank. in console I get this:
`(node:8583) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.`
 
**Expected behavior**
should open new windows without issues.

**To Reproduce**
Please add all steps to reproduce the behavior:
start new instances in new windows.

Tried this on Arch and Windows 10.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @bob808, this issue has already been solved in the nightly builds by this PR https://github.com/FreeTubeApp/FreeTube/pull/1658

If u want u can already download the nightly build.

**Comment by bob808** [comment]
awesome, thanks!
