### ISSUE TITLE
Feature request: Automatically download subscibed videos

### ISSUE THREAD

**Issue by Zypherspace** [FreeTubeApp/FreeTube#168]
A fantastic option would be a checkbox to automatically download new videos in subscription feeds to local storage. This would be a godsend for slow connections or other scenarios where the user would like to have the downloaded files available for local playback on demand. Depending on difficulty, further granularity for auto download per subscription could be implemented.

**Comment by PrestonN** [comment]
I'm not too sure on automatically downloading videos as that could fill up someone's hard drive pretty quickly if it isn't treated carefully.  I do however have plans to have a built in download manager for videos so hopefully that will work well for you once I can implement it.

**Comment by grrrrr** [comment]
Alternatively,  allowing us to "check" multiple videos and copy the URLs for all of them in one go, for easy pasting into `youtube-dl` on commandline

**Comment by Zypherspace** [comment]
Good to hear about the download manager. Regarding the space concern that would be at user discretion, but normally 10s or even 100s of average youtube downloads don't make a dent in modern storage as long as they are autodeleted after a period or when cache size exceeded.
