### ISSUE TITLE
"This channel does not currently have any videos."

### ISSUE THREAD

**Issue by aharper14** [FreeTubeApp/FreeTube#1684]
**Behavior of the program:**
Displays "This channel does not currently have any videos" message and doesn't show videos when videos clearly exist on the official YouTube site.

**Expected behavior:**
The page should show all videos uploaded by the channel.

**To reproduce:**
1. Search for channel.
2. Click on channel.
3. See "This channel does not currently have any videos" message and lack of videos.

**Technical info:**
 - OS: macOS (M1)
 - OS Version: 11.5.2
 - FreeTube version: 0.14.0
 - Installation Method (If applicable): .dmg
 - Primary API Used: Preferred API Backend is set to Local API

**Screenshots:**
<img width="1792" alt="Screen Shot 2021-09-09 at 8 05 32 PM" src="https://user-images.githubusercontent.com/88669313/132778073-824b5b59-3a4a-4609-bfc5-cdbe8be2069d.png">

<img width="1792" alt="Screen Shot 2021-09-09 at 8 05 24 PM" src="https://user-images.githubusercontent.com/88669313/132778063-b9e3bb65-a5f4-420d-8518-684dd8b576b0.png">

<img width="1792" alt="Screen Shot 2021-09-09 at 8 05 51 PM" src="https://user-images.githubusercontent.com/88669313/132778081-a17167ff-d70a-4a66-91e3-9e9dde0e0ba5.png">

**Comment by PikachuEXE** [comment]
I am unable to reproduce with your provided steps
I tried searching Netflix

If you have other non-default setting values please provide here. Thx

![image](https://user-images.githubusercontent.com/1018543/133030888-75e88ea5-8b19-4e8f-a865-4b32ef53b983.png)

**Comment by aharper14** [comment]
The issue resolved itself. Could’ve been issues with YouTube, my internet, or something else. I honestly forgot I submitted this report. 


Sep 13, 2021, 1:55 AM by ***@***.***:

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@WizardOfWor1969 is your primary API set to Invidious?

**Comment by WizardOfWor1969** [comment]
Preferred API Backend is set to Invidious API

**Comment by WizardOfWor1969** [comment]
![Screenshot from 2022-11-02 03-22-30](https://user-images.githubusercontent.com/52321250/199465492-9314826a-f27c-4556-b9f1-802f799b9263.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@WizardOfWor1969 could u try the local API

**Comment by WizardOfWor1969** [comment]
> @WizardOfWor1969 could u try the local API

Local API Error: AXIOS Error: Network error

**Comment by WizardOfWor1969** [comment]
We are blocking Google services on my network, if that should mean something

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hmm ok so lets try this

Set preferred API to local api -> reload FT with CTRL + SHIFT + R -> try 3 channels

**Comment by WizardOfWor1969** [comment]
I am seeing missing stuff on Invidous ....


![Screenshot from 2022-11-02 03-54-43](https://user-images.githubusercontent.com/52321250/199472132-cf76649a-d5aa-40aa-b4e1-62b0e44af521.png)

**Comment by WizardOfWor1969** [comment]
> Hmm ok so lets try this
> 
> Set preferred API to local api -> reload FT with CTRL + SHIFT + R -> try 3 channels

Same thing for all 3 channels : This channel does not currently have any videos

**Comment by WizardOfWor1969** [comment]
> I am seeing missing stuff on Invidous ....
> 
> ![Screenshot from 2022-11-02 03-54-43](https://user-images.githubusercontent.com/52321250/199472132-cf76649a-d5aa-40aa-b4e1-62b0e44af521.png)

BTW- I am using Brave browser to at Invidous with the missing videos as well.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is definitely a invidious issue when primary api is set to inviduius. It is our of our control to fix this.


Local api should work for u.

Try disabling fallback to another api in the settings and make sure local api is set as ur primary

**Comment by WizardOfWor1969** [comment]
I see, so the local API connects to youtube.com?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> I see, so the local API connects to youtube.com?

See https://docs.freetubeapp.io/usage/local-api/ for more info

**Comment by WizardOfWor1969** [comment]
Ok, well we are blocking Google on the network (so that includes youtube). I will just have to live with Invidous not showing any videos for a channel.
