### ISSUE TITLE
Only Plays Videos at 720p

### ISSUE THREAD

**Issue by meximan** [FreeTubeApp/FreeTube#1688]
I have DASH formats enabled and 1080p enabled as well yet Freetube only plays at 720p. My internet connection is 100mbps up and down. I have the latest version of the app.

**Comment by meximan** [comment]
Changing the instance helps with this.

**Comment by meximan** [comment]
I think there's a bug because when I turned off "Proxy Videos Through Invidious" this enabled 1080p.

**Comment by jasonhenriquez** [comment]
You are correct, there is a bug wherein proxying videos through Invidious inhibits DASH format & initiates a fallback to Legacy format, which does not support resolutions >720p. This issue will be closed as it does not use the issue template provided.
