### ISSUE TITLE
Remember playback speed

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1695]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
At the moment when u change the playback speed while watching a video to 1,5x and u click on another video the playback speed gets overwritten by the default set playback speed in the settings.

**Describe the solution you'd like to see implemented**
So lets take the current implementation of the default volume setting as an example. Your default setting is set to 100% so when u go to a video the volume will be 100%. When u change the volume to 50% while watching a video and click on another video the volume stays at 50%. 

I would like to see the same implementation for playback speed. 

**Describe alternatives you've considered**
None.

**Screenshots**
None.

**Additional context**
None.

**Comment by RubenArtmann** [comment]
The icing on top would be regex support, so you could do:
* 1.0x for /VEVO$/ matching the channel
* 1.8x for /OpenCourseWare/ matching the channel
* 1.0x for /\(Official\sAudio\)/ matching the title
* 1.0x for /Auto\-generated\sby\sYouTube\./ matching the description

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2295
