### ISSUE TITLE
Remember video quality

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1696]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
At the moment when u change the video quality while watching a video to 144p and u click on another video the video quality gets overwritten by the default set quality in the settings.

**Describe the solution you'd like to see implemented**
So lets take the current implementation of the default volume setting as an example. Your default setting is set to 100% so when u go to a video the volume will be 100%. When u change the volume to 50% while watching a video and click on another video the volume stays at 50%. 

I would like to see the same implementation for playback speed. 

**Describe alternatives you've considered**
None.

**Screenshots**
None.

**Additional context**
None.

**Comment by jasonhenriquez** [comment]
To clarify, [using the settings scope manifesto,](https://github.com/FreeTubeApp/FreeTube/pull/1281#issuecomment-912846345) you would prefer a change in the default behavior from scope level 1 to scope level 3?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
That would be correct.

**Comment by toby63** [comment]
Sry I disagree, I like it when the default setting is applied to a different video.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Its ok to disagree with me. We just have to figure out what we would like as default, the current implementation or the described implementation. We could also make something like this a setting of some sort.

**Comment by toby63** [comment]
I agree an option in the settings would be a good idea.

Still I think it would be good to have the default setting as default for every new video, as thats what it's there for imho.

Another idea I just had is that it makes a difference, whether the default setting is increased or decreased by the user.
For example a decrease is not so problematic (I am mainly thinking about the loudness here), while an increase can be more problematic :thinking:.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2295
