### ISSUE TITLE
Auto-update feature

### ISSUE THREAD

**Issue by rebelcode-xr** [FreeTubeApp/FreeTube#1701]
Please consider implement a way to easily auto-update the app, instead of download and substitute the file manually.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @rebelcode-xr this is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/841

If u want u can leave a comment over there.

I'll be closing this issue in order to prevent cluttering the backlog.

**Comment by rebelcode-xr** [comment]
Sorry, I didn't find it when I searched "autoupdate", thanks!
