### ISSUE TITLE
MPV does not launch when clicking Open in mpv

### ISSUE THREAD

**Issue by WonderfulSpivey** [FreeTubeApp/FreeTube#1704]
**Behavior of the program**
After setting MPV as the External Player and Custom External Player Executable as "C:\Program Files\MPV\mpv.exe" in settings and then clicking the Open in mpv button on a video the "opening video in mpv..." message appears in FreeTube but MPV never launches.
**Expected behavior**
After clicking on open in mpv button video should launch in MPV

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any video
2. Click on open video in mpv
3. nothing happens

**Link to video**
Has happened on every video I've tried, here is an example: https://invidious-jp.kavin.rocks/watch?v=R0duyfHPQks

**Environment Information (please complete the following information):**
 - OS: Windows 10
 - FreeTube version: v0.14.0 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Comment by elvindsouza** [comment]
for anyone using Ubuntu Linux, 
`mpv <YouTube URL>`
the output can help you diagnose this. in my case, youtube-dl was not installed (id assumed it pick up on yt-dlp being present)

**Comment by kajdo** [comment]
thx for the hint @elvindsouza ... stupid me wanted to just open an issue

yt-dlp didn't work after upgrading PopOS to the newest version ... if someone faces the same issue - check if mpv works in the first place like mentioned above

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
inquires regarding external players migrated to https://github.com/FreeTubeApp/FreeTube/discussions/7789
