### ISSUE TITLE
Videos Won't Load After Using Localhost ( 127.0.0.1 ) SOCKS5 Proxy

### ISSUE THREAD

**Issue by rizatsubudji** [FreeTubeApp/FreeTube#1706]
Version : 0.14.0 Beta
OS : Windows 8.1 x64 Pro

The bug happened after I setup the SSH Tunnel to tunnel into FreeTube with Socks5 Proxy in the settings. The settings option in the app won't opened because the traffic outside is connecting to 127.0.0.1:1080 but  **not going through**, for example: **My Computer** -> **SSH Tunnel Socks5 Proxy** -> **127.0.0.1:1080**.

Screenshot: 
![Untitled](https://user-images.githubusercontent.com/58281559/133384586-99412109-56cf-4875-bf3b-46a93aa811f5.png)

**Comment by JonathanTSilva** [comment]
I'm having a similar problem: im my case, I can only access the app if I liberate my machine's IP in the proxy (and I can't do this). Then I realized that in the Proxy Settings option, there is no information that is necessary for my access: the username and password of my proxy.
![image](https://user-images.githubusercontent.com/58694273/133436764-2e9b886f-0d56-4bc7-b16b-31b3754aeb75.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi did u read our documentation? https://docs.freetubeapp.io/usage/tor/
did this fix it for u?
