### ISSUE TITLE
How to import youtube history from csv/json?

### ISSUE THREAD

**Issue by rsmyst** [FreeTubeApp/FreeTube#1707]
I'm on 0.14.0 beta and i am not able to import history into freetube.
Google takeout only uses csv and json.
Freetube wants some database files. any help?

**Comment by jasonhenriquez** [comment]
Importing history from CSV / JSON is not supported at this time unfortunately. There is an issue proposing this functionality (#1623).

**Comment by rsmyst** [comment]
> Importing history from CSV / JSON is not supported at this time unfortunately. There is an issue proposing this functionality (#1623).

then does that just mean i'll have to wait for the next release for me to import history? guess i'll just have to wait
