### ISSUE TITLE
How to exit picture in picture mode without closing the entire video?

### ISSUE THREAD

**Issue by rsmyst** [FreeTubeApp/FreeTube#1708]
I was trying to return to the video but no matter what I clicked, the video just exited and nothing happened. 
I was on another page on freetube but i would expect picture in picture to reopen the video in full screen...

**Comment by jasonhenriquez** [comment]
You will have to stay on the same page for this behavior to occur in our current implementation. You are welcome to create a feature request for this functionality as long as you use the template properly.
