### ISSUE TITLE
macOS is unable to identify developer

### ISSUE THREAD

**Issue by dhruv-agg** [FreeTubeApp/FreeTube#1709]
**Behavior of the program**
macOS is unable to identify developer

**Expected behavior**
developer info should be specified

**Environment Information (please complete the following information):**
 - OS: MacOS
 - OS Version: BigSur 11.5
 - FreeTube version: 0.14.0
 - Installation Method (If applicable): [.dmg, brew install --cask freetube]

**Comment by jasonhenriquez** [comment]
This issue is a duplicate of #1520. Unfortunately, FreeTube would have to pay for a yearly subscription to rectify this behavior:

> The security issue that your mentioning has nothing to do with it being in the app store or not. The problem is that Apple (and Microsoft) expects every application to be "Signed" with a verified certificate that tells the user that the software that you are about to install comes from the verified source that it claims to be. The issue with getting FreeTube signed is that it involves paying Apple a yearly subscription to their developer program (Which is about ~$100 IIRC) just for the privilege of having their software signed (Microsoft charges even more).
