### ISSUE TITLE
Crashing when re-scaling between horizontal and vertical versions

### ISSUE THREAD

**Issue by cihlarma** [FreeTubeApp/FreeTube#1710]
**Behavior of the program**
FreeTube often (if not always) crashes whenever I try to change the screen's orientation on a PinePhone.

**Expected behavior**
The app scales between landscape and vertical versions without crashing.

**To Reproduce**
1. Play any video on a PinePhone
2. Rotate screen orientation
3. App doesn't re-scale, crashes instead

**Core dump from `journalctl`**
[freetube-coredump.txt](https://github.com/FreeTubeApp/FreeTube/files/7176937/freetube-coredump.txt)

**Environment Information (please complete the following information):**
 - OS: Manjaro Phosh
 - OS Version: Beta 15
 - FreeTube version: v0.14.0 Beta Release
 - Installation Method (If applicable): AUR (`freetube-bin`, uses official .deb build)
 - Primary API Used: Local API

**Additional context**
Seems to be a regression in 0.14.0, I can't replicate the behaviour with 0.13.2. Furthermore, I cannot replicate the crashes when resizing the window manually to switch between the landscape and vertical views on my desktop (Debian 11 amd64).

**Comment by pkrasicki** [comment]
I can't reproduce this on 0.15.0 on Mobian Bookworm. Changing the orientation works for me in fullscreen and in normal mode.

**Comment by cihlarma** [comment]
Neither can I, looks like the bug was caused by Electron 14.

From [0.15.0 release notes](https://github.com/FreeTubeApp/FreeTube/discussions/1835):
> - Downgraded Electron version from 14.0 to 13.5.1
>   - Commmentary: In FreeTube v0.14.0, one of our last-minute changes was upgrading the Electron version. In doing so, we introduced a litany of Electron bugs that degraded the user experience. As a result, we will keep FreeTube's Electron version at v13.5.1 until these issues are thoroughly addressed.

Closing for now, will re-open if the issue re-emerges after the (eventual) upgrade to Electron 15.
