### ISSUE TITLE
Certain videos do not offer 1080p, despite doing so in VLC and on the web. 

### ISSUE THREAD

**Issue by Taihouu** [FreeTubeApp/FreeTube#1711]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. 

**Question**
I'm unable to view certain videos in 1080p in Freetube despite the resolution being available both on the Youtube website and in VLC. I've seen a few bug reports which are similar, but not the same as this seems to affect a subset of videos for me rather than all of them, and I have tried solutions such as disabling Invidious and forcing DASH. Before I open a bug report, perhaps someone here could offer an explanation or reproduce the result. 

Here is a selection of videos which do not offer 1080p for me in Freetube, but do so elsewhere:
https://youtu.be/TtRmboKFUug
https://youtu.be/VZanqhWTnsE
https://youtu.be/WchjFArhh3U

These videos are loaded in 360p (I have 1080p set as default) and offer 720p. I have set it to use DASH, but I'm not sure how I can verify that it is actually using DASH. [Settings screenshot](https://imgur.com/a/P96SJlS).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Taihouu, are u using a VPN?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Videos Are Only Limited to 720p 

Your video player is either set to use Legacy formats, or your video player is having issues with playing the DASH formats and reverting to legacy.

Legacy 

Legacy formats are more of a term coined specifically for FreeTube. YouTube provides a small number of video streams that are traditional MP4 files with the video and audio combined and do not take advantage of DASH. These videos are labeled as “Legacy” videos within FreeTube.

The main limitation of Legacy formats is that a legacy video will never have a quality above 720p.

I think this is happened.
