### ISSUE TITLE
Feature Request - Use ctrl+scroll for playback speed

### ISSUE THREAD

**Issue by codysechelski** [FreeTubeApp/FreeTube#1713]
Allow for playback speed control using ctrl+scrollwheel while your mouse cursor is over the video. A ctrl+click on the video will quickly return it back to 1x.

This is a feature that is in the popular "Enhancer for YouTube" browser plugin for Chrome and Firebox. This is super helpful for long tutorial-based videos as it allows you to ramp the speed up and down quickly while scrubbing through the video. 

![image](https://user-images.githubusercontent.com/1571418/133670562-0ff82ec3-6911-4393-81a1-a91cec651c60.png)

**Comment by codysechelski** [comment]
I would like to work on this feature is possible

**Comment by jasonhenriquez** [comment]
@codysechelski Awesome! One important requirement is that this behavior should be toggleable in the Player Settings and set to off by default. Good luck, and feel free to ask if you need any help.

**Comment by codysechelski** [comment]
Hey @jasonhenriquez, I'm taking you up on your offer for help 😀. 

I have pretty much implemented this except for one feature.  My plan was to ctrl+scroll to control the playback rate (that part is working) and to return to 1x (or the user's default playback rate) on a ctrl+click of the video. I am able to respond to the click event and if the ctrl key is pressed, it returns to the appropriate playback rate, but the video also pauses. 

I thought it would be simple to modify the "click" event for toggling play/pause and ignore clicks when the ctrl key was pressed, but it's not obvious to me where that code is. I figured it would be in the ft-video-player.js, but I'm not seeing it.

Can you give me any pointers on where I can look for this? I'm still learning the codebase and even though I have experience with vanilla js web components, Vue is something that is still pretty new to me.

THANKS!

**Comment by jasonhenriquez** [comment]
Just to clarify, the idea is that CTRL+Click while hovering over the video region will set the playback rate to 1x (regardless of default playback) and only when this new CTRL+Scroll setting is set to active?

Offhand, I would think that the code for stopping a video on the click event is implemented by the library we use for videos, Video.js. However, for your purposes, I think you should only have to call preventDefault and stopPropagation on the click event (and make sure to catch it before the "stop video" event listener, a problem I am hoping you will not have to worry about).

**Comment by codysechelski** [comment]
Thanks for the reply.
You are correct in that the ctrl+click action will only fire when the "scroll to change playback rate" option is turned on in settings. At first, I was going to return it to 1x, but I later thought it would be better to return it to whatever the user has selected as their default playback speed, I don't have a strong opinion on which is better and I'm open to suggestions.

Thanks for the suggestion. I think stopPropagation might be the answer, I'll give it a shot.
