### ISSUE TITLE
Gconf dependency

### ISSUE THREAD

**Issue by linxoln** [FreeTubeApp/FreeTube#172]
"error while loading shared libraries: libgconf-2.so.4"

Works fine with Gconf installed.  

Would be nice if it wasn't needed as it is deprecated but I have no idea how feasible it is to replace...?

(Using 0.3.2 on Arch Linux)

Thanks

**Comment by PrestonN** [comment]
Yeah I've seen this issue from several people now and it seems to be Arch specific and has to do with Electron itself.  I will make sure that Electron is up to date along with the next release which should hopefully fix the issue.  I will keep this open in the mean time though in case anyone else comes across the issue.

**Comment by PrestonN** [comment]
Could you guys check and see if 0.4.0 fixes this issue? Electron was updated and I couldn't see any dependency issue. If this is fixed then we can close this.

**Comment by secremgithub** [comment]
New install from the deb didn't work. I have other electron based apps could that be a problem?

I'm using the appimage now.

**Comment by PrestonN** [comment]
An update to Electron seems to have fixed this.  I have tested this on Ubuntu 18.04 and the error seems to be gone now.  I will close the issue since this will be fixed with the next release.
