### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by ghostlyentity** [FreeTubeApp/FreeTube#1722]
**Behavior of the program**
when starting up the entire program is white(blank

**Expected behavior**
load

**To Reproduce**
open 1201 or 1202

**Screenshots**

![Screenshot from 2021-09-20 06-35-03](https://user-images.githubusercontent.com/86599520/133957568-aedab0d6-f58e-42e3-ba9d-85b87b2dd0c8.png)

**Environment Information (please complete the following information):**
 - OS: Solus
 - OS Version: [4.2]
 - FreeTube version: [1201, 1202]
 - Installation Method (AppImage]
 - Primary API Used: [Local API]

**Additional context**
this is likely a cause of the change from npm to yarn?, was tested on two different machines

**Comment by ghostlyentity** [comment]
oh wow that was mighty quick, thank you for such a swift correction, it all loads fine again

**Comment by PikachuEXE** [comment]
@ghostlyentity 
If you are using [build 1203](https://github.com/FreeTubeApp/FreeTube/actions/runs/1252405514)
It's started by my PR and it's not "official" yet
Will reopen this until it's "officially" fixed

**Comment by ghostlyentity** [comment]
understandable
i am indeed using this build and it fixed it, so far i it appears it also fixed the issues of #1674 and #1705 or at the very least i havent noticed any videos not appearing in the history yet.

**Comment by KNAPPI23** [comment]
I have this blank page too  Build #1204
Windows 7 X64

**Comment by mapi68** [comment]
Same blank page with Windows 10 x64, latest working night build was 1169.

**Comment by PikachuEXE** [comment]
Thanks!
We already got a fix in #1723
You can test the nightly builds **after** that PR is merged and you can subscribe to that PR
