### ISSUE TITLE
FreeTube uses tons of CPU suddenly after a decent amount of watchtime in a single stretch

### ISSUE THREAD

**Issue by rsmyst** [FreeTubeApp/FreeTube#1726]
I actually began using freetube more due to how CPU efficient it was compared to browser playback. BUT, it seems i've run into an issue.
Watching for more than 40 mins at a time causes CPU usage to skyrocket to 60%-ish from the usual 10-20%.
OPERATING SYSTEM: WINDOWS 10 LATEST PATCH AS OF AUGUST
NOTHING ELSE WAS RUNNING ON SYSTEM EXCEPT FOR 1 BROWSER TAB WHEN USING FREETUBE
IT HAPPENED ONLY ONCE AS OF NOW SINCE I DON'T WATCH VIDEOS ON MY COMPUTER TOO OFTEN. WILL UPDATE WHEN IT HAPPENS AGAIN.

**Comment by jasonhenriquez** [comment]
Hello, please use the provided issue template or we will be required to remove this issue. This bug report is not very helpful without corroborating information about your operating system, the exact circumstances under which this occurred, whether this behavior is rare or happens consistently, etc. Please and thank you.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please provide the requested information for us to evaluate further.

**Comment by rsmyst** [comment]
Good evening.Sorry to inform but I have moved away from freetube as its very much inconvenient for me. I use an app called mytube from windows store now that’s much cleaner looking anf functions better. Sent from Mail for Windows From: efb4f5ff-1298-471a-8973-3d47447115dcSent: Saturday, January 8, 2022 3:53 PMTo: FreeTubeApp/FreeTubeCc: myst; AuthorSubject: Re: [FreeTubeApp/FreeTube] FreeTube uses tons of CPU suddenly after a decent amount of watchtime in a single stretch (#1726) Please provide the requested information for us to evaluate further.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
