### ISSUE TITLE
How-To remove a subscription when it will no longer load

### ISSUE THREAD

**Issue by CurrentWave** [FreeTubeApp/FreeTube#1730]
Hello - I did a search for this but found nothing, so here we go -

**How-To remove a subscription when it will no longer load.**

I now have 2 subscriptions which are dead for all purposes, but right-mouse clicking (most direct route) on the icon at the left hand panel does not offer removal.  The subscription will not load, these are dead links.

I cannot imagine there is not an outside of subscription way to remove - is this a needed feature?  Is this a hidden feature?  Is this a bug?

I leave it to the Mods to file this cry for help in the appropriate location.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @CurrentWave, on the far right side of the search bar u see a profile icon. Click on it > tap on the profile settings button > select profile > scroll down to subscription list > select profile > delete selected profile.

Hope this helps.

**Comment by CurrentWave** [comment]
Perfect!  Thank You
