### ISSUE TITLE
Upgrading video quality causes playback failure

### ISSUE THREAD

**Issue by LynHyper** [FreeTubeApp/FreeTube#1732]
**Behavior of the program**
When video playback starts, changing the quality to be higher causes the video playback to fail with:
```
video append of 1225291b failed for segment #0 in playlist 10-placeholder-uri-10
```
Things of note:
- This doesn't occur when changing the quality to be lower no matter the default quality.
- This doesn't *usually* occur if you pause playback and then upgrade the quality, however, it has failed even when paused before so it seems inconsistent.
- Despite what the error implies, the videos that fail aren't in playlists.

**Expected behavior**
Upgrading the quality on a video shouldn't cause video playback to fail.

**To Reproduce**
1. Go to any video.
2. Start the video.
3. Change the quality from any quality to a higher quality.
4. See the error mentioned above, if the error doesn't occur the first time then reload and try again; it's quite inconsistent.

**Environment Information**
 - OS: Arch Linux
 - FreeTube version: 0.14.0
 - Installation Method: FlatHub
 - Primary API Used: Local API

**Comment by jasonhenriquez** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc That error message was stated to have been displayed under many circumstances, this not being one of them. I think this issue is sufficiently different because it happens only under the action of changing video quality.

**Comment by LynHyper** [comment]
@jasonhenriquez I think this *is* related to that issue, but, whatever mitigation was implemented which fixed it is now being bypassed or has been broken. I've posted a comment on there linking to this issue since this issue has a lot of details.
