### ISSUE TITLE
Cursor changes position in searchbar

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1741]
**Behavior of the program**
If u type something into the searchbar and u go down the list using arrow key u see that the placement of the is on the right. If u go up in the list using the arrow key u see that the placement of the cursor changes.

**Expected behavior**
Cursor doesn't change position.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Type something into the searchbar.
2. use the arrow key to go down the list.
3. use the arrow ket to go back up the list.
4. Cursor placement is changed.

**Link to video**

https://user-images.githubusercontent.com/73130443/134500584-375cb082-c6ad-49a1-804a-cabf448a852b.mp4

**Screenshots**
None.

**Environment Information (please complete the following information):**

    OS: [Windows 10]
    OS Version: [Windows 10 20H2]
    FreeTube version: [v0.14.0-nightly-1222 Beta]
    Installation Method (If applicable): [Portable]
    Primary API Used: [Local API]

**Additional context**
None.

**Comment by jasonhenriquez** [comment]
To clarify, would you like the cursor to default to the position after the last character of any given search result? Makes sense, will be consistent with standard browser behavior.

**Comment by peepopoggers** [comment]
Not able to replicate on latest.
Using: Popos 20.04 (GNU/Linux based on ubuntu)
Installation method: Development

Try without portable mode.

**Comment by peepopoggers** [comment]
Able to replicate on popos.
After the last character would make sense.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> To clarify, would you like the cursor to default to the position after the last character of any given search result? Makes sense, will be consistent with standard browser behavior.

Yes it just needs to stay on the same position. This would indeed make it consistent with browser and yt behaviour.

**Comment by jasonhenriquez** [comment]
> Yes it just needs to stay on the same position. This would indeed make it consistent with browser and yt behaviour.

At least in Firefox, it does not return to the same cursor position when you arrow through the results and return back, just the very last position in any case.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
thats weird i dont have that behavior in FF

**Comment by jasonhenriquez** [comment]
> thats weird i dont have that behavior in FF

Oh, maybe it's different for "Firefox Suggest" and the results from the web? I have the latter turned off.
