### ISSUE TITLE
Automatically open general tab when visiting settings

### ISSUE THREAD

**Issue by peepopoggers** [FreeTubeApp/FreeTube#1742]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
It is nicer to see the general tab automatically appear because it contains settings that are commonly changed.

**Describe the solution you'd like to see implemented**
It would be cool for the general tab to open automatically so the user is brought to the most changed settings tab without needing to click.

**Describe alternatives you've considered**
Opening it manually.

**Screenshots**
![image](https://user-images.githubusercontent.com/72892531/134537565-1e49e43d-584d-44e9-9c57-413f020d4731.png)

**Comment by jasonhenriquez** [comment]
Neat idea. Please use the template!

**Comment by peepopoggers** [comment]
@jasonhenriquez :+1:

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing because of https://github.com/FreeTubeApp/FreeTube/pull/2234#issuecomment-1120459855
