### ISSUE TITLE
Trending and Most popular pages video time displayed

### ISSUE THREAD

**Issue by mapi68** [FreeTubeApp/FreeTube#1744]
**Behavior of the program**
In Trending and Most popular pages there is wrong time video displayed.

**Expected behavior**
Instead of minutes, hours, days, etc is displayed "%".

**To Reproduce**
1. Open Trending and Most popular pages;
2. Compare with my screenshot.

**Link to video**
None.

**Screenshots**
Red arrows are wrong, green OK.

**Environment Information:**
``` 
 - OS: Windows
 - OS Version: 10 Pro 21H1
 - FreeTube version: 0.14.0-nightly-1224 Beta
 - Installation Method: freetube-0.14.0-nightly-1224-setup-x64.exe
 - Primary API Used: Local API
```

**Additional context**
None.

![screenshot_2021_09_23_at_18_09_14](https://user-images.githubusercontent.com/41143572/134553222-39a94382-e314-4652-990f-3a136fca8cfe.png)

**Comment by jasonhenriquez** [comment]
I can't replicate this issue. Please use the provided template. I copied it into your post.

**Comment by peepopoggers** [comment]
This is useless without system version etc please use format.

**Comment by mapi68** [comment]
> This is useless without system version etc please use format.

Done

**Comment by mapi68** [comment]
Please remove this tag 
https://github.com/FreeTubeApp/FreeTube/labels/doesn%27t%20follow%20template

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
do you still experience this?

**Comment by mapi68** [comment]
The same problem, nothing change

![screenshot_2022_05_16_at_21_58_00](https://user-images.githubusercontent.com/41143572/168672353-b9acf59d-5393-4813-9429-fc23115245d0.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could u maybe provide some logs. Maybe that will tell us some more. ```CTRL + SHIFT + i``` and copy the red errors.
