### ISSUE TITLE
local (offline) repository to save my favorite without Google account

### ISSUE THREAD

**Issue by hamedsbt** [FreeTubeApp/FreeTube#1751]
To save my privacy and stop google tracking I don't have gmail (google account).
So its very important for me (and people like me) to track the favorite channels so its require a local (prefer offline) storage to save them.

Thank you developer...

**Comment by jasonhenriquez** [comment]
Hello, just to clarify, you would like the option to save channels?

**Comment by hamedsbt** [comment]
> Hello, just to clarify, you would like the option to save channels?

Yes, save channels at least ;) and It would better save any settings the google can save on their servers. thank you.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@hamedsbt i dont understand your request. It is already possible to save your channels. U can export the subscription file.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please clarify your request
