### ISSUE TITLE
error message in xfce

### ISSUE THREAD

**Issue by nanoitch** [FreeTubeApp/FreeTube#1752]
I get this error message when opening freetube_0.13.2_amd64.AppImage or freetube_0.14.0_amd64.AppImage.
"xdg-settings default-url-scheme-handler not implemented for xfce"
If I click OK the program launches and works as normal
the error message appears on every start
I'm using PCLinuxOS with XFCE 4.16

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi does this still happen to u?

**Comment by nanoitch** [comment]
Just did a clean install of PCLinuxOS XFCE edition and then updated
Rebooted and installed Freetube from repo and downloaded the freetube appimage.
The error message I reported before no longer appears on either version.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not if we had anything to do with the fixing of it could. Maybe updating one of our dependenciess fixed it for u. Hard to know at this point because this was reported a few versions back. If u ever run into this again. Please reach out to us!
