### ISSUE TITLE
Opening new tabs leads to a blank white page

### ISSUE THREAD

**Issue by shamuwu** [FreeTubeApp/FreeTube#1753]
Behavior of the program
Opening a video or channel in a new tab via middle mouse or ctrl-lmb opens a blank white page (no sidebar etc. visible). Reload or force reload does not fix the issue.
However, opening a link from a video description to any page works properly.

Expected behavior
The app used to open new tabs just fine until ~2 weeks ago.

To Reproduce
Open any channel or video in a new tab.

Environment Information:
    OS: Windows 10 Pro
    OS Version: 21H1
    FreeTube version: v0.14.0 Beta Release
    Primary API Used: Local API

![ft1](https://user-images.githubusercontent.com/91381892/134776258-2d9d4a5b-b531-46f5-b14d-b029cb974945.png)

**Comment by jasonhenriquez** [comment]
Thank you for posting this issue. Thankfully, this bug has been fixed and will be in the upcoming release. You can [download the latest nightly build here](https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml) to use the app with the fix. Please let me know if there is anything else I can do to help!
