### ISSUE TITLE
Opening link from terminal or script does not open the video with electron-flags.conf set to use wayland

### ISSUE THREAD

**Issue by burrhole** [FreeTubeApp/FreeTube#1756]
**Behavior of the program**
When running `freetube $url` from a terminal or shell script, freetube opens but does not go to the video when electron-flags.conf is set to 
```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```

**Expected behavior**
Freetube should open the video provided in the command line option, as it does without the electron-flags.conf file, even when using `freetube --enable-features=UseOzonePlatform --ozone-platform=wayland $url` or changing the freetube.desktop file to `Exec=freetube --enable-features=UseOzonePlatform --ozone-platform=wayland %U`

**To Reproduce**
Make $HOME/.config/electron-flags.conf (or possibly $HOME/.config/electron13-flags.conf, i have both), and add 
```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```
to it, then open a terminal and run, for example, `freetube "https://www.youtube.com/watch?v=xcJtL7QggTI"`
**Environment Information (please complete the following information):**
 - OS: Arch
 - FreeTube version: 0.14.0-2 from https://aur.archlinux.org/packages/freetube/
 - Primary API Used: Local API

**Additional context**
I'm thinking this could be an electron issue, however the same set of steps works just fine to open a url in chromium.

**Comment by BirdInFire** [comment]
Any news on this, now that nvidia work by default (fedora) on wayland the wayland support must be one of the top priority.

**Comment by lurkynerd** [comment]
Can confirm forcing Wayland doesn't work with Freetube.
