### ISSUE TITLE
Search suggestion doesnt stay within the suggestionsbox

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1769]
**Behavior of the program**
When a search suggestion gets too long it gets outside of the suggestions area.

**Expected behavior**
I would like to see the suggestions box not break. we can do multiple things here we could change the size of the searchbar like yt does and we can make the search suggestions box bigger then the size of the searchbar when query gets too long, see screen.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open FreeTube
2. Click on searchbar
3. Copy and paste abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz song

**Link to video**
None.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/73130443/135585563-ade47bc4-30a0-4633-aab4-c51b7514286a.PNG)

![Screenshot (231)](https://user-images.githubusercontent.com/73130443/135585564-4436b77f-faff-4fea-836c-0636d0656525.png)
**Environment Information (please complete the following information):**
    
    OS: [Windows 10]
    OS Version: [Windows 10 20H2]
    FreeTube version: [v0.14.0-nightly-1224 Beta]
    Installation Method (If applicable): [Portable]
    Primary API Used: [Local API]

**Additional context**
None.

**Comment by peepopoggers** [comment]
Guessing this is just an overflow: none
