### ISSUE TITLE
Remove English (UK) from language options or refactor

### ISSUE THREAD

**Issue by peepo5** [FreeTubeApp/FreeTube#1775]
**Topic**
Please select what topic your discussion is about.
- [x] Languages

**Discussion**
The differences between English (US) and English (UK) are very weird and inconsistent.
Some places have titlecasing removed, others have - added but those are both inconsistent changes.

I feel like maintaining and extra variant of English which has very little differences is not needed, however some may disagree with that opinion. Nevertheless, lots of changes in the UK version are very inconsistent and I think it should be addressed.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I understand where you're coming from but the English - UK language wont get removed because we dont want to exclude users that prefer this language. Also the minor inconsistencies your talking about can be easily solved by the community and shouldn't be done by us.
