### ISSUE TITLE
0.40 Beta - Invidious API call errors

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#178]
Since installing 0.40b  I have been noticing frequent API errors for Invidious.    This results as with the old Youtube API, having the Subscription loading fail  and favorites to be empty

**Comment by Zypherspace** [comment]
Same error from with Whonix VM. The progress bar (nice new feature!) goes to about 90% (cuing all youtube subs I assume) then returns the error:

`There was an error calling the Invidious API.`

Is Invidious compatible through the TOR TCP gateway? Maybe a toggle under settings to ignore Invidious would fix.

**Comment by PrestonN** [comment]
I was able to reproduce the issue.  This was something that I did not encounter during testing.  I will update on here when I find anything out.  So far the error is very inconsistent where sometimes it will happen and sometimes it won't.

> Is Invidious compatible through the TOR TCP gateway? Maybe a toggle under settings to ignore Invidious would fix.

I don't know why it wouldn't be.  Though if I ignored Invidious that would basically make the Tor functionality non existent.

**Comment by grrrrr** [comment]
> I was able to reproduce the issue. This was something that I did not encounter during testing. I will update on here when I find anything out. So far the error is very inconsistent where sometimes it will happen and sometimes it won't.

Yes, I have been trying to figure it out but more recently it has been behaving its self

**Comment by thebrowser** [comment]
It doesn't work at all on 4.0, and now not even 3.2 when I tried to install back the old version. Is this happening anyone else? I tried to clear everything, reinstalling, clearing firewall rules, appdata, etc, but no result...

**Comment by alex-esc** [comment]
@thebrowser It happened to me, so far I found no solution, so I have switched temporally to an rss reader + mpv untill the next release.

**Comment by PrestonN** [comment]
Hey everyone,

I've added some changes to FreeTube that should handle these errors better.  The errors themselves are on the Invidious end and I have no control over this.  @omarroth is keeping an eye out for solutions.

In the mean time, I have it so subscriptions should still load properly even if a channel or 2 fails to load.  You will be made aware which channel failed to load while your subscriptions are loading.

Expect to see a fix released some time this weekend, hopefully later today if I have the time.

**Comment by alex-esc** [comment]
@PrestonN Version 0.4.1 completely solved the issue, thanks!

**Comment by PrestonN** [comment]
Closing as there has been no further reported issues.  The last 2 releases should have fixed these issues.
