### ISSUE TITLE
If selected default resolution isn't available, the next lower isn't selected

### ISSUE THREAD

**Issue by merspieler** [FreeTubeApp/FreeTube#1781]
**Behavior of the program**
I've set the default res to 1080p, a video, which is only available in 360p and 720p plays in 360p.

**Expected behavior**
The video plays in the next lower resolution from the selected one, in this example 720p

**To Reproduce**
1. Set Default resolution to 1080p
2. Open a video with lower res than 1080p https://youtu.be/PvTCc0iXGcQ for example
3. See selected resolution is not the new lower one.

**Link to video**
https://youtu.be/PvTCc0iXGcQ (available in 720p and 360p), 100% of the time reproducible

**Environment Information (please complete the following information):**
 - OS: Debian
 - OS Version: Testing
 - FreeTube version: v0.14.0-nightly-1169 Beta
 - Installation Method (If applicable): .deb
 - Primary API Used: Local

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
not completely true try this one https://youtu.be/v3dclL2grbs

**Comment by F-I-R-E-F-O-X** [comment]
This is still happening on v0.17.1 Beta.

Additionally, the resolution on the video player will still show the default resolution until you mouse over it (1080p for example) but once you do mouse over it, the selection list will show which resolutions are actually available for the the video. (The video I just checked on only went up to 720)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This seems to be fixed in [the latest nightly builds](https://docs.freetubeapp.io/development/nightly-builds).
