### ISSUE TITLE
Localize `Cut`, `Copy` and `Paste` in the search bar

### ISSUE THREAD

**Issue by ovari** [FreeTubeApp/FreeTube#1785]
**Behavior of the program**
Show Cut, Copy and Paste shown in English.

**Expected behavior**
Show Cut, Copy and Paste in the correct locale, i.e. Hungarian.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Copy a youtube link
2. Right-click in the search bar
3. Cut, Copy and Paste shown in English, not Hungarian.

**Screenshots**
![kép](https://user-images.githubusercontent.com/17465872/135743982-ecca4dd4-5908-4baf-81da-dae6a561b6f6.png)

**Environment Information (please complete the following information):**
 - OS: GNU/Linux
 - OS Version: Linux Mint 20.2 Cinnamon
 - FreeTube version: v0.14.0 Béta
 - Installation Method (If applicable): FlatHub

Thank you

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Its better to discuss this over at #673
