### ISSUE TITLE
Upcoming scheduled videos are shown with a negative seconds post date

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#179]
This is the first time I've seen a video that is public but scheduled to be made available in the future

https://www.youtube.com/watch?v=kIS-2y64SEg

As you can see in the screenshot it was posted `-83135 seconds ago` (23hrs)  when it will not actually be available to view for another 23 hours

![future_post](https://user-images.githubusercontent.com/1025506/47256263-82c05780-d46c-11e8-954a-044cf38d8d04.png)

It would be useful to be able to detect such future scheduled videos and put the correct air date

**Comment by PrestonN** [comment]
This has been fixed.  Premiered videos will show when they air instead of negative seconds..
