### ISSUE TITLE
PR: WIP tag is not removed after moving a PR from Draft to Ready

### ISSUE THREAD

**Issue by codysechelski** [FreeTubeApp/FreeTube#1790]
**Important note**
Please check other open and closed issues for a similar discussion or a question relating to your discussion before posting a new one. 

**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [x] Setup
- [ ] Other. Please specify:

**Discussion**
The `PR: WIP` Label does not get removed when a Draft PR is moved back to "Ready for Review". I'm guessing that it should, but I'm pretty new to the whole github automation scene 😀

Also, should the tests be rerun after a PR moved from "Draft" to "Ready"?

On PR #1745, I pushed a commit. The tests went red because the "PR was not in the proper state". I then marked the PR as "Ready for Review", but the tests did not run again. So I ended up pushing a commit that did not make any "real" changes just to see if all of the tests will pass.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
There is no automation for this yet see https://github.com/FreeTubeApp/FreeTube/issues/1720. I'll add the proper label to it. Could u ask that question about the tests in the PR so the others can see it? I dont have a proper answer for it.

I'll close this issue after u copied ur question over to the PR.

**Comment by codysechelski** [comment]
Thanks! I copied the question to the PR.
