### ISSUE TITLE
Add settings option for ionicons

### ISSUE THREAD

**Issue by peepo5** [FreeTubeApp/FreeTube#1794]
**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify:

**Discussion**
The icons from [ionicons](https://ionic.io/ionicons) look subjectively better, cleaner and less clunky than font awesome icons.
While there are less available, they are arguably more consistent in design. I would like to hear some feedback on the differences.

Regarding licensing, ionicons are completely open sourced and you can check more out about it on their [website](https://ionic.io/ionicons). I feel like the current icons look too 'bubbly' and if a prototype showing how they would look in use is created, it would aid in knowing if it would make freetube look better aesthetically.

**Examples**

font awesome:
![image](https://user-images.githubusercontent.com/72892531/136069640-aab02ba8-9be3-44e8-84b0-f26e6a8800fe.png)

ionicons:
![image](https://user-images.githubusercontent.com/72892531/136069697-b015b071-67a4-4f2e-b45b-00f150695449.png)

font awesome:
![image](https://user-images.githubusercontent.com/72892531/136069808-583fed1c-53a5-416f-ac3f-25bf6d65711a.png)

ionicons:
![image](https://user-images.githubusercontent.com/72892531/136069840-f46629c5-c2c4-4f72-8be7-176463e591a3.png)
![image](https://user-images.githubusercontent.com/72892531/136069895-2a0db60e-6aaf-498c-b234-21e36d1be277.png)

font awesome:
![image](https://user-images.githubusercontent.com/72892531/136070127-1c863fc8-783c-4e8b-9526-8b1e226b7af8.png)

ionicons (equivalents):
![image](https://user-images.githubusercontent.com/72892531/136070298-ca10e754-fbab-4b81-a258-abddb1f3516d.png)
![image](https://user-images.githubusercontent.com/72892531/136070240-787213e0-4db3-4876-a8c6-f39008bc10f6.png)

font awesome:
![image](https://user-images.githubusercontent.com/72892531/136070354-e4b932ba-59a6-4358-8f91-83c80d7b1430.png)

ionicons:
![image](https://user-images.githubusercontent.com/72892531/136070407-d93fe55b-c7c2-40c6-9fff-72d845f7f20c.png)

fontawesome:
![image](https://user-images.githubusercontent.com/72892531/136070817-3ff00d59-2258-4f6b-9ee9-184141872e8f.png)

ionicons (flip this icon):
![image](https://user-images.githubusercontent.com/72892531/136070848-378a99ce-e563-44b7-9f3b-171b94ccbe21.png)

fontawesome:
![image](https://user-images.githubusercontent.com/72892531/136070928-5d0fe204-328d-4363-87a2-2bf7f86b6542.png)

ionicons:
![image](https://user-images.githubusercontent.com/72892531/136071073-57667db1-93c6-4fa5-b7b0-373d3267b9f7.png)
![image](https://user-images.githubusercontent.com/72892531/136071108-07100c42-3933-48b2-b1c5-35553e5dce8e.png)
![image](https://user-images.githubusercontent.com/72892531/136070974-08516d58-d8a2-4642-96dd-df5f658c8c8a.png)

fontawesome:
![image](https://user-images.githubusercontent.com/72892531/136071330-099b625d-e068-46c9-a320-1f4267ad8b13.png)

ionicons:
![image](https://user-images.githubusercontent.com/72892531/136071360-7e1c33f5-59d3-4d15-922c-36e03841b08f.png)
![image](https://user-images.githubusercontent.com/72892531/136071579-f1c358f4-8c0c-4742-b155-fa22da4e7799.png)

fontawesome:
![image](https://user-images.githubusercontent.com/72892531/136071427-a6cbd427-0d50-4412-8461-758b135e0fa0.png)

ionicons:
![image](https://user-images.githubusercontent.com/72892531/136071456-82a3d685-d9a1-44de-bf81-62762517a896.png)
![image](https://user-images.githubusercontent.com/72892531/136071480-31852543-5a3d-45a5-987e-f415fd8da203.png)

fontawesome:
![image](https://user-images.githubusercontent.com/72892531/136071629-9053c119-9039-4706-8d71-7b74a10a0ab1.png)

ionicons:
![image](https://user-images.githubusercontent.com/72892531/136071677-315b0939-c4d9-46be-8935-a582736bbe79.png)
![image](https://user-images.githubusercontent.com/72892531/136071701-874744f0-d56a-438e-9a2f-347b24144e12.png)

**Comment by ChunkyProgrammer** [comment]
Just gonna add this link on how to use the icons https://ionic.io/ionicons/usage

**Comment by peepopoggers** [comment]
@ChunkyProgrammer what are your thoughts

**Comment by ChunkyProgrammer** [comment]
I have no preference

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Maybe we can have this integrated into the theme section so the user can choose the icon pack they like

**Comment by PikachuEXE** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
Yup
I think the current is fine
And I dislike **taking away** stuff that might be liked by users
If this icon set is introduced as an *option* then it's fine (And I might try it out when introduced)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I also thought about that but feels kinda weird to me

**Comment by jasonhenriquez** [comment]
The Ionicons, subjectively speaking, evoke a look that I often see in Linux software. If we were to ever have shareable theme settings configurations, this would be great for a "Linux" theme config (e.g., something like dark mode, Ionicons, hide side labels by default, blue primary theme, green secondary theme).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing because i couldnt find good replacements for some icons
