### ISSUE TITLE
Add a feature to mark a video as not watched

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#180]
It would be helpful to be able to mark a video as unwatched.

In #179 I came across a video that was not scheduled to be viewable for 24 hours in the future.  I was not aware that this was the fact until I had clicked into the video and as a result having it marked as `watched` even though I was not able to.

![future_post](https://user-images.githubusercontent.com/1025506/47256333-fadb4d00-d46d-11e8-9cab-10176a822156.png)

As FreeTube works at the moment I have two choices,  either mark the video as a favorite and come back to it later for viewing  or try and remember that I have not actually watched it yet.

**Comment by PrestonN** [comment]
I've added a "Remove from history" button in the sub menu for each video that is in the user's history.  This will allow you to remove individual videos from your history.  Expect to see this in the next release.
