### ISSUE TITLE
Dropdowns arent working properly

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1804]
**Behavior of the program**
When u click on some dropdowns they wont open.

**Expected behavior**
Dropdowns open properly like all other dropdowns

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to settings page
2. Click on General Settings to fold out
3. Click on Preferred API Backend or Thumbnail Preference

**Link to video**

https://user-images.githubusercontent.com/73130443/136675760-9affbb3b-632c-401b-bad0-28d7f786100e.mp4

**Screenshots**
None.

**Environment Information (please complete the following information):**
OS: [Windows 10]
OS Version: [Windows 10 20H2]
FreeTube version: [v0.15.0-nightly-1266 Beta]
Installation Method (If applicable): [Portable]
Primary API Used: [Local API]

**Additional context**
None.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Dropping this here.


https://user-images.githubusercontent.com/73130443/232821372-8a89ad47-3416-45eb-bebb-5720dfd16afd.mp4


https://user-images.githubusercontent.com/73130443/232821381-a852a076-1cfc-432c-9d1b-6d2810377096.mp4


https://user-images.githubusercontent.com/73130443/232821386-ffee3d9d-73a6-4625-b30c-268aee0f056a.mp4


https://user-images.githubusercontent.com/73130443/232821393-219a8757-4b05-4f74-a255-cb6b0234317d.mp4






Based on all videos i can draw the following conclusions

- clicking on the arrow only works when the dropdown is big enough
- when a dropdown is large u can click outside of the dropdown area to expand it

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @pkrasicki is this also something you like to work with? You can fix the current drop downs but if you want to create a better kind of dropdown thats also okay

**Comment by pkrasicki** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc hi, yeah, I can take a look :).
