### ISSUE TITLE
Handling of Youtube video links in comment with middle mouse button is unexpected

### ISSUE THREAD

**Issue by PikachuEXE** [FreeTubeApp/FreeTube#1809]
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**
FT opens a new window as embedded browser and navigates to the YT video page (with tracking and ads :S)

**Expected behavior**
FT should open a new window, change to player view and play that video
Just like when you click the link with left mouse button

**To Reproduce**
Please add all steps to reproduce the behavior:
1. https://www.youtube.com/watch?v=qNWNArktMvY&list=PLzFTGYa_evXgy_taoUv9a_8VD2yR6WihK
2. Expand comment section and change "Sort By" to "Newest First"
3. Scroll down to "Vocal Version: (URL of another YT Video)"
4. Click with middle mouse button

**Link to video**
https://www.youtube.com/watch?v=qNWNArktMvY&list=PLzFTGYa_evXgy_taoUv9a_8VD2yR6WihK

**Screenshots**
Comment with link
![image](https://user-images.githubusercontent.com/1018543/136728431-c11275c1-c356-43d5-b4b9-e83b3b1c34ef.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: v0.15.0-RC-1239 Beta
 - Installation Method (If applicable): Portable
 - Primary API Used: Local API

**Additional context**

**Comment by PrestonN** [comment]
Should be fixed with https://github.com/FreeTubeApp/FreeTube/commit/2be2301d92e37d13a4839ded1fc436836292b7d4

**Comment by PikachuEXE** [comment]
I kind of expect it to open in new window
But I can implement that myself later

**Comment by PrestonN** [comment]
Ahh, I see what you mean. Was mostly wanting to get this fixed as soon as possible to fix the potential security issue. Should be simple to add though
