### ISSUE TITLE
Missing strings for translation

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#181]
Looking at https://github.com/FreeTubeApp/FreeTube/blob/development/locales/en-US.json it would appear to be a few string missing for translation.  Such as "Favorite" and "Remember History"

**Comment by PrestonN** [comment]
As of right now, the strings in the locales folder are not being used in FreeTube.  This has caused them to become very out of date with what's in the application itself.  I'm hoping to update them soon and start using them within FreeTube.
