### ISSUE TITLE
Extremely slow video loading/caching lately

### ISSUE THREAD

**Issue by EvilGremlin** [FreeTubeApp/FreeTube#1818]
Lately every video loads extremely slow and stuttery in FreeTube no matter what, in RC build as well. Previously i noticed slow loading only on freshly uploaded unprocessed videos, but now it's every single one. No matter  OS, VPN or DASH/legacy format, it feels like there's some 1Mbps bandwith limit somewhere. For last 3-4 days i have to resort to view everything in browser, which works fine of course. It looks like Invidious API works fine, though still marginally slower than original youtube, i will check for a few days and report more.

 - OS Version: [ Windows 10, Mint 20.2, KDE neon]
 - FreeTube version: [0.14, 0.15]
 - Installation Method (If applicable): [, .exe, .deb,]
 - Primary API Used: [Local API]

**Comment by neonturbo** [comment]
I am having this same issue or one very similar. 

- No VPN or other complex network items like subnets.
-  200M download that works fine with all other services, including Youtube, Netflix, and others. I can stream multiple services simultaneously with no issues.
-  OS Win10
- Local API as primary
- Freetube 0.14 and 0.15

So it loads the video fine at first. Then at some point, all buffering stops or slows to a crawl. The video itself will stop and start, the video might not play but the audio continues to play. You can pause for a few minutes and load a little more buffer, but it never seems to fix itself once in this state. The only way to fix it is to go back to the main menu, and go back into the video or close out this app and view the video again.

This is a completely new install as I just started using this app a couple weeks ago. I started on V14 and did the V15 when it came out recently. I haven't really changed any settings from default other than to make a couple profiles.
