### ISSUE TITLE
Prevent autoplay loops

### ISSUE THREAD

**Issue by Rabcor** [FreeTubeApp/FreeTube#1827]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Sometimes (actually quite frequently in freetube) autoplay will just jump back and forth between two videos, never playing anything else. It'd be great if functionality was implemented to prevent this from happening.

**Describe the solution you'd like to see implemented**
If the video next in the playlist was played within X many previously watched videos, replace it with something from the up next list that hasn't been played within X many watched videos.

The ability for the user to configure X would be nice but not necessary, something like maybe 3 or 5 would probably be sufficient for most cases.

To be absolutely clear about what I mean here, then if aforementioned X for example would be 5, then autoplay would never be allowed to play the same video again unless at least 5 other videos have been watched first.

The logic should also prevent videos with the same or very similar titles from being played too (so when for instance it's a song, it would avoid playing a different upload of the same song)

**Comment by Rabcor** [comment]
> Duplicate of #397

This one I didn't see because the title was terribly poorly phrased

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Yeah there are allot of titles like that dont worry about it :)
