### ISSUE TITLE
invidiousError: certificate has expired

### ISSUE THREAD

**Issue by xeleven11** [FreeTubeApp/FreeTube#1834]
**Behavior of the program**
Launch freetube to default page pops error at center bottom of screen. Subscriptions page loading takes longer than usual and can see red bar at top.

**Expected behavior**
No errors should pop up at startup. Subscription page loading should be instant hardly showing no red bar at top.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Launch 'Freetube'
2. See error

**Environment Information (please complete the following information):**
 - OS: [Ubuntu]
 - OS Version: [Ubuntu 20.10 x64]
 - FreeTube version: [0.14.0]
 - Installation Method: [.deb]
 - Primary API Used: [Local API]

**Additional context**
```
`Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1507)
    at TLSSocket.emit (events.js:376)
    at TLSSocket._finishInit (_tls_wrap.js:932)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706)
Uncaught (in promise) Error: certificate has expired  internal/process/task_queues.js:95
    at TLSSocket.onConnectSecure (_tls_wrap.js:1507)
    at TLSSocket.emit (events.js:376)
    at TLSSocket._finishInit (_tls_wrap.js:932)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706)`
```

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
In the nightlys FT is already on 0.15.0 but the official release of 0.15.0 has yet to come

#1621 is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1442 and is still open
