### ISSUE TITLE
Sponsorblock: support more categories

### ISSUE THREAD

**Issue by StuffonGithub** [FreeTubeApp/FreeTube#1840]
**Behavior of the program**
Sponsorblock just doesn't seem to be working on my Freetube. Not sure how else to elaborate. But the "Screenshots" section should be able to help me with clarifying my issue.

**Expected behavior**
Auto-skip segments for the unappreciative free content consumer. 😈 _But in my defence, I only use YouTube to play some music I don't listen to enough to warrant having a locally saved FLAC file._ 😇

**To Reproduce**
Not sure if it's reproducible. Makes me feel like it's an isolated problem since I haven't seen any other posts.
I've tried reinstalling the program, "reapplying" settings, etc.

**Link to video**
Affects all videos for me but here's one connected to my screenshot:
https://www.youtube.com/watch?v=r_0JjYUe5jo

**Screenshots**
Firefox 93.0 (64-bit) (with Sponsorblock):
![image](https://user-images.githubusercontent.com/65162653/137956387-f1be25dc-1821-4e98-a976-cbb3816e5c68.png)

Freetube v0.15.0 Beta:
![image](https://user-images.githubusercontent.com/65162653/137956542-75f34ab6-d48d-416b-ac3f-c7a7714ffded.png)

This is the only thing showing up on my Sponsorblock Settings. Seeing https://github.com/FreeTubeApp/FreeTube/issues/1439#issuecomment-896579285 makes me think something's not loading for me.
![image](https://user-images.githubusercontent.com/65162653/137957931-20e92d3a-091e-49e9-b259-713a27f33e1a.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 21H1 build 19043.1288
 - FreeTube version: v0.15.0 Beta
 - Installation Method (If applicable): freetube-0.15.0-setup-x64.exe
 - Primary API Used: Local API

**Additional context**
Hi, I've searched previous issues and didn't find anything related. I also read that the devs doesn't really want to work on SponsorBlock so I hope a general question thread to the community is okay here since the subreddit is restricted and I have no idea where else to ask.

Closest related issue I've found is the video posted in https://github.com/FreeTubeApp/FreeTube/issues/1439 where sometimes the segment highlights doesn't show up when he opens a video. But obviously, Sponsorblock still works for him.

I've tried all the basic troubleshooting that I know but the result's the same. Any help would be appreciated.

**Comment by StuffonGithub** [comment]
@ChunkyProgrammer You got it! And wow, thanks for working on it immediately! I don't mind if it'll take a while, there are more important stuff on the to-do list after all. But thanks!

**Comment by xdpirate** [comment]
This is literally the only reason stopping me from using FreeTube full time over the actual YouTube website in a browser, hope the changes from @ChunkyProgrammer will be merged for the next release!
