### ISSUE TITLE
Remember videos loaded from "Fetch more results" on channels

### ISSUE THREAD

**Issue by Winterhuman** [FreeTubeApp/FreeTube#1842]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
In the search results page, clicking "Fetch more results" will load more videos, if you navigate away from the page and come back it will remember the list and won't require you to click "Fetch more results" over and over again to get to the same point.

However, this doesn't happen when clicking "Fetch more results" on a channel's page, it will forget how many videos you had loaded on the channel page when you navigate away from it, this makes searching through a channel for a particular video you don't know the name of a bit tedious.

**Describe the solution you'd like to see implemented**
The results of "Fetch more results" should be remembered on the channel's page the same way it does for the search results' page.

**Describe alternatives you've considered**
Another option is to change how these lists are populated, for example:
- You could show the number of pages as a horizontal numbered list at the bottom of the page where "Fetch more results" used to be, this would allow you to quickly jump ahead, but, it's not the most visually appealing. Additionally, you'd either have to calculate the total number of pages, or, you'd have to truncate the list to the first 10 pages and then keep searching for the next 10 pages after you reach page 10.
- Or, you could have an infinitely loading list and remove the "Fetch more results" button. I know some people don't like infinite loading though so this is something that would need to be discussed.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2446
