### ISSUE TITLE
Picture-in-picture (PIP) buttons don't work.

### ISSUE THREAD

**Issue by LilLymphocyteB** [FreeTubeApp/FreeTube#1843]
**Behavior of the program**
When a video is playing in a picture-in-picture window, all of the buttons in that window do not work, including the play button, the back to player button and the close window button. I have to use the main FreeTube window to do these actions.

**Expected behavior**
The buttons should work correctly, without having to go back to the main FreeTube window.

**To Reproduce**
1. Play any video
2. Enable picture-in-picture
3. Try any of the buttons in the picture-in-picture window

**Environment Information (please complete the following information):**
 - OS: Pop!_OS (Linux, Ubuntu-based)
 - OS Version: Pop!_OS 21.04
 - FreeTube version: 0.15
 - Installation Method (If applicable): flatpack, but I also tried the .deb, same issue.
 - Primary API Used: Invidious, but the local API doesn't change anything

**Comment by PrestonN** [comment]
I can replicate on my machine. You'll have to believe me when I say this, but I believe it is related to [this](https://github.com/electron/electron/issues/31448) issue with Electron. This seems to be an upstream issue with Electron. When this gets fixed upstream, we'll update FreeTube as well.
