### ISSUE TITLE
Subscriptions can be added more than once

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#185]
There is a probable bug in the subscription that allows you to subscribe to a channel more than ones

**Steps to reproduce**
1. Search for a channel
2. Go into the channel and click on `Subscribe` button, it changes to `Unsubscribe`
3. Search for the channel again
4. Go into the channel.  `Subscribe` is an option
5. Select `Subscribe` for a second time
6. Channel is added to subscription list twice

**What should happen**
1. Search for a channel
2. Go into the channel and click on `Subscribe` button, it changes to `Unsubscribe`
3. Search for the channel again
4. Go into the channel.  and you should be given the option to `unsubscribe` only

**Computer Setup**
* OS: Debian 9
* FreeTube: 0.40b

**Comment by PrestonN** [comment]
This should be fixed with 0.5.0.  Closing
