### ISSUE TITLE
Sudden neverending buffering

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#1856]
**Behavior of the program**
I was watching a video, then it suddenly stopped for a buffering that never stopped, as if my connection was down, but it wasn't, downloading speed was at 0 until i use my connection for other things.

**Expected behavior**
Video playing smoothly, or at least a more effective buffering.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to a video
2. Play it

**Link to video**
Current video i have this problem: https://youtu.be/fe716alkdLU

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.

**Environment Information (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 21.10
 - FreeTube version: 0.15 bêta
 - Installation Method (If applicable): deb
 - Primary API Used: both

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I'll close this because it is already stated that this will be fixed if the upstream issue is resolved https://github.com/FreeTubeApp/FreeTube/discussions/1835#discussioncomment-1497715
