### ISSUE TITLE
Include "Edit Profile" in the same page of "Profile manager"

### ISSUE THREAD

**Issue by sameyepatch** [FreeTubeApp/FreeTube#1860]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Yes. The current way to select profiles for editing is confusing (for me). It goes like this:
1. Click on the current profile indicator and in the dropdown menu click on "Profile Select", which will open the "Profile Manager"
2. Click on a profile, which will open "Edit Profile"
3. Edit your profile, click on "Update Profile"
4. If you want to edit another profile, start from step 1

From personal experience (maybe I'm the only one, but anyways) this flow is kind of confusing, because if I want to edit another profile, I end up selecting another profile by accident instead of clicking on "Profile Select" from the current profile indicator

**Describe the solution you'd like to see implemented**
Let the "Edit Profile" section be included in the same page or section as the "Profile Manager" (Also maybe rename the option "Profile Select" to "Profile Manager" or "Profile Settings" to be more precise). The flow would be as follows:
1. Click on the current profile indicator and in the dropdown menu click on "Profile Select", which will open the "Profile Manager"
2. Click on a profile, and "Edit Profile" will appear below the profile list
3. Edit your profile, click on "Update Profile"
4. If you want to edit another profile, select any profile from the profile list on top, continue from step 2

**Describe alternatives you've considered**
Haven't considered other options

**Screenshots**
This is how it would look like
* The "Profile Manager" would look the usual when no profile has been selected yet
![Screenshot_2021-10-27_12-51-45](https://user-images.githubusercontent.com/31149431/139121841-bbb4b747-8d9c-45c0-be85-dd49482b1061.png)

* When selecting a profile, the "Edit Profile" will appear below the profile list
![freetube](https://user-images.githubusercontent.com/31149431/139122069-61699d42-1637-434a-ad9b-f54f38264c9a.png)

**Additional context**
No additional context that I can think of

**Comment by jasonhenriquez** [comment]
On top of what you already said, for existing profiles, it would be far more convenient to have the Subscription List above the Edit profile section; it's a lot of scrolling down. We can also mitigate that by reducing the size of the color selection area.

![Screenshot_20231119_135835](https://github.com/FreeTubeApp/FreeTube/assets/84899178/9e790477-ac4b-446b-934d-13a8982803c7)
