### ISSUE TITLE
Automatically switch audio format depending on profile.

### ISSUE THREAD

**Issue by absidue** [FreeTubeApp/FreeTube#1861]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Please describe clear and concise of what the problem is. Ex. I'm always frustrated when [...]

I am an avid user of the multiple profile feature in FreeTube and am frustrated by the way that the default formats work at the moment. If you adjust the volume away from the default you have set, it stays adjusted for the rest of the session, the default format however goes back to the default for each new video which is annoying because i have it set to audio only by default for listening to music and then have to adjust the format when i want to watch a video and have to wait for the video to load (hopefully ytdl-core bypasses the throttling soon).

**Describe the solution you'd like to see implemented**
Please give a clear and concise description of what you want to happen.

It would be nice to be able to specify different default formats for each profile. In my case I have a music profile so it would be nice to default to audio formats on that profile and video formats on the other ones.

**Describe alternatives you've considered**
Are there other ways to solve the problem? Please give a clear and concise description of any alternative solutions or features you might have considered.

Alternatively it would be cool if the default audio format worked like the volume, so once you have adjusted it away from the default value it stays like that for the rest of the session.

**Screenshots**
N/A

**Additional context**
Add any other context about the feature request here.

**Comment by jasonhenriquez** [comment]
In the past, I have entertained the idea of 1. profile settings configurations and 2. adjustable scopes for settings changes. Either / both such solution(s) should be sufficient in closing this issue whenever they are implemented, and I do not recommend to other contributors to specially code for this specific interaction. A reasonable enhancement for sure.

**Comment by absidue** [comment]
My preferred solution would be to keep the global settings but allow overrides on a per profile basis, this would allow you to keep most of the settings the same and only change the few ones you actually want to have set differently.

I'm not exactly sure what the UI and UX would look like for a system like this, although I would probably expect to see some kind of indicator on the overriden settings (maybe an asterisk next to the changed settings) and a way to reset a profile back to the global settings values.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Comment mentioned in https://github.com/FreeTubeApp/FreeTube/issues/1996#issuecomment-1483858987, closing.
