### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by jlkdasjkldasklj** [FreeTubeApp/FreeTube#1863]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [X] Other. Please specify: Building from source

**Question**
Hi, do someone know how I can fix this:
The full error: 
```
npm run build                           

> freetube@0.15.0 build
> run-s rebuild:electron pack build-release

sh: 1: run-s: not found
npm ERR! code 127
npm ERR! path /home/user/FreeTube
npm ERR! command failed
npm ERR! command sh -c run-s rebuild:electron pack build-release

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-10-29T19_54_29_936Z-debug.log

```
Thanks in advance !

**Comment by Svallinn** [comment]
I'm assuming you read the docs, specifically this
https://docs.freetubeapp.io/development/building-from-source

If not, shame on you, the link to the docs in right in the README of the project!
If you did, you probably skipped over the very first paragraph without even noticing.

> This article assumes that your development environment is setup. For instructions on how to do so, please see the [Getting Started](https://docs.freetubeapp.io/development/getting-started) page

**Comment by jlkdasjkldasklj** [comment]
Hi, I tried to use `yarnpkg install` to install dependencies but got this error:
`yarnpkg install           
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '@babel/runtime/helpers/interopRequireWildcard'
Require stack:
- /usr/share/nodejs/yarn/lib/cli/index.js
- /usr/share/nodejs/yarn/bin/yarn.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/share/nodejs/yarn/lib/cli/index.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/nodejs/yarn/lib/cli/index.js',
    '/usr/share/nodejs/yarn/bin/yarn.js'
  ]
}
`
I install nodejs v14.18.1 using this link
[](https://github.com/nodesource/distributions/blob/master/README.md#debinstall)

**Comment by Svallinn** [comment]
No idea, can't replicate.
Try adding the latest version of `@babel/runtime` manually (`yarn add @babel/runtime@latest`) and then run the install command again.

**Comment by jlkdasjkldasklj** [comment]
I had to remove yarnpkg using `sudo apt remove yarnpkg` and install it using `npm install --global yarn` then run `yarn install` and then run `npm run build`.
I ran into another issue this one: `ERR_ELECTRON_BUILDER_CANNOT_EXECUTE` but it build a .deb so I don't really care about the error.
