### ISSUE TITLE
Fullscreen button and quality selection don't fit on mobile screen

### ISSUE THREAD

**Issue by pkrasicki** [FreeTubeApp/FreeTube#1865]
**Behavior of the program**
On mobile the fullscreen button and quality selection are not shown in portrait mode. In landscape mode quality selection is visible, but fullscreen button is only partially visible.

**Expected behavior**
Fullscreen button and quality selection should be visible on mobile screen.

**To Reproduce**
1. Use a phone or set your window dimensions to 360x650px on desktop.
2. Go to any video page.

**Screenshots**
![freetube-fullscreen-mobile](https://user-images.githubusercontent.com/49721209/139536216-2b0a9dbb-d1d2-4911-9261-11dd0a09bc93.png)

![freetube-fullscreen-mobile2](https://user-images.githubusercontent.com/49721209/139536242-50f51331-a3b1-4ca9-ba0e-d4d85a5e619b.png)

**Environment Information (please complete the following information):**
 - OS: Mobian
 - OS Version: Bookworm
 - FreeTube version: 0.15.0
 - Installation Method (If applicable): .deb arm64 package
 - Primary API Used: Invidious API

**Additional context**
I can always double tap to toggle fullscreen, so the app is still usable.

**Comment by absidue** [comment]
Completed in #2688
