### ISSUE TITLE
[MacOS] Tabbed "browsing"

### ISSUE THREAD

**Issue by lothar-cell** [FreeTubeApp/FreeTube#1870]
**Describe the solution you'd like to see implemented**
Native OS implementation of tabs, eg. like in Finder and any browser. First tab should be invisible, I mean it is the window itself.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Follow the full template otherwise we will close ur issue. We cant understand what u mean if u dont follow the template and please add and screenshot or video of what u mean.

**Comment by PrestonN** [comment]
Duplicate of #333
