### ISSUE TITLE
[MacOS] Loading FreeTube freezes system for a couple of seconds

### ISSUE THREAD

**Issue by lothar-cell** [FreeTubeApp/FreeTube#1872]
**Behavior of the program**
When starting up FreeTube, system becomes unresponsive for a couple of seconds.

**Expected behavior**
This shouldn't happen. 

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to the FreeTube app.
2. Click on the FreeTube app.
3. Scroll down to nothing
4. See error When starting up FreeTube, system becomes unresponsive for a couple of seconds.

**Link to video**
no video

**Screenshots**
no screenshots

**Environment Information (please complete the following information):**
 - OS: MacOS
 - OS Version: 10.14.6
 - FreeTube version: 0.15.0 (0.15.0)
 - Installation Method (If applicable): .dmg
 - Primary API Used: Local API

**Additional context**
no additional context.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1856

**Comment by lothar-cell** [comment]
Again, this issue isn't a duplicate of #1856. It is about system hang-up, when launching the FreeTube app and not about video buffering.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I'll only consider reopening is if u follow the provided template and provide all the information that is needed to evaluate this.

**Comment by lothar-cell** [comment]
Well, because there are no more information to give on the template, but there you go, I updated it for you nevertheless.

**Comment by lothar-cell** [comment]
Issue gone in v0.16.0 Beta.
