### ISSUE TITLE
Wireless Headset: Audio goes idle in flatpak version on Ubuntu 20.04

### ISSUE THREAD

**Issue by muffinmaster1024** [FreeTubeApp/FreeTube#1874]
My headphones happen to put themselves in standby when there is no audio for a certain time. They also go into this idle state when streaming through Freetube. I have not noticed this problem before on any other app.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could u read through the comments of this issue and tell me if it is the same
https://github.com/FreeTubeApp/FreeTube/issues/1529

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@LynHyper isn't this the same as what u described over in this issue #1529

**Comment by LynHyper** [comment]
No actually, my issue is about reconnecting wireless headphones and having FreeTube (or perhaps electron in general) not using them afterwards.

My headphones do go idle if audio isn't present after a certain amount of time, but I think that's just part of the headphones functionality for me. @muffinmaster1024 Do your headphones permanently go idle when audio isn't present or do they start working when the audio starts again?

**Comment by muffinmaster1024** [comment]
It was after all a headphone related issue. Unfortunately it happened more often and more noticable in FreeTube than on other apps. 
Sorry to have bothered you with that.
