### ISSUE TITLE
Does FreeTube Support HDR Playback?

### ISSUE THREAD

**Issue by pqhf5kd** [FreeTubeApp/FreeTube#1875]
**Important note**
No existing issues about HDR

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [X] Other. Please specify:

**Question**
Does FreeTube support HDR playback?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
HDR is not supported at the moment.
