### ISSUE TITLE
Nightly AppImage changes mimeapps.list

### ISSUE THREAD

**Issue by fcwoknhenuxdfiyv** [FreeTubeApp/FreeTube#1879]
**Behavior of the program**
Whenever I launch the AppImage, it changes the entry for `text/html` to `Freetube.desktop` - it's normally `firefox.desktop`. This breaks xdg-open on the linux desktop when double-clicking html files.

**Expected behavior**
I expect to be able to double-click on an html file and have it open in my browser. The same goes for the html reports for `go test -cover`, etc.

**To Reproduce**
Launch the AppImage and open `~/.config/mimeapps.list` in a text editor. You will see the `text/html` entry has been modified.

**Environment Information (please complete the following information):**
 - OS: Fedora Silverblue
 - OS Version: 35
 - FreeTube version: Nightly build
 - Installation Method (If applicable): .AppImage
 - Primary API Used: Local API

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is this still an issue in [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)?

**Comment by fcwoknhenuxdfiyv** [comment]
I've stopped using Linux desktop. As nobody else is involved with the ticket, should I close it?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah okay. I'll go ahead and close it :)
