### ISSUE TITLE
Missing Invidious instance list

### ISSUE THREAD

**Issue by ariel3557** [FreeTubeApp/FreeTube#1881]
**Behavior of the program**
The list of available Invidious instances to be switched is missing

**Expected behavior**
Display the full list of available Invidious instances to select one. 

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to Settings->General Settings-> 
2. Click on: Current Invidious Instance box
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/7221989/140937828-7bb38c8c-4b54-455a-a8e5-19b53b271591.png)

**Environment Information (please complete the following information):**
 - OS: Windows 
 - OS Version:  Windows 10 
 - FreeTube version: v0.15.0-nightly-1309
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It is not missing try removing everything and search for an specific instance
