### ISSUE TITLE
Video speed issue while playing a game

### ISSUE THREAD

**Issue by BrenzoG** [FreeTubeApp/FreeTube#1884]
While playing a video on second monitor, if I have a game open on steam (have tried DaysGone, FTL, Outerworlds on primary monitor, the speed of the video increases to what seems like 1.25x and distorts the sound. Changing back to 1.0x does not do anything, but going to 0.75x does change correctly. Repeatable on my end, happens every time.

Starting the game first then launching Freetube results in the same issue, so no workarounds that i can find so far.

Closing Freetube and the game and relaunching resolves the issue.

Using Pop!_OS 21.04 and Freetube v0.15.0 beta

3600x, b450 and 1070
Using focusrite solo gen 1, there is audible popping while the audio changes to the faster speed.

**Comment by arrowgent** [comment]
freetube probally doesnt do anything differently than what other electron apps or chromium does
its basically just a browser (steam is also a browser using CEF)

your symptoms are very strange however...

im using ubuntu 18.04 w/ freetube 0.15.0 and have no issues related to gaming and video speed

**Comment by BrenzoG** [comment]
The issue is no longer present, a restart did not fix it originally, but after the second restart it has gone away. Not really sure what fixed it as I have been dealing with this for 4/5 days now.

The only thing I did in the meantime was reinstall the dev version of wine but not sure how that would be related.

Anyways I'll make a video of the issue if/when it crops up again.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@BrenzoG Did the issue occur again?

**Comment by BrenzoG** [comment]
> @BrenzoG Did the issue occur again?

Yes it did, it's a recurring issue, but the source is linux not freetube.  It's solved by forcing pulseaudio to always use 48khz rather than 44, this is what causes the minor slowdown/frequency shift.   Will close now.
