### ISSUE TITLE
Show view to like ratio

### ISSUE THREAD

**Issue by JAIABRIEL** [FreeTubeApp/FreeTube#1891]
Since YouTube doesn't show a videos dislikes anymore (RIP :/ ), it would be useful if we could show the view to like ratio to see at least some kind of response.
![Screenshot from 2021-11-13 11-27-48](https://user-images.githubusercontent.com/31685376/141615274-fd3dc595-61d9-4fac-9a8d-e72c825a1e9a.png)

**Comment by peepopoggers** [comment]
Actually a good idea!

**Comment by jasonhenriquez** [comment]
As discussed in Matrix channel, there is a wide variance on this ratio that is very hard for an average user to meaningfully interpret. This would only be useful if we had statistics on the distribution of likes to views on YT videos, and even then, its value as indicator would be notably distinct and esoteric compared to the dislike button.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing this

> This would only be useful if we had statistics on the distribution of likes to views on YT videos, and even then, its value as indicator would be notably distinct and esoteric compared to the dislike button.

If we have something like this we can consider reopening
