### ISSUE TITLE
back to video play button from picture in picture should return to the video even when the video is closed

### ISSUE THREAD

**Issue by constraintAutomaton** [FreeTubeApp/FreeTube#1893]
**Behavior of the program**
When a video is open in picture in picture and the button back to video is clicked it simply close the picture in picture panel. 

**Expected behavior**
I think it should reopen the video page instead.

**To Reproduce**
1. Go to a video
2. Click on` picture in picture`
3. Go to any other page of Freetube
3. Click on `back to video player` button
4. The panel simply close

**Environment Information (please complete the following information):**
 **Desktop**
    - OS: Ubuntu
    - OS Version: 20.04.3 LTS
    - FreeTube version: v0.15.0 Beta

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/624
