### ISSUE TITLE
Is there a way to make freetube use a cookie, JWT or otherwise to login to an locked down invidious instance/api?

### ISSUE THREAD

**Issue by cocoonkid** [FreeTubeApp/FreeTube#1896]
Is there a way to make freetube use basic auth, cookie, JWT or otherwise to login to an locked-down invidious instance/api?

A option to do basic auth would be hugely beneficial for the proxy setting too.

This would also allow people to use private instances and take load from the public invidious instances as well

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
People can already do this see https://github.com/FreeTubeApp/FreeTube/issues/686#issuecomment-1129274232

**Comment by Green-Sky** [comment]
lies!

`Request cannot be constructed from a URL that includes credentials`

**Comment by Tha14** [comment]
```Invidious API Error (Click to copy): TypeError: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: https://Tha_14:password@invidious.x.x/feed/channel/id```

**Comment by cocoonkid** [comment]
I worked around it by restricting access to my IP range via nginx proxy.

**Comment by Tha14** [comment]
> I worked around it by restricting access to my IP range via nginx proxy.

I consider that insecure. I am currently rewriting freetube to send basic auth with fetch properly.

**Comment by a7maadf** [comment]
@Tha14 
Any updates?

**Comment by H1dd3** [comment]
Hey, just wondering if this was ever implemented? It seems like my ip gets blocked after some time because of too many requests lol.
