### ISSUE TITLE
Bar expand or shrink when unsaving videos

### ISSUE THREAD

**Issue by maplepy** [FreeTubeApp/FreeTube#1897]
**Behavior of the program**
Watch bar gets so big (or small) and is inaccurate when removing a video out of the playlist

**Expected behavior**
Bar doesn't expand or shrink

**To Reproduce**
1. Go into the playlist tab on the left
2. Have a video you watched (with a bar under the video)
3. Unstar any video
4. See the bar either shrink or expand massively

**Link to video**

https://user-images.githubusercontent.com/28269333/142013688-37b25174-d28a-4e34-a248-3d14233d9a68.mov

Yes the quality is awful (480p), I couldn't go beyond 10Mb to upload unfortunately

**Screenshots**
![image](https://user-images.githubusercontent.com/28269333/142010087-aea5ed9f-fbd4-471e-bf19-3e4ad8083558.png)
![image](https://user-images.githubusercontent.com/28269333/142010173-873ee974-3caf-40b6-9962-283bf6399375.png)
![image](https://user-images.githubusercontent.com/28269333/142010145-eedf530c-0b7a-461f-9fab-e030bc44003e.png)

**Environment Information (please complete the following information):**
 - OS: EndeavourOS Linux x86_64 
 - OS Version: Kernel: 5.15.2-arch1-1 
 - FreeTube version: v0.15.1 Beta
 - Installation Method (If applicable): AUR
 - Primary API Used: Invidious

**Additional context**
Of all the bugs encountered, that's the funniest one

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
That is an interesting one indeed. Great catch!

**Comment by peepopoggers** [comment]
When you unstar one video, it may increase the length of watchtime of another which is weird.

**Comment by ClemGlacee** [comment]
The weird thing is that it seems like the amount of saved video has something to do with the bar length. When I remove a star and add it again, I'll get the same bar lengths. 

If for example:

1. I remove a star on a video in my saved playlist, let's say the length of two videos will be 3x and 7x
2. When removing another it will become 1x and 12x (fictional numbers of course)
3. If I add the star on any video that don't have one (the first one I removed at the beginning for example), it will revert back to 3x and 7x as if the number of saved videos have a "predefined" bar length

Also note that unsaving a video and resaving it will prevent its bar length to change

**Comment by ClemGlacee** [comment]
If you need any log, I can send those too

**Comment by PrestonN** [comment]
Should be fixed in the latest nightly builds / today's release. Let me know if you experience the issue again.
