### ISSUE TITLE
Download button is gone? I was using this service to download memorable videos on my drive, please reconsider it.

### ISSUE THREAD

**Issue by kaliyuga1** [FreeTubeApp/FreeTube#1899]
**Behavior of the program**
No download button on video's like there used to be!

**Expected behavior**
I expect there to be a juicy download button for my finger to consume, may I???

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any video
2. Look on the bottom right of the video
3. Do you see a shiny download button? Because I don't

**Link to video**
https://youtu.be/yUnKv4BT3kE

**Screenshots**
![image](https://user-images.githubusercontent.com/52457745/142275317-7a9722f4-c946-4bae-a94a-e7a513ad2c7e.png)

**Comment by peepopoggers** [comment]
I think its something to do with it being a stream. Open in odysee to download for now

**Comment by constraintAutomaton** [comment]
I encounter the same problem too and every time it was a video that was streamed. Maybe it can be fixed by getting the download link from individous when no candidate is available in the local api?
