### ISSUE TITLE
Results have seemed quite irrelevant to the search term for the past couple of days

### ISSUE THREAD

**Issue by rjdg14** [FreeTubeApp/FreeTube#1903]
I've been finding that search results have seemed far less relevant than what they were previously, while on YouTube's site they seem the same as before as far as I can tell. The search results now seem to take either the first or the most common word into account and give very little account of other words, which previously made a lot of difference in what the client's search tool brought up and made the results much more relevant to what the query was. As far as I can tell there has been no change to the search results algorithm on YouTube, which makes me wonder what's causing this. The problem seems to be most prevelant when the API is set to Invidious, but is also there when I switch to Local.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
do u have some example data for me to test?
