### ISSUE TITLE
Enable "Hide Video Views" does not hide video views in the playlist

### ISSUE THREAD

**Issue by sw5fmnc3** [FreeTubeApp/FreeTube#1905]
**Behavior of the program**
Enable "Hide Video Views" does not hide video views in the playlist.

**Expected behavior**
Hide video views in the playlist when "Hide Video Views" is enable.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open FreeTube
2. Click on "Settings"
3. Click on "Distraction Free Settings"
4. Enable "Hide Video Views"
5. Open a playlist of some kind

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/94696295/142645063-f64e8cfd-0254-4664-96ad-26faaf7c1b51.png)

**Comment by hb-coding** [comment]
I can take this issue

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sure go for it!
