### ISSUE TITLE
Hide "Toggle Theatre Mode" when "Hide Recommended Videos" is enable

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#1907]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
When "Hide Recommended Videos" is enable, the video player is forced to go into Theatre Mode, so I think should be hide "Toggle Theatre Mode" when "Hide Recommended Videos" is enable.

**Describe the solution you'd like to see implemented**
Hide the "Toggle Theatre Mode" of the video player when "Hide Recommended Videos" is enable.

**Screenshots**
![screenshot3](https://user-images.githubusercontent.com/94696295/142708069-36854807-1663-4f66-b815-11fab2d3adbc.png)

**Comment by peepopoggers** [comment]
this makes no sense.

**Comment by peepopoggers** [comment]
this makes sense.

**Comment by sw5fmnc3** [comment]
**Additional context**
Open a playlist or LIVE, it will not be forced into Theatre Mode.
It is only when open a video that it will be forced into Theatre Mode.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This seems to be implemented in the latest nightly build
