### ISSUE TITLE
New version crashes on opening video, Win7 x64 SPI

### ISSUE THREAD

**Issue by gpilot24** [FreeTubeApp/FreeTube#1908]
Hello:

Version 15.0 did not crash.  Some of the issues addressed by the v 15.1 update were present on v15.0, buffering issues mostly.

I can open the app (15.1)  on my PC.  All menus and search appear to work.  As soon as I click on a video link, the video image (still image) will open and the **audio** plays for about 3 seconds.  Then I get a windows crash message as pasted below.  The video never begins.

Please don't ask me to (down)grade to Win 10.  When I can't continue to use Win7,its Linux for me.  I wont get into it here for this problem report.  All updates to Jan 2020 are on the Win7 x64 SP1 system. Please contact me if you need more information.  The system is running a core i7 6700 with 8 Gb ram.  Locally stored videos play fine on vlc.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	FreeTube.exe
  Application Version:	0.15.1.0
  Application Timestamp:	6189679d
  Fault Module Name:	FreeTube.exe
  Fault Module Version:	0.15.1.0
  Fault Module Timestamp:	6189679d
  Exception Code:	c0000005
  Exception Offset:	00000000004e0903
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	6bf1
  Additional Information 2:	6bf10fa8aa45fd539e87ea3d291a83a9
  Additional Information 3:	0fd1
  Additional Information 4:	0fd1cbae0a4ab9b20165920fef308b6f

The system is running a core i7 6700 with 8 Gb ram.

**Comment by gpilot24** [comment]
Sorry, this seems reported in issue 1886.  Closing

**Comment by peepopoggers** [comment]
Win7 is broken due to electron update, use last freetube version for now.

**Comment by peepopoggers** [comment]
Off topic, but I would recommend linux over win7 (you can test with dual boot or using USB), as it may be actually more compatible with programs and games than windows 7 is now. It is a great operating system with a diverse range of distributions and customization, so give it a try :)
