### ISSUE TITLE
No title bar, videometada (likes, views, publish date, buttons to save etc.) on some videos of the same channel

### ISSUE THREAD

**Issue by maplepy** [FreeTubeApp/FreeTube#1911]
**Behavior of the program**
On some channel (I have found one for now) the "header" above the comments, so the bar with all of the video information (channel name, title, subscribe button, publish date, like, dislikes etc.) is missing.

**Expected behavior**
The "info" bar is visible on every video as you'd find it on any other video

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to this channel for instance https://youtube.com/channel/UCjrj3gdo-KL2S_JN_gdNyPw
2. Click on any of the video he published (except the second one, see the screenshot)
3. Don't find the title bar
4. Be sad because you can't share the youtube video link

**Screenshots**
![image](https://user-images.githubusercontent.com/28269333/143085607-28b2412e-cdc5-403c-ae51-25c8ebd0b58c.png)
![image](https://user-images.githubusercontent.com/28269333/143085828-b25a6a14-f9ed-45d2-9a1f-8c71aaf01c0e.png)
![image](https://user-images.githubusercontent.com/28269333/143085987-c5e9d524-1cb4-452c-8dd1-cf441dbce040.png)

**Environment Information (please complete the following information):**

- OS: EndeavourOS Linux x86_64
- OS Version: Kernel: 5.15.2-arch1-1
- FreeTube version: v0.15.1 Beta
- Installation Method (If applicable): AUR
- Primary API Used: Invidious

**Additional context**
*Console output with one of the bugged video*

```
﻿
renderer.js:2 No sources available
renderer.js:2 MediaImage src can only be of http/https/data/blob scheme: file:///usr/lib/freetube/app.asar/dist/index.html
renderer.js:2 Getting video info please wait...
renderer.js:2 
{page: 'watch', player_response: {…}, response: {…}, html5player: '/s/player/10df06bb/player_ias.vflset/en_US/base.js', formats: Array(26), …}
renderer.js:2 
{page: 'watch', player_response: {…}, response: {…}, html5player: '/s/player/10df06bb/player_ias.vflset/en_US/base.js', formats: Array(26), …}
renderer.js:2 TypeError: Cannot read properties of null (reading 'toLocaleString')
    at o.parsedLikeCount (renderer.js:2)
    at hn.get (renderer.js:2)
    at hn.evaluate (renderer.js:2)
    at o.parsedLikeCount (renderer.js:2)
    at o.<anonymous> (renderer.js:2)
    at o.t._render (renderer.js:2)
    at o.i (renderer.js:2)
    at hn.get (renderer.js:2)
    at new hn (renderer.js:2)
    at renderer.js:2
renderer.js:2 
(24) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, __ob__: Pt]
renderer.js:2 3
```

*Console output with one of the **non** bugged video*

```
No sources available
renderer.js:2 MediaImage src can only be of http/https/data/blob scheme: file:///usr/lib/freetube/app.asar/dist/index.html
renderer.js:2 Getting video info please wait...
renderer.js:2 
{page: 'watch', player_response: {…}, response: {…}, html5player: '/s/player/f1ca6900/player_ias.vflset/en_US/base.js', formats: Array(26), …}
renderer.js:2 
{page: 'watch', player_response: {…}, response: {…}, html5player: '/s/player/f1ca6900/player_ias.vflset/en_US/base.js', formats: Array(26), …}
renderer.js:2 
(24) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, __ob__: Pt]
renderer.js:2 1
```

**Comment by ClemGlacee** [comment]
If you need more information, tell me :)

**Comment by peepopoggers** [comment]
Woah that is weird. Reproducible.
