### ISSUE TITLE
Disappearing videos and duplicate saved videos (when unsaving and resaving) in the playlist tab

### ISSUE THREAD

**Issue by maplepy** [FreeTubeApp/FreeTube#1917]
Another day, another bug

**Behavior of the program**
Unsaving a video, make the last one saved (the very last one at the bottom disappear), unsaving another one will remove the other last one and resaving those unsaved will add the very last one (1st to be removed back) and resaving another one will duplicate that last one

**Expected behavior**
The video unsaved is unsaved, nothing else happens 

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to saved videos
2. Have some saved (at least 2)
3. Unsave the top one (not the last one)
4. Have the last one disappear
5. If you unsaved multiple, see the last videos disappearing 
6. If you saved those back, see the very 1st one to be removed duplicate 

**Link to video**

https://user-images.githubusercontent.com/28269333/143492315-5b9d7ccb-a047-47b7-af47-adf626e92d72.mp4

**Screenshots**

![image](https://user-images.githubusercontent.com/28269333/143492407-9f704dd4-9544-4735-aec9-877aa6374961.png)

**Environment Information (please complete the following information):**

- OS: EndeavourOS Linux x86_64
- OS Version: Kernel: 5.15.2-arch1-1
- FreeTube version: v0.15.1 Beta
- Installation Method (If applicable): AUR
- Primary API Used: Invidious

**Additional context**
I'm starting to wonder if making an advent calendar with each day a new bug reported would be a good idea aha
As always, if you need logs, I can send those

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Woah great catch keep um coming. Cant wait for ur advent calendar to be released😜

I'll hope it stays with minor bugs tho😅

**Comment by ClemGlacee** [comment]
Thanks :) Hope so too! But who knows, maybe you'll get a app breaking bug for christmas aha
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @maplepy just checking in if this is still an issue for u on 0.17.1?

**Comment by maplepy** [comment]
Hey!

I think it's been fixed :) Whenever I unstar a video it automatically refreshes the page so I can't restar it back. I also tried removing videos from the `Playlists` tab and adding some other back and it adds the correct ones so it seems to be working as expected :+1: 

Thank you for what you do and for checking back on the issue, I'll mark it closed, totally forgot to do it, sorry about that
