### ISSUE TITLE
Subscription Categories

### ISSUE THREAD

**Issue by ulph0** [FreeTubeApp/FreeTube#1921]
I checked for "categories" but didn't find any already posted feature request issues for this topic.

Hi, i am coming from Newpipe and looked for sth similar on the desktop. Found you and am very happy. Only one thing i really miss: The possibility to order my Subscriptions in categories. sometimes i would like to see the new videos only for one categories, eg. "FPV", "electronics", "enternatinment", .... You also could put a category-thumbnail for categorized subscriptions on the left column. If you like this and do it, the next Feature request will be a way to synchronize that with subscriptions of newpipe :)

Regards

**Comment by PrestonN** [comment]
Hi there! We already support this, however we call them "Profiles". Check out this link for more information.

https://docs.freetubeapp.io/usage/profiles/
