### ISSUE TITLE
Opening a youtube link from a video description opens Youtube page

### ISSUE THREAD

**Issue by aldum** [FreeTubeApp/FreeTube#1923]
**Behavior of the program**
Opening a link to another youtube video in a new tab (middle click) from a video description renders a vanilla youtube page.

**Expected behavior**
Should open in a regular window.

**Screenshots**
![yt_open](https://user-images.githubusercontent.com/1568020/143769303-04bc53b7-4bbb-446d-991a-7c678c2b5778.gif)

**Environment Information (please complete the following information):**
 - OS: Artix Linux
 - OS Version: N/A
 - FreeTube version: 0.15.1
 - Installation Method: package manager
 - Primary API Used: Local API

**Comment by PrestonN** [comment]
Should be fixed in latest release / nightly builds.
