### ISSUE TITLE
No subtitles choice

### ISSUE THREAD

**Issue by mrtpcet** [FreeTubeApp/FreeTube#1930]
**Behavior of the program**
I can't select subtitles because no option is showing. For example : https://www.youtube.com/watch?v=UqqB0HUFmUU

**Expected behavior**
How i can activate subtitles ?

**Link to video**
https://www.youtube.com/watch?v=UqqB0HUFmUU

**Environment Information (please complete the following information):**
 - OS: MacOS
 - OS Version: Catalina
 - FreeTube version: 0.15.1
 - Primary API Used: [Local API, Invidious API] Local API but doesn't works during my tests.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is #1189 or https://github.com/FreeTubeApp/FreeTube/issues/1343 the same problem ur facing?

**Comment by mrtpcet** [comment]
Not really, just subtitles's button doesn't show up
Image 1 : on invidious with subtitles
Image 2 : on Freetube same video with no subtitles's button

<img width="498" alt="invidious" src="https://user-images.githubusercontent.com/60814449/144429298-50fa915e-273f-4fc0-b855-bd2b4c5a094b.png">
<img width="718" alt="freetube" src="https://user-images.githubusercontent.com/60814449/144429258-ec9912ac-6faf-40c3-a764-4267c75c5ad9.png">

**Comment by skoufaki** [comment]
I have the same issue when selecting Invidious API as preferred API Backend. Switching to Local API (directly connecting to youtube) the option to activate subtitles appears.

**Comment by xz-dev** [comment]
I guess it's proxy problem.
If I use proxy, I have same thing.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This issue doesnt seem to persist anymore
