### ISSUE TITLE
Add Bluetooth headphones commands support.

### ISSUE THREAD

**Issue by x-N0** [FreeTubeApp/FreeTube#1931]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
It's not a big deal, but I'll be cool if we could use the command of previous|pause|next to change the videos without having to stand from my bed when I'm resting.

**Describe the solution you'd like to see implemented**
I don't really know, any advice would be useful.

**Additional context**
Youtube Web Client has this features, but I don't really know how they achieve it. But I think this wont have to be extra complicated, since the Bluetooth signals are already being processed by the

**Comment by absidue** [comment]
Play and pause works fine on my bluetooth headphones on Windows 10. Which operating system and version are you using?

Previous and next probably don't work on bluetooth, presumably because FreeTube doesn't support the previous and next media keys.

**Comment by x-N0** [comment]
Try any Arch linux based distro.

**Comment by absidue** [comment]
What browser are you viewing the YouTube website in? Is it chromium based?

**Comment by x-N0** [comment]
Nope. Firefox.

**Comment by x-N0** [comment]
Thanks, guys!
