### ISSUE TITLE
Sound async on AMD CPU

### ISSUE THREAD

**Issue by TMS-Namespace** [FreeTubeApp/FreeTube#1932]
**Behavior of the program**
A noticible async (arround 0.5 sec) between the video and the audio during playing in FreeTube on AMD processor.

**Expected behavior**
There should not be async.

**To Reproduce**
1. Get two laptops as I have, one with i7 9750H cpu, GTX1650 gpu, and AMD Ryzen 7 5800H with RTX3070, both on Win10 19043.1387, both 32Gb ram and SSD.
2. Play same video on FreeTube of the same and latest, portable, version, on both of them.
3. You will notice immediately how sound is laginng behind on AMD laptop, actuallly, the video starts to play, and only after a fraction of a second, its sound come up.
4. Play same video on different browsers, no lagging. Tried that with local and invideos API.

**Additional context**
I just bought a new laptop, and transferred my portable FreeTube, with all of its settings to it, and noticed this.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@TMS-Namespace is this still an issue for u on v0.17.1?

**Comment by TMS-Namespace** [comment]
> @TMS-Namespace is this still an issue for u on v0.17.1?

Hi,  yes,  nothing changed in this regard through the 2-3 updates you pushed from that report.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @TMS-Namespace its been a while. Do you still experience this?
