### ISSUE TITLE
Video lag while progress bar hiding animation runs on 60fps video

### ISSUE THREAD

**Issue by humantypingwords** [FreeTubeApp/FreeTube#1935]
**Behavior of the program**
While watching any 60fps video the video massively slows down while the progress bar is in the process of hiding (moving down and off the screen). Once the progress bar is fully hidden, the video speeds up to catch up and then resumes playing normally.

**Expected behavior**
The video should not slow down while the progress bar is in the process of hiding.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open Freetube v0.15.1 Beta
2. Start any 60fps video
3. Move cursor off the progress bar and wait a moment for it to start moving down to hide
4. The video slows down while the progress bar hiding animation plays

**Link to video**
Example Video: https://youtu.be/KZhoU_3k0Nk

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: v0.15.1 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: preferred Local API, fallback to https://invidious.kavin.rocks (also tested with some other instances, same problem)

**Additional context**
Tested with 1080p60 and 720p60 videos

**Comment by humantypingwords** [comment]
Update: This only happened on a 60hz display. After upgrading to a 144hz display, the problem is gone.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@humantypingwords is this still an issue ur facing?

**Comment by humantypingwords** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Since upgrading to a 144hz display, this issue is no longer present. Instead the whole app often freezes completely while watching a video and only unfreezes while dragging the app around the screen, but that's a separate problem I assume.
