### ISSUE TITLE
Support for next/previous media keys

### ISSUE THREAD

**Issue by jakubcze12** [FreeTubeApp/FreeTube#1941]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
When I want to, for example, play next suggested video with the "next track" media key, it does nothing. This would be particularly useful when using freetube to listen to music on the background.

**Describe the solution you'd like to see implemented**
When pressing the "next" media key, go to the first video in the "Up Next" section. In a playlist it would go to the next video in the playlist. The "previous" media key would act as the "back" button in the up left cornet of the program and would play a previously watched video. It would have a similar functionality in playlists. The stop media key works well already. This wouldn't have to be the default, but at least an option in the settings.

**Platform**
GNU/Linux.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing this is favor of #2138
