### ISSUE TITLE
FreeTube opens minimised and app won't restore

### ISSUE THREAD

**Issue by eo-in** [FreeTubeApp/FreeTube#1944]
**Behaviour of the program**
When I try to open FreeTube it stays minimised to the taskbar. Clicking on the FreeTube icon in the taskbar doesn't restore FreeTube. Using Alt+Tab or Windows+Tab interfaces the app is visible as if it is open. However, when I click to open in this view FreeTube remains minimised.

**Expected behavior**
I expected when I click on FreeTube or launch FreeTube.exe that the app would open normally as it should.

**To reproduce**
1. Launch FreeTube.exe
2. FreeTube remains minimised
3. Clicking on taskbar icon will not restore FreeTube
4. Navigating to FreeTube via Alt+Tab will not restore FreeTube
5. Navigating to FreeTube via Alt+Windows will not restore FreeTube

**Environment Information:**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version:  0.15.1 Beta
 - Installation Method (If applicable): .exe

**Additional context**
The app was working as normal previously. Apologies if there is more information about the problem that you need that I haven't shared; I can find this if needed.

**Comment by MagicLike** [comment]
Same Issue for me.
I also tried to roll back to earlier versions, but the behaviour didn't change in any aspect.

**Comment by MagicLike** [comment]
I even tested the portable version, but that didn't work either...

**Comment by MagicLike** [comment]
@eo-in 
@PrestonN gave me following advice for the problem in the Matrix chat:

1. Make shure FreeTube is closed
2. Go to the [location of your data](https://docs.freetubeapp.io/usage/data-location/)
2. Open the "settings.db" file with a text editor
3. Delete the line, that says "_id":"bounds" (Screenshot below)
4. Save the file and open FreeTube again

Hope it works

![notepad++_vP1adMKqlZ](https://user-images.githubusercontent.com/82117109/152599348-6c3a4c38-d3ab-456b-b94b-991123f5f637.png)

**Comment by eoin-eyefall** [comment]
Followed those steps and everything works perfectly now. Thank you.

**Comment by eo-in** [comment]
This solution worked for me, thank you
