### ISSUE TITLE
Does FreeTube require Chromium to be installed?

### ISSUE THREAD

**Issue by Git-Forked** [FreeTubeApp/FreeTube#1947]
I noticed that the audio from FreeTube was coming through listed as Chromium, I thought this was very odd, so I removed Chromium completely since I don't use it anyways (I prefer Firefox). Since removing Chromium I noticed that videos no longer play any audio. 
So my question is: Does FreeTube require Chromium to be installed?

**Comment by PrestonN** [comment]
FreeTube should not require Chromium itself to be installed.

Having said that, it's worth mentioning that FreeTube is built using the [Electron Framework](https://www.electronjs.org/), which uses Chromium as a base. FreeTube should have all of the files it needs to run and doesn't rely on a separate Chromium installation, it has it's own built in. The fact that FreeTube is running on your machine without Chromium installed proves that it's using it's built in version.

As far as your sound issue goes, I can't say I know for sure. There are likely some apps that will label FreeTube as Chromium like you've mentioned, but I don't believe that is something that I can fix on my end. There's likely something else on your system that's causing the issue.

I believe I've answered your question, so I'll go ahead and close this issue. If you truly believe that the sound issue has to do with FreeTube itself and not something with your system, please feel free to create a new issue. _Please_ use the issue template if you do however.

**Comment by Git-Forked** [comment]
I found the issue I was having.  I had muted the real Chromium before uninstalling it, and apparently that also causes the Chromium built into FreeTube to also be muted in sound settings of Manjaro, which lists FreeTube's audio stream as Chromium.

**Comment by steanne** [comment]
more info on the audio input name.
https://github.com/electron/electron/issues/7470
