### ISSUE TITLE
Porting age-restricted playability from Invidious API to Local API

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1954]
**Is your feature request related to a usage problem (not a bug)? Please describe.**

1. Youtube's new age-restricted functionality is accessible through the Invidious API, as the video link fallback from Local to Invidious API for the age-restricted video and plays well as desired. 
But it gives an API error for Local API.
Porting of this function will benefit in future, as the Invidious is said to be discontinued in near future.

2. Also, the comments on the age-restricted videos are non-viewable even when Invidious fallback.

FreeTube version: 0.15.1. Beta

**Comment by absidue** [comment]
I haven't looked into how Invidious gets past the age restrictions, however the only way I can see it working for the local API is being logged into YouTube, which goes against the whole principle of FreeTube.

**Comment by bachig26** [comment]
> I haven't looked into how Invidious gets past the age restrictions, however the only way I can see it working for the local API is being logged into YouTube, which goes against the whole principle of FreeTube.

I also don't how it works (I have no programming knowledge to understand), but I found this GitHub project, [Simple YouTube Age Restriction Bypass](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass) (userscript) for this purpose to work with userscript manager.
This works well without any issue as I tried today with Violentmonkey, please have look at this one, and there may be a possibility to integrate within the Local API.

The below zip file can be found in the project itself, I just added it in case of need.
[Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/FreeTubeApp/FreeTube/files/7748643/Simple-YouTube-Age-Restriction-Bypass.user.zip)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please post this suggestion here https://github.com/FreeTubeApp/FreeTube/issues/1296
