### ISSUE TITLE
Align messages - enhancement | texts customization

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1956]
**Is your feature request related to a usage problem (not a bug)? Please describe.**

Enhancement 1:
1. The In-App messages during the program process like **"Fetching results. Please wait", etc.** are currently **defaulted to the bottom-center** and it's sometimes annoying as it **overlays on the content**.

Enhancement 2:
2. And the **overall FreeTube texts are too big, for example at "About", "Settings", everywhere**. It needs to reduce to a proper size.

**Describe the solution you'd like to see implemented**

For Enhancement 1:
1. I hope that these messages are **aligned to the bottom-right corner** or it will be a good idea if there is an **option to customize these per user preferences** like the Grid or List View option at Settings.

For Enhancement 2:
2. It will a good one to have a **similar option along the alignment to personalize the text sizes**.

**Screenshots (Examples)**

For Enhancement 1:
![FreeTube_TyJ4vWV9bL](https://user-images.githubusercontent.com/96393348/146837786-a6ab60f0-e4f2-4b3b-a1f9-71c0649f60b9.png)
![FreeTube_VrgHztKhMm](https://user-images.githubusercontent.com/96393348/146837800-c7727eff-2bc1-4a50-a996-0f6e1b410345.png)
![FreeTube_Kj9Oed1wSZ](https://user-images.githubusercontent.com/96393348/146837809-d7214c24-aa42-4a0c-a1ea-0dd779e8f4bb.png)

For Enhancement 2:
![FreeTube_KG2kYQVpRu](https://user-images.githubusercontent.com/96393348/146840326-a7fa2db3-2e4e-42b0-b136-fef947719a29.png)
![FreeTube_0gdcQ3VSCw](https://user-images.githubusercontent.com/96393348/146840339-f6dc2b19-cfc4-4d83-b80f-28343b971aa2.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This issue will be closed because the team doesnt see any issues with the current state of FT
