### ISSUE TITLE
[Bug] video stops playing after 6 hours.

### ISSUE THREAD

**Issue by arrowgent** [FreeTubeApp/FreeTube#1964]
```
There isn't much we can do about this unfortunately.

YouTube video URLs stay active for ~6 hours and refreshes after that time frame. We then have to make a new call to YouTube to get new URLs in order for the video to continue. Letting the video continue while you're away instead of pausing can help since when you come back the video will then be downloaded and can be played repeatedly, though the only real solution is by refreshing the page / adding a refresh button.

Since there's already issues related to those features, I'll go ahead and close this.
```

_Originally posted by @PrestonN in https://github.com/FreeTubeApp/FreeTube/issues/1500#issuecomment-881117040_

https://github.com/iv-org/invidious/issues/2731
is there a solution to work around this?
is this a youtube 6 hour limit, invidious 6 hour limit, or a freetube 6 hour limit?

i often play 10-12 hour videos then go sleep
only to be woken up at 6 hours because of the silence.....(or the noise that the audio was covering up)

also
i can imagine actively watching a 10 hour long video
and having the video player stop at exactly 6 hours
being forced to GoBack then GoForward to refresh the video

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Retrieved from IRC

> (witd) PrestonFT: how realistic is it to be able to hit pause on a video, come back to it hours later, and have it continue playing after the buffered portion has run out
It's not the end of the world but figured I would ask.

> (Svallinn) tl;dr it's not impossible, but no one is gonna go through the effort of implementing it since refreshing takes one Ctrl+R

> (PrestonFT) Basically what Svallinn said.

> (enigma9o7) oh, if you pause too long it requires a refresh?

> (PrestonFT) YouTube refreshes the video URLs every few hours, which is why it stops playing. We could try refreshing the URL, but whatever timeframe we pick could end up just refreshing your page in the middle of watching, which wouldn't be ideal either.
