### ISSUE TITLE
Download Menu & Built-in Download Function

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1965]
**Topic**
Please select what topic you are referring to.
- [ ] Other. Please specify: Function

**Question**
is there any plan to make a **download tab** and **download videos within FreeTube without redirecting to webpage (browser)**?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Q1: see 
https://github.com/FreeTubeApp/FreeTube/issues/1772#issuecomment-996264558 for download tab

Q2: See https://github.com/FreeTubeApp/FreeTube/issues/582#issuecomment-703641821 for download without browser redirect
