### ISSUE TITLE
Removal of IINA external player support in Windows version

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1977]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
IINA external player support is needed for windows or Linux devices, as I find IINA is macOS only.
By removal of the argument/ support, it can be less complex at some point of complying or future maintenance.
[FYI, from personal use and system support.]

**Describe the solution you'd like to see implemented**
N/A

**Describe alternatives you've considered**
N/A

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
![Screenshot_20220104-121046_1.png](https://user-images.githubusercontent.com/73130443/148050695-12770db3-394f-4606-9766-d39656de6c40.png)

The arguments u have stated are invalid
