### ISSUE TITLE
Youtube Originals cluttering subscriptions

### ISSUE THREAD

**Issue by lbcat06** [FreeTubeApp/FreeTube#198]
I am aware you have a lot of stuff to do, mainly the syncing of audio files and video files to support 1080p+, but I would just like you to know that channels which have a youtube original series clutter at the top of my subscriptions tab, not sure if its just me but seems like it isnt. Thanks

**Comment by alex-esc** [comment]
all of the youtube originals in my sub box have '0 view - 0 second ago' below the title, maybe this can be used to filter them out in a future update.

**Comment by niceorg1** [comment]
> 
> 
> all of the youtube originals in my sub box have '0 view - 0 second ago' below the title, maybe this can be used to filter them out in a future update.

I'm sure there is some tag that indicates if its it for premium users or not, but last case scenario maybe.

**Comment by omarroth** [comment]
See also omarroth/invidious#275. The API FreeTube uses provides a `paid` flag, so for most cases you should be able to filter videos fairly easily.

**Comment by zorbakus** [comment]
Please see #208 for screenshot
