### ISSUE TITLE
Can't import any subscriptions in FreeTube on Win 11

### ISSUE THREAD

**Issue by sakulzz** [FreeTubeApp/FreeTube#1983]
Hello I have downloaded freetube on win 11, I wanted to import a json file and opml file, but no one will be recognized/ nothing is loading.
I've tried it on v 0.15.0 & and on v.0.15.1.
I also installed in once via the setup & via the zip files, nothing worked.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi there, did u try to troubleshoot the issue using https://docs.freetubeapp.io/usage/importing-subscriptions/#troubleshooting-issues
