### ISSUE TITLE
Duplicates of comment replies

### ISSUE THREAD

**Issue by ssnor** [FreeTubeApp/FreeTube#1985]
**Behavior of the program**
In the comment section, when you click "View * replies" more than once during the time it takes to fetch the comments, FreeTube will display the fetched comments with as many duplicates as you clicked "View * replies".

**Expected behavior**
For FreeTube to only display the fetched comments once.
Alternatively one might double click because you quickly regretted your decision to view the replies, and thus would expect FreeTube to hide the replies.

**To Reproduce**
1. Use Local API
2. Go to any video that has comments with replies
3. Click "Click to View Comments"
4. Click on "View * replies" more than once during the time it takes to fetch the comments
5. See the error in how the fetched replies are displayed

**Environment Information:**
 - OS: Fedora
 - OS Version: Fedora 34 (Workstation Edition)
 - FreeTube version: v0.15.1-nightly-1377 Beta
 - Installation Method: .rpm
 - Primary API Used: Local API, this bug does not appear when using the Invidious API

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
do you have examples because i cant reproduce

**Comment by ChunkyProgrammer** [comment]
I'm able to reproduce

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Im curious. Do you have a few links for me to test out?

**Comment by ChunkyProgrammer** [comment]
I think this issue only happens when using local api (wasn't able to reproduce with invidious) but you should be able to reproduce with any video
![comments repeat](https://user-images.githubusercontent.com/78101139/148612796-8baebc8d-7299-47c9-b410-1216c853addf.gif)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can reproduce it was just user error on my end.
