### ISSUE TITLE
[Bug]: Some Channels don't open up using Invidious-API

### ISSUE THREAD

**Issue by RootBeerFan** [FreeTubeApp/FreeTube#1990]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

0. Prefered API-Backend is set to "Invidious API".
1. Go ether to your subscriptions, history or browse for content
2. try to open up one of the following channels
- https://youtube.com/channel/UCi9LaoY3GbqCdbbRyaQ5_vA
- https://youtube.com/channel/UCPygLEFniGZmehxouDK-vbw
3. the window title now changes to the channels name but the loading animation keeps playing while nothing happens
![grafik](https://user-images.githubusercontent.com/97342923/148643980-c337bbcd-5c3d-4246-b925-5d4bfff5cf1a.png)

4. it runs until forever trying to upen up the channel
5. try to open up the channels via youtube directly -> it works
6. try to open up the channels via different invidious instances -> it works
7. change the preferred API-Backend to "Local API" -> it works

### Expected Behavior

1. Select a channel of your favour
2. try to access it by clicking on the channel name
3. the channel should just open up

### Issue Labels

content not loading, feature stopped working, inconsistent behavior

### FreeTube Version

v0.15.1

### Operating System Version

Windows 10 Pro 21H2 19044.1415

### Installation Method (If applicable)

.exe

### Primary API used

Invidious API

### Additional Information

It does not happen with all channels or with any clear pattern regarding the channels that are not working.
I tried all working invidius instances with different versions that are available and also made sure that it works
if I'm accessing the channels directly via Invidius. Also my Linux-Mint laptop with the same release 0.15.1 beta it is the exact same issue. 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by SoakedTofu** [comment]
I'm experiencing the same issue. The first channel you linked works on my end, but the second doesn't. I'm on Fedora 35, using 0.15.1, installed through flatpak.

Here are two channels that don't work for me.

https://www.youtube.com/channel/UC9PBzalIcEQCsiIkq36PyUA
https://www.youtube.com/channel/UCRxPrFmRHsXGWfAyE6oqrPQ

**Comment by arrowgent** [comment]
same, im not sure what causes it at all

the links above invidious instances they open fine in a browser
but they dont open in freetube at all

https://invidious.kavin.rocks/channel/UC9PBzalIcEQCsiIkq36PyUA
https://invidious.kavin.rocks/channel/UCRxPrFmRHsXGWfAyE6oqrPQ

https://invidious.kavin.rocks/channel/UCi9LaoY3GbqCdbbRyaQ5_vA
https://invidious.kavin.rocks/channel/UCPygLEFniGZmehxouDK-vbw

**Comment by Jitnaught** [comment]
I'm having the same issue. When loading certain channels using the Invidious API, the channel will load forever, and on some other channels it will stop loading and an error message will pop up:
> Invidious API Error (Click to copy): Missing hash key: "gridChannelRenderer"

The Invidious instance used does not matter. On channels with the error popup, if I change the "Sort By" to anything else the channel will load. So to view the latest videos I have to go to the channel, sort by Oldest or Most viewed, then sort by Newest again.

Channel that loads forever:
Technology Connextras

Channels with error popup:
Andrew Camarata
Technology Connections
Vsauce

FreeTube versions tried:
0.15.1
git e929c7d

OS:
Manjaro

Installation method:
Compiled from source using AUR https://aur.archlinux.org/packages/freetube https://aur.archlinux.org/packages/freetube-git

**Comment by PrestonN** [comment]
I looked more into this and the error is coming from the Invidious instance itself, so there seems to be a problem with the Invidious API itself, not with FreeTube.

Going to close because of that but I'll go ahead and tag @TheFrenchGhosty so that they're aware.
