### ISSUE TITLE
[Bug]: Cant download 1080p + Audio

### ISSUE THREAD

**Issue by firefoxlover** [FreeTubeApp/FreeTube#1993]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Try to download a video
2. max. is 720p with audio

### Expected Behavior

There should be the option to download Video + Audio in 1080p and maybe higher, like its possible for only video.

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

Flatpak stable, 11.11.2021

### Operating System Version

Ubuntu Linux

### Installation Method (If applicable)

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isn't a bug
See https://github.com/FreeTubeApp/FreeTube/issues/582#issuecomment-703641821
