### ISSUE TITLE
[Bug]: Channel add or remove issue between Profile {Discussion #1994}

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1995]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

When a channel or multiple channels are added or removed to a profile, it correspondingly adds (sync) to the default profile.

This issue happens in the code base, so this can be seen while subscribing or unsubscribing a channel at the FreeTube working environment level or at the profile settings level.

In Profile settings, if one adds multiple channels from a profile called "Music" to "Entertainment", this affects directly the "Default Profile eg. Home (All Channels)".

Also, refer to the Discussions of a Q&A #1994 which followed this Bug Report Issue.

Furthermore, there needs to be a separate sync factor for the profile in terms of channels, playlists, history, and settings; as commented by efb4f5ff-1298-471a-8973-3d47447115dc, _https://github.com/FreeTubeApp/FreeTube/discussions/1994#discussioncomment-1934878_.

### Expected Behavior

In an Ideal state,
The Channel's subscription or subscription should only reflect the selected profile.

Sync needs to be revised, at present, the Default profile works like a Backup Profile.

[FYI, Default Profile should only be factored for the opening of the new FreeTube Session to have a default profile page.]

### Issue Labels

inconsistent behavior, usability issue, visual bug

### FreeTube Version

0.15.1 Beta

### Operating System Version

Windows 10

### Installation Method (If applicable)

.exe

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by bachig26** [comment]
#1997

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
yeah thats my bad i was trying something out

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@bachig26 https://github.com/FreeTubeApp/FreeTube/discussions/1994#discussioncomment-1935380

**Comment by bachig26** [comment]
> yeah thats my bad i was trying something out

:)
I wanted to add your closed issue as mentioned but I don't know how to do it. This is the best as a comment. 😁

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing in favour of #1996

**Comment by bachig26** [comment]
> Does this affect how 'import subscriptions' works too? I wanted to import different subscription files to different profiles instead of adding them all to the default profile.

yes, it does reflect the subscriptions import and export.
Also, you can refer and comment more in the future to the open issue #1996 on Profile Separation, which is more detailed about this issue and more relevant matter.
