### ISSUE TITLE
Building source on windows is broken

### ISSUE THREAD

**Issue by LDSpits** [FreeTubeApp/FreeTube#200]
When cloning and following the guidelines on [setting up the project](https://github.com/FreeTubeApp/FreeTube/blob/master/CONTRIBUTING.md#setting-up-your-environment) I noticed that i couldn't build from source on windows. There where a few problems:

- you need ``electron-forge`` as a global npm tool. I didnt see this anywhere but was quick to fix.
- there are problems with the "electron-installer-flatpack" package.

When you run ``npm i(nstall)`` it'll fail on windows with 
```node
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for electron-installer-flatpak@0.8.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

this will block the ``postinstall`` of nodejs. removing electron-installer-flatpack from the dependencies will successfully complete the install and run the postinstall with a electron download.

when you run ``npm start`` without the postinstall, you'll get an error saying that it cannot find the electron package and advices deleting the ``electron`` package from ``node_modules`` *which will not work*

**Comment by openffchrome** [comment]
how do you add forge as global? i have tried npm install -g electron-forge but i'm still gettings error

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! FreeTube@0.4.1 start: `electron-forge start`
npm ERR! Exit status 1


thanks
