### ISSUE TITLE
[Feature Request]: right-click menu to open a channel or video in a new window

### ISSUE THREAD

**Issue by constraintAutomaton** [FreeTubeApp/FreeTube#2000]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Sometime I want to open a video/channel to a new window to check it later. Right now I have to click on the new window button and copy the video/channel name into the search bar to.

### Proposed Solution

A right-click menu to open the video/channel to a new window would be an ideal solution.

### Alternatives Considered

a middle click would also be great

### Issue Labels

ease of use improvement

### Additional Information

It's related to #333 but I don't think it's the same

**Comment by constraintAutomaton** [comment]
I'm gonna do it.

**Comment by Tiltowait2** [comment]
Middle click already works like this.  Click on any video to open it in a new window.

**Comment by constraintAutomaton** [comment]
> Middle click already works like this. Click on any video to open it in a new window.
personally, I don't use middle click often and I don't have one on my laptop

**Comment by RagglenLove** [comment]
> Middle click already works like this. Click on any video to open it in a new window.

Middle clicking isn't very intuitive though and not all mouse has scrollers, so an option for opening links in new window in the right click context menu should still be considered as an alternative to middle clicks.

![Screenshot_2022-02-03_19-33-33](https://user-images.githubusercontent.com/45503845/152340030-1eff3e83-9b80-41dd-893b-aab534b015c2.jpg)

**Comment by Tiltowait2** [comment]
The guy requested middle click as a solution.  I pointed out it has already been implemented.
