### ISSUE TITLE
[Feature Request]: Nextcloud sync across device

### ISSUE THREAD

**Issue by cmalvi** [FreeTubeApp/FreeTube#2003]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to sync data across devices using my private nexctloud 

### Proposed Solution

add nextcloud sync for profile data

### Alternatives Considered

guide for do it manually

### Issue Labels

new feature

**Comment by PrestonN** [comment]
Duplicate of [#370](https://github.com/FreeTubeApp/FreeTube/issues/370)
