### ISSUE TITLE
[Feature Request]: Ability to add favorite folders to download videos to

### ISSUE THREAD

**Issue by peepo5** [FreeTubeApp/FreeTube#2004]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

This would rely on the downloads tab being implemented.

(Future) Problem is that browsing the file system to find your favorite folder when downloading is tedious.

### Proposed Solution

My idea is that you could add new folders by browsing for them or providing the path, and then when downloading videos, you could pick a location from your favorites rather than manually browsing the file system through the explorer window.

### Alternatives Considered

none

### Issue Labels

ease of use improvement, improvement to existing feature, new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@constraintAutomaton i think u last PR also covered this right

**Comment by constraintAutomaton** [comment]
> @constraintAutomaton i think u last PR also covered this right

Yes I'm pretty sure that 

![image](https://user-images.githubusercontent.com/19601176/196105067-a7c81101-0e3a-4da4-bae0-8195af456682.png)

does it
