### ISSUE TITLE
I can't get Potplayer to work as a the external player

### ISSUE THREAD

**Issue by Janaue** [FreeTubeApp/FreeTube#2005]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

I use Potplayer instead of VLC so I want to use it even with Freetube, and since the command line is very simple like in VLC, i expected to work, but the only thing the eternal button does is launch Potplayer and no video is even attempted to be openned, ie nothing happens once Potplayer is launched.

outside Freetube, in order to open a youtube link, The command I use is "PotPlayerMini64.exe http://youtube_link", just like vlc.
but in Freetube, when I enter the path for Potplayer and then choose a video to be played with Potplayer, the player is launched and nothing else happens.

Here is the command line for Potplayer

> Usage: PotPlayerMini64.exe ["content"] [/switch]
> 
> "content"	:You can specify a file, folder or URL as content.
>                 -You can specify multiple contents by separating them with a space.
> 		-You can specify titles for URLs by separating them with a backslash (\) at the end of URLs. ("http://...\title of this url")
>             	-Wildcards (*,?) are allowed.
>               	-The setting "Misc > When Files Opened" affects this when a file is specified.
> 
> - 		:Plays streaming media from stdin
>                 -Example usage: youtube-dl.exe -o - -f best[ext=webm] https://www.youtube.com/watch?v=l22sS8DEiVU | PotPlayerMini64.exe -
> 
> /filedlg	:Opens the open file dialog box.
> /urldlg        	:Opens the open URL dialog box.
> /folderdlg	:Opens the open folder dialog box.
> /simple	   	:Opens file navigator.
> /cap	   	:Runs screen capture.
> /cam	   	:Runs webcam/Other devices.
> /atv[:ch]	:Runs Analog TV device from the specified channel.
> /dtv[:ch[-idx]]	:Runs Digital TV device from the specified channel.
> /dvd       	:Runs DVD device.
> /cd[:drive]	:Runs the specified drive.
> /add		:Appends the specified content(s) into playlist.
> /insert		:Inserts the specified content(s) just below the item being played in playlist.(Or adds at the end of playlist if there is nothing playing at the time)
> /autoplay 	:Plays the last played item.
> /same	   	:Loads and plays the specified contents as multiple streams.
>             	-You can independently select loaded video and audio streams under Video/Audio/Filters context menus.
> /sort		:Sorts the specified contents by name before adding them into playlist.
> /randomize	:Sorts the specified contents by randomly before adding them into playlist.
> /new 		:Plays the specified content(s) within a new instance of the program.
>                 -The setting "F5 > General > Multiple instances" does not affect this.
> /current 	:Plays the specified content(s) within an existing instance of the program.
>                 -The setting "F5 > General > Multiple instances" does not affect this.
> /clipboard      :Appends content(s) from clipboard into playlist and starts playback immediately.
> /seek=time      :Starts playback of the specified/last played content from the specified time point.
>                 -time format is: hh:mm:ss.ms (OR specify seconds only e.g. /seek=1800 to start at 30th min)
> /sub="subfile"  :Loads the specified subtitle(s) from the specified paths or URLs.
> /user_agent="ua":Sets user agent header for HTTP(S) requests.
> /referer="ref"  :Sets referer header for HTTP(S) requests.
> /headers="hdrs" :Appends the specified header(s) to HTTP(S) requests.
> /title="title"  : Use title
> config="name"	:Activates the specified preset.

### Expected Behavior

To play the video.

### Issue Labels

content not loading

### FreeTube Version

v0.15

### Operating System Version

w10 1809

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Janaue is this still an issue for u on v0.17.1?

**Comment by Janaue** [comment]
Yes it still does not work with potplayer
So to recap, I use vlc portable and i put its path like this

<img width="768" alt="2022-08-24 18_13_01-Paramètres - FreeTube" src="https://user-images.githubusercontent.com/10972636/186470890-f2a4416a-7f71-41a5-8742-66cecc8693a1.png">
and it works with a stock profile for vlc...

then I use potplayer portable from
https://portableapps.com/apps/music_video/potplayer-portable
and I just put its path mimicking VLCportable, the player launches but nothing happens
On the task manage by windows, here is the command line used by potplayer

<img width="698" alt="2022-08-24 18_18_25-Gestionnaire des tâches" src="https://user-images.githubusercontent.com/10972636/186471155-94702b63-05cb-4e5d-9cf0-acf7cac240a5.png">

I bet it is the --rate=1.25 which is unknown for potplayer. So i think there should be an option just to passe a naked URL to a custom player.

**Comment by Janaue** [comment]
bump

**Comment by Janaue** [comment]
I am on v0.18.0-nightly-2526 Bêta and there is still the flag --rate=1.25 which prevents potplayer to read the video, when using the ''VLC"' entry to define the path to potplayer.
It is better to offer an option ''generic player'' which transmits only the URL.

**Comment by Xelbayria** [comment]
Hello,  

I was able to get it working using v0.18.0-Beta, almost perfectly. 
i copied the filename of potplayer and rename it "VLCPortable.exe" 
![image](https://user-images.githubusercontent.com/12866666/230752172-cdeac8ba-ffa2-436b-a613-da168eac659f.png)

and it works BUT there is an extra file which is actually an argument, see the picture below: 
![image](https://user-images.githubusercontent.com/12866666/230752192-1b77ea69-13c1-4473-a8e9-3cefa69012c0.png)

I saw the more info via potplayer, it's `\url\ --rate=1`   
I wasn't sure how to correct this? 🤔

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
inquires regarding external players migrated to https://github.com/FreeTubeApp/FreeTube/discussions/7789
