### ISSUE TITLE
subscriptions tor api calls leak at start

### ISSUE THREAD

**Issue by openffchrome** [FreeTubeApp/FreeTube#201]
hello, when using the option to make api calls using tor it make the first calls (the calls for subscribed channels, right after starting the app) using the usual internet instead of tor :/

![annotation 2018-12-08 011630](https://user-images.githubusercontent.com/43328037/49678766-f6530e00-fa86-11e8-8d5a-33cb49c0ab11.jpg)

freetube 0.4.1 Beta

thanks

**Comment by PrestonN** [comment]
Hey there.  Could you try testing with the latest dev branch?  Tor has been revamped quite a bit but I'd like to know if this is still an issue.  I can upload a binary if that would be easier.

**Comment by PrestonN** [comment]
The leaks have been addressed and should no longer happen in the next release.  Closing this issue since it has been resolved.
