### ISSUE TITLE
[Bug]: Video flicker when mouse is taken off, or still.

### ISSUE THREAD

**Issue by U2V4eU5hbWVIZXJl** [FreeTubeApp/FreeTube#2012]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

This bug occurs when the mouse has either stopped moving or taken of the video itself. It seems to start when the bar at the bottom of the video disappears. This causes as shown in the video linked the graphics to have a seizure and start rapidly blinking with black 'bars' or as seen in the video full video player flickers. This occurs throughout all video's I try. I can almost confirm this is not a graphics issue on my end seeing as all the other video players on my computer, including normal YouTube work fine.The video shown is one of the worst case scenarios as like I said it ranges from what you see to little black bars starting at the top of the media player. 

Edit: With more testing it seems the flicker varies from not flickering to the full player flicker to anything in-between on every different video.

https://user-images.githubusercontent.com/97810738/149640317-b3bdd502-a192-4e74-9b17-6a4633f31a84.mp4

### Expected Behavior

Video plays without giving the user a seizure.

### Issue Labels

usability issue, visual bug, inconsistent behavior

### FreeTube Version

v0.15.1

### Operating System Version

Windows 10 Build 19041

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@U2V4eU5hbWVIZXJl is this still an issue for u on v0.17.1?

**Comment by the-overdriven** [comment]
Looks like it's electron issue. Running FreePipe with `--disable-gpu` param makes the flickering go away.
