### ISSUE TITLE
[Bug]: Can't get full screen on the wayland version of the app

### ISSUE THREAD

**Issue by KarkanAlzwayed** [FreeTubeApp/FreeTube#2025]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1.Download the wayland version of the app.
2. Play a video and try to put in full screen
3. It will go semi-full screen where I can still see the top panel, but the video just freezes to no return with the audio still playing. To get out of the frozen picture, just double click anywhere on the video, and it will go back to playing normal, video and audio.
4. Also, cursor is very tiny on my 4k screen, but when hovering over anything that is clickable, a giant hand shows.
FreeTube (wayland) v0.15.1 Beta
Operating System: Manjaro Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.15.16-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

### Expected Behavior

To be able to make a video in full screen
Normal size cursor on a 4k screen.

### Issue Labels

usability issue

### FreeTube Version

v0.15.1 Beta

### Operating System Version

Manjaro Linux stable, KDE 

### Installation Method (If applicable)

other

### Last Known Working FreeTube Version (If Any)

0.15.1-1 non wayland

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@KarkanAlzwayed is this still an issue for u on v0.17.1?
