### ISSUE TITLE
Don't hide videos while reloading [Feature Request]: 

### ISSUE THREAD

**Issue by IronMaltese** [FreeTubeApp/FreeTube#2026]
### Guidelines

- [x] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Videos are hidden while reloading subscription feed, and if you're subscribed to a lot of channels, you can just sit there looking at a loading button instead of checking your new videos

### Proposed Solution

add an animation to the refresh button and new videos will show up one as a time in the subscription feed

### Alternatives Considered

N/A

### Issue Labels

ease of use improvement, improvement to existing feature, visual improvement

**Comment by PrestonN** [comment]
This is unlikely to happen. The videos are not sorted until the very end to save resources and displaying the list as they come in would mean we have to re-sort the list upon every new batch that we get. This would be pretty resource intensive.
