### ISSUE TITLE
[Bug]: PIP freezes when next video autoplays

### ISSUE THREAD

**Issue by Addictc** [FreeTubeApp/FreeTube#2028]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Go to any playlist
2. Start the playlist
3. Enter PIP mode
4. Wait for video to finish and next one to start

### Expected Behavior

Expected next video to show up in PIP player 

### Issue Labels

usability issue

### FreeTube Version

v0.15.1 Beta

### Operating System Version

5.13.0-27-generic #29~20.04.1-Ubuntu SMP

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/927
