### ISSUE TITLE
Use Invidio.us's hidden service when Tor option is enabled

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#203]
Invidio.us has an official Tor Hidden Service located at http://kgg2m7yk5aybusll.onion/

I would like to suggest that the hidden service be used if `Use Tor for API calls` is enabled.    This means that all interaction will exist inside the Tor network,  unlike now where you have to exit into the clear net to reach the site.

**Comment by dimqua** [comment]
Not all, since Invidious does not proxy all youtube videos.

**Comment by PrestonN** [comment]
I will go ahead and close this issue for now, as this can be done by configuring your Invidious instance to point to the onion site.  Users can choose which one version of the site they would like to connect to.
