### ISSUE TITLE
[Feature Request]: Discord Rich Presence

### ISSUE THREAD

**Issue by JeremyBorja** [FreeTubeApp/FreeTube#2030]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

It would be cool to add Discord Rich Presence to FreeTube like you're using PreMID or tools for show what you're watching on YouTube.

### Proposed Solution

-

### Alternatives Considered

-

### Issue Labels

new feature

### Additional Information

-

**Comment by PrestonN** [comment]
Very unlikely to happen. As a privacy app, we don't want to encourage non-privacy solutions (Outside of YouTube of course), so adding Rich Presence would only encourage usage of Discord, which we don't want to imply.
