### ISSUE TITLE
[Feature Request]: Update node-ytdl-core to v4.10.1

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#2039]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The FreeTube needs the ytdl core to updated with latest version,
https://github.com/fent/node-ytdl-core/releases/tag/v4.10.1

### Proposed Solution

-

### Alternatives Considered

-

### Issue Labels

improvement to existing feature

**Comment by PrestonN** [comment]
Done.
