### ISSUE TITLE
[Bug]: [Wayland] PiP video is laggy when the main Freetube window is minimised

### ISSUE THREAD

**Issue by bacteriostat** [FreeTubeApp/FreeTube#2040]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

The video inside the picture in picture window lags when the main window is minimized. This does not happen when the main window is not minimized. 

**How to reproduce?**
1. Launch Freetube under Wayland using `freetube --enable-features=UseOzonePlatform --ozone-platform=wayland`
2. Play a video.
3. Select Picture in picture mode.
4. Minimize the main window
5. The video in picture in picture lags as soon as we minimize the main Freetube window.

Here's the bug in action:

https://user-images.githubusercontent.com/32611672/152211552-a183b157-299f-45f5-b29a-b82a08a5c5a4.mp4

### Expected Behavior

The video in picture in picture should not lag even if the main window is minimized.

### Issue Labels

usability issue, visual bug

### FreeTube Version

v0.15.1 Beta

### Operating System Version

Arch Linux

### Installation Method (If applicable)

other

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@bacteriostat is this still an issue for u in v0.17.1?

**Comment by bacteriostat** [comment]
v0.17.1 does not launch under Wayland for me, so can't really test it. I think freetube needs to bump electron version.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is this still an issue on [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)?

**Comment by bacteriostat** [comment]
On the latest nightly, the issue seems to be gone. Closing this.
