### ISSUE TITLE
[Bug]: Double audio

### ISSUE THREAD

**Issue by anonaddict** [FreeTubeApp/FreeTube#2041]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Open a playlist with at least 2 videos.
Play the first video
Go to PiP mode
Wait for the video to finish and the next to start playing
close the PiP view which has now frozen (might need to wait a couple seconds while the new video is playing)
press space bar
Second video pauses and the audio of the first video should now be playing

### Expected Behavior

Expected to simply pause video 2 

### Issue Labels

keyboard control not working

### FreeTube Version

v0.15.1 Beta

### Operating System Version

5.13.0-27-generic #29~20.04.1-Ubuntu SMP, QubesOS R4.0.4, Windows 10, 

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Addictc** [comment]
Update: If you repeat this process with more than a couple videos it can easily crash your computer

**Comment by Addictc** [comment]
@PrestonN can you add the crash tag to the issue?

**Comment by anonaddict** [comment]
Seems to be closely related to #1281 #927 #1192

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@anonaddict is this still happening to u?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@anonaddict is this still an issue for u on the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds)?
