### ISSUE TITLE
[Bug]: Video keep getting interrupted

### ISSUE THREAD

**Issue by Dang-The-Vuong** [FreeTubeApp/FreeTube#2045]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Find any video
Watch it
It load
The video would play
Then the video experience interruption and load for a while and then continue
This would happen over and over again while watching the video

### Expected Behavior

The video would constantly get pause and I would have to wait for loading, this would repeat over and over again. I try watching Youtube in the browser and I don't experience this problem, so it definitely not a network problem.

### Issue Labels

usability issue

### FreeTube Version

0.15.1 Beta

### Operating System Version

Debian GNU/Linux 11 (bullseye) x86_64

### Installation Method (If applicable)

.deb

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We are aware of this issue. Youtube changed something again. Fix is coming soon!

**Comment by PrestonN** [comment]
Fix is already in our nightly builds. New release hopefully this weekend :)

**Comment by Dang-The-Vuong** [comment]
Awesome! Thank you! You guys are awesome! Thank you so much! Keep up the good work!
