### ISSUE TITLE
[Feature Request]: Add a "no profile" profile

### ISSUE THREAD

**Issue by toff** [FreeTubeApp/FreeTube#2048]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When you import a lots of channels (~150 in my case), it is very cumbersome to sort each channel in profiles, you need lots of click and scrolling.

### Proposed Solution

It would be good to have a "no profile" profile, that only shows channels without any profile.
It can be hidden if the user doesn't use profiles, or when there is nothing in this profile.
It doesn't need any new UI elements.

### Alternatives Considered

A specific UI could also be introduced to sort profiles with drag&drop, like at left all unsorted channels and at the right all profiles.
But it's more work I suppose.

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2223
