### ISSUE TITLE
[Feature] Add Android Support

### ISSUE THREAD

**Issue by asddsaz** [FreeTubeApp/FreeTube#205]
**Feature**: Support Android
**Why**? Android is the most used mobile OS. Despite it having many privacy issues[1](https://en.wikipedia.org/wiki/Android_(operating_system)#Security_and_privacy), it is still vital to support as Android based OSes like [Replicant](https://replicant.us/) and [LineageOS](https://en.wikipedia.org/wiki/LineageOS) may also be able to run it.

**Comment by lionirdeadman** [comment]
I would recommend using Newpipe instead of this since this is not compatible with mobile OSs in its current state and should probably focus on the desktop only.

**Comment by PrestonN** [comment]
As it was mentioned, I see no reason to support Android when there are great alternatives such as NewPipe and SkyTube.  I would recommend using one of those apps if you would like a similar experience for Android.
