### ISSUE TITLE
[Bug]: Errors when viewing certain channel

### ISSUE THREAD

**Issue by elesto** [FreeTubeApp/FreeTube#2052]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

When viewing or adding to subscriptions or importing it to subscriptions. 
The url is: https://www.youtube.com/channel/UC4HQlrs23tItzTD-wGKIxMA

### Expected Behavior

No errors

### Issue Labels

API issue, text/string issue

### FreeTube Version

0.16.0

### Operating System Version

Macos Monterey

### Installation Method (If applicable)

other

### Last Known Working FreeTube Version (If Any)

none

### Primary API used

Local API

### Additional Information

It was a real pain to find the problematic channel in all my subscriptions. Maybe more info in the error popup would be helpful.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
this error seem to be fixed in the latest nightly
