### ISSUE TITLE
[Bug]: No Download Button 

### ISSUE THREAD

**Issue by igorchook** [FreeTubeApp/FreeTube#2053]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

The download button is gone in the latest release v0.16.0  .

### Expected Behavior

Download button is gone.

### Issue Labels

feature stopped working

### FreeTube Version

v0.16.0

### Operating System Version

Windows 10

### Last Known Working FreeTube Version (If Any)

v0.15.1

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is it everywhere or just on some places?

Also do u have urls for me to test out.

**Comment by igorchook** [comment]
It seems to have, somehow, resolved itself. Rebooted a few time to be sure and it's there (though trying to download anything keeps returning an error message).
