### ISSUE TITLE
[Bug]: Pressing I in the search box toggles "stats for nerds"

### ISSUE THREAD

**Issue by voidbert** [FreeTubeApp/FreeTube#2062]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

If the video element is focused (by clicking on it) and then the search text box is clicked on, typing `i` on the text box will toggle the feature "stats for nerds" (the video needs to be playing). Selecting text on the page before clicking on the search box and then pressing `i`, for example, doesn't solve the problem.

Also, if the video is paused, "stats for nerds" is disabled, and I type `i` on the search box, when I unpause the video it toggles stats for nerds.

### Expected Behavior

When focused on the video, pressing I toggles the new 0.16 feature "stats for nerds". This shouldn't happen while not focused on it.

### Issue Labels

usability issue

### FreeTube Version

freetube-bin (.deb based AUR package) 0.16.0-1

### Operating System Version

Arch Linux (5.16.7-arch1-1 x86_64)

### Installation Method (If applicable)

.deb

### Last Known Working FreeTube Version (If Any)

Feature not present in prior versions

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PrestonN** [comment]
Should be fixed now. Will be included in the next release.
