### ISSUE TITLE
[Bug]: "stats for nerds" display volume 0% until the volumes has been changed 

### ISSUE THREAD

**Issue by constraintAutomaton** [FreeTubeApp/FreeTube#2065]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Go to a random video
Open the stats for nerds via any methods
You will see that the volumes display 0% regardless of the current volumes, but will display the valid volume if it is changed

### Expected Behavior

The initial value should be the valid one

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.16.0 Beta

### Operating System Version

 Ubuntu 20.04.3 LTS

### Installation Method (If applicable)

.deb

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PrestonN** [comment]
Should be fixed now. Will be included in the next release.
