### ISSUE TITLE
[Feature Request]: CHANNEL FILTER 

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [FreeTubeApp/FreeTube#2066]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Groups can only help so much for isolating a single channel in the subscriptions feed 

### Proposed Solution

I communicate better visually than in writing:

![FreeTube_Channel_Filter_Needed_Feature](https://user-images.githubusercontent.com/577091/153110899-9a216538-5630-44aa-9c48-b15a973cd2ad.png)

### Alternatives Considered

Having the option to switch between a list and/or grid layout would a weaker alternative

### Issue Labels

ease of use improvement

**Comment by hockerschwan** [comment]
I'm working on this.
<div style="display:flex;">
<img src="https://user-images.githubusercontent.com/80553357/154720617-540b96d8-a176-469e-b3c0-414233e63451.PNG" width="240" />
<img src="https://user-images.githubusercontent.com/80553357/154720639-f11c019e-2887-437d-a563-c87221fdd01f.PNG" width="240" />
<img src="https://user-images.githubusercontent.com/80553357/154720635-27da0cd3-a8fc-4b3d-bb0c-7a55f63f9916.PNG" width="240" />
<img src="https://user-images.githubusercontent.com/80553357/154720629-dba77244-eb18-4c5e-b8c0-2d82700e4703.PNG" width="240" />
<img src="https://user-images.githubusercontent.com/80553357/154720627-3027e29e-47ea-4ad9-9bf0-7760160155ea.PNG" width="240" />
<img src="https://user-images.githubusercontent.com/80553357/154720623-34088586-ff33-4f0e-ad1e-e10f860ca6ba.PNG" width="240" />
</div>

<br />
There are 2 concerns.<br />
1: In the 2nd picture, with "Dark" theme, input field blends in with SideNav. ( both #262626 )<br />
2: Side bar is narrow so translations might be problematic depending on the language.<br />
   maybe just "filter"
<br />
Any thoughts?

**Comment by neurodiverseEsoteric** [comment]
How tricky would it be to make the expanded sidebar resize-able (a wider scrollbar would be nice for accessibility, too) 
What if the sidebar color was the same as the videos feed (which for dark theme is #303030)?

**Comment by PrestonN** [comment]
I can't say I'm a fan of this type of workflow (having a text input in the sidebar). I'd much rather have a dedicated page for viewing your channels and have a search option put there instead. Likely the best approach would be to repurpose some of the profile pages to allow you to search and then navigate to a channel's page. If we desperately need to then we can add a button in the sidebar to go to this new page, but having a text input sitting on the sidebar is not very pleasing to look at IMO.

**Comment by neurodiverseEsoteric** [comment]
It doesn't bother me or my OCD, and surely fewer carpal-tunnel-loving micro-movements and the reduction of stress caused by more navigation (plus the added loading time) are more of a priority than aesthetics...

**Comment by hockerschwan** [comment]
Right now, we have "Subscription List" in Profile Select -> Profile Manager -> Edit Profile, but can't navigate to the channel page and to be honest, it's hard to reach.
This may be a good opportunity to create "Channels" page (or whatever) on the side bar to manage and search subscriptions
.<br>
As for the background, #303030 is the same as top nav<br>
<img src="https://user-images.githubusercontent.com/80553357/154786577-f0a75acb-bd3a-40f4-9a94-84161cda8951.PNG"  width=100>

**Comment by neurodiverseEsoteric** [comment]
Looks good to me (aside from the still-too-skinny-and-easy-to-miss scrollbar, and the lack of a grab widget to resize the whole sidebar itself). If any page is most needed; it's one for subscribing to playlists (as well for creating them).

**Comment by ChunkyProgrammer** [comment]
I think creating the "Channels" page on the sidebar would be the best option
