### ISSUE TITLE
[Bug]: Not having the 1080 resolution option

### ISSUE THREAD

**Issue by aeropatron** [FreeTubeApp/FreeTube#2067]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

In some youtube videos as this one-->  https://www.youtube.com/watch?v=H99hvPlC4is
Where you have  144p 240p 360p 480p 720p and 1080p resolutions available
![Captura de pantalla de 2022-02-09 16-02-19](https://user-images.githubusercontent.com/12184566/153229509-ccb82775-22ed-4265-8b1c-8e759709ad6d.png)
Freetube only shows to me two options: 360p and 720p
![Captura de pantalla de 2022-02-09 16-02-45](https://user-images.githubusercontent.com/12184566/153230016-27d21d77-556d-4180-80a2-6003e925d63f.png)

Despite having at settings that predetermined setting at player must be 1080; (changing it to auto don't fix it)

I am a daily user of FreeTube, so thank you very much devs for letting me use the software you coded and mantain.   : )

### Expected Behavior

Display the 1080p on all the videos with the 1080p option and use it by defeault if selected by default.

### Issue Labels

feature stopped working in some videos

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Ubuntu 21.10

### Installation Method (If applicable)

.deb

### Last Known Working FreeTube Version (If Any)

Not sure

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by maplepy** [comment]
It happened to me because the API had to fallback to an invidious instance that didn't support 1080p, is that something you checked? Or does it happen every time on this video even if you reload Freetube?

**Comment by aeropatron** [comment]
Hi there @maplepy,
I have just try changing API from local to indivious and it shows all resolutions and plays 1080.  : )

So I will use this API and dont use the local one.

Thank you.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Thankyou @maplepy  for helping out @aeropatron
