### ISSUE TITLE
Paid videos spam subscription feed

### ISSUE THREAD

**Issue by zorbakus** [FreeTubeApp/FreeTube#208]
One of my subs is "Vsauce" who has some non-free videos which you have to buy first. 
I attached a screenshot where you can see that those videos appear on top of the sub feed with 0 views and 0 or 2 seconds ago. I have to scroll further way down to see actual feed content.

![freetube_glitch](https://user-images.githubusercontent.com/43297999/50566656-39299e00-0d34-11e9-839d-3905d6325488.png)

**Comment by MegaArthur** [comment]
Same here, also VSauce

**Comment by MegaArthur** [comment]
But also, duplicate of https://github.com/FreeTubeApp/FreeTube/issues/198

**Comment by PrestonN** [comment]
This should be fixed with #210
