### ISSUE TITLE
[Bug]: [Wayland] Slowscrolling

### ISSUE THREAD

**Issue by BirdInFire** [FreeTubeApp/FreeTube#2080]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Use wayland server (fedora) by default.
2. Open the app.
3. Scroll, the scroll speed is very slow.

### Expected Behavior

Normal scroll speed

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.16.0 Bêta

### Operating System Version

Fedora 35

### Installation Method (If applicable)

Flathub

### Last Known Working FreeTube Version (If Any)

Never worked propely

### Primary API used

Invidious API

### Additional Information

I do know it's a electron bug (himself herited from chromium). 
But since they do not fix it and in the end of a day your app have it too, can you please fix it when detecting wayland increase the scroll speed ?

Even if it's a temporary fix because chromium know this bug from year and they haven't fixed it.

Note : it's probably due to the use of Xwayland when launched on a wayland desktop
Note 2 : imwheel can fix it, but it force freetube to fallback on xwayland, so temp solution, would prefer a fix to remain on wayland native electron code.
Note 3 : Wayland fix some security misconception of the X server, so relying too much on Xwayland isn't a good idea. 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by BirdInFire** [comment]
Note : imwheel can fix it, but it force freetube to fallback on xwayland, so temp solution, would prefer a fix to remain on wayland native electron code.

**Comment by PrestonN** [comment]
If it's a Chromium bug, then it isn't something that we can fix and needs to be fixed by Chromium / Electron. See my comment at #2081
