### ISSUE TITLE
[Bug]: [Wayland] native support broken

### ISSUE THREAD

**Issue by BirdInFire** [FreeTubeApp/FreeTube#2081]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Run Flatpak on Elecrton's native code with the command : flatpak run io.freetubeapp.FreeTube --disable-gpu --enable-features=UseOzonePlatform --ozone-platform=wayland
Disable gpu is enabled because some electron app do not work on native wayland with gpu acceleration enabled (without it it doesn't work too.)

2. see this error :

[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/freetube/freetube --type=zygote --enable-crashpad
LaunchProcess: failed to execvp:
xdg-settings
[2:0215/000209.731764:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: 
[2:0215/000209.832786:ERROR:cursor_loader.cc(114)] Failed to load a platform cursor of type kNull
[53:0100/000000.848231:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.

### Expected Behavior

Freetube start and open the page.

### Issue Labels

content not loading, usability issue, visual bug

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Fedora 35

### Installation Method (If applicable)

Flathub

### Primary API used

Invidious API

### Additional Information

I think Any wayland bug must be resolved because majority of linux distro actually convert themselve to wayland default, so the "normal" user will not understand why freetube does not work like always (due to Xwayland use).

Note : it's probably due to Electron version, so updating to a fixed version of electron must do the trick.
Note 2 : Wayland fix some security misconception of the X server, so relying too much on Xwayland isn't a good idea.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PrestonN** [comment]
There isn't much we can do about this. Electron on Wayland, while working, may have quirks that we can't solve ourselves. We always do our best to stay up to date on Electron versions to get issues like these fixed as soon as possible. If there's a special flag that can help with support then we can enable it. If not, it's out of our hands.

**Comment by BirdInFire** [comment]
> There isn't much we can do about this. Electron on Wayland, while working, may have quirks that we can't solve ourselves. We always do our best to stay up to date on Electron versions to get issues like these fixed as soon as possible. If there's a special flag that can help with support then we can enable it. If not, it's out of our hands.

Can you reopen it to link it to a request to update electron 17.3.1 who seem to have fixed the problem

See their changelog : https://github.com/electron/electron/releases/tag/v17.3.1
