### ISSUE TITLE
[Bug]: Search in playlist does not work

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#2084]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Go to playlist tab.
2. Type something in.
3. The window will reload, but not search for something.

### Expected Behavior

A search should start and show results.

### Issue Labels

feature stopped working

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Manjaro

### Installation Method (If applicable)

other

### Last Known Working FreeTube Version (If Any)

It used to work with a custom/patched version of v0.15.1

### Additional Information

The search function in the history tab is still working.

Related to #1942 and maybe #2023.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by toby63** [comment]
I did some testing:
1. It is not related to #2023, which was also not expected.
2. It also does not work with Electron 15.

**Comment by PrestonN** [comment]
Should be fixed now. Will be included in the next release.
