### ISSUE TITLE
[Feature Request]: Add the "Question" type to the repository in the "FreeTube/issues/new/choose" page.

### ISSUE THREAD

**Issue by sebma** [FreeTubeApp/FreeTube#2086]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi,

I'd like to ask a question but there is no "Question" type in the https://github.com/FreeTubeApp/FreeTube/issues/new/choose page.

### Proposed Solution

Create a `question.yaml` in the [FreeTube/.github/ISSUE_TEMPLATE](https://github.com/FreeTubeApp/FreeTube/tree/development/.github/ISSUE_TEMPLATE/) to add a new "Question" type template.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
U are able to ask questions in our discussion tab.

**Comment by sebma** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc I didn't about the discussion tab.Thanks.

**Comment by sebma** [comment]
https://github.com/FreeTubeApp/FreeTube/discussions/2100
