### ISSUE TITLE
Recommend Libredirect instead of Privacy Redirect

### ISSUE THREAD

**Issue by IronMaltese** [FreeTubeApp/FreeTube#2089]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Freetube recommends that the user downloads Privacy redirect to watch YouTube videos in freetube, but this extension hasn’t been updated in 3 months

### Proposed Solution

Link to [Libredirect](https://github.com/libredirect/libredirect) instead, since this project is actively maintained

### Alternatives Considered

Maybe don’t get rid of privacy redirect, and instead just add lib redirect as another recommendation

### Issue Labels

display more information to user, ease of use improvement

### Additional Information

N/A

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
6dec 2021 was their last commit. If it was a year ago i would consider it out of date.

**Comment by dtbj** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Please reopen issue he send link to wrong repo here is the original one maybe? not sure: https://github.com/libredirect/libredirect

**Comment by dtbj** [comment]
it's last commit is 2hrs ago which is cool.

**Comment by dtbj** [comment]
![image](https://user-images.githubusercontent.com/87176273/154856757-79e7a2d5-6ea8-4778-add5-06bbc522230a.png)
They already have support for FreeTube :-)
