### ISSUE TITLE
[Feature Request]: Right click menu should match theme

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#2092]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Right click menu is always black, it doesnt matter what theme is applied.

### Proposed Solution

Menu should match the applied theme

### Alternatives Considered

None.

### Issue Labels

visual improvement

**Comment by truthinhoney** [comment]
I think that this might be a bug.

My right click menu is always dark regardless of the theme I change it to.

Using Flatpak v0.16.0 Beta

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
ah i said white. i meant to say black :)
