### ISSUE TITLE
Getting API Error

### ISSUE THREAD

**Issue by shom13** [FreeTubeApp/FreeTube#2093]
Getting local api error 429 followed by individous api error undefined. 

A recent problem, maybe since yesterday before that everything was working fine

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hello! Please see this [article](https://docs.freetubeapp.io/usage/common-issues/#429-errors) to learn more.

Note: DO NOT remove the template. Ur issue will be closed without any response to ur issue if we cant get all the info we need.

In this case everything u need to know is stated on our wiki.
