### ISSUE TITLE
[Bug]: Middle clicking on certain button won't do anything

### ISSUE THREAD

**Issue by 0x6e656b6f** [FreeTubeApp/FreeTube#2094]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Some of the places that I find middle click to not do anything:
- [x] Channel name and picture when watching a video.
- [x] Any item on left menu.
- [ ] Back and forward button. (Pika: Impossible, see https://github.com/FreeTubeApp/FreeTube/issues/2094#issuecomment-1464841860)
- [x] Channel name and picture when in playlist view.
- [x] Channel menu (Videos, Playlists, and About).

### Expected Behavior

Middle clicking should always open a new window according to the button that's being clicked.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Fedora Silverblue 35

### Installation Method (If applicable)

Flathub

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
maybe this could be @PikachuEXE next project :)

**Comment by 0x6e656b6f** [comment]
> WHAT!?

It can be like this: middle click on back button would bring up the previous window in a new window and vice versa.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I didnt know that this was a thing but i also like to see this implemented the same way its implemented in the browser.

**Comment by PikachuEXE** [comment]
Update `Channel menu (Videos, Playlists, and About).` to be checked (I assume checked = solved)

`Back and forward button` still valid though (and I have no idea how to implement yet)

**Comment by PikachuEXE** [comment]
History API only allows going back/forth but NOT reading states
https://developer.mozilla.org/en-US/docs/Web/API/History

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PikachuEXE so that means we can close it right?

**Comment by PikachuEXE** [comment]
The title reads "Middle clicking on certain button won't do anything"
We can still make middle click on `Back and forward button` navigates but no in new window
Very easy but not sure if that's needed

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Expected Behavior
> Middle clicking should always open a new window according to the button that's being clicked.

**Comment by PikachuEXE** [comment]
Unless we implement "history" with our own method and store all the previous/forward entries, this won't be possible
And it seems too complicated to solve this and I would mark it as won't fix (until there is an easy enough way)

**Comment by PikachuEXE** [comment]
In addition there is [an issue on electron already complaining the lack if API for history access](https://github.com/electron/electron/issues/33899)
I don't think this can be implemented until it's solved

**Comment by PikachuEXE** [comment]
Thus I updated the issue description to indicate that it's currently impossible to implement middle click on `Back and forward button`
So all issues should be addressed now
