### ISSUE TITLE
[Feature Request]: Add an anti-biometric fingerprinting option against keypress timing analysis in the search bar

### ISSUE THREAD

**Issue by Skavard** [FreeTubeApp/FreeTube#2095]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Many big tech companies uses many techniques to collect our data even if we try to be anonymous. Even if we use many front-end programs to anonymize ourselves, they could just analyze the timing of our keypress to fingerprint us. Facebook already collects the data on how long the user scrolls through the feeds so this technique already exists beyond just theoretical.

### Proposed Solution

One way to help mitigate this is by adding an option that makes the keypress timing similar across users by delaying the sending of the keystroke even by just a few milliseconds and averaging them all out so that the service, in this case YouTube, will have a harder time differentiating one person from the crowd.

### Alternatives Considered

Turning off autosuggest may or may not mitigate the issue by hopefully not sending every keystroke individually but you miss out on that feature and many people may not choose to do that.

### Issue Labels

new optional setting

**Comment by PrestonN** [comment]
We use a debouncer for grabbing search settings, which means that it doesn't make the call for every keystroke you make unless you were extremely slow at typing. Once it detects a pause in your typing, it will then attempt to get search suggestions. Plus like you mentioned, if you're really concerned about this, you can just disable suggestions all together.
