### ISSUE TITLE
[Bug]: FreeTube interferes with video displaying in VLC Media Player

### ISSUE THREAD

**Issue by deejf** [FreeTubeApp/FreeTube#2096]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

After running a flatpak update, when I run FreeTube, and then run VLC Media Player, the video in VLC does not display properly. This behavior persists until I reboot, whether or not FreeTube is running at the same time. Also, the behavior is somewhat intermittent. It happens most of the time, but sometimes VLC works just fine.

### Expected Behavior

I expect to be able to run VLC without interference from other apps. It's my main video player. (The XFCE standard player, Parole, does not share this issue. Only VLC.)

### Issue Labels

visual bug

### FreeTube Version

v0.16.0 beta

### Operating System Version

Fedora 35 (XFCE Spin)

### Installation Method (If applicable)

Flathub

### Last Known Working FreeTube Version (If Any)

v0.15.1

### Primary API used

Local API

### Additional Information

I am not a programmer in any capacity. I use the command line to run software updates, and do limited file conversions, and that's all. So I don't know which packages are being affected, nor how to determine it, nor what files or logs I need to grep or anything like that.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@deejf is this still an issue for u on v0.17.1?
