### ISSUE TITLE
[Bug]: Live chat comments doesn't load

### ISSUE THREAD

**Issue by archNATRON** [FreeTubeApp/FreeTube#2097]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Open a live with active chat. In my case I used the first result of "lofi 24/7" on FreeTube ( lofi hip hop radio - beats to relax/study to ).
2. Instead of the chat menssages, get "Live chat is enabled. Chat messages will appear here once sent."
3. Wait to get any comment
4. Get nothing still, while if opening on Youtube is the opposite

### Expected Behavior

When opening a live on FreeTube, the chat doesn't loads comments.

I do not use Invidious API

### Issue Labels

API issue, content not loading, text/string issue, usability issue

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Windows 10

### Installation Method (If applicable)

.exe

### Last Known Working FreeTube Version (If Any)

No

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@archNATRON
