### ISSUE TITLE
[Bug]: Since today : Five "Local API Errors" on Subscription page and a "Local API Error (Click to copy) Error: connect ECONNREFUSED 127.0.0.1:9050" on a Video page

### ISSUE THREAD

**Issue by sebma** [FreeTubeApp/FreeTube#2101]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Open Freetube on the Subscription page
2. Click on any video

### Expected Behavior

It should be able to connect to the local API. 

### Issue Labels

API issue

### FreeTube Version

v0.16.0

### Operating System Version

Ubuntu 20.04.4 LTS

### Installation Method (If applicable)

.deb

### Last Known Working FreeTube Version (If Any)

v0.16.0

### Primary API used

Local API

### Additional Information

Hi,

The weird thing is that it is working fine on another computer with the same OS version.

I wonder what TCP/UDP port the local API is listening to : 
```shell
$ ss -anut | grep -w 9050
$
```

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could u provide all the errors you're getting and send screenshots of the errors in the console. U can open the console with `CTRL+SHIFT+I`

**Comment by sebma** [comment]
Sure :smile: 

The Subscription Page : 

![image](https://user-images.githubusercontent.com/4569306/156382981-2737ca2f-6144-4efe-bd1d-bfc1b8960c6b.png)

A video Page : 

![image](https://user-images.githubusercontent.com/4569306/156383168-3de803cc-3727-4cd7-b8be-5f0457412bb8.png)

**Comment by sebma** [comment]
Found it ! It seemed the "Enable Tor / Proxy" option was somehow enabled in the "Proxy Settings" although there is no Tor program running on my system. I just disabled it and it solved the problem. Thanks for help. Sorry for the inconvenience.
