### ISSUE TITLE
Freetube - Armhf 

### ISSUE THREAD

**Issue by burny0202** [FreeTubeApp/FreeTube#2104]
### Guidelines

- [x] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Is not currently build for raspberry pi Armhf

### Proposed Solution

Build a version for armhf

### Alternatives Considered

Flatkpak does not work

### Issue Labels

new feature

**Comment by arrowgent** [comment]
[pi-apps](https://github.com/Botspot/pi-apps/blob/master/apps/FreeTube/install-32) & [raspbian-addons](https://docs.raspbian-addons.org/package-list/)

both maintain an armhf freetube
but a release here on the official github source would be preferred.

hopefully the github actions for build & release works out
