### ISSUE TITLE
Zoom function for PiP

### ISSUE THREAD

**Issue by MagicLike** [FreeTubeApp/FreeTube#2105]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When using a laptop, resizing the PiP window is more difficult with a trackpad than with a mouse.

### Proposed Solution

Implement the function to zoom on the PiP window to resize it.
(Also a cool thing would be to ba able to use the scrollwheel too)

### Alternatives Considered

Using the normal way to resize the PiP window.

### Issue Labels

ease of use improvement, improvement to existing feature, new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isn't possible because PIP is very limited in   their implementation.

See  https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API
