### ISSUE TITLE
[Feature Request]: match theme of context menu when pressing 'alt'

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#2106]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

menu is always black, it doesnt matter what theme is applied.

### Proposed Solution

Menu should match the applied theme

### Alternatives Considered

None.

### Issue Labels

visual improvement

**Comment by vallode** [comment]
#1800 will actually cause this to sync to system preference which seems to be the current standard for Electron applications... the color of the context menu cannot be affected from our side and only system-level theming.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is it the same for #2092

**Comment by vallode** [comment]
> Is it the same for #2092?

Was about to comment there too: yes, the right click menu will also match system theme. Key point though is that it will be _system theme_ not app theme, I think it's intentional that native menus should follow system theme options.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Okay if that is the case i'll check if ur pr does that and close these issues if thats the case.
