### ISSUE TITLE
[Bug]: Sponsorblock segments are not loading

### ISSUE THREAD

**Issue by HairyMilkshakes** [FreeTubeApp/FreeTube#2109]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Go to this video as an example: https://www.youtube.com/watch?v=1B3Xi5L6siI
2. Have it load, then open the same video in FreeTube and compare
3. Some submitted SB segments are not loading
4. Pics below as comparison
FreeTube: ![2022-03-05_20-49-35](https://user-images.githubusercontent.com/13473043/156909695-c61dff36-c2d1-4488-a1ec-118879dc8bb7.png)
YouTube extension: ![2022-03-05_20-49-56](https://user-images.githubusercontent.com/13473043/156909696-9a6c1edf-a8a8-49d0-b230-5e3ee9ea93c9.png)

### Expected Behavior

Expected all segments submitted to SB to load.

### Issue Labels

feature stopped working

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Windows 10

### Last Known Working FreeTube Version (If Any)

N/A

### Additional Information

N/A

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is correct we don't have all categories of sponsor segments implemented yet
