### ISSUE TITLE
[Bug]: User feedback for downloading process missing

### ISSUE THREAD

**Issue by ayoungethan** [FreeTubeApp/FreeTube#2110]
### Guidelines

- [x] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Go to a video
2. Select a format to download
3. Start download
4. Wait indefinitely
5. No download ever appears or finishes
6. No failure notice or dialogue appears telling me what happened -- I have to infer that the download started, failed or succeeded by checking my internet usage and folder where the file was supposed to be saved
7. Successful downloads also appear to provide no notification

### Expected Behavior

If a download fails, I expect a dialogue box telling me it failed and perhaps why it failed so I can try to correct the issue. A download progress tracker* or download queue would also be very helpful

*might not be possible due to the nature of the downloading from YouTube

### Issue Labels

feature stopped working

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Elementary OS 6.1

### Installation Method (If applicable)

Flathub

### Last Known Working FreeTube Version (If Any)

[my first version]

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ayoungethan** [comment]
Related to this, download capacities are opaque. Can the program download multiple files (from the same or different videos) at once? Can it playback while downloading? If a download gets interrupted (due to network disruption or the computer going to sleep, etc), does it autoresume or does it need to be restarted from scratch? It is difficult for the user to discover these limitations as it stands.

this is a wonderful project!

**Comment by Proctophobic** [comment]
Just to confirm, i'm experiencing the same issue(s) . . . It's possible that it is downloading, just 'extremely' slowly, like 3Mbps . . . Unfortunately, since there is no download dialogue (showing the progress of downloads is a much needed feature) it's difficult to know what's happening except for monitoring your network speed . . . It's also possible that this issue is to do with Invidious because Web downloads are also stopping (at about 25%), for me at least . . . I know this program uses Invidious though I have no idea how or why!?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
u will get messages when a download has failed or something is wrong with it. also u will get a message when a download has started and completed. the download capacities will be shown when the download tab has been implemented otherwise u'll get a spam of messages.

please provide examples of videos that are not working for u?

**Comment by ayoungethan** [comment]
I don't think it's the fault if individual videos or FreeTube that downloads fail. I've always dealt with failing downloads from YT regardless of how I try or what software I use. The only difference is that, e.g., I get progress and failure notices so I know what fails and when without having to go figure out it.

It sounds like there are planned enhancements to the FreeTube download process that will resolve this issue, so I would say let's wait for those before doing anything further. If they enhance transparency of the download process by allowing user to stay informed of progress (%, rate, time elapsed, etc) or failure (stalls and timeouts) then I would say that should resolve the issue.

**Comment by Proctophobic** [comment]
Yeah, it's not particular Vids, it seems to happen all the time now; although I am getting an error message sometimes ('There was an issue downloading').

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Yeah, it's not particular Vids, it seems to happen all the time now; although I am getting an error message sometimes ('There was an issue downloading').

I'm sure that this is fixable. I'm pretty sure it has to do with the way filename is being saved. U cant use some characters in filenames and we don't check to replace them. So it will throw an error

**Comment by Proctophobic** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc :: That's quite insightful . . . I did manage to download a couple of files by simplifying the filenames, but it still seems to be hit or miss otherwise . . . This for example:  https://youtu.be/LPr8VPFTUVk  refuses to download either as combined MP4 or components (video and audio webm/mp4), although I can download it without issue using an online downloader or with NewPipe on an Android device.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
yeah ur right something weird is going on there

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Just to confirm if u download a video doesnt it does take very long to get downloaded. U can download multiple videos (that dont use weird filenames) and it will eventually finish.

> @efb4f5ff-1298-471a-8973-3d47447115dc :: That's quite insightful . . . I did manage to download a couple of files by simplifying the filenames, but it still seems to be hit or miss otherwise . . . This for example: https://youtu.be/LPr8VPFTUVk refuses to download either as combined MP4 or components (video and audio webm/mp4), although I can download it without issue using an online downloader or with NewPipe on an Android device.

@Proctophobic This does also apply to this video.

**Comment by aldobelus0** [comment]
I have installed also the v0.16.0 Beta and I got the same problem. Freetube doesn't offers me a download dialogue to know what is happening. And I can tell you that I have no downloaded files on my computer with or without a warning.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
all bugs regarding downloading are fixed in the latest nightly build. The only thing that is left is integrate a download tab where u can see the status of your downloads.

**Comment by aldobelus0** [comment]
It's solved in v0.18.0 Beta

**Comment by ayoungethan** [comment]
> It's solved in v0.18.0 Beta

No it's not. There is still no indicator that download is ongoing. Download occurs entirely in the background as of 18.0 beta. This is a problem, because it is possible to accidentally interrupt the download by closing the program, or by starting the download of another video, as the program can only support one download at a time (at least that is my consistent experience).

**Comment by purpwiz** [comment]
> all bugs regarding downloading are fixed in the latest nightly build. The only thing that is left is integrate a download tab where u can see the status of your downloads.

Any news on the download tab?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> > It's solved in v0.18.0 Beta
> 
> No it's not. There is still no indicator that download is ongoing. Download occurs entirely in the background as of 18.0 beta. This is a problem, because it is possible to accidentally interrupt the download by closing the program, or by starting the download of another video, as the program can only support one download at a time (at least that is my consistent experience).

Closing as this kind of info is something that is going to be addressed in the download tab https://github.com/FreeTubeApp/FreeTube/issues/1772#issuecomment-1689720206
