### ISSUE TITLE
Clarify download capacities for users

### ISSUE THREAD

**Issue by ayoungethan** [FreeTubeApp/FreeTube#2111]
Download capacities are opaque. Can the program download multiple files (from the same or different videos) at once? Can it playback streaming videos while downloading? If a download gets interrupted (due to network disruption or the computer going to sleep, etc), does it autoresume or does it need to be restarted from scratch? Or, for example, is it one download or stream at a time? It is difficult for the user to discover these limitations as it stands.

this is a wonderful project!

_Originally posted by @ayoungethan in https://github.com/FreeTubeApp/FreeTube/issues/2110#issuecomment-1060035239_

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
this will be fixed when the download tab will be introduced will close for now
