### ISSUE TITLE
[Bug]: Invidious API

### ISSUE THREAD

**Issue by BirdInFire** [FreeTubeApp/FreeTube#2112]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Add a specifically selected instance into the invidious url form.
2. Close the software and clear dns cache.
3. Launch a command to see the dns query.
4. Launch Freetube.
5. Now you see that even with invidious manually set it connect to api.invidious and connect to randomly selected invidious and the one we have selected 2 unwanted connection.

Because now it connect to invidious api and another instance too and if we block these extra connection at DNS level (even if we have manually added an authorized invidious freetube start with black page and block.

### Expected Behavior

See dns query and connection only to freetube related url and invidious set url only and do not contact and select invidious instance if we have manually set one.

### Issue Labels

API issue, content not loading

### FreeTube Version

0.16.0 Beta

### Operating System Version

Fedora 35

### Installation Method (If applicable)

Flathub

### Primary API used

Invidious API

### Additional Information

this cause a problem for those like me who select their instance for their géographical localtion / security (TLS version) and or the support or DNSSEC for their domain.
Randomly selected instance do not meet these requirement.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PrestonN** [comment]
You must manually declare that set instance as your default one once you have changed your current instance. Use the "Set Current Instance as Default" button to do this. Even though this will be set, you will still connect to https://api.invidious.io in order to get a list of publicly available instances.

**Comment by BirdInFire** [comment]
> You must manually declare that set instance as your default one once you have changed your current instance. Use the "Set Current Instance as Default" button to do this. Even though this will be set, you will still connect to https://api.invidious.io in order to get a list of publicly available instances.

and it's what i have done and the software continue to contact the api ...

**Comment by BirdInFire** [comment]
@PrestonN after some research the problem stop when i hide in the left bar my chanel subscribe.
It seem the icon of this bar do not follow the manual instance.
someone can try to replicate ?
