### ISSUE TITLE
[Feature Request]: Subtitle support in the Picture-in-Picture window

### ISSUE THREAD

**Issue by daks** [FreeTubeApp/FreeTube#2115]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

First, thanks for this amazing software.
I use a lot PiP window to watch videos out of Freetube main videos, but subtitles still appears in this main video not in the PiP window.

### Proposed Solution

Make subtitles appear in the PiP window instead of the main one.

### Alternatives Considered

No real alternative considered.

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
this is not possible see https://github.com/FreeTubeApp/FreeTube/issues/1219#issuecomment-824160994

**Comment by bachig26** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc @PrestonN I wanted to ask for the possibility of reopening this feature request in favor of the new Firefox browser version 100.0 which supports the caption/ subtitle in PiP.
I think there is a possibility if you can use this to write the code by replacing the chromium, as I think this might a difficult one at present if the core/base doesn't support it. I letting you know the possibility to explore in this.

https://blog.mozilla.org/en/products/firefox/firefox-picture-in-picture-rolls-out-subtitles/
