### ISSUE TITLE
[Feature Request]: A setting in the themes for the light/dark theme to match the Windows global theme

### ISSUE THREAD

**Issue by Memesy02** [FreeTubeApp/FreeTube#2116]
### Guidelines

- [x] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Need to manually change theme for dark or light mode

### Proposed Solution

An option for this would also be more familiar to people coming from the youtube website. Additionally it's one less setting to have to toggle for a user who wants to change their theme depending on time of day.

### Alternatives Considered

Have not considered any

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/691
