### ISSUE TITLE
[Bug]: No anti-aliasing on Japanese characters

### ISSUE THREAD

**Issue by Fxsch** [FreeTubeApp/FreeTube#2119]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Japanese characters don't have anti-aliasing applied to them, making them look pixelated. I expected this to be the same for Korean and Chinese characters but they look exactly how they should.

### Expected Behavior

I expected the Japanese characters to have anti-aliasing applied to them.

### Issue Labels

visual bug

### FreeTube Version

v0.16.0

### Operating System Version

Arch Linux kernel version 5.16.14

### Installation Method (If applicable)

other

### Additional Information

I've installed Freetube through the AUR (https://aur.archlinux.org/packages/freetube-bin). 

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Fxsch is this still an issue for u in the latest version of FT? If so could maybe provide some screenshots of how it supposed to look and how it actually looks?

**Comment by maboroshin** [comment]
Related: https://github.com/FreeTubeApp/FreeTube/issues/673

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Fxsch please address this over at https://github.com/FreeTubeApp/FreeTube/discussions/3619, so we keep everything in one place.
