### ISSUE TITLE
[Bug]: A JavaScript error occurred when launching the application

### ISSUE THREAD

**Issue by samiullahqutbi** [FreeTubeApp/FreeTube#2131]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

![image](https://user-images.githubusercontent.com/89246695/158540056-364e5c76-0270-40d0-ab57-5077c8c51d97.png)
After clicking on ok, the app started and I watched videos without facing any error message

### Expected Behavior

The error message shouldn't appear

### Issue Labels

accessibility issue

### FreeTube Version

v0.16.0 Beta

### Operating System Version

windows 10 21h2

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by TMS-Namespace** [comment]
I am not the dev here, just passed by, but from the error message, it hints you that your history file is corrupted, and it asks you to restore the backup. To do so, it asks you to rename the "history.db~" by removing the ~, maybe you can try that?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @samiullahqutbi did u try out the fix that @TMS-Namespace suggested?

**Comment by samiullahqutbi** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc I don't get this error anymore that's why I didn't tried to rename the history.db file
