### ISSUE TITLE
[Feature Request]: Hiding left menu

### ISSUE THREAD

**Issue by 0x6e656b6f** [FreeTubeApp/FreeTube#2132]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Left menu size can be controlled by the hamburger button and clicking it would expand/collapse the left menu. By programming the hamburger button as a button that expand/collapse left menu, the button cannot be used to hide the left menu. Hiding left menu is especially important if you have a device with small screen size.

### Proposed Solution

Clicking on hamburger button should hide the left menu. As to expand/collapse the left menu, we could implement so that when the user hover the cursor to the right side of left menu, the cursor changes to resize cursor and clicking and dragging will resize left menu.

### Alternatives Considered

Add option for left menu to intelligently hide itself when video is in theater mode. Hovering the cursor on the left side of the app will then reveal the left menu.

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@0x6e656b6f what is the size of your screen?
