### ISSUE TITLE
[Feature Request]: Delete channels that no longer exist

### ISSUE THREAD

**Issue by sibeliusg** [FreeTubeApp/FreeTube#2133]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I have subscribed to about 300 channels. Some of them do not exist anymore on youtube. Unfortunately there is no way to delete or unsubscribe to them on Freetube as the channel keeps loading and loading. 

I'm using Freetube 0.16.0 as a Flatpack on Manjaro Linux.

### Proposed Solution

It would be awesome, if there was a way to detect those channels and delete them from Freetube. 

### Alternatives Considered

right click on any channel gives the option to delete it.

### Issue Labels

improvement to existing feature

**Comment by arrowgent** [comment]
problem is getting the required api info from invidious/youtube to know what the channel name & info WAS
if its gone, then so is the data to query this information

something to indicate
A) channel was infact deleted/banned
B) info inserted to say "deleted channel"
