### ISSUE TITLE
[Feature Request]: Should be able to open settings while video continues to play in the background

### ISSUE THREAD

**Issue by PAI5REECHO** [FreeTubeApp/FreeTube#2137]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When opening the settings the currently playing video is paused

### Proposed Solution

Continue to play video in the background while settings are being changed

### Alternatives Considered

[comment]: <> (asd)

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1077
