### ISSUE TITLE
[Bug]: Videos in subscription list sorted by channel

### ISSUE THREAD

**Issue by mattfj10** [FreeTubeApp/FreeTube#2139]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Open Freetube
2. Click subscriptions menu item
3. Refresh list if necessary

### Expected Behavior

Recently, I've noticed that in my subscription list in FreeTube, all the videos are grouped by channel. So when I see all the new videos in my subscription feed as I scroll down all the new videos will be grouped/sorted by channel rather than upload time. 

### Issue Labels

visual bug

### FreeTube Version

0.16.0

### Operating System Version

Linux Mint 19.3 

### Installation Method (If applicable)

.deb

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
after 24hours passes Youtube only provides uploaded 2 days ago. So everything after 24hours will get grouped. Nothing we can do about this.
