### ISSUE TITLE
[Bug]: Skin color emojis break live chats

### ISSUE THREAD

**Issue by HughBone** [FreeTubeApp/FreeTube#2144]
### Guidelines

- [x] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Was messing around with the youtube-chat repo and discovered any non-yellow emojis (e.x. 👍🏾) sent in live chat cause an error.

"TypeError: Cannot read properties of undefined (reading 'shift')"
**(Comes from data.emoji.shortcuts.shift())**

On FreeTube, this stops future messages from loading.

### Expected Behavior

Skin-colored emojis display as normal in live chat.

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Ubuntu

### Installation Method (If applicable)

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
Note for whoever works on this: Error seems to occur here

https://github.com/FreeTubeApp/youtube-chat/blob/718f8f3d4a190572593165a30ed4e50da88d6238/src/parser.ts#L56
