### ISSUE TITLE
[Bug]: FreeTube 0.16.0 not opening in Debian 11 

### ISSUE THREAD

**Issue by 66samhain** [FreeTubeApp/FreeTube#2145]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Hello. I have installed the .deb package for the 0.16.0 version, but I can't seem to be able to open up the app. When I click on the icon, it loads for a few seconds, then closes. Opening it from the terminal yields the same result. Version 0.15.1 works fine and opens up nicely. I also do not have any missing dependencies and the installation process went smoothly.

### Expected Behavior

For the application to open up. 

### Issue Labels

content not loading, inconsistent behavior, usability issue

### FreeTube Version

0.16.0

### Operating System Version

Debian 11 Bullseye

### Installation Method (If applicable)

.deb

### Last Known Working FreeTube Version (If Any)

0.15.1

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Atrate** [comment]
Same issue on Arch Linux, FreeTube 0.16.0-1
Log:
```
[DATE:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[1715712:0410/211555.158614:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property

```

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
i maybe have i hunch on whats happening but before we try that could u install [the latest nightly build](https://github.com/FreeTubeApp/FreeTube/actions/runs/2329685245) and check if this does open.
