### ISSUE TITLE
[Feature Request]: time slider in picture-in-picture

### ISSUE THREAD

**Issue by rebelcode-xr** [FreeTubeApp/FreeTube#2154]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Without a slider the user must disable PiP (Picture-in-Picture) to move forward/backward the video and activate again the PiP.

**NO SLIDER**
<img width="638" alt="image" src="https://user-images.githubusercontent.com/63522951/160398278-2c7d780e-c35b-4541-9150-00efa277e080.png">

### Proposed Solution

Add an "on hover" slider control to scroll the video timeline (removing the dark effect):

**MOCKUP**
<img width="638" alt="image" src="https://user-images.githubusercontent.com/63522951/160399937-5fa391a0-ce74-4050-bb11-6d00d3f6621b.png">

The slider color is taken from the theme.

### Alternatives Considered

It's also possible to add more UI controls like:
- volume
- +/-5 seconds
- time info

Would be interesting to consider also adding keyboard controls:
- up/down = volume
- left/right = +/-5 seconds

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isn't possible because PIP is very limited in   their implementation.

See  https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API
