### ISSUE TITLE
[Bug]: External Player iina failed to start.

### ISSUE THREAD

**Issue by sopans** [FreeTubeApp/FreeTube#2158]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Go to the settings menu.
2. Go to "External Player Settings".
3. Set external player to "iina"
4. Press the button to open a video in an external player.
5. Receive error¹
6.Attempted to change Custom External Player Executable to /Applications/iina.app to another error.²

### Expected Behavior

On step 4, I expected the video to open in the iina media player.

### Issue Labels

content not loading, usability issue

### FreeTube Version

v0.16.0 Beta

### Operating System Version

MacOS Monterey 12.3 (21E230)

### Installation Method (If applicable)

other

### Last Known Working FreeTube Version (If Any)

Not sure.

### Primary API used

Invidious API

### Additional Information

¹A JavaScript error occurred in the main process
Uncaught Exception:
Error: spawn iina ENOENT
at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
at onErrorNT (node:internal/child_process:477:16)
at processTicksAndRejections (node:internal/process/task_queues:83:21)

²Uncaught Exception:
Error: spawn /Applications/iina.app EACCES
at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
at onErrorNT (node:internal/child_process:477:16)
at processTicksAndRejections (node:internal/process/task_queues:83:21)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by eimimue** [comment]
Bug is still present in v0.17.0-RC-1735 Beta (macOS Monterey 12.3.1). Same result for mpv or vlc.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@sopans is this still an issue for u on v0.17.1?

**Comment by rootedetc** [comment]
> @sopans is this still an issue for u on v0.17.1?

Not the original author, but can confirm that issue still exists in 0.17.1-nightly-1915.

**Comment by elesto** [comment]
This issue is still happening in 0.17.1!

**Comment by lothar-cell** [comment]
It is still an issue on 0.18.0.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi, can you try a nightly build and check if u can still reproduce the bug? 
https://docs.freetubeapp.io/development/nightly-builds

https://github.com/FreeTubeApp/FreeTube/actions/runs/4045534050

**Comment by mhwice** [comment]
I can confirm this problem still exists with v0.19.0 Beta

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
inquires regarding external players migrated to https://github.com/FreeTubeApp/FreeTube/discussions/7789
