### ISSUE TITLE
[Bug]: FreeTube on windows 11 can't play some vdo that running ads, I guess. 

### ISSUE THREAD

**Issue by ThaidudeA** [FreeTubeApp/FreeTube#2159]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. go to https://youtu.be/AJsHbFgfmQY
2. play

### Expected Behavior

play

### Issue Labels

content not loading

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Windows 11

### Installation Method (If applicable)

.exe

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi, is it still not possible for u to play this video?
