### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by blackmaserati** [FreeTubeApp/FreeTube#2160]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Facing issue with Proxy settings. When I enable Tor/Proxy and tried to test proxy with the default setting I get a notification like "Error getting network information. Is your proxy is Configured Properly"
![Screenshot (25)](https://user-images.githubusercontent.com/87432651/161052364-acc5200a-af60-41b6-951e-e63cd921a406.png)
 

### Proposed Solution

I Couldn't  find alternatives to make this work

### Alternatives Considered

Expecting guidelines from the community.

### Issue Labels

improvement to existing feature

**Comment by blackmaserati** [comment]
![Screenshot (26)](https://user-images.githubusercontent.com/87432651/161053044-7ea8a2e5-0d60-4e98-aa31-ea7728c991a5.png)
After Enabling the proxy and testing a video from my subscription I get the above code error.

**Comment by ChunkyProgrammer** [comment]
Do you have tor running on that port?

**Comment by blackmaserati** [comment]
No I just enabled it in the app through proxy setting

**Comment by grrrrr** [comment]
You need to have a working instance of tor already installed that's listening on `127.0.0.1:9050`

**Comment by ChunkyProgrammer** [comment]
Closing this issue.

Reference:
https://github.com/FreeTubeApp/FreeTube/issues/1169#issuecomment-814269061
