### ISSUE TITLE
[Feature Request]: Improve layout of Data Settings section

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#2161]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

In the Data Settings (`Settings > Data Settings`) there are currently 8 buttons and 1 link to manage import/export of data.

With the currently layout the majority of the buttons are on one line making it not immediately clear the button groupings and the potential for overlooking an important export option is possible.

### Proposed Solution

I would suggest that the layout if changed slightly to group the paired import/export options on individual lines.

The styling appears that setting options are all center justified.  Given that, I would propose the following layout for the `Data Settings` section

```
           Export Settings / Import Settings / Check for Legacy Settings

                              Export History / Import History

                           Export Playlists / Import Playlists

                                    Manage Subscriptions

                            How do I import my subscriptions?
```
(**edit**:  changed to put export before import as this is the option which will likely get used more)

This makes it immediately clear that there are **three** options for importing and exporting data as well as a manage subscriptions and a help link.

 

### Alternatives Considered

No other suggested alternatives other than leave it as it's current less than clear layout.

### Issue Labels

visual improvement

### Additional Information

none

**Comment by grrrrr** [comment]
Does using the bot to mark items stale make sense when it's tagged [Feature Requests](https://github.com/FreeTubeApp/FreeTube/projects/7#card-80061626) even if unassigned?

**Comment by grrrrr** [comment]
oh I am sorry, I meant to come back to this after I had been testing the nightlies.   Yes the new layout makes things clearer imo and I'm happy to close this as complete

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Its okay, thanks for your contribution and i hope u like the nightly's :)
