### ISSUE TITLE
[Feature Request]: Better handle returning to a channel after doing a search in it.

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#2162]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Doing a `Search Channel` in one of your subscriptions makes it cumbersome to get back to the full video list

Example
1. Click a channel from the list in the side bar
2. Enter a search term into the `Search Channel` box and press enter
3. Decide you want to go back to the full channel list
4. Click on the Channel list in your sidebar to find it does nothing
5. Click on a different channel
6. Click on the channel you want
7. see all videos

### Proposed Solution

Possible solutions

1.  Add a x/clear button on the channel search box (in general a useful feature to remove the text) that would bring back the full channel listing of videos

and/or 

2.  Allow clicking on the channel listing in the sidebar to go back to the full listing

### Alternatives Considered

Leave the setup as is where you have to change to a different channel, then go back to the one you want.

### Issue Labels

ease of use improvement

### Additional Information

none

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2446
