### ISSUE TITLE
[Feature Request]: More frequent updates for Chrome webview

### ISSUE THREAD

**Issue by outis151** [FreeTubeApp/FreeTube#2164]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The latest Freetube release is still using Chrome v96 (latest is v100) as the underlying webview. With each new version there are usually a lot of security vulnerabilities that are fixed in Chrome.

While the risk of a security vulnerability being triggered during the use of the local Freetube API which is accessing Youtube is low, the risk of that happening while accessing an external invidious instance is significantly higher.

### Proposed Solution

More frequent stable builds

### Alternatives Considered

Warn the user before using external Invidious instances

### Issue Labels

improvement to existing feature

**Comment by PrestonN** [comment]
The Electron team itself will more than likely backport any fixes to older releases to help keep up with security. We try to keep up to date with whatever the latest Electron version is. Their release cycle is very fast however (A new major version is released every ~8 weeks) so it is rather difficult to be at the very latest version as they are. We still have to test whenever new versions come out and make sure that they work with our existing codebase. Sometimes the API changes which breaks something that we've done and we'll have to adapt our code before upgrading.

I can't guarantee that we'll always be on the latest version, but I can promise that we'll always be on a supported version, which we currently are.
