### ISSUE TITLE
[Bug]: Local API failing to get videos for most channels

### ISSUE THREAD

**Issue by simoniz0r** [FreeTubeApp/FreeTube#2165]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Set the `Preferred API Backend` to `Local API` in the general settings.
2. Refresh your subscriptions page or click on a subscribed channel in the sidebar.
3. Be bombarded with `TypeError: Cannot read properties of undefined (reading 'response')` and `Falling back to Invidious API` errors.

### Expected Behavior

Local API and Invidious API should both work for loading video information.

### Issue Labels

API issue

### FreeTube Version

v0.16.0 Beta

### Operating System Version

openSUSE Leap 15.3

### Installation Method (If applicable)

.AppImage

### Last Known Working FreeTube Version (If Any)

v0.16.0 Beta

### Primary API used

Local API

### Additional Information

Switching the preferred backend to the Invidious API seems to work, but I'd much rather use the local API as it's usually more reliable.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by VictoriousFan** [comment]
I am also getting this error, every time a channel is opened or subscriptions are refreshed.

Installation method:
* FlatPak 
* Latest nightly build (AMD64.deb)

This started happening (on both installations) just after opening the app on a fresh install, no configuration changes, even after deleting all related files and reinstalling.

Platform: Pop!_OS

**Comment by PrestonN** [comment]
We're aware of the issue and have made a fix for it [here](https://github.com/FreeTubeApp/yt-channel-info/pull/64). We'll get the app updated as soon as we can.

**Comment by PrestonN** [comment]
As a workaround until the next release, you can enable RSS feeds within your subscription settings and enable the Invidious API fallback so that you can still access channels / subscriptions.

**Comment by flyhippo** [comment]
I have had this problem for several months now, the latest version is very difficult, the number of errors has increased
Win7

**Comment by nowakommunikation** [comment]
Freetube seems to have a problem not recognizing the Invidious instance when the "https://" part of the address is missing. 

I noticed this since I've also had trouble getting videos during the past days and therefore changed the instance a few times. And every time I copied only the address without the https:// part, it still wouldn't load. When added, everything worked fine.

**Comment by ZeroDot1** [comment]
Unfortunately, I also have this problem.

**Comment by simoniz0r** [comment]
The latest nightly release (currently available [here](https://github.com/FreeTubeApp/FreeTube/actions/runs/2155505162) under artifacts) fixes this issue for me.

**Comment by KNAPPI23** [comment]
This The error still exists on v0.16.0-nightly-1567 Beta.No video starts and the Invidious API loads very slowly

**Comment by formlessdao** [comment]
I get the local api error 429 when importing my subscriptions. I have enabler RSS method as primary but I still see this errors.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> I get the Local Api Error 429 when importing my subscriptions. I have enabled RSS method as primary but I still see these errors.

Ur error is not related to this issue. See documentation for more information about 429 errors
https://docs.freetubeapp.io/usage/common-issues/#429-errors

**Comment by formlessdao** [comment]
> > I get the Local Api Error 429 when importing my subscriptions. I have enabled RSS method as primary but I still see these errors.
> 
> Ur error is not related to this issue. See documentation for more information about 429 errors https://docs.freetubeapp.io/usage/common-issues/#429-errors

That blog post does not talk at all about my own issue so I commented here.

**Comment by ChunkyProgrammer** [comment]
> > > I get the Local Api Error 429 when importing my subscriptions. I have enabled RSS method as primary but I still see these errors.
> > 
> > 
> > Ur error is not related to this issue. See documentation for more information about 429 errors https://docs.freetubeapp.io/usage/common-issues/#429-errors
> 
> That post you linked does not talk at all about my own issue.

Currently, a request to YT or Invidious is made for each subscription you have in order to get the subscription's avatar image so that is probably where this issue is coming from (lots of subscriptions). This won't need to happen when https://github.com/FreeTubeApp/FreeTube/pull/1783 gets merged

**Comment by ChunkyProgrammer** [comment]
original issue seems to be fixed so i will be closing this one
