### ISSUE TITLE
[Bug]: Can't create a string longer than xxx characters

### ISSUE THREAD

**Issue by TMS-Namespace** [FreeTubeApp/FreeTube#2171]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

It happens wherever  I start FreeTube, pressing on OK on the error message (see below screenshot), it continues to work fine, but all contents of my favorites (play list) is empty.
I think this happened because I added too many items to the play list, because for a long time everything was working fine, but lately this started to happen suddenly, and no app update took place within this period.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/40037422/162398239-ab184fe5-388f-482f-a437-f9b8d5b9e02b.png">

### Expected Behavior

No error should happen, and the play list should contain the items I chosen.

### Issue Labels

causes crash

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Win10, 21H1, 19043.1586

### Installation Method (If applicable)

Portable

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PrestonN** [comment]
Hey there! If it's alright with you, could you please send me your playlists file? You can use [this](https://docs.freetubeapp.io/usage/data-location/) article to know where it's located. Sending it to me at freetubeapp@protonmail.com or through Matrix would be best. I can take a look at it and see what needs to be done in order for it to be read properly.

**Comment by TMS-Namespace** [comment]
@PrestonN Hi, sorry I prefer to not send it for privacy concerns.
However, I am a programmer also, although in a different field/technologies from FreeTube uses, so maybe you can tell me what to look on, so I can check my self.
A quick look on the playlists.db file, that happens to be of un realistically large size (547MB!) and that as I understand is JSON-like formatted, I noticed that the same root element is being repeated many times (360 times exactly), along with all its contents, this seems to be incorrect...
I opened it in VSCode, removed the repeated lines, the file size become about 1.5Mb, and now FreeTube runs fine, and my old favorites are all in place.
Hence, you need to recheck your play list saving logic, something causes it to go into a loop of repeating same contents, particularly 360 times.

**Comment by PrestonN** [comment]
It's all good. I understand the concerns.

The playlist logically will likely be overhauled once I'm done with full user created playlists, so I'll take an extra look at that logic and make sure nothing is duplicating on accident.

Our DB can potentially show multiple entries when the app is running and would be as intended, but if they persist when the app is closed then that would obviously be an issue that needs looked at.

This admittedly might not get looked at right away and I'll save it for when I'm back to working on full playlists.

If you'd like to look a bit deeper yourself, the majority of the logic you're looking for will likely come from [these](https://github.com/FreeTubeApp/FreeTube/blob/development/src/renderer/store/modules/playlists.js) [three](https://github.com/FreeTubeApp/FreeTube/blob/development/src/datastores/handlers/electron.js) [files](https://github.com/FreeTubeApp/FreeTube/blob/development/src/main/index.js#L547=). The logic for starting the workflow will be [here](https://github.com/FreeTubeApp/FreeTube/blob/development/src/renderer/components/ft-list-video/ft-list-video.js#L236=). Feel free to let me know if you have any questions.

**Comment by cocoonkid** [comment]
Had the same happening to me.

Playlist was at nearly 700MB.  I restored last nights backup (at 300MB). ..

Then starred my favs from subs again, closed freetube. 
Reopened, now it's back at 2.3MB and works fine.

Will report back if it appears again. Really keen on knowing what triggers this.

**Comment by GlowingUmbreon** [comment]
I have a feeling that you should the exempt-issue-labels feature to stop the spam from this action. Having to re-open this ticket every month probably negates the benefit from having this feature.

https://github.com/actions/stale#exempt-issue-labels
```
exempt-issue-labels
Comma separated list of labels that can be assigned to issues to exclude them from being marked as stale (e.g: question,bug)

If unset (or an empty string), this option will not alter the stale workflow.

Default value: unset
```

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@GlowingUmbreon we are using this workflow only on bug reports, feature requests are exempted. Every month when a bug report gets stale we will evaluate if it is still unresolved. We have caught 100+ issues this way that could be closed and are still catching issues that are resolved but still open. This is how we use it to keep our issue tracker clean. I understand that it could be annoying for u to get an notification about this every month but this is a way of working is very efficient for us.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Does this still happen in the latest version of FT?
