### ISSUE TITLE
FreeTube for Raspberry Pi 3B + (armhf architecture)

### ISSUE THREAD

**Issue by Oleffa** [FreeTubeApp/FreeTube#218]
Hi,

first of all thank you so much for creating this software!

I would like to use FreeTube on my Raspberry Pi 3B + running Raspbian 9 (armhf architecture). The problem is the releases are for arm64, so they dont run. I also tried downloading the source code and building for armhf. But I am not familiar with JS applications and I couldn't figure out how to add a script to build for armhf (Is it even possible at all?).

Would it be possible to provide a release for the Raspberry Pi with armhf as well? If you could give me some pointers on how to start to do that I could look into that myself.

Best Regards!

**Comment by PrestonN** [comment]
I own a 3B+ that I can test with, but the basic idea is that I haven't been supporting 32 bit versions of FreeTube.  The 3B+ would be the only Pi that could have a chance of being supported as it is capable of running a 64 bit OS.  I'd love to support them if I can but I don't know if I'd have time to do so.

You're welcome to attempt to [setup a local environment](https://github.com/FreeTubeApp/FreeTube/blob/development/CONTRIBUTING.md#setting-up-your-environment) on the Pi to see how it runs though I cannot guarantee that I can support it.

**Comment by LeandroStanger** [comment]
Test the Flatpak version https://flathub.org/apps/details/io.freetubeapp.FreeTube

**Comment by LeandroStanger** [comment]
@Oleffa Test the Flatpak version https://flathub.org/apps/details/io.freetubeapp.FreeTube

**Comment by gkeegan** [comment]
I managed to get FreeTube working on my 3B+, but it was not an enjoyable experience, and videos would constantly just stop played. I believe I used Arch Linux to do it. It was a custom version I found somewhere.
