### ISSUE TITLE
[Bug]: Wayland broken update electron to fix it

### ISSUE THREAD

**Issue by BirdInFire** [FreeTubeApp/FreeTube#2190]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

When we try to launch on wayland it do not start

### Expected Behavior

Starting

### Issue Labels

visual bug

### FreeTube Version

0.16 beta

### Operating System Version

Linux

### Installation Method (If applicable)

Flathub

### Primary API used

Invidious API

### Additional Information

request to update electron to 17.3.1 (or the latest from the branche you use who have the wayland fix) who seem to have fixed the problem
See their change-log : https://github.com/electron/electron/releases/tag/v17.3.1

Note this very same bug was fixed by Signal by updating to the version of electron who contain the fix the branch 17 and 18 had their update to fix this problem.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Hi, the same thing happens to me but with Xorg, I am using electron 18.0.1-1

Are u on Arch?

**Comment by 9ekaitz** [comment]
> > Hi, the same thing happens to me but with Xorg, I am using electron 18.0.1-1
> 
> Are u on Arch?

yes btw

**Comment by 9ekaitz** [comment]
> > > > Hi, the same thing happens to me but with Xorg, I am using electron 18.0.1-1
> > > 
> > > 
> > > Are u on Arch?
> > 
> > 
> > yes btw
> 
> See this issue for more info on Arch #2163

Thank you!, it works know

**Comment by BirdInFire** [comment]
> > Hi, the same thing happens to me but with Xorg, I am using electron 18.0.1-1
> 
> Are u on Arch?

In my case it's a wayland problem (Xwayland work), just you must update electron to fix a bug in electron regarding starting with ozone=wayland.

Signal had the same problem, so updating electron in their end have fixed it.

**Comment by Smollejan** [comment]
Same problem for me on Fedora 36 using Wayland on a gtx 1060. Black screen on launch. Xorg is working fine.

**Comment by Aiz0** [comment]
Working on latest nightly build.
https://github.com/FreeTubeApp/FreeTube/pull/2448 updated electron and now `freetube --enable-features=UseOzonePlatform --ozone-platform=wayland` launches freetube under wayland without issue.
