### ISSUE TITLE
[Feature Request]: register uri scheme for opening videos on desktop/mobile

### ISSUE THREAD

**Issue by SethFalco** [FreeTubeApp/FreeTube#2191]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

If someone links me to a YouTube video, it opens in a new tab in my browser. Instead, I'd like this to be directed to the FreeTube application I have installed locally.

### Proposed Solution

I'd like to see a FreeTube adopt a URI scheme like `tube://`, so users can link to it, or browsers could redirect requests from YouTube to the FreeTube application.

Proposed links could be:
* `tube://search/{:query}` - To search for content.
* `tube://watch/{:videoId}` - To open a video.

### Alternatives Considered

N/A

### Issue Labels

support for external software

### Additional Information

From here, a browser extension could for example forward navigation requests from `youtube.com` or Invidious instances to FreeTube, making it much more seamless to use.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
i think ur looking for this https://docs.freetubeapp.io/usage/browser-extension/

**Comment by SethFalco** [comment]
Ahh shoot! You're correct, that's great!
Sorry for the noise then, I'll close this.
