### ISSUE TITLE
[Bug]: Closed Captions Text Not Appearing

### ISSUE THREAD

**Issue by VinTechage** [FreeTubeApp/FreeTube#2194]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

When I enable Closed Captions when using the "Invidious API", I don't see any text on the video screen as Closed Captions. I don't know why they are not appearing at all. I see no errors popping up when I change the Closed Captions settings.

### Expected Behavior

I expected text to appear on the video window when I switched on Closed Captions from "Off" to "English" 

### Issue Labels

content not loading, visual bug

### FreeTube Version

0.16.0.

### Operating System Version

EndeavourOS, Arch Linux, Linux Kernel 5.17

### Installation Method (If applicable)

other

### Primary API used

Invidious API

### Additional Information

I've tested this after switching to the "Local API", and it works.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is actually an invidious issue. If go to an instance and turn on invidious captions u'll also see that they are not working

**Comment by VitoItalianGamer** [comment]
I have the same issue too
