### ISSUE TITLE
[Bug]: Opening FreeTube from Privacy Redirect and LibRedirect extension creates a new empty tab

### ISSUE THREAD

**Issue by 0x6e656b6f** [FreeTubeApp/FreeTube#2196]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Click on Youtube link.
2. A new empty tab and a FreeTube window opens.

### Expected Behavior

Clicking a Youtube link should only spawn a Freetube window.

### Issue Labels

usability issue

### FreeTube Version

v0.16.0

### Operating System Version

Fedora Workstation 35

### Installation Method (If applicable)

Flathub

### Primary API used

Local API

### Additional Information

Web browser version: Librewolf 99.0
Privacy Redirect version: 1.1.49
LibRedirect version: 1.6.3

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
FreeTube can't control your browser tabs, please report that issue to the maintainers of the extensions.
