### ISSUE TITLE
Remove Most Popular and Trending

### ISSUE THREAD

**Issue by tiotrom** [FreeTubeApp/FreeTube#220]
Would be great if those could be de-activated just for the user freedom kind of purpose :)

**Comment by PrestonN** [comment]
Maybe these could be added to a possible Distraction Free mode like mentioned in #209?  Curious on anyone's thoughts.

**Comment by tiotrom** [comment]
To me it sounds great! Maybe a simply opt-out in settings for such things?

**Comment by PrestonN** [comment]
Closing as this has been implemented and will be included in the next release.
