### ISSUE TITLE
[Bug]: Channel avatar on sidebar fails to load

### ISSUE THREAD

**Issue by 0x6e656b6f** [FreeTubeApp/FreeTube#2204]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Out of 56 channel, 4 channel avatar fails to load. Restarting FreeTube don't fix it. Changing API to Invidious also don't fix it.

### Expected Behavior

Channel avatar image should load properly.

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.16.0

### Operating System Version

Fedora 35 Workstation

### Installation Method (If applicable)

Flathub

### Primary API used

Local API

### Nightly Build

- [x] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @0x6e656b6f could u try out [the latest nightly build](https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml) and see if this error is still occurs.

**Comment by 0x6e656b6f** [comment]
I tried looking for a nightly flatpak build but it seems like there's none. Am I missing something?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
No ur not i just noticed that one channel in my application is also not loaded

**Comment by 0x6e656b6f** [comment]
Should we create a new issue?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> I tried looking for a nightly flatpak build but it seems like there's none. Am I missing something?

Im sorry i misread this completely u have to download the artifact that is compatible for ur OS

**Comment by 0x6e656b6f** [comment]
> > I tried looking for a nightly flatpak build but it seems like there's none. Am I missing something?
> 
> Im sorry i misread this completely u have to download the artifact that is compatible for ur OS
> 
> Edit: this issue is still valid because [this channel](https://www.youtube.com/channel/UCxvjGipATx7lJHhzfCEERSA) icon does not load in the sidebar. With both the local and invidious api

I don't think it's a channel specific bug. It seems like the API failed to get the image randomly.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Do u get an api error?

**Comment by 0x6e656b6f** [comment]
> Do u get an api error?

Nope.

**Comment by hockerschwan** [comment]
My guess is that url saved in profile is old. What if you unsubscribe and subscribe those channels?

**Comment by 0x6e656b6f** [comment]
> My guess is that url saved in profile is old. What if you unsubscribe and subscribe those channels?

Thanks, that worked. I'm not closing this issue however since it's a workaround and not a proper fix.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I can confirm that https://github.com/FreeTubeApp/FreeTube/pull/1783 fixed this issue.
