### ISSUE TITLE
Remove from Favourites

### ISSUE THREAD

**Issue by tiotrom** [FreeTubeApp/FreeTube#221]
There is no button to remove a video from favourites. I also think it is a good idea to add a watch later feature. Thanks!

**Comment by PrestonN** [comment]
Hey there.  You can remove a video from favorites by clicking on the icon in the corner on the video thumbnail.

I would consider "Favorites" and "Watch later" as the same thing.  Is there a good enough reason as to why these should be 2 separate options?

**Comment by tiotrom** [comment]
Ah ok. Maybe it is better to have like an "X" button to remove. I didn't realize if I click the same button it removes, especially because if I click it it doesn't remove right away, You have to click another tab then favourites again to see them disappear. 

Favorites vs Watch Later: If I favorite a video I maybe want to show it to someone else or keep it fir certain reasons (say I write a book and I need to "bookmark" some videos for it, or whatever). And I would add videos to Watch Later to watch later and then delete. Disposable items. That's how I think people use the Watch Later on youtube vs the "add to playlists" on youtube.
