### ISSUE TITLE
[Bug]: [MacOS] When Freetube is playing and the user switches Desktops Freetube is "duplicated" to all empty  Desktops.

### ISSUE THREAD

**Issue by cocoonkid** [FreeTubeApp/FreeTube#2216]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

[Bug]: When Freetube is playing and the user switches Desktops Freetube is "duplicated" to all empty  Desktops.

0. Create a few empty Desktops via Mission Control. There can be desktops with running apps in between the empty ones.
1. Open Freetube in normal (window mode but expanded to nearly fullscreen). Bug does not happen in Fullscreeen.
2. Play any video in normal mode (Bug does not happen in Fullscreen).
3. Switch Desktops via hotkey or swipe gesture.
4. See how Freetube gets mirrored on the empty desktops.

### Expected Behavior

Freetube in normal window mode (but expanded to Full Size NOT Full Screen) does NOT mirror to any other desktops but lives only on its designated desktop like any other macos application.

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

Version 0.16.0-nightly-1553 

### Operating System Version

Macos Monterey 12.3.1 arm (but happens on x86 as well)

### Installation Method (If applicable)

.dmg

### Last Known Working FreeTube Version (If Any)

bug exists for 2 years at least. Just did not report it yet :-)

### Primary API used

Invidious API

### Additional Information

The issue is pretty weird and possibly dangerous.

People got get seizures or motion sickness. 

I might be exaggerating but I as a healthy person get slowly triggerd whenever this happens. It is very unexpected and annoying.  

I'd like to know what others think after reproducing this issue.

Thanks to the developers for this amazing tool! 

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PikachuEXE is it possible to reproduce it?

**Comment by PikachuEXE** [comment]
Running 0.17.1 locally ( via`yarn dev`)
I am unable to reproduce
MacOS 12.1

https://user-images.githubusercontent.com/1018543/185562662-c5c329a7-2365-484e-a6d9-c350ddf47477.mov

**Comment by PikachuEXE** [comment]
Please try to update FreeTrue and/or MacOS version if available and try again
I will update my MacOS soon and try again

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@cocoonkid try the suggested above and report back please.
