### ISSUE TITLE
[Bug]: Middle click causes choppy scrolling

### ISSUE THREAD

**Issue by 0x6e656b6f** [FreeTubeApp/FreeTube#2217]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Steps to reproduce:
1. Open Freetube.
2. Middle click anywhere.
3. Try scrolling (if middle click spawns a new window, go back to the original window then scroll).

### Expected Behavior

Scrolling should not be choppy.

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.16.0

### Operating System Version

Fedora 36 Workstation

### Installation Method (If applicable)

Flathub

### Additional Information

This might be unrelated but this issue doesn't happen prior upgrading to Fedora 36 Beta.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@0x6e656b6f are u still facing this issue?

**Comment by 0x6e656b6f** [comment]
Nope.
