### ISSUE TITLE
[Bug]: Font and UI Resolution on mobile low

### ISSUE THREAD

**Issue by CaptainMorgan12** [FreeTubeApp/FreeTube#2218]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Environment: freetube flatpak, 0.17.0-1pureos1, mobile portrait, 720x1440, Librem 5 phone using Gnome GTK base.

![Screenshot from 2022-04-23 11-55-33](https://user-images.githubusercontent.com/80182265/164946168-b1651d6d-0dac-46ae-ad71-53afa44f720d.png)

Observe Subscriptions font is fuzzy.

### Expected Behavior

Font and UI rendered maybe more based on GTK presets or libadwaita.

### Issue Labels

visual bug

### FreeTube Version

0.16.0 beta

### Operating System Version

PureOS

### Installation Method (If applicable)

Flathub

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ScanuNicco** [comment]
I can confirm that my PinePhone Pro running Arch Linux with Plasma Mobile is also affected by this issue. It seems to me that this is a problem related to the 200% system-wide UI scale used by default in Plasma Mobile (and probably PureOS).
![Screenshot_20220726_133132](https://user-images.githubusercontent.com/30136040/181107543-dcf80b8d-f4bc-47a0-963e-935a0e827973.png)
Setting the system UI scale to 100% and setting the FreeTube UI scale to 200% causes FreeTube to display properly scaled content at full resolution.
![Screenshot_20220726_140046](https://user-images.githubusercontent.com/30136040/181111631-7100b641-e2d8-489f-9ef4-20e6e0fffbab.png)
As pointed out in [electron/electron#6571](https://github.com/electron/electron/issues/6571), it may be possible to force a 100% scale by placing the following lines in the main process:
```js
app.commandLine.appendSwitch('high-dpi-support', 1)
app.commandLine.appendSwitch('force-device-scale-factor', 1)
```

**Comment by 1peter10** [comment]
AFAIK is not a FreeTube bug, it's due to xwayland being used and xwayland making things fuzzy at 2x. This should be solvable by setting flags for chromium/electron, maybe this AUR buld can help with figuring out a flatpak implementation for avoiding xwayland: https://aur.archlinux.org/packages/freetube-wayland

**Comment by ScanuNicco** [comment]
Yeah I recently got a new laptop and discovered that blurry apps are just a normal thing on xwayland. Turns out that Plasma desktop 5.26 is going to fix this by adding an "allow apps to scale themselves" option in display settings, so we'll see if that makes it onto plasma mobile.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Do you guys think that this can be closed?

**Comment by ScanuNicco** [comment]
While it still might be worth implementing a workaround it seems like the root problem with this is not freetube, so yeah probably.
