### ISSUE TITLE
[Bug]: Cannot Import Subscriptions, Getting "Error: Request failed with status code 404"

### ISSUE THREAD

**Issue by GameGuyOnYT** [FreeTubeApp/FreeTube#2219]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Go to Data Settings
2. Import [this](https://github.com/FreeTubeApp/FreeTube/files/8550156/abonelikler.csv) subscription .csv file
3. Get "Error: Request failed with status code 404"

### Expected Behavior

I expected that the subscriptions would **be in the app** after I imported them.

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Windows 11 Pro version 21H2

### Last Known Working FreeTube Version (If Any)

None

### Primary API used

Local API

### Additional Information

https://user-images.githubusercontent.com/81768350/164988863-f9729bf2-407a-4ccd-9d44-891c05092c9c.mp4

This is a video of me showcasing the bug.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Lau-San** [comment]
I'm getting the exact same error here on Linux Mint 20.3

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi there have u tried to troubleshoot this issue like its described on https://docs.freetubeapp.io/usage/importing-subscriptions/#troubleshooting-issues

**Comment by ChunkyProgrammer** [comment]
This issue is caused by one of the channels they're subscribed to having commas in their name.

> hi there have u tried to troubleshoot this issue like its described on https://docs.freetubeapp.io/usage/importing-subscriptions/#troubleshooting-issues
