### ISSUE TITLE
Very slow loading the subscriptions

### ISSUE THREAD

**Issue by tiotrom** [FreeTubeApp/FreeTube#222]
I have like 40-50 subscriptions and I see it takes quite a long time (30s to a minute) to load the subscription page. Is that normal? My internet is super fast btw

**Comment by PrestonN** [comment]
This should be addressed in the next release.  @omarroth made a new end point with Invidious which should speed up the current process of grabbing subscriptions.  The issue right now is that the API is grabbing the 60 latest videos from each channel to sort by the time they were released.  This number is way too high for our usage and the new end point lowers this number to 15.  This change alone should speed up subscriptions quite a bit.

**Comment by PrestonN** [comment]
The fix has been made and will be included in the next release.  Subscriptions load a bit faster now but more testing needs to be done to know exactly how much faster.
