### ISSUE TITLE
Second screen issue: new instances open in original screen

### ISSUE THREAD

**Issue by nowakommunikation** [FreeTubeApp/FreeTube#2240]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

On macos (here: 10.13.6), when you open a new instance by cmd-clicking a video, the new window opens up on the original/ first screen screen rather than over the first instance of the program on the attached/second screen.

### Expected Behavior

A new instance should open over the first instance like with web browsers.

### Issue Labels

usability issue

### FreeTube Version

0.16.0 beta

### Operating System Version

macOS 10.13.6

### Additional Information

First of all: great program! 

I use version 0.16.0 beta on macos 10.13.6 and usually push the window to an attached screen (MacBook Pro) or a second screen (MacMini). 
When I cmd-click (Apple-click) a video to open the video in a second instance of FreeTube (in order to preserve search results on the first instance), the new window opens on the main screen rather than over the first instance on the second screen. (Does this make sense to readers?)

I've tried this on a MacBook Pro with an attached monitor and a Mac Mini with two monitors. Also on the Mac Mini, the new instance opens up on the original screen. 

When I make the external/second screen the main screen by dragging the Taskbar to that screen (in Settings menu) THEN the new instance also opens on the external/second screen and over the first instance. 

I've looked for settings in preferences that might control this, but there's nothing. 
Now, I'm not sure if this is a feature or a bug, but imho the new window should open above the original window, like it does with regular browsers. 

Correct me if I'm wrong.

Have a great weekend.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing, converted to a feature request in #4154 because this isnt a bug
