### ISSUE TITLE
[Feature Request]: Convert `/channel/ID` links to `@User` links

### ISSUE THREAD

**Issue by Winterhuman** [FreeTubeApp/FreeTube#2241]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

(See https://github.com/FreeTubeApp/FreeTube/issues/2232)

Some Invidious instances don't show links to users in the form `@User`, but instead show them as `/channel/ID`. This means user links in comments can appear different depending on the Invidious instance configured for FreeTube's Invidious API.

### Proposed Solution

If `/channel/ID` links appear in comments, FreeTube could convert these links into `@User` links and display them instead. This means all Invidious instances would be visually consistent with each other regardless of whether they display `@User` or `/channel/ID` originally.

### Alternatives Considered

Not converting to `@User` links. `/channel/ID` links are probably a feature of old versions of Invidious, this issue might just solve itself as instances update over time.

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
i dont see how this is our problem to fix. I would recommend pointing this out at the maintainer of that instance
