### ISSUE TITLE
Login with Invidious account

### ISSUE THREAD

**Issue by cmalvi** [FreeTubeApp/FreeTube#2246]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Seems there’s no cloud / local sync option, with desktop pc copy related file is the only way to keep FreeTube synced between Pc. However, I’m starting using Yattee on my iOS device and I realised that I can’t sync my subs/history with FreeTube installation because FreeTube doesn’t allow to fetch user data from invidious.

### Proposed Solution

Add the possibility to use invidious account, maybe adding it using the cookie string like on Yattee

### Alternatives Considered

Login with username and password

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1896

**Comment by cmalvi** [comment]
> basically a duplicate of #1896

Also the missing reply is a duplicate, thank you

**Comment by dderg** [comment]
the linked "duplicate" talks about http auth, and this one is talking about invidious account to sync subscriptions, what am I missing here? doesn't seem like a duplicate to me

**Comment by TheInfamousAlk** [comment]
This doesn't look to be a duplicate.

**Comment by dderg** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Please reopen as this is not a duplicate

**Comment by CloisteredCaiman** [comment]
This is definitely NOT a duplicate of #1896. I also use basic auth to access my invidious instance thanks to #1896... however I cant login to my actual invidious account, that would be useful to access my watch history and subscriptions
