### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#2248]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Subscribe to https://youtube.com/channel/UCjr2bPAyPV7t35MvcgT3W8Q and https://youtube.com/channel/UCueOZEvMffxjJyVO1fGiJNQ so u have them listed in the sidebar for convenience. 
2. Click in the sidebar on the channel icon from 'the hated one' and u'll see that everything works fine. 
3. Go to the other channel u subscribed to and see ```TypeError: Cannot read properties of null (reading '1')``` also notice that the channel icon and banner from the other channel is still visible instead of the channel u just navigated to (this is actually the same behavior as https://github.com/FreeTubeApp/FreeTube/issues/1545 but im unable to reproduce that one).

### Expected Behavior

Local api does not fail and correct channel icon and banner are displayed.

### Issue Labels

API issue

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/fa7fb33cda4348a7cd3ebd332b4ee5a813304588

### Operating System Version

Win10 21H1

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

Edit: I'm able to reproduce https://github.com/FreeTubeApp/FreeTube/issues/1545

**Comment by ChunkyProgrammer** [comment]
Might be fixed by https://github.com/FreeTubeApp/yt-channel-info/pull/78
