### ISSUE TITLE
[Bug]: YouTube is doing some A/B tests that will likely break FreeTube in the near future

### ISSUE THREAD

**Issue by absidue** [FreeTubeApp/FreeTube#2251]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

YouTube is currently doing some very unpopuler A/B tests, due to those changes FreeTube will likely break once they are fully implemented. As we have learnt in the past the less popular a change is, the higher the chance is that YouTube will make it permanent. At this point I'm starting to question the sanity of the people working at YouTube.

Here are the ones that will likely affect FreeTube:
1. video lengths are being removed from thumbnails (this is probably a dark pattern with the goal to increase overall watchtime on the platform) [reddit post on r/youtube](https://old.reddit.com/r/youtube/comments/us3gct/video_lengths_have_just_been_removed_from_the/)
2. removing sorting by oldest on channels [reddit post on r/youtube](https://old.reddit.com/r/youtube/comments/uqyevv/youtube_made_it_so_you_cant_sort_by_oldest_anymore/)
3. Watch page redesign [reddit post on r/youtube](https://old.reddit.com/r/youtube/comments/uof13c/what_the_hell_is_this_layout_my_eyes_are_burning/)
4. Removing the likes from under the video, presumably a continuation of their fever dream where they thought that removing the dislikes was a good idea [reddit post on r/youtube](https://www.reddit.com/r/youtube/comments/udmn8v/are_they_removing_likes_now/)

Personally I haven't seen FreeTube breaking because of those changes just yet, but it's just a matter of time so I thought I would create this issue to let everyone know early.

### Expected Behavior

n/a

### Issue Labels

race condition

### FreeTube Version

all of them

### Operating System Version

all of them

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
How nice of them... -.-

Thanks for the info though

**Comment by ChunkyProgrammer** [comment]
Interesting. I'll add any other potential changes to this comment.

YT might be adding reactions (might replace likes): https://old.reddit.com/r/youtube/comments/us92v8/weird_reaction_emojis_in_comments_what_are_they/ 
https://old.reddit.com/r/youtube/comments/urig1u/what_is_this_button/

**Comment by absidue** [comment]
As there hasn't been a FreeTube release in a long time, the last one was on the 7th of February, would it make sense to release an update so the current big issues in 0.16.0 are fixed? Or would it make sense to wait even longer and hope that YouTube decideds if they are going to implement these changes soon?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We actually want to do a release for a while now but every time something breaks and holds us back from releasing :(

**Comment by absidue** [comment]
Looks like they all just need reviewing, which I can't help with. I can take a look at #1442 though.

**Comment by PrestonN** [comment]
@absidue we were actually curious if you would be interested in becoming an approved reviewer / contributor to the project? Your reviews would then be counted towards the approved reviews needed from our rules in order to get PRs merged quicker.

Send me a message on [Matrix](https://matrix.to/#/+freetube:matrix.org) if you're interested and I can invite you to our dev channel. There's also some documents that I can share with you to get you up to speed on how we try to do things

**Comment by arrowgent** [comment]
curious how youtube's design effects invidious

freetube gets its information from invidious, not directly from youtube (in some cases)


of course im on the side: most of these youtube changes are not good...

**Comment by absidue** [comment]
@arrowgent Invidious scrapes YouTube's website just like the local API does in FreeTube, so design changes on YouTube's side will break both Invidious and FreeTube's local API.

FreeTube only gets it's information from an Invidious instance if that's what you set it to, the default setting is the local API (it's usally quicker and you aren't at the mercy of broken and slow Invidious instances and the ratelimits on their side).

**Comment by absidue** [comment]
Closing this as the changes didn't come as soon as I expected them too.
