### ISSUE TITLE
[Feature Request]: Grab Videos from other Platforms

### ISSUE THREAD

**Issue by Ch1p4** [FreeTubeApp/FreeTube#2256]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There's an increasing number of content creators using other platforms, due to Youtube guidelines.

### Proposed Solution

Freetube could also grab videos from other platforms.

### Alternatives Considered

This is just an idea for a potencial new feature that would make the freetube app more versatile.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
That isnt something we want to do.
https://docs.freetubeapp.io/faq/#will-you-consider-adding-support-for-services-outside-of-youtube-twitch-soundcloud-peertube-etc
