### ISSUE TITLE
[Feature Request]: play/watch queue

### ISSUE THREAD

**Issue by makerio90** [FreeTubeApp/FreeTube#2258]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

whenever i'm watching a video, i often see multiple videos worth watching.

### Proposed Solution

add a queue that would allow me to queue up multiple videos.

### Alternatives Considered

- creating a playlist that i add and delete from
    - inconvenient, it should auto remove items once you've watched them.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/519
