### ISSUE TITLE
[Feature Request]: add padding to menu button on title bar

### ISSUE THREAD

**Issue by skrshe** [FreeTubeApp/FreeTube#2264]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

the menu icon in the top bar looks jank

### Proposed Solution

add padding to the left of the menu icon

### Alternatives Considered

none

### Issue Labels

visual improvement

### Additional Information

currently:
![ft-spacing-issue](https://user-images.githubusercontent.com/40524589/170024470-72c3a8c9-3d03-43fb-ab6d-192855597301.png)
proposed:
![ft-spacing-fix](https://user-images.githubusercontent.com/40524589/170024461-7cd95e97-d472-4b40-904c-433d3ba51111.png)

**Comment by vallode** [comment]
#2280 tackles this to an extent. I want to open a PR/discussion about the side navigation in general because I think having the "burger" button be separate from the sidebar is not a good experience.
