### ISSUE TITLE
[Bug]: Many API errors

### ISSUE THREAD

**Issue by MaiaDereva** [FreeTubeApp/FreeTube#2265]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

I see this message in all videos: 
`TypeError: Cannot read properties of undefined (reading 'baseUrl')`

I tried to change API Backend, Invidious source, RSS,... but I always have the same issue.

### Expected Behavior

No error

### Issue Labels

API issue

### FreeTube Version

v0.16.0 Bêta

### Operating System Version

Linux 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Installation Method (If applicable)

.zip

### Primary API used

Local API

### Additional Information

![freetube-API-errors](https://user-images.githubusercontent.com/17183356/170071887-e4137d7a-18e5-48f9-814f-62c78cca014b.png)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is too little info for us. Could u provide a few videos where this is happening for u. I cant reproduce.

**Comment by MaiaDereva** [comment]
Hi, thank you for your answer. It's happening with every videos...
I can pick some of them as examples:
inv.bp.projectsegfau.lt/watch?v=rklJCVvRieA
inv.bp.projectsegfau.lt/watch?v=PqyOi1TqZNM
inv.bp.projectsegfau.lt/watch?v=lAZAcyPxbUc
inv.bp.projectsegfau.lt/watch?v=x0AnMT9RXfU
inv.bp.projectsegfau.lt/watch?v=1uBfJX0BT8s

After a while, error disappears, and I can normally watch most of the videos.

**Comment by MaiaDereva** [comment]
It happened after I installed v0.16.0 Bêta when it was released.
It never happened before, with the oldest version but I can't remember its number of version (just the version before, I didn't use Freetube before that).
I thought it will be fixed but it's not so I prefer reporting the issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
- Could u try out other Invidious instances.
- If that doesnt work. Could u try out [the latest nightly build](https://github.com/FreeTubeApp/FreeTube/actions/runs/2377416867) and report back.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> - I downloaded the latest nightly build but as I'm not an advanced Linux user, I don't know where to put these files... Can you help me?

As far as im aware u will get a zip file. U got to unpack the zip file and in the zip is an executable. Then u just need to run the executable.

**Comment by MaiaDereva** [comment]
I launched it a second time, I don't see the above HTML message anymore. But always the API errors.

**Comment by hockerschwan** [comment]
invidious.kavin.rocks doesn't work anymore #2236
Would you select instance from https://api.invidious.io near your location (make sure it works on browser), set it default and see what happens ?

**Comment by MaiaDereva** [comment]
![freetube-API-errors2](https://user-images.githubusercontent.com/17183356/170089522-d8876df2-4fbd-4b22-81ef-137d23fde05e.png)

**Comment by hockerschwan** [comment]
Did reproduce this on ubuntu 20.04.

TypeError: Cannot read properties of undefined (reading 'baseUrl')
    at eval ([Watch.js?5b49:425](https://github.com/FreeTubeApp/FreeTube/blob/a5585afa18314cd4757b4a63a47c21cb3a9afc02/src/renderer/views/Watch/Watch.js#L425))
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96)

1. Set API to Local
2. Set Language to anything but English (US, UK or System)
3. Watch any video with caption and receive error.
 With caption: https://vid.puffyan.us/watch?v=PqyOi1TqZNM
 Without caption: https://vid.puffyan.us/watch?v=F_tlGJLXwSI
<img src="https://user-images.githubusercontent.com/80553357/170199023-a4081028-dbc1-4ad7-8eae-af63664c34bb.png" width=300>

**Comment by MaiaDereva** [comment]
Right! If I choose English (US or UK), everything's fine.
If I choose System (which is French here), the errors appear.
