### ISSUE TITLE
[Bug]: Libva error in freetube 0.16.0 on fedora 36 causes black window, maybe nvidia proprietary driver's fault ?

### ISSUE THREAD

**Issue by TracerK** [FreeTubeApp/FreeTube#2269]
### Guidelines

- [x] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

When launched, via rpm, flatpak or even appimage on fedora 36 and with nvidia 510 drivers, the application output just a black screen, and the following error : `libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
`
![Capture d’écran du 2022-05-25 18-23-03](https://user-images.githubusercontent.com/106265547/170316313-5d3b7194-3212-4a01-aace-80ff042ad210.png)

### Expected Behavior

Normal launch of the application

### Issue Labels

causes crash, visual bug

### FreeTube Version

v0.16.0

### Operating System Version

Fedora 36

### Additional Information

Infos:
OS: Fedora Linux **36** (Workstation Edition) (64 bits)
Linux Kernel Version: **5.17.9**
GNOME Version: **42.1**
Window system: Wayland
Nvidia Driver: **510.68.02** (obtained via akmod-nvidia package)
GPU : Geforce GTX **1650**
Freetube Version: **0.16.0**

Additional notes:
So my guess is that the nvidia proprietary drivers are not supported by Freetube and that installing the nouveau drivers would certainly fix the problem. But I want to stick with the proprietary drivers on Fedora for now. And I have searched for any other similar issues on this github, and on other websites, but I could not find anything like my problem. So I thought that I should report that. Voilà :)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Could you please try the [latest nightly build](https://github.com/FreeTubeApp/FreeTube/actions/runs/2394263907) and see if your issue still exists on that build?

**Comment by TracerK** [comment]
> Could you please try the [latest nightly build](https://github.com/FreeTubeApp/FreeTube/actions/runs/2394263907) and see if your issue still exists on that build?

It does'nt. Same error and same visual bug again

**Comment by absidue** [comment]
I suspect this issue will be solved when the issue in https://github.com/FreeTubeApp/FreeTube/issues/2190 is solved (updating the electron dependency and fixing problems caused by updating it).

**Comment by FGYada1984** [comment]
OS: Nobara Linux 36 (Thirty Six) x86_64 
Kernel: 5.18.13-201.fsync.fc36.x86_64 
DE: GNOME 42.3.1 
CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz 
GPU: NVIDIA GeForce RTX 2070 SUPER 

just to contribute to the registry and offer to test some possible solution, the same is happening here in wayland, it works normally in xorg.

**Comment by DanaHolt** [comment]
If you are running Wayland with Nvidia drivers then installing these will probably fix the black window issue (works for me):
```
dnf install qt qt5-qtbase qt-devel
```

**Comment by pm4rcin** [comment]
I'm on wlroots and when I did run it through flatpak with `--no-sandbox` option it worked. Note that --no-sandbox is an electron and not flatpak option so it doesn't break flatpak sandboxing.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://youtu.be/v2H4l9RpkwM

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is this still an issue on [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)?

**Comment by pm4rcin** [comment]
> Is this still an issue on [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)?

I've tried the freetube-git from AUR and it kinda works but not the first time. I think the second time I've launched it worked but it has a chance of going black window when you select video format that it doesn't "like". For example the hdr video it goes black screen or even if you select a bad entry in quality options. So it's not really "stable" Wayland although when it works it's great. Of course I've used `--ozone-platform-hint=auto` since this flag is supported from Electron20.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> > Is this still an issue on [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)?
> 
> I've tried the freetube-git from AUR and it kinda works but not the first time. I think the second time I've launched it worked but it has a chance of going black window when you select video format that it doesn't "like". For example the hdr video it goes black screen or even if you select a bad entry in quality options. So it's not really "stable" Wayland although when it works it's great. Of course I've used `--ozone-platform-hint=auto` since this flag is supported from Electron20.

I dont understand. I linked to our nightly builds and u responded with a message related to AUR. AUR is not maintained by us the nightly builds are.

**Comment by pm4rcin** [comment]
> > > Is this still an issue on [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)?
> > 
> > 
> > I've tried the freetube-git from AUR and it kinda works but not the first time. I think the second time I've launched it worked but it has a chance of going black window when you select video format that it doesn't "like". For example the hdr video it goes black screen or even if you select a bad entry in quality options. So it's not really "stable" Wayland although when it works it's great. Of course I've used `--ozone-platform-hint=auto` since this flag is supported from Electron20.
> 
> I dont understand. I linked to our nightly builds and u responded with a message related to AUR. AUR is not maintained by us the nightly builds are.

You're right, sorry I thought it's essentially the same. I have downloaded [this one](https://github.com/FreeTubeApp/FreeTube/suites/8621870998/artifacts/387058420) and from my testing with the same flag it just works. It may take a moment to load the app but looks like everything is just fine. :)

**Comment by pm4rcin** [comment]
Also the newest nvidia driver has fixed the issue on current stable so you can easily run the flatpak without --no-sandbox option.

**Comment by Parkourist** [comment]
> @Parkourist did you install the same package that I linked from github?

No I currently have 0.17.1 not 0.16.0 but I'm sure it happened back then too as I've had this for ages now.

**Comment by absidue** [comment]
@Parkourist Only the nightly builds currently have proper Wayland support because they use electron 21.
