### ISSUE TITLE
[Bug]: Freetube command not working with firedragon browser

### ISSUE THREAD

**Issue by Arndorferd** [FreeTubeApp/FreeTube#2272]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

freetube:// command opens freetube but does not play the subsequent youtube video in firedragon browser but works in librewolf the browser its forked from, added a [request ](https://github.com/dr460nf1r3/firedragon-browser/issues/33) on firedragons repository as well.

### Expected Behavior

expected to redirect youtube video to freetube and play video, it doesnt play the video only opens freetube

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.16.0 Beta

### Operating System Version

5.17.7-xanmod1-MANJARO

### Installation Method (If applicable)

other

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Confirmed by the dev of the browser that this is a bug on their end.
