### ISSUE TITLE
[Feature Request]: Add option to add a video to a specific profile (playlist)

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#2274]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

As of now there does not seem to be a good and intuitive way to sort videos.

### Proposed Solution

This would be an intermediate solution instead/before (of) implementing tags for the video playlist (#25).

The idea is that you can add a video to a specific profile (e.g. a profile named "music") and then the video will be shown in the playlist of this profile.

### Alternatives Considered

See #25.

### Issue Labels

new feature

### Additional Information

I think that #1996 has to be implemented first.

**Comment by arrowgent** [comment]
there already is a way to do this

all subscriptions go to the main profile

1) you can add them to other profile in settings.  this wont remove it from the main profile
2) click on the profile top right then click subscribe.  now its in both main & the new profile

i have 15 profiles setup to categorize over 800 subscriptions

**Comment by toby63** [comment]
@arrowgent My request is about playlists, not about subscriptions.
Nonetheless you could be right, but #1996 needs to be implemented first, because right now there seem to be kind of shared playlists among profiles, instead of seperate playlists.

Still my request would be to have a button for it, instead of always manually having to change the profile, then click subscribe etc.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@minhhang107 do you maybe have something in mind to make this easier?

**Comment by BarbzYHOOL** [comment]
This is so needed

I am subscribed to like 40 channels and it's becoming extremely hard to filter the new videos :(

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Implementation of #1996 should solve this therefore im closing this
