### ISSUE TITLE
Bug: History thumbnail not loading on Windows

### ISSUE THREAD

**Issue by SamuelMiller** [FreeTubeApp/FreeTube#228]
On Windows 10, video thumbnails not loading in History view, . Instead, a broken image icon is displayed. Interestingly. Favorite view does work, but not History.

**Comment by PrestonN** [comment]
Hey there.  I took a look into this and it looks like this is an issue over at the Invidious end.  Invidious is returning an invalid URL which FreeTube cannot read.  When the fix has been made on the Invidious side, then it will be fixed for FreeTube without the need of an update.  Any current video in history that has the issue will not be fixed, but future videos in your history will.

You can keep track of [this](https://github.com/omarroth/invidious/issues/406) issue to know when it is fixed.
