### ISSUE TITLE
[Bug]: Featured Channels names are being cut off

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#2291]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Go to https://youtube.com/channel/UCm9K6rby98W8JigLoZOh6FQ
2. Go to the About tab
3. Scroll down to the Featured Channels
4. See channel names being cut off

### Expected Behavior

Channel names are not being cut off

### Issue Labels

text/string issue, visual bug

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/fd46b22f9191bbfa6527a630226f691725c70f08

### Operating System Version

Win10 21H2

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by vallode** [comment]
Note for future, Youtube's logic will simply remove words from the channel name until a single word can either fit or is long enough to be cut off by ellipsis. So I guess we can just add ellipsis to these.

![image](https://user-images.githubusercontent.com/18506096/172043343-d2e9aeee-31f9-48a2-aee0-e4e2602c5002.png)
