### ISSUE TITLE
Freetube changing default app to open .html files

### ISSUE THREAD

**Issue by Dry4233** [FreeTubeApp/FreeTube#230]
Hi,
Upon opening **Freetube**, the default app to open **.html** files becomes **Freetube**
_Before_
    https://i.imgur.com/PUkIjGT.png
_After_(opening FreeTube)
    https://i.imgur.com/LZNsZYz.png

Running linuxmint
`NAME="Linux Mint"
VERSION="19 (Tara)"
ID=linuxmint
IDNAME="Linux Mint"
VERSION="19 (Tara)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19"
VERSION_ID="19"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tara
UBUNTU_CODENAME=bionic
_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19"
VERSION_ID="19"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tara
UBUNTU_CODENAME=bionic
`

**Comment by Fzorkas** [comment]
Just wanted to second this issue. The FreeTube app is currently overriding the defaults to open HTML files whenever FreeTube starts up.

Also running Linux Mint 19.

**Comment by PrestonN** [comment]
Should be fixed with the latest release.  Please re-open this issue if the problem still exists.

**Comment by YoannPa** [comment]
I would like to reopen this issue, as I am encountering the same issue under Ubuntu 22.04, Freetube version v0.24.1
Could someone please reopen it I don't have the permissions for that?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@YoannPa this is fixed and will be included in the upcoming release, see https://github.com/FreeTubeApp/FreeTube/issues/8935#issuecomment-4600284808
