### ISSUE TITLE
[Bug]: API error on importing subscriptions

### ISSUE THREAD

**Issue by petyadev1** [FreeTubeApp/FreeTube#2307]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Go to settings
2. Scroll down to Data Settings
3. Click Import Subscriptions
4. Click NewPipe or YouTube 
5. Select file
6. Error: - API error: This account has been terminated for violating Google's Terms of Service.

### Expected Behavior

It should import the subscriptions

### Issue Labels

API issue

### FreeTube Version

v0.16.0

### Operating System Version

Windows 11

### Installation Method (If applicable)

.exe

### Primary API used

Local API

### Additional Information

https://user-images.githubusercontent.com/80815822/173235197-75a245d2-3089-4d1a-b434-3da5a5152065.mp4

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Are u sure u have received this error on the latest nightly build?

https://github.com/FreeTubeApp/FreeTube/actions/runs/2480241086

**Comment by petyadev1** [comment]
I don't know what nightly build means, I tought it means the latest version. I have the latest FreeTube installed btw

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Read more about nightly builds here

https://docs.freetubeapp.io/development/nightly-builds

**Comment by ChunkyProgrammer** [comment]
Try disabling "api fallback"  as a workaround https://github.com/FreeTubeApp/FreeTube/issues/1283#issuecomment-841743412

**Comment by petyadev1** [comment]
I just don't really know what Nightly build means. I tought its the latest
version. Anyways, I have latest FreeTube installed

efb4f5ff-1298-471a-8973-3d47447115dc ***@***.***> ezt írta
(időpont: 2022. jún. 12., V 16:54):
