### ISSUE TITLE
[Feature Request]: Automatically open in external player

### ISSUE THREAD

**Issue by MichaelMackus** [FreeTubeApp/FreeTube#2332]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

It would be great if there was an option to automatically open videos in an external video player. I much prefer using mpv for video playback, since the HW acceleration seems much better than the freetube/chrome implementation. The button to open in an external player works fine, but it would be nice to just use this for all videos.

### Proposed Solution

Add a setting to open all videos in an external video player by default. Ideally, this would be embedded directly into the freetube application (without opening a new window), but I'm not sure how feasible that is. Just opening a new window whenever a video is clicked works fine though. 

We would likely need to also pause the freetube video player when clicked since viewing comments and related videos is still good functionality. Alternatively, just hide the video player altogether - which would actually look quite nice, especially with a tiling WM... then users could resize the external video and view comments/other videos in a nicely sized small tiled window, à la picture-in-picture (which does not work well with tiling WM).

### Alternatives Considered

Clicking the button is obviously fine, but I'm lazy :)
Using firefox to do this via a user script works fine, but I much prefer freetube's interface and ability to add subscriptions (without logging into youtube).

### Issue Labels

ease of use improvement

### Additional Information

Definitely not a priority

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/5427
