### ISSUE TITLE
[Feature Request]: A randomized content tab

### ISSUE THREAD

**Issue by Minimi003** [FreeTubeApp/FreeTube#2338]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

When you use Freetube you only have the subscription feed but no other content, which only reinforces your filter bubble.

### Proposed Solution

A solution to this problem would be a tab like Trends, but only with random content in set languages. So that you only get content that is in a language that you understand.

### Alternatives Considered

-

### Issue Labels

display more information to user, new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I dont see what the purpose is of this if u just use the trending tab

**Comment by Minimi003** [comment]
> I dont see what the purpose is of this if u just use the trending tab

The Trending tab is its own bubble.

**Comment by absidue** [comment]
@Minimi003 How do you expect the feature to work? Keep in mind that FreeTube can only access the parts of YouTube that are publicly accessible through the website.

**Comment by Minimi003** [comment]
> @Minimi003 How do you expect the feature to work? Keep in mind that FreeTube can only access the parts of YouTube that are publicly accessible through the website.

That's a good point. Since this feature does not exist on YouTube, Freetube would have to do it themselves. By analyzing and sorting all videos on YouTube according to their language. And then randomize the videos according to certain languages that the user has chosen. I would understand if this didn't work, because it would be too complex to implement.

**Comment by absidue** [comment]
As FreeTube doesn't have a server side component, all the sorting and analysing would need to happen on your device. There is no way to access all videos on YouTube so you would likely need to spam searches with random words (where do you get the random words from?) and select some videos from the results, which would get you ratelimited by YouTube or the Invidious instance you are using within minutes, so you wouldn't be able to watch any of the videos.

**Comment by Minimi003** [comment]
You're right. That won't work.
