### ISSUE TITLE
[Bug]: Loop button not working

### ISSUE THREAD

**Issue by Dsw77** [FreeTubeApp/FreeTube#2361]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Open a video
2. Mouseover the video
3. click the loop button: 
![image](https://user-images.githubusercontent.com/66573511/175804231-1a4b8aab-8743-4c05-b2ac-a4186d081c22.png)

Nothing happens, loop button isn't working

### Expected Behavior

After loop button click the loop function will be activated.

### Issue Labels

feature stopped working

### FreeTube Version

v0.17.0-RC-1721 Beta

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.16

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Already fixed in the latest RC build
https://github.com/FreeTubeApp/FreeTube/discussions/2309#discussioncomment-2993176
