### ISSUE TITLE
[Bug]: Playlist will automatically play regardless of whether or not "Autoplay Playlists" is turned on

### ISSUE THREAD

**Issue by loma-baldsson** [FreeTubeApp/FreeTube#2362]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Go to "Settings", and make sure "Autoplay Playlists" (Under "Player Settings") is turned off.
2. Open a playlist. I used the "[Drawing Basics | Proko](https://youtube.com/playlist?list=PLtG4P3lq8RHFRfdirLJKk822fwOxR6Zn6)" to reproduce this.
3. Choose a video. I used the "[How to Hold and Control Your Pencil](https://www.youtube.com/watch?v=pMC0Cx3Uk84&list=PLtG4P3lq8RHFRfdirLJKk822fwOxR6Zn6)" video to reproduce this.
4. Skip to the end. I did this by clicking near the end of the video progress bar, then repeatedly skipping forward.

### Expected Behavior

The video should not autoplay automatically. However, the "Playing next video in X seconds, click to cancel" prompt still shows up, and upon the countdown reaching 0, it proceeds to the next video.

### Issue Labels

feature stopped working

### FreeTube Version

v0.17.0-nightly-1777

### Operating System Version

Ubuntu 22.04 LTS

### Installation Method

.AppImage

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @loma-baldsson could u try out the latest RC build and report back of this is also an issue in the RC

https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml?query=branch%3Av0.17.0-RC

if the issue also persists in the RC, please close this issue and open up a thread in the RC discussion tab so we know we have to fix it before release

**Comment by loma-baldsson** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc The bug is still present in the latest RC build. I don't know how to open up a thread there so could you do so for me? I'll keep it open for the time being. Thanks

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> @efb4f5ff-1298-471a-8973-3d47447115dc The bug is still present in the latest RC build. I don't know how to open up a thread there so could you do so for me? I'll keep it open for the time being. Thanks

I put this bug in the RC thread.
See https://github.com/FreeTubeApp/FreeTube/discussions/2309#discussioncomment-3043757

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I'm reopening this because this was already broken in v0.16.0. We will fix this after the release.
