### ISSUE TITLE
[Bug]: Buffering is slower in Freetube than on youtube.com, mostly on new videos

### ISSUE THREAD

**Issue by AnonymousHex** [FreeTubeApp/FreeTube#2363]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Open any video, newer the better (under 1 day old).
2. Within the first 5-10 seconds, the video will run out of buffer, and will require some amount of paused time to buffer enough.
3. After allowing time to buffer more of the video, no more buffering is neeed for the rest of the video.
4. Watching the same video on youtube.com will play without interruption and buffer more data initially.

Older videos seem to buffer more quickly than new videos, however new videos buffer much quicker on youtube.com.

### Expected Behavior

Identical buffering behavior to that of youtube.com without the need for any pausing or waiting.  Freetube should buffer more aggressively at the beginning.

### Issue Labels

content not loading, inconsistent behavior

### FreeTube Version

v0.17.0-nightly-1727 Beta

### Operating System Version

Windows 7 64bit Pro

### Installation Method

.zip

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

N/A

### Additional Information

The behavior when running out of buffer is identical to that described [here](https://github.com/FreeTubeApp/FreeTube/issues/1557).

Not every video does this, but it happens with a large enough percentage to be noticeable.  Internet download speed is not an issue.  Videos that have this problem will buffer fine on youtube.com.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is a known issue see https://github.com/FreeTubeApp/FreeTube/discussions/1835#discussioncomment-1497715

We have to wait for an upstream patch

**Comment by RootBeerFan** [comment]
> This is a known issue see [#1835 (comment)](https://github.com/FreeTubeApp/FreeTube/discussions/1835#discussioncomment-1497715)
> 
> We have to wait for an upstream patch

Do you know when this will be actively worked on? I'm on 0.17 and the issue still persists.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> > This is a known issue see [#1835 (comment)](https://github.com/FreeTubeApp/FreeTube/discussions/1835#discussioncomment-1497715)
> > 
> > We have to wait for an upstream patch
> 
> Do you know when this will be actively worked on? I'm on 0.17 and the issue still persists.

This isnt up to us to fix. I needs to be fixed upstream.

**Comment by RootBeerFan** [comment]
> > > This is a known issue see [#1835 (comment)](https://github.com/FreeTubeApp/FreeTube/discussions/1835#discussioncomment-1497715)
> > > We have to wait for an upstream patch
> > 
> > 
> > Do you know when this will be actively worked on? I'm on 0.17 and the issue still persists.
> 
> This isnt up to us to fix. I needs to be fixed upstream.

Upstream in this case refers to Electron?
Already thanks for your reply!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> > > > This is a known issue see [#1835 (comment)](https://github.com/FreeTubeApp/FreeTube/discussions/1835#discussioncomment-1497715)
> > > > We have to wait for an upstream patch
> > > 
> > > 
> > > Do you know when this will be actively worked on? I'm on 0.17 and the issue still persists.
> > 
> > This isnt up to us to fix. I needs to be fixed upstream.
> 
> Upstream in this case refers to Electron?
> Already thanks for your reply!

IIRC its node-ytdl-core that needs to patch this

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is this still an issue for u on new videos with v0.17.1?

**Comment by RootBeerFan** [comment]
> Is this still an issue for u on new videos with v0.17.1?

I'm not the original author but I can say that it still happens in the first 1-5seconds but after that the buffering is just fine.
I compared the same source video between my Ubuntu Mint laptop with FT 0.17.1 and my Windows 10 PC with FT 0.17.0.
The Windows 10 PC had 3 major stutters within the first 25 seconds compared to just 1 minor stutter on FT 0.17.1.
Hope this helps

**Comment by RootBeerFan** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc because this seems to be an active issue I would appreciate it if you'd reopen this case. I added my experience as well, its quite unfortunate that this has been closed just because the OP hasn't replied yet.

Also, I switched to fiber based internet recently and comparison to almost all other traffic relatet apps on ether my Linux or Windows machines, only the Freetube client doesn't show any improvement at all. If I open ether Youtube directly, or any Invidious instance all streams get buffered very quickly. Only the Freetube client still is hassling a lot to buffer at all. For me that seems like a fixed buffer size or inbound stream value is set because all other reasons don't make any sense to me. I can download with more than 500mbit/s but Freetube downloads like I am still using a 6mbit/s connection on a netbook with 2gb ram.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Oh sorry about that, somehow missed your comment otherwise it wouldnt let it autoclose

**Comment by RootBeerFan** [comment]
> Oh sorry about that, somehow missed your comment otherwise it wouldnt let it autoclose

Hi Fellow,

today I updated to v0.18.0 beta and at a first glance the buffering improved. Until further notice this is only my first experience, based on my linux client laptop. I watched about 5 videos with different length, quality and from different channels. All had a pre-playing buffering of about 4-5 seconds until the video started playing but afterwards not even one stutter happened again.

I will update my post if I also tested with another windows-based client.

Settings so far:
- local API prioritized
- https://yewtu.be as primary instance
- Dash 1080p preferred

**Comment by zh54tg234f** [comment]
this issue exist since ages , its really annoying when you use a slow vpn / have an unstable connection. a buffer ahead as much as possible would be nice as optional feature (opt in - since people might use cell services and dont have this issue)

**Comment by jnihil** [comment]
I am running the AppImage  v0.18.0 Beta version of Freetube on Debian 11 and have the very slow buffering issues on videos which have a smaller view count. Popular videos don't seem to have this issue. I workaround the buffering by pressing the Back button on the top of the Freetube screen when the slow buffering starts, and then hitting the Forward button successfully buffers the stream.

**Comment by Konglomneshued** [comment]
Yeah, I'm having extremely slow buffering.  I can't watch any videos, every two seconds or so it buffers again.

**Comment by jnihil** [comment]
I'm testing the v0.18.0-nightly-2635 Beta build Appimage for Linux/amd64.
The buffering seems **significantly better as a whole**, but for many older videos Freetube still experiences the same buffering problem:

- Long wait for the video to start due to buffering
- Plays for a few seconds, runs out of buffered video and pauses while waiting for buffer to fill
- Plays for a few more seconds but repeats the pause/buffer cycle over and over

Reloading the page fixes this, and the entire video will playback without any pauses. The same page plays back without such issues in Firefox and Chrome.

This is an example of such a page with buffering issue: https://youtu.be/qG-vNzcn96k

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@jnihil In the General Settings of FT what is your preferred API backend set to? Also is the Proxy Videos Through Invidious setting enabled under the Player Settings?

**Comment by jnihil** [comment]
Preferred local backend is Local API, and Proxy Videos Through Invidious was disabled. I just enabled the Proxy Videos Through Invidious setting which seems to have stopped the buffering issue for older/less-popular videos. I'll do more testing this evening with this setting and report back.

**Comment by jnihil** [comment]
I tested quite a large selection of videos and the playback on v0.18.0-nightly-2635 Beta build has been flawless with no more buffering issues. Many thanks for the efforts!!
