### ISSUE TITLE
[Bug]: External player is not proxied through Invidious

### ISSUE THREAD

**Issue by JacksonBarker** [FreeTubeApp/FreeTube#2373]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. In "Player Settings" enable "Proxy Videos Through Invidious".
2. Set "External Player" to "VLC" in "External Player Settings".
3. Open any video
4. Click "Open in vlc"
5. Press "Ctrl+I" in VLC to open "Media Information"
6. "Location" at bottom of "Current Media Information" window shows that the media's location is "googlevideo.com"

### Expected Behavior

"Location" at bottom of "Current Media Information" window shows that the media's location is either my default Invidious instance, or a random instance if a default instance is not set.

### Issue Labels

API issue

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Fedora Linux 36 KDE Plasma Desktop Edition

### Installation Method

.rpm

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
FreeTube passes the YouTube video URL to the external player. e.g. `vlc {other args here} https://www.youtube.com/watch?v=dQw4w9WgXcQ` what the external player does with the URL is left up to the external player.

**Comment by JacksonBarker** [comment]
This could probably be communicated more clearly to a user who is not aware that their privacy is potentially compromised by using an external player.

**Comment by lost22git** [comment]
how can i pass env var like http_proxy to external player command?
