### ISSUE TITLE
[Feature Request]: Playlist of unwatched videos

### ISSUE THREAD

**Issue by UltraBlackLinux** [FreeTubeApp/FreeTube#2375]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I myself watch almost all the videos of my subs and it would make things easier if I didn't have to always find where I left off.

It's sometimes also hard to see which videos I have and haven't watched. Especially on dark thumbnails

### Proposed Solution

I would love to have a feature that puts all unwatched videos into a playlist. 

### Alternatives Considered

there is nothing comparable yet, at least as far as I have noticed

### Issue Labels

ease of use improvement, new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You can hide subscription videos when watched by enabling it in your settings.

**Comment by UltraBlackLinux** [comment]
> @UltraBlackLinux You can hide subscription videos when watched by enabling it in your settings.

Well I have thought about this, but sometimes I just accidentally click on a video and thus set it to watched even though I didn't watch it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This can easily be reverted in this history tab. I dont think the proposed solution is a feasible one. 

What we could do is implement a better way to fast show/hide watched videos instead of going into the settings menu.
