### ISSUE TITLE
[Bug]: Inverted shortcuts

### ISSUE THREAD

**Issue by galure** [FreeTubeApp/FreeTube#2376]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1.Play a video
2. `I` shows video statistics modal
3. `D` enters/exits Picture in Picture Mode
4. `Ctrl+L` doesn't focus on the search bar (neither does `Alt+D`)
5.  `Ctrl + +` or `Ctrl + =` and `Ctrl + -` doesn't scale the UI

### Expected Behavior

According to [this page](https://docs.freetubeapp.io/usage/keyboard-shortcuts/):

1. `D` should show video statistics modal
2. `I` should enter/exit Picture in Picture Mode
3. `Ctrl+L` and `Alt+D` should focus on the search bar
4. `Ctrl + +` or `Ctrl + =` and `Ctrl + -` should scale the UI. 

### Issue Labels

keyboard control not working

### FreeTube Version

freetube_0.16.0_amd64

### Operating System Version

Fedora36 Wayland

### Installation Method

.rpm

### Primary API used

Invidious API

### Additional Information

I've been using Freetube for a very long time, and this is really a very minor issue. I'm sorry if it's not useful.

I was initially looking for a way to open a suggested video in a new Freetube window. I was searching the Github for a request made for this feature, and discovered in a post that you can do it with a middle button click (side note here, maybe it should be an option in the dot-sandwich's list: something like "open video in a new Freetube window", because not everybody has a middle button, right?). I didn't find it in the [shortcut list](https://docs.freetubeapp.io/usage/keyboard-shortcuts/) and I don't know if it's anywhere in the docs, because searching for "new window" gives you a long list of Windows-related results.

Well, sorry again if I'm blabbing for nothing, I'd like to thank you very very much for Freetube, it's one of my most used feature on every of my computers, and it's life changing. 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
U need to download the latest nightly build to benefit from the shortcuts

 https://docs.freetubeapp.io/development/nightly-builds

**Comment by galure** [comment]
Oh, ok, good to know it will be implemented in the next update. I'll wait. Thank you!
