### ISSUE TITLE
[Bug]: Can't scroll down while cursor is over Video Player

### ISSUE THREAD

**Issue by J-Kappes** [FreeTubeApp/FreeTube#2379]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

0. Have "Scroll Volume Over Video Player" disabled
1. Scroll down over Video Player while in default or theater view
2. Nothing happens

### Expected Behavior

Scroll down the page.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Fedora 5.18.9-200.fc36.x86_64

### Installation Method

Flathub

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @J-Kappes we have tested this internally and we couldn't reproduce this behavior. It is possible that u are doing something that we didnt think of that causes this issue. Could u maybe provide a screen recording and show us the following

1. open FT
2. show Have "Scroll Volume Over Video Player" disabled
3. go to video
4. Scroll down over Video Player while in default or theater view
