### ISSUE TITLE
[Bug]: Enabling the "Hide Recommended Videos" Option breaks automatic UI relocation.

### ISSUE THREAD

**Issue by Quantenzitrone** [FreeTubeApp/FreeTube#2380]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

https://user-images.githubusercontent.com/74491719/177688362-d507dd1d-774d-4797-aee4-b137677d7987.mp4

### Expected Behavior

The option should just hide the recommended Videos.

### Issue Labels

visual bug

### FreeTube Version

v0.16.0 and v0.17.0-nightly-1784 Beta

### Operating System Version

NixOS 22.05

### Installation Method

other

### Primary API used

Local API

### Additional Information

I encountered the bug in both the latest release version `v1.16.0` installed from Nixpkgs and the latest Nightly build `v0.17.0-nightly-1784 Beta` executed as an AppImage with appimage-run (AppImages are not easy on NixOS).
I am using i3wm which may be a factor, but since it works without the option enabled this should not be a problem.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
@Quantenzitrone Looks like when the setting is disabled that really long link in the video description is not getting handled correctly and breaking the layout. Could you please send the URL of the video on the left, so I can confirm my suspicions and so that whoever wants to fix it can then also test it?

**Comment by Quantenzitrone** [comment]
amazing thanks
