### ISSUE TITLE
[Bug]: search `#shorts` in searchbar results in `TypeError: Cannot read properties of undefined (reading 'url')`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#2385]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Search #shorts
2. see error

### Expected Behavior

no error

### Issue Labels

API issue, text/string issue

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/04c276ca73a62db8c9ecdeddc38b9acbf0c469e9

### Operating System Version

win10 21h2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
looks like @ChunkyProgrammer opened a PR https://github.com/TimeForANinja/node-ytsr/pull/164 to fix that in the ytsr repo a while ago, it might make sense to make FreeTube use the branch in that PR as upstream hasn't merged the PR yet.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Noticed that now anything with a # in the search query will give u this error

Try searching 

1. #anything 
2. #ltt

**Comment by ChunkyProgrammer** [comment]
We could switch to my branch for the search module (my pr got closed due to inactivity)
