### ISSUE TITLE
[Feature Request]: Settings option too hide invidious error responses

### ISSUE THREAD

**Issue by fugbixer** [FreeTubeApp/FreeTube#2396]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Often errors are displayed but the video is playing fine, due too updates on invidious 

Its annoying for the users to see these errors while the video is playing fine.

### Proposed Solution

Adding a optional setting to hide these invidious errors makes it nice so that we can still access the errors when needed
and not be annoyed when the instance and freetube are working fine.

### Alternatives Considered

Some other type of logging errors like an error log being accessed over the settings page but this option would not be preferred from me 

### Issue Labels

visual improvement

### Additional Information

Its flashing errors, showing not needed errors sometimes

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Errors happens for different reasons even if the video is running. It is important for the users and us to know when something is going on. 

This is not going to happen.

**Comment by fugbixer** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 

for what reason you directly close it, i dont say it should be on by default but then the user wants it having this setting makes sense.

i had to revert from local api to an web api because it made my mom crazy and honestly since its more often pooping up on the usage of the web api i think its a reasonable ask for implementation.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Please note that FreeTube is currently in Beta. While it should work well for most users, there are still bugs and missing features that need to be addressed.

If the feature would be considered then i would be past v1.0.0 and not in beta stage. Therefore it doesn't make any sense to keep this open

**Comment by zh54tg234f** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 

so when does freetube gets out of beta? 
the error warnings while the videos are loading correctly is confusing and annoying.
i guess freetube will never be user friendly for the unwashed masses.... nice attitude bro

i commend here because i got the same response from a friend about the topic on why he uses invidious instead of freetube. ( i dont mind the errors just the not loading of videos...)
