### ISSUE TITLE
Can't unsubscribe from the subscriptions list

### ISSUE THREAD

**Issue by TheFrenchGhosty** [FreeTubeApp/FreeTube#240]
When trying to unsubscribing to a channel from the subscriptions list, the channel is not removed and instead "Added undefined to subscriptions." is displayed.

Unsubscribing from the channel page is working correctly.

**Comment by PrestonN** [comment]
This has been fixed.

**Comment by LinuxOnTheDesktop** [comment]
Might I add here that I cannot find anyway within the app to unsubscribe from a channel. The closest thing that I can find is 'hide this channel' within a context menu. _Oh_ - the unsubscribe button is within the 'channel' screen. Something here for the 'common issues' page, perhaps.
