### ISSUE TITLE
[Bug]: commit 903f3a2 (#2303) breaks portable version

### ISSUE THREAD

**Issue by livingentity** [FreeTubeApp/FreeTube#2401]
### Guidelines

- [ ] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Download and unpack [freetube-0.17.0-nightly-1812-win-x64-portable](https://github.com/FreeTubeApp/FreeTube/suites/7358837726/artifacts/298648222) or newer.
2. Start FreeTube and enjoy an completely empty window.

### Expected Behavior

FreeTube works normally.

### Issue Labels

feature stopped working

### FreeTube Version

v0.17.0 nightly 1812 or newer

### Operating System Version

Windows 11

### Installation Method

Portable

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.17.0 nightly 1811

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by nodeg** [comment]
I can confirm the issue on macOS Monterey (Intel). Version v0.17.0 nightly 1811 and older are working as expected.
