### ISSUE TITLE
[Bug]: Crashing on Linux hardened

### ISSUE THREAD

**Issue by romelsalwi** [FreeTubeApp/FreeTube#2413]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

I recently switched to Linux-hardened and came across Freetube appImage crashing. Thought of checking out the AUR package and still the same issue. This never happened on base Linux.

Process 10509 (freetube) of user 1000 dumped core.
░░ Subject: Process 10509 (freetube) dumped core
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ Documentation: man:core(5)
░░ 
░░ Process 10509 (freetube) crashed and dumped core.
░░ 
░░ This usually indicates a programming error in the crashing program and
░░ should be reported to its vendor as a bug.

### Expected Behavior

To run as normal.

### Issue Labels

causes crash

### FreeTube Version

freetube_0.16.0_amd64.AppImage

### Operating System Version

Arch Linux 5.18.12-hardened1-1-hardened

### Installation Method

.AppImage

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

freetube_0.16.0_amd64.AppImage

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by iminaqube** [comment]
I have this issue as well and launching freetube from console produces
```
[24710:0100/000000.145592:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is egl, ANGLE is 
[1]    24639 segmentation fault (core dumped)  freetube
[24710:0100/000000.939190:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by fugbixer** [comment]
my tip while being unfixed. use it with firejail, i dont have these issues.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
is this also the case on the latest release v0.17.1?

**Comment by romelsalwi** [comment]
> is this also the case on the latest release v0.17.1?

Yes
```

./freetube_0.17.1_amd64.AppImage 
[34704:0818/163031.252439:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_freetuisFWVb/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```
I have been running the appImage through this command:
`./freetube_0.17.1_amd64.AppImage --no-sandbox`

Which on console gives me this error:
```
(node:35012) UnhandledPromiseRejectionWarning: Error: Cannot create a secure cookie from an insecure URL
(Use `freetube --trace-warnings ...` to show where the warning was created)
(node:35012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35012) UnhandledPromiseRejectionWarning: Error: Cannot create a secure cookie from an insecure URL
(node:35012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

```

**Comment by romelsalwi** [comment]
> my tip while being unfixed. use it with firejail, i dont have these issues.

I haven't been successful in containing appimages through firejail.

**Comment by iminaqube** [comment]
Hello guys, I think i found what was causing it to not work.

temp fix is sudo sysctl -w kernel.unprivileged_userns_clone=0
[kernel.unprivileged_userns_clone=0 in](https://wiki.archlinux.org/title/Security#Sandboxing_applications)

load on system boot is in the config files 
https://wiki.archlinux.org/title/Sysctl#Configuration

**Comment by romelsalwi** [comment]
> Hello guys, I think i found what was causing it to not work.
> 
> temp fix is sudo sysctl -w kernel.unprivileged_userns_clone=1 https://wiki.archlinux.org/title/Security#Sandboxing_applications
> 
> load on system boot is in the config files https://wiki.archlinux.org/title/Sysctl#Configuration
> 
> should be fixed to work with this but i don't think it will (if it is the problem) @romelsalwi @fugbixer

I'm able to run the appimage with `--no-sandbox` argument. But I'm not sure it is the right way to execute the file. The issue is related with electron based apps.

**Comment by romelsalwi** [comment]
UPDATE: works flawlessly on Gentoo

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is this still an issue on [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)?
