### ISSUE TITLE
Keep "playlists" screen when going back from a playlist

### ISSUE THREAD

**Issue by VenomSupreme** [FreeTubeApp/FreeTube#2414]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

When we go to a channel and open it's playlist, and then  `Go Back`  it goes to  `Videos` section, **NOT** `Playlist` section.

Annoying

https://user-images.githubusercontent.com/69515491/180647397-e08fd047-e6a8-4fe5-9ac2-3fbd9ec05393.mp4

.

### Proposed Solution

Simply, 
Keep the `Playlist` section in focus when going back

### Alternatives Considered

.

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2446
