### ISSUE TITLE
[Bug]: Custom channel URLs resolve by username which is incorrect

### ISSUE THREAD

**Issue by PAI5REECHO** [FreeTubeApp/FreeTube#2420]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Enter `https://www.youtube.com/c/RealEngineering` into the search bar and hit <kbd>Enter</kbd>
2. The channel goes to https://www.youtube.com/user/realengineering which is the wrong channel

### Expected Behavior

It should go to the correct channel

### Issue Labels

API issue, inconsistent behavior, usability issue

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Linux 5.18.4, NixOS, 22.11 (Raccoon), 22.11.20220619.0d68d7c

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Just curious what was ur method of installing the application? Asking this because u filled in other.

**Comment by PAI5REECHO** [comment]
> Just curious what was ur method of installing the application? Asking this because u filled in other.

https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=freetube
