### ISSUE TITLE
[Feature Request]: Embedded SponsorBlockServer 

### ISSUE THREAD

**Issue by fugbixer** [FreeTubeApp/FreeTube#2422]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Privacy request increase by using a local mirror of the sponsorblock database

### Proposed Solution

https://github.com/ajayyy/SponsorBlockServer

### Alternatives Considered

https://github.com/mchangrh/sb-mirror

### Issue Labels

improvement to existing feature

**Comment by ChunkyProgrammer** [comment]
Embedding the server into freetube isn't really in scope (and would greatly increase the size of the application due to the database). You can change the url that freetube uses for sponsorblock api and that should be enough.
