### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'baseUrl')

### ISSUE THREAD

**Issue by zynexiz** [FreeTubeApp/FreeTube#2428]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

It seems like this error is related to what locale preference is set. If I don't change it (using English US), no error is thrown when playing a video. If I try to change the language to my native one (Swedish in my case, or if I try fx Norwegian), errors is always thrown when playing videos; TypeError: Cannot read properties of undefined (reading 'baseUrl').

The video itself is playing, so nothing wrong there. But it's pretty annoying to have the toasts always pop up.

### Expected Behavior

No matter what language used, there shouldn't be any errors when paying videos.

### Issue Labels

API issue

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Arch Linux / kernel 5.18.14-arch1-1

### Installation Method

AUR

### Primary API used

Local API

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is already fixed in https://github.com/FreeTubeApp/FreeTube/pull/2268

**Comment by zynexiz** [comment]
> This is already fixed in #2268

Good to know, seems that there isn't any release since v0.16.0b though.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@zynexiz release coming very soon https://github.com/FreeTubeApp/FreeTube/discussions/2309

**Comment by zynexiz** [comment]
> @zynexiz release coming very soon #2309

Got the update today, confirmed working now :)
