### ISSUE TITLE
[Bug]: il % in label of the video

### ISSUE THREAD

**Issue by taxizaxis** [FreeTubeApp/FreeTube#2439]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

![image](https://user-images.githubusercontent.com/21279913/182210524-5d00c3c2-39ac-4b49-9cfc-307efce5b5e7.png)
In the title of the French video, we get "il ya il %" instead of having the number of days.

### Expected Behavior

I would like to get the number of days since the video was uploaded

### Issue Labels

text/string issue

### FreeTube Version

v0.17.0 Bêta

### Operating System Version

Windows 11 Professionnel 21H2 22000.795

### Installation Method

.exe

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by vnivuahc** [comment]
I’m facing the same issue in v0.17.1 Beta.

I installed the application in French. Then, switching the locale to English (US) or Spanish doesn’t help.
In all of these languages the number of days since the video was uploaded is not displayed.

Translation files seems ok to me, but the replacement of `$` and `%` is failing.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @taxizaxis is this still an issue for u in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds)?

**Comment by vnivuahc** [comment]
I had the same bug, but it is gone now. I'm running the v0.18.0 Bêta, but I'm pretty sure it disappeared a few versions ago.
