### ISSUE TITLE
[Feature Request]: Actual Sizing for Video Frame Option

### ISSUE THREAD

**Issue by hl2guide** [FreeTubeApp/FreeTube#2441]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

A setting for "actual sizing" that resizes the video frame to the chosen quality would be nice.

e.g.

720p: 1280 × 720
1080p: 1920 × 1080
2160p: 3840 × 2160

This would help with blurriness and retaining quality.

### Proposed Solution

Please add a setting.

### Alternatives Considered

Using as is.

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Probably best to not implement it. It's _possible_ but I can see a lot of issues coming out of it.

This will likely look pretty weird. Especially on HiDPI displays.

This doesn't even account for odd resolution types like vertical video resolutions.
