### ISSUE TITLE
[Bug]: Long buffering when downgrading video resolution

### ISSUE THREAD

**Issue by kubo6472** [FreeTubeApp/FreeTube#2443]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

0. Possibly related to #2363
1. Open a video
2. Let it load
3. When playing downgrade the resolution
4. The video starts buffering for unreasonable amount of time.

### Expected Behavior

Compared to the same video on YouTube, where there is none to sometimes almost none buffering when doing the same resolution downgrade.

### Issue Labels

accessibility issue, content not loading, inconsistent behavior, usability issue

### FreeTube Version

v0.17.0

### Operating System Version

Microsoft Windows 10 Enterprise LTSC Version 10.0.19044 Build 19044

### Installation Method

.exe

### Primary API used

Invidious API

### Additional Information

How come does YouTube have such short buffer times? I checked I was using the DASH format, so I supposed the conditions were the same.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by maplepy** [comment]
Basically any video is awfully long to load, old or new, 1080 or 480p. That's painful to see it's still not fixed after months :/

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi @kubo6472 is this still an issue for u on the latest release v0.17.1?

**Comment by kubo6472** [comment]
Well, it now does this instead:
![image](https://user-images.githubusercontent.com/26146502/185491295-5add7c36-33f6-4fe9-82c8-183dd68ffd8b.png)
