### ISSUE TITLE
[Bug]: Windows - installing 0.17 leaves 0.16 on system; and it is the older version that executes

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [FreeTubeApp/FreeTube#2445]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Have 0.16 installed (via freetube-0.16.0-setup-x64.exe).
2. Download freetube-0.17.0-setup-x64.exe from your website.
3. Run freetube-0.17.0-setup-x64.exe.
4. Run freetube. (I used a launcher called keyperinha, but I imagine that using the inbuilt Windows search would have the same result; I am afraid that I cannot check now, because I have uninstalled 0.16.)
5. Find that the version of freetube that is running is 0.16.
6. Find that two versions of freetube are installed - both 0.16 and 0.17.

### Expected Behavior

Installing a new version should _overwrite_ any old version (at least if both versions are installed using the same method).

### Issue Labels

usability issue

### FreeTube Version

v0.17.0 Beta

### Operating System Version

Windows 10 Pro - 21H2 (2009: 19044)

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

![image](https://user-images.githubusercontent.com/47056543/182481509-844017ef-5f96-476e-9c01-1fa7bacb3075.png)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Something must have gone wrong on your end. I do allot of installs of different FT versions for testing and the old one always gets deleted.
