### ISSUE TITLE
[Bug]: Just had a random video play when clicking freetube logo

### ISSUE THREAD

**Issue by sol8712** [FreeTubeApp/FreeTube#2449]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

What happened: After watching a video, before the next video countdown ended i clicked the Freetube logo on the top right to return to the main page like usual but the page turned blank with the title bar showing the name of a very random video in all Chinese, i started clicking away before the video itself loaded but its in my history.

The video i was on before had nothing to do with anything China and nothing China related in the Up Next box. I am unable to duplicate this again.

This is the first video i was wathcing: https://youtu.be/iE5WS-KZJsw
This is the Chinese video i was redirected to: https://youtu.be/VYvzrOJ1qxM

Now but this random Chinese video is in my history and im wondering why/how. Very weird.....

### Expected Behavior

Not playing random videos on a ui click.

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.17.0 Beta

### Operating System Version

Linux Pop OS(Ubuntu Based)

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.16.0

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I am not able to duplicate this kind of behavior. Ur also not able to duplicate this again therefore im closing this.
