### ISSUE TITLE
Feature Request :  Hiding watched videos from "Subscription" view

### ISSUE THREAD

**Issue by MikeZeDev** [FreeTubeApp/FreeTube#245]
I was previously using Minitube and i just switched to Freetube.

It could be handy if there was an option to hide watched videos from the "Subscriptions" view.
It may use the history or not, i dont care .

And ofc with an option to mark a video as read :)

I have seen this https://github.com/FreeTubeApp/FreeTube/issues/138 but i may be blind i dont see the watched marker

**Comment by Cynthetika** [comment]
Backing up this enhancement request, I would really appreciate this same feature.

Since the "Watched" marker is already implemented, could a new option to 'hide' items with that flag be provided in the settings?

**Comment by PrestonN** [comment]
This has been implemented in the latest release, so I will go ahead and close the issue.

**Comment by christian179717** [comment]
@PrestonN Where do you find this option?
