### ISSUE TITLE
[BUG/UX]: Replace "Change Video Formats" with "Change Media Formats"

### ISSUE THREAD

**Issue by SethFalco** [FreeTubeApp/FreeTube#2463]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Navigate to a video
2. Go to the **Change Video Formats** button (a camera inside of a page)
3. Observe that this can be used to serve non-video formats.

### Expected Behavior

The button icon and name should be agnostic to video and audio if it can be used to select audio formats. 

Users (namely myself) may struggle to find how to play in audio only mode, as it's not expected to find such a thing behind a button named for video formats. 

I did actually hover over it, see "Change **Video** Formats" and continued looking elsewhere because it didn't seem to be what I needed.

### Issue Labels

usability issue

### FreeTube Version

0.17.0 Beta

### Operating System Version

Debian 11

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

An alternative solution to this could be to pull the **Use Audio Formats** item from under **Change Video Formats** button, and instead make it a separate button with a headphones icon.

In my opinion, what Invidious does isn't perfect either as the audio-mode button can be mistaken for an emoji suffixed to the end of the video title. Just wanted to share how they handle it, though. That pair of headphones is a button… it's just not very apparent until you explicitly hover over it.

![image](https://user-images.githubusercontent.com/22801583/183313141-92be68d9-0f7e-4c03-8c55-8a6af88e29d1.png)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
What about changing the label to Change Video / Audio Formats?

**Comment by SethFalco** [comment]
That works for me too!
I personally do like just using the term "Media" more.

However, that's entirely subjective. Using "Video / Audio" would still resolve the confusion described in the issue, so if you'd prefer that I think it's good.
