### ISSUE TITLE
[Bug]: Local Api Error: TypeError: Cannot read properties of null (reading '2')

### ISSUE THREAD

**Issue by RevAngel7** [FreeTubeApp/FreeTube#2468]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

v0.17.0 Beta
On every video I click to play I get a **Local Api Error: TypeError: Cannot read properties of null (reading '2')** error now and it switches to Invidious API.
It's strange, because I used the 17 Beta from release day on, and never encountered the error before, did not make any changes in configuration. 
Using this version from the .deb installation for Ubuntu 22.04.1 LTS using kernel 5.19.1.
![2022-08-11_error_FreeTube](https://user-images.githubusercontent.com/38556983/184215759-54180cc3-3dbd-4649-a296-042c92846838.png)

### Expected Behavior

Video should load over standard local youtube API

### Issue Labels

API issue

### FreeTube Version

v0.17.0 Beta

### Operating System Version

Ubuntu 22.04.1 LTS using kernel 5.19.1

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

-

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Victor239** [comment]
Believe I have the same issue which started within this past hour also. YouTube likely changed something on their side.

**Comment by SkyTheGreatOne** [comment]
I also have the same issue. Tried using a VPN, switching Invidious instances, and disabling firewall. @Victor239 is likely correct.

**Comment by petaded** [comment]
I am having the same issue with 17.0 and 16.0 however **version 0.15.1 of freetube is working for me.** am happily watching videos using that.

The issue started the same time as Victor239 mentioned.
Note: I am running Manjaro and using the appimage for all three different versions.

**Comment by nutstalker** [comment]
encountered the same issue starting today. I have been on the latest version since Aug 5th and had no issues until today..I'm sure YT has changed something on their end.

**Comment by Gevaarlijk** [comment]
I get this same error when I try to 'fetch more results'. The first 2 or 3 fetches work, after that no more.
