### ISSUE TITLE
[Feature Request]: hotkey w & s for sound control

### ISSUE THREAD

**Issue by fugbixer** [FreeTubeApp/FreeTube#2474]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

arrow keys are barely used, its from the old days of driving in video games (at least for me)

### Proposed Solution

don't remove the feature from the arrow keys but please extend it to w & s for controlling the sound as well

w & s is easier accessible since they are in shorter range of most other hotkey compared too the arrow keys.

w would be increase sound
s would be decrease sound

### Alternatives Considered

think about it.

thanks

### Issue Labels

improvement to existing feature

**Comment by ChunkyProgrammer** [comment]
Hello,
We hope to add support for customizing keyboard shortcuts in the future but we do not want to implement this shortcut by default. Subscribe to #251 if you'd like to get updates on this.
