### ISSUE TITLE
[Feature Request]: Add dedicated shorts tab

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#2476]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Since i kinda love youtube shorts, and also since it also owned by google. I dont get to be anonymous watching these youtube shorts since you know its owned by google. I think this could be good for FreeTube if you added this.

### Proposed Solution

I dont whats the solution yet, i dont even know programming is. So yeah.

### Alternatives Considered

none.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
U can already watch shorts in FreeTube

**Comment by ChunkyProgrammer** [comment]
> U can already watch shorts in FreeTube

They probably mean the YouTube Shorts page (ex: https://www.youtube.com/shorts/{videoId} which behaves a lot like a tiktok page with infinite scrolling of short form content only..
<img width="180" alt="image" src="https://user-images.githubusercontent.com/78101139/184773761-e96582cb-6256-4a9e-92f7-d592b42c5a37.png">

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Oh didnt know that that was a thing now. Edited the title and will reopen.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Just a thought about the implementation of this. This tab should just be like your subscription tab but with all shorts together from all your subscriptions

**Comment by Victor239** [comment]
It'd also be helpful if a channel can be filtered by Shorts only. I don't care to watch all the videos of a certain channel but I would like to see their Shorts. Either as a new tab or some kind of filter:

![](https://i.imgur.com/tX24pN3.png)

**Comment by Victor239** [comment]
Bump

**Comment by ChunkyProgrammer** [comment]
@KarateCowboy 
Some info:
yt-channel-info will need to be updated (there hasnt been a new release in a while so you could set the version to a specific commit)
I believe the command would be:
`yarn add git://github.com/freetubeapp/yt-channel-info.git#1e80fc79bdc86355ca48425f03bc8a64d7451133`
(This should add getLiveStreams and getShorts to the local api)

Invidious has two new endpoints:
/channels/{channelId}/streams for live streams
And
/channels/{channelId}/shorts for shorts

I believe there are settings to hide shorts and live content too (not 100% sure about hiding shorts) so make sure that it isn't displayed and the code isn't ran if it's disabled 🙂.
Let us know if you need any more help

**Comment by KarateCowboy** [comment]
Great! That will be super helpful. Understanding the general application layout was pretty easy. The next part to grok is those APIs and this will save me time reverse engineering and head scratching.

**Comment by KarateCowboy** [comment]
@ChunkyProgrammer 

I created a PR for feedback. The basic Shorts tab is implemented. Looking for feedback about localization or any other things I need to know. I am sure there are some loose ends of which I am unaware.

**Comment by wweevv-johndpope** [comment]
cool - merge.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
As for the original requested feature

> They probably mean the YouTube Shorts page (ex: [https://www.youtube.com/shorts/{videoId}](https://www.youtube.com/shorts/%7BvideoId%7D) which behaves a lot like a tiktok page with infinite scrolling of short form content only.. <img alt="image" width="180" src="https://user-images.githubusercontent.com/78101139/184773761-e96582cb-6256-4a9e-92f7-d592b42c5a37.png">

We wont implement this. Shorts tab on the channel page is already implemented and is [going to be implemented on the subscription page](https://github.com/FreeTubeApp/FreeTube/pull/3725)
