### ISSUE TITLE
[Bug]: Livestream Endless Spinner No Loading

### ISSUE THREAD

**Issue by hl2guide** [FreeTubeApp/FreeTube#2477]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Load up a livestream when live and it's an endless spinner.

### Expected Behavior

Livestream loads, or if livestreams are not supported by the app then hide livestream videos.

### Issue Labels

content not loading

### FreeTube Version

0.17.1 Beta

### Operating System Version

Windows 11 21H2

### Installation Method

.zip

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by skaendo** [comment]
I am having the same issue except nothing will play. Just a endless spinner.
v0.17.1/Debian

**Comment by absidue** [comment]
@hl2guide I see you've said you use the Invidious API, could you please check if the issue happens with the local API as well, if not this is likely to be an issue with the invidious instance you are using.

**Comment by mkalinski** [comment]
I'm having the same problem with livestreams. When using local API, it just falls back to invidious, printing "Cannot read properties of undefined (reading 'spec')"

**Comment by skaendo** [comment]
I'm not the OP but, it must have been the Invidious API since it seems to be cleared up now. It was just weird that I was able to watch things from subscriptions and not a playlist url that I entered into "search/url".

**Comment by hl2guide** [comment]
From my basic testing it seems hit and miss for whether it works or not (Invidious on or off).
