### ISSUE TITLE
[Bug]: Odd video time numbers

### ISSUE THREAD

**Issue by leestarb** [FreeTubeApp/FreeTube#2478]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Open a video
2. Look at the time
3. See 0️⃣0️⃣ instead of normal `00`
4. Wtf

### Expected Behavior

Normal decimal time number symbols (not 1️⃣2️⃣3️⃣ etc)

### Issue Labels

visual bug

### FreeTube Version

1.17.1 latest

### Operating System Version

Ubuntu latest

### Installation Method

.deb

### Primary API used

Local API

### Additional Information

That were in older versions too

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Hi @leestarb

Could you please provide some screenshots and videos that are affected by this, as I can't replicate this on my side at the moment.

**Comment by leestarb** [comment]
> Hi @leestarb
> 
> Could you please provide some screenshots and videos that are affected by this, as I can't replicate this on my side at the moment.

Every video is being affected, I tried to change the invidious, but that still has non ascii, emoji numbers in black rects!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@leestarb u didnt provide screenshots. Please provide them because we cant replicate this behavior, so we need to know how it looks like.

**Comment by leestarb** [comment]
> @leestarb u didnt provide screenshots like requested. Please provide them because we cant replicate this behavior, so we need to know how it looks like. 

@absidue @efb4f5ff-1298-471a-8973-3d47447115dc 

Here you go: https://privfile.com/download.php?fid=62ff5e374ec38-MTQyOTM=

**Consider downloading the image to avoid losting of it. The password is: ||`freetube`||

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
In case the link expires

![FreeTube.png](https://user-images.githubusercontent.com/73130443/185617524-1444e52b-c854-4485-847a-6a6a6c6be4a2.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is this still an issue on [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)?

**Comment by leestarb** [comment]
Yeah guys it is fine now. No those emoji numbers! Thank you :)

**Comment by 6d8** [comment]
I'm seeing this as well. Any digit displayed on the video overlay (such as current runtime, title when in full screen, playback speed) is rendered in a different font with excessive spacing. 

Note: they are not emojis as the previous reporter said, just oddly displayed text.

I'm on Linux 6.10.10-arch1-1 with KDE Plasma, using the portable linux release.

Examples below:

![Screenshot_20240920_224934](https://github.com/user-attachments/assets/ab555a6b-aa98-4e5c-b103-966f6797741b)
![Screenshot_20240920_225220](https://github.com/user-attachments/assets/2898856d-6dae-4ffe-91f6-e1f46cde268c)
