### ISSUE TITLE
Enhancement: Watch Later / Playlist Creation

### ISSUE THREAD

**Issue by FreeTubeFan** [FreeTubeApp/FreeTube#248]
Hello,
I downloaded FreeTube a few days ago and am loving it so far. 

Really my only problem is that there is no ability currently to make playlists or to add things to a "Watch Later" section like on the actual YouTube page. Using the Favorites option is the only substitute, but I would like to be able to separate things into like a music playlist, a funny videos playlist, etc.

Thanks for all the hard work you do! :)

**Comment by avamk** [comment]
Agree with @FreeTubeFan. Good playlists support - which includes creating/managing my own playlists *and* viewing/importing a channel's playlists - would be a killer feature, and makes accessing youtube.com almost completely unnecessary.

Will playlists support be hard to implement? How do we help prioritise this and help make this happen?

**Comment by PrestonN** [comment]
It's planned and should be coming soon.  My priorities typically go along with what gets requested the most.  Local profiles (or subscription categories as some have called it) have a higher priority and is almost ready.  When that is ready, user playlists will be started immediately after as the requests for it have been very high recently.

As far as difficulty goes, I foresee no roadblocks in making it happen though I will always accept help to make it happen faster.  If you understand your way around some JavaScript then you're welcome to help out with it.  Let me know and I can help you get started.

**Comment by snakyjake1** [comment]
I like using my RSS reader to view my subscriptions, choose what I want to watch, then then open a bunch of videos to watch in my web browser.  This is not good because opened YouTube browser tabs consume resources.  One solution is to use something like FreeTube to queue my videos I want to watch, and something that can help me manage that queue.

**Comment by BarbzYHOOL** [comment]
When will we have playlists? I am subscribed to like 40 channels and it's becoming extremely hard to filter the new videos :(

**Comment by dmland** [comment]
Four years. Can we accept that this feature is not going to happen?

**Comment by BarbzYHOOL** [comment]
its not completed
