### ISSUE TITLE
[Bug]: Cannot open short URLs from external apps

### ISSUE THREAD

**Issue by domy86** [FreeTubeApp/FreeTube#2480]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

I'm not sure if this is libredirect issue or not because I have no idea how to test it without libredirect.

1. Open some short YouTube URL from Signal, Telegram, Viber, Thunderbird or some other app, for example: https://youtu.be/Yt5A5z8fJco
2. Firefox will show up, a new blank tab will be opened and libredirect will send a link to FreeTube.
3. FreeTube will act like some YouTube channel is opened but with 0 subscribers, without channel info and with toast errors:

Local API Error (Click to copy): Error: Request failed with status code 404
Falling back to Invidious API
Local API Error (Click to copy): Error: Request failed with status code 404
Falling back to Invidious API
Invidious API Error (Click to copy): Could not get channel info.

![image](https://user-images.githubusercontent.com/84593035/184516926-d59b5df6-4101-4084-b56e-6fc6df2ecd6a.png)

### Expected Behavior

FreeTube should open a short URLs like it opens a full URLs, for example: https://www.youtube.com/watch?v=Yt5A5z8fJco

![image](https://user-images.githubusercontent.com/84593035/184517065-f5c7cd37-76e8-4fd2-b4fa-6e5b43896c82.png)

Also, if I put a short URL into the search bar, it works as expected.

### Issue Labels

content not loading

### FreeTube Version

v0.17.1

### Operating System Version

Kubuntu 22.04.1 LTS

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

Tried Invidious API and other instances but not helped.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
I highly suspect that this is an issue with libredirect, as pasting the URL into the search bar works and opening it via the URL scheme `freetube://https://youtu.be/Yt5A5z8fJco` works fine as well.

**Comment by absidue** [comment]
Okay so I've investigated it and it is definitely an issue with libredirect, i've left a comment on their repo, hopefully they will fix it on their end.
https://github.com/libredirect/libredirect/pull/393#issuecomment-1214449067

**Comment by absidue** [comment]
Closing this as it's not something we can fix.

**Comment by domy86** [comment]
Thank you! I have tested Privacy Redirect and works fine, so it's definitely an issue with libredirect.
