### ISSUE TITLE
[Bug]: Featured Channels throw error on click (only while using the Invidious API)

### ISSUE THREAD

**Issue by MarmadileManteater** [FreeTubeApp/FreeTube#2481]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Select "Invidious API" as the preferred API backend.
2. Navigate to a channel with featured channels.
3. Click on one of the featured channel icons.
![featured-channels-error](https://user-images.githubusercontent.com/106682128/184550611-2a5a7020-685b-49e7-bf16-e7f9f894ef0b.gif)

The page remains the same except that the body changes to contain the text: "Could not get channel info".
I started debugging this issue in my fork (original issue: MarmadileManteater#12) because I thought it was something I introduced, but I found the issue was inside of `./src/renderer/views/Channel/Channel.vue`, and I was able to replicate the issue on the newest release.

### Expected Behavior

Clicking one of the featured channel icons should change the route to the id of that featured channel.

### Issue Labels

API issue

### FreeTube Version

v0.17.1

### Operating System Version

Windows 10 Pro Version	21H2 Installed on	‎4/‎3/‎2022 OS build	19044.1889 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Installation Method

.exe

### Primary API used

Invidious API

### Additional Information

I believe the issue is that the `ft-channel-bubble` element expects featured channels to contain the key "channelId".
```vue
<!-- line 130 of src/renderer/views/Channel/Channel.vue -->
<ft-channel-bubble
  v-for="(channel, index) in relatedChannels"
  :key="index"
  :channel-name="channel.author || channel.channelName"
  :channel-id="channel.channelId"
  :channel-thumbnail="channel.authorThumbnails[channel.authorThumbnails.length - 1].url"
  @click="goToChannel(channel.channelId)"
/>
```

The problem is that the response from the Invidious API only contains a key named "authorId", not "channelId". This could be fixed by mapping the "channelId" field to "authorId" inside of the `getChannelInfoInvidious` function in `./src/renderer/views/Channel/Channel.js`. There already is a map for the related channels, so this could be fixed with one new line of code inside that map.
```js
// line 417 of src/renderer/views/Channel/Channel.js
this.relatedChannels = response.relatedChannels.map((channel) => {
  channel.authorThumbnails[channel.authorThumbnails.length - 1].url = channel.authorThumbnails[channel.authorThumbnails.length - 1].url.replace('https://yt3.ggpht.com', `${this.currentInvidiousInstance}/ggpht/`)
  // Mapping authorId to channelId
  channel.channelId = channel.authorId;
  return channel
})
```

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
Would you like to create a PR for this issue or would you want someone else to create one?

**Comment by MarmadileManteater** [comment]
I can make one.
