### ISSUE TITLE
[Bug]: "Command+M" do not work in some Invidious Instance

### ISSUE THREAD

**Issue by filcode** [FreeTubeApp/FreeTube#2485]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Depending on the Invidious Instance used, YouTube keyboard shortcuts override application window keyboard shortcuts.

Example:

"Command+M" mutes the video instead of minimizing the FreeTube window.

### Expected Behavior

"Command+M" should minimize FreeTube window and not mute Youtube video independently of the Invidious Instance used.

### Issue Labels

keyboard control not working

### FreeTube Version

Version 0.17.1 (0.17.1)

### Operating System Version

macOS Monterey 12.5

### Installation Method

.dmg

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PikachuEXE can u verify this :)

**Comment by PikachuEXE** [comment]
Confirmed it's an issue

**Comment by PikachuEXE** [comment]
https://github.com/FreeTubeApp/FreeTube/pull/2486 created

**Comment by absidue** [comment]
Completed in #2486
