### ISSUE TITLE
[Feature Request]: "Cmd+F" keyboard shortcut should go the Search field on FreeTube on macOS

### ISSUE THREAD

**Issue by filcode** [FreeTubeApp/FreeTube#2490]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

"Cmd+F" keyboard shortcut don't go to the Search field on FreeTube on macOS.

### Proposed Solution

"Cmd+F" keyboard shortcut don't go to the Search field on FreeTube on macOS.

### Alternatives Considered

Select Search field on FreeTube using mouse. Annoying solution.

### Issue Labels

ease of use improvement, new keyboard shortcut, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
First of all u are describing this as a bug but u opened up a feature request.

Im going to make an assumption here that u think this is a bug based in your description.

This shortcut isnt being used at all within the application.


'''Cmd+L''' is the shortcut u want for this behavior, see https://docs.freetubeapp.io/usage/keyboard-shortcuts/.

**Comment by filcode** [comment]
I thought this shortcut was missing since the objective was to make a search. So the shortcut “cmd+L” is what I was looking for and is the same shortcut used to access the URL bar of browsers on macOS.
