### ISSUE TITLE
[Bug]: Constant buffering on any videos

### ISSUE THREAD

**Issue by CyberaxAnnon** [FreeTubeApp/FreeTube#2491]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

When going to any video, it will load with a the screen frozen followed by the audio continuing before needing to load again. it loads a second or to before it happens again and continues to do so, as seen in the video.

https://user-images.githubusercontent.com/99626705/185069109-ac9a4f50-9c7b-4402-b6f6-8d53bd85b4c3.mp4

### Expected Behavior

Should load and run the video.

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

0.17.1 Beta

### Operating System Version

Pop.OS

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

Latest version

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ThiloteE** [comment]
Could be ANYTHING, but what helped me on my old laptop with not the best internet was to manually change the framerate from 60 to 30, or alternatively change to lower resolution, because my laptop was not fast enough CPU wise to keep up with rendering.

Example:

720p60 --> 720p
720p60 --> 480p

**Comment by ThiloteE** [comment]
I would suggest to set default to 720p instead of 720p60

**Comment by LWFlouisa** [comment]
This seems to be the case regardless of whether I use NewPipe or Freetube. Though curiously it works fine on Invidio.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is this still an issue on [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)?
