### ISSUE TITLE
[Bug]: SponsorBlock segments don't always display in the timeline when using the Invidious API

### ISSUE THREAD

**Issue by MarmadileManteater** [FreeTubeApp/FreeTube#2492]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Enable "Sponsor Block" in the settings
2. Select "Invidious API" as your default API
3. Navigate to a video which has sponsored segments (ex: [2Q0bLo5nSsU](https://www.youtube.com/watch?v=2Q0bLo5nSsU))
4. Sponsor block segments are not visible, but the player does still skip the segments when they would occur.
![image](https://user-images.githubusercontent.com/106682128/185188335-73af89c9-6d18-4425-87b9-794a36c313fb.png)

### Expected Behavior

The sponsored segments should display on the timeline in the color selected in the settings. This is what the video looks like when the local API is selected.
![image](https://user-images.githubusercontent.com/106682128/185187705-c3077754-0641-498c-a1cd-2445f052b226.png)

### Issue Labels

race condition

### FreeTube Version

v0.17.1

### Operating System Version

Windows 10 Pro Version	21H2 Installed on 4/‎3/‎2022 OS build	19044.1889 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Installation Method

.exe

### Primary API used

Invidious API

### Additional Information

This issue seems to be occurring because `this.player.duration()` is often 0 at the time when `addSponsorBlockMarker` is called (especially when the Invidious API is preferred), and `this.player.duration()` only becomes the length of the video after `addSponsorBlockMarker` is called. This causes a division by zero where the width and positioning of the sponsored segments would normally be set. 
```js 
// line 630 of src\renderer\components\ft-video-player\ft-video-player.js
markerDiv.style.width = (marker.duration / this.player.duration()) * 100 + '%'
markerDiv.style.marginLeft = (marker.time / this.player.duration()) * 100 + '%'
```
JavaScript evaulates the strings  as `Infinity%`, and the result is that the sponsored segments do not always appear when the Invidious API is selected as the preferred API.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Did u also had issue with the local api like in https://github.com/FreeTubeApp/FreeTube/issues/1439

**Comment by MarmadileManteater** [comment]
I am unsure. It is totally possible, but it is very likely it is less pronounced for the Local API because it is taking less time with each request.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is it possible for u to look into. If u want and have the time for it?

**Comment by MarmadileManteater** [comment]
I believe my pull request will fix this issue. I do not know for sure if it will fix the other issue, but it might from the looks of it.
