### ISSUE TITLE
[Bug]: Fails to start with TypeError

### ISSUE THREAD

**Issue by hollunder** [FreeTubeApp/FreeTube#2494]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Crashes on startup, see below.
The weird thing is that after installing 0.17.1 the previously working version 0.17.0 would also fail to start with the same error.
Installed using this AUR script, just with updated version: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freetube-wayland

### Expected Behavior

Expected to not crash on startup.

### Issue Labels

causes crash

### FreeTube Version

0.17.1

### Operating System Version

Arch Linux

### Installation Method

AUR

### Primary API used

Local API

### Additional Information

```
$ freetube
[25487:0819/090543.722013:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is egl, ANGLE is 
[25487:0819/090543.726936:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
(node:25438) UnhandledPromiseRejectionWarning: Error: Cannot create a secure cookie from an insecure URL
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:25438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25438) UnhandledPromiseRejectionWarning: Error: Cannot create a secure cookie from an insecure URL
(node:25438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
TypeError: Cannot destructure property 'value' of 'object null' as it is null.
    at /usr/lib/freetube/app.asar/dist/main.js:1:4801
    at async W (/usr/lib/freetube/app.asar/dist/main.js:1:4757)
    at async App.<anonymous> (/usr/lib/freetube/app.asar/dist/main.js:1:9167)
[1]    25438 segmentation fault (core dumped)  freetube --trace-warnings
```

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I actually think that https://github.com/FreeTubeApp/FreeTube/issues/2190 is your issue

**Comment by hollunder** [comment]
Possibly. What is weird is that 0.17.0 worked, I installed 0.17.1 which showed that error and after going back to 0.17.0 I got the same error. So I guess it could be related to some setting or something else persistent that Freetube does on startup.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hmm i don't think #2190 is related based of u saying v0.17.0 was working and looking at the change log of v0.17.1. 

The AUR package is not being maintained by us. I would recommend reaching out to the maintainer of that package.

**Comment by hollunder** [comment]
I tried to install https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freetube-git again, from which I previously switched away because of some issue. This one works, even though it throws similar errors on startup. I did notice that it uses a newer version of Electron.

```
$ freetube
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
TypeError: Cannot destructure property 'value' of 'object null' as it is null.
    at /usr/lib/freetube-git/app.asar/dist/main.js:1:4801
    at async W (/usr/lib/freetube-git/app.asar/dist/main.js:1:4757)
    at async App.<anonymous> (/usr/lib/freetube-git/app.asar/dist/main.js:1:9167)
(node:51544) UnhandledPromiseRejectionWarning: Error: Cannot create a secure cookie from an insecure URL
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:51544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:51544) UnhandledPromiseRejectionWarning: Error: Cannot create a secure cookie from an insecure URL
(node:51544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[51606:0819/134203.597374:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[51606:0819/134207.351485:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[51606:0819/134220.697247:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I have seen this error before over at https://github.com/FreeTubeApp/FreeTube/issues/2269

**Comment by hollunder** [comment]
Interesting. I run open source AMD drivers though, so quite a different graphics stack. Since I have a build that runs now and not much time to do debugging I will leave it here.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Looking at this again and noticed that https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freetube-git is very outdated. I recommend that u use an up to date package.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://aur.archlinux.org/packages?O=0&K=freetube

v0.17.1 is the latest version

**Comment by hollunder** [comment]
Thanks, but the version number you see there is not really relevant as long as the build steps are still appropriate. VCS packages can be a bit confusing that way. Basically you get the latest commit at the time of building the package.
The "-wayland" package is actually outdated and caused issues on my system.
All it does however is to use a different freetube.sh and I don't see a reason to not use that in general.
https://aur.archlinux.org/cgit/aur.git/tree/freetube.sh?h=freetube-wayland

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is this still an issue on [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)?
