### ISSUE TITLE
[Bug]: Select Quality button is untappable

### ISSUE THREAD

**Issue by 0x6e656b6f** [FreeTubeApp/FreeTube#2496]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Steps to reproduce:
1. On devices with touch input, tap the select quality button.
2. Button didn't show video quality selection.

### Expected Behavior

The button should open up the quality selection popup.

### Issue Labels

accessibility issue

### FreeTube Version

v0.17.1

### Operating System Version

Windows 10 21H1

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

I think the bug is caused by the behavior of the button. When using mouse or touchpad, you hover your cursor on the button to show the popup. However, on touch devices you can't hover over button.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is it maybe possible to do a long press so it will come up?

**Comment by 0x6e656b6f** [comment]
Oh yes, that worked. But shouldn't the button open up without needing to long press it?
