### ISSUE TITLE
[Feature Request]: Some kind of Download Menu where I can see my download progess.

### ISSUE THREAD

**Issue by COALROCK8642** [FreeTubeApp/FreeTube#2500]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I wanted to propose that we have a download menu like browsers. 

### Proposed Solution

So we can see download progress. Because there is no message of download failure.

Probably this menu can be fitted under the profile sub-menu.

This is not shortcut to download. And should be done under it's own window or small menu.

### Alternatives Considered

Probably use notifications as way to show success and failure of downloads.

### Issue Labels

display more information to user, ease of use improvement, visual improvement

**Comment by absidue** [comment]
Duplicate of  #2110
