### ISSUE TITLE
[Bug]: Doesn't start (AUR)

### ISSUE THREAD

**Issue by Trochatole** [FreeTubeApp/FreeTube#2503]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Freetube does not start

### Expected Behavior

Freetube starts

### Issue Labels

causes crash

### FreeTube Version

0.17.1-1

### Operating System Version

Arch linux

### Installation Method

AUR

### Primary API used

Local API

### Additional Information

Freetube: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory 

this is on the most recent version of arch on the 5.19.2-zen1-1-zen kernal 

Im using a intel celeron N4000
With uhd graphics 600

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This is probably an issue with the AUR package that you are using, the AUR packages are not maintained by us. Please try one of the other AUR packages, if none of them work then one of the official downloads that are maintained by us will probably work for you.

**Comment by bacteriostat** [comment]
Freetube(AUR) works just fine for me. This must be an issue specific to author's setup of Arch. I am using `freetube-bin` AUR package.
