### ISSUE TITLE
[Feature Request]: Improve typing on search: Do not mark the already written text when switching input language.

### ISSUE THREAD

**Issue by loveisfoss** [FreeTubeApp/FreeTube#2505]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Assume having FreeTube open and doing a search.
Assume that I want to write one word in one language and then change language and write another word.
If I press cmnd + space to switch language, the first word that I had written becomes marked and when I start typing the second word, the marked first word becomes replaced from the first letter of the second word.

### Proposed Solution

The first word should not become marked when switching input language. The aim is to write one word, switch the language and add the second word without the first word disappearing.

### Alternatives Considered

No alternatives.

### Issue Labels

ease of use improvement

**Comment by absidue** [comment]
When you focus the search box FreeTube, selects the existing contents so you can quickly type your new search query without needing to delete the old one first.

When you change input language the operating system you are using removes the focus from the search field and then focuses it again afterwards, that way it triggers the focus event handler on the search field so FreeTube selects the existing content for you.

As there is no good way for us to detect whether the focus was triggered by you manually focusing the search field or if the focus event was triggered by the operating system, we won't be able to implement the feature that you want.
