### ISSUE TITLE
[Feature Request]: Ability to view ID/URL of terminated channels

### ISSUE THREAD

**Issue by PAI5REECHO** [FreeTubeApp/FreeTube#2508]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I'd like to copy to be able to copy the URL of terminated channels so I may identify them

### Proposed Solution

Add a share button for terminated channels

### Alternatives Considered

Finding the channel ID from the application data directory/settings database stored somewhere on my computer

### Issue Labels

ease of use improvement, new feature

### Additional Information

Running view `v0.17.1`

**Comment by PAI5REECHO** [comment]
Checking the application database file and/or dev tools isn't user friendly. A simple Share button next to the Subscribe button would be useful for opening any channel in your browser whether it's suspended or not. Videos already have this type of ease of access, I don't understand why channels shouldn't have it too.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sound allot like https://github.com/FreeTubeApp/FreeTube/issues/1414
