### ISSUE TITLE
Feature Request: Remember player volume

### ISSUE THREAD

**Issue by 2n4z0Xt** [FreeTubeApp/FreeTube#252]
It would be really cool to add a "Remember player volume" feature, or a simple option to set the volume from the Settings (Like Invidious).

This is really annoying to change the volume all time. (even more when the volume is way too loud)

**Comment by PrestonN** [comment]
FreeTube currently persists your set volume during your session, but will reset to 100% when you restart the application.  I can add a default to the settings screen for volume, however I wouldn't be keen on forcing that volume if you've changed the volume in your current session.

**Comment by PrestonN** [comment]
Added in latest release.
