### ISSUE TITLE
[Feature Request]: Optional Google Account integration for livechat/comment

### ISSUE THREAD

**Issue by Hasunemiku2015** [FreeTubeApp/FreeTube#2529]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I understand that this software is designed to prevent YouTube and Google from tracking on our usage.

However , it would be great that we could comment or live chat on YouTube with your software instead of opening a new browser to do so.

### Proposed Solution

I would propose to use the google API to ONLY post comments and live chat. It would be great to add a optional (default disable) setting that allows users to enable.

An account pool could also be implemented to allow users to select different accounts to comment on a video.

### Alternatives Considered

I have considered opening a new browser and logging into my google account that way.

It might be strange , but I am using the ungoogled chromium as my browser and it could not play some videos and livestreams , I am using this app to play such videos.

I am sure it would be more convinient to allow users to comment directly from the app.

### Issue Labels

new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We wouldnt even consider it even if it was optional. FT is a privacy first application. This doesnt enhance user privacy. So we wont implement this.
