### ISSUE TITLE
[Bug]: Title inconsistency between watch and ft-list-playlist

### ISSUE THREAD

**Issue by MarmadileManteater** [FreeTubeApp/FreeTube#2530]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Navigate to a playlist which uses Japanese in the video titles. EX: [PLB6Mfu4v-kdUKpNVGykSxx5CpnTP2_rcB](https://youtube.com/playlist?list=PLB6Mfu4v-kdUKpNVGykSxx5CpnTP2_rcB)
2. Click play on one of the videos

The title under the video is different than the title displayed in the playlist.
![image](https://user-images.githubusercontent.com/106682128/188131058-abe1496d-8323-4bf0-b274-10f0cc15e985.png)

### Expected Behavior

The expected behavior is just that these titles match, not that they are specifically one version. This might involve using the user's locale preference to determine which to display.

This is what I expect it to look like:
![image](https://user-images.githubusercontent.com/106682128/188131168-99f34e81-cce0-4580-a688-73fece57f809.png)

I could also expect it to look like this:
![image](https://user-images.githubusercontent.com/106682128/188139226-308227bb-ae0d-42d7-b023-88b4806ac977.png)

### Issue Labels

API issue, text/string issue

### FreeTube Version

v0.17.1

### Operating System Version

Windows 10 Pro Version 21H2 Installed on ‎4/‎3/‎2022 OS build  19044.1889 Experience	 Windows Feature Experience Pack 120.2212.4180.0

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

This issue has to do with the response from the APIs. It seems that they always hand back a romanized version of the title when requesting a playlist, but they hand back a non-romanized version of the title when requesting a video directly.

[Response from the Invidious API for a single video](https://invidious.sethforprivacy.com/api/v1/videos/iLp1wjlNSm8?fields=title&pretty=1)
```json
{
  "title": "私、能力は平均値でって言ったよね! OST (CD 1) ~ 01.ティルス王国の王都!"
}
```
[Reponse from the Invidious API for a playlist](https://invidious.esmailelbob.xyz/api/v1/playlists/PLB6Mfu4v-kdUKpNVGykSxx5CpnTP2_rcB?pretty=1)
```json
"videos": [
  {
    "title": "Watashi, Nouryoku wa Heikinchi dette Itta yo ne! OST (CD 1) ~ 01. Tyrus Oukoku No Outo!",
```

Response from local API for a video
![image](https://user-images.githubusercontent.com/106682128/188137695-abf3ca70-b3ab-484a-8e0a-aee4b53f54a3.png)

Response from local API for a playlist
![image](https://user-images.githubusercontent.com/106682128/188133830-dbf1d644-c4f5-4cd5-9b1f-a2d5cae03c54.png)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
**Local API**
For the Local API sends the user's language while fetching playlists but sends `en-US` while fetching video info, I presume this is so that FreeTube's parsing works (FreeTube does a lot of information extraction itself as the stuff that ytdl-core extracts isn't always the way we want or need it).

Before someone implements sending of the user's chosen language for the video info fetching with the local API, they will need to verify that none of the info extraction/parsing fails if the language is anything other than `en-US`.

**Invidious API**
FreeTube doesn't inform the Invidious API about the user's language.

The Invidious API docs mention that you can use the `hl` query parameter to localise requests, which probably accepts the same values as YouTube itself.
> All endpoints that return a JSON body support &hl=LANGUAGE for translating fields into the desired language.
https://docs.invidious.io/api/

**Comment by MarmadileManteater** [comment]
This confused me at first. It is correct that, in FreeTube, `ytdl-core` always uses `en-US` when fetching video info, but reading that, it didn't make any sense to me based on what is happening. If `en-US` is used as the locale, I would expect the title below the video to always be the romanized version (instead of always being the Japanese version) and the problem to be reversed. 

I believe the underlying issue here is that `ytdl-core` isn't always fetching the same video titles as `ytpl` even when the locales match. I created a [small gist](https://gist.github.com/MarmadileManteater/5e59345b205e1480ace104d3ee9e0c50) to demonstrate what I am talking about. When I set `nl` as the locale, the titles all match, but when I set `en-US` as the locale, `ytpl` gives back romanji, and `ytdl-core` gives back Japanese. This means that if someone was to wire up `ytdl-core` to use the user's locale instead of `en-US`, it would not solve this problem.

With regards the Invidious API, I was unaware of the `hl` query parameter. It doesn't seem to address this issue with romanization, and/or it just doesn't work, and/or the documentation is out of date and it works differently than I expect. I used [locale codes from the documentation](https://github.com/iv-org/invidious/blob/0.17.0/src/invidious.cr#L63-L75) , so I am pretty sure I'm not just getting tripped up.

[Response from the Invidious API for a single video (with hl set to en-US)](https://invidious.namazso.eu/api/v1/videos/iLp1wjlNSm8?fields=title&hl=en-US&pretty=1)
(expected romanized)
```json
{
  "title": "私、能力は平均値でって言ったよね! OST (CD 1) ~ 01.ティルス王国の王都!"
}
```
[Response from the Invidious API for a single video (with hl set to nl)](https://invidious.namazso.eu/api/v1/videos/iLp1wjlNSm8?fields=title&hl=nl&pretty=1)
(expected Japanese because there is no localization for nl)
```json
{
  "title": "私、能力は平均値でって言ったよね! OST (CD 1) ~ 01.ティルス王国の王都!"
}
```

[Response from the Invidious API for a playlist (with hl set to nl)](https://invidious.namazso.eu/api/v1/playlists/PLB6Mfu4v-kdUKpNVGykSxx5CpnTP2_rcB?fields=title,description,videos&hl=nl&pretty=1)
(expected Japanese because there is no localization for nl)
```json
  "videos": [
    {
      "title": "Watashi, Nouryoku wa Heikinchi dette Itta yo ne! OST (CD 1) ~ 01. Tyrus Oukoku No Outo!",
```

**Comment by absidue** [comment]
YouTube's title localisation is kind of black magic. Sometimes it uses the `hl` parameter, other times the `gl` (geolocation) parameter and other times it will use the location of the IP requesting the page. Other times it will use the [`Accept-Language`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) HTTP header.

**Comment by MarmadileManteater** [comment]
I was stepping through both `ytpl` and `ytdl`, and I discovered something.
`ytdl-core` actually returns 2 titles, but one is burried inside of the response.
![image](https://user-images.githubusercontent.com/106682128/188216029-e03f3b64-c7c2-48d9-801f-bd6af8a8b7bc.png)
`videoResponse.response.contents.twoColumnWatchNextResults.results.results.contents[0].videoPrimaryInfoRenderer.title.runs[0].text` contains a title which is more accurate to the locale than `videoResponse.videoDetails.title`.

I created [another gist](https://gist.github.com/MarmadileManteater/37b48376fcf250852f704fa1766bd4fa) which uses that property, and it is able to verify that the title inside of that property matches the title returned by `ytpl` (for locales `en-US` and `nl`). This could potentially be a workaround to using `.videoDetails.title` which might fix this problem (for the local API).

If one were to replace line 279 of `src\renderer\views\Watch\Watch.js` with:
```js
this.videoTitle = result.response.contents.twoColumnWatchNextResults.results.results.contents[0].videoPrimaryInfoRenderer.title.runs[0].text
```
The video title will be localized to en-US (like it is expected to be):
![image](https://user-images.githubusercontent.com/106682128/188220211-38ccc5db-a411-4dc3-9147-c88aee1e1d7e.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is https://github.com/FreeTubeApp/FreeTube/issues/1801 the same issue as this one? if will close that one in favor of this issue.

**Comment by MarmadileManteater** [comment]
It appears to be the same issue.

**Comment by absidue** [comment]
@MarmadileManteater Sounds like a good fix, feel free to PR it.
