### ISSUE TITLE
[Bug]: Quality in FreeTube seems worse than on web with same resolution

### ISSUE THREAD

**Issue by kgorol** [FreeTubeApp/FreeTube#2543]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Web version:
![image](https://user-images.githubusercontent.com/34159482/188556554-18faa289-e467-4266-bd67-5de46ef0fb2b.png)
FreeTube version:
![image](https://user-images.githubusercontent.com/34159482/188556597-82b46bb7-8ec5-437d-a51d-32938d7767f4.png)

### Expected Behavior

Video quality on FreeTube should be much better.

### Issue Labels

visual bug

### FreeTube Version

v0.17.1 Beta

### Operating System Version

Windows 10 21H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by m-gohary** [comment]
yup , i can clearly see a difference in quality between freetube instance and normal youtube one , 480p looks way worse on freetube , i guess its the same for the rest of the qualities , but u can see it distinctly in lower qualities such as 480p

**Comment by F-I-R-E-F-O-X** [comment]
I've noticed that even when selecting a different resolution manually the video may stay at a lower res for whatever reason. Maybe this is happening because the video is trying to catch up the download of the higher res video? No idea. The player should lock in to a resolution if someone selects it manually though.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I'm going to close this issue in favor of #2013 

More explanation regarding this can be found https://github.com/FreeTubeApp/FreeTube/issues/2013#issuecomment-1564000972

**Comment by humble-codes** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc why did you close this issue ?
