### ISSUE TITLE
[Bug]: Localized separators

### ISSUE THREAD

**Issue by milotype** [FreeTubeApp/FreeTube#2547]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

![Localized decimal](https://user-images.githubusercontent.com/43657314/188953846-72c93f71-2cbe-4ffc-ae18-1eadfa618bb2.png)

### Expected Behavior

Use localized decimal separators ...

### Issue Labels

visual bug

### FreeTube Version

v0.17.1 Beta

### Operating System Version

Mac OS 10.11.6

### Installation Method

.dmg

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
looks like the date isn't being shown properly either
