### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by tiotrom** [FreeTubeApp/FreeTube#255]
For the past 2 days or so no video loads. Manjaro Gnome. Is this an isolated case?

EDIT: Works in Video Popup but not normal mode....

**Comment by PrestonN** [comment]
Hey there.  What version are you on? v0.5.3 should fix the issue.  If it doesn't, try going back to v0.5.2 and see if that works.

**Comment by tiotrom** [comment]
Ok I switched to 0.5.3 and it works now. Thanks! I was using 0.5.2 beta

**Comment by PrestonN** [comment]
Great! Glad that fixed it for you.
