### ISSUE TITLE
Flickering black bars

### ISSUE THREAD

**Issue by BaumGuard** [FreeTubeApp/FreeTube#256]
When I use FreeTube for a while, and scroll through the video suggestions, there are always black bars, which appear in different places on the screen and disappear when I scroll ahead. So there is sometimes unpleasant flickering on the screen. It first ends when I restart FreeTube.

I use the version 0.5.3 Beta, but I had that problem also in older versions.
I installed the package freetube-bin on Manjaro Linux. My desktop environment is KDE Plasma.

**Comment by ChenDanCMU** [comment]
Same issue here. I am using Linux Mint 19 with xfce.

**Comment by BaumGuard** [comment]
@ChenDanCMU I think the problem is caused by a graphical environment of linux. In the past I had problems with KDE Plasma because it sometimes started flickering.

**Comment by PrestonN** [comment]
Does this problem still happen?  I can't seem to replicate this on my end.

**Comment by BaumGuard** [comment]
@PrestonN I don't know. I haven't used FreeTube for a longer time now.

**Comment by PrestonN** [comment]
If that's the cause then I will go ahead and close this issue.  If anyone sees the problem again feel free to open a new issue.
