### ISSUE TITLE
[Feature Request]: Trending Channels

### ISSUE THREAD

**Issue by mewcrazy** [FreeTubeApp/FreeTube#2564]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Hey,
I spent a whole lot in FreeTube now. It's almost a perfect replacement for YouTube.

One thing I really miss though:
- Channels (Trending Channels)

I'd love to see those in a feature version of FreeTube.

### Proposed Solution

- Simple categorizing of playlists
- RSS feed integration of popular channels? Or a generated list of channels based on the 1000 most popular videos or so?

### Alternatives Considered

1) Only alternative I found is to download them all, which is sad
2) [-](https://socialblade.com/youtube/top/category/education)

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Where can i find trending channels on YT?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Also the playlist issue is requested in multiple issues. Please remove that from the issue body. We dont want users to request multiple features in one issue.

**Comment by mewcrazy** [comment]
True. I just removed it.

I was thinking about something like this: https://socialblade.com/youtube/top/category/education

Not sure if it's possible or useful for others.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
So just to be clear this trending channels list isnt from YouTube itself? It is generated by socialblade?

**Comment by mewcrazy** [comment]
I had some time to take another look at it. YouTube offers a lot of categories to filter the videos. For example on the homepage:

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Will stay closed because duplicate of #1582
