### ISSUE TITLE
In Manjaro Gnome no proper icon or ability to add to favorite

### ISSUE THREAD

**Issue by tiotrom** [FreeTubeApp/FreeTube#257]
Like the title said, this new version doesn't seem to have a proper icon when the application is open, neither you can pin to the favourites bar.

**Comment by Brn9hrd7** [comment]
I have noticed the same issue when using the AUR package, it doesn't happen when using the flatpak version though.

**Comment by PrestonN** [comment]
This should be fixed in the latest release.  Please re-open this issue if the problem still exists.
