### ISSUE TITLE
[Bug]: FreeTube is not playing audio

### ISSUE THREAD

**Issue by iam01110011** [FreeTubeApp/FreeTube#2570]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

I was listening to freetube on ubuntu and was playing as usual. then out of nowhere - the sound stopped. i am listening via bluetooth speaker. ensured was not the speaker. nor the computer - makes appropriate sounds otherwise, will play music files etc just fine. Freetube only is not playing sound. reinstalled freetube. restarted computer. problem still persists

### Expected Behavior

Sound to be played 

### Issue Labels

feature stopped working

### FreeTube Version

0.17.1 beta

### Operating System Version

ubuntu studio

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.17.1 beta (was working earlier today)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
Does this match the issue you're having? https://github.com/FreeTubeApp/FreeTube/issues/2540

**Comment by iam01110011** [comment]
this issue can be closed - after some digging around in my system controls it seems somehow streaming volume alone had been deactivated in the actual system settings (not the foggiest how - or that this was even possible!) so once i changed that, all was good once again! 

sorry for the non issue!
