### ISSUE TITLE
[Bug]: "Invalid date" after manually marking video watched from Subscription tab

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#2579]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. go to subscription tab
2. click menu button for any video
3. mark as watched
4. go to history tab
5. release date of video is listed as `invalid date`

### Expected Behavior

1. go to subscription tab
2. click menu button for any video
3. mark as watched
4. go to history tab
5. release date of video is listed as a valid date e.g `9/16/2022`

This behavior is seen if is at step 2+3 you click into the video, instead of manually marking it as watched  

### Issue Labels

text/string issue

### FreeTube Version

v0.17.1 Beta

### Operating System Version

Debian 11.5

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Reopened this, as I ended up implementing it in the linked pull request. The next time this issue is closed, it will be because that pull request got merged :).
