### ISSUE TITLE
New videos for some subscribed channels do not show up

### ISSUE THREAD

**Issue by HairyMilkshakes** [FreeTubeApp/FreeTube#258]
Noticed this issue starting when I updated to the current latest version as of this writing - new videos for subscribed channels don't show up when I refresh the sub tab. I have to manually check each channel for updated content to find them.

**Comment by PrestonN** [comment]
I'm having trouble replicating this?  Do you have an example?

As a reminder, clicking on the Subscriptions button will only refresh your subscriptions once every 2 hours.  You can manually update your subscriptions by clicking on the refresh button at the top nav bar.

**Comment by pawlosck** [comment]
I am not sure if this is the same problem, but I have similar problem.
I subscribed channel "Astrofaza" and FreeTube doesn't show at least one episode -> "Kosmiczna Turystyka - Astrofaza LIVE".
I removed all settings and subscribed this channel again, but this episode is not visible again.
This episode is visible via website and via NewPipe.
Episode uploaded 2016-04-16.

**Comment by HairyMilkshakes** [comment]
> I'm having trouble replicating this? Do you have an example?
> 
> As a reminder, clicking on the Subscriptions button will only refresh your subscriptions once every 2 hours. You can manually update your subscriptions by clicking on the refresh button at the top nav bar.

Unsure steps to reproduce. All I did was subscribe to a bunch of channels (17) and then some of the new videos uploaded wouldn't show up until I check their channels one by one by clicking on their names on the bottom right.

**Comment by PrestonN** [comment]
Apologies for the late reply.  When you subscribed to the new channels, did you refresh your feed by hitting the refresh button in the top left corner?  That might be why you don't see them right away.
