### ISSUE TITLE
[Bug]: error while loading shared libraries: libFLAC.so.8

### ISSUE THREAD

**Issue by UltraBlackLinux** [FreeTubeApp/FreeTube#2583]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Start Freetube
2. See missing-lib error

### Expected Behavior

It should start

### Issue Labels

causes crash

### FreeTube Version

0.17.1-1

### Operating System Version

Garuda Linux

### Installation Method

AUR

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.17.1-1

### Additional Information

This does appear to be a local issue and it's happening since I updated yesterday. I am only posting this here, because there do not appear to be legacy-flac packages that still contain libFLAC.so.8 and FreeTube seems to depend on it. (libFLAC.so.12 is the version the flac codec package provides)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by UltraBlackLinux** [comment]
Might  be an issue with the chaotic aur using an old version of libFLAC, currently waiting for their response

**Comment by UltraBlackLinux** [comment]
build problem maybe

**Comment by UltraBlackLinux** [comment]
They did trigger a rebuild, but it's still not working. Judging by the freetube-git package on the aur, a switch from electron 16 to electron 20 was made.

The only way I managed to run freetube was by forcing electron 20 via `electron /usr/lib/freetube/app.asar`

**Comment by taivlam** [comment]
I am also experiencing this issue on Manjaro Linux (Unstable branch, so on par with native Arch Linux packages) and I've updated Pacman today.  (I was about 1 week overdue with a system update, which is probably why I now only started to see this error.)

The `$ electron /usr/lib/freetube/app.asar` workaround from @UltraBlackLinux does make FreeTube work.

**Comment by absidue** [comment]
@UltraBlackLinux @taivlam This is definitely an issue with the AUR package, not with FreeTube, please report it to the maintainers of said package. It's unofficial so we don't maintain it, so it's not something we can fix on our end.
