### ISSUE TITLE
Enhancement: Put video in mini-player back into main window

### ISSUE THREAD

**Issue by avamk** [FreeTubeApp/FreeTube#26]
Hello again,

In order to keep a video playing while doing other things (searching, subscribing, etc.), I move the playing video into the mini-player first. However, AFAIK there's no way to put the mini-player video *back* into the main window once I've navigated away from it in the main window? If so, I think being able to do so would be a big improvement.

**Comment by PrestonN** [comment]
This is something that I want to look into, but the way you've mentioned could make it complicated.

Others have suggested keeping the video in a small window on the bottom left of the app as you're navigating around the application.  If the user has multiple videos in the mini player, it could get annoying if they are closing them out one by one.

Another suggestion that's been mentioned is having tabs, I feel like this would be the most intuitive solution out of all of them.

I'd like to see what others think and what route FreeTube should go with solving this issue.

**Comment by avamk** [comment]
> Another suggestion that's been mentioned is having tabs, I feel like this would be the most intuitive solution out of all of them.
I really like this idea, and it would solve the issue I'm talking about. Maybe as part of the tab functionality, let users choose between "open in current tab" and "open in new tab"?

**Comment by Randshot** [comment]
I also like the idea of having tabs. This is the only issue I have with FreeTube at the moment, since switching between (watching) videos and the subscription window always resets the position to the top, since there is no real (browse) history being kept (excluding when searching).

**Comment by Archive5** [comment]
But tabs only help to solve eg: search anything in new tab

@PrestonN Implement something similar below,
When user click settings, history, subscriptions etc then maximize a window to right side expanding contents on selected component and user can do whatever want but video remain playing under it then after that able to collapse back.
If user pick a video to watch then open it in new tab.

**Comment by Archive5** [comment]
Regarding miniplayer, it must be something similar this #466 or check skype desktop latest version with video call.
