### ISSUE TITLE
Invalid OPML

### ISSUE THREAD

**Issue by mouarfff** [FreeTubeApp/FreeTube#260]
Hello

thx for this app !

I try to import rss from RSSbandit and akkregator and i have alway "invalid format import unseccesfull" (opml exported from RSSbandit 1.9.0.1002 and Akkregator 5.11 on manjaro linux)

**Comment by PrestonN** [comment]
Hello!

Currently FreeTube does not support exporting subscriptions from RSS.  FreeTube currently only supports export files from YouTube (.ompl), FreeTube (.db), or NewPipe(.json).  Other formats can be up for consideration though so I will keep RSS in mind for future updates.

**Comment by mouarfff** [comment]
Ouch !

Ok thanks for your response :)

i hope it' will be possible in the future ^^

regards
