### ISSUE TITLE
There was an error calling the Invidious API.

### ISSUE THREAD

**Issue by DanielValahul** [FreeTubeApp/FreeTube#261]
Hello,
Before i start, I know there was another issue opened on this, but that was closed, and that fix doesn't do anything for me. The app unfortunately doesnt work, and I dont know where the problem is. I get the message from the title everytime i try to search or even open the trending page. Is there any fix I can try? I really want to use this app because it seems to have more features than the youtube website.
I'm using the latest beta (0.5.3) and my current invidious instance is https://invidio.us

**Comment by PrestonN** [comment]
Hello.  As you can tell, the error message is a little vague so it's hard for me to pinpoint the issue with the current information I have about your situation.  If you could please follow the instructions from [this post](https://github.com/FreeTubeApp/FreeTube/issues/249#issuecomment-479212710) and let me know what it says then I should be able to help you further.

**Comment by DanielValahul** [comment]
Hello,
```settings.js? [sm]:131 Object
vue.js:8542 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.js:8553 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
api.github.com/repos/freetubeapp/freetube/releases:1 Failed to load resource: net::ERR_NETWORK_ACCESS_DENIED
updates.js? [sm]:60 Uncaught ReferenceError: fail is not defined
    at Object.<anonymous> (updates.js? [sm]:60)
    at fire (C:\Users\danie\AppData\Local\freetube\app-0.5.3\resources\app\node_modules\jquery\dist\jquery.js:3291)
    at Object.fireWith [as rejectWith] (C:\Users\danie\AppData\Local\freetube\app-0.5.3\resources\app\node_modules\jquery\dist\jquery.js:3421)
    at done (C:\Users\danie\AppData\Local\freetube\app-0.5.3\resources\app\node_modules\jquery\dist\jquery.js:9525)
    at XMLHttpRequest.<anonymous> (C:\Users\danie\AppData\Local\freetube\app-0.5.3\resources\app\node_modules\jquery\dist\jquery.js:9767)
invidio.us/api/v1/trending/?region=US:1 Failed to load resource: net::ERR_NETWORK_ACCESS_DENIED
youtubeApi.js? [sm]:54 Object
youtubeApi.js? [sm]:55 error
youtubeApi.js? [sm]:56 https://invidio.us/api/v1/trending/?region=US
```
This is the log I get.

**Comment by PrestonN** [comment]
The error seems to involve the `net::ERR_NETWORK_ACCESS_DENIED` message.

Do you have any program on your machine or network running that may block connections?  It seems like the configuration may need to be changed on that in order for FreeTube to function.

**Comment by DanielValahul** [comment]
Yes, it was the Antivirus (Bitdefender) which was blocking the app. However, before I posted this I checked the logs and there was no request that the app tried to access the internet. I will report the issue to them since the first time I tried to install the app it marked it as a trojan. Thank you for your help!
PS. There's only one executable which should be whitelisted, right? (FreeTubeApp.exe)

**Comment by PrestonN** [comment]
It's unlikely that any virus protection would whitelist FreeTube at it's current state.  It has to do with the fact that right now the Windows version is not signed, which is required for it to not be alerted by virus protection.  Any attempt to whitelist it beforehand would likely be a security hole as any application named "FreeTubeApp.exe" could be used for malicious intentions.  There is currently no way to confirm that the .exe comes from the trusted source so having a signed certificate along with the application usually fixes this.  It's rather expensive for this certificate so that is why I haven't attempted to get one yet.  The hope is to get one around the time FreeTube hits a stable 1.0.0 release.

Since this issue seems fixed, I will close this thread.
