### ISSUE TITLE
[Feature Request]: Ongoing LIVE streams to DISPLAY it's going (a red "LIVE"?) on the default subscribed channels view list

### ISSUE THREAD

**Issue by heidiwenger** [FreeTubeApp/FreeTube#2625]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

You can only see the live broadcast of subbed channel is ongoing by going specifically to that channels page. 

### Proposed Solution

To make subscribed channels LIVE broadcasts show on the main page (where subsciptions are all listed). Or is this a bug? Live broadcasts should show?

### Alternatives Considered

Makes also the UPCOMING live broadcasts or the subbed channel show?

### Issue Labels

new feature

**Comment by Aiz0** [comment]
Live videos and premieres do show up in the subscription page.
They are however sorted by date, So you may have to scroll down a bit depending on when the stream started and how many videos where uploaded after it started.
I do agree that they should be moved up or listed separately.

Or do you mean that "Live" should be displayed on top of / below Channel-thumbnail / profile picture?
