### ISSUE TITLE
[Feature Request]: Export format that is really compatible with newpipe

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#2628]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I exported my subscriptions list in all available formats, but no one, including so called "newpipe format" is compatible with the said app.

The real newpipe format
[NewPipeData-20220927_102736.zip](https://github.com/FreeTubeApp/FreeTube/files/9653585/NewPipeData-20220927_102736.zip)

The so-called freetube's newpipe format (the real file format is json)
[newpipe-subscriptions-2022-09-27.txt](https://github.com/FreeTubeApp/FreeTube/files/9653610/newpipe-subscriptions-2022-09-27.txt)

### Proposed Solution

An export function that creates a format compatible with newpipe.

### Alternatives Considered

none

### Issue Labels

improvement to existing feature

**Comment by ChunkyProgrammer** [comment]
Hi, I think you're trying to import settings not subscriptions. To import subscriptions you:
1) go to your subscriptions
![newpipe1](https://user-images.githubusercontent.com/78101139/192631756-d7b75085-ccf7-4986-8d20-e06ec51902f9.png)

2) click the 3 dots
![newpipe2](https://user-images.githubusercontent.com/78101139/192631805-b6089ba6-b13a-42f8-ade1-0ae1a6c8babc.png)

3) click "import from" then "previous export"
![newpipe3](https://user-images.githubusercontent.com/78101139/192631846-07d08723-3d52-467e-aa05-596c33358133.png)


Source: https://newpipe.net/FAQ/tutorials/import-export-data/

**Comment by ChunkyProgrammer** [comment]
Closing as NewPipe supports the file we generate
