### ISSUE TITLE
There should be a hardcoded default list of invidious instances

### ISSUE THREAD

**Issue by pkrasicki** [FreeTubeApp/FreeTube#2629]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Yesterday I was unable to use FreeTube, because the website https://api.invidious.io would only return an empty list of instances. This issue seems to be fixed now, but it was like that for 10+ hours. I don't know why that happened and I understand it's not a bug in FreeTube, but I was still not able to use the app. I could have tried switching to the local api, but I suspect an average user might have a problem with figuring that out.

![freetube-no-instances-screenshot](https://user-images.githubusercontent.com/49721209/192532603-6cff2f37-6a18-49d8-b121-f4e249dcb629.png)

### Proposed Solution

Perhaps there should be some default list of invidious instances in the app? Then users would still be able to use FreeTube with invidious even when there is a problem with the api.

### Alternatives Considered

None.

### Issue Labels

ease of use improvement

### Additional Information

I don't know how those default instances should be selected or how the list should be maintained.

**Comment by absidue** [comment]
There is a fallback list but because of a bug in FreeTube (apparently solved in https://github.com/FreeTubeApp/FreeTube/pull/2626) it wasn't falling back to them properly.
