### ISSUE TITLE
[Feature Request]: Ability to select resolution of video for external player.

### ISSUE THREAD

**Issue by Rustbread** [FreeTubeApp/FreeTube#2630]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I cannot set resolution that external player uses.

### Proposed Solution

Ability to select resolution of video external player will use.

### Alternatives Considered

Default Quality from Player Settings might be used instead of creating separate setting in External Player Settings.

### Issue Labels

display more information to user, ease of use improvement, new feature, new optional setting, support for external software

### Additional Information

Currently it opens best available quality, with might not be the desired quality.

**Comment by absidue** [comment]
FreeTube just passes the YouTube link (e.g. `https://www.youtube.com/watch?v=dQw4w9WgXcQ` or for players that support it `ytdl://dQw4w9WgXcQ`) to the external player, what the external player does with that link is up to them. Some players like mpv allow you to configure which quality is selected in their configuration file (https://mpv.io/manual/stable/#options-ytdl-format).
