### ISSUE TITLE
[Feature Request]: Shortcut to refresh subscriptions (R)

### ISSUE THREAD

**Issue by Aiz0** [FreeTubeApp/FreeTube#2631]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I often refresh my subscriptions with `CTRL + R` but this reloads the entire view and is therefore slower than just refreshing the subscriptions.

### Proposed Solution

I would like a shortcut key for the `refresh subscriptions` button.
`R` would be my recommendation, Since it's already used with modifiers to reload the app.

### Alternatives Considered

Refreshing just the subscriptions with  `CTRL + R` might be better, i'm not sure.
Since the plan is to replace all other refresh buttons with https://github.com/FreeTubeApp/FreeTube/pull/1578 a shortcut for that would be preferable. There hasn't been any updates to that for about a year now since the rework was planned so I don't know how it would reload the subscription page.

### Issue Labels

ease of use improvement, new keyboard shortcut

### Additional Information

Other relevant issues.
https://github.com/FreeTubeApp/FreeTube/issues/1966

**Comment by Aiz0** [comment]
I could work on this.
Do I need to open a PR to add the new shortcut to documentation as well?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
yes please

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Aiz0 would u maybe like to give the reload button PR a shot?

**Comment by Aiz0** [comment]
> @Aiz0 would u maybe like to give the reload button PR a shot?

At the moment, no, later maybe.
I don't really know what the reload button should do and I might have to read some electron and vue documentation before knowing how to do it 😅

If you can post a feature spec or something that would be a good starting point for me and others to try to implement it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
maybe u can look into https://github.com/FreeTubeApp/FreeTube/issues/2138#issuecomment-1073724876 because it is shortcuts related
