### ISSUE TITLE
Fix "This video is not available in your country"!

### ISSUE THREAD

**Issue by cyberchief1984** [FreeTubeApp/FreeTube#265]
It's really annoying that some videos are blocked in my country, Serbia. Can you fix this?

**Comment by stemy2** [comment]
Same problem, but with videos i can view on youtube or invidious without blocking. It doesn't make any sense.

**Comment by rickndmorty** [comment]
Can confirm; seems to be happening randomly and has nothing to do with actual country. Maybe make additional requests if it returns that.

**Comment by PrestonN** [comment]
Hey everyone.  Give the new release a try.  There is a toggle that can be used to pick whether the video URLs come from Invidious or grabbed locally.  Play around with it and see if that works.

**Comment by cyberchief1984** [comment]
It works fine now.

**Comment by cyberchief1984** [comment]
Still doesn't work on some videos, what's wrong?
