### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lephemere** [FreeTubeApp/FreeTube#2652]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Go to Settings
2. Got to Parental Control Settings
3. Enable Hide Unsubscribe Button

Now the Unsubscribe button is hidden, however the Subscribe button on channel not subscribed to yet is also hidden.

### Expected Behavior

Would expect to have the Subscribe button available.

However, as it is a parental control setting, the expected behavior is probably to prevent messing with subscription list. Hence, probably just changing the label to something like `Hide Subscribe and Unsubscribe Buttons` would make it more explicit.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.17.1 Beta

### Operating System Version

5.15.65-1-MANJARO

### Installation Method

AUR

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is intended behavior and not a bug.
