### ISSUE TITLE
[Feature Request]: Use FSR to upscale videos with low resolution

### ISSUE THREAD

**Issue by Elendil211** [FreeTubeApp/FreeTube#2654]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Videos with low resolution look bad when watched on a bigger screen.

### Proposed Solution

Use AMD FSR Super Resolution to upscale the video. 

As a proof of work, I tried using FSR via gamescope. For example, to upscale a 240p video to 1080p, I used `gamescope -f -U --fsr-sharpness 2 -w 426 -h 240 chromium`, and manually set the video quality to 240p. I used chromium, because starting FreeTube with gamescope didn't work for me. In my opinion, videos that are upscaled with FSR look much better than videos that are not upscaled, however the result does depend on the video.

Screenshots: https://imgur.com/a/xxNtbrC

The video: https://youtu.be/8IawVGRlLm0

The left side is with FSR, the right side is without FSR.

What I find particularly impressive:
- The blue lines on the bottom left of the first image
- The company logo on the keyboard in the third image

### Alternatives Considered

It might be better to make this an optional setting, instead as the default handling. FSR does have some CPU overhead, and even though it is not much, it might be a problem for some weaker systems.

### Issue Labels

new feature, new optional setting, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Integrating FSR into FreeTube will likely be very difficult and involve a lot of work, as we would either need to build our own versions of Electron or find some way of pre-processing the video inside of video.js before it's shown on screen.

**Comment by ChunkyProgrammer** [comment]
Might be better to open an issue for this on electron repo @Elendil211
