### ISSUE TITLE
[Feature Request] Let FreeTube out itself as a browser to the OS so that it can open YouTube URLs

### ISSUE THREAD

**Issue by hipunk** [FreeTubeApp/FreeTube#266]
Hi,

whenever I have a link in e.g. a chat window and wish to watch it in FreeTube, I have to copy and paste the URL into the search bar in FT and only then I can watch it. If FreeTube would out itself as a webbrowser to the OS, I could make FT the default app for YouTube links.
There is an application on macOS/Mac OS X called Bumpr. It resembles a copy of the default app chooser in Android: https://img.gadgethacks.com/img/00/33/63610067421515/0/redirect-links-android-open-app-you-really-wanted.w1456.jpg
This window pops up when clicking a `https://www.youtube.com/watch?xxxxxxxxx` URL: https://getbumpr.com/images/webapps.png
At the current point in time, FreeTube is missing from that list.

That's what I'm on about.

(Also: Can we remove those margins in the Mini-Player? I usually let that Mini-Player float on top of all other windows using Afloat and that border around the actual imagery is a totally unnecessary waste of screen estate.)

Great application, really enjoying it! Thanks!

Greetings,

hipunk

**Comment by Mhowser** [comment]
Is this what you are looking for? https://github.com/FreeTubeApp/FreeTube/wiki/Browser-Extension

**Comment by hipunk** [comment]
Sorry, but no.

**Comment by PrestonN** [comment]
I'm still not sure what's different from this request and the browser extension.  Either way, that might still be the better way than always hijacking browser calls.

**Comment by hipunk** [comment]
A browser extensions slows down the browser, duh.

**Comment by Mhowser** [comment]
A URL helper extension would be an extremely negligible burden on resources. This isn't like the Grammarly extension where it is always active.

**Comment by hipunk** [comment]
about:performance says it's always active though?
