### ISSUE TITLE
2 simple requests: background playing and folders 

### ISSUE THREAD

**Issue by wongfeihung1984** [FreeTubeApp/FreeTube#268]
Hi,

First of all, thank you for the fantastic job you've done creating this app.

If I may I'd like to request a few features:

1. Background playing when changing channels/videos...or why not a minimized player, like the one Freetube currently has but way smaller so that no manipulation would be required to get it out of the way, that would automatically open if a user clicked on another video or channel

2. Sorting videos by categories: say I have subscribed to 10 channels that are Linux related, I'd like to be able to put them under a Linux folder, so that when I open that folder, I would get a list of channels from that folder to choose from, and when I choose a channel I would have displayed all the videos from that channel (and not the "home", "playlist", "channel", "discussion" or "about" tab)...if you consider implementing that PLEASE don't make it that when I click on one of my folders I get all the videos from that folder...if you wanted to you could implement that behavior when clicking on the "subscriptions" menu with toggles for displaying or not the videos for specific folders.

I have attached two photos of my youtube home page while using the Youtube subscription manager (https://yousub.info/) which is a fantastic addon...and yes, I'd love to see the way this addon organizes collection lists implemented in Freetube.

Regards

<img width="1258" alt="Capture d’écran 2019-06-03 à 23 24 34" src="https://user-images.githubusercontent.com/51026268/58835655-d461cf00-8656-11e9-9b1d-aa044a1b5e6f.png">
<img width="1265" alt="Capture d’écran 2019-06-03 à 23 23 53" src="https://user-images.githubusercontent.com/51026268/58835675-e5124500-8656-11e9-9938-3b1f7ea15a66.png">

**Comment by PrestonN** [comment]
Hey there!  I'm glad that you enjoy using FreeTube.

I believe both of these features have already been requested and are on the roadmap, so I will go ahead and close this issue for now.

Thanks a bunch for the pictures though.  These will be a good reference for when I get ready to work on subscription categories.  It may need to be included in v0.7.0 as I keep seeing it requested so I'd expect it to be included soonish.

**Comment by wongfeihung1984** [comment]
Oh you're most welcome! And thanks for your hard work. I can't wait for the following updates.
