### ISSUE TITLE
[Bug]:  Error: Invidious API Error:  Error:connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by deroverda** [FreeTubeApp/FreeTube#2693]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Can't view anything. Subscriptions tab is all empty. 

### Expected Behavior

It worked 2-3 hours ago. What can have happened?

### Issue Labels

API issue

### FreeTube Version

v0.17.1 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by deroverda** [comment]
![Free-Tube-0-BJPp-KZ9c5](https://user-images.githubusercontent.com/70813982/194761198-8b19143f-d1b9-4e07-8860-5196e547fb74.png)

Here's what it looks like.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi there could u send a screenshot of your settings

**Comment by deroverda** [comment]
Seems to work now.
