### ISSUE TITLE
Feature request: Select video/audio streams to download and mux

### ISSUE THREAD

**Issue by avamk** [FreeTubeApp/FreeTube#27]
Hello again,

A super useful feature would be to show the available video and audio streams for a video, and allow downloading them and muxing them together (such as you often need to do when downloading DASH streams) within the FreeTube interface. Is this possible? Thanks!

**Comment by PrestonN** [comment]
This should be coming in the future. It will probably come in a couple of waves before fully implemented. I still need to support WebM and Dash.

I'd like to incorporate some sort of download manager with FreeTube for downloading video and audio. This will most likely come later though.

**Comment by avamk** [comment]
> I'd like to incorporate some sort of download manager with FreeTube for downloading video and audio. This will most likely come later though.

This sounds perfect. Thanks for considering this! IMHO it would be a killer feature!
