### ISSUE TITLE
[Feature Request]: Additional Picture-In-Picture Controls (inspired by Firefox)

### ISSUE THREAD

**Issue by MintMain21** [FreeTubeApp/FreeTube#2715]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Over the course of the past year, Firefox has been rolling out numerous quality of life updates to their PiP feature to make it (imo) among the best among similar features in other browsers, apps, etc.

Most notably, subtitles are displayed in PiP, there is a mute button for PiP, and set to come down the pipeline later are fast-forward/rewind buttons for PiP.

All of these would be welcome in FreeTube.

### Proposed Solution

Add these features to PiP in FreeTube

### Alternatives Considered

The only applicable alternatives at present are to either use other video players (MPV, SMPlayer, etc) or to just use Firefox (which would require either using YouTube or another private frontend, which in turn has it's own cons compared to using FreeTube.

### Issue Labels

improvement to existing feature

### Additional Information

Here's what PiP looks like in the current Nightly builds of Firefox.

https://techdows.com/2022/09/firefox-picture-in-picture-video-seek-forward-backward-buttons.html

**Comment by absidue** [comment]
FreeTube uses the picture in picture functionality that is built into electron/chromium, so we can't make any changes to the picture in picture window, the changes will need to happen in the upstream electron or chromium projects.

We only have access to the standard web PIP API: https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API
