### ISSUE TITLE
[Feature Request]: hide specific channel videos

### ISSUE THREAD

**Issue by BENDER-V2** [FreeTubeApp/FreeTube#2718]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

As i continue to use freetube and discover channels that interest me, i find that looking at the subscriptions tab can tend to get over saturated and overwhelming and even distracting at times. I'd like to keep the channels there so i can access them easily but i don't want so much different content showing.

### Proposed Solution

Create a slider that when turned on will block that channel's videos from appearing in the subscriptions tab. The slider would appear on the channel's page.

### Alternatives Considered

Create a filter that when you add a channel to it, that channel's videos will not show up in the subscriptions tab.

### Issue Labels

new optional setting

**Comment by absidue** [comment]
Have you tried using FreeTube's profile feature? You could create two profiles, one for the channels you want to see in the subscriptions tab and another for the ones that you don't. That way you only have to see the other channels if you are in the "All channels" profile or have your bookmarks only one selected.
