### ISSUE TITLE
[Feature Request] Resume Playback

### ISSUE THREAD

**Issue by kvithayathil** [FreeTubeApp/FreeTube#272]
Not sure if this is already on the road map (or in the app), but whenever I navigate away from the current video and come back, the playback progress of the video resets and I have to manually seek back.

A method of caching progress (possibly making it portable between clients) would be nice to have.

**Comment by PrestonN** [comment]
Funny enough, this is already done and will be in the next release next Friday. Keep an eye out for when the release drops :)

**Comment by kvithayathil** [comment]
Awesome! Looking forward to it :) Thank you for the great work!
