### ISSUE TITLE
[Feature Request]: Hide sidebar

### ISSUE THREAD

**Issue by davidoskky** [FreeTubeApp/FreeTube#2724]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I very often take notes while watching videos, to do this I open another software and place it on the left of Freetube.
Since there is the sidebar on the left, some space on my screen is unused to show the sidebar.
Also the sidebar on the right is a problem but you can overlay the notepad so it is not too big of an issue.
I can move freetube of the screen to hide the sidebar, but doing that often is quite an hassle.

### Proposed Solution

Provide an option to hide the left sidebar so that the video is flush with the left border of the window.

### Alternatives Considered

I can use the PiP viewer to solve this problem, however there is no seekbar and thus navigating the video gets difficult.
At times I just download the video and play it in another video player.

### Issue Labels

ease of use improvement

**Comment by Aiz0** [comment]
Have you tried the full window mode? Shortcut key for it is <kbd>s</kbd>.

**Comment by davidoskky** [comment]
Wow, didn't know about this, sorry for the useless issue. This is exactly what I was searching for.
Disregard my original request, my objective can be accomplished in another better way.
