### ISSUE TITLE
Add 4 features 

### ISSUE THREAD

**Issue by KalpanaChetan** [FreeTubeApp/FreeTube#2725]
### Guidelines

- [ ] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [ ] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

1.please add scheduler 
 
2.Download video from a playlist in this method 
 
Create a folder (channel name) and create another folder (playlist name) inside it and a third folder (video number) inside it 
Video has to be downloaded in third folder 
Create a third folder (video number) for each video 
 
 
3. no video number
![2022-10-14 21_23_00-Window](https://user-images.githubusercontent.com/112402936/195977565-536f32df-f795-4e4c-8258-f821a7a0dcd6.png)

4. Option for open download folder
![2022-10-14 21_17_04-Window](https://user-images.githubusercontent.com/112402936/195977594-6b121acd-55c3-4a08-84a7-cb685b84e46b.png)

### Proposed Solution

Blank

### Alternatives Considered

Blank

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing this issue for breaking 2 guidelines.

1. Not filling in the template correctly
2. Creating multiple requests in one issues
