### ISSUE TITLE
[Feature Request]: Back, Foward, and reload keyboard shortcuts

### ISSUE THREAD

**Issue by quailmage** [FreeTubeApp/FreeTube#2738]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I think it would be useful to be able to go back to previous pages with a keyboard shortcut. I also think going to the next page would be useful. To be honest I use this for reloading the page when it gets stuck.

### Proposed Solution

As stated in the problem portion, I don't know what specific keys would be best, Shift J for previous page, Shift K for next page, r for reload.

### Alternatives Considered

The other thing to fix the reload problem would be to make so it never gets stuck, I may prefer that but it seams harder to solve that problem.

### Issue Labels

new keyboard shortcut

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
all these shortcuts are already implemented in the latest nightly build.

`r`: reloading every page with a reload button available (Subscriptions, trending and most popular page) 
`Ctrl + r` is to reload FT in the event u mentioned
`Alt + left key` is going back a page
`Alt + right key` is going forward a page

All shortcuts can be found at https://docs.freetubeapp.io/usage/keyboard-shortcuts/
