### ISSUE TITLE
[Bug]: using Picture-in-Picture on a video makes seek keyboard shortcuts to not work anymore

### ISSUE THREAD

**Issue by n3rd4i** [FreeTubeApp/FreeTube#2754]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Open any video
2. Mouse press (or button press)  Picture-in-Picture mode
3. Press keyboard for seeking (forward or backwards)  the video
4. Pressing the seek buttons has no effect anymore

### Expected Behavior

Using Picture-in-Picture should not break the existing [keyboard shortucts] functionality

### Issue Labels

usability issue

### FreeTube Version

v0.17.1 Beta

### Operating System Version

Debian GNU/Linux 10 (buster)

### Installation Method

.deb

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Just to check, this PR is about not being able to use keyboard shortcuts on the picture-in-picture window, not that the shortcuts are broken in the main window while picture-in-picture is active?

**Comment by n3rd4i** [comment]
bug was present in the main window and [future] picture-in-picture windows (after discarding the first picture-in-picture, regardless how was initiated, keyboard or mouse press). This seems to be fixed in v0.18.0 Beta.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@n3rd4i so this can be closed right?

**Comment by n3rd4i** [comment]
hi yes we can close this, seems to be fixed (from that version). thanks.
