### ISSUE TITLE
[Feature Request]: Allow scrolling while ignoring the media player

### ISSUE THREAD

**Issue by z8n19d** [FreeTubeApp/FreeTube#2759]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

If the option to control the volume by scrolling over the video is disabled, scrolling over it does absolutely nothing, including scrolling the page.

### Proposed Solution

Scrolling scrolls the page if it does not need to interact with the media player.

### Alternatives Considered

ERROR 404

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi there, could u open a bug report instead so we can get detailed info about this issue
