### ISSUE TITLE
How do you even launch freetube 0.6?

### ISSUE THREAD

**Issue by annadane** [FreeTubeApp/FreeTube#276]
I notice after unzipping that there's no more single folder, it's split between a bunch of stuff (it'd be nice to have one single top level directory for everything so the home directory doesn't get populated with stuff), but more importantly, when I try to execute the binary... "[29926:0615/091545.128362:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/annadane/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap"

**Comment by evpne** [comment]
If you want  a little workaround type into your Terminal "freetube --no-sandbox"

**Comment by annadane** [comment]
This can be closed now I guess (it was never an issue anyway, purely tech support question)
