### ISSUE TITLE
[Feature Request]: Activate and select subtitles automatically

### ISSUE THREAD

**Issue by z8n19d** [FreeTubeApp/FreeTube#2760]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Most of the content I view is not in my native language, which means I have to manually activate the subtitles with each video. Even though it is enough to press "c" to activate them, I have to spend more time to choose them manually, since they are always chosen by default translated english.

### Proposed Solution

Add an option in the configuration to activate them automatically when they are available.
Add an option to choose the language priority for subtitles.

### Alternatives Considered

Prefer by default the system language. This would also be great in a complementary way.

### Issue Labels

ease of use improvement, improvement to existing feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of #62

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could u clarify what u mean with second half?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It is not needed to open or edit this issue because if we implement this it will be included
