### ISSUE TITLE
Option to enable grid-based view for channel video list

### ISSUE THREAD

**Issue by Millichrome** [FreeTubeApp/FreeTube#277]
First of all, thanks for making this application. It has a lot of potential. 

In YT proper, a channel video page has a grid-view:

 https://i.imgur.com/0sgus1X.jpg

When I click on a channel page in FT, it seems you can only get a "list" view:

https://i.imgur.com/XTGRMrH.jpg

I personally find the grid view better for quickly picking a new video that interests me. It would be useful if you could hide the "about info" when clicking on a subscription entry in FT (chances are you already know about the channel you subbed too).

**Comment by PrestonN** [comment]
This has been requested before (might be a duplicate issue even) and it's planned.  I don't have an ETA but it should be happening soon.

**Comment by Millichrome** [comment]
Sounds good! Thanks for you work on FT! :)

**Comment by PrestonN** [comment]
This has been added with the latest release.  Go check it out :)
