### ISSUE TITLE
[Bug]: Videos loading slowly

### ISSUE THREAD

**Issue by gbeyer3** [FreeTubeApp/FreeTube#2781]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

When I click most videos, they clock (buffer) for a few seconds, and then play normally.  On other vidoes, upon clicking, the clocking goes on for minutes if I let it.  I eventually give up and select a different video, which usually plays as normal.  I get no error message/number.  I make no change to settings between tries.  Some vids just will not play.

On several problem vids, if I find them on YT via in my browser (FF 102.0) they play just fine, albeit with ads.

### Expected Behavior

I would expect all videos to play with minimal buffering.  I can understand a few seconds to load, but to clock for minutes, not.

### Issue Labels

content not loading, usability issue

### FreeTube Version

v0.17.0 Beta

### Operating System Version

LinuxMint Release Linux Mint 20.3 Una 64-bit, Kernel Linux 5.15.0-52-generic x86_64, MATE 1.26.012GB RAM

### Installation Method

.deb

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

v0.17.0 Beta  (intermittently)

### Additional Information

I just had a thought after submitting this issue.  Is there a FT setting to cause the player to limit buffering to arbitrary value, say 2 minute of vid, then start playing...then the vid continues to load in the background?  Thx  I am trying out nightly build 2167 to see if this problem might be resolved.  Will update the case if so.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).
YES - encountered the same problem on nightly build 2167

**Comment by absidue** [comment]
As you are using the Invidious API as the backend, this issue is probably due to slow Invidious servers, could you please check if you see the same issue occurs with the local API?

**Comment by gbeyer3** [comment]
Well, DANG, that fixed it!  I thought it was necessary to use an invideous server as that's what it was configured with when I installed it.  Thanks much!!
