### ISSUE TITLE
[Bug]: Open in external player (thumbnail) ignores history setting

### ISSUE THREAD

**Issue by 74naUM2EMP** [FreeTubeApp/FreeTube#2785]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Clicking the 'open in (external player)' option on a video thumbnail marks the video as watched, even if history is disabled. This doesn't happen if you open the video first and then select 'open in (external player)' from the video controls (beneath the views and likes).

### Expected Behavior

The video shouldn't be marked as watched in both cases if history is disabled.

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.17.1 Beta

### Operating System Version

Linux 5.19

### Installation Method

AUR

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by petaded** [comment]
I cannot reproduce this using version 0.17.0 app image or 0.18.0 app image

with "Remember history" setting as false
![image](https://user-images.githubusercontent.com/74797538/209362699-a04aa924-d304-4050-b410-220d53f7c77c.png)

Clicking triple dots -> open in Youtube ( or individious) 
![image](https://user-images.githubusercontent.com/74797538/209362760-c1ff47fe-6a42-4f72-a5c7-e30fb2d690b7.png)

Video remains unwatched, Is there something I'm missing?

**Comment by petaded** [comment]
Also tested adding vlc as external player - again remained unwatched.
![image](https://user-images.githubusercontent.com/74797538/209363411-e2d4d28b-7443-4d73-8284-0de7c9b58684.png)

**Comment by 74naUM2EMP** [comment]
I figured it out.
Before you disable "Remember History" you have to disable "Save Watched Progress" first (because it's greyed out after disabling "Remember History").
In the current version of FreeTube this is done automatically, so I probably imported this problem from an older version.
