### ISSUE TITLE
Disable power management while playing

### ISSUE THREAD

**Issue by Keplyx** [FreeTubeApp/FreeTube#279]
I am using Ubuntu 18.04 (Kde Neon), and when playing videos, if I do not move the mouse, the computer goes into sleep mode after a while.
Since I use Kde, I can easily disable power management to stop sleep mode, but it might not be the case for every distribution.

It would be very useful if you could tell the system not to use power management while playing a video.

**Comment by PrestonN** [comment]
There isn't an easy way to modify a user's power settings and I could see a lot of user's unhappy of an application doing that depending on their situation.  I think it's best to leave it up to the user as to how they'd like their computer to run.

**Comment by Ezwen** [comment]
My apologies to dig up this issue, but I encounter a similar problem with FreeTube : in GNOME my screen is configured to go black every 5 minutes, and FreeTube does not disable that. Therefore I must either regularly move my mouse while playing a video with FreeTube, or disable my OS screen saving configuration each time I use it.

Yet, when I use another video playing app such as VLC, Kodi, GNOME Video, or even Firefox (when putting an HTML5 video in fullscreen), I never have this problem, as I suppose these applications do tell the operating system to temporarily not use any screen saving?

Wouldn't it be possible to have something similar with FreeTube, ie. tell the OS to not do any power saving during a video playback?

(by the way thanks for FreeTube, a very neat app I have to say!)

**Comment by Ezwen** [comment]
After a quick lookup it seems there is standardized dbus procedure called "Inhibit" that can be used to disable power saving temporarily (eg. during video playback), and which should work on all Linux systems. See this example: https://stackoverflow.com/a/43531016

**Comment by sanecito** [comment]
Came here to chime in and say that I would also prefer my screen going to sleep when watching videos longer than 5 min. I feel like a compromise could be reached in situations where the device is at least plugged in to disable power saving.
