### ISSUE TITLE
[Bug]: Freetube fetches zero videos from subscription list

### ISSUE THREAD

**Issue by Publius1788** [FreeTubeApp/FreeTube#2796]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Freetube appears to be unable to fetch subscription content. Freetube can only fetch videos if you directly search for that specific video.

When I launch Freetube, I expect all latest videos from my subscription list to be shown. Instead, I get this message: Your Subscription list is currently empty. Start adding subscriptions to see them here."

If I click on any of the channels on my subscription list - expected behavior is to be brought to that channel's video content. While clicking on a channel does indeed bring me to that creator's splash page - Freetube reports "This channel does not currently have any videos"

If I search for any content creator - Freetube finds their channel, but again, reports "This channel does not currently have any videos"

Meanwhile, that search will also fetch individual videos from that same channel - Freetube WILL fetch/play that video if I click on it.

### Expected Behavior

I feel above description covers it well.

### Issue Labels

content not loading

### FreeTube Version

17.1 Beta

### Operating System Version

Windows 10

### Installation Method

.zip

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

17.1 Beta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ssnor** [comment]
I have the same problem except that I only get videos from one channel.

If I try to go directly to a channel it says "This channel does not currently have any videos" on every one.
If I change to using Invidious as preferred API backend I get a bunch of "Invidious API Error (Click to copy): undefined" scrolling and then it seems to default to fetching the feed trough RSS and I can see the videos in my subscription overview. 

A temporary workaround is to change to "Fetch Feeds from RSS" in subscription settings, though you have to give up the ability to see video length in the subscriptions overview.

This is on v0.17.1-nightly-2223 Beta, Fedora Linux 35.

**Comment by Fifty1980** [comment]
I have the same issue on arch linux. v0.17.1 beta

**Comment by Publius1788** [comment]
I might also add: I use Newpipe on my android device - and it quit working last night in more or less the same way Freetube has. I realize these two softwares use totally different approaches, but I suspect it implies that YouTube has changed their end. Hopefully the developers for NewPipe and Freetube get this patched quickly!

**Comment by t3dium** [comment]
also experiencing this issue, only appears to be a problem when using invidious

**Comment by nowakommunikation** [comment]
I have the same experience on macOS 10.11 - 10.14. To make sure it's not a mac issue I tried my Windows 7 setup. By now it also behaves strange and won't fetch from subscriptions. 

This bug has worsened over the last seven or ten days. At first some videos showed up in sub's, mostly older ones (like a year old). Some back and forth and clicking different channels and it would sometimes work again. 
Also I noticed with the SNL channel that I get shown only recent shorts (those 1 minute vids). But on the general "Subscriptions" page (that shows the latest of all sub's), also longer videos from the latest show poped up. But clicking on it wouldn't load it. 
At that point I still thought it was a geo-blocking issue (I'm in Germany, so they perhaps won't show all SNL content). 
But by now: NOTHING shows up in the subscriptions any more.

I can still search for videos or channels (SNL or CNN or so) in the top search bar and content will show up. SNL will still not play (with the time symbol not showing the length of the video but a -:- instead), but e. g. CNN videos do play. 

Strange. 

I have tried different instances of Invidious. No difference. 

Tethered to my phone's LTE network to make sure it's not my landline DSL or my Pi Hole etc. (which I had also deactivated during testing), but no difference. 

Tried my Skytube and Newpipe apps on my phone and tablet and they also won't load channels. They will however play videos from a direct search. 

Is this the beginning of the end of FOSS youtube players that circumvent ads?

**Comment by johnsd46** [comment]
I'm having the same problem in the UK. I've been seeing API errors for several days, now today when I select a channel it says "This channel does not currently have any videos".

The API error messages seem to be Javascript errors, and I think YouTube must have changed the format of the JSON data it provides. If so it should be fixable by a developer familiar with FreeTube.

**Comment by johnsd46** [comment]
Further to my previous comment I'm using FreeTube on Kubuntu linux, but if it is indeed a change made by YouTube the platform should be irrelevant.

**Comment by cathteg** [comment]
Having the same problem on Win10, Freetube 0.17.1 Beta. The last few days have been full if API errors where it reverts from local to invidious. Today the subscription list says it's empty and when I go to the accounts directly it says they have no videos. I can still access their playlists, and get to things from my viewing history.

**Comment by github-666999** [comment]
Got the same problem with v0.17.1-nightly-2219 Beta AppImage on Linux Mint. 
Only a few channels show videos (in subscriptions list and if you open the channels directly).

**Comment by PrestonN** [comment]
Hey everyone. We're well aware of the issue and already have a fix in the pipelines. We'll be getting a new release out here as soon as we can. We ask that everyone is patient with us while we prepare the new release.

**Comment by RektalTk** [comment]
I have the same issue on v0.18.0 Beta. This problem exist on Debian and Windows 11. The same problem is on NewPipe 0.24.0.
Is this an issue on YouTube side?

**Comment by absidue** [comment]
@RektalTk Are you using the local or the Invidious API? The issue is fixed in 0.18.0 for the local API, if you are using the Invidious API, you will need to wait for the Invidious servers you are using to be updated with a fix, which is out of our control.

**Comment by GiorgosCouk** [comment]
Changing to local API fixed the issue for me. (I use 0.18.0 version on Windows 10)

**Comment by nowakommunikation** [comment]
> Hey everyone. We're well aware of the issue and already have a fix in the pipelines. We'll be getting a new release out here as soon as we can. We ask that everyone is patient with us while we prepare the new release.

Thank you! 
After dl'ing version 0.18 it works again. 
(The different API's didn't make a difference for me in the previous version.)

**Comment by deroverda** [comment]
> I have the same problem except that I only get videos from one channel.
> 
> If I try to go directly to a channel it says "This channel does not currently have any videos" on every one. If I change to using Invidious as preferred API backend I get a bunch of "Invidious API Error (Click to copy): undefined" scrolling and then it seems to default to fetching the feed trough RSS and I can see the videos in my subscription overview.
> 
> A temporary workaround is to change to "Fetch Feeds from RSS" in subscription settings, though you have to give up the ability to see video length in the subscriptions overview.
> 
> This is on v0.17.1-nightly-2223 Beta, Fedora Linux 35.

I've got the same problem. Downloaded the latest "freetube-0.18.0-setup-x64.exe" and I only get a couple of videos from one channel in my "subscriptions" list.

**Comment by absidue** [comment]
@deroverda see my comment further up in this issue https://github.com/FreeTubeApp/FreeTube/issues/2796#issuecomment-1299695701 you need to set the API to the local on until the invidious servers get fixed.

**Comment by t3dium** [comment]
btw, some instances (particularly ones running older versions) are still working, for others using invidious, until invidious fixes the issue you can try a couple instances from: https://api.invidious.io/

**Comment by Patrick260** [comment]
> btw, some instances still work fine, for anyone else encountering issues i'd recommend switching instances temporarily, until your invidious instance fixes this issue: https://api.invidious.io/

Which of them are working?

**Comment by MarmadileManteater** [comment]
> > btw, some instances still work fine, for anyone else encountering issues i'd recommend switching instances temporarily, until your invidious instance fixes this issue: https://api.invidious.io/
> 
> Which of them are working?

If the version is `2022.11.02-*` or newer, the server should work.

**Comment by Patrick260** [comment]
> > > btw, some instances still work fine, for anyone else encountering issues i'd recommend switching instances temporarily, until your invidious instance fixes this issue: https://api.invidious.io/
> > 
> > Which of them are working?
> 
> If the version is `2022.11.02-09942de` or newer, the server should have a fix for this issue applied.

Subscribtion list is now working but when I click on a channel there are still no videos shown.

**Comment by Patrick260** [comment]
And when I switch to other profiles the subscription list is still empty. Only default profile is working.

**Comment by MarmadileManteater** [comment]
> And when I switch to other profiles the subscription list is still empty. Only default profile is working.

Which invidious server are you using? 

These are the ones that are updated right now:
- [yt.artemislena.eu](https://yt.artemislena.eu)
- [inv.bp.projectsegfau.lt](https://inv.bp.projectsegfau.lt)
- [invidious.projectsegfau.lt](https://invidious.projectsegfau.lt)
- [inv.odyssey346.dev](https://inv.odyssey346.dev)

**Comment by ChunkyProgrammer** [comment]
This issue should be solved now

**Comment by thingsiplay** [comment]
Using FreeTube since weeks, currently at v0.19.1 Beta and got hit with this issue first time. Just half an hour ago it worked fine and now it can't fetch videos on my subscriptions view. Local API and Individious API does not matter which one. Because I have a huge list of subscriptions, it always uses and defaults to Fetch Feeds from RSS, so there is nothing to test with this setting for me.

However when I open a channel directly, I can see all the videos from it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
For a quick fix create a profile with < 100 subscriptions

**Comment by thingsiplay** [comment]
I should have mentioned I tried that before. I have 9 (+1 for all) profiles with different focus. None of them work in subscriptions view. And to test, I also created a brand new profile with 6 channels and restarted the app. We are talking about the profiles available in the right Profile Select menu, right?

**Comment by Winterhuman** [comment]
Can confirm the exact thing here too, FreeTube suddenly started reporting all channels as "with errors" until I disabled RSS feed subscriptions. My guess is that YouTube's changed something again, since nothing else on my system has changed.

OS: Arch Linux
Version: 0.19.1 (Flatpak)

**Comment by thingsiplay** [comment]
Just 1 minute ago it works again normally, with All subscriptions and RSS enabled too.

**Comment by Winterhuman** [comment]
Yep, same here. Hopefully this was just a temporary issue on YouTube's side

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The bug is on YouTube's side, we can't do anything about YouTube breaking their own systems.

Hopefully it is resolved soon.

For everyone that needs to use FT right now, try the workaround. 

> For a quick fix create a profile with < 100 subscriptions
