### ISSUE TITLE
[Bug]: Tiny mouse cursors

### ISSUE THREAD

**Issue by bungadrum** [FreeTubeApp/FreeTube#2799]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Whenever I select a custom cursor for example Nordic, Qogir, Dracula or any other that is not default adjust the size to be a bit bigger and hover over the video thumbnails, player or comments it gets very tiny and it changes it's shape to a plain one.

### Expected Behavior

The cursor looks normal and is normal size when you hover over the WM, but when you lower it down it gets tiny and it stays like that until you pull it back up on top of WM. The exception is for the default cursor they stay the same both in color and shape and size, but the custom installed ones from Pling don't. Also when you hover over a playing video the cursor changes to a tiny white hand with index finger pointing over it. This happenes in the Flatpak can you somehow fix it?

### Issue Labels

inconsistent behavior, visual bug

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Ubuntu 22.04 LTS 

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Was this also the case for u in v0.17.1?

**Comment by bungadrum** [comment]
Yes in every version so far it was the same even before v0.17.1

**Comment by absidue** [comment]
@bungadrum Could you please try visiting this website https://www.w3schools.com/cssref/playit.php?filename=playcss_cursor&preval=pointer in your web browser (Firefox, Chrome, etc) and see if you are seeing the same issue there? If you do, then the issue is more likely to be with your WM or that the mouse packs you are using don't support the `pointer` cursor, so it falls back to the default pointer cursor.

**Comment by bungadrum** [comment]
> @bungadrum Could you please try visiting this website https://www.w3schools.com/cssref/playit.php?filename=playcss_cursor&preval=pointer in your web browser (Firefox, Chrome, etc) and see if you are seeing the same issue there? If you do, then the issue is more likely to be with your WM or that the mouse packs you are using don't support the `pointer` cursor, so it falls back to the default pointer cursor.

I tried it everything works fine there using Graphite cursor theme https://www.pling.com/p/1651517 the problem is only in the Flatpak app

**Comment by bungadrum** [comment]
I figured out the problem it was because the Flatpak version wasn't given permission to theme so when you apply a non default cursor that you downloaded the Flatpak won't recognize it. After using GTK ENV command and granting it permission to the icons the cursor looks normal. It can also be used with Flatseal to give it permission to the icons. You can close it now.
