### ISSUE TITLE
Feature request: Proxy support

### ISSUE THREAD

**Issue by avamk** [FreeTubeApp/FreeTube#28]
Sorry about the barrage of issues, I wanted to get ideas down before I forget!

Is there a way to set a proxy for FreeTube so that, for example, a user can define a local SOCKS5 proxy to connect with the Tor Browser? I think this would be great from a privacy POV. Thanks!

**Comment by PrestonN** [comment]
Don't worry about posting tons of issues. Keep them coming, it keeps me organized :)

This is something I'd like to do, I just need to figure out how to approach this.  I'd rather not have users rely on a server that I host and I'd rather want users to be able to connect to their own.  I haven't done research yet, but I'm unaware of any service that provides easy to use/setup proxy servers.

The last point with this is that I feel like a proper VPN solves this issue for the most part.  Those that are concerned with their privacy should be using one already and I'd hate to make a ton of effort towards something that already has a solution.  If I'm wrong and if there's a good value to sending API requests through a proxy then please let me know.

Also when I switch over to the NewPipe API, I feel like this will be needed even less, so I'm pretty hesitant to doing this.

**Comment by avamk** [comment]
> The last point with this is that I feel like a proper VPN solves this issue for the most part.

I agree on "most". But it's not all. :) I think there's still a benefit of routing FreeTube through Tor that VPNs can't achieve. Anyway, I agree this doesn't have to be top priority, but it can at least be a "great to have" feature? Thanks!

**Comment by PrestonN** [comment]
Yes definitely.  It may be until after FreeTube is at it's stable release before I make serious efforts towards it though.  If anyone has suggestions or wants to help on this in the mean time feel free to do so :)
