### ISSUE TITLE
Player doesn't shrink when exiting fullscreen initiated with the "F" Shortcut

### ISSUE THREAD

**Issue by T-vK** [FreeTubeApp/FreeTube#280]
First of all I'm really glad the new player finally supports the "F" shortcut that allows you to enter/exit the fullscreen mode. But I noticed a bug: 
When you enter/exit the fullscreen mode by pressing "F", the player won't shrink to its small size after leaving the fullscreen mode again.

Let me show you what I mean.

Expected behavior:
![image](https://user-images.githubusercontent.com/11368523/59563294-4fa08900-9038-11e9-9226-9f8dda8ebded.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/11368523/59563303-647d1c80-9038-11e9-8239-2319cbabb3b8.png)

**Comment by PrestonN** [comment]
This should be fixed with the latest release.  Give that a try and re-open this issue if the problem persists.
