### ISSUE TITLE
[Bug]: Building 18.0 from source only gives x64 .dmg instead of arm64

### ISSUE THREAD

**Issue by RonaldRegister** [FreeTubeApp/FreeTube#2800]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

as with every update I compile my Freetube version on my M1 Macbook. But as of 18.0 it does not result in an arm64 version. It produces a x64 version (which works because of Rosetta, but it is very slow)

I've downloaded 17.1 source again, and this does result in a arm64 version, but this version has its problems which are fixed in the new version. 

### Expected Behavior

Produce arm64 build

### Issue Labels

feature stopped working

### FreeTube Version

v0.18.0

### Operating System Version

macOS 12.6.1

### Installation Method

other

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.17.1

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Which command are you using to build?

**Comment by RonaldRegister** [comment]
yarn install
npm run build

No errors after compiling
these are the same commands i've used in the previous versions (which still produce a working arm64 version)

**Comment by RonaldRegister** [comment]
can confirm this works. Thank you for the quick responses, and for your work. I feel pretty stupid now. Just decided to donate to this project, because.. well it's really great!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing because this issue is resolved :)
