### ISSUE TITLE
[Bug]: Videos cannot be sorted

### ISSUE THREAD

**Issue by lonix1** [FreeTubeApp/FreeTube#2805]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. open channel
2. click "sort by"
3. items not sorted

### Expected Behavior

Items to be sorted

### Issue Labels

feature stopped working

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Ubuntu 22.04.1 LTS

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.17.1 Beta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by MarmadileManteater** [comment]
I believe this is due to a fundamental change in the way that YouTube channel pages work. Looking at YouTube, the sort options they now offer don't even seem to correspond with the ones used in FreeTube.
![image](https://user-images.githubusercontent.com/106682128/199745969-6bd3c9ec-46b6-49af-98c9-836680c92a07.png)
It also looks like sorting is now handled with continuations which is different than it was before. `yt-channel-info` will need to be patched to fix this.
![image](https://user-images.githubusercontent.com/106682128/199749935-0eec80a3-c85f-4246-b834-8d27267baa9f.png)

**Comment by Charsy89** [comment]
Could this issue possibly be expanded to cover shorts and livestreams being sorted differently? Or should that be put into its own issue? Channel shorts and livestreams (past and ongoing) no longer appear on the subscription feed, nor the channel view.

I just thought they fit in a similar enough area in terms of what caused it and how it could be fixed. I also searched and this is the closest issue I could find relating to. Sorry if I'm wrong.

**Comment by MarmadileManteater** [comment]
> Could this issue possibly be expanded to cover shorts and livestreams being sorted differently? Or should that be put into its own issue? Channel shorts and livestreams (past and ongoing) no longer appear on the subscription feed, nor the channel view.
> 
> I just thought they fit in a similar enough area in terms of what caused it and how it could be fixed. I also searched and this is the closest issue I could find relating to. Sorry if I'm wrong.

Those are different issues. There is already a fix for shorts in `yt-channel-info`, but it hasn't made its way into FreeTube yet. Live videos not appearing on channel pages is a similar problem, but it will require its own solution.
