### ISSUE TITLE
[Bug]: MS Defender Smart Screen prevents from opening 0.18.0 setup

### ISSUE THREAD

**Issue by Kash629** [FreeTubeApp/FreeTube#2809]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Install exe for 64bit 
2. Open installer
3. Windows prevents you / warns you from opening it.
![image](https://user-images.githubusercontent.com/82764690/199780410-15aaf014-d3fd-4a98-bbbb-7ffa896c396c.png)

### Expected Behavior

Installer opening without warning

### Issue Labels

accessibility issue, usability issue

### FreeTube Version

v0.18.0

### Operating System Version

Windows 10 Pro 64bit

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.17.1 was the latest i tried

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hey there,

This is not a bug. The cause of this is because the packages for FreeTube are not code signed. 

Code signing FT with Microsoft will cost around $100 a year. 

If you still have concerns of something malicious being in the executable, you are welcome to clone down the repo and build an executable.

Hope this helps.
