### ISSUE TITLE
Enhancement: Allow import/export of watched video history

### ISSUE THREAD

**Issue by Cynthetika** [FreeTubeApp/FreeTube#281]
**Background:** One major frustration I have with using multiple alternate frontends over multiple devices is the loss of my watched video history. I frequently watch tutorial channels and have difficulty tracking which videos I have watched due to picking up playlists at varying times on different devices.

**It would be excellent to be able to:**

- export history - using a processable format (accounting for other frontends to also parse it)

- import history - merging with existing history on import (to allow easily "synchronising" history over multiple devices without loss)

**Relevant note:** NewPipe allows import/export of history along with subscriptions. Perhaps a starting point may be extending the current NewPipe subscription importer to provide merged import of history as well from a native NewPipe export? I frequently move between NewPipe and FreeTube - I'm guessing many people probably do. I admit I haven't looked into the existing formats yet so perhaps this may be more involved than I'm assuming (if so, sorry!).

**Comment by PrestonN** [comment]
Importing and exporting history (or settings and favorites) is a rather simple thing to do.  Making it compatible with NewPipe would be a little bit of extra work but it still shouldn't be difficult.

I think the best thing to do in the future would be to have some sort of webDAV support where FreeTube and NewPipe (or any other app) can automatically sync up data like subscriptions and history. Something like this would take some cooperation between projects and I don't think either project is ready to do something such as that but it's still something to keep in mind.

**Comment by Cynthetika** [comment]
I absolutely agree. Synchronisation via webDAV would be fantastic and I was planning to have a think about both standardisation and synchronisation methods and open a separate issue with some ideas later. I wasn't sure if there was already some effort to do something similar (expandable to platforms other than YouTube, as well) as I haven't had time to check.

I'd love to help more directly but my background is in C/C++ and I rarely seem to have enough free time... I can definitely see how webDAV could work well for this and would be better than what I was thinking of, especially since JS can handle that easily. Would work nicely with Nextcloud, too =)

**Comment by drod3763** [comment]
I have tried doing this using dropbox and symbolic links, but when Freetube opens it breaks the linkage. Any ideas of what I might be doing wrong?

**Comment by heartlessglasses** [comment]
@drod3763 Sadly I think symbolic links don't really work with some programs that open them, I tried something similar with Syncthing and an Excel file, but due to the way Excel saves files (makes a new file, deletes the old one and gives its name to the new one) it breaks symbolic links. This is just a guess but FreeTube might do something similar here.

A native history import/export/sync function would definitely be welcome.

**Comment by PrestonN** [comment]
Importing / Exporting history is implemented in the rewrite and will be released soon.
