### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by justaguydoinghisstuff** [FreeTubeApp/FreeTube#2817]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Everytime the application starts or whenever im manually refreshing my subscription feed i get this error.
`Local API error (click to copy): TypeError: Cannot read properties of undefined (reading 'indexOf')`

### Expected Behavior

i dont know, the feed does gets updated though so im unsure if this is even an error.

### Issue Labels

API issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Windows 10 22H2

### Installation Method

.zip

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Lets try to get more information on this. Open console with the following command `CTRL + SHIFT + I` -> now reload the subscription page -> some red errors are starting to popup in the console. Please share a screenshot of the full console log window.

**Comment by justaguydoinghisstuff** [comment]
i hope thats what you meant, otherwise i can try to take it again.
![image](https://user-images.githubusercontent.com/61499129/200136418-6ea601e3-7c8c-4d67-a9fd-9327211b7351.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
That is exactly what i meant :)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @justaguydoinghisstuff could u try out [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds) to check if that solves it?

**Comment by justaguydoinghisstuff** [comment]
Yes this seem to have worked, i dont get the message anymore

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Thanks for testing :)
