### ISSUE TITLE
[Bug]: Video lags (probably the framerate just drops) when switching to fullscreen

### ISSUE THREAD

**Issue by hacksenwerk** [FreeTubeApp/FreeTube#2818]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

I've tested this compared 0.17.1 and 0.18.0 several times under the same conditions (same video, same resoltion etc.) 
This is since 0.18.0. 
I've switched back to 0.17.1 where this wasn't the case and it still isn't, so I will use 0.17.1 again, till it is fixed in 0.18.0. 

Thank you for your hard work anyway. ;)

### Expected Behavior

Lag free playback in fullscreen.

### Issue Labels

usability issue

### FreeTube Version

0.18.0

### Operating System Version

Debian 11

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.17.1

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Could you please share the video you experienced that with? as you say you used a specific video to test this.

**Comment by hacksenwerk** [comment]
@absidue Hi. No sorry I tested it with several videos, but here you go: 
https://youtu.be/k2RKtUh6m3Q

**Comment by absidue** [comment]
Does it lag for you in all parts of the video or just at the start, while it's still loading in stuff?
I get a short pause at 0:05 regardless of whether it is fullscreen or not, when it gets to the end of the already buffered stuff and then it works fine once it's loaded in more of the video.

I've tested a bunch of videos and I only see it happening for this specific video.

Is that what you are experiencing as well or are you seeing different behaviour?

**Comment by hacksenwerk** [comment]
It lags in all parts. 

If it would only lag in while buffering, it would lag in window or cinema / theatre mode too, but it doesn't.

**Comment by absidue** [comment]
Labelling this issue with Linux, as I can't replicate this issue on Windows 10.

**Comment by zh54tg234f** [comment]
>Lag free playback in fullscreen.

never saw this unless i had no proper graphic drivers. (nvidia is famous for crappy linux drivers on debian/ ubuntu, sometimes the installation is "done" but the kernel module isnt really working )

everything else works fine? browser fullscreen video playing?

**Comment by hacksenwerk** [comment]
> have you updated any graphic drivers since?
No.  
> never saw this unless i had no proper graphic drivers. (nvidia is famous for crappy linux drivers on debian/ ubuntu, sometimes the installation is "done" but the kernel module isnt really working )
Yes, nvidia sucks, since Linux 5.0 or so it is better but nvidia still sucks.  
> everything else works fine? browser fullscreen video playing?
Yes.

**Comment by hacksenwerk** [comment]
I have installed the unfree nvidia driver now. 
I have used the free noveau before. 
The issue is now solved for me.
