### ISSUE TITLE
Enhancement: Mini player always on top option

### ISSUE THREAD

**Issue by DanielValahul** [FreeTubeApp/FreeTube#282]
This is a feature that would be great for windows users since there is no way to pin windows like in some linux DE.  A feature like this would be great for multitasking (for example, watching a photo editing tutorial without leaving Photoshop). I think windows does have some capabilities for this as MusicBee has an always on feature for their mini player.

**Comment by PrestonN** [comment]
I will be looking into this.  No ETA on it but I hope to have it implemented at some point.

**Comment by PrestonN** [comment]
This has been done and will be included in the upcoming patch release.

**Comment by DanielValahul** [comment]
Was it added only on Linux? I cant find the option on the windows version (i also tried looking for it in the developer mode)

**Comment by PrestonN** [comment]
@DanielValahul when the mini player is open, hit `Alt` on your keyboard to open a menu.  Go to Window -> Toggle Always on Top to turn it on.
