### ISSUE TITLE
[Feature Request]: Add a pop-up that displays all the keyboard shortcuts available for the player (Shift+?)

### ISSUE THREAD

**Issue by CrazzzzyChipmunk** [FreeTubeApp/FreeTube#2822]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

It would be nice to get list of all the keyboard shortcuts available for the player via "Shift+?".

### Proposed Solution

Add a pop-up that is invoked by "Shift+?" where all the available keyboard shortcuts for the player are listed, like it is implemented in YouTube's player.

![1](https://user-images.githubusercontent.com/117451463/199977773-91e4f565-fa51-4c01-8b3d-b0e47dd8658f.png)

### Alternatives Considered

None

### Issue Labels

display more information to user, new feature

**Comment by LinuxOnTheDesktop** [comment]
I have been unable to find any way of displaying the player's keyboard shortcuts, let alone any way of customizing them. Surely the features at issue are very desirable.

**Comment by absidue** [comment]
@LinuxOnTheDesktop all keyboard shortcuts are listed in the docs: https://docs.freetubeapp.io/usage/keyboard-shortcuts/

**Comment by LinuxOnTheDesktop** [comment]
@absidue: thanks; but the existence of that webpage does not fulfil this feature request.

@CrazzzzyChipmunk: I do not understand; please clarify.

**Comment by BarbzYHOOL** [comment]
yes, this is very NEEDED, especially when someone uses freetube on an old computer, launching an extra browser just for this is very long and annoying

**Comment by hutonahill** [comment]
I would implement this if you hold down shift+? it pops up a window displaying shortcuts that will do something right now. when you release the keys the windows drop back down. 

a quick reference is extremely useful.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sure go for it!

**Comment by LinuxOnTheDesktop** [comment]
@hutonahill 

You have been interpreted (by @efb4f5ff-1298-471a-8973-3d47447115dc) as meaning that you _will_ implement the feature. I fear that that is not what you meant.

**Comment by hutonahill** [comment]
no no no... i love designing stuff, but my hatred of js is only rivled by my hatred of C++.  and this project is JS and C++ so...

**Comment by absidue** [comment]
FreeTube uses Electron's precompiled binaries, there is no C++ code here, just Vue, JavaScript and CSS.

https://docs.freetubeapp.io/faq/#electron-is-bad-please-use-something-else

**Comment by shadycloud** [comment]
Did a little grepping on @CrazzzzyChipmunk's idea. I ended up thinking that an alert box would be a more minimalist solution.

```
    // right click menu
        if (process.env.IS_ELECTRON) {
          const { ipcRenderer } = require('electron')
          ipcRenderer.removeAllListeners('showVideoStatistics')
          ipcRenderer.on('showVideoStatistics', (event) => {
            this.toggleShowStatsModal()
```
Found the displayed info located in an array of ft-video-player.js
![Screenshot from 2023-11-12 16-31-42](https://github.com/FreeTubeApp/FreeTube/assets/13189052/c17e0bc5-51ea-4c67-a707-7d286f3fd3db)
![Screenshot from 2023-11-12 17-11-46](https://github.com/FreeTubeApp/FreeTube/assets/13189052/25449677-035e-4da0-9010-e9c6512800a8)

**Comment by jasonhenriquez** [comment]
That looks good, but having two left-aligned text columns does make it easier to follow. Also lowercase versus uppercase probably does not need to be specified. Monospaced font for the right column and/or boxed "key" styling seems like a reasonable choice as well.

**Comment by shadycloud** [comment]
> That looks good, but having two left-aligned text columns does make it easier to follow. Also lowercase versus uppercase probably does not need to be specified. Monospaced font for the right column and/or boxed "key" styling seems like a reasonable choice as well.
Cool. Tried messin with it a little more. Here's what I got so far...
![Screenshot from 2023-11-12 21-13-46](https://github.com/FreeTubeApp/FreeTube/assets/13189052/a1af5338-8a47-4f11-b362-510db7a36cfa)
```
displayShortcuts:  function() {
    const shortcuts = `
  ┌──────────────────────
  │ Shortcuts:               
  ├──────────────────────
  │ Play\t\t\tSpace Bar
  │ Pause\t\t\tSpace Bar
  │ Replay\t\t\t\t\tH
  │ Mute\t\t\t\t\tM
  │ Toggle Loop\t\t\tR
  │ Pic in Pic\t\t\t\tI
  │ Full Window\t\t\tS
  │ Full Screen\t\t\tF
  └───────────────────────
  `;
  alert(shortcuts);
},
```

**Comment by jasonhenriquez** [comment]
The columns look easier to visually follow now. To be clear, by "boxed 'key' styling," I was referring to the `kbd` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd).

**Comment by absidue** [comment]
That would limit it to the watch page but there are app wide shortcuts too and some other pages have their own ones. The the popup should be app wide and show the right shortcuts depending on the context/page.

**Comment by absidue** [comment]
Also overwriting the stats modal seems like a bad idea too.

**Comment by absidue** [comment]
That would limit it to the player, a better option to create an app-wide popup would be to use the ft-prompt component.

**Comment by shadycloud** [comment]
> That looks good, but having two left-aligned text columns does make it easier to follow. Also lowercase versus uppercase probably does not need to be specified. Monospaced font for the right column and/or boxed "key" styling seems like a reasonable choice as well.


tried the <kbd> tags w/o success so the information on the stack link I shared last week might be right… 
![385D7ED2-6981-404C-80F8-8F2A78096CBB](https://github.com/FreeTubeApp/FreeTube/assets/13189052/6aeaa5b4-b708-4171-abc6-00cd7840febb)


some alternatives like already mentioned, the ‘modal’ being app wide (meaning no matter what part of the app is in focus the shortcuts displayed actually do what they are supposed to do and probably with the keyed box format as well. I haven’t got in to what the sweetalert can do, but apparently the regular old alert box is quite limited. 
https://stackoverflow.com/questions/5810740/javascript-alert-message-alternative

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We can maybe look at how Signal implemented this on their desktop application which also uses Electron
 https://github.com/signalapp/Signal-Desktop

**Comment by kommunarr** [comment]
I'm thinking the shortcuts should be grouped like this:
- Player
  - General
  - Playback
- App
  - General
  - Situational

**Comment by nhooey** [comment]
The shortcut: `⌥D Focus on the search bar` doesn't seem to work in Freetube version: `0.23.5 (0.23.5)` on Mac OS version: `Sonoma 14.6.1 (23G93)`.

It doesn't work in a window with a video already loaded, nor a new window with nothing loaded yet.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> The shortcut: `⌥D Focus on the search bar` doesn't seem to work in Freetube version: `0.23.5 (0.23.5)` on Mac OS version: `Sonoma 14.6.1 (23G93)`.
> 
> It does nothing in a window with a video already loaded, nor a new window with nothing loaded yet.

@PikachuEXE

**Comment by PikachuEXE** [comment]
https://github.com/FreeTubeApp/FreeTube/pull/7448
