### ISSUE TITLE
Enhancement: Autoplay next video

### ISSUE THREAD

**Issue by DylanVanAssche** [FreeTubeApp/FreeTube#283]
I found already a setting to autoplay the videos. I looked in the issues already, but I havn't found anything related to automatically play the next recommended video.
It would be nice that the next recommended video is automatically played too.

Youtube already does this, which is handy if your listening to music on Youtube.
Of course, this feature should be modifiable in the Settings, since not everyone likes this behavior I guess.

Thanks!

**Comment by PrestonN** [comment]
This is planned.  Should be an easy addition.

**Comment by DylanVanAssche** [comment]
Thanks! Great to hear that :D

**Comment by PrestonN** [comment]
This has been finished.  Expect to see it in the upcoming patch release.

**Comment by DylanVanAssche** [comment]
Great to hear that! FreeTube is really awesome :D
