### ISSUE TITLE
[Bug]: ytming.com Redirect - Unable to Visit YT Images

### ISSUE THREAD

**Issue by eightyy8** [FreeTubeApp/FreeTube#2854]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Accessing any "i.ytimg.com" link will force redirect you to FreeTube, and since FreeTube isn't an image viewer it gives back obvious errors, and because of the redirect it doesn't show anything on the image page.
If you say no to the redirect it to FreeTube, it will just close the tab.
...
Leaving you unable to access any thumbnails hosted on YouTube

### Expected Behavior

To visit i.ytimg.com and actually be able to see an image.

### Issue Labels

usability issue

### FreeTube Version

v0.18.0 Beta (and below)

### Operating System Version

Windows 10 Pro 21H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [x] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Please report this issue to the developers of the browser extension you are using to get redirected, this is not an issue on our end.
