### ISSUE TITLE
[Bug]: Sponsor segments loaded, even if skipped

### ISSUE THREAD

**Issue by UltraBlackLinux** [FreeTubeApp/FreeTube#2860]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Freetube loads the sponsor segment, even if it's going to be skipped leading to a playback stop until the part after the segment is loaded once freetube skips it

### Expected Behavior

it should not load the sponsor segment and start immediately loading the part behind it

### Issue Labels

content not loading

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux lolcat 6.0.8-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:22 +0000 x86_64 GNU/Linux

### Installation Method

AUR

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @UltraBlackLinux do u experience this behavior on all videos?

**Comment by UltraBlackLinux** [comment]
yeah I do. It's very easy to reproduce.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing, because this requires us to dig into video.js internals and tell it to not download the parts that sponsorblock has marked as sponsors. This is only really noticeable when YouTube is throttling us

It's basically out of our control unless we want to rewrite parts of video.js
