### ISSUE TITLE
[Feature Request]:  Allow search results to be filtered from newest to oldest.

### ISSUE THREAD

**Issue by cocoonkid** [FreeTubeApp/FreeTube#2865]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

[Feature Request]:  Allow search results to be filtered from newest to oldest.

### Proposed Solution

Allow search results to be filtered from newest to oldest.

### Alternatives Considered

The option to filter by  "within last month" / timeframes is too unwieldy.

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not possible. Yt doesnt provide such a filter.

![Screenshot_20221114-171430.png](https://user-images.githubusercontent.com/73130443/201710106-3d5f694e-cc40-405e-8514-416d51b28e22.png)

These are the only options.

**Comment by cocoonkid** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 

Could this not be just parsed from the release date of the video?

Newpipe can do this. When I refresh my subs there it shows them in order of release.
