### ISSUE TITLE
[Bug]: Channel name not visible on Subscriptions page

### ISSUE THREAD

**Issue by OrdinaryGecko** [FreeTubeApp/FreeTube#2869]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to "Subscriptions"
2. See error

![freetube_subscriptions](https://user-images.githubusercontent.com/92624591/201817276-35a79645-e54b-4dbf-aa74-f909cc607e19.png)

### Expected Behavior

Channel name should appear under the video like it does in other tabs like "Trending", "Most Popular", etc.

![freetube_mostpopular](https://user-images.githubusercontent.com/92624591/201817334-64e7c97f-4395-4ea8-b46b-70ccb25c3295.png)

### Issue Labels

inconsistent behavior, text/string issue

### FreeTube Version

v0.18.0

### Operating System Version

Arch Linux

### Installation Method

AUR

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by petaded** [comment]
This seems to be an issue on the invidious side.
You can see the problem directly from their api:
https://invidious.tiekoetter.com/api/v1/channels/latest/UCXuqSBlHAE6Xw-yeJA0Tunw

```
"title":"We Found One Good Thing About the GeForce RTX 4080...","videoId":"0CunGt3cQXc","author":"","authorId":"UCXuqSBlHAE6Xw-yeJA0Tunw"
```

Note that in the above returned data `"author": ""`  - no channel name returned, which freetube is then reading and displaying.
Either have to wait for invidious to be fixed or do some extra work to fetch the channel name from some other api.

**Comment by ChunkyProgrammer** [comment]
Is this still an issue?

**Comment by OrdinaryGecko** [comment]
> Is this still an issue?

Unfortunately yes.

**Comment by curbengh** [comment]
fixed by https://github.com/iv-org/invidious/pull/3590, I can now see channel name by using any [instance](https://api.invidious.io/) running on 2023.01.26-3b8e6c6 or newer.
