### ISSUE TITLE
[Bug]: Download site unavailable freetubeapp.io

### ISSUE THREAD

**Issue by glerner** [FreeTubeApp/FreeTube#2872]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

FreeTube v0.17.1 Beta on Linux says in banner to download new version. 
Link is https://freetubeapp.io
Link fails with Firefox "Problem loading page". 
```

mtr https://freetubeapp.io/
mtr: Failed to resolve host: https://freetubeapp.io/: Name or service not known

```

Of course, I can update the software via GitHub

### Expected Behavior

Download .deb file from the website.

### Issue Labels

content not loading

### FreeTube Version

v0.17.1 Beta

### Operating System Version

Linux Mint, 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Site should be back online now. Thanks for letting us know!
