### ISSUE TITLE
WATCH list history reset for some reason today

### ISSUE THREAD

**Issue by avincent98144** [FreeTubeApp/FreeTube#2876]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

WATCH list history reset to default today. On that note, is there a way for a global "all watched" in one fell swoop?

### Expected Behavior

I use FT daily, and manually WATCHED vids I'm not interested in as well.

### Issue Labels

feature stopped working

### FreeTube Version

0.18.0

### Operating System Version

13.2 beta 3

### Installation Method

.dmg

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

N/A

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by avincent98144** [comment]
see above

**Comment by EvilGremlin** [comment]
Lateset verison show hidden videos in subscriptions on launch (some greyed and some not), page refresh fix it

**Comment by avincent98144** [comment]
Thanks, but that is not it.

**Comment by EvilGremlin** [comment]
could be related

**Comment by avincent98144** [comment]
I’ve done a handful of page refreshes along with other steps ..

**Comment by PaperOrb** [comment]
Same scenario as the OP. I'd just like to add that no new history is being generated either in my case.

**Comment by PaperOrb** [comment]
Any workaround for this in the meantime? I haven't had history for newly watched videos for weeks now.

**Comment by PaperOrb** [comment]
Commenting because this still isn't resolved in my case.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @avincent98144  apologies for the delayed response. Would u be willing to provide the affected database files. We would like to investigate what caused this issue. U can find the files [here](https://docs.freetubeapp.io/usage/data-location/).

**Comment by grrrrr** [comment]
I am noticing similar.  I can open new ticket if needed.

OS: Debian 11
FreeTube: v0.18.0 Beta (via .deb)

What I am seeing:  

I started noticing this about a month ago, but thought I had just missed marking items watched.

If I go into a channel where I have watch all videos or in the majority of cases just marked them as watched, I am noticing that (appearing to be) random videos in channels where were watched are now showing up as unwatched.   This appears to be happening over most channels (though most easy to spot when majority of videos are marched watched in a channel

Looking at a backup of the history,  any videos that I have marked as watched but is no longer showing as watch does not appear in the db file.

history db is >5,000 lines and 2.4MB

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@grrrrr could u try the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds) and check if it still happens when u watch all vids in a channel

**Comment by grrrrr** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc  sure can.   Might take a bit to test though as I'm not entirely sure when they get removed from watch list.   

While trying to replicate should I keep installing nightlies or just stick with one?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
u dont have to install every nightly. I think if u download the most recent one now u should be fine

**Comment by grrrrr** [comment]
One thing I'm curios about....   Is there a reason that some videos in the history DB  include the "description" field from the video  and some don't?

e.g.

With description:

`{"videoId":"MO0DepVkgjg","title":"How bright did you say this is?! - Nitecore TM12K (12,000 lumens)","author":"Nitecore Lights","authorId":"UC9Or6QhIiAk_PkafIuNAdXg","published":1684364400000,"description":"Order yours here - https://www.nitecorelights.com/tm12k\nGet 10% off your order with coupon code 'YT10'\n\nChapters\n00:44 – Who is it for?\n01:27 – Similar lights\n02:25 – Mad recharge speed\n03:54 – OLED display\n04:31 – Turbo Ready controls\n05:20 – Turbo Timer, WHY?!\n06:25 – 2-Stage safety lockout\n07:30 – Beamshots\n07:54 – Use cases for floodbeams\n10:40 – Ways to carry\n12:35 – Where to buy\n\n#nitecore #tm12k #flashlight \n\nNB10k Powerbank - https://www.nitecorelights.com/nb10k\nShargeek Powerbank - https://www.nitecorelights.com/storm2\nNU06 LE Beacon - https://www.nitecorelights.com/products/nu06-le-15-lumens\nALS Laser light - https://www.nitecorelights.com/products/pen154r-pen-light-red-laser-150-lumens\nTM20k - https://www.nitecorelights.com/tm20k\n\n-----------------\nWhenever you're ready, here are the 3 best ways I can help you get the perfect light:\n\n1) Shop the best promo bundles this week here, these are designed as ready-to-run kits to get you up and running immediately. - http://bit.ly/nitecore-bundles\n\n2) Download the free guide on how to put together your Ultimate Blackout Kit - https://theblackoutkit.com/freeguide\n\n3) Join the Nitecore Owner's (Singapore) Facebook Group to get your questions answered, get the latest deals and also learn how other Nitecore Owners are using their gear. \n\nNitecore Owner's Facebook Group: https://bit.ly/nightwalkers-sg\nOfficial Facebook Page: https://bit.ly/nitecore-sg\nInstagram: https://bit.ly/nitecore-sg-insta","viewCount":4505,"lengthSeconds":846,"watchProgress":0,"timeWatched":1684593864293,"isLive":false,"paid":false,"type":"video","_id":"pyjORFcuDeJDbkHr"}`


Without description

`{"videoId":"A0rlgY_XccY","title":"Tortuga Packing Cubes Review (2 Weeks of Use)","author":"Pack Hacker Reviews","authorId":"UCa9O7ulUbt4axNo6h1c-JTQ","published":"2 weeks ago","viewCount":5629,"lengthSeconds":312,"watchProgress":0,"timeWatched":1684593541587,"isLive":false,"paid":false,"type":"video","_id":"1jUSwhTw6y2Nf9Kh"}`

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I'm going to take a guess and i think that i doesn't include the description if u manually mark a video as watched

**Comment by grrrrr** [comment]
Initial update...

Using v0.18.0-nightly-2949 Beta (.deb)   I am not seeing this problem occur any more.  Though I am still working through and re-marking videos as watched so the sample size is much smaller than when it first started occurring.
