### ISSUE TITLE
[Feature Request]: Channel Grouping via user set tag

### ISSUE THREAD

**Issue by Smurflicious** [FreeTubeApp/FreeTube#2877]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Having lots of subscriptions makes it hard to see new videos from channels you might regard as higher priority than others. Would be nice to have a separate page for some channels.

### Proposed Solution

Allow arbitrary tags to be set on channels that I have subscribed to, such as "Physics", "Chess", "News" etc etc, these would be stored locally. Then when I click on the Subscriptions page it could show several tabs headed with the aforementioned tags (and one at the end "untagged channels"), and only videos from the relevant channels would be loaded in the tab.

This would allow me to quickly find new videos in certain groups of channels. 

Additionally it could perhaps take some load off the Subscription screen loading as you would be updating less channels (If the tabs only do the update call when they are made visible). So this is perhaps a way to mitigate large calls to APIs??

### Alternatives Considered

I can just get on with the awful task of looking through lots of videos on my subs page.

### Issue Labels

ease of use improvement, improvement to existing feature, new optional setting

**Comment by absidue** [comment]
Does the exising profiles feature work for you or would you like this, on top of the separation you can already achieve, by using different profiles?

**Comment by Smurflicious** [comment]
Hi absidue, you are correct and I am an idiot. How do I close this request lol.

Yes the profiles thing does exactly what I was wanting.
