### ISSUE TITLE
[Feature Request]: Warn about unfinished downloads when quitting

### ISSUE THREAD

**Issue by ohreally** [FreeTubeApp/FreeTube#2886]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When shutting down, FreeTube does not check for unfinished downloads. Resulting in downloads being interrupted and consequentially lost.

### Proposed Solution

Check for unfinished downloads when the user tries to shut down the application, and display a dialogue like "_The following videos have not finished downloading: [...]. Are you sure you want to quit?_". An estimation of time left would be nice, but isn't even a must-have.

### Alternatives Considered

My current alternative is to leave FreeTube running for some time after I have finished using it, to make sure all videos have time to download. (YouTube is used as a support medium for a course I'm following; I download all videos to watch them offline.)

### Issue Labels

display more information to user

### Additional Information

This functionality could be part of #1772 but that feature request includes a lot more functionality, so it will probably take some time to be implemented (open for more than a year now). It would be nice to at least have my suggested functionality until #1772 is implemented.

Thanks for considering.

Rob

**Comment by ohreally** [comment]
Commenting to prevent the issue from being closed automatically.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing in favour of https://github.com/FreeTubeApp/FreeTube/issues/3032
