### ISSUE TITLE
[Bug]: Access Blocked

### ISSUE THREAD

**Issue by ohhsodead** [FreeTubeApp/FreeTube#2888]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Just launched app for the first time, clicked Sign In, the (should be) login page dialog shown but with the error message:
Access blocked: myTube! for Windows’s request is invalid

### Expected Behavior

Login to YouTube account

### Issue Labels

content not loading

### FreeTube Version

4.0.19.0

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

![image](https://user-images.githubusercontent.com/17911431/203445831-a1468f6d-ebba-4118-b769-21355837e0d4.png)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Please report the issue to the developers of "myTube! for Windows", this GitHub repository is for FreeTube, which doesn't have any affiliation with myTube! for Windows.
