### ISSUE TITLE
Minor improvement playback controls

### ISSUE THREAD

**Issue by Kenitilas** [FreeTubeApp/FreeTube#289]
Hello,

I am a happy user of FreeTube.
Recently I discovered that using the arrow keys during a video leads to a jump forward or backward. My problem is that the jump time is too long. I often use this to skip smaller events or just rewind a little.
Is it possible to set a fixed number of seconds with a single press? For example, 5 or 10 seconds?
Probably you can add an option in the settings menu so that every user can customize it. 

Thank you!
Ken

**Comment by PrestonN** [comment]
This was the case in a previous version, however the switch to the new player ended up increasing the length.  I will be fixing this in the next release.  In the mean time, you can use `J` and `L` to scrub through by 10 seconds which should help.

**Comment by PrestonN** [comment]
This has been fixed and will be included in the next release.

**Comment by snakyjake1** [comment]
Might it be better to let the user select what length to skip forward/reverse?
Or maybe a double-click of the skip/forward/reverse key is exponential.  Sometimes I just want to skip 10 seconds, sometimes 30 seconds, sometimes longer.
