### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by eshsdhsd** [FreeTubeApp/FreeTube#2891]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I want to search for videos I want to filter out shorts in the search results just like how I can filter out live streams in distraction free settings

### Proposed Solution

An option to tick and hide shorts just like live streams in the distraction settings.

### Alternatives Considered

N/A

### Issue Labels

new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of #2008
