### ISSUE TITLE
Feature Request: Add Transition Animation on Sidebar Toggle

### ISSUE THREAD

**Issue by AdmiralAsshat** [FreeTubeApp/FreeTube#29]
This app looks like it's going by loose Material Design guidelines. Maybe I'm completely misreading it, but that seems to me to be the attempt.

One of MG's guidelines is that the transition should [guide the eye](https://material.io/guidelines/motion/material-motion.html#material-motion-implications-of-motion) from the old view to the new one.

So if I click the hamburger menu bar, it would be great if we had a transition animation between the before:

![before](https://user-images.githubusercontent.com/5513487/37188602-0cdea904-231e-11e8-80dd-428485f753cf.png)

and the after

![after](https://user-images.githubusercontent.com/5513487/37188609-12758e82-231e-11e8-9a9a-1774ba84e8fe.png)

Maybe something like the bar sliding out from the left-hand side of the screen moving towards the right.

**Comment by PrestonN** [comment]
Definitely something I've been wanting to do.  I very loosely follow their guidelines but it's not exact.  I more or less do what looks right instead of following it word for word.  This will be a "nice to have feature" for now though.  I will definitely look into it soon though.

Thanks for making the issue :)

**Comment by PrestonN** [comment]
Oh man these screenshots are almost embarrassing to look at.  We've come a long way since those times.  With tomorrow's release, there will be a little animation when opening / closing the side bar, so I think we can go ahead and close this.
