### ISSUE TITLE
[Bug]: Choppy, inconsistent playback at 720p/1080p, 50/60fps

### ISSUE THREAD

**Issue by RetroAbstract** [FreeTubeApp/FreeTube#2908]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Videos playing in 720p50, 720p60, 1080p50 & 1080p60 have choppy playback.

Enabling the video stats, I notice lots of frames are dropped during playback, resulting in the choppy playback.

The playback varies in speed, and stutter in the resolutions & frame rates outlisted above. It's very inconsistent.

This happens on both Local/Invidious APIs and .7z/.exe installations.

### Expected Behavior

Smooth 50/60fps playback at 720p & 1080p resolutions.

### Issue Labels

visual bug

### FreeTube Version

v.0.18.0, 4fc5b47

### Operating System Version

Windows 10 Pro 22H2

### Installation Method

.zip

### Primary API used

Local API

### Additional Information

Videos playing in 30fps are smooth.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by arrowgent** [comment]
are you using an invidious instance?
can you go to that invidious website in a browser and view the video on invidious?

the instances are *not* as fast as youtube, they will be slow and buffer at times

it may be freetube, yet be sure to narrow down that your invidious instance choice is working "correctly"
https://api.invidious.io/
this will show you Location, and Users (ie: service load)

**Comment by RetroAbstract** [comment]
> are you using an invidious instance? can you go to that invidious website in a browser and view the video on invidious?
> 
> the instances are _not_ as fast as youtube, they will be slow and buffer at times
> 
> it may be freetube, yet be sure to narrow down that your invidious instance choice is working "correctly" https://api.invidious.io/ this will show you Location, and Users (ie: service load)

@arrowgent This happens on both the Local API & Invidious API, whether the video are proxied through Invidious.

It's specifically the playback of what has been buffered that is inconsistent (details in original post above). The speed at which FreeTube buffers videos is perfectly fine.

It only happens at 50fps & 60fps playback. The standard 30fps is smooth and consistent as expected.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @RetroAbstract  can you try a nightly build and check if u can still reproduce the bug? 
https://docs.freetubeapp.io/development/nightly-builds

https://github.com/FreeTubeApp/FreeTube/actions/runs/4056792643

**Comment by RetroAbstract** [comment]
> Hi @RetroAbstract can you try a nightly build and check if u can still reproduce the bug? https://docs.freetubeapp.io/development/nightly-builds
> 
> https://github.com/FreeTubeApp/FreeTube/actions/runs/4056792643

Tried the latest nightly build and seems to be fixed! Thank you.
