### ISSUE TITLE
New feature: Prevent autoplay, except in a playlist

### ISSUE THREAD

**Issue by cyberchief1984** [FreeTubeApp/FreeTube#292]
I've seen this in various Youtube enhancement scripts, and I thought FreeTube should have it as well. Maybe as a toggle switch.

**Comment by PrestonN** [comment]
FreeTube already has an autoplay toggle in the settings page.  I'm guessing this is what you're wanting?

**Comment by cyberchief1984** [comment]
Nope, I want it to stop preventing autoplay if it's in a playlist.

**Comment by PrestonN** [comment]
Gotcha.  This is a small feature so I'll get it in for the upcoming patch release.

**Comment by PrestonN** [comment]
Finished.  Expect to see it in the upcoming patch release.
