### ISSUE TITLE
Tor not working in 0.61 beta 

### ISSUE THREAD

**Issue by 01010011010** [FreeTubeApp/FreeTube#293]
Anyone else having problems with the Tor api calls in 0.61 beta ? seems the proxy settings are ignored. 

Tor is working 

torify curl https://check.torproject.org/

      Congratulations. This browser is configured to use Tor.
      Your IP address appears to be:  <strong>1xx.xxx.x.xx

**Comment by 01010011010** [comment]
btw using  the FreeTube-0.6.1-linux.tar.xz version

**Comment by PrestonN** [comment]
I have identified the issue.  There was some leftover code from when I was playing around with the possibility of proxy authentication.  I ended up scrapping the plan but some leftover stuff ended up included with v0.6.1.  I've made the fix and will be included with the next release.  For now, you can revert to v0.6.0 to have working Tor functionality.
