### ISSUE TITLE
[Bug]: Problem with subtitle centering with local language option

### ISSUE THREAD

**Issue by Uploadsgit** [FreeTubeApp/FreeTube#2931]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When local language are selected in subtitles, that are centered to the left instead center 

Check image.

Thanks!

![l2k4gdx](https://i.imgur.com/9DuhLLo.png)

### Expected Behavior

I dont know why happens

### Issue Labels

visual bug

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by petaded** [comment]
This seems to happen with any non-english auto generated subtitles.

I have found I can fix it via adding the following to src/renderer/videoJS.css
```
.video-js .vjs-text-track-cue {
  text-align: center !important;
}
```

Not sure if there is a neater way (without using !important).
For reference the text-align: start is added in the html directly hence the need for !important, here is the html element in question.
```
<div class="vjs-text-track-cue vjs-text-track-cue-de-DE" lang="de-DE" style="direction: ltr; writing-mode: horizontal-tb; unicode-bidi: plaintext; text-align: start; font: 21.1px sans-serif; white-space: pre-line; position: absolute; width: 845.203px; inset: 373.984px 0px 0px; height: 48px; background-color: rgba(0, 0, 0, 0);"><div style="color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); position: relative; inset: 0px; display: inline; writing-mode: horizontal-tb; unicode-bidi: plaintext; font-family: sans-serif;">darauf, auf die gleiche Seite zu kommen, richtig, dass
diese <?timestamp 92.96?><span>Grafikkarten </span><?timestamp 93.64?><span>entworfen </span><?timestamp 94.32?><span>wurden</span></div></div>
```


I also don't know if it is intended to have left justified subtitles. Some languages are read right to left and I don't know how centre justifying the text will impact them.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@petaded is this the same issue

In https://youtu.be/yGXaAWbzl5A 

https://github.com/FreeTubeApp/FreeTube/assets/73130443/5a0ab009-050f-43d5-9da5-73d22bc715fa
