### ISSUE TITLE
[Bug]: Posibility of making freetube playlist compatible w newpipe playlist export.But its broken?

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [FreeTubeApp/FreeTube#2935]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

It would be great to support the format newpipe saves in so its convinient to import and export across devices of these foss privacy focused client.

I see this,https://github.com/FreeTubeApp/FreeTube/issues/1304
and i tried using exporting the newpipe subscription and the database.
then import into freetube,however it seems to have no effect.

Is it broken?

### Expected Behavior

properly import and can see the playlist sub etc.

### Issue Labels

usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Win

### Installation Method

.zip

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
You cannot import the db file from newpipe. You can only import the subscriptions and not playlists. Take a look at https://docs.freetubeapp.io/usage/importing-subscriptions/#from-newpipe if you'd like to import subscriptions from NewPipe

**Comment by RESDXChgfore9hing** [comment]
i tried import as the docs says and it says please wait a while,

i waited 2 minutes.I also see the local api,error....... popping up a few times

open the subscription panel.
saw:Your Subscription list is currently empty. Start adding subscriptions to see them here.

Do I need to wait longer and how do i know its finished?isnt it supposed to be in a background thread?
