### ISSUE TITLE
[Feature Request]: Save history as playlist

### ISSUE THREAD

**Issue by cyclonejet** [FreeTubeApp/FreeTube#2939]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When you watch a playlist, the history only saves the video but not the playlist from which the video was played from.

### Proposed Solution

Save video history as playlist if played from a playlist.

### Alternatives Considered

None

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PikachuEXE isnt this already implemented by u?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah yes found it.

This feature was implemented in https://github.com/FreeTubeApp/FreeTube/pull/3006
