### ISSUE TITLE
Glitchy website

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#294]
Hello,
The site seems not working at all, the links doesn't do anything. Here is a screenshot.

![Screenshot at 2019-07-09 17:30:11](https://user-images.githubusercontent.com/22192600/60902216-c9eeb280-a25e-11e9-8940-afc51a3a9e82.png)

**Comment by PrestonN** [comment]
I noticed it for a moment but it seems to have gone back to normal.  I never changed anything so it's weird that an issue came up.  It could have maybe been something to do with the GitHub API but I'm not sure.  Everything seems to be working now so I'll go ahead and close this issue.
