### ISSUE TITLE
[Feature Request]: List of features to replace youtube web

### ISSUE THREAD

**Issue by Shituation** [FreeTubeApp/FreeTube#2954]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I like this project but right now youtube webpage + userscripts + extensions are the most convenient way for me. I hope the features listed below will be implemented soon:

**1- True app fullscreen (like browser, no title bar), exit app hotkey and setting to toggle.
2- Automatic fullscreen video playback and setting to toggle.**
3- Fix automatic res selection for videos, selecting "auto" makes the video play in very low res until manually corrected.
4- Ability to block videos / channels from feeds, filter videos by tags or words.
5- A "home" page to get recommended videos (sometimes its good to have new content from other channels)

If anybody is curious about simulating what I'm saying, try using youtube with the following settings and extensions. I use the above points:

1- Use the extension: AutoFullscreen https://github.com/tazeat/AutoFullscreen
2- Use extension: 'Improve YouTube!' (Video & YouTube Tools)🎧 https://github.com/code4charity/YouTube-Extension/
3- Use youtube web.
4- Use the extension: BlockTube https://github.com/amitbl/blocktube
5- Use youtbe web.

EXTRAS that FreeTube already satisfies:
6- [Clickbait remover](https://addons.mozilla.org/en-US/firefox/addon/clickbait-remover-for-youtube/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) 
7- [Enhancer for YouTube™ ](https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/)
8- [Sponsorblock](https://sponsor.ajay.app/)

Extra but not a deal breaker in any way:
Rating on video thumbnails. ([Thumbnail Rating Bar for YouTube™](https://github.com/elliotwaite/youtube-thumbnail-rating-bar) )

### Proposed Solution

Add the listed features.

### Alternatives Considered

Using Youtube webpage and listed extensions.

### Issue Labels

ease of use improvement

### Additional Information

Using Windows 10 x64.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing because this issue contains multiple requests. Therefore breaking our guidelines. Also all the things requested are already documented in other issues.

**Comment by Shituation** [comment]
Ok, firefox with ublock and youtube will be sufficient for me then.

**Comment by absidue** [comment]
We aren't saying they won't be added at some point, just that everything listed here is already in other feature requests (you checked the box about looking for other feature requests that are identical, so I would have expected you to find them) and keeping duplicate issues around is pointless.

**Comment by BarbzYHOOL** [comment]
Where is the issue about the "recommend other videos"? (though not sure it's even possible to do)

What about clickbait remover?
