### ISSUE TITLE
Add a option to use a google account

### ISSUE THREAD

**Issue by your-mom-spec-ops** [FreeTubeApp/FreeTube#2959]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Alright so my problem is that I cannot use a Google account on this, if I was able to, I would be using this as my primary YouTube (i think).

### Proposed Solution

My solution to that problem is Google integration, IM KIDDING OK, My actual solution would to be to integrate MicroG or another google account integration-but-not-google-stuff

### Alternatives Considered

No alternatives considered because there are no alternatives available for me to consider to like having google except the one here, but if I liked the solution a lot here I wouldn't be filing this issue request.

### Issue Labels

ease of use improvement, new feature, new optional setting

**Comment by ChunkyProgrammer** [comment]
I believe invidious would allow you to log in to google. This is not something that we would want to include in our app. :)

**Comment by EvilGremlin** [comment]
It's time to reopen this.
With youtube aggressively cracking down on requests from datacenters etc now, i think now there is no choice but to implement youtube login. I can't use direct connection becasue youtube is blocked here, can't use my VPS becasue it's datacenter (and non-DMCA country too) and even with Tor i have to reconnect manually a few times until i get non-datacenter exit node. 
Yes, this might go against this project principles, but as of now, app quickly becoming useless for way too many people, which goes against the project's very existence.
