### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Oh-My-Lands** [FreeTubeApp/FreeTube#2967]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open Freetube and expand the sidebar.
2. Above settings and below the about section, view the out of place separation bars.

### Expected Behavior

I expect the colored bars not to be there since they are visually jarring and serve no purpose.

### Issue Labels

visual bug

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Fedora Workstation 37

### Installation Method

Flathub

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

v0.18.0 Beta

### Additional Information

![image](https://user-images.githubusercontent.com/114635931/207931407-56e7f05d-f821-48e7-b593-6be2c7b4bf84.png)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as this isnt a bug
