### ISSUE TITLE
[Feature Request]: If history enabled, retain the playback speed used when watching the video

### ISSUE THREAD

**Issue by SethFalco** [FreeTubeApp/FreeTube#2983]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

By default, I have videos on FreeTube played back at 2.5x speed. However, for music I want only 1x speed.

It's a bit annoying to have to change the playback speed to 1x manually whenever I do want to listen to music, especially as it's normally just compilation videos I've watched before.

### Proposed Solution

If history is enabled, store the playback speed the user was using along with it so that it can be read back if the user visits that video again.

### Alternatives Considered

N/A

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This should be properly fixed by #1996 and https://github.com/FreeTubeApp/FreeTube/issues/2295
