### ISSUE TITLE
Enhancement: Improved Search Options

### ISSUE THREAD

**Issue by aproposnix** [FreeTubeApp/FreeTube#3]
Right now, the search function is simple and it works.  However, it is very limited.

It would be nice to be able to further filter searches... for example: 
 - Date filters (today, yesterday, month, year, etc) 
 - Duration
- Video Quality 
- Sort by date 
- Sort By Relevance
- Sort By Rating 
- Sort By View Count 

In terms of UX, it would be nice if you could go back to previous searches (classic back button functionality). I find it frustrating that I cannot do that.

**Comment by PrestonN** [comment]
This is definitely on the road map for enhancements.  This is something I'd like to have done before version 1.0.  Thanks for putting it on here so I can track it.

**Comment by gerroon** [comment]
Please at least add a way to sort based on publish date. Most of the time videos are not relevant due to dates are not considered.

**Comment by PrestonN** [comment]
Full search support has been implemented.  Expect to see it in the next release.
