### ISSUE TITLE
Looking Good! - I suggest a video sorting option

### ISSUE THREAD

**Issue by philiprhoades** [FreeTubeApp/FreeTube#30]
FT,

For some subscriptions I like watching the videos in uploaded order rather than category order eg:

https://safenetforum.org/t/maidsafe-dev-update-march-8-2018/22125

- is that possible to add as an enhancement?

Thanks,
Phil.

**Comment by aproposnix** [comment]
I think this is covered in #3 as it includes "sort by"

**Comment by philiprhoades** [comment]
Ah yes . . sorry, I did do a quick scan of the issues but didn't think to look at one with "search" in the subject more closely . . 
Thanks.

**Comment by PrestonN** [comment]
Hey there, looked like @aproposnix already caught it, but this looks like a duplicate.  I'm going to close this issue to keep the open issues cleaned up.  Feel free to open up another issue if you have other suggestions.

Thanks :)
