### ISSUE TITLE
live not play; message = 'write after end'

### ISSUE THREAD

**Issue by linuxgirl22** [FreeTubeApp/FreeTube#303]
Hi, love the new release, especially the layout, but an issue with live videos not playing ... blank screen, and 'write after end' message appears. Have tried the 3 different settings (dash/legacy/embedded), but same result. Happening with some non-live videos also. 
Arch KDE (beginner) and latest Freetube release via AUR (0.6.1-1)

**Comment by 0b10** [comment]
Looks like ytdl-core is throwing: https://github.com/FreeTubeApp/FreeTube/blob/21974110236c7b4855b6ae942458678f9cc07bdb/src/js/youtubeApi.js#L80-L86

**Comment by linuxgirl22** [comment]
Sorry, I should have looked at the console. Here's the output when I click on a live video. 

![console](https://user-images.githubusercontent.com/35760727/61193311-85c23e80-a6b2-11e9-9023-8b000bba85c2.png)

**Comment by PrestonN** [comment]
For now, you can disable "Grab Videos Locally" in your settings to prevent this from happening.  I will look into providing a proper fix for this in the mean time.

**Comment by PrestonN** [comment]
It looks like the issue was fixed a couple of days ago upstream.  I will include the fix along with the next release.

**Comment by linuxgirl22** [comment]
Thank you; disabling 'Grab Videos Locally' has worked perfectly, and great news about the fix. Much appreciate your work.
