### ISSUE TITLE
[Bug]: Some video times do not appear

### ISSUE THREAD

**Issue by maplepy** [FreeTubeApp/FreeTube#3034]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

As you can see in the screenshot below, some video times do not appear (Veritasium in that case) on a very tiny portion of videos

### Expected Behavior

Video times appear on every video

### Issue Labels

content not loading, feature stopped working, inconsistent behavior

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux 6.1.1-arch1-1

### Installation Method

AUR

### Primary API used

Local API

### Additional Information

![image](https://user-images.githubusercontent.com/28269333/210932042-bdf2eaf6-5963-4fc7-bb10-473036dd8457.png)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by maplepy** [comment]
It seems like it appears on shorts (havent properly tested this but veritasium video in the example was a short)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@maplepy could u check if this is still an issue for u. I cant reproduce this

**Comment by maplepy** [comment]
will check tonight if I see some shorts in my feed :)

**Comment by maplepy** [comment]
Still relevant indeed
![image](https://user-images.githubusercontent.com/28269333/218334047-b5001cbb-e8c5-483e-a331-e3ca90f2457d.png)
![image](https://user-images.githubusercontent.com/28269333/218334052-5b7a2619-3224-4928-ac11-863b1d54fc09.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@maplepy i cant reproduce this on the latest nightly build. Is this also the case on the latest nightly build for u?

**Comment by maplepy** [comment]
I'll try to install the latest nightly build and will let you know when I go back home :)
