### ISSUE TITLE
No sound / Not available in your country

### ISSUE THREAD

**Issue by BrainlessConsumer** [FreeTubeApp/FreeTube#304]
Regardless of the three video players in 6.0.1 some channels have no sound or are unwatchable unless played in a browser version of invidio.us

Also why are video downloads repeatedly stopping?

**Comment by awsms** [comment]
Having the same issue here with random videos.

Sometimes I just have the pop-up "This video is not available in your country", go to the history, reload it and it works.

**Comment by superfreeman1989** [comment]
Some 720p videos will create this message and switch to legacy player.
