### ISSUE TITLE
"Play Next Video" setting not saved between sessions

### ISSUE THREAD

**Issue by triatic** [FreeTubeApp/FreeTube#305]
The "Play Next Video" setting in "Player Settings" is not saved between FreeTube sessions. The setting is lost when FreeTube is closed.

**Comment by PrestonN** [comment]
I've found the problem and pushed out a fix.  I don't know if I'll do another patch release just yet but the fix will be included in whatever the next release is.

**Comment by fjrider** [comment]
I have noticed this issue on my OSX and Linux Mint machines.  Both loose the "Play Next Video" setting after the app is closed and opened again.

**Comment by PrestonN** [comment]
@fjrider The fix has already been made but it has not been added to any release yet.  The next release that comes out (should be very soon) will have the fix for this.
