### ISSUE TITLE
[Feature Request]: Customisable scrollbar size

### ISSUE THREAD

**Issue by BarbzYHOOL** [FreeTubeApp/FreeTube#3057]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I'm using a remote to control Freetube on my TV

The remote has no scroll wheel or button. So I am forced to use the mouse to select the scroll bars (or use pg down but it's very unprecise)

The bar on the right is hard to get, the bar on the left (with the channel list) is ultra hard to select

### Proposed Solution

Please add options to allow customising the scrollbar size and making them always visible.

### Alternatives Considered

None

### Issue Labels

ease of use improvement, improvement existing feature, new optional setting

**Comment by niceFont** [comment]
I would like to work on this, can you assign it to me?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> I would like to work on this, can you assign it to me?

Done!

**Comment by BarbzYHOOL** [comment]
> I would like to work on this, can you assign it to me?

thanks if you do!

**Comment by MichaelMackus** [comment]
Yes, I agree. It is much too small currently IMO. 

It looks like the original PR was closed unfortunately. Can I take that over? It looks like it just had some conflicts, not sure what else that needs to be done without diving in.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sure u can take it over, please read the conversation after their latest commit there were some things that need to be addressed

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@MichaelMackus what is your status on this do you need any help?

**Comment by MichaelMackus** [comment]
Haven't gotten started on this yet, I've gotten distracted by other things
atm.

**Comment by jurekcy** [comment]
@MichaelMackus any progress?

**Comment by cplittlfield** [comment]
I realise that making scroll bars extremely narrow and then hiding them from view is considered elegant design; however, those of us who are older and whose hands shake a bit have trouble getting invisible skinny scroll bars to show up and positioning the pointer accurately on the very narrow width of the scroll bar, once it is visible.  Poor eyesight is no help, here, either, lol!

I have my Linux Mint theme set to make scroll bars always visible and wide enough that I can put the pointer on them without too much trouble; however, FreeTube ignores those settings, so an accessibility feature that would permit making FreeTube scroll bars wide and always visible would be a great addition to the user interface.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@BarbzYHOOL we aim to have good defaults for everyone instead of everything being customizable. If we would make every part of the application customizable it would bloat and slow down the application. In v0.21.0 beta we have made the scrollbars bigger. Does this solve the issue you are having with the scrollbars?

**Comment by scriptsforweirdos** [comment]
The scrollbars in the Windows exe version used to honor my accessibility changes in the registry which make my scrollbars 30px wide. 

In 0.24.0 beta this is no longer the case, making it nearly impossible for me to scroll down without pgup/pgdn. I can't even see the scroll bar now, let alone click on it. I have no scroll wheel.

Please honor scrollbar width instructions from the OS.
