### ISSUE TITLE
0.6.1 Beta no longer working since yesterday

### ISSUE THREAD

**Issue by aproposnix** [FreeTubeApp/FreeTube#306]
Since yesterday, none of my subscriptions would refresh. I just get an error telling me that subscription X could bot be refreshed.  I have reset the app by removing all data but the issue persists. Was there a change in the API used to get the data? 

EDIT: 
I'm in the EU
I'm running Ubuntu 18.04

**Comment by PrestonN** [comment]
Is the issue still happening?  I'm not seeing any problems on my end using a UK IP with Ubuntu 19.04.  It's possible there was an issue with Invidious earlier but it seems to be working right now.

If it still isn't working, you could maybe try pointing FreeTube to one of the other [public Invidious instances](https://github.com/omarroth/invidious/wiki/Invidious-Instances) to see if that solves your problem.

**Comment by aproposnix** [comment]
@PrestonN I tried that with the invidious link. It now allows me to load trending... unfortunately I get import errors on the backup I made so I cannot test my subscriptions at the moment. However, I can subscribe to other channels and they seem to work.  

Also, when I click on the "most popular" link on the side panel, it freezes the whole application. I'll try to create a bug report for this one later.

**Comment by PrestonN** [comment]
I believe if you add `.db` to the end of your exported file, it should import properly.  I've already made this fix for the next release.

Which instance are you using so I can test?  I some instances might be able to disable Most Popular which could be the problem.

I'll have to look into an instance fallback if the main one doesn't work.  I don't know when I'll look into it but if this issue becomes more common then I'll push up the priority.

**Comment by aproposnix** [comment]
Sorry for being a noob, but what do you mean by the instance?  Do you mean the version of the app? 

> Which instance are you using so I can test? I some instances might be able to disable Most Popular which could be the problem.
> 
> I'll have to look into an instance fallback if the main one doesn't work. I don't know when I'll look into it but if this issue becomes more common then I'll push up the priority.

**Comment by PrestonN** [comment]
I apologize for being unclear.  Which Invidious server do you have FreeTube pointed to?

**Comment by aproposnix** [comment]
Based on your previous post I had switched it to https://invidious.13ad.de but it was the same as the main US instance. I had also tried another German server (sorry don't have the URL handy at the moment but it was the first German one on the list). 

I'll try more of them later and report back if any of them work.

**Comment by PrestonN** [comment]
I was able to replicate the issue using the instance that you linked.  It looks like that instance isn't returning the amount of views a video has when grabbing videos from their "Popular" page, which crashes FreeTube.  I can fix it on my end but I think it would be better for the instance admin to update their version of Invidious as it looks like the issue doesn't exist on https://invidio.us

**Comment by aproposnix** [comment]
The weird thing is that https://invidio.us was the one where I first got the issue. 

Anyway, thanks for the help in getting me sorted. It's much appreciated.

**Comment by PrestonN** [comment]
You're very welcome.  It's possible that @omarroth quickly noticed and fixed the issue sometime during this.  It would explain why some instances don't have the fix just yet.

As everything seems to be sorted here, I'll go ahead and close this issue.  Thanks for the support!
