### ISSUE TITLE
[Feature Request] uBlock Origin Integration

### ISSUE THREAD

**Issue by grravity** [FreeTubeApp/FreeTube#307]
So, due to the integrated player having issues with anything higher than 720p, I think a good temporary fix for users who want to be able to view higher quality videos, is to have an integration of uBlock Origin into FreeTube and then use the YouTube player. So we don't have to deal with pesky ads or popups.

I have uBlock Origin installed on my browser, and have not gotten a single YouTube ad in absolutely forever. I think if it was integrated, it would be nice to allow users to add their own host and choose their own blocks. For example, in my case I run jspenguins Nano adblocker in my userResourcesLocation and it works absolutely amazingly. (https://jspenguin2017.github.io/uBlockProtector/)

**Comment by PrestonN** [comment]
What sort of issues with the player are you having?  The main player already supports higher qualities.

**Comment by Z3ROGRAV1TYx** [comment]
@PrestonN Weird, I wasnt getting  options past 720p in legacy or main only YouTube player
But with youtube player i was getting those annotations ads at the bottom of videos

**Comment by PrestonN** [comment]
If you use the Legacy player, you will be capped at 720p as it is only playing legacy non-dash formats.  The main Dash player is the only way to watch higher qualities.

What video are you testing with?  If there's a problem with a video not displaying the proper quality option then I can look into it.

**Comment by UnoYakshi** [comment]
I still think having uBlock Origin inside of FreeTube is a great addition. Let's say it is extra insurance.
Following the same idea, I'd probably add JShelter, too.
