### ISSUE TITLE
[Bug]: missing subtitles 

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#3071]
### Guidelines

- [ ] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Support for subtitles was removed again (from portable version only?) by the commits from Jan 7th (probably #3035 or #3036).

### Expected Behavior

There should be a button for selecting subtitles as it was before.

### Issue Labels

feature stopped working

### FreeTube Version

v0.18.0-nightly-2514

### Operating System Version

Windows 11 22H2

### Installation Method

Portable

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18.0-nightly-2514

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Subtitles show up on videos for me, some videos don't have any though. Could you please provide some links to videos that don't work for you and what language you are using FreeTube in?
