### ISSUE TITLE
[Bug]: missing subtitle button

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#3095]
### Guidelines

- [ ] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [ ] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Most videos (for me, maybe language dependent or whatever) are missing the subtitle button now so they cannot be selected.
Example videos: [1](https://youtu.be/TwJcSD7WsB0), [2](https://youtu.be/3WvRrm2at3w)

### Expected Behavior

Videos with subtitles should have a subtitle button so that they can be used again.

### Issue Labels

feature stopped working

### FreeTube Version

v0.18.0-nightly-2566

### Operating System Version

Windows 11 22H2

### Installation Method

Portable

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18.0-nightly-2514

### Additional Information

Same as this closed (without fixing) issue #3071.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Thanks for trying out all of the languages, it would have been quicker to open the devtools and take a screenshot of the error, although I forget sometimes that not everyone knows about the devtools.

Turns out it was a simple typo `languageCode` instead of `language_code`.
