### ISSUE TITLE
[Feature Request]: Videosettings -> higher default quality than 1080p

### ISSUE THREAD

**Issue by smausenberger** [FreeTubeApp/FreeTube#3096]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

In the playersettings the option for the default quality ranges only from automatic to 1080p.

### Proposed Solution

Add more resolutions, 1440p, 2160p, ...

### Alternatives Considered

Add a setting to always choose the maximum available resolution.

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing because we dont support those qualities at the moment. See https://github.com/FreeTubeApp/FreeTube/issues/2013
