### ISSUE TITLE
[Bug]: blurred screen in windows 7

### ISSUE THREAD

**Issue by Thiago92nr** [FreeTubeApp/FreeTube#3098]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

In windows 7 I am having an error, the screen is blurry sometimes.

### Expected Behavior

Videos should be shown normally.
![image](https://user-images.githubusercontent.com/32148073/213870432-d5c2c952-2110-496b-849d-a329dce1c49f.png)
![image](https://user-images.githubusercontent.com/32148073/213870466-1dbb014d-e12d-46f8-b19c-91c4932b0745.png)
![image](https://user-images.githubusercontent.com/32148073/213870495-2f58b664-ed61-4ba9-8e4a-bf1e179e283d.png)

### Issue Labels

visual bug

### FreeTube Version

0.18.0

### Operating System Version

Windows 7 sp1

### Installation Method

.exe

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
You may need to switch to "legacy formats" https://docs.freetubeapp.io/usage/video-formats/

**Comment by ChunkyProgrammer** [comment]
https://github.com/FreeTubeApp/FreeTube/issues/2296 may fix this as well

**Comment by Thiago92nr** [comment]
> You may need to switch to "legacy formats" https://docs.freetubeapp.io/usage/video-formats/

this solution worked fine for me, thanks a lot everyone
