### ISSUE TITLE
Subtitle support

### ISSUE THREAD

**Issue by dimqua** [FreeTubeApp/FreeTube#31]
Can you please add support for subtitles? 
Thanks for such a great app!

**Comment by PrestonN** [comment]
Thanks for adding this on here.  This was something I was thinking about doing and having issues created on here helps me keep track of it better.

With the recent switch to youtube-dl, I believe that this can be done sooner than before.  I'll definitely look into it and get this working for a future release.

Cheers :)

**Comment by PrestonN** [comment]
Hey there.  This has been added as of my latest commit.  This will be included in the next release. :)
