### ISSUE TITLE
[Feature Request]: Improve chapters selection

### ISSUE THREAD

**Issue by BarbzYHOOL** [FreeTubeApp/FreeTube#3102]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I don't think it's very practical either with a mouse to have to scroll down and hide the video to click on the chapters. I mean, it probably could be easier to use.

### Proposed Solution

I tried the current youtube desktop method, it appears on the right, which is easier to use. 
But the best way is inspired by the android tv official youtube app.

For screenshots, it's hard to find. here is what I found:
https://images.frandroid.com/wp-content/uploads/2021/12/chapitres-youtube-frandroid-1-1200x737.jpg
https://tekdeeps.com/youtube-will-also-display-video-chapters-in-the-smart-tv-and-game-console-app/

I think it has been updated a little since then. So what it does is that you press the "up" arrow, it displays the timeline of the video with the chapters sections and current chapter like in the screenshots, then you press the right/left arrow and it pauses the video and lets you navigate the timeline, if you press the up arrow again you can navigate through the thumbnails of each chapter (i found it alone, so it means it's not even hard to use) and it jumps on the timeline as well, press OK and it jumps to it. You don't have to leave the video at all, it would work in full screen on a desktop.
I use it all the time.

### Alternatives Considered

Shown on the right like the youtube desktop site.

### Issue Labels

ease of use improvement, improvement to existing feature

### Additional Information

This could also be very useful for people using a remote to control freetube, but it would be useful to anybody anyway.

**Comment by BarbzYHOOL** [comment]
A way to make this would be to mimic the actual youtube desktop feature "More videos" at the end of a video, where you can click for more videos, but here with chapters

**Comment by awsms** [comment]
Would be cool to show the chapter name when hovering the progress bar, and display the current chapter next to the timecode; just like YT does

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We would like to stick as close to the YT design like how it is in the browser. Therefore i'm closing this in favor of https://github.com/FreeTubeApp/FreeTube/issues/2829
