### ISSUE TITLE
[Bug]: Constanty reverts to Legacy formats

### ISSUE THREAD

**Issue by cardcraft** [FreeTubeApp/FreeTube#3103]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When format is set to Dash in settings or set via the dashboard FreeTube will randomly switch any video back to legacy formats. At that point it is impossible to set it back to Dash without a restart.

### Expected Behavior

When I set it to Dash it should use Dash not Legacy

### Issue Labels

usability issue

### FreeTube Version

v0.18.0 BETA

### Operating System Version

Kubuntu 22.04

### Installation Method

.AppImage

### Primary API used

Local API

### Additional Information

It hasn't ever worked in any version from my experience

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
Can you try a nightly build? 
https://docs.freetubeapp.io/development/nightly-builds

https://github.com/FreeTubeApp/FreeTube/actions/runs/3974207060
