### ISSUE TITLE
[Bug]: Channel doesn't exist despite videos shown in search and playable 

### ISSUE THREAD

**Issue by gonzoknows** [FreeTubeApp/FreeTube#3104]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. search my videos "ChatGPT history gonzoknows"
2. subscribe to my channel
3. go to subscriptions and it will show my channel has an error 
4. click my channel, and it will show no videos and display this error. 
![image](https://user-images.githubusercontent.com/122128828/213901385-59b16bea-bb69-49a2-b1d3-3f35d61021d3.png)

### Expected Behavior

to be able to view channel content 

### Issue Labels

usability issue, visual bug

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux, Vanilla OS (Release 3)

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

Content is viewable when searching it manually. 
![image](https://user-images.githubusercontent.com/122128828/213901430-3416af5d-78f8-47a0-bfe6-610df3cfc3a0.png)
![image](https://user-images.githubusercontent.com/122128828/213901441-f0d5ca01-3644-441c-bc70-cf16de0501cd.png)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
Hi,
I'm unable to reproduce this error:
![image](https://user-images.githubusercontent.com/78101139/215131062-e13a7c11-bc06-4f33-adc8-62be7a292ea0.png)

Could you use `Ctrl + Shift + i` to open dev tools and send a screenshot of the error?
