### ISSUE TITLE
[Bug]: Missing number of likes

### ISSUE THREAD

**Issue by petcat30** [FreeTubeApp/FreeTube#3108]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I'm not seeing the amount of likes on any video, just a thumbs up with nothing.
![23_Tu9L2q5BN7mHfFTVqDKI](https://user-images.githubusercontent.com/108421858/213974373-e2bc695e-2d3d-49d6-8615-b94c3471fe3c.png)
![23_nazl7D0LDFSlmAjfUtJz](https://user-images.githubusercontent.com/108421858/213974379-58973bc9-5393-4153-b1ca-44ecc7921f5f.png)

### Expected Behavior

Should see the amount of likes next to the thumbs up.

### Issue Labels

visual bug

### FreeTube Version

v0.18.0

### Operating System Version

Windows 10 22H2

### Installation Method

Portable

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Growebis** [comment]
Funnily enough, if you switch to invidious as the primary API, the likes show but not the view count.

**Comment by ChunkyProgrammer** [comment]
@petcat30  This is fixed in the nightly builds (see: https://docs.freetubeapp.io/development/nightly-builds for how to download a nightly build or you can wait for the next release) 😄 
![image](https://user-images.githubusercontent.com/78101139/214907412-bc62c35d-4c8e-4f5e-820f-0d3efa3511d7.png)

@Growebis  You can follow a PR for the invidious fix here if you'd like 😄 : https://github.com/iv-org/invidious/pull/3557
