### ISSUE TITLE
Security concern: "nodeIntegration" option needs to be disabled

### ISSUE THREAD

**Issue by vladimiry** [FreeTubeApp/FreeTube#311]
- The simplest way to require the nodejs libraries and use the functionality of the main process is to do that in preload script via `remote` handle.
- The better option is to use IPC communication for everything but this way is normally more compliated in terms of implementation.

I don't have the time capacity to handle the issue on my own.

**Comment by PrestonN** [comment]
I understand the concerns with having this enabled, though since we don't navigate to any external pages and everything is ran locally I am willing to accept this risk and see it as a non-issue.
