### ISSUE TITLE
[Feature Request]: hide/sort wached videos

### ISSUE THREAD

**Issue by makerio90** [FreeTubeApp/FreeTube#3120]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

the subscription tab often gets flooded with videos I've already watched

### Proposed Solution

ether
 - have a button to hide videos that have already been watched (kinda like newpipe) or
 - have an option to sort the videos by watch time

i personally like option 2 since free tube counts any amount of watch time as "watched

### Alternatives Considered

N/A

### Issue Labels

ease of use improvement

### Additional Information

i attempted to do the first idea (hide watched videos) but i didn't get very far due to my limited vue knowledge

**Comment by absidue** [comment]
In the subscription settings there is a `Hide videos on Watch` setting, you need to have `Remember History` turned on in the privacy settings for it to work, but that should, if I'm understanding your features request correctly, already cover what you are asking for.

**Comment by makerio90** [comment]
i was unaware of this setting, but i still think that it would be nice to have that option available on the list page itself, like next to the reload button, so that it could be quickly toggled
