### ISSUE TITLE
[Bug]: Loudness set to full when unmuting

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#3125]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click on a Video.
2. Video starts unmuted (because I might have muted the last video).
3. I click unmute.
4. The Video continues with full loudness (100%).

### Expected Behavior

Loudness should be set to my standard value, which is 20%.

In general I would recommend to not set the Loudness to 100%, when unmuting.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.18.0.beta.9d679cd9

### Operating System Version

Manjaro Linux

### Installation Method

AUR

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

-

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Completed in #3203
