### ISSUE TITLE
Window position stays on a secondary monitor even if it's disconnected.

### ISSUE THREAD

**Issue by RiabikovR** [FreeTubeApp/FreeTube#313]
Windows build.
If FreeTube window is opened on a secondary monitor, closed, and then said monitor is disconnected, FreeTube will remember the window's position, and the next time will open outside of the viewport with no way to move it back without connecting the monitor again.

**Comment by PrestonN** [comment]
This was actually mentioned a while back on our Matrix server.  The fix has already been made and will be included in the next release.
