### ISSUE TITLE
[Bug]: Block a.nel.cloudflare.com logging domain

### ISSUE THREAD

**Issue by mctvcse839** [FreeTubeApp/FreeTube#3151]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Using various software to analyse network requests I noticed that freetube sends request to a.nel.cloudflare.com which is a network logging domain. I can block it locally with the software I have and it has not effect on the functionalities. I was wondering if it's possible to block this telemetry domain for privacy reasons. It sends request quite often about 1 to 10 times a minute.
source: https://support.cloudflare.com/hc/en-us/articles/360050691831-Understanding-Network-Error-Logging

Also on that note I was also wondering why are there requests for the write.as domain?

Reducing third party network request is ideal for a project aiming for privacy. Furthermore if it's a logging/telemetry domain.

### Expected Behavior

Block logging/telemetry domain

### Issue Labels

API issue

### FreeTube Version

0.18.0

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
When the "Check for Latest Blog Posts" setting is enabled FreeTube gets the RSS feed of blog posts  for the FreeTube blog (https://write.as/freetube/feed/), so you can disable that setting to stop requests being made to write.as.

As for the cloudflare stuff that is very odd, FreeTube doesn't have any code that sends requests telemetry to cloudflare or any other kind of telemetry, feel free to dig through every line of code in this repository if you don't believe us.

If you are 100% sure that those requests are coming from FreeTube (you've been quite vague about how you detected the requests), not any other app or the operating system itself, then we'll have to investigate our dependencies, because it's definitely not coming from any of our code.

**Comment by mctvcse839** [comment]
Thank you for clarifying the write.as domain.

As for the tools, I used portmaster which is a firewall that intercepts and shows request for each individual application on windows 10 and linux. I also saw the same requests using proxifier a software that proxies specific programs. I doubt this is a mistake.
Here is a screenshot of portmaster and the request coming from freetube.
![image](https://user-images.githubusercontent.com/124193980/216828541-da5f5a09-a975-4007-8314-c9343321aa2a.png)


After opening the developer tools there was a request for ajay.app that had a report-to header for the a.nel.cloudflare.com domain.
![image](https://user-images.githubusercontent.com/124193980/216828614-56ed2ed4-dfee-470e-8d26-7872a93b0f14.png)

Not sure if it's possible to remove this on your end or someone has to contact this sponserblock domain to ask them kindly to disable this option which is on by default.

**Comment by absidue** [comment]
Ah that makes sense, SponsorBlock uses Cloudflare to reduce the load on their servers, so those headers are added by Cloudflare. We can try to remove the header before it gets processed (can't promise it will work), although if you are worried about Cloudflare knowing what you are doing, then you'll have to stop using SponsorBlock as all the requests to the SponsorBlock API go through Cloudflare.

**Comment by absidue** [comment]
You can always host your own SponsorBlock instance, as the server code and dataset are both available: https://github.com/ajayyy/SponsorBlock#server

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
i dont think this is ours to address based on what im reading in our [documentation](https://docs.freetubeapp.io/usage/sponsorblock/)

**Comment by ajayyy** [comment]
I have disabled "Network error logging" on cloudflare as requested in https://github.com/ajayyy/SponsorBlock/issues/1667

Also, if anyone wants to use SponsorBlock without cloudflare MITM every request, change your API url to "https://api.sponsor.ajay.app".

I do want to get off cloudflare entirely at some point but right now it causes too many issues.
