### ISSUE TITLE
Inconsistent FreeTube miniplayer window aspect ratio

### ISSUE THREAD

**Issue by katktv** [FreeTubeApp/FreeTube#316]
the ability to resize the miniplayer horizontally and vertically is useless because the player itself doesn't adapt properly to the window size. either the player window should maintain aspect ratio of the player, or it should be centered according to the window size (probably more preferable so it won't clash with windows 10 multitasking features)

For reference, here's how mpv handles it
![XWnKWK5EOl](https://user-images.githubusercontent.com/47599466/62487504-8fbaf700-b7b1-11e9-95d4-3e6ddea3830a.gif)
 
Here's the current behavior of FreeTube
![POwVPnQx7H](https://user-images.githubusercontent.com/47599466/62488010-c2192400-b7b2-11e9-9de7-a83a6a375669.gif)

**Comment by PrestonN** [comment]
I've made an attempt to better resize the window when it is being changed.  For the next release, it should work the expected way when resizing horizontally or diagonally, but not vertically.  Hopefully this should at least help when resizing the mini-player.

**Comment by Emaro** [comment]
Currently, the mini player misses a bit vertical size so the progress bar is hidden and you are not able to select a timestamp. And the window flickers while resizing.
