### ISSUE TITLE
[Bug]: `Ctrl + Q` shortcut doesnt work

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3165]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open FT
2. Try to close the window with `Ctrl + Q`
3. See open window

### Expected Behavior

Windows closes

### Issue Labels

keyboard control not working

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/fa8cc07b5e9ebd831b0806cf6384cc6d9005f6e6

### Operating System Version

Windows 10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
Did this used to work?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@ChunkyProgrammer im not sure if this used to work. I tested all the shortcuts after i noticed that one didnt work (https://github.com/FreeTubeApp/FreeTube/issues/3160). So i looked into our docs, tested all and this was the only one that didnt work.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@ChunkyProgrammer i think this was never implemented based on https://github.com/FreeTubeApp/FreeTube-Docs/pull/27 the description of the pr body
