### ISSUE TITLE
At startup, the default theme and filter options are briefly displayed

### ISSUE THREAD

**Issue by SicroAtGit** [FreeTubeApp/FreeTube#318]
I have set the dark theme and when I start the program, the default theme is briefly displayed before switching to the dark theme.

The filter options are also displayed briefly.

**Comment by SicroAtGit** [comment]
> The filter options are also displayed briefly.

This is now no longer the case.

However, in the current version (0.14.0 Beta), the program still briefly shows a blank white window content at startup, then briefly shows the default light theme and then the configured dark theme.

So I don't understand why this issue was closed. Yes, I know it's a negligible problem, but maybe it's easy to fix.

Screen video recording:
![Record](https://user-images.githubusercontent.com/18380976/136707987-0e8716fe-e64b-471f-959c-91dc1947ef3f.gif)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Blank window will be dealt with in a upcoming PR

And the light theme is already fixed in the latest nightly builds

**Comment by SicroAtGit** [comment]
Thanks for the good news :-)
