### ISSUE TITLE
[Feature Request] Make video subtitles selectable

### ISSUE THREAD

**Issue by 1over137** [FreeTubeApp/FreeTube#3195]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Video subtitles are not selectable. Making it selectable should be a minimal change, and would be very helpful for language learners who want to look up words or translate sentences. 

### Proposed Solution

Set the text to selectable. I think it would be fine for it to just be the new behavior, but it would be fine to make it an option as well.

### Alternatives Considered

In browsers, there are various extensions to make them selectable, but they are not available for use in freetube.

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @1over137 what about downloading the subtitles from within FT and opening them in your editor of choice

**Comment by akramalyaseen31-star** [comment]
yes i well be so happy if it would be added
