### ISSUE TITLE
Electron Helper detected as virus in Virustotal

### ISSUE THREAD

**Issue by idcristi** [FreeTubeApp/FreeTube#3197]
### Describe the bug
TaskExplorer detects Electron Helper, Electron Helper (GPU) and Electron Helper (Renderer) as virus.

### Screenshots
Attached there are the screenshots from the TaskExplorer.
![Screenshot-1](https://user-images.githubusercontent.com/17257053/219128373-6441e474-b019-4849-b4e9-8fffc56988bd.jpg)
![Screenshot-2](https://user-images.githubusercontent.com/17257053/219128388-5f3fc253-0081-48cc-be80-1da47b92e0aa.jpg)

### Expected Behavior

Solve the issue in the next release.

### Issue Labels

inconsistent behavior

### FreeTube Version

v.0.18.0

### Operating System Version

macOS 13.0

### Installation Method

.dmg

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18.0

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isnt anything to worry about see https://docs.freetubeapp.io/faq/#my-virus-protection-gave-a-warning-when-i-tried-to-run-freetube-is-freetube-a-malicious-application
