### ISSUE TITLE
[Feature Request]: Mark As Skipped

### ISSUE THREAD

**Issue by hl2guide** [FreeTubeApp/FreeTube#3198]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There is currently no "skipped" status for videos in the Subscriptions video feed.

### Proposed Solution

Please add a "Mark As Skipped" option to the Subscriptions video feed's video context menu.

### Alternatives Considered

use as is

### Issue Labels

display more information to user

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@hl2guide your problem description isnt clear to me what problem solves this?

**Comment by hl2guide** [comment]
> @hl2guide your problem description isnt clear to me what problem solves this?

The problem of incorrectly having to mark skipped videos as "watched" and then the history is incorrect.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
But why would u want to mark something as skipped? What should that do?

**Comment by hl2guide** [comment]
its just a status that has an accurate meaning for the history list.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Going to close this because we think that 'marked as watched' is an accurate representation.
