### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by meatspinner** [FreeTubeApp/FreeTube#3206]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When you click on the 3 dots close to a video name, you have a "Mark As Watched" option but the effects after you click it are the same as when you click a video but don't watch it, making it hard to tell if you've actually watched the video or not.

### Proposed Solution

The "Mark As Watched" feature should show the purple line on the video thumbnail so that one can know they've actually watched the video.

### Alternatives Considered

None

### Issue Labels

display more information to user, improvement to existing feature, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This sounds like a wont fix.

Screenshot of the history page:
![Capture](https://user-images.githubusercontent.com/73130443/219952443-855f100d-455a-4b5e-be88-d4c90b73a8c1.PNG)

Screenshot of the subscription page:
![Capture1](https://user-images.githubusercontent.com/73130443/219952448-12051f5f-5c8e-4082-a5d2-0ae5070311fc.PNG)

The red line clearly marks that the video has been watched to a certain point and if u dont see it u have marked it as watch manually and u dont see the line.
