### ISSUE TITLE
[Bug]: Not all profiles' channels are shown in the "Channels" tab.

### ISSUE THREAD

**Issue by Giger22** [FreeTubeApp/FreeTube#3211]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click on "Channels".
2. I got "0 channel(s) found"
NOTE: This happens only for random profiles.

### Expected Behavior

1. Click on "Channels"
2. All channels appear regardless of profile selected.

### Issue Labels

content not loading

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Artix Linux 6.1.12 64 bit

### Installation Method

Flathub

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

v0.17.0 
(not sure if I hadn't had a problem back then but looks like there was an issue 
https://github.com/FreeTubeApp/FreeTube/issues/1642
but the thread is closed) I tried fix but it did not help me.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
Could you provide a link for one of these profiles?

**Comment by Giger22** [comment]
I mea normal profiles that you can add manually.
[FreeTube profile list](https://i.imgur.com/2EjHEZW.jpg)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Giger22 do you still face this issue in v0.20.0?
