### ISSUE TITLE
[Bug]: Local API Error TypeError: Cannot read properties of undefined (reading 'sWidth')

### ISSUE THREAD

**Issue by inflictedgolf38** [FreeTubeApp/FreeTube#3217]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Any video from linux tech tips usually has the same effect,
opening the video throws a typeerror
Local API Error: TypeError: Cannot read properties of undefined (reading 'sWidth')
tried clicking the warning to copy it but it does nothing.
invidious does work mostly, if I'm using my vpn because i think my uni blocks most invidious clones

### Expected Behavior

it should just open the video but i assume linus messes with the video width by a few pixels for this exact reason (i have seen it on no other videos), to force people to watch on youtube. really annoying but still

### Issue Labels

API issue, content not loading

### FreeTube Version

0.18.0

### Operating System Version

Windows 10 Home Version 21H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Firlaev-Hans** [comment]
Having the same issue (Flatpak 0.18.0), although after a minute or two the content does load for me (just gotta be patient).

You might want to update the title of this issue to something more descriptive tho :D

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing, because fixed in [the nightly builds](https://docs.freetubeapp.io/development/nightly-builds).
