### ISSUE TITLE
The menu/channel list scrollbar goes under the top panel

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#322]
I noticed that the menu/channel list scrollbar goes under the top panel, and when the scrollbar is really short, you can't target it, and you have to scroll a little bit down, which isn't really convenient when you want fast access to some of the channels from the middle of the list.

**Comment by PrestonN** [comment]
This has been fixed and will be in the next release.

**Comment by morfikov** [comment]
I can confirm that this works nice now.
