### ISSUE TITLE
Add "fetch more" to the Latest Subscriptions tab

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#323]
When you have lots of channels, the `Latest Subscriptions` tab can contain only the most recent positions from all the channels, and they can rotate really quickly. Could you add "fetch more" to this tab?

**Comment by Asgaros** [comment]
I also would love to see this because especially after a longer holiday you can have a lot of unwatched videos in your list which are not accessible anymore without the possibility to load more videos.
