### ISSUE TITLE
[Feature Request]: PIP (Picture-in-Picture) Double Click Fullscreen

### ISSUE THREAD

**Issue by o-data** [FreeTubeApp/FreeTube#3232]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Would like to be able to go Fullscreen from PIP, right now we need to "Back to Tab", go to Freetube and then click Full Screen.

### Proposed Solution

Able to double click the PIP to go Fullscreen directly

### Alternatives Considered

A button to Full Screen if we can't double click. Or in focus, we can press "F" to full screen (shortcut)

### Issue Labels

ease of use improvement, new feature, new keyboard shortcut

**Comment by msagr** [comment]
Nice, Lets try to implement it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This will be closed because the cannot be implemented properly due to the limited functionality of the current upstream PIP implementation
