### ISSUE TITLE
[Feature Request]: Store captions to enhance search

### ISSUE THREAD

**Issue by Victor239** [FreeTubeApp/FreeTube#3233]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Searching through your history of videos based on just the video title is too limited.

### Proposed Solution

The user should be able to search their history using keywords from the video captions. I might forget the exact name of the video, but I have a good idea of some of the things said or at least the keywords used.

### Alternatives Considered

https://incaptions.com is a web-based search engine for captions, but it's not as accurate as searching your own video history.

### Issue Labels

improvement to existing feature, new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as this would bloat the database file enormously and this issue has been identified as too niche of an usecase.
