### ISSUE TITLE
[Bug]: Cant load subscription to my "profile".

### ISSUE THREAD

**Issue by 9acca9** [FreeTubeApp/FreeTube#3244]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When i import the subscriptions all the channels goes to "all channel" profile. And cant see any subscription in my profile. I want to add a new profile but, if i cant separate the channels... then is not too useful.
I see this when importing:
![Captura desde 2023-03-02 18-07-50](https://user-images.githubusercontent.com/25393371/222553818-6665a13b-e3f0-4f22-bb8b-b845e463ee53.png)

Thanks.

### Expected Behavior

Import subscriptions to the profile.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Garuda Linux

### Installation Method

other

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
So just to be clarify. U have imported your subscriptions into the All channels profile and that worked but when u wanted to do the same for another profile it didnt work?

**Comment by 9acca9** [comment]
"All channels profile" exist be default. 
Then i make a profile called "Me" i select that profile and make the import of subscriptions. None of the subscriptions go to my "me profile" they go to "all channels". 

I "fix"  that selecting **all the channels** of "All channels" profile like this:
![image](https://user-images.githubusercontent.com/25393371/222967247-358826a5-2c4d-4604-a348-ad9461263492.png)
(this is just an example im not in my machine so i have nothing in the image to import).

But the problem is that that "fix" will not work because if i want to add another profile i will have mixed "Me" profile and "the new" channels in "All channels" (from the new profile), in that case i can do it by hand but... is a lot of channels to discriminate.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
So this issue you are describing is intended behavior. You should do the following. 

1. Import subscriptions into all channels profile
2. create another profile
3. go to that profile settings
4. use the filter on the bottom based on the all channels profile
5. select the subscriptions u want in that profile


https://user-images.githubusercontent.com/73130443/223073059-61cb6c85-e460-4d51-a30e-acdfbb3a5d49.mp4

I agree with u that it should change but that is tracked in https://github.com/FreeTubeApp/FreeTube/issues/1996

**Comment by 9acca9** [comment]
Yep, that is what i did for the first profile but if you make another profile.... then you will have to select by hand and your new channels will be mixed with the all profile in the "all channels" and then you will need to discriminate between a lot of channels, you cannot select all like in a just 1 profile.

**Comment by absidue** [comment]
That is intentional behaviour, because while the YouTube subscriptions export is just a list of channels, if you export your subscriptions from FreeTube, it includes all of your profiles. So your "import into the currently selected profile" idea doesn't work for the FreeTube subscriptions import unless you want to break it.
