### ISSUE TITLE
[Bug]: Shared posted on community tab isnt visible 

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3252]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Here the creator shared an post on her timeline but it isn't showing on ours

https://user-images.githubusercontent.com/73130443/222265814-edc75d65-6ca1-48c8-bcca-79d8404167a7.mp4

### Expected Behavior

Implement fix when https://github.com/LuanRT/YouTube.js/pull/334 is merged

### Issue Labels

content not loading

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/4ef2f709ee8983029033a0952dfd22ba86bef6ac

### Operating System Version

Win10 22h2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://github.com/LuanRT/YouTube.js/releases/tag/v3.2.0 has been released!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not quite happy how it is being displayed right now. It doesnt say it is shared and the shared text isnt being displayed

![Screenshot (303)](https://user-images.githubusercontent.com/73130443/236672883-39e67f97-c712-463d-9694-040f00235ec8.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is a better look of it and u also see where the shared comment of the channel owners is.

https://github.com/FreeTubeApp/FreeTube/assets/73130443/aaff7f48-770c-4a9e-b7c4-22752797017f

Edit: also tested with the channel i posted in the issue and can confirm it is the same.

**Comment by PikachuEXE** [comment]
Small style, steps:
- Create a new profile (no sub)
- Subscribe https://www.youtube.com/channel/UCs6KfncB4OV6Vug4o_bzijg
- Go to community tab, scroll to bottom

It looks like cut off due to background color
Possible to add a bit of border and/or shadow to ensure user know the image boundary?
(Optional coz not sure if border/shadow looks good on all themes)

![image](https://github.com/FreeTubeApp/FreeTube/assets/1018543/5f8fa60f-f26c-4722-ba39-c3860d0bfeff)
![image](https://github.com/FreeTubeApp/FreeTube/assets/1018543/629c64d5-1a84-4063-b7ae-0947487771d1)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Small style issue, steps:
> 
>     * Create a new profile (no sub)
> 
>     * Subscribe https://www.youtube.com/channel/UCs6KfncB4OV6Vug4o_bzijg
> 
>     * Go to community tab, scroll to bottom
> 
> 
> It looks like content got cut off (partially hidden) due to background color Possible to add a bit of border and/or shadow to ensure user know the image boundary? (Optional coz not sure if border/shadow looks good on all themes)
> 
> ![image](https://user-images.githubusercontent.com/1018543/266889042-5f8fa60f-f26c-4722-ba39-c3860d0bfeff.png) ![image](https://user-images.githubusercontent.com/1018543/266889439-629c64d5-1a84-4063-b7ae-0947487771d1.png)

@PikachuEXE could u open a feature request for that

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as the orignal issue is fixed and i opened a feature request to show the shared community posts in https://github.com/FreeTubeApp/FreeTube/issues/4153
