### ISSUE TITLE
[Feature Request]: Nvidia RTX Video Super Resolution

### ISSUE THREAD

**Issue by BobbyMcJefferson** [FreeTubeApp/FreeTube#3260]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

https://blogs.nvidia.com/blog/2023/02/28/rtx-video-super-resolution/

Chrome already supports it, would be nice to have it in FreeTube as well.

### Proposed Solution

support for Nvidia RTX Video Super Resolution

### Alternatives Considered

-

### Issue Labels

new feature, visual improvement

**Comment by absidue** [comment]
Should automatically work once we upgrade to Electron 23, however as Electron 23 drops support Windows 7, 8 and 8.1, we want to wait a bit before doing it.

**Comment by absidue** [comment]
@BobbyMcJefferson Can you please download the latest nightly build and see if FreeTube picks up NVIDIA's RTX Video Super Resolution setting?
https://docs.freetubeapp.io/development/nightly-builds
