### ISSUE TITLE
[Feature Request]: "Remove from history" (May known as "mark as unwatched") in the video plaing page

### ISSUE THREAD

**Issue by PeterDaveHello** [FreeTubeApp/FreeTube#3283]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I would like FreeTube to add a feature to remove playback history from the video player page, which is currently only available in the play list.

Sometimes I open a video but don't finish watching it, and I don't want to mark it as watched.

### Proposed Solution

add a button(?) or option on the video player page that allows users to remove playback history from the video player page, mark the video as not played.

### Alternatives Considered

Another possible solution is to add an option on the video player page that allows users to easily toggle the viewing status of a video.

For example, users can click on an icon to mark a video as unwatched or watched. This would be a more intuitive and convenient way for users to manage the viewing status of their videos without spending too much time on settings and choices.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We think if the playlist feature is implemented users can have a "watch later" list. Then this feature is not really needed.
