### ISSUE TITLE
[Bug]: Sort by broken on channel page

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3287]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

https://user-images.githubusercontent.com/73130443/224539155-02e4bee4-bd46-481f-9eda-c1d226e72f30.mp4

Didnt test the playlist tab but im pretty sure it is the same there.

### Expected Behavior

Sort by works correctly.

### Issue Labels

feature stopped working

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/903edc2e6eeae46893839607bf952e120cbe2260

### Operating System Version

Win10 22h2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Victor239** [comment]
Still an issue.

**Comment by absidue** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Is this still an issue?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
No it isnt showing the most popular videos anymore when switching channels but u still see that the filter is on most popular. In addition to that i get an error now


https://github.com/FreeTubeApp/FreeTube/assets/73130443/ca7c2b7e-e87a-47a8-ae48-0fba8fc67b29

**Comment by Fivavoa** [comment]
Also an issue for me as well, sorting by oldest, or most popular doesn't change it at all from newest.
