### ISSUE TITLE
[Bug]: Screen tearing on Linux after fullscreening, possible issue with either Intel or Nvidia

### ISSUE THREAD

**Issue by vannotz** [FreeTubeApp/FreeTube#3292]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [ ] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [x] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I have encountered a screen tearing issue after entering fullscreen, happens with either local or invidious backend, I have two theories of what is happening:
1. It is an issue with my Intel card, the issue is related to OpenGL video output and is encountered when entering fullscreen in mpv, [it is mentioned in the Arch Wiki](https://wiki.archlinux.org/title/Mpv#Fix_jerky_playback_and_tearing) with a fix that works on my machine.
2. Another possible problem is that it is related to my NVIDIA DGPU (GeForce MX110) but I wouldn't know what it is.

### Expected Behavior

no screen tear

### Issue Labels

visual bug

### FreeTube Version

v0.18.0-1

### Operating System Version

Artix Linux 6.2.2-zen1-1-zen

### Installation Method

AUR

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is it similar to https://github.com/FreeTubeApp/FreeTube/issues/3098

**Comment by vannotz** [comment]
> Is it similar to #3098
No, mine causes simple screen tearing (i.e chopped frames) to that persists over the entire system until Xorg is killed, similar to the mpv issue on the Arch Wiki I mentioned. I also get the same

**Comment by ChunkyProgrammer** [comment]
If i had to guess, I'd say that this is likely an issue with your graphics driver.

Maybe this link can help?
https://www.makeuseof.com/fix-screen-tearing-on-linux/

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @vannotz did the url Chunky posted helped u to resolve the issue?
