### ISSUE TITLE
Add youtube-nocookie URL in the share button

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#331]
Some people don't really want to go to the YT page to watch a vid, and they simply want to have full screen embedded video, which can be accessed via the `https://www.youtube-nocookie.com/embed/[vid_ID]` URL. This link also renders faster compared to a regular YT page. Could you add support for this kind of URL under the `Share` button?

**Comment by SigmundurMorkore** [comment]
I'd like to have a go at this.
Thinking maybe it would be nice to add the youtube-nocookie links everywhere, so that people can go directly to youtube-nocookie from their subscriptions/playlists/trending etc?
