### ISSUE TITLE
[Bug]: `TypeError: Cannot read properties of undefined (reading 'length')`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3310]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig
2. Find video that has "Premiere" status instead of "Live"
3. Video and Live chat loads indefinitely 

```
renderer.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at xo (renderer.js:2:447792)
    at i.handleMaster_ (renderer.js:2:474293)
    at renderer.js:2:471235
    at No (renderer.js:2:460246)
    at Object.callback (renderer.js:2:460480)
    at i (renderer.js:2:7768)
    at XMLHttpRequest.r (renderer.js:2:8785)
```

### Expected Behavior

Video and live chat loads

### Issue Labels

API issue

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/dc78ae5ecc980297ba9b27c7a4fc76cf75c8da67

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
okay so this is caused by isLiveContent being false, so we try to treat it like a normal video instead of a live one. looks like isLive is true for anything that is live (live + live premieres) and isLiveContent is only true for videos that are counted as live (live but not live premieres) or were historically live
