### ISSUE TITLE
[Bug]: `TypeError: Cannot read properties of null (reading 'split')`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3311]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to https://www.youtube.com/live
2. Click on a stream that is labeled "Premiere"
3. Subscribe to the channel
4. Refresh subscriptions 
5. See error

```
TypeError: Cannot read properties of null (reading 'split')
    at renderer.js:2:1428473
    at renderer.js:2:1428815
    at Array.map (<anonymous>)
    at a.getChannelVideosLocalScraper (renderer.js:2:1428295)
    at async renderer.js:2:1426644
```

### Expected Behavior

I should be able to see this video in my subscriptions.

### Issue Labels

API issue

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/dc78ae5ecc980297ba9b27c7a4fc76cf75c8da67

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
okay so i'm pretty sure this is because YouTube changed something and broke the is_live, is_upcoming and is_premiere getters in YouTube.js, i'll look into PRing a fix upstream.

**Comment by absidue** [comment]
Will be resolved when we upgrade YouTube.js to 4.1.0

**Comment by absidue** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Is this still an issue for you on the latest nightly?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not an issue anymore.
