### ISSUE TITLE
[Bug]: Load More button on Playlist page doesnt disappear

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3312]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Import [freetube-playlists-2023-03-16.txt](https://github.com/FreeTubeApp/FreeTube/files/10993923/freetube-playlists-2023-03-16.txt)
2. Change file extension to .db
3. Go to playlist page
4. scroll down to see load more button
5. Click on load more button
6. Repeat step 3 and 4 once
7. Now delete all saved videos expect for 12 (yes within the UI)
8. Close FT
9. Open FT
10. Go to Playlist page
11. Scroll down to see Load more button
12. Click on it and see nothing happens

### Expected Behavior

Load more button should not appear.

### Issue Labels

visual bug

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/dc78ae5ecc980297ba9b27c7a4fc76cf75c8da67

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This seems to be fixed now, not sure when it was fixed but following the described steps I no longer see a load more button after restarting FreeTube with 12 favourites.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
can confirm not reproducible anymore, not sure what fixed it but sure ill take it
