### ISSUE TITLE
[Bug]: FreeTube (as flatpak app) does not open/play redirected video

### ISSUE THREAD

**Issue by lisandrocarmona** [FreeTubeApp/FreeTube#3319]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I'm using FreeTube installed as Flatpak and Privacy Redirect Chrome browser extension. I gave URL access rights to the extension.

When I click in a YouTube link, it is redirected to FreeTube, but instead of showing and playing the video, FreeTube is opened in the default tab.

I've tested in two different Linux distros. I also check if there is any permission into Flatseal that could solve this issue, with no luck.

If it matters, the URL is not present in the Clipboard.

### Expected Behavior

When I click in a YouTube link, the video is shown in FreeTube (and start playing as per my configurations).

### Issue Labels

content not loading

### FreeTube Version

v0.18.0 Beta (Flatpak)

### Operating System Version

Arch Linux and openSUSE Tumbleweed

### Installation Method

Flathub

### Primary API used

Local API

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @lisandrocarmona i tried replicating this but without succes. 

1. Installed FT through flathub
2. installed chrome through .rpm file, 
3. installed extension, 
4. enabled 

![Capture](https://user-images.githubusercontent.com/73130443/226213151-2dadfbf4-3e40-4bf8-993d-1bbc2b39d659.PNG)

5. grabbed yt url and it opened properly

Do i need to do something different?

**Comment by lisandrocarmona** [comment]
So, trying in Windows (with FT not as Flatpak, as obvious) the redirection works and the video start playing. I'll check if any of my browser or FT settings are blocking the normal behavior on Linux (I've tried on Arch, openSUSE Tumbleweed, Sparky (Debian based), and NixOS, all of them sharing the same browser user profile folder).

I'll test again and post back. At least, in Windows it's working as it should for me.

**Comment by ChunkyProgrammer** [comment]
@lisandrocarmona do you use QT? https://github.com/FreeTubeApp/FreeTube/issues/373#issuecomment-1116352210

If so, this issue will likely be fixed in the next release

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I'll be closing this as it was solved in https://github.com/FreeTubeApp/FreeTube/pull/3119. If u can't want until next release, u can install [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds).
