### ISSUE TITLE
[Feature Request]: Better performance under Raspberry Pi 4

### ISSUE THREAD

**Issue by sudo-splinter-cell** [FreeTubeApp/FreeTube#3326]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Video playback performance under Raspberry Pi 4 (even when 720p resolution is selected) is quite choppy and laggy. The very same youtube videos can be opened and played back within Chromium with so much better performance under RPI.

### Proposed Solution

Maybe a different backend that utilizes open source Chromium be used for the playback of videos under Freetube. Or maybe this can be offered as an option in the settings.

### Alternatives Considered

A "web" based version of Freetube that can be opened and used within the browsers would probably also increase the quality of playback of videos under RPI and any other system that has similar issues.

### Issue Labels

improvement to existing feature

**Comment by absidue** [comment]
Can you try using the legacy formats? Unlike DASH which has separate audio and video streams, the legacy formats have the audio and video streams combined in a single file and generally work better on lower powered hardware.

FreeTube uses Electron which is built on top of Chromium. It's entirely possible that the Chromium build, that is distributed for Raspberry Pis, comes with Raspberry Pi specific patches, that aren't in upstream Chromium and Electron.

**Comment by sudo-splinter-cell** [comment]
> Can you try using the legacy formats? Unlike DASH which has separate audio and video streams, the legacy formats have the audio and video streams combined in a single file and generally work better on lower powered hardware.
> 
> FreeTube uses Electron which is built on top of Chromium. It's entirely possible that the Chromium build, that is distributed for Raspberry Pis, comes with Raspberry Pi specific patches, that aren't in upstream Chromium and Electron.

What you say about the Chromium build that is distributed for the RPI might be true. It has some patches for better video playback, especially for youtube i assume. I have tried the "legacy" option in Freetube. It doesn't really change much in terms of performance other than making the video resolution a lot worse. But of couse this is a Raspberry Pi with a very limited ARM cpu and i assume Freetube works a lot better with x86 machines.

What i have been trying is to divert the playback to an "external" player under Fretube. VLC has been succesful however, i found out, due to youtube's recent limitations, it is almost impossible to timely buffer youtube videos with VLC. I am currently trying to divert video playback to MPV, which has been unsuccesful even thought it is already installed. I can maybe open up a new issue thread for this separately.
Thanks anyway.
