### ISSUE TITLE
[Bug]: Searching on Invidious API shows wrong results

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3354]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

For some weird reason it is showing us the second page instead of the first one. I have the feeling that it is thinking it is already on the first page after the first search and when i apply the filter it is just +1. Counter must be reset.

1. Search something on Invidious
2. Apply Channels filter
3. Go to FT and search for the same thing
4. Apply Channels filter
5. Notice difference in results
6. Go to the next page of results on the Invidious site
7. See same results as in FT

https://user-images.githubusercontent.com/73130443/227722364-aed8b384-07c5-459d-bd84-7a30c41f1dc8.mp4

### Expected Behavior

Search results must always reflect the first page.

### Issue Labels

content not loading

### FreeTube Version

Latest

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Is this still an issue for you? It might have been solved as part of #3342

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Seems to be fixed!
