### ISSUE TITLE
Weird background video playing

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#338]
Steps to reproduce:
- Add a favorite video
- play the favorite vid via the `Favorites` tab
- scroll down and click the channel icon.

Do the third step when the video hasn't been started yet, and you will be redirected to the channel page and the video will start in the background without any player and a way to stop it. :)

**Comment by RiabikovR** [comment]
Something similar sometimes happens to me when DASH crashes and reverts to legacy player.
I'm not sure if it happens when I switch back, or just sime time after it reverts, but sometimes the previous player randomly restarts and keeps playing in background.

**Comment by PrestonN** [comment]
This should be fixed in the rewrite.
