### ISSUE TITLE
Write After End and a bug

### ISSUE THREAD

**Issue by cyberchief1984** [FreeTubeApp/FreeTube#339]
I have two issues. First, I keep seeing the words "write after end" on some videos. The second problem I have is with subscriptions. Whenever I click on the Subscribe button on a video page of a channel I'm already subscribed to, I would get subscribed twice, and this would cause the channel to fail to load.

**Comment by PrestonN** [comment]
Give the new release a try.  It should include a fix for this.  You can also find more information over at #303
