### ISSUE TITLE
Confusing "copied 0 channels..." in local subscription profiles

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#340]
When you copy some channels between local profiles (for subscriptions), you're are able to copy the same item over and over. Currently it only says that "copied 0 channels..." or you can get less number of channels when you copy some of them and one or two already exist in the destination set. Sometimes this message can be confusing, and a user may not be aware the channel were already copied. Some better message would be appreciated here.

**Comment by PrestonN** [comment]
Wow, you're quick when it comes to downloading a testing.  Not a bad thing.

My thought process for this is that sometimes a user may accidentally copy a channel multiple times to the same profile.  This is more so a visual representation to show that some / all channels didn't get copied over.  I can attempt to make a better message to be sent instead but for now it's working as intended.
