### ISSUE TITLE
[Bug]: Video descriptions missing

### ISSUE THREAD

**Issue by GreaterJoe** [FreeTubeApp/FreeTube#3403]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open any video
2. Scroll down past the title and buttons block
3. Find that the only thing below it is the hyperlink to view comments.

### Expected Behavior

Between the block with the video titles and various buttons, and the block to load comments, there should be a block with the video's description.

### Issue Labels

content not loading, feature stopped working, text/string issue, usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

6.2.8-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Mar 22 21:14:50 UTC 2023 x86_64 GNU/Linux

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

The description often includes information that contextualises the content of the video, as well as helpful links to co-creators, cited documents for statements of facts, etc. A Youtube video is not complete without it.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by megarodent** [comment]
I also have this issue and thought it was just me.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@GreaterJoe could u try [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)

**Comment by GreaterJoe** [comment]
> @GreaterJoe could u try [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds), to check if that resolves it for u

I tried nightly build _v0.18.0-nightly-2846 Beta_ and the issue is fixed there.

**Comment by ulph0** [comment]
> > @GreaterJoe could u try [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds), to check if that resolves it for u
> 
> I tried nightly build _v0.18.0-nightly-2846 Beta_ and the issue is fixed there.

had the same problem, can confirm the fix.
