### ISSUE TITLE
[Feature Request]: 'Open in FreeTube' extension for web browsers when clicking on a YT video.

### ISSUE THREAD

**Issue by princehalfblood** [FreeTubeApp/FreeTube#3404]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

---

### Proposed Solution

I would like a feature, 'Open in FreeTube' extension for web browsers when clicking on a YT video. This would then open the downloaded app and the video.

### Alternatives Considered

---

### Issue Labels

new feature

**Comment by absidue** [comment]
You can use the LibRedirect or PrivacyRedirect extensions to have YouTube links open FreeTube. Links to them are available in the README: https://github.com/FreeTubeApp/FreeTube#browser-extension

**Comment by princehalfblood** [comment]
@absidue LibRedirect works almost perfect but with this i can't go to youtube.com itself, so I can't select the video which I want to open on FreeTube, how do I know what links I want to open on freetube if I can't go to youtube? I hope you understand.
