### ISSUE TITLE
[Bug]: Proxy in nightly build extremely slow

### ISSUE THREAD

**Issue by tytqnxt898** [FreeTubeApp/FreeTube#3405]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

It was discussed in #3092 

Using the latest freetube version 0.18 I use the electron flag --proxy to get the proxy working and it works fine. But in the nightly build the proxy setting was updated to use this flag (if I understood correctly) but the same proxy that I tested back and forth between nightly and the latest version is really slow on the nightly build. It takes 30 seconds to load the first 5 frames of a video on the nightly (100 kbps). While on the latest build 0.18 it get 80k kbps. The worst part is that I even tried using the --proxy flag on the nightly but it's still slow 100kbps.

### Expected Behavior

Input a proxy, proxy works with full speed.

### Issue Labels

data loss, inconsistent behavior, usability issue

### FreeTube Version

 0.18.0-nightly-2844

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.18

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Do you have a proxy that we could use to investigate this issues?

**Comment by tytqnxt898** [comment]
> Do you have a proxy that we could use to investigate this issue?

Sadly I can't. I use mullvad's proxies that can be only used if you are connected to one of their vpn servers. The only reason I use proxies is because without them my connection is throttled down to 3k kpbs and with a proxy I get 80k kbps I don't know why. Without a proxy im still on a vpn and the proxies are from a vpn no idea why it does this. Only happens on freetube, I even tried same vpn server on firefox/chrome and it wasn't throttled, only on freetube it is

**Comment by ChunkyProgrammer** [comment]
Found a free proxy that we could try to use for testing @absidue  (i'm not sure how secure or private it is)

![proxy](https://user-images.githubusercontent.com/78101139/232836953-64363c86-b45f-44ff-ad8e-23c3362bd241.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@tytqnxt898 are you still facing this issue on the latest stable and latest nightly build?
