### ISSUE TITLE
[Bug]: Subtitle button not showing itself

### ISSUE THREAD

**Issue by Xelbayria** [FreeTubeApp/FreeTube#3407]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1) I've confirmed that the videos I am watching in Youtube have the CC button (subtitle). FreeTube do not show the CC. 
    Please see ( 1 ) in Additional Information
2) Some videos have CC shown itself in FreeTube but it's not displaying the subtitles.  
    Please see ( 2 ) in Additional Information

 Here are the closed issues related to here: #3071 and #3095. I haven't found any open issues related. 

### Expected Behavior

Subtitle (CC) to show itself so i can enable it. 

### Issue Labels

feature stopped working

### FreeTube Version

v0.18.0-Beta

### Operating System Version

Windows 10 Pro 21H2

### Installation Method

.zip

### Primary API used

Local API

### Additional Information

( 1 ) https://youtu.be/218DQqAVkoQ
( 2 ) https://youtu.be/owijYeRAlEw

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is already fixed in [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)

**Comment by Xelbayria** [comment]
> This is already fixed in [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)

which commit was this fix included in?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://github.com/FreeTubeApp/FreeTube/pull/3100
