### ISSUE TITLE
Deselect items after copying them in the subscription profile manager

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#342]
When you select some channels in a subscription profile and copy them to another profile, the selection is preserved after the process is done. When you have many channels and want to copy another channels to another set, you have to first remove the selection from the already copied channels, so they wouldn't be copied once more to the new set. This is a little bit inconvenient and not really intuitive.

**Comment by PrestonN** [comment]
The thoughts behind this is that you may want to copy a group of channels over to multiple profiles, so it could be annoying if you had to re-select that same group multiple times.  There is a "Select None" option which will deselect everything at once if that is what you'd prefer.

**Comment by morfikov** [comment]
Oh right, I didn't notice the "select none option". So I think it's good as it is now.
