### ISSUE TITLE
[Bug]: Enabling Sponsor block changes the videos original language

### ISSUE THREAD

**Issue by Tech-e1** [FreeTubeApp/FreeTube#3423]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug
It appears that enabling sponsor block, causes the invidious api settings to go offtrack. Everytime i opened a video invidious failed and reverted to local api. apparently the local api is tied to language(s) that aren't English. I tried adding many different active instances but with no avail.

1. Enable Sponsor block
2. open new video
3.

### Expected Behavior

I would expect that sponsor block recognizes my default language localization as well as the original language of the video itself and maintain that. All the while, blocking and segmenting the parts i don't need to see.

### Issue Labels

API issue

### FreeTube Version

v0.18.0 beta

### Operating System Version

Linux  6.1.21-1-MANJARO 

### Installation Method

AUR

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

unsure

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
Could you provide some screenshots please?

**Comment by Tech-e1** [comment]
I made a mistake. This issue is isolated only to certain popular videos. I tested this primarily on Mr. Beast. Others that i've watched have produced intended results.

**Comment by ChunkyProgrammer** [comment]
> I made a mistake. This issue is isolated only to certain popular videos. I tested this primarily on Mr. Beast. Others that i've watched have produced intended results.

The audio issue is known: https://github.com/FreeTubeApp/FreeTube/issues/2419

We'll need to look more into invidious failing. Thanks for more clarification.

**Comment by Sandyran** [comment]
I don't think it is SpondorBlock that changes the language of Mr Beast's videos. I tried disabling it, and it still gave me the Arabic versions of his videos.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Tech-e1 Sponserblock isnt related to the audio being changed to arabic. Could u maybe make a screenrecording of the Invidious API failing.

The things i would like to see in this order:

- Your API settings 
- Selected Invidious instance 
- Sponsorblock settings
- The Invidious API error

**Comment by staticf0x** [comment]
I also experience this, for example here: https://youtu.be/XFPOylBJCeA

If the SponsorBlock is *disabled*, it's in Spanish, if it's *enabled*, it's in English. But like a month ago with a different video from the same channel it was reversed.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> I also experience this, for example here: https://youtu.be/XFPOylBJCeA
> 
> If the SponsorBlock is _disabled_, it's in Spanish, if it's _enabled_, it's in English. But like a month ago with a different video from the same channel it was reversed.

 @staticf0x this isnt the case in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).
