### ISSUE TITLE
[Bug]: FreeTube still accessing Google's servers even after enabling proxying through Invidious

### ISSUE THREAD

**Issue by 6-AND-9** [FreeTubeApp/FreeTube#3429]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Enable 'Proxy videos through Invidious' option in Player settings
2. Try to open a video
3. Video loading takes ages (sometimes up to half an hour)
4. Check traffic with firewall:
5. FreeTube is trying to access googleusercontent and googlevideo even though I explicitly selected to proxy, and since these are blocked by my router, loading videos takes ages until somehow magically it resolves and loads the video from an Individious instance.

Could you please make 'Proxy videos through Invidious' actually mean 'Proxy videos through Invidious'  and not access Google's servers at all?

Thanks,
- A

### Expected Behavior

'Proxy videos through Invidious' actually means 'Proxy videos through Invidious'  i.e. traffic comes solely from an Invidious instance, and there's no accessing of Google's servers at all.

### Issue Labels

API issue, content not loading, usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux

### Installation Method

Flathub

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

Can't remember, probably v0.15 or so

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
which formats are you using? legacy, audio or DASH?

**Comment by ceeeej1141** [comment]
Same for me. FreeTube doesn't display the subscription thumbnails without allowing yt3.googleusercontent.com in my firewall.

**Comment by ChunkyProgrammer** [comment]
Do you get this issue while using nightly builds? https://docs.freetubeapp.io/development/nightly-builds#downloading-nightly-builds

**Comment by ceeeej1141** [comment]
> Do you get this issue while using nightly builds? https://docs.freetubeapp.io/development/nightly-builds#downloading-nightly-builds

Thanks you, It no longer access yt3.googleusercontent.com in order to display the thumbnails though importing my history doesn't work.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Do you get this issue while using nightly builds? https://docs.freetubeapp.io/development/nightly-builds#downloading-nightly-builds

@6-AND-9 please try this and come back to us

**Comment by mit242** [comment]
I can replicate the issue using the latest nightly build 2892.
Proxy through Invidious selected, no fallback to non-preferred selected, no force local backend for legacy selected,  tried with both dash and legacy as default formats.

**Comment by ChunkyProgrammer** [comment]
> I can replicate the issue using the latest nightly build 2892. Proxy through Invidious selected, no fallback to non-preferred selected, no force local backend for legacy selected, tried with both dash and legacy as default formats.

What are you doing when the requests are made/what domains does it connect to?

**Comment by mit242** [comment]
Oh, I'm using the AppImage btw. This happens when I watch a video from the subscription list. It connects to the invidious instance a few times and then something like this:

> rr5.sn-4g5ednsd.googlevideo.com	x.x.x.x	QUIC	1278	Protected Payload (KP0

**Comment by ChunkyProgrammer** [comment]
Should be fixed by:
https://github.com/FreeTubeApp/FreeTube/pull/3639
