### ISSUE TITLE
A better indication of selected channels in the subscription profile manager needed

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#343]
Currently after selecting a channel in the subscription profile manager, the channel icon gets grayed out with a white-some mark. The gray icon doesn't really contrast well with the slightly more gray tab background. Looking through channels to be sure you marked all the needed ones can be difficult, and at first sight I can't find the ones I marked. I have to look very closely to find them. So I think some better coloring is needed here.

**Comment by dCo3lh0** [comment]
i could add more to this, add some visual information to what profile that channel is previously assigned to, like a round dot to the bottom-right of the round avatars in channel management, or a little oversized circle behind the round image in the color of the profile, highlight selection could be on the color of profile too, after updates it changes to the profile you selected. And a plus to this, could be an option to the profile selection that shows, currently non assigned channels to any profile, which is "all channels" except all the channels that belongs to actual existing profiles

**Comment by PrestonN** [comment]
I think this was a problem with how the theming worked.  This should be fixed in the rewrite.
