### ISSUE TITLE
[Bug]: `TypeError: Failed to fetch`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3446]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I sometimes get this error when just browsing FT and trying to fetch channels/videos/searches. Its very random and cant reproduce it consistently :(

![image](https://user-images.githubusercontent.com/73130443/232822397-d4f7a0fb-f4e5-440d-be4a-cbc53bb681bb.png)

First try recording yay, dont watch the whole vid i was trying to get it again in the vid but didnt succeed.

https://user-images.githubusercontent.com/73130443/232823415-e7533258-daf7-4f45-ac34-e4f0ea872a83.mp4

Ah i noticed that i can force it to throw the error if i switch pages very fast. U see the page shows content but if it would fetch it for the first time it wouldnt show any content and thats why this bug is so annoying. Sometimes i get it 3/4 times back to back so that would mean if i go to trending it will throw error and show me nothing. Then ill go to a channel i get the error and it shows nothing.

https://user-images.githubusercontent.com/73130443/232830298-00807eb7-c0b1-47c4-a0a6-753606d8d206.mp4

### Expected Behavior

No fetching error :)

### Issue Labels

content not loading, usability issue

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/2984df111222e4c849f099e8b0e974f96a998f60

### Operating System Version

win10 22h2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It changed to

```
renderer.js:2 TypeError: Failed to fetch
    at hD.fetch (renderer.js:2:1361467)
    at hD.<anonymous> (renderer.js:2:1271638)
    at Generator.next (<anonymous>)
    at renderer.js:2:871590
    at new Promise (<anonymous>)
    at Iu (renderer.js:2:871335)
    at hD.fetch (renderer.js:2:1269423)
    at VO.<anonymous> (renderer.js:2:1312461)
    at Generator.next (<anonymous>)
    at renderer.js:2:871590
```

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I always get this connection closed error before the failed to fetch error. That might be the real culprit.

![connection_closed](https://github.com/FreeTubeApp/FreeTube/assets/73130443/710c5873-dba1-4724-bd95-22d8e7c8fee4)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is actually great. This was a low priority for our team because i was the only one getting this annoying bug. Hopefully we can address this sooner now that we know that this isn't actually a me problem

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Yeah, actually I had no issues with 0.18.0 originally for some reason (like 3 weeks ago.) I have no idea why it worked for me because if I go back to 0.18.0 now, local API predictably errors out every time.

Just want to clarify a bit. The reason u didn't had this issue in 0.18.0 is because the change that introduced this error wasn't introduced in that version. This only happens in the nightly builds. 

We had a migration of the Local API that took about 4 months to make it more stable so all the issues regarding the Local API ur seeing in v0.18.0 are not related to the ones u see in the nightly builds.

The Local API in v0.18.0 is probably fully broken now because YT changed to much on their end and that caused the old modules to break

**Comment by absidue** [comment]
`TypeError: Failed to fetch` is an error that is produced by the built-in `fetch` function. Not sure what makes YouTube decide to randomly close a connection. With a VPN I got the error occasionally but without a VPN I have never seen it, maybe YouTube doesn't like VPNs?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hmm could be i only use FT with VPN so i cant really comment on not getting this error without VPN

**Comment by kirbyjohnson** [comment]
I was unable to watch any videos or look at any channels while getting this error code. Adding it to my vpn's whitelist fixed it. Apparently when updating this program is gets removed from my VPN's whitelist. Probably has something to do with having to re-run the setup exe file on every update.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Ammako use ctrl + r

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@kirbyjohnson @Ammako are you still running into this error?
