### ISSUE TITLE
[Bug]: Manual loading of Subscription page is not copied across windows

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#3447]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Disable automatically loading the Subscriptions page.
2. Click Load Subscriptions in window 1.
3. Open a new window 2.
4. window 2 wants you to click to load the subscriptions again, while window 1 shows the subscriptions that have already been loaded.

### Expected Behavior

Window 2 should show the subscriptions that were already loaded in window 1.

### Issue Labels

content not loading, inconsistent behavior

### FreeTube Version

v0.18.0.beta.03d3df87

### Operating System Version

Manjaro Linux

### Installation Method

other

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

-

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing, converted to a feature request in #4152 because this isnt a bug
