### ISSUE TITLE
[CI]  make release asset naming consistent

### ISSUE THREAD

**Issue by attila-lendvai** [FreeTubeApp/FreeTube#3454]
### Describe the bug

release asset file name is as follows:

https://github.com/FreeTubeApp/FreeTube/releases/download/v0.18.0-beta/freetube-0.18.0-linux-portable-x64.7z

### Expected Behavior

if the release tag and version name is `0.18.0-beta` then the asset's name should also contain the `-beta` suffix.

alternatively, remove the `-beta` from everywhere.

context: i'm writing a Guix packaging and updater script and this anomaly needs special handling.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.18.0

### Operating System Version

Guix (Linux)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing, converted to a feature request in #4151 because this isnt a bug
