### ISSUE TITLE
[Feature Request]: Show video durations in the subscriptions tab

### ISSUE THREAD

**Issue by sudo-splinter-cell** [FreeTubeApp/FreeTube#3470]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The durations of videos can not be seen in the subscriptions tab. In all the other tabs, durations can ben seen on the lower right corner of each video thumbnail.

### Proposed Solution

This feature can be implemented to the subscriptions tab also.

### Alternatives Considered

There is no alternative really.

### Issue Labels

display more information to user

**Comment by sudo-splinter-cell** [comment]
I guess i have to. Because it says "too many subs, switching to rss" even when i do not select it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
[There isnt really anything we can do about that because its a limitation of RSS](https://docs.freetubeapp.io/usage/subscriptions/#methods-of-generating-your-feed)

**Comment by absidue** [comment]
> YouTube has a limit on how many requests per day an IP address is allowed to make. If you exceed this limit, you will be greeted with a 429 error and will not be allowed to browse using FreeTube any more. This limit can be reached much faster if you have a large amount of subscriptions. As mentioned above, using RSS does not count towards this limit and can be safely used even when you have a large amount of subscriptions.

> As a safety precaution, FreeTube will automatically force the RSS method whenever you have more than 125 subscriptions in a profile. This will happen regardless of your settings and there is no way to disable this. Creating a new profile with less than 125 subscriptions will bypass this however.
