### ISSUE TITLE
[Bug]: windowsx64.exe Malware detected with virustotal

### ISSUE THREAD

**Issue by ElSamiru** [FreeTubeApp/FreeTube#3472]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to https://freetubeapp.io/
2. Copy the link address of Windows.exe (x64) 
3. Go to https://www.virustotal.com/gui/home/url
4. Paste the URL and click on the search button
5. Should be detected by Lumu service (Malware)
6. I test others the links and they are all green only the Windows.exe x64 is detected

### Expected Behavior

Should not contains any Malware like the others links 

### Issue Labels

causes crash

### FreeTube Version

v.0.18.0 Beta

### Operating System Version

Windows

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
https://docs.freetubeapp.io/faq/#my-virus-protection-gave-a-warning-when-i-tried-to-run-freetube-is-freetube-a-malicious-application
