### ISSUE TITLE
A safety margin around the video progress bar

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#348]
When you hover a mouse pointer over the video progress bar, some miniature will show up. As you move the mouse left/right, the video frame from the current position will be presented. But when you move the mouse just a little bit up or down, the frame disappears, and you have to adjust the pointer to be exact on the progress bar again. In the case of YT page, it gives some safety margin around the progress bar, so it's a way easier to look through the miniatures. Is there a way to implement such margins in FreeTube?

**Comment by PrestonN** [comment]
This has been fixed in the rewrite.
