### ISSUE TITLE
[Feature Request]: Always open youtube links in FreeTube

### ISSUE THREAD

**Issue by PrincessMiki** [FreeTubeApp/FreeTube#3491]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

A previous post said to install freetube via .deb and that will fix it.

### Proposed Solution

I installed freetube from .deb and see no 'freetube protocol' option and they continue to open in firefox

### Alternatives Considered

(I dont really know how github forum differs from discord threads)

### Issue Labels

ease of use improvement

**Comment by absidue** [comment]
Have you installed one of the browser extensions that redirects YouTube links to FreeTube as instructed in the README? https://github.com/FreeTubeApp/FreeTube#browser-extension

**Comment by PrincessMiki** [comment]
> Have you installed one of the browser extensions that redirects YouTube links to FreeTube as instructed in the README? https://github.com/FreeTubeApp/FreeTube#browser-extension

yeah the extension works. 

Is this incorrect? 'install freetube via .deb and that will fix it.'

**Comment by absidue** [comment]
FreeTube has no idea what is going on in your web browser, you need the extension to redirect the URLs to the `freetube://` URL scheme to open FreeTube.

So this sounds like this is resolved then after you installed the extension?

**Comment by PrincessMiki** [comment]
> FreeTube has no idea what is going on in your web browser, you need the extension to redirect the YouTube URLs to the `freetube://` URL scheme to open FreeTube.
> 
> So this sounds like this is resolved then after you installed the extension?

Yes that's right
