### ISSUE TITLE
[Bug]: Search `TypeError: Cannot read properties of undefined (reading 'length')`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3494]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. type in `ziggo sport napoli florentina 2020` in the search bar
2. see the search suggestion and navigate to it with arrow keys
3. press enter
4. search results are loaded now
5. click on the end of the search query
6. press enter

https://user-images.githubusercontent.com/73130443/236677879-73997cce-a8ef-4ac8-917e-68c305b61f4c.mp4

### Expected Behavior

no error

### Issue Labels

API issue

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/2345752308c7ae35b7acbd45297b57599a14a0c3

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
Is this still an issue?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
cant reproduce this anymore
