### ISSUE TITLE
[Bug]: Channel Community `Invidious API error Error: This channel hasn't posted yet`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3499]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Set Invidious as primary API
2. Navigate to https://www.youtube.com/channel/UCUKPG1-r4WFyxpyhIuCs86Q
3. See error

```
renderer.js:2 Invidious API error https://invidious.nerdvpn.de/api/v1/channels/UCUKPG1-r4WFyxpyhIuCs86Q/community? Error: This channel hasn't posted yet
    at renderer.js:2:904112
```

https://user-images.githubusercontent.com/73130443/236683002-bd5e17bf-c11e-4288-a77d-c10ce2529f59.mp4

### Expected Behavior

No error.

### Issue Labels

API issue

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/2345752308c7ae35b7acbd45297b57599a14a0c3

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Opened a bug report on the Invidious GitHub repository for this, as Invidious doesn't return errors when other channel tabs are empty e.g. the playlists one.
https://github.com/iv-org/invidious/issues/3814

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@absidue im not seeing this particular error anymore but i did notice a silent one in the console

![Capture](https://github.com/FreeTubeApp/FreeTube/assets/73130443/b9139eda-8cc4-496e-8bb2-d8c4dde8e8b8)

**Comment by ChunkyProgrammer** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc I think we should be able to close this now, can you verify?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I think this one is in a weird spot because the video on that channel i linked was planned in the future back when i created this issue. Now that video is in the posted state.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as i didnt see it in a long time
