### ISSUE TITLE
[Bug]: `Remove All Subscriptions / Profiles` in Privacy Settings should be removed when `Hide Unsubscribe button` is enabled

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3503]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Basically the same request as #3501 

1. Enable `Hide unsubscribe button` in the Parental Control Settings
2. Scroll up and Open the Privacy Settings tab
3. See that the `Remove All Subscriptions / Profiles` is available

This button does the same as unsubscribing to a channel but in a way more destructive way.

https://user-images.githubusercontent.com/73130443/236694416-ed631977-41e7-4ca9-a5f8-d446375f38f9.mp4

### Expected Behavior

Hide `Remove All Subscriptions / Profiles` in Privacy Settings if `Hide unsubscribe button` in the Parental Control Settings is enabled

### Issue Labels

inconsistent behavior

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/2345752308c7ae35b7acbd45297b57599a14a0c3

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Rikthepixel** [comment]
Sounds like a fair request/bug. Since it is in bug reports board, I thought I'd implement it. 

Solved it in pull request: #3693

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://github.com/FreeTubeApp/FreeTube/pull/3693#issuecomment-1609020704
