### ISSUE TITLE
Media play button activates video in the background

### ISSUE THREAD

**Issue by Mech0z** [FreeTubeApp/FreeTube#351]
If I start to play a video, goes back to "Subscriptions" the playback stops. 

If I then use the media keys to start media it will start to play the video again, but I cant see where, just hear the audio. This also happens if I minimized freetube, so it takes precedence over for example spotify while minimized.

On Windows 10, version 0.7.0 beta

**Comment by morfikov** [comment]
Similar (or the same) to #338

**Comment by PrestonN** [comment]
This has been fixed in the rewrite.
