### ISSUE TITLE
"Topic" channels are broken

### ISSUE THREAD

**Issue by TheFrenchGhosty** [FreeTubeApp/FreeTube#352]
The "Topic" channels (usually music artist channels generated by YouTube) are broken and don't display any content : 
![freetube](https://user-images.githubusercontent.com/47571719/63403577-61ebca00-c3cf-11e9-871f-0192c7765c19.png)

The same channel on invidious : 
![invidious](https://user-images.githubusercontent.com/47571719/63403598-79c34e00-c3cf-11e9-9aa1-ca63ffae6276.png)

**Comment by PrestonN** [comment]
It appears that topic channels only provides playlists and do not have any videos.  If you click on the playlists tab in FreeTube, it will display these playlists just fine.  I seems that I will simply have to hide the videos tab when a topic channel is being viewed as well as default to the playlist view.

**Comment by TheFrenchGhosty** [comment]
The problem is that if I click on "Playlists" no playlist are displayed, and if I click on load more I get "There are no more playlists for this channel." 

See this gif : 
![freetube](https://user-images.githubusercontent.com/47571719/63449469-c3dc1c00-c42f-11e9-9366-741a3bc754e1.gif)

**Comment by TheFrenchGhosty** [comment]
This was a invidious bug, https://github.com/omarroth/invidious/commit/059f50dad477daab63246314198ec7e274493ece fixed it.
