### ISSUE TITLE
[Feature Request]: Add skip forward/backward buttons

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#3520]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

In some scenarios, such as the usage of FreeTube on a touchscreen, it can be dificult to skip to the right point with the usual method.

### Proposed Solution

Implement this: https://github.com/videojs/video.js/pull/8147

It will be available, once https://github.com/FreeTubeApp/FreeTube/pull/3482 is merged.

### Alternatives Considered

-

### Issue Labels

ease of use improvement, new optional setting

**Comment by ChunkyProgrammer** [comment]
On touch devices, You should be able to double tap the right side of the video to skip forward and double tap the left side to skip backwards

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
IMO this is a wont implement, tapping is already available and more configurable than this.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> IMO this is a wont implement, tapping is already available to skip backward/forward and more configurable than this.

Because of the reason stated earlier i go ahead and close this

**Comment by HattDroid** [comment]
Reopened as double tapping left and right sides fo the videos do not allow to skip backward and forward the video anymore.
I'm using the latest beta.
