### ISSUE TITLE
[Bug]: Weblate issue

### ISSUE THREAD

**Issue by rddim** [FreeTubeApp/FreeTube#3522]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When I try do translate the new strings on Weblate I see an error message at top of the page.

https://hosted.weblate.org/projects/free-tube/translations/#alerts

### Expected Behavior

I have expect to have no errors

### Issue Labels

text/string issue

### FreeTube Version

v0.18.0-nightly-2736

### Operating System Version

Win 7

### Installation Method

PortableApps

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18.0-nightly-2736

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Related https://github.com/FreeTubeApp/FreeTube/issues/673#issuecomment-1527615575

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@rddim it should be fixed now, could u verify this for us?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Issue isnt gone yet

```
static/locales/as.yaml	'could not find expected \':\' in "<unicode string>", line 54, column 1:\n Change Format:\n ^ (line: 54)'
static/locales/hi.yaml	'could not find expected \':\' in "<unicode string>", line 210, column 1:\n Change Format:\n ^ (line: 210)'
static/locales/ku.yaml	'could not find expected \':\' in "<unicode string>", line 200, column 1:\n Comments:\n ^ (line: 200)'
static/locales/or.yaml	'could not find expected \':\' in "<unicode string>", line 144, column 1:\n Toggle Theatre Mode: \'\'\n ^ (line: 144)'
static/locales/sat.yaml	'could not find expected \':\' in "<unicode string>", line 67, column 1:\n Change Format:\n ^ (line: 67)'
```

**Comment by absidue** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc it was gone but weblate added them back (see commit history).

**Comment by ChunkyProgrammer** [comment]
Weblate seems to be working again
