### ISSUE TITLE
[Feature Request]:  Validation For Snap Maintenance

### ISSUE THREAD

**Issue by capecrusader-121** [FreeTubeApp/FreeTube#3525]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

@ChunkyProgrammer  Can i please get an upstream nod or approval for maintaining snap packages, i wish to publish snap packages under the name freetube (currently freetube-snap) , and to get the freetube name, the snapcraft community is asking for upstream approval or acknowledgement officially or unofficially, please comment or reply back by acknowledging that snap packages by me has received approval for unofficial way of distributing freetube, your coordination and favour will be sincerely appreciated.
I have to link them with this post as a proof.
Do it ASAP I f possible. 

### Proposed Solution

Acknowledgement for snap packages to publish snap packages under the freetube name

### Alternatives Considered

Nothing ??

### Issue Labels

support for external software

**Comment by absidue** [comment]
This "silly" process, as you call it, is actually very sensible, they want to give us (the FreeTube project) a chance to use the `freetube` name to distribute an official package, before they let you use it.
They are essentially asking us, whether we will ever create an official snap package and if the answer is yes, they will reserve the `freetube` name for us.

**Comment by CapeCrusader321** [comment]
@absidue  okay so do this project wish to maintain the official snap builds ??. and should i detest myself to not use the name ??

**Comment by CapeCrusader321** [comment]
@absidue  @ChunkyProgrammer  Can i get this conformation and approval for maintaining the snap package on behalf of the project ??, in future even if the snap version is made official i will voluntarily maintain it on behalf of the project or i will transfer it to project devs if needed, adding collaborators is also an option.

**Comment by CapeCrusader321** [comment]
@PrestonN  Any Updates on This ??

**Comment by sudo-splinter-cell** [comment]
Hello. I am on a RPI4 and i use Freetube daily almost. I am using the nightly version (deb version) and as you all know, this app is getting almost daily updates. I am in search of an easier and shorter way to update the app. Currently what i do is to download the newest deb. Remove the previous version (sudo apt autoremove freetube) and install the newest deb with a right click command. Is there an easier way to update freetube on a raspberry pi? Is it possible to add a third party repository for the updates so when i do "sudo apt update", it actually includes it in the upgradable packages?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Hello. I am on a RPI4 and i use Freetube daily almost. I am using the nightly version (deb version) and as you all know, this app is getting almost daily updates. I am in search of an easier and shorter way to update the app. Currently what i do is to download the newest deb. Remove the previous version (sudo apt autoremove freetube) and install the newest deb with a right click command. Is there an easier way to update freetube on a raspberry pi? Is it possible to add a third party repository for the updates so when i do "sudo apt update", it actually includes it in the upgradable packages?

@sudo-splinter-cell i think its better to ask it over at https://github.com/FreeTubeApp/FreeTube/discussions

**Comment by CapeCrusader321** [comment]
@sudo-splinter-cell  I can package an arm version of freetube as snap as well if you and other users of arm wish, then you can easily upgrade and uninstall.

**Comment by capecrusader-121** [comment]
@PrestonN  Any updates on this ?

**Comment by capecrusader-121** [comment]
@absidue  @ChunkyProgrammer Cant this be granted for now i mean i will initiate a transfer of the snap to the project in the future if needed, there has been no reply since months, i dont understand why the snap cant use the original name, let it remain unofficial if the projects dont wish to endorse snaps but at-least using the official name shouldnt be a problem i mean literally all other unofficial packages are using the name freetube why is the project against/ignoring the snap using the official name ? permitting it will only promote the project with snap having thousands of downloads already.
To emphasize why i am pushing for official name is that. 
1) using duplicate names is redundant
2) using unofficial names lead to app icon display issues.
3) users dont feel much better sense of trust in using duplicate names.
4) snap reviewers have pushed me multiple times to prefer using official names instead of duplicate names. 

Behaving like am seeking some intellectual property of the project is funny.
Everything has limit either simply say no or yes ?

**Comment by ChunkyProgrammer** [comment]
Hi @capecrusader-121 . You can use FreeTube as the name for your package 🙂

**Comment by capecrusader-121** [comment]
@ChunkyProgrammer  Thanks.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@capecrusader-121 can this be closed?

**Comment by capecrusader-121** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc  I will myself close this once its finalized at the snap end, the name transfer is still under progress.

**Comment by capecrusader-121** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc  @ChunkyProgrammer  Closing this, this has been resolved although the snaps will take some time to appear in stores when it does i will create a new PR to update snap listing.
