### ISSUE TITLE
Why does it install to AppData\Local\Programs\ instead of Local Disc C\Program Files ?!

### ISSUE THREAD

**Issue by Xulinaah** [FreeTubeApp/FreeTube#353]
Why does it install to **Users\xxxx\AppData\Local\Programs\** ??? Is this by design? I would infinitely prefer for it to go to **Local Disc C\Program Files\** like any normal software does! Is it my computer mishandling the install or is this the way it was designed? Amazed not to see this brought up yet. If it is intended to install in this way, I would like to know why. It's always problematic when I try to update to the latest version. Still can't get it to work! I always look forward to the updates but dread trying to get them to work!

**Comment by TheFrenchGhosty** [comment]
Every Electron app behave like that on Windows by default, it's a "feature".

See : 
https://github.com/electron-userland/electron-builder/issues/718
https://github.com/electron-userland/electron-builder/issues/693

**Comment by Xulinaah** [comment]
Well, it's not working for me. When I click the desktop icon, I get a popup message saying **Problem with Shortcut. The item 'FreeTube.exe' that this shortcut refers to has been changed or moved. so the shortcut will no longer work properly. Do you want to delete this shortcut?**  How can I access the AppData folder which is no longer visible where it used to be. So far, not sure if I like Electron. Anyway, has anyone else ever encountered this situation ?

**Comment by gkeegan** [comment]
You can type `%appdata%` into the file explorer, then go up a level and see the local folder. It should be in there. Maybe make a new shortcut from the .exe?

**Comment by Xulinaah** [comment]
Thanks for your suggestions. Still no luck. How can I get a version that will install to Program Files? Also for future versions of FT, updates should be internal like when updating a browser. When I update a browser, I don't have to go to their websites to click a download button. It tells me **updates will take effect when browser is restarted. Would you like to restart now?** That's what I want to see in the next version. All the other feature requests on here are great, but none should be top priority until FT can be updated the same way as browsers! Let that be goal number one, please.

**Comment by PrestonN** [comment]
Looking through this, it sounds like your real request is that you'd like automated updates.  It's something that is planned but I don't have an ETA on when I will get to it.  As a reminder this functionality has to work for all operating systems so it won't be as simple as making it work under Windows.

Looking at the issues linked, it looks like I can allow the user to determine where it is installed.  I will set this up.  If this isn't the desired functionality then it doesn't look like I'll be able to fulfill your request.

May I ask what is so problematic with updating FreeTube?  I have yet to have any issues during an update process on Windows.

**Comment by PrestonN** [comment]
Closing as this likely won't be an issue with the rewrite.
