### ISSUE TITLE
[Bug]: Click Spam load more button on community tab shows duplicate posts

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3531]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

First noticed in https://github.com/FreeTubeApp/FreeTube/pull/3465 and happens on both API's. 

1. Go to any channel's community page
2. Scroll down until u see the load more button
3. Spam the load more button
4. See duplicate posts appear

Used a fast clicker tool becuz im too slow to properly reproduce it for a clip :(

https://github.com/FreeTubeApp/FreeTube/assets/73130443/8e2ea4f4-2b87-4c89-94d5-fe59f7ef361e

### Expected Behavior

Dont show duplicate posts

### Issue Labels

inconsistent behavior, visual bug

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/a4d45b5fa8a8a1726808c9eebe307643f8dde9c9

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
We should hide the button while it's fetching more stuff and replace it with a loading icon, similar to how it's already implemented on the playlist page.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/3541
