### ISSUE TITLE
[Feature Request]: Disable Thumbnail Images

### ISSUE THREAD

**Issue by joshuabengal** [FreeTubeApp/FreeTube#3535]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Add a Thumbnail Preference, "None" that when selected will eliminate video thumbnails altogether. NewPipe has this feature 

### Proposed Solution

Thumbnails will just just show a static image (like a "Play" icon or something) or just an outline of a thumbnail with no content or picture. 

### Alternatives Considered

Browsers have add ons to do this

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2814
