### ISSUE TITLE
[Bug]: Live chat `Uncaught TypeError: Cannot read properties of undefined (reading 'url')`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3544]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to https://www.youtube.com/watch?v=36YnV9STBqc
2. See that chat doesnt load and error in console

```
Uncaught TypeError: Cannot read properties of undefined (reading 'url')
    at a.parseLiveChatComment (renderer.js:2:1638272)
    at renderer.js:2:1637125
    at UL.i (renderer.js:2:1057291)
    at UL.emit (renderer.js:2:1057093)
    at UL.<anonymous> (renderer.js:2:1257554)
    at Generator.next (<anonymous>)
    at a (renderer.js:2:871535)
```

https://github.com/FreeTubeApp/FreeTube/assets/73130443/fda89ce9-982c-4ced-a7ca-0afda84d6243

### Expected Behavior

Live chat should load and there shouldnt be an error in the console

### Issue Labels

content not loading, feature stopped working, inconsistent behavior

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/a4d45b5fa8a8a1726808c9eebe307643f8dde9c9

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Rekit0** [comment]
i tried a temporary fix, i will send a PR
![image](https://github.com/FreeTubeApp/FreeTube/assets/50448746/02238084-9d94-44bb-b46e-75bb65762352)
