### ISSUE TITLE
Server installation / docker image

### ISSUE THREAD

**Issue by Albirew** [FreeTubeApp/FreeTube#355]
Can you provide an advanced server installation documentation or a docker image so people can install it on a server the same way as an invidious instance?
May be related to #74 if used with an addon or an userscript that redirect youtube URLs to chosen instance.

**Comment by PrestonN** [comment]
it's theoretically possible to set up a server version of FreeTube, however there are parts of it that would need to be rewritten to replace any existing Electron functionality that FreeTube currently uses.  Depending on what's wanted, this may also have to include some sort of account functionality for that instance, which would need to be written.  Right now I want to focus on the desktop experience.  This will be something I can look at after a stable release.

**Comment by PrestonN** [comment]
Since FreeTube doesn't have a web version (yet), a docker image doesn't really make sense right now.  If we focus more on getting the web version fully working, then we can look at this again.

**Comment by Albirew** [comment]
well, docker image was more "if something more than a LAMP server was needed" case.
If you're closing this issue, does this mean there's another issue for the web version?

**Comment by PrestonN** [comment]
There was, however it's likely closed right now as the web version will be shelved for the time being.  It technically works however it will have to rely on the Invidious API to obtain data.  Since Invidious might not get too many new features / patches, I'm going to keep it closed since it probably won't be worked on for a while.  If development in Invidious picks back up, we can re-open these issues and discuss these again.

**Comment by MichelDiz** [comment]
It would be nice to have a web version cuz we could have it in a Proxmox server or HomeLab thing to offer in our local LAN env to all family and stuff. Desktop is appealing but a server which I can control storage, make automatic backups in ZFS ou Proxmox Backup Server and so many options it would be nice. Also using VMs or LXC we could have coding and decoding in a controllable env. We can setup downloads or anything else without needing to let the laptop/pc wake the whole night.

Also we could do parental control. Blocking youtube in the router and DNS. But cherrypicking channels for the kids. They could access the server via web browser in a tablet or something.

Anyway. The possibilities are endless.

Cheers!
