### ISSUE TITLE
[Bug]: Subscribe button and function missing

### ISSUE THREAD

**Issue by CaptainMorgan12** [FreeTubeApp/FreeTube#3585]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads)
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Environment: 0.18.beta flatpak install, ubuntu 23.04, wayland, trashcan macpro 2013.

1. select channel like "Starship Gazer"
2. https://yt3.googleusercontent.com/df03SI5EEWWj_Mb7z9ptWKRJcUcU0WBa6Z2OET9fi2cK5GxsW7K_UPVPadrTbAKwX07ztTJj=s176-c-k-c0x00ffffff-no-rj
3. observe there is no "Subscribe Button"

### Expected Behavior

Subscribe button exists.

### Issue Labels

usability issue

### FreeTube Version

See above

### Operating System Version

See Above

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

See Above

### Additional Information

See Above

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Please check that the "Hide Unsubscribe Button" parental control setting is disabled.

**Comment by CaptainMorgan12** [comment]
In fact it was disabled, maybe i was confused with the wording because shouldn't it say "Hide Subscribe Button"? Once unchecked subscribe finally shows!
