### ISSUE TITLE
[Bug]: very old videos being shown before new videos on the subscription page

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#3587]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads)
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open FreeTube on the Subscription page or refresh the Subscription page
2. The first listed videos are from subscribed channels except months to years old.  Usually old videos from 1 to ~~2~~3 different channels.

So far I have seen a max of ~~26~~57 of these old videos before it starts listing the expected new videos.    Upcoming Videos always appear before the old videos.

Refreshing the subscriptions tab multiple times can result in the old videos now showing but it's inconsistent if it works or how many times you have to refresh

### Expected Behavior

Open FreeTube or Refresh the subscription tab and only see new videos

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.18.0-nightly-2949 Beta 

### Operating System Version

Debian 11

### Installation Method

.deb

### Primary API used

Local API

### Additional Information

First noticed a couple of days after installing v0.18.0-nightly-2949 Beta,  still present in v0.18.0-nightly-2949 Beta 

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We also noticed this and it looks like youtube might be experimenting with returning the published dates in a different format (compare the ones at the top 8d/2w/2mo vs the ones further down which use full words)

**Comment by grrrrr** [comment]
> compare the ones at the top 8d/2w/2mo vs the ones further down which use full words

eagle eyed :)

**Comment by bacteriostat** [comment]
Can we have a release soon? Looks like youtube went live with the change and now videos of one youtuber are listed 100% of the time. Falling back to Invidious for now.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@bacteriostat install the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds if u dont want to wait for release

**Comment by maplepy** [comment]
every time i reload the page, i get another youtuber. is that the same issue or something else?

**Comment by maplepy** [comment]
i dont think i updated yet, let me check (i'm on the AUR so i dont think i have it?)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
AUR are not maintained by us so they don't have nightly builds. Please read the info in the provided link properly

**Comment by maplepy** [comment]
yes i know, that's why i asked

**Comment by aleksejrs** [comment]
Just in case, YouTube's RSS can list old videos as new for no reason.
