### ISSUE TITLE
Please stop destructive and closed actions by developer

### ISSUE THREAD

**Issue by maboroshin** [FreeTubeApp/FreeTube#3590]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The GitHub Community Guidelines include welcoming and open-minded and respectful. I'm reporting it to GitHub as a violation of the guidelines. Please stop destructive and closed actions.

----
https://github.com/FreeTubeApp/FreeTube/issues/3589

I have created an issue with this content. The lead developer has received a big donation, yet the official release has been stalled for over 6 months.

@efb4f5ff-1298-471a-8973-3d47447115dc replies (I will call him efb4):

> Allot of devs already responded to your Weblate issues and we still stand by the previously made arguments. ... but continuously spamming closed issues

efb4 has completely misunderstood. Then efb4 labeled my statement as spam. There is no word Weblate in my text. My references include donations and stalled official releases. This doesn't exist in previous issues. But efb4 has closed the issue.

### Proposed Solution

Developers will be welcoming, open-minded and respectful.

### Alternatives Considered

Deprive the authority to be used destructively and closedly.

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> As lead developer, PrestonN is inactive for about 6 months in the first half of 2023. Since he has released the latest version, now the latest version 0.1.8 has a release date of November 2022.

PrestonN's activity doesnt impact anything. We have a team and their is allot going on behind the scenes before we can do a new release but u would already know this if u had taken a look at https://github.com/FreeTubeApp/FreeTube/commits/development

> On the other hand, PrestonN is getting excessive donations. Open https://liberapay.com/FreeTube/ for showing donations. A graph of donations is shown at the bottom. Currently, PrestonN gets $45 per week in donations. In 2022, it exceeded $40 per week. This is about 5 times the $8.50 he states as a necessary expense. In other words, he has already received the necessary expenses for 5 years.

>> In an effort to be transparent, I want to make it very clear that donations are not necessary in any way with FreeTube. ... have no need to make money off of the project. ... Progress speed will not increase or decrease because of donations. Only donate if you really want to.
 
> PrestonN stated it this way. We need to ask ourselves. Would you need to donate to an inactive developer? Or would you like to make a gratuitous contribution on behalf of a developer who receives donations for inactivity?

`Donation: money or goods that are given to help a person or organization, or the act of giving them`
retrieved from https://dictionary.cambridge.org/dictionary/english/donation
 
Donation is about giving and you're not giving it to PrestonN ur giving it to the team. The project is healthy and alive like i said before. Therefore its logical to get donations. 

> Proposed Solution
> 
>     PrestonN needs to release at least the latest version. This would be the minimum activity expected by the donor.
>     And, Use excess donations to improve the user experience. For example, you can charge for other paid services.

U are not in authority to make any demands for when a new version should be released. Improving FT everyday that is what the minimum activity expected by the donor is. The donor can always install the nightly build to have the bleeding edge experience. 

> Alternatives Considered
> 
>     Suspension of donations for 5 years. Due to excessive donations, donations are currently not required.
> 

A donation is a donation u cant decide for the team what we do with it after our expenses are paid. 

Now that i have addressed this nonsense like u wanted. FINAL WARNING: I will repeat myself one more time. Stop spamming our issue tracker with your behavior or u get banned.
