### ISSUE TITLE
[Bug]: Video page `TypeError: Cannot read properties of undefined (reading 'id')`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3596]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads)
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to https://youtu.be/9oZjE42cJuM
2. U will get the following error and video will not play

```
TypeError: Cannot read properties of undefined (reading 'id')
    at renderer.js:2:1673849
    at Array.forEach (<anonymous>)
    at a.getVideoInformationLocal (renderer.js:2:1673804)
```

### Expected Behavior

No error and vid should play.

### Issue Labels

content not loading

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/7d8a4c8cd7f31d6e94fde92e8bebc9dedd5c990c

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Looks like YouTube may have fixed this on their end, as the extra unlabled audio tracks no longer show up in the response.

@efb4f5ff-1298-471a-8973-3d47447115dc Can you please check if this issue still shows up on your side?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Nope error is gone
