### ISSUE TITLE
refreshing subs shows "unable to load channel: XYZ"

### ISSUE THREAD

**Issue by MKs2w7cBxTRP3e2ivnYBddxc** [FreeTubeApp/FreeTube#360]
On 0.7.0, I switched between 3 of the official invidious instances but keep getting this error even after restarting freetube. Running with --no-sandbox on a whonix virtual machine. I'd give debug information but I couldn't find how to display it.

**Comment by morfikov** [comment]
I think this was a temporary issue. I had it for an hour or so, but now it backed to normal.

**Comment by PrestonN** [comment]
Is it the same channels that are giving the error?  Or is it a different channel each time?  If it's the same channel, try going to the channel's page and see if it loads.  It's possible that you have channels that have been terminated by YouTube.  If the channel hasn't been terminated, please let me know which channel it is and I can look into it.

If it's different channels each time, then something happened on the Invidious end where it couldn't grab the channel.  These errors are typically one-off problems and will solve themselves in the next refresh.

**Comment by MKs2w7cBxTRP3e2ivnYBddxc** [comment]
It was the Domain of Science channel which hasn't been terminated, but I unsubscribed to it and now the same message pops up for Enrico Deiana. Trending/popular show the read loading circle but never load. The issue has persisted for 3 days now on version 0.7.0.

**Comment by MKs2w7cBxTRP3e2ivnYBddxc** [comment]
> If it's different channels each time, then something happened on the Invidious end where it couldn't grab the channel. These errors are typically one-off problems and will solve themselves in the next refresh.

It's persisted for 11 days at this point. Let me know if you get a chance to check out those channels I listed--none of them were terminated, and the issue just occurs on a new channel if I unsub from the previous problem channel.

I'll download another copy of the linux tar and see if that has the issue. If I want to transfer my subs/favorites, what folder do I need to copy? Thanks.
