### ISSUE TITLE
[Feature Request]: Open videos in MPC-BE, MPC-HC, or PotPlayer

### ISSUE THREAD

**Issue by shockwavebd** [FreeTubeApp/FreeTube#3614]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I prefer using MPC-BE, MPC-HC, or PotPlayer with FreeTube.

### Proposed Solution

To enable these players, you may need to add them appropriately in the 'external-player-map.json' file. Here's an example of how to add MPC-BE: 
` {
        "name": "MPC-BE",
        "nameTranslationKey": "Settings.External Player Settings.Players.MPC-BE.Name",
        "value": "mpc-be",
        "cmdArguments": {
            "defaultExecutable": "mpc-be64",
            "defaultCustomArguments": null,
            "supportsYtdlProtocol": false,
            "videoUrl": "",
            "playlistUrl": "",
            "startOffset": null,
            "playbackRate": null,
            "playlistIndex": null,
            "playlistReverse": null,
            "playlistShuffle": null,
            "playlistLoop": null
        }
    },` 
    By adding the above code snippet to the file, you should be able to launch videos in MPC-BE or PotPlayer successfully. However, configuring arguments for MPC-HC or MPC-BE is a bit tricky with just this modification. For example, the `startOffset` command switch for MPC-BE/MPC-HC is `/startpos`, which expects the value in the format hh:mm:ss. This format is not what FreeTube passes, as far as I know. Additionally, setting `/audiorenderer 0` as an external player argument breaks playback for some reason. This argument is required because changing the playback speed alters the voice pitch without MPC-AR. Although setting MPC-AR as the default audio renderer might solve this issue, it's not an ideal solution.
    The `--rate=1` argument is the reason why simply changing the path for VLC media player to MPC-BE/PotPlayer doesn't work. Having a nice playback rate at startup can be useful, so you may want to consider this. 
    MPC-BE and PotPlayer support native YouTube parsing and playback, while MPC-HC requires yt-dl/yt-dlp. However, MPC-BE can also use yt-dl/yt-dlp.

### Alternatives Considered

Attempted to play videos in MPC-BE and PotPlayer by configuring a custom path after setting VLC as the external player, since both players are capable of playing YouTube videos. However, it didn't work as the `--rate=1` option is not supported by either player. MPC-BE throws an error, while PotPlayer adds the video to the playlist but fails to play it.

### Issue Labels

ease of use improvement, improvement to existing feature, support for external software

### Additional Information

This issue seems to be related to problems discussed in issues https://github.com/FreeTubeApp/FreeTube/issues/418 and https://github.com/FreeTubeApp/FreeTube/issues/2005. The latter issue is quite similar but hasn't made any progress and instead suggested opening a feature request.

I want to clarify that I'm a newbie and don't have a strong understanding of programming. I included all this information simply to complete this form. Please feel free to disregard any of it if you find it irrelevant. I tried to solve the problem myself by reading the aforementioned issues, but ended up making a mess of it.

Thank you.

**Comment by absidue** [comment]
> Additionally, setting /audiorenderer 0 as an external player argument breaks playback for some reason.

As FreeTube passes arguments directly to the program, instead of going through a shell, you need to tell it that `/audiorenderer` and `0` are two separate ones. You can do that by separating them with semicolons `;`. That means that you'll want to enter them like this: `/audiorenderer;0`.

**Comment by shockwavebd** [comment]
> > Additionally, setting /audiorenderer 0 as an external player argument breaks playback for some reason.
> 
> As FreeTube passes arguments directly to the program, instead of going through a shell, you need to tell it that `/audiorenderer` and `0` are two separate ones. You can do that by separating them with semicolons `;`. That means that you'll want to enter them like this: `/audiorenderer;0`.

Thanks, `/audiorenderer;0` works.

**Comment by Xelbayria** [comment]
Okay. I am a bit lost. How do you add the JSON file to freetube to use external player like potplayer or MPC-HC (with yt-dlp). That part is not clear?

**Comment by shockwavebd** [comment]
> Okay. I am a bit lost. How do you add the JSON file to freetube to use external player like potplayer or MPC-HC (with yt-dlp). That part is not clear?

Didn't add the JSON file to Freetube. After going through related issues and searching for a solution, I forked Freetube and edited the source JSON to allow the use of external players like Potplayer or MPC-HC (with yt-dlp). However, that was very basic implementation (code was included in the original post).

**Comment by Xelbayria** [comment]
> Didn't add the JSON file to Freetube. After going through related issues and searching for a solution, I forked Freetube and edited the source JSON to allow the use of external players like Potplayer or MPC-HC (with yt-dlp). However, that was very basic implementation (code was included in the original post).

Ah, I understand now. Thanks for the explanation.
