### ISSUE TITLE
[Bug]: Invidious API Error 

### ISSUE THREAD

**Issue by CaptainMorgan12** [FreeTubeApp/FreeTube#3618]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

The error does not seems to affect FreeTube function negatively. The error only shows when selecting refresh of subscriptions, or when selecting subscriptions tab initially after launching app. Once it refreshes no more errors are shown and videos play properly.

![image](https://github.com/FreeTubeApp/FreeTube/assets/80182265/ed4835c6-c245-4248-8eb4-1bc691c67d24)

### Expected Behavior

No Error. Also when selecting to copy error no text or debug information is copied.

### Issue Labels

API issue

### FreeTube Version

0.18beta

### Operating System Version

Ubuntu 23.04

### Installation Method

Flathub

### Primary API used

Invidious API

### Additional Information

Log based on Ctrl + Shift + I console:

[-1685641322032.log](https://github.com/FreeTubeApp/FreeTube/files/11628067/-1685641322032.log)

Console Image:
![image](https://github.com/FreeTubeApp/FreeTube/assets/80182265/0a56e04a-4fe3-444e-9617-df73dba877d4)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi @CaptainMorgan12 can u take a screenshot of the invidious api settings and what instance u are using

**Comment by CaptainMorgan12** [comment]
> hi @CaptainMorgan12 can u take a screenshot of the invidious api settings and what instance u are using

![image](https://github.com/FreeTubeApp/FreeTube/assets/80182265/787ef774-0f91-4593-b365-54cb46d39804)

**Comment by CaptainMorgan12** [comment]
> Also, If you use `Ctrl + Shift + i` you can open the developer console. It might have more information of the error there slightly_smiling_face

Thanks for the tip!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah i also get the undefined error when using that instance and when i refresh my subscriptions 



![Capture](https://github.com/FreeTubeApp/FreeTube/assets/73130443/399ebaf2-4f9d-4d78-8d3f-a469e9b5840a)

**Comment by CaptainMorgan12** [comment]
Getting more errors including the above when using another instance:

https://api.invidious.io

[-1685644848088.log](https://github.com/FreeTubeApp/FreeTube/files/11628420/-1685644848088.log)

**Comment by CaptainMorgan12** [comment]
> Looking at https://stats.uptimerobot.com/89VnzSKAn/786957161 and discovered that the instance has some issues. FT cannot do anything about this as the instance maintainers need to fix this.
> 
> I would suggest using another instance while they fix their issues.
> 
> Closing as this isnt an issue on our end

Any suggestion of an instance that is more reliable?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://inv.riverside.rocks seems to work fine
