### ISSUE TITLE
[Feature Request] Use a randomly changed username/password when connecting to Tor

### ISSUE THREAD

**Issue by aleksejrs** [FreeTubeApp/FreeTube#3626]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

#1169 was closed with the assumption that changing the circuit from the client is complicated. However, according to `man torsocks`, it is done by using a different username/password pair.
When I specify username/password for the SOCKS5 proxy manually, it fails to connect.

### Proposed Solution

A checkbox to use a random username/password pair.

### Alternatives Considered

Support username/password for the SOCKS5 proxy. Even without randomization, that will help isolate FreeTube's connections from those of other software.

### Issue Labels

improvement to existing feature, new feature, new optional setting, support for external software

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Svallinn whats your opinion on this?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Retrieved from internal discussion

> torsocks's integration with the tor daemon's SOCKS5 Authentication capability (in this case specifically, the username/password method), which basically dictates any SOCKS5 connection made by the program uses this method of authentication
> 
> it has no direct effect on switching the circuits, although using a different user/pass pair would definitely use a different one
> 
> but you can't simply solve it by "using a different username/password pair", torsocks reads the pair from its config file/env vars once and you can't tell it to use something else in the same runtime

> the only 2 solutions I've come up for this
> 
> 1 - send SIGHUP to the tor daemon, this reloads the configuration and has the side-effect of forming different circuits
> 
> 2 - send a command SIGNAL NEWNYM to the tor daemon's control port, which according to control-spec.txt of the spec
> 
> > NEWNYM -- Switch to clean circuits, so new application requests
> > don't share any circuits with old ones. Also clears
> > the client-side DNS cache. (Tor MAY rate-limit its
> > response to this signal.)

> solution 1 is, no good
> Windows doesn't implement these types of signals

> solution 2 is fine, except for the fact that we don't know where the control port is (if there is one, considering the user has to explicitly place the option in the torrc config file and set up a password for it, which adds to the problems -> how are we gonna know the password?)

> it could require a lot of work, but it's not impossible
> there's a few ways of addressing it with solution 2

> technically speaking, we could simply have an option to add a control port to the settings
if nothing is on the port, just fail silently
otherwise, a mechanism to automatically spin up a new circuit depending on the response that comes from YouTube is implementable

> there's a few problems that come to mind immediately, namely our current parallelization of channel calls in the subscriptions feed
these calls would have to be much more sequential in order to not make every single Tor exit node (connecting to YouTube) explode

After this discussion we came to the conclusion that this isn't feasible, therefore I'm closing this issue.

**Comment by aleksejrs** [comment]
>> torsocks's integration with the tor daemon's SOCKS5 Authentication capability (in this case specifically, the username/password method), which basically dictates any SOCKS5 connection made by the program uses this method of authentication

Does that mean it does more to Tor than just connect to its proxy with username/password?

>> it has no direct effect on switching the circuits, although using a different user/pass pair would definitely use a different one

What does that mean? Why the contradiction?

>> but you can't simply solve it by "using a different username/password pair", torsocks reads the pair from its config file/env vars once 

>   -i, --isolate
>  Automatic tor isolation. Set the username and password for the SOCKS5 authentication method to a PID/current time based value automatically.
>   Username and Password MUST NOT be set.

>> and you can't tell it to use something else in the same runtime

The same runtime of the tor daemon? What is torsocks doing at all, then? Why then

>> although using a different user/pass pair would definitely use a different one

?

**Comment by Svallinn** [comment]
> What does that mean? Why the contradiction?

It's not a contradiction, I stated it has no **direct** effect on it and that, if it were possible, it probably would give out a different circuit indirectly
However, when I said "runtime", I meant the torsocks/freetube runtime, not the tor daemon's runtime
We have no means of communicating to torsocks that we want a different user/pass pair while the program is running, making getting new circuits in that fashion impossible.

**Comment by aleksejrs** [comment]
What does FreeTube has to do with torsocks? Why can't it just reconnect with a different user/pass?

**Comment by Svallinn** [comment]
1. No, it doesn't, you're the one who mentioned `torsocks`, so I simply integrated it into the main topic of the conversation: the capability of switching to new circuits at runtime

2. And what exactly do you think that would accomplish?
All that would do is isolate the application's circuits from any other circuits used by other applications.
The actual issue is related to the inability to switch to a new circuit when the current circuit can't get a proper response from YouTube due to rate limiting or some other similar issue, which has nothing to do with SOCKS5 Authentication.
Granted (and I have not tested this), somehow passing a different user/pass pair from the application would probably give out a new circuit, but it's impossible to do that from our end for several reasons:

- `torsocks` is what injects the username/password pair into the SOCKS connection from its config file / env vars and there's no way to switch those credentials during runtime
- If you simply use the `tor` daemon without `torsocks`, then you'd have to add the credentials to the URL itself:
`socks5://username:password@127.0.0.1:9050`
But these credentials can't be provided to proxies due to Chromium "limitations" (it's not really a limitation since it would a security hazard -> https://bugs.chromium.org/p/chromium/issues/detail?id=615947)

3. Restart what? The proxy? The application?
If you mean the proxy, that's ridiculous, the application has no direct control over the proxy, that would only be possible if the proxy exposes a control port (which it doesn't by default) and the application would somehow have to know where it is
If you mean the application, that's even more ridiculous, is your suggestion to restart the application every time the circuit can't get a normal response from YouTube? And even if the application restarted, the circuit wouldn't change since the `tor` daemon is the one responsible for the circuits, not the application.

**Comment by aleksejrs** [comment]
> 1. No, it doesn't, you're the one who mentioned `torsocks`, so I simply integrated it into the main topic of the conversation: the capability of switching to new circuits at runtime

I didn't know about Chromium's limitation, so it seemed strange without that context that you kept mentioning `torsocks`.

> `torsocks` is what injects the username/password pair into the SOCKS connection from its config file / env vars and there's no way to switch those credentials during runtime

It uses "a PID/current time based value automatically" if you specify `--isolate`, which are not the credentials from its config file or env vars.

> The actual issue is related to the inability to switch to a new circuit when the current circuit can't get a proper response from YouTube due to rate limiting or some other similar issue

I filed this issue because I wanted FreeTube isolated from other applications.
There is another one: sometimes, only one of the YouTube domains is inaccessible, like the one with avatars, and then there is no real need to proxify everything else. It may not even matter much if it works. Maybe I even want to proxify only Invidious and not Google.

> * If you simply use the `tor` daemon without `torsocks`, then you'd have to add the credentials to the URL itself:

So, it's just completely impossible to make the platform connect to a SOCKS proxy with credentials? But I guess Chromium itself can do it by storing them somewhere? But then FreeTube can't make it use different ones?

> Restart what? The proxy? The application?

The connection or `torsocks`.

**Comment by Svallinn** [comment]
> It uses "a PID/current time based value automatically" if you specify --isolate, which are not the credentials from its config file or env vars.

You're right, those don't come from the config file or env vars, but they're still credentials, it's simply a PID/timestamp based username generated at runtime and a hardcoded password.
From the `torsocks` codebase
```
	/* PID based isolation requested.
	 *   Username: 'torsocks-' PID ':' TIME
	 *   Password: '0'
	 */
```

> I filed this issue because I wanted FreeTube isolated from other applications.

What?
You only mentioned isolation in the `Alternatives Considered`, not in the main description of the issue.
On top of that, you referenced https://github.com/FreeTubeApp/FreeTube/issues/1169, which concerns rate-limiting and circuit switching, not application isolation.
Put those two together and anyone would assume isolation was an afterthought and not the main topic of the issue, so I don't understand how you can even state that.

> There is another one: sometimes, only one of the YouTube domains is inaccessible, like the one with avatars, and then there is no real need to proxify everything else. It may not even matter much if it works. Maybe I even want to proxify only Invidious and not Google.

Even assuming such fine-grained control over the proxy were possible from our side, it'd take enormous effort to implement and it would be something almost nobody would care about.
The costs don't justify the gains.

> So, it's just completely impossible to make the platform connect to a SOCKS proxy with credentials? But I guess Chromium itself can do it by storing them somewhere? But then FreeTube can't make it use different ones?

I don't know how much more clear I can make this: **Chromium does not allow this**, period.
https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/proxy.md#proxy-server-schemes
> No proxy authentication methods are supported for SOCKSv4.
...
No authentication methods are supported for SOCKSv5 in Chrome (although some do exist for the protocol).

> The connection or torsocks.

I'm repeating myself again, there's no way to directly interact with `torsocks` (in case it's being used).
And it's not like the connection to the proxy (`tor` daemon) is continuous, the very concept of "restart the connection" is non existent. It's similar to HTTP, you make a request and something is on the other end, it works or if there's nothing on the other end, it won't.

Please don't make me repeat myself anymore than I already have.

**Comment by aleksejrs** [comment]
> You only mentioned isolation in the `Alternatives Considered`, not in the main description of the issue.

I guess I should have used the word "still". It is not an alternative, it is a benefit that is present even if the credentials are not changed.

> https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/proxy.md#proxy-server-schemes

Now, *this* is clear. Too bad about Chromium.

> I'm repeating myself again, there's no way to directly interact with `torsocks` (in case it's being used).

I guess you mean running FreeTube with `torsocks freetube`. I had assumed you meant something I have no idea about, which would still look like a setting in FreeTube to the user. I can use `torsocks` myself, and I know it cannot be controlled. `man torsocks` was just the source for the claim that you can change the circuit, which contradicted what was stated in #1169.

I have no further questions.
