### ISSUE TITLE
[Bug]: Crash on flatpak + debian 12 (x11)

### ISSUE THREAD

**Issue by LaBaude32** [FreeTubeApp/FreeTube#3638]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open freetube
2. It's Crash 

(the first time I was able to import my subscriptions in db format)

### Expected Behavior

Just working  😂

### Issue Labels

causes crash, inconsistent behavior, visual bug

### FreeTube Version

0.18.0 Beta

### Operating System Version

Debian 12 (x11)

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by LaBaude32** [comment]
Hi, the deb package version of the night build works well, as the v0.18.0 Beta deb package

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah thanks for the info! I would recommend opening up an issue over at https://github.com/flathub/io.freetubeapp.FreeTube so flathub also will be in the loop about this

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I'm going to close this issue because there is an open issue in the flathub repo and needs to be addressed over there.
