### ISSUE TITLE
[Feature Request]: When not able to get a channel’s videos list through the local API, fallback to the RSS feed

### ISSUE THREAD

**Issue by hollownights** [FreeTubeApp/FreeTube#3641]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Any time YouTube makes some change to the channel's videos page/tab, FreeTube can be affected by not being able to retrieve a list of videos. This problem also occurs if there is some restriction to the user's IP address.

### Proposed Solution

When not able to get a channel’s videos list through the local API for any reason whatsoever, fallback to the RSS feed. The RSS feed is limited to the last 10 videos, but that is 10 videos better than nothing.

### Alternatives Considered

Considering that FreeTube (and FreeTube-like softwares/services) doesn't uses the official API, there isn't any, really. Only the RSS feeds can be expected to keep the same structure, despite the limitations imposed by YouTube. 

### Issue Labels

display more information to user, ease of use improvement, improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @hollownights on what page do you want the RSS fallback to be applied to?

**Comment by hollownights** [comment]
Hi, @efb4f5ff-1298-471a-8973-3d47447115dc! To a channel's videos page/tab.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Implementing this on the channel page would be a mess, as the RSS feeds contain videos, shorts and live, with no way of differentiating them, so we couldn't split them up properly into their individual channel tabs

**Comment by aleksejrs** [comment]
> videos, shorts and live, with no way of differentiating them, so we couldn't split them up properly into their individual channel tabs.
I hate the distinction between shorts and videos, because I have to check two places to see if there are new videos on a channel.

**Comment by hollownights** [comment]
> Implementing this on the channel page would be a mess, as the RSS feeds contain videos, shorts and live, with no way of differentiating them, so we couldn't split them up properly into their individual channel tabs.
> 
> So for that reason i unfortunately have to close the issue.

"Implementing this on the channel page" [...] "as the RSS feeds contain videos, shorts and live" [...]

@efb4f5ff-1298-471a-8973-3d47447115dc  So... It has exactly what a channel has?

You clearly completely missed the point. This issue here isn't about having things tiddly divided into tabs, but rather making sure that even if YouTube nukes the channel's page and FreeTube can't make head and tails of it anymore, FreeTube still keeps working, even if with only a limited amount of content (that content that is precisely the content of a channel). The other reason for this feature is to make sure that any restriction to user's requests don't get on the way of content retrieval, **just like what already happens on the main subscriptions page that automatically falls back to RSS feeds** when it can't get (or shouldn't try to get) content through the local API, **despite the fact that there is also no separation between different types of content when it does this.** Do you think FreeTube should stop using RSS feeds for the subscriptions page, @efb4f5ff-1298-471a-8973-3d47447115dc?
