### ISSUE TITLE
[Bug]: IV: Channel url in comment section isnt being parsed correctly

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3642]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to https://youtu.be/LHRw3sDQH1w
2. Load comment section
3. See pinned comment has url in it but it didnt parse correctly

![ft](https://github.com/FreeTubeApp/FreeTube/assets/73130443/517733ad-362a-43a4-9fbc-d3f1280c6077)
![yt](https://github.com/FreeTubeApp/FreeTube/assets/73130443/50cb43ee-10b3-48ac-9a1b-3dc1122c9314)

### Expected Behavior

Channel url should be parsed correctly

### Issue Labels

inconsistent behavior, text/string issue, usability issue

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/5295934a579359900d242d2cf4516f4b0d06deeb

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Invidious API

### Additional Information

In the YT pic u also see a custom emoji. Do we filter these out or does Invidious not support these kind of emoji's?

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by lamemakes** [comment]
Are there any extra settings you're using that could've caused this? I couldn't recreate it on version [5295934](https://github.com/FreeTubeApp/FreeTube/commit/5295934a579359900d242d2cf4516f4b0d06deeb), running on fedora. My result can be seen here: https://imgur.com/a/StnJXJZ, which even includes the custom emoji. Cheers!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah thanks for testing this. I made a mistake in my description because i used the Invidious API instead of Local

**Comment by lamemakes** [comment]
Sweet! It's showing now, I'll probably take a stab at fixing if there's no opposition there from anyone

**Comment by lamemakes** [comment]
Alright so this appears to be an upstream Invidious issue. The Invidious URI being hit here is `https://y.com.sb/api/v1/comments/LHRw3sDQH1w?continuation=&sort_by=top` and doing a GET on that will get you this `contentHtml` JSON return:
```
"contentHtml": "Niece and nephew, check out nephew Nigel podcast clip about getting punched here ➡️ <a href=\"/watch?v=Wh3OjzDvj9M\">https://youtu.be/Wh3OjzDvj9M</a><br><br>Big thank you to nephew Ryan for helping Uncle Roger out with some research. Check out his channel Way Of Ramen: <a href=\"/channel/UCuM3xKQ_D0RIMMSUh9AYxNA\">/channel/UCuM3xKQ_D0RIMMSUh9AYxNA</a><br><br>Would you eat Mr Chilli Jam&#39;s ramen? <img alt=\"shocked\" src=\"/ggpht/Z8KtdMcjPsmlPW62Ys3Ik4fQKyQvbMsUcyWHmhuXUMkhgEeK63EI_y1-xLAApV2Zj2XQCm9mJQ=w24-h24-c-k-nd\" title=\"shocked\" width=\"24\" height=\"24\" class=\"channel-emoji\" />",
```

which leads me to believe they're (accidentally?) stripping `https://www.youtube.com` out, while keeping `https://youtu.be`. 

The custom image aspect of that is also weird as the working local API turns up: 
`https://yt3.ggpht.com/Z8KtdMcjPsmlPW62Ys3Ik4fQKyQvbMsUcyWHmhuXUMkhgEeK63EI_y1-xLAApV2Zj2XQCm9mJQ=w48-h48-c-k-nd`
but invidious seems to be grabbing something of a different format with:
`/ggpht/Z8KtdMcjPsmlPW62Ys3Ik4fQKyQvbMsUcyWHmhuXUMkhgEeK63EI_y1-xLAApV2Zj2XQCm9mJQ=w24-h24-c-k-nd\`

As a temp fix I could work on some form of regex that searches for commonly messed up YouTube URLs and attempts to properly patches them. That might come out to be more guess work though.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I'll assign u to it!

IIRC the local API had this exact issue. 

Issue: https://github.com/FreeTubeApp/FreeTube/issues/3497

Fix:

Maybe u can take a look at it to enhance your code

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is fixed in https://github.com/iv-org/invidious/pull/3911 and tested on -> https://invidious.protokolla.fi

Thanks @lamemakes !
