### ISSUE TITLE
[Feature Request]: do not skip private (unavailable) videos when numbering items in a playlist

### ISSUE THREAD

**Issue by aleksejrs** [FreeTubeApp/FreeTube#3660]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When there are unavailable videos, YouTube playlists have two states (if you are logged in without age restrictions):
1. Hide videos that are not available in your region or are private. The videos are numbered as if the hidden videos did not exist.
2. Show everything. Every video has a proper number, which is different.

If I understand correctly, FreeTube should be showing videos that are not available in your region, but it is not showing videos that are private. Numbers are as if the private videos did not exist.

`yt-dlp --playlist-items` acts as if all videos were on the list, so FreeTube's numbers are not compatible with it.

### Proposed Solution

Do not skip private videos when numbering list items.

### Alternatives Considered

None, unless there is any use for the skipping.

### Issue Labels

improvement to existing feature, support for external software

**Comment by absidue** [comment]
Keep in mind that FreeTube always interacts with YouTube logged out, so you can't compare it to being logged into YouTube.

Just had a look, YouTube's numbering on the website is based on the videos visible in the current view:
1. Normal (hide unavailable): Numbering is based on the available videos
2. Show unavailable (activated with the 3 dots menu): Numbering is based on all videos in the playlist
3. Videos only: Numbering based on visible videos/the videos in the response
4. Shorts only: Numbering based on visible videos/the videos in the response

Conclusion: FreeTube's numbering is the same as YouTube's.

**Comment by aleksejrs** [comment]
yt-dlp uses #2, even if it cannot download unavailable videos.
yt-dlp uses #1 if you specify `--compat-options no-youtube-unavailable-videos`.

Some videos that are unavailable can still be downloaded with a VPN or by logging in. "Show unavailable" is the view with the most stable numbering.

**Comment by absidue** [comment]
So this is actually a much bigger feature request, instead of just different numbering you want us to change the way we extract playlists, telling YouTube to return the useless hidden stuff (could only do it for the local API, as we only have that amount of control there, highly doubt Invidious would want a breaking change like this as it would mean that everyone using the Invidious API would have to adapt their stuff), which will also require a bunch of changes to the watch page, including rethinking and rewriting the way things like shuffling etc work so you don't end up on a broken watch page.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing this as it isn't worth it to change this much for content we cant even play and displaying it just for the sake of matching with the total videos in playlist number
