### ISSUE TITLE
[Bug]: Mild flickering effect present on screen when in full-screen (wayland)

### ISSUE THREAD

**Issue by bravemenrun** [FreeTubeApp/FreeTube#3664]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When playing videos in full-screen a mild flickering effect is present on screen. It is very noticeable on dark and/or static images but is always present. The flickering is very distracting, especially with videos that display static or dark images. The bug appears in the latest stable and nightly release of FreeTube. So far I have tried the Flatpak, AppImage, and AUR build of FreeTube linked [here](https://freetubeapp.io/#download).

### Expected Behavior

I would expect that the video plays without this flickering effect.

### Issue Labels

visual bug

### FreeTube Version

v0.18.0 Beta

### Operating System Version

EndeavourOS Linux x86_64

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

I am using EndeavourOS with the KDE desktop environment. I am using Wayland as well. I am not sure if this issue is present in X11.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @bravemenrun this could be an issue with the settings of your graphics card.

Try https://github.com/FreeTubeApp/FreeTube/issues/2235#issuecomment-1133918031 if u have a nvidea card.

**Comment by bravemenrun** [comment]
I considered the possibility, however I am using an AMD card with the open source amdgpu driver.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Are u running the latest drivers?

**Comment by bravemenrun** [comment]
Yes, my system is fully up to date with the latest drivers installed.

**Comment by bravemenrun** [comment]
Upon further testing the issue is only present on Wayland. FreeTube functions as it should on X11.

**Comment by absidue** [comment]
Are you adding any extra flags to force enable hardware acceleration? If yes, those are likely the problem.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
sounds like electron doesn't like variable refresh rate stuff in wayland. Closing as this is out of our control and u solved the issue yourself.

**Comment by aAsm321** [comment]
I can confirm that disabling variable refresh rate in adrelanine works. However, if you want to keep using variable refresh rate for other apps, follow these steps.
1. Open AMD software: adrenaline editon
2. Add freetube as a game
![image](https://github.com/FreeTubeApp/FreeTube/assets/143520149/0373081c-b0a1-49c5-914f-73775d21fc93)
3. disable AMD FreeSync
![image](https://github.com/FreeTubeApp/FreeTube/assets/143520149/42f3b442-10f2-4bf4-aa63-8570170bb1e0)
