### ISSUE TITLE
[Bug]: Oppening without a window

### ISSUE THREAD

**Issue by i5bii977** [FreeTubeApp/FreeTube#3666]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When opening FreeTube, it opens an empty window. I already uninstalled and reinstalled it, and did it again with a previous version, with no success. It used to work two days ago.

![ReporteFreeTube](https://github.com/FreeTubeApp/FreeTube/assets/136620595/9597a36d-ba17-4741-92ad-127d2a07591a)

System: 

![SystemProperties](https://github.com/FreeTubeApp/FreeTube/assets/136620595/d4fea9e9-59f4-4da5-a929-a604f170141b)

### Expected Behavior

I would expect the FreeTube window to open with all the features.

### Issue Labels

visual bug

### FreeTube Version

v0.18.0 x64, V-0.17.1 x64

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18.0 used to work

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @i5bii977 do you by any chance use 2 screens?

**Comment by i5bii977** [comment]
The nightly build did work! And no, I do not have two monitors.
Thanks!
