### ISSUE TITLE
[Bug]: IV URL in comment section redirect to wrong page

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3669]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to https://youtu.be/4OjoZZVyHgc
2. Load comments
3. See url in pinned comments cut off and if u click on it redirects u to the wrong page.

It is also cut off on the IV side but they do redirect to the correct page.

With Invidious API
![Capture1](https://github.com/iv-org/invidious/assets/73130443/5dc43b08-9545-4e35-a588-295dd6d32a24)

Compared to our Local API
![Capture](https://github.com/iv-org/invidious/assets/73130443/f2c5192a-f278-47ef-902e-925247054d6b)

### Expected Behavior

Redirect the user to the correct page if they click on the url.

### Issue Labels

inconsistent behavior, text/string issue, usability issue

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/5295934a579359900d242d2cf4516f4b0d06deeb

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Invidious API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by lamemakes** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc I can snag this one - looks like the issue is with the [autolinker](https://github.com/FreeTubeApp/FreeTube/blob/development/src/renderer/helpers/api/invidious.js#L141) putting the links in the wrong order. 

What's the purpose of the autolinker here? Would we be better off writing our own link parser?

**Comment by lamemakes** [comment]
> > @efb4f5ff-1298-471a-8973-3d47447115dc I can snag this one - looks like the issue is with the [autolinker](https://github.com/FreeTubeApp/FreeTube/blob/development/src/renderer/helpers/api/invidious.js#L141) putting the links in the wrong order.
> > What's the purpose of the autolinker here? Would we be better off writing our own link parser?
> 
> I think the issue has more to do with our html stripping logic. We basically remove the a tags and keep the text. (
> 
> https://github.com/FreeTubeApp/FreeTube/blob/0a471f8a172214925724acb367696086d3afe5e1/src/renderer/helpers/utils.js#L409
> )

Great catch! You were dead on, made my life easy! Cheers!
