### ISSUE TITLE
PPA or HTML versions?

### ISSUE THREAD

**Issue by username2468** [FreeTubeApp/FreeTube#367]
Is there a way to install this through a PPA (so it automatically updates) or use it as a bunch of HTML files so no installation is needed (for security concerns, especially considering this software is in beta and the fact that it is flagging up as proprietary).

Also, the package flags itself as "proprietary" and not open source, meaning that ether the package or the website has a wrong description.

**Comment by morfikov** [comment]
What do you mean by "flags itself as proprietary"?

**Comment by username2468** [comment]
I get a message like this before downloading it (this screenshot is not from this app, but from Google to demonstrate what it is) https://user-images.githubusercontent.com/2313/37870844-41bb433a-2f94-11e8-9b1b-04bc5cec660c.png

**Comment by PrestonN** [comment]
There is a duplicate issue to the second statement requested over at #355.

A PPA is planned, but I don't have an ETA on when that will be.  I am aware that the package is stated as proprietary but that is not the case.  Each official build is created from the master branch with no modifications.  If you have any security concerns with the builds that I distribute you are welcome to make a build yourself over at the [Contributing](https://github.com/FreeTubeApp/FreeTube/blob/development/CONTRIBUTING.md#setting-up-your-environment) section.

**Comment by PrestonN** [comment]
Closing in favor of #354
