### ISSUE TITLE
[Bug]: Fetch More Results on a channel page doesnt fetch anything

### ISSUE THREAD

**Issue by byAshx** [FreeTubeApp/FreeTube#3670]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Went to a users YouTube channel, scrolled down to look at older videos and I clicked 'Fetch More Results'.
The button wont load any older content at all. It just highlights the button text.

### Expected Behavior

Expect to pull older videos from channel when using Fetch More Results.

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

v0.18.0

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Growebis** [comment]
Have you tried the latest nightly build? You can get the latest nightly build by going the Action tab on GitHub, then go to Builds and click on the latest build and then download the FreeTube Windows version. If this solves your issue please close it.

**Comment by Marcellus97** [comment]
I also experienced this bug on the latest release, but can confirm the latest nightly build works for loading more videos. (for me i chose https://github.com/FreeTubeApp/FreeTube/actions/runs/5284314213)

**Comment by byAshx** [comment]
> I also experienced this bug on the latest release, but can confirm the latest nightly build works for loading more videos. (for me i chose https://github.com/FreeTubeApp/FreeTube/actions/runs/5284314213)

This worked thank you!
