### ISSUE TITLE
[Bug]: Opening many windows (like 35-50) hangs FreeTube and causes issues for Xfce

### ISSUE THREAD

**Issue by aleksejrs** [FreeTubeApp/FreeTube#3671]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Open 35-50 different videos in new windows. I do it to look at the videos and save links to the good ones (since FreeTube only supports one playlist, loading the window takes time, and I don't want to forget where I stopped).

FreeTube slows down, then the windows become unavailable. Xfce panel freezes when going to the workspace, and is showing the previous state of the panel (for the previous active workspace), until I leave the workspace. The window buttons for the workspace with FreeTube only show for a moment after leaving the workspace. Hung FreeTube does not use much (if at all) CPU or RAM.

Videos do not need to be played, speed of opening probably does not matter.

Some recent errors (the last one are repeated many times)

`[3140855:0616/121004.405146:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RG_88, share_between_threads: 0, gmb_type: shared_memory`

That one appears for every video?

`[3140855:0100/000000.293320:ERROR:vaapi_wrapper.cc(2471)] vaExportSurfaceHandle failed, VA error: invalid VASurfaceID`
That one is suspicious.

`[3140855:0100/000000.293723:ERROR:vaapi_video_decoder.cc(1206)] failed Initialize()ing the frame pool`
That one is also okay?

```
TypeError: Cannot destructure property 'value' of 'object null' as it is null.
    at /opt/FreeTube/resources/app.asar/dist/main.js:2:242658
    at async O (/opt/FreeTube/resources/app.asar/dist/main.js:2:242614)
```
?

`[3140778:0616/121006.592550:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")`
That one happens frequently.

```
[3140878:0616/121008.204679:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -101
[3140878:0616/121008.208697:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -101
[3140878:0616/121008.240965:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -101
```
This is probably related to many videos being opened.

### Expected Behavior

It works okay. Firefox with that many tabs works okay, although it unloads tabs when there is not enough RAM (I have plenty of RAM). Tabs do not usually use too much CPU.

### Issue Labels

causes crash

### FreeTube Version

v0.18.0-nightly-3030 Beta, 3004 Beta

### Operating System Version

Debian bookworm

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [x] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
I'm going to close this as this is an extreme unsupported use case.

FreeTube was never designed to be able to handle that many windows open at a time. The only reason doing that many things in Firefox even works, is because people have spent years optimising it and coming up with solutions to handle extreme cases like this (e.g. stopping all processing for background tabs, moving things from RAM to disk storage, etc etc). FreeTube is maintained by a few volunteers in our free time, so I'm not surprised that overloading it causes it to break.

As your goal seems to be mass processing/downloading videos which 
FreeTube is not designed for, you may want to look into more appropriate tools for your use case like shell scripts with yt-dlp.
