### ISSUE TITLE
[Security Issue:] Trying to download malware via Invidious when using FreeTube

### ISSUE THREAD

**Issue by FreedomIsAChoice** [FreeTubeApp/FreeTube#3713]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

On June 26, 2023, a repeated threat alert from my Bitdefender Internet security software occurred.

The first message was already about 9 months ago, which I unfortunately had not documented, but after it happened repeatedly the day before yesterday, I documented it and would like to point out this security issue herewith.

Right after starting FreeTube and loading the subscriptions, the Bitdefender security message appeared

"Suspicious activity was detected on the https://invidious.slipfox.xyz page. We recommend that you leave the site immediately. Accessed by: FreeTube.exe"

### Expected Behavior

I expect that when using FreeTube, you do not run the risk of getting your system infected with malware.

### Issue Labels

accessibility issue

### FreeTube Version

v.0.18.0 Beta

### Operating System Version

Win 10 Pro

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

I am ready to provide you with the screenshots of Bitdefender's alert messages via email.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @FreedomIsAChoice could u test out other instances to check if u get the same notification?

**Comment by ChunkyProgrammer** [comment]
We send a request for every channel you're subscribed to when the subscription page is loaded/refreshed and you're antivirus probably didn't like that (if you have 200 subscriptions, for example, we'd send 200 requests to the invidious instance)

**Comment by FreedomIsAChoice** [comment]
> Hi @FreedomIsAChoice could u test out other instances to check if u get the same notification?

Hello,
one day after this incident FreeTube works well again (with other instances?).

> We send a request for every channel you're subscribed to when the subscription page is loaded/refreshed and you're antivirus probably didn't like that (if you have 200 subscriptions, for example, we'd send 200 requests to the invidious instance)

No, ChunkyProgrammer... this isn't a issue. Yes, I have a lot of subscriptions (e.g. 100-120) but this is not a problem for my Internet-Security. How I told you above, this is the second time, that my Internet-Security gave me an alert. But I use FreeTube nearly every day. And there are other programs which send a lot of requests to different servers, this is not a security issue - or not perceived as a threat. 

I suggest, that from time to time there is an malware infected Invidious-Server(-instance).

Who can run an Invidious instance? Everybody?
And what can be done to ensure the security of the instances?
Has anyone already thought about this?

Below I have attached the messages from Bitdefender:

![2023-06-26 19_31_57-Bitdefender-Sicherheitscenter](https://github.com/FreeTubeApp/FreeTube/assets/80854676/13ea4caa-a541-4752-ab14-5505e636e853)

![2023-06-26 19_32_18-Bitdefender-Sicherheitscenter](https://github.com/FreeTubeApp/FreeTube/assets/80854676/49d518d4-183a-4301-bbff-563d8b62ca3f)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Who can run an Invidious instance? Everybody?
Yes everybody but


> And what can be done to ensure the security of the instances?
Has anyone already thought about this?

The instances listed on api.invidious.io are vetted by the Invidious team. We list only those instances within FT. There aren't malicious instances on there. Also the code can be easily checked by yourself.

**Comment by FreedomIsAChoice** [comment]
If you are sure that it is not worth pursuing, then I agree. But I will get back to you if a similar case occurs.
