### ISSUE TITLE
[Feature Request]: 32bits x86 .zip .7z win builds, please!

### ISSUE THREAD

**Issue by DI555** [FreeTubeApp/FreeTube#3717]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

there’re a lots of 32 bits windows sistems yet.. and ReactOS is still 32 bits fornow..

### Proposed Solution

please, provide and win 32bits .zip and/or .7z builds!
many thanks in advance!

### Alternatives Considered

no

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Unfortunately a 32-bit release will never be happening as Electron dropped support for 32-bit a long time ago. We'd be more than happy to make releases for 32-bit if it was still supported but that sadly isn't the case any more.

**Comment by DI555** [comment]
hm, i thought and think clearly, win32 Windows7 builds is supported by electron//
