### ISSUE TITLE
Searching within a channel gives results from other channels

### ISSUE THREAD

**Issue by IHadToPickaUsername** [FreeTubeApp/FreeTube#372]
Searching within a channel gives results from other channels,

![freetubegithub1](https://user-images.githubusercontent.com/54917003/64298220-190e4680-cf75-11e9-9b55-3ff8196276ca.png)

![freetubegithub2](https://user-images.githubusercontent.com/54917003/64298245-2fb49d80-cf75-11e9-9949-14387dd5e7ae.png)

The issue/unwantedFeature actually comes from youtube, as many users have commented on [Reddit](https://old.reddit.com/r/youtube/comments/cynvwr/feature_discussion_youtube_is_now_promoting_other/)

One [user](https://reddit.com/r/youtube/comments/cynvwr/feature_discussion_youtube_is_now_promoting_other/eyx44nr/) on the thread made this [script](https://gist.github.com/ethanwu10/a446926af1de7cd9d7180f60dca1acbb) which seems to fix the issue on the browser.

The script just checks if the channel of the results matches the channel you're supposed to be searching within and removes the ones that don't.

**Comment by PrestonN** [comment]
While I can easily hide the unwanted channels, looking at the Reddit thread it looks like YouTube will be fixing this on their end.  It would be best to simply wait for YouTube to fix this themselves and FreeTube should reflect the changes once they are done.
