### ISSUE TITLE
[Bug]: Local API Error (Click to copy): TypeError: Cannot read properties of undefined (reading 'ur!)

### ISSUE THREAD

**Issue by tio-trom** [FreeTubeApp/FreeTube#3728]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Only enable the local API and no fallnack
2. Search for something, say "linux"
3. You get that error and no videos are displayed

It only seems to happen when you search. Everything else seems to work.

### Expected Behavior

Display the search results.

### Issue Labels

API issue, content not loading

### FreeTube Version

0.18.0-2.3

### Operating System Version

Linux Arch plus XFCE

### Installation Method

AUR

### Primary API used

Local API

### Additional Information

I would like to only rely on the local API since Invidious instances are banned more and more often by youtube.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can confirm that this is an issue on stable release but this has been already solved in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).
