### ISSUE TITLE
[Bug]: Freetube removes all subscriptions and channels, and does not allow you to subsrcibe to more.

### ISSUE THREAD

**Issue by asdfghjkl403622** [FreeTubeApp/FreeTube#3731]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. subscribe to a lot of channels
2. force a shut down of your device 
3. you will no longer be able to access your subscriptions or profiles, and you cannot add any new ones.

### Expected Behavior

My subscriptions should be accessible in my feed, and my profiles should still be available.  

### Issue Labels

data loss, feature stopped working

### FreeTube Version

v0.18.0

### Operating System Version

Linux mobian 6.1-rockchip #1 SMP PREEMPT_DYNAMIC Thu Jun  1 11:21:27 UTC 2023 aarch64 GNU/Linux

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
If you shutdown your device while FreeTube was still open and writing to its databases, they are probably corrupted now.

You can try deleting the profiles.db file in the location mentioned here: https://docs.freetubeapp.io/usage/data-location/

**Comment by asdfghjkl403622** [comment]
here is a pastebin of my profiles.db folder: https://pastebin.com/KPU0R2eH
is there any way to  save it?

**Comment by asdfghjkl403622** [comment]
maybe it's too long?

**Comment by asdfghjkl403622** [comment]
I have tried deleting the database files, and the issue still persisted. the files were not recreated, and I even tried deleting the whole freetube folder in .config, and not only did that not get remade when the app launched next, it also kept all the data outside of the subscriptions and profiles, which leads me to believe that the freetube data is not stored in it's .config folder.

**Comment by absidue** [comment]
As you are using the flatpak you need to check the flatpak location listed on that site, not the standard linux one.

**Comment by asdfghjkl403622** [comment]
ok I looked at it, and the one stored where the flatpak is has all of the subscriptions stored twice? it has the profile "all channels" and lists it's subscriptions, and then says subscriptions again and lists all of those 
[profiles.txt](https://github.com/FreeTubeApp/FreeTube/files/12002789/profiles.txt)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@asdfghjkl403622 so u are still unable to import your subscriptions? I could import them on my windows machine without any errors.
