### ISSUE TITLE
[Bug]: FreeTube doesn’t handles channels’ pages of geoblocked channels and doesn’t falls back to Invidious API

### ISSUE THREAD

**Issue by hollownights** [FreeTubeApp/FreeTube#3739]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When the user visits the page of a geoblocked channel, and Local API is the preferred API in the settings, FreeTube doesn’t falls back to an Invidious instance and just shows the default YouTube message: “This channel is not available”. No error is registered in the console. When visiting the channel page of a geoblocked channel on the browser, that message comes inside this html element:

```
<div id="alerts" class="style-scope ytd-browse"><yt-alert-renderer class="style-scope ytd-browse"><!--css-build:shady--><!--css-build:shady--><div id="container" class="ERROR style-scope yt-alert-renderer style-scope yt-alert-renderer">
  <yt-formatted-string class="style-scope yt-alert-renderer">This channel is not available.</yt-formatted-string>
</div>
</yt-alert-renderer></div>
```

Curiously, though, if the user subscribe to such a channel, when visiting the subscriptions page FreeTube does registers an error...

```
renderer.js:2 Error: This channel is not available.
    at new dP (renderer.js:2:1114108)
    at renderer.js:2:1380742
    at async a.getChannelVideosLocalScraper (renderer.js:2:1380609)
    at async renderer.js:2:1379674
    at async Promise.all (index 0)
    at async a.loadVideosForSubscriptionsFromRemote (renderer.js:2:1379458)
    at async a.maybeLoadVideosForSubscriptionsFromRemote (renderer.js:2:1380434)
(anonymous) @ renderer.js:2
```

… but also doesn’t do anything and doesn’t tries to retrieve the channel’s content through Invidious. In fact, it seems like the only time FreeTube does falls back to Invidious is when trying to get info on a video, something that, by default, is a meaningless action, as seen in #3733. This problem is also related to #3641.

### Expected Behavior

Make proper use of Invidious instances by actually falling back to the Invidious API.

### Issue Labels

API issue, content not loading, inconsistent behavior, usability issue

### FreeTube Version

nightly 3089

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
i would like to have multiple urls of channels that are geoblocked

**Comment by hollownights** [comment]
I don't want to promote any of these people, so I will just leave a link to a paste with links to their channels: https://bin.infini.fr/?7edf741eccf68a19#A1JEp6VBMs5s28D6Kh6L1k9xYSPsLS18ZJdS1LzBTAWA

Try opening in FreeTube and in the browser those channels, subscribing to them (in FreeTube) and playing their videos. After that, try opening in NewPipe the same channels and videos that you couldn't play in FreeTube and/or in the browser.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> When the user visits the page of a geoblocked channel, and Local API is the preferred API in the settings, FreeTube doesn’t falls back to an Invidious instance and just shows the default YouTube message: “This channel is not available”. 

I understand from a user point of view that it is annoying that Local API cant show u the channel and therefore asking us to make it fallback to IV but that is not the right thing to do. We just show the user the same thing as YT would and we wont fallback to IV in order to make something viewable. The user really needs to do that by them self.

> but also doesn’t do anything and doesn’t tries to retrieve the channel’s content through Invidious.

This comes back to the argument above. When fetching FT sees that it cant go to that channel because blocked so it wont retrieve the videos through the Local API. That doesnt mean it should fallback because FT knows it is expected behavior.
