### ISSUE TITLE
Add an option to replace thumbnails with a frame from the video.

### ISSUE THREAD

**Issue by SK10** [FreeTubeApp/FreeTube#374]
There is already an open source [add-on](https://github.com/pietervanheijningen/clickbait-remover-for-youtube) on Firefox that does this, Maybe it would help

**Comment by PrestonN** [comment]
I haven't mentioned this anywhere, but I actually planned on doing this for the next release.  It's a very simple thing to do which could also be a nice QOL improvement to users.

**Comment by PrestonN** [comment]
This has been implemented in the rewrite.
