### ISSUE TITLE
[Feature Request]: Allow copying channel rss feeds

### ISSUE THREAD

**Issue by OpenBozo** [FreeTubeApp/FreeTube#3740]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

i love the feature in invidious where you can copy the channel rss feed

### Proposed Solution

i propose adding this feature into freetube i would like seeing it next to the channel subscribe button 

### Issue Labels

display more information to user, new feature

**Comment by aleksejrs** [comment]
> i would like seeing it next to the channel subscribe button

Do you mean when clicking the Share Channel button?

**Comment by aleksejrs** [comment]
The RSS feed link is just "http://www.youtube.com/feeds/videos.xml?channel_id=" with the channel ID appended. The "Copy link" button copies "https://www.youtube.com/channel/" with the channel ID appended.

I am not sure copying the RSS link for a particular channel is very useful unless you have an RSS client you prefer to FreeTube for *some* channels. There is an "Export Subscriptions" button in "Data Settings", which can export an OPML file with *all* channels, or you can export a CSV file and replace the prefixes. Unfortunately, it does not take profiles into account yet.
