### ISSUE TITLE
[Bug]: Sort by oldest or most popular in the channel page does not work

### ISSUE THREAD

**Issue by OpenBozo** [FreeTubeApp/FreeTube#3741]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

sort by oldest or most popular in the channel page does not work

### Expected Behavior

i expect that when i sort channel videos by oldest i would be able to see the old videos or when i sort the channel videos by most popular i would be able to see the videos with higher views counts

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

0.18.0-1

### Operating System Version

Linux gunixs 6.4.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 06 Jul 2023 18:35:40 +0000 x86_64 GNU/Linux

### Installation Method

AUR

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can confirm that this is an issue in v0.18.0 but is already solved in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).
