### ISSUE TITLE
[Bug]: Broken Community post

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3746]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to https://www.youtube.com/@LofiGirl/community
2. scroll down until u see the post

![Capture](https://github.com/FreeTubeApp/FreeTube/assets/73130443/19b3c890-f3b3-4600-93e8-708e98219be5)

### Expected Behavior

Should look like

![Capture1](https://github.com/FreeTubeApp/FreeTube/assets/73130443/4c92fe2b-2797-46d8-acf5-cc937cc8096f)

### Issue Labels

content not loading, visual bug

### FreeTube Version

v0.18.0-nightly-3096 Beta

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

Error i see in console

![Capture2](https://github.com/FreeTubeApp/FreeTube/assets/73130443/423e4d9e-68b7-4474-a8a9-341669dd43e9)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by lamemakes** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc I can work this - are users supposed to be able to interact with content like quizzes and polls? I can't seem to vote on polls, did recreate with the quiz though.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi @lamemake in this example the quiz isnt visible for some reason and to fix this we need to make the post visible again. No need to make interactions with posts or polls.

If u want to look into more interaction style issues regarding to community posts u can maybe look into #3253

**Comment by lamemakes** [comment]
Yeah I gotcha, I was working on this yesterday and think I've got a solution to both. 

In terms of interaction I mean should users be able to select an option for a quiz or see what the correct option is? Like as opposed to just having a few blank boxes that don't reveal anything.

Cheers!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Umm im not behind my machine so i dont really know but users should see the same on FT as is shown on YT when u are a not logged in user

I don't think that not logged in users can interact with posts

**Comment by lamemakes** [comment]
Okay great - I think polls work that way but I was able to do a quiz and get the correct answer without logging in, even though afterwards it tried to direct me to a login: 

![IMG_20230808_092326](https://github.com/FreeTubeApp/FreeTube/assets/83597346/ee5eb69d-4ef1-4ce3-aae8-18e3094e3439)

The correct answer is also contained in the response in from indivious (I didn't check the local API though) so in that regard there wouldn't be any additional requests needed for this implementation.

If you though this was feasible we could either let the user take the quiz and show them when they're correct/incorrect *or* just highlight the correct answer right out of the gate.

Thanks for the thoughts here!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
if we want to allow interaction it should just be local, not sending the response to youtube

So the question is, does youtube give us the answer without having to interact?

if yes: we could implement local interaction just make them buttons and show the right answer afterwards (just because youtube pings their server when you answer doesn't mean we have to)

if no: we show it the same as polls
