### ISSUE TITLE
Import Subscriptions Unavailable  - Flatpak 

### ISSUE THREAD

**Issue by tippunmon** [FreeTubeApp/FreeTube#3774]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

After installation on going into data settings and clicking the "import subscriptions" button the button changes shade each time it is pressed but nothing else happens. 

### Expected Behavior

Expected to access the dialogues to import my .csv file which houses my YouTube subscription list.

### Issue Labels

content not loading, feature stopped working, usability issue

### FreeTube Version

Flatpak 

### Operating System Version

Salix 15.0 (Slackware Fork)

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

I am familiar with the methodology involved in importing my YouTube subscriptions and have done this many times in the past. In this instance I am simply unable to gain any response from any of the offered buttons displayed after entering the data settings segment. 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
Could you use "Ctrl +Shift + i" then try it again and see if anything appears in the log

**Comment by tippunmon** [comment]
Problem now resolved. Salix developer duplicated the issue and confirmed it. After technical investigation he discovered a further Salix package was needed then all worked perfectly.  Missing package =  xdg-desktop-portal-gtk
