### ISSUE TITLE
An option to stop refreshing subs

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#378]
When the refreshing subs process is started, there's no way to stop it. Sometimes the process takes a long time (possibly because of the connection issues -- it could be temporary). 

1. Would you add an option to stop the process? Because when the process is running, you can't really do anything in the app. So currently the option in to restart the app with the "fav" home tab. 

2.  Also would it be possible to refresh the subs in the background, so the user could normally use the app (search/play vids)?

This issue is similar to #330, but it's a different kind. :)

**Comment by PrestonN** [comment]
Adding the ability to cancel the sub refresh can be done, but I don't see background refreshes as a possibility.  You can technically already refresh your subs in the background but as you've noticed it locks up the rest of the app.  Nearly every function that FreeTube does is call the Invidious API and API calls are more or less queued to determine which call goes next.  I'm not really sure how to prioritize certain API calls at this time but I can try to experiment with it when I get some free time.  If anyone has suggestions for this then I'm open to it.

**Comment by PrestonN** [comment]
Auto refreshing subs have been removed in the rewrite.  If we re-add it I'll look into setting the interval / disabling it entirely.
