### ISSUE TITLE
[Bug]: Slow rendering with large history

### ISSUE THREAD

**Issue by Nemo157** [FreeTubeApp/FreeTube#3796]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

After importing my youtube history of ~32k videos rendering subscription pages slowed down a lot.

Profiling one load 1.5s is spent initializing the page to display, 80% of that in `historyIndex`, rendering each video calls it twice taking ~40ms each time.

### Expected Behavior

Increasing history size should barely affect page rendering speed.

### Issue Labels

usability issue

### FreeTube Version

v0.18.0-nightly-3112 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

It looks like it's doing a linear scan through the history, building an index by video-id would speed this up greatly.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Building a separate index by id would definitely help with this issue, it would double the RAM usage of the watch history (we still need to keep the other chronological one) but considering the potential rendering speedup of video/mixed item lists throughout FreeTube, it's probably worth it.

**Comment by apatheticslacker** [comment]
this is still a big problem on v0.19.0 Beta

**Comment by absidue** [comment]
We haven't done anything about it yet. The quick and dirty solution will double RAM use for every window, a proper solution will require more extensive refactoring and lots of testing. I could probably come up with some solutions but I won't be able to test, if they work and don't cause other issues, as I don't use the watch history/have it disabled.

**Comment by StrangestNoob** [comment]
wouldn't it only double the storage of the index? can you explain your reasoning

**Comment by absidue** [comment]
No, because FreeTube currently keeps the history in memory in every window in an array chronological order. To fix this issue the quick and dirty way, we could add a second history object, this time an object/map where the keys are the video id and the value is the history entry.

If you are wondering why the second object can't just have the video ids and the array indies as the values. When you watch a video again it gets placed at the front of the array and when you watch a new video is gets placed at the front of the array too, which means the indies change for every video you watch. Having to recreate that entire index object every time you watch a video, would just add more performance problems into the mix.

The proper solution would be to refactor the entire history handling, so that it is only cached in memory in the main process and the windows query the main process via ipc, when they need history entries (could be optimised, so it only returns the ones that are needed at that moment).
But the second option is a lot more invasive and requires a lot more work and testing, than the quick and dirty option that doubles memory use.

**Comment by StrangestNoob** [comment]
why not just a map that has the video id as the key and the value being the same object as in the already existing array? it can search by video id, doesn't need to duplicate the entry (just a pointer to the existing one), doesn't need to reorganise anything in the new map when videos are watched, just add an entry or remove an entry by key (video id)

**Comment by absidue** [comment]
That sounds like you'll just be move the performance and memory problem to the history page, as you'll have to duplicate and sort it for every visit to the history page. (haven't checked if the chronological order is used for anything else yet, will probably require rewriting the window sync code though).

**Comment by absidue** [comment]
Also again I have the watch history turned off as I just find it a nuisance. So if anyone creates a pull request with a solution to speed it up, all of you will either need to share your history files or rigorously test the pull request for us, including performance and bug hunting (rewriting how history is handled app-wide, is likely to introduce bugs).
A synthetic load won't be able to properly replicate your real world examples, that have scattershot watch dates, watch progress, payload sizes etc.

**Comment by absidue** [comment]
@Nemo157 @StrangestNoob Would you accept the history page becoming slow in exchange for the video lists in the rest of FreeTube becoming fast?

The choices are either slow video lists everywhere (current), slow history page (we would show a loading icon while it does the sorting) or doubling the memory usage (keeping both a sorted list and an indexed by id one in memory).

**Comment by Nemo157** [comment]
I just did a heap snapshot to check how much memory that actually is, of the 239MB the history array (with just <30k elements) is using 79MB of it, I at least would be completely fine with doubling that (though it also seems to me that it shouldn't actually require duplicate elements, just a new map referencing the same history objects). I also very rarely use the history page so I'd be fine with that taking a couple seconds to open.
