### ISSUE TITLE
[Bug]: channels without videos = channels with errors

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#3800]
### Guidelines

- [ ] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

On start, when subscriptions are first loaded, all channels _without_ videos are reported as channels with errors.

### Expected Behavior

Subscriptions should load without reporting errors just because they have no videos.

### Issue Labels

visual bug

### FreeTube Version

v0.18.0-nightly-3166

### Operating System Version

Windows 11

### Installation Method

Portable

### Primary API used

Local API

### Additional Information

This is a very recent bug added in the last few days.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @c5aba924-b91a-4504-b8e7-9dd81a704703 could u provide a few channels for us to test out?
