### ISSUE TITLE
Avast detects as Malware / Virus 

### ISSUE THREAD

**Issue by EJM97** [FreeTubeApp/FreeTube#381]
Avast (Virus definitions Version -190913-0) detects it as a FileRepMalware.
I downloaded zip file v0.7.0 for windows and .exe file both have problem
Checked in [Virus Total](https://www.virustotal.com/gui/file/b98322aa46941874c05c94f63eba4623e9b37c31d3b19026892840264fa8be89/detection), It says 3 engines detected it.

**Comment by PrestonN** [comment]
Check the [Wiki](https://github.com/FreeTubeApp/FreeTube/wiki/F.A.Q.#my-virus-protection-gave-a-warning-when-i-tried-to-run-freetube--is-freetube-a-malicious-application) for why this happens.  Also more information at #315
