### ISSUE TITLE
[Bug]: MPV playback doesn't work

### ISSUE THREAD

**Issue by aand18** [FreeTubeApp/FreeTube#3820]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open  `Settings > External Player`
2. Select `External Player > mpv`
3. In `Custom External Player Executable ` >   put `"X:\Downloads\mpv-0.35.1-x86_64-v3\mpv.exe"`     or your actual MPV path
4. Open a video, wait for playback, click `Open in MPV`
5. MPV doesn't open

### Expected Behavior

Video should play in MPV

### Issue Labels

feature stopped working

### FreeTube Version

v0.18 beta

### Operating System Version

Windows 10 v2004

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

Also not working in latest nightly.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
MPV requires youtube-dl to play YouTube videos, check that you have that available on your path.

**Comment by aand18** [comment]
OK, added youtube-dl to PATH (shouldn't this be in the readme/docs somewhere?)

It spawns the processes but exits after 2 seconds, no window is displayed.

![image](https://github.com/FreeTubeApp/FreeTube/assets/36073609/e0345100-0084-4659-b2e2-1007dabef05b)

**Comment by absidue** [comment]
I don't think it should be our job to document how to setup and configure external programs, especially when it is documented in their own docs and can be figured out with a single internet search.

Try copying the command line into a terminal and see if the MPV terminal output gives you some useful information. I highly suspect that this is an issue with your setup and not FreeTube, as nobody else has had this issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
inquires regarding external players migrated to https://github.com/FreeTubeApp/FreeTube/discussions/7789
