### ISSUE TITLE
[Bug]: VLC playback doesn't work

### ISSUE THREAD

**Issue by aand18** [FreeTubeApp/FreeTube#3821]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open  `Settings > External Player`
2. Select `External Player > VLC`
3. In `Custom External Player Executable ` >   put `C:\Program Files (x86)\VideoLAN\VLC\vlc.exe`     or your actual VLC path
4. Open a video, wait for playback, click `Open in VLC`
5. VLC v3.0.18  opens, the playback list briefly flashes a filename similar to the youtube URL e.g.  `watch?v=f8d9a090f-dsaf`; the playback list becomes empty immediately
6. Nothing happens after that

### Expected Behavior

Video should play in VLC

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

v0.18 beta

### Operating System Version

Windows 10 v2004

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
As Ammako mentioned this is a VLC issue, looks like their YouTube handling broke, as you'll see this message in VLC's logs if you turn on logging in the VLC settings: `lua error: Couldn't extract youtube video URL, please check for updates to this script`.
