### ISSUE TITLE
Unable to load channel

### ISSUE THREAD

**Issue by Brn9hrd7** [FreeTubeApp/FreeTube#383]
I just tried to refresh the subscription page and I got the "Unable to load channel" error with every channel I'm subscribed to. It seems like videos that are already added to the favorites won't load either.

**Comment by morfikov** [comment]
It looks like it's working for me just fine. Are you sure it wasn't just a temporary issue?

**Comment by Brn9hrd7** [comment]
I just tried it again, don't have the issue anymore...
