### ISSUE TITLE
[Feature Request]: Hide youtube shorts

### ISSUE THREAD

**Issue by HTF81** [FreeTubeApp/FreeTube#3836]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I'm tired of seeing shorts in my feed, I have no interest in them.

### Proposed Solution

Hide / filter out shorts from appearing on my subscriptions. 

### Alternatives Considered

Hunting down youtube execs and forcing them to watch shorts until their brain melts and I can coerce them into removing shorts. (The videos not the garments)

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is already possible in the latest nightly build

**Comment by Flashwalker** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
Not possible for search results

**Comment by Flashwalker** [comment]
Shorts are still present in the search results. Please add a filter for search results
