### ISSUE TITLE
[Feature Request]: Handle redirected YouTube search results URL

### ISSUE THREAD

**Issue by confluence** [FreeTubeApp/FreeTube#3846]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I have filed this as a feature request rather than a bug, since it's unclear to me whether this feature is broken or just unsupported (since my setup may be atypical).

I am using the LibRedirect extension in Firefox to redirect YouTube URLs to FreeTube. I also have YouTube's search added as a search engine directly in the browser. When I search for `something` using this built-in search (i.e. bypassing browsing to YouTube in order to perform a search), I am sent to a URL in the format `https://www.youtube.com/results?search_query=something`. This is redirected to FreeTube, but it appears that FreeTube cannot process URLs in this format, and I get a blank page and a bunch of API errors.

### Proposed Solution

I would like to be redirected to a FreeTube search with the same query.

### Alternatives Considered

I know that I can search directly in FreeTube, but this makes the process much less seamless. As far as I know it's not possible to integrate an external app as a search engine in Firefox, so I don't think that there's any way for me to add FreeTube directly as a search engine and bypass YouTube entirely.

### Issue Labels

improvement to existing feature

**Comment by ChunkyProgrammer** [comment]
Hi, this should be fixed in the next version of libredirect
