### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by omega3** [FreeTubeApp/FreeTube#3862]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Please add option to organize subscriptions into folders.

### Proposed Solution

Something like [Youtube Tabs add-on](https://addons.mozilla.org/en-US/firefox/addon/youtube-tabs-/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) is a nice example. Any other ideas are welcomed.

### Alternatives Considered

I have no ideas. So also [PocketTube - YouTube Subscription Manager
](https://pockettube.io/)

### Issue Labels

new feature

### Additional Information

This feature used to be in youtube but they removed it. Users need to use add-on on web-browsers. Being able to organize subscriptions better would attract more users to FreeTube.

**Comment by absidue** [comment]
Sounds like you are looking for FreeTube's already existing profiles feature: https://docs.freetubeapp.io/usage/profiles/
