### ISSUE TITLE
[Bug]: Audio Duplication From Previous Video

### ISSUE THREAD

**Issue by jorge-a-goncalves** [FreeTubeApp/FreeTube#3866]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Audio from a previously watched video plays during new video. Space bar stops and resumes both the current video and the audio from a previous video. 
What I'm certain about is that it takes changing from a video to another, but I don't know in what form, timing or anything else. I'm also not certain if it is from THE previous video or just A previous video. 
I've seen this happen for a few weeks at random, not very common. 

### Expected Behavior

I would expect that only the audio from the video that is being watched be played.

### Issue Labels

usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux Box 6.3.10-200.fsync.fc38.x86_64

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @jorge-a-goncalves could u try out the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds) to check if this fixes it for u

**Comment by jorge-a-goncalves** [comment]
Hi, I have tried on the nightly build for a little and did not seem to be able to reproduce the bug, but since it's pretty rare to happen, I might just have been unlucky. 
On the other hand, on the latest official release it did happen to me again and this time I was more attentive so I got more information. 
The bug happened on a specific video, the first I watched on this session, the video that is bugged will play the audio whenever I go, I can stop and play the audio with the space bar, be it on another video, the main page, a channel page, history, doesn't matter. Also even after trying to change video a couple of times, the bug presisted and with the same video. 
I watched the full video in question and having auto play enabled he jumped to the next one alone, so it might be something with auto play. But having let another videos auto play into the next one, did not solve it nor bugged another.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Hi, I have tried on the nightly build for a little and did not seem to be able to reproduce the bug, but since it's pretty rare to happen, I might just have been unlucky. 

Please keep using the nightly build as these are always up to date with the latest changes.



> On the other hand, on the latest official release it did happen to me again and this time I was more attentive so I got more information. The bug happened on a specific video, the first I watched on this session, the video that is bugged will play the audio whenever I go, I can stop and play the audio with the space bar, be it on another video, the main page, a channel page, history, doesn't matter. Also even after trying to change video a couple of times, the bug presisted and with the same video. I watched the full video in question and having auto play enabled he jumped to the next one alone, so it might be something with auto play. But having let another videos auto play into the next one, did not solve it nor bugged another.

There have been allot of changes since v0.18.0 and i would recommend to use the nightly build like suggested above.

I will add the "Waiting for Response from Author" label to this issue. This will close the issue automatically after 14 days when u did not leave a comment. 

Please comment only on this issue within 14days if u have experienced this issue on the latest nightly build.
