### ISSUE TITLE
[Feature Request]: gather recommended videos when watching videos to use on some recommendations page

### ISSUE THREAD

**Issue by aleksejrs** [FreeTubeApp/FreeTube#3868]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

On a Watch page, there are recommended videos on the right, unless you disabled that.

With the watch history enabled on YouTube, YouTube recommends you related videos. If you disable watch history, YouTube used to show you recommendations related to your channel subscriptions, but now it seems to be removing that.

It would be great if FreeTube could remember the recommendations from various videos and show them all on a page, especially if it can sort or categorize them in some way (there have been ways to have YouTube recommendations separated by the reason they were chosen).

### Proposed Solution

Recommendations may be stored for the videos in History and/or Playlists, as configured. I would prefer them to be stored for as long as the video is in History* and/or Playlists, but PrestonN [wanted them to be stored for a session only for privacy reasons in 2020](https://github.com/FreeTubeApp/FreeTube/issues/677#issuecomment-710116842).
If FreeTube can distinguish between videos recommended specifically to you and videos recommended neutrally, then retention could depend on that.

*This issue is not about which videos to recommend on the recommendation page or how to sort them. The initial implementation could just show them all, but a good implementation is not simple; for example, I would often mark a video watched because I don't like it.

### Issue Labels

new feature

### Additional Information

There is https://github.com/FreeTubeApp/FreeTube/issues/677#issuecomment-710116842 and some discussion on that page, but the goal of #677 is disputed and it has been ignored lately, it is not even in discussion #3620.

**Comment by absidue** [comment]
As mentioned in the other issue, please compare FreeTube with logged out YouTube, not to YouTube when you are logged in.

YouTube will never give you recommendations specifically for you in FreeTube, that's literally the whole point of FreeTube existing, to get away from YouTube's tracking. The recommendations you see on the watch page are only for that video, YouTube also doesn't know about what channels you are subscribed to in FreeTube.

**Comment by absidue** [comment]
Please don't open duplicate issues just because you feel like the existing ones have been "ignored", that's just spam.

**Comment by aleksejrs** [comment]
@absidue, it isn't ignored for no reason. It is about two different things (showing random videos from subscriptions and showing collected recommendations) and thus cannot be improved so that it stops being ignored. Please reopen.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@aleksejrs its being "ignored" because there are way too many issues with higher priorities than this one. Opening an issue to talk about it again wont solve anything. If u would like that feature to be implemented that bad u should open a PR urself. Otherwise u should wait in line.
