### ISSUE TITLE
auto-update system and frenquency

### ISSUE THREAD

**Issue by mouarfff** [FreeTubeApp/FreeTube#387]
hello !

Each time i launch freetube, i have an update, very often i need to go to github and download my self last version, always ^^

there is no auto-update system ?

**Comment by PrestonN** [comment]
Not yet.  Auto updates are planned.  If you use certain Linux binaries then auto updates won't be possible.

**Comment by fourstepper** [comment]
@mouarfff the issue has, however, been taken into account. It is under feature requests here - https://github.com/FreeTubeApp/FreeTube/issues/539
