### ISSUE TITLE
[Bug]: Suddenly changes to Spanish dubbing

### ISSUE THREAD

**Issue by RolfTBerg** [FreeTubeApp/FreeTube#3873]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Suddenly the FreeTube app puts a Spanish voiceover on an English channel. And I can't seem to change it. There doesn't seem to be a setting for it. Why does it happen, and how do I make it go back to the original language. It has happened a few times now. ?

### Expected Behavior

I expect the video to play in its original language. 

### Issue Labels

API issue, inconsistent behavior, usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Windows 10 

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Use the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).
