### ISSUE TITLE
FreeTube Executable being blockes after 0.7.0 by AVG and detected by other antivirus

### ISSUE THREAD

**Issue by JoeJoeTV** [FreeTubeApp/FreeTube#388]
Here's the Virus Total scan: https://www.virustotal.com/gui/file/b98322aa46941874c05c94f63eba4623e9b37c31d3b19026892840264fa8be89/detection

The AVG on my computer also triggered when I ran it. I have sent it for analysis a week ago but it's still detected.
I really want to know if it's being detected because of not being signed or something else.

**Comment by PrestonN** [comment]
See #381 and #315
