### ISSUE TITLE
[Feature Request]: Keyboard Shortcut to copy link to clipboard

### ISSUE THREAD

**Issue by fov95** [FreeTubeApp/FreeTube#3889]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I build a quite elaborated dmenu script to download stuff from youtube which worked fine back when I used a browser to navigate yt.
Now on freetube I have to manually use the mouse to copy the link of the current running video to clipboard for further use.

### Proposed Solution

A keyboard shortcut would be nice to copy the video link or even playlist link to clipboard.
Or maybe someone already came up with a different solution for this issue?

### Alternatives Considered

I don't know any other way to get the link tbh and messing with mouse input automation for this feels a bit too messy for me.

### Issue Labels

ease of use improvement, new keyboard shortcut, support for external software

**Comment by absidue** [comment]
Everything accessible with a mouse, should also be accessible by keyboard navigation in FreeTube e.g. the tab key and space bar.

Does that solve your issue?

**Comment by absidue** [comment]
The problem with having a keyboard shortcut like that, is that it isn't one size fits all, as we have 4 different links to the video in the watch page share menu and different users will want different ones: YouTube, YouTube Embed, Invidious, Invidious Embed.

**Comment by fov95** [comment]
It's 21 times tab until I reach the links :D 
I think having the original youtube link would be sufficient for _any_ external use because you can put the needed characters as needed into invidvidious and whatever else.
Having the original youtube link is the way to go IMHO.
Was worth a try. :)

**Comment by absidue** [comment]
Alternatively, as FreeTube is built with Electron, you can use something like Selenium with the web devtools API, to query and control the page, without having to do hacky keyboard and mouse interactions.

**Comment by fov95** [comment]
I'd rather not install more stuff for something that should be possible in the program itself tbh.
I tried the tab method and even that isn't consistent. On some videos it needs 18, some 19, some 20 tabs as well. -_-

It seems the history.db is updating in real time. Too bad it's only updating after pressing pause in the video..
So going into a video, xdotool key space and tailing the last entry in history.db seems to be a working method..
It's hacky but works _for now_
Getting the whole playlist would still be a nice addition..
Leaving it open

**Comment by absidue** [comment]
Tabbing will be inconsistent because it's based on where you last left the focus and also as you are automating it, you might be sending the keypresses too fast for the app to keep up with.

Please keep in mind FreeTube was designed to be used by humans, not by automation tools.

I do not recommend writing code that observes the databases at runtime, considering that when the database framework decides to flush the state to disk and when it compacts it back to a single line, is outside of FreeTube and your control.

I question why you would want to go through the pain of automating a UI app, when command line tools exist that were designed with automation in mind.

**Comment by absidue** [comment]
Copying the entire playlist on the playlist page, won't work unless you first load all the playlist pages, which is undesirable for a normal user as they don't want to sit there for ages waiting for it to load.

Honestly I think it's probably best for you to maintain a personal custom build that contains all the hacks you need to get your automation working, as some of the things you'll want/need will be undesirable for a normal user.

If you don't want to maintain a custom build, please use my already suggested solution of doing it with Selenium or a similar web app automation framework.

**Comment by fov95** [comment]
> Tabbing will be inconsistent because it's based on where you last left the focus and also as you are automating it, you might be sending the keypresses too fast for the app to keep up with.

Nah I tested it. Always started in the same position. Yea it may have been too fast but it should be as fast as possible

> Please keep in mind FreeTube was designed to be used by humans, not by automation tools.

You know how people are. We are lazy and want everything at fingertip.

> I do not recommend writing code that observes the databases at runtime, considering that when the database framework decides to flush the state to disk and when it compacts it back to a single line, is outside of FreeTube and your control.

Well then you know what to do :p

> I question why you would want to go through the pain of automating a UI app, when command line tools exist that were designed with automation in mind.

I think to get people off the browser and off google accounts, alternative software should allow _(power)_ users to do what they did before without hassle.
Let's be honest, FreeTube users are maybe 10% _normies_.
Offering direct download is really nice. Still I'd like to just press a key on my keyboard and be done with it.
I am not using any other software and see no reason for it. I watch YouTube only on FreeTube because it's all I need.

**Comment by fov95** [comment]
> Copying the entire playlist on the playlist page, won't work unless you first load all the playlist pages, which is undesirable for a normal user as they don't want to sit there for ages waiting for it to load.
> 
> Honestly I think it's probably best for you to maintain a personal custom build that contains all the hacks you need to get your automation working, as some of the things you'll want/need will be undesirable for a normal user.
> 
> If you don't want to maintain a custom build, please use my already suggested solution of doing it with Selenium or a similar web app automation framework.

aight

**Comment by absidue** [comment]
I know you might not want to use external tools, but tools like yt-dlp are commandline tools, that were designed with automation in mind, supporting things like downloading entire YouTube playlists, embedding subtitles etc etc, which are all things which FreeTube's rudimentary downloader doesn't support.
