### ISSUE TITLE
[Bug]: Video not loading properly.

### ISSUE THREAD

**Issue by SkyTheGreatOne** [FreeTubeApp/FreeTube#3894]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

On the following video, there are many distorted colors: https://youtu.be/QMaDaaL7S-c

UPDATE: The distorted colors only appear if "Legacy Formats" is selected instead of "DASH Formats." I'm not sure if this would still be considered an issue. If it isn't, please close/edit this issue.

![image](https://github.com/FreeTubeApp/FreeTube/assets/87588105/0f3992c9-dc31-411c-9cca-db3f79622805)
![image](https://github.com/FreeTubeApp/FreeTube/assets/87588105/b51877b5-ccb0-4dd6-b148-60db0d9cd52c)

### Expected Behavior

It is expected to not have the colors distorted.

### Issue Labels

visual bug

### FreeTube Version

Build Number: #3236

### Operating System Version

Linux Mint 21.2

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
It looks like the actual video file for that stream is corrupted, as it has the same issues in Firefox or when downloaded and viewed in VLC. Something must have gone wrong in YouTube's video pipeline for that video.

As we can't do anything about YouTube having a broken stream, all we can do is recommend that you don't use the legacy formats for that video.

Closing this as the file is corrupt on YouTube's side, so we can't do anything about it from our side.
