### ISSUE TITLE
[Bug]: Some external players don't play the YouTube video

### ISSUE THREAD

**Issue by redactedscribe** [FreeTubeApp/FreeTube#3902]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Set VLC or PotPlayer as the external player of choice.
2. Click the button to launch a video from FreeTube in an external player.

**VLC:** VLC opens but no video plays (nothing happens).

**PotPlayer:**

```
[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: spawn potplayermini64 ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

[OK]
```

MPV works like it did before.

### Expected Behavior

All external players should play the content.

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

v0.19.0-beta a8658a7

### Operating System Version

Windows 11 22H2 22621.1992

### Installation Method

Scoop

### Primary API used

Local API

### Additional Information

My MPV, PotPlayer, and VLC are all installed via Scoop. MPV still works, but not the other two newly introduced external players, so the Scoop installation method shouldn't be the problem here I think.

Pasting a YouTube URL in VLC as a network stream also doesn't work, however I've never done so, so I'm not sure if that should normally work.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
VLC: we can't do anything about it, as VLC itself can't handle YouTube URLs properly anymore (see https://github.com/FreeTubeApp/FreeTube/issues/3821#issuecomment-1656741951 for more information)
PotPlayer: looks like it's not on your PATH, so you need to specify the pot player exe location in the FreeTube external player settings, as it can't find the exe to launch at the moment.

**Comment by redactedscribe** [comment]
Adding PotPlayer to PATH fixed the issue. I guess I'll just wait for VLC to update for YouTube URLs to begin working in it again. A descriptive error would help when an external player can't be found. Thanks.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
inquires regarding external players migrated to https://github.com/FreeTubeApp/FreeTube/discussions/7789
