### ISSUE TITLE
[Feature Request]: latest release URL on api.github.com

### ISSUE THREAD

**Issue by sid-the-sloth** [FreeTubeApp/FreeTube#3928]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I want to automate the installation of FreeTube with a script.

Most of the apps on GitHub have a url pointing to the latest release, such as:

https://api.github.com/repos/FreeTubeApp/FreeTube/releases/latest

In the case of FreeTube that does not exist, one must fish out the full json -- and then the first element (with index 0) from:

https://api.github.com/repos/FreeTubeApp/FreeTube/releases

### Proposed Solution

Look for example at how VSCodium team is doing it:

https://api.github.com/repos/VSCodium/vscodium/releases/latest

### Alternatives Considered

n/a

### Issue Labels

ease of use improvement

**Comment by absidue** [comment]
GitHub only generates that URL for repositories that have non-prerelease releases, as FreeTube is still in beta, the latest URL doesn't exist, unfortunately that is a gitHub limitation that is out of our control.

**Comment by absidue** [comment]
Closing as there is nothing we can do about it from our side.

**Comment by dinotheextinct** [comment]
So why use GitHub?
