### ISSUE TITLE
Bug: Freetube unable to load subscriptions

### ISSUE THREAD

**Issue by mcmurphy8097234789** [FreeTubeApp/FreeTube#393]
**Expected Behaviour:**
Freetube appimage boots and loads subscriptions and plays videos

**Actual behaviour:**
When Freetube Appimage is loaded, youtube subscriptions are unable to load (gives message to this effect). Behaviour is the same whether or not proxying through invidious is selected. Freetube unable to search, display, or play any video. Rebooting computer and re-downloading the 0.7.0 Beta does not fix this issue.

However, leaving freetube open for 5 minutes resolved this bug. Bug is not reproducible at this time.

Computer Specs: Ryzen 1600x, Asrock Ab350m pro4 mbd, MSI GTX 1080 Duke, Gskill 3200mhz RAM, Samsung EVO 860 SSD. 
OS: Solus 4.0 Fortitude Budgie, Linux 5.2.13-126.current #1 SMP PREEMPT Sat Sep 7 08:07:23 UTC 2019 x86_64 GNU/Linux

**Comment by stemy2** [comment]
Ihave a almost similar problem. When proxy is activated, it can't load anything. When proxy is desactivated, it loads only some of my subscribed channels.

**Comment by stemy2** [comment]
It seems it's because the default invidious instance is failing. You can change it in the settings. For now, the instance https://vid.wxzm.sx works pretty fine.
