### ISSUE TITLE
[Feature Request]: Voice-over translation

### ISSUE THREAD

**Issue by il2020** [FreeTubeApp/FreeTube#3940]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There are many interesting videos in different languages that I don't understand. In the browser I can use a script that translates and immediately dubs the video in an understandable language, but in FreeTube I can't enable it.

### Proposed Solution

You can add a translation function directly in FreeTube. For example, you can add a button to the player that, when pressed, will open a menu for language selection.

Below you can see exactly what the translation script does, where and how it accesses (the Yandex service is use), and what elements it adds to the video.

https://github.com/ilyhalight/voice-over-translation/blob/master/dist/vot.user.js

### Alternatives Considered

Or you could add the ability to import a custom script that will translate the video. For example, embed Tampermonkey or its analog into FreeTube.

### Issue Labels

new feature, support for external software

### Additional Information

![image](https://github.com/FreeTubeApp/FreeTube/assets/77854832/b652e126-a97d-4b4d-9f37-f71146397d0b)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @il2020 unfortunately this service uses Yandex and that goes against the goal of FT to provide users privacy. 

Also we provide captions in videos when they are available.

if we do add something like that it has to be either local or something that has a similar level of trustworthiness as invidious.

Based on these things i'll close this issue. If u come up with a solution to these things we'll consider reopening.
