### ISSUE TITLE
[Feature Request]: Subscription groups

### ISSUE THREAD

**Issue by rootsandstones** [FreeTubeApp/FreeTube#3941]
### Guidelines

- [x] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I have a lot of subscriptions and I would like to able to group them. 

### Proposed Solution

The browser extension Pockettube is a good example how it could work.

### Alternatives Considered

-

### Issue Labels

ease of use improvement, new feature

**Comment by absidue** [comment]
Hi
Sounds like you are looking for FreeTube's profiles feature, here are the docs about them: https://docs.freetubeapp.io/usage/profiles/.
