### ISSUE TITLE
[Feature Request]: Do not show upcoming livestreams in the live tab of the subscriptions page

### ISSUE THREAD

**Issue by chrrybmb64** [FreeTubeApp/FreeTube#3944]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

In the live tab of my subscriptions page, I do not want to see upcoming livestreams. I only want to see current livestreams and streams which have already ended.

### Proposed Solution

Add an option to hide upcoming livestreams in the live tab of the subscriptions page. I still want to see upcoming streams when I do searches and view channels, so this option would only affect the subscriptions page.

### Alternatives Considered

n/a

### Issue Labels

improvement to existing feature

**Comment by absidue** [comment]
Just leaving a note here for when/if someone decides to implement this.

This will only work when the subscriptions are fetched via the APIs not RSS (less than 125 subscriptions in current profile and RSS not manually enabled in the subscription settings), as the RSS feeds don't provide any information to indicate the live status of a video/stream (no duration or upcoming information either).

**Comment by chrrybmb64** [comment]
Closing in favor of #5785
