### ISSUE TITLE
[Bug]: (Unofficial NixOS package) App turns entirely white a few moments after startup on wayland-WM-only-setups

### ISSUE THREAD

**Issue by LAURAilway** [FreeTubeApp/FreeTube#3953]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [ ] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open FreeTube
2. Either wait a few seconds or click something
3. Entire app turns solid white

### Expected Behavior

App doen't turn white and continues working as normal

### Issue Labels

visual bug

### FreeTube Version

v0.19.0

### Operating System Version

6.4.7-zen1 #1-NixOS ZEN

### Installation Method

Nix

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18.0

### Additional Information
I am using sway (wayland) as window manager

It worked yesterday after updating to 0.19, the package downgraded to 0.18 for some reason and after updating again, the error ocurred

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by LAURAilway** [comment]
Edit: Issue doesn't appear on a live-iso with gnome-wayland, river and sway both seem to have it, will test further

**Comment by LAURAilway** [comment]
Further testing revealed the error message `GetVSyncParametersIfAvailable() failed`, which only appears on river wm and seems to be inked to [this](https://github.com/electron/electron/issues/32760) issue in electron

**Comment by socherbyc** [comment]
Same error here on NixOS for versions 0.18.0 and 0.19.0.

**Comment by socherbyc** [comment]
No issues using the AppImage version.

**Comment by absidue** [comment]
As you are all using NixOS and can't replicate the issue with the official downloads, please report the issue to the people packaging the NixOS package, as it's unofficial/not maintained by us.

**Comment by absidue** [comment]
@LAURAilway In the future please only tick the `I have encountered this bug in the official downloads of FreeTube.` box if you are actually using an official download.

**Comment by LAURAilway** [comment]
> @LAURAilway In the future please only tick the `I have encountered this bug in the official downloads of FreeTube.` box if you are actually using an official download or have at least tested it with an official download.

Yep, created the issue way too late at night and didn't see the "unofficial downloads" section begin. Sorry.

**Comment by absidue** [comment]
@janTasija @socherbyc Could you please check if @LAURAilway's fix works for you too, so that we can close the issue if it's resolved?

**Comment by socherbyc** [comment]
It worked for me too :)

**Comment by absidue** [comment]
Thanks everyone! I'll close this then :)
