### ISSUE TITLE
[Bug]: externer video player - Javascript Error

### ISSUE THREAD

**Issue by harkai84** [FreeTubeApp/FreeTube#3971]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

when I press external video player, a javascript error comes up.
Here is a picture:

https://postimg.cc/cKWGryKy

### Expected Behavior

it should open the external video player VLC.

### Issue Labels

content not loading, feature stopped working, visual bug

### FreeTube Version

v0.19.0 Beta

### Operating System Version

 Linux Mint 21.2 x86_64

### Installation Method

flatpak

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by harkai84** [comment]
Sorry, the Installation Method is flatpak not *.deb

**Comment by ChunkyProgrammer** [comment]
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1735 i think some people in the comments of that issue were able to get it to work using flatseal

**Comment by harkai84** [comment]
Thank you ChunkyProgrammer. I tried flatseal. But it doesnt work at all.
Here is a pic taken in flatseal:

https://postimg.cc/xJMFqnKb

The same errror msg comes up like i posted it in the first place. (https://postimg.cc/cKWGryKy)
When I Set "Custom External Player Executable" to "flatpak-spawn", the error msg disappears, but nothing happen.
The external player load not at all.
Maybe it is another bug.
Perhaps some one has a tip for me.
Thank you all :)

**Comment by ChunkyProgrammer** [comment]
Can you zend a screenshot of your external player settings?

**Comment by harkai84** [comment]
of course:

https://postimg.cc/ykXrGxDb

I hope this help.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
inquires regarding external players migrated to https://github.com/FreeTubeApp/FreeTube/discussions/7789
