### ISSUE TITLE
[Bug]: choppy YouTube play

### ISSUE THREAD

**Issue by arturasb** [FreeTubeApp/FreeTube#3979]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Install FreeTube v0.19.0 Beta from Flathub.
2. Set Prefered API Backend to "Local API".
3. Play a Youtube video:
a) it starts 1080p
b) in ~10-15 seconds it start buffering
c) video is switched to lowest resolutions - 240p or even 144p

### Expected Behavior

It is expected that video will continue to play 1080p, without being choppy/buffering even in lowest resolutions. Same video plays fine in Firefox at 1080p.

This the quality I get now:
 ![image](https://github.com/FreeTubeApp/FreeTube/assets/35307455/c1fe8cb4-335c-4943-938f-644be39ddc2a)

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.19.0 Beta

### Operating System Version

Fedora Workstation 37
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 37 (Thirty Seven)
Release:	37
Codename:	ThirtySeven

### Installation Method

flatpak, Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18.0 Beta

### Additional Information

N/A

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Do you have the proxy video through Invidious setting enabled?

**Comment by arturasb** [comment]
> Do you have the proxy video through Invidious setting enabled?

It seems, I don't
![image](https://github.com/FreeTubeApp/FreeTube/assets/35307455/fe9a895b-1c0d-4ffc-bd60-63bc672c996b)

**Comment by absidue** [comment]
If you set the default quality to 1080p instead of auto in the player settings, does it stay at 1080p with smooth playback?

**Comment by arturasb** [comment]
> If you set the default quality to 1080p instead of auto in the player settings, does it stay at 1080p with smooth playback?

No, it starts buffering in ~5 seconds with a last frame frozen.

**Comment by absidue** [comment]
Oh goodness that sounds like YouTube throttling must be an A/B test then as playback seems to be fine on my machine.

Do you have a proxy setup in the proxy settings section? If yes please try disabling it and seeing if that fixes the issue.

If you are using a VPN, can you try without one to see if it still happens and if you aren't using a VPN can you try with one (please close FreeTube between turning on/off you VPN, just to make sure that all connections are closed).

Additionally to check if it's actually throttling and not something else, could you please open the devtools (CTRL+SHIFT+I) and switching to the network tab before opening the video page. When you open the video, see if any of the `videoplayback?expire=...` requests are taking a significantly long amount of time than others. e.g. 10+ seconds.

**Comment by arturasb** [comment]
> Do you have a proxy setup in the proxy settings section? If yes please try disabling it and seeing if that fixes the issue.

No, I do not have a proxy.

> If you are using a VPN, can you try without one to see if it still happens and if you aren't using a VPN can you try with one (please close FreeTube between turning on/off you VPN, just to make sure that all connections are closed).

No, I'm not behind VPN.

> Additionally to check if it's actually throttling and not something else, could you please open the devtools (CTRL+SHIFT+I) and switching to the network tab before opening the video page. When you open the video, see if any of the videoplayback?expire=... requests are taking a significantly long amount of time than others. e.g. 10+ seconds.

I don't know how to interpret this tho:
![image](https://github.com/FreeTubeApp/FreeTube/assets/35307455/e0c8cd19-7bb7-4fbc-9769-73fea605edf7)

**Comment by arturasb** [comment]
Additionally checked with LibreWolf web browser, 1440p widescreen video plays without a single hiccup.

**Comment by arturasb** [comment]
An update - tried enabling proxying  through Invidious and now I'm able to play 720p, 1080p smoothly. But I had to experiment and find an Invidious proxy instance which worked....

**Comment by RodoMa92** [comment]
same exact issue, it's unusable

![image](https://github.com/FreeTubeApp/FreeTube/assets/16669146/406eeef5-b303-4cba-a703-a6eadb31be31)

**Comment by RodoMa92** [comment]
Mind you that I have a 2.5Gbit connection down, so I doubt it's a connection issue :)

**Comment by absidue** [comment]
@RodoMa92 Just to confirm you are using the local API with proxy videos through Invidious disabled?

**Comment by RodoMa92** [comment]
> @RodoMa92 Just to confirm you are using the local API with proxy videos through Invidious disabled?

Yes, that is correct. I can play videos fine after searching for a decent invidious instance and enabling it as a proxy, but I had issues in the past where I'm finding myself having to test different instances multiple times (since sometimes they tend to perform badly from load or just the people behind them having issues).

Might be worth to implement a dynamic tester for people who requires to use a proxy through invidious to test which instance is the faster/working one. Might take a look at it myself, but I'm not really a web developer myself, so I can't promise anything.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@arturasb are you still facing this issue on v0.20.0?

**Comment by arturasb** [comment]
> @arturasb are you still facing this issue on v0.20.0?

Yes, but the nature of the issue is a bit different - there are days and weeks when I can watch videos without interruptions and then suddenly day, two or three days when it is barely watchable in 480p. As I'm on stable system (desktop PC, LAN connected) and my internet is on fiber, I cannot determine condition when or why playback gets choppy suddenly and then it is OK again... On thing I check when I experience poor playback - I test couple or more videos directly from YouTube via web browser and all the time it is OK.
I'm ready to help by collecting some stats or something if needed, just give me instructions.
Small update - now I'm on Fedora 39 and FreeTube v0.20.0 Beta.

**Comment by arturasb** [comment]
Fresh example. For ~4-5 days now FreeTube drops resolution to 144p and only this resolution is not choppy. This is how it looks:
![image](https://github.com/FreeTubeApp/FreeTube/assets/35307455/aa64e2dc-5678-4da0-ab0a-7c934fd8cf5f)

And the same video in Firefox (720p and more,plays smoothly):
![image](https://github.com/FreeTubeApp/FreeTube/assets/35307455/9af3a2e7-ad91-4653-bb98-58e4600ee285)

**Comment by arturasb** [comment]
> Fresh example. For ~4-5 days now FreeTube drops resolution to **144p** and playback only of this resolution is not choppy. This is how it looks: ![image](https://private-user-images.githubusercontent.com/35307455/328142927-aa64e2dc-5678-4da0-ab0a-7c934fd8cf5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTM1OTIsIm5iZiI6MTcxNDk5MzI5MiwicGF0aCI6Ii8zNTMwNzQ1NS8zMjgxNDI5MjctYWE2NGUyZGMtNTY3OC00ZGEwLWFiMGEtN2M5MzRmZDhjZjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDExMDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZjg0MDdhYmI2NjRkMjUwMGNiMDQ1MDM3ODdmYTA5YzRlMTdmMDA2NDVjMjRiZmYzNWUzY2Y0MmUwOTMxMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Mq2l1Su5eSyvwU4eT-3kn_c7h4bvEfpWdJ-2pOPUeo)
> 
> And the same video in Firefox (720p): ![image](https://private-user-images.githubusercontent.com/35307455/328143247-9af3a2e7-ad91-4653-bb98-58e4600ee285.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTM1OTIsIm5iZiI6MTcxNDk5MzI5MiwicGF0aCI6Ii8zNTMwNzQ1NS8zMjgxNDMyNDctOWFmM2EyZTctYWQ5MS00NjUzLWJiOTgtNThlNDYwMGVlMjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDExMDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNGY0Y2ZkYWY0NTYzYWIxMjQwZWZlZWQ4MDNhNjA4OGJjZjA3NzZjYWM1N2E4MzMwODVhZmYyNzlmNDMyN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yylxki51NUBkqqOkj8C_-xATG0hk9Ta7leihCggXJUs) 1440p, plays smoothly ![image](https://private-user-images.githubusercontent.com/35307455/328143844-477ba653-7913-4227-a547-0649f2f12444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTM1OTIsIm5iZiI6MTcxNDk5MzI5MiwicGF0aCI6Ii8zNTMwNzQ1NS8zMjgxNDM4NDQtNDc3YmE2NTMtNzkxMy00MjI3LWE1NDctMDY0OWYyZjEyNDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDExMDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZmQ4ODg2Y2Q1NTM1NzY5YWI0Mzc1ZmI2ZWJhMThlYmU5YTI1MDEyZjZmNGU0NTg2NGI4MTIyYzk4YTZiNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MItyT8h0GkcR9MgUXF12-1LJIA9Nj95FnSGzlWo3ad0)

Interestingly, if I toggle "Proxy Videos Through Invidious" ON, FreeTube plays 1080p without hiccups now.

**Comment by RodoMa92** [comment]
Yeah, since the throttling is done only where freetube connect directly through youtube and not using a proxy. Issue is that a lot of the time I need to keep reloading the page to get a workable invidious instance. I would still like to get this fixed if possible.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@arturasb is this still an issue for you in v0.22.1

**Comment by arturasb** [comment]
> @arturasb is this still an issue for you in v0.22.1

No, with new versions the issue is gone.
