### ISSUE TITLE
Invidious API error: null

### ISSUE THREAD

**Issue by burnerdog** [FreeTubeApp/FreeTube#398]
This error popped up today whenever I try and watch a video.
Here is what the console says:

> invidio.us/api/v1/videos/gOgfdAZq9rc?:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by PrestonN** [comment]
Is this still happening? Apparently there were some issues with Invidious earlier which have been fixed.

**Comment by PrestonN** [comment]
This is likely related to the discussion over [here](https://github.com/omarroth/invidious/issues/811) on the Invidious page.  Since this isn't anything with FreeTube itself, I will close this issue.
