### ISSUE TITLE
[Bug]: "Up Next" video sometimes opens instead of the pasted video URL

### ISSUE THREAD

**Issue by MoonlitMonitor** [FreeTubeApp/FreeTube#3983]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

This bug may be difficult to replicate as it has been occurring intermittently for me:

1. Open a YouTube video on FreeTube
2. Copy a YouTube video URL and paste it in the search-bar at the top and press enter
3. Sometimes, instead of FreeTube loading the video at the pasted URL, it instead loads the video which is first on the "Up Next" list at the right

I have noticed that this sometimes occurs when I have multiple FreeTube windows open, but I am not sure if that is relevant to the issue at hand.

### Expected Behavior

FreeTube should open the video URL that was pasted into the search-bar instead of the video that is first in "Up Next".

### Issue Labels

content not loading, inconsistent behavior, usability issue

### FreeTube Version

Release v0.19.0 Beta

### Operating System Version

Fedora 38

### Installation Method

.rpm

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could you maybe provide a way to reproduce this consistently. Im unable to recreate this
