### ISSUE TITLE
[Bug]: New version (v0.19.0) deb installer does not replace/overwrite previous version (v0.18.0)

### ISSUE THREAD

**Issue by networkr0** [FreeTubeApp/FreeTube#3989]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Version 0.18 was working ok
Then I got message at launch of new version available, 0.19.
Downloaded .deb file to install on Ubuntu 22.04 assuming it would overwrite and replace Version 0.18, but it does not, now there are two versions on my machine with the exact same launch icon.
Next version releases should have installer that replaces and not leave older version on system.
In the meantime, I also need to know how to delete version 0.18 from my Ubuntu 22.04LTS system

### Expected Behavior

Next version releases should have installer that replaces and not leave older version on system.

### Issue Labels

usability issue

### FreeTube Version

v0.19.0

### Operating System Version

Ubuntu 22.04 LTS

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18.0 Beta

### Additional Information

n/a

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Ammako first of all thanks @Ammako for helping out on so many issues :)

> Run the 0.18 one and see if it actually launches 0.19

Second please try this and come back to us @networkr0 !
