### ISSUE TITLE
[Enhancement] Download avancement bar

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#399]
Hello,

Whe we download a video, we have no avancement indicator, except the increasigly big output file.

**Comment by PrestonN** [comment]
Right now I don't consider "Downloading videos" as a current function of FreeTube, though it's something that is planned.  The ability to download videos within FreeTube is something that happened by chance as a button was included with the video player.  Obviously it works, though it leaves a lot to be desired.

When I get around to making a download feature, things such as progress will be included along with it.
