### ISSUE TITLE
[Bug]: Downloading the big thumbnail and naming it properly

### ISSUE THREAD

**Issue by Janaue** [FreeTubeApp/FreeTube#3991]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I am on w10 with version v0.19.0-nightly-3363 Beta

Sometimes I want to download the thumbnail of a video. For this i right click on it and select ''save image as''. This works on videos in my playlists or the feed for the current profile, by giving a jpg called ''mqdefault.jpg''. However the only thumbnail i get is very tiny, 320x180px.

So to get a big thumbnail i thought i would click a particular video, like https://youtu.be/kCTpfqRJ2kk, and then right lick on it (the video still is not playing), the only thing happening is that the still picture gets bigger and gets outside the player, and I don't get any right click menu at all. illustration after i right-click on a video

![2023-09-04 07_57_17-Algebraic Topology 0_ Cell Complexes - FreeTube](https://github.com/FreeTubeApp/FreeTube/assets/10972636/9f5da812-a58d-431c-b540-d446183c73dd)

### Expected Behavior

So 
-is it possible to have a right lick menu on a particular video to download the thumbnail
-can the thumbnail be bigger than 180px
-can the thumbnail be called by the title of the video

### Issue Labels

usability issue

### FreeTube Version

v0.19.0-nightly-3363 Beta

### Operating System Version

w10 22h2

### Installation Method

.zip

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Zeabyte** [comment]
Hello and thank you for contributing your idea. YouTube thumbnails come in different resolutions. Those relatively small thumbnails, which you are talking about, have the identifier "mqdefault" (Medium-quality default). You can download different thumbnails with the following URLs:
- https://i.ytimg.com/vi/<ID\>/<identifier\>
or
- https://img.youtube.com/vi/<ID\>/<identifier\>

by replacing `<ID>` with the YouTube video ID found in the URL for the YouTube video and `<identifier>` with one of for example "mqdefault.jpg", "hqdefault.jpg" or (for the best quality possible) "maxresdefault.jpg".

One could add a button beneath the video for downloading thumbnails in different resolutions.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isnt a bug. You're asking for new things to be implemented and if that is possible. I would recommend opening a feature request instead of a bug so we can discuss this further.
