### ISSUE TITLE
[Bug]: app crashing after 1 to 5 seconds

### ISSUE THREAD

**Issue by alexou2** [FreeTubeApp/FreeTube#3998]
### Guidelines

- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Launch the flatpak version of freetube
2. Wait about 1-2 seconds
4. The app crashes in my case

### Expected Behavior

the app souldn't crash

### Issue Labels

usability issue

### FreeTube Version

0.19.0 Beta

### Operating System Version

Kubuntu 23.04

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.19.0 Beta

### Additional Information

I can interact with the app before it crashes.

the error when I start freetube(from the terminal):
 `LaunchProcess: failed to execvp:`
`xdg-settings`
`[2:0904/192325.741751:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`
`[2:0904/192325.741791:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`

The error when the app crashes: 
`[46:0904/192329.806703:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!`
`[46:0904/192331.826508:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!`

in journalctl: 
`Sep 04 19:23:25 <pc_name> systemd[1793]: Started app-flatpak-io.freetubeapp.FreeTube-6474.scope.`
`Sep 04 19:23:25 <pc_name> systemd[1793]: Started app-flatpak-io.freetubeapp.FreeTube-6499.scope.`
`Sep 04 19:23:33 <pc_name> systemd[1793]: app-flatpak-io.freetubeapp.FreeTube-6474.scope: Consumed 1.546s CPU time.`

The app keeps crashing since I forbade it from running in the backgound(there was a kde popup for that asked me if i want freetube running in the background). Thats my best guess for now.

(Edit)
I can make the app last for ~5 seconds if i interact with it.
### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by chiefbief** [comment]
I have the same issue.

- App downloaded from Discover, the Kubuntu Software center (Flatpak, v 0.19) opens for a few seconds and then closes without warning.

**Comment by absidue** [comment]
According to https://github.com/FreeTubeApp/FreeTube/issues/3638#issuecomment-1587400690 denying it to run in the background is the cause of the issue.
Not sure why it causes problems or how exactly that flatpak/flatseal setting works but it clearly breaks something in FreeTube.

**Comment by chiefbief** [comment]
Yes! Thank you. This works : 

- Install Flatseal from the Software Center
- When you launch this app it will display a list of all the Flatpak apps that you have installed. 
- Select FreeTube in the right hand pane
- Scroll almost to the bottom where you will find the setting that will allow the app to run in the background.
- Restart FreeTube

Thank you @absidue
