### ISSUE TITLE
Feature Request: Audio Only Mode??

### ISSUE THREAD

**Issue by Singtoh** [FreeTubeApp/FreeTube#401]
Hello,
Wonderful app. Love it so far!!! I have been looking for an app like this for a long long time and have tried others like MotionBox & Minitube but they just don't work well at all!!
Anyway, Just wondering if you could add an "Audio Only" option for us that are bandwidth limited?? Maybe it has it already and I missed it. I often just listen to the audio on youtube subscriptions when I work. Thanks and please do keep up the good work. This app is super and I like it alot!!!! Good Job!!!!!

Cheers,

Singtoh

**Comment by PrestonN** [comment]
It's a bit hidden, but it's an option when you use the Legacy player.  Check the quality selection tab when the legacy player is enabled. You can default the legacy player in the settings but you can't default to audio only.

There's a limitation with having the option in the dash player alongside the typical qualities which is why it feels a bit hidden.  Maybe it would be worth making it easier to find.

Anyways, since this feature exists, I will close this issue.

**Comment by marscher** [comment]
defaulting to audio would be a great thing, if you just intend to listen to some music.

**Comment by Blake-LeBlanc** [comment]
> It's a bit hidden, but it's an option when you use the Legacy player. Check the quality selection tab when the legacy player is enabled. You can default the legacy player in the settings but you can't default to audio only.
> 
> There's a limitation with having the option in the dash player alongside the typical qualities which is why it feels a bit hidden. Maybe it would be worth making it easier to find.
> 
> Anyways, since this feature exists, I will close this issue.

Is this the setting you're talking about @PrestonN ?

![image](https://user-images.githubusercontent.com/19244245/155186668-004d2954-466d-473e-abd2-4db252086290.png)

**Comment by PrestonN** [comment]
When I made that original comment, it was regarding the version of FreeTube that existed before the rewrite. Everything was structured very differently around that time.

Having said that, we do still provide an audio only mode. The screenshot you provided will set it to audio only by default. If you'd like to toggle between them, there's an icon below the video view counter that will let you switch between DASH, Legacy, and Audio formats.

**Comment by Blake-LeBlanc** [comment]
> When I made that original comment, it was regarding the version of FreeTube that existed before the rewrite. Everything was structured very differently around that time.
> 
> Having said that, we do still provide an audio only mode. The screenshot you provided will set it to audio only by default. If you'd like to toggle between them, there's an icon below the video view counter that will let you switch between DASH, Legacy, and Audio formats.

Oh, beautiful! Learned something new, that makes it really convenient! Thank you for following up Preston!

**Comment by marscher** [comment]
The only "convenience" extension of this already existing feature would be to change the format for a session, or playlist, instead of just one song/video. Should we open a new issue for this?

**Comment by BlaY0** [comment]
I would agree... like for example there's a toggle for autoplay also in the "Up Next" section of the watch page even tho it's in the settings already. It's not session based but it's there and you see it all the time and can toggle it from there.

The reasoning for adding audio/video toggle to the watch page would be if one for example has password protected settings for the kids but this setting is not really something that would need to be password protected. I know it kind of duplicates the function of "change media format" button, but maybe this button could be redefined to interpret the same setting from the settings (not just for the currently playing video) and it could change in button icon style (different for DASH, Legacy or Audio)
