### ISSUE TITLE
[Feature Request]: Option to have Channel Groups

### ISSUE THREAD

**Issue by tarigeltom** [FreeTubeApp/FreeTube#4014]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hi
I 've been using FreeTube for a couple of month and definitely I love it! Thank you soo much for the great job
But I miss the option to have "Channel Groups"  based on a selection of some of my channels, currently subscribed to in Freetube.
Say I have 200+ Youtube channels, and I am in the mode of watching only graphic creation for example. without this requested feature, I will have to click on individual channels and see which contain what I am looking for.

### Proposed Solution

With the "Channel Groups" option,  I could make a new group named  "Graphics" for example, in which I choose only the channels that are related to graphics creation. and when  done creating it and I click the "Graphics" group, FreeTube shows only feed from the selected channels.

The requested feature is available in Newpipe Android app.

### Alternatives Considered

Alternatively, There could be an option to "tag" my channels; eg: News, Documentaries, Graphic Creation.. etc
All my tags will be shown in the side panel ready to be clicked.
When I click the "News" tag for example,  FreeTube will show only feed from channels  that are tagged "News".

### Issue Labels

ease of use improvement, new feature, new optional setting

**Comment by absidue** [comment]
FreeTube already support multiple profiles, which sounds like it is already what you are looking for, here is the docs page on them: https://docs.freetubeapp.io/usage/profiles/
