### ISSUE TITLE
[Feature Request]: Middle-clicking timestamps in comments and description to open video at that timestamp in new window

### ISSUE THREAD

**Issue by Winterhuman** [FreeTubeApp/FreeTube#4015]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to a video, and navigate to a comment with a timestamp link.
2. Click the timestamp with the middle mouse button.
3. See the Subscriptions page open in a new window.

### Expected Behavior

On middle click, open a new window for the current video with the video playback set to start at the timestamp value (similar to what would happen for an "Include Timestamp" link that'd you'd get from the Share button).

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.19.0 Beta

### Operating System Version

Arch Linux, x86_64, 6.4.12-arch1-1

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Currently they aren't proper links, they are empty links with a click handler that tells the player to seek to that timestamp. Not sure if it's possible to have your requested functionality, while still having them seek the player if you activate them normally.

**Comment by absidue** [comment]
Changed this to a feature request.

**Comment by Winterhuman** [comment]
@absidue If it isn't possible to implement the feature, disabling the ability to middle-click them might be a good idea (either as a temporary or permanent change), since the current behaviour isn't very intuitive or useful

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing this as i have opened https://github.com/FreeTubeApp/FreeTube/issues/4018. For more info read the additional context header on that issue
