### ISSUE TITLE
[Bug]: Data Recovery Issue After Linux Format

### ISSUE THREAD

**Issue by mathe00** [FreeTubeApp/FreeTube#4019]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When I formatted my Linux system and restored my personal folder with ~/.config/Freetube/profiles.db, I am now trying to launch FreeTube, but it opens empty. Additionally, when I try to open the .db file, it asks for a password. I would like to understand why this is happening and how I can recover my data, especially my subscriptions.

### Expected Behavior

I expected FreeTube to launch normally with all my data, including my subscriptions, after restoring the profiles.db file.

### Issue Labels

content not loading, data loss, usability issue

### FreeTube Version

v0.19.0 Bêta

### Operating System Version

Manjaro Linux, Kernel 6.1.44-1-MANJARO (64-bit)

### Installation Method

.AppImage

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Freetube doesn't add any kind of password to the files, they are unecrypted plaintext files. Sounds like something went wrong in your backup or when restoring it, as this is definitely not caused by FreeTube.

The system asking you for a password when you try to open the file, is probably why FreeTube is failing too, because it doesn't have that password. Have you checked that the file is owned by your current user and that the directories permissions are correct?

**Comment by mathe00** [comment]
Yes, everything is correct at this level. It's just that when I try to open the .db file with DB Browser, for example, to see what's inside, I'm asked for a password because the database is encrypted.

**Comment by absidue** [comment]
It's a plaintext file with lines of json inside it, you should be able to open it in amy text editor, db explorer might not recognise the format.

FreeTube doesn't do any kind if encryption on the files, so either your program just isn't able to handle plaintext files or something you've done has resulted in it getting encrypted.

**Comment by mathe00** [comment]
ok thanks for your answers, I'll look into it
