### ISSUE TITLE
[Feature Request]: chatreplay.stream implementation

### ISSUE THREAD

**Issue by God-damnit-all** [FreeTubeApp/FreeTube#4024]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

YouTube channels used for archiving Twitch VODs sometimes make use of a free service called [Chat Replay](https://chatreplay.stream/), which simulates the Twitch chat of the original stream by timecode as the video plays.

Videos can be played either through [their website](https://chatreplay.stream/videos), [an extension](https://chatreplay.stream/extension), or a [GreaseMonkey script](https://chatreplay.stream/script). Compatible videos can be found [here](https://chatreplay.stream/videos).

### Proposed Solution

The GreaseMonkey script linked above should help with implementing this feature.

### Issue Labels

new feature

**Comment by absidue** [comment]
As FreeTube is primarily a privacy focused app, we want to be cautious that we don't integrate 3rd party services, that will hurt user's privacy. Can you confirm that chatreplay.stream fits into the guidelines we layed out for ReturnYouTubeDislike here?: https://github.com/FreeTubeApp/FreeTube/issues/1927#issuecomment-1007121970
