### ISSUE TITLE
[Feature Request]: Song finder integration

### ISSUE THREAD

**Issue by realgooseman** [FreeTubeApp/FreeTube#4033]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

You watch a video and hear a song you like but don't know the title. The YouTube website could use Shazam, AudD or AHA Music Chrome extension to find that song. But it's not the case for FreeTube yet.

### Proposed Solution

Integrating a song finder plugin/extension that can be turned on or off, via ACRCloud, AudD, AHA Music API...

I found [ShazamIO](https://github.com/dotX12/ShazamIO) as well (reverse engineered Shazam API), might this work too ?

### Alternatives Considered

Chrome extension support on Electron for those particular song finding extensions ? (Don't know if possible)

### Issue Labels

new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
As FreeTube is primarily a privacy focused app, we want to be cautious that we don't integrate 3rd party services, that will hurt user's privacy (the only exception is YouTube, but as this is a privacy friendly YouTube app, that one is unavoidable without loosing functionality). 

Can you confirm that the services u listed fits into the guidelines we layed out for ReturnYouTubeDislike here?: https://github.com/FreeTubeApp/FreeTube/issues/1927#issuecomment-1007121970

**Comment by realgooseman** [comment]
[ShazamIO](https://github.com/dotX12/ShazamIO) might fit into the guidelines as it's an open source library. The question is, can it be implemented in FreeTube and is it a good enough solution ?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Open source library doesn't mean privacy friendly. This tool still connects to Apple's servers.
