### ISSUE TITLE
Invidious API Error: Video unavailable.

### ISSUE THREAD

**Issue by rmlrml** [FreeTubeApp/FreeTube#404]
Hello.  Just installed FreeTube_0.7.0_amd64.deb in Debian Stable and using FreeTube for the first time.  Exported my YT subscriptions as OPML and imported into FT.  But every video I click, from any channel at all, returns

`Invidious API Error: Video unavailable.`

If I click the menu next to a video and select "Open in Mini Player", same error.

"Proxy Videos Through Invidious" is turned off in Settings, I don't know why invidious is involved here.  What do I do?

**Comment by danrobi11** [comment]
Same here

**Comment by PrestonN** [comment]
Looking into it, it looks to be a problem with the Invidious API and not Invidious itself.  It seems to be throwing an error when it wasn't before.

This seems to only be an issue with the main instance though.  As a workaround, you can use a different Invidious instance over at the [Instances](https://instances.invidio.us/) page.  This issue should be fixed when @omarroth is able to look into it.

For @omarroth, this is the error being given from Invidious.

```
"Expected Hash for #[]?(key : String), not Array(JSON::Any)"
```

This error is given even when no JSON object is passed along with it.

**Comment by rmlrml** [comment]
> use a different Invidious instance

worked, thanks

**Comment by SlidingHorn** [comment]
Stupid question:  How do I change Invidious instances in FT?  I'm on the settings screen and I don't see the option.  (linux version - Ubuntu 18.04)

**Comment by rmlrml** [comment]
@SlidingHorn scroll all the way down and it's called "Current Invidious Instance".  You manually type it in.

**Comment by SlidingHorn** [comment]
@rmlrml Doesn't appear to be in my version...that said, it looks like the main invidious API is back up and working now

**Comment by Singtoh** [comment]
Just a heads up. I just rebooted my machine and my router and it's working again!! Don't know man, just letting you know it's working for me now, at the moment.

Cheers

**Comment by PrestonN** [comment]
This seems to have been fixed upstream so I will go ahead and close this issue.
