### ISSUE TITLE
Invidious API Error: Video Unavailable

### ISSUE THREAD

**Issue by Singtoh** [FreeTubeApp/FreeTube#405]
Just started getting this this morning. Invidious API Error: Video Unavailable??? All videos will not play today. Yesterday all was ok and with no problem. I did get some upgrades this morning though and after them this seems to be happening. Here is a "History List" of the upgrades recieved this morning. I hope it helps, as I said it was fine before going to bed last night:

Upgrade: libsystemd0:amd64 (237-3ubuntu10.29, 237-3ubuntu10.31), udev:amd64 (237-3ubuntu10.29, 237-3ubuntu10.31), libudev1:amd64 (237-3ubuntu10.29, 237-3ubuntu10.31), systemd-sysv:amd64 (237-3ubuntu10.29, 237-3ubuntu10.31), libpam-systemd:amd64 (237-3ubuntu10.29, 237-3ubuntu10.31), systemd:amd64 (237-3ubuntu10.29, 237-3ubuntu10.31), libnss-systemd:amd64 (237-3ubuntu10.29, 237-3ubuntu10.31)

Cheers,

Singtoh

**Comment by danrobi11** [comment]
Same here

**Comment by PrestonN** [comment]
Closing in favor of #404
