### ISSUE TITLE
Error writing socket: Broken pipe

### ISSUE THREAD

**Issue by cyberchief1984** [FreeTubeApp/FreeTube#406]
I keep seeing this error, and videos don't play. What's wrong?

**Comment by PrestonN** [comment]
I believe that this is related to some recent issues with Invidious.  You can learn more about it over [here](https://github.com/omarroth/invidious/issues/811).  As a workaround, you can switch to a different Invidious [instance](https://instances.invidio.us/) which should solve the problem.
