### ISSUE TITLE
[Feature Request]: Inconsistent/nonexistent search results for "free with ads movies" 

### ISSUE THREAD

**Issue by shadycloud** [FreeTubeApp/FreeTube#4065]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Inconsistent / non existent search results for "free with ads movies" 

Standalone search for a movie hosted as 'free with ads' on YT doesn't return the desired movie in results. (Tested searching for "13 Hours: The Secret Soldiers of Benghazi")

URL for 13 Hours: The Secret Soldiers of Benghazi:
https://www.youtube.com/watch?v=YDZgtl4OsXk

URL for searching "free with ads movies" on YT: https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D

![Screenshot from 2023-09-23 09-04-47](https://github.com/FreeTubeApp/FreeTube/assets/13189052/3fead67d-6d11-43f7-aa91-6ba3cfb28e14)
![Screenshot from 2023-09-23 08-32-59](https://github.com/FreeTubeApp/FreeTube/assets/13189052/b92249e8-2a5d-4695-9248-0273fdf1e9bf)
![Screenshot from 2023-09-23 08-34-09](https://github.com/FreeTubeApp/FreeTube/assets/13189052/ad2e2ba2-6b0e-4c39-8751-c3a8ff8d872e)

### Proposed Solution

If possible, returning the exact search results as YT would be ideal.

### Alternatives Considered

Perhaps a button that feeds on youtube.com/feed/storefront could be another path to a solution of locating featured free movies.

### Issue Labels

ease of use improvement, improvement to existing feature

### Additional Information

I first thought of posting this issue as a bug since it seems to fit "inconsistent behavior", but decided it's more of a feature request after [reading ](https://blog.codinghorror.com/thats-not-a-bug-its-a-feature-request/)

**Comment by absidue** [comment]
We don't currently show them in the search results as FreeTube would only be able to play the trailers, which we currently don't do. Those free with ads movies have DRM and as far as I know Electron doesn't support it out of the box, as Google doesn't open source it.
