### ISSUE TITLE
[Bug]: Plasmashell restarts and Freetube crashes on launch

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#4075]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. launch freetube portable version or latest arch repository version

2. Plasmashell from KDE Plasma version: 5.27.8 crashes oftentimes along with freetube

### Expected Behavior

Freetube launches without crashing itself or plasmashell

### Issue Labels

causes crash

### FreeTube Version

v0.19.0

### Operating System Version

6.5.3-1-Manjaro 

### Installation Method

Portable

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

Not Sure

### Additional Information

Produces TypeError on launch, not sure if related
```
TypeError: Cannot destructure property 'value' of 'object null' as it is null.
    at /home/linux/Desktop/freetube-0.19.0-linux-portable-x64/resources/app.asar/dist/main.js:2:240440
    at async _ (/home/linux/Desktop/freetube-0.19.0-linux-portable-x64/resources/app.asar/dist/main.js:2:240396)
    at async App.<anonymous> (/home/linux/Desktop/freetube-0.19.0-linux-portable-x64/resources/app.asar/dist/main.js:2:245665)
[198187:0925/171506.149060:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[198187:0925/171507.234691:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
```

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This could the be same as #3998, could you check if the suggested solution works for you?

**Comment by Arndorferd** [comment]
No because flatpak in general works. However it doesnt integrate well with my plasma theme so I generally avoid flatpaks. If I would have a guess, I think its because Flatpak likes to use GTK and this appears like an issue with how this program interacts with Qt. My Qt version is 5.15.10.

**Comment by Arndorferd** [comment]
Out of curiosity I tested on x11 and it still happens but with less consistency than on wayland.

**Comment by absidue** [comment]
The relevant part of the log is `GetVSyncParametersIfAvailable() failed`, which is probably linked to this upstream issue in Electron: https://github.com/electron/electron/issues/32760

The only workaround in that thread is to disable hardware acceleration, which for a video playing app like FreeTube, is definitely not something we want to do.

**Comment by Arndorferd** [comment]
Is it a red herring? Thats just logs from starting the program in terminal. I thought you may know more. Im not sure how to get more detailed information at this point. Suspecting program interaction with qt or plasmashell is the issue.

**Comment by Cyanide-1** [comment]
> No because flatpak in general works. However it doesnt integrate well with my plasma theme so I generally avoid flatpaks. If I would have a guess, I think its because Flatpak likes to use GTK and this appears like an issue with how this program interacts with Qt. My Qt version is 5.15.10.

Freetube uses electron, not GTK.

**Comment by Cyanide-1** [comment]
Which package are you using? Manjaro is known for issues like this.

**Comment by PapaBones** [comment]
Have the same issue, KDE-Plasma, Arch Linux, Nvidia GPU on x11 though mine's not the flatpak but the version from the AUR. This usually happens when another fullscreen window is on another display(i.e. a game). Freetube did crash once or twice @ launch but usually just runs and then randomly crashes. Don't know if it is related and whether or not I should open a new issue up.

**Comment by absidue** [comment]
@PapaBones Can you still reproduce the issue on the latest FreeTube release 0.22.0?

**Comment by PapaBones** [comment]
Latest KDE and Freetube(freetube-git from the AUR) have not shown this exact issue. Problem has fixed itself thankfully.

**Comment by absidue** [comment]
Thank you for confirming.
