### ISSUE TITLE
[Bug]: Long loading option when runing app without the cursor

### ISSUE THREAD

**Issue by bungadrum** [FreeTubeApp/FreeTube#4077]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open the Application Finder with the keybinding that's the default or a custom hotkey that you set yourself
2. Search for Freetube
3. Press ENTER
4. Curosr animation starts and it doesn't stop for 30-40 min while left clickin on it it stops after a minute

### Expected Behavior

When you run the app without the mouse cursor it should load the same way, but it doesn't the loading animation lasts 30-40 minutes or even longer. Eventually it stops while if you click on the icon with a mouse the loading time only lasts 1 minute. I am using XFCE and when I run it with the Application finder I get this problem don't know if it's a Flatpak issue. If you reboot the system while the cursor is still loading it will give you a error so you have to wait for 30-40 min for it to stop before you do anything while if you just click it with a mouse it will only last 1 minute at best.

### Issue Labels

inconsistent behavior, usability issue, visual bug

### FreeTube Version

v0.19.0 Beta

### Operating System Version

Xubuntu 22.04 LTS

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

I haven't tested if this bug happenes on other keybord app launchers only on the default XFCE one.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This sounds like an issue with your launcher, not FreeTube.

**Comment by bungadrum** [comment]
It only happens when FT is runned this way every other app works fine

**Comment by absidue** [comment]
Again sounds like your launcher is doing something weird, FreeTube doesn't know or care about how you activated the icon in your launcher. FreeTube is built with Electron, a framework built on top of the Chromium source code, so we don't even have low level access, so it is extremely unlikely that the FreeTube code is causing that.
