### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by TheFrenchGhosty** [FreeTubeApp/FreeTube#408]
"Chocolatey is software management automation for Windows that wraps installers, executables, zips, and scripts into compiled packages."

https://chocolatey.org/

TL;DR: This is a package manager similar to apt/pacman with community maintained packages similar to the Arch User Repository **for Windows**.

Having a Chocolatey package for Freetube would be great considering how bad Windows handle software installation/updates.

Edit: Actually, there is [one](https://chocolatey.org/packages/freetube/) (it's marked as pre-release so I didn't see it) but it's heavily outdated and looks abandoned (the github page of the author doesn't exist anymore).

**Comment by digitalcoyote** [comment]
I'd be willing to adopt that package, but the process for doing so can take a bit. I'll see what I can do to get the process started.

**Comment by vncastanheira** [comment]
Any update on this?

**Comment by PrestonN** [comment]
FreeTube is currently unofficially available within Chocolatey over [here](https://chocolatey.org/packages/freetube/).  I am unaware if this will be updated for the rewrite, however it should at least still be mentioned.
