### ISSUE TITLE
[Bug]: Blank Page When Watching Videos

### ISSUE THREAD

**Issue by akano12** [FreeTubeApp/FreeTube#4097]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Play a video 
2. Halfway through the video, FreeTube turns into a blank page

### Expected Behavior

Video plays till end without any issues

### Issue Labels

content not loading, inconsistent behavior, usability issue

### FreeTube Version

0.19.0-2

### Operating System Version

6.5.5-arch1-1

### Installation Method

AUR (Unofficial)

### Primary API used

Invidious API

### Additional Information

Issue started yesterday iirc, encountered it multiple times on different videos. Searched in closed/opened issues and didn't find anything, could've missed if there's any.

Anyway i'm proxying everything through invidious instance. And below is an attached screenshot of how FreeTube looks like when the issue happens..
![2023-10-03_21-01](https://github.com/FreeTubeApp/FreeTube/assets/50032603/be319e25-a1ea-4dc3-aeb7-7371155f4022)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@akano12 u checked this requirement

> I have encountered this bug in the official downloads of FreeTube.

But the only download u mentioned is AUR which is an unofficial download.

Did you or did u not test this on an official download before reporting this?

**Comment by akano12** [comment]
> @akano12 u checked this requirement
> 
> > I have encountered this bug in the official downloads of FreeTube.
> But the only download u mentioned is AUR which is an unofficial download.

Because i've tested the appimage (considering there isn't a pacman release for arch) before trying the AUR.
And i updated my system yesterday and one of the updates that were available was for electron, not sure if this is related to the issue.

**Comment by ChunkyProgrammer** [comment]
@akano12 could you try this build with an updated version of electron and see if it fixes the issue? https://github.com/FreeTubeApp/FreeTube/pull/3967#issuecomment-1713066061

It's always a good idea to back up your data before installing the new build if you haven't already

**Comment by ACR-Jeff** [comment]
On Debian 12 Bookworm, I have encountered this issue after unpacking freetube-0.19.0-linux-portable-x64.7z and executing freetube on several occasions within the last few days. I didn't really give it much thought at first, Assumed it was an issue with my internet until it happened 2 times in a row today, I am proxying also through invidious, Possibly an issue with an Invidious instance? I am going to monitor when it happens and check the invidious instances, As I know I don't have one set to default.

**Comment by ACR-Jeff** [comment]
Well since my last comment, I downloaded freetube_0.19.0_amd64.AppImage and encountered the blank page issue 2 times on different invidious instances, Later I will be trying the deb package.

**Comment by akano12** [comment]
> @akano12 could you try this build with an updated version of electron and see if it fixes the issue? https://github.com/FreeTubeApp/FreeTube/pull/3967#issuecomment-1713066061
> 
> It's always a good idea to back up your data before installing the new build if you haven't already

Will give it a try later today, been busy the past few days.

**Comment by akano12** [comment]
> On Debian 12 Bookworm, I have encountered this issue after unpacking freetube-0.19.0-linux-portable-x64.7z and executing freetube on several occasions within the last few days. I didn't really give it much thought at first, Assumed it was an issue with my internet until it happened 2 times in a row today, I am proxying also through invidious, Possibly an issue with an Invidious instance? I am going to monitor when it happens and check the invidious instances, As I know I don't have one set to default.

Not an instance problem, if there's a problem with an instance videos won't play, not crash freetube.

My only guess is that there's something wrong with electron, it would be great if you test the version attached above your first comment and see if it works

**Comment by ACR-Jeff** [comment]
> > On Debian 12 Bookworm, I have encountered this issue after unpacking freetube-0.19.0-linux-portable-x64.7z and executing freetube on several occasions within the last few days. I didn't really give it much thought at first, Assumed it was an issue with my internet until it happened 2 times in a row today, I am proxying also through invidious, Possibly an issue with an Invidious instance? I am going to monitor when it happens and check the invidious instances, As I know I don't have one set to default.
> 
> Not an instance problem, if there's a problem with an instance videos won't play, not crash freetube.
> 
> My only guess is that there's something wrong with electron, it would be great if you test the version attached above your first comment and see if it works

Makes sense, I downloaded several different copies of v0.18.0 Beta and tested them through out the day, I haven't seen FreeTube crash, This is with even my previous config files.

**Comment by absidue** [comment]
@ACR-Jeff Please download and test that specific version in the link listed above that you were asked to test, testing a version of FreeTube that is almost a year old isn't helpful to the situation.

**Comment by ACR-Jeff** [comment]
> @ACR-Jeff Please download and test that specific version in the link listed above that you were asked to test, testing a version of FreeTube that is almost a year old isn't helpful to the situation.

Oh crap, I misunderstood previously, Thank you for clearing that up. I will do that today, Thanks

**Comment by ACR-Jeff** [comment]
Tested day and night the version posted above on 2 separate systems, Both with Debian 12 installed, Neither showing signs of crashes.

**Comment by absidue** [comment]
Okay so it sounds like the Electron upgrade should solve this issue.

**Comment by ACR-Jeff** [comment]
> Okay so it sounds like the Electron upgrade should solve this issue.

It appears so on my end, I installed and tested the version posted above as a fix, For several days without an issue, I then followed through with the newest release, Same no more issues of crashes
