### ISSUE TITLE
video is not playing

### ISSUE THREAD

**Issue by kensully** [FreeTubeApp/FreeTube#41]
Hi, thank you for developing this application. I am on Ubuntu 16.04 platform. I cloned the repo and did `npm i`, finally launched the application with `npm start`, I also entered `youtube api` it lists the video thumbnails when I type in the search box but it fails to play videos when I click the thumbnail, I get a blank window where it should be playing the video.

**Comment by PrestonN** [comment]
Hey there.  I'll have to look at this later tonight.  In the meantime, could you try cloning down the development branch and see if that works better?  It should be more updated than the master branch right now.  If you're still having issues, I will look into this when I'm available.

**Comment by kensully** [comment]
@PrestonN thank you for responding. I just tried the `development` branch`, the result is the same, blank video page.

**Comment by kensully** [comment]
I forgot to add, I am using multiarch enabled disribution, it's a 32 bit installation but using 64 bit kernel. By the way, I just tested released package `electron-v2.0.0-beta.3-linux-x64` it works well.

**Comment by 5had0w5talk3r** [comment]
Can confirm the bug on Arch Linux. Everything seems work fine, except the video page which loads nothing.

**Comment by PrestonN** [comment]
Hey I've figure out the issue.  My master branch is a little wonky right now because of some code refactoring.  When I do a merge to master during (hopefully) this weekend's release, then the issue will be fixed.  In the mean time, please use the tar file included in the release section like you've already mentioned.  If you are still keen on running FreeTube using the command line, here's some quick instructions that should at least get you up and running.

While in the FreeTube directory:

Switch to the development branch
```
git checkout development
```

Pull down the latest changes just in case.
```
git pull
```

Install Dependencies
```
npm install
```

Start FreeTube
```
npm start
```

Let me know if this works for you.  If it does, please close the issue.  Thanks.

**Comment by kensully** [comment]
@PrestonN I just tested `development` branch, video is still not playing.

**Comment by PrestonN** [comment]
@kensully could you open up the Chrome Dev tools (Press Alt to open the menu) and let me know what the error in the console says?  If the error has something to do with toggleLoading() not being a function, then I do not believe you are on the development branch.  I was only able to encounter the error when I try to run on the master branch.

**Comment by kensully** [comment]
@PrestonN you are right about it, I get 

          player.js? [sm]:33 Uncaught ReferenceError: toggleLoading is not defined
          at playVideo (player.js? [sm]:33)
          at HTMLImageElement.onclick (index.html:1)
but I did switch to `development` branch. Anyway I try again and let you know.

**Comment by kensully** [comment]
I am sorry for bothering you, I successfully cloned the ` development` branch and  I launched the application but  this time I encounter another error: `There was an issue calling youtube-dl`

       Uncaught TypeError: Cannot read property 'player' of undefined
    at Object.success (file:///home/**/NewDesktop/Mart-2018/FreeTube/src/js/videos.js:257:36)
    at fire (/home/**/NewDesktop/Mart-2018/FreeTube/node_modules/jquery/dist/jquery.js:3268:31)
    at Object.fireWith [as resolveWith] (/home/**/NewDesktop/Mart-2018/FreeTube/node_modules/jquery/dist/jquery.js:3398:7)
    at done (/home/**/NewDesktop/Mart-2018/FreeTube/node_modules/jquery/dist/jquery.js:9305:14)
    at XMLHttpRequest.<anonymous> (/home/**/NewDesktop/Mart-2018/FreeTube/node_modules/jquery/dist/jquery.js:9548:9)
      youtubeApi.js:38 Error: Command failed: /home/**/NewDesktop/Mart-2018/FreeTube/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best --all-subs --geo-bypass http://www.youtube.com/watch?v=[object Object]
      WARNING: Falling back on generic information extractor.
      ERROR: Unsupported URL: https://www.youtube.com/


      at ChildProcess.exithandler (child_process.js:282:12)
      at emitTwo (events.js:125:13)
      at ChildProcess.emit (events.js:213:7)
      at maybeClose (internal/child_process.js:921:16)
      at Socket.stream.socket.on (internal/child_process.js:348:11)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)
      at Pipe._handle.close [as _onclose] (net.js:549:12)
      events.js:76 16
      events.js:76 17
      events.js:76 73

**Comment by PrestonN** [comment]
Hey there. I don't know if you're still around, but does the latest update fix this issue?
