### ISSUE TITLE
[Feature Request]: Keyboard shortcut to toggle autoplay

### ISSUE THREAD

**Issue by shadycloud** [FreeTubeApp/FreeTube#4103]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

A keyboard shortcut for the "Autoplay" toggle switch/slide button. 

This feature would be a nice work around for  #1181 and another option to #2138 and https://docs.freetubeapp.io/usage/keyboard-shortcuts/  

"At this moment the Autoplay mode button is not part of the media player. Lets say for example u are in fullscreen but u want autoplay mode enabled then u need to do the following things:

Go out of fullscreen > enable autoplay > go into fullscreen.

That doesn't make allot of sense to me. This is also the case when u are in Fullwindow mode."

### Proposed Solution

1) "A" or "a"  being the keyboard shortcut for the "Autoplay" toggle switch/slide button.

2) Some sort of label to indicate when Auto Play is on/off in the UI.  

### Alternatives Considered

Perhaps using a different char. No label... idk...

### Issue Labels

ease of use improvement, improvement to existing feature, new keyboard shortcut

### Additional Information

https://docs.freetubeapp.io/usage/keyboard-shortcuts/  
https://github.com/FreeTubeApp/FreeTube/issues/2138
https://github.com/FreeTubeApp/FreeTube/issues/1181

**Comment by Sohailsaifi** [comment]
I want to work on this issue. Can you please assign it to me?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Done!

**Comment by shadycloud** [comment]
Please show me how  this is accomplished. I was trying some dumb stuff last night... ```    return
      }

      if (this.player !== null) {
        switch (event.key) {
          case ' ':
          case 'Spacebar': // older browsers might return spacebar instead of a space character
            // Toggle Play/Pause
            event.preventDefault()
            this.togglePlayPause()
            break
          case 'a':
          case 'A':
            // Toggle Auto Play
            event.preventDefault()
            this.toggleAutoPlay()
            break
          case 'J':
          case 'j':
            // Rewind by 2x the time-skip interval (in seconds)
            event.preventDefault()
            this.changeDurationBySeconds(-this.defaultSkipInterval * this.player.playbackRate() * 2)
            break
```

**Comment by shadycloud** [comment]
I've also switched ```toggleAutoPlay``` put with ```autoplayVideos```

**Comment by Sohailsaifi** [comment]
You mentioned that we have to get out of the fullscreen to enable/disable autoplay but I can't see the autoplay button even when I'm not in full screen. The only place I found the autoplay option is inside the settings tab. Can you please tell me if I'm missing something?

**Comment by jasonhenriquez** [comment]
See top right of the image below:

![Screenshot_20231009_164143](https://github.com/FreeTubeApp/FreeTube/assets/84899178/dede4a66-2584-4128-be66-fc51c7e3eac9)

Make sure that "Hide Recommended Videos" under Distraction Free Settings is disabled. Note that this is related to the `playNextVideo` variable, not `autoplayVideos` or `autoplayPlaylists`, which is admittedly a bit confusing of a naming schema.

**Comment by Hector118** [comment]
Can you please assign me to this issue?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
[This issue will be closed](https://github.com/FreeTubeApp/FreeTube/pull/4227#issuecomment-1817706760)
