### ISSUE TITLE
[Feature Request]: Confirmation to remove subscriptions

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#4109]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

It is very easy to accidentally remove (or add) a subscription on various pages. While typically this shouldn't be noteworthy (except for the most clumsy or accessibility-challenged), it's still something that can happen to anyone, and it's a problem if it happens inadvertently.

### Proposed Solution

Add an option to ask for confirmation to remove subscriptions.

### Alternatives Considered

Maybe make it the default?

### Issue Labels

ease of use improvement, new optional setting

### Additional Information

I know there is currently an option in parental controls to block it completely, but having to go back and forth to turn it off and on quite a bit more tedious.

**Comment by msagr** [comment]
Hey @zipfile6209  its really an amazing feature, will try to implement it.
