### ISSUE TITLE
[Feature Request] Import/Export favorites

### ISSUE THREAD

**Issue by TheFrenchGhosty** [FreeTubeApp/FreeTube#411]
Right now the only way to import the favorites is to add the content of the file the user want  to the existing file (or just replace the existing file).

It would be nice to have a more efficient way to do it (similar to subscriptions).

**Comment by jordanbates** [comment]
Agreed this would be great. 

@TheFrenchGhosty could you explain your current method of achieving this? I'm not following

**Comment by TheFrenchGhosty** [comment]
Go to the freetube configuration folder

Find the favorite file

Open it

Copy it's content to the existing file in your other computer.

**Comment by jordanbates** [comment]
Oh interesting, I don't see any such file or folder. Closest thing is db files and the like.

**Comment by TheFrenchGhosty** [comment]
The db files are text, they can be opened as text files.

**Comment by ways** [comment]
Which file are favorites stored in?
