### ISSUE TITLE
[Bug]: Videos run very slowly, there is a lack of synchrony, a very low frame rate

### ISSUE THREAD

**Issue by Mkcein** [FreeTubeApp/FreeTube#4110]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When opening any video the problem occurs, I tried using the LOCAL API and also the INVIDIOUS API and none of them make a difference, I also tried to use LEGACY mode and DASH mode there is no change in the problem, I tried with countless videos, this problem has been going on since the first installation for days, I use updated window 10, my internet link is 700MB on normal youtube everything goes well, on the INVIDIOUS website everything also flows normally. Only in the FREETUBE app does the problem occur.

### Expected Behavior

I want the video to run at a normal frame rate equal to the INVIDIOUS website or even on youtube. There is a lot of slowness in the video while the audio comes out normally, it seems that the video is at 0.5x

### Issue Labels

API issue

### FreeTube Version

v0.19.0 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Daryl76679** [comment]
I haven't been able to get any videos to play at all since the update

**Comment by absidue** [comment]
Do you have the setting enabled to proxy videos through Invidious?

**Comment by Daryl76679** [comment]
Yes, but only as my fallback. I have the local api as my preferred choices, and yewtu.be as my backup.

**Comment by absidue** [comment]
yewtu.be has the API disabled so it cannot be used in FreeTube.

The proxy videos through Invidious is a separate setting in the player setting section, if enabled it applies regardless of the preferred API backend setting.

Do you have that setting enabled?

**Comment by Mkcein** [comment]
> Do you have the setting enabled to proxy videos through Invidious?

It is necessary to activate PROXY VIDEOS by INVIDIOUS ? In my case there is an option within the settings that has to do with PROXY that is turned off, as I do to activate this proxy that you mentioned ?

The option that is turned off is ENABLE TOR / PROXY

**Comment by Mkcein** [comment]
> yewtu.be has the API disabled so it cannot be used in FreeTube.
> 
> The proxy videos through Invidious is a separate setting in the player setting section, if enabled it applies regardless of the preferred API backend setting.
> 
> Do you have that setting enabled?

You can send a print to see how you configured that part ?

**Comment by absidue** [comment]
@Mkcein Can you please if it works with these settings:
- Proxy Videos Through Invidious: **OFF**
- Preferred API Backend: **Local API**

**Comment by Mkcein** [comment]
> @Mkcein Can you please if it works with these settings:
> 
> * Proxy Videos Through Invidious: **OFF**
> * Preferred API Backend: **Local API**

I tested several combinations, local API, INVIDIOUS API, with PROXY on and off, tested other instances, to tell you the truth I came to test many alternatives for 3 days in a row, None of them really had an effect. I'm about to stop using FreeTube and use another PIPED system, it's a shame because I really liked the possibilities of FREETUBE, mainly because of the agility in updating their FEED.

**Comment by absidue** [comment]
Proxy and proxy videos through invidious are two unrelated settings.

I need to know if the specific combination of local API + Proxy Videos Through Invidious: OFF works, because currently Invidious instances are getting IP blocked and throttled by YouTube, so if you have the preferred backend set to Invidious or Proxy Videos Through Invidious: ON, then you will have the playback issues you are describing.

**Comment by Daryl76679** [comment]
> Do you have that setting enabled?

@absidue, no I do not.

**Comment by absidue** [comment]
@Daryl76679 Are you using the local or Invidious API? If you are using the Invidious API, which instance are you using?

**Comment by Daryl76679** [comment]
I am using the local by default

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Did v0.20.0 solve your issues?
