### ISSUE TITLE
[Feature Request]: Search feature for comments

### ISSUE THREAD

**Issue by XxTriviumxX** [FreeTubeApp/FreeTube#4111]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I'd like to search for comments without having to use ctrl+F in piped/invidious in my browser.

### Proposed Solution

Put a search field near the comments

### Alternatives Considered

being able to use ctrl+f like a web browser works too.

### Issue Labels

new feature

**Comment by XxTriviumxX** [comment]
sorry, i found another issue like mine after looking again.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1401
