### ISSUE TITLE
[Bug]: Subscribe/share/etc buttons invisible on videos that I'm watching.

### ISSUE THREAD

**Issue by PaperOrb** [FreeTubeApp/FreeTube#4113]
edit: looks like the solution was to switch invidious instance from https://onion.tube to some other instance and then restart freetube. It still seems like an freetube bug since freetube's GUI elements shouldn't be impacted by what's happening with the local API.

### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

The subscribe, share, bookmark, and etc buttons are no longer visible beneath the video when watching.

### Expected Behavior

While watching a video, the subscribe, share, bookmark, and etc buttons should be visible directly underneath.

### Issue Labels

feature stopped working

### FreeTube Version

v0.19.0 Beta

### Operating System Version

Linux lite

### Installation Method

.AppImage

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.0 Beta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PaperOrb please try the latest nightly build

**Comment by MaxMaxMaxCh** [comment]
Same here! The nightly build works fine though

**Comment by PaperOrb** [comment]
> @PaperOrb please try the latest nightly build and report back if that solved it for u

Thanks, but I'm going to close this as I just realized this issue was actually posted already: https://github.com/FreeTubeApp/FreeTube/issues/4104
