### ISSUE TITLE
[Bug]:  subscribe button missing due to missing published date

### ISSUE THREAD

**Issue by PeterHagen** [FreeTubeApp/FreeTube#4115]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. open the following video: https://youtu.be/mvXFGikltPc
2. on play start the html container with the subscribe button is missing
3. on checking the developer console, the following error is shown:

```
renderer.js:formatted:32444 RangeError: Invalid time value
    at a.dateString (renderer.js:formatted:75065:24)
    at t.get (renderer.js:formatted:32594:37)
    at t.evaluate (renderer.js:formatted:32662:35)
    at a.dateString (renderer.js:formatted:33450:41)
    at a.<anonymous> (renderer.js:formatted:75197:67)
    at t._render (renderer.js:formatted:33756:27)
    at a.n (renderer.js:formatted:35290:33)
    at t.get (renderer.js:formatted:32594:37)
    at new t (renderer.js:formatted:32587:56)
    at t (renderer.js:formatted:35293:17)
```

4. This prevents the html container with the subscribe button to show up.

### Expected Behavior

The subscribe button should be visible

### Issue Labels

visual bug

### FreeTube Version

v.0.19.0

### Operating System Version

macOS 14.0 (23A344)

### Installation Method

other

### Primary API used

Local API

### Additional Information

The dateString function should validate if `this.published` has a value. In this case its `NaN`

<img width="612" alt="Screenshot 2023-10-08 at 12 50 31" src="https://github.com/FreeTubeApp/FreeTube/assets/12300899/5d487456-071f-4ed6-9ee9-d8394b9c521b">

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please try the latest nightly build and report back

**Comment by PeterHagen** [comment]
Yes, its works fine in nightly!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as this has been fixed in nightly!
