### ISSUE TITLE
[Bug]: Can't view any video on macOS

### ISSUE THREAD

**Issue by xiaolilo** [FreeTubeApp/FreeTube#4127]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Find a video
2. Click to play video 

### Expected Behavior

The video plays.

### Issue Labels

content not loading

### FreeTube Version

v.0.19.1beta

### Operating System Version

macOS Sonoma 14.1 beta 2

### Installation Method

.dmg

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

not sure. probably 0.17 or 18 (definitely not 0.19.0)

### Additional Information

Same things happens regardless of Proxy settings, API selection, or Invidious instance. Hasn't been working for a little while. 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by xiaolilo** [comment]
video screenshot (available 3 days): https://send.vis.ee/download/699760664ad86470/#GfCzbszMwckgZlmdJ727Kw

**Comment by absidue** [comment]
Do you have the "Proxy Videos Through Invidious" setting enabled in the "Player Settings"? (see screenshot)

![proxy-videos-through-invidious-setting](https://github.com/FreeTubeApp/FreeTube/assets/48293849/9b05843a-a46d-46a5-b326-9f7e650f83f1)

**Comment by xiaolilo** [comment]
Good point. That was activated indeed, and both local api and invidious api work when it's off. How come?

**Comment by absidue** [comment]
The proxy videos through Invidious setting overrides the API preference, so when it is enabled FreeTube will always stream videos through Invidious, when it is disabled, FreeTube will always stream videos directly from YouTube.

I'm guessing that the Invidious instance you are using got IP blocked by YouTube for video streaming.

**Comment by xiaolilo** [comment]
Thanks. But then shouldn't the videos also break when using the invidious api?

**Comment by absidue** [comment]
No, because by default the Invidious API returns YouTube streaming links, it only gives you proxied streaming links if you specifically ask for them.

**Comment by xiaolilo** [comment]
Does it matter if I changed the api?
