### ISSUE TITLE
[Feature Request]: Allow subtitles for two languages at the same time

### ISSUE THREAD

**Issue by calhix** [FreeTubeApp/FreeTube#4133]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

You can only have subtitles for one language at a time.

### Proposed Solution

Allow subtitles for two different languages at the same time. You could have one language at the top of the video and one on the bottom. You could also just have one language right on top of the other but I prefer the first option. This is super useful when learning languages or if you are watching a video with a spouse/friend that speaks a different language then the one in the video. Example: video is in Spanish, you don't know Spanish but English is available, friend/spouse doesn't know either language well but speaks French, luckily French subtitles are available for the video, now you can watch the video together.

### Alternatives Considered

None

### Issue Labels

new feature

**Comment by absidue** [comment]
As far as I know this is not supported by both the current video player and the one we will be switching to in the future, so it won't be possible for us to do, unless they get support.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing because of the reason stated above
