### ISSUE TITLE
Freetube extension/Call from command line

### ISSUE THREAD

**Issue by DocKDE** [FreeTubeApp/FreeTube#414]
Dear all,
I just tried the freetube extension for firefox. I have freetube installed on Arch via the AUR package so maybe it's related to that. Now when I click on a YT link my browser tries to call "freetube://https://www.youtube.com/watch[somevideo]". I tried the same thing on a different machine running Fedora which worked fine. 
What I'm wondering is what the extension actually tries to do. Does it try to run a freetube command from a terminal directly calling the video? I tried this but the command doesn't work that way it seems. Is there a way to call freetube from command line with a specific YT link? This would actually help me more than the actual extension I just can't figure out how.

Any clarifications would be appreciated.

**Comment by PrestonN** [comment]
This essentially calls the CLI while passing the YouTube video as an argument.  FreeTube then takes that video and attempts to play it if an ID can be found.  I don't manage the Arch packages so I don't know if they enable to protocol properly.  Flatpak and Deb files do however.  If the protocol isn't set properly then the extension / FreeTube will not work properly.
