### ISSUE TITLE
[Bug]: API fetch fails for Most Poppular 

### ISSUE THREAD

**Issue by KSterner2** [FreeTubeApp/FreeTube#4140]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When clicking on the Most Popular sidebar button, API failed to fetch.  
<img width="1398" alt="Screenshot 2023-10-12 at 1 16 43 PM" src="https://github.com/FreeTubeApp/FreeTube/assets/95242846/11b85cb2-0d5a-47ff-8939-d8e1ac5ed080">

### Expected Behavior

Display popular videos.  

### Issue Labels

API issue

### FreeTube Version

0.19.1

### Operating System Version

macOS

### Installation Method

.dmg

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please send a screenshot of your Settings -> Genral settings

**Comment by Adecom16** [comment]
Can you assign this to me and receive an instant PR

**Comment by Adecom16** [comment]
Can you assign this to me and receive an instant PR

**Comment by KSterner2** [comment]
<img width="774" alt="Screenshot 2023-10-15 at 11 07 58 AM" src="https://github.com/FreeTubeApp/FreeTube/assets/95242846/9a59289f-0a57-42af-a0da-98b410399269">

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I notice that u dont have a default invidious instance set. Can u remember on what instance this error occurred?

**Comment by KSterner2** [comment]
Yes its anytime I try to click on the side bar column and load up "most popular" videos

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is it only the failed to fetch error or do you also get other errors?

**Comment by KSterner2** [comment]
As far as I can tell it is the only the failed to fetch error.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could u do the following:

Open FT -> Open console (CTRL+SHIFT+i) -> Go to Most Popular page -> Make a screenshot of the errors that popup in the console

**Comment by KSterner2** [comment]
Okay closing when I closed then reopened FT I was able to get the Most Popular page to work this time but here's a screen shot of the warnings I get.  In the mean time I'll try again to see if I can get the failed catching errors.  

<img width="1402" alt="Screenshot 2023-10-15 at 12 01 55 PM" src="https://github.com/FreeTubeApp/FreeTube/assets/95242846/9a7881d4-70a5-4b42-99b6-cc71ff3379b6">

**Comment by KSterner2** [comment]
Heres the Failed catching errors:
<img width="1405" alt="Screenshot 2023-10-15 at 12 04 46 PM" src="https://github.com/FreeTubeApp/FreeTube/assets/95242846/361c5297-b8db-4087-ae59-bbf665526f65">

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
To clarify on the error in console: The closed stream error u see in the red is expected as this instance does not have a most popular page https://yt.artemislena.eu/

**Comment by KSterner2** [comment]
Oh so is that why it's working 50% of the time?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Im not 100% sure about that because i didnt see the failed to fetch error and closed stream error together

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could u try one of these instances they should work because they have most popular enabled:

- https://yt.oelrichsgarcia.de/
- https://inv.us.projectsegfau.lt/
- https://invidious.private.coffee/
- https://invidious.no-logs.com/
- https://onion.tube/
- https://inv.tux.pizza/

**Comment by KSterner2** [comment]
Okay I've tried a couple of those instances and it works.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing this issue, if this comes back feel free to reach out

**Comment by sutex** [comment]
API error -  So I'm unable to play Live news stream on You tube.
https://www.youtube.com/watch?v=vOTiJkg1voo
