### ISSUE TITLE
[Bug]: Import Playlists does not work

### ISSUE THREAD

**Issue by krasimirkrustev** [FreeTubeApp/FreeTube#4143]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Freetube expects to import playlist files with ".db" file extension, but YouTube exports its playlist as ".csv" files.

### Expected Behavior

Freetube expects to import playlist files with ".db" file extension, but YouTube exports its playlist as ".csv" files.

### Issue Labels

feature stopped working

### FreeTube Version

v0.19.1, 89686ad

### Operating System Version

Windows 10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Playlist importing from YT is not implemented into FT yet. U will get a .db file when u export FT playlists so u can import it into FT again at some point 

There is an open for supporting the import of YT playlists
https://github.com/FreeTubeApp/FreeTube/issues/1016

**Comment by krasimirkrustev** [comment]
Taken directly from FreeTube's website usage guide. Read the note section! It says viewing and playing playlists directly from YouTube is already supported.

### Playlists
A planned feature for the future of FreeTube is the ability to create playlists. Once this has been finished, we will add more information to this page to explain more about how the feature works.

**Note: This feature is different from being able to view and play playlists directly from YouTube. This functionality is already supported within FreeTube**

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I think u should read again that is not talking about local user created playlists but viewing and playing playlists from creators

**Comment by tbergeron** [comment]
That'd be amazing, the csv file only contains video IDs and dates... wouldn't be that hard to implement.
That way we'd be able to import our watch history and any playlists.

**Comment by y0nei** [comment]
Whats the status of this? Importing playlists from `.csv` files is still not possible.

**Comment by HanM23** [comment]
Is there any plan to import YT playlist ?
Thank you
