### ISSUE TITLE
[Feature Request]: Save Window Position on exit

### ISSUE THREAD

**Issue by Migs3** [FreeTubeApp/FreeTube#4148]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

With other applications, when you close the application, it "stores" where it was located on your desktop (whether that be full screen, snapped on the right/left, on monitor 1 or 3, etc.) and then when you open the application the next time, it will open exactly as you have left it.

Currently, regardless of where I leave the window, it just opens on my main monitor screen in a windowed mode.

I have a 4 monitor configuration and so I have things "where they belong" and this seems like a pretty simple add to simply remember where it's at.

### Proposed Solution

Add the ability to retain the window position on the desktop and "attempt" to redraw the window at that same location the next time you open it.

If you can't redraw at the same location (monitor is no longer connected, different resolution, etc.) then default to the main screen in windowed mode.

### Alternatives Considered

Not really any alternatives here, seems like a simple function of an application to remember where it was the last time it was used.

### Issue Labels

ease of use improvement

**Comment by absidue** [comment]
Hmm FreeTube already does that, interesting that it isn't working for you.

**Comment by Migs3** [comment]
I actually realized I'm an idiot.  I assumed windows would "gracefully" shut down FreeTube when it was told to Shut Down.  Well, that isn't the case, and FreeTube wasn't saving it's position simply because Windows didn't give it the proper time to do so.  After I closed just the app and re-opened, it recalled the correct position.  Sorry, I should have actually tested properly, closing this.

**Comment by Migs3** [comment]
In thinking about it, it might still be considered a bug anyway.  I think there are other apps that can remember their position when windows kills them when shutting down, so might still be a bug? I'll leave it closed at least, someone who knows better can re-open it, if they like.
