### ISSUE TITLE
[Bug]: Freetube App Stuck on a Full Screen (Windows)

### ISSUE THREAD

**Issue by nyanikoding** [FreeTubeApp/FreeTube#4149]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open Freetube App on Windows
2. The App is stuck on a full screen
3. Can't Minimize, restore, close the app

![image](https://github.com/FreeTubeApp/FreeTube/assets/104826783/bbb87e82-cc29-4f20-8cde-724f966a578a)

Even when pressing alt, there is no restore button
![image](https://github.com/FreeTubeApp/FreeTube/assets/104826783/2a696dbf-402c-4deb-9355-1e0569369218)

### Expected Behavior

Being able to restore, minimize, and close the freetube app just like any other windows app

### Issue Labels

accessibility issue, usability issue

### FreeTube Version

v0.19.1 Beta

### Operating System Version

windows 10

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.0

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @nyanikoding  can u try pressing F11

**Comment by gittergesicht** [comment]
I had the same issue. Pressing F11 works for me.
THxs  efb4f5ff-1298-471a-8973-3d47447115dc ;)

**Comment by nyanikoding** [comment]
Bruh it's that easy 💀

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3220
Thanks for confirming!
