### ISSUE TITLE
[Bug]: Channel Name, channel buttons all disappeared under a video

### ISSUE THREAD

**Issue by BarbzYHOOL** [FreeTubeApp/FreeTube#4158]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When I view a video, there is no more channel name, Subscribe or Favourite button.
All the part between the chapters and the videos have disappeared for like 1 or 2 weeks already.

### Expected Behavior

Like before, working fine

### Issue Labels

feature stopped working, usability issue

### FreeTube Version

v0.19beta

### Operating System Version

Linux Mint 20

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18

### Additional Information

I don't know which keywords to search for the issue, didn't find with the ones I typed

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by BarbzYHOOL** [comment]
hmm i feel like it's like this https://github.com/FreeTubeApp/FreeTube/issues/4104

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
install 0.19.1

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4113 #4104
