### ISSUE TITLE
[Feature Request] Ability to download YouTube Videos

### ISSUE THREAD

**Issue by creepertron95** [FreeTubeApp/FreeTube#416]
I tried FreeTube and I like using it. Would It be possible to implement downloading of YouTube Videos from the FreeTube app itself, including a download manager? 
Something like youtube-dl, https://ytdl-org.github.io/youtube-dl/index.html.

**Comment by Archive5** [comment]
Add custom quality download options.
<img src="https://user-images.githubusercontent.com/63988538/82373296-3e8f9300-99d2-11ea-9b57-a763f7be162c.png" alt="drawing" width="500"/>

Fast downloads similar IDM

**Comment by Archive5** [comment]
#27

**Comment by DesertStars** [comment]
Is there any reason to why this was closed?

**Comment by postacik** [comment]
This would be a tremendous feature. Why did you close the enhancement request?

**Comment by pqhf5kd** [comment]
Also looking for this feature. I have terrible internet at home and would like the option to download several videos while at another location to watch later. Videos could be removed x hours after being watched?
