### ISSUE TITLE
[Bug]: Symlinked database files seem not to work

### ISSUE THREAD

**Issue by wojtek1171** [FreeTubeApp/FreeTube#4161]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Close FreeTube
2. cd to ~/.var/app/io.freetubeapp.FreeTube/config/FreeTube
3. Move profiles.db (or any other db file) to another location
4. Create symlink (ln -s ~/new/location/profiles.db profiles.db)
5. Check if symlink was created correctly (ls -ln)
6. Open FreeTube
   - Only grey background of the app is visible
   - Console (F12) shows no errors
   - Close the app
   - Open it again
   - App crashes with:
![Screenshot](https://github.com/FreeTubeApp/FreeTube/assets/19674576/7089d89a-05be-434a-a41e-c3ef9d68f19a)

 

### Expected Behavior

The app reads the symlinked files properly.

### Issue Labels

feature stopped working

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Pop_OS! 22.04 LTS

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@curbengh CamilleHbp pinging u guys because i know more than i do on this. Is this a bug or is their maybe being misconfigured?

**Comment by Lcchy** [comment]
I am experiencing the same error when trying to symlink the profiles.db
(FEdora 38 FreeTube flatpak v0.19.1)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
If u follow this does it make any change anything for u?

1. Close FreeTube
2. Move your database files to another location on the disk
3. Create symlinks at the original location pointing to the new location
4. Open FreeTube and check that your settings, profiles, history, playlists are still there

**Comment by Lcchy** [comment]
These are the exact steps I have taken. In my case the GUI does not start and I have these error messages:

```
(node:2) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/lcchy/.var/app/io.freetubeapp.FreeTube/config/FreeTube/profiles.db'
(Use `freetube --trace-warnings ...` to show where the warning was created)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/lcchy/.var/app/io.freetubeapp.FreeTube/config/FreeTube/history.db'
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:2) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/lcchy/.var/app/io.freetubeapp.FreeTube/config/FreeTube/playlists.db'
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:2) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/lcchy/.var/app/io.freetubeapp.FreeTube/config/FreeTube/settings.db'
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

**Comment by Lcchy** [comment]
Ah I just found out why! 

The FreeTube flatpak didn't have the permission to access the location where the symlink destination was stored.

Giving the permission solved the issue for me.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@wojtek1171 could u try the same as @Lcchy

**Comment by wojtek1171** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Yes, it works now. I should have check that in the first place. Thanks for help @Lcchy
