### ISSUE TITLE
[Feature Request]: Add subscription categories / grouping of subscriptions

### ISSUE THREAD

**Issue by Julienist** [FreeTubeApp/FreeTube#4163]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

(Why to add the feature)
Normally I just use YouTube in the Firefox browser, but was getting annoyed by the anti-adblocker, so switched easily to FreeTube. In Firefox, I had several extensions which were making my experience better. One of them was pocket tube subscription manager, which allowed me to categorize/group my subscriptions (even though they aren't registered through YouTube).

### Proposed Solution

(just straight to the point)
It would be nice to have the function of categorizing/grouping my subs in folders like: "music", "tech", "minecraft", etc. 

### Alternatives Considered

(Sort a like feature request, but not exact)
Feature request #1052 was sort of discussing this, as in making playlists for videos (but then you have to click individual videos (which is time-wasting)), by categorizing subs, you can categorize by artists you like in bulk.

It's also maybe a good thing to be able to import subscriptions from the pockettube subscription manager extension. (this would be another feature request), but is a bit relate-able to this.

### Issue Labels

ease of use improvement, new feature, visual improvement

**Comment by absidue** [comment]
The existing profiles feature is probably what you are looking for: https://docs.freetubeapp.io/usage/profiles/

**Comment by Julienist** [comment]
Totally correct. my bad
