### ISSUE TITLE
[Bug]: Translation on weblate locked

### ISSUE THREAD

**Issue by Mr-Bajs** [FreeTubeApp/FreeTube#4172]
Translation in Weblate are auto locked due to an error

The error says.
 'could not find expected \':\'   in "<unicode string>", line 18, column 1:\n    Tooltips: {}\n    ^ (line: 18)'

And refers to the file:
static/locales/be.yaml

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Thanks for reporting!

For future reference report weblate stuff over at https://github.com/FreeTubeApp/FreeTube/discussions/3619
