### ISSUE TITLE
[Bug]: Copy Link with Invidious doesn't include https:// in the URL, affects embedding on other services

### ISSUE THREAD

**Issue by hjc25** [FreeTubeApp/FreeTube#4175]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click any video
2. Click share button
3. Copy Link with YouTube
4. Confirm URL contains https:// in front of URL
5. Repeat Step 2 and 3, but include use Invidious
6. Confirm URL doesn't contain https:// in front of URL

### Expected Behavior

This affects ability to immediate copy and paste into messaging apps (Messenger, Discord), which then automatically embed the link in the chat with a preview or embedded player. You manually have to include the https:// in order for it to correctly embed in other services if you are sharing content to others This adds unneeded friction to using this functionality of Freetube.

### Issue Labels

text/string issue, usability issue

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 10 Pro 22H2 OS Build 19045.3570 Windows Feature Experience Pack 1000.19052.1000.0

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

N/A

### Additional Information

For example, when I copy link to clipboard, here is what it currently looks like

YouTube: https://youtu.be/CkZyZFa5qO0
Invidious: vid.puffyan.us/watch?v=CkZyZFa5qO0

All I'm asking for is that https:// to be included in front of the Invidious link by default.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Working fine for me, sounds like you may have forgot to add https:// to the instance url when you set it up in the FreeTube settings.

Please send a screenshot of the general settings section.

**Comment by hjc25** [comment]
> Working fine for me, sounds like you may have forgot to add https:// to the instance url when you set it up in the FreeTube settings.
> 
> Please send a screenshot of the general settings section.

Piss.

![image](https://github.com/FreeTubeApp/FreeTube/assets/28969068/71821c81-5eb7-496c-bb7c-c4973ec79351)

Made even funnier when you click into the textbox after the fact, it does include the https:// lmao

![image](https://github.com/FreeTubeApp/FreeTube/assets/28969068/f0bad44c-cb0f-401c-9494-aa76f2ef5195)

**Comment by absidue** [comment]
Yes that's auto-complete suggesting the correct one, because the correct one is in invidious' instance list.

**Comment by hjc25** [comment]
> Yes that's auto-complete suggesting the correct one, because the correct one is in invidious' instance list.

Well, don't I feel like a complete ass right now.
