### ISSUE TITLE
[Bug]: Screan Tearing

### ISSUE THREAD

**Issue by StrandedTimelord** [FreeTubeApp/FreeTube#4184]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When in full-screen mode in Freetube, the video player screen tears a lot and is quite jarring. I have tried setting vsync to fast as to test out if it would fix the issue, but it still persists.

### Expected Behavior

The video player should match the refresh rate of YouTube, which is 60 hertz.

### Issue Labels

usability issue, visual bug

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 10 home

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

None

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Try disabling any globally applied graphics card settings. If I remember correctly, in the past one of NVIDIA's global graphics settings resulted in issues too. I definitely think this is a graphics card setting issue, not something inside FreeTube that is the problem, as I'm using FreeTube on Windows 10 with an NVIDIA graphics card with no tearing.

The global NVIDIA settings that have caused issues in the past are:
- Multi-Frame Sampled AA (MFAA)
- Antialiasing - FXAA

https://github.com/FreeTubeApp/FreeTube/issues/2235#issuecomment-1133918031

**Comment by StrandedTimelord** [comment]
This seemed to have fixed the issue. Thanks.

**Comment by StrandedTimelord** [comment]
This seemed to have fixed the issue. Thanks.

**Comment by LinuxOnTheDesktop** [comment]
On AMD, on Windows, disabling both 'Anti-lag' and 'enhanced sync' seems to reduce screen-tearing within FreeTube. However, AMD's interface is bad; to disable those settings only for FreeTube, I had to find a way (it was hard) of adding FreeTube as, er, a 'game'.
