### ISSUE TITLE
[Feature Request]: Shortcut to add to favorites

### ISSUE THREAD

**Issue by BarbzYHOOL** [FreeTubeApp/FreeTube#4185]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I put videos in favorite all the time (sadly only one playlist available but eh...) and remove them too.
I'm glad we have different ways to do it but when you're viewing a video there should be a shortcut to quickly add or remove it with the confirmation showing up at the top/bottom.

### Proposed Solution

there should be a shortcut to quickly add or remove it with the confirmation showing up at the top/bottom

It could be S, Ctrl+S, Alt+S, Ctrl+F (but weird as it's usually Search), or Alt+F (F for favorite in those cases)

### Alternatives Considered

None, it is needed!

### Issue Labels

ease of use improvement, improvement to existing feature, new keyboard shortcut

### Additional Information

If possible, it should work even when fullscreen on the video

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Favorites going to be replaced by fully working playlist feature. In that implementation u cannot quickly do this. Therefore im closing this issue

**Comment by BarbzYHOOL** [comment]
> Favorites going to be replaced by fully working playlist feature. In that implementation u cannot quickly do this. Therefore im closing this issue

playlists are going to be implemented for years already and it never happened

and there wont be a default "favorite" playlist like on all sites ? if so, this could be useful (or "watch later")

**Comment by BarbzYHOOL** [comment]
Reopen this please
