### ISSUE TITLE
[Bug]: Search filters do not work

### ISSUE THREAD

**Issue by Moerusan** [FreeTubeApp/FreeTube#4187]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When searching for a video, it's not possible to set any search filters. No matter which settings I choose, the list of videos does not change.

### Expected Behavior

The list of videos is supposed to change after choosing search filters.

### Issue Labels

accessibility issue

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.1 Beta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Moerusan could u maybe screen record this

**Comment by absidue** [comment]
Did you click search after changing the filters (you can also set the filters before you press search the first time)?
