### ISSUE TITLE
[Bug]: Hdr video color conversion is incorrect

### ISSUE THREAD

**Issue by Pesc0** [FreeTubeApp/FreeTube#4188]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. play an HDR video
2. observe how green areas become fully saturated green

### Expected Behavior

correct colors as in any other player

### Issue Labels

visual bug

### FreeTube Version

0.19.1 beta

### Operating System Version

arch linux

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

-

### Additional Information

Green Flames:
![Screenshot from 2023-10-19 01-07-59](https://github.com/FreeTubeApp/FreeTube/assets/54720203/29473725-de5b-4e73-b789-b17a557120f6)

Poor frog has radioactive fluorescent hands
![Screenshot from 2023-10-19 01-11-44](https://github.com/FreeTubeApp/FreeTube/assets/54720203/79a38f28-32a0-47b0-ab67-62bd99233976)

Not related to the bug: thank you so much for this application. Now that youtube is enforcing their no-adblock policy this app has been a blessing. Except for this bug everything else has worked flawlessly so far.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Pesc0** [comment]
Not stale

**Comment by Pesc0** [comment]
Omfg not stale

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Pesc0 Please go to the YT website in a Chromium browser and report back how the colors look like. This way we can try to isolate the issue some more.

**Comment by Pesc0** [comment]
Looks fine in chromium - latest version on arch @efb4f5ff-1298-471a-8973-3d47447115dc

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Do you still face this issue in v0.20.0?
