### ISSUE TITLE
Unable to load any channel or subscription

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#419]
Hello,

I can't load any subscription, it says «Unable to load [always the same channel]» then doesn't event try to load the others. When i delete the said channel, it does exactly the same with another random channel. The instance set in parameters is working and even finds the channels that freetube is unable to load.

**Comment by esotericDisciple** [comment]
It seems the app can't load anything at the moment

**Comment by morfikov** [comment]
I have the same issue.

**Comment by esotericDisciple** [comment]
Managed to fix it with changing the "Current Invidious Instance (Defaults to https://invidio.us)" Setting to something other than the default instance ( https://github.com/omarroth/invidious/wiki/Invidious-Instances )... invidio.us has a message caliming the service is unavailable...

**Comment by morfikov** [comment]
Yes, this fixed the issue.

**Comment by linuxgirl22** [comment]
Same unable to load any videos ... happened a couple of days ago ... changed invidious instance to the one recommended by another user in Riot general chat, and that worked, but now has broken today.

**Comment by MKs2w7cBxTRP3e2ivnYBddxc** [comment]
Still an ongoing issue for me, and has been for 3+ months. I believe the last time I posted about it, I was told to copy my settings.db and history.db from ~/.config/Freetube to my desktop, export my subscriptions, close freetube, delete ~/.config/Freetube, run freetube again so it generates the folder, and then import the subscriptions back in, and then copy paste the other 2 files back into the new ~/.config/Freetube. This isn't working whatsoever this time around.

I'm running on whonix fyi and have to use ./freetube --no-sandbox to launch freetube.

**Comment by stemy2** [comment]
It works now.
