### ISSUE TITLE
[Bug]: Lag during scroll when playing 1080p60 videos

### ISSUE THREAD

**Issue by infinity099** [FreeTubeApp/FreeTube#4196]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When playing a video under 1080p60 quality, the client lags. Does not happen with non-60 fps videos. 

### Expected Behavior

Laggy scroll during video playback under 1080p60

### Issue Labels

usability issue

### FreeTube Version

0.19.1 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please inlcude 2 screenrecordings:

1. a video that doesn't support 60fps
2. a video that does support 60fps

**Comment by infinity099** [comment]
> Please include 2 screen recordings:
> 
> 1. a video that doesn't support 60fps
> 2. a video that does support 60fps

I recorded both instances in the video below.

https://github.com/FreeTubeApp/FreeTube/assets/76820039/b21fef4b-0a8b-4a46-98ec-940a887d6de2

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I followed the video but i cant reproduce this on my side

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@infinity099 try updating your graphics driver

**Comment by infinity099** [comment]
What GPU do you have? I have a GTX 3060.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
My GPU doesnt matter in this instance. We had similar cases like yours and updating the GPU drivers always fixed the issue

**Comment by infinity099** [comment]
> My GPU doesnt matter in this instance. We had similar cases like yours and updating the GPU drivers always fixed the issue

I tried updating the drivers and it still looks laggy.

**Comment by infinity099** [comment]
> My GPU doesnt matter in this instance. We had similar cases like yours and updating the GPU drivers always fixed the issue

I tried setting my refresh rate from 75 hz from 60 hz and it looks better now. Idk how that works but the laggy look is gone.

**Comment by absidue** [comment]
@infinity099 in the NVIDIA settings make sure that GSYNC is configured to only trigger for full screen windows, not for windowed windows. Sounds like the problem could be that it keeps switching between 60hz for the video and 75hz for the scrolling.
