### ISSUE TITLE
[Bug]: Live tab videos sorting randomly and incorrectly

### ISSUE THREAD

**Issue by ACR-Jeff** [FreeTubeApp/FreeTube#4197]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1 Subscriptions Live Tab
2 Clicking the Refresh Button
3 Videos are showing as newest with a more recent published time than the real published time on channels.
4 Going to the channel shows a different published time on said videos, Hours earlier then what's in Live tab has shown.
5 Which the above prevents proper sorting in Live tab.

### Expected Behavior

Proper published time on the videos to sort them properly: Newest first

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Debian 12 Bookworm

### Installation Method

Portable

### Primary API used

Local API

### Additional Information

Removing app config files, Allowing FT to generate new config back to a fresh install state, Importing subscriptions only, Resorts to the same behavior above.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can u include a screenshot

**Comment by ACR-Jeff** [comment]
> Can u include a screenshot

Surely I can :)
First screen shot is of live tab, Second is of the channel with a published live video, Two different published times.

![FT1](https://github.com/FreeTubeApp/FreeTube/assets/61212551/3d9355c2-246c-4d14-bef3-33fb888a11eb)
![FT2](https://github.com/FreeTubeApp/FreeTube/assets/61212551/b0fc8a8a-1ae6-47a5-8200-b1318879cf97)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@ACR-Jeff in the case of bravo media i cant seem to reproduce this. Both are showing 13hours ago on my side. Can u maybe try to close the program and open it fresh and check again

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Note: There is a known bug when RSS is forced or enbaled that upcoming videos are displayed wrong

https://github.com/FreeTubeApp/FreeTube/issues/3356

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Oh wait i enabled RSS and i can reproduce this. But i dont think its the same issue because this video is clearly not upcoming

**Comment by ACR-Jeff** [comment]
> Note: There is a known bug when RSS is forced or enabled that upcoming videos are displayed wrong
> 
> #3356

Oh Ok I was unaware of this bug, I am going to assume it's related to RSS, I reset FT to a fresh state again, Subscribed to the known channels with said videos producing this issue, Checked without RSS enabled All was good and normal, Then Enabled RSS, Refreshing the Live tab produced the issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
So i check with a random RSS feed app if this is a FT issue and its not.
https://rss.app/feed/IGmJo0llEvpbNnhq as you can see it displays 2h ago

Still investigating if we can do something about this.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@ACR-Jeff Unfortunately there is nothing we can do about this. YT is just behaving in weird ways.
