### ISSUE TITLE
Hide "Recommendations"

### ISSUE THREAD

**Issue by dimqua** [FreeTubeApp/FreeTube#42]
I think it would be useful to have an option to hide recommended videos.

**Comment by PrestonN** [comment]
Seems simple enough.  I can add in a quick toggle before the next release.

**Comment by 132ikl** [comment]
Any ETA on this?

**Comment by PrestonN** [comment]
This will likely be included with a new "Distraction Free" mode as explained in #209.  I will be included in 0.6.0 but I do not have an ETA for it at this time.  This issue will be closed once it has been implemented.

**Comment by PrestonN** [comment]
Closing as this has been implemented and will be included in the next release.

**Comment by CodingMadness** [comment]
@PrestonN can you maybe expand this feature by allowing to hide the "Up Next" section, on the right-hand side of FreeTube? 

This one I speak of:


![grafik](https://github.com/user-attachments/assets/dd8edf97-a560-4991-ba40-00006c362a07)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@CodingMadness see, `Hide Recommended Videos` under the `Watch page` section in `Distraction Free Settings`

**Comment by CodingMadness** [comment]
> @CodingMadness see, `Hide Recommended Videos` under the `Watch page` section in `Distraction Free Settings`

Now IT would BE extremly awesome to BE able to See Videos from subscriptions AS "recommended Videos"

**Comment by mugwhump** [comment]
> Now IT would BE extremly awesome to BE able to See Videos from subscriptions AS "recommended Videos"

YES! That would be amazing! Death to the algorithm!
