### ISSUE TITLE
Import Subscription dont work(electron 7.0.1)

### ISSUE THREAD

**Issue by d43m0nhLInt3r** [FreeTubeApp/FreeTube#421]
I upgraded electron with this command: `npm i -D electron@latest` and build it for Linux|x64|pacman. When I Import the subscriptions nothing happens.

**Comment by d34m0nhLInt3r** [comment]
just downgraded again to electron 6.0.12 and its working fine. So there should be something fixed if you want to upgrade to electron 7.
