### ISSUE TITLE
[Bug]: Alt+Tab with a full screen video crashes X

### ISSUE THREAD

**Issue by xxxxme** [FreeTubeApp/FreeTube#4210]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

With a video running full screen, I press Alt+Tab. FreeTube and X crash.
If I have multiple monitors connected, with FreeTube running fullscreen on one of them, dragging a window to that monitor from another also crashes FreeTube and X.

Xorg.0.log.old looks like X shut down normally.

Arch Linux x64 (up to date)
FreeTube 0.19.1 (both official 64-bit .deb release and self compiled, both installed from AUR packages)
Openbox 3.6.1

### Expected Behavior

FreeTube should not crash when Alt+Tab is pressed and it's running fullscreen.

### Issue Labels

causes crash

### FreeTube Version

0.19.1

### Operating System Version

Arch Linux x64 kernel version 6.1.59-1-lts

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Cant reproduce on a single monitor. Maybe its because of the multiple monitors?

**Comment by xxxxme** [comment]
Still happens for me on a single monitor.  That suggests it might be something else, like my WM or DE.  Checking that.
