### ISSUE TITLE
[Bug]: Blank space in tall windows

### ISSUE THREAD

**Issue by maplepy** [FreeTubeApp/FreeTube#4211]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [x] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Open a new window with the 
![image](https://github.com/FreeTubeApp/FreeTube/assets/28269333/c78966d0-71a1-42cf-8fb4-b9503b2afd53)
Click any channel and get this weird bug

### Expected Behavior

No blank space

### Issue Labels

feature stopped working, visual bug

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Arch Linux

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Additional Information

![image](https://github.com/FreeTubeApp/FreeTube/assets/28269333/06e77dca-1df4-4394-ba39-0664671a3bdc)
![image](https://github.com/FreeTubeApp/FreeTube/assets/28269333/eaede31b-944b-4aef-b5f7-d3b48394b43b)
![image](https://github.com/FreeTubeApp/FreeTube/assets/28269333/41f7bb41-f9a6-4be6-acb8-208b3ac3d52e)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This is already fixed in the latest nightly in https://github.com/FreeTubeApp/FreeTube/pull/4139
