### ISSUE TITLE
[Feature Request]: Sort playlist by channel, duration, date, …

### ISSUE THREAD

**Issue by XanderLeaDaren** [FreeTubeApp/FreeTube#4212]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Videos are viewed in the Playlist in the order one added them.

There is actually no way of sorting them by channel, duration, date, nb. of views, and so on, in increasing/decreasing order.

### Proposed Solution

Add a droplist next to the Search field, reading “Sort by:” and with (at least) the following items: “Channel, Duration (increasing), Duration (decreasing), Date (old to recent), Date (recent to old)”
Eventually: number of views, or like/dislike, if it’s easy to extract from videos.

### Alternatives Considered

You may actually already find out videos from a channel by using the Search field, whereas you may get false positive if the search query matches titles of videos from other channels.

As far as I know, there is no alternative to sort by date nor duration.

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Im going ahead and close this because this is already implemented in the new playlist viewer that will be coming in v0.20.0
