### ISSUE TITLE
legacy player fallback wastes a lot of bandwidth  

### ISSUE THREAD

**Issue by pirate486743186** [FreeTubeApp/FreeTube#422]
when there's some problem with Invidious( often), the app fallbacks to legacy player.

Problems: After one failed attempt at using the dash player, then it uses the legacy player for everything, until you restart the app.
The video quality is also maxed (i normally use 360p). If you move away from the video, it still downloading. You can't stop it, unless you restart the app.

So very quickly, it eats a lot of bandwidth.

**Comment by morfikov** [comment]
I noticed that also -- it probably downloads the whole vid at max quality

**Comment by PrestonN** [comment]
This should be fixed in the rewrite.
