### ISSUE TITLE
[Feature Request]: Remove or move red play button in middle of video when paused

### ISSUE THREAD

**Issue by pagesix1536** [FreeTubeApp/FreeTube#4221]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When a video is paused, a giant red play button is centered on the video making it impossible to take a screenshot of a frame of video, or examine a video with something in the middle because the play button is blocking it.  This is unnecessary. There's a play button in the bottom left of the window.

### Proposed Solution

Remove it entirely, or maybe make a toggle option in the settings menu to remove it if desired when a video is paused so a clean screenshot can be taken without a button right in the middle of the video.

### Alternatives Considered

I suppose there's an alternative of downloading the video or opening it in an external play, but this is extra steps and requires you to download the WHOLE video. Fine for short ones, but if you're trying to take screenshots of a 60 minute video it's kind of overkill to download the whole thing to an external player just to elminiate the red play button.

### Issue Labels

new optional setting, visual improvement

**Comment by absidue** [comment]
Hiii

Thanks for opening this feature request, you'll be pleased to know we already have a setting for that :).

Settings -> Player Settings -> Display Play Button In Video Player
