### ISSUE TITLE
[Feature Request]: Tampermonkey 

### ISSUE THREAD

**Issue by SimonOriginal** [FreeTubeApp/FreeTube#4222]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Is it possible to embed the Tampermonkey add-on into the FreeTube application? https://www.tampermonkey.net/

### Proposed Solution

As far as I know Electron allows you to use add-ons written in JavaScript for web browsers.

### Alternatives Considered

-

### Issue Labels

new feature

**Comment by absidue** [comment]
Even if we add it, you won't be able to use any of the existing userscripts that are made for YouTube, you'll have to write custom FreeTube specific ones. You are probably better off creating a pull request with whatever you want to do with the scripts or creating a custom build with your desired changes.
