### ISSUE TITLE
[Feature Request]: Membership-only videos

### ISSUE THREAD

**Issue by KSXGitHub** [FreeTubeApp/FreeTube#4232]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I use FreeTube to bypass YouTube Ad-blocker detector, but I cannot watch membership only videos with it.

### Proposed Solution

Allow user to authenticate to watch membership-only videos.

### Alternatives Considered

Open in incognito doesn't work because YouTube will lock me out for using ad blocker.

Disabling ad blocker doesn't work.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> FreeTube is an open source desktop YouTube player built with privacy in mind. Use YouTube without advertisements and prevent Google from tracking you with their cookies and JavaScript.

This will go against the believes of FreeTube. Like stated above FreeTube is build with privacy in mind.
With this feature u will defeat the main purposes of FreeTube: enable the user to privately watch videos and that is to let YouTube track u.

We try to minimize tracking, not make it easier for them to track you.

I'll be closing this.
