### ISSUE TITLE
[Feature Request]: Add ability to copy link to video at current time

### ISSUE THREAD

**Issue by LiquidZulu** [FreeTubeApp/FreeTube#4236]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

On the YouTube website, I am able to right click the video and a menu appears allowing me to copy the link to the video at the current timestamp. I.e. if I am on the video with ID AAAA, then I can right click the player and copy the link to the current time, perhaps I am 300 seconds in and I get the link `https://youtu.be/AAAA?t=300`. I cannot discern any way of doing this within the FreeTube application, but this is a very useful feature for me---I find myself going back and forth between FreeTube and YouTube in order to get these timestamped links.

### Proposed Solution

Add the right-click menu that appears on YouTube, or add an "at the current time" option to the share menu below the video. Currently there are links for sharing the video, but none for sharing the video at the current timestamp.

### Alternatives Considered

My current solution to this problem is to watch the video on FreeTube to get to the point I want (FreeTube is far more responsive for me, so I prefer this), and then I navigate to the requisite time on YouTube and use the right-click menu to get the proper URL. This is clearly sub-par.

### Issue Labels

ease of use improvement

**Comment by jasonhenriquez** [comment]
![Picture of the existent feature](https://github.com/FreeTubeApp/FreeTube/assets/84899178/dd615cdc-44bd-4372-b2f0-65df49c9a2a4)
