### ISSUE TITLE
[Feature Request]: disable the title in full screen

### ISSUE THREAD

**Issue by sarfbooztahera** [FreeTubeApp/FreeTube#4239]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Disable title in full screen mode

### Proposed Solution

A settings option to disable the title in full screen mode which is very distracting

### Alternatives Considered

A settings option to disable the title in full screen mode which is very distracting

### Issue Labels

visual improvement

**Comment by jasonhenriquez** [comment]
Could you clarify what this is referring to and add a screenshot?

**Comment by akano12** [comment]
> Could you clarify what this is referring to and add a screenshot?

Pretty sure he's talking about the video title in the title bar.

And note to the author, press F11 as a workaround if you want to go to fullscreen, this will make FreeTube go to fullscreen, hiding the title bar entirely.

**Comment by jasonhenriquez** [comment]
Our team has decided that this is not a feature we would want to include in FreeTube given the lack of obtrusiveness.
