### ISSUE TITLE
Button "Load More" in the subscriptions

### ISSUE THREAD

**Issue by Agych** [FreeTubeApp/FreeTube#424]
It would very cool and convenient to have "Load More" button in the bottom of subscriptions, to be able to load more videos manually like on youtube.

**Comment by IAteYourBacon** [comment]
The subscriptions section barely covers the last 4 days for me. It would be nice to be able to go back further when not keeping up regularly with the new videos posted.

**Comment by PrestonN** [comment]
This will be implemented in the rewrite.  It might take a while before it's release but it's on the way.
