### ISSUE TITLE
[Feature Request]: remove the text in search / go to URL

### ISSUE THREAD

**Issue by wiiguy** [FreeTubeApp/FreeTube#4247]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

whenever i have searched for something and then search something again i have to manually remove the text in the search bar before i can search for something again

### Proposed Solution

is it possible to remove the text that is in it after the search ?

### Alternatives Considered

maybe make the text auto select after we click the search whenever there is text in it ?

### Issue Labels

ease of use improvement, new feature

### Additional Information

.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Wont implement, search is on par with YT UX and u can always just click the clear input button

https://github.com/FreeTubeApp/FreeTube/assets/73130443/aa1e5d53-cf61-4d7e-bb16-b61915b413d0
