### ISSUE TITLE
Video not available in your country, also, invidio API errors

### ISSUE THREAD

**Issue by aghdjkd** [FreeTubeApp/FreeTube#426]
The heck does this even happen? What's worse is that I don't even get this issue all the time, or even on the same video. I started watching a video yesterday, it loaded fine, returned to it today - got the issue. The video on youtube doesn't have country restrictions on youtube, so it can't be that.
Previously, I'd get such errors on "official" music videos, but I've found a workaround - just open the same song but with a fan-made video (like all those 'lyrics' videos). Yet, most recently, I got the issue with Timeline channel (the one that uploads documentaries).
And no, switching on proxy doesn't change anything.

**Comment by morfikov** [comment]
I've seen this two or so times, and reloading a movie fixed the issue for me, so I think it's not related to country restrictions, maybe some other error has wrong description. :D
