### ISSUE TITLE
[Feature Request]: Integrate SponsorBlock into FreeTube

### ISSUE THREAD

**Issue by 69Starship420** [FreeTubeApp/FreeTube#4260]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The near-equivalent of FreeTube on Android is YouTube ReVanced, which has similar features to FreeTube but also includes the highly popular Chrome extension SponsorBlock built in.  SponsorBlock's purpose is to skip sponsor segments in the same way as an adblocker on YouTube videos via community input.  Since FreeTube already has no ads, why not skip sponsor segments with SponsorBlock?  It would probably be one of the best features to be added to FreeTube.

### Proposed Solution

The proposed solution is to contact Ajay Ramachandran (SponsorBlock's developer) and politely get his permission to integrate SponsorBlock on the FreeTube app.  If YouTube Vanced (now ReVanced) has successfully integrated the SponsorBlock extension into its app, then FreeTube definitely has the ability to do it, too.  Insert pieces of code that integrate SponsorBlock into the FreeTube app.

### Alternatives Considered

If he does not allow permission to integrate SponsorBlock onto the FreeTube app, then try developing an in-house version of SponsorBlock that does the same thing: skip sponsorship segments on YouTube videos that have them via community input.  It will be unlikely that an alternative plan will have to be used because if Ajay Ramachandran allowed YouTube Vanced (now ReVanced) to integrate SponsorBlock, then he will probably allow the integration of SponsorBlock onto the FreeTube app.

### Issue Labels

new feature

**Comment by absidue** [comment]
Hi

FreeTube has had SponsorBlock support for a while, as mentioned in the README https://github.com/FreeTubeApp/FreeTube#features.

You can enable and configure it, in the adequately named "SponsorBlock Settings" section in the FreeTube settings.
