### ISSUE TITLE
[Feature Request]: Add 2160p 1440p to default quality 

### ISSUE THREAD

**Issue by superfreeman1989** [FreeTubeApp/FreeTube#4265]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

2160p is now supported, previous feature request is relevant again.

### Proposed Solution

add higher than 1080p to drop down menu

### Alternatives Considered

none available

### Issue Labels

improvement to existing feature

### Additional Information

![SCR-20231031-p1n](https://github.com/FreeTubeApp/FreeTube/assets/15226945/f63c0e4b-b6e0-4a2c-8d8b-177171af34b6)
![SCR-20231031-p28](https://github.com/FreeTubeApp/FreeTube/assets/15226945/81195c69-1b7d-498a-af12-20484a2072bf)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not possible see https://github.com/FreeTubeApp/FreeTube/discussions/4207#discussioncomment-7347659
