### ISSUE TITLE
Allow saving playlists to favorites

### ISSUE THREAD

**Issue by trignonun** [FreeTubeApp/FreeTube#427]
Title. 

Currently also if i open a playlist in the "Search" bar, it just goes to the first video, and doesn't keep playing the playlist afterwards.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@RogerBytes 

https://github.com/user-attachments/assets/f6da98ce-1f1f-443f-8145-a0bec2f1619a

**Comment by RogerBytes** [comment]
> [@RogerBytes](https://github.com/RogerBytes)
> FreeTube_MHbhVm2gtS.mp4

Thanks, it works flawlessly, I was thinking the button was for copying the playlist's URL.
