### ISSUE TITLE
NotSupportedError: Failed to load because no supported source was found.[Bug]: 

### ISSUE THREAD

**Issue by AHimlenes** [FreeTubeApp/FreeTube#4271]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

 Hello! Probably a week or two ago, when trying to play a video from YouTube, the application gave an error:
 NotSupportedError: Failed to load because no supported source was found.
  This happens regardless of which video is launched. What's the problem? How do I fix it?

### Expected Behavior

The video was expected to play as it had done before.

### Issue Labels

visual bug

### FreeTube Version

v0.19.1

### Operating System Version

Win 10 22H2

### Installation Method

Portable

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please provide urls of videos this bug is occurring on

**Comment by AHimlenes** [comment]
https://github.com/FreeTubeApp/FreeTube/assets/103057432/fbe0fb49-64de-4592-bcb4-df42f044809f

video fail is added...

**Comment by AHimlenes** [comment]
There is any video from YouTube. Nothing is played...

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I cant read that language therefore i cannot go to those videos to reproduce the bug. Please provide the urls of those videos

**Comment by AHimlenes** [comment]
https://github.com/FreeTubeApp/FreeTube/assets/103057432/7238431c-3d86-4389-ac29-f20da5850333

 What does the language of video have to do with it? Does the language change the codec or data transfer protocol? Or which of the words "no video" you don't understand? Any video won't play...

**Comment by TauAdam** [comment]
The same bug. Eroor: NotSupportedError: Failed to load because no supported source was found.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could u do the following: 

1. open the dev tools with ctrl + shift + i
2. Navigate to a video
3. Make a screenshot of the errors that appeared in the dev console

**Comment by AHimlenes** [comment]
![ss1](https://github.com/FreeTubeApp/FreeTube/assets/103057432/8400e462-fcb3-485f-9280-3eb7702c8ae6)
Is that good?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@AHimlenes it seems like the Invidious Instance you're using is IP blocked.

U can do the following things:
1. Disable `Proxy Videos Through Invidious` under the `Player Settings`
2. If u dont want to go with route 1 then u need to set another `Current Invidious Instance` under the `General Settings`. If u also see the error on the new set instance then u need to keep searching for one that isnt IP blocked.

**Comment by AHimlenes** [comment]
Thank you for your reply. Everything worked! It appears that this setting was enabled by default. I think you should warn the users. Otherwise, someone will decide to try it and immediately face such a problem, one will think that the program is buggy. And spit on her. Judge for yourself how much effort I have to spend to get the program working. Will everyone spend so much time and effort? Do you put so much effort into other people's programs?
 And here's another. It would be very helpful to be able to copy the link of the video you are watching. For example, how it is done on YouTube. Or display it in the address bar. For example, if you want to send a link to someone.
 Thank you for your help and program! Good luck!

**Comment by absidue** [comment]
@AHimlenes That setting is definitely disabled by default. Just checked the code and tested it myself, by backing up my settings, then deleting the original file and starting FreeTube without it, so it used the default settings. I'm guessing you turned it on at some point and forgot that you turned it on.

You can already copy the link, click the share button and then in the menu that pops out click the button to copy the YouTube link, it's the same button and menu that exists on the Channel and Playlist pages.

Anywhere else in FreeTube (e.g. search results) you can use the 3 dots menu that appears if you hover over the video thumbnail or right click on the video.
