### ISSUE TITLE
[Bug]: Hide Unsubscribe button in parental controls also hides subscribe button

### ISSUE THREAD

**Issue by Jeefongithub** [FreeTubeApp/FreeTube#4279]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1.  Go to Settings
2. Go to Parental Control Settings
3. Select Hide Unsubscribe button
4. Search / goto channel not subscribed to. See button is missing

### Expected Behavior

I expected the toggle to hide the unsubscribe button but not both subscribe and unsubscribe. I had enabled thinking it was a good way to make sure no accidental clicks unsubscribed from a channel. Not sure if intended behavior

### Issue Labels

visual bug

### FreeTube Version

v0.19.1 beta

### Operating System Version

Debian 12

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by jasonhenriquez** [comment]
[This seems to be the intended behavior](https://github.com/FreeTubeApp/FreeTube/pull/1456), so not a bug. Others are welcome to discuss the merits of adding more granularity or the improving the clarity of the naming if either are real issues at all, but that's not my place.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Indeed intended behavior, we should definitely communicate that better.

Some options:

Hide (Un)subscribe button
Hide Subscribe and Unsubscribe button
