### ISSUE TITLE
[Bug]: err_invalid_arg_type when trying to download videos

### ISSUE THREAD

**Issue by keithfre** [FreeTubeApp/FreeTube#4280]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I'm on Windows 10 64-bit.
1. Open any video.
2. Click download button.
3. Select video/mp4 (or any other option).
4. Error message err_invalid_arg_type the path argument must be of type string [...].

### Expected Behavior

The download starts!

### Issue Labels

feature stopped working

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 10 Home, 22H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.1 Beta

### Additional Information

Download was working, but now generates this error. Don't know what API is being used.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by lamemakes** [comment]
I couldn't recreate this on Fedora, can any of the Windows folk confirm it's potentially OS specific?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Cant reproduce on Win 10 either. @keithfre could you maybe make a screenrecording of this behavior?
