### ISSUE TITLE
[Feature Request]: Nebula Partnership

### ISSUE THREAD

**Issue by hutonahill** [FreeTubeApp/FreeTube#4305]
### Guidelines

- [x] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently, I watch videos on two services. YouTube and Nebula. I would like to be able to watch them on the same platform.YouTube

### Proposed Solution

I propose you partner with Nebula to become their desktop client. 

### Alternatives Considered

N/A. Ether you do this or you dont

### Issue Labels

new feature, support for external software

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://docs.freetubeapp.io/faq/#will-you-consider-adding-support-for-services-outside-of-youtube-twitch-soundcloud-peertube-etc
