### ISSUE TITLE
[Feature Request]: Save Progerss

### ISSUE THREAD

**Issue by hutonahill** [FreeTubeApp/FreeTube#4316]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

ocationaly i leave a video and my progress is not saved

### Proposed Solution

add a button to manually trigger the save progress.

### Alternatives Considered

You could increase the frequency that the system saves videos

### Issue Labels

ease of use improvement, improvement to existing feature, new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We will not add a button to save watch progress. Could u maybe provide reproducible steps for the watch progress not being saved.
