### ISSUE TITLE
autoplay videos in a playlist instantly. no five second wait

### ISSUE THREAD

**Issue by elitecoder27** [FreeTubeApp/FreeTube#4317]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

In a playlist, I have to wait five seconds for the next video to play. in other frontends and yt itself, the video plays instantly.

### Proposed Solution

remove the five-second wait time and play videos in a playlist (not recommended video autoplay)

### Alternatives Considered

simple fix. no need for any alternative solutions.

### Issue Labels

ease of use improvement, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You can configure this under the player settings.
