### ISSUE TITLE
Can't load any channel/video even on working instances

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#433]
Hello,

I can't load anything even when the invidious instance is working.

**Comment by qrlk** [comment]
I have had same issue on macOS Catalina (I have never used FreeTube on macOS before). I could open program and even browse "Trending" & "Most Popular" but trying to open a video resulted in infinite load.
On my Linux machine FreeTube was working fine so I just exported my subscriptions on Linux and imported it on Mac. I have no idea why, but now it's working.
Here is [my backup](https://filesend.standardnotes.org/send/SGJfQzFDQKMLDoqpyuOK#MzZkMTRmODBjZWJlY2IzYTAxMDVh).
