### ISSUE TITLE
AI Features 

### ISSUE THREAD

**Issue by fire17** [FreeTubeApp/FreeTube#4331]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There are so many AI features that will be super helpful
Like:
Asking a question about the current video
Asking a question that finds a video
Alternative recommendation system that is more aligned to my prompt

### Proposed Solution

We just entered the new age of LLMS
No need to wait for Google to release it
All of this could be done today

### Alternatives Considered

I asked the same from the ReVanced team

### Issue Labels

new feature

### Additional Information

Ps - when are you gonna have a mobile app ??!

Thanks a lot and all the best!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We're not interested in maintaining such features. Keeping up with YT changing and FT breaking is a big chore.

**Comment by absidue** [comment]
FreeTube runs on your own computer, there is no "FreeTube server", so those AI features would have to run on your own computer too, compared to the massive data centres and billions of dollars worth of hardware and energy that big companies use.

So sure if you want to wait, while your computer is maxed out and completely unusable for many hours or days or weeks to generate a few video suggestions, that's on you.

**Comment by fire17** [comment]
@absidue, dude you're so ridgid, i was more thinking of a feature that utilizes the user's own api key... (for oai or other apis) or even asking users to sponsor the server/api cost, honestly the most difficult thing in this is the integration and riding on the youtube app, which you guys are already doing.

@efb4f5ff-1298-471a-8973-3d47447115dc i'm very sad to hear that, honestly i thought open-source would lead the way forward, and offer the (too good for the public) features, before google desides to give out (which you know they would only push to premium users), hope you can reconside

I would love it if you can teach me or refer to how one would add a button and layout , and my (soon to be deployed) agi assistant will do that (when this comment will be pulled and read in the upcoming future a kin to all of my github issues)

**Comment by absidue** [comment]
@fire17 FreeTube's primary goal is to be a privacy friendly app. Giving you the ability to put in an OpenAI API key, a company that is known to store everything you send it and regurgitate it to other users, goes completely against that goal.

**Comment by fire17** [comment]
@absidue , there are other (and soon will be more) api's and companies that would be more trust worthy
the privacy policy is up to the user to accept.
secondly, some of the ai features can be easily done today just by scanning some captions
you dont need youtube's servers for that,
again, ai isn't the problem here, integrating it in the same place where people whats youtube from is whats keeping this away
hope you guys reconsider, or atleast teach/direct us on where and how to add some button and layouts

**Comment by fire17** [comment]
@absidue my friend, im system's architect and all i do is mess with the latest cutting edge ai solutions, (also try to keep it foss) 
and what i meant is that FOR ME the hardest part is integration and making the layouts.
Everything else is just designing the data (mostly captions) pipeline and llms correctly, don't assume i dont understand the complexities invoved

**Comment by absidue** [comment]
> also i dont know why i got on your bad side

Because you kept going even though we told you that we are not interested in adding anything like that. We aren't dropping the ball. There is just no added value in wasting loads of energy destroying the planet to violate people's privacy.
Want to search for a video? Use the search bar like a normal person.
Asking questions about the content of the video, can easily be done by doing your own research with a search engine or in a library, that way you are also more likely to get accurate information, instead of whatever your LLM hallucinated about.

**Comment by WhiteTorn** [comment]
Video Summarizer would be great...
Please add feature for those who wants it
