### ISSUE TITLE
[Feature Request]: Optionally show the current video id somewhere in the UI

### ISSUE THREAD

**Issue by lefuturiste** [FreeTubeApp/FreeTube#4334]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Being able to optionally easily see the current video id.
Why?
For exemple you need to check if two videos are actually the same, you need to compare the id.
You could use the share feature but it's an extra step.
AFAIK there is no more easier way that using the share button.

### Proposed Solution

Provide a user setting, that, when enabled will show up the id of the current video after or before the timestamp of the video.

### Alternatives Considered

Use the share button

### Issue Labels

display more information to user

**Comment by absidue** [comment]
You can enable the stats in the player either by right clicking on it or pressing `D` on your keyboard while on the watch page.

**Comment by lefuturiste** [comment]
Thanks for the answer, Related question: is there a shortcut to copy the video link or Id directly to keyboard?

**Comment by absidue** [comment]
No and it's unlikely that one will be added as there are 8 possible links that shortcut could use (16 if you take the option to include the timestamp into consideration), every user wants a different link to be copied (at least that's what has come up in previous discussions about that). Using the share button works just fine, without adding a controversial keyboard shortcut :).
