### ISSUE TITLE
[Feature Request]: Allow ESC to quit from PiP

### ISSUE THREAD

**Issue by mooreye** [FreeTubeApp/FreeTube#4367]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

You have to move mouse to PiP window and click "Back to tab" in order to quit PiP mode. It would be convenient to be able to just press Esc, especially that going to PiP mode can already be doone with keyboard by pressing `I`.

### Proposed Solution

Allow Esc to quit from PiP back to main window

### Alternatives Considered

none

### Issue Labels

ease of use improvement

**Comment by mooreye** [comment]
> I dont think Global Esc key is a good choice, 'we' might want to Esc something else. PiP always should require focus on the window somehow.
> 
> Pressing `i` when you are on the PiP also minimize it at the moment.

Pressing `i` doesnt work for me in PiP's window, it doesn't exit from PIP mode. I use flatpak version

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Implementing ESC can introduce other weird behavior into FT and is non standard behavior for the PIP module we're using, see https://googlechrome.github.io/samples/picture-in-picture/.

Therfore im closing this issue.
