### ISSUE TITLE
0.7.2 debian issue 

### ISSUE THREAD

**Issue by danrobi11** [FreeTubeApp/FreeTube#439]
Cant run appimage nor deb package on debian
I've tried debian 10 and MX Linux (MX-19)
FreeTube doesnt launch.

> $ freetube
[22324:1224/143449.610275:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/FreeTube/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

**Comment by oakes8585** [comment]
Having the same issue here on my end ive tried every workaround i can think of at this time with no good coming from it.....

**Comment by counterstrike999** [comment]
easy fix, just give it the permissions requested for chrome-sandbox:
$ sudo chmod 4755 /opt/Freetube/chrome-sandbox 

Please add this line to the new version*.

**Comment by danrobi11** [comment]
@counterstrike999  That doesnt work: sudo chmod 4755 /opt/Freetube/chrome-sandbox
But that does work: sudo sysctl kernel.unprivileged_userns_clone=1

**Comment by cbrunning** [comment]
$ sudo chmod 4755 /opt/Free**T**ube/chrome-sandbox

0.7.3 -- chmod with capital letter T in the directory name
