### ISSUE TITLE
[Feature Request]:  Grayscale mode to avoid the "YouTube Rabbit Hole" (attention grabbing)

### ISSUE THREAD

**Issue by Exponent4806** [FreeTubeApp/FreeTube#4400]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Youtube has a great ability to grab our **attention** and _reduce our productivity._   

One feature that keeps users hooked into the "Youtube Rabbit Hole" is the efficient usage of attention-grabbing colors to capture our attention. Those colors are used masterfully to generate clickbaits (front image of videos). Furthermore, within videos, the usage of attractive nuances of colors promotes to spend more time watching videos and reducing our productivity.

### Proposed Solution

Adding an optional feature to avoid distractions called **“Grayscale mode”**.

If technically feasible, it might be helpful to convert front images of videos and videos itself into a gray scale mode. 

There are browser extensions that convert the browser into a gray scale mode, and that helps to avoid distractions. If possible, that would be a useful option in Freetube.

### Alternatives Considered

I am not suggesting simply a “gray scale” Theme, rather a way to remove color from clickbaits and videos themselves. 

If converting the videos into a grayscale mode is not technically possible, at least removing colors from "clickbaits” could help to avoid wasting time in Youtube.

### Issue Labels

new optional setting

### Additional Information

Here is an extension for Firefox that converts everything into a grayscale mode: https://github.com/rewkha/firefox-grayscale

**Comment by absidue** [comment]
Hi

Not sure how long you've been using FreeTube, but if you are a new user you might want to check out the "Distraction Free Settings" section in the settings, it includes various different settings such as hiding YouTube's recommended videos on the watch page.

You also mentioned clickbait being a problem for you, FreeTube also has settings for that:
For thumbnails you can check out the "Thumbail Preference" dropdown in the General Settings section.
For titles you have two choices "Use DeArrow Video Titles" in the SponsorBlock Settings (https://dearrow.ajay.app/ FreeTube only supports their titles at the moment) or "Display Titles Without Excessive Capitalisation" in the Distraction Free Settings.

**Comment by Exponent4806** [comment]
> thumbnails

I remove the thumbnails and use all the anti-distraction features. 

What would be a useful extra feature would be to turn the videos into grayscale.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Exponent4806 we have decided that this could be better handled on the OS side instead of in FT.

**Comment by absidue** [comment]
Both Windows and macOS let you set colour filters at the operating system level, including greyscale one. On Linux you can probably find utilities to do it if your distro doesn't already support it.
