### ISSUE TITLE
[Bug]: Search only works on new window

### ISSUE THREAD

**Issue by m3thm4th** [FreeTubeApp/FreeTube#4402]
### Guidelines

- [X] I have encountered this bug in the latest release of FreeTube.
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

If I open a new window and search for something I get the results I want, but if I enter another query I get the same results of the previous search, no matter how many times I try, the search results are always from the first search, unless I open a new window, then the new query returns the expected results.

1. Search any words
2. Search other words
3. Get always the same results from 1

### Expected Behavior

I should get results for the new queries

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Debian 12

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @m3thm4th i cant reproduce this on my end. Could u do the following, Open FT -> Open the dev console (CTRL + shift + i) -> search for the first time -> search for the second time -> check if there are any red errors are popping up in the console

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We still need to know the error that are being shown in the console to help you further. Please follow the steps i laid out in my previous comment

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> The issue seems to occur only when I use Tor in proxy settings, on clearnet it works as expected

Please try another proxy as this seems an issue with the current proxy you're using
