### ISSUE TITLE
0.7.2 Legacy player broken

### ISSUE THREAD

**Issue by hunguscrungus** [FreeTubeApp/FreeTube#441]
The Legacy player fallback just stopped working entirely for a few hours as of this post. It's frozen on 0:00 with the video thumbnail displayed behind the player GUI and the play button is greyed out. Completely unresponsive to any clicks anywhere as well as timestamps. 

This is an especially large problem since the only fallback available does not exist anymore, so the instance has to be efficient enough to load the video in DASH or revert back to the YouTube player. Hope it can be fixed.

**Comment by AlphaShadows77** [comment]
I've got the same issue. It worked for a few minutes after installing FreeTube but now, it does not work anymore. Hope it can be fixed too \o/
