### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by Feuerstahl** [FreeTubeApp/FreeTube#4411]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Videos of this speciefic playlist cannot be opened. 

Channel: JJ's One Girl Band
Playlist: LIVESTREAM
[https://www.youtube.com/playlist?list=PLGwwLsQaMyaPJJVY1CuHlijmHjMXm1xnK](url)

Could be the issue with videos being marked as  'Members only'.

Changing the Invidious Instance didn't solve the problem.

### Expected Behavior

no Error

### Issue Labels

API issue

### FreeTube Version

freetube-0.19.1-nightly-3694-setup-x64.exe

### Operating System Version

Windows 10 Pro 22H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

freetube-0.19.1-nightly-3617-setup-x64.exe

### Additional Information

![Freetube Issue](https://github.com/FreeTubeApp/FreeTube/assets/59896256/8d8f1a1a-a67f-452e-864b-8b242b10cc3d)
![Freetube Issue2](https://github.com/FreeTubeApp/FreeTube/assets/59896256/49263e2c-9e97-444b-baac-9141342c101c)
![Freetube Issue3](https://github.com/FreeTubeApp/FreeTube/assets/59896256/162076ef-1172-4e9d-b0c0-60fa2465a2fa)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Nothing we can do about it. We cannot show members only content.

**Comment by absidue** [comment]
@fabbadabbawow Your issue is completely unrelated to this one, read this open issue please: https://github.com/FreeTubeApp/FreeTube/issues/4811
