### ISSUE TITLE
[Bug]: Crashes when launching flatpak app and playing video in gnome

### ISSUE THREAD

**Issue by echakr** [FreeTubeApp/FreeTube#4422]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

The app crashes when viewing the first video with the following messages in journalctl:

Dec 04 16:31:27 [hostname] gnome-shell[2431568]: cogl_framebuffer_set_viewport: assertion 'width > 0 && height > 0' failed
Dec 04 16:31:29 [hostname] systemd[2431284]: Started app-gnome-io.freetubeapp.FreeTube-2617861.scope - Application launched by gnome-shell.
Dec 04 16:31:29 [hostname] gnome-shell[2431568]: cogl_framebuffer_set_viewport: assertion 'width > 0 && height > 0' failed
Dec 04 16:31:29 [hostname] systemd[2431284]: Started app-flatpak-io.freetubeapp.FreeTube-2617861.scope.
Dec 04 16:31:29 [hostname] systemd[2431284]: Started app-flatpak-io.freetubeapp.FreeTube-2617890.scope.
Dec 04 16:31:29 [hostname] io.freetubeapp.FreeTube.desktop[2617880]: LaunchProcess: failed to execvp:
Dec 04 16:31:29 [hostname] io.freetubeapp.FreeTube.desktop[2617880]: xdg-settings
Dec 04 16:31:29 [hostname] io.freetubeapp.FreeTube.desktop[2617880]: Gtk-Message: 16:31:29.846: Failed to load module "canberra-gtk-module"
Dec 04 16:31:29 [hostname] io.freetubeapp.FreeTube.desktop[2617880]: Gtk-Message: 16:31:29.848: Failed to load module "canberra-gtk-module"
Dec 04 16:31:29 [hostname] io.freetubeapp.FreeTube.desktop[2617880]: [2:1204/163129.867787:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Dec 04 16:31:29 [hostname] io.freetubeapp.FreeTube.desktop[2617880]: [2:1204/163129.867844:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Dec 04 16:31:38 [hostname] io.freetubeapp.FreeTube.desktop[2617880]: [47:1204/163138.058443:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: DisplayRead|Scanout, format: YUV_420_BIPLANAR, share_between_threads: 0, gmb_type: platform
Dec 04 16:31:38 [hostname] io.freetubeapp.FreeTube.desktop[2617880]: [47:1204/163138.058571:ERROR:shared_image_stub.cc(147)] SharedImageStub: Unable to create shared image
Dec 04 16:31:39 [hostname] systemd[2431284]: app-flatpak-io.freetubeapp.FreeTube-2617861.scope: Consumed 10.303s CPU time.

### Expected Behavior

When running the app using flatpak run in a terminal window the errors still appear (in stdout) but the app continues to work

### Issue Labels

causes crash

### FreeTube Version

0.19.1 Beta

### Operating System Version

Debian 12.2

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Did you change any of the flatpak permissions?

**Comment by echakr** [comment]
I just attempted this again, un-setting and resetting the Wayland socket permission, restarted freetube a couple of times and the issue seems to have gone away?!
