### ISSUE TITLE
Suggestion: more organization features 

### ISSUE THREAD

**Issue by BrainlessConsumer** [FreeTubeApp/FreeTube#443]
As the FreeTube App evolves, please consider adding more organization features.
Adding bookmark folders or directories to store channels, would shorten the channel list into smaller sections, and be a time saver scrolling through a very long channel list.

Thanks again for update 0.7.2 - the quick response was greatly appreciated.

**Comment by Archive5** [comment]
https://github.com/FreeTubeApp/FreeTube/issues/333
