### ISSUE TITLE
[Bug]: Main screen not showing on osx

### ISSUE THREAD

**Issue by tyoc213** [FreeTubeApp/FreeTube#4430]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

On macos open freetube app after downloaded from site dmg and confirm security exception about the developer.

No window will show, but the menu is visible and can clicking on  diferent items but doesnt show the window.

### Expected Behavior

The main window to be visible

### Issue Labels

content not loading

### FreeTube Version

0.19.1-mac-x64.dmg

### Operating System Version

osx sonoma 14.1.2 (23B92)

### Installation Method

.dmg

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by sarimak** [comment]
My wife's Freetube was also not visible but she managed to fix that by noticing a strange small white thin vertical bar (with height cca 1 letter and width cca 1 pixel) in lower left part of the screen. By hovering over the bar the cursor changed to "resize window" and it was possible to make the window larger and restore its original size. Since then Freetube works fine.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@sarimak is that also on a mac?

**Comment by sarimak** [comment]
Yes, latest OS X on the last MacBook Air that used Intel CPUs.

BTW: I use Ubuntu and never saw such a problem, so it is most likely an OS X specific issue.

**Comment by pranavburnwal** [comment]
+1 

Any possibilities of this being fixed?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@tyoc213 are you also facing this issue in v0.20.0?
