### ISSUE TITLE
[Bug]: webpack builds broken on node 20

### ISSUE THREAD

**Issue by selfisekai** [FreeTubeApp/FreeTube#4432]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

```
$ yarn run pack
yarn run v1.22.19
$ run-p pack:main pack:renderer
$ webpack --mode=production --node-env=production --config _scripts/webpack.renderer.config.js
$ webpack --mode=production --node-env=production --config _scripts/webpack.main.config.js
node:internal/modules/esm/resolve:205
  const resolvedOption = FSLegacyMainResolve(packageJsonUrlString, packageConfig.main, baseStringified);
                         ^

TypeError: The URL must be of scheme file:
    at legacyMainResolve (node:internal/modules/esm/resolve:205:26)
    at packageResolve (node:internal/modules/esm/resolve:831:14)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_INVALID_URL_SCHEME'
}

Node.js v20.10.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "pack:main" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

building assets successfully

### Issue Labels

usability issue

### FreeTube Version

d6a6cc034988b8a61aed0790556db01c541310f8

### Operating System Version

Alpine Linux edge

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
The build is working fine here for me on Node 21.3.0 on Windows 10 and on CI on Windows, macOS and Linux with Node 20 in this test build (only change was changing the Node version in the workflow file from 18 to 20): https://github.com/absidue/FreeTube/actions/runs/7146374516

**Comment by selfisekai** [comment]
ok seems to be a node.js issue https://github.com/nodejs/node/issues/51096
