### ISSUE TITLE
[Feature Request]: Lemmy Comments for FreeTube

### ISSUE THREAD

**Issue by slrgt** [FreeTubeApp/FreeTube#4434]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

It's currently impossible to browse Lemmy comments posted to a thread made with the youtube URL you are watching on FreeTube

### Proposed Solution

It would be great to be able to have Lemmy comments embedded in FreeTube which is possible on youtube with this extension: https://github.com/Xyl-AU/Reddit-Comments-for-YouTube

### Alternatives Considered

Using the extension and browsing the youtube website is the only alternative possible currently but people using FreeTube don't want to use the YouTube website.

### Issue Labels

new feature

**Comment by ElijahHW** [comment]
+1

Would love to see this implemented 💪

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Marking this as duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1981
