### ISSUE TITLE
[Bug]: video is flashing and thus unwatchable 

### ISSUE THREAD

**Issue by MAHOOTYBOI** [FreeTubeApp/FreeTube#4443]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

open freetube, 
open any video 
see flashing video flashing black randomly. 
happens for both APIs 

https://github.com/FreeTubeApp/FreeTube/assets/98348466/ec06b395-019c-4746-9be0-ba033c062053

### Expected Behavior

I expected the video to play normally with no flashing.

### Issue Labels

usability issue, visual bug

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

fixes tried:
reinstall 
API change
graphics driver update
in case its a problem with computer hardware this is what I was trying to run it with: ryzen 7000, rtx 4060 and at 1080p 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @MAHOOTYBOI could you try this https://github.com/FreeTubeApp/FreeTube/issues/4184#issuecomment-1769299483

**Comment by MAHOOTYBOI** [comment]
> Hi @MAHOOTYBOI could you try this [#4184 (comment)](https://github.com/FreeTubeApp/FreeTube/issues/4184#issuecomment-1769299483) to see if that resolves your issue

it seems that disabling multiframe sampling has fixed the issue, thank you
