### ISSUE TITLE
[Feature Request]: YT Summarizer

### ISSUE THREAD

**Issue by sm18lr88** [FreeTubeApp/FreeTube#4445]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Between clickbait, marketing, and time-wasting scripts, we waste lots of time on YT just to get a tiny bit of key information.

### Proposed Solution

Could a feature be installed where users input an API Key (for OpenAI, Azure, or another service) that automatically summarizes video transcripts?

### Alternatives Considered

Manually copy/paste URLs into sites like Summarize.Tech. 

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We will not implement such features, for more info read https://github.com/FreeTubeApp/FreeTube/issues/4331
