### ISSUE TITLE
[Feature Request]: Save Playback rate / speed for each channel

### ISSUE THREAD

**Issue by thingsiplay** [FreeTubeApp/FreeTube#4447]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Some content creators I listen regularly are talking slow. I have to speed it up by adjusting playback rate every time. It is annoying to remember the correct setting for every channel (using 1.15, 1.25 and even 1.4 or 1.5 times) I am watching (150 subscribed channels) and always adjusting when starting the video. A global setting is not useful, because I have to adjust channels who speak normal speed too.

### Proposed Solution

An option to save and restore default playback speed for each subscribed channel.

### Alternatives Considered

I could not come up with an alternative solution, as this needs to have builtin or through plugins support. Back when I was on Firefox, I searched for such a plugin for a long time (without success) too.

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is a bit too specific of an usecase to implement like suggested. 

Our main intended way of implementing behaviors like this is through profiles. In this case, specifically [profile settings separation](https://github.com/FreeTubeApp/FreeTube/issues/1996)

Therefore I'm closing this issue

**Comment by thingsiplay** [comment]
Hi, sorry for the late reply. After looking into it, I want to say that this solution with profiles is not sufficient for my use case. I understand this is a specific use case from your perspective and therefore not worth the time to implement. Nonetheless it is useful in my opinion and there is no good alternative. I describe why below. Notice, I am not forcing or demanding the feature, just explain why it is needed and suggest it.

Because that means I cannot create themed profiles then and always have to remember which profile to use to listen to a specific video. With 150 and more subscribed channels and currently 8 themed profiles (such as "Retro Gaming", "Programming", "Science") its well organized. My normal usage is still the "All" profile for daily usage. Now if I create speed based profiles and put a specific science and a retro gaming content in the x1.4 times profile and create other speed profiles, then what happens is that I have to remember in what profile each channel is, switch to that profile, and click video again.

But as said before, I understand having priorities. This is just an explanation, not demand.

**Comment by thingsiplay** [comment]
> If you are still using FreeTube and interested in getting this feature I forked and implemented it now: https://github.com/D3SOX/FreeTube

This is amazing and I am interested into this feature. But switching to a fork is something I want to avoid, because of trust issues and for convenience. I would need to trust you, and I would need to update it manually instead through official Flatpak.

This needs to be implemented into the original upstream project. Hopefully this will be accepted. I want to thank you for the efforts.

**Comment by absidue** [comment]
> I asked again but they rejected it, even if I were to provide a PR for it.. :(

Because doing a pull request for it is the smallest and easiest part of the story, maintaining things and providing support for them is the much bigger burden which you would be delegating to us by doing a pull request. FreeTube is not supposed to cover every niche setup or browser extension, so while you might not like that we don't accept feature requests and pull requests for niche things and feature creep like this, it is the only way we can stop FreeTube becoming even more of a nightmare to maintain than it already is, which would result in the project getting abandoned entirely.

**Comment by absidue** [comment]
Go for it, FreeTube is open source after all, as long as you respect the AGPL 3.0 license (crediting FreeTube for all the things you are using from it and open sourcing all changes that you make, along with all the other things the license requires) and don't make your changes and users our problem, so we can keep working on the important things it's all good.
