### ISSUE TITLE
[Bug]: screen flashes white when watching videos

### ISSUE THREAD

**Issue by geotraders** [FreeTubeApp/FreeTube#4448]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

While watching a video the app will flash white, the video is unaffected but the entire area of the app flickrs white for a second.

### Expected Behavior

N/A

### Issue Labels

visual bug

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

N/A

### Additional Information

N/A

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please upload a video of this behavior.

**Comment by geotraders** [comment]
https://imgur.com/a/xPDUhZB
I uploaded it to imgur.

**Comment by geotraders** [comment]
its flashing black now. it was flashing white before. it happens when watching live streams.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@geotraders You can also upload gif/videos straight into your comment 

https://github.com/FreeTubeApp/FreeTube/assets/73130443/e66da8e9-c547-43ce-812e-8fbca91d2cdf

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Does this only happen on live streams?

**Comment by geotraders** [comment]
yea it seems to be just the live-streams

**Comment by geotraders** [comment]
https://github.com/FreeTubeApp/FreeTube/assets/153692559/a43b777f-e0c9-468c-946f-2d59dc640860

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
A theory that we have

is that there is some graphics card setting turned on, that doesn't like the length of the video increasing. With that assumption we can also assume that it is happening every 5 seconds, because that's the interval that the new live manifest is fetched, then the segment downloaded and appended to the player buffer. 

Maybe the video length changing is causing the graphics card driver to do some kind of reset, which is why it flickers for a moment.

Historically weird graphical issues happening in FreeTube on Windows 10 have been caused by NVIDIA graphics card settings.

So please check you're graphics card settings and make sure the drivers are up to date.

**Comment by geotraders** [comment]
It happens randomly and I am using a RX5700XT. Could a hacker be causing this? My network was breached and they have been doing weird things to harass me like blocking webpages, powershell popups, freezing streams on kick and twitch. Is there any monitoring tool you'd recommend to help find the issue?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I dont think a hacker would cause these kind of issues. 

In the past we have seen allot of issues with the player because of weird graphics settings turned on and we've also seen issues with the player when the graphics drivers were outdated.

> So please check you're graphics card settings and make sure the drivers are up to date.

Please try this first.

**Comment by geotraders** [comment]
I am using Adrenalin 23.11.1 (WHQL Recommended). These issues were not happening before is why I brought it up. I am upgrading to 23.12.1 and will let u know if it fixes it,
