### ISSUE TITLE
[Feature Request]: Add verification Checkmark on the Flathub page

### ISSUE THREAD

**Issue by MysteriousOrb2000** [FreeTubeApp/FreeTube#4458]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

FreeTube has official Flatpak release support, yet there is no verification checkmark on Flathub, which might confuse users into thinking it's not officially support by the developers.

https://flathub.org/apps/io.freetubeapp.FreeTube

### Proposed Solution

The developers can get the app verfied on Flathub.

https://docs.flathub.org/docs/for-users/verification/

### Alternatives Considered

Not Applicable

### Issue Labels

display more information to user

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is not needed for this, already being tracked in https://github.com/FreeTubeApp/FreeTube/discussions/4339
