### ISSUE TITLE
[Feature Request]: Don't create ~/.pki directory, move it to $XDG_DATA_HOME/pki

### ISSUE THREAD

**Issue by Samueru-sama** [FreeTubeApp/FreeTube#4461]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

NSS already supports XDG Base Directory Specification however FreeTube instead decides to create the directory ~/.pki, likely because the path is hardcoded. 

### Proposed Solution

FreeTube should create the directory in $XDG_DATA_HOME

### Alternatives Considered

Even full support is not needed, FreeTube can check $XDG_DATA_HOME/pki first before defaulting to ~/.pki. 

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
[For people that dont know that NSS is](https://firefox-source-docs.mozilla.org/security/nss/index.html)
[Might be related](https://github.com/brave/brave-browser/issues/13733)

**Comment by absidue** [comment]
That's a chromium bug and completely out of our control.

https://bugs.chromium.org/p/chromium/issues/detail?id=1038587

**Comment by Samueru-sama** [comment]
> That's a chromium bug and completely out of our control.
> 
> https://bugs.chromium.org/p/chromium/issues/detail?id=1038587

Alright, in the meantime I'm launching freetube in a fake symlinked homedir to prevent the ~/.pki dir creation. 

There is a patched version of chromium that gets rid of the directory in the Aur, but I assume that getting it to work with freetube takes more work.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing this because of the reason stated earlier.
