### ISSUE TITLE
Thumbs Up Feature not working

### ISSUE THREAD

**Issue by Adrian281701** [FreeTubeApp/FreeTube#4479]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Thumbs Up Icon and count appear under eacch video, alwas in grey with a count of 0. The icon when clicked does nothing (supposed to turn blue), and the count remains at 0. Have tried on numerous videos, al the same. 

### Expected Behavior

Icon should indicate a change in state by turning blue, and ccount shoud increase by 1

### Issue Labels

feature stopped working, usability issue, visual bug

### FreeTube Version

0.19.1 beta

### Operating System Version

Windows 10 Pro - build 19045.3803

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
You need a YouTube account to like videos, so it isn't possible from inside FreeTube. If you want to like videos, you have to open YouTube in your web browser, log in with your Google account and then like it there.
