### ISSUE TITLE
[Feature Request]: Hide and do no play already watched videos in "next video" when hide watched videos option is set (or make a relevant option)

### ISSUE THREAD

**Issue by VincentCaruso** [FreeTubeApp/FreeTube#4482]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When hide watched videos is checked, videos are properly hidden on the subscriptions page, but when playing a video the next videos section still display and plays already watched videos.

### Proposed Solution

Hide already watched video in next videos and don't play it when "hide already watched video" option is checked.

### Alternatives Considered

Make a relevant option in the settings to disable autoplaying already watched videos.

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://github.com/FreeTubeApp/FreeTube/pull/4394 fixed the need for this issue
