### ISSUE TITLE
Hide Play button/Youtube logo from center of screen when video paused[Feature Request]: 

### ISSUE THREAD

**Issue by Gshaw12** [FreeTubeApp/FreeTube#4483]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Youtube play logo/button thing appears when video is paused, 

### Proposed Solution

I would like the option to permanently hide it since all it does is get in the way of what I paused the video to see. 

### Alternatives Considered

None

### Issue Labels

visual improvement

**Comment by jasonhenriquez** [comment]
This is already a feature: disable the "Display Play Button In Video Player" setting under Player Settings.
