### ISSUE TITLE
[Feature Request]: Ctrl+F should focus on search bar

### ISSUE THREAD

**Issue by mooreye** [FreeTubeApp/FreeTube#4484]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Ctrl+F doesn't focus on video search bar, I have to click it with mouse

### Proposed Solution

make Ctrl+F focus on search bar

### Alternatives Considered

none

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
CTRL+F should search stuff on the page not focus on the searchbar, like for example explained in #1401

We alreary have shortcuts for this usecase listed: https://docs.freetubeapp.io/usage/keyboard-shortcuts/
