### ISSUE TITLE
[Bug]: Empty space at the top of the channel page when the window takes up half of the screen

### ISSUE THREAD

**Issue by il2020** [FreeTubeApp/FreeTube#4485]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open FreeTube and shrink the window to half the screen.
2. Go to the page of any channel. For example:
    - Click on the channel name under any video.
    - Find any channel using search.

### Expected Behavior

The content of the page is visible at once, without scrolling down, without indentation at the top.

### Issue Labels

usability issue, visual bug

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Arch

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

Full width:

![image](https://github.com/FreeTubeApp/FreeTube/assets/77854832/a4f62bd9-8488-46d5-852c-44b37287a030)

Half the screen:

![image](https://github.com/FreeTubeApp/FreeTube/assets/77854832/be64caa9-cefb-403d-b9cd-706601fcff51)

![image](https://github.com/FreeTubeApp/FreeTube/assets/77854832/ceb1ba81-db65-4823-a12c-1e6ea7c406a7)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Already fixed in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).
