### ISSUE TITLE
[Request] Allow media buttons to control play/pause of video

### ISSUE THREAD

**Issue by kevinp15** [FreeTubeApp/FreeTube#449]
Self-explanatory title. I'd like to be able to play/pause the video without needing to move my cursor over and manually clicking rather than just pressing play/pause on my keyboard.

**Comment by PrestonN** [comment]
FreeTube already allows for keyboard shortcuts.  A list of them can be found [here](https://github.com/FreeTubeApp/FreeTube/wiki/Keyboard-Shortcuts).

As for the actual media keys on your keyboard, it's something I'd like to implement properly.  From what I've seen, it does work on Windows, but not on Mac or Linux.
