### ISSUE TITLE
[Bug]: Live Videos Not Loading on VPN

### ISSUE THREAD

**Issue by oToRINtI** [FreeTubeApp/FreeTube#4498]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Search for live video
2. Click live video
3. Video buffers continually and does not play

I have set up a router level VPN (Proton) and regular videos work fine, however live videos buffer endlessly and do not play.  Live videos do work when disconnected from the VPN in FT, but also work in the browser while connected to the VPN, so it is rather strange.  Download speeds show 50Mbps while connected to VPN so don't believe that is the issue.

### Expected Behavior

Expected live video to play since it works in browser while connected to VPN.

### Issue Labels

content not loading

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Ubuntu 22.04.3 LTS

### Installation Method

.AppImage

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @oToRINtI, i cant reproduce this issue. I tried Proton servers on multiple locations. Can screen/shot/record the following:
Open FT -> Open Dev Console (CTRL + Shift+ i) -> Go to a live video -> check if red errors pop up in console

**Comment by oToRINtI** [comment]
![Screenshot from 2024-01-02 21-04-10](https://github.com/FreeTubeApp/FreeTube/assets/155334726/34457c03-39b5-4320-b92b-b49f3cf7a5ab)

Screenshot uploaded, thank you.

**Comment by b1ek** [comment]
> ![Screenshot from 2024-01-02 21-04-10](https://private-user-images.githubusercontent.com/155334726/293832095-34457c03-39b5-4320-b92b-b49f3cf7a5ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODAzODAsIm5iZiI6MTcwNDQ4MDA4MCwicGF0aCI6Ii8xNTUzMzQ3MjYvMjkzODMyMDk1LTM0NDU3YzAzLTM5YjUtNDMyMC1iOTJiLWI0OWYzY2Y3YTVhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQxODQxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzFhY2JmYmYyODFiZjA1ODhkOWIyOGRmMmU0ZjZjZGE4MWU1ZjBlM2NhZTUxZjEwOGUzNTI4ZGFlODUzYWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.215UEehhErUhcO2Zy102KVFBCd36f2r6s5g9vc9RcWA)
> 
> Screenshot uploaded, thank you.

i have a feeling that your installation is broken. did you compile it manually?

also there is a warning at the bottom in your console from an underlying library that tells that there is some bug to be reported at their repository, that might be causing this issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The warnings are unrelated.

**Comment by b1ek** [comment]
@oToRINtI just to be clear, if you open the video on youtube.com in browser, it plays correctly, right?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Retrieved from dev chat

> only thing i can think of is that kavin mentioned a while back that Piped was getting blocked on the manifest endpoints, so maybe that users managed to get unlucky and end up on a VPN IP that a Piped instance was or had been using
> other than that, just YouTube seeing using a VPN as suspicious

> only thing i can think of is that kavin mentioned a while back that Piped was getting blocked on the manifest endpoints, so maybe that users managed to get unlucky and end up on a VPN IP that a Piped instance was or had been using
> (the error message seems to be that it's requesting the HLS manifest and getting HTML in return)

> well more realistically what is happening is that our getFormatsFromHLSManifest is getting HTML in return, so then it passes that HTML as a URL to video.js, which is why video.js is saying that it can't read the URL that looks like HTML

**Comment by oToRINtI** [comment]
I have not compiled manually, it is doing it on the official AppImage.  Yes, the live videos do play fine using the web browser.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @oToRINtI are you still facing this issue in v0.20.0?

**Comment by oToRINtI** [comment]
It seems to be fixed now! Thank you.

Sent with [Proton Mail](https://proton.me/) secure email.
