### ISSUE TITLE
Open youtube channels links

### ISSUE THREAD

**Issue by dimqua** [FreeTubeApp/FreeTube#45]
~~The app lacks a feature to manually open custom youtube links. I think there is should be a possibility to paste your own youtube link into the app.~~

**Comment by dimqua** [comment]
Oops, such feature is already exist, but I can't open links to playlists or channels.

**Comment by PrestonN** [comment]
This is planned.  Right now it has just been one of those features that I haven't been able to get to yet.  I will definitely have this included in the future.

**Comment by PrestonN** [comment]
Channels will be included in the next release.  Playlist links will be supported when playlists are included.
