### ISSUE TITLE
[Feature Request]: Update Copyright

### ISSUE THREAD

**Issue by amanr-dev** [FreeTubeApp/FreeTube#4506]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Copyright update to 2024

### Proposed Solution

Update Copyright text to 2024

### Alternatives Considered

.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This issue is opened in the wrong repo.
