### ISSUE TITLE
[Feature Request]: Change "Favorites" playlist title & icon to "Watch Later"

### ISSUE THREAD

**Issue by jasonhenriquez** [FreeTubeApp/FreeTube#4512]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The "Watch Later" button is a more familiar & welcoming label & iconography than the Favorites icon & labeling, which appears more dated.

### Proposed Solution

Rename the Favorites playlist to "Watch Later". Change the "unstarred" icon to the [`fa-clock`](https://fontawesome.com/icons/clock?f=classic&s=regular). Changed the "starred" icon to the [`fa-check`](https://fontawesome.com/icons/check?f=classic&s=solid).

### Alternatives Considered

Change the name but not the icons. Or change the icons but not the label. Or don't implement this feature.

### Issue Labels

visual improvement

**Comment by aleksejrs** [comment]
"Watch Later" is how I've been using that list because it was so easy to add to it.

**Comment by Charsy89** [comment]
If the idea is to provide a familiar experience for those migrating from YouTube, I propose removing the extra button entirely and having only the button that opens the list of playlists. This cuts down on the complexity of the UI, and really, that button is only there for convenience.

**Comment by alaestor** [comment]
<rant about youtube's UX>

> My main complaint with YouTube is a usability frustration due to incoherent design. It's the only reason I'm looking at alternative front-ends. In this case, I care much more about usability than privacy; the problem is that YouTube is offering me neither.
>
> I like to queue up a lot of videos to watch and watch them all in one go. YouTube's suggestions feed has that nice little 'Watch Later' button on the thumbnails, very much like this project's favorite star. But on the home and search result pages of YouTube, that button doesn't exist and you need to click the triple dot drop-down. Worse yet, is YouTube's notification UI that doesn't have playlist features at all!
> 
> Ingesting videos from bell notifications to a playlist becomes a 5~6 click workflow: <ctrl+lmb> to open in a new tab, <lmb> tab, <lmb> triple dot (only sometimes), <lmb> 'Save', <lmb> 'Watch Later', <lmb> to close tab.
>
> It's absurd compared to suggested videos that take _only one click_! The only alternatives are to use a third-party playlist plugin with right-click context menu options, or leaving a dozen tabs open.

</rant about youtube's UX>

I really hope this project gets fully-featured playlists **_and a very easy to use and design-coherent_** Watch Later list. 

Having UX that doesn't make the user want to jump off a bridge would be an amazing selling point for any front-end, and make it an attractive alternative to the YouTube site, even for casual and less-privacy-focused users.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Alternative has been implemented in #4825

Change the icons but not the label.
