### ISSUE TITLE
[Bug]: Pressing `i` doesn't exit from Picture-in-picture to normal window

### ISSUE THREAD

**Issue by mooreye** [FreeTubeApp/FreeTube#4516]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Pressing `i` doesn't exit from Picture-in-picture to normal window, it has no effect.

Confirmed both in AppImage and flatpak versions.

### Expected Behavior

pressing `i` on the PIP window brings back the normal player

### Issue Labels

keyboard control not working

### FreeTube Version

0.19.1 Beta

### Operating System Version

fedora 39

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Just to be sure, is this the behavior that is not working for you? Im pressing `i` here to open and close the window.

https://github.com/FreeTubeApp/FreeTube/assets/73130443/bf263a4e-d364-4ab9-9062-e8fe8fc964d0

**Comment by mooreye** [comment]
> Just to be sure, is this the behavior that is not working for you? Im pressing `i` here to open and close the window.
> VirtualBoxVM_yoXUPqs9KN.mp4

okay should have been more clear: it does work when you click `i` in the main window but not if you click in the popup (pip) window.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This unfortunately is expected because we don't have any control over the PiP window. We just use the built in one so we also cant implement this.
