### ISSUE TITLE
[Feature Request] Old YouTube-Styled or Compact Layout

### ISSUE THREAD

**Issue by sgern** [FreeTubeApp/FreeTube#452]
YouTube seems to be about to phase out the Old YouTube layout. Would it be possible to implement an option that mimics the Old YouTube layout, or at least a more compact layout?

**Comment by PrestonN** [comment]
Yep.  This is possible.  Would we want just a more compact layout or a layout that more organizes subscriptions (today's videos, yesterdays, videos from last week, last month, etc.)?

**Comment by sgern** [comment]
Maybe both? Your changelog for the most recent release did say you were planning on cleaning up the code and design a bit, so I imagine a better implementation would be possible then.

**Comment by PrestonN** [comment]
Why don't you check out the latest [blog post](https://write.as/freetube/behind-the-scenes-the-rewrite-also-code-release) about the rewrite and tell me if that looks better? ;)

**Comment by creepertron95** [comment]
Well, YouTube just completely got rid of the old YouTube layout.
