### ISSUE TITLE
[Bug]: Error on resizing window

### ISSUE THREAD

**Issue by neuroticAxolotl** [FreeTubeApp/FreeTube#4538]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Close the app while the window is maximized.
2. Open the app and start a video.
3. Resize the window
4. Video player is replaced by a black screen, with the following error: 

> The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

 Also rarely shows different errors: 

> video append of 1162251b failed for segment #2 in playlist 3-placeholder-uri-3

> video append of 1087894b failed for segment #1 in playlist 3-placeholder-uri-3

### Expected Behavior

Video continues to play.

### Issue Labels

causes crash, feature stopped working, inconsistent behavior

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 10 version 22H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.1 Beta

### Additional Information

Started happening today. Nothing has been updated to my knowledge.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Does this happen on all videos or just specific ones? Also do you have your default player quality set to `auto` or something else?

**Comment by neuroticAxolotl** [comment]
Happens with all videos. Default quality is 720p.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@neuroticAxolotl please provide a screenrecording of this behavior

**Comment by neuroticAxolotl** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 

https://github.com/FreeTubeApp/FreeTube/assets/89627453/be8af55e-1478-4964-9983-0cf6410dc463

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @neuroticAxolotl is this still happening for you on v0.20.0?

**Comment by neuroticAxolotl** [comment]
v0.20.0 fixed it
