### ISSUE TITLE
[Feature Request} Pull from LBRY version of video if available

### ISSUE THREAD

**Issue by KinoGhoul** [FreeTubeApp/FreeTube#454]
Here is an idea I believe could do several things.
1. Lessen the amount of requests to invidio.us which should help its performance and maybe reduce how much it shows up on youtubes radar of frontends to thwart.
2. Increase performance of video loading.
3. Possibly promote the syncing of content across platforms.

Not 100% sure if it would have those effects but i think its a logical argument.

The reason I suggest LBRY is because the service provides syncing with a youtube creators channel. I believe, though I may be wrong, that it may be possible to have a specific video capable of being found on both platforms if the youtube creator has an account on both platforms.

Just a passing thought. Not sure how feasible this may or may not be.

**Comment by PrestonN** [comment]
It'll be a very long time before this ever gets worked on, so I'm going to close this for now.  We can look at this again if we find time to do so.
