### ISSUE TITLE
Major rewrite/refactor checklist

### ISSUE THREAD

**Issue by TAnas0** [FreeTubeApp/FreeTube#455]
Hello,

First and foremost, thanks for this software. Highly appreciated.

Second, I am sure I read somewhere that you are eyeing a major rewrite of Freetube. We would love seeing a detailed checklist for this, since I believe this refactor can help attract new contributors, but also help new one get accustomed with the code base.

**Comment by PrestonN** [comment]
This is something that I've thought about doing.  It would likely come alongside a blog post to explain a few things.  I want to get the rewrite to a point where enough of the structure is done where potential contributors can reference what I've done to know what I want the code to look like moving forward.  It all depends on how much time I have to work on the rewrite as far as when I will have a checklist / the new code all put together (This may be sooner than later as I've had a bit of free time lately).

The rewrite will likely live in it's own repository and will migrate to the current repository when the rewrite is considered complete.

**Comment by TAnas0** [comment]
Well if you do, please keep us in the loop.

I personally wanted to contribute something, but found out that it would be quite difficult to wrap my head around the whole project. Something like rewriting to use ESLint + Standard/Airbnb would be ideal to fly across the whole code base, and to standardize the style of code.

**Comment by PrestonN** [comment]
The rewrite will somewhat be remade from scratch, while reusing existing code when able to.  I will try to work on documentation this week on what I want to achieve with this rewrite so that you and anyone else can contribute.

I've already started the rewrite by the using the [electron-vue](https://github.com/SimulatedGREG/electron-vue) boilerplate, which includes common dev-tools such as eslint, webpack, babel, etc.

**Comment by PrestonN** [comment]
@TAnas0 I wanted to let you know that the rewrite is now public.  You can check out the related blog post over [here](https://write.as/freetube/behind-the-scenes-the-rewrite-also-code-release).

The repository itself is over [here](https://github.com/FreeTubeApp/FreeTube-Vue) and includes articles on how to get started as well as a quick run down of what still needs to be done.  Let me know if you have any questions about it.
