### ISSUE TITLE
[Bug]: YouTube history import instructions in the documentation are incorrect

### ISSUE THREAD

**Issue by TonyginSLC** [FreeTubeApp/FreeTube#4558]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

On instructions located [here](https://docs.freetubeapp.io/usage/importing-history/), they break down at step number 7, unless I am missing something. Thought you might want to know.

### Expected Behavior

Accurate instructions for exporting and importing YouTube data specifically history

### Issue Labels

usability issue

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Kubuntu 23.10

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

I suppose this is not really a bug per se, but I thought it was some valuable information to pass on. Thanks.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @TonyginSLC could you open a report over at https://github.com/FreeTubeApp/FreeTube-Docs and maybe lay out how it needs to be fixed
