### ISSUE TITLE
[Bug]: Hardware video acceleration on Wayland

### ISSUE THREAD

**Issue by zestygrass** [FreeTubeApp/FreeTube#4559]
### Guidelines

- [ ] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [ ] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I'm using freetube nightly build 3821, I wanted to try out the newly merged hardware video acceleration on Linux #4532. 
It works as intended, if I'm using freetube on  xwayland but does not work if freetube is running under wayland natively.

I used the following flags to use the hardware video acceleration on linux when using it under xwayland:
```
--enable-features=VaapiVideoDecodeLinuxGL
``` 

Run it natively on wayland I added the following flags:
```
--enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --enable-features=VaapiVideoDecodeLinuxGL --gpu-context=wayland
```

### Expected Behavior

Hardware video acceleration should work as intended on wayland.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.19.1-nightly-3821

### Operating System Version

Fedora Linux 39

### Installation Method

.rpm

### Primary API used

Local API

### Additional Information

Operating System: Fedora Linux 39
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.6.9-200.fc39.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × 12th Gen Intel® Core™ i5-1240P
Memory: 31.1 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: Framework
Product Name: Laptop (12th Gen Intel Core)
System Version: A4

I have checked my drivers, I have the intel-media-drivers, Libva and Libva-utils installed. 

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
That PR was never meant for wayland, so that means wayland not working is intended behavior. Therfore this is not a bug and a feature request should be opened instead
