### ISSUE TITLE
[Feature Request]: Make player progress bar always visible in fullscreen

### ISSUE THREAD

**Issue by gobalius** [FreeTubeApp/FreeTube#4566]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I really like the thin progress bar which stays visible when watching videos, however this is only true if you are NOT watching in fullscreen.

### Proposed Solution

Add an option to enable/disable the always visible thin progress bar for fullscreen (and also non-fullscreen; maybe someone doesn't like to see it).

### Alternatives Considered

Alternative would be to make the thin progress bar always visible also for fullscreen, the same as it is otherwise.

### Issue Labels

display more information to user, improvement to existing feature, new optional setting, visual improvement

**Comment by ALOK9442** [comment]
Hello, I wanna work on it can you assign this to me?

**Comment by ALOK9442** [comment]
Hello, I wanna work on it can you please assign this to me?

**Comment by gobalius** [comment]
@ALOK9442 that's great, I don't have the permissions to assign you though.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @ALOK9442 normally i would assign you but we are currently undergoing a migration on the video player. If you would open your PR it could take weeks if not months to get it merged.

Best to wait until the migration is done.

**Comment by ALOK9442** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc okay got it, I will be waiting for the migration to be completed. Please let me know.

**Comment by ALOK9442** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc can i work on it now

**Comment by ALOK9442** [comment]
> @efb4f5ff-1298-471a-8973-3d47447115dc can i work on it now

a gentle reminder

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> @efb4f5ff-1298-471a-8973-3d47447115dc okay got it, I will be waiting for the migration to be completed. Please let me know.

I will reach out to you when the migration is done.

**Comment by ALOK9442** [comment]
Okay got it

**Comment by ALOK9442** [comment]
hey is this ticket available? I would like to work on it

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Player migration is still in progress see #4978

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
we wont be addressing this
