### ISSUE TITLE
[Bug]: Clicking "Open in Invidious" opens up a windows explorer window; nothing else happens.

### ISSUE THREAD

**Issue by mathewjcohen** [FreeTubeApp/FreeTube#4574]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. In Subscription feed
2. click a more options menu for a video in grid view
3. Select "Open In Invidious"
4. That is.

### Expected Behavior

Up until recently, it had been opening the invidious link in a new browser tab for my default browser. It randomly stopped doing this even before I upgraded to the newest version.

### Issue Labels

usability issue

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 10 Pro Version 10.0.19045

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
FreeTube just tells the operating system, in your case Windows, to open the URL. Please check that you still have a default web browser configured in your Windows system settings.

**Comment by mathewjcohen** [comment]
I do, in fact, have a default browser selected. I use Brave as my default. I've tried setting all other installed browsers to default as well with the same outcome.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I cant reproduce this behavior in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds), i tried this with FireFox and Brave.

**Comment by mathewjcohen** [comment]
It just started working again after I changed my _Current Invidious Instance_ in the General Settings tab. 🤷 

Might be something to look at?
