### ISSUE TITLE
[Feature Request]: Show next video by date from that creator

### ISSUE THREAD

**Issue by geyesborg** [FreeTubeApp/FreeTube#4575]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I would like to see a feature that when your done watching a video from a creator on the right will have the next video the creator has made. if you did not want to see the next video you could add a skip button.

### Proposed Solution

none

### Alternatives Considered

Be able to make a playlist with all of the creators videos or all the videos up until that point, when you watch the video from the playlist it removes it from the playlist.

### Issue Labels

new feature

**Comment by MarmadileManteater** [comment]
(seeing the alternatives considered)

If you are looking for a channel uploads playlist, you can turn a channel id into a playlist id for the uploads playlist by replacing "UC" with "UULF". 

**ex:**

[https://www.youtube.com/channel/`UC`E6acMV3m35znLcf0JGNn7Q](https://www.youtube.com/channel/UCE6acMV3m35znLcf0JGNn7Q)

becomes

[https://www.youtube.com/playlist?list=`UULF`E6acMV3m35znLcf0JGNn7Q](https://www.youtube.com/playlist?list=UULFE6acMV3m35znLcf0JGNn7Q)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can confirm that FT supports this so i consider this solved

**Comment by jasonhenriquez** [comment]
As an aside, I remember the last time someone mentioned the idea of integrating the UULF thing as an actual feature, there was some reason it wasn't optimal. Does anyone remember what that is or what thread I'm remembering?

**Comment by kommunarr** [comment]
Has the UULF trick stopped working specifically in FreeTube?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@kommunarr all playlists are not working rn -> https://github.com/FreeTubeApp/FreeTube/issues/9263 https://github.com/FreeTubeApp/FreeTube/pull/9291
