### ISSUE TITLE
Play by launching external application (like VLC)

### ISSUE THREAD

**Issue by palikacska** [FreeTubeApp/FreeTube#459]
The main concept of a Youtube desktop application would be not just privacy but to free yourself from the need to use Chrome/Firefox bloated video playing backend and crappy hardware acceleration compatible with nothing, especially when you're on Linux.

Since you have chosen Electron as the toolkit for your application, please add **at least an option to launch external applications like VLC Media Player (or MPV) for playing searched Youtube videos**. Native video players like VLC Media Player can use hardware acceleration properly, either on Windows, Linux or Mac. A feature like this would enable your users to play videos more smoothly and using much less resources than a JS-based player in Electron would use.

Otherwise, your application is great and way more usable than the official Youtube site. It's the video playing (the most important part) that is not better than in a browser (stuttering, lagging, tearing, using more CPU than in a native player) but that's not your fault.

**Comment by tnrs** [comment]
I also would feel myself more comfortable if external player added!

**Comment by MyCatShoegazer** [comment]
I also thought about it today.

**Comment by MyCatShoegazer** [comment]
> The main concept of a Youtube desktop application would be not just privacy but to free yourself from the need to use Chrome/Firefox bloated video playing backend and crappy hardware acceleration compatible with nothing, especially when you're on Linux.
> 
> Since you have chosen Electron as the toolkit for your application, please add **at least an option to launch external applications like VLC Media Player (or MPV) for playing searched Youtube videos**. Native video players like VLC Media Player can use hardware acceleration properly, either on Windows, Linux or Mac. A feature like this would enable your users to play videos more smoothly and using much less resources than a JS-based player in Electron would use.
> 
> Otherwise, your application is great and way more usable than the official Youtube site. It's the video playing (the most important part) that is not better than in a browser (stuttering, lagging, tearing, using more CPU than in a native player) but that's not your fault.

I started working on it. [VLC External Player](https://github.com/FreeTubeApp/FreeTube/pull/476)

**Comment by PrestonN** [comment]
Closing in favor of #418
