### ISSUE TITLE
[Feature Request]: Verify on Flathub

### ISSUE THREAD

**Issue by cassidyjames** [FreeTubeApp/FreeTube#4595]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

FreeTube is currently one of the most popular apps [on Flathub](https://flathub.org/apps/io.freetubeapp.FreeTube) in the top 100 with nearly 500k installs (congratulations!). However, it's not possible to see at a glance from Flathub (or native app store clients) that it's actually the FreeTube app [linked to from the FreeTube site](https://freetubeapp.io/#download).

### Proposed Solution

Flathub now supports [app verification](https://docs.flathub.org/docs/for-app-authors/verification); it only requires placing a `.well-known` file at your domain to show the app ID belongs to the same people who control the site itself. Then you'll get a nice **✅ Verified** indication on the Flathub site and in native app stores like GNOME Software.

### Alternatives Considered

You could choose not to verify the app, I suppose. 😄 

### Issue Labels

display more information to user

### Additional Information

I'm a volunteer at Flathub and am happy to help you out however I can.

**Comment by absidue** [comment]
The docs say that the process has to be started from a logged in FlatHub account, because of that limitation, as mentioned in this comment https://github.com/FreeTubeApp/FreeTube/discussions/4339#discussioncomment-7857594, it won't happen before the next release.

**Comment by cassidyjames** [comment]
Ah, great @absidue! I searched for issues but missed that discussion. :)

Yep, you can log into Flathub with your GitHub account; if you have commit access to the Flatpak manifest, your app will automatically show on your dashboard. If you don't have commit access, that's something we should get set up—I can file an issue on Flathub if that's the case.

Once you're logged in, you're given the verification token for your app, which can then be placed in a plain text file at `https://freetubeapp.io/.well-known/org.flathub.VerifiedApps.txt`. It's a pretty quick process and doesn't technically require making a release.

I'm happy to help out and answer any additional questions!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Lets continue this over at https://github.com/FreeTubeApp/FreeTube/discussions/4339
