### ISSUE TITLE
[Feature Request]: Message for deleted channels

### ISSUE THREAD

**Issue by red-potato-web** [FreeTubeApp/FreeTube#4596]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Trying to view removed videos makes the player UI broken.

### Proposed Solution

Showing users a message that tells them that the channel (or/and its videos) are deleted.

### Alternatives Considered

Reporting an error in form of a notification at the bottom.

### Issue Labels

new feature

### Additional Information

![Broken UI Screenshot.](https://github.com/FreeTubeApp/FreeTube/assets/154558724/ba2fcf6d-0f92-42a2-b743-35eceb2f1f48)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It should give an error. Can you provide a few example of videos you dont get an error?

**Comment by red-potato-web** [comment]
i don't think that this is deleted so there is no need for this feature.
Thank you.
