### ISSUE TITLE
[Bug]: DeArrow does not work

### ISSUE THREAD

**Issue by tonyrulez** [FreeTubeApp/FreeTube#4600]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Using latest FreeTube release, enabling DeArrow, not one title gets replaced either in subscription or player view.

Tested on 2 computers, not working on either of them.

![kép](https://github.com/FreeTubeApp/FreeTube/assets/27233005/b96dd578-7ad0-4900-a696-ac9f672c4712)
![kép](https://github.com/FreeTubeApp/FreeTube/assets/27233005/c2ff3037-6191-40f7-ad19-d57f67bd5948)

### Expected Behavior

Title should be replaced, as it is working on Firefox so DeArrow servers are up:
![kép](https://github.com/FreeTubeApp/FreeTube/assets/27233005/69d87b31-93bd-419c-82c7-4f92be7366d5)

### Issue Labels

feature stopped working

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 10 version 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is probably already solved when https://github.com/FreeTubeApp/FreeTube/issues/4320 closed

Please try the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds) and get back to us.

**Comment by tonyrulez** [comment]
Can confirm it works with this build: v0.19.1-nightly-3880 Beta

**Comment by jasonhenriquez** [comment]
Thanks for the confirmation! Closing this out now.
