### ISSUE TITLE
Option to watch "Watch later"

### ISSUE THREAD

**Issue by Hessi71** [FreeTubeApp/FreeTube#4601]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There is no option for a youtube login and so I am not able to watch videos that i put in "watch later" with the official youtube web side.

### Proposed Solution

Is it possible to add a login to my youtube account to that I can watch the videos I put in "watch later".

### Alternatives Considered

Really I d not know anything

### Issue Labels

display more information to user

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
No, that would defeat FreeTube's primary goal of letting you use YouTube a lot more privately. If you want to comprise your privacy you need to log into YouTube in a web browser.

BUT there is already an open issue that describes implementing a watch later like feature in https://github.com/FreeTubeApp/FreeTube/issues/4512
