### ISSUE TITLE
[Feature Request]: New Playlists: Implement an "All" list

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#4602]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There are multiple problems with the New playlists:
1. You can't see all videos at once.
2. You can't search for videos.
3. You can't really sort videos intuitively
4. You can't see if a video was already added (#4561 fixes this partly, but in the add menu)

### Proposed Solution

Having an "All" Playlist can be the first way to solve this.

It would:
1. show all videos that were added to any list
2. maybe make it easier to search for specific videos, as it could be used as the only search source.
3. it could be the menu to sort videos, as it includes all videos.
4. make it easier to connect it with an indicator, such as the already existing star symbole.

### Alternatives Considered

-

### Issue Labels

improvement to existing feature

**Comment by absidue** [comment]
> You can't see if a video was already added (Update add video ot playlist prompt to show presence count when adding one video #4561 fixes this partly, but in the add menu)

As playlists are allowed to contain the same video multiple times, this would just have to be a visual indicator, not a toggle button like the old favorites.

Secondly as you can now create as many playlists as you want, I'm not sure how much benefit you would get from an icon that tells you it is added to a playlist, because you have no idea which one.

**Comment by absidue** [comment]
While an all playlist does sound cool, a playlist that will inevitably be gigantic, will cause significant performance problems. See https://github.com/FreeTubeApp/FreeTube/issues/4578 and https://github.com/FreeTubeApp/FreeTube/pull/4597 for more information (TL;DR freezing for 14 seconds, on decently powerful hardware, on the watch page and any time the video changes while you are in that playlist).

Therefore, anyone wanting to implement the all list, should definitely wait until there are workarounds in place for gigantic playlists, to avoid them causing performance problems (no that linked pull request doesn't solve it, solving it will require reworking the lazy loading system, which is a bigger change).

There is a difference between a user creating a gigantic playlist and it lagging versus FreeTube auto-generating that gigantic playlist for you. If FreeTube does it, everyone would have the reasonable expectation that it should work well, so the all list should definitely wait.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
migrated to https://github.com/PikachuEXE/FreeTube/issues/66
