### ISSUE TITLE
[Bug]:  no abo list on start up with RSS

### ISSUE THREAD

**Issue by Cyborgscode** [FreeTubeApp/FreeTube#4614]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Start the app.
It should display all latest videos of creators, but it says: no videos from your ... ### 

### Expected Behavior

show list of latest videos.

### Issue Labels

feature stopped working

### FreeTube Version

0.19.1beta

### Operating System Version

Fedora 38

### Installation Method

.rpm

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.19.1beta

### Additional Information

This worked yesterday, but today the list is empty. COULD be a YT issue itself.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The bug is on YouTube's side, we can't do anything about YouTube breaking their own systems.

Hopefully it is resolved soon.

For everyone that needs to use FT right now, try the workaround. 

> For a quick fix create a profile with < 100 subscriptions and disable RSS under Subscription Settings

**Comment by doritoshave9sides** [comment]
https://github.com/FreeTubeApp/FreeTube/assets/158083919/a73034d3-3079-4fc6-94be-e89adac0aab2
I think this is exactly what I am also experiencing. Double checked and it seems like individual channels work fine.

**Comment by serpack** [comment]
> This issue only occurs when RSS is enabled by the user or forced by the application because the profile contains >= 100 subscriptions

I have only around 60 subs. Yesterday everything worked fine but today RSS feed broke :(

**Comment by treker7** [comment]
I'm currently experiencing this exact same issue. Is there a way to force disable RSS? I have a profile with 100+ subscriptions and since RSS isn't working I can't see any of my subscriptions.

**Comment by HappyApple1508** [comment]
> I'm expressing the seam exact issue, yesterday was working fine with more than 300 channels.

Yes youtube broke something.

**Comment by shumafuk** [comment]
Same here, over 200 channels yesterday worked. Today every channels are with errors.

**Comment by Dispatch3376** [comment]
This morning I got an update for FreeTube flat pack version, could that be a problem?

**Comment by ayvind** [comment]
yes, totally broke the latest subscription feed

**Comment by JamarleyHub** [comment]
> I hope YouTube hasn't canned RSS support for good and it's just a fluke.

Sincerely doubt RSS is going to go anywhere. That is like saying "JSON is an old and useless format". RSS is vitally important for news feeds and web devs continue to use and build support for it to this day because it's easy, extremely light weight, easily automated and cheap to implement with a very robust and widely supported standard. It's a ridiculously functional protocol that saves a lot of websites tons of time. It's been proclaimed "dead" since 2008, and look at it still kicking around being more important and alive than ever.

**Comment by karolyi** [comment]
#4429

**Comment by karolyi** [comment]
> > I hope YouTube hasn't canned RSS support for good and it's just a fluke.
> 
> Sincerely doubt RSS is going to go anywhere. That is like saying "JSON is an old and useless format".

Never underestimate big tech's audacity to "redefine" open standards.

Then again, they want to get rid of the freeloaders in their eyes, which they're completely free to do - also to enjoy its consequences of losing significance.

**Comment by Squint9987** [comment]
It is now loading subscriptions again for me.

**Comment by treker7** [comment]
Subscriptions are working again for me now as well. Not sure what is different...

**Comment by absidue** [comment]
> Subscriptions are working again for me now as well. Not sure what is different...

@treker7 YouTube fixed their issue, that's what changed.

**Comment by ayvind** [comment]
it's working again. Everybody go home!

**Comment by Cyborgscode** [comment]
Working again. Closing Issue.

**Comment by Cyborgscode** [comment]
x
