### ISSUE TITLE
[Feature Request]: Add multiple sub feeds, each linked to separate channel lists, to get around the 125 limit that forces FreeTube to use RSS

### ISSUE THREAD

**Issue by vF360** [FreeTubeApp/FreeTube#4617]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The title says it all. RSS feeds are not reliable, hence my request.

### Proposed Solution

There should be a tab for each subscription feed in the subscription window (preferably numbered from 1-10, with the channel list window also being numbered with a similar tab layout). This is not a duplicate of other similar proposed solutions, as I do not want multiple profiles, just multiple feeds where all saved videos go into 1 playlist.  

If I subscribe to a new channel and I already have 125 channels in my existing feed, then FreeTube should automatically create a new feed tab with a new channel list tab.

### Alternatives Considered

None.

### Issue Labels

new feature

**Comment by absidue** [comment]
@ACR-Jeff you can already split your subscriptions up into separate profiles, that should cover your categories use case.

**Comment by vF360** [comment]
> @ACR-Jeff you can already split your subscriptions up into separate profiles, that should cover your categories use case.

The problem is it takes too long to load and switch between multiple profiles, but if everything is in 1 window with multiple tabs, then switching becomes effortless.

**Comment by absidue** [comment]
@vF360 Switching rapidly would likely get you ratelimited, as you would be sending a large number of requests in a short space of time, which is the whole reason FreeTube has a 125 limit before forcing RSS to avoid ratelimiting.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We arent going to revamp the whole UI because:

- In all these years of FT being operational RSS broke down 2 times and went back up pretty fast
- You can just create profiles to get around this issue
