### ISSUE TITLE
[Feature Request]: Hardware video acceleration on Wayland

### ISSUE THREAD

**Issue by zestygrass** [FreeTubeApp/FreeTube#4621]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hardware video acceleration implementation introduced in #4532 for Linux is currently X-org only.

### Proposed Solution

Hardware video acceleration on Linux should support Wayland. In the near future, Wayland will be the default display server protocol for Linux. This change should make Freetube ready for when more DE's default to Wayland.

Distro's such as Fedora have [approved Wayland only session for their KDE Plasma spin in Fedora 40](https://fedoraproject.org/wiki/Changes/KDE_Plasma_6#Why_drop_the_X11_session?).
A similar issue was [opened for Gnome in Fedora 40](https://pagure.io/fedora-workstation/issue/395).

### Alternatives Considered

N/A

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not sure this is something we can solve as Electron also seems to have some issues https://github.com/electron/electron/issues/36633

**Comment by Revival8697** [comment]
This is impossible untill Electron 29 (Chromium 122), where [this patch](https://chromium-review.googlesource.com/c/chromium/src/+/3646633) is merged.

**Comment by zestygrass** [comment]
I suppose this would be possible once electron has official support, now we wait for stable release of electron 29 later this month.
Thanks for responding with appropriate information, it was helpful.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi all could you try the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds) and report back if this behavior is fixed. The latest nightly build contains Electron version v29.x.x!
