### ISSUE TITLE
[Bug] Missing controls on the right top corner: 

### ISSUE THREAD

**Issue by PetarMK** [FreeTubeApp/FreeTube#4624]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

There are no controls to minimaze, maximize or close the window on the top right corner.

### Expected Behavior

I can close the window only through the icon on the taskbar.

### Issue Labels

usability issue

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Sounds like you accidentally put the window in full screen, pressing F11 will get you back to a normal window.

**Comment by PetarMK** [comment]
Thanks, Absidue. It was not obvious at all. I was struggling for a very long time and got frustrated. This solved the problem. Thanks again.
