### ISSUE TITLE
[Bug]: No videos in up next/recommended

### ISSUE THREAD

**Issue by passmgrgui** [FreeTubeApp/FreeTube#4625]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open a video
2. On the right hand side there is no recommended videos showing

### Expected Behavior

The recommended videos will show

### Issue Labels

visual bug

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 11 22631.3007

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.0 Beta

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by KandiPanda** [comment]
Also seeing this, both on the release FreeTube v0.19.1 Beta on Windows 7 Ultimate, and checking with FreeTube Nightly 3898 (currently the latest nightly as I post this).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We have identified the issue and a fix on its way.

**Comment by harmonysky** [comment]
Also seeing this on the Flatpak version of FreeTube v0.19.1 Beta release on Mint 21.3.

**Comment by FishZonez** [comment]
> We have identified the issue and a fix is on its way.

Hey guys, how can I download this fix? Sorry, new to this… 🤭

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Just to be clear, the fix isn't merged yet. Thats why this issue is still open

**Comment by absidue** [comment]
Closing this issue, as YouTube seems to have fixed the issue on their end.

**Comment by ChromiumOS-Guy** [comment]
a bug with same behavior is back , such fun!
