### ISSUE TITLE
[Feature Request]: Open in Youtube Embedded Player shouldn't open new Tabs for each video

### ISSUE THREAD

**Issue by cheak1974** [FreeTubeApp/FreeTube#4628]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I am using FreeTube UI to search videos and plan to play it when on a Party. I play it with the "Open in embedded YT player" feature which works really fine, because I can push the content to a chromecast device with my chrome browser. 

What is not very handy is the fact, that for every new video a new browser tab is opened when clicking the above funktion.

### Proposed Solution

It would be really nice if the embedded player (maybe there could be a config option for that) stays the same all the time. So if you push a video to the embedded player you would not have to close the old player and switch over to the new windows anymore. Furthermore only the players Tab could be streamed.

### Alternatives Considered

not really

### Issue Labels

improvement to existing feature

### Additional Information

that's it

**Comment by absidue** [comment]
All FreeTube does it tell your operating system to open YouTube's embed URL, that passes it to your default browser. We have no control over how your browser handles the URL, we also have control over that page as it's a YouTube website and nothing to do with FreeTube.

**Comment by absidue** [comment]
Closing this, because what you are asking for is not possible.
