### ISSUE TITLE
[Feature Request]: subtitle autotranslate into selected language

### ISSUE THREAD

**Issue by edmundlaugasson** [FreeTubeApp/FreeTube#4632]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [x] This issue contains only one feature request.

### Problem Description

Subtitles are often needed to be translated into selected language - very much missing feature for now. Feature exist in web version of YouTube. This will improve already existing subtitle feature.

### Proposed Solution

The CC button could have an option to autotranslate subtitle. In Settings there could be an option to select the language for subtitle autotranslation. For subtitle, the Subtitle Settings could be created. Automatic language selection for subtitle autotranslate could be based on operating system language.

### Alternatives Considered

Manually open video in web to get subtitle autotranslation - very uncomfortable.

### Issue Labels

improvement to existing feature

### Additional Information

Actually currently the missing feature of subtitle translation renders FreeTube quite useless in case when subtitle autotranslation is needed. To be honest, it is quite often needed.
Tested FreeTube version: v0.19.1 Beta (Flatpak)
OS: Linux Mint XFCE

**Comment by absidue** [comment]
Here is what it looks like when FreeTube's locale preference is set to French and you visit the latest video on the official `@YouTube` channel: https://youtu.be/78Ok52tMB30
![screenshot](https://github.com/FreeTubeApp/FreeTube/assets/48293849/a287bca5-d082-4bf1-936f-10d88dc37ba5)
