### ISSUE TITLE
Playlists like Newpipe?

### ISSUE THREAD

**Issue by jdsys271** [FreeTubeApp/FreeTube#465]
Thanks for this amazing app!

Just wondering is there a playlist feature whereby i can create named playlists and store favorite videos in them? or "Add video to playlist"  Just like newpipe has?

Ive seen the profiles feature, and that simply adds the subscription of the Youtube User to the profile you create.
I can add videos to favorites but i have 100s of videos in different categories, how do i put them in their own named playlists?

Ive seen the requests here: https://github.com/FreeTubeApp/FreeTube/issues/25 and https://github.com/FreeTubeApp/FreeTube/issues/8  but i dont think they relate to what im saying.

**Comment by esotericDisciple** [comment]
Seconded...would also like support to create local playlists with import/export compatibility w/newpipe please...
