### ISSUE TITLE
[Feature Request]: Gecko/Firefox-based renderer/backend

### ISSUE THREAD

**Issue by cyborgcatboy** [FreeTubeApp/FreeTube#4653]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

FreeTube is an electron-based application mrow, and due to it being based on chromium and the lack of competition in the webrendering market against the chromium/blink engine, FreeTube is contributing to this near-monopoly and i think itd be better for FreeTube to be a little free-er and to have a choice.

### Proposed Solution

Introducing a gecko/firefox-based FreeTube app, perhaps using [the neutron desktop web app tool](https://github.com/gamingdoom/neutron), although im not sure that'd quite work for freetube. the compatibility layer for electron on gecko, [positron](https://github.com/mozilla/positron) has been discontinued so thats probly not a viable option mrrp so 

### Alternatives Considered

It may be easier to make a web-server build of FreeTube (forgive my ignorance ive never used electron mrrp ><) that can then be connected to by a normal webbrowser as something like a localhost service (or another kind of selfhostable service mrowz), and then other people can bundle the server application with whatever webrendering engine they want.

### Issue Labels

new feature, support for external software

### Additional Information

this is more of a request-for-comments than a i-want-this-now, and i wanna help drive discussion about this, but it is a feature i am quite interested in meow!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://docs.freetubeapp.io/faq/#electron-is-bad-please-use-something-else

**Comment by cyborgcatboy** [comment]
aw man howd i miss that DX, feel free to close the issue then mrows..
