### ISSUE TITLE
[Bug]: Copy link to the tab you are on on an channel page (Playlists → /playlists)

### ISSUE THREAD

**Issue by aleksejrs** [FreeTubeApp/FreeTube#4655]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to a channel page, like https://www.youtube.com/channel/UCs6KfncB4OV6Vug4o_bzijg
2. Click "PLAYLISTS"
3. Click "Share Channel"
4. Click YouTube → Copy Link
result: https://www.youtube.com/channel/UCs6KfncB4OV6Vug4o_bzijg

If I want to download all the videos that are in a playlist, and I give that URL to yt-dlp, it will download all videos from the channel without playlist data, and it will be difficult to sort them without redownloading.

### Expected Behavior

Copy https://www.youtube.com/channel/UCs6KfncB4OV6Vug4o_bzijg/playlists

On YouTube, step 2 leads me to https://www.youtube.com/@techlore/playlists, which is a synonym for https://www.youtube.com/channel/UCs6KfncB4OV6Vug4o_bzijg/playlists

### Issue Labels

usability issue

### FreeTube Version

v0.19.1-nightly-3875 Beta

### Operating System Version

Linux

### Installation Method

.deb

### Primary API used

Local API

### Additional Information

The issue tracker said "Bug Report" is to "Report an issue or *unexpected behavior* that occurs within the application"

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is expected behavior and not a bug. You should open a feature request for this
