### ISSUE TITLE
[Feature Request]: Disable video

### ISSUE THREAD

**Issue by thomas-mc-work** [FreeTubeApp/FreeTube#4659]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Often I use FreeTube only to listen to music. Thus, downloading the video part would be a waste of resources.

### Proposed Solution

Add on option to disable the video part of the stream, while using the best possible audio stream.

### Alternatives Considered

Minimization of the video quality would also lead to less wasted resources.

### Issue Labels

new optional setting

**Comment by jasonhenriquez** [comment]
You're in luck! Under Player Settings, change "Default Video Format" to "Audio Formats".
