### ISSUE TITLE
[Feature Request]: Full-screen option without activation of playback bar.

### ISSUE THREAD

**Issue by riverpiers** [FreeTubeApp/FreeTube#4666]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

On YouTube and other players, there is a full-screen option available, namely: ctrl+shift+lmb (left mouse button). This allows for watching videos without accidental cursor movements or key presses, but it disables any overlays like subtitles. It's useful for taking screenshots, especially when browsing individual frames with the ',' and '.' keys. When using the system screenshot shortcut: win+printscreen, the playback bar pops up, which is visible in the screenshot. The FreeTube screenshot icon bypasses this bar (OK), but when trying to use the keyboard shortcut 'u', it depends on which last player/window element was active, and the first screenshot may not appear. To be sure, you need to press 'u' twice to ensure it's saved.

### Proposed Solution

Adding a shortcut (on/off) to hide the playback bar in full-screen mode, or optionally in the player's focus/appearance settings.

### Alternatives Considered

Activation of the menu shortcut (ctrl+shift+lmb/left mouse button) with the option to select the clean full-screen mode.

### Issue Labels

ease of use improvement, improvement to existing feature, new feature, new keyboard shortcut, new optional setting, visual improvement

**Comment by absidue** [comment]
Just to be clear that is an option offered by your web browser not YouTube, which full screens just the video, which is why you don't see anything other than the video.

**Comment by riverpiers** [comment]
There exists a further dependency on the "Schrödinger's screen" shortcuts, which do and do not do what you want.
The shortcut 'u' does not save overlays, such as subtitles when, for example, you're learning another language, or when you want to have information plus text/subtitles for an image/screen capture as context, then the use of the system shortcut (win+prtscr) is necessary: 1. for the overlaid subtitles to be included, 2. a playback bar pops up and covers the text when there is some text at the bottom of the screen or other details you want to capture. There is a contradiction here between what you want to capture as seen at the given moment, and the result of what you can actually capture after using the specific keyboard shortcut. None of the shortcuts in different situations (subtitles/playback bar) work like: WYSIWYG.
I found a temporary solution in FreeTube, in such situations in the code inspection: 1. ctrl+shift+i, 2. ctrl+shift+c (click under the total video time to capture the frame with the entire playback bar), 3. On the highlighted code fragment: div class=”vjs-control-bar”.., lmb(left mouse button)/’hide element’.

Clarification regarding menu keys: I confused left/right keys, I have a tablet with a stylus and the key assignment has been changed. It should be ctrl+shift+rmb (right mouse button) with the option of full-screen without overlays.
In my case, the shortcut works on YT in Firefox. It is only visible after playback has started, and after a slightly faster x2 click (RMB). Without playback starting, the default YT menu is visible, and RMBx2 shows a different menu. In principle, the shortcut is available on any HTML5 player, but the "default" menu is limited except for some options and usually hidden behind transparent frames, sometimes with 5 frames, so as not to activate this menu. In the past, in the flash player, there was always an option to download the video when there was no video splitting into separate files/audio/video portions. HLS (HTML Live Stream). On some players, you can still download the video in this way. Frames can also be removed (besides developer tools) using a plugin, e.g., ublock and assigning a shortcut for the option to remove page elements, (available in Firefox/Chrome/Opera and others), as a temporary rule on the loaded page.

BTW: Is the set time skip "multiplied" by the playback speed? Because the skip time does not match when the speed is different from x1. Sometimes it jumps over a minute at x2+ with 15s set.

**Comment by absidue** [comment]
The screenshot button and the `u` keyboard shortcut, ask the video player for the currently visible frame of the video stream and save that. The subtitles are overlays, they aren't burned into the video stream, which is why they are understandably not in the image that you saved. It takes a screenshot of the video not the player, as that wasn't clear to you, maybe we need to clarify that in a tooltip next to the setting. If you want part of the player saved in the image, such as the subtitle overlays, then yes you need to take an actual screenshot with the tools offered by your operating system.

The player UI hides itself when you are idle, by pressing keys on your keyboard you are telling FreeTube that you are interacting with it again, which is why it display the player buttons and progress bar again.

As it sounds like you are using Windows, instead of using <kbd>Win</kbd>+<kbd>PrntScrn</kbd>, you should be using the `Snip & Sketch` (which you can trigger with <kbd>Win</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd>) or `Snipping Tool` system utilities.

Yes the skip time is multiplied by the playback speed, the same as what YouTube does.

**Comment by riverpiers** [comment]
Yes, it's possible to do it this way, but when you want to take screenshots "on the fly," without pausing every time and selecting the appropriate mode/keyboard shortcut for taking a screenshot, it's a hindrance. FreeTube limits the freedom to take screenshots as they appear, and on Windows, pressing (win+) in the case of YouTube, such a situation does not occur. The playback bar is not activated in full-screen mode when the shortcut does not apply to it, and even when it does, it only appears after moving the cursor. In FreeTube, the freedom to take screenshots on the fly is limited when you want more than one with direct saving to a folder without confirming anything.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Does v0.22.0 solve this for you?

**Comment by riverpiers** [comment]
v0.22.0 solves this problem, the playbar does not activate every time 'u' or win+prtscr is pressed. In lower versions, this can be bypassed by activating the area under the player, clicking or holding the click, moving the cursor slightly and activating playback by pressing 'k'.
