### ISSUE TITLE
Dark theme toggle

### ISSUE THREAD

**Issue by dimqua** [FreeTubeApp/FreeTube#47]
I think [this behavior](https://github.com/FreeTubeApp/FreeTube/blob/d222f3edb47cd348a54add544c9877ee320de39a/src/templates/settings.html#L8) is confusing:

![](https://i.imgur.com/JXsbMEV.png)

You may think that light theme is enable, but it's not.

**Comment by PrestonN** [comment]
I was trying to have a dark theme toggle similar to how Google does theirs.  It looks like Google doesn't change the text as you toggle between themes.  I will include a similar behavior in the next release.

**Comment by PrestonN** [comment]
This has been fixed.
