### ISSUE TITLE
feature request | add sponsor block

### ISSUE THREAD

**Issue by MLWALK3R** [FreeTubeApp/FreeTube#471]
https://sponsor.ajay.app/

**Comment by stemy2** [comment]
It may cause some ethical issues, since sponsoring is the unique source of income for many creators.

**Comment by connervieira** [comment]
> It may cause some ethical issues, since sponsoring is the unique source of income for many creators.

Thats potentially true, but I'd argue it still makes sense to have it. There are quite a few creators who have sponsor spots that are more than a minute out of a 5 minute video. I don't want to sit through something like that, but I'd gladly whitelist channels like LTT who are concise and honest about sponsored segments.

Also, this doesn't significantly differ from blocking advertisements, as sponsored segments aren't funded by views, they're funded by who actually uses the product sponsored.

**Comment by wangxu94** [comment]
Content creators will still get paid by the sponsors. This is no different from manually skipping the sponsored segments.

**Comment by alex9099** [comment]
Also FreeTube (as well as newpipe) AFAIK don't count views, so ethics are broken right in there. Besides that... It can be opt-in, that way it wont break any "ethics"

**Comment by alien2003** [comment]
> It may cause some ethical issues, since sponsoring is the unique source of income for many creators.

Creators of YouTube will gain their money anyway

**Comment by EmeraldSnorlax** [comment]
> It may cause some ethical issues, since sponsoring is the unique source of income for many creators.

having my data sold and harvested is already an ethical issue.

besides, i dont think freetube submits view counts, or even loads ads to begin with, so they arent missing out on much

if its **really** that much of a concern then i guess you can make it opt in

**Comment by pablodekota** [comment]
I don't know if the Dev even has this on his to-do list, but would be very cool to have, either someone integrates it or the dev himself, would like to get a update on this from the dev

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://github.com/FreeTubeApp/FreeTube/pull/1130 closes this issue.
