### ISSUE TITLE
[Bug]: Hide videos from channels option is messed up

### ISSUE THREAD

**Issue by fabbadabbawow** [FreeTubeApp/FreeTube#4710]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

There are two problems:

1. Option to hide channel is missing from drop down list when clicking the three little dots by a video (sorry, I don't know what it's called).
2. Channels that have been previously added to the 'Hide videos from channel' list in the Settings menu no longer display the channel icons, and instead look like raw code.

Sorry, I can't add screenshots.

### Expected Behavior

When I click on the three dots beside a video, one of the options in the drop down menu should allow me to block that channel. The blocked channel list on the Settings page previously showed the name and icon of the channels.

### Issue Labels

feature stopped working, usability issue

### FreeTube Version

0.19.2

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

I don't know. It was one of the nightly builds.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Were you on a recent nightly build before you switched to 0.19.2. If the answer is yes, then that is entirely expected, the nightlies contain new features like showing the channel icon and showing the option in the drop down, as 0.19.2 was just a bug fix release, so new features like that were not included. You need to wait for 0.20.0 if you want to the new features and all the other bug fixes.
