### ISSUE TITLE
[Bug]: packaging issue:  the date and time stamps of archived files are missing in the 7z archives!

### ISSUE THREAD

**Issue by j4reporting** [FreeTubeApp/FreeTube#4711]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

This is not an issue with the application but  packaging of  the 7z release archives

e.g output  of 7z.exe  l archive.7z

```
Path = freetube-0.19.2-win-x64-portable.7z
Type = 7z
Physical Size = 63003912
Headers Size = 1122
Method = LZMA2:26 LZMA:20 BCJ2
Solid = +
Blocks = 2

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
                    D....            0            0  locales
                    D....            0            0  resources
                    ....A       129653     14991579  chrome_100_percent.pak
                    ....A       179934               chrome_200_percent.pak
                    ....A     10462432               icudtl.dat
                    ....A         1096               LICENSE.electron.txt
                    ....A      6813275               LICENSES.chromium.html
                    ....A       348321               locales\af.pak
                    ....A       564794               locales\am.pak
                    ....A       616572               locales\ar.pak
                    ....A       647156               locales\bg.pak
                    ....A       832270               locales\bn.pak
                    ....A       394131               locales\ca.pak
```

the same for the zip archive
```

Path = freetube-0.19.2-win-x64-portable.zip
Type = zip
Physical Size = 95086509

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2024-02-23 23:30:30 ....A       129653       121107  chrome_100_percent.pak
2024-02-23 23:30:30 ....A       179934       168292  chrome_200_percent.pak
2024-02-23 23:30:30 ....A      4891080      2048841  d3dcompiler_47.dll
2024-02-23 23:30:30 ....A      2767872      1160468  ffmpeg.dll
2024-02-23 23:30:34 ....A    157605888     67582447  FreeTube.exe
2024-02-23 23:30:30 ....A     10462432      4315906  icudtl.dat
2024-02-23 23:30:30 ....A       484352       205847  libEGL.dll
2024-02-23 23:30:30 ....A      7535616      2755719  libGLESv2.dll
2024-02-23 23:30:30 ....A         1096          626  LICENSE.electron.txt
2024-02-23 23:30:30 ....A      6813275       811781  LICENSES.chromium.html
```

### Expected Behavior

files should have date and time stamps  saved in archive

### Issue Labels

usability issue

### FreeTube Version

0.19.2

### Operating System Version

all 7z archives

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Have the missing timestamps caused any actual issues for you or is this just something you've observed that bothers you?
