### ISSUE TITLE
[Bug]: new version deleted all of my data! no pre-warning of replacing all files in install folder

### ISSUE THREAD

**Issue by sqrxz** [FreeTubeApp/FreeTube#4714]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1-I had a need to keep my profile folders and sync it across devices, so I had employed the shortcut workaround to make it Freetube portable, with the /data subfolder as the data folder
2-I noticed the constant errors when watching anything, so I clicked the prompt to download the new version, I got the installer, installed it.
3-all of the data has been erased, all of my subscriptions and categories for the subscriptions are gone, as well as the playlists.
4-I tried copying and pasting the /Data subfolder to appdata roaming to confirm that there were no subscriptions, it's all still blank.

### Expected Behavior

some kind of warning that it would erease all of the contents of the chosen install folder, or a backup of what was in there.

### Issue Labels

data loss

### FreeTube Version

v0.19.2

### Operating System Version

Win10 

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by OmarLipton** [comment]
I had the same problem but "fixed" it by downgrading to the latest 19.1 beta nightly
https://github.com/FreeTubeApp/FreeTube/actions/runs/8038266582.
Installed ver 3994 and all playlists and data returned. 
This version doesn't seem to have the local API error either.

**Comment by absidue** [comment]
@sqrxz I'm sorry to hear that you lost your data. That being said we don't recommend changing the location of where data is stored. Instead of using the installer, you should download the zip file, then you are in control of how and where FreeTube is installed.
