### ISSUE TITLE
[Feature Request]: mark video as watched

### ISSUE THREAD

**Issue by mati-gotta** [FreeTubeApp/FreeTube#4728]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The functionality to mark video as watched (or uncheck it) is extremely useful, and I find it very inconvenient to have to go to the three-dot menu on the video card to drop down the options to choose this very useful feature. Considering that one repeats this action many times, those extra clicks are too many.

### Proposed Solution

I propose that such a function be an icon on the video card, an eye to mark it as seen and become a crossed out eye to unmark it.

### Alternatives Considered

Otherwise, another solution would be to add a keyboard shortcut to do the same, but it would be necessary to read that the mouse is located on one card and not on another, so that when applying the shortcut the state of the video we really want to catalog is modified.

### Issue Labels

improvement to existing feature

### Additional Information

I would like to point out that this would contribute to maintaining a much cleaner interface, especially necessary for users who consume a lot of content.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
2 clicks vs 1 click? This is definitely a wont implement as the video card is reserved for things that really need quick access like the upcoming add to playlist feature or the current favorite button
