### ISSUE TITLE
NewPipe Style Custom Feeds?

### ISSUE THREAD

**Issue by denemier** [FreeTubeApp/FreeTube#473]
I just downloaded freetube and i saw that you already support newpipe integration for import export subscriptions.

can you please add custom feeds option like newpipe
**so a channel can be added to multiple feeds like:**
-all news (german, french, english)
-only german news
-only french news

I think its a good direction freetube/newpipe import/export sync, so if user wants alternative technlogie for
**1-** freetube alternative on android = can download newpipe
**2-** newpipe alternative on windows = can download freetube

it would be nice too see developers of both side (freetube and newpipe) fully integrate basic features with these two softwares like:
-subscriptions (already)
-playlists
-custom feeds

**Comment by denemier** [comment]
i just saw profile option in freetube, it is like newpipe but can you fetch newpipe's feed export file (as db not json file)
and integrate it every
feed as -> profile in freetube


so can we please use multiple profiles from newpipe's feed system in the future?

**Comment by PrestonN** [comment]
The export that NewPipe provides doesn't include the feeds that are also created.  If they update their export file then it would be no problem to make the change on my end as well.

Since this can't be done though, I'm going to close this issue.
