### ISSUE TITLE
[Bug]: GPU load in background

### ISSUE THREAD

**Issue by riverpiers** [FreeTubeApp/FreeTube#4734]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When the window is minimized there is still GPU processing, where in such a situation e.g. in a web browser there is no background image processing.
[Edit]: Occurs when 2 program windows are minimized, regardless of whether the second is video or "empty" without video, such as a settings tab or a new window (ctrl+n).
[Edit2]: More details: 1. The order of the windows does not matter and whether it is the default tab(subscriptions) of the new window (ctrl+n), 2. It seems that the problem is only with 50/60fps video, even though the video is minimized. GPU activity remains 10+%.

### Expected Behavior

No GPU usage when the window is minimized and I am only listening to audio.

### Issue Labels

usability issue

### FreeTube Version

v0.19.2 Beta

### Operating System Version

Windows 10 (19045)

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.2 Beta

### Additional Information

I don't know if the situation occurred in the previous version.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isn't a bug but expected behavior as something like this isn't implemented, see https://github.com/FreeTubeApp/FreeTube/issues/1405

**Comment by riverpiers** [comment]
Further info: When I go lower with resolution, e.g. 720p, background GPU usage drops, but there is still ~5%. Interestingly, with video without the 50/60fps option, when I go down to the same resolution, i.e. 720p, the GPU usage is 0% with the window minimized/background video.
Ok. duplicate..
