### ISSUE TITLE
FreeTube ignores default browser

### ISSUE THREAD

**Issue by B0pol** [FreeTubeApp/FreeTube#474]
Hi,
My default browser is Firefox, but I've also installed brave browser, which is chromium based
Whenever I click on a link in FreeTube, it opens brave browser instead of my default browser.
The installed FreeTube version is 0.7.2.

**Comment by PrestonN** [comment]
I haven't had any issues with this in the rewrite.  There's nothing specific in the app itself that determines your default browser as it goes with whatever your OS is set to.

If this shows up in the rewrite then feel free to reopen.
