### ISSUE TITLE
[Feature Request]: Loading percentage bar

### ISSUE THREAD

**Issue by eshsdhsd** [FreeTubeApp/FreeTube#4745]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When Videos load All I see is this and sometimes it takes time to load.
![Clipboard01](https://github.com/FreeTubeApp/FreeTube/assets/79751239/c7f0edc3-e8d5-4aa8-99ea-ab9254cb90f5)

### Proposed Solution

At least have a progress bar when loading so I know the percentage of loading

### Alternatives Considered

Option to disable loading animation if

### Issue Labels

display more information to user, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Retriwvwd from dev chat:

> If we had any way of determining any sensible amount of progress sure, but unlike the subscription page or data import where we know exactly how many items we are processing and just bump up the progress bar when we finish processing an item, we don't have anything like that for the watch page.

> The closest thing we could do would be bytes downloaded but especially with the Invidious API, that would only cover a tiny amount of the actual waiting time (downloading the few 10s of kbs is quite fast), as most of it is waiting for Invidious to do it's communication with YouTube and process YouTube's response.

I will close this issue as this is definitely a wont implement
