### ISSUE TITLE
[Feature Request]: Select all text when focusing the search bar

### ISSUE THREAD

**Issue by 9mdv** [FreeTubeApp/FreeTube#4746]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently it doesn't select all text when you focus the search bar via Ctrl+L, only if you tab out and in.
Most of my keyboard-driven use case is as follows:
1. Copy a YouTube link from somewhere.
2. Go to FreeTube and press Ctrl+L to focus the search bar.
3. Press Backspace (slow) or Ctrl+Backspace (faster) to clear the previous link or search query.
4. If there's multiple words, I have to press Ctrl+Backspace for every word.
5. Only then can I paste the link to watch the video.

### Proposed Solution

It would be nice if it auto selects all text when you focus the search bar so that it's only one backspace away from clearing.

### Alternatives Considered

Another solution would be to use Ctrl+U to clear all text even if it's not selected. This is implemented in YouTube and pretty much every HTML input I've encountered but doesn't seem to work on FreeTube.

### Issue Labels

ease of use improvement, new feature, new keyboard shortcut

### Additional Information

https://github.com/FreeTubeApp/FreeTube/assets/12945959/ebe5f7b3-281d-4c41-ad53-3ba873be2d6a

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
`Ctrl+L` Does also select all text for me on Windows. On what OS is this recorded on?

**Comment by 9mdv** [comment]
Arch Linux with kernel version 6.6.20 LTS, running i3 window manager. I've tested the [AUR package](https://aur.archlinux.org/packages/freetube-bin) and the portable version in the [official release](https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.19.2-beta).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
So your PR addresses this for Linux users?
