### ISSUE TITLE
[Bug]: Error: [UNPLAYABLE] Video unavailable: The uploader has not made this video available in your country

### ISSUE THREAD

**Issue by Cyborgscode** [FreeTubeApp/FreeTube#4748]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

API: Local API

since 2 weeks i can observe this message:

"Error: [UNPLAYABLE] Video unavailable: The uploader has not made this video available in your country"

it may be true for video from different countrys, but today it started for one in my country and **without** the usage of a VPN to hide my true identity, it's a bug. It's unclear who makes the mistake, could be YT or FreeTube. Please invest.

Video: https://youtu.be/O9ZePY0VD-0
Location: Germany
Updater: Germany

### Expected Behavior

normal playback.

### Issue Labels

content not loading

### FreeTube Version

0.19.2beta

### Operating System Version

Fedora Linux 38

### Installation Method

.rpm

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
That error comes from YouTube and is correct, according to YouTube's official API the uploader has restricted the video to only be viewable in Austria. You will get the same error message if you view the video on YouTube itself.

```json
regionRestriction": {
  "allowed": [
    "AT"
  ]
}
```

You can see it for yourself by clicking `Execute` on the API explorer here:
`https://developers.google.com/youtube/v3/docs/videos/list?apix_params=%7B%22part%22%3A%5B%22contentDetails%22%5D%2C%22id%22%3A%5B%22O9ZePY0VD-0%22%5D%2C%22fields%22%3A%22items%2FcontentDetails%2FregionRestriction%22%7D`

**Comment by absidue** [comment]
Closing as this isn't a FreeTube or a YouTube bug, we cannot do anything from our side about uploaders adding region restrictions to their videos.
