### ISSUE TITLE
Can we have an option to start videos from the start, not remember where we were?

### ISSUE THREAD

**Issue by annadane** [FreeTubeApp/FreeTube#475]
There's a disable history feature but I think that's for video history, not history of the video, if you get what I mean. I don't want videos to remember where I was, I want them to start from the beginning

**Comment by PrestonN** [comment]
For now, disabling history will disable the ability to save where you last left off in the video and will always start from the beginning.  This won't work retroactively with videos already watched unless you also clear your history.

I'll add an option in the rewrite to allow you to toggle this separately.
