### ISSUE TITLE
[Bug]: NewPipe Subscription Import Fails with No Feedback (Workaround Found)

### ISSUE THREAD

**Issue by terminal-root** [FreeTubeApp/FreeTube#4754]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

NewPipe `0.25.2`

1. Go to `Subscriptions > Triple-dot Menu > Export to > File
2. Export the json file and transfer it to PC

FreeTube `v0.19.2`

1. Go to `Settings > Data Settings`
2. Press `Import Subscriptions`
3. Select NewPipe subscriptions json file

The application does not respond in any way. No network requests are made nor errors shown, but none of the subscriptions are imported.

I've used this feature before and it worked great. I've seen some talk on looking through your subs for deleted/banned channels, but I have ~150 subs, so I figured I'd ask before committing that time.

### Expected Behavior

Subscriptions are imported and their videos show up in the subscriptions page.

### Issue Labels

feature stopped working

### FreeTube Version

0.19.2

### Operating System Version

Artix Linux

### Installation Method

.AppImage

### Primary API used

Local API

### Additional Information

I tried appimage releases back to v0.17.1 and all them behaved the same other than the extra menu when you press import in the earlier v0.17.1

Hm. I prettified (de-minified) the json file with `jq` and it worked... Maybe a NewPipe export problem then or something with FreeTube's import function?

Here is the console error when I import the minified version.

```
renderer.js:2 VIDEOJS: WARN: using Vhs.BANDWIDTH_VARIANCE is UNSAFE be sure you know what you are doing
(anonymous) @ renderer.js:2
renderer.js:2 SyntaxError: Unexpected non-whitespace character after JSON at position 15886 (line 1 column 15887)
    at JSON.parse (<anonymous>)
    at renderer.js:2:1569396
    at Array.forEach (<anonymous>)
    at r.importSubscriptions (renderer.js:2:1569164)
Le @ renderer.js:2
Ae @ renderer.js:2
Ie @ renderer.js:2
(anonymous) @ renderer.js:2
Promise.catch (async)
Ee @ renderer.js:2
i @ renderer.js:2
Ee @ renderer.js:2
t.$emit @ renderer.js:2
click @ renderer.js:2
Ee @ renderer.js:2
```

I suppose now this issue doesn't necessarily need to stay open, but I'll post it so others with the same issue can find it. I'll leave choosing whether to close this now up to the maintainers.

I don't feel comfortable publicly posting the full json of my subscriptions lol, so, if a dev would like them I can privately send them.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This looks like an issue with NewPipe's export, the error message is saying that the JSON is invalid (I would be very surprised if chromium's JSON parser were the issue here, so this doesn't seem like a FreeTube bug):
> Unexpected non-whitespace character after JSON at position 15886 (line 1 column 15887)

**Comment by terminal-root** [comment]
@absidue; Seems to be so. Exported again today with ~2 more subscriptions and it imported with no problems. Don't think this issue needs to stay open.
