### ISSUE TITLE
[Bug]: Ugly UI/UX degradation

### ISSUE THREAD

**Issue by Flashwalker** [FreeTubeApp/FreeTube#4759]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

In the last night releases 1-column playlists was implemented instead of a single favorites/bookmarks grid list.

When favorites were in the form of a bookmark grid list, recently added videos were at the top of the list, and if you scroll all the way down, you can access the oldest ones.

Now if you have a lot of videos in your playlist, it's close to impossible to access the oldest ones.
Watch video:

https://github.com/FreeTubeApp/FreeTube/assets/2188215/35b227f6-43cc-40bb-9ba5-01e7b0015be0

Functionality is literally broken.

Recent nightly releases have added a button at the bottom of the playlist, increasing the clicks hell UI/UX.

### Expected Behavior

Please make it so that the user can choose between the current ugly UI/UX and the previous one. So that the user can simply switch any bookmarks playlist to a grid view where recently added videos are placed at the top.

### Issue Labels

usability issue

### FreeTube Version

v0.19.1-nightly-4047 beta

### Operating System Version

Ubuntu 22.04

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.18.0-nightly-3004

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Nightly builds means that they are the latest changes from our development branch. That means we are still developing. We wont go back to a single bookmark page view. However we will implement grid view for playlist at a later point in time. This is already documented elsewhere. 

Closing as this isnt a bug and grid view is already documented.

**Comment by Flashwalker** [comment]
> Nightly builds means that they are the latest changes from our development branch. That means we are still developing. We wont go back to a single bookmark page view. However we will implement grid view for playlist at a later point in time. This is already documented elsewhere.
> 
> Closing as this isnt a bug and grid view is already documented.

I did this
![2024-03-13_17-43-47](https://github.com/FreeTubeApp/FreeTube/assets/2188215/e432bb27-b00e-40bd-96a6-d3c747f8965e)
in a couple minutes. It was that easy

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Do you want to create a pull request for it?

**Comment by Janaue** [comment]
I concur with OP. I have 900 videos in the legacy playlist so the official display which is vertical is just unusable lol. The legacy UI was perfect for the playlist.

**Comment by absidue** [comment]
> Recent nightly releases have added a button at the bottom of the playlist, increasing the clicks hell UI/UX.

That was added to avoid FreeTube freezing completely for 15 seconds when you open a playlist, so while you may not like it the alternative is horrible performance problems.

**Comment by absidue** [comment]
@Janaue

> I concur with OP. I have 900 videos in the legacy playlist so the official display which is vertical is just unusable lol.

If you are struggling to find your videos in a 900 video list, may I recommend using the search instead of scrolling through all of the videos looking for them manually.

> The legacy UI was perfect for the playlist.

The old UI was objectively worse, if you want the worse UI with less functionality, you are welcome to downgrade to 0.19.2 instead of using pre-release versions of FreeTube.

**Comment by Flashwalker** [comment]
> Do you want to create a pull request for it?

I can, it's just a few css flex declarations.
But you already have the proper grid layout from the old UI, so why not just reuse it?

**Comment by Flashwalker** [comment]
Thanx for adding sorting to the list
