### ISSUE TITLE
symlinks for .db files overwritten on startup

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#477]
Hi friends,
I m on Linux and I'd like to have the .db files in another folder than ~/.config/FreeTube/ so I ve created symlinks.
Unfortunately on each restart of FreeTube is overwrites the .db file with the .db file pointed to by the symlink.
Would it be possible to change this behaviour and preserve the symlink please? :-)
Cheers,

**Comment by PrestonN** [comment]
This happens because FreeTube creates new .db files if it detects them as missing.  This is done automatically with the module I use and can't be changed.

I'm going to close this in favor of the feature to determine your .db location within the app itself.

**Comment by dbogdanov** [comment]
I am having the same problem. Custom .db location would be great.
