### ISSUE TITLE
[Feature Request]: download path

### ISSUE THREAD

**Issue by Augusto7743** [FreeTubeApp/FreeTube#4785]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Thanks for added the feature for download videos.
However each time is done an download open the download window to select the path being the an default startup path, but in next download return to default path.
In Linux the default download path is /home.

### Proposed Solution

An option to select an alternate download path avoid that problem.

### Issue Labels

new feature

### Additional Information

Thanks for reading my topic.
Have an nice week.

**Comment by absidue** [comment]
If you turn off `Ask for download path` in the `Download Settings` in FreeTube's settings, you can pick a location where you always want the downloads to be saved, that way if won't ask you for the location every time.

**Comment by Augusto7743** [comment]
Thanks very much for your reply !
Have an nice week.
