### ISSUE TITLE
[Bug]: Videos not loading in Subscription feed.

### ISSUE THREAD

**Issue by DerpDerpingtonIsHere** [FreeTubeApp/FreeTube#4790]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to Subscriptions
2. All channels show as "Channels with Errors" which you are able to see their pfp's and click them to go to the channels.
3. This is what it is showing. https://imgur.com/a/9BAIQRi However, sometimes it will load a single channels videos but from months ago? Not sure why that is happening.

### Expected Behavior

Show current videos in the subscription feed.

### Issue Labels

content not loading

### FreeTube Version

v0.19.2 Beta

### Operating System Version

Windows 11 23H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

I have tried using different invidious API's as well as local. Local seems to be the one having the issue but invidious seems to not want to load the thumbnails for videos.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by hjc25** [comment]
Same here. Windows 10 22H2.

![image](https://github.com/FreeTubeApp/FreeTube/assets/28969068/630219fa-29c3-4e06-b261-ff1c59a4a002)

**Comment by pentacord** [comment]
same here

**Comment by XModxGodX** [comment]
Also an issue on Linux guessing it's server related.

**Comment by John-foobar-Doe** [comment]
I got the same issue for profile with >100 channels, which will use RSS to fetch the feeds. For profile with less than 100 channels, there is no issue. So this is likely a problem with YouTube's RSS feed.

**Comment by vonhyd** [comment]
Also having the same issue, as well as on Newpipe so I'm assuming its an issue with the RSS feed. Newpipe works fine with the RSS setting turned off. Is there a way to force RSS off with a large subscription list?

**Comment by hutonahill** [comment]
also experiencing this issue

**Comment by ACR-Jeff** [comment]
Appears to have been resolved, 
I switched from local API to invidious instance, Refreshed, Changed to another invidious instance then back to local API, Refreshed again and it's back to normal. 
Not sure if that solved it or the issue was solved on YT's side.

**Comment by John-foobar-Doe** [comment]
> Appears to have been resolved, I switched from local API to invidious instance, Refreshed, Changed to another invidious instance then back to local API, Refreshed again and it's back to normal. Not sure if that solved it or the issue was solved on YT's side.

I didn't switch to Invidious API but this problem no longer appears, so it must be that YouTube fixed its RSS feed issue.

**Comment by hjc25** [comment]
This is not yet fixed. Swapped to Invidious, reloaded, back to Local, reloaded, all are channels with errors.

![image](https://github.com/FreeTubeApp/FreeTube/assets/28969068/5e3d7b6a-31ca-475e-838d-b00d65b5729d)

**Comment by zombiemimic** [comment]
> Appears to have been resolved, I switched from local API to invidious instance, Refreshed, Changed to another invidious instance then back to local API, Refreshed again and it's back to normal. Not sure if that solved it or the issue was solved on YT's side.

followed this advice, no luck, I'm still met with the wall of channels with errors.
![image](https://github.com/FreeTubeApp/FreeTube/assets/71949337/87cb84b1-9113-4995-9fb8-796ad32c2699)
unsure if it's a me problem or a YT-side problem

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
YT is experimenting again and everyone that is using RSS is affected. RSS will probably return to its normal state in a couple of hours.

To mitigate this in the meantime this is what you can do:

- create a profile that has under 100 subscriptions so FT wont force RSS on you
- make sure RSS is disabled in the Subscription settings
