### ISSUE TITLE
[General Question]: can I install Freetube on a chromebook? 

### ISSUE THREAD

**Issue by siemvaessen** [FreeTubeApp/FreeTube#4791]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hi there, no feature request here I **think**.

Can I use Freetube on a chromebook. On my son's school they use youtube on chromebooks and on larger so called 'Digiboards' where I often see ads in the classroom..

Just wondering if I can move them to use Freetube.

Happy to contribute towards making Freetube available on Chromebooks if needed.

Thanks.

### Proposed Solution

Chromebook support

### Alternatives Considered

Nonne

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@kaypoush you are running FT on a Chromebook right?

**Comment by ACR-Jeff** [comment]
Here is the Android version https://github.com/MarmadileManteater/FreeTubeCordova

**Comment by absidue** [comment]
Looks like there is no way to Electron apps directly on Chromebooks, so we won't be able to create a Chromebook compatible version of FreeTube. You do however have to other options of installing FreeTube on Chromebooks:

- Enable Linux via Crostini on the Chromebooks and then install whichever Linux release of FreeTube is suitable for each Chromebook. This is the process that Visual Studio Code suggests for their users: https://code.visualstudio.com/blogs/2020/12/03/chromebook-get-started
- You can try installing the fork of FreeTube that ports it to Android, as it's designed for Android it's missing some of the features of the desktop version of FreeTube, but it comes pretty close and works great, although I don't know if anyone has tried it on a Chromebooks yet: https://github.com/MarmadileManteater/FreeTubeCordova

Please keep in mind that FreeTube doesn't upgrade automatically, so whichever choice you go with, you will have to manually download and install updates on every Chromebook.

**Comment by siemvaessen** [comment]
Sorry for the belated feedback - thanks for all the tips, it seems I have to wait for input from 'tech team' that manages IT systems in school.
