### ISSUE TITLE
[Bug]: Videos not loading in Subscription feed under Local API

### ISSUE THREAD

**Issue by hjc25** [FreeTubeApp/FreeTube#4795]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

    Open the application on my desktop
    Wait for loading
    All subscription load under "channels with errors"

### Expected Behavior

Subscriptions are visible

### Issue Labels

API issue, content not loading, visual bug

### FreeTube Version

v 0.19.2 Beta

### Operating System Version

Windows 10 Pro 22H2 OS Build 19045.4046 Windows Feature Experience Pack 1000.19053.1000.0

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.2 Beta

### Additional Information

![image](https://github.com/FreeTubeApp/FreeTube/assets/28969068/c9a58c5c-4949-4743-88ca-9b06eedb5ca4)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by gregorgoettfert** [comment]
I am getting exactly the same behavior here.
running x64 version under win11 home.
re-installing the app (0.19.2) did not change the behavior.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
YT is experimenting again and everyone that is using RSS is affected. RSS will probably return to its normal state in a couple of hours.

In the meantime you can do something to mitigate this:

- create a profile that has under 100 subscriptions so FT wont force RSS on you
- make sure RSS is disabled in the Subscription settings

**Comment by dfgshdsfh** [comment]
Following the instructions [here](https://docs.freetubeapp.io/development/nightly-builds) I installed this [nightly build](https://github.com/FreeTubeApp/FreeTube/actions/runs/8402923503) though it has the same issue of neither the local or invidious API being able to load the subscription list. As mentioned, loading videos per channel works.

It seems I have 700 subscriptions. Not sure if that has something to do with it. I should probably prune but I'm unlikely to bring it down to a small number.

**Comment by johnno66** [comment]
The RSS feeds start working again at exactly 8:00 CET.  This is the 3rd morning  in a row this happens.
Clearly YT is being annoying....
