### ISSUE TITLE
Enhanced playback controls

### ISSUE THREAD

**Issue by aproposnix** [FreeTubeApp/FreeTube#48]
It would be nice if we had the ability to:
 - Pause/start a video by clicking on the spacebar of the keyboard
 - Double clicking a video should make the video go fullscreen. 

I know these are minor but I'm putting them here because they will improve usability.

**Comment by PrestonN** [comment]
Hey there.  I already have keyboard shortcuts finished and ready for the next release.  This will include using the spacebar to pause as well as a number of other shortcuts.  I still need to do the double click to full screen though so I'll keep this issue open.  It should be a pretty quick addition though.

**Comment by PrestonN** [comment]
This has been added.  Expect to see these in the next release (hopefully this weekend).
