### ISSUE TITLE
[Request] Add the option "only audio" in the settings to make it DEFAULT everytime when playing a video just to hear the audio 

### ISSUE THREAD

**Issue by Josehkn** [FreeTubeApp/FreeTube#480]
I know there is an option to play the video "only audio", but i have to switch that option everytime i want to hear a video. I just want to hear music if I say so (so the settings is always default and won't play a video, just the audio).

Will it be possible?

Thanks in advanced.

**Comment by Josehkn** [comment]
@GilgusMaximus Would be nice to have a background why you are closing this. I know you are working in your own (and better) fork. If that's the case, thanks then, will be following your progress.

**Comment by PrestonN** [comment]
Yes, this was added in the rewrite. It'll be releasing soon so we're cleaning up some issues that won't be relevant anymore.
