### ISSUE TITLE
Request: Freetube for winget (Official Windows 10 Package manager)

### ISSUE THREAD

**Issue by PhillyMay** [FreeTubeApp/FreeTube#481]
A few days ago, Microsoft unvieled their new Package Manager called "winget).
https://github.com/microsoft/winget-cli

Would be cool, if Freetube can be installed with a simple command line script. Sadly its currently not part of the chocolatey pakage manager either

**Comment by PrestonN** [comment]
FreeTube is actually available in Chocolatey over [here](https://chocolatey.org/packages/freetube/), though it's an unofficial build and I do not maintain this.  Adding FreeTube to Winget might not be worth it because of it being an official store.  There's a good chance it would be removed soon after even if it did get accepted.

**Comment by starsep** [comment]
I created a PR here: https://github.com/microsoft/winget-pkgs/pull/5179

Unfortunately unattended mode of an installer is required.
I couldn't find such an option for current installer, it seems that such could be build using different configuration.
Configuration for Windows installer is documented here: https://www.electron.build/configuration/nsis
Here is installer template https://github.com/electron-userland/electron-builder/blob/c35b3150536be66a9e1c2aae75f7e8f7f610699d/packages/app-builder-lib/templates/nsis/installSection.nsh
I suspect `Silent` option is relevant here.

I am of my depth here. If anybody wants to take over - good luck! Maybe I could help somehow.

**Comment by PrestonN** [comment]
My problem with moving forward with this is that there's a good suspicion that MS would simply remove the app from their store. If I know for a fact that this won't happen then I can consider publishing there.

Even if it gets published, there's no promise that it would be there in the long run. MS might approve it without knowing anything and maybe a months / years time it can get taken down unprovoked for one reason or another.

I don't see myself making this happen anytime soon. Windows users has a solution with Chocolatey and I'll be working on in-app updates at some point as well. I don't see the benefits of working on this at the moment.
