### ISSUE TITLE
[Feature Request]: Liking the playlists and make them appears in Playlists menu

### ISSUE THREAD

**Issue by Miatec** [FreeTubeApp/FreeTube#4813]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

As far as I know, playlists menu only displays my playlists. 
It seems that we can "star" only videos and not playlists.

### Proposed Solution

I suppose the simplest way to integrate this idea is to add the star button on the playlist view :
![playlist_like](https://github.com/FreeTubeApp/FreeTube/assets/12949689/74ebcb23-80e9-41b5-b35f-abec09b9ee76)

I would like this "starred" playlists to appear in "Your playlists" menu. I guess it should come with some filter options to show only our playlist and/or the starred ones.

### Alternatives Considered

An other alternative to "star" a playlist of another user and save the link to it is to have a local copy of this playlist and allow us to modify this local copy. I guess it's more work.

### Issue Labels

new feature

### Additional Information

Thank you for your work :-)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Miatec, i think you're looking for this feature

https://github.com/FreeTubeApp/FreeTube/assets/73130443/7c6dd69e-2e18-4ca2-8265-ed24133a7104

**Comment by Miatec** [comment]
Hi @efb4f5ff-1298-471a-8973-3d47447115dc , 

Your video shows exactly what I described as an alternative.  That would indeed meet my needs, even if it's a lot more clicks than the former solution.
nevertheless, my version is v0.19.2 Beta, on windows .zip (x64) and on the exact playlist you've show, I don't have the copy icon you used:
![image](https://github.com/FreeTubeApp/FreeTube/assets/12949689/8453d9d4-7651-4f69-ac72-863d1e24e404)

Is there a subtility somewhere that I missed ?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
No you haven't missed this :) This will be available in v0.20.0

**Comment by Miatec** [comment]
Good news! I'm looking forward to this new version :)

Do you think the one-click starring option can be considered?

Anyway, thank you for you work !

**Comment by Darmorque** [comment]
I'm also totally into the "Star" option. You can copy someone else's playlist, that's true, but as far as I know the copied playlist doesn't auto update when there's a new video added to it. You have to repeat the whole playlist-copying process every time to get the up to date playlist.

Why does it make the difference? Well, I use multiple (own made) playlists to have my videos nicely sorted by topic. Those playlists constantly change - I'm adding new videos to them while removing the watched ones. Besides, I use various devices / third-party apps to watch them: NewPipe on Android smartphone, SmartTube on Chromecast, and FreeTube on Windows PC. The former two allow playlist subscription and that makes it very convenient - you just add the video to the desired playlist either in YT app or YT website, and it is nicely synced among all other apps/platforms. 

In FreeTube the new playlist standalone functionality is indeed really great, as you can edit them, add new videos from subscriptions, etc., and all of that without the need of signing in with Google credentials, but even the passive access to external playlists and the ability to pin them in the playlist library would be awesome. I know that even in pre-0.20 version you could technically do that in a way by copying playlist's url to the FreeTube app and then play the playlist's content, but doing this every time you want to access a particular playlist is really tedious.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> but as far as I know the copied playlist doesn't auto update when there's a new video added to it.

Thats right. The functionality you are looking for is documented in #312 and is a but more complicated to implement but now that Local Playlists are finally here that issue will probably way more traction

> but even the passive access to external playlists and the ability to pin them in the playlist library would be awesome.

Pinning is also documented in #4594

So everything you mentioned is definitely on our radar :)
