### ISSUE TITLE
[Feature Request]: Make Loop and Shuffle Playlist AWAYS enabled

### ISSUE THREAD

**Issue by caiota** [FreeTubeApp/FreeTube#4819]
### Guidelines

- [x] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Make Loop and Shuffle Playlist AWAYS enabled when i click it. Or in the settings

### Proposed Solution

Make Loop and Shuffle Playlist AWAYS enabled when i click it. Or in the settings

### Alternatives Considered

Make Loop and Shuffle Playlist AWAYS enabled when i click it. Or in the settings

### Issue Labels

improvement to existing feature, new feature, new optional setting, visual improvement

### Additional Information

Make Loop and Shuffle Playlist AWAYS enabled when i click it. Or in the settings

:D

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It is always enabled when you click it.

https://github.com/FreeTubeApp/FreeTube/assets/73130443/e2beb060-138b-4bb7-8eff-4102dc0d5f97

**Comment by caiota** [comment]
**I say when you exit the player, or the app, the option is deactivated**

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Making a setting to make it default is a too niche usecase but retaining that setting within the setting could be easily done when https://github.com/FreeTubeApp/FreeTube/issues/2295 is implemented
