### ISSUE TITLE
[Bug]: Live streams show only with RSS enabled

### ISSUE THREAD

**Issue by ACR-Jeff** [FreeTubeApp/FreeTube#4827]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to Live tab
2. Click "Refresh Subscriptions"

### Expected Behavior

When clicking "Refresh Subscriptions" the subscriptions should refresh and show the most recent live streams.

### Issue Labels

content not loading

### FreeTube Version

v0.19.2 Beta and v0.19.1-nightly-4119 Beta

### Operating System Version

Void Linux Kernel: 6.6.22_1

### Installation Method

Portable

### Primary API used

Local API

### Additional Information

Current Live streams only show in creators channels
If activating RSS feed, Live streams are then visible in Live tab.
This doesn't appear to be happening with all live streams. It appears to happen randomly.
I deleted my Freetube config files to start with default settings and the issue is still occurring on both v0.19.2 Beta and v0.19.1-nightly-4119 Beta builds

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ACR-Jeff** [comment]
This appears to be a wide spread issue, I've made sure I have less then 100 subs, RSS off and Refreshed Subscriptions, I've tested with RSS on and Refresh Subscriptions, Same tests performed on other apps: On my android with FreeTubeCordova, Piped in my browsers, and Newpipe. All having the same issue, with custom and default settings. 
YT messing up the API again?

**Comment by absidue** [comment]
@ACR-Jeff Is it always the same channels or random ones each time?

**Comment by ACR-Jeff** [comment]
> @ACR-Jeff Is it always the same channels or random ones each time?

It appears to be the same channels each time

**Comment by ACR-Jeff** [comment]
Sorry about the delay, Surely will be glad to share, `TW Lives` is the channel name.
I noticed on this one particular channel when going to the channels "LIVE" tab, It says "This channel does not currently have any live streams", Yet clicking "Fetch more results" Shows current and previous live streams. Seems you have to click the Fetch more results twice to get anything results.

![Screenshot from 2024-03-29 11-20-36](https://github.com/FreeTubeApp/FreeTube/assets/61212551/159b735b-1ef4-4ecd-a9cd-dc9bdf869e1d)

![Screenshot from 2024-03-29 11-21-02](https://github.com/FreeTubeApp/FreeTube/assets/61212551/127ea305-6366-4f74-97c7-70a5d86f2836)

**Comment by absidue** [comment]
Sounds like a YouTube bug, like on the community tab on some channels. The workaround will probably be the same, if the response is empty keep fetching continuations until we get at least one video. Not ideal, especially for the subscriptions tab, as we really don't want to be making more than one request per channel there.

That being said I haven't checked if my original theory is true yet though, so maybe the response isn't empty, FreeTube might just not know how to handle it.

**Comment by ACR-Jeff** [comment]
Thank you @absidue for checking in on this, Very strange though considering I am not a member of that channel yet still able to watch the live streams, Except they don't show up in the feed. Obviously though it's something wrong on YT's side. Thank you again.

**Comment by absidue** [comment]
I'm saying that there are probably some member exclusive live streams, that you can't see.
