### ISSUE TITLE
RSS feed for the blog

### ISSUE THREAD

**Issue by p2635** [FreeTubeApp/FreeTube#483]
Can you turn on the RSS feed for the blog? I want to follow any updates that happen to FreeTube.

**Comment by calculeris** [comment]
> Can you turn on the RSS feed for the blog? I want to follow any updates that happen to FreeTube.

There you go : https://freetube.writeas.com/feed/

found in the html code of https://freetube.writeas.com/

**Comment by p2635** [comment]
Oh right, cool, solved! thanks @calculeris
