### ISSUE TITLE
[Feature Request]: hide API error messages

### ISSUE THREAD

**Issue by openforfuture** [FreeTubeApp/FreeTube#4830]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hi, thank you for this amazing app! Would be possible to add a setting to hide these annoying messages?

![image](https://github.com/FreeTubeApp/FreeTube/assets/99279367/3c242b8f-b82e-4652-9c26-269fb45bb2e5)

Thanks

### Proposed Solution

Add a setting to show or hide error messages.

### Alternatives Considered

Maybe would be possible to show them in a different, less annoying, way. Like not showing many times the same error. Still hiding them would be a nice option since the user cannot fix the problem and has to wait for a new release.

### Issue Labels

new optional setting

**Comment by reterkha** [comment]
Are the videos playing for you?  I've been getting similar errors and this morning videos won't play.

**Comment by openforfuture** [comment]
On desktop they work fine 👌

**Comment by reterkha** [comment]
Turning off the "proxy videos through Invidious" fixed the non playing error.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The errors popup for a reason and shouldnt be hidden.

> since the user cannot fix the problem and has to wait for a new release

This isnt true.

**Comment by openforfuture** [comment]
> This isnt true.

Than, please explain what I am supposed to do with this error. How can I fix it?
Btw, why I cannot be the one to decide if I want to show error messages or not?

The main point is: **these messages are annoying** in the way they appear right now, they could show up in a different form, like in the console or somewhere else.

You closed the issue without even having a discussion, denying the UI/UX problem exposed.

**Comment by absidue** [comment]
It would be an even worse if the errors were hidden, because then things wouldn't be working correctly but you would have no idea why. If there were an option to hide them, which there shouldn't be, anyone that has it turned on should be barred from opening an issues here, as they wouldn't be able to provide any useful information on the problem.

**Comment by doopening** [comment]
I agree that the messages are annoying when repeatedly appearing in the current location. 

In scenarios where errors (such as an API fallback) occur and self-resolve, I as the end-user in this scenario find no utility in such pop-up error messages appearing below the successfully-loaded video. 
![image](https://github.com/user-attachments/assets/94771ca9-5eee-4619-9d51-1347d8f5cb0f)

Maybe an option to move the messages elsewhere on the screen would be better.
