### ISSUE TITLE
[Bug]: "Version Now Available" Persists After Upgrade

### ISSUE THREAD

**Issue by jerrytomato** [FreeTubeApp/FreeTube#4831]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I just upgraded to the requested version, but the banner asking me to upgrade is still being shown every so often. Didn't see any option to hide it in the settings.

<img width="1019" alt="image" src="https://github.com/FreeTubeApp/FreeTube/assets/134457354/40279d4e-89af-4dd8-a8f0-9e63c40190aa">

### Expected Behavior

When upgrade is completed, the banner should disappear. 

### Issue Labels

inconsistent behavior

### FreeTube Version

0.19.2

### Operating System Version

Mac ARM64

### Installation Method

.dmg

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
The banner is correct, you didn't change to 0.19.2, otherwise you wouldn't see a `+` next to the Your Playlists text, as support for multiple playlists doesn't exist yet in 0.19.2, only in the nightlies which are currently pre-release versions of 0.20.0. That means you are using a nightly, which you can confirm by looking at the About page.

**Comment by jerrytomato** [comment]
> The banner is correct, you didn't change to 0.19.2, otherwise you wouldn't see a `+` next to the Your Playlists text, as support for multiple playlists doesn't exist yet in 0.19.2, only in the nightlies which are currently pre-release versions of 0.20.0. That means you are using a nightly, which you can confirm by looking at the About page.

I can confirm that I am running 0.19.2. I was running 0.19.1 previously, and then I upgraded.

<img width="998" alt="image" src="https://github.com/FreeTubeApp/FreeTube/assets/134457354/8172e7c6-5991-4557-bb60-814e53eabfd3">

**Comment by absidue** [comment]
Does FreeTube's own About page, the one listed in the side bar say 0.19.2 too?

**Comment by jerrytomato** [comment]
> Does FreeTube's own About page, the one listed in the side bar say 0.19.2 too?

No it doesn't actually say that oddly enough. It appear the about from the titlebar is from the new application version, yet the application that is running is from the old one. Strange, any idea how that happens?
