### ISSUE TITLE
[Feature Request]: Add option to make star icon for unsaved videos black for dark/black themes.

### ISSUE THREAD

**Issue by vF360** [FreeTubeApp/FreeTube#4844]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently, I am stuck using the default white theme as I cannot differentiate between saved & unsaved videos when I have f.lux on max settings on dark/black themes as the star colour in the thumbnail for unsaved videos is white.

### Proposed Solution

Dark/black themes should be made f.lux friendly by having an option to use a black star icon for unsaved videos.

### Alternatives Considered

No alternatives considered.

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
star wont be a thing in the upcoming version
