### ISSUE TITLE
[Bug]: Theme not respected; Linux Mint 21.3 Cinnamon

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [FreeTubeApp/FreeTube#4851]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I had 0.19.2 installed and it was dark-themed in line with my system. (I forget whether I had to specify the dark theme manually within the app.)

I installed 0.20.0 (via downloaded .deb). I ran the program and it was in light mode until I set it manually to dark mode.

### Expected Behavior

I expect the app to respect my themes or at least to keep the same theming as my previous installation.

### Issue Labels

visual bug

### FreeTube Version

v0.20.0

### Operating System Version

Linux Mint 21.3 Cinnamon

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.2

### Additional Information

**My OS (/DE settings)**

![image](https://github.com/FreeTubeApp/FreeTube/assets/47056543/b2b9ab0f-8d7a-4b3c-b3ea-d301280dfc64)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Did this also happen when you upgraded to v0.21.0?
