### ISSUE TITLE
[Bug]: search in playlist doesn't work for channel names

### ISSUE THREAD

**Issue by abdelrahman-y** [FreeTubeApp/FreeTube#4857]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I can't search for channel names in playlist 

### Expected Behavior

it used to provide videos of channels names given in search box

### Issue Labels

content not loading

### FreeTube Version

v0.20.0-beta, 54b49dc

### Operating System Version

windows 11 22631

### Installation Method

.zip

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.2

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This has never been implemented so this isnt a bug.

**Comment by vF360** [comment]
> This has never been implemented for playlists so this isnt a bug.

Why wasn't it implemented? Seems like an odd thing to not include, given it was available in previous versions.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please create a feature request issue for this.
