### ISSUE TITLE
[Bug]: Picture-in-Picture leave black box after closing

### ISSUE THREAD

**Issue by abdelrahman-y** [FreeTubeApp/FreeTube#4859]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

open any video then press picture-in-picture button and then close the popup window to return back to player and it will leave a black box behind which you can click through but can't remove

### Expected Behavior

the black box shouldn't appear

### Issue Labels

inconsistent behavior, usability issue, visual bug

### FreeTube Version

v0.20.0-beta, 54b49dc

### Operating System Version

windows 11 22631

### Installation Method

Portable

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.2

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could you send a screen recording of this
