### ISSUE TITLE
[Bug]: Deprecation warning

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#4869]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. While building freetube on Archlinux I get a warning:

`DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.`

### Expected Behavior

No warning.

### Issue Labels

build

### FreeTube Version

v.0.20.0

### Operating System Version

ArchLinux

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

-

### Additional Information

https://nodejs.org/api/punycode.html

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
You need to upgrade your local install of `yarn` to 1.22.22.

https://github.com/yarnpkg/yarn/releases/tag/v1.22.22

> Fixes a punycode warning.
