### ISSUE TITLE
[Bug]: 'Download Video' doesn't work

### ISSUE THREAD

**Issue by sebington** [FreeTubeApp/FreeTube#4879]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When clicking on the "Download Video" button below the video, and choosing a video format, video doesn't download. Instead video opens and plays in the default browser (Firefox).

### Expected Behavior

Usually video downloads and is saved on PC.

### Issue Labels

feature stopped working

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Ubuntu 23.10, Windows 11

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.2-beta

### Additional Information

Below is an example of a video URL displayed in the browser's address bar:
https://rr1---sn-4g5edn6k.googlevideo.com/videoplayback?expire=1712356022&ei=ViYQZrWnE83UxN8P3OyS0A8&ip=2a01%3Ae0a%3A2e%3A8de0%3Ab081%3Af42e%3Ab06d%3A4397&id=o-AHXUuVyII3fApeG98UTczMSRt6U_yXem69v3lYxLyaWT&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=HM&mm=31%2C29&mn=sn-4g5edn6k%2Csn-25glenl6&ms=au%2Crdu&mv=m&mvi=1&pl=50&initcwndbps=2353750&spc=UWF9f8aaO1lq2uwu32bELlAQ44oG_bOIsTefucFdNEZXgtKDkvU6zpFTEg&vprv=1&svpuc=1&mime=video%2Fmp4&ns=HBD9ARMS3vYe6TPvzfeMgLUQ&cnr=14&ratebypass=yes&dur=839.378&lmt=1712318960185848&mt=1712334079&fvip=5&fexp=51141541&c=WEB&sefc=1&txp=6308224&n=Oj6-_i9aQeyoiA&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRgIhAISIiL0msnfLfBCdkWK-MVgoDM7IJ0gy6LaEsKjx1O0kAiEA-Ii5PNrLcxsgxedDjZEjrK3PXygyAA3OvKX65o7B4r0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALClDIEwRQIgYAVYsZ-j8GjlT11BJlGYMWw-sHlJE_elKaxHY75ljDcCIQDCv0mMSVfcs91yNTq4UJgow621Jwsg7XENXs5loeJ0fg%3D%3D&cver=2.20240111.09.00

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
That is expected, as mentioned in the changelog, we changed the default download behaviour to open in browser, as the in-app downloader has a much worse user experience. No progress information, can't stop downloads, can't resume interrupted downloads, no oversight over what is downloading, all things web browsers already offer, hence the change of the default download behaviour.

If you want to keep downloading with the in-app downloader, despite all the downsides, you can change the download behaviour setting in the download settings.
