### ISSUE TITLE
[Bug]: Stutters when playing audio on a hidden workspace

### ISSUE THREAD

**Issue by catAngent** [FreeTubeApp/FreeTube#4882]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Start watching a video
2. Switch to another workspace 
3. Hear stuttering audio (might need to wait a bit before stutters start)

### Expected Behavior

No stutters

### Issue Labels

usability issue

### FreeTube Version

v0.20.0

### Operating System Version

Gentoo

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.2

### Additional Information

No stutters appear if picture-in-picture window is visible.

GPU: Intel Iris Xe, WM: hyprland 0.37.1

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by alkapwn3d** [comment]
I'm having the same issue on arch linux. 
App is unusable when using multiple workspaces.

**Comment by xe-3** [comment]
I am experiencing a similar problem, which also began yesterday (right around the time I upgraded to version 0.20 Beta, I unfortunately can't recall whether it started before or after upgrading.

The issue I experience is very similar to your experience except that:


1.  Start watching a video
2. Switch to another workspace
3. ~~Hear stuttering audio (might need to wait a bit before stutters start)~~ Video stops playing completely about 2-5 seconds after changing to another workspace, and automatically resumes when I switch back to the Freetube workspace)

I've confirmed that this problem only occurs when switching workspaces, I can _minimize_ Freetube without the video stopping.

My system is Fedora Workstation (Gnome), Freetube is installed as a Flatpak.

**Comment by andigandi** [comment]
Have you tried minimizing before switching workspaces? That does the trick for me. Switching the workspace away from an open FreeTube window leads to stuttering, minimizing FreeTube and then switching away leads to smooth playback. Maybe this information is helpful to someone.

FreeTube v0.20.0 Beta installed from Flatpak
Arch Linux with KDE on Wayland

**Comment by Atrate** [comment]
That's helpful, though only for stacking window managers. Tilers like i3, sway, hyprland don't have minimize functionality.

**Comment by evnct** [comment]
I encountered this on Debian 12.5 Gnome version 43.9. Oddly enough, I did not experience this on KDE Plasma, Cinnamon or XFCE.

> Have you tried minimizing before switching workspaces?

Yes. That didn't work for me.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@catAngent is this still an issue for you on v0.21.0?

**Comment by Atrate** [comment]
I can confirm that this is still an issue on Hyprland. The issue should probably be reopened.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Lets wait until the next major releases. We are close to release and will include many fixes.
