### ISSUE TITLE
[Bug]: Flatpak, Wayland, Plasma 5 cursor is tiny

### ISSUE THREAD

**Issue by firefoxlover** [FreeTubeApp/FreeTube#4895]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Enable Wayland in the flatpak options (simply ticking the box and disabling X11 will ensure that)

Now open the app. The cursor is tiny only when using Wayland.

### Expected Behavior

I am on KDE Plasma 5 with 125% scaling, on X11 the cursor scales normally, on Wayland it is tiny, like ¼ the size.

### Issue Labels

usability issue, visual bug

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Fedora Kinoite 39

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Maybe this could help you https://github.com/FreeTubeApp/FreeTube/issues/2799#issuecomment-1825542263
