### ISSUE TITLE
[Feature Request]: Only subscribe to certain content types on a per-channel basis

### ISSUE THREAD

**Issue by James-Fire** [FreeTubeApp/FreeTube#4907]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Some channels I don't want to be subscribed to everything. I only want their videos, and not their shorts or livestreams.

### Proposed Solution

Allow some way of subscribing to Videos, Shorts, and Livestreams for each channel separately. Configurable defaults would be ideal, but the best default would be to subscribe to everything I think.

### Alternatives Considered

I could have separate profiles for Videos, Shorts, and Livestreams. And may end up doing that anyway, but I feel greater control over the feed in general is a good thing.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Its best to create profiles for this.
