### ISSUE TITLE
The ability to keep the mini player above all other windows

### ISSUE THREAD

**Issue by connervieira** [FreeTubeApp/FreeTube#491]
When using the mini player, I think it would be more useful if the mini player window stayed above all other windows, so it could be used as a picture in picture system.

**Comment by PrestonN** [comment]
Hit `Alt` on your keyboard and go to `Window -> Toggle Always on Top` while inside the mini-player and that will accomplish what you're wanting.

**Comment by connervieira** [comment]
> Hit `Alt` on your keyboard and go to `Window -> Toggle Always on Top` while inside the mini-player and that will accomplish what you're wanting.

This only seems to be present on specific platforms, and is part of the OS, not the program itself.
