### ISSUE TITLE
[Feature Request]: Subscription settings "Only show videos uploaded from the time this is enabled and onward"

### ISSUE THREAD

**Issue by cjohn-afk** [FreeTubeApp/FreeTube#4911]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Not sure if this has been requested yet so please mark as duplicate if so. Couldn't find it anywhere.

Many people are only interested in watching new videos from subscriptions as they are released. Those users have a somewhat decent solution right now: Hiding watched videos and only showing the latest video from each channel. **The problem** is that old videos are back filled into your subscriptions as you watch the new ones. Your subscription feed will not appear empty until you have marked every video from every subscribed channel as watched.

### Proposed Solution

Adding a setting in the Subscription Settings which, when toggled, only shows videos in the subscription tab whose upload date is more recent than the date/time when the setting was toggled.

### Alternatives Considered

An alternative solution that would only partially solve the issue is allowing a user to mark all videos on a channel as watched at once. Perhaps this feature should be added either way. It would seemingly be simpler to implement.

### Issue Labels

new optional setting

**Comment by cjohn-afk** [comment]
This is not a duplicate of #3799, it doesn't address the same problem. #3799 proposes collapsible sections based certain upload time windows. I'm suggesting not showing any uploads that are older than when this setting is toggled. These are two separate things and #3799 doesn't address the problem proposed here, as you still see old uploads, whether they be in a collapsed section or not.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Same functionality different UI. Doesnt mean that that UI will be implemented

**Comment by cjohn-afk** [comment]
Its not the same functionality. #3799 adds a collapsible menu to subscriptions and playlists, one completely hides all subscription uploads from before it was toggled. I could see how you'd relate the two but they are similar at best. They don't solve the same problem at all.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah i see. One last question before i reopen. Could https://github.com/FreeTubeApp/FreeTube/issues/4803 and https://github.com/FreeTubeApp/FreeTube/pull/4380 potentially solve this as you now know where the user left of watching. These 2 combined with hide to watch could be more powerful imo.

**Comment by cjohn-afk** [comment]
I think the idea behind these features is inherently different. The core of my feature request is about the option of having a subscription feed that appears entirely empty after watching the videos that have been uploaded since I've started using Freetube, without having to go back and mark every video from every channel that I'm subscribed to as watched.

Now that I think of it, a 'mark all as watched' function would also work, when applied to an entire tab. Perhaps that is an even better approach. I will edit the request to add this.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hmm imo the feature you're asking might be too niche of an usecase. When #4803 is implemented you only have to mark as watched once and then you dont have to do that ever again.

And when #4198 that wont be a hassle at all. It implements a way to select multiple videos at a time an perform an action like marked as watched.
