### ISSUE TITLE
Music videos doin't play

### ISSUE THREAD

**Issue by Spritan** [FreeTubeApp/FreeTube#492]
Songs of popular singers don;t play with either of the player and youytube player says don't exist

**Comment by MetalNeo** [comment]
Same here. These videos can be searched and their information pulled up, but the video refuses to play.

**Comment by grrrrr** [comment]
have you examples?  Do they work if you are using youtube or invidious through browser?

**Comment by ProyashPSB** [comment]
work on youtube not tried invidious

**Comment by grrrrr** [comment]
what artists...  can you provide links to particular songs?
