### ISSUE TITLE
[Bug]: Window No Longer Visible

### ISSUE THREAD

**Issue by Jamesmms** [FreeTubeApp/FreeTube#4923]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Whenever I open the program, it appears without the window, meaning I cannot click on maximize/minimize/close. I have to use the windows key to open up my taskbar, which is rather annoying. Here is a screenshot of what my screen looks like. Notice the bar/window that is supposed to be at the top is missing.

![Screenshot 2024-04-10 201627](https://github.com/FreeTubeApp/FreeTube/assets/71465644/fc3201f7-2625-4192-80ca-081c478825f2)

### Expected Behavior

This is supposed to be visible at the top:

![image](https://github.com/FreeTubeApp/FreeTube/assets/71465644/bb278ce7-e2a0-4cb3-94ea-a74984cff0a5)

### Issue Labels

visual bug

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Windows 11 Home, version 10.0.22631, build 22631

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Jamesmms** [comment]
> Could you try pressing f11

Thanks, that worked.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Known issue duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3220
