### ISSUE TITLE
Subscriptions No Longer Loading

### ISSUE THREAD

**Issue by MetalNeo** [FreeTubeApp/FreeTube#493]
Starting today, all of my subscriptions are failing to load. I have tried toggling "Grab Videos Locally" and changing the invidious instance with no change in behavior.

I am still able to view the channels and videos by searching them manually.

**Comment by PrestonN** [comment]
Hey there!  I'm aware of the issue.  There's a problem upstream that's preventing it from grabbing subscriptions.  This can be tracked from the issue that I created over [here](https://github.com/omarroth/invidious/issues/1251).

There won't be a fix that I can do on my end unfortunately.  You will have to get your subscriptions somewhere else in the mean time.  Obviously as you mentioned, the rest of the app should be functional at this time.

**Comment by PrestonN** [comment]
This should be fixed now.
