### ISSUE TITLE
Feature request: SYNC with google

### ISSUE THREAD

**Issue by lynrayy** [FreeTubeApp/FreeTube#4930]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Please add sync with google account:
Login to your channel
Get from youtubt:
History, watch later, playlists, likes etc.

Add like/dislike buttons and possibility to use it, add dislikes counter using Return YouTube Dislike API

### Proposed Solution

All described in the problem section

### Alternatives Considered

All described in the problem section

### Issue Labels

new optional setting

### Additional Information

All described in the problem section

**Comment by jasonhenriquez** [comment]
See our answer to #2959.
