### ISSUE TITLE
[Bug]: Cursor doesn't change to hand on link hover with Dracula theme

### ISSUE THREAD

**Issue by mooreye** [FreeTubeApp/FreeTube#4937]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

This used to work. When hovering over a link or thumbnail, with Dracula theme, the arrow used to change to a index finger hand cursor. In recent version the arrow is all there is, however,

### Expected Behavior

Cursor is different when hovering on links

### Issue Labels

visual bug

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Fedora 39

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.2 Beta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This sounds like it could be similar to the other cursor issues on Linux, could you please try the steps mentioned here to see if they help you: https://github.com/FreeTubeApp/FreeTube/issues/2799#issuecomment-1825542263

**Comment by mooreye** [comment]
> This sounds like it could be similar to the other cursor issues on Linux, could you please try the steps mentioned here to see if they help you: [#2799 (comment)](https://github.com/FreeTubeApp/FreeTube/issues/2799#issuecomment-1825542263)

I don't think this would help as the Freetube themes are built into it, while things like cursor size are set outside of the sandbox. Also, what GTK ENV would I even use in this case?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can reproduce this on Windows.

> I don't think this would help

Trying cant hurt :)

**Comment by mooreye** [comment]
Probably was something bad in my distro because after upgrading to Fedora 40 the problem went away.
