### ISSUE TITLE
Version 0.20.0 has API error same as Version 0.19.1 

### ISSUE THREAD

**Issue by 09211947** [FreeTubeApp/FreeTube#4939]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

API error

### Expected Behavior

Searched page loaded

### Issue Labels

API issue

### FreeTube Version

0.20.0

### Operating System Version

Version	10.0.19045 Build 19045

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

Version 0.19.2

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please list the API error you received in v0.20.0 and steps to reproduce.

**Comment by DnickC** [comment]
I am also experiencing API errors from before the last update,  I want to provide more info but I dont know how to start debugging. I only see an API error popup, but no error code.

**Comment by DnickC** [comment]
I am also experiencing API errors from before the last update,  I want to provide more info but I don't know where to start debugging. I see an "API Error: Failed to request player id" popup, but no error code.
