### ISSUE TITLE
[Request?] 32 bit arch?

### ISSUE THREAD

**Issue by nam108** [FreeTubeApp/FreeTube#494]
I am not a programmer so I have no idea how time & energy consuming it's but I was wondering what is there reason that there is only 64 bit arch installer. I believe there might be plenty of people still using 32bit system and those people are having some windows 8/10 tablets from few years ago and most of them uses 32bit systems. I am obviously one of them and many of people I know have such devices.

**Comment by PrestonN** [comment]
Hello,

Unfortunately a 32-bit release will never be happening as Electron dropped support for 32-bit a long time ago.  I'd be more than happy to make releases for 32-bit if it was still supported but that sadly isn't the case any more.

The rewrite that I'm focusing on may have an alternative that you can use though, so be on the lookout for that. :)
