### ISSUE TITLE
[Feature Request]: Video translation option

### ISSUE THREAD

**Issue by MuerteRoja** [FreeTubeApp/FreeTube#4948]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Good morning, I come to present a problem with its possible solution, currently the Freetube application has many users consuming it, however, people do not only consume music videos, they also consume documentary videos, tutorials, foreign youtubers/streamers doing gameplay of a video game, Freetube users would like to understand what foreign YouTubers are saying, since they do not speak in their native language

### Proposed Solution

Browsing the Internet I have discovered an extension called Language Reactor https://www.languagereactor.com/ which allows videos to be translated into several languages, both from YouTube, Netflix, and other multimedia platforms, translation in real time, I think it would be quite good if the Freetube developers They add this feature, I mean, as far as I know and have knowledge, they have been inserting the Sponsorblock option for a long time, and that, Sponsorblock is an extension that you can find both in Firefox Addons and in the Chrome Web Store, yes they have already If you were able to add Sponsorblock to Freetube, why not also add Language Reactor? I am convinced that this would cause the number of users consuming the application to rise exponentially.

### Alternatives Considered

Although the Language Reactor extension cannot be added to the application, another alternative that could be considered is to translate the videos in real time locally using artificial intelligence, that would be a second option

### Issue Labels

new feature, new optional setting

**Comment by jasonhenriquez** [comment]
If I may ask, what features does this offer that are not currently available through subtitles?

**Comment by MuerteRoja** [comment]
> If I may ask, what features does this offer that are not currently available through subtitles?


 Dual-Language Subtitles: Language Reactor allows you to watch a video with two sets of subtitles (two different languages) at the same time.
  Pop-up Dictionary: By clicking on a word in the subtitles, a special menu opens that pronounces the word in a clear and correct accent, and presents examples of alternative uses.
  Precise Video Playback Controls: Language Reactor offers more precise video playback controls.
  Subtitle Export: Language Reactor allows you to view and export subtitles (original, human translation, automatic translation) from a video.
  Vocabulary Learning: If you create an account on Language Reactor, the extension will enable level selection in the “Highlight Vocabulary” field for words that appear in the subtitles.
  Language Learning: Language Reactor is an excellent tool for learning new languages. By watching videos with subtitles in the language you are learning, you can improve your listening comprehension and vocabulary. Plus, you can click on any word or phrase to get an instant translation. This allows you to learn at your own pace and in a more interactive way.

**Comment by absidue** [comment]
> Dual-Language Subtitles: Language Reactor allows you to watch a video with two sets of subtitles (two different languages) at the same time.

Not supported by the current player or the player that we will be switching to, that FreeTube uses, so we can't add this.

> Pop-up Dictionary: By clicking on a word in the subtitles, a special menu opens that pronounces the word in a clear and correct accent, and presents examples of alternative uses.

If that information is available through a public and open source API (see the various discussions about Return YouTube Dislikes on this issue tracker), we might be able to add this otherwise that won't be possible.
Do keep in mind though, that unlike SponsorBlock where everything is open source (browser extension, server, API that requires no signup or API key and even provides database dumps so you can setup your own SponsorBlock server), LanguageReactor is closed source, so we would have to find some place to get the data that satisfies the requirements mentioned in the first sentence in this paragraph.

> Precise Video Playback Controls: Language Reactor offers more precise video playback controls.

That's very vague, could you please clarify what that entails?

> Subtitle Export: Language Reactor allows you to view and export subtitles (original, human translation, automatic translation) from a video.

You can click the download button below the video in FreeTube to download the subtitles, so this one is already fulfilled.

> Vocabulary Learning: If you create an account on Language Reactor, the extension will enable level selection in the “Highlight Vocabulary” field for words that appear in the subtitles.

Creating an account on a closed source service to be able to use a feature is a big no-go for FreeTube. Unless there is a data sources that fits the requirements in paragraph 2 this won't be possible.

**Comment by MuerteRoja** [comment]
> > Dual-Language Subtitles: Language Reactor allows you to watch a video with two sets of subtitles (two different languages) at the same time.
> 
> Not supported by the current player or the player that we will be switching to, that FreeTube uses, so we can't add this.
> 
> > Pop-up Dictionary: By clicking on a word in the subtitles, a special menu opens that pronounces the word in a clear and correct accent, and presents examples of alternative uses.
> 
> If that information is available through a public and open source API (see the various discussions about Return YouTube Dislikes on this issue tracker), we might be able to add this otherwise that won't be possible. Do keep in mind though, that unlike SponsorBlock where everything is open source (browser extension, server, API that requires no signup or API key and even provides database dumps so you can setup your own SponsorBlock server), LanguageReactor is closed source, so we would have to find some other place to get the data that satisfies the requirements mentioned in the first sentence in this paragraph.
> 
> > Precise Video Playback Controls: Language Reactor offers more precise video playback controls.
> 
> That's very vague, could you please clarify what that entails?
> 
> > Subtitle Export: Language Reactor allows you to view and export subtitles (original, human translation, automatic translation) from a video.
> 
> You can click the download button below the video in FreeTube to download the subtitles, so this one is already fulfilled.
> 
> > Vocabulary Learning: If you create an account on Language Reactor, the extension will enable level selection in the “Highlight Vocabulary” field for words that appear in the subtitles.
> 
> Creating an account on a closed source service to be able to use a feature is a big no-go for FreeTube. Unless there is a data sources that fits the requirements in paragraph 2 this won't be possible.

I understand, so everything indicates that this feature cannot be added, ergo it is unnecessary to add it, I am sorry for the inconvenience caused.
