### ISSUE TITLE
premier / scheduled videos no longer listed as such

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#495]
Following #179 a feature was added to detect when a video was added with a premier date in the future

This no longer works.   

From the subscription page it show  the video upload as `0 seconds ago`.  If you click into the video is shows it as `Published on Jun 26th, 2020`

example: https://youtube.com/watch?v=-49jDul2wR4

OS: Debian 10
FreeTube: 0.7.2 Beta (.deb)

**Comment by PrestonN** [comment]
Looks like it was because of a slight change to the Invidious API.  I've pushed a fix.  New release will be this weekend so expect to see this fix included there.

**Comment by grrrrr** [comment]
thank you for the quick fix. looking forward to the new release
