### ISSUE TITLE
[Feature Request]: Button to hide channel

### ISSUE THREAD

**Issue by BjarneVerschorre** [FreeTubeApp/FreeTube#4961]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The "Hide Videos From Channels" settings is a bit annoying, adding a button to the channel's page would make it a lot easier.

### Proposed Solution

A button like this would add it to the list
![example](https://github.com/FreeTubeApp/FreeTube/assets/83133360/2d852e67-66e3-4934-94d8-50d4d4dbdb0a)

### Alternatives Considered

You can always add channels my hand but this would be a lot easier to do

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You can Hide a channel on every page you are like this:


https://github.com/FreeTubeApp/FreeTube/assets/73130443/40426306-f877-466b-94e8-90d0eb07878b

Adding an extra button on the channel page seems a bit overkill as this is already available within the whole application

**Comment by BjarneVerschorre** [comment]
My bad, I always looked over that button

**Comment by GrudRegrub** [comment]
This feature (and others as well) gets removed when applying the "Hide sharing actions" toggle. Found this out just as I was about to post here asking for help. 

Hiding channels isn't really a sharing option so maybe it should be exempt from that toggle.

Loving the app btw. Great work guys!

<img width="773" alt="Screenshot 2024-05-13 224753" src="https://github.com/FreeTubeApp/FreeTube/assets/169671796/f42e928d-b07d-4f59-ab26-7f4700b1089f">
