### ISSUE TITLE
[Bug]: Application does not open

### ISSUE THREAD

**Issue by CSsnap** [FreeTubeApp/FreeTube#4981]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When starting Freetube, the application does not open at all. It shows up in the task manager with 0% CPU usage and a few megs of ram usage, but not the screen or taskbar. This occurs no matter how the application is started.

### Expected Behavior

The application opens and is ready for use.

### Issue Labels

usability issue

### FreeTube Version

0.20.0

### Operating System Version

Windows 10 19045.4170

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

This issue was present in previous versions. This latest issue is from a fresh install.
![Screenshot 2024-04-18 193512](https://github.com/FreeTubeApp/FreeTube/assets/148958589/23ea2d96-5c73-41ea-9e0f-d5d68c748b09)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Bouch76** [comment]
Essentially I've the same issue with:
"freetube-0.19.2-setup-x64" 
"freetube-0.20.0-setup-x64" 
Also tried extracting "freetube-0.20.0-win-x64-portable" to "C:\Program Files\FreeTube"

Note: I am nubile.

OS Build:  22631.3527  
Ver:  23H2
Installed: 1/‎28/‎2023
Experience: Pack 1000.22700.1003.0

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is this also present in v0.21.0?
