### ISSUE TITLE
[Feature Request]: Sort by longest on channel page

### ISSUE THREAD

**Issue by lonix1** [FreeTubeApp/FreeTube#4984]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

A channel page shows "Sort By":
- Newest
- Most Popular
- Oldest

Sometimes it's useful to sort by "Longest" - useful for finding mixes, long videos, skipping over short videos, etc.

### Proposed Solution

A new menu item "Longest".

### Alternatives Considered

/

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by absidue** [comment]
We can only show the sort options on the channel page that YouTube has, as YouTube does the sorting on the server side. If we wanted to do anything like that, it would require fetching all items on the channel first and then sorting them inside FreeTube, as YouTube returns the items on the videos channel page tab in 30 item pages/chunks, so if the channel had a 1000 items on that tab, it would require 34 requests, one after the other, to get everything, which would be slow and very wasteful.

I'm closing this as infeasible.
