### ISSUE TITLE
[Bug]: Abnormal window scalling behavior on Wayland / XWayland backend.

### ISSUE THREAD

**Issue by GamePlayer-8** [FreeTubeApp/FreeTube#4986]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Use Alpine Edge / Freetube version `0.20.0`
2. Use KDE Plasma with Wayland support with a scalled display viewport set on 60%.
3. Launch FreeTube.
4. Try maximalizing it.

### Expected Behavior

FreeTube will maximalize window.

### Issue Labels

inconsistent behavior

### FreeTube Version

0.20.0

### Operating System Version

Alpine Linux Edge

### Installation Method

.apk (Alpine Linux Package)

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

-

### Additional Information

FreeTube will weirdly scale the window, ignore the scaled display parameter from Wayland, randomly downscale it's window size upon lost focus / switching between applications.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Does the same issue happen for other Electron apps such as Visual Studio Code or Discord to mention some well-known ones?
