### ISSUE TITLE
[Feature Request]: ctrl; alt; shift-click modifiers for 3-dot menu functions 

### ISSUE THREAD

**Issue by KamelittaOida** [FreeTubeApp/FreeTube#4989]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

OS: Windows 

would be great if we could assign actions to these clicks. mostly the ones from the 3-dot menu: Copy link (for me the main one); Mark as watched; Copy channel link; Remove from History; etc.

currently it's assigned to: shift: open new window; ctrl: open new window; alt (Windows): download html

### Proposed Solution

see above

### Alternatives Considered

no alternative

### Issue Labels

ease of use improvement, new keyboard shortcut

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as this seems more something for #251

> ctrl: open new window; 

just an FYI this one is intended to behave this way 

> alt (Windows): download html

Good point this is undisarible and should be addressed. Please open a feature request for this!
