### ISSUE TITLE
[Bug]: Installer doesn't install the app correctly on win 10

### ISSUE THREAD

**Issue by Reo0o** [FreeTubeApp/FreeTube#4998]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1.I downloaded from this git latest version called "freetube-0.20.0-setup-arm64.exe" on my win 10 pc
2. installed it for ALL USERS in "C:\Program Files (x86)\FreeTube"
3. only "Uninstall FreeTube.exe" exist there and no other file shown 
4. of course app doesn't launch
![Untitled](https://github.com/FreeTubeApp/FreeTube/assets/39520753/93348aa1-844f-4658-b979-822f78eb757c)
 run at all  

### Expected Behavior

to have the app running 

### Issue Labels

data loss

### FreeTube Version

v0.20.0-Beta, 54b49dc

### Operating System Version

windows 10 version 20H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
Are you using an arm64 device? 

If not then you should use this instead:
`freetube-0.20.0-setup-x64.exe`
