### ISSUE TITLE
[Bug]: Downloading a video only opens a Google link

### ISSUE THREAD

**Issue by MrPRAINGLE** [FreeTubeApp/FreeTube#5014]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go on any video
2. Click on the Download button
3. Select any option
4. Instead of opening a file dialog asking for the downloaded file location, Freetube opens a URL of googlevideo.com

### Expected Behavior

When I click on an option among the list of available audio and / or video streams, I am expecting for a file dialog to appear asking me where do I want the downloaded file to be, then, after a small amount of time relative to the size of the file to download, said file is to be found in the location I specified earlier.

### Issue Labels

feature stopped working

### FreeTube Version

v0.20.0

### Operating System Version

Pop!_OS 22.04 LTS x86_64 (kernel 6.6.10-76060610-generic)

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.0

### Additional Information

Although the media can be played in the opened URL, even with Video Download Helper, I couldn't manage to download it. I don't understand what causes this issue, this happened as soon as I upgraded to 0.20.0 so I think this is linked to a source code update. Looking through the Features added in the Release v0.20.0 Beta on GitHub, I could see nothing related to downloads.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by jasonhenriquez** [comment]
From [the v0.20.0 release discussion](https://github.com/FreeTubeApp/FreeTube/discussions/4848):
> The default download behavior has been changed to "Open in web browser" due to some UX issues with the in-app functionality by @absidue in https://github.com/FreeTubeApp/FreeTube/pull/4683

You can change this behavior under "Download Settings."
