### ISSUE TITLE
[Bug]: media Play/Pause keybinding doesn't work on Ubuntu

### ISSUE THREAD

**Issue by alexanderlavrenko** [FreeTubeApp/FreeTube#5015]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When I click Fn + F5 on my laptop's keyboard to trigger Play/Pause, or I tap on my earbuds to trigger the same functionality, it works with most music players like Audacious or Spotify but it would be nice if FreeTube could pick it up as well.

### Proposed Solution

Triggering Play/Pause also plays/pauses video in opened FreeTube.

### Alternatives Considered

Either it works or not, no alternatives here.

### Issue Labels

new keyboard shortcut

### Additional Information

System: Kubuntu 22.04, Format: AppImage

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Play pause media key is supported but that is with a real key for it. Idk if the fn+f5 could be supported as play/pause is different on all keyboard layouts

and in addition to that we have a shortcuts for play/pause listed on https://docs.freetubeapp.io/usage/keyboard-shortcuts/

**Comment by alexanderlavrenko** [comment]
> Play pause media key is supported but that is with a real key for it. Idk if the fn+f5 could be supported as play/pause is different on all keyboard layouts
> 
> and in addition to that we have a shortcuts for play/pause listed on https://docs.freetubeapp.io/usage/keyboard-shortcuts/

You're missing a point, I'm talking about global shortcut when you are doing something else, not in an app itself. Have you ever opened Spotify, and could just walk away, and play/pause a track by tapping on your earbud? That's what I mean.

**Comment by alexanderlavrenko** [comment]
> Play pause media key is supported but that is with a real key for it. Idk if the fn+f5 could be supported as play/pause is different on all keyboard layouts
> 
> and in addition to that we have a shortcuts for play/pause listed on https://docs.freetubeapp.io/usage/keyboard-shortcuts/

Okay, it seems like it supposed to work from link you showed me but it doesn't work on my Ubuntu while Spotify and other audio players work.

**Comment by alexanderlavrenko** [comment]
> Play pause media key is supported but that is with a real key for it. Idk if the fn+f5 could be supported as play/pause is different on all keyboard layouts
> 
> and in addition to that we have a shortcuts for play/pause listed on https://docs.freetubeapp.io/usage/keyboard-shortcuts/

I use AppImage, should I use .deb or "portable" version?

**Comment by alexanderlavrenko** [comment]
> > Play pause media key is supported but that is with a real key for it. Idk if the fn+f5 could be supported as play/pause is different on all keyboard layouts
> > and in addition to that we have a shortcuts for play/pause listed on https://docs.freetubeapp.io/usage/keyboard-shortcuts/
> 
> I use AppImage, should I use .deb or "portable" version?

No, it doesn't, it's the same thing but packaged differently it seems. Can you confirm Play/Pause media button working on Windows or Mac?

**Comment by absidue** [comment]
Can confirm it works correctly on Windows 10.
Please close this issue and open another one with the bug report template.
