### ISSUE TITLE
Add a reload button

### ISSUE THREAD

**Issue by m3thm4th** [FreeTubeApp/FreeTube#5019]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Add a button that has the Ctrl+R function

### Proposed Solution

.

### Alternatives Considered

.

### Issue Labels

new optional setting

**Comment by jasonhenriquez** [comment]
Duplicate of #1005. Please use the issue template as intended.
