### ISSUE TITLE
Bug: Playing playlist by pasting URL doesn't work the same as searching for the list and play it

### ISSUE THREAD

**Issue by sunnypp** [FreeTubeApp/FreeTube#502]
If I copy the link and play it in the App, I will have the following issues (using Mac version)
1. However it seems that the videos below are Recommendations instead of the videos from the list. This may be expected, just that I want to see what videos are in the list,
2. so that I can play anything of the videos in a long list
3. I want to skip the current song from a playlist

However, if I used the search box and click on the playlist that is shown as the search result, it works completely fine.

**Comment by ToughGuyKunio** [comment]
I believe I'm having the same issue? I'm using the [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect) extension, when I click on a playlist link `https://www.youtube.com/playlist?list=<playlist ID>` it won't open, FreeTube just starts on the home screen. Example: https://www.youtube.com/playlist?list=PL69BD06CC757E1D61
There's plenty more examples on: https://www.reddit.com/r/YTPL/top/?t=all
Is this the same issue or should I make a new issue report? Or is this a problem with the extension?

**Comment by GilgusMaximus** [comment]
I would leave it here and see whether this is fixed when it is implemented in v0.10.0
If not, you can create a new issue if you like : )

**Comment by Joe10s** [comment]
I think I am experiencing the same problem...

This worked prior to V0.9

1. Copy Youtube URL for playlist and paste in Freetube Search - 
....<V0.9 = Playlist retrieved and good to go
....V0.9 = Playlist not retrieved, but separate videos not in playlist retrieved as result of search

2. Searched Name of Playlist 
....<V0.9 = Playlist retrieved and good to go
....V0.9 = Search result empty

Looking forward to the fix.

**Comment by GilgusMaximus** [comment]
The empty search result is not connected to the pasting of the playlist url.

Also, it is not a problem. It is simply not implemented. 
However the receiving of random videos from the url link is weird. It at least showed the playlist in the results during the rewrite,.But this is a problem with the search module. Not our code.

**Comment by PrestonN** [comment]
This has been fixed and will be included in the next release

**Comment by Joe10s** [comment]
You guys rock. I am now able to play a full lists and not have to skip ads.
