### ISSUE TITLE
The current app icon is really lame, so I wish it had a better design.

### ISSUE THREAD

**Issue by dog6o** [FreeTubeApp/FreeTube#5025]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The current app icon is really lame, so I wish it had a better design.

### Proposed Solution

The current app icon is really lame, so I wish it had a better design.

### Alternatives Considered

The current app icon is really lame, so I wish it had a better design.

### Issue Labels

visual improvement

**Comment by jasonhenriquez** [comment]
This doesn't qualify as specific or actionable advice. You're welcome to introduce a new one if the current offering does not suffice.
