### ISSUE TITLE
[Bug]: Application crashes when closing one window

### ISSUE THREAD

**Issue by m3thm4th** [FreeTubeApp/FreeTube#5026]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open videos in multiple windows
2. Close one window
3. Sometimes the whole application crashes and all open videos are lost

### Expected Behavior

Only the window that is closed should be closed, application should not crash

### Issue Labels

causes crash

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Debian 12

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Victor239** [comment]
I've experienced this issue a number of times since this version too.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Does this issue still persist for you on v0.21.0?
