### ISSUE TITLE
[Bug]: 'your subscribed channels currently does not have any videos'

### ISSUE THREAD

**Issue by jorp** [FreeTubeApp/FreeTube#5032]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. go to subscriptions
2. refresh
3. receive error 'your subscribed channels currently does not have any videos'

### Expected Behavior

I expect there to be a full list of subscribed videos. At the moment it is just empty.

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Linux fedora 6.8.7-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Apr 17 19:21:08 UTC 2024 x86_64 GNU/Linux

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

This was working just yesterday. Occasionally when I refresh there will just be a grid of all my subscribed channels under' channels with errors'.

There is no problem clicking channels and watching their videos that way. Search also works as well. I have a large number of subscriptions so I am using RSS to retrieve them.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by UnconsciousBlaringHuman** [comment]
The same is happening to me on Windows 10, same FT version.
Likely the same problem as #4795 : youtube being annoying and therefore likely no solution from freetube's side.
If you disable fetching from RSS it does work (assuming the profile doesn't have so many subscriptions as to force RSS).
I think we'll just have to wait it out...

**Comment by jorp** [comment]
> The same is happening to me on Windows 10, same FT version.
> 
> Likely the same problem as #4795 : youtube being annoying and therefore likely no solution from freetube's side.
> 
> If you disable fetching from RSS it does work (assuming the profile doesn't have so many subscriptions as to force RSS).
> 
> I think we'll just have to wait it out...

Likely seems to be the case. Unfortunately related to [this](https://support.google.com/youtube/thread/269521462/enforcement-on-third-party-apps?hl=en). I hope the end isn't near...

**Comment by EvilGremlin** [comment]
Looks like google strated to heavily limit RSS requests. I think small rewrite of fetching is in order, to get data in <100 channels chunks, this is long overdue tbh.

**Comment by DerpDerpingtonIsHere** [comment]
> > The same is happening to me on Windows 10, same FT version.
> > Likely the same problem as #4795 : youtube being annoying and therefore likely no solution from freetube's side.
> > If you disable fetching from RSS it does work (assuming the profile doesn't have so many subscriptions as to force RSS).
> > I think we'll just have to wait it out...
> 
> Likely seems to be the case. Unfortunately related to [this](https://support.google.com/youtube/thread/269521462/enforcement-on-third-party-apps?hl=en). I hope the end isn't near...

That wouldn't affect Freetube as Freetube doesn't use youtubes API.

**Comment by hboetes** [comment]
Still would make sense to do the RSS pulls in chunks.

Sorting channels on their last released video and then requesting only the top 100 channels, and only occasionally requesting the other channels would be an improvement I'd guess.

There are lots of channels that only occasionally produce content. No need to keep checking them.

**Comment by Gorrrg** [comment]
There's a similar issue when FreeTube hasn't exited cleanly and is still running without GUI. When you start another instance, since files are still locked they can't be used for storing intermediate results like when fetching Subscriptions, but the new FreeTube instance won't notify you that it's still running in the background, so it seems like fetching Subscriptions isn't doing anything. But there's no error message in that case. Still as a precaution people should check with Task Manager if there's a stale FreeTube instance running in the background and kill it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
RSS should be up. Anyone facing still facing this issue?

**Comment by EvilGremlin** [comment]
Works fine today... youtube being youtube. They had live chat completely broken last few days as well.

**Comment by hboetes** [comment]
I object to closing this issue, since it's reoccurring, and there might be an elegant solution to it: don't try to fetch more than 100 channels from the RSS at the same time.

**Comment by 0x09AF** [comment]
Just happened to me today on 2 separate machines. Guessing, this is on the YT side because I saw subscriptions earlier today

**Comment by Spocketknife** [comment]
This just started two days ago. It worked in the morning, but not worked since. I can view channel videos directly, but only on the HOME tab, not the VIDEOS tab, where it says, "This channel does not currently have any videos." All other tabs work: Live, Playlists, Posts, About.
OS: Bazzite x86_64
FreeTube v0.24.0 Beta

**Comment by 0x09AF** [comment]
@Spocketknife #9163
