### ISSUE TITLE
Settings are not permanent

### ISSUE THREAD

**Issue by kortewegdevries** [FreeTubeApp/FreeTube#505]
Not sure about this...

`Freetube 0.7.3 Beta:amd64` binary,tested on Debian 10/Xubuntu 20.04.

Open Freetube from the command-line make some changes like `Dark Mode`,`Video Quality 240p`,`Enable Debug`,close it and reopen; immediately everything reverts back to stock. Nothing on terminal, subscriptions are unchanged.

Any ideas?

**Comment by PrestonN** [comment]
You need to click on "Save Settings" at the bottom of the screen when you make changes to your settings.

**Comment by kortewegdevries** [comment]
I did save them but it wasn't permanent. I had to manually write them to `settings.db` to fix it and it works for now. Thanks,
