### ISSUE TITLE
[Feature Request]: Summarize videos on history page

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#5052]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

My history is sometimes filled with many videos (per day) and I would like to have a better overview.

### Proposed Solution

One idea is to have settings to "summarize" certain videos into one "entry/playlist".
For example videos from the same youtube playlist could be summarized in one entry.

Like this:

Video xy 6 (including more videos from the same playlist, video xy 6 would be the newest one watched of course) - video b (video from different or no playlist) - video c - video d etc.

When you clock on "show more" (right next or under that entry) then all watched video from that playlist are shown (at best inside the history page, not on a seperate page; but this is a question of taste).

There could also be other options, like videos from the same Artist, Channel etc., but this might be a bit too much.

### Alternatives Considered

-

### Issue Labels

new optional setting

### Additional Information

-

**Comment by jasonhenriquez** [comment]
I'm not really understanding this description. Could you add some type of visual and/or paint a clearer picture of the described feature?

**Comment by toby63** [comment]
Well instead of having each entry of the same playlist, (e.g. video #6, v #5, v #4, v#3 etc. ), you have only one entry, a playlist entry so to speak (e.g. video #6 (and show more)).

I would need some time to edit a screenshot to show it in "action".
