### ISSUE TITLE
add to playlist from proposed More options

### ISSUE THREAD

**Issue by omega3** [FreeTubeApp/FreeTube#5069]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Now "add to playlist" is only possible when video is being watched, I mean is in the main window.

### Proposed Solution

I'd like to be able to have for proposed videos when I click on three dots (More options) an option to add this particular video to certain playlist. 

### Alternatives Considered

Add to queue is similar but not the same. Opening each video to add it to playlist is troublesome task.
Actually I can create "watch later" playlist or name it whatever and be able to organize "watch later" videos, so this might have broader scope of usage  than adding to temporary queue.

### Issue Labels

new feature

**Comment by absidue** [comment]
The plus icon and the quick bookmark icon, that every video thumbnail has, already serves this purpose. So unless there is something I'm missing, it doesn't really make sense to duplicate that into the three dots menu.

**Comment by omega3** [comment]
Yes. Forgive me but I just started testing freetube and somehow missed that. Please delete this thread.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
No worries :)

We wont delete this because this could help someone else that is stuck in the same situation as you.
