### ISSUE TITLE
[Feature Request]: Disable navigation by keyboard numbers

### ISSUE THREAD

**Issue by FelipeJz** [FreeTubeApp/FreeTube#5070]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I constantly tap the number row by accident making the video jump around

### Proposed Solution

Create a setting to disable number row navigation

### Alternatives Considered

Is the only solution really

### Issue Labels

new optional setting

**Comment by DontBlameMe99** [comment]
Duplicate of 992
This one tried to implement this change, but was closed due to inactivity: 4296

**Comment by jasonhenriquez** [comment]
Thanks @DontBlameMe99! Closing as this is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/992 and https://github.com/FreeTubeApp/FreeTube/issues/251.
