### ISSUE TITLE
Videos not loading: invidious api 

### ISSUE THREAD

**Issue by vuurvogelblog** [FreeTubeApp/FreeTube#508]
Subscription feed is loading, but video's wont play (today encountered for first time): invidious api error: null trying other method to retrieve video. 
I am guessing that the latest youtube changes have affected invidious? As Newpipe was also affected, they released an update yesterday. But if I am the only one experiencing this with freetube.., idk. I have tried several settings (grab videos locally, tor proxy on/of), system reboots and vpn on/off. but still getting the same error.

**Comment by apemann** [comment]
I've got exactly the same error on my rig today so I don't think it has anything to do with your local setup.

**Comment by iTrooz** [comment]
Same for me ! Maybe it's related to the change in youtube's api, a few days ago ?

**Comment by vuurvogelblog** [comment]
> Same for me ! Maybe it's related to the change in youtube's api, a few days ago ?

Yes, must be, just reading youtube api updates and keeping eye on issues on github invidious.

**Comment by PrestonN** [comment]
Yep, can confirm that it's happening on my end.  We will have to simply wait for Invidious to get fixed upstream and then you will see the changes reflected in FreeTube (As long as you're using the main instance).  There won't be anything that can be done on my end in the mean time.

**Comment by vuurvogelblog** [comment]
> Yep, can confirm that it's happening on my end. We will have to simply wait for Invidious to get fixed upstream and then you will see the changes reflected in FreeTube (As long as you're using the main instance). There won't be anything that can be done on my end in the mean time.

Thank you for confirming. Hope freetube is up & running again soon.

**Comment by danieljudd** [comment]
Have you tried switching to a different instance (https://instances.invidio.us/) and putting the full URL in Settings > Advanced > (bottom of page)?
