### ISSUE TITLE
[Bug]: Allow AV1 dash formats limits resolution to 360P

### ISSUE THREAD

**Issue by CharAznableLoNZ** [FreeTubeApp/FreeTube#5085]
### Guidelines

- [X] I have encounteted this in the latest version of FreeTube
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Player settings Dash Formats Default quality 1080p Allow dash AV1 formats On
Load video
https://www.youtube.com/watch?v=snbruf35H5E
Video plays in 360P, selecting resolution show this is the highest resolution available.
Player settings Dash Formats Default quality 1080p Allow dash AV1 formats Off
Select video again, Video now plays in 1080P60FPS.
Set AV1 on again, problem occurs again.

### Expected Behavior

Enabling AV1 formats should not result in 360P resolution limit.

### Issue Labels

feature stopped working

### FreeTube Version

v0.20.0 Beta

### Operating System Version

W10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Cant replicate, with following settings:
Local API
Dash Formats 
Default quality 1080p 
Allow dash AV1 formats enabled

It sounds like FT maybe switched to legacy formats

**Comment by absidue** [comment]
As you reported the issue only a short time after the video was published, YouTube media processing pipeline likely hadn't created the AV1 streams for the higher resolutions on that video yet. The streams seem to be there now, so I think it's nothing wrong on our side, just that YouTube hadn't finished processing the video when you watched it.
