### ISSUE TITLE
[Feature Request]: Add buttons (preferably with shortcuts) which open/copy YouTube link with watching progress from FreeTube

### ISSUE THREAD

**Issue by alexanderlavrenko** [FreeTubeApp/FreeTube#5087]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

You can open YouTube video with specific watching progress (minute, second) but you can't do the opposite if you started to watch YouTube video from FreeTube itself. 

For example, If I open video on specific minute and second from YouTube in FreeTube, continue to watch it in FreeTube, I should be able to open video with updated progress in YouTube, so it would save this progress, so later I can easily continue to watch/listen to this video from YouTube app on my Android tablet/phone without setting it manually.

### Proposed Solution

New buttons/shortcuts that copy/open YouTube video with current watching progress in FreeTube, it should be "Copy/Open Link" buttons in "Share" options.

### Alternatives Considered

Shortcuts that implement this idea.

### Issue Labels

improvement to existing feature, new keyboard shortcut

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is already possible

Here you see me copy the video url with the timestamp. You can also choose here to open the YT video with timestamp.

https://github.com/FreeTubeApp/FreeTube/assets/73130443/2c206cc1-ec55-473e-9d39-dfbe6069f9dc

**Comment by alexanderlavrenko** [comment]
> This is already possible
> 
> Here you see me copy the video url with the timestamp. You can also choose here to open the YT video with timestamp.
> FreeTube_5HRyJG0pCD.mp4

My bad, I couldn't notice the Timestamp switch for some reason 😂 Thank you for pointing it out!

**Comment by alexanderlavrenko** [comment]
I'm searching through settings but I can't find a setting that would turn "Timestamp" by default, I have to click on "Timestamp" each time which is not convenient. Would be great if you could fix that. Thank you!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We do the same as YT here but i can see how that can be annoying. I dont think adding another setting is the way to go here. I think the best way to address this is expanding the scope of https://github.com/FreeTubeApp/FreeTube/issues/2295 a bit. That means the first time the user has to enable it and then it will stay that way for other videos until the user decides to disable it.
