### ISSUE TITLE
[Feature Request]: Add numbering to ordered video grids

### ISSUE THREAD

**Issue by kommunarr** [FreeTubeApp/FreeTube#5090]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Grid views containing videos in a particular order are currently un-numbered, compared to `ft-list-video-numbered`, for list views of ordered videos. This information might be pertinent in certain contexts.

### Proposed Solution

Implement displayed ordinals for videos in a grid view. This currently only needs to be implemented for the User Playlist grid view, since that is the only other place where we use a grid equivalent of `ft-list-video-numbered`. The ordinals need to be legible even with `watched` styling.

### Alternatives Considered

Don't implement this feature.

### Issue Labels

display more information to user

### Additional Information

See #4949 for additional context.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as this doesnt seem that important to display to the users. We couldnt make it work as i didnt look good and it would potentially degrade the UI/UX. Months later it seems like there is no need for this so i dont see why we should leave this issue open
