### ISSUE TITLE
[Bug / feature request]: application should load with the search box focused or at least allow ctrl-f to focus that box 

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [FreeTubeApp/FreeTube#5093]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open the application.
2. Discover the search box is unfocused.
3. Press ctrl-f.
4. Find that the search box remains unfocused.

### Expected Behavior

I expect the search box to be focused upon launch or at least to have a well-known and/or easily discoverable keyboard shortcut achieve that focus.

### Issue Labels

usability issue

### FreeTube Version

0.20.0 Beta

### Operating System Version

Windows 10 Pro - 22H2 (2009: 19045)

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.20.0

### Additional Information

It is true that `Alt + D` and `Command/Ctrl + L` will focus the search box and that the documentation says so. Yet, those shortcuts are non-standard (as far as I know) and moreover (or so I believe) not particularly discoverable.

One could more or less solve the whole problem by focusing the search box upon launch. I note also that if the user acts as if the search box were focused initially-by-default, i.e. starts pressing keys, then peculiar things happen.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by jasonhenriquez** [comment]
The problem that you've identified is valid, but unfortunately this is not a good solution because of the disorienting effect it would have on our users who navigate the app with screenreaders. Our current planned solution for this problem is #2822.

**Comment by absidue** [comment]
> Yet, those shortcuts are non-standard (as far as I know) and moreover (or so I believe) not particularly discoverable.

Those shortcuts are the same ones used in web browsers to focus the main search bar.
