### ISSUE TITLE
[Bug]: freetube doesn't operate with android 14 (Nothing phone 2a)

### ISSUE THREAD

**Issue by drkl** [FreeTubeApp/FreeTube#5094]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

xxx

### Expected Behavior

x

### Issue Labels

accessibility issue

### FreeTube Version

v 0.14

### Operating System Version

android 14

### Installation Method

.apk (FreeTubeAndroid Unofficial)

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Open an report in https://github.com/MarmadileManteater/FreeTubeAndroid
