### ISSUE TITLE
[Bug]: "Autoplay Playlists" setting in internal player does not work as expected (or at all)

### ISSUE THREAD

**Issue by Quikswitch** [FreeTubeApp/FreeTube#5095]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Enable settings as shown on the picture (Autoplay playlists on; autoplay videos off)
2. Open video outside of playlist to confirm "Autoplay Videos" being disabled works as intended
3. Open a playlist
4. Observe that the first video in the playlist doesn't autoplay (intended? it's alright as is imo)
5. Let video playthrough (or skip to the end)
6. BUG: Player switches to the next video automatically, but does not autoplay the next video in the playlist

### Expected Behavior

The reason why I consider this to be a bug is that "autoplay playlists" as implemented is not a useful feature on its own. There's no point in making playlists go to the next video automatically if it needs to be started manually. "Autoplay videos", when enabled, produces correct behavior, but that setting also affects videos outside playlists, which a user may want to not autoplay.

User story: I like to open several videos on my subscription feed when I get on the computer for the day. I do not want them to autoplay, as I simply want to have a "to watch" list for the selected videos, and I can't watch more than one at once. After finishing those videos, and closing those windows, I want to listen to music through a playlist. The playlist, however, does not autoplay videos as expected unless I tweak settings in between these activities. This is an issue.

Expected behavior:
Videos in playlists will switch automatically, as they currently do, and autoplay, as they currently do not, when "Autoplay Playlists" is enabled, regardless of the state of the setting "Autoplay Videos"

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Windows 10 Home, v19045.4291

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

Unknown

### Additional Information

![example settings](https://github.com/FreeTubeApp/FreeTube/assets/95876385/c9232109-1700-4c78-bf53-d04f25d3c62c)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by jasonhenriquez** [comment]
I think your confusion comes down to our naming system being odd. "Autoplay Videos" means "start video automatically without clicking play button". "Autoplay Playlists" means "play next video in list automatically," with the generic version (e.g., for upcoming Recommended Videos) being "Play Next Video". Does this address your concern?

**Comment by jasonhenriquez** [comment]
I think I understand now, although that ask is admittedly a bit niche. Maybe that use case would be best served by having a profile with that setting enabled (once we have this behavior in implemented in #1996), then you can have any types of videos you choose to watch on that account start automatically.

**Comment by jasonhenriquez** [comment]
> I use "autoplay" to mean "automatically start playing the video on load". I don't know if this is the commonly accepted meaning, or if my suggestions should be flipped around so that (2) and (3) use "autoplay" and (1) is called something else.

There's a PR looking for a new author to take over that implements this naming change in the template and variable naming: #4342. Reason for doing so is that "Autoplay" in the "play next" meaning has been made more common by platforms like YT than the other interpretation. "Split Autoplay Videos" is the only step that we do not plan to implement at this time, as its use case should be adequately addressed by the other solution I shared.
