### ISSUE TITLE
Unable to load: any channel (invidio.us related?)

### ISSUE THREAD

**Issue by lucanomax** [FreeTubeApp/FreeTube#510]
I guess it's related to recent invidious news.
Idk if it's the same problem as newpipe with url encryption or because of invidious API, i just can't get feeds.

Edit: changed instance and works, will be more careful opening future issues

**Comment by lucanomax** [comment]
changed instance and works, will be more careful opening future issues

**Comment by Lynnporter1212** [comment]
![334A5971-E121-40CE-AEA1-8044DFA2DCB0](https://user-images.githubusercontent.com/69568331/90776980-ae523a00-e2af-11ea-95f5-1d8435614e79.jpeg)

**Comment by Lynnporter1212** [comment]
Hi jimmy bean Jamie ruff 11
Why are you such a dirty pig to me? I don’t understand why?
