### ISSUE TITLE
[Feature Request]: add to playlist autosave

### ISSUE THREAD

**Issue by omega3** [FreeTubeApp/FreeTube#5100]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When I click + icon and playlist window appears I need to click on chosen playlist and click save.

### Proposed Solution

Please add option to automatically autosave when I choose certain playlist. This would limit clicks and make process much faster. 

### Alternatives Considered

When I click + icon a list of name of playlists appears just like on youtube and when chosen it is autosaved.

### Issue Labels

ease of use improvement, new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
See https://github.com/FreeTubeApp/FreeTube/issues/4982#issuecomment-2073361703

**Comment by jasonhenriquez** [comment]
> I wish there was an option in Freetube that would work exactly like this one on youtube.

You're in luck; this is what the Add to Playlist prompt is when you press the "Add to Playlist" button.

**Comment by toby63** [comment]
@omega3 You can set a different playlist as standard playlist for the quicksave button, it is the second button right next to the "+".
See here how to do it: https://github.com/PikachuEXE/FreeTube/issues/65#issuecomment-1924918276

I also think that this is not intuitive, but the team decided this way, so we have to accept this.
See also: https://github.com/PikachuEXE/FreeTube/issues/65

**Comment by omega3** [comment]
How many playlist can be set for the quicksave button? 

In my freetube only one (v0.20.0 Beta). On youtube I can add to whatever playlist I want.
I am talking about this:
https://i.imgur.com/NpRw41t.png

You press in ... icon and you have a list of all playlist that you created available and just choosing one autosaves.

In freetube, with plus icon I can add to whatever playlist I want but this involves displaying playlist window, choosing playlist and click save. 

With clock icon I can add only to one predefined playlist. This is not how youtube works. Therefore I still claim that my request is not the same as  options already available in Freetube.

**Comment by jasonhenriquez** [comment]
> You press in ... icon and you have a list of all playlist that you created available and just choosing one autosaves. In freetube, with plus icon I can add to whatever playlist I want but this involves displaying playlist window, choosing playlist and click save.

So the change you're suggesting is getting rid of the "Save" button on that modal and have the changes save automatically?

**Comment by omega3** [comment]
If you not want to do it exactly the same as on youtube, that would be a solution. After all if I choose a certain playlist from all my playlist this means that I want to add this video to this exact playlist. This is like my will statement. So "save" as confirmation should be not necessary. Instead of three clicks (plus icon →  certain playlist → save) we would have only two clicks. Profit seems obvious considering that a single user may do this literally hundred or thousands of times.

Clock icons is great but I see it as having slightly different role for me, namely it serves me as a tool for creating a temporary playlist for videos that I want to see soon or that I don't feel like adding to any other playlist, in other words it is for me more like an equivalent of a queue on youtube.

**Comment by jasonhenriquez** [comment]
I've proposed getting rid of the saving in the past, and I am still considering it, although I will note it's actually still the same number of clicks, as even under that model you still need to click outside of the modal or on a close button to have it go away.

**Comment by omega3** [comment]
You are right. I admit I didn't noticed this. But autosave seems more intuitive for me because when I choose playlist there is this "thick" sign that I interpret as: "it is done". A few times after that I hit Escape button on keyboard to escape from Playlist window, which resulted in not saving (not adding to playlist). 

Then autosave could also result in closing the playlists window. 

Well, I see the way it works at present as a precaution for undecided people who have complex decision making process. But considering downsides and benefits and being perfectly aware that I myself may sometimes do wrong decisions I believe that I personally prefer from time to time to be wrong and redesign my playlist in favor of more intuitive work which comes with autosave. 

Now I know that you understood my intentions correctly and I will leave it to you to decide.

**Comment by absidue** [comment]
@omega3 The reason you need to click save, is because you can select multiple playlists to add the video to before you click save, something that wouldn't be possible if the prompt closed as soon as you clicked on a playlist.

**Comment by omega3** [comment]
But how many times you add video to multiple playlists? I assume that the majority of videos users add to single playlist most of the time and occasionally to multiple playlists.

With "autosave and auto-close playlist window" users also could add video to multiple playlist just by repeating the process.

Both ways seem to have their advantages and disadvantages. Perhaps you could consider giving some configuration options. You don't need to treat it as priority but someday / maybe.

**Comment by absidue** [comment]
I'm not saying which way is better, I'm just explaining why it works the way it does at the moment, as nobody else in the thread mentioned it.
