### ISSUE TITLE
[Feature Request]: Search Subscribed Channels Only

### ISSUE THREAD

**Issue by Astra060** [FreeTubeApp/FreeTube#5101]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

All these features for categorizing channels, and not being able to only search Subscribed Channels?

### Proposed Solution

Add a button next to search bar, which allows switching between searching All YouTube Channels or Only Your subscribed channels.

### Alternatives Considered

a simple toggle in settings, annoying to work with but gets the job done.

### Issue Labels

new feature

### Additional Information

Tnx for the great App!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is too niche of an usecase to add to FT. People generally dont interact in the way you are proposing. Closing as i dont see this happening.
