### ISSUE TITLE
[Bug]: `ERROR:vaapi_video_decoder.cc(1242)] failed Initialize()ing the frame pool`

### ISSUE THREAD

**Issue by Victor239** [FreeTubeApp/FreeTube#5112]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I'm getting this error whenever I click play on a new video. I believe it's related to hardware video acceleration, but I'm confused why it's occurring as my [`vainfo`](https://wiki.archlinux.org/title/Hardware_video_acceleration#Verifying_VA-API) looks similar and [`radeontop`](https://github.com/clbr/radeontop) seems to increase in usage when I start playing videos. 

### Expected Behavior

No errors

### Issue Labels

feature stopped working

### FreeTube Version

v0.20.0

### Operating System Version

Kubuntu 23.10

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

AMD Ryzen 7 7840U w/ Radeon 780M Graphics
X11

<details closed>
<summary>`vainfo` output</summary>

libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.19 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 23.2.1-1ubuntu3.1 for AMD Radeon Graphics (gfx1103_r1, LLVM 15.0.7, DRM 3.54, 6.5.0-28-generic)
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointEncSlice
      VAProfileNone                   : VAEntrypointVideoProc

</details>

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Could you please elaborate on where the error appears? A screenshot of it would be useful too. Additionally does the video still play when you get the error message or does it prevent playback?

**Comment by Victor239** [comment]
This is when launching FreeTube from the terminal using `/var/lib/flatpak/exports/bin/io.freetubeapp.FreeTube`, it appears as messages in the terminal.

No it doesn't prevent playback.

**Comment by absidue** [comment]
In that case just ignore it, FreeTube itself never writes anything to the terminal, unless something has actually gone wrong in the FreeTube code in the main process (which is definitely hasn't this time, you would know because it would look like a JavaScript error with a stacktrace) and as you mentioned it doesn't affect your usage of FreeTube.

Anything that gets written to your terminal is from Electron or Chromium, so things entirely out of our control anyway. When something goes wrong inside one of FreeTube's windows, it will appear inside the dev tools inside that window, never in the terminal. The only time you should look at the terminal output from FreeTube is something is seriously wrong like the app crashing or failing to start, as that's the only time messages from Electron and Chromium's internals are relevant.

**Comment by Victor239** [comment]
Ah I see, thanks for the info.
