### ISSUE TITLE
[Bug]: Wrong video sometimes loads when opening link in second FreeTube window

### ISSUE THREAD

**Issue by MoonlitMonitor** [FreeTubeApp/FreeTube#5116]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I cannot reproduce this bug with 100% success, but this sometimes happens:

1. I have one FreeTube window open, playing a video
2. I pause the first video and I open another FreeTube window
3. In the second window, I paste a YouTube URL into the searchbar and hit enter
4. Instead of FreeTube showing me the correct video, it shows me an unrelated video - seemingly a video on "Up Next" of the first video even though Autoplay is disabled

### Expected Behavior

The video corresponding to the URL I visit should play in the second window.

### Issue Labels

usability issue

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Windows 11 Pro 23H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

I also experienced this bug on several different versions of Fedora.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I tried my best but im unable to reproduce this
