### ISSUE TITLE
[Bug]: Fails to load some playlists (empty playlist result)

### ISSUE THREAD

**Issue by Flashwalker** [FreeTubeApp/FreeTube#5117]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Search by `https://youtube.com/playlist?list=OLAK5uy_mY8igizy8wyUNd8H-POfkQaxQktkjpUpI` playlist
2. Get empty playlist

### Expected Behavior

playlist loaded

### Issue Labels

content not loading

### FreeTube Version

v0.20.0-nightly-4210 Beta

### Operating System Version

Ubuntu 22.04 x64

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

???

### Additional Information

![2024-05-16_00-03-24-nq8](https://github.com/FreeTubeApp/FreeTube/assets/2188215/ec7e9506-5c04-49d7-8ec8-af96a5fb0c3b)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by jasonhenriquez** [comment]
Cannot replicate with Local Backend set as either Local API or Invidious. It seems like your Invidious instance was having an issue. Could you try switching to a different instance and trying again?

**Comment by Flashwalker** [comment]
yeap, it looks like Invidious issue
