### ISSUE TITLE
[Feature Request]: Ability to set default Freetube profile on Freetube loading, if a user has more than one

### ISSUE THREAD

**Issue by Xmetalfanx** [FreeTubeApp/FreeTube#5121]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Not a problem per-say but I am starting to organize my large list of subs into categories and one I have is "Notifications" ... (like for subbed channels where you "click the bell" on YT and get notified of those specific channels) ... while this takes time to organize it leads me to an idea I looked for in settings or past issue and unless i missed it I dont see.

I load up Freetube and it defaults to "all profiles" in the sub tab ... or maybe just "all profiles" for any tab/window.   

### Proposed Solution

I'd like a feature to set a DEFAULT profile on Freetube loading ... so say i have the loading page set to "subscriptions" ... instead of it having to load EVERY video from (I admit way too many YT subbed channels) it'd just load a smaller number (just the ones i'd have "notifications set for" in my example) of subs.

I am sure outside of my exact example there could be other useful use-cases for a "default on Freetube loading" profile.

### Alternatives Considered

If this (say "remember last used profile") is suppose to happen for instance ... It's not here ...or perhaps I am doing something wrong ... I am open to that idea 

### Issue Labels

new optional setting

**Comment by jasonhenriquez** [comment]
You're in luck: In the Profile Manager, navigate to the profile you want to set as the default and click `Make Default Profile`.

![Screenshot_20240517_153125](https://github.com/FreeTubeApp/FreeTube/assets/84899178/3bf7d40b-06c3-41c6-98d3-0e3306c3674f)
