### ISSUE TITLE
[Bug]: Blog on FreeTube.io seems to be stuck on 2021/10/01

### ISSUE THREAD

**Issue by AlexanderESmith** [FreeTubeApp/FreeTube#5124]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Every time there's an update, I click the link to see the newest blog entry. The only one I've ever seen is the 2021/10/01 entry ("Behind the Scenes: Improving Project Structure and Other Updates"). I don't know if the links in the app after releases is flawed, or if it's the blog software.

### Expected Behavior

I expect to see the blog that's noted in the big red banner after each release (which usually mentions specific changes in that version).

### Issue Labels

content not loading

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Ubuntu 20.04

### Installation Method

.AppImage

### Primary API used

Local API

### Additional Information

The about section (which is where I confirmed my version) also has a link to [the blog](https://blog.freetubeapp.io), and it shows the same 2021/10/01 entry.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
There have been no blog posts since then, that's not a bug.

If you want to see the changelog you can look at https://github.com/FreeTubeApp/FreeTube/releases. As for seeing it in the app, you need to have the "Check for Updates" setting enabled. When there is an update available, it will show a banner informing you that there is an update available and if you click on the banner it will show the changelog for that update, the same one that you see on GitHub.
