### ISSUE TITLE
[Bug]: Slow loading unknown cause

### ISSUE THREAD

**Issue by eshsdhsd** [FreeTubeApp/FreeTube#5127]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1 go click on a video
2 Video stuck on loading screen and takes 5-20 seconds to load
3 Then later loads instantly?

![image](https://github.com/FreeTubeApp/FreeTube/assets/79751239/bfa06b84-f33f-4fe0-b2aa-125a9b3e5928)

### Expected Behavior

Not to ever take this long

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.19.2 Beta and latest

### Operating System Version

windows 7 also on 10

### Installation Method

.exe

### Primary API used

Invidious API

### Additional Information

Sometimes It takes 7to18 seconds to load something and is stuck at the loading icon, I have no Idea whats causing this and how do I tell whats going on?

Any tool to tell whats going on or key?

Also the issue happens sometimes otherwise it's pretty fine

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
You mentioned that you are using the Invidious API, so you are probably just using a slow instance, try using a different instance or the local API.

Additionally we only support the lastest version of FreeTube and Windows 10+, so please only report issues that you actually experience on those versions.

**Comment by eshsdhsd** [comment]
I tried local Api and it seems to be fine I do not have the issue
Happens on win10 and latest

**Comment by absidue** [comment]
I'll close this then, as we can't do anything about Invidious instances being slow, you just have to pick a different one.
