### ISSUE TITLE
[Feature Request]: Video/Audio playback should continue, unless navigating to a new video

### ISSUE THREAD

**Issue by stdedos** [FreeTubeApp/FreeTube#5144]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

A number of actions that should _not_ lead to a/v playback be stopped:

- Searching for the next video
- Navigating to _anything from the sidebar_, including:
	- About dialog
	- Settings dialog
- Profile Select

### Proposed Solution

:upside_down_face: 

### Alternatives Considered

:upside_down_face: 

### Issue Labels

ease of use improvement, new feature

### Additional Information

- https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+video+playback+should+continue

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We do the same as YT here. If you want the playback to continue either use PIP or open a new window

**Comment by stdedos** [comment]
_Please close as not-completed, since you are not planning to implement this_ :upside_down_face: 

When/If you implement https://github.com/FreeTubeApp/FreeTube/issues/333, are you going to continue doing the same? (i.e. new window === new tab)

**Comment by stdedos** [comment]
Is there a setting that makes "Switch to PiP" a default when the user is navigating away?

ik the Youtube model is to press "I".

... also ik that I am switching from 10s of browser youtube tabs to an AMAZING app, so that is what creates my friction as well :pray:
