### ISSUE TITLE
[Feature Request]: Silent install on Windows

### ISSUE THREAD

**Issue by silmaril42** [FreeTubeApp/FreeTube#5145]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I'd like to have a way to roll out FreeTube on Windows systems using automated tools like Baramundi or OPSI.

It seems that FreeTube is using a NullSoft / NSIS installer, but I cannot achieve a command line installation using the [NSIS command line options](https://nsis.sourceforge.io/Docs/Chapter3.html#3.2).

Running `freetube-0.20.0-setup-x64.exe /S /D=C:\Program Files\FreeTube` results in the target directory being created, but nothing is installed.

I guess this might have something to do with the choice between installation for current user vs. all users that is the first thing the UI installer asks and for which no NSIS option exists.

### Proposed Solution

I don't know if there is a good way to solve this using NSIS.

One way to achieve this could be switching to [Inno Setup](https://jrsoftware.org/isinfo.php), which allows much more [command line options](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline). It's also [Open Source](https://github.com/smxi-software/Inno-Setup/blob/main/license.txt), even if one could argue it's not really free software.

### Alternatives Considered

Other installer frameworks might work as well - I don't have much experience here.

### Issue Labels

new feature, support for external software

**Comment by absidue** [comment]
The NSIS installer is generated by electron-builder. Looking at the source code, for it's NSIS templates it looks like it has `/allusers` and `/currentuser` arguments. The `/allusers` one also automatically sets the installation directory to program files, so you don't need to do it yourself.

Untested but running `freetube-0.20.0-setup-x64.exe /S /allusers` as administrator/in an elevated command prompt should do what you want.

https://github.com/electron-userland/electron-builder/blob/77f977435c99247d5db395895618b150f5006e8f/packages/app-builder-lib/templates/nsis/assistedInstaller.nsh#L122-L133
