### ISSUE TITLE
[Feature Request]: Reload with F5 as well

### ISSUE THREAD

**Issue by stdedos** [FreeTubeApp/FreeTube#5152]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I'm accustomed to F5 for reloading the page

### Proposed Solution

Reload with F5 as well

### Alternatives Considered

Dev Tools _and then_ reload with F5 :upside_down_face: 

### Issue Labels

new keyboard shortcut

### Additional Information

- https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+reload+f5

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
That will happen in the implementation of #1005

Because shortcuts regarding to refresh will need to be changed to work for all pages.

https://docs.freetubeapp.io/usage/keyboard-shortcuts/

**Comment by PrivacyFriendlyMuffins** [comment]
> That will happen in the implementation of #1005
> 
> Because shortcuts regarding to refresh will need to be changed to work for all pages.
> 
> https://docs.freetubeapp.io/usage/keyboard-shortcuts/

#1005 was implemented in v0.20.0 Beta as you said, but pressing F5 only reloads the Subscriptions page; it doesn't reload a video page.
