### ISSUE TITLE
[Bug]: [Flatpak] (Gnome) -> New Window shortcut is not working

### ISSUE THREAD

**Issue by stdedos** [FreeTubeApp/FreeTube#5153]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Using the (Gnome) -> New Window shortcut is not working.

Using the button from inside the app works

### Expected Behavior

Using the (Gnome) -> New Window shortcut should work

### Issue Labels

feature stopped working

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Ubuntu 20.04.6

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

- https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+ubuntu+new+window+is+not+working

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Where can i find this New Window shortcut in the ubuntu settings?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
As this is intentionally programmed like this I dont consider this a bug. Please open a Feature request for this. 

You dont have to mention flatpak or gnome because this is works like this on all platforms. If user wants to open a new window the user currently only has the option to do it from the application. From outside the app FreeTube is told to just focus the current window right now

**Comment by stdedos** [comment]
It is misleading to see "New Window" as an action.

... idk, convert this to a Feature Request then - if that is what you want 😕

**Comment by stdedos** [comment]
Should I reopen this / create a new one now?

https://github.com/FreeTubeApp/FreeTube/issues/5425 (and https://github.com/FreeTubeApp/FreeTube/pull/7049) do not address Linux/Gnome 😓 

I am on v0.23.5 Beta / flatpak as of today

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
No need for a new issue. There are some limitations with Linux and because of that we cant implement it, see https://github.com/FreeTubeApp/FreeTube/pull/7049#discussion_r2020135454
