### ISSUE TITLE
[Feature Request]: Add the documentation in the app

### ISSUE THREAD

**Issue by stdedos** [FreeTubeApp/FreeTube#5154]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Reference the app documentation in the app

### Proposed Solution

I don't know how the app works exactly, but there could be a number of ways to implement this.

In descending-preference order (first is preferred):

1. Documentation button before About, rendered in-app, offline documentation (if the artifacts are not that big)
2. Documentation button before About, rendered in-app
3. Documentation button before About, opening the documentation in the default browser

### Alternatives Considered

:upside_down_face: 

### Issue Labels

display more information to user, ease of use improvement

### Additional Information

- https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+documentation+inside+the+app

**Comment by jasonhenriquez** [comment]
We already have a link to the documentation in the About page (addressing your suggestion 3). We don't intend to pursue suggestions 1 or 2 at this time.

 https://github.com/FreeTubeApp/FreeTube/blob/a28c5d17dd2d35b8c46a392d1e2d526a2f085972/src/renderer/views/About/About.js#L27

**Comment by jasonhenriquez** [comment]
> I don't know how the app works exactly, but there could be a number of ways to implement this.
In descending-preference order (first is preferred):
[...]
> - Documentation button before About, opening the documentation in the default browser

Can you explain how this is not completed when the existing behavior meets your request?

**Comment by stdedos** [comment]
... yeah. Maybe I shouldn't have. You are right 🙃
