### ISSUE TITLE
[Feature Request]: Don't grey out miniplayer

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#5194]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Whenever the mouse moves over the miniplayer/PiP or even when the miniplayer gets focus, the screen becomes "grey" and "Back to Tab" is shown.

### Proposed Solution

Don't grey out, instead only show the control menu.

It would be even nicer though, if the control menu was shown below the content.

### Alternatives Considered

-

### Issue Labels

improvement to existing feature

**Comment by absidue** [comment]
We have no control over what is displayed in the PiP window or how it behaves, all we can do is ask the browser to open or close the PiP window.

**Comment by toby63** [comment]
@absidue Ok, and which browser is that? Chromium? or does Electron have its own stuff?

Also: You are sure, there is nothing you can do?
Aren't you using a "custom" player? Does that not apply to the PiP window?

**Comment by absidue** [comment]
Yes, I am sure, that's also why we've dismissed every other feature request about customizing the PiP window. There are two PiP APIs, the normal one and a recent one called document PiP. The first one exists in all browsers (it's the one we are currently using), the second one doesn't exist in Firefox and doesn't do anything in Electron. While yes Electron is based on Chromium, the fact that it gives app devs so much control, also means that for some features they can't just use the upstream Chromium implementation. The document PiP API is one of those, that will likely require a custom implementation inside Electron.
