### ISSUE TITLE
[Feature Request]: Offer option to exit Full Window at end of video

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#5195]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I always have to manually exit the full window mode.

### Proposed Solution

Automatic exit.

An enhancement would be to also enter full window mode, when video starts playing, but this is probably a second request.

### Alternatives Considered

-

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is a too niche usecase to offer an option for. 
FYT: Fullscreen and Theatre mode work in the same way as fullwindow so we would need to do it for everything for the sake of consistency which i dont see happening
