### ISSUE TITLE
[Feature Request]: Add a toggle button in playlist to always restart video to act as music playlist

### ISSUE THREAD

**Issue by ArthurKun21** [FreeTubeApp/FreeTube#5196]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I am treating some of my playlist as music playlist and would love to be able to start the music from the start. Due to saving of history, it sometimes start from the start or like near the end. I just don't want to turn off my saving history settings due to the other playlist that I used that needed tracking

### Proposed Solution

Add a toggle button that will reset the progress of the video upon loading of it.

It will have default to false, and doesn't have to be remembered when exiting the playing of the playlist

![image](https://github.com/FreeTubeApp/FreeTube/assets/16458204/97875fbe-a094-4b8c-bc80-05f9af5f9220)

### Alternatives Considered

Be able to mark some playlist as music playlist and it will always default to start from the beginning.

### Issue Labels

improvement to existing feature

**Comment by KandiPanda** [comment]
Related to this, I've actually thought that "play from beginning" and/or "clear resume time" options in the right-click menu for specific videos (in playlist pages and in the related videos in the sidebar and similar) would be nice.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is too niche of a feature to add for every user + this is probably an issue that could be better handled by other open issues on our repo

**Comment by tralph3** [comment]
I don't think it's a niche usecase to listen to music on YouTube. Anyone who is listening to a YouTube playlist would prefer for each video to start from the beginning.

I'm facing this issue as well, a simple toggle as proposed would be ideal.

**Comment by jasonhenriquez** [comment]
@tralph3 Would [the "0" key](https://docs.freetubeapp.io/usage/keyboard-shortcuts/) work for your use case?

**Comment by tralph3** [comment]
Tabbing to freetube and pressing 0 is in fact what I'm doing right now, yes. Not having to do that is the entire point of the issue.

**Comment by heisenberg2980** [comment]
I just found this issue thinking it would be impossible that this functionality was not already available, and I can see that I was wrong, but why is this issue closed if the functionality is not available yet? Using FreeTube to listen music from a playlist is what I use most of the time, and it´s really anoying that the music videos don´t start from the begining, so I would say this functionality should be a priority in the roadmap (I´m sure a lot of users agree with me).

Can this issue be reopen and prioritized?

**Comment by heisenberg2980** [comment]
> This is too niche of a feature to add for every user + this is probably an issue that could be better handled by other open issues on our repo

@efb4f5ff-1298-471a-8973-3d47447115dc can you please confirm what other issue will handle this? Not having this option available is a huge issue making a lot of people not use Freetube, as it´s really anoying having to open it and click 0 every time a new video starts playing halfway through.

**Comment by ArthurKun21** [comment]
With the https://github.com/FreeTubeApp/FreeTube/pull/6754 being able to choose if you will save watched progress on video exit and the current https://github.com/FreeTubeApp/FreeTube/pull/7139 where you can save playlist sort.

Would it be possible now to set a per playlist settings of the saving of watched progress, and be able to turn some playlist into never saving the watched progress
