### ISSUE TITLE
[Bug]: After an Ubuntu upgrade from 23.10 to 24.04, FreeTube 0.20.0 portable gives sandbox error and won't start unless --no-sandbox is used or setting the ownedship to root ???!!

### ISSUE THREAD

**Issue by attilalearning** [FreeTubeApp/FreeTube#5199]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

After running FreeTube from terminal, I get the error:

FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that ../freetube-old/chrome-sandbox is owned by root and has mode 4755.

### Expected Behavior

On Ubuntu 23.10 all was working fine. On Ubuntu 24.04 it will give the error mentioned.

### Issue Labels

accessibility issue, API issue, causes crash, feature stopped working

### FreeTube Version

v0.20.0 linux portable x64

### Operating System Version

Ubuntu 24.04

### Installation Method

.zip

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by archisman-panigrahi** [comment]
It might be related to recent changes in apparmor in Ubuntu, that breaks many apps. Here is the workaround https://askubuntu.com/a/1511655/124466

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@attilalearning could you try the suggested workaround and report back if it solved your issue?

**Comment by oren** [comment]
I have the same issue with Freetube "0.22.0 Beta" and Ubuntu 24.04.
