### ISSUE TITLE
[Feature Request]: Draggable subtitles

### ISSUE THREAD

**Issue by ckaiqos** [FreeTubeApp/FreeTube#5204]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Sometimes there's something going on at the bottom of the screen (for instance, an in-game dialog box) and the subtitles block it. This is an issue if there's something else you need subtitles for like someone talking.

### Proposed Solution

Make the subtitles a click and drag component. 

### Alternatives Considered

Add a setting to place the subtitles on pre-specified corners of the screen (i.e: top-center instead of bottom-center).

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by absidue** [comment]
duplicate of #5072
