### ISSUE TITLE
could not find player config

### ISSUE THREAD

**Issue by boistordu** [FreeTubeApp/FreeTube#521]
Some vidz gives me trouble with 0.7.3 with error message "could not find player config"
https://youtube.com/watch?v=vBV9D4sMnHY

**Comment by dyue05** [comment]
Me too. It seems the same across all age-restricted videos.

**Comment by nikita-moor** [comment]
This video is "unavailable" on YouTube, but FreeTube shows error "Could not find player config"
https://www.youtube.com/watch?v=oDYW17xeS48

**Comment by gugulet-hu** [comment]
I seem to have this same problem any time I try to watch NFL videos.
