### ISSUE TITLE
[Feature Request]: Add 'Subscribe/Unsubscribe' option in context menu when I right-click on a channel name

### ISSUE THREAD

**Issue by vF360** [FreeTubeApp/FreeTube#5214]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I do not want to open a new FreeTube window simply to sub or unsub to a channel & then to close it. Since FT does not have tabs, I'd like to keep window opening to a minimum. Having the option to quickly unsub from channels in my feed without manually opening/closing many different windows helps to keep everything streamlined, so I only see what I want to see.

### Proposed Solution

Title says it all.

### Alternatives Considered

None.

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as this is non standard behavior and people will not look on that place to subscribe to a channel. Its too different from the mental model & sets of behaviors YT laid out.
