### ISSUE TITLE
[Feature Request]: 'favourites' floating button just like 'refresh subscriptions' floating button.

### ISSUE THREAD

**Issue by valtoree** [FreeTubeApp/FreeTube#5217]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hi, currently i add videos i want to watch into the favorites playlist via the little 'clock' button labeled 'Add to favorites' from the subscriptions tab.
Once i'm done adding videos i then need to click on 'playlist's' then 'favorites' to start watching.

### Proposed Solution

Can we please get a floating button for 'favorites' just like the 'refresh subscriptions'?

### Alternatives Considered

dont know alternate.

### Issue Labels

ease of use improvement

**Comment by jasonhenriquez** [comment]
Hi @valtoree, we intend to address this use case with #4594.
