### ISSUE TITLE
[Bug]: Favorite Button looks like a clock / Watch Later

### ISSUE THREAD

**Issue by stdedos** [FreeTubeApp/FreeTube#5225]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

![image](https://github.com/FreeTubeApp/FreeTube/assets/133706/96e510b7-b96d-4c2c-be50-8478f86c1566)

### Expected Behavior

The Favorite icon looks like a heart or something.
And/or the "Watch Later" icon is a separate icon

### Issue Labels

usability issue, visual bug

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Ubuntu 20.04.6

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

- https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+favorite+icon+watch+later
- https://github.com/FreeTubeApp/FreeTube/issues/221
- https://github.com/FreeTubeApp/FreeTube/issues/4512

Topic has been discussed on the previous issues, but I don't think it has been "fully resolved"

"Favorite" playlist (if it has to be an "built-in playlist") and "Watch later" serve two different things - even if "both are generic buckets".

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not an issue as https://github.com/FreeTubeApp/FreeTube/pull/4885 is merged

**Comment by stdedos** [comment]
I guess fixed by https://github.com/FreeTubeApp/FreeTube/pull/4885, but not released yet?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Correct
