### ISSUE TITLE
[Feature Request]: FreeTube + nostr?

### ISSUE THREAD

**Issue by stokebreakup** [FreeTubeApp/FreeTube#5228]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Instead of storing browser data from the channels you subscribe to, automate scripting of channel subscriptions on a decentralized network.

### Proposed Solution

This proposal is used to backup videos watched, likes and other things.

### Alternatives Considered

none.

### Issue Labels

new feature

### Additional Information

nostr is a decentralized network protocol.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I dont see why this is needed when we will implement https://github.com/FreeTubeApp/FreeTube/issues/370 therefore im closing this
