### ISSUE TITLE
[Bug]: Application screen flickering while use invidious api.

### ISSUE THREAD

**Issue by Lence23** [FreeTubeApp/FreeTube#5229]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Start Freetube 0.20.0 Beta. 2. Settings > General settings >  Preferred backend : Invidious API. 3. Set    Current  Instance as default. 4. playing videos (some) 5. video screen flickering.

### Expected Behavior

Freetube 0.20.0 beta for Linux showing flickering screen while using Invidious APIs.  Also I noted that the issue is not for all videos but some videos, (in my case a video having 14min length).  I don't know why this happening.

### Issue Labels

API issue

### FreeTube Version

0.20.0.Beta amd64.deb

### Operating System Version

Linux Mint 21.2 Cinnamon. Linux Kernel : 5.15.0-107-Generic

### Installation Method

.deb

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
please provide a screenrecording of this
