### ISSUE TITLE
DASH player error

### ISSUE THREAD

**Issue by xeleven11** [FreeTubeApp/FreeTube#523]
[https://invidiou.site/watch?v=1d0Zf9sXlHk](url) This video plays as DASH in the first few seconds then automatically switches to legacy mode. There were other videos in the past and I thought it would have been fixed by now. I tried debugging and pasted the info shown in the console. None of the instances are displaying video list when I click any channel.

![dasher](https://user-images.githubusercontent.com/47713837/91418041-94ef5600-e88c-11ea-822f-9a7632e5fff0.png)

`mediaelement-and-player.js:5701 
{error: "mediasource", event: "MEDIA_ERR_SRC_NOT_SUPPORTED (CHUNK_DEMUXER_ERROR_A…am codec h264 doesn't match SourceBuffer codecs.)", type: "error"}
error: "mediasource"
event: "MEDIA_ERR_SRC_NOT_SUPPORTED (CHUNK_DEMUXER_ERROR_APPEND_FAILED: Video stream codec h264 doesn't match SourceBuffer codecs.)"
type: "error"`

**Comment by GilgusMaximus** [comment]
This is fixed in the rewrite. The local DASH replay works fine and does not depend on Invidious anymore. However some features like subscriptions are not fully implemented yet. 
So if you can wave subscription for the moment, you can watch videos with DASH over there.

**Comment by xeleven11** [comment]
I am using rewrite Vue but the same video is still playing as legacy mode. Few days ago it was available in dash but it doesn't work anymore.
