### ISSUE TITLE
Problems related to Invidious changes

### ISSUE THREAD

**Issue by qu4ntumrush** [FreeTubeApp/FreeTube#524]
Since the last update Invidious has announced that its main instance is shutting down on September 1 and it probably explains numerous problems I have had with the app. First, while using the main instance (invidio.us), only some of my subscriptions load in the Subscription feed (all related to music), and none of the individual channels load any videos, but some (but not all) can be searched within the channel page. Second, while using any other of the instances like invidious.snopyta.org or yewtu.be no videos load at all. In a matter of days this app will become defunct and I suggest an announcement about the future of Freetube or whether a fix is quickly incoming.

**Comment by PrestonN** [comment]
If you were subscribed to my [blog](https://freetube.writeas.com/the-invidious-project-will-be-shutting-down-soon), you would know that I've already made an announcement of my future plans for FreeTube.  I'm well aware of what's going on and I'm hard at work at making the needed adjustments.
