### ISSUE TITLE
Can't load subscriptions

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#525]
Hello,

My "latest subscriptions" list is empty, and when i reload it, it shows the message "unable to load channel: [random channel from my actual subscriptions]" then stops loading. If i delete the said channel, i have the same problem with another random channel.

**Comment by PrestonN** [comment]
This is a problem with Invidious and not something that can be fixed on my end.  Please see [this](https://github.com/iv-org/invidious/issues/1333) issue for any updates.
