### ISSUE TITLE
[Bug]: App (or Electron29) coredumps when closing FreeTube

### ISSUE THREAD

**Issue by ajgringo619** [FreeTubeApp/FreeTube#5251]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

(Running on EndeavourOS)
I've tried both the `freetube` and `freetube-bin` AUR packages. The former coredumps **electron29** whenever I close the screen, while the latter coredumps **freetube-bin** itself. I normally close my windows with Alt-F4 (no window decorations). What's weird is if I use `wmctrl -c freetube`, the coredumps do not happen.

What could be causing this? Both programs work great, just these minor glitches at program exit.

### Expected Behavior

Program should shutdown without error.

### Issue Labels

causes crash

### FreeTube Version

v0.20

### Operating System Version

Linux dss-endeavouros 6.9.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 x86_64 GNU/Linux

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
> - [x] I have encountered this bug in the official downloads of FreeTube.

You checked that box, but in your text you only mentioned the AUR builds, which are all unofficial and maintained by the community not the FreeTube team.

If you haven't tried an official FreeTube download (https://github.com/FreeTubeApp/FreeTube/blob/development/README.md#official-downloads) yet, please do so and check that the issue happens with an official download too.

**Comment by ajgringo619** [comment]
Well, the Arch AUR builds are listed on the official download page. Is the .zip download the real official one?

**Comment by ajgringo619** [comment]
OK, this version works: https://github.com/FreeTubeApp/FreeTube/releases/download/v0.20.0-beta/freetube-0.20.0-linux-portable-x64.zip. The main one I've been using is installed from the .deb package.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as it is confirmed by the OP that this issue is not present in the official downloads. This is an AUR issue like seen in previous reported issues regarding AUR
