### ISSUE TITLE
[Bug]: Player title getting stuck on fullscreen mode

### ISSUE THREAD

**Issue by Caxtonis** [FreeTubeApp/FreeTube#5253]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go into fullscreen mode on any video
2. Move the mouse a fraction of a millimeter so it triggers the player title to show but not the player controls (the title is more sensitive to mouse movements than the player controls)
3. The title now remains on screen indefinitely until you move the mouse so that the player controls appears and then hides dragging the title along with it (the title seems to rely on the player controls to hide)

Its difficult to replicate due to how little you need to move the mouse but any kind of desk vibration can potentially set it off

### Expected Behavior

For the title to hide like the player control does or the option to turn the player titles off in the settings as they add no extra information

### Issue Labels

visual bug

### FreeTube Version

v0.20.0

### Operating System Version

Debian 12

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

![mpv-shot0002](https://github.com/FreeTubeApp/FreeTube/assets/165458369/948339d9-a188-4aa7-88ca-7174898ac5ff)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please provide a screen recording of this.
