### ISSUE TITLE
[Bug]: Program fails to start after 0.20.0 update

### ISSUE THREAD

**Issue by icodemad** [FreeTubeApp/FreeTube#5256]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Run installer freetube-0.20.0-setup-x64.exe downloaded from the official download page.
Complete installation.
Run Freetube
Receive the following error:
---------------------------
FreeTube.exe - Entry Point Not Found
---------------------------
The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library C:\Program Files\FreeTube\FreeTube.exe. 
---------------------------
OK   
---------------------------

Followed by program crash:
Freetube has stopped working....
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	FreeTube.exe
  Application Version:	0.20.0.0
  Application Timestamp:	660448e8
  Fault Module Name:	ram Files\FreeTube\FreeTube.exe!DiscardVirtualMemory
  Fault Module Version:	6.3.9600.20144
  Fault Module Timestamp:	615be9b3
  Exception Code:	c0000139
  Exception Offset:	00000000000ed170
(Additional entries from the problem details report omitted because I don't know if it contains sensitive data about my computer or if it's necessary to share)

Note: I'm not certain which version I upgraded from.  But the last installer I have in my downloads folder is freetube-0.19.1-setup-x64.exe.  I occassionally delete some of these if I see them later, so I may have had an even newer version before 0.20.0.

### Expected Behavior

I download and install the x64 version from the download site.
The program loads, and works without crashing or errors.
My bookmarks, subscriptions, etc are preserved.
I watch stuff.  Google gets bent.

### Issue Labels

causes crash

### FreeTube Version

0.20.0.0

### Operating System Version

Windows 8.1

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.19.1 (I think, see description)

### Additional Information

I installed the latest nightly build.  After installation, I received an error saying freetube.lnk is not associated with an app, and telling me to either install the appropriate app or create the association.  Clicking on the installed freetube.exe results in an error saying this app can't run on my PC (no details).  This is not the same bug, so I didn't check the box about nightly builds.

I don't frequently check github, or use the computer where I updated freetube and encountered this problem.  I'm reluctant to try updating freetube on another computer.  I may not respond promptly to further inquiries on this issue.  I will make a real effort to check in a few times at least to follow up if there are replies within a reasonable period.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Retrieved from the [release notes](https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.20.0-beta)

> In order to stay in line with recent updates to Electron, this update drops support for all Windows operating systems below Windows 10 as well as macOS 10.13 / 10.14. These operating systems have been considered end of life for quite a while now and should also be considered a security risk. It is highly recommended that you switch to an alternative operating system if you are still using any of the ones mentioned above.

Support has been dropped for Windows 8 so you have to look into the [Unofficial downloads](https://github.com/FreeTubeApp/FreeTube/tree/v0.20.0-beta?tab=readme-ov-file#unofficial-downloads) for something that will work for you.
