### ISSUE TITLE
Not showing all of the subscription videos 

### ISSUE THREAD

**Issue by UsernameAlreadyPicked2** [FreeTubeApp/FreeTube#526]
In the subscriptions section it doesn't show all of the new videos, maybe because 85 subscriptions is too much..

**Comment by dexter-2** [comment]
Also having this problem. Only getting videos from about 10 channels of the ~100 or so subscriptions. Unsure as to if all the non-working channels stopped at once or gradually.

**Comment by ekianjo** [comment]
Confirmed I have the same issue for several days now. something like 80% of all my subscriptions stopped working all of a sudden.

**Comment by Domiuns** [comment]
I have the same problem :(

**Comment by PrestonN** [comment]
This is a problem with Invidious and not something that can be fixed on my end.  Please see [this](https://github.com/iv-org/invidious/issues/1333) issue for any updates.

**Comment by Domiuns** [comment]
@PrestonN https://omar.yt/posts/stepping-away-from-open-source

**Comment by PrestonN** [comment]
Please see my [response](https://freetube.writeas.com/the-invidious-project-will-be-shutting-down-soon) for more information on that.  I'm currently working on a solution.
