### ISSUE TITLE
[Feature Request]: Import / Export buttons on subscription page

### ISSUE THREAD

**Issue by eMPee584** [FreeTubeApp/FreeTube#5267]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I have curated a set of channels and would like a more user-friendly way to share it than this:
https://github.com/fsfw-dresden/usb-live-linux/tree/main/features/app_freetube_yt_frontend/user-config/.config/FreeTube

### Proposed Solution

Maybe a channel set object that can be ex- and imported?

### Alternatives Considered

uhm :thinking: 
Other similar ideas?

### Issue Labels

ease of use improvement, new feature

**Comment by jasonhenriquez** [comment]
Hi @eMPee584, we support multiple options for exporting and importing subscriptions. What is more user-friendly than downloading / uploading a file?

![Screenshot_20240615_141520](https://github.com/FreeTubeApp/FreeTube/assets/84899178/8547e093-99b3-4836-b434-4f77c1009d42)

**Comment by eMPee584** [comment]
Wow ok, that sounds somewhat similar 🤔
but i can not fin ... uhm ahh, there it is 😅 (sorry for fake-ticking the checkboxes, was a bit distracted yesterday...)
Guess import / export buttons on the subscriptions page would increase visibility?

**Comment by jasonhenriquez** [comment]
No worries, while that specific solution is unfavorable due to the signal-to-noise ratio we try to maintain, it sounds like the #4726 should address your problem.

**Comment by eMPee584** [comment]
While I like #4726 a lot, I actually would argue that the export/import function does rhather belong to the subscription page than to the settings page... :thinking:
