### ISSUE TITLE
all instances "read timed out" or hang when loading subscribed channels

### ISSUE THREAD

**Issue by esotericDisciple** [FreeTubeApp/FreeTube#528]

**Comment by grrrrr** [comment]
I am seeing the same,  on screen pops up  "can't load channel  xyz"   xyz being one of 70.  then results in full blank screen.  

I wonder if this is the same issue as #526  or as a result of the invidious side fix https://github.com/iv-org/invidious/pull/1355

* FreeTube 0.7.3 beta  
* Debian 10  
* using https://invidious.snopyta.org which seems to be running the fixed code

If I used invidio.us which I think is running old code,  I still get some channels

**Comment by vuurvogelblog** [comment]
Same here, subscriptions are not loading, subscriptions screen stays blank. I tried several settings, several invidious instances (which are up, incl. snopyta.org) but no change. (using version 0.7.3 beta, on ubuntu 20.04).

**Comment by linuxgirl22** [comment]
Same here. Used 'open in tab' in Liferea, and it showed a google captcha. Google blocking everything, if try to open Invidious or Youtube link in Liferea or in web browser.

**Comment by PrestonN** [comment]
I understand many things have been broken recently, and I do apologize for the inconvenience.

Right now my full focus is trying to finalize all of the functionality within the rewrite that should be releasing soon.  The rewrite will be fixing all of these issues and more once released and I do ask that everyone please be patient until I can get it done.  We are closing in on the release date and still have a few issues / features we need to finish up, but I promise it will be well worth the wait.

For now, all of the issues mentioned are issues with Invidious itself and is not anything that I can do to fix it.  I would recommend keeping an eye out for fixes to Invidious and trying again once a fix has been made.  With no clear developer working on the project, it is unknown if a fix will even be made.

I'll keep the issue open for now, however I will likely be closing this here soon.

**Comment by linuxgirl22** [comment]
Hello and thanks so much for your reassuring post! No need for you to apologise ... really appreciate what you're doing about the rewrite, more than I can say. Fully understand this is invidious issues. Will keep an eye on any fixes, but not hope too much, with, as you say, there not being a clear developer. Excited for when the new Freetube releases!, plus understand about closing the issue when necessary too, as everyone'll be realising that it's google putting deliberate blocks up, and best to be patient and do other things for now.

**Comment by vuurvogelblog** [comment]
Thank you for keeping us updated. Very happy that the project is still alive, I love the app.
