### ISSUE TITLE
[Bug]: "Topic" channels contain no videos.

### ISSUE THREAD

**Issue by Jey-Galactica** [FreeTubeApp/FreeTube#5282]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1) Starting FreeTube;
2) Going to channels;
3) Opening one of "smth - Topic" channel;

### Expected Behavior

Shows up only info about channel. Videos counter also, but no videos. 

![image](https://github.com/FreeTubeApp/FreeTube/assets/30151809/9a75a5fd-2e4c-4441-8206-cbdd898bbb6f)

By the way, thank you for your support!

### Issue Labels

content not loading

### FreeTube Version

0.20.0 Beta 

### Operating System Version

0.20.0 Beta 

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Already fixed by https://github.com/FreeTubeApp/FreeTube/pull/5241 and will be included in the upcoming release!
