### ISSUE TITLE
[Feature Request]: Watched videos counter on playlist preview.

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#5283]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hello.

I'm using FreeTube mainly as the source of music, so I'm watching playlists like 99% of all the time I'm using the app as all singles, EPs and albums are collected into them. But it's quite difficult to control which playlist I've already seen, and which I haven't. 

### Proposed Solution

I think it could be very helpful and useful to have some kind of "progress bar" on the playlist preview (if it is possible), so user has no need to open playlist to see if it has been watched or not.

### Alternatives Considered

I suppose a simple counter of watched videos like "N out of M" (N/M) would be enough.

### Issue Labels

display more information to user

### Additional Information

Thanks for your work. Looking forward to news.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as this is considered a niche usecase imo. I dont know any platform that informs users in the playlist preview how many videos they already watched in the playlist.
