### ISSUE TITLE
[Bug]: No 60fps in full screen

### ISSUE THREAD

**Issue by AlexiGalaxy** [FreeTubeApp/FreeTube#5284]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Play video that is 60fps
2. Video plays in 60fps and also if you expand the player but taskbar still visible
3. If you go fullscreen the video goes to 24fps.

### Expected Behavior

The the video plays also 60fps when full screen.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Windows 10 LTSC

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @AlexiGalaxy Could you do the following things:

- Update your graphics driver and see if that resolves the issue
- Provide information about the model your graphics card

**Comment by AlexiGalaxy** [comment]
7900XTX, latest driver: 24.5.1

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Update your graphics driver and see if that resolves the issue

Did this work?

**Comment by AlexiGalaxy** [comment]
I reinstalled the driver with factory reset option enabled, rebooted, but the issue remained.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Try setting your display settings to a lower refresh rate (e.g. 60hz)

**Comment by AlexiGalaxy** [comment]
I've changed screen to 60hz and can confirm this solves the issue. I'm not going to use 60hz just to use this app though.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Good to hear that changing that solved it but I understand that this is inconvenient. 

It is still weird that its happening only on fullscreen so i suggest doing the following:

- Try adjusting variable refresh rate settings
- Check for settings that are only applied in fullscreen
