### ISSUE TITLE
Channels names with uppercase and lowercase are sorted separately

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#529]
Hello,

In my subscriptions, i have both channels beginning by an uppercase letter and other beginning with a lowercase letter. In my subscription list, they are sorted like that: A-Z then a-z. It would be better if they were sorted togheter.

**Comment by PrestonN** [comment]
This is fixed in the rewrite.  Please wait for that to be released for the fix to come through.
