### ISSUE TITLE
[Feature Request]: Scheduled export option of Subscriptions/History/Playlists (aka "Timeshift" backup)

### ISSUE THREAD

**Issue by ichigo13** [FreeTubeApp/FreeTube#5292]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I find myself forgetting to periodically backup my subscriptions, history and playlists. 
In case Freetube encounters an issue that blocks it from running completely or run in a state that is unresponsive and cannot be fixed easily/quickly I usually have to resort to an uninstall and fresh install as part of troubleshooting (happened a couple of times already).
I end up having a fresh install with old backups to import. All my activity in-between (the time of my most recent backup and the fresh install date) is gone.

### Proposed Solution

Implement a "Timeshift" backup solution for Subscriptions - History - Playlists:

1. I can designate a backup/export location
2. I can choose the exported file type (if applicable). Option to export in all types would be great.
3. I can choose the schedule of the snapshots and copies to keep:

- Hourly          -     Keep X copies in export location
- Daily          -     Keep X copies in export location
- Weekly          -     Keep X copies in export location
- Monthly          -     Keep X copies in export location

As long as Freetube is running or is launched it can check and execute any scheduled exports that the user defined.

### Alternatives Considered

I have not considered any alternative solutions since the proposed solution is already implemented by Timeshift for system wide snapshots and it works amazing for scheduled backups. It would be a great fit in Freetube as well.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Making backups falls into the responsibility of the user. Allot of users use other ways to automate this and you should look into them instead of asking us to make something from scratch.
