### ISSUE TITLE
[Bug]: Watch Later button can only add to "Favorites" playlist

### ISSUE THREAD

**Issue by Zetaphor** [FreeTubeApp/FreeTube#5293]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

The "Watch Later" icon, as I've come to call it can only add videos to a playlist with the name "Favorites"

![image](https://github.com/FreeTubeApp/FreeTube/assets/3112763/bd0db995-13ea-454a-8e68-189e37882abc)

If you attempt to rename this playlist to something like "Watch Later", the button will disappear entirely.

Additionally it will only appear if a "Favorites" playlist exists.

I was really confused when I had gained the feature because I added a playlist named Favorites (I already had one named Watch Later), and when I saw videos saved with this icon were going to the Favorites list I renamed it to Watch Later and removed the previous list, only for that button to now disappear because there was no playlist named Favorites.

While shuffling around playlists I also managed to make a playlist no longer appear until I added a new Favorites, though I'm having trouble reproducing that. Overall this feature in its current state is confusing, lacking discoverability, and potentially buggy.

### Expected Behavior

The button should always be present, even if a playlist named Favorites does not exist.
If there is only one playlist it should save to that one, regardless of what its name is.
The user should be able to set what playlist the button saves to, ie: Watch Later instead of Favorites

### Issue Labels

inconsistent behavior, usability issue, visual bug

### FreeTube Version

v0.20.0 Beta

### Operating System Version

NixOS

### Installation Method

Nix (Unofficial)

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by kommunarr** [comment]
Hi @Zetaphor, this icon's appearance, behavior, and prominence have since been changed in #4885 and #5058, and these changes will be included in our next release.
