### ISSUE TITLE
[Bug]: Finicky "Live" comment arrow scrolling

### ISSUE THREAD

**Issue by kommunarr** [FreeTubeApp/FreeTube#5301]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Navigate to a live video with live comments
2. Scroll up by some amount
3. Scroll down back to the bottom in a moderately fast motion. Encounter bug (the arrow doesn't disappear unless you try to scroll down again in a separate motion)

### Expected Behavior

1. Navigate to a live video with live comments
2. Scroll up by some amount
3. Scroll down back to the bottom in a moderately fast motion. The "scroll to bottom" arrow is no longer present

### Issue Labels

visual bug

### FreeTube Version

v0.21.0

### Operating System Version

OpenSUSE TW

### Installation Method

.rpm

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

none

### Additional Information

This does not occur with slow scrolling down. It might have something to do with "momentum" of a faster scroll propelling it to the bottom that's not getting caught by the `onscroll` event handler (`onScroll` in `watch-video-live-chat.js`). I can tell that this is the likely issue because it's not happening when I put that handler logic in a `setTimeout` with a 100ms delay. That would technically work, but I would like to see if there's a less hacky fix.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You even commented on it xD

see https://github.com/FreeTubeApp/FreeTube/issues/3158
