### ISSUE TITLE
[Bug]: FreeTube crashes when being maximized or fullscreened (Wayland)

### ISSUE THREAD

**Issue by pm4rcin** [FreeTubeApp/FreeTube#5304]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open app
2. Maximize app or video
3. Observe window crash

### Expected Behavior

App should function normally when being maximized.

### Issue Labels

causes crash

### FreeTube Version

v0.21.0

### Operating System Version

Fedora Sway Atomic 40

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.20.0

### Additional Information

Started with flags for wayland on Hyprland 0.39.1

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Zeabyte** [comment]
Does this happen for you with stock flatpak options? Meaning on x11. I can only reproduce this on wayland with the following command:
```
flatpak run --socket=wayland io.freetubeapp.FreeTube --enable-features=UseOzonePlatform --ozone-platform=wayland
```
With this I have the same problem. With stock config, without wayland support, it works.

**Comment by kommunarr** [comment]
See https://github.com/electron/electron/issues/42560.

**Comment by aidzm** [comment]
This has mysteriously been fixed with the 0.21.1 update. (The unusual configuration here is due to trying a workaround for a separate issue. This workaround still caused a crash when fullscreen on <0.21.1)

Info: Fedora Kinoite 40, Flatpak version, forced Wayland through flatpak permissions system (+ ELECTRON_OZONE_PLATFORM_HINT = auto)

Can someone confirm?

**Comment by jmcelroy01** [comment]
> This has mysteriously been fixed with the 0.21.1 update. (The unusual configuration here is due to trying a workaround for a separate issue. This workaround still caused a crash when fullscreen on <0.21.1)
> 
> Info: Fedora Kinoite 40, Flatpak version, forced Wayland through flatpak permissions system (+ ELECTRON_OZONE_PLATFORM_HINT = auto)
> 
> Can someone confirm?

It is fixed for me as well on Gentoo/Hyprland/Flatpak, no forced permission though.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We have updated Electron twice so that maybe did the trick (havent look through their changelog yet)

See #5355 and #5328

**Comment by pm4rcin** [comment]
Hard to tell which release fixed it or maybe even chromium bump in Electron. I'll close for now.
