### ISSUE TITLE
[Feature Request]: Allow the user to filter Shorts content from search results

### ISSUE THREAD

**Issue by rjdg14** [FreeTubeApp/FreeTube#5306]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

YouTube's current search algorithm seems to prioritise a lot of Shorts videos (vertical videos no longer than 1 minute). In my experience, most of these videos are pretty dumb and resemble TikTok content, which I am not a fan of, and they clutter results lists.

The improved search filters in FreeTube v0.21.0 allow you to show only videos between certain lengths (under 4 minutes, 4-20 minutes or over 20 minutes) as well as allowing you to only show content matching certain criteria such as HD or Creative Commons licensed. They don't, however, seem to provide a way to either filter out or only display Shorts content. Asking the results to only display 4-20 minute or over 20 minute videos will filter out all Shorts, however not all videos under 4 minutes long are Shorts (in the YouTube sense).

### Proposed Solution

I'd like an option in the search options menu that allows the user to both hide or only display Shorts content from results pages.

### Alternatives Considered

My current solution to remove a large number of Shorts is to hide videos that contain the text "#shorts", "#short", "#youtubeshorts", "#viral" and "#reels" in their title, a feature which FreeTube does seem to support. A significant number of YouTube Shorts, though not all (although most of the clickbaity TikTok style ones, which are the ones that annoy me), seem to contain at least one of these hashtags, and thankfully the hide by text option seems to be punctuation sensitive meaning that it doesn't remove non-Shorts content that contains a word like "short" or "viral" without a hashtag in its title.

### Issue Labels

ease of use improvement, improvement to existing feature, new feature, new optional setting

**Comment by Anonymous-hss** [comment]
Short videos means the video which is less than 60sec right ? since youtube also allows shorts less than 60 secs

**Comment by rjdg14** [comment]
I think all Shorts are 60 seconds or less, but not all videos under this length are Shorts (I think videos deemed non-family friendly or those shot horizontally do not meet the Shorts criteria).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isnt possible because YT doesnt provide that filter.

**Comment by rjdg14** [comment]
> This isnt possible because YT doesnt provide that filter.
> 
> We also dont have a reliable way of hiding it because YT provides very little info on Shorts content.

If that's the case then I think that using the FreeTube feature that allows you to hide videos with certain words in their title, and hiding "#shorts", "#short", "#youtubeshorts", "#viral" and "#reels" is the way to go. Most of the clickbaity Shorts that dominate search results seem to contain one or more of those tags.

**Comment by Anonymous-hss** [comment]
> > This isnt possible because YT doesnt provide that filter.
> > We also dont have a reliable way of hiding it because YT provides very little info on Shorts content.
> 
> If that's the case then I think that using the FreeTube feature that allows you to hide videos with certain words in their title, and hiding "#shorts", "#short", "#youtubeshorts", "#viral" and "#reels" is the way to go. Most of the clickbaity Shorts that dominate search results seem to contain one or more of those tags.

I am looking after it will update it here if I could make something which will show horts explicitly. Gonna try both the ways filtering by time as well as the hashtag way.

**Comment by PrivacyFriendlyMuffins** [comment]
> I think all Shorts are 60 seconds or less, but not all videos under this length are Shorts (I think videos deemed non-family friendly or those shot horizontally do not meet the Shorts criteria).

YouTube also have what's called "long shorts", which are videos that are like 1-4 minutes but are mobile-phone aspect ratios. It's stupid, imo.
