### ISSUE TITLE
Enhancements picture-in-picture

### ISSUE THREAD

**Issue by STVGecko** [FreeTubeApp/FreeTube#5308]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The image within the image lacks functionalities.

### Proposed Solution

Can you improve the picture-in-picture (backwards and forwards, shortcuts, subtitles...).

![image_28](https://github.com/FreeTubeApp/FreeTube/assets/71868745/0a2386af-4216-400e-ba4b-8e7acfcdac58)

### Alternatives Considered

The interface you see is that of Mozilla Firefox.

### Issue Labels

visual improvement

### Additional Information

Thank you for your superb application.

**Comment by absidue** [comment]
As mentioned in this comment and my follow up one, the picture in picture window is not customizable by us: https://github.com/FreeTubeApp/FreeTube/issues/5194#issuecomment-2140928913
