### ISSUE TITLE
Can you add an option to export all Freetube parameters ?

### ISSUE THREAD

**Issue by STVGecko** [FreeTubeApp/FreeTube#5311]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I can export history, subscriptions and playlists, but I can't find the option to export all the settings (interface colours, default quality, etc.).

### Proposed Solution

Can you add an option to export all Freetube parameters ?

### Alternatives Considered

No

### Issue Labels

ease of use improvement

**Comment by johnl-m** [comment]
I'd like to work on this.

@STVGecko, you'd also want an option to import application settings in addition to exporting them, right?

**Comment by STVGecko** [comment]
Yes, of course.
Thank you for your reply.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You can already do that but not in the application. See https://docs.freetubeapp.io/usage/data-location/#notable-files for the location of the file.

**Comment by kommunarr** [comment]
Also, this is a duplicate of #1018.

**Comment by STVGecko** [comment]
Thanks for your answers
