### ISSUE TITLE
[Bug]: F5 doesn't work for refreshing, while ctrl+r does. 

### ISSUE THREAD

**Issue by GlacieAwn** [FreeTubeApp/FreeTube#5315]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [x] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. click on any video
2. press F5 or fn + F5
3. it should refresh, but doesn't. ctrl + r works to refresh though

### Expected Behavior

the page is supposed to refresh, the same way that pressing ctrl + r does. 

### Issue Labels

keyboard control not working

### FreeTube Version

v0.21.0 Beta

### Operating System Version

Windows 10 Home 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
F5 only work on The Subscription, Trending, and Most Popular Pages. See https://docs.freetubeapp.io/usage/keyboard-shortcuts/
