### ISSUE TITLE
[Bug]: Top bar of Freetube goes out of screen

### ISSUE THREAD

**Issue by DerpDerpingtonIsHere** [FreeTubeApp/FreeTube#5316]
### Guidelines

- [x] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open freetube
2. right click on a video and select "open in a new window".
It will open a new window with the top bar out of the view of the screen (See attached photo for clarification.

This was not an issue till v0.21.0 Beta

### Expected Behavior

Open in the center of the desktop or remember if I was in maximum mode or not.

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.21.0 Beta

### Operating System Version

Windows version: Windows 11 version 24H2 build 26120.961

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

![Screenshot 2024-06-23 191819](https://github.com/FreeTubeApp/FreeTube/assets/12119604/c0a5f629-e2bb-475a-b49e-001c6ad544ca)

Installing the nightly build seems to have fixed this issue for now, however I am not sure if it will reoccur. so I am making this bug report in case it is still an issue as I did not see it posted in open or closed and in case someone else is experiencing this same issue.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by kommunarr** [comment]
Can't replicate on Linux (OpenSUSE TW, Wayland). Probably a bug with a new Electron version, if I had to guess, as I don't think we touched this functionality.

**Comment by DerpDerpingtonIsHere** [comment]
> Can't replicate on Linux (OpenSUSE TW, Wayland). Probably a bug with a new Electron version, if I had to guess, as I don't think we touched this functionality.

Not happening on mint x11 out fedora Wayland either. It's just one of those things I guess. It's fixed with the nightly build either way. I'll close this issue for now but it's here for reference if anyone else is experiencing this issue.
