### ISSUE TITLE
[Bug]: FreeTube Flashes black when watching video

### ISSUE THREAD

**Issue by wewefefwefef** [FreeTubeApp/FreeTube#5317]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

[Bug]: FreeTube Flashes black when watching video

### Expected Behavior

[Bug]: FreeTube Flashes black when watching video

### Issue Labels

usability issue

### FreeTube Version

FreeTube v0.21.0 Beta

### Operating System Version

window 11

### Installation Method

other

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

FreeTube v0.21.0 Beta

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Last Known Working FreeTube Version (If Any)
> FreeTube v0.21.0 Beta

How is the `Last Known Working FreeTube Version` the current stable version? Does this mean the behavior is inconsistent? 

> Installation Method
> other

How did you install it?

**Comment by Exosq** [comment]
Hi, i have the exact same issue as the author, same OS version and freetube parameters.

I installed it with the .exe file, i didn't have this issue in the previous version (0.20.0 beta), i completely uninstalled the 0.20.1 to go back to the previous version and the bug was still there, which is weird, i also deleted all files related to Freetube before reinstalling the 0.20.0 version to be sure.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Exosq Could you maybe provide a screenrecording of this behavior?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This looks like an issue with your graphics card. Could you try updating you graphics driver.

**Comment by Exosq** [comment]
It's already updated to the latest version and the bug wasn't happening with the previous one but i'll reinstall the driver to be sure :)

**Comment by Exosq** [comment]
Still happening even after uninstalling the graphic driver with DDU to do a clean install.

**Comment by Exosq** [comment]
Ok so i tested every version since the 0.15.1 Beta (included) until the last one and the bug only start appearing in the 0.20.0 on my machine
