### ISSUE TITLE
[Feature Request]: Quick Mask as Watched icon 

### ISSUE THREAD

**Issue by lamborghinipth** [FreeTubeApp/FreeTube#5321]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I know we had Mark As Watched function but it is not convenient enough. We need 2 steps.

We had [Quick Bookmark](https://github.com/FreeTubeApp/FreeTube/pull/4885) in the latest version.

We also should have Quick Mark as Watched button. Like Mark as Read in Email. All email clients have this button/ icon. It makes sense to reduce steps from 2 to 1 step.

### Proposed Solution

We can put this icon on the top left side of thumbnails

![100](https://i.imgur.com/YpR6uLC.jpeg)

### Alternatives Considered

None

### Issue Labels

improvement to existing feature

### Additional Information

None

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We wont implement this as it will cause too much bloat on the thumbnail. 

> Like Mark as Read in Email. All email clients have this button/ icon

We arent an email client.
