### ISSUE TITLE
[Bug]: Duration is not displayed in Subscriptions page

### ISSUE THREAD

**Issue by lamborghinipth** [FreeTubeApp/FreeTube#5322]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Reproduce:
1. Create new profile (e.g named P)
2. Subscribe some channels to profile P
3. Click the Freetube logo on top bar
4. See the bug
![100](https://i.imgur.com/a9vQx7m.jpeg)

### Expected Behavior

Duration is displayed in bottom right of each video's thumbnail
![100](https://i.imgur.com/NMmAaKp.jpeg)

### Issue Labels

content not loading, text/string issue, visual bug

### FreeTube Version

v0.21.0

### Operating System Version

Win 11 Pro

### Installation Method

Portable

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.0

### Additional Information

None

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @lamborghinipth how many channels are you subscribed to?

**Comment by feather42** [comment]
I have this same problem, I'm subscribed to 800+ channels, the duration on subscription page is vital I often watch videos based on the duration fitting the time I have and swatch the longer ones later.
Please please fix this.

**Comment by absidue** [comment]
@feather42 FreeTube automatically forces RSS when the currently selected profile has 125 or more subscriptions to avoid getting ratelimited. If FreeTube didn't force RSS, only about 130-160 channels would get fetched before you would hit YouTube's ratelimit and you would just get errors for the remaining 640-670 channels.

If you don't want to use RSS, split your subscriptions up into different smaller profiles or drastically reduce you subscriptions.

**Comment by lamborghinipth** [comment]
> Hi @lamborghinipth how many channels are you subscribed to?
> 
> You can see this number on the Channels page

Total more than 200 channels in more than 10 profiles. Means I have about 20 channels in each profiles.



> @feather42 FreeTube automatically forces RSS when the currently selected profile has 125 or more subscriptions to avoid getting ratelimited. Unfortunately YouTube's RSS feeds don't include the video duration or live status. If FreeTube didn't force RSS, only about 130-160 channels would get fetched before you would hit YouTube's ratelimit and you would just get errors for the remaining 640-670 channels.
> 
> If you don't want to use RSS, split your subscriptions up into different smaller profiles or drastically reduce you subscriptions.

I think I did as your suggestion. I split into profiles as I said above.

For example, I have profiles Sports that contain 16 channels. When I click on FreeTube logo while switching to profile Sports, the issue is still here right now.

**Comment by absidue** [comment]
@lamborghinipth

> For example, I have profiles Sports that contain 16 channels. When I click on FreeTube logo while switching to profile Sports, the issue is still here right now.

If you refreshed your subscriptions with the all channels profile, which had too many subscriptions so got forced to use RSS and then switch to another profile **without** refreshing your subscriptions you will see the information that FreeTube fetched when you refreshed the all channels profile.

If you switch to your sports profile and then refresh your subscriptions you should see the video durations.

> I also check a single latest subscribed channel - the 211st channel I subscribed. It works properly.
So duration only doesn't appear in Subscriptions page.

That is entirely expected, when you visit a single channel directly FreeTube only has to fetch information for that specific channel from YouTube. The risk of getting ratelimited only exists on the subscriptions page, because FreeTube has to fetch information for every subscription in the profile at the same time, which is why it uses RSS if you have too many.
