### ISSUE TITLE
[Bug]: Duration cut to 2 hours from an originally 9 hours video

### ISSUE THREAD

**Issue by endcr** [FreeTubeApp/FreeTube#5330]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to https://youtu.be/emYpLWC9rGk
2. Find that Freetube only plays the last 2 hours of the video, despite the full video being over 9 hours

### Expected Behavior

Expected Freetube to display full duration of the video

### Issue Labels

data loss

### FreeTube Version

v0.21.0

### Operating System Version

Windows 11 Build 22631

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

A 8 and half hours long video seems to load just fine.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Try to access the video again. YT was still processing this and that's why you only saw part of the VOD
