### ISSUE TITLE
[Feature Request]: order channel video by longest

### ISSUE THREAD

**Issue by e471wo** [FreeTubeApp/FreeTube#5331]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hi, 
When I m on a channel, and all videos of a youtuber is presented, we can only sort by oldest, most popular, etc...
Could be cool if we could order by longest time. In lot of case, I m looking for a long video from a particular youtuber and it's not easy today. 

I dunno if it's possible as youdube do not propose that functionnalities, but could be cool to have it :-D. 

### Proposed Solution

Adding in the sort by menu a longest (and shortest why not).

![image](https://github.com/FreeTubeApp/FreeTube/assets/64007061/09253402-3ec3-45f1-9f4c-82898c934bd9)

### Alternatives Considered

alternative is search by hand.

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We unfortunately cant provide functionality that YT doesn't provide to us

**Comment by e471wo** [comment]
but you have it.  youtube give you the time of each video. 

Does that mean that when I click to sort by newest, you ask to youtube to do it and it's not internal (sort by date)???
