### ISSUE TITLE
[Bug]: Video download (video & audio) only offers 360p

### ISSUE THREAD

**Issue by feather42** [FreeTubeApp/FreeTube#5338]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1: Goto subscription page, click on a video
2: Press download button under video and the top item is video/mp4 there is no option for higher quality as there used to be.
3: If I go to youtube and use other downloading tools higher resolutions of the video are confirmed to be avaialble.

### Expected Behavior

The download list should offer video/mp4 at all resolutions available from YouTube.

### Issue Labels

feature stopped working

### FreeTube Version

V0.21.0 beta

### Operating System Version

Windows 11 & Mint 21.3

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Please read https://github.com/FreeTubeApp/FreeTube/issues/5030#issuecomment-2080462240 and https://github.com/FreeTubeApp/FreeTube/discussions/5333#discussioncomment-9863599
