### ISSUE TITLE
[Feature Request]: Rename "Avoid Accidental Unsubscription" to "Confirm before unsubscribing"

### ISSUE THREAD

**Issue by jn64** [FreeTubeApp/FreeTube#5340]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

0.21 introduced a new setting "Avoid Accidental Unsubscription" which is vague.

### Proposed Solution

Rename the setting to "Confirm before unsubscribing"

Use sentence case #5000

### Alternatives Considered

NA

### Issue Labels

improvement to existing feature

**Comment by Jaishree2310** [comment]
Hey @jn64 @kommunarr, can you please assign this issue to me?
Thanks!

**Comment by Jaishree2310** [comment]
Hi @absidue, I have opened a PR can you please review it? 
Thanks!!
