### ISSUE TITLE
[Feature Request] SponsorBlock

### ISSUE THREAD

**Issue by HolySoap** [FreeTubeApp/FreeTube#535]
Hello,
with the ongoing demonetization on **YouTube** more and more people getting annoying sponsors and self-promotion you can't get rid of, and that's where **SponsorBlock** comes in action. It's something I don't wanna miss in the browser any more and **YouTube Vanced** implemented it in their last version too.
It uses the **_GPL v3.0_** ([CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) for the API) licence and can be found [here on GitHub](https://github.com/ajayyy/SponsorBlock).

I know that this is a duplicate of #471 and #487 but both are closed without any progress.

**Comment by PrestonN** [comment]
I don't know what you're looking at, but #471 isn't closed.  It's planned, but it's lower priority for now.  There are several other things that I need to work on first.
