### ISSUE TITLE
[feature request] Always-on-top mini player

### ISSUE THREAD

**Issue by Icing-weaponry** [FreeTubeApp/FreeTube#536]
Hi there,

I don't know if it's already implemented, I was unable to find anything regarding this feature but it would be nice to have an "always-on-top" option for the mini player.

I use that function very often in my browser with an add-on but having it bake into freetube would be the dream.

thank you for your time

**Comment by PrestonN** [comment]
It's already implemented.  In the mini-player, hit `Alt` on your keyboard and go to Window -> Toggle Always on Top.

The mini-player is getting removed on Friday anyways in replacement for the built in PiP mode so this issue can be closed.

**Comment by Icing-weaponry** [comment]
thanks for your help and the info!
