### ISSUE TITLE
[Bug]: Channels "Channel list" tab empty: "0 channel(s) found."

### ISSUE THREAD

**Issue by redactedscribe** [FreeTubeApp/FreeTube#5360]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

This has been present since 0.19.2 *at least* for me. Updating to 0.21.0 did not change the situation. It's been so many months since I've seen anything under this tab I'm not even sure what it's meant to look like. In fact, I might have never seen anything under this tab. All I know is that it shows 0 channels when presumably it should display something.

### Expected Behavior

Should not be an empty page since I have many subscriptions.

### Issue Labels

content not loading

### FreeTube Version

0.21.0

### Operating System Version

Windows 11 Pro

### Installation Method

Scoop (Unofficial)

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

Unsure

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please follow these steps:

1. Launch FreeTube
2. Open the dev tool with `ctrl + shift + i`
3. Go to the Channel List page
4. See if there are any red errors listed in the console of the dev tools
5. Make a screenshot and upload here

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> My second guess is that it's related the instance I'm using

is your primary API set to Invidious?

**Comment by Gorrrg** [comment]
Is there more than one instance of FreeTube running? Look in Task Manager if there is a windowless stale FreeTube.exe process, kill it and try again. There's an issue where the new instance can't read the databases because the first one that crashed is still blocking file access.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Would you like to provide your .db file so i can look around if i can manage to find the culprit in there?
