### ISSUE TITLE
[Bug]: Video doesn't sometimes offer quality selection button in the UI playback upon playing it and plays in 144p and/or 240p instead

### ISSUE THREAD

**Issue by dustter** [FreeTubeApp/FreeTube#5365]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to a video
2. Play it
3. The bug occurs
![ZeosL3kDlg](https://github.com/FreeTubeApp/FreeTube/assets/54286558/a3c42abe-b6e5-41ce-b2a2-1e5ac8e9fc5d)

### Expected Behavior

Quality selection should appear regularly everytime + play in my set-up resolution (1080p in my case).

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

0.21.0

### Operating System Version

W11 24H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.20.0 and prior I have used

### Additional Information

It's a random occurrence, doesn't happen everytime.
There IS a temporary workaround of completely closing the app window if I opened the video in a new instance and than reopening it, or returning to the video backwards and forwards if in the same window, but I still consider this unintended behavior, as it is only happening in this latest version. 
EDIT: Nightly included.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isnt a bug. FreeTube sometimes has to fallback to the `Legacy Video Format` when something goes wrong when fetching the `Dash Video Format`.

**Comment by dustter** [comment]
So I was just lucky with it this whole time? Because as mentioned, it only started happening in 0.21.0.

**Comment by absidue** [comment]
You'll get the same problem if you go back to previous versions, the problem is caused by YouTube messing around and trying to stop FreeTube from using DASH, see #5350.

**Comment by dustter** [comment]
> You'll get the same problem if you go back to previous versions, the problem is caused by YouTube messing around and trying to stop FreeTube from using DASH, see #5350.

Fair enough, but what does it have to do with the fact of "stopping loading during playback"? That's not my issue. Or it's different behaviors then? They try to stop the playback loading for some, and for some as me, it automatically loads lowest quality?

**Comment by absidue** [comment]
If you scroll down a bit further, you'll find a comment from me saying that YouTube is returning HTTP 403 error codes, which means access denied and is what they use as a block.
