### ISSUE TITLE
Preview timeline of video on hover

### ISSUE THREAD

**Issue by GilgusMaximus** [FreeTubeApp/FreeTube#537]
On YouTube you can hover over a video element and it displays a few images from different point of the video.

This behavior would be very nice to be replicated in FreeTube.
If there is not a predefined way the image sequence is accessible, we could simply download the large storyboard and pick a few images from there to play.

The question how performant that is and whether it influences the speed at which YouTube ratelimits a user must be tested beforehand.

**Comment by peepopoggers** [comment]
It is now in FreeTube unless you are talking about thumbnail previews.
