### ISSUE TITLE
[Feature Request]: Sort playlists by date ascending / descending

### ISSUE THREAD

**Issue by shakeyourbunny** [FreeTubeApp/FreeTube#5381]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Playlists are not sortable by date either ascending or descending.

### Proposed Solution

Add feature that playlists may be sorted by date in either direction.

I looked at the JSON for the playlists and they do not save the upload date of the video. If this would get be implemented, adding videos should include the upload date information in the list to avoid unnecessary lookups and API calls.

For current playlists, Freetube should add that information. Note that there may be very long playlists (2000+ videos in my imported youtube favorites), so that the requests should be done in chunks or to avoid blockage.

### Alternatives Considered

Alternative would be resorting to manual manipulation of the JSON files.

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We are unable to implement this. On YT publish dates don't exists on some videos. Invidious also does not return them inside playlists.
