### ISSUE TITLE
[Bug]: Can't watch a wrongfully? age-restricted video

### ISSUE THREAD

**Issue by WatchOfTime** [FreeTubeApp/FreeTube#5383]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Before all I had to do to play an age-restricted video was change the API & sometimes proxy the video through invidious, but now it doesn't work. I checked on youtube directly and it IS age-restricted, but I also have a feeling the video was only age-restricted because there are curse words in the title.

### Expected Behavior

to play a video

### Issue Labels

API issue, content not loading, feature stopped working, usability issue

### FreeTube Version

v0.21.0

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

v0.19.2

### Additional Information

The video was "motor spirits mikey drum cam fuckin rippin this shit" by the band King Gizzard and the Lizard Wizard.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by WatchOfTime** [comment]
I don't have a default instance, but when I tried, it was set to https://invidious.incogniweb.net/

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
If you try to play the video on the instance it self it wont play. I suggest opening an issue on their repo.

**Comment by WatchOfTime** [comment]
Okay thanks.
