### ISSUE TITLE
[Feature Request]: Timestamps from comments on video timeline

### ISSUE THREAD

**Issue by Nobylo** [FreeTubeApp/FreeTube#5388]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There's that inconvenient problem where you're looking at a music album in youtube and someone was nice enough to write down the timestamps for all the songs, but every time you wanna go to a new song you need to scroll all the way down to that comment to select a timestamp. That inconvenience also comes up if you're ever looking for any other sort of highlights to a video, like funny moments in a comedy compilation or where the solution is actually shown in a help video.

### Proposed Solution

Displaying comments with timestamps as a dot on the video timeline would solve the above problems alongside making the user experience generally more convenient.

[This has already been done for Youtube with an open source browser extension.](https://github.com/ris58h/youtube-timestamps) You could base your implementation off this like you did with sponsorblock.

### Alternatives Considered

Implementing the timeline popularity graph some youtube videos have now could also solve the issue (since people clicking the timestamps would show up as spikes) but it could be much harder to implement.

### Issue Labels

display more information to user, new feature

### Additional Information

If you have any doubts about how well this idea would work then I recommend you try it out yourself via the link above. Here is a screenshot showcasing how their implementation looks:
![screenshot](https://github.com/FreeTubeApp/FreeTube/assets/93540280/0ccc97fb-e855-4701-bcf8-6e0aa1de444e)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Thanks for the suggestion but what I have seen from testing is that this can easily be abused by bots. Also I think this is just a too niche of an usecase to implement. We would probably also need to create a custom build of our player and I dont see that happening.
