### ISSUE TITLE
[Bug]: Invalid JSON on Flatpak install

### ISSUE THREAD

**Issue by Luiz-C-Lima** [FreeTubeApp/FreeTube#5394]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

If using Local API, you get the following error when trying to play a video "SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON"
If using the Invidious API you get the same error as soon as you open FreeTube.

This appears to only happen with a Flatpak install, the Appimage is working fine.

### Expected Behavior

To be able to play videos just like the Appimage.

### Issue Labels

API issue

### FreeTube Version

0.21.1

### Operating System Version

Ubuntu 22.04

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.21.0

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please do the following:

1. Open the dev console by pressing ctrl + shift + i
2. Produce the error
3. Make a screenshot of the red errors in the console

**Comment by Luiz-C-Lima** [comment]
Strange, I am getting an Invidious error despite using local API.

Using Local API
![localAPI](https://github.com/user-attachments/assets/3b0fbe0d-2f12-4a2a-b85a-c626115f2355)

Using Invidious
![invidious](https://github.com/user-attachments/assets/6d9925ca-2082-443d-bdd8-d5142fdc153b)

**Comment by Luiz-C-Lima** [comment]
Just to add some information, after seeing this Invidious error on Local API, I changed to Invidious API and changed from the default yewtu.be instance to the invidious.privacyredirect.com instance and then changed back to Local API, and now both the Local API and Invidious API are working without any errors.
It appears that the Local API is trying to force the use of Invidious.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah you are seeing these errors because of the current Invidious instance you are using. Please only use Invidious instances that are listed in the Instances field. To see all supported instances type in `https://`

**Comment by Luiz-C-Lima** [comment]
> Ah you are seeing these errors because of the current Invidious instance you are using. Please only use Invidious instances that are listed in the Instances field. To see all supported instances type in `https://`

But should this happen despite me using the Local API? I even have fallback disabled.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It could still occur on the video player page when you have the following setting enabled:

Settings -> Player settings -> `Proxy Videos Through Invidious`
