### ISSUE TITLE
How to run - dev version?

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube#540]
Could you write tutorial, how to configure environment to update source and build Freetube from new repo?

I tried to use steps from Freetube-Vue, but it doesn't work. There is message " npm ERR! missing script: dev"

When I used "npm run start", then I saw old version of Freetube (0.7.3)

**Comment by PrestonN** [comment]
There are slightly different directions depending on which version of FreeTube you're using (Live versus Vue remake).

The directions in the Vue repository are only valid for the Vue build.  Build instructions for the live release over in the Wiki over [here](https://github.com/FreeTubeApp/FreeTube/wiki/Environment-Setup-and-Packaging).

Please know that we're currently in the process of migrating the Vue code over to this repository as we're releasing tomorrow, so things might be messed up a little bit until migrations are complete.  I would maybe hold off for a little bit before trying to work on building anything.

**Comment by pawlosck** [comment]
OK. I tried to setting up, but I couldn't run, so I will wait one or two days until you fix all bugs connected with moving repo.
There is problem with file package.json (I copied from Freetube-Vue and looks well) and script start (npm ERR! missing script: start)

I would like to test new features :).

**Comment by pawlosck** [comment]
Did you fixed all problems? I can't build Freetube. 

npm start
npm ERR! missing script: start

**Comment by PrestonN** [comment]
The instructions are as follows:

Install Dependencies:

`npm install`

Run in Development Mode:

`npm run dev`

If you come across any issues with this then you may need to upgrade your node version.  Let me know if you come across any problems.

**Comment by pawlosck** [comment]
Thanks. Now it works. Could you update wiki? There are other steps on the wiki.
https://github.com/FreeTubeApp/FreeTube/wiki/Environment-Setup-and-Packaging

**Comment by PrestonN** [comment]
I'm updating it as I type this actually.  Will be updated shortly.
