### ISSUE TITLE
[Bug]: "SyntaxError: Unexpected token (1:47)" shows up for every video

### ISSUE THREAD

**Issue by SeoReadeHenn** [FreeTubeApp/FreeTube#5402]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click on any video
2. The error "SyntaxError: Unexpected token (1:47)" will appear without exception, shortly followed by "Falling back to Invidious API"
3. In about 2/3rds of cases, either the error "NotSupportedError: Failed to load because no supported source was found." will appear and the video will not play, or the error "undefined" will occur in the Invidious API and the video will fail to load whatsoever.
4. Additionally, upload dates are now missing from all the videos that appear on the right side of the screen while watching a video.

### Expected Behavior

The errors should not show up and videos should play as normal.

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.21.0

### Operating System Version

Windows 10 version 22H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

I only began to experience this issue a few days ago, which I believe is shortly (but not immediately) after i switched to 0.21.0.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Please upgrade FreeTube to 0.21.1, which fixes that problem.

**Comment by SeoReadeHenn** [comment]
> Please upgrade FreeTube to 0.21.1, which fixes that problem.

I was unaware an update was available yet, thank you!
