### ISSUE TITLE
[Bug]:  Video is not Playing 

### ISSUE THREAD

**Issue by exefile2** [FreeTubeApp/FreeTube#5403]
### Guidelines

- [ ] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Video is not playing in FreeTube. Showing Error.

SyntaxError: Unexpected token (1:47)
![Screenshot (233)](https://github.com/user-attachments/assets/40668aed-7377-46cf-a11e-6d82a4576f88)

### Expected Behavior

The video should play, but its not playing and showing this error- SyntaxError: Unexpected token (1:47)
![Screenshot (233)](https://github.com/user-attachments/assets/f3502629-eec1-4c72-8bcc-4737313074a1)

### Issue Labels

API issue

### FreeTube Version

v0.19.2 Beta

### Operating System Version

Windows 10 pro

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Update to 0.21.1 and it'll work, you are still on 0.19.2.

**Comment by exefile2** [comment]
> Update to 0.21.1 and it'll work, you are still on 0.19.2.

Done
