### ISSUE TITLE
[Bug]: Full Window mode not available on some videos

### ISSUE THREAD

**Issue by Venomtek** [FreeTubeApp/FreeTube#5406]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

On some videos, the full window toggle does not show, and using the keyboard shortcut does nothing.
It appeared after I quit the program and came back a few hours later.

### Expected Behavior

I expect to see the full window option.

### Issue Labels

feature stopped working

### FreeTube Version

v0.21.1 beta

### Operating System Version

Windows 11 23H2

### Installation Method

Portable

### Primary API used

Local API

### Additional Information

![Screenshot 2024-07-13 180121](https://github.com/user-attachments/assets/1499d0ad-1f1a-46fe-ba2c-ca8ee78f9670)
![Screenshot 2024-07-14 033132](https://github.com/user-attachments/assets/ba707ccb-e8f6-4730-8dbc-7d2ab626762e)
![Screenshot 2024-07-13 182235](https://github.com/user-attachments/assets/59500332-ba1b-4181-ba50-5cc689006253)
![Screenshot 2024-07-14 032819](https://github.com/user-attachments/assets/bf59a8a6-6da5-4a32-8b64-33da73465ba7)
![general](https://github.com/user-attachments/assets/8407b968-e692-491d-97e5-b51d567ca580)
![player](https://github.com/user-attachments/assets/70cc979c-ebd6-4d04-85cf-225bf0c57cce)
![distraction](https://github.com/user-attachments/assets/ae9edb99-cbea-4822-8cbe-e9c1b79ed5dc)

### Nightly Build

- [x] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Venomtek** [comment]
> Please provide a consistent way to reproduce this,

I would love to, how do I do that when it only happens on 10% of videos?

**Comment by Venomtek** [comment]
> If there is no way to reproduce how do you expect us to investigate? I tried the videos in the screenshots and all worked fine for me.
> 
>     * Please share the red errors in the dev console (ctrl + shift + i) when this is occurring for you.
> 
>     * Also could you make a screenshot of the general, player and distraction free settings

I don't know, how about giving me some insight into how to diagnose this and provide more information, I looked at the .LOG files in %APPDATA\FreeTube but they are all binary.  The next video this happens with I can go into Dev Tools now that I know about it from reading other issues.

I guess I will just leave this open for others to find when they have the same problem too.

**Comment by Venomtek** [comment]
>     * Also could you make a screenshot of the general, player and distraction free settings

I've added the requested screenshots "addition information" section.

**Comment by Venomtek** [comment]
So what am I looking for here, it's all gobbledygook to me...  Notice the lack of full window toggle button.

![image](https://github.com/user-attachments/assets/fd646ff8-c185-4351-b712-d8f16c214fbe)

**Comment by Venomtek** [comment]
when I clicked the Fullscreen button, then go back to non-Fullscreen, the Full Window button showed up.
![image](https://github.com/user-attachments/assets/17feec7b-b14a-48f7-977e-8f8865e07048)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Well we are looking for red errors but as far i cam see i only see the yellow warnings meaning that it might not throw any errors

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Tried to reproduce it to copy your settings but failed to do so. In our next minor release we will migrate to another player so I hope that solves this weird behavior. Please keep sharing information on errors or how to reproduce this better.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
fixed by the player migration, will be available in the next minor version
