### ISSUE TITLE
[Bug]: Failed to Connect to Bus

### ISSUE THREAD

**Issue by Tahinli** [FreeTubeApp/FreeTube#5422]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Try to open

### Expected Behavior

To be opened

### Issue Labels

causes crash

### FreeTube Version

0.21.1 Beta

### Operating System Version

Fedora 40 Kde Plasma

### Installation Method

.apk (Alpine Linux Package)

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

It was working yesterday :D

### Additional Information

Flatpak Version Crashes When I Try to Open
<img width="693" alt="image" src="https://github.com/user-attachments/assets/c4ff6090-a113-45d4-97b2-e47a62eaf2bd">

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Tahinli** [comment]
After restarting computer, it opened but with these errors.

<img width="399" alt="image" src="https://github.com/user-attachments/assets/6c48bebf-6deb-4101-8ce9-2bed1b9c0c0c">

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@bbhtt any idea why this is happening. I also saw this popping up but FT just ran fine.

![Capture](https://github.com/user-attachments/assets/13d1f5ec-5c70-4f28-8389-c391192488d5)

**Comment by bbhtt** [comment]
Those are not an issue, it's because of the sandbox restricting access to sockets.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah okay thats expected. Closing as this isnt a bug and those messages are purely informative.

Thanks for clarifying @bbhtt :)

**Comment by mooreye** [comment]
What Flatpak override needs to be done to fix this? I randomly have this problem.

**Comment by Erothas** [comment]
> What Flatpak override needs to be done to fix this? I randomly have this problem.

Enabling this in flatseal worked for me:
![image](https://github.com/user-attachments/assets/ddcdb957-dcc0-433e-9daa-057322b7c598)

You could easily do this through the terminal, if you prefer not going through the flatseal route. The socket is just called `wayland`.

**Comment by mooreye** [comment]
@Erothas I already have this, actually without this it wouldn't run on Wayland at all (without fallback to X). I still randomly experience this issue. Sometimes running Freetube again works, but sometimes I have to relogin my whole user.
