### ISSUE TITLE
[Feature Request]: Move "Chapters" to the right side not bottom

### ISSUE THREAD

**Issue by codeduph** [FreeTubeApp/FreeTube#5424]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

the "Chapters" is a bit annoying that you need to scroll down every time you want to skip to a particular part...

### Proposed Solution

just move it to the right side just like in youtube....

### Alternatives Considered

![2024-07-17_011251](https://github.com/user-attachments/assets/ba78057a-965a-449c-b91f-5517ff6b5a2e)

![2024-07-17_011045](https://github.com/user-attachments/assets/8e1c65ce-735d-4803-bee3-ba66949346fb)

### Issue Labels

improvement to existing feature

**Comment by absidue** [comment]
Would a chapters menu inside the player, in addition to keeping the existing one, work for you?
That would avoid needing to have multiple layouts because having it on the side would only work for people that have the window big enough, like yourself.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
If thats the case im going to close this issue in favor of https://github.com/FreeTubeApp/FreeTube/issues/2829
