### ISSUE TITLE
[Feature Request]:  control of the volume and play in PiP

### ISSUE THREAD

**Issue by Janaue** [FreeTubeApp/FreeTube#5428]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I am interested in having the same control of the volume in the PiP as on the main regular view: possibility to mute a video by clicking on the speaker, and possibility to change the volume with a slider.  Same thing with the playing button and the theater + full screen button

### Proposed Solution

just make the current control mechanism of the volume and play and size available on the picture in picture mode.

### Alternatives Considered

NA.

### Issue Labels

display more information to user

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Unfortunately this isnt possible due to the limited implementation of the upstream PIP window
