### ISSUE TITLE
[Bug]: Window size defaults when starting on system boot

### ISSUE THREAD

**Issue by Eiion** [FreeTubeApp/FreeTube#5433]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I've set FreeTube to start on system boot and after every startup FreeTube is back to its default window size. It also doesn't remember its position on the screen.
Considering how small the default window size on a 1440p 25" screen is I have to manually adjust the window size after each start.

I'm reporting this as a bug as this should've been fixed 6 years ago wit this closed report https://github.com/FreeTubeApp/FreeTube/issues/71.

### Expected Behavior

FreeTube remembers window size and position it was when closing and reopens in the exact same position and size.

### Issue Labels

feature stopped working, inconsistent behavior

### FreeTube Version

v0.21.1 Beta

### Operating System Version

Windows 10 Pro Version	10.0.19045 Build 19045

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
FreeTube correctly saves that information on my machine. Please make sure FreeTube has time to save the information e.g. close the app manually before shutting down your computer, because when Windows force closes it, FreeTube doesn't have enough time to save it.
