### ISSUE TITLE
[Bug]: Colors mismatch

### ISSUE THREAD

**Issue by Dirk9220** [FreeTubeApp/FreeTube#5449]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

On opening the program, all colors are blueish. Also, all opened video's have the same issue. It doesn't happen when viewing YT in Firefox.  See screenshots :) FYI, I did not make any changes in my settings. All other video-viewers work normal.
![Schermafdruk_2024-07-23_13-43-48](https://github.com/user-attachments/assets/564291b4-9433-4f08-8958-f1952f5e3da4)
![Schermafdruk_2024-07-23_13-44-26](https://github.com/user-attachments/assets/ae80ba18-216d-4a19-83dc-986c65360340)

### Expected Behavior

Colors should show as real, not as if RGB flipped over into BRG or something.  I don't know if it's possible, but I suspect YT to alter settings to annoy FT users.  

### Issue Labels

usability issue

### FreeTube Version

v0.21.1beta

### Operating System Version

Linux Carbon670E 6.10.0-x64v4-xanmod1 #0~20240716.gabb00c5 SMP PREEMPT_DYNAMIC Tue Jul 16 01:56:51 UTC x86_64 x86_64 x86_64 GNU/Linux

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.0

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Please check that you don't have invert colors or other accessibility color filters turned on in your operating system. Also worth checking that your graphics card drivers are working correctly, as from your screenshot only images and videos are getting rendered incorrectly. Additionally please try a chromium browser, to see if the same issues happen there.

**Comment by Dirk9220** [comment]
I'm not aware of any color filters on my system. Graphics are AMD RX6600 (amdGPU driver from Mesa 24.3 (Oibaf ppa))
Rendering in other programs is flawless, except for the Chromium...
![Schermafdruk_2024-07-23_19-03-44](https://github.com/user-attachments/assets/0f87af57-017d-474c-8cd7-15f422366b65)
![Schermafdruk_2024-07-23_19-04-16](https://github.com/user-attachments/assets/0231e3ff-ab14-4c33-b7eb-cc45a9e110b9)
 ![Schermafdruk_2024-07-23_18-22-35](https://github.com/user-attachments/assets/bf890850-c828-4f98-aa83-7fbf1bfdab88)
![Schermafdruk_2024-07-23_18-23-58](https://github.com/user-attachments/assets/80c514e6-45f1-4b23-ac27-abf79b893386)

**Comment by Dirk9220** [comment]
I installed that Chromium to test . As it displays the same flaw, I will remove it now. What do I do now ?

**Comment by absidue** [comment]
I suspect it is either a driver issue or a bug in Chromium, in both cases there is nothing we (the FreeTube team can do about it on our side). It's probably the same bug that is happening in https://github.com/FreeTubeApp/FreeTube/issues/5420.

**Comment by Dirk9220** [comment]
I had Chromium installed because you suggested it to be the culprit. This was correct, after that I removed it again (including related files and settings). The XanMod kernel is now replaced with 5.15.0-116-generic, the result is the same.
![Schermafdruk_2024-07-23_20-07-11](https://github.com/user-attachments/assets/f19b0006-ce5d-4476-9a62-6ac0665b7766)
The difference with #5420 is that videos don't play OK and the overlay doesn't go away after clicking.

**Comment by absidue** [comment]
FreeTube uses Electron, which is based on Chromium, which is why I suggested you should test Chromium too. As you confirmed that it happens with Chromium alone as well, it is either a bug in Chromium or something else going wrong in the chain e.g. the graphics drivers. Currently I'm leaning towards it being something with your setup, as you seem to be the only person experiencing the problem.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Going to close it as we cant solve this on our end but feel free to keep discussing it to try to find an solution

**Comment by Dirk9220** [comment]
Might be, but as I stated before, nothing has changed in my setup. And the glitch happened after upgrading to v0.20.x, my guess is the Chromium has a problem. I'll keep an eye on it and for the time being, I'll hang on. Thanks for your assistance.

Beleefde groeten

https://drive.proton.me/urls/50DEGNWJ4M#KFy1MJH6WkH6

Verzonden met [Proton Mail](https://proton.me/) beveiligde e-mail.

Op dinsdag 23 juli 2024 om 22:01 schreef absidue ***@***.***>:
