### ISSUE TITLE
Option to disable recommended videos?

### ISSUE THREAD

**Issue by lucanomax** [FreeTubeApp/FreeTube#545]
I really like the new UI, but I kinda miss the "no-distraction mode" that hide all the unnecessary stuff on the screen (comments, related videos). What do you guys think?

**Comment by PrestonN** [comment]
This is coming.  I'll be revamping how the "Distraction Free Mode" worked to allow you to fine-tune what gets hidden in the UI.  I simply wasn't able to get this finished in time for this release.  It's definitely planned though!

**Comment by heartlessglasses** [comment]
I believe it was mentioned that it will be re-added to the rewrite later! (When it comes back, would also be great if it still showed the channel name and description, that is sadly the only thing preventing me from using distraction-free mode in the old version.)

**Comment by heartlessglasses** [comment]
> 
> 
> This is coming. I'll be revamping how the "Distraction Free Mode" worked to allow you to fine-tune what gets hidden in the UI. I simply wasn't able to get this finished in time for this release. It's definitely planned though!

!! Fine-tuning it would be perfect, thank you!

**Comment by lucanomax** [comment]
> 
> This is coming. I'll be revamping how the "Distraction Free Mode" worked to allow you to fine-tune what gets hidden in the UI. I simply wasn't able to get this finished in time for this release. It's definitely planned though!

Nice! Take your time tho!

>
> I believe it was mentioned that it will be re-added to the rewrite later

I checked recent issues and read blog posts but eventually i missed it.
