### ISSUE TITLE
Breakpoint reached on shutdown

### ISSUE THREAD

**Issue by NikNikovsky** [FreeTubeApp/FreeTube#5451]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

So I watched a video earlier
I tried to shutdown the computer a bit later (around 30 minutes or more 
A breakpoint  error popped up on shutdown 

### Expected Behavior

The computer should have just shutdown 

### Issue Labels

causes crash

### FreeTube Version

0.21.1 beta

### Operating System Version

Windows 11 23H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.21.1 beta 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Did you shutdown the machine while FreeTube was still running?

**Comment by NikNikovsky** [comment]
Yes
