### ISSUE TITLE
[Bug]: Error: No valid URL to decipher

### ISSUE THREAD

**Issue by ArthurKun21** [FreeTubeApp/FreeTube#5453]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click a video (there is no consistent video where I keep encountering the error)
2. Encounter the error

### Expected Behavior

Be able to watch video

### Issue Labels

content not loading

### FreeTube Version

b2fe59d331289e0365f67e04e0186e17374b8d1c

### Operating System Version

Windows 11 22635.3930

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

```js
Error: No valid URL to decipher
    at wF.decipher (renderer.js:2:1363128)
    at iD.decipher (renderer.js:2:1126826)
    at BN (renderer.js:2:1410819)
    at MN (renderer.js:2:1410695)
    at async r.getVideoIn

renderer.js:2 TypeError: Cannot read properties of undefined (reading 'primaries')
    at new iD (renderer.js:2:1125270)
    at PN (renderer.js:2:1404973)
    at r.createInvidiousDashManifest (renderer.js:2:1906203)
    at async renderer.js:2:1896383

TypeError: Cannot read properties of undefined (reading 'primaries')
    at new iD (renderer.js:2:1125270)
    at PN (renderer.js:2:1404973)
    at r.createInvidiousDashManifest (renderer.js:2:1906203)
    at async renderer.js:2:1896383
```

I actually have been encountering this issue for the past few days and just managed to capture it.

I have also been using [Pikachu's shaka build](https://github.com/PikachuEXE/FreeTube/commit/61883ee4b5c5247b38ac1e77055408f19f6b7270) and on there while I did not capture it, I am getting 403 error

navigating away and clicking the video again fixes the issue.

https://github.com/user-attachments/assets/a578562c-4a80-49a2-8828-f00cdd697f7f

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by OothecaPickle** [comment]
+1, started experiencing this error on videos today

**Comment by M-Hamano16** [comment]
Last week I had the same issue everyone else had where the screen would flicker.  Now with the new version (I think it is 21.2) it stopped doing this. 

What I get now is when I first load up the program ( I have it on 3 seperate computers) it will fail on the first load of a video and give me some message.  When I refresh it works OK.  I notice that I don't have resolution options sometime, and if I refresh it fixes that.  It seems to be more consistent if I go away for a few hours and then try and watch a video later (when there is a break in between usage)
