### ISSUE TITLE
[Bug]: Tiny cursor on wayland session while using fractional scaling

### ISSUE THREAD

**Issue by EstimatorZeppelin** [FreeTubeApp/FreeTube#5454]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When using FreeTube flatpak via a wayland session, and also having fractional scaling turned on, the cursor ends up becoming extremely tiny. This issue isn't present when using via xwayland, however on displays that require fractional scaling, it results in a very blurry and low resolution interface.

It had been reported in the electron issue tracker earlier [here](https://github.com/electron/electron/issues/19810)

However, this pretty much requires individual app fixes to rectify the issue as per [this](https://discuss.kde.org/t/electron-wayland-tiny-cursor-size/13674)

Other [screenshots](https://github.com/electron/electron/issues/19810#issuecomment-567042495) of this issue

Screenshot from FreeTube:

![cursor](https://github.com/user-attachments/assets/a9758ec3-0de4-4a46-a1a9-ea8cbb91d1d1)

### Expected Behavior

The cursor is rendered at the proper size

### Issue Labels

usability issue, visual bug

### FreeTube Version

v0.21.1 Beta

### Operating System Version

Ubuntu 24.04 LTS

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

Fixing this issue should make FreeTube pretty much completely wayland compatible

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Try https://github.com/FreeTubeApp/FreeTube/issues/2799#issuecomment-1825542263

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@bungadrum any ideas?

**Comment by ssnepenthe** [comment]
Overriding the XCURSOR_PATH env var (`XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons`) seems to fix the issue.

Ref https://github.com/flathub/com.visualstudio.code/pull/490/files

**Comment by sith-on-mars** [comment]
> > Overriding the XCURSOR_PATH env var (`XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons`) seems to fix the issue.
> > Ref https://github.com/flathub/com.visualstudio.code/pull/490/files
> 
> Overriding did indeed fix the issue, thank you very much for the solution to this. It would be better, if it is added by default though.

Agree. Many electron apps have this by default, such as Signal and Obsidian.
