### ISSUE TITLE
[Bug]: Dropdown selection menus not opening

### ISSUE THREAD

**Issue by Spookakra** [FreeTubeApp/FreeTube#5460]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Dropdown menus don't display content when pressed making it impossible to do certain tasks.

### Expected Behavior

Normally the Dropdown menu would display content when interacted with.

### Issue Labels

feature stopped working, usability issue

### FreeTube Version

v0.21.1

### Operating System Version

macOS Catalina 10.15.7

### Installation Method

.dmg

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.2

### Additional Information

https://github.com/user-attachments/assets/946787d5-c986-4f00-8153-a0e6be27c575

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Looks like it's a known bug in Electron and they have already fixed it, we just need to wait for them to release a version with the fix and upgrade to it :).

**Comment by absidue** [comment]
Fixed by #5584

Specifically by the following entry in Electron's changelog:
> Fixed several view hierarchy issues related to web contents view on MacOS.
