### ISSUE TITLE
[Bug]: Don't unpin Windows taskbar icon (if pinned) upon installing new update

### ISSUE THREAD

**Issue by PrivacyFriendlyMuffins** [FreeTubeApp/FreeTube#5473]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Make sure Freetube is already installed (but not the newest version).
2. Pin Freetube to Windows taskbar.
3. Download & install the newest version.
4. Freetube will no longer be pinned to taskbar.

### Expected Behavior

Freetube being kept pinned to Windows taskbar through version updates.

&nbsp;

(**As a side-note**: I apologize if the Issue Label I selected below is incorrect. I honestly wasn't sure which was most applicable, so I chose the one I thought least........inapplicable? Words are hard.)

### Issue Labels

accessibility issue

### FreeTube Version

v0.21.2 Beta

### Operating System Version

Windows 10 version 22H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

NA

### Additional Information

Not sure if it matters, but this happens regardless of whether I have the primary API used set to Local or Invidious before installing the new update.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChienKaiMa** [comment]
This also happens to me with Windows 11 23H2.

**Comment by PrivacyFriendlyMuffins** [comment]
Um... Here's a comment to keep the thread open.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is an upstream issue. There is no FreeTube code involved in the installer, so there is nothing we can change on the FreeTube side to fix it
