### ISSUE TITLE
[Bug]: Invalid Digital Signature

### ISSUE THREAD

**Issue by hix1000** [FreeTubeApp/FreeTube#5474]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Invalid digital signature

### Expected Behavior

Valid digital signature

### Issue Labels

API issue, text/string issue

### FreeTube Version

v0.21.2

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.1

### Additional Information

Unknown on how it was caused

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Did you get this before opening the application?

**Comment by hix1000** [comment]
Yes

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not a bug. See: https://github.com/FreeTubeApp/FreeTube/issues/1520#issuecomment-881112252

**Comment by hix1000** [comment]
oh, my bad, it's just Microsoft being greedy
