### ISSUE TITLE
[Bug]: Video Not Playing 

### ISSUE THREAD

**Issue by exefile2** [FreeTubeApp/FreeTube#5477]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

While opening a video, the video is not playing and showing an error.
![Screenshot (242)](https://github.com/user-attachments/assets/a728dbf6-34d3-44e4-9984-446b1d6d5bb7)

### Expected Behavior

The video should play but showing an error every time.

### Issue Labels

API issue

### FreeTube Version

v0.21.1 Beta

### Operating System Version

Windows 10 pro

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.19

### Additional Information

This issue is happening with every video, and other youtube clients were facing the same issue like newpipe but now it is fixed... And now freetube is facing the issue and need to be fixed soon...

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
It has already been fixed, you need to upgrade to 0.21.2.
