### ISSUE TITLE
[Feature Request]: Allow to sort the channels per Account

### ISSUE THREAD

**Issue by CodingMadness** [FreeTubeApp/FreeTube#5479]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When I open FreeTube, I see all the videos from my 4-5 Abos mixed on the "Subscription" Tab,
right now its like: 
    YoutuberA: [VideoA1, VideoA2] 
	YoutuberB: [VideoB1, VideoB2]
	YoutuberA: [VideoA3, VideoA4, VideoA5]
	YoutuberB: [VideoB3, VideoB4]

### Proposed Solution

I would love to have it like this:

YoutuberA: [VideoA1, VideoA2, VideoA3, VideoA4...VideoAX]
YoutuberB: [VideoB1, VideoB2, VideoB3, VideoB4...VideoBX]

or something like this, so would be super clean to see in 1 section ONLY videos from YoutuberA, then only videos from YoutuberB and so on.. 

### Alternatives Considered

none.		

### Issue Labels

ease of use improvement, new optional setting

### Additional Information

none.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
If you want to see all the videos from one channel its best to visit the channel itself. You can also use our profiles feature to put the channel in a separate profile: https://docs.freetubeapp.io/usage/profiles/
