### ISSUE TITLE
[Bug]: Some videos not showing in Subscriptions page

### ISSUE THREAD

**Issue by swilly97** [FreeTubeApp/FreeTube#5481]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to Subscriptions Page
2. Scroll through
3. Random videos do not show up in Subscriptions
4. Go to channel page and find video manually
5. start playing video
6. go back to subscriptions page
7. video is now visible in Subscriptions page, 

### Expected Behavior

New videos should be visible in the subscriptions page.

### Issue Labels

content not loading, feature stopped working, inconsistent behavior

### FreeTube Version

v0.21.2

### Operating System Version

Ubuntu MATE

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@swilly97 could you provide a screenrecording of this?

**Comment by James-Fire** [comment]
I have the same issue. I have noticed that some videos do not show up in subscriptions.

https://github.com/user-attachments/assets/7b8174bb-7863-4732-b18c-722f87a29545

I have attached a video showing an unwatched video that should be showing up, but it clearly doesn't. It does not seem to be a channel issue, as there are videos from the channel that do show up, as shown in the attached. I have noticed that sometimes when I refresh, I will have a bunch more videos that were not showing up before.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@swilly97 is this still an issue for you in v0.22.0?

**Comment by James-Fire** [comment]
I'm not the OP, but I did provide the video of it.

I confirm it is not fixed in v0.22.0. I just updated and then checked.

![image](https://github.com/user-attachments/assets/174de55e-1276-4eca-b1ab-d5ebcf4e6cc7)

![image](https://github.com/user-attachments/assets/e54759be-0f6b-4d05-9ce5-ede716992d0f)

The first image contains videos that *should* be showing up in the second image, but are not.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@James-Fire try the following:

1. Backup your subscriptions
2. Delete all your subscriptions
3. Close FreeTube
4. Import the subscription file you exported

**Comment by James-Fire** [comment]
I did those steps, same videos still don't show in subscriptions

It also seems to shuffle where videos appear?

![image](https://github.com/user-attachments/assets/355db0b1-a71c-414a-b311-77804fe875b2)

![image](https://github.com/user-attachments/assets/7c445376-7f73-43c9-96bc-a54f2c25845c)

Same deal, first image shows vids that should be appearing in the second one but aren't.

Second image here has all the same videos as the previous second image, plus some other ones, but they're in a different order for some reason. Does the upload time get fuzzy when it's far in the past?
