### ISSUE TITLE
[Bug]: Closed Captions broken

### ISSUE THREAD

**Issue by yahsboymatt** [FreeTubeApp/FreeTube#5482]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

After the latest beta update the Closed Caption function no longer works.  I used CC to watch videos and it worked fine prior to the new update.  

### Expected Behavior

I expect CC to work when it is enabled.

### Issue Labels

feature stopped working

### FreeTube Version

v0.21.2 Beta

### Operating System Version

Linux Mint

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

freetube_0.21.2_amd64.deb

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please make a screenrecording of this behavior.

**Comment by Bennguyen2** [comment]
The closed caption is fixed on new update 0.21.3 beta so this is no longer relevant.
