### ISSUE TITLE
[Feature Request]: Add all the features of youtube revanced extended

### ISSUE THREAD

**Issue by Barshan-Mandal** [FreeTubeApp/FreeTube#5484]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

youtube revanced is a add free solution  .You can search in google.It is very much popular for phones.You can integrate all these features in this app .I liked your app .So i am suggesting this

### Proposed Solution

https://github.com/NoName-exe/revanced-extended

https://www.bing.com/ck/a?!&&p=994acb59e8f03e4bJmltdHM9MTcyMjEyNDgwMCZpZ3VpZD0yMmI5ZWYyNi05ZTBhLTY5ZTEtMWMwZS1mYjhmOWY5MTY4ZDAmaW5zaWQ9NTIxMw&ptn=3&ver=2&hsh=3&fclid=22b9ef26-9e0a-69e1-1c0e-fb8f9f9168d0&psq=youtybe+revanced+extended&u=a1aHR0cHM6Ly9yZXZhbmNlZGV4dGVuZGVkLmNvbS8&ntb=1

### Alternatives Considered

none

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We wont add "all" features. Maybe you should look for the features you want to see on our issue tracker

**Comment by Barshan-Mandal** [comment]
But you can add some very much important features like below:
1.SponsorBlock: This open-source feature skips sponsor content, intros, outros, and reminders in videos. Say goodbye to those pesky ads!
2.Shorts Component Control: Hide or unhide various shorts components, including the Shorts button, Shorts Shelf, Comments, Remix, Thanks, and Subscription buttons. Customize your viewing experience.
3.Return YouTube Dislike (RYD): This feature allows you to view the dislike count on videos. Transparency matters!
4.Ad-Free Experience: Ads can be annoying, but ReVanced Extended lets you remove them from the Home page, videos, and other places.
5.Downloads: Download videos up to 4K at 60 FPS. 
6.Whitelist: Want to support your favorite channels? Use the whitelist option to see channel ads and sponsors while keeping the rest ad-free.
7.Extra player  Controls: Add swiping gestures,picture in picture mode to the video player. Adjust various settings for that player
