### ISSUE TITLE
[Feature Request]: Add  below features

### ISSUE THREAD

**Issue by Barshan-Mandal** [FreeTubeApp/FreeTube#5485]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Ad Blocking
Remove Video Ads: Blocks all video ads, including pre-roll, mid-roll, and banner ads.
SponsorBlock Integration: Automatically skips sponsored segments in videos.
Background Playback
Background Play: Allows videos to continue playing in the background even when the app is minimized.
Customization
Themes: Custom themes and color options for the app interface.
Layout Customization: Adjust the layout of various elements, such as hiding certain buttons or rearranging sections.
Enhanced Playback Controls
Playback Speed Control: Customizable playback speed options beyond the default 0.25x to 2x.
Resolution Override: Force the app to play videos at a specific resolution regardless of the connection speed.
Repeat Videos: Loop videos or specific parts of a video.
Enhanced User Interface
Swipe Controls: Implement swipe gestures to control volume and brightness.
PiP (Picture-in-Picture): Floating video player that allows users to watch videos while using other applications.
Privacy and Security
Incognito Mode: A browsing mode that doesn’t save watch history.
Disable Tracking: Blocks tracking and analytics scripts to enhance user privacy.
Download and Offline Viewing
Download Videos: Allows downloading videos for offline viewing with custom resolution and format options.
Download Audio: Extract and download only the audio from videos.
Enhanced Subtitles and Captions
Subtitle Customization: Adjust subtitle size, color, and background.
Automatic Subtitle Translation: Automatically translate subtitles into a user-selected language.
Miscellaneous
Disable Age Restrictions: Removes age restrictions on videos.
Custom SponsorBlock Settings: Fine-tune settings for skipping sponsored segments.
Advanced Video Stats: Displays detailed statistics for videos, such as resolution, codec, bitrate, and frame rate.
Dislike Button: Restore the dislike count for videos.
Comments Enhancement: Improved comment section with advanced sorting and filtering options.

### Proposed Solution

add them.you can follow youtube revanced extended

### Alternatives Considered

none

### Issue Labels

new feature

**Comment by NikNikovsky** [comment]
The things I believe are already done in this project:
- Ad Blocking
- Remove Video Ads: Blocks all video ads, including pre-roll, mid-roll, and banner ads.
- SponsorBlock Integration: Automatically skips sponsored segments in videos.
- Background Playback
- Background Play: Allows videos to continue playing in the background even when the app is minimized.
- Customization
- Enhanced Playback Controls
- Playback Speed Control: Customizable playback speed options beyond the default 0.25x to 2x.
- Resolution Override: Force the app to play videos at a specific resolution regardless of the connection speed.
- PiP (Picture-in-Picture): Floating video player that allows users to watch videos while using other applications.
Privacy and Security
- Incognito Mode: A browsing mode that doesn’t save watch history. (You can disable the "save watch history" option in the settings
- Disable Tracking: Blocks tracking and analytics scripts to enhance user privacy.
- Download and Offline Viewing
- Download Videos: Allows downloading videos for offline viewing with custom resolution and format options.
- Download Audio: Extract and download only the audio from videos.
- Enhanced Subtitles and Captions
- Subtitle Customization: Adjust subtitle size, color, and background.
- Automatic Subtitle Translation: Automatically translate subtitles into a user-selected language.
- Custom SponsorBlock Settings: Fine-tune settings for skipping sponsored segments.
*admins and contributors feel free to correct me*
@Barshan-Mandal Have you even checked the settings or downloaded FreeTube?
Just wondering

**Comment by ChunkyProgrammer** [comment]
Most of these seem to be implemented (and if they're not implemented there is an issue for them):
-  Repeat Videos: Loop videos or specific parts of a video.
Could you open a separate issue for `Looping specific parts of a video` @Barshan-Mandal ?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not needes see #1029
