### ISSUE TITLE
[Bug]: Subscriber count not showing up

### ISSUE THREAD

**Issue by NikNikovsky** [FreeTubeApp/FreeTube#5488]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Go to a channel:
![image](https://github.com/user-attachments/assets/8beb2050-0f4f-46e2-baf7-e7f6aad21d7d)
![image](https://github.com/user-attachments/assets/95b8d3b3-2e8d-4dcd-85f8-7e7dbbf275a4)
those are the examples but I think it's FreeTube wise, it shows 0 subscribers.

### Expected Behavior

Subscribers should show up.

### Issue Labels

API issue, feature stopped working

### FreeTube Version

0.21.2 beta

### Operating System Version

Windows 11 23H2

### Installation Method

.exe

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

0.21.2

### Additional Information

I've also noticed that the playlists tab has disappeared on one channel.
![image](https://github.com/user-attachments/assets/8d46d273-dd7f-4a72-b524-548d154defa6)
![image](https://github.com/user-attachments/assets/83c9cf7a-e220-4053-bf5d-250b1be3b3ee)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by NikNikovsky** [comment]
I just realized that if you search for a youtuber the sub count shows up
![image](https://github.com/user-attachments/assets/41f4b87c-48f0-482e-8a3e-8e00280a2e4f)
![image](https://github.com/user-attachments/assets/d17c8100-fc08-4eaa-90ed-f574c94689f8)

**Comment by ChunkyProgrammer** [comment]
Closing since this was fixed here: https://github.com/iv-org/invidious/pull/4785 . 

Some invidious instances should work (https://api.invidious.io/ the ones with the newer versions). The reason why some instances work and others don't is that some instances are deployed with the latest commits from `master` while others are deployed with the latest invidious `release` (the last release was in April)
