### ISSUE TITLE
[Bug]: Invidious API Error: Watch on the latest version of YouTube.

### ISSUE THREAD

**Issue by agirnob** [FreeTubeApp/FreeTube#5489]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Preferred API backend is local API
2. Open a video
3. Error: Watch on the latest version of YouTube. gives as an error
This error is not consistant I can't replicate every time

### Expected Behavior

Error: Watch on the latest version of YouTube. Doesn't show

### Issue Labels

content not loading

### FreeTube Version

v0.21.2 Beta

### Operating System Version

6.10.0-arch1-2 #1 SMP PREEMPT_DYNAMIC Mon, 22 Jul 2024 17:28:23 +0000 x86_64 GNU/Linux

### Installation Method

.AppImage

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.2 Beta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by wonder75** [comment]
Can confirm this. v0.21.2 Beta

Free Tube stopped working for me 2 days ago. YouTube videos don't play anymore. Just seem to load forever. Changing the Invidious instance does not fix it. Videos play fine on the websites of the invidious instances. Loading the content of channels/feeds, etc. works fine. Just playing videos fails, no matter if I use Invidious or local API.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is an issue with Invidious: https://github.com/iv-org/invidious/issues/4734

**Comment by M-Hamano16** [comment]
> This is an issue with Invidious: [iv-org/invidious#4734](https://github.com/iv-org/invidious/issues/4734)

so, if what you are saying is correct... if I disable "switch to fallback" and only use local api, we should not see this?

**Comment by agirnob** [comment]
Disabled switch to fallback still getting the same error:
Error: Watch on the latest version of YouTube.
![image](https://github.com/user-attachments/assets/2009e346-5cc1-42bc-87bc-3a29589ada1e)
![image](https://github.com/user-attachments/assets/d1aa132d-64b5-493d-bd78-f8e0f009db52)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@agirnob is the following setting enabled?

Player settings -> Proxy Videos Through Invidious

**Comment by agirnob** [comment]
I think that was the problem, I can open without youtube error now. Thank you for the pointer.

**Comment by agirnob** [comment]
Can confirm I start to having to same issue
Error: Failed to extract n-token decipher algorithm

**Comment by 4yman-0** [comment]
>Can confirm I start to having to same issue
Error: Failed to extract n-token decipher algorithm

see #5502 (please only upvote,, don't spam comments)

**Comment by senolfndk** [comment]
Same mistake
![Ekran görüntüsü 2024-08-01 123735](https://github.com/user-attachments/assets/1888cb11-c05e-4909-9190-23ec84d5c646)

**Comment by rlsbrowning** [comment]
Recently got this error message when launching FreeTube, different from above but maybe related? Haven't seen this until today. The application seems to be running normally at least:

Error: Could not extract JSON. Youtube API returned error 500 with message:<br>"Internal error encountered."

**Comment by Esch1234** [comment]
As of yesterday I started getting this issue again. I went in and turned off the "Fallback to non-preferred" switch, which removed one of the errors, but this error still appears and videos/live streams won't play: "Local API Error: Failed to extract n-token decipher algorithm"

**Comment by jfmherokiller** [comment]
I just ran into this error as well but i was able to fix it by deleting the currently used invidious instance. I still have the ntoken popup but the video plays correctly. 

 i was using "https://invidious.darkness.services" as my instance as a fix for a previous error where the videos would "Bounce" without playing. 

"Proxy Videos Through Invidious" is false through out all of this. 

I also have prefered api set to "local"

I finally have fallback to non prefered set to true.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
See https://github.com/FreeTubeApp/FreeTube/issues/5502#issuecomment-2261544217 for recommended settings

**Comment by Jiejue233** [comment]
a news from invidious API 
https://github.com/iv-org/invidious/issues/4734#issuecomment-2290075097

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Should be fixed
