### ISSUE TITLE
Loop video

### ISSUE THREAD

**Issue by GilgusMaximus** [FreeTubeApp/FreeTube#549]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Related to a missing feature from the old FreeTube.

**Describe the solution you'd like to see implemented**
Add a button to VideoJS which automatically replays the video. Needs to use this [flag](https://docs.videojs.com/docs/guides/options.html#loop) in VideoJS.

**Comment by mateusKoppe** [comment]
Need any help? I think I can work on this =]

**Comment by PrestonN** [comment]
Hey there!  Feel free to work on it.  We already have [this](https://github.com/phhu/videojs-abloop) module installed in the project so if you could please use this in your work.  I'll take a look at your PR once it's ready.  Thank you for the offer!

**Comment by PrestonN** [comment]
This has been implemented and will be included in the next release.

**Comment by leszekbar** [comment]
if it is implemented, when it will be released?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @leszekbar, you can find this functionality within the Cogwheel menu

<img width="1147" height="53" alt="Image" src="https://github.com/user-attachments/assets/13be911f-ca39-4a35-9da9-0e6cb50c1c4b" />

The one that says HD
