### ISSUE TITLE
add a VERSION file to repo to help with automating release downloads

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#550]
**Is your feature request related to a usage problem (not a bug)? Please describe.**

In lieu of a PPA for FreeTube, I would like to set up a script to download and install the latest version. 

**Describe the solution you'd like to see implemented**

I would like to see a VERSION text file added to the repo.  This file would contain just the version number of the latest release.

This would allow for the script to easily get the version number which can be used for downloading the most recent version.

**Describe alternatives you've considered**

none

**Comment by PrestonN** [comment]
You can use GitHub's API to get the version number. The API requires no authentication and no API key to use. This is how FreeTube checks for updates itself and should be sufficient for your needs.

[Example call](https://api.github.com/repos/freetubeapp/freetube/releases)
