### ISSUE TITLE
[Bug]: Invidious API Error: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by gokuthehedgehog56** [FreeTubeApp/FreeTube#5506]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. With Invidious set as API, select a video
2. Video will error, giving a syntax error

### Expected Behavior

Video plays as normal

### Issue Labels

API issue

### FreeTube Version

v0.21.2 beta

### Operating System Version

Windows 10 Home, version 22H2

### Installation Method

.exe

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by thingsiplay** [comment]
This depends on the Invidious instance and needs to be fixed there. I already found a working instance and currently watch videos with FreeTube using https://yt.artemislena.eu as the instance. So from FreeTube's side, this is working with Invidious API.

**Comment by Prazgreen1** [comment]
not planned? This is a freetube issue and not an invidious issue as invidious instances I have tested to work have this issue in freetube.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Prazgreen1 please refrain from commenting when you don't understand the inner workings of the application

**Comment by Prazgreen1** [comment]
Nvm about my previous comment. It was not reasonable. Anyways, I checked every invidious instance currently online that I could find, and all had this issue. I misread the above comment thinking it said that freetube was the issue rather than the invidious instance. I am mostly familiar with web frontend, however considering that using the invidious api with the public instances currently online, the option to embed videos from invidious could be a decent alternative patch
