### ISSUE TITLE
enable Github code scanning

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#551]
**Describe the solution you'd like to see implemented**

To help remove potential security bugs from FreeTube, it would be nice to see Github's Code scanning tool being enabled.

This tool is free for Public and OpenSource projects and from what I can see, FreeTube meets all requirements.

[Blog post about Security code scanning](https://github.blog/2020-09-30-code-scanning-is-now-available/)

[Steps to take to enable code scanning](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository)

**Comment by peepopoggers** [comment]
@PrestonN Do we want this?

**Comment by grrrrr** [comment]
While admittedly not critical it would be nice, finding potential security issues is always a _good thing_ ™ :)
