### ISSUE TITLE
[Feature Request]: Better behavior to resume playing at previous timestamp

### ISSUE THREAD

**Issue by scampsi** [FreeTubeApp/FreeTube#5512]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When the app is working normally it is safe to trust it to remember the playback position in [long] videos and to resume at the appropriate timestamp next time.

But when the app has intermittent issues with playing videos like we've seen recently it can forget the playback position:
- When trying to resume watching a video results in an error then a subsequent successful attempt to launch the video will restart playback from the beginning (particularly relevant for intermittent errors that can be resolved by retrying manually)

### Proposed Solution

The player doesn't forget the previous timestamp after encountering

### Alternatives Considered

The app could store the most recent playback timestamp for watched videos separately from the player.
It would not overwrite an existing stored position if the new one falls in the first X seconds of the video to give the user time to react when the player restarts the video from the beginning.
It would display the stored timestamp and, optionally, offer an way to jump to it.

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Edited your issue and removed parts that are related to https://github.com/FreeTubeApp/FreeTube/issues/2365 which will be fixed in our next minor release.

**Comment by OothecaPickle** [comment]
is this implemented by #5719?

**Comment by scampsi** [comment]
agreed. think this issue has been resolved. at least for the 403 error from watch session expired which is the only way I know to reproduce this manually
