### ISSUE TITLE
[Feature Request]: Option to hide/remove title bar on linux

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#5517]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Having the title bar visible on Linux (GNOME) can be problematic as it takes up valuable screen space and can interfere with the overall user experience. For users who prefer a more streamlined and efficient workspace, the title bar can be redundant and clutter the interface. 

### Proposed Solution

It would be beneficial to have an option to remove or hide the title bar to maximize screen real estate and improve usability. Additionally, moving the essential window controls (minimize, maximize, close) to the top bar would help maintain functionality.

### Alternatives Considered

I can't think any alternative solution.

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
f11

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Also duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1267
