### ISSUE TITLE
[Feature Request]: Send to JDownloader2 button

### ISSUE THREAD

**Issue by TheTimebreaker** [FreeTubeApp/FreeTube#5518]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I may be literally the only person who wants this so feel free to close this if nobody wants it:
A "Send to JDownloader" button that allows you to send videos, playlists and channels to your local installation of JDownloader2
(this program is a universal file downloader that works great with youtube, its been my go-to program for a literal decade, thats why i want a button for this, because that would be an incredibly easy way to download videos using a preconfigured program that behaves exactly like you have configured it)

### Proposed Solution

in my dev build, i have hacked together a concept for such a "Send to JDownloader" button, that uses the local server (`http://127.0.0.1:9666/flash/add`, see also [here](https://jdownloader.org/knowledge/wiki/glossary/cnl2) for the official docs)
(hacked together meaning it works but only because i have replaced the share button with it because i wanted to see if my idea would even work at all)
this has the benefit that it doesn't need a MyJdownloader account afaik and it doesnt need their servers to be online

### Alternatives Considered

If such a button is not deemed as being useful (which i could 100% understand lol), then ill keep my hacked together button and be happy with it.
If not, I would suggest that it can be toggled on/off in the settings because most people probably wont need it.
Then I would suggest placing that button next to the share button on all pages where it exists (so video, channel, playlist)
I'm pretty sure i would be able to get it to work (if it's actually a wanted feature), its really a small thing once you've figured out how jdownloader expects the urls

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sorry but this sounds like a too niche of an usecase. You could implement it yourself and run it in a custom build.
