### ISSUE TITLE
[Bug]: Application refuses to open after first time

### ISSUE THREAD

**Issue by MattyGWS** [FreeTubeApp/FreeTube#5519]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

On both the .rpm and flatpak, after installing and running the application first time, closing it then trying to open it again it just doesn't. :(

I'm on fedora, however my fedroa tablet application works while my fedora desktop doesn't. 

The fact that this is on both rpm and flatpak makes me think it's not an isolated issue.

### Expected Behavior

It should open.

### Issue Labels

causes crash, inconsistent behavior

### FreeTube Version

0.21.3 Beta

### Operating System Version

Fedora

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.21.3 Beta

### Additional Information

While I am using the latest of everything on both devices, both systems up to date, one works and the other doesn't. May be related to something about d-bus but I have no idea.

Both on wayland.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by juntawflo** [comment]
Hello,

I have encountered the same issue 
I'm using macOS Big Sur , Version 11.7.10

After updating and launching freetube to 0.21.3 Beta , the app doesn't launch (it just appears in the dock but  no window displayed).

Things I have tried : 

- Rebooting my computer 
- uninstalling and installing again 
- Using the previous beta (freetube-0.21.2-mac-x64 ) , but now it strangely behaves the same way

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@MattyGWS is this still an issue for you on v0.22.0?
