### ISSUE TITLE
[Bug]: No Option For 720p 30 FPS on a 60 FPS Video in Latest FreeTube Version

### ISSUE THREAD

**Issue by exefile2** [FreeTubeApp/FreeTube#5524]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

In the previous versions of FreeTube, there was an option to select 720p or 1080p videos at 30 FPS. However, in the latest version, this option is no longer available, and only 60 FPS options are present like 720p60 and 1080p60. My PC is unable to handle 60 FPS videos smoothly, so I rely on the 30 FPS option for better performance.
![Screenshot (247)](https://github.com/user-attachments/assets/b04a2635-e1d2-45f5-bebb-02e03b41ad62)

### Expected Behavior

There should be an option to select 720p or 1080p at 30 FPS, as was available in previous versions.

### Issue Labels

feature stopped working

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 10 pro

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

![Screenshot (249)](https://github.com/user-attachments/assets/ee7e97f6-072e-457e-80f8-587fd115a5bc)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
That is unfortunately a side-effect of what we had to do to get video playback to work again.

**Comment by exefile2** [comment]
> That is unfortunately a side-effect of what we had to do to get video playback to work again. Although even without the workarounds that we had to use, only 720p had a 30fps option, 1080p would still have been 60fps on that video.

But before, there were options for 720p and 1080p besides 720p60 and 1080p60. When will we get those options back???

**Comment by absidue** [comment]
That video never had a 1080p 30fps option on the local API, it's a fact but I know you won't believe me regardless of how many times I repeat it.

As for getting it back, I can make a custom build for you specifically if you want the removes the workaround the makes videos play 100% of the time and you can have the 720p 30fps stream on that video, you'll just have to accept that randomly with increasing frequency videos will fail to play, if you don't have the proper fix. So don't complain on this issue or any other one if videos don't play with that custom build, because you were warned.

**Comment by absidue** [comment]
So your choices are:
- All videos work until YouTube breaks them again
- Videos won't play at random and it's only going to get worse as time goes on, but you get the 720p 30fps stream on that video.

**Comment by exefile2** [comment]
> So your choices are:
> 
> * All videos work until YouTube breaks them again
> * Videos won't play at random and it's only going to get worse as time goes on, but you get the 720p 30fps stream on that video.

I don't know why you are not believing but I swear that there were these options in the previous versions and I also used that...
1080p60
1080p
720p60
720p
480p
360
240p
...
Here in my pc, the normal 720p and 1080p works fine and smooth but when I selected 720p60 or 1080p60, the experience got worse and now I can't see the 720p and 1080p options.

**Comment by absidue** [comment]
I don't believe you because what you are saying literally doesn't match up with that YouTube API response for the old system.

**Comment by exefile2** [comment]
> So your choices are:
> 
> * All videos work until YouTube breaks them again
> * Videos won't play at random and it's only going to get worse as time goes on, but you get the 720p 30fps stream on that video.

I appreciate your offer to create a custom build. Given that my low-end PC struggles with 720p 60fps videos, I’m interested in the custom build that allows for 720p 30fps streaming. I understand the potential for increased playback issues and am prepared for that. Please proceed with the custom build. Thanks for your help!

**Comment by exefile2** [comment]
> I don't believe you because what you are saying literally doesn't match up with that YouTube API response for the old system.
![IMG-20240804-WA0019](https://github.com/user-attachments/assets/ac99667f-4794-45ec-8a6b-054184137b64)
Soo what's this??? 720p and 720p60

**Comment by exefile2** [comment]
> > I don't believe you because what you are saying literally doesn't match up with that YouTube API response for the old system.
> > ![IMG-20240804-WA0019](https://private-user-images.githubusercontent.com/175214193/354917161-ac99667f-4794-45ec-8a6b-054184137b64.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTEyOTgsIm5iZiI6MTcyMjc5MDk5OCwicGF0aCI6Ii8xNzUyMTQxOTMvMzU0OTE3MTYxLWFjOTk2NjdmLTQ3OTQtNDVlYy04YTZiLTA1NDE4NDEzN2I2NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQxNzAzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTA0NWQzOTUyYjM3MjkwY2JjNjE1YTg0MzYyN2MxNzJkZTA5YTE3MDg0NzlmZDdiYjAyOThiNmM3NmVlNzM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.weXmoZBGSGybgvLdSSZsqiZGNbW0NLZ4Crcy3YMtglo)
> > Soo what's this??? 720p and 720p60

Here you can see, there is a option for 720p which means 30fps besides 720p60, my pc can handle 720p and this option is unavailable in the latest build, that's my point...

**Comment by absidue** [comment]
Your screenshot proves my point, that 1080p 30fps was never available for 60fps videos.

This one time I will create a custom build for you, but you have to promise that you WILL NOT open any GitHub issues about ANY problems you experience with that build, because YOU specifically asked for a broken build that WILL have problems.

**Comment by absidue** [comment]
As mentioned about DO NOT report any issues that you experience with this build, as this build is expected to have problems: https://github.com/absidue/FreeTube/actions/runs/10238507652

**Comment by exefile2** [comment]
> Your screenshot proves my point, that 1080p 30fps was never available for 60fps videos.
> 
> This one time I will create a custom build for you, but you have to promise that you WILL NOT open any GitHub issues about ANY problems you experience with that build, because YOU specifically asked for a broken build that WILL have problems.

But the 720p option is missing you can see. So, when will I get back the 720p option beside the 720p60? Will I even get back this option in any build or otherwise I have to shift into any other alternative. I use freetube just to block stupid YouTube ads and to have a smooth experience. But if the 720p option is gone permanently, I have to shift. That's my question. 

Will I get the 720p option in any future build or not...

**Comment by absidue** [comment]
Shifting to an alternative won't get you the 720p 30 fps option back, because just like FreeTube every other project is moving away from pretending to be the YouTube website because YouTube has added strict integrity checks, which cause videos to stop playing if you don't use their official website.

If you want someone to be unhappy with, be unhappy at YouTube, but please stop acting like it is our fault.

**Comment by exefile2** [comment]
> Shifting to an alternative won't get you the 720p 30 fps option back, because just like FreeTube every other project is moving away from pretending to be the YouTube website because YouTube has added strict integrity checks, which cause videos to stop playing if you don't use their official website.
> 
> If you want someone to be unhappy with, be unhappy at YouTube, but please stop acting like it is our fault.

You should have mentioned to me earlier that this is due to YouTube's own restrictions. Don't be so rude. I just asked if this issue will be fixed or not. I didn't act like it was your fault or anything like that. I think you misunderstood my question.

**Comment by absidue** [comment]
I think we both clearly have very different understandings of your behaviour in this thread. At least after the millionth time of me repeating the same thing, you've finally realised that it's YouTube fault, instead of just constantly arguing.
