### ISSUE TITLE
[Bug]: Comment reply count is possibly outdated, even after fetching replies

### ISSUE THREAD

**Issue by TheodorSmall** [FreeTubeApp/FreeTube#5532]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When loading comments, their respective number of replies is fetched. However, if new replies are submitted in the meantime, just before the user clicks "view n replies", this count may be outdated, and there may be more (in theory, I suppose also less) replies than earlier, when the main comment was fetched.

The suggested fix is to update the reply count after fetching comment replies.

### Expected Behavior

The correct reply count should be updated after fetching the replies.

### Issue Labels

text/string issue, visual bug

### FreeTube Version

v0.21.3 Beta (built from source at development/79ca2a)

### Operating System Version

Linux 6.6.36-1-lts #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

### Installation Method

.pacman

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

not known, probably none

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
FreeTube's behaviour matches YouTube's in this regard, it shows the count at the time that the comment was fetched, which yes can also be higher than the amount of replies that are actually shown, as YouTube' servers also count comments that are being held for review, so not returned in the response, in their replies count. So if anything this is a feature request, additionally if there is more than one page (each page contains 10 replies) of replies for a given comment you would have to click load more replies until you have fetched every available reply for that comment before we could update the count.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as this isnt a bug. I don't think that its worth filing a bug report because counting all the replies to see if they match the number when there are a large number of replies seems very unreasonable.

Also YT sometimes also shows that there are for example 11 replies but only shows 9 because the others are deleted and they themselves didn't update the number
