### ISSUE TITLE
[Bug]: Error: The uploader has not made this video available in your country 

### ISSUE THREAD

**Issue by Nickleaton** [FreeTubeApp/FreeTube#5537]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Accessing a video. 
2. Get the error message [Bug]: Error: The uploader has not made this video available in your country

### Expected Behavior

Not sure if there is a solution, but presumable it can be downloaded from a different country

### Issue Labels

content not loading

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

https://youtu.be/tYla6ISFx0o for the link

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
That isn't a bug, that error message is coming directly from YouTube, telling you that the video isn't available in your country. YouTube uses your IP address to determine your location, so there is nothing FreeTube can do about it. However you aren't completely out of luck, you can try changing your IP address to a different country by using a VPN or changing to the Invidious backend and using an Invidious instance from a country that the video isn't blocked in.
