### ISSUE TITLE
[Feature Request]: Automatically Open Playlist If Only One

### ISSUE THREAD

**Issue by deepspaceaxolotl** [FreeTubeApp/FreeTube#5539]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently, if there is only one playlist, it is still required to select it after going to the Playlists tab.

### Proposed Solution

If there is only one playlist, it would be nice for it to automatically open when clicking the Playlist tab, either as an option or as a default if that seems sensible. I prefer having a single watch later list, so reducing how many clicks it takes to get to it would be helpful (both nicer and a tiny accessibility improvement for me) and feel more streamlined.

### Alternatives Considered

#4594 is a potential alternative, though this would work in the meantime for those using only one playlist and be a nice quality of life feature even if #4594 gets implemented.

### Issue Labels

ease of use improvement, new optional setting

**Comment by absidue** [comment]
This would definitely have to be an opt-in option if it were to get added, as making an entire page and it's functionality inaccessible is not a good user experience. As you already mentioned #4594 would cover this use case without breaking the playlists page or requiring the addition of an extra option, so I'm inclined to close this feature request in favour of that one.

**Comment by deepspaceaxolotl** [comment]
That makes sense, hopefully that issue can get implemented without issue soon. Thank you for the quick response!
