### ISSUE TITLE
[Bug]: The "Published date" on FreeTube is different than the "Released date" on youtube.com

### ISSUE THREAD

**Issue by sebma** [FreeTubeApp/FreeTube#5542]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to https://www.youtube.com/watch?v=MUbBaVQBCuU
2. Compare the Published date (Jun 29, 2024) on FreeTube : 
<img width="909" alt="image" src="https://github.com/user-attachments/assets/47e15be4-d50a-4491-a20e-197fadc292a9">

with the Released date (19 Jun 2016) on youtube.com : 
<img width="832" alt="image" src="https://github.com/user-attachments/assets/5b8fbd13-6ed4-4eda-9773-71d1944f4199">

### Expected Behavior

I expect the dates to be the same.

### Issue Labels

text/string issue

### FreeTube Version

v0.21.3

### Operating System Version

macOS Monterey 12.7.5

### Installation Method

Homebrew (Unofficial)

### Primary API used

Local API

### Additional Information

Same pb with this nightly build : 
<img width="396" alt="image" src="https://github.com/user-attachments/assets/82e084e0-199f-4619-b9e4-ad320b77130a">

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
If you expand the video description on the YouTube website, you'll notice that it, shows the same published/upload date as FreeTube.

Maybe the uploader released that podcast o
episode on a different platform before they released it on YouTube?
