### ISSUE TITLE
Unpleasant view when viewing a banned channel

### ISSUE THREAD

**Issue by Svallinn** [FreeTubeApp/FreeTube#555]
**Behavior of the program**
If there's a terminated channel present in the subscriptions and it's navigated to, a broken-ish view appears

**Expected behavior**
Something better than a broken-ish view

**To Reproduce**
1. Navigate to terminated channel present in subscriptions

**Desktop:**
 - FreeTube version: 0.8

**Comment by GilgusMaximus** [comment]
Yes. Due to the time constraints on the release, this was not implemented yet.

**Comment by peepopoggers** [comment]
I would like to chip in. Youtube provides an error which could be used to make a nicer view for a banned channel.
The linux experiment was banned for a day and when I clicked on his video an error popped up with "4xx channel banned" or something along those lines. This means channel removal could be handled to a page which would say just the text "Channel banned [channel_id]".
