### ISSUE TITLE
Cannot 'Fetch more results' from certain channel

### ISSUE THREAD

**Issue by computeristic** [FreeTubeApp/FreeTube#556]
I get 'TypeError: Cannot read property '0' of undefined' whenever I try to fetch more results (to browse old videos) from one channel. Other channels work just fine. 

Steps to reproduce error:

1. Go to channel 'HDCYT'
2. Scroll to the bottom and press 'Fetch more results'

I am using FreeTube v.0.8.0 Beta on a MacBook Pro running MacOS Mojave 10.14.6.

**Comment by GilgusMaximus** [comment]
I can confirm this issue. Seems like there is a problem with the fetching module for some channels.
Some investigation is definitely required.

**Comment by PrestonN** [comment]
This has been fixed in dev.  There was an error with the module that we're using when it involved the last few videos that was returned by a channel.  I've made the change over in that module and updated the packages in FreeTube.
