### ISSUE TITLE
[Bug]: permanent loading when default video format is "audio format"

### ISSUE THREAD

**Issue by Jiejue233** [FreeTubeApp/FreeTube#5561]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [x] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

**I didn't encounter this bug for every video, but I can reproduce the bug once I encounters it** 
1. choose the "default video format" to "audio format"
2. play some video (for me, this bug happens more often when the video is a generated video, like this 
![image](https://github.com/user-attachments/assets/e93c787d-702e-4fba-9075-a62c3257d986))
3. the video is loading permanently
3.1. if now change the "default video format" to "dash format" then
3.2. a bug info `NotSupportedError: Failed to load because no supported source was found.` is popped but the video is playing

### Expected Behavior

the video is playing as it should be

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.21.3 beta

### Operating System Version

Windows 10 19045.4651

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

when the primary API is local API:
step 3.2 a bug info `NotSupportedError: Failed to load because no supported source was found.` is popped **and** the video is **also loading permanently**
Yes, I do have checked #5511 but I don't think they are a same bug

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by peterweissbier** [comment]
this just happened for me too latest version

**Comment by Jiejue233** [comment]
## Update: 
I have made several test, then I found that this is possibly caused by the VPN proxies and/or the provider. I grabbed and checked every outgoing request, and most requests to either invidious and youtube directly is returning 403 forbidden from a few specific regions. I'm not providing the exact region, but those proxies are mostly centered at Asia and a few in north America. 
## conclusion: 
this is happened because the VPN proxies is blocked by either invidious API or youtube 
![image](https://github.com/user-attachments/assets/2cafd3c2-8f44-4942-9059-4050a9d37931)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as we cant do anything about the geo restrictions
