### ISSUE TITLE
[Feature Request]:  Video Duration and open incognito web browser

### ISSUE THREAD

**Issue by svdemir** [FreeTubeApp/FreeTube#5566]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I want to see the duration of the videos.
I also want the option to open in incognito window in the right click menu.
I would be very happy if you add it in new versions.
Good work. 
Best regards.
![Capture](https://github.com/user-attachments/assets/54414bca-9645-415c-9ec1-1de9508fa705)

### Proposed Solution

![Capture](https://github.com/user-attachments/assets/9b7aa9a9-7441-475e-95db-e59270e6f417)

### Alternatives Considered

I want to see the duration of the videos.
I also want the option to open in incognito window in the right click menu.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not going to comment on the fact that you broke the rules for opening a request. Going to treat this as one: 

- `open incognito web browser `

We will not implement this implementing this is different for every OS and every browser
