### ISSUE TITLE
[Feature Request]: Show Comments by Default on Page Load

### ISSUE THREAD

**Issue by Yontemoon** [FreeTubeApp/FreeTube#5572]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I would like the option to have the choice to be able to automatically see comments every time on page load instead of having to click "Click to View Comments" every time. 

### Proposed Solution

Add an option in the general or distraction-free settings to toggle comments to be automatically visible on page load, eliminating the need to click "Click to View Comments" every time.

### Alternatives Considered

None 

### Issue Labels

ease of use improvement, new feature, new optional setting

**Comment by konradmb** [comment]
Why was this closed? I can't find this feature in settings.

**Comment by smahm006** [comment]
Yeah either I'm bind or this feature isn't working.

I can see there was a PR for it - https://github.com/FreeTubeApp/FreeTube/pull/3352/files#

So the setting definitely exists but why can't we see it?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
General settings -> Load next page by default

**Comment by smahm006** [comment]
Ok thank you @efb4f5ff-1298-471a-8973-3d47447115dc that does work
