### ISSUE TITLE
[Bug]: Video minimizes and maximizes in-window all the time

### ISSUE THREAD

**Issue by gituser823** [FreeTubeApp/FreeTube#5573]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open Freetube
2. click on a video you want to play
3. experience the bug

### Expected Behavior

the video should be played and the video in-window should not minimize and maximize all the time.

[Screencast_20240815_193016.webm](https://github.com/user-attachments/assets/d8e8f6e8-4fd0-4ded-b14e-f8fd23eca224)

[Screencast_20240815_192837.webm](https://github.com/user-attachments/assets/bbcc764b-1638-4d2b-aeab-1aa132f6cad0)

### Issue Labels

visual bug

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Linux fedora 6.10.4-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Aug 11 15:32:50 UTC 2024 x86_64 GNU/Linux

### Installation Method

Flathub

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Use a different Invidious instance or switch to the local API, the Invidious instance that you are currently using is failing to play the videos.

Going to close this as there are already existing issues covering the UI bug that happens when videos fail to play.

**Comment by gituser823** [comment]
I get this bug again after updating to the latest version.
