### ISSUE TITLE
[Feature Request] "Watched video" label more visible

### ISSUE THREAD

**Issue by ThatIsAPseudo** [FreeTubeApp/FreeTube#558]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
There's only a text on the thumbnail that labels the video as watched, that is not clearly visible (especially since every youtube video has text on its thumbnail). However, I don't want to completely hide watched video.

**Describe the solution you'd like to see implemented**
There should be a colored element (thumbnail border, video title text, ...) that clearly indicates that the video has already been watched.

**Describe alternatives you've considered**
Here is a user script that does that on the Youtube web version (uses a shortcut) : https://greasyfork.org/scripts/30261-mark-watched-youtube-videos/ *(this issue is linked to #557)*

**Screenshots**

Currently:
![Capture d’écran 2020-10-03 à 13 43 01](https://user-images.githubusercontent.com/17936055/94990737-a5c37380-057e-11eb-8f7b-f03227bc97f9.png)

Userscript:
![Capture d’écran 2020-10-03 à 13 03 13](https://user-images.githubusercontent.com/17936055/94990205-84f91f00-057a-11eb-9c01-398e3828c4b6.png)

Edit : added screnshot

**Comment by GilgusMaximus** [comment]
Yep. That is definitely a valid point. Whether changing the whole element will be colored differently, or just the thumbnail needs to be discussed. But it definitely is a very strong visual indicator.

**Comment by heartlessglasses** [comment]
I think having it be visibly darkened or lightened (depending on the theme?) is necessary, especially for some vision issues and as it's very easy to tell at a glance that it's blending in more with the background than the rest and is thus standing out _less_, rather than more.

**Comment by rahulpatel596** [comment]
I would like to work on it and give it a shot if it's still available for grab?
@GilgusMaximus

**Comment by cloudrac3r** [comment]
> I would like to work on it and give it a shot if it's still available for grab?

Sure - but I think this needs some thought and discussion about what the actual design would be before anyone jumps into coding.

Here's two possibilities that I shared in the Matrix chatroom:

Opacity = 0.3 on watched videos: https://matrix.cadence.moe/_matrix/media/r0/download/cadence.moe/yoLGudgclNCgcbiUGAzULSCG

Opacity = 0.3 and background = black on watched videos: https://matrix.cadence.moe/_matrix/media/r0/download/cadence.moe/UmuuOuwCrpKSsOZwzaiDDmbO

We could restore the opacity when the video is hovered to make it easier to read.

These are just ideas - I'm not perfectly happy with either of them and I'd like to see other options.

**Comment by GilgusMaximus** [comment]
The original way that you suggested it, is probably something that can be done with the custom CSS themes in a future update. There we could just allow you to change the color of it easily. A similar way @cloudrac3r proposed it, is more likely to be the FreeTube default

**Comment by saideepesh000** [comment]
@GilgusMaximus, can I work on this, I am new to vue and electron, I would try, and please help me if I struck.

**Comment by GilgusMaximus** [comment]
@saideepesh000 Hi, sure you can work on this. We are always open for new contributors 👍 
If you have any question beforehand, you can write them here. Once you got the first bits together, it would be great if you can create a draft pull request for any further discussions. This way it is easier for all people to find it and help where they can :)

I will assign you to this issue

And please, to prevent any confusion, implement it in the way @cloudrac3r explained it. The way of the original issue post will not be merged.

**Comment by cloudrac3r** [comment]
Oh - some time ago I started making code changes to implement the opacity + background concept as actual code. I can't remember how far I got. Maybe it works perfectly. Feel free to steal my work-in-progress code (CC-0): https://paste.sr.ht/~cadence/dce577e942a21235e1f21725f634996d0c43fc3b

**Comment by cloudrac3r** [comment]
oh, you can apply this with `curl https://paste.sr.ht/blob/0712eaca6f35a387a2f6a877df8f45439d823d5c | patch -p1` while in the repo.

**Comment by saideepesh000** [comment]
@cloudrac3r, Hey, thanks for your help, I'll definitely make sure to understand the code(not just copy and pasting) and code it down.

**Comment by GilgusMaximus** [comment]
I'm gonna close this issue now because this has been implemented and merges
