### ISSUE TITLE
[Bug]: audio not available for download

### ISSUE THREAD

**Issue by claudiu-balciza** [FreeTubeApp/FreeTube#5580]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

go to https://www.youtube.com/watch?v=thJgU9jkdU4
click on "download"
video download is available
audio download is NOT available

### Expected Behavior

both video and audio should be downloadable

### Issue Labels

feature stopped working

### FreeTube Version

v0.21.3 Beta

### Operating System Version

W10

### Installation Method

.zip

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

unknown

### Additional Information

I can download the video but not the audio track
https://www.youtube.com/watch?v=thJgU9jkdU4

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
YouTube only has one stream that contains both audio and video and it's a 360p stream (it's also in the downloads list), all the others contain only audio or only video. So if you want both you'll have to download of of each and then combine them with an external tool like ffmpeg.

**Comment by absidue** [comment]
That question is already answered in the first link I provided. TL;DR: no.

**Comment by absidue** [comment]
#4178

**Comment by hueldoeu** [comment]
> YouTube only has one stream that contains both audio and video and it's a 360p stream (it's also in the downloads list), all the others contain only audio or only video. So if you want both you'll have to download of of each and then combine them with an external tool like ffmpeg.
> 
> Links to various other issues discussing the same thing (please check for duplicates first next time before opening a ticket, as the template tells you do to):
> 
> * [[Feature Request]: More Download preference options  #5030 (comment)](https://github.com/FreeTubeApp/FreeTube/issues/5030#issuecomment-2080462240)
> * [720p mp4 video selection no longer available. #5333](https://github.com/FreeTubeApp/FreeTube/discussions/5333)

how does newpipe and pipepipe solve this problem?

**Comment by absidue** [comment]
@hueldoeu Please read https://github.com/FreeTubeApp/FreeTube/issues/5030#issuecomment-2080462240

**Comment by hueldoeu** [comment]
> [@hueldoeu](https://github.com/hueldoeu) Please read [#5030 (comment)](https://github.com/FreeTubeApp/FreeTube/issues/5030#issuecomment-2080462240)

i can't believe that newpipe uses ffmpeg on an android device slower than my toaster (but same heat). it's so fast on android it takes more time to search for the video on the device/microSD card.
