### ISSUE TITLE
[Feature Request]: Hide big Play button when paused

### ISSUE THREAD

**Issue by FragataIncognita** [FreeTubeApp/FreeTube#5587]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I watch online classes recordings, and I have to pause constantly to do and copy the exercises that are shown, but the big red play button in the middle is a little bit annoying and covers some parts of the content.

### Proposed Solution

Don't implement the button once that the position of the playhead, or the timestamp, is different than 00:00, just like piped or youtube.

### Alternatives Considered

Hide the button after a few seconds, but this is sub optimal compared to the other solution.

### Issue Labels

ease of use improvement, visual improvement

**Comment by absidue** [comment]
There is already a setting to hide it, turn off `Display Play Button In Video Player` in the `Player Settings`.

**Comment by LinuxOnTheDesktop** [comment]
I add: there are quite a few settings; the settings are not searchable; and 'Play button in video player' is not the most intuitive name for a big play/pause button that appears within (or atop) the video.

**Comment by kommunarr** [comment]
We have an open issue for that already (#4726), but please feel free to share your idea for an alternative label.
