### ISSUE TITLE
Italian translation typo: "indidious" instead of "invidious"

### ISSUE THREAD

**Issue by lucanomax** [FreeTubeApp/FreeTube#559]
**Behavior of the program**
Typo in italian translation under "preferred API backend". Already fixed in weblate.

**Expected behavior**
Indidious instead of invidious

**To Reproduce**
Pretty self explanatory: Set freetube in italian > Settings > Preferred API backend

**Screenshots**
![screenshot](https://i.imgur.com/v1y8U1e.png)
![screenshot2](https://i.imgur.com/AotkaDQ.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - FreeTube version: 0.8.0

**Additional context**
I'm not into coding, ~~that's why I didn't just add a PR~~. Just changed the word, wasn't that hard lol.

PR: https://github.com/FreeTubeApp/FreeTube/pull/560

**Comment by dennis1248** [comment]
Hey @lucanomax 

You can suggest a corrected translation here:
https://hosted.weblate.org/projects/free-tube/translations/

**Comment by lucanomax** [comment]
> 
> 
> Hey @lucanomax
> 
> You can suggest a corrected translation here:
> https://hosted.weblate.org/projects/free-tube/translations/

Already did, I linked a screenshot of weblate.

**Comment by lucanomax** [comment]
idk why it doesn't link to https://github.com/FreeTubeApp/FreeTube/pull/560
i'll close manually
