### ISSUE TITLE
[Feature Request]: Document and extend the freetube:// protocol

### ISSUE THREAD

**Issue by pakoito** [FreeTubeApp/FreeTube#5591]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I would like to build interactions with the Freetube app from the browser. For that I need to understand how the `freetube://` protocol works, and have some capabilities available such as "open request in a new window".

### Proposed Solution

Add a section in the documentation with the protocol and API parameters allowed, i.e. youtube searches become regular searches within the app, and youtube urls open the video directly. Extend those parameters.

### Alternatives Considered

I have read the code and there is no documentation available.

### Issue Labels

support for external software

### Additional Information

This is my use case: https://github.com/pakoito/freetube-forwarder/

**Comment by absidue** [comment]
The `freetube://` protocol takes full YouTube URLs, just append `freetube://` to the start of a YouTube URL and it will open that URL. So for searches just format the URL the same as YouTube does when you do a search.

**Comment by absidue** [comment]
> and have some capabilities available such as "open request in a new window".

Things like that should be in-app settings, not something that is handled via the URL scheme and is already requested here: #1501

**Comment by absidue** [comment]
As this feature request now only covers documenting the URL scheme, please open an issue on the docs repo for it.
