### ISSUE TITLE
[Bug]: Playlists stopped working

### ISSUE THREAD

**Issue by YonderGod** [FreeTubeApp/FreeTube#5596]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

All previous playlists are gone and cannot create a new one. It was working normally an hour ago. 
Same thing happens whether I'm clicking the + button on a video or on the Playlist tab.
The message "Playlist _____ has been created successfully" appears, but the playlist isn't listed and I can't add a video to it.

### Expected Behavior

Create playlist button should create a playlist. 
Return old playlists to the list if possible. 

### Issue Labels

feature stopped working

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 10 Pro V22H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information
I am not sure if this is related, but it seems to have started happening at the same time. When I close FreeTube and re-open it I get this error. I have to go to task manager and end the process before I can open FreeTube again.
![image](https://github.com/user-attachments/assets/7257a475-f43b-483c-9ee7-449ca1cc8a7b)

Screenshots: 
![image](https://github.com/user-attachments/assets/41488849-4040-4f11-853b-c167441c61d7)
![image](https://github.com/user-attachments/assets/14040e8f-6a54-449f-b85e-e46730c4576e)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by YonderGod** [comment]
My issue is sort-of resolved but I'll just leave this info here in case the devs want to troubleshoot it.
I reinstalled windows for an unrelated reason, and then installed FreeTube and playlists were working correctly. So I guess it was some sort of glitch with my installation. 
I wanted at least my subscriptions back so I copied over the whole FreeTube folder in appdata. The original issue came back like I suspected would happen. So I exported my subscriptions, history, and playlists, then went back to the known-working appdata folder, and then imported them. My old playlists "Favorites" and "Watch later" were back (except they are empty) plus I got ONE of the playlists called "test" that I was trying to create when I was having the issue.
So in the end, it's not a big deal to me but if you guys want the appdata folder or more info to try to figure out what caused it, let me know.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @YonderGod would it be possible for you to provide the files?

**Comment by YonderGod** [comment]
> Hi @YonderGod would it be possible for you to provide the files?

I can, but I'm not sure if there's any personal info other than subscriptions and watch history? You want me to upload the whole \AppData\Roaming\FreeTube folder?

**Comment by CodingMadness** [comment]
> > Hi @YonderGod would it be possible for you to provide the files?
> 
> I can, but I'm not sure if there's any personal info other than subscriptions and watch history? You want me to upload the whole \AppData\Roaming\FreeTube folder?

any news on this?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The .db files are enough.

**Comment by YonderGod** [comment]
> The .db files are enough.
Ok, I'm not sure if they will be enough since I was able to export and then import on my new install, but you can check it.
[db.zip](https://github.com/user-attachments/files/17037004/db.zip)

**Comment by Valnir17** [comment]
Reporting the same issue on Linux mint.

**Comment by Valnir17** [comment]
[playlists.db.zip](https://github.com/user-attachments/files/17066197/playlists.db.zip)

My playlists.db for if it can help

**Comment by Valnir17** [comment]
Any news?

**Comment by YonderGod** [comment]
> Any news?

If you just want it to work for now; export your info, uninstall Freetube, delete the appdata folder (or move it if you want to keep it to help with troubleshooting), reinstall.

**Comment by Valnir17** [comment]
Thanks!

**Comment by CodingMadness** [comment]
> > Any news?
> 
> If you just want it to work for now; export your info, uninstall Freetube, delete the appdata folder (or move it if you want to keep it to help with troubleshooting), reinstall.


ngl this must be a priority to fix cause its a basic feature. If you already support this type of app, this must have priority,

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @YonderGod and @Valnir17, I have attempted to uncorrupt your files:

- [Valnir17_playlists.zip](https://github.com/user-attachments/files/17170972/Valnir17_playlists.zip)
- [YonderGod_playlists.zip](https://github.com/user-attachments/files/17170973/YonderGod_playlists.zip)

Corruption of your databases can happen when FT didnt have enough time to write the data to the databases for example when you shutdown your machine but FT is still running. I recommend to always close FT properly to prevent data loss.

More on this topic in https://github.com/FreeTubeApp/FreeTube/issues/4762
