### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON 

### ISSUE THREAD

**Issue by hix1000** [FreeTubeApp/FreeTube#5598]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Error with JSON

### Expected Behavior

Player doesn't crash

### Issue Labels

causes crash, text/string issue

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
The Invidious instance you chose returned HTML instead of JSON, please make sure to use an Invidious instance that actually works.

**Comment by hix1000** [comment]
oh, didn't know invidious were third-parties lol

**Comment by Sasinyork** [comment]
> The Invidious instance you chose returned HTML instead of JSON, please make sure to use an Invidious instance that actually works, considering this is your second issue in less than an hour about broken Invidious instances.

hi. i am encountering the same error. what does that mean? what should i do?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Use the Local API and disable fallback in the General settings
