### ISSUE TITLE
[Bug]: Combined video + audio downloads only allow the lowest quality

### ISSUE THREAD

**Issue by Anonymous941** [FreeTubeApp/FreeTube#5603]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to a video
2. Press download
3. While audio only and video only have high quality options, the combined audio + video just has the lowest quality option

### Expected Behavior

I can download the same quality together that I can individually

### Issue Labels

feature stopped working, inconsistent behavior, usability issue

### FreeTube Version

v0.21.3 beta

### Operating System Version

Ubuntu 24.04

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Please check existing issues and discussions before opening issues: https://github.com/FreeTubeApp/FreeTube/issues/5580#issuecomment-2295122910
