### ISSUE TITLE
Import Subscriptions from Invidioius instances

### ISSUE THREAD

**Issue by WandeingLagomorph793** [FreeTubeApp/FreeTube#561]
I noticed the import subscriptions options but those did not seem to work when trying to import a subscription opml from Invidious, either the old invidio.us instance or some of the community instances like snopyta or yewtu.be. With an error code upon trying to import from any of those everytime

Error: Request failed with status code 429

Either that error code pops up or it shows the instance links and doesn't recognize it, one request was the ability to import from Invidious instances like Snopyta, I used all three of it's options to no effect, even it's native "Import to OPML for Freetube and Newpipe" option

**Comment by PrestonN** [comment]
Invidious instances have support for exporting into a FreeTube format.  You'll have the best luck importing that.  Any other import and you're forced to make a lot of requests to YouTube to get some information and you'll end up blocked.  That's what the 429 error is.  This isn't an issue on our end.
