### ISSUE TITLE
Importation from freetube db displaying the channels 3 times

### ISSUE THREAD

**Issue by Bira-oliverio** [FreeTubeApp/FreeTube#562]
![freetube_3_times](https://user-images.githubusercontent.com/25584338/94997416-49ae1e80-0581-11eb-9c0a-c29276048e3e.png)
I exported the subscriptions from the previous freetube version, when I load to 0.8.0 the same channels appear 3 times in the left bar.

**Comment by durbarak** [comment]
Using the conversion tool linked in the blogpost yields the same result . However I noticed that not all channels are affected. I believe that only channels that were imported previously - in my case from youtube - display this error. Channels I added after I started using freetube and subscribed to directly don't exhibit this multiplication.

This is a sample entry from my 0.7 subscription export:
`{"channelId":"UCjTfChr0yyz4iZq0x12Q6xA","channelName":"Weitz / HAW Hamburg","channelThumbnail":"https://yt3.ggpht.com/a/AATXAJy2c2rTSeOTiKoKQToWeaaFniQ-Fj0DEwsCWg=s100-c-k-c0xffffffff-no-rj-mo","profile":[{"value":"All Channels"},{"value":"All Channels"},{"value":"All Channels"}],"_id":"0ZPNlgU8f8VskeCF"}`

As you can see the entry "All Channels" appears 3 times.

Manually removing the duplicate entries and then importing the file in freetube 0.8 fixes the problem and channels will be correctly imported only once.

**Comment by Bira-oliverio** [comment]
> Using the conversion tool linked in the blogpost yields the same result . However I noticed that not all channels are affected. I believe that only channels that were imported previously - in my case from youtube - display this error. Channels I added after I started using freetube and subscribed to directly don't exhibit this multiplication.
> 
> This is a sample entry from my 0.7 subscription export:
> `{"channelId":"UCjTfChr0yyz4iZq0x12Q6xA","channelName":"Weitz / HAW Hamburg","channelThumbnail":"https://yt3.ggpht.com/a/AATXAJy2c2rTSeOTiKoKQToWeaaFniQ-Fj0DEwsCWg=s100-c-k-c0xffffffff-no-rj-mo","profile":[{"value":"All Channels"},{"value":"All Channels"},{"value":"All Channels"}],"_id":"0ZPNlgU8f8VskeCF"}`
> 
> As you can see the entry "All Channels" appears 3 times.
> 
> Manually removing the duplicate entries and then importing the file in freetube 0.8 fixes the problem and channels will be correctly imported only once.

Manually changing the db file worked. Thanks.

**Comment by GilgusMaximus** [comment]
Okay that is interesting. For most people the default import worked. (Including me)
And my script was just a simple way to convert them before the feature was implemented and worked as well.

It is likely that the .db file from old FreeTube had a flaw or some other kind of expected behavior (I wasn't here before the rewrite) leading to the problem at converting the file.

**Comment by durbarak** [comment]
> It is likely that the .db file from old FreeTube had a flaw

Exactly! The import is working (but doesn't check for duplicates). The excerpt I posted is from the "old" freetube. 

As far as I can tell only channels which I imported previously from my youtube subs are affected. Channels I subbed to within freetube aren't.

**Comment by PrestonN** [comment]
Just as some extra info to give in the mean time while we work on fixing this issue, I can confirm that unsubscribing and resubscribing to the affected channels will remove the duplicates.  We'll try to have a fix out in the next couple of days or so.
