### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of null (reading 'reason')

### ISSUE THREAD

**Issue by marifolwra** [FreeTubeApp/FreeTube#5623]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click on any video
2. Video does not play and instead error message "TypeError: Cannot read properties of null (reading 'reason')"

### Expected Behavior

Video will play

### Issue Labels

content not loading

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by marifolwra** [comment]
Upon further investigation, this error only seems to appear when on VPN (specifically the Atlanta server in ExpressVPN). Without a VPN, freetube works as intended...I'm not sure what would cause this, but this bug is fixed by just choosing a different server.

**Comment by XboxD00d** [comment]
Click on any video
    Video does not play and instead error message "TypeError: Cannot read properties of null (reading 'reason')"

Expected Behavior
Video will play

Issue Labels
content not loading

FreeTube Version
v0.21.3 Beta

Operating System Version
Linux Fedora 40 KDE

Installation Method
Flathub Discover

Primary API used
Local API
