### ISSUE TITLE
Local API - Error: Request failed with status code 429

### ISSUE THREAD

**Issue by Bira-oliverio** [FreeTubeApp/FreeTube#563]
When downloading any channel or subscribed content the message appears.

**Comment by Bira-oliverio** [comment]
Screenshot.

![Freetube_error_429](https://user-images.githubusercontent.com/25584338/94997384-21bebb00-0581-11eb-92db-0a5779ab537a.png)

The same error happens when trying to load any video.

**Comment by ducky710** [comment]
Seconding this, I'm also experiencing the same issue. As a first time user of Freetube..

**Comment by PrestonN** [comment]
Hey everyone, please read this [blog post](https://write.as/freetube/experiencing-429-errors-please-read-for-info) that was sent out to better understand what these errors are along with our plans for solutions.

I'll keep this issue up until it's fixed, but know that we're looking into solutions and there are already a few things that can be done to prevent this.

**Comment by ducky710** [comment]
Thanks for the update. I had just imported 600+ subscriptions so that's definitely the reason, certainly makes sense lol.

**Comment by Bira-oliverio** [comment]
Fetching the feed via RSS worked.

Thanks.

**Comment by drod3763** [comment]
I can't even import my subscriptions due to the 429 error
