### ISSUE TITLE
[Feature Request]: search filter out shorts (search filter for all durations other than short)

### ISSUE THREAD

**Issue by asagdotzler** [FreeTubeApp/FreeTube#5630]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Some of us never want to see shorts, ever, anywhere, for any reason. Right now, to see all long-form content I must perform two search filters, once for medium length content and one for long length content.

### Proposed Solution

 It would be much nicer if I could do one search filter to eliminate the awful shorts.

### Alternatives Considered

A checkbox somewhere in the settings for "never let YouTube Shorts show up in any of my FreeTube searches, ever, for any reason.

### Issue Labels

improvement to existing feature

### Additional Information

Open to other solutions for eliminating shorts from wasting my time in FreeTube. I mostly use search results so that's where I'm focused but I'm happy with any solution to this terrible problem.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is unfortunately not possible, see https://github.com/FreeTubeApp/FreeTube/issues/3976#issuecomment-1704226232

**Comment by asagdotzler** [comment]
You have 4 radios for duration, make them check boxes and you've fixed my isue? Why can't you do that? It's fully within your power given what's in the app today. Just let me exclude "less than 4 minute" by checking each item that's more than 4 minutes.
