### ISSUE TITLE
[Feature Request]: Toggles for DeArrow to only apply to selected feeds

### ISSUE THREAD

**Issue by Cat333Pokemon** [FreeTubeApp/FreeTube#5632]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

**DeArrow** is really useful to reduce clickbait, but I don't use it because several of my subscriptions lose their consistent titles and thumbnail format.

### Proposed Solution

I'd like to suggest adding a few toggles for DeArrow to apply to:

- [ ] Subscriptions – _Toggling this option would enable/disable for all profiles_
  - [ ] Profile 1
  - [ ] Profile 2
  - [ ] ...
- [ ] Trending
- [ ] Popular
- [ ] Search Results
- [ ] Recommended Videos

For these next two, it would use the same UI element as the “Hide Videos From Channels” in the *Distraction Free Settings*.

- Always use DeArrow on these channels: ________
- Never use DeArrow on these channels: ________

### Alternatives Considered

Issue #5549 describes a similar issue with SponsorBlock, but this affects a different part of the interface.

Perhaps, it might also be possible to add a “DeArrow this video” option to the triple-dots menu for any video.

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
DeArrow will always be applied app wide just like how it works with the extension but i do agree that settings like this should be bound to a profile. That is already covered in https://github.com/FreeTubeApp/FreeTube/issues/1996. I will close this as we wont add support for such granular support
