### ISSUE TITLE
[Bug]: Error when trying to Fetch more results Local API Error TypeError: Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by liammcsh2008** [FreeTubeApp/FreeTube#5638]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to Community Tab
2. Click fetch more results
3. the first few results show up
4. An error pops up

### Expected Behavior

The community tab should show the results loading posts normally

### Issue Labels

content not loading

### FreeTube Version

v0.14.0

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

Community tab results dont show up resulting in and error

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
What channel does this happen on?

**Comment by RetroJimmyX** [comment]
On 0.21.3 Beta, I am getting the following errors on every video I open (posted here as one error is the same).

`TypeError: Cannot read properties of null (reading 'reason')`
`NotSupportedError: Failed to load because no supported source was found.`

**Comment by absidue** [comment]
@RetroJimmyX That's a different issues, see: https://github.com/FreeTubeApp/FreeTube/issues/5534
