### ISSUE TITLE
Does the flatpak build is expected to be updated ?

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [FreeTubeApp/FreeTube#564]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify: Distribution of the releases.

**Question**
Please write down your question.
I´ve noticed that the long awaited 0.8.0 beta, haven´t had any flatpak release, nor update on the flathub repo. It is still stuck on 0.7.3 https://flathub.org/apps/details/io.freetubeapp.FreeTube
As Freetube isn´t available in the Solus repositories yet, nor does it have compiled packages for it, my main choice is to use the flatpak version.
Has it been forgotten, staled, or in hold ?
*And yeah, I still could use the snap, AppImage or compiled binaries obviously, while still possibly be able to compile it myself*.

**Comment by GilgusMaximus** [comment]
Hi. Currently we are not maintaining the Flatpak build ourselves. So you would have to write the person in charge of that. 
However moving forward, we want to maintain it ourselves. It is an open issue, which neither PrestoN nor me worked on yet. Additionally I do not work on Linux by default, so I am probably not going to do that. 

But it might take a while to get this done.

**Comment by PoorPocketsMcNewHold** [comment]
Thanks for the answer! I’ll wait a bit myself then.
