### ISSUE TITLE
[Bug]: Linux AppImage Built with FUSE v2: Only FUSE v3 Included with Newer Distros

### ISSUE THREAD

**Issue by the-burrito-triangle** [FreeTubeApp/FreeTube#5641]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1)  Download FreeTube AppImage on Fedora 41 or CachyOS (Gnome DE) from github.
2)  Right click AppImage and set Executable as Program to enabled.
3)  Open a terminal in the directory containing FreeTube AppImage (or cd to directory).
4)  Run FreeTube: 
$ ./freetube_0.21.3_amd64.AppImage
FreeTube returns an error about FUSE not being present:
"Cannot mount AppImage, please check your FUSE setup."

On Fedora 41:
$ rpm -qa | grep fuse
fuse3
fuse3-libs
fuse-common

Old FUSE v2 is not installed on Fedora 41 by default (or CachyOS, an Arch Linux based distro).

After installing appropriate FUSE v2 packages FreeTube opens and runs normally:
$ sudo dnf install fuse fuse-libs

NOTE: FUSE v3 is included with at least Fedora 39. I'm not sure what distros only ship FUSE v2 packages, but switching to FUSE v3 should not be an issue from what I can tell as Flatpak and distro maintained FreeTube packages should not be affected by this change. The AppImage should be okay to update unless there was a technical reason for using FUSE v2 over v3.

### Expected Behavior

AppImage should run on newer distros.

### Issue Labels

usability issue

### FreeTube Version

freetube_0.21.3_amd64.AppImage

### Operating System Version

Fedora 41, CachyOS

### Installation Method

.AppImage

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Considering that official AppImage docs instruct you to install fuse2 if your system only has fuse3 installed by default, I'm guessing that AppImage doesn't support fuse3.

https://docs.appimage.org/user-guide/troubleshooting/fuse.html?highlight=fuse

**Comment by the-burrito-triangle** [comment]
Thanks absidue! I had no idea AppImage was suck on FUSE 2; and with newer distros dropping FUSE 2 from the default installed packages, the only logical move is just to inform people they'll need to manually install those dependencies for their distro.

If you need someone to help with documenting the required FUSE packages on Arch or Fedora for the FreeTube AppImage, let me know. (Should I submit a pull request for this?)
