### ISSUE TITLE
[Bug]: Remove the big play button when paused, from the shakha player

### ISSUE THREAD

**Issue by Janaue** [FreeTubeApp/FreeTube#5645]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I have freetube-0.21.3-nightly-4714-win-x64-portable.7z  on windows and with the change of the player, there's now the big play button which hides the content of the video.
![Finder Time Switches - Programming Weekday On_Off Times for a DGT Timer - FreeTu_2024-09-04 14_29_11](https://github.com/user-attachments/assets/e0a8af55-bcd1-4636-9b00-06f9f83952ed)

edit: actually even when the video is playing there's the big fat circle printed on the video, so as soon as i move my cursor and it hovers the video, the fat circle shows up and blocks the view.

### Expected Behavior

keep the video visible like with the previous player.

### Issue Labels

visual bug

### FreeTube Version

freetube-0.21.3-nightly-4714-win-x64-portable

### Operating System Version

w10

### Installation Method

.zip

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by khaleel2788** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Player settings -> Display Play Button In Video Player
