### ISSUE TITLE
[Feature Request]: Reduce padding on video controls bar

### ISSUE THREAD

**Issue by jspast** [FreeTubeApp/FreeTube#5647]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

With shaka-player introduced in #4978, there is excessive padding on the video controls bar, both on the bottom and sides. This can be shown in a comparison with the reference YouTube's official interface, and is especially noticeable when in full screen. Even with bigger fonts and icons, YouTube controls take less space on screen.

FreeTube
![FreeTube](https://github.com/user-attachments/assets/0f4c4c92-df2f-4f0c-bffd-24aa66e1883d)

YouTube
![YouTube](https://github.com/user-attachments/assets/343ac5ae-d51d-42a0-a95d-126379112859)

### Full screen:

FreeTube 
![FreeTube full screen](https://github.com/user-attachments/assets/cb0b875c-bc03-4910-ab19-f633c8d14d14)

YouTube
![YouTube full screen](https://github.com/user-attachments/assets/175ab59a-dc7e-4232-bdf7-3ac9ef0bde0a)

### Proposed Solution

Reduce the padding so that the controls take less of the screen.

### Alternatives Considered

Maybe this is intended, but it honestly doesn't look right. Also, the padding on previous FreeTube versions with video.js was closer to YouTube's.

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Wont implement as this layout is more accessible for all our users compared to the previous one. Keep in mind that FT is not only used on Desktop but also on TV's and phones
