### ISSUE TITLE
[Feature Request]: Ability to leave comments

### ISSUE THREAD

**Issue by mooleshacat** [FreeTubeApp/FreeTube#5651]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I can already block ads with Brave browser, but the reason I downloaded this app was two fold:
- To allow me to create sub list without a YT account
- To hopefully be allowed to speak once again

The problem is currently the app does not allow you to comment. I think it would be neat if we were allowed to comment, even if it only shows to users of this app.

At least then, we wouldn't be censored.

### Proposed Solution

Allow comments, that can be merged together with YT comments and put this app's comments at the top
Allow thumbs up/down for comments left by YT Lusers and users of this app (maybe forward data to returnyoutubedislike creators)

### Alternatives Considered

None, YT won't let me speak

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
FreeTube allows the users to have the same experience as YT logged out state but privately. This wont be implemented as this would bring along privacy implications and a maintenance burden on the team
