### ISSUE TITLE
[Bug]: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials

### ISSUE THREAD

**Issue by sallyFoster** [FreeTubeApp/FreeTube#5653]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Every time that I try to load a video from my URL with credentials it doesn't load the video and displays that error instead

![Screenshot 2024-09-05 at 11 55 13 AM](https://github.com/user-attachments/assets/980a42bd-590e-4a71-8152-9fe4946f985f)

### Expected Behavior

It should just load the video

### Issue Labels

content not loading

### FreeTube Version

0.21.3 (0.21.3)

### Operating System Version

MacOS 14.6.1 (23G93)

### Installation Method

.dmg

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by sallyFoster** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc  But, I am using the latest version, shouldn't that already be fixed on it?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
nope this fix will be included in the next release.
