### ISSUE TITLE
[Feature Request]: On the new player, make the playback rate directly visible like on the old player and make it change the rate when clicked

### ISSUE THREAD

**Issue by Janaue** [FreeTubeApp/FreeTube#5657]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

On the old player the playback rate was directly visible but on the new player this information is hidden behind a useless icon, so now I don't know which speed is used.
There's no reason to hide this information and now clicking on the icon doesn't change the rate to the next upward step.

### Proposed Solution

going back to the old system of display the rate and when clicked the speed increases by +1 step

### Alternatives Considered

NA

### Issue Labels

display more information to user

**Comment by absidue** [comment]
> when clicked the speed increases by +1 step

This is definitely not coming back, it made it impossible to use on mobile and also only being able to open the menu when you hovered and not with a click was bad for accessibility.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> On the old player the playback rate was directly visible but on the new player this information is hidden behind a useless icon, so now I don't know which speed is used.

Its not hidden, just hover on the icon. Users dont need to know what speed they are using all the time. They set a default speed and they know what it is. YT does the same thing.

**Comment by Zer0Tester** [comment]
How hard would it be to let users decide what's useful for them? For instance, by adding a setting to choose between Youtube interface and custom interface?

**Comment by absidue** [comment]
@Zer0Tester If you want a custom interface you are welcome to fork FreeTube and maintain your own version of FreeTube with the customisations that you want.

**Comment by Zer0Tester** [comment]
By 'custom' interface, I meant 'original Freetube' interface, i.e. the one from v0.21.3 Beta. I don't have the skills required to build my own.

**Comment by absidue** [comment]
If you want that back then you need to downgrade to 0.21.3.
