### ISSUE TITLE
[Bug]: Playbar and video title never go away in fullscreen with flatpak version of FreeTube when cursor leaves screen.

### ISSUE THREAD

**Issue by Zhaze** [FreeTubeApp/FreeTube#5659]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When playing videos in full screen, the playbar and the video title will eventually disappear, but only if the cursor stays on that screen.  I have dual monitors and when I put a video on the seconday monitor and then move the cursor to the primary screen to do other things the title and the playbar never leave the video.

### Expected Behavior

I expect the playbar and the title to disappear whenever my mouse isn't actively on the video.

### Issue Labels

inconsistent behavior

### FreeTube Version

0.21.3 Beta

### Operating System Version

Fedora Linux 40

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

![Screenshot_20240906_231743](https://github.com/user-attachments/assets/02d4e7bd-6cf9-41bc-9287-0bba02e1fc1f)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Zhaze is this still an issue for you in v0.22.0
