### ISSUE TITLE
Missing contribution guidelines link

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [FreeTubeApp/FreeTube#566]
**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [ ] Other. Please specify:

**Question**
I’ve noticed that the contribution guidelines linked in the README.md were removed (The CONTRIBUTION.md). Was it moved somewhere else, or should this be removed from the README.md ?

**Comment by GilgusMaximus** [comment]
We have to include it again. Also we have to discuss how we want to handle contributions going forward.
So after the new release 0.9 (should come in a few days at latest), PrestoN and I will probably discuss this and setup a new contribution file
