### ISSUE TITLE
[Bug]: Video plays fine on invidious website, but using same instance on Freetube fails to load.

### ISSUE THREAD

**Issue by hix1000** [FreeTubeApp/FreeTube#5667]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

The video I watched failed to load (play request error), however if I loaded the video on the invidious instance i was using inv.nadeko.net in my browser, _without_ using Freetube, it loads just fine.

### Expected Behavior

Loads just fine on Freetube.

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Invidious API

### Additional Information

weird bug

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by hix1000** [comment]
specifically using inv.nakedo.net

**Comment by absidue** [comment]
Please provide a lot more detail when reporting bugs, we cannot read your mind. Unfortunately without more information we cannot help you, please provide screenshots or of what is happening, ideally also take a look at the devtools and see what is going on there and what video it happened with.

**Comment by figuld** [comment]
@absidue @efb4f5ff-1298-471a-8973-3d47447115dc
Specifically on inv.nadeko.net, (other invidious instances also don't work but have different errors), I can't open a channel page, play a video, and refresh without RSS. Thumbnail from playlists load fine, refresh using RSS works but prints errors.
From the errors, it looks like the instance author disabled the API.

On inv.nadeko.net site (I use inv7.nadeko.net - german server), videos play, but there's non-interactive `go-away` captcha, on channel pages there is no captcha.

On a channel page in console I get these errors:
`renderer.js:2  GET https://inv7.nadeko.net/api/v1/channels/UCSpzAXtHPzo3_vW1VbYi2eg? 403 (Forbidden)`
`renderer.js:2 Invidious API error http://inv7.nadeko.net/api/v1/channels/UCSpzAXtHPzo3_vW1VbYi2eg? SyntaxError: Unexpected token 'E', "Endpoint disabled" is not valid JSON`

On a video page:
`renderer.js:2  GET https://inv7.nadeko.net/api/v1/videos/flXs_joCP9c? 403 (Forbidden)`
`renderer.js:2 Invidious API error http://inv7.nadeko.net/api/v1/videos/flXs_joCP9c? SyntaxError: Unexpected token 'E', "Endpoint disabled" is not valid JSON`
`renderer.js:2 MediaImage src can only be of http/https/data/blob scheme: app://bundle/index.html`
```
renderer.js:2 Player Error (category and code explainations here: https://shaka-player-demo.appspot.com/docs/ ↳ api/shaka.util.Error.html)
Video ID: "flXs_joCP9c"                                                                              
FreeTube player context: "loading dash/audio manifest and setting default quality in mounted"
                                                                                                     
Severity: CRITICAL (2)                                                                               
Category: NETWORK (1)                                                                                
Code: UNSUPPORTED_SCHEME (1000)                                                                      
Stack trace:                                                                                         
Error: Shaka Error 1000                                                                              
    at new te (app://bundle/renderer.js:2:9734)                                                      
    at ba (app://bundle/renderer.js:2:77781)                                                         
    at wa.request (app://bundle/renderer.js:2:80047)                                                 
    at Ky (app://bundle/renderer.js:2:460844)                                                        
    at Gy (app://bundle/renderer.js:2:458556)                                                        
    at cv.start (app://bundle/renderer.js:2:485643)                                                  
    at app://bundle/renderer.js:2:213235                                                             
    at app://bundle/renderer.js:2:214295                                                             
```
`renderer.js:2 Unable to play DASH formats. Reverting to legacy formats...`

On RSS refresh this error 5 times:
`renderer.js:2  GET https://inv7.nadeko.net/feed/playlist/UULFzD6YFm2wGo8qQ-2Enx46hQ 503 (Service Unavailable)`

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please do not ping us. Instance has disabled their API nothing we can do about that https://api.invidious.io/
