### ISSUE TITLE
[Feature Request]: Configurable pause/play icon size and transparency

### ISSUE THREAD

**Issue by geominorai** [FreeTubeApp/FreeTube#5688]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Following the migration to shaka-player in nightly, the pause/play icon that appears in the middle of the video player is jarringly gigantic compared to previously, which is unfortunately quite distracting when starting and pausing a video as well when moving the mouse over it (which causes it to reappear).  This is especially glaring when using a dark theme.

This also makes it almost impossible to pause a video to read text on screen (or examine anything behind the icon for that matter).

### Proposed Solution

Add settings to resize the icon and adjust the transparency of the icon and its background circle.

### Alternatives Considered

It would also be nice to have the option to disable showing the icon entirely (the playback bar already has the play/pause icon).  This may be the quickest workaround if implementing icon resizing/transparency is difficult.  Setting 100% icon and background transparency would indirectly also implement this.

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We will not provide a setting the resizes this. You can disable the pause button in the player settings.

**Comment by geominorai** [comment]
Oh, I missed that setting.  Thanks!
