### ISSUE TITLE
Package conflict with other software

### ISSUE THREAD

**Issue by sith-on-mars** [FreeTubeApp/FreeTube#569]
First, congratulations on the rewrite release!

I was trying to use the Freetube 0.8 on Fedora 32.

I have [Zettlr](https://github.com/Zettlr/Zettlr), a markdown editor using electron, installed on my device. This caused me unable to install Freetube on my system. I got this error output in my terminal:

`Error: Transaction test error:`
  `file /usr/lib/.build-id/1b/46d89702261ec7350b37d9c294e9cf30056cec from install of freetube-0.8.0-1.x86_64 conflicts with file from package zettlr-1.7.5-1.x86_64`
  `file /usr/lib/.build-id/3a/c7cba3b980738c950b4f65063d26a2bdea49cd from install of freetube-0.8.0-1.x86_64 conflicts with file from package zettlr-1.7.5-1.x86_64`
  `file /usr/lib/.build-id/46/08cfee8a6c5916de40a1eb9aa8584a12ae65e0 from install of freetube-0.8.0-1.x86_64 conflicts with file from package zettlr-1.7.5-1.x86_64`
  `file /usr/lib/.build-id/65/a1ae27d9027fcf07a6e027c5ed4d3f7d389c54 from install of freetube-0.8.0-1.x86_64 conflicts with file from package zettlr-1.7.5-1.x86_64`
  `file /usr/lib/.build-id/e2/9e37c9cc2e715a24a77b13bee84b4e1e6e06f0 from install of freetube-0.8.0-1.x86_64 conflicts with file from package zettlr-1.7.5-1.x86_64`
  `file /usr/lib/.build-id/ed/11ec403fe639e0d12f9263a7aaa93f8bbf6a6c from install of freetube-0.8.0-1.x86_64 conflicts with file from package zettlr-1.7.5-1.x86_64`

What could have cause this package conflict? Could that be an electron version incompatibility?  Thank you!

Edit: Also, I can't installed Zettlr if Freetube is installed previously. I have submit a [bug report](https://github.com/Zettlr/Zettlr/issues/1321) on the Zettlr Github page, in case that's helpful for you.

**Comment by Bira-oliverio** [comment]
A workaround is to use the appimage instead of the rpm.

**Comment by GilgusMaximus** [comment]
Does the appimage solve the issue? If so I'd close this issue

**Comment by Svallinn** [comment]
Since the AppImage seems to be an appropriate workaround and this problem is a very upstream issue, I'll be closing this for now.
You're free to comment to overturn my decision.
