### ISSUE TITLE
[Bug]: player does not always play full video

### ISSUE THREAD

**Issue by Krik658** [FreeTubeApp/FreeTube#5695]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to the channel https://www.youtube.com/channel/UCxb8STz7WB3Q1b8uM2k2jpg
2. Click on "_LIVE_" tab
3. Search for "_Steel, Vehicles & S.A.M.! - Let's Play 🔴 Satisfactory Live_" (currently the first video in the list) YT-Link: https://youtu.be/2nO0qMhXhcM
4. Observe video length in thumbnail: **6:56:39**
![thumbnail](https://github.com/user-attachments/assets/aa4becae-58d8-438b-a6b5-ed66de10cfd5)
5. Click on video, observe video length in the player: **2:00:00**
![player](https://github.com/user-attachments/assets/aabf2e98-5a90-4940-86a9-71b9577b264e)
6. Fast forward to the end, video stops playing a **2:00:00**

### Expected Behavior

1. Both lengths should be the same.
2. It should be **6:56:39** (according to youtube.com).
3. Player should play the full video and not stop at **2:00:00**

### Issue Labels

content not loading, inconsistent behavior

### FreeTube Version

v0.21.3 Beta

### Operating System Version

SteamOS 3.5.10 (current stable) // Linux 6.1.52-valve16-1-neptune-61 #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000 x86_64 GNU/Linux

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Video was still being processed on YT side and thats why you saw that timestamp.
