### ISSUE TITLE
[Bug]: Shaka-player unable to override sponsor block segment

### ISSUE THREAD

**Issue by k0zyrev** [FreeTubeApp/FreeTube#5700]
### Guidelines

- [x] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

It is impossible to manually click on a video segment that is marked by sponsor block to be skipped and force it to be played. When you click on such segment, it immediately skips is.

### Expected Behavior

with the previous video engine it was possible to click or rewind the video and watch any segment marked by sponsor block

### Issue Labels

feature stopped working, usability issue

### FreeTube Version

0.21.3 Beta c90674d

### Operating System Version

win10

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This is working as expected, as mentioned in the "Missing/Removed features" section of the player migration pull request:
> I removed the ability to seek into sponsor block segments that are set to skip, as it was causing the skipping to not work properly, due to the existing implementation being fundamentally flawed. If someone would like to add something like that back in the future, it should require a specific user-interaction to unskip the segment, e.g. a button in the skip message, instead of allowing users to manually seek into the segment.

**Comment by k0zyrev** [comment]
> removed the ability to seek into sponsor block segments 

is there a way to undo it manually? I don't mind occasional breakage in exchange of being able to seek through entire video without disabling the feature. I've encountered more than a few mislabled segments for less popular videos.

**Comment by absidue** [comment]
> is there a way to undo it manually?

No not at the moment, that functionality would have to be newly implemented and would likely require rewritting the SponsorBlock implementation again.

**Comment by absidue** [comment]
> I would greatly appreciate it if you give me a hint to what file and function I should look into.

* `src/renderer/components/ft-shaka-video-player/ft-shaka-video-player.js` -> You'll want to go to the region labeled `SponsorBlock`
* `src/renderer/components/ft-shaka-video-player/ft-shaka-video-player.vue` -> For UI changes, which you'll definitely need it you want a manual undo.

**Comment by k0zyrev** [comment]
Thank you!

>  For UI changes, which you'll definitely need it you want a manual undo.

I meant just to hardcode the thing back, not implement it properly, not sure if I'll need extra UI work for that.

**Comment by absidue** [comment]
Ah okay sure if you are doing it just for yourself, then you can do whatever you want and even go back to the old broken behaviour, well reimplement the broken behaviour in the new SponsorBlock code.

**Comment by k0zyrev** [comment]
I've seem to have managed a ~~decent~~ working result with my limited skills with one problem though - I've only figured out how to do it with keyboard seeking https://pastebin.com/raw/4RQwmPMs (ft-shaka-video-player.js diff)

In short, when I press a key (left/right arrows or 1..9) I also save that it was a manual action and, if that resulted into moving into a sponsorblock segment, the segment is not being skipped. I also remember which segment that was and remove the "manual action" state, so the next segment gets skipped as intended.

So I need help with one last thing - when I click on the seek bar, I need to set change a variable. For the love of god I can't figure out where in the file it handles mouse click events. Could someone help me please?
