### ISSUE TITLE
[Feature Request]: Shaka Player - Picture in Picture Keep Open When Navigating 

### ISSUE THREAD

**Issue by o-data** [FreeTubeApp/FreeTube#5701]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

v0.21.3-nightly-4754 Beta

With the new Shaka Player, while using Picture in Picture (PiP), the moment you navigate away from video it will auto close. This restrict user from 'multi-tasking', for example: finding more video to watch, browsing video and subscription, changing Freetube setting, etc from being possible. 

We now must use a new Window/Instant if we still want to watch video while multi tasking.

### Proposed Solution

Picture in Picture should follow old behavior (video.js / pre-Shaka Player), we can still watch video while freely using Freetube.

### Alternatives Considered

Not sure what would be Alternative proposal here. My brain not big enough. Perhaps this Feature is not possible with Shaka Player.

### Issue Labels

ease of use improvement, improvement to existing feature, new feature

**Comment by absidue** [comment]
The old behaviour was a bug, the PiP window was never meant to outlast the watch page, because the only time FreeTube knows that you are watching a video is when you are on the watch page, which also lead to bugs like the watch history not getting saved and different videos playing in the PiP window vs the main window, with no way to get back to the watch page of the original video.

**Comment by absidue** [comment]
It is a bug because it was broken and broke other things such as the watch history saving. It was never meant to be that broken in the first place. It's like being unhappy that your car doesn't go as fast down hills anymore because the mechanic fixed the breaks.
