### ISSUE TITLE
[Feature Request]: Remember Picture in Picture (PiP) Window Size (Resolution) in "New Window"

### ISSUE THREAD

**Issue by o-data** [FreeTubeApp/FreeTube#5702]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

v0.21.3-nightly-4754 Beta

Each New Window (Ctrl+N) seem to reset the Picture in Picture window size.

### Proposed Solution

Last use Window Size is remember and it will re-open in that size.

### Alternatives Considered

A new setting which we can choose the "default resolution" perhaps?

### Issue Labels

improvement to existing feature, new optional setting

### Additional Information

![image](https://github.com/user-attachments/assets/fb3a71c9-4d6b-419d-9a4b-7073e802c36e)
The size of the PiP when you use it in a New Window.

**Comment by absidue** [comment]
The Picture-in-Picture window is managed by Electron/the browser itself, all we can do is ask for it to be opened or closed. So I'm going to close this as not possible.
