### ISSUE TITLE
[Bug]: All data wiped after updating to 21.3

### ISSUE THREAD

**Issue by YI8it** [FreeTubeApp/FreeTube#5703]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I updated from 21.0 to 21.3 and now everything is deleted. My subscriptions, history, settings, playlists, profile is all gone. I checked the Recycle Bin in hopes that my old files wasn't permanently deleted but no luck.

### Expected Behavior

Updating software ≠ wipe everything.

### Issue Labels

data loss

### FreeTube Version

v0.21.3

### Operating System Version

Windows 10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v21.0

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It is not possible to get your data wiped by updating FreeTube. FreeTube does not touch the database files when updating.
