### ISSUE TITLE
Copy/pasting YouTube URLs in the nav bar ignores some query parameters

### ISSUE THREAD

**Issue by VioletRose** [FreeTubeApp/FreeTube#572]
**Behavior of the program**
When pasting a YouTube URL containing query parameters specifying a start time or playlist into the search/navigation box, those parameters are ignored. The video will play from the start and no playlist is visible.

The parameters which are ignored include `t`, `list`, and likely `index` (which can't be confirmed until list is supported).

**Expected behavior**
Entering a YouTube URL in the search/navigation box should produce equivalent results in the application to navigating to that URL in a browser, including query string parameters.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Navigate to any page containing the search/navigation box at the top
2. Paste a YouTube URL containing a timestamp and/or playlist parameter into the search/navigation box
3. Navigate to the URL
4. Observe that the video loads to the beginning, with no playlist present

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Xubuntu
 - OS Version: 20.04
 - FreeTube version: 0.8

**Additional context**
https://github.com/FreeTubeApp/FreeTube-Vue/issues/133

**Comment by ChunkyProgrammer** [comment]
t parameter was solved with #1090
list parameter was solved with #1260

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@VioletRose is this fixed for u?

**Comment by VioletRose** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Yes, thanks for checking! I tried youtu.be and youtube.com, and both are picking up the query parameters correctly.
