### ISSUE TITLE
[Feature Request]: Active profile and/or channel/playlist name in window title (at all times, including with video title)

### ISSUE THREAD

**Issue by UnconsciousBlaringHuman** [FreeTubeApp/FreeTube#5721]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I use ActivityWatch to track my productive time and Cold Turkey Blocker to close/block windows and tabs that are a distraction, and both work mainly by reading the active window title.

I'm sure most, if not all, of you can relate to 1 - using youtube for learning as well as entertainment; and 2 - every now and again having one of them days where you just can't get anything done, with youtube being, at least in part, the guilty party. So I use them both to help me keep on track with my productivity.

### Proposed Solution

If it was possible to have the active profile and/or channel name and/or playlist name in the window title, especially when there's a video open, it'd make my life slightly better.

If only one of them was to be added, my preference would be to have the active profile, as channels I haven't used before wouldn't be a problem, though profile+channel or profile+playlist or all 3 at the same time would give me better granularity, which I'd definitely appreciate.

If any of it was to be implemented, I'd strongly suggest adding them as toggles that are off by default, otherwise it might clutter the window title way too much, especially when there's a video open.

### Alternatives Considered

Using keywords from video titles. Works ok but I get too many false positives and it misses some titles, not to mention the need to whitelist a lot of windows in Cold Turkey.

### Issue Labels

ease of use improvement, new optional setting, support for external software

### Additional Information

Honestly, I don't even need it to be added officially to FreeTube. As I said, I understand it might clutter the window title too much, but if any of you lovely people tell me what files (all I know is that App.js is the one that handles the title) need changing and what are the necessary changes, I'd happily build it myself and try to keep it working in a future version if it were to fail, but I'm entirely unfamiliar with JS and I've failed to figure this out until so far.

If this doesn't get implemented but someone tells me what needs changing, there's no need to help me add a toggle for them in settings, I wouldn't need or use it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is too niche of an usecase to add to FT. People generally dont interact in the way you are proposing. Closing as i dont see this happening.
