### ISSUE TITLE
[Bug]: shaka-player setup on macOS fails when building locally

### ISSUE THREAD

**Issue by aaronhma** [FreeTubeApp/FreeTube#5731]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [ ] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Following https://github.com/FreeTubeApp/FreeTube/discussions/2771#discussioncomment-3973550, on the `yarn install` command, this happens:

```zsh
$ run-s --silent rebuild:electron patch-shaka
  • electron-builder  version=24.13.3
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at resolve (node:path:1101:7)
    at file:///Users/[username]/Desktop/FreeTube/_scripts/patchShaka.mjs:8:24
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  code: 'ERR_INVALID_ARG_TYPE'
```

This issue stems from [this commit 2 weeks ago](https://github.com/FreeTubeApp/FreeTube/commit/b3ff837468845ab55eca5499e60c352ff2df506d) on [line 8 of patchShaka.mps](https://github.com/FreeTubeApp/FreeTube/blob/development/_scripts/patchShaka.mjs#L8).

Replacing line 8 with `const SHAKA_DIST_DIR =  '/Users/[username]/Desktop/FreeTube/node_modules/shaka-player/dist'` fixes the issue.

### Expected Behavior

There should be no error, as it was working about 2 weeks ago.

### Issue Labels

causes crash, content not loading, feature stopped working, usability issue

### FreeTube Version

development

### Operating System Version

macOS Sequoia 15.1 Developer Beta 4 (24B5046f)

### Installation Method

.dmg

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Your version of Node.js is too old, you should be using at least version 20.11.0 or 21.2.0. As you are using the lastest version of macOS you could also just install the latest version of Node.js.

**Comment by aaronhma** [comment]
@absidue thanks, i totally forgot about updating node! 😅
