### ISSUE TITLE
[Bug]: While viewing a playlist in picture-in-picture, when the next video starts video will not show

### ISSUE THREAD

**Issue by cjshrader** [FreeTubeApp/FreeTube#5739]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Start playing videos in a playlist
2. Open the picture-in-picture mini player
3. When the first video ends, the next is automatically played
4. Observe that the video is now completely black, though audio works

### Expected Behavior

Expected behavior would be that video continues to work through playlist video transitions in the picture-in-picture player

### Issue Labels

content not loading

### FreeTube Version

0.21.3 Beta

### Operating System Version

Edition	Windows 11 Pro Version	22H2 Installed on	‎10/‎7/‎2023 OS build	22621.4169 Experience	Windows Feature Experience Pack 1000.22700.1034.0

### Installation Method

.zip

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not possible due to the brokenness and limitations of how the upstream player implemented this

**Comment by cjshrader** [comment]
Sorry, does that mean I should report this bug to whomever implemented the upstream player? Do you know where I can find that?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Well we are actually migrating away from that player to a new one in the next minor release. This specific functionality wont be implemented and im not sure at the moment if its even possible. I would recommend reaching out again a few weeks after the next minor release has been dropped to see of there is something we can do about this.
