### ISSUE TITLE
[Feature Request]: Long video filters

### ISSUE THREAD

**Issue by throwException** [FreeTubeApp/FreeTube#5742]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I'd like to find longer videos of more than 30m, 40m or 60m.

### Proposed Solution

Add a programmatic filter on to of the YouTube API filter to filter out all shorter videos.

### Alternatives Considered

I've used the ">20m" filter and then manually look for longer videos.

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We unfortunately only can use the same filters that YT provide.
