### ISSUE TITLE
[Bug]: audio video sync issues on new gaming laptop.  No peripheral's

### ISSUE THREAD

**Issue by NinjaKristo** [FreeTubeApp/FreeTube#5746]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Of 10 videos tested, all were well out of sync (audio/video).  youtube works fine, other streaming works fine.  just freetube.  Unable to tell if audio is advanced or retarded.  

### Expected Behavior

audio-visual synchronization

### Issue Labels

API issue, visual bug

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 11 23H2, 

### Installation Method

.exe

### Primary API used

Invidious API

### Additional Information

2024 HP Omen w Nvideo 4070 (gaming laptop)
Processor	13th Gen Intel(R) Core(TM) i7-13700HX   2.10 GHz
Installed RAM	32.0 GB (31.6 GB usable)
Device ID	2FC162C4-026A-42BA-B036-9F18AD3D8E95
Product ID	00330-52680-29484-AAOEM
System type	64-bit operating system, x64-based processor
WIN11 PRO

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could you try updating your cpu/gpu drivers?
