### ISSUE TITLE
[Bug]: Video keyboard shortcuts don't work if the last mouse focus was on a button/control.

### ISSUE THREAD

**Issue by mbomb007** [FreeTubeApp/FreeTube#5751]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open FreeTube
1. Click to watch a video
1. Click play and click the fullscreen toggle in the lower-right of the video to make it full screen.
1. Press <kbd>F</kbd>, to toggle fullscreen; or press <kbd>K</kbd> to start/stop; or an arrow. None of them work. <kbd>Space</kbd> will press the button that was last pressed, but the actual shortcuts don't work.

Now, click in the middle of the video. Then try the shortcuts again. They work.

### Expected Behavior

Shortcuts should work even if the last-clicked thing was a button in the video controls.

### Issue Labels

keyboard control not working

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 11 23H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Issue fixed by the player migration that will be available in the next minor release.
