### ISSUE TITLE
[Bug]: Error: Failed to request player id on video startup

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [FreeTubeApp/FreeTube#5752]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When i am  trying to start a video it would not with pop up error 
**Error: Failed to request player id**. Bug has appered today. Before it was ok.
Api  - local, proxy -tor (socks5)

### Expected Behavior

video should be started 

### Issue Labels

feature stopped working

### FreeTube Version

v0.21.3 

### Operating System Version

Linux mint 

### Installation Method

.apk (Alpine Linux Package)

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by AlekseiKhatkevich** [comment]
Sometimes exception text is different - **TypeError: Cannot read properties of null (reading 'reason')**

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is it possible for you to try a different proxy?

**Comment by Zeabyte** [comment]
> Sometimes exception text is different - **TypeError: Cannot read properties of null (reading 'reason')**

I am getting the same error pretty often now. I am using ProtonVPN and have to change server almost daily. Why is that suddenly the case? In a year I have never had issues because of an IP blacklist and suddenly it's a daily occurrence...

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Zeabyte can you list a few servers of the ProtonVPN this is happening on for you?

**Comment by Zeabyte** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Sure, if I find one that's blocked for a longer time.

The server that had a problem 20 minutes ago is working fine again. And after looking at some logs of my HTTP Proxy (that uses ProtonVPN) I am not too sure if this is actually IP blacklisting after all, because there were some DNS resolve errors...

Next time this happens I will take a closer look. Thanks for looking into this.

**Comment by AlekseiKhatkevich** [comment]
> Is it possible for you to try a different proxy?

Yes, but it happens only while traffic goes via TOR. I guess DPI mix up heeaders or somthing like this
