### ISSUE TITLE
[Bug]: Show subscription cache even if the RSS subscription video list failed to fetch/load

### ISSUE THREAD

**Issue by ArthurKun21** [FreeTubeApp/FreeTube#5755]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open freetube and sees the subscription cache
2. Refresh the subscription cache
3. Sees the IP block by Google
4. Could no longer see the cache video list

### Expected Behavior

After refreshing the subscription video list, if it fails due to IP block by Google it should still be able to see the cache video list

### Issue Labels

content not loading

### FreeTube Version

9ca2c7452968e976896191d87281fe8eecf4fea1

### Operating System Version

windows 11

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

This bug report is in tandem with https://github.com/FreeTubeApp/FreeTube/issues/5749

Make it similar to the error when loading a YouTube channel(s) but could not load any videos on it.

It shows the YouTube Channel(s) on top with the text: `could not load from the following channel(s)` but instead `could not fetch/load subscription videos due to RSS failed to load`

At the moment I have already reset my router and have gotten new IP, so I won't be able to check the fix(when it is available) and check if the issue still persist with the RSS not loading and still retaining the subscription cache

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://github.com/FreeTubeApp/FreeTube/pull/5756 should solve this one but we have no way of knowing as the RSS is up again. Ill close this one but feel free to reach out when RSS is down and that PR didnt fully solve it.
