### ISSUE TITLE
[Feature Request] Option to hide the gigantic Play/Pause circle

### ISSUE THREAD

**Issue by awsms** [FreeTubeApp/FreeTube#5762]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I don't remember since which commit (must have been a couple of weeks) this new behaviour was added, a gigantic cercle that takes a big part of the video visibility when the mouse enters the video area, or when the playback state is toggled.
![image](https://github.com/user-attachments/assets/fbf57303-1f35-4f0a-bcfa-f5009f3e5b49)

### Proposed Solution

Add an option in the settings to hide this.

### Alternatives Considered

Using mpv directly.

### Issue Labels

new optional setting

**Comment by absidue** [comment]
`Player Settings` -> `Display Play Button In Video Player`.

Next time please check if the setting that you want to request already exists, before opening a feature request.
