### ISSUE TITLE
Can't import ompl files from YouTube

### ISSUE THREAD

**Issue by serjor** [FreeTubeApp/FreeTube#577]
**Behavior of the program**
I'm trying to import into FreeTube the OPML file downloaded from YouTube using the AppImage from the [v0.8.0-beta](https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.8.0-beta) release, but it is not possible.
Whenever I click on import from youtube, the file extension filter is set to "Database file" and it doesn't offer any other option, so the OPML isn't show

**Expected behavior**
Being able to look for a OPML and import it into FreeTube

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Import Subscriptions'
3. Click on 'Import YouTube (.opml)'
4. Navigate to where the file is located
5. File filter is set to 'Database File' and OPML file isn't shown

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - OS Version: Manjaro (it is a rolling release, so "version" doesn't apply here)
 - FreeTube version: 0.8.0-beta

**Comment by GilgusMaximus** [comment]
For me (windows) it does show the correct file type:
![image](https://user-images.githubusercontent.com/34301369/95014811-bab90900-0649-11eb-8851-82f86f9c04fd.png)

Anyone else with this issue on Linux?

**Comment by serjor** [comment]
This is what I see:
![imagen](https://user-images.githubusercontent.com/6491212/95014865-1edbcd00-064a-11eb-9c74-159ed7b6471d.png)

**Comment by Hiers** [comment]
To me, it also only has the option for "Database File", but .opml files do show up. Please make sure the file has the extension ".opml", otherwise it won't show.

**Comment by anthony-beckett** [comment]
> To me, it also only has the option for "Database File", but .opml files do show up. Please make sure the file has the extension ".opml", otherwise it won't show.

This worked, thanks. Strange that you need to do this on 0.8.0 now though, perhaps it's from the rewrite?

**Comment by GilgusMaximus** [comment]
@serjor could you confirm that it works for you as well? Then I would close the issue afterwards.

**Comment by serjor** [comment]
I have to apologize. Renaming the file was the first thing I tried and also I tried to rename it to .db just in case, but maybe I made a typo or something like that, because today the file is there.

Sorry for the inconveniences.
