### ISSUE TITLE
[Feature Request]: Playlist categories

### ISSUE THREAD

**Issue by chrrybmb64** [FreeTubeApp/FreeTube#5780]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I have lots of playlists and want to organize them.

### Proposed Solution

Implement playlist categories that allow users to separate and organize their playlists.

### Alternatives Considered

n/a

### Issue Labels

improvement to existing feature, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as I think this is better suited for https://github.com/FreeTubeApp/FreeTube/issues/1996. For example If somebody got a Music Profile they can put all their music related playlists in that profile to separate them
