### ISSUE TITLE
[Bug]: Subscriptions page does not show any video when opening FreeTube

### ISSUE THREAD

**Issue by cesc1989** [FreeTubeApp/FreeTube#5781]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

On launching FreeTube 0.21.3, the app does not load my already imported subscriptions. Instead it displays the following message on the subscription page. Refreshing does not correct this.

> Your Subscription list is currently empty. Start adding subscriptions to see them here.

Subscriptions can be seen in the Profile settings page, under "Other Channels".

### Expected Behavior

Opening FreeTube app, it should display videos from the subscription list.

### Issue Labels

content not loading

### FreeTube Version

0.21.3

### Operating System Version

Macos Ventura

### Installation Method

.zip

### Primary API used

Local API

### Additional Information

![Screenshot 2024-10-02 at 4 27 24 PM](https://github.com/user-attachments/assets/5ecb8458-c6df-4a4b-a45b-d2121b24afca)

![Screenshot 2024-10-02 at 4 27 44 PM](https://github.com/user-attachments/assets/5ba50a46-f092-42b6-ad15-8dc1c3fbf4dd)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
From looking at your screenshot the current behavior seems to be correct.

In the Profile manager the current active profile `El Coshinita` does not contain any subscriptions, see `Subscription List` section. Thats why you see no subscriptions in the Subscription page. The Other subscriptions section in the Profile manager are subscriptions that are available to add to this profile that are retrieved from the other profiles.

**Comment by cesc1989** [comment]
> From looking at your screenshot the current behavior seems to be correct.
> 
> In the Profile manager the current active profile `El Coshinita` does not contain any subscriptions, see `Subscription List` section. Thats why you see no subscriptions in the Subscription page. The Other subscriptions section in the Profile manager are subscriptions that are available to add to this profile that are retrieved from the other profiles.

So you're telling me I correctly imported them but for the wrong profile? I don't recall the order I configure the app but that explains it.

Thanks a bunch.
