### ISSUE TITLE
[Bug]: newpipe subscription list not importing.

### ISSUE THREAD

**Issue by locoloon** [FreeTubeApp/FreeTube#5787]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I did a recent export from the latest newpipe version.  and then tried to import to freetube latest version. nothing has shown up after 15min. and after a reboot.  pc is on windows 10.  rx5800 64gig ram. the files in the exported zip were newpipe.db and newpipe.settings it did not contain .json file

### Expected Behavior

no subscribed channels show up

### Issue Labels

feature stopped working

### FreeTube Version

v0.21.3 beta

### Operating System Version

windows 10 pro 1094

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@locoloon is it possible for you to share the file you are trying to import?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> it did not contain .json file

![IMG_20241003_185230.jpg](https://github.com/user-attachments/assets/5e6f0db6-78cc-4227-82e7-88ba5bac323c)

You should go to this page and hit the three dots on the top right corner to export the correct file.
