### ISSUE TITLE
[Bug]: Playlist repeating the same video

### ISSUE THREAD

**Issue by m3thm4th** [FreeTubeApp/FreeTube#5788]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

This problem occurs when using Local API without fallback and proxying traffic through Tor.

When watching a playlist, sometimes (at random, couldn't find any pattern) when the next video starts it's actually the one that's finished, the next element in the playlist is highlated as currently playing and marked as watched in history, but the actual video playing is the one that just ended. If Tor proxy is disabled it behaves as expected.

### Expected Behavior

.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.21.3

### Operating System Version

Debian 12

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
As there isnt a reliable way to reproduce this,

Please do the following:
1. Open the dev console by pressing `CTRL+SHIFT+i`
2. Go to a playlist
3. Bug occurs
4. See if there are any red errors popping up when the bug occurs 
5. Create a screenshot of these errors.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> please whitelist this issue so the github-actions bot doesn't mark it as stale as I don't know when this will occur.

I wont. I will mark this with `U: Waiting for Response from Author` and if you dont respond within 14 days with the info we need the issue will close itself. We can reopen it after when you found the info we need.

To be clear only comment when you can provide the info.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@m3thm4th is this still happening in v0.22.0?
