### ISSUE TITLE
[Feature Request]: Keyboard shortcut for "full window"

### ISSUE THREAD

**Issue by Nitesh3141** [FreeTubeApp/FreeTube#5792]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

"Full window" option is unique to FreeTube and pretty useful when used with a tiling manager. However, the screen button is not visible when FreeTube is tiled ina  small floating window. Can there please be a shortcut to enable full window from a tiled FreeTube window.

### Proposed Solution

A keyboard shortcut along with diagonal arrows to enable and disable full window

### Alternatives Considered

Maximising window, enabling full window and tiling FreeTube again. This is a long process though.

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
There is already a shortcut for Full Window, `s`

For future reference see https://docs.freetubeapp.io/usage/keyboard-shortcuts/
