### ISSUE TITLE
[Feature Request]: Ability to sort playlists by oldest videos

### ISSUE THREAD

**Issue by xp4eternity** [FreeTubeApp/FreeTube#5796]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Playlists are shown by newest video

### Proposed Solution

Playlists to have the ability to sort by oldest video.

### Alternatives Considered

None so far. 

### Issue Labels

new feature

**Comment by Nobylo** [comment]
Important to note: You are able to sort by oldest if it's a playlist you made in freetube, and you can "reverse" playlists while watching them (as flawed as it is) but you can't sort by oldest when just viewing others' playlists. You can copy a playlist and edit it but sorting by "date added" no longer works cause, they all got added at the same time.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @xp4eternity, just to clarify, is this talking about sorting videos in an user playlist by recently uploaded and oldest uploaded?

**Comment by xp4eternity** [comment]
Sorting videos yes.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You didnt answer the question.

**Comment by xp4eternity** [comment]
wdym i didnt answer the question? 

"by recently uploaded and oldest uploaded"

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> in FreeTube by recently uploaded and oldest uploaded or about sorting YouTube playlists?

There is a "or" in this question.

**Comment by xp4eternity** [comment]
I already answered the question 2 messages above IN THIS thread

**Comment by absidue** [comment]
@xp4eternity There is a big difference between playlists created in FreeTube and one that are on YouTube, so which one of the two do you mean?

If you actually want anyone to be able to do anything with this feature request, you need to actually provide useful information when asked, otherwise we'll have to close this issue because we don't actually know what you are asking for and you are being very uncooperative.

**Comment by xp4eternity** [comment]
Im saying the ones already created on Youtube.  

Is that the answer y'all are looking for. cause im starting to get mad.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isnt possible as YouTube doesnt provide this information to us.

**Comment by xp4eternity** [comment]
Thought they did.
