### ISSUE TITLE
Open links in default browser

### ISSUE THREAD

**Issue by dimqua** [FreeTubeApp/FreeTube#58]
Would be nice to have a possibility to open both youtube and hooktube links in the default browser.

**Comment by PrestonN** [comment]
This is something I'm already working on.  The plan is to include this in the next release.

**Comment by dimqua** [comment]
@PrestonN please make it possible to open the video into YouTube/HookTube, when you already open it in FreeTube.

**Comment by PrestonN** [comment]
This was added in 0.2.1 so I will close this issue.
