### ISSUE TITLE
Open app at startup

### ISSUE THREAD

**Issue by paulpopus** [FreeTubeApp/FreeTube#580]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I think it would be useful to have the option to start the Freetube app at start up. I know this can be done OS side but most applications will have an internal setting.

[Electron 9.3.1 has this API](https://github.com/electron/electron/blob/v9.3.1/docs/api/app.md#appgetloginitemsettingsoptions-macos-windows) which I'm not sure will handle the full functionality. It also doesn't mention Linux but workarounds can be figured out if this is possible.

**Describe the solution you'd like to see implemented**
When I go into settings, under General settings I see the option "Run Freetube at startup" and when I start my computer, Freetube will start after logging in.

**Describe alternatives you've considered**
n/a

**Screenshots**
n/a

**Additional context**
An additional setting could be to start minimised.

I don't yet know my way around Electron but after I finish my currently active project, I'll gladly jump in and add some PRs if nobody takes this on until then.

**Comment by arrowgent** [comment]
you must be speaking from the Windows side of the application?

when adding a PR you must consider all OS which the application currently supports
and on their build add an exclusion option

personally i dont want things to start when i boot my computer (launch my os)
thus by default all options should be the Least Invasive

**Comment by PrestonN** [comment]
I think I'd rather let everyone use the built in OS settings than to create new functionality myself. All major OS systems support it and if that works fine then I don't see a reason to also add it.

If you make a PR and supports all operating systems, I'll consider merging it, however I have no plans on including this myself.
