### ISSUE TITLE
Comments aren't fully rendered

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#581]
There's a way to read YT comments under videos after clicking `Click to view comments`. But it looks like the comments aren't fully rendered -- a new line or a URL breaks the comments. For instance, if you open this url `https://www.youtube.com/watch?v=n7NXKA_7Ks8` in FreeTube and check comments, you get this:

![2020-10-04-14:45:08](https://user-images.githubusercontent.com/3797768/95015978-9b1ce300-063f-11eb-92dd-0b83be9ab707.png)

But the comment in reality looks like this:

![2020-10-04-14:45:18](https://user-images.githubusercontent.com/3797768/95015983-a4a64b00-063f-11eb-882c-d013616f9632.png)

**Desktop **
 - OS: Linux version 5.8.13-amd64 (morfik@morfikownia) (gcc (Debian 10.2.0-13) 10.2.0, GNU ld (GNU Binutils for Debian) 2.35.1) #12 SMP PREEMPT Sun Oct 4 12:45:20 CEST 2020
 - FreeTube version: 0.8

**Comment by GilgusMaximus** [comment]
Okay. I will investigate that in my module in the coming days. Also thanks for the video. I just found another bug 👍
