### ISSUE TITLE
Download videos locally

### ISSUE THREAD

**Issue by hebertcisco** [FreeTubeApp/FreeTube#582]
You could have the option to download the videos locally.

A button that would open a Selection with the Download options, in different formats and sizes.

**Comment by GilgusMaximus** [comment]
Downloads are on our bucket list. However PrestoN has something planned for that with the ytdl module. So it might take a while till it is available.

**Comment by creepertron95** [comment]
I wanted to suggest a download manager as well, I had a similar issue #416 that was closed prematurely.

**Comment by PrestonN** [comment]
My current plans with this is to show the basic download options similar to what Invidious did.  This does mean that a majority of sources are going to have the video / audio split into different downloads though.

My long term plan is to integrate something like [YouTube DL Material](https://github.com/Tzahi12345/YoutubeDL-Material) to handle the downloads as they can combine the audio / video formats and will overall likely handle this better than I could.  This will be a while before I can implement it though.

**Comment by KizunaH** [comment]
https://subhra74.github.io/xdm/

**Comment by GilgusMaximus** [comment]
It would be better to have something that uses Javascript and not a completely different programming language, as we would have to include the binary instead of pure code.

**Comment by PrestonN** [comment]
I've just added this to the new dev builds.  This will open the selected format into your web browser so that you can download it from there.  We'll include better download functionality in a future update, but this should be enough for now.
