### ISSUE TITLE
[Bug]: Can not export subscriptions, history and playlists

### ISSUE THREAD

**Issue by gituser823** [FreeTubeApp/FreeTube#5827]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to options
2. Export subscriptions, playlists and history
3. no .db-files are being created in the folder i chose.

### Expected Behavior

the .db files should be created.
I wanted to import them to the latest development version of freetube.

### Issue Labels

usability issue

### FreeTube Version

v0.21.3-beta

### Operating System Version

Linux fedora 6.10.4-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Aug 11 15:32:50 UTC 2024 x86_64 GNU/Linux

### Installation Method

.rpm

### Primary API used

Invidious API

### Additional Information

bug seems to be fixed in the latest development version.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You can also get the files like this: https://docs.freetubeapp.io/usage/data-location/

Make sure FreeTube is closed when you copy the files. 

Can you open the dev console and then try to export the files. If something is really going wrong there should be red errors popping up in the console after you chose the folder to save them to.
