### ISSUE TITLE
Demetrificator?

### ISSUE THREAD

**Issue by privacyseekinguser** [FreeTubeApp/FreeTube#584]
Do you think it's possible to add a setting that makes things like numbers of views/dislikes (on videos and comments), numbers of likes, numbers of comments, numbers of subscribers invisible? One thing that a lot of people (including myself) dislike about social media is that it turns into a popularity contest, and having this as a setting could help those who don't want a popularity contest to be unaware of it.

**Comment by GilgusMaximus** [comment]
Hi. A distraction free mode is planned. Hasn't been implemented yet. But we are aware that a lot of people want this.

This could also be a good first issue for new contributors, as only some UI elements have to be disabled when the setting is enabled.

**Comment by tayloraviets** [comment]
Hi, I'd like to take a crack at this one, unless @Deedone has dibs already.

**Comment by PrestonN** [comment]
Hey there!  I'll leave that up to you and @Deedone on who wants to get it done.  Feel free to collaborate if that works better.

**Comment by Deedone** [comment]
@tayloraviets sure, take it if you want. I just started and haven't done much yet, so I'll focus on suggestions.

**Comment by tayloraviets** [comment]
@Deedone thanks!

**Comment by tayloraviets** [comment]
Hi, my branch is ready for PR however I cannot push my branch (seems like permissions issues). Maybe a stupid question but I haven't really done open source before, is there some other procedure I am supposed to follow for creating a PR?

**Comment by PrestonN** [comment]
Hello!  Please fork the project into a new repository, push your changes to that, and then submit a pull request to merge that branch into ours.  Once done, we'll review it with you and see if any changes are necessary.  Hope this helps!

**Comment by tayloraviets** [comment]
@PrestonN thank you for the explanation! PR is up, sorry it took a minute, I had to make the linter happy.

**Comment by PrestonN** [comment]
#596 has been merged and is now added, so this issue can be closed.
