### ISSUE TITLE
[Feature Request]: Don't remove additional files from cache folders

### ISSUE THREAD

**Issue by JoergPalmer** [FreeTubeApp/FreeTube#5848]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Running FreeTube on Linux, the configuration files are located in ~/.config/Freetube, as it should be. This folder includes several cache related folders, e.g. Cache, Code Cache, DawnGraphiteCache, etc.

My backup strategy includes marking cache folders with a CACHEDIR.TAG file, following the concepts of the [Cache Directory Tagging Specification](https://bford.info/cachedir/). This prevents the folder (and its subfolders) from being part of backups.

Seemingly, FreeTube insists on wiping any file that is not part of its own package from the said folders. So, my CACHEDIR.TAG files are wiped when using the application.

### Proposed Solution

Don't wipe files foreign to FreeTube, or at least leave any CACHEDIR.TAG file alone.

### Alternatives Considered

Unfortunately, I can't come up with any

### Issue Labels

support for external software

**Comment by absidue** [comment]
Those cache files are generated by Chromium/Electron, we have no control over them and you definitely shouldn't be modifying those folders if you want FreeTube to work correctly (all you can safely do is delete them while FreeTube isn't running, but they will be recreated the next time it runs.

One option would be to only backup the 4 files that FreeTube writes itself, the ones that contain your settings, watch history, profiles/subscriptions and user playlists.
https://docs.freetubeapp.io/usage/data-location/#notable-files

Another one would be to move those 4 files to another directory and symlink each one back to the original location.
