### ISSUE TITLE
Remove black bars from videos

### ISSUE THREAD

**Issue by dosc919** [FreeTubeApp/FreeTube#585]
There are still a lot of 21:9 videos, that are rendered with black bars to fit an aspect ratio of 16:9. I have a 21:9 monitor, so I always have a black box around such videos. If 21:9 videos were rendered without black bars, they fill out the whole screen.

It would be nice to have a button, that symmetrically cuts away the bottom and top of a video to fit a 21:9 aspect ratio. In other words, it makes a 21:9 video out of an 16:9 video. This will probably not work for all monitor and video aspect ratio, but there could be a view ratio conversions to choose from.

An alternative would be to automatically detect black bars and remove them. However, I have no idea how hard it is to implement that.

**Comment by GilgusMaximus** [comment]
I am not too sure this is something useful for most people as 21:9 monitors are not very common and it is not easy to implement that as you have to work on VideoJS itself. And that is something very time intensive as a lot of code is involved and the advantages are only minor for the moment. So in the foreseeable future this is a low priority.

However if someone wants to implement a setting which removes black bars, he/she is open to do so. Would be great if someone who already knows a lot about Videojs could join the Matrix channel and help us with 2k and 4k resolutions

**Comment by PrestonN** [comment]
I've update the video player to use [Fluid Mode](https://docs.videojs.com/tutorial-layout.html) instead of forcing an aspect ratio, which should remove the black bars for a majority of videos.

I say majority because any sort of vertical video ended up looking extremely ugly, so I'm still going to force 16:9 there. Either way, this should behave the way you expect it.

**Comment by serverNinja25** [comment]
@PrestonN version 0.11 did not fix this issue

**Comment by PrestonN** [comment]
Could you please send me an example video where black bars are appearing? I can take a look into it again.

**Comment by serverNinja25** [comment]
I have to apologize because I just quickly read through this thread and I just realized now that the owner of this thread might have had a different issue than me. My issue is that when I open pip and it reaches a certain size it disappears for a second and reappears with black bars on both sides

**Comment by dosc919** [comment]
First of all, thanks for your work. I really appreciate it.

For me it works fine most of the times. However, it does not work for some videos, e.g.:
https://youtu.be/6XMuUVw7TOM

And for some i get the following error:
`Video Player is loading.This is a modal window.video append of 568589b failed for segment #0 in playlist 4-placeholder-uri-4`
The error occurs, when setting the "Autoplay Videos" option to on and watching a video for the first time / from the very beginning. I don't press any button on the video player or page of the video. The video simply doesn't load and it shows the error. When setting "Autoplay Videos" to off and then manually starting the video, it works fine. Also continuing a started video with autoplay does not produce an error. Clearing history and cache and restarting Freetube makes the error to reappear.
I don't know if it makes a difference, but I have installed / updated Freetube with chocolatey and I use the "Local API" as preferred backend with fallback to Invideos.
I could most reliably reproduce the issue with this video (probably not your taste in music, you may want to play it mute)
https://youtu.be/Q0wbyQRRQJA

**Comment by PrestonN** [comment]
The videos that you linked have the black bars embedded into the video itself. You can see this if you open the videos on YouTube directly. In this situation, there's nothing I can do about it.

The other issue you mentioned seems to be a fairly recent one, but it's been reported a couple of times now. I'll need to look into it and see what's causing that issue.
