### ISSUE TITLE
[Bug]: There's no Progress bar / Seek bar in Live streams

### ISSUE THREAD

**Issue by kugiigi** [FreeTubeApp/FreeTube#5851]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to a Live stream video
2. Try to skip to past timestamp

### Expected Behavior

A seek bar is located at the bottom of the player just like every video and clicking on it will skip to the relevant timestamp

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Ubuntu 22.04

### Installation Method

Snapcraft (Unofficial)

### Primary API used

Local API

### Additional Information

Also the same with Windows version so probably a general issue/missing feature

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
fixed by https://github.com/FreeTubeApp/FreeTube/pull/5705
