### ISSUE TITLE
[Bug]: Fullscreen dropping frames when monitor refresh >60Hz

### ISSUE THREAD

**Issue by BrentL1** [FreeTubeApp/FreeTube#5855]
### Guidelines

- [ ] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [ ] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug
Edited

1. Open Video example https://youtu.be/ndOlKlBAanI (in my case 1440p) and play
2.  show statistics -> video playing fine, no dropped frames
3. go to fullscreen with statistics on -> see dropping fps (and video stutter)

*EDIT*
This seems not to happen on every video, for example happens in the Video I linked above, 
but does NOT happen in this video:
https://youtu.be/tkkx2h-rIEI

Both same at 1440p

My Monitor is 144Hz refresh. When I set it to 60Hz in Windows the frame drops in fullscreen go away.
GPU ist Radeon 7900XT; drivers tested 24.8.1 & 24.9.1 

Also tested on other machine connected to TV (LG Oled 120Hz), same behaviour
GPU Radeon 6700XT; drivers tested 24.8.1 & 24.9.1 

### Expected Behavior

Expected no difference between playing in window mode and fullscreen.

### Issue Labels

inconsistent behavior, visual bug

### FreeTube Version

v0.21.3-RC-4879

### Operating System Version

Windows 11 24H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
As most games are fullscreen, graphics drivers tend to have different behavior for fullscreen apps. Please check your graphics driver settings and try disabling anything that says it is activated for fullscreen apps or find a way to exclude FreeTube from those settings. I would suggest checking settings related to variable refresh rate first, as you problem is related to refresh rate.

**Comment by BrentL1** [comment]
Ok, I nailed it down to the AMD FreeSync feature. Not Freetubes fault.
If you disable FreeSync everything is working normal. You can also disable FreeSync just for Freetube. Just add FreeTube.exe in the AMD Software Control Panel under the gaming tab just like you would add some game. Then just disable FreeSync just for it in its profile.
btw, this seemed to be an issue for like Brave Browser (and other less known Browsers) for a while as well until Amd maybe hardcoded to disable Freesync for Brave.
