### ISSUE TITLE
[Feature Request] Show duration of video on thumbnail

### ISSUE THREAD

**Issue by ThatIsAPseudo** [FreeTubeApp/FreeTube#587]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I'd like to know how long is a video without having to open it

**Describe the solution you'd like to see implemented**
There should be the video duration written on its thumbnail, like on Youtube

**Comment by PrestonN** [comment]
Durations are already shown on the thumbnail of a video.  You can see them in the screenshots in this repo or on the website.

If you're not seeing the duration in your videos, then that likely means that you're using RSS for grabbing subscriptions.  While RSS is faster and prevents rate limiting, it doesn't provide all of the typical information such as video duration.  There's nothing that can be done about this.

**Comment by ThatIsAPseudo** [comment]
Okay, thanks for letting me know !
