### ISSUE TITLE
[Feature Request]: Add to Watch Later button for listed videos

### ISSUE THREAD

**Issue by Robert-LC** [FreeTubeApp/FreeTube#5873]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When searching for videos or browsing the trending pages, sometimes I see a video I want to watch and want to add it to my "Watch Later" playlist

Currently, you have to open the video and then add it to a playlist, if your currently watching a video its annoying flow. It requires you to press back multiple times

### Proposed Solution

It would be beneficial if you could click the 3 dots on the thumbnail of a video and add it to your "Watch Later" right away without having to go back and forth. This might be something I would be interesting in contributing as a first-timer, if you approve.

### Alternatives Considered

It might not be worth the fix, specially if Watch later isn't used by many.

### Issue Labels

ease of use improvement, new optional setting

**Comment by kommunarr** [comment]
Hi @Robert-LC, we already have a Quick Bookmark setting that lets you pick any user playlist of your choice. Do you not currently have any Quick Bookmark set?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
When you have selected a playlist as your quick bookmark you should be able to hover over any video thumbnail and see the bookmark icon.

![Screenshot (352)](https://github.com/user-attachments/assets/f5aa8687-da38-413e-8ab2-5a6f13aa8c05)

**Comment by Robert-LC** [comment]
Thanks, I just started using FreeTube and was unaware of the quick bookmark selector for playlists. Thank you.
Closing this Feature Request.
