### ISSUE TITLE
[Bug]: CPU usage scales with playback speed

### ISSUE THREAD

**Issue by Victor239** [FreeTubeApp/FreeTube#5875]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Lately I play most videos on 1.75x speed or higher and I found that it's making my laptop fans turn on loudly. When I investigated this further found FreeTube scaled linearly in CPU usage with playback speed, and I was wondering if this is possible to avoid.

### Expected Behavior

CPU usage is similar regardless of playback speed.

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.21.3

### Operating System Version

Kubuntu 24.10

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
When you play at faster speeds the player has to do download data at a faster rate, do a lot more processing in a shorter space of time and then actually play the stuff a lot faster, which means figuring what to skip in the audio and video streams, but to do that is still has to process through all of it. So yes it is entirely expected that the CPU usage goes up, when you ask you computer to do more work.

**Comment by Victor239** [comment]
Ah okay, I wasn't sure if this was something that could be mitigated or not so I was hesitant to file as a "bug".

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as it is expected behavior.
