### ISSUE TITLE
channel autoplay

### ISSUE THREAD

**Issue by therealgoodstuff** [FreeTubeApp/FreeTube#588]
I want a channel autoplay. While there is an autoplay to the right called "up next" when I start a video of a certain channel this autoplay does not only consist out of channel content but content from all kind of other channels.
All I want is that the channel content will be played in the correct timely order.
cheers

**Comment by GilgusMaximus** [comment]
This is similar to #547 #413 and #519.
Whether this will be implemented is open to debate at the moment and depends on how the dynamic playlist will be implemented. But once the dynamic playlist is there, it should be easy to create a PR for that.

**Comment by arrowgent** [comment]
get the _channel id_ which starts
`UC`
then replace that with
`playlist?list=UU`


can also get from **UPLOADS PlayAll**

**Comment by ChunkyProgrammer** [comment]
Closing in favor of #629
