### ISSUE TITLE
Option to hide video suggestions

### ISSUE THREAD

**Issue by Deedone** [FreeTubeApp/FreeTube#590]
Hi, would you be okay with a feature to hide all video suggestions and popular/trending pages? I personally have a mild youtube addiction and think it would be a great way to fight with it. If it's not against your ideas and someone else not working on it already, I could implement it along with #584.

**Comment by PrestonN** [comment]
My plan is to have a new section in settings titled "Distraction Free Settings".  In here, I'd like to include different toggles for being able to hide many different things within the app.  Recommendations would be one of those such things.  If you'd like to get started on this functionality then feel free to do so.

**Comment by PrestonN** [comment]
This has been finished with #596
