### ISSUE TITLE
[Bug]: Proxy-settings do not work at launch of FreeTube

### ISSUE THREAD

**Issue by forenta** [FreeTubeApp/FreeTube#5915]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I need a proxy to get access to YouTube. It's working as long as I'm in the session - close FreeTube and launch it again, the settings are ignored even though they are still set.

1. Click on settings
2. Select proxy settings ➡️ HTTPS ➡️ 192.168.178.55, Port 80 ➡️ click to check proxy ➡️ see that everythings fine and you'll see the IP you'll get via proxy.
3. Close FreeTube and launch it again
4. Click on settings ➡️ proxy settings ➡️ check proxy again ➡️ see the error message of misconfiguration
5. Workaround: Switch from HTTPS to HTTP and back again ➡️ everything is fine again.

### Expected Behavior

Usage of the proxy at launch

### Issue Labels

content not loading, feature stopped working, inconsistent behavior

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 11 Pro 23H2

### Installation Method

Chocolatey (Unofficial)

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by briankendall** [comment]
I am also experiencing this bug. 100% reproducible. Running 0.23.5 on macOS, so not just a Windows issue.

Sounds like the app is not loading its settings correctly. Maybe an easy fix?

**Comment by ipo0x** [comment]
I’ve noticed the same issue for several versions on Linux (Fedora Silverblue and Secureblue). It’s a very frustrating problem, as every time you start the programme you have to apply the workaround of "switching to HTTP and then back to HTTPS" for it to work properly. Surely this should be a persistent setting, working from the moment the programme starts, if the proxy settings are already configured correctly?
