### ISSUE TITLE
[Feature Request]: Selective toggle off "Save Watched Progress" on a per-playlist basis

### ISSUE THREAD

**Issue by cyberwolfie1** [FreeTubeApp/FreeTube#5917]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I like the "Save Watched Progress"-feature. But I have a mixture of different playlists, including some that contain only music. For these I would always want the Watch Progress to be either ignored so that when started from that playlist, it always starts from the start.

### Proposed Solution

In the playlist view, there could be a toggle that says "Disable Watch Progress" or something like this. When this is toggled, then all the videos in that playlist will start from the beginning of the video if accessed through this playlist.

### Alternatives Considered

Instead of ignoring the Watch Progress, the same kind of toggle could instead be used to automatically reset the Watch Progress of the videos in the current playlist.

### Issue Labels

improvement to existing feature, new optional setting

**Comment by LovingNumbers** [comment]
thought about something like this would def improve useability

**Comment by Seneral** [comment]
If we could implement something broadly acceptable without users having to find a new feature in the UI to use it, that'd be preferrable. Youtube knows which videos are music, and doesn't do it for music videos.
I suggest we either have a toggle for music and normal videos separately, IF we can easily parse what is music and what is not.
If we can't, a slider defaulting to a maximum video length of 8 minutes would work too - chances are if you aborted a normal 8min video, you won't be coming back to it. The save progress feature is great mostly for longform content anyway. So any video under 8min (adjustable), which includes most (sadly not all) songs, would automatically start from the beginning (either never save the progresss, or better, just ignore it when loading)

**Comment by LovingNumbers** [comment]
> If we could implement something broadly acceptable without users having to find a new feature in the UI to use it, that'd be preferrable. Youtube knows which videos are music, and doesn't do it for music videos.
> I suggest we either have a toggle for music and normal videos separately, IF we can easily parse what is music and what is not.
> If we can't, a slider defaulting to a maximum video length of 8 minutes would work too - chances are if you aborted a normal 8min video, you won't be coming back to it. The save progress feature is great mostly for longform content anyway. So any video under 8min (adjustable), which includes most (sadly not all) songs, would automatically start from the beginning (either never save the progresss, or better, just ignore it when loading)


idk i think one toggle in the playlist should be enough lol
toggle on and it ignores progress that's it don't rly see a benefit making things complicated

**Comment by Seneral** [comment]
I think it's easier, and applies to more people
Not everyone has one playlist to listen to, or one at all
I regularly just listen with autoplay, exploring new songs along the way, and this happens then, too

On a related note, this automatic music detection could also "fix" a gripe of mine where videos already watched would be sorted at the bottom of related videos. Good for normal videos I already watched, bad for music I like to listen to repeatedly.

The playlist toggle would be awkward, basically a setting that people would have to find without any reasonable expectation to find it there. I searched the app settings for a solution when I encountered the problem. Looking into the playlist interface was not on my mind, so users would have to stumble upon the right issue/PR to find that solution. Not user friendly.

Not saying a button in the playlist interface is BAD, especially as it could fix the problem with those 15min songs, or a playlist full of albums (1hr+). But it shouldn't be the main solution IMO. The way YouTube does it transparently is best IMO.

**Comment by LovingNumbers** [comment]
> I think it's easier, and applies to more people
> Not everyone has one playlist to listen to, or one at all
> I regularly just listen with autoplay, exploring new songs along the way, and this happens then, too
> 
> On a related note, this automatic music detection could also "fix" a gripe of mine where videos already watched would be sorted at the bottom of related videos. Good for normal videos I already watched, bad for music I like to listen to repeatedly.
> 
> The playlist toggle would be awkward, basically a setting that people would have to find without any reasonable expectation to find it there. I searched the app settings for a solution when I encountered the problem. Looking into the playlist interface was not on my mind, so users would have to stumble upon the right issue/PR to find that solution. Not user friendly.
> 
> Not saying a button in the playlist interface is BAD, especially as it could fix the problem with those 15min songs, or a playlist full of albums (1hr+). But it shouldn't be the main solution IMO. The way YouTube does it transparently is best IMO.

disregard my previous response then ꜂(꜀ ꜄ ‹:)꜆ 
 this if possible to implement would be better ig

**Comment by Seneral** [comment]
> disregard my previous response then ꜂(꜀ ꜄ ‹:)꜆ this if possible to implement would be better ig
No worries, it's a valid discussion to have, one that surely happened at youtube too

Btw to add to this, just checked how youtube handles this.
Seems it knows somehow what is a song and what is not, even if it is not obvious or tagged.
E.g. it will remember progress and resume for a sub-5-min animated video.
But it won't do so for a sub-5-min "unofficial" music video:
- covers/karaoke where the original song was NOT detected
- Small indie songs (down to sub 100 views)
- Reuploads of small indie songs by channels that normally don't upload music so likely didn't tag their video correctly
- Songs that are not categorised as music (tested myself, though it might still have cached the category 1hour after)
There are false positives, on a channel that does a lot of music-related things, a few longer (4+min) videos that did not contain much musical elements did still not retain the progress, so either they were categorised as music by the creator or the channel itself influences the tagging.

Anyway, all this doesn't matter if we can't get that information ourselves.
Unfortunately from a quick ytInitialData comparison there's no obvious indication to the client which is which.
So we'll likely just have to do a hack based on time, and make it adjustable. Honestly I wouldn't mind my 6min normal video to restart anyway, should I ever want to pick one so short up again.

Another "easy" addition is to mark ALL videos that only have a minute left to go (or 5% of video runtime) as finished to make sure they'll also start from the beginning. Nothing worse than clicking on ANY video and being confronted with the outro.

**Comment by cyberwolfie1** [comment]
Just want to chime in that I am not married to my suggested solution at all, and I think @Seneral's suggestions sounds good. I agree that shorter videos not having a save state is completely fine, and as long as the behavior can be toggled on and off with a threshold that is adjustable, I think it should be generally suitable.

I have no experience with UI design, so maybe having an option to toggle this in the playlist would be a poor choice. With that said, I absolutely expected to find such a toggle in the playlist view and it was the first place I looked after not finding it in the settings.

**Comment by Penguin-Guru** [comment]
I think it would be nice to specify the duration of video for which "save watched progress" begins to take effect. For example, some users might want it only for videos longer than 30 minutes while other users might want it for videos longer than 15 minutes.

Incidentally, I really want a button on the video player's button bar that simple toggles "save watched progress" for the specific video regardless of the default setting. I suppose it would be nice to have support for bookmarking multiple positions in the video to skip between, but that would obviously be a bit more work.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing this in favor of https://github.com/FreeTubeApp/FreeTube/issues/1996

This is something that is encapsulated in that issue because if you have a separate music profile with it own settings than there is no need for this.

**Comment by Seneral** [comment]
Can't say I suite agree with that assessment.
To some degree I can see that work, but it would be a LOT of work to maintain simply to fix music playback.
If I understand your reasoning that it's equivalent, you want music listeners (probably most users) to:
1. Create a separate music profile
2. Port all music playlists and music subscriptions over
3. Disable watch history for that profile only
4. Never forget to switch to it when you randomly find new music lest that new artist subscription is not in the music profile
5. Never forget to regularly switch and check subscription feed to not miss new music related videos
6. Reload the page if you just naturally transition to music before you can add it to any of your music playlists
7. And wait many more months for such a complex feature to be implemented compared to a much simpler fix like this would be (again, comparatively)
8. And meanwhile, let every other user be annoyed by the default state of music always starting in the middle until they are fed up enough to search for a solution online to find only a complex, hard to maintain workaround that nobody but the most dedicated would do

Sorry, but I don't think they are equivalent, nor even that even if that proposal was already implemented and useable, it would warrant closing this one.

**Comment by Penguin-Guru** [comment]
They aren't equivalent for me either. My use-case has nothing to do with music and I only intend to use one profile.

**Comment by kommunarr** [comment]
While the desire for this feature is valid, nothing is without a tradeoff - an additional setting needs an access method. If we had per-playlist toggles for each type of setting, that would add many different toggles to the UI, causing information overload and a worse UX. This is not just theoretical, as many people want many different settings to be made per-playlist as well. As a result of this, our team is not likely to reach sufficient consensus to approve solutions of this type, but we do want to try to address the underlying problems in different ways.

**Comment by Penguin-Guru** [comment]
Addressing underlying issues is probably always the best option, if possible.

For what it's worth, I think the U.X. overload factor can be managed by simply grouping the settings into a collapsible field. Such fields could be nested to contain whichever groups of settings make sense and the whole container could have some size limit imposed so users could scroll through it if there are too many settings. I suck at visual design but I'm sure it's possible to do something like this well. I only say this because I'm a fan of customisability. More settings is pretty much always a good thing in my opinion, though obviously not always a priority. It would be a shame for the U.I. to get in the way of that long-term.

**Comment by Seneral** [comment]
> They aren't equivalent for me either. My use case has nothing to do with music and I only intend to use one profile.

> Another feature that might be nice is a colour shaded indicator on the video's progress bar that shows how far ahead of the current position in the video the user has already watched in the past. I can imagine some users preferring this to actually having their player jump to where they last were, but where they last were is also not necessarily the farthest they've watched in the past. 

If I'm not mistaken that already exists.
I agree it would be nice for some videos to manually specify chapters, or "read in" those chapters from some comments providing timestamps. Useful for e.g. podcasts, or videos with multiple songs (e.g. albums or compilations), that aren't properly using the chapter feature.
But I don't think it's realistic to add something like this to the UI either, the implementation and usability complexity versus the rate of users I would expect to use this is... quite high.


> While the desire for this feature is valid, nothing is without a tradeoff - an additional setting needs an access method. If we had per-playlist toggles for each type of setting, that would add many different toggles to the UI, causing information overload and a worse UX. This is not just theoretical, as many people want many different settings to be made per-playlist as well. As a result of this, our team is not likely to reach sufficient consensus to approve solutions of this type, but we do want to try to address the underlying problems in different ways.

Have you seen my proposed solution? It's less settings, works by default, no UI overload, and I believe is a reasonable solution.
Essentially just a minimum video duration for which to actually use the watched progress.
So a short video would be accepted into the watch history and progress maybe saved, but upon encountering it, it would NOT be shuffled down the related videos list, and upon loading, it would NOT automatically restart at the last position, but from the beginning (but maybe show the last progress anyway). That is the most cut-down and simple implementation I can think of for music playback.
Defaults to, 8-10min, and if you want, you can just increase the time limit by a lot and always manually jump to the last position if you do desire it (a popup would be ideal, but sure).
That way, even albums and long songs and the like would not start somewhere in the middle of a song. Considering how little I personally benefit from jumping back in, compared to how often I am annoyed by music starting in the middle, I'd probably do that and manually jump / use such a popup.

So one setting addition, default behaviour is good IMO, not too complex to implement. If any dev thinks this is fine to add, I could do it myself and do a PR. Just don't want to do it if it's already clear it won't be accepted (assuming ofc it meets guidelines)

**Comment by kommunarr** [comment]
Gotcha, you can discuss that specific proposal under #964. I think it's interesting but would like to hear more thoughts from the rest of the team.

**Comment by Penguin-Guru** [comment]
> I agree it would be nice for some videos to manually specify chapters, or "read in" those chapters from some comments providing timestamps. Useful for e.g. podcasts, or videos with multiple songs (e.g. albums or compilations), that aren't properly using the chapter feature.
> But I don't think it's realistic to add something like this to the UI either, the implementation and usability complexity versus the rate of users I would expect to use this is... quite high.

Yes, I also think all that would be a bit more work than it's worth right now. The program does already support video chapters somehow. I'm guessing that data is provided by the video's source. This is already good enough in my opinion. I only mentioned the idea of remembering points each user has marked within videos because it feels like a natural extension of the feature to remember the users' last position in the video or the farthest they've watched into it. I imagine most of the code already exists. It's definitely not a priority though. 🙂

I know there wasn't an indication of farthest watched point when I last had that feature enabled, but I've had it disabled for a long time now because there was no way of toggling it on/off for specific videos. That's one feature I would personally consider a priority. Maybe some day I'll try implementing it myself. Electron is intimidating.
