### ISSUE TITLE
[Feature Request]: Customize the autoplay timer in playlists

### ISSUE THREAD

**Issue by cyberwolfie1** [FreeTubeApp/FreeTube#5918]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently, if "Autoplay Playlists" is enabled, there will be a timer of 5 seconds between each video is played. It would be nice if this could be customized within each playlist. I have some playlists that consists only of music, and in these cases a 5 second gap is too long. 

### Proposed Solution

It could be a field in the playlist view specifying the number of seconds delay there should be between loading of a new videos, and when playing from that playlist, that number will be respected. The default could stay at 5 seconds.

### Alternatives Considered

Instead of a per-playlist option, it could be a global option than can be toggled in "Player Settings"

### Issue Labels

new optional setting

**Comment by kommunarr** [comment]
We already have this; it's called `Next Video Interval`. We will likely change the name to `Autoplay Countdown Timer` in the release after next.
