### ISSUE TITLE
[Bug]: Missing icons

### ISSUE THREAD

**Issue by sim6** [FreeTubeApp/FreeTube#5919]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Install from flathub in Librem5

There are missing icons:

![image](https://github.com/user-attachments/assets/740b82ed-e70b-4971-9f9d-502b4bcd39d0)

### Expected Behavior

Show icons

### Issue Labels

usability issue, visual bug

### FreeTube Version

v0.21.3 Beta

### Operating System Version

PureOS

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isnt a bug that is related to FreeTube but related to the device. I would recommend updating all the drivers and doing distributions upgrades

**Comment by sim6** [comment]
Installing via the deb from Releases work as expected. I guess the problem is in the flatpak package.

**Comment by pravi** [comment]
This might be related to gtk 4.18 dropping support for GLES 2 (if the flatpak is using a newer GTK4).
