### ISSUE TITLE
[Automated Build] For ArchLinux

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [FreeTubeApp/FreeTube#592]
**Topic**
Please select what topic your discussion is about.
- [x] Setup

**Discussion**
**Is your feature request related to a usage problem (not a bug)? Please describe.**

Hello @PrestonN , at first take my love for an awesome re-write. I know FreeTube has so many packages for various OS. But unfortunately Arch doesn't have any release from you guys ! (I already know about AUR) (Unofficial)

**Describe the solution you'd like to see implemented**

As you have mentioned in the blogs that if anyone don't wanna wait for official updates they can enjoy the automated builds. But there is no package for ArchLinux which can be installed using `pacman -U <pkg.tar.zst>`

**Describe alternatives you've considered**

I hope next builds will contain builds for arch linux too for seamless experience ! (AUR will be optional)

Greetings
BL4CKH47H4CK3R

**Comment by PrestonN** [comment]
It's not that I'm against creating Arch binaries, the issue is that electron-builder, the tool I use to create the binaries, doesn't seem to support `tar.zst` as an export option.  You can take a look over [here](https://www.electron.build/configuration/linux).

If one of the other options are acceptable to you, I'm more than happy to enable them into our automated builds. Unless someone tells me otherwise, it doesn't look like I'll be able to provide this.

**Comment by PrestonN** [comment]
I've added pacman builds to the automated builds.  Let me know if that works out for you.

**Comment by BL4CKH47H4CK3R** [comment]
Tested & working flawlessly. Thank you for you great effort !

![freetube_pacman](https://user-images.githubusercontent.com/54761717/95134492-7e250480-0752-11eb-8373-7b648c5cd380.jpg)

**Comment by BL4CKH47H4CK3R** [comment]
Why there is no official release for arch linux on the releases tabs just automated builds ?

Can you package .pacman ---> pkg.tar.zst format for electron builds ?

**Comment by PrestonN** [comment]
Is there any conversion I need to do for the pkg.tar.zst format with the pacman file?  I don't use Arch regularly so I'm actually not sure.  If it's easy to setup (Or if just publishing the .pacman file is acceptable) then I don't mind including them for official releases.

**Comment by BL4CKH47H4CK3R** [comment]
> Is there any conversion I need to do for the pkg.tar.zst format with the pacman file? I don't use Arch regularly so I'm actually not sure. If it's easy to setup (Or if just publishing the .pacman file is acceptable) then I don't mind including them for official releases.

I have extracted and tried renaming the file from .pacman ----> pkg.tar.zst (official arch package format) and installed using `pacman -U <freetube......pkg.tar.zst>` and it works. Now you have to check if electron builder can directly build `pkg.tar.zst` format or you have to rename `.pacman` ----> `.pkg.tar.zst`
But I am going to build with `pkg.tar.zst` instead of  `.pacman`

**Comment by ShalokShalom** [comment]
Hello, I know this is old and everything... 

It's just.. the [releases](https://github.com/FreeTubeApp/FreeTube/releases) do list them now as .pacman, and that is very unheard of in the community. 

I didn't even know at first if this was seriously related to Arch Linux. 

`freetube-0.23.8-1-x86_64.pkg.tar.zst` is how a file should look. 
This is how makepkg creates them, so how do you end up with .pacman?
