### ISSUE TITLE
[Bug]: Behavior changed for middle click window title in gnome

### ISSUE THREAD

**Issue by lonix1** [FreeTubeApp/FreeTube#5923]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I use the mouse middle click (on a window's titlebar) to lower the window - so I can easily cycle through open windows. This setting is set via the shell, or the gnome tweaks tool.

That changed after upgrading to gnome 46. It doesn't honor that gnome setting anymore. So a middle click on the titlebar does nothing.

### Expected Behavior

Middle click to work.

### Issue Labels

feature stopped working, usability issue

### FreeTube Version

v0.21.3 Beta

### Operating System Version

linux ubuntu 24.04

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
So you are saying that a Gnome feature broke after a Gnome update. Why are you opening a bug report on the FreeTube repo?

**Comment by absidue** [comment]
Can you please test various other apps, specifically Chromium and see if that has the same problem, if the answer is yes then it is a Chromium problem and nothing that we on the FreeTube side can do about it.

This still very mich sounds like a Gnome problem and not a Chromium or Electron app problem, considering that that is a Gnome feature and nothing to do with FreeTube and it was caused by updating Gnome.
