### ISSUE TITLE
[Bug]: Unable to play Member-only videos

### ISSUE THREAD

**Issue by kvhjdffv** [FreeTubeApp/FreeTube#5934]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Paste the direct URL of any Member-only video
2. The video won't play

### Expected Behavior

The app should be able to play Member-only videos

### Issue Labels

API issue, content not loading, inconsistent behavior, usability issue

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 10 22H2 (OS Build 19045 . 5011)

### Installation Method

.apk (Alpine Linux Package)

### Primary API used

Local API

### Additional Information

![2024-10-25 13_37_53-Subscriptions - FreeTube](https://github.com/user-attachments/assets/e58e2c14-cc83-4426-8571-3d5d58233522)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
FreeTube is the same experience as YouTube in a logged out state. We cant show member only content as that requires an account
