### ISSUE TITLE
Ability to sort through comments. 

### ISSUE THREAD

**Issue by Aryamik** [FreeTubeApp/FreeTube#594]
Currently, when a user clicks 'Click to view comments', the comments are sorted by 'Newest First'. It would be nice to have a feature where a user can also sort through the top rated comments on a video. 

![comments](https://user-images.githubusercontent.com/40525852/95062206-4ef2a100-071a-11eb-812c-c53ca0504500.PNG)

On https://invidious.snopyta.org/, the comments are sorted by 'Top Rated' as well.

![Comments2](https://user-images.githubusercontent.com/40525852/95062792-12737500-071b-11eb-87a1-7d3c295aee76.PNG)

**Comment by GilgusMaximus** [comment]
Closing this, as we are currently implementing this. As seen here: https://github.com/FreeTubeApp/FreeTube/projects/3
