### ISSUE TITLE
[Feature Request]: Add support for flag emojis

### ISSUE THREAD

**Issue by kvhjdffv** [FreeTubeApp/FreeTube#5942]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Flag emojis in titles and other places don't seem to load. They just appear as the text. Make them appear as emojis.

### Proposed Solution

Add flag emojis so that they will replace the text.

### Alternatives Considered

None

### Issue Labels

ease of use improvement, new feature, new optional setting, visual improvement

### Additional Information

![2024-10-26 12_46_44-Honest Government Ad _ Democracy™  Blocked in 🇮🇳  - FreeTube](https://github.com/user-attachments/assets/418538c5-f5c1-46b5-b2e6-84e6be0b94b8)

**Comment by absidue** [comment]
FreeTube uses your operating system's emoji font, so it is likely that your are using an operating system with an emoji font that doesn't support flags such as Windows 10.

**Comment by kvhjdffv** [comment]
Yes, i am using Windows 10.

**Comment by absidue** [comment]
In that case it's because the emoji font in Windows 10 doesn't have images for the flags and shows the letters instead.
