### ISSUE TITLE
[Feature Request] Make a TV/PS5/NS etc. version of freetube

### ISSUE THREAD

**Issue by NikNikovsky** [FreeTubeApp/FreeTube#5946]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The ad breaks are insane (60 seconds sometimes)

### Proposed Solution

Port it over to android tv and some consoles 

### Alternatives Considered

Provide a way to access Individous on them where possible 

### Issue Labels

ease of use improvement, new feature

### Additional Information

I'll add a photo when I encounter an ad break

**Comment by NikNikovsky** [comment]
![IMG_20241026_232610](https://github.com/user-attachments/assets/d0a7f8a5-5701-4e37-9bc8-dd668316ce54)
![IMG_20241026_232616](https://github.com/user-attachments/assets/65ce46b0-feaf-4d7e-b7c7-6e140884f42a)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We wont do ports. People are already using FreeTube on their TV's. Idk how but you can already do it
