### ISSUE TITLE
[Feature Request] Make ESR versions for older systems

### ISSUE THREAD

**Issue by NikNikovsky** [FreeTubeApp/FreeTube#5947]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

People stuck with windows 7 or high sierra have to watch ads 

### Proposed Solution

Compile the same code with an older version of Electron

### Alternatives Considered

Maybe add some of the bug fixes to the old versions to make them work?

### Issue Labels

improvement to existing feature

### Additional Information

You could do something similar to [this](https://github.com/IzK-ArcOS/v5/releases/tag/6.0.1) when you make this a thing

**Comment by absidue** [comment]
Please read the comment here on why that won't be happening: https://github.com/FreeTubeApp/FreeTube/discussions/4848#discussioncomment-9013849
That thread also has some options suggested by users on how to keep using FreeTube on Windows 7, although keep in mind that none of those solutions are supported by the FreeTube team.
