### ISSUE TITLE
[Feature Request]: Please remove "Play & Pause" overlay on video while mouse hovering. Version 0.22

### ISSUE THREAD

**Issue by sethkaven88** [FreeTubeApp/FreeTube#5953]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

**Please remove the huge Play and Pause white overlay on the video or disable it on mouse hovering.. if the mouse is inside the video screen it appears, its very annoying specially if you like watching in "Full Window" mode. in version 0.22**

![Screenshot_20241027_110147](https://github.com/user-attachments/assets/278feeea-88b5-4c8c-9f73-38c5f0277683)

![Screenshot_20241027_105534](https://github.com/user-attachments/assets/a666ad5b-2a5c-4c10-8b13-e933265baf07)

### Proposed Solution

Remove the overlay or disable it appearing while mouse hover only while clicking. 

### Alternatives Considered

none

### Issue Labels

improvement to existing feature

**Comment by NeverLoseHope777** [comment]
Oh no, please, I beg you, remove it! Or give us a way to remove it in the settings. This is so outrageously annoying.
