### ISSUE TITLE
[Feature Request]: Bring back the notification about the playback speed.

### ISSUE THREAD

**Issue by Giger22** [FreeTubeApp/FreeTube#5957]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Before the 0.22.0 update, the player displayed the playback rate on the video player whenever it was changed.

### Proposed Solution

A notification box should appear on the video player whenever the playback speed is changed.

### Alternatives Considered

n/a

### Issue Labels

display more information to user, new feature, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We are doing the same as YouTube here. Why? Most people that are using FreeTube are coming from YouTube. YouTube users have defined mental modal and we are following that to make FreeTube easier to understand/use. 

There also no benefit in seeing the current playback speed all the time. 

If you hover on the icon you can see the current playback speed.

**Comment by Giger22** [comment]
That was incredibly useful when changing the playback speed... Also a downgrade from previous version...

**Comment by 12people** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 

There is benefit to seeing the playback speed, though. As a person who tends to switch between playback speeds (I often use 2x for news, but 1x for music, and sometimes 1.5x or 1.25x for more dense informational material), it has happened to me on Youtube that, on multiple occasions, a bit of e.g. new music sounds funny to me only to find out that the speed is different than intended. Having this info displayed in FreeTube always made me aware of the currently set speed.

UX-wise, "Visibility of System Status" is Jacob Nielsen's [first usability heuristic](https://www.nngroup.com/articles/ten-usability-heuristics/), so I would say it's worth reexamining.

And it's not like the bottom bar is distracting, given that it only appears temporarily, when the user deliberately wants to know the playback state or change settings.

And as far as mental models go, while speed is in a cog menu on desktop Youtube, after clicking on that cog menu, the playback speed is presented with not just an icon and its label, but also a clear label with the currently set speed. Unless FreeTube wants to hide all the options away under one cog menu button, then using a short label with the current speed should be just as familiar to Youtube users as the playback icon. (I would argue perhaps moreso, as I find "1x", "2x", "1.5x" to be much more clearly descriptive of speed than a play button within a circle whose left half is dashed. I honestly had to search for a bit with the new FreeTube version before I realized that this icon represents speed.)

**Comment by kommunarr** [comment]
I created an issue related to this on the video player repo itself (https://github.com/shaka-project/shaka-player/issues/7444), as modifying the base behavior in FreeTube for this player button would present a maintainability risk.

**Comment by CEHitchens** [comment]
I do agree that having the playback speed being displayed, at least on the player's interface bar, the one at the bottom of the video, IS useful and adds value.
