### ISSUE TITLE
[BUG]: Freetube freezes before playing video.

### ISSUE THREAD

**Issue by 4yman-0** [FreeTubeApp/FreeTube#5971]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to [this video](https://www.youtube.com/watch?v=mXCx50yaseA).
2. Freetube freezes. UI does not work and renderer process uses lots of CPU.

### Expected Behavior

Show an error message/toast.

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Debian GNU/Linux 12 "Bookworm"

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.3 Beta

#### Console log starts with:
```
GET https://SOMETHING.googlevideo.com/videoplayback?expire=1730074672&e…wySmuLHjqiSFmHg2S5wzgCIQD1PXrqjXr2e97zDc44dcChhkhKd7YRnZZJQaOIgkfEEg%3D%3D 403 (Forbidden)
renderer.js:2 Player Error (category and code explainations here: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html)
Video ID: "SOMETHING"
FreeTube player context: "shaka error handler"
```

#### Then these error repeat over and over causing a UI/renderer freeze
```
renderer.js:2 Player Error (category and code explainations here: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html)
Video ID: "SOMETHING"
FreeTube player context: "loading dash/audio manifest and setting default quality in mounted"

Severity: CRITICAL (2)
Category: PLAYER (7)
Code: LOAD_INTERRUPTED (7000)
Stack trace:
Error: Shaka Error 7000
    at new Ae (app://bundle/renderer.js:2:26185)
    at P.h (app://bundle/renderer.js:2:272568)
    at A (app://bundle/renderer.js:2:5174)
    at L.next (app://bundle/renderer.js:2:5468)
    at t (app://bundle/renderer.js:2:5848)
renderer.js:2 Unable to play DASH formats. Reverting to legacy formats...
renderer.js:2 Player Error (category and code explainations here: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html)
Video ID: "SOMETHING"
FreeTube player context: "loading dash/audio manifest and setting default quality in mounted"

Severity: CRITICAL (2)
Category: PLAYER (7)
Code: LOAD_INTERRUPTED (7000)
Stack trace:
Error: Shaka Error 7000
    at new Ae (app://bundle/renderer.js:2:26185)
    at P.h (app://bundle/renderer.js:2:272568)
    at A (app://bundle/renderer.js:2:5174)
    at L.next (app://bundle/renderer.js:2:5468)
    at t (app://bundle/renderer.js:2:5848)
renderer.js:2 Unable to play legacy formats. Reverting to audio formats...
renderer.js:2 Player Error (category and code explainations here: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html)
Video ID: "SOMETHING"
FreeTube player context: "setLegacyFormat"

Severity: CRITICAL (2)
Category: PLAYER (7)
Code: LOAD_INTERRUPTED (7000)
Stack trace:
Error: Shaka Error 7000
    at new Ae (app://bundle/renderer.js:2:26185)
    at P.h (app://bundle/renderer.js:2:272568)
    at A (app://bundle/renderer.js:2:5174)
    at L.next (app://bundle/renderer.js:2:5468)
    at app://bundle/renderer.js:2:6003
    at new Promise (<anonymous>)
    at app://bundle/renderer.js:2:5895
    at D (app://bundle/renderer.js:2:6014)
    at o (app://bundle/renderer.js:2:272487)
    at P.h (app://bundle/renderer.js:2:272694) 
```

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
FT doesnt freeze for me when navigating to that video. Do you maybe have other steps to reproduce this?

**Comment by 4yman-0** [comment]
I played the same video and the freezing disappreared somehow.

Thank you

**Comment by cocoonkid** [comment]
Same issue today on this video https://youtu.be/fC6CFSN9BPI
All others work. In Browser works too.
Had the same with a dozen or so videos from a conf last week.
This week they all work.

Some mystery shit going on here.

![image](https://github.com/user-attachments/assets/47797ecb-f26e-4715-b0ff-85d3c26cf4b3)
