### ISSUE TITLE
[Bug]: Unable to update to v0.22.0 on Manjaro

### ISSUE THREAD

**Issue by Zakanuva** [FreeTubeApp/FreeTube#5972]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Opened "Add/Remove Software" (OS's default GUI package manager)
2. Clicked on "Updates" tab and waited for updates to be checked
3. Clicked the "Apply" button to begin update process, verified packages to upgrade, and entered security PIN

Results displayed by package manager's back-end:
```
Preparing...
Synchronizing package databases...

Failed to synchronize AUR database
Cloning freetube build files...
Generating freetube information...
Checking freetube dependencies...
Warning: python-inputs: local (0.5.0-1) is newer than extra (0.5-6)
Resolving dependencies...
Checking inter-conflicts...

Building freetube...
==> Making package: freetube 0.22.0-1 (Sun 27 Oct 2024 11:37:21 AM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found v0.22.0-beta.tar.gz
  -> Found freetube.desktop
  -> Found freetube.sh
==> Validating source files with sha256sums...
    v0.22.0-beta.tar.gz ... Passed
    freetube.desktop ... Passed
    freetube.sh ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting v0.22.0-beta.tar.gz with bsdtar
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
error minimatch@10.0.1: The engine "node" is incompatible with this module. Expected version "20 || >=22". Got "18.20.4"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...
```

### Expected Behavior

Freetube updates from v0.21.3-1 to v0.22.0-1 without issue

### Issue Labels

causes crash, usability issue

### FreeTube Version

v0.22.0-1

### Operating System Version

Linux zachary-um700 6.11.2-4-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Oct  8 11:52:01 UTC 2024 x86_64 GNU/Linux

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.3-1

### Additional Information

Package manager's output suggests a problem with Yarn; further investigation found that OS is using Yarn Classic instead of Yarn Modern.

Left "Updates" tab and replaced `yarn` with `yarn-berry`: no issues encountered.

Went back to "Updates" and reattempted update; result was this:
```
Preparing...
Synchronizing package databases...

Failed to synchronize AUR database
Cloning freetube build files...
Generating freetube information...
Checking freetube dependencies...
Warning: python-inputs: local (0.5.0-1) is newer than extra (0.5-6)
Resolving dependencies...
Checking inter-conflicts...

Building freetube...
==> Making package: freetube 0.22.0-1 (Sun 27 Oct 2024 11:54:39 AM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found v0.22.0-beta.tar.gz
  -> Found freetube.desktop
  -> Found freetube.sh
==> Validating source files with sha256sums...
    v0.22.0-beta.tar.gz ... Passed
    freetube.desktop ... Passed
    freetube.sh ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting v0.22.0-beta.tar.gz with bsdtar
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Ambiguous Syntax Error: Cannot find which to pick amongst the following alternatives:

  0. yarn install [--json] [--immutable] [--immutable-cache] [--refresh-lockfile] [--check-cache] [--check-resolutions] [--inline-builds] [--mode #0]
  1. yarn install [--json] [--immutable] [--immutable-cache] [--refresh-lockfile] [--check-cache] [--check-resolutions] [--inline-builds] [--mode #0]

While running --cache-folder /var/tmp/pamac-build-zacharyb/freetube/src/yarn-cache install
==> ERROR: A failure occurred in build().
    Aborting...
```
...How do I fix this?

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Janter1603** [comment]
did you try updating through discover?

**Comment by Zakanuva** [comment]
What is "discover"?

**Comment by absidue** [comment]
@Zakanuva The AUR packages are not maintained by the FreeTube team, so in the future any issue you experience with them should be directed at the AUR package maintainers. Please use one of the official FreeTube installation methods (FreeTube website, the releases page on this GitHub repository and the flatpak) to avoid problems like this in the future.

As you are building FreeTube from the source code you need to make sure your build environment is set up correctly, you need to install a newer version of Node.js, ideally the latest version but the latest version of v20 should be enough but v18 is definitely incompatible.

**Comment by Janter1603** [comment]
> What is "discover"?

it's a kde version of the snap store in gnome
