### ISSUE TITLE
[Bug]: Version 0.22.0 seems on the slow side on MacOS

### ISSUE THREAD

**Issue by rjdg14** [FreeTubeApp/FreeTube#5987]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1: Open FreeTube 0.22.0 on MacOS
2: New windows and offline interface pages (eg: history/settings) seem to load slowly compared with on previous versions of FreeTube.

### Expected Behavior

There should be minimal lag, similar to on 0.21.

### Issue Labels

API issue, usability issue

### FreeTube Version

v0.22.0 Beta

### Operating System Version

macOS Sequoia 15.0.1

### Installation Method

.dmg

### Primary API used

Local API

### Additional Information

I suspect these changes are likely related to the switch in the app's API with this version.

These issues were experienced on a MacBook Air M3 running MacOS Sequoia, the latest version. Considering that the Apple M3 is a decent processor, it seems like the problem is almost certainly related to FreeTube. Has the software been optimised for the ARM architecture that Apple Silicon Macs use or is it only optimised for x86 processors?

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by rjdg14** [comment]
> You can download macOS ARM versions of FreeTube here: https://github.com/PikachuEXE/homebrew-FreeTube/releases

I've just noticed that the version on your website mentions Mac x86. I've got Rosetta installed so it runs on my M3 processor, though perhaps not optimally.

**Comment by absidue** [comment]
The website only mentions binaries built in the FreeTubeApp/FreeTube GitHub repository, if you look at the link I sent you above, you'll notice that it is a repository on one FreeTube maintainer's own account.

**Comment by rjdg14** [comment]
> The website only mentions binaries built in the FreeTubeApp/FreeTube GitHub repository, if you look at the link I sent you above, you'll notice that it is a repository on one FreeTube maintainer's own account.

I've just installed the ARM version of 0.22.0 manually via Homebrew and unlike the DMG version, this time it worked (and does not have the lag issues that the x86 version had), so I feel the issue is closed now.
