### ISSUE TITLE
Make playlist show more than 100 videos

### ISSUE THREAD

**Issue by ModdedGamers** [FreeTubeApp/FreeTube#599]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I want to watch all the videos in a playlist that has 132 videos, but in order to see all the videos, I need to scroll through the youtuber's channel instead of just loading the rest of the playlist.

**Describe the solution you'd like to see implemented**
A way of loading more than 100 videos in playlists.

**Describe alternatives you've considered**
There isn't a way of seeing more than 100 videos in a playlist besides viewing on youtube, but I want to minimize the number of calls I make to youtube. Also just looking through their videos isn't helpful if they don't have a series number attached to the videos, i.e. Let's play 1, let's play 2, etc.

**Screenshots**
Sorry, none.

**Additional context**
I understand this may involve a lot of work, so I understand if I have to do this the annoying way. Thanks!

**Comment by PrestonN** [comment]
This was more of a bug than a feature, as we were getting all of the videos in a playlist however due to an upstream change, we weren't getting them any more.  This has been fixed.

**Comment by ModdedGamers** [comment]
Thanks!
