### ISSUE TITLE
[Bug]: BAD_HTTP_STATUS: 403 YouTube watch session expired. Please reopen this video.

### ISSUE THREAD

**Issue by mooleshacat** [FreeTubeApp/FreeTube#5991]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Using FreeTube connected to invidious.catspeed.cc as the Invidious backend:
1. Select any video to watch
2. Either receive playback, or "BAD_HTTP_STATUS: 403 YouTube watch session expired. Please reopen this video."

### Expected Behavior

- Expected playback / uninterrupted playback
- I would expect FT to attempt the connection maybe 3-5 times before giving the user the error and asking them to reload.

### Issue Labels

content not loading, inconsistent behavior

### FreeTube Version

v0.22.0

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

Tracking this issue on my gitea https://gitea.catspeed.cc/catspeed-cc/invidious/issues/11

One thing I have noticed, is invidious.catspeed.cc player will retry the XHR request when it receives a 403 and while it may take longer, always plays the video

On FreeTube only is where I get this error, and instead of FreeTube retrying again and getting playback, it just shows the error and forces me to re-open the video.

I would expect FT to attempt the connection maybe 3-5 times before giving the user the error and asking them to reload.

This also affects users who are mid-playback and will get a random 403 which then gives the error asking the user to reload the video. I think FT should try the request over 3-5 times before giving the error so playback is not interrupted.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by mooleshacat** [comment]
Please note, this error only occurs with FreeTube.

The invidious web player always retries the XHR request and will eventually get a good response.

**Comment by absidue** [comment]
Okay so it looks like I forgot to add support for extracting the video expiry time for Invidious, as it's not in any of the API response fields, we probably need to take it from the streaming URL instead. That will make it show the correct error message: `[BAD_HTTP_STATUS: 403] Potential causes: IP block or streaming URL deciphering failed`

Are you saying that Invidious instances are now expected to automatically fix their servers in a quick enough time that playback can resume? Previously once they were dead they stayed dead for a while, which is why FreeTube is design to show an error screen when it breaks, because there is no point wasting network requests and the users time if you know it is broken.

**Comment by absidue** [comment]
Just be clear FreeTube shows the error message in response to the Invidious server returning 403s, so yes FreeTube is showing the wrong message but the cause of the problem is the Invidious server.

So to answer my own question based on the information you provided, when an Invidious instance starts returning 403s, the Invidious server is expected to fix itself and start returning usable responses in a short space of time. Guess we need to add another Invidious specific workaround to FreeTube then, fun.

**Comment by absidue** [comment]
We can add a retry loop/ignore errors when using the Invidious API for a while, but we definitely shouldn't do it on the local API because it will just result in YouTube extending the IP block for a longer period of time.

**Comment by mooleshacat** [comment]
Well the 403 error can be caused by numerous things. The 403 error can be because the po_token is invalid (as I suspect in this case) and most instance owners have a method to automatically update the po_token (hence why the 403 is only temporary until tokens refresh)

That is why when the web player retries later it gets a valid response

**Comment by absidue** [comment]
Okay so this issue is two things:
- We need to add support to FreeTube for extracting the expiry date from the streaming URLs.
- We need to add another Invidious specific workaround to FreeTube to make it only show an error message if the error is repeated too many times, but for the local API make it behave normally and show the error as soon as it happens.

**Comment by absidue** [comment]
There are no local API instances, the local API is FreeTube on your computer talking directly to YouTube. FreeTube only uses Invidious if the user explicity configures it to do so.

**Comment by absidue** [comment]
Ah okay so the confusion stems from you thinking that adding `local=true` to an Invidious URL is FreeTube's local API. FreeTube's local API is a completely separate thing in FreeTube where FreeTube makes requests to YouTube's APIs, Invidious is not involved in the local API at all.

**Comment by absidue** [comment]
403s can happen on the local API when deciphering the streaming URLs fails (e.g. in the past when YouTube made changes to their n-parameter stuff), when you are IP blocked or when the streaming URLs expire (after 6 hours).

**Comment by mooleshacat** [comment]
> Ah okay so the confusion stems from you thinking that adding `local=true` to an Invidious URL is FreeTube's local API. FreeTube's local API is a completely separate thing in FreeTube where FreeTube makes requests to YouTube's APIs directly, Invidious is not involved in the local API at all.

```local=true``` means you are proxying video through the invidious server.

The confusion is probably you are expecting the average user to use local API (without an invidious instance) while I kind of expect users will use a public instance (mainly because I run one).

> 403s can happen on the local API when deciphering the streaming URLs fails (e.g. in the past when YouTube made changes to their n-parameter stuff), when you are IP blocked or when the streaming URLs expire (after 6 hours).

So while I've never experienced one myself, it is good to know they do happen from time to time.

**Comment by absidue** [comment]
Yes, I expect most FreeTube users to be using FreeTube's own stuff, because it's the default and especially in recent history with Invidious instances breaking so often most users probably stopped using the Invidious option in FreeTube because the local API usually keeps working even when Invidious instances are broken.

**Comment by mooleshacat** [comment]
> Yes, as a FreeTube dev I expect most FreeTube users to be using FreeTube's own stuff, because it's the default and especially in recent history with Invidious instances breaking so often most users probably stopped using the Invidious option in FreeTube because the local API usually keeps working even when Invidious instances are broken.

Yes, I would expect the average user would use defaults which does not use an invidious backend.

However there are some people who will configure an invidious backend just so they can proxy videos through the instance, so the traffic appears to come from the instance and not the user's home IP (for privacy)

**Comment by absidue** [comment]
I already agreed to it here https://github.com/FreeTubeApp/FreeTube/issues/5991#issuecomment-2442104563 ...

**Comment by mooleshacat** [comment]
> I already agreed to it here [#5991 (comment)](https://github.com/FreeTubeApp/FreeTube/issues/5991#issuecomment-2442104563) ...

Ok let me know if you need more information 👍

**Comment by mooleshacat** [comment]
I was just thinking, maybe F5 to refresh the video would be a better implementation, that leaves it up to the user.

**Comment by CharAznableLoNZ** [comment]
Maybe clicking the error could refresh the page or a refresh button could be added to the top toolbar next to the back and forward buttons.  Or alternatively, if the error is detected the page refreshes automatically.  I use Freetube on my HTPC and do not have any F keys on my remote to refresh the page so I have to use the back and forward buttons to get a refresh.

**Comment by Damus765** [comment]
> I was just thinking, maybe F5 to refresh the video would be a better implementation, that leaves it up to the user.

You can already use `ctrl + r` to refresh the view.

**Comment by LinuxOnTheDesktop** [comment]
Cf. #6136 and also (on the keyboard shortcut) #2822.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@mooleshacat we changed some thing, please test the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds) and check if the issue is resolved

**Comment by Darklesss** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc  I'm not the OP, but I came here searching for a solution to the same problem and the nightly build fixed it, thanks.

**Comment by DownyDawn** [comment]
I tried the latest nightly build 5301 cause of the 403 error and its a big win ! Thanks you guys :D

**Comment by LueKely** [comment]
I have also encountered this bug on linux mint but reinstalling the software from Flatpack seems to be the solution for me

**Comment by aydintb** [comment]
Same error on Arch Linux.

**Comment by robtoll** [comment]
I was having 403 issues and updated to the nightly. It didn't solve the issue immediately. I found that copying the youtbe link, going back, entering the link in the search - doing this once or twice fixes it. After that it works most of the time. Hope you mange to fix it. Great app. Cheers!

**Comment by sdykae** [comment]
Same error today

**Comment by FrenchVillain** [comment]
Same issue today. Uninstalled the app running on v.0.23.0, installed the latest v.0.23.1 (beta) but it didn't fix it. I'm running Mac OS Sequoia 15.3.1 (24D70).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
See #6701

**Comment by adamxberlin** [comment]
Sharing this temporary fix for anyone on macOS (but you can tweak it for win & linux):
[https://github.com/FreeTubeApp/FreeTube/issues/6853#issuecomment-2676106877](https://github.com/FreeTubeApp/FreeTube/issues/6853#issuecomment-2676106877)

**Comment by gurtner-it** [comment]
I also have the issue

**Comment by NicoTheCinderace** [comment]
I just ran into this issue today. I'm on v0.23.12, and it is **still** happening. This comment may be a duplicate, but despite what the update says, I still ran into this issue..
