### ISSUE TITLE
[Bug]: Playback reset

### ISSUE THREAD

**Issue by Flashwalker** [FreeTubeApp/FreeTube#5992]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Use **tor** proxy on v.0.22.0 Beta
2. Play the video for the 10+ min

I'm runing **Freetube** Appimage (the .deb package is also affected) via **tor** proxy.
Playback is interrupted every few minutes and the playback progress returns to the beginning and stops.
As far as I know, **tor** rebuilds the proxy chain every 10 minutes.

I didn't have this problem in **v.0.21.2**.

### Expected Behavior

Continuous playback  
Keep playback position

### Issue Labels

content not loading

### FreeTube Version

v.0.22.0 Beta

### Operating System Version

Ubuntu 24.04

### Installation Method

.AppImage

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v.0.21.2

### Additional Information

```
Error: ENOENT: no such file or directory, open '/home/user/.config/FreeTube/player_cache/576f07ca'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1242:14)
    at async /run/firejail/appimage/resources/app.asar/dist/main.js:2:105760
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:86160) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/user/.config/FreeTube/player_cache/576f07ca'
}
```

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Could you please provide screenshots or screen recordings of what is happening? Please also provide logs from the devtools inside the app (<kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>I</kbd>), FreeTube doesn't log to the command line.

**Comment by Flashwalker** [comment]
Hard to catch, it's random.

The actual problem is just that the playback progress goes back to the beginning:
after disconnecting, I press Ctrl+R to reload the page, and previously the playback progress was saved. But now it more often than not starts over again.

**Comment by kLabz** [comment]
Got the same error, the window seemingly freezes but is actually in an error loop
![image](https://github.com/user-attachments/assets/5a11261f-b0b0-4933-a2f7-a3718c8ef713)
![image](https://github.com/user-attachments/assets/f3976237-b944-4047-bd01-1ba00dce8e59)

I can repro anytime, if there's something you need me to try.
`freetube-0.22.0-2` (installed via AUR)

And I'm getting the same error in terminal:
```
Error: ENOENT: no such file or directory, open '/home/user/.config/FreeTube/player_cache/3bb1f723'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1242:14)
    at async /usr/lib/freetube/app.asar/dist/main.js:2:105760
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:86160) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/user/.config/FreeTube/player_cache/3bb1f723'
}
```

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@kLabz see https://github.com/FreeTubeApp/FreeTube/issues/6334#issuecomment-2529906778

**Comment by kLabz** [comment]
Oh ok, thanks! Was following that other issue too :sweat_smile:
