### ISSUE TITLE
[Feature Request]: Scroll over Playback speed and Resolution to change settings.

### ISSUE THREAD

**Issue by Vinnyboiler** [FreeTubeApp/FreeTube#5999]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Changing Resolution and Playback Speed is currently only restricted a three step process where you locate the button, press it to access a context menu (which partially obscures the video) and select the option. 

### Proposed Solution

An option for scrolling over Resolution and Playback Speed to change settings would be appreciated. 

### Alternatives Considered

Perhaps a middle mouse button (mouse 3) click to change Resolution and Playback Speed could instead be considered though I don't think it's as intuitive as scrolling.

### Issue Labels

ease of use improvement

### Additional Information

The code is already implemented for the volume bar so I'm asking for it to be expanded to the other options.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
See, Player settings -> Scroll Playback Rate Over Video Player
