### ISSUE TITLE
Accounts without listed subscribers display as 0 subscribers

### ISSUE THREAD

**Issue by tayloraviets** [FreeTubeApp/FreeTube#600]
**Important note**
Please check other open and closed issues for a similar bug before reporting a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Behavior of the program**
When an account hides its subscriber count (typically seen on streaming accounts) the subscriber count is listed as 0.

**Expected behavior**
No subscriber count should be shown. This is what happens on the youtube UI 

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Search for "stocks rocks" in the search bar
2. Click on the "stocks rocks" channel
3. Observe "0 Subscribers"

**Screenshots**
Image from FreeTube:
![image](https://user-images.githubusercontent.com/14251231/95149402-d0b2f080-0753-11eb-87a6-adf662a36ab0.png)
Image from YouTube in browser:
![image](https://user-images.githubusercontent.com/14251231/95149438-f04a1900-0753-11eb-82f7-fb2879e0c292.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - OS Version: 10.0.18362 Build 18362
 - FreeTube version: Development

**Additional context**

**Comment by PrestonN** [comment]
I've hidden this value if nothing is returned.  Should be fixed now.
