### ISSUE TITLE
[Bug]: Going backward/forward in a video doesn't go where it should

### ISSUE THREAD

**Issue by awsms** [FreeTubeApp/FreeTube#6004]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I first encountered this issue with a version compiled from the latest commit, then successfully reproduced it with the latest beta build (0.22.0).

1. Launch a video in PiP mode
2. Use an external command to go backward/forward in the video (for example, `playerctl --player playerctld position 5+`)
3. Instead of going +/- x seconds from the current playback instant, it will go from the latest time the video was paused

### Expected Behavior

I'm expecting the video playback to go at +/- x seconds from its current progression.

### Issue Labels

inconsistent behavior

### FreeTube Version

0.22.0

### Operating System Version

EndeavourOS

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Additional Information

I can not 100% reproduce this issue, instead it happens 3 out of 4 times.
This issue never occurred before, happened for the first time ~ a week ago.
Reproduced in the AppImage official release, the AUR bin package, and the AUR git package.
To "reset" the timestamp, I have to alt-tab in FreeTube again.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
I'm able to successfully seek to the correct spot on Windows 10 using ModernFlyouts and as you didn't fill in the last known working version, it sounds like this is possibly an issue with the external tool that you are using, not FreeTube itself.
