### ISSUE TITLE
Autoplay setting persists when recommended videos are hidden

### ISSUE THREAD

**Issue by tayloraviets** [FreeTubeApp/FreeTube#601]
**Important note**
Please check other open and closed issues for a similar bug before reporting a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Behavior of the program**
If autoplay is enabled before recommended videos are hidden the next video will autoplay despite not being visible

**Expected behavior**
The next video is not played in this situation.
Not sure if expected behavior should be autoplay is set to autoplay false or if the setting just doesn't do anything while recommended videos are hidden.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Turn on Autoplay toggle
2. Turn on Hide Recommended Videos in distraction free settings
3. Go to any video and allow the video to finish
4. Observe next video autoplays

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - OS Version: 10.0.18362 Build 18362
 - FreeTube version: Development with Distraction Free Settings

**Additional context**
per prestonN "We could probably just display a message that tells the user that the autoplay next video is disabled if they decide to also disable viewing the video recommendations"

**Comment by PrestonN** [comment]
This has been completed.
