### ISSUE TITLE
[Bug]: utility and gpu process occasionally stay open after main process has been terminated

### ISSUE THREAD

**Issue by Kazcade** [FreeTubeApp/FreeTube#6016]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Preface: I am using the newest version (0.22) of freetube with an [electron fork based on supermium](https://github.com/win32ss/supermium-electron), for backwards compatibility. I have only encountered this bug with the newest version, not with prior versions (<= 0.21).

Occasionally after I exit freetube, the gpu and the utility subprocess will stay active for ~5-10 seconds after I close freetube, which in turn leads to an exception being thrown when I try to launch freetube again while those processes are still active. Is there any reason the recent change should prevent -type=gpu-process or -type=utility from terminating together with the renderer?

Checking other reports this might be related to #4762 and #5553, but I only encountered the bug after upgrading to 0.22, not with prior versions.

Addendum:

Something is screwy with whatever is used to fetch the feed/update subscriptions. Disabling "Fetch feed automatically" prevents the bug from happening, at least for me. 

_Caveat: this only applies **after** a restart, not while the application is still running_

Switching feed updates to RSS ameliorates this somewhat, but it doesn't fix it. I have also enountered the bug less frequently or not at all when reducing subscriptions to less ~70 (my actual channel count is 114). Can whoever is experiencing #4762 and #5553 check if they can reproduce this behaviour (i.e. disabling automatic feed updates) prevents this from happening _after restarting the application_?

### Expected Behavior

All subprocesses should terminate correctly and promptly after freetube is exited.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Windows 7 64-bit

### Installation Method

.zip

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.21 Beta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
As stated in the README we only support Windows 10+. Unless you can reproduce this with the official Electron release that FreeTube 0.22.0 uses (Electron 32) and a supported operating system and version we won't be able to help you.
