### ISSUE TITLE
[Bug]: Local API error (/player HTTP 429)

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#6020]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When i click on a video, i have this
`Error: Request to https://www.youtube.com/youtubei/v1/player?prettyPrint=false&alt=json failed with status 429`
Then it goes back to the invidious API, but the video is showed as "unavailable" ("uploaded" jan 1 1970, 0 views, duration 0:00, can't be played).

### Expected Behavior

Video is playing normally

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.22.0 Bêta

### Operating System Version

ubuntu

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.22.0 Bêta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Do you still face this issue?
