### ISSUE TITLE
[Bug]: Default Quality is ignored

### ISSUE THREAD

**Issue by m3thm4th** [FreeTubeApp/FreeTube#6023]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. In Player settings set Default Video Format to Legacy and Default Quality to anything,
2. Open a video
3. Switch to DASH Format
4. The video plays at the same resolution as the legacy video being played moments before

### Expected Behavior

The video should play at the resolution specified in settings. This bug was not present in previous versions than 0.22.0

### Issue Labels

feature stopped working

### FreeTube Version

v0.22.0

### Operating System Version

Debian 12

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.0

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
That is entirely expected YouTube only provides one legacy stream which is 360p. If you want to other qualities switch to DASH.

**Comment by absidue** [comment]
That it working correctly too, defaults are only applied when the player starts. In previous releases switching formats would reset the entire player, which not only caused the UI to glitch but also meant that it forgot all of the current player settings. Now when you switch formats it remembers your playback position, selected subtitle track, selected audio track and selected quality. So yes if you had 360p selected with the legacy formats it will retain your quality selection when you switch to the DASH formats and play 360p.
