### ISSUE TITLE
Open the menu of player buttons on top of the buttons

### ISSUE THREAD

**Issue by NomadVibes88** [FreeTubeApp/FreeTube#6035]
### Guidelines

- [x] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When clicking on a player button, the menu doesn’t open directly above it; instead, it opens slightly to the side.
![2024-10-30 14_48_22-Breaking the Windows Clipboard - FreeTube](https://github.com/user-attachments/assets/44ffed89-98f7-4c3e-8a54-1dc23bbcd7de)

### Proposed Solution

 I would like the menu to appear directly above the button.

### Alternatives Considered

None

### Issue Labels

ease of use improvement, improvement to existing feature, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Addressed by https://github.com/FreeTubeApp/FreeTube/pull/6007
