### ISSUE TITLE
[Bug]: Videos with multi language audio tracks do not default to the _original_ audio

### ISSUE THREAD

**Issue by k0zyrev** [FreeTubeApp/FreeTube#6044]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When a video contains multiple language tracks, it starts playing whatever it has first in the list 

1. Go to a video with multiple language tracks (https://youtu.be/-aeFekbm3Nc)
2. it starts playing in German, while the original language is English

### Expected Behavior

When videos have option for normalised audio tracks, they default to the original track as uploaded by the author. I would expect the multilanguage audio track to also use the original language track by default.

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

0.22 ee68ef4

### Operating System Version

win10

### Installation Method

Portable

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Already solved by #5943 and #5996

**Comment by k0zyrev** [comment]
@absidue  I'm having the issue with the [latest nightly build ](https://github.com/FreeTubeApp/FreeTube/actions/runs/11597107778) which supposedly includes the fixes you've linked.

I'm also only testing it with local api, so the invidious thing isn't relevant, and from the changelog of https://github.com/FreeTubeApp/FreeTube/pull/5996 I can only see

> Support auto-dubbed audio tracks ([#786](https://redirect.github.com/LuanRT/YouTube.js/issues/786)) ([a4ef224](https://github.com/LuanRT/YouTube.js/commit/a4ef2249ffbe14f5d5fa702b269dd0f61e14ada8))

Yes, I see that audio tracks are supported, but **it's playing the wrong track by default**.
