### ISSUE TITLE
[Bug]: "Default quality" and "Resolution" menu are not consistent for ultra-wide (21:9) videos

### ISSUE THREAD

**Issue by chiak597** [FreeTubeApp/FreeTube#6045]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Set "default quality" to 1080p
2. Open an ultra-wide video (21:9), for example https://youtu.be/mlHklH5VBtI
3. Click the "Resolution" button -> 1440p resolution is selected
4. Press "d" -> Resolution is 2560x1066. That is ultra-wide 1080p.

### Expected Behavior

2560x1080 (x1070, x1066) marked as 1080p in the Resolution menu, not 1440p.

### Issue Labels

visual bug

### FreeTube Version

v0.22.0

### Operating System Version

Debian Unstable

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This behaves exactly the same on YouTube, so I think it's probably fair to say that this is working as expected.
