### ISSUE TITLE
[Bug]: 0.22.0 Beta doesn't see VPN

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#6047]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Earlier today I tested the FreeTube 0.22.0 Beta. I use a VPN and was able to use it no problem.

Fast forward to this evening and 0.22.0 Beta doesn't see the VPN anymore and insists on connecting through my router/non-VPN connection, resulting in me not being able to use it anymore.

I've restarted my PC to see if it was a temporary bug but nope, 0.22.0 Beta still insists on connecting outside of the VPN/doesn't see the VPN anymore.

Also tried just redownloading the Beta but same result.

Any idea on how to fix this? Thanks :smile:

### Expected Behavior

FreeTube should connect through the VPN.

### Issue Labels

content not loading, feature stopped working, inconsistent behavior, usability issue

### FreeTube Version

0.22.0 Beta

### Operating System Version

Windows 10 21H2

### Installation Method

Portable

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.21.3 Beta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> still insists on connecting outside of the VPN

How does the application show this to you?
