### ISSUE TITLE
Pause without interference

### ISSUE THREAD

**Issue by GS88088** [FreeTubeApp/FreeTube#6051]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

It is extremely necessary to observe the entire area of the screen during a pause

### Proposed Solution

Add an option to settings - hide the interface during a pause

### Alternatives Considered

I didn't find any

### Issue Labels

ease of use improvement, new feature, new optional setting, visual improvement

**Comment by absidue** [comment]
Duplicate of #6050
