### ISSUE TITLE
[Feature Request]: Export data (subs, history and playlists) using powershell.

### ISSUE THREAD

**Issue by skossan** [FreeTubeApp/FreeTube#6056]
### Guidelines

- [x] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

My main problem is that I find it hard to stay up to date with my data on all of my devices. Work desktop, work laptop, personal desktop, phones etc etc.

### Proposed Solution

If we were able to export data using powershell I could easily code together a script that I can run with the click of a shortcut that will export all the data I need to a remote cloud location of my choice.

When that's done I can easily import the data on any device I want from the remote location.

I'm also able to backup my data as well which is great!

### Alternatives Considered

An alternative solution could be to build a sync feature right into the app but I think it would require more time and investment!

### Issue Labels

new feature

### Additional Information
I wanna be clear that this can all be done manually at present and the purpose of this is to be able to automate the process!

_No response_

**Comment by Tech-How** [comment]
I actually do this by using my computers syncing software, Syncthing, but you could also use something like MEGA or Insync or Dropbox, and then select the database files that FreeTube stores this data in. Then those files are synced across my devices. On Windows they are stored in %AppData%, and on Linux it depends on your distro and installation method. For Flatpak it's in ~/.var/app.

**Comment by absidue** [comment]
That page lists the directories for each operating system and which files are relevant: https://docs.freetubeapp.io/usage/data-location/

Just keep in mind that while FreeTube is running it assumes that it is the only program using the files, so avoid reading or writing to the file while FreeTube is running if you want to avoid data loss.
