### ISSUE TITLE
Optionally show a different profile instead of "All Channels" when adding channels to a new profile.

### ISSUE THREAD

**Issue by PrestonN** [FreeTubeApp/FreeTube#606]
**Describe the solution you'd like to see implemented**
When adding channels to a new profile, it has been suggested to know which channels are present in another profile.  My suggested solution to this is to have a drop down where the user can select which profile they'd like to display and filters / additions would be based off of that instead of the "All Channels" profile.

**Additional context**
This could potentially be a good first issue for new contributors.  The `ft-select` component can be used to handle the dropdown of profiles that will be selected.  Once selected, the shown list of profiles would then be updated to show only the channels from that profile, while still filtering out any channels that are already included in the profile you are currently editing.  I likely won't be working on this right away so someone else is free to grab this is they'd like.  I'm also available if you have any questions.

**Comment by alphabet-codes** [comment]
@PrestonN I'd love to pick up this issue if you don't mind

**Comment by PrestonN** [comment]
Feel free to do so.  I will review your PR once it's ready, please let me know if you have any questions while working on this.

**Comment by alphabet-codes** [comment]
@PrestonN i noticed the code was writing in vue, and I'm not familiar with vue yet. So i was wondering if i learn how to use vue then i can contribute. Or what do you think?

**Comment by lambdaclan** [comment]
Hello @PrestonN first of all I would like to thank you for your work on this project. I have been using it for quite some time and decided to start helping out a bit.

I would like to resume work on this ticket if that is OK.

Here is a quick demonstration of the current WIP (feedback is welcome of course):

https://user-images.githubusercontent.com/47409392/106234192-3427c900-61f0-11eb-8c2d-ed211c216bdb.mp4

I have some questions regarding the implementation details:

1. Where do you think the change should take place? Directly in the `ProfleEdit` component or? I started down that path but then changed my mind and created a new component based on the `FtProfileAllChannelsList` and named it `FtProfileFilterChannelsList` that adds an `ft-select` component to the template as you specify above. Not sure if that is considered duplication but will be happy to amend it if necessary.
2. Regarding the filtering options. The active profile and the profile being edited can be different as you know so should the filter also include the name of the profile being edited or?
3. I will need some information regarding the appearance/position of the widget.
4. I guess there might be more intricacies in the implementation details such as using computed, data or watch etc but we can discuss those during the PR.

Note: there is a bug that the channel added is still being shown until next dropdown change. I realized that during the demo. I will take care of it.

There are probably more things to discuss but this should be enough to get me started.

**Comment by PrestonN** [comment]
Hello @lambdaclan, I appreciate you taking the time to work on this feature. The demo in your post is looking really good! As for the questions you asked:

1. What you did was correct. I'd rather have the functionality in it's own component similar to how it is now instead of adding the functionality directly to `ProfileEdit`. Renaming the component makes sense as well since the functionality is a bit different. Judging by your video, it looks like `FtProfileAllChannelsList` isn't being used any more so we'll just need to make sure this component is deleted in the PR.
2. I think it's fine without it. The user more than likely knows which profile is being edited so we likely don't need to put the name here. I'd be open to adding the name to `FtProfileEdit` if we felt it was needed however.
3. The position looks fine. It may be worth seeing how it looks having the dropdown and "$ selected" text be centered instead of on the side like that. You can do this fairly easily by using `FtFlexBox` though it may need some slight configuration as by default it will show both on the same line (may look better that way but not sure). We can talk about this more during the PR if you'd like.
4. The only major thing I can think of is making sure you include the new locales so that they can be changed for translations. You only need to add them to en_US so that the translation software can pick it up.

Besides the one minor bug you mentioned, everything looks pretty good. If you have any trouble getting that last part fixed feel free to go ahead and start your PR and I can help look into it.

Let me know if you have any more questions.
