### ISSUE TITLE
60fps 

### ISSUE THREAD

**Issue by baraa272** [FreeTubeApp/FreeTube#607]
**Important note**
Please check other open and closed issues for a similar bug before reporting a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Behavior of the program**
Please write a clear and concise description of what the bug is.
leaving the program to its default settings 
**Expected behavior**
Please describe clear and concise what you expected to happen.
show at least 720p60fps option in quality chooser

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.

**Desktop (please complete the following information):**
 - OS: win10
 - OS Version: 1809
 - FreeTube version: 0.8 beta

**Additional context**
60fps isnt here at all even though i checked some videos with 60fps on youtube still freetube wont show option for 60 fps while using DASH formats NEITHER legacy formats

**Comment by PrestonN** [comment]
60fps videos _do_ get played properly, however it won't explicitly say that you're watching in 60fps.  If a video has 60fps available, it will always play instead of the 30fps option.  This is an upstream issue and can't be fixed on our end.  If the fix ever gets made upstream then I will happily update to make it available.

**Comment by baraa272** [comment]
ok guess i'll close the issue lel

**Comment by baraa272** [comment]
i have a question though , will you implement at least codec choice ? like mp4 OR WEBM

**Comment by PrestonN** [comment]
This is also an upstream issue.  We're already including both mp4 and webm in our DASH files but we have no way to differentiate them with our current setup.  It's also why we can't offer qualities higher than 1080p.  I believe there's an open issue for it over in the other repository but I can't give an ETA on if or when they work on it.
