### ISSUE TITLE
[Bug]: When Screensaver Activates, App Freezes and Not Responding Until Force Closed

### ISSUE THREAD

**Issue by KPCOFGS** [FreeTubeApp/FreeTube#6074]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When screensaver activates and turning the computer back on, the whole app freezes, CPU usage suddenly surge, and the app is not responding. What is weird is when I used the nightly build, [10737752218](https://github.com/FreeTubeApp/FreeTube/actions/runs/10737752218), this was not the problem.

### Expected Behavior

No freeze

### Issue Labels

causes crash, content not loading, feature stopped working

### FreeTube Version

v0.22.0

### Operating System Version

Linux Mint Debian Edition 6

### Installation Method

.zip

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

Build [10737752218](https://github.com/FreeTubeApp/FreeTube/actions/runs/10737752218)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@KPCOFGS please try the latest nightly build and check if the problem is resolved

**Comment by KPCOFGS** [comment]
Hi! The issue has been resolved. Thank you very much!
