### ISSUE TITLE
[Feature Request]: undo remove channel

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [FreeTubeApp/FreeTube#6077]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I deleted a channel accidentally - I clicked the big red button, thinking it would list that channel's videos - and there is no undo feature (so far as I can see). I had trouble remembering the name of the channel - and FreeTube, for all its merits, seems to lack a predictive search feature. So I was in trouble. Eventually, by searching the web, I found the channel again.

### Proposed Solution

An undo function, perhaps with one trigger being ctrl-Z, for that action and perhaps also for other actions; cf. #5421, #4386.

### Alternatives Considered

There is, admittedly, the option to enable watching history. Had I had that enabled, it would have solved my problem.

### Issue Labels

ease of use improvement, new keyboard shortcut

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Settings -> Subscription -> Confirm Before Unsubscribing should cover this usecase

**Comment by LinuxOnTheDesktop** [comment]
> Settings -> Subscription -> Confirm Before Unsubscribing should cover this usecase

Indeed. My mistake. Thank you.
