### ISSUE TITLE
[Bug]: When i refresh freetube window, audio raise to maximum value

### ISSUE THREAD

**Issue by onlineapps-cloud** [FreeTubeApp/FreeTube#6078]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When i refresh freetube window, audio raise to maximum value, but when i going back or forward to main page audio stay with previous state.
1. Refresh page (ctrl+r)
2. Audio raise to maximum

### Expected Behavior

audio stay to previous state

### Issue Labels

usability issue

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Linux (debian 11)

### Installation Method

.AppImage

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This sounds like it is working as expected, refreshing the window is the same as restarting the app, so it is understandable that it will reset it back to the default value that you have configured in the settings. We always tell people to not refresh the window, but they still do it and then are surprised when it breaks stuff.

**Comment by absidue** [comment]
Because you have the watch history turned on so it is loading your watch progress from the watch history on the file system.

**Comment by absidue** [comment]
When you restart the app it loads the default configured volume in the settings, if you don't want FreeTube to start with 100% volume, then change the default in your settings.
