### ISSUE TITLE
Add support for android too please

### ISSUE THREAD

**Issue by vikasdigital** [FreeTubeApp/FreeTube#608]
**Important note**
Please check other open and closed issues for a similar feature request before proposing a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Is your feature request related to a usage problem (not a bug)? Please describe.**
Please describe clear and concise of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like to see implemented**
Please give a clear and concise description of what you want to happen.

**Describe alternatives you've considered**
Are there other ways to solve the problem? Please give a clear and concise description of any alternative solutions or features you might have considered.

**Screenshots**
Sometimes people have screenshots from mock-ups or other projects. Add them here.

**Additional context**
Add any other context about the feature request here.

**Comment by GilgusMaximus** [comment]
I'm not too sure this is even possible. Electron has a lot of issues about that stating they won't implement it.
Additionally, we do not want to compete with NewPipe. Therefore I would say that we will not do this in the foreseeable future.
