### ISSUE TITLE
[Feature Request]: Replace "Forcing RSS to avoid rate limiting" info message with a visual cue that RSS is activated (UI improvement)

### ISSUE THREAD

**Issue by cyberwolfie1** [FreeTubeApp/FreeTube#6081]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I have many profiles with tons of different subscriptions. Everytime I open Freetube, I am faced with the information message "This profile has too many subscriptions. Forcing RSS to avoid rate limiting". I find the behavior somewhat annoying, because I know this, and don't need to be reminded about this every day with an information box. I would much rather avoid seeing this, and instead see some kind of visual cue that RSS is active in the subscription feed.

### Proposed Solution

An RSS-icon, or colored box saying "RSS active" or something like this next to or below the "Subscriptions" header would suffice to indicate to the user that RSS is active. The information about RSS being forced could possibly be available as a hover-over tooltip. 

### Alternatives Considered

Could just allow for toggling off these messages instead. 

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
enable this, Settings -> Subscription -> `Fetch Feeds from RSS` so you dont see the message again

**Comment by cyberwolfie1** [comment]
Some added context, as the solution does not solve my issue: I would still like regular subscription fetching to be active for my separate profiles  - I want the information about duration especially, so I don't want to turn that off. But since the All-profile will contain all the subscriptions from all the profiles, it will always exceed the threshold to force RSS-fetching. I am also OK with that, but it is in these situations I would like to be able to turn off the message.

**Comment by kommunarr** [comment]
I do think there is merit to giving the user a choice to not see the same popup that occurs consistently (this one and the recent "this playlist has videos that do not contain a timestamp" one are the top two that come to mind). The problem from an open source perspective is that a non-negligible percentage of users will inevitably opt to block these messages if they have the choice, eventually forget the information being relayed in the popup, and then report spurious issues on our board. This makes this one tough to prioritize.

**Comment by cyberwolfie1** [comment]
> I do think there is merit to giving the user a choice to not see the same popup that occurs consistently (this one and the recent "this playlist has videos that do not contain a timestamp" one are the top two that come to mind). The problem from an open source perspective is that a non-negligible percentage of users will inevitably opt to block these messages if they have the choice, eventually forget the information being relayed in the popup, and then report spurious issues on our board. This makes this one tough to prioritize.

At least for "Forcing RSS to avoid rate limiting", an icon could be shown to indicate this and to remind the user that something has been changed. The icon could also be active if the user has explicitly chosen to, perhaps with a different tooltip saying it is due to a user enabled setting. For the "This playlist has videos that do not contain a timestamp" it is not as obvious how that would be shown, but maybe there could be a more generic "something is wrong"-indicator that shows the details of the specific problem as a tooltip, that could be reused later as well for other issues.

However, it is merely a minor annoyance, and it seems it won't be prioritized.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Some added context, as the solution does not solve my issue: I would still like regular subscription fetching to be active for my separate profiles - I want the information about duration especially, so I don't want to turn that off. But since the All-profile will contain all the subscriptions from all the profiles, it will always exceed the threshold to force RSS-fetching. I am also OK with that, but it is in these situations I would like to be able to turn off the message.

I think the root cause of the minor annoyance has todo with https://github.com/FreeTubeApp/FreeTube/issues/1996. We wouldnt have this convo if this was already implemented

**Comment by cyberwolfie1** [comment]
> > Some added context, as the solution does not solve my issue: I would still like regular subscription fetching to be active for my separate profiles - I want the information about duration especially, so I don't want to turn that off. But since the All-profile will contain all the subscriptions from all the profiles, it will always exceed the threshold to force RSS-fetching. I am also OK with that, but it is in these situations I would like to be able to turn off the message.
> 
> I think the root cause of the minor annoyance has todo with #1996. We wouldnt have this convo if this was already implemented

Yes, separate settings for the All-profile would indeed solve this for me.
