### ISSUE TITLE
[Bug]: Switching profiles does not refresh feed

### ISSUE THREAD

**Issue by Victor239** [FreeTubeApp/FreeTube#6089]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

In Subscription settings I have enabled `Fetch feed automatically`, which says it will automatically fetch when switching profile and when opening a new window. In the current version neither of those seem to work. Opening a new window will however refresh my one `default profile`, as my `Default landing page` is `Subscriptions`.

In the previous version changing profile would refresh that profile, but this would only happen once per profile. This worked well for me because I swap between profiles constantly, I don't need a refresh on every single switch. 

Closing the application and reopening it used to refresh the default profile again and would allow the one-time refresh of each profile again, so I did this every few hours to get a refresh of all profiles with minimal clicks. 

As you can see the behaviour of this setting was quite different from the description in my experience, though I have an idea of a better overall behaviour. 

### Expected Behavior

Switching profiles or opening a new window should refresh fetch the feed again if `Fetch feed automatically` is enabled, but it should also avoid fetching the feed if it's been fetched recently.

This should be a separate setting for how long to wait until fetching feed, as a default set it to 60 minutes. 

### Issue Labels

feature stopped working

### FreeTube Version

v0.22.0 Beta 

### Operating System Version

Kubuntu 24.10

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.0 Beta 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by onegladiator4u** [comment]
same happens to me too.

**Comment by Victor239** [comment]
Still an issue.

**Comment by Brier1104** [comment]
Still an issue in v0.22.1

**Comment by kommunarr** [comment]
The behavior described of showing the cached results is intended. I'd recommend opening a feature request for more finely discussing your preferred solutions. The suggested setting for a configurable "staleness time limit" that is checked when switching profiles or on navigation to the Subscriptions page sounds interesting but definitely has ample room for refinement, discussion, and prioritization.
