### ISSUE TITLE
[Bug]: "Subcriptions" and "Most Popular" are misaligned in the main menu

### ISSUE THREAD

**Issue by DerekTurtleRoe** [FreeTubeApp/FreeTube#6093]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open the latest stable FreeTube release
2. Look at the menu on the left side with the single column of icons, two of the icons have misaligned text

### Expected Behavior

The text below the icons should either be centered or the text should be shortened to be properly aligned.

This happens regardless of theme or other settings in the app.

It should be noted that the other view (which has horizontal text next to the icons) works as intended.

### Issue Labels

text/string issue

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Microsoft Windows 11 Pro, Version 10.0.22631

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

![image_1](https://github.com/user-attachments/assets/d07e1d40-6657-4a1e-8957-882ab6a10b7f)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
If you look closer at your screenshot you'll notice that the text is aligned correctly with their respective icons and that everything: icons, text and divider lines are offset from the right, so that there is space for the scroll bar.

**Comment by DerekTurtleRoe** [comment]
> If you look closer at your screenshot you'll notice that the text is aligned correctly with the icons and that everything: icons, text and divider lines are offset from the right, so that there is space for the scroll bar.

The scrollbar on the other side of the screen, you mean?

**Comment by absidue** [comment]
No, the scroll bar inside the sidebar, that lets you scroll through the icons and your subscriptions.

**Comment by DerekTurtleRoe** [comment]
> No, the scroll bar inside the sidebar, that lets you scroll through the icons and your subscriptions.

Oh, well for the entire time I've used FreeTube I've never gotten a scroll bar on the left side, just the right side. Maybe that is another issue?
