### ISSUE TITLE
[Bug]: "Local API Error TypeError: Failed to fetch" has been stopping me from using the app for the past couple days, specifically after I updated to the most recent version. I can't load any videos or watch anything.

### ISSUE THREAD

**Issue by Responder07** [FreeTubeApp/FreeTube#6096]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Every time I try to load any page, the errors: "Local API Error: TypeError: Failed to Fetch" and "Invidious API Error: TypeError: Failed to Fetch" continuously appear, with a new error message about every second. I thought it might have to do with the new player in the newest version, but it only started give-or-take 6-hours *after* I updated, and worked fine in between me downloading the update and then. I've also tried disconnecting from my VPN and re-installing the app, to no avail.

### Expected Behavior

Pages load without issue.

### Issue Labels

API issue

### FreeTube Version

v.0.22.0

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
Do you have `Settings > Proxy Settings > Enable Tor / Proxy` enabled? If yes, try disabling it.

**Comment by PrivacyFriendlyMuffins** [comment]
I'm having the same thing happen, and I don't have `Enable Tor / Proxy` enabled. I switch to different VPN servers (US to/from and other countries to/from etc) and it keeps giving me that error.

Weird thing is it only started tonight. Earlier around 07:00 UTC it worked without any issue. It has been happening of course, but usually switching to a non-US VPN server fixes the issue, at least temporarily.

---
**Details**:

- FreeTube Version: 0.22.0 Beta
- OS: Windows 10 Home (22H2)

**Comment by Responder07** [comment]
Sorry for the very late reply, the last few days have been real busy lol, but it did work, thanks!

**Comment by Richard-EnglishUK** [comment]
Similar problem for a while. In my case it seems connected to NordVPN. I've made FreeTube an exception, (so not protected) and the problem has gone - for now anyway

**Comment by Zakanuva** [comment]
> Do you have `Settings > Proxy Settings > Enable Tor / Proxy` enabled? If yes, try disabling it.

I've been having similar problems with my build on Manjaro Linux, and when I check these settings, "Enable Tor/Proxy" was already disabled.

**Comment by faxotherapy** [comment]
Still happening for me on macOS. As a sudden, I've got the message “Local API Error (Click to copy): TypeError: Failed to fetch”. What could have possibly happened? Tried FreeTube on my Linux laptop and no problem. macOS seems to be the problematic OS.

**Comment by simon-lucas** [comment]
I'm getting this consistently.  Got build Version 0.22.1 (0.22.1). Mac OS 10.15.7. Proxy setting as desacribed above already disabled

**Comment by T140V** [comment]
> Similar problem for a while, although sometimes it worked fine. In my case it seems connected to NordVPN. I've now made FreeTube an exception, (so not protected) and the problem has gone - for now anyway

I struggled with a similar issue for a long time and nearly gave up on FreeTube, I eventually discovered that using a 'Virtual' connection in NordVPN the issue went away. HTH

**Comment by faxotherapy** [comment]
YouTube denies VPN users, as discusses [here](https://discuss.techlore.tech/t/accessing-youtube-are-the-good-days-behind-us/12057).

**Comment by T140V** [comment]
Thanks for the info. I'm simply passing on what worked for me. I couldn't properly access YouTube either until I used a NordVPN Virtual connection e.g. Andorra or Algeria which worked for directly accessing YouTube (no ads etc.) as well as FreeTube. I much prefer using the functionality of FreeTube which works much better for me.

**Comment by simon-lucas** [comment]
> YouTube denies VPN users, as discussed [here](https://discuss.techlore.tech/t/accessing-youtube-are-the-good-days-behind-us/12057).

I'm not a VPN user, so why wont my Freetube work?
