### ISSUE TITLE
Release 0.2.0 Beta Discussion

### ISSUE THREAD

**Issue by PrestonN** [FreeTubeApp/FreeTube#61]
Hey everyone!

I'd like to start a discussion and get some general feedback on the progress of FreeTube.  If this goes well then I might open one up for every release.

I'm curious as to what the general opinion is on FreeTube at it's current state.  How do you like the frequency of updates?  What features should take priority?  Is there anything that I should be doing better with?  This is my first time managing a project this big so it's very possible that things could be better.  I don't want to assume that everyone is 100% happy with everything because surely that isn't the case.

Let me know what you think.  I'm looking forward to hearing your thoughts. :)

**Comment by aproposnix** [comment]
@PrestonN Thanks for the great release. I did notice with the double clicking, it fullscreens it but doesn't "un-fullscreen" it. Should I make an issue for it?

**Comment by DanielJenkyn** [comment]
@PrestonN Honestly your doing great. I love the transparency you have going on!

One thing I would like to point out is an issue I raised #60. The main reason being as this is a core part of YouTube's functionality that is not yet in FreeTube.

Other than that I think a lot of the main functionality is there, It was really easy for me just to switch from YouTube straight away (after adding all my subscriptions)

**Comment by dimqua** [comment]
Please consider to create a roadmap for the next release.

**Comment by D-Ermis** [comment]
You're doing really great man, keep up the good work!

**Comment by JonnyCodewalker** [comment]
Things i would improve:
- Roadmap for future releases, not ordered or anything, just some kind of list. 
- Maybe an IRC-Channel or something like that to talk about it, not sure if the amount of usage already warrants that though.
- 1080p is basically the only thing holding me back.
- Not sure, but how does youtube livestreaming work?

**Comment by theonetoday** [comment]
Just wanted to say you're doing a great job! Thanks!

**Comment by PrestonN** [comment]
Thanks for the feedback everyone.  It is very appreciated. :)

> I did notice with the double clicking, it fullscreens it but doesn't "un-fullscreen" it. Should I make an issue for it?

Nah it's fine.  I'll remember to get that fixed for the next release.  It's small enough where there isn't much need to make an issue for it.

> One thing I would like to point out is an issue I raised #60. The main reason being as this is a core part of YouTube's functionality that is not yet in FreeTube.

> 1080p is basically the only thing holding me back.

I will make a response about this over at #60 shortly.

> Maybe an IRC-Channel or something like that to talk about it, not sure if the amount of usage already warrants that though.

I'm not against this idea.  I think the problem, like you've mentioned, is that I don't believe there would be enough activity over there to warrant making one in the first place.  The flip side of that is that FreeTube gets hundreds of downloads per release and not everyone uses GitHub so it is possible for a small community to form. Anyone else have thoughts on this?  If there's enough interest for one then let me know and I can set something up.

> Not sure, but how does youtube livestreaming work?

Live streaming currently reverts to the default YouTube player.  FreeTube will still let you know if someone is currently live though.  The hope is to not need to do this in the future.

> Please consider to create a roadmap for the next release.

> Roadmap for future releases, not ordered or anything, just some kind of list.

This is a good idea.  I guess I sort of leave people in the dark on progress don't I?  I think the first step is to try to utilize GitHub's project board a little bit more to get a better idea on the current road map.  I'll start setting that up but for now, here's where I plan on going with FreeTube.

Plans for the next release:
* Auto Updates
* Playlist / Video Queue support
* Updated channel view
* Small quality of life updates

Planned for FreeTube to go stable:
* 1080p+ Support
* WebM Support
* Move Live videos to player
* Advanced Search
* Featured List
* Pick Region for featured list
* Updated / more Settings
* Small Quality of life polish (Viewing comment replies, UI Changes, etc.)
* Make a website for FreeTube

Nice to have features / After stable:
* Allow youtube-dl to be called locally
* Remove the YouTube API and switch to the NewPipe Extractor (when they are finished with it)
* Layout / theme customization
* Web extension to open links to FreeTube
* Download manager for video / audio
* Notifications

Obviously these are subject to change and priority can change based on demand or urgency.  It's also possible that I simply forgot something to list on here.  I plan to knock out everything on this list as well as current or future requests already here on GitHub.  I'm very pleased with how FreeTube is turning out as well as the community that is forming around it.  Thanks again to everyone for sticking around. :)

**Comment by dimqua** [comment]
@PrestonN how much beta releases do you plan to make?

**Comment by PrestonN** [comment]
I don't have a set plan as far as how many beta releases will be made.  The idea is when FreeTube has most of the features that YouTube has, and is in a stable position, then I will take it out of beta.  There is no telling on how long this will take. Obviously I won't be done with FreeTube when it's out of beta as there are plenty of things to do afterwards, but I want the core functionality to be done before I consider it ready for a stable release.

**Comment by MegaArthur** [comment]
I guess I'd just like to say that FreeTube in its current state is actually more than enough for my needs and I'd like to say that Your work is so much appreciated man!

**Comment by PrestonN** [comment]
Hey everyone, I've filled out a project board over at the projects section of the repo.  I'll try my best to keep this updated as development continues.  This should give everyone a glance at what's being worked on and what's planned.  Things should be added and moved around as progress is made.  Let me know what you think.

You can check it out here: https://github.com/FreeTubeApp/FreeTube/projects/1

**Comment by aproposnix** [comment]
@PrestonN I've had no problems at all on the new release.  Thanks for the great work! 

Also, thanks for adding the double click to minimize video!

**Comment by PrestonN** [comment]
Closing as 0.3.0 is now released.
