### ISSUE TITLE
Local Api Error (Error: Status code: 429)

### ISSUE THREAD

**Issue by NewFisiu** [FreeTubeApp/FreeTube#610]
**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to Safiya Nygaard channel (that one was error triggering for me)
2. Click on her latest video
3. See error

**Desktop (please complete the following information):**
 - OS: Win 10
 - OS Version: LTSC
 - FreeTube version: 0.8

**Additional context**
So, everything worked just fine yesterday, but today when I tried to watch I got Error: Status code: 429 (Local Api Error). Unfortunately, turning app off and on again did not worked.

Any workaround?

Thank you.

**Comment by GilgusMaximus** [comment]
Yes the workarounds are mentioned here https://freetube.writeas.com/experiencing-429-errors-please-read-for-info and here
https://github.com/FreeTubeApp/FreeTube/wiki/F.A.Q.
