### ISSUE TITLE
[Feature Request]: Preselect what I want to see in Home

### ISSUE THREAD

**Issue by MrCuteCat** [FreeTubeApp/FreeTube#6101]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I have to change tabs to see lives or shorts.

### Proposed Solution

Preselect what I want to see in Home. For example, I want to see videos, shorts and live all together in the same window but not the community. Or videos and live together but shorts/community separately.

### Alternatives Considered

Mix everything in one tab.

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not possible because you will be rate limited in no time.
