### ISSUE TITLE
[Bug]: Crashes during Playback since New Update

### ISSUE THREAD

**Issue by OutsideTub3r** [FreeTubeApp/FreeTube#6105]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Ever since I got the new update, during playback, it will stop. Freeze. Crash. If its in its own window, I can easily close and reopen; if its the only window, I have to close it how ever I can, then restart. This hasn't before, and now it is post-update. It never happened when anything else was open, or even playing. This is an issue I don't know why I have or know how to resolve. 

### Expected Behavior

When it happened the last time, I use CTRL>SHIFT>I and grabbed what popped up.

publishedText is missing but the video isn't live or upcoming
yY @ renderer.js:2
rr1---sn-vgqsrn66.googlevideo.com/videoplayback?expire=1730853404&ei=vGUqZ93gHfOBkucPvq3GyQQ&ip=69.204.44.151&id=o-AFiAmi7J2E8l2-O5plYU6hWh8TpInvyOpJSyKpYzGyV9&itag=303&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1730831804%2C&mh=0P&mm=31%2C26&mn=sn-vgqsrn66%2Csn-ab5l6nkd&ms=au%2Conr&mv=m&mvi=1&pl=19&rms=au%2Cau&initcwndbps=981250&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=660160236&dur=3267.466&lmt=1730807883703222&mt=1730830871&fvip=4&keepalive=yes&fexp=51312688%2C51326932&c=IOS&txp=4437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgAkxoyww9f8gk20nBNPRACOG-o9C7BrTPVjCxszmRjQ0CIG1Z7Wqmla_Qo57RABgrwS_7ruk9eIQu1Bao4aVMUOAo&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRQIhAKRGPS-OyDAXSbmlIUnlC5sQC9FE0u3x26S9EoAcz_FXAiBS3xKSKzzAeOnYeeZqReU0crJfFDKAtrpFD1rPC3DW3Q%3D%3D&cpn=Lvg3B7ZkLByk-VRf&range=363014835-364738285&alr=yes:1 
        
Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_TOO_MANY_RTOS

Player Error (category and code explainations here: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html)
Video ID: "a7sTcSebF74"
FreeTube player context: "shaka error handler"

Severity: CRITICAL (2)
Category: NETWORK (1)
Code: TIMEOUT (1003)
Stack trace:
Error: Shaka Error 1003
    at new Ae (app://bundle/renderer.js:2:26185)
    at app://bundle/renderer.js:2:101791
    at app://bundle/renderer.js:2:102566
    at app://bundle/renderer.js:2:102807 

shaka-player Data: Array(2)

### Issue Labels

causes crash, content not loading

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could you check if this still occurs in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by OutsideTub3r** [comment]
Please unclose this, this is still an issue. Sorry for the late reply. Busy with life. 

Playback still pauses, then crashes, when a skip forward.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please respond to my previous comment.

**Comment by OutsideTub3r** [comment]
> Please respond to my previous comment.

I don't understand any of that. I thought it was a update patch or something but it directs to a listing that includes this thread.
