### ISSUE TITLE
[Bug]: How do we get the nightlies now?

### ISSUE THREAD

**Issue by Moonbane** [FreeTubeApp/FreeTube#6108]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I'm sure you're aware of this, folks, but just in case - everything in the Build workflow in the last 5 days is in red.
https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml
So how do we get the nightlies now?

### Expected Behavior

No errors in the runs & be able to download the nightlies

### Issue Labels

feature stopped working

### FreeTube Version

v0.22.0-nightly-5032 Beta

### Operating System Version

Windows 11 24h2

### Installation Method

Portable

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Will be fixed by https://github.com/FreeTubeApp/FreeTube/pull/6084.

To answer your question: You either be patient and wait for it to be fixed or you build the development branch on your machine yourself, if you don't know how to do the latter then I would suggest being patient and waiting.
