### ISSUE TITLE
[Bug]: Possible fake age restriction

### ISSUE THREAD

**Issue by windowsfan6** [FreeTubeApp/FreeTube#6112]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to this video: https://youtu.be/MuP-9O7gNIc
2. Shows the prompt that video is age restricted, despite it isn't as it plays fine on YT even when logged off

### Expected Behavior

Video will play as usual

### Issue Labels

API issue, content not loading, usability issue

### FreeTube Version

v0.22.0

### Operating System Version

Windows 11 24H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

Did YT started to make fake age restrictions?

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Could you please provide screenshots or write down the exact message.

**Comment by windowsfan6** [comment]
Works fine now, probably a temporary bug. If it will happen again, then I will post the screenshot.

**Comment by windowsfan6** [comment]
Okay, so it happened the 2nd time. Basically, it drops to Invidious API and says that video is "unavailable" until next launch of video. Isn't the age restriction prompt for some reason appiled to unavailable vids as well

**Comment by absidue** [comment]
That just sounds like you are getting IP blocked, unless you can provide a screenshot of the toast messages that are show or write them down word for word, we won't be able to tell you exactly what is going on.
