### ISSUE TITLE
[Feature Request]: Make default to Open Video with New Window

### ISSUE THREAD

**Issue by coffeechococake7** [FreeTubeApp/FreeTube#6115]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently, Freetube allows you to open a new window by pressing ctrl, not regular clicks.

### Proposed Solution

Function to default to opening a new window when clicking on a video (without ctrl key)

### Alternatives Considered

I don't think I need to say much about this proposal here

### Issue Labels

improvement to existing feature, new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is a non standard way to open a video. Therefore this issue will be closed.
