### ISSUE TITLE
[Feature Request]: Please add a refresh button in the address bar

### ISSUE THREAD

**Issue by FreeUDP** [FreeTubeApp/FreeTube#6117]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Please add a refresh button（Ctrl+R） in the address bar。Thanks！

### Proposed Solution

~

### Alternatives Considered

~

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by absidue** [comment]
Nobody should be using CTRL+R, it is the same as if you were to restart the entire app, it is extremely wasteful. If you want to reload just the page you are seeing you should press the back arrow once and then the forward arrow once, that fetches the data for that page again without having to restart the entire app.

Giving people an easier way to do something that they shouldn't be doing is not something we want to do.

**Comment by FreeUDP** [comment]
Thank you for your reply. FreeTube is a very good software, thanks for your work.
Some people (users in China and Iran) watch YouTube live streams through VPN. VPN is unstable, streams will often freeze.
Back and forward buttons can be refreshed, but usually require multiple mouse clicks
If there are many items in the list, I also need to find which item was played previously, which is very inconvenient
If there is a refresh button, it will bring convenience to these people.

Request again,Please add this button.

My English is poor, hope you can understand.

**Comment by absidue** [comment]
> Back and forward buttons can be refreshed, but usually require multiple mouse clicks
> If there are many items in the list, I also need to find which item was played previously, which is very inconvenient

If you press the forward button after pressing the back button, FreeTube will take you to the page you were just on, you only need to search again if you only press the back button.

> Request again,Please add this button.

As mentioned above CTRL+R restarts the entire app, so no we won't be adding a button to do that.
