### ISSUE TITLE
[Bug]: Color shifting when scrolling; washed out colors

### ISSUE THREAD

**Issue by infinity099** [FreeTubeApp/FreeTube#6126]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

See the video:

https://streamable.com/0rdt06

### Expected Behavior

Color should not change when scrolling. 

### Issue Labels

usability issue, visual bug

### FreeTube Version

0.22.0 Beta

### Operating System Version

Windows 10 21H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
If your display and graphics card supports variable refresh rate, please to excluding FreeTube from that in your graphics card settings.

**Comment by infinity099** [comment]
I don't have that setting on my laptop

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please edit the issue body and upload the video in the post instead of an external site

**Comment by penguin9000** [comment]
I also have this. It might have something to do with color profiles. I have a high color gamut monitor as my main display. The video is saturated in normal viewing, desaturated when scrolling. Interestingly, when I connect my second monitor, the program does not have this behavior and displays in a constant desaturated color whether still or scrolling. I wouldn't say the desaturation is a bad look. I think the colors look more natural, like viewing an image with a proper ICC profile. Windows 11.
