### ISSUE TITLE
[Bug]: Comments Not Loading in FreeTube

### ISSUE THREAD

**Issue by exefile2** [FreeTubeApp/FreeTube#6128]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I am experiencing an issue in FreeTube where video comments are not loading. Regardless of the video or channel, the comment section is showing that there are no comments in the video, where there are comments. 
![image](https://github.com/user-attachments/assets/96593fa5-1d28-4a1c-8bed-6496d7654915)

### Expected Behavior

The comments should load.

### Issue Labels

content not loading

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 10 pro

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
This was fixed in 0.22.0. You can officially download the latest version here: https://freetubeapp.io/#download or here: https://github.com/FreeTubeApp/FreeTube/releases
