### ISSUE TITLE
[Feature Request]: Having a log file of errors with channel info

### ISSUE THREAD

**Issue by Janaue** [FreeTubeApp/FreeTube#6130]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I have thousands of subscriptions so when I update the subscription page and some error is thrown I have no idea which channel has a problem. Also the error message are kind of cryptic so I do not really know if the problem stems from Freetube, yotuube, the channel itself or the API.
![Subscriptions - FreeTube_2024-11-10 07_52_31](https://github.com/user-attachments/assets/d8303cf7-7bd7-4a27-be4e-4b85a60d1998)
![Subscriptions - FreeTube_2024-11-10 07_52_13](https://github.com/user-attachments/assets/7cc62c55-a8e5-4fec-a450-229b4e39e469)

### Proposed Solution

when an error happens, it is logged into a file with the timestamp, the channel name, the channel URL and the error itself

### Alternatives Considered

NA

### Issue Labels

display more information to user

**Comment by absidue** [comment]
In this case it's not specific channels but both the Invidious server and your own computer getting ratelimited by YouTube. That can happen if you try to load all subscriptions tabs right after each other or refresh you subscriptions too often.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
