### ISSUE TITLE
[Bug]: 429 api limiit

### ISSUE THREAD

**Issue by fanno** [FreeTubeApp/FreeTube#6132]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Yesterday i was locked out for the first time. with the 429 api limit, and did a bit of google and such.

I switch to the RSS as suggested. this morning i was able to view 2 videos and then was locked out again.
I am not entierly sure what is going on and not 100 % sure if its a but or not but may be hard to recate due to the 1 day lockeout each time.

Something comes to mind that may or may not be related.

I dont know how the internals of the program works. i have enabled the feature to hide watched videos and my sub feed now only has videos that are older than a year or so.

Now do this means when using rss/api or what not its going back throw the feed untill the subscriptions feed is full? there by everytime app refresh it update A LOT.

If so i would suggest making it so that it only go back in time X months or stop looking of a whole feed list fetched is in the watched list. or maybe some other matrix i have not thought of .. assuming this is the cause it would prevent the api from looking back and then back and then back to find content to put in the feed. "spending" all all the api usages on esencially "nothing"

I realize this is a feature and should pehaps be listed under a feature but i would not bring there unless it is related to the 429 then there is no real need for this feature.

I have used local and invedious

Again i am aware it is a api limit issue and not really much can be done. with hitting the limit it self. i am just wondering if youtube is "targeting" freetube since i only saw 2 videos and then it happen again. or if i suspect it has to die with how the app read the api when hide watch videos are used.

NOTE:
i am also hiding. Shorts this may also cause problems as more and more of thoes are around but they dont really interest me .

### Expected Behavior

I would like to revent the 429 so i can use the app again.
Further more it prevents ALL device in the house to access youtube all together like tv and other devices. as they are on same IP

### Issue Labels

API issue

### FreeTube Version

v0.22.0 Beta 

### Operating System Version

Windows 11 Pro /  23H2 / 22631.4317

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
As mentioned on Matrix I'll close this issue as we are already talking to you there and there is no point duplicating the discussion in two separate places.
