### ISSUE TITLE
[Bug]: Playback breaks when pausing video sometimes

### ISSUE THREAD

**Issue by Blechlawine** [FreeTubeApp/FreeTube#6136]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Start playing a video
2. somewhere in the video press pause (it only happens sometimes when pausing)
3. The marker on the seekbar jumps to the start of the video and pressing play doesn't do anything until reloading

### Expected Behavior

pressing play continues the video at the position it was paused

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

0.22.0 Beta

### Operating System Version

Linux based on ubuntu 22.04

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Could you please check in the devtools console (CTRL+SHIFT+I, then choose the console tab) if there are any red messages when that happens (only red, yellow ones are warnings and likely completely unrelated to this issue).

**Comment by Blechlawine** [comment]
I don't get any output which seems related to the issue. And no output at all at the time when it breaks

**Comment by riverpiers** [comment]
I have the same problem on Windows 10, v0.22.0-nightly-5095 Beta: Video, https://youtu.be/VXC1rplHdt0, which was originally added as a stream/broadcast, stops many times at various random moments and does not want to continue playing. When you first start playback, after stopping, the counter jumps to T:0:00 and the default thumbnail, and then after a while it returns to the last stopped shot. You have to wait a few seconds until playback returns. Internet connection works normally.
(Is this an error on the part of YouTube/FreeTube/Channel containing age-restricted videos/Not subscribed to such channel?)

The bug causes codecs to switch from vp09.00.40.0 when playback starts to avc1.42001E after playback stops/error occurs+:
In this video it switched the codec in T: https://youtu.be/WR-_WRWgX84?t=299 after stopping playback. Info from the console in the screenshot:
![Error_FT_streams_v0 22 0-nightly-5095 Beta](https://github.com/user-attachments/assets/2d906ee1-680a-4373-84bc-8bcbb30c4088)

Another error fragment from the console:
>renderer.js:2 Player Error (category and code explainations here: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html)
Video ID: "VXC1rplHdt0"
FreeTube player context: "shaka error handler"
Severity: CRITICAL (2)
Category: NETWORK (1)
Code: TIMEOUT (1003)
Stack trace:
Error: Shaka Error 1003
    at new Ae (app://bundle/renderer.js:2:26185)
    at app://bundle/renderer.js:2:101791
    at app://bundle/renderer.js:2:102566
    at app://bundle/renderer.js:2:102807 
shaka-player Data: 
---
>renderer.js:2 Unable to play DASH formats. Reverting to legacy formats...
