### ISSUE TITLE
Where is the Contribution.md file?

### ISSUE THREAD

**Issue by TeeKKar** [FreeTubeApp/FreeTube#614]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ x] Contribution
- [ ] Languages
- [ ] Setup
- [ ] Other. Please specify:

**Question**
Where can I find the contributions guidelines? I clicked the link on the read me page but I get a 404 error.

**Comment by GilgusMaximus** [comment]
We have to include it again. Also we have to discuss how we want to handle contributions going forward.
So after the new release 0.9 (should come in a few days at latest), PrestoN and I will probably discuss this and setup a new contribution file

**Comment by GilgusMaximus** [comment]
Also closing it in favor of #566
