### ISSUE TITLE
[Feature Request]: Hide the round "play" icon while a video is paused when the cursor is not over the middle of a video

### ISSUE THREAD

**Issue by rjdg14** [FreeTubeApp/FreeTube#6149]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The issue with this large round "play" icon is almost certainly related to the API change in 0.22.0. Earlier versions did not show this largely opaque icon over the middle of videos when paused.

### Proposed Solution

I would ideally like the round play icon to disappear when there is not a cursor over the middle of a video when paused.

### Alternatives Considered

If the new API that 0.22.0 uses doesn't allow the above, would it be possible to create a setting that allows the user the choice of keeping the current play icon in its current form or disabling it completely when a video is paused?

### Issue Labels

ease of use improvement, visual improvement

**Comment by absidue** [comment]
You can hide it with the "Display Play Button in Video Player" setting in the Player settings, as mentioned in various other issues and the same setting as in previous FreeTube releases.
