### ISSUE TITLE
Discord RPC Support?

### ISSUE THREAD

**Issue by snaildos** [FreeTubeApp/FreeTube#615]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Nope. It's a feature suggestion.

**Describe the solution you'd like to see implemented**
I would like to see discord RPC support, if anyone was is wanting to add that that would be cool.

**Describe alternatives you've considered**
Nope.

**Screenshots**
No screenshots.

**Additional context**
Now playing support and time left.

**Comment by snaildos** [comment]
Actually, I can contribute for this. I'll add onto this issue for updates of what I am adding now.

**Comment by Dem1se** [comment]
https://github.com/discord/discord-rpc - "This library has been deprecated in favor of Discord's GameSDK.".
I'm not sure if the suggested package is based on the Discord's RPC library.

the suggested package's repo: https://github.com/discordjs/RPC

**Comment by GilgusMaximus** [comment]
I am not too sure what advantage you see in integrating that.
Could you elaborate that a bit more, so we can make up our mind?

**Comment by snaildos** [comment]
So, The advantage is just so people can see what other people are watching. Obviously not enabled my default, https://premid.app/ is the site I use for my youtube but I want to move to FreeTubeApp and this does not have any RPC support, I want others to see "Playing FreeTube" "Watching video %videoname%.
Here is a example image from premid:
https://i.imgur.com/IyRxdiy.gif
I think it would be a cool feature to add in my opinion @GilgusMaximus 
@Dem1se I don't know- One of the Premid staff showed me that. There should be many examples that work well with electron.

**Comment by PrestonN** [comment]
I'm going to go ahead and say that we won't be working on this.

Implementing this means that we're essentially encouraging use of Discord, which we don't want to encourage.  It would be the first sort of "Account" that we start offering and as a privacy alternative that doesn't really look good.

Sorry, this won't be worked on.

**Comment by snaildos** [comment]
This isn't encouraging use of discord.....??? It's just a way that discord users can show other people what they are watching. Alright then. Will there be plugin support for FreeTube then?

**Comment by PrestonN** [comment]
Discord as a service is not privacy friendly.  As a privacy friendly service, we want to discourage the use of these tools for better alternatives.  Integrating their feature set into our app contradicts what we want to advocate for.

We may have some sort of plugin support far in the future but for now it'll be a while before that ever gets put together.  Especially when most things we'd consider as plugins are features we'd want to integrate into the app itself.

**Comment by snaildos** [comment]
.. Alright then..... Thank you.
