### ISSUE TITLE
[Bug]: Freetube rejects `_gateway` as a proxy hostname

### ISSUE THREAD

**Issue by d-g** [FreeTubeApp/FreeTube#6150]
FreeTube Version: 0.22.0 Beta
Operating System: Debian GNU/Linux 12 (bookworm)
Origin: Flathub

## steps to reproduce

Run a proxy on gateway machine.

Make sure, that it serves Freetube fine, when specified by address.

Make sure, that `_gateway` resovles to that address (in a flatpak enviroment, if relevant):
```
$ flatpak run --command=bash io.freetubeapp.FreeTube
[📦 io.freetubeapp.FreeTube ~]$ getent hosts _gateway
192.168.100.1   _gateway
```
Freetube / Settings / Proxy /
- [X] Enable
- Proxy Host: _gateway
- Proxy Port Number: 1080

[Test Proxy]

## expected result
success

## actual result

	Error getting network information. Is your proxy configured properly?

Evidently, something makes some (a) unnecessary, (b) incorrect check of user input.

**Comment by absidue** [comment]
The template is there for a reason, **do not delete it**. If you think you are able to follow the template and the rules properly, please open a new issue, I'm closing this one as invalid.

**Comment by d-g** [comment]
@absidue:
> The template is there for a reason...
To ensure a minimal legal level of visual clutter?

> please open a new issue
By the way, which `B:` tag would your suggest to select?  None of them seem to be adequate.
