### ISSUE TITLE
[Feature Request]: Rockchip VPU acceleration via rkmpp

### ISSUE THREAD

**Issue by defencedog** [FreeTubeApp/FreeTube#6154]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Jellyfin has recently added Rockchip VPU acceleration via `rkmpp`
https://jellyfin.org/docs/general/administration/hardware-acceleration/rockchip/

A similar feature is requested

### Proposed Solution

Video playback can use `ffmpeg` binary that utilize Rockchip HW components X4
```
$ ls -l /dev | grep -E "mpp|rga|dri|dma_heap"
drwxr-xr-x  2 root       root          80 Jan  1  1970 dma_heap
drwxr-xr-x  3 root       root         140 Jan 18 18:50 dri
crw-rw----  1 root       video   241,   0 Jan 18 18:50 mpp_service
crw-rw----  1 root       video    10, 122 Jan 18 18:50 rga
```

### Alternatives Considered

nOT APPLICABLE

### Issue Labels

new feature

**Comment by absidue** [comment]
You need to make this feature request to Chromium. Once they add support and Electron updates to the relevant version of Chromium and FreeTube updates to that version of Electron, it'll be supported in FreeTube.
