### ISSUE TITLE
[Bug]: Error: [UNPLAYABLE] Please sign in

### ISSUE THREAD

**Issue by 626164** [FreeTubeApp/FreeTube#6159]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

For the last 24 hours, I have not been able to play any video on this app. When I click on a video to watch, "Error: [UNPLAYABLE] Please sign in" instantly pops up and "Falling back to Invidious API" appear right beneath it, and goes away after a moment to be replaced by "[VIDEO_ERROR] YouTube watch session expired. Please reopen this video."

The Invidious Instantance is currently defaulted to "https://inv.nadeko.net", I have tried other with no noticable affect. 

### Expected Behavior

Vidoes should play when I click on them. Either using the Local API or the Invidious API fallback.

### Issue Labels

API issue, usability issue

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Microsoft Windows 11 Pro v10.0.22631 Build 22631

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.3 Beta 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by 626164** [comment]
And now its back to functioning normally. Nothing changed on my end.

**Comment by 626164** [comment]
I've noticed that this error occurs when I am connected to the Manassas VA, Nord VPN server.

**Comment by 626164** [comment]
@absidue That's what I realized earlier. Do you think there is any code solution for detecting if Invidius is blocked & then to switch to the local api as a backup?

**Comment by absidue** [comment]
The local API is what is receiving the error in the title of this issue from YouTube, when you are blocked.

**Comment by absidue** [comment]
Also it already switches back and forth automatically, hence the "falling back to {local or invidious} api" messages.

**Comment by Dizelyator** [comment]
Столкнулся с такой же проблемой. Смотрел без ограничений, и через пару дней пользования, программа перестала работать. Смена локации VPN не помогает, спустя несколько дней ничего не изменилось. Жаль, что ничего нельзя сделать. Но моё дело - сообщить здесь об этом
