### ISSUE TITLE
[Feature Request] Variable playback speed with smaller step

### ISSUE THREAD

**Issue by ThatIsAPseudo** [FreeTubeApp/FreeTube#616]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Variable playback speed is great for speeding up videos, however a 0.25 step is quite big when you want to find the perfect speed to match exactly the speach in the video (especially long ones such as conferences and talks)

**Describe the solution you'd like to see implemented**
There could be an option in the settings to set the step, so that if you select 0.1, you'll be able to choose 0.8, 0.9, 1, 1.1, 1.2, etc. However, this could lead to too many choices for small steps.

Another solution could be using buttons such as the ones on the toolbar of the browser extension _Enhancer for Youtube_ (see screenshot below). Clicking on minus/plus will decrease/increase the playback speed (by a step defined in settings), and clicking on the middle button will set back the playback speed to 1.
If only a few people are interested in such a feature, a contextual menu option would be enough.

**Screenshots**
![Capture d’écran 2020-10-08 à 10 54 35](https://user-images.githubusercontent.com/17936055/95438558-c01e9800-0956-11eb-9575-677792678c5b.png)

**Additional context**
Chrome addon : https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle
Firefox addon : https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/

**Comment by GilgusMaximus** [comment]
This is something that has already come up during the rewrite. 
PrestoN added more options, however such a super detailed option is yet to be made.

This could be done in combination with #251 and #375. Because adding such buttons is a major change in the video player and something more people would have to agree on to make it accepted by everyone. However adding hotkeys, with adjustable step size, which change the speed, would not need such a discussion, because you do no have to make interface changes.

**Comment by snakyjake1** [comment]
Also, in the UI when selecting the playback speed, improve the slider:

1)  The selected playback speed should be visible and centered.

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: 7
 - FreeTube version: 0.9.2
 - Installation Method (If applicable): Portable
 - Primary API Used: Local API

    OS: Windows
    OS Version: 7
    FreeTube version: 0.9.2
    Installation Method (If applicable): Portable
    Primary API Used: Local API

**Comment by orthand** [comment]
Chiming in on this: As currently left clicking the playback speed indicator increases it would it be possible to decrease it by right clicking? That could be an alternative to the three button option from @ThatIsAPseudo.

**Comment by ZER0-X** [comment]
I made [video-speed-setter](https://github.com/ZER0-X/video-speed-setter) firefox extension and i've used `Alt+L` & `Alt+J` as hotkeys. I think they are good sinse they are the same buttons for going forwards and backwards.
