### ISSUE TITLE
[Feature Request]: Add 2 buttons to control bar, 1  Rewind  15s & 1 Fast Forward 15 sec. (See Image Below)

### ISSUE THREAD

**Issue by via80HD** [FreeTubeApp/FreeTube#6161]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Howdy,  
I know y'all probably have enough to work on already so if you find  the time & can implement this suggestion then amazing but if not....thats perfectly fine too.  So basically I have been using  a video player that has seek forward and reverse by 15 seconds buttons right next to the play button in the control bar of the video player. I have become used to & really love having the buttons there when I'm feeling lazy & my keyboard is like 3 arm lengths (so basically 6 miles) away & all I have is my mouse. The seek buttons IMHO would be preferred over having to just click somewhere on the time line & hoping to be close.  So yeah, Ill put a screenshot of the buttons to give you an idea of what it looks like on the video player I got this from below & leave the rest up to yyall. Thanks 

![croppedandscrewed](https://github.com/user-attachments/assets/cc299ec3-404f-45ea-b928-7b5c4bcc3e7b)

### Proposed Solution

Adding the 2 buttons marked with a yellow rectangle in the image above. 

### Alternatives Considered

Fell free to put the buttons anywhere on the control bar, it doesn't have to be up by the play button.l. 

### Issue Labels

ease of use improvement, new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sorry but this is a wont implement. We cant deviate from the YT UI too much. We are still reworking the player looks/functionality and this doesnt fit in there

**Comment by onegladiator4u** [comment]
How about a fast 2x when click and hold like in youtube?
