### ISSUE TITLE
[Feature Request]: Setting to enforce original audio track

### ISSUE THREAD

**Issue by LeonidNougat** [FreeTubeApp/FreeTube#6162]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There are certain videos where others use A.I. to add audio translations to YouTubers' videos. These "good intentions" push the original audio track at the bottom of the option list thus making the video start in whatever is the first language in line.
For example [this one starts in German](https://youtu.be/68R3kwpuLR4) and [this one starts in Hindi](https://youtu.be/ZlbBCBjdnig) (for now at least). **Both videos are in English originally.**

It catches one by surprise when A.I. generated translations start playing instead of what you'd expect. Quite an irritating matter!

### Proposed Solution

If possible, the option to toggle and enforce the original audio in FreeTube's player settings would be useful.

### Alternatives Considered

If as an option in the player settings is too much of a hassle, enforcing the original audio by default is just as good. Even better I would say!

### Issue Labels

ease of use improvement, new optional setting

**Comment by Huecuva** [comment]
I just want to point out that I have this same issue. My settings are configured to use English as the default language but often I have videos starting in other languages and it's pretty irritating.
