### ISSUE TITLE
Contributing file

### ISSUE THREAD

**Issue by Dem1se** [FreeTubeApp/FreeTube#617]
**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [x] Contribution
- [ ] Languages
- [ ] Setup
- [ ] Other. Please specify:

**Discussion**
I wanted to ask about the lack of a CONTRIBUTING.md file. 
Is it intentional for some reason, or if not, why not make one pretty soon? I feel it's essential to every public project that invites public contributions. The issues page is pretty filled right now, but still having a formal record of how the project needs help from contributors can help get some meaningful and much appreciated contributions.

**Comment by GilgusMaximus** [comment]
Closing in regards to #566 as I answered it there.
