### ISSUE TITLE
[Bug]: Cannot open video in external player (VLC)

### ISSUE THREAD

**Issue by MStankiewiczOfficial** [FreeTubeApp/FreeTube#6176]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

The default external player is set to _VLC_.

1. Open any video in PT
2. Click _Open in vlc_
3. An error appears:
<img width="372" alt="A JavaScript error occurred in the main process. Uncaught Exception: Error: spawn vlc ENOENT at ChildProcess._handle.onexit (node:internal/child_process:286:19) at onErrorNT (node:internal/child_process:484:16) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)" src="https://github.com/user-attachments/assets/d1b2da14-9b11-445a-b8b6-d5cc3e53a153">

### Expected Behavior

The VLC player should open.

### Issue Labels

content not loading, inconsistent behavior, visual bug

### FreeTube Version

0.22.0

### Operating System Version

macOS Sequoia 15.1 (24B83)

### Installation Method

.dmg

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
It sounds like you didn't configure the path to the VLC binary in FreeTube's external player settings which is why FreeTube is failing to launch it.

**Comment by MStankiewiczOfficial** [comment]
I added it, but there is still the same error.
<img width="372" alt="A JavaScript error occurred in the main process. Uncaught Exception:
Error: spawn /Applications/VLC.app EACCES at ChildProcess._handle.onexit (node:internal/child_process:286:19) at onErrorNT (node:internal/child_process:484:16) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)" src="https://github.com/user-attachments/assets/66d22874-3a5f-4f17-9589-258790e273fd">

**Comment by absidue** [comment]
As mentioned in my message above you need to specify the path to the actual binary, `/Applications/VLC.app` is a folder. FreeTube trusts that your input is correct, it doesn't do all the extra magic that macOS does to treat the folder as an app.

**Comment by moriel5** [comment]
Same happens to me on Linux, even if I manually set the exact path, whether it be to `vlc` or to `vlc-wrapper`, to `celluloid` and to `mpv` there are no such issues.

**Comment by vipweixiao** [comment]
路径换成"/Applications/VLC.app/Contents/MacOS/VLC"就可以唤起 vlc 了，但打开提示 vlc 提示报错“您的输入无法被打开
VLC 无法打开 MRL「https://rr1---sn-un57snee.googlevideo.com/videoplayback?”

**Comment by kasselvania** [comment]
Has the issue of "You're input can't be opened VLC is unable to open the MRL ..." issue been corrected?

**Comment by moriel5** [comment]
I'll check in a few moments, though to my knowledge it hasn't.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
inquires regarding external players migrated to https://github.com/FreeTubeApp/FreeTube/discussions/7789
