### ISSUE TITLE
[Feature Request]: Add "Mark As Watched" Option in Video Page

### ISSUE THREAD

**Issue by lwobniar** [FreeTubeApp/FreeTube#6177]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Would like the ability to manually mark a video as watched within the video page, instead of having always to go back to the subscription or search page to use function under the three dots menu.

I prefer to manually mark each video as watched rather than using the auto detection for watch history.

### Proposed Solution

Add the ability to manually mark a video as watched within the video page. For example, add a button beside "Share Video".
![Screenshot 2024-11-16 125121](https://github.com/user-attachments/assets/a8f1c652-9062-4c53-9f62-ccb91c49ae97)

### Alternatives Considered

I currently go back to the subscription or search page and use the "Mark As Watch" function under the three dots menu.

### Issue Labels

ease of use improvement, new optional setting

**Comment by onegladiator4u** [comment]
Whenever a video is opened to play its considered as watched i think. If you go back and see in subscription page it'll be marked as watched.

**Comment by absidue** [comment]
When you have the watch history enabled FreeTube automatically marks videos as watched as soon as the video loads on the watch page.

Could you please explain your use case in more detail?  Currently this sounds like a very niche use case and it is too much work to develop, test and maintain something that only one user will use.

**Comment by lwobniar** [comment]
My current set up:
 - "Remember History" is NOT enabled
 - "Hide Videos on Watch" under Subscription is enabled.

By manually marking a video as watched, it allows me to manually hide videos from my subscription page and see which videos have been watched on search. I prefer not to have "Remember History" enabled as I often start a video and return to finish it at a later time. If I have this option enable, I would have videos "incorrectly" marked as watched.

Currently I always have to go back to the subscription/search page to mark a video as watched. Given that the "Mark As Watched" option is already available on subscription/search page, it would be really helpful (and I think it also makes sense) to have the "Mark As Watched" option available on the video page as well.

**Comment by absidue** [comment]
Technically it should probably be considered a bug that the mark as watched option shows up when saving history is disabled.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The usecase presented here is definitely a niche one and could be covered by other issues.

**Comment by zacryol** [comment]
Perhaps this issue should be reopened? There are less niche usecases for this feature. Notably, with the occasional widespread 403 errors that happen, there are plenty of times where I (and presumably others) would open a video, find the error, and then open the video in an embed or external player to watch it for real.

None of those actions will add the video to the history, so you would still need to go back to another page listing the video to add it to history from there, which could be harder if that video was opened directly from a browser.

At the very least, I think that the "Open in [External Player]" button on the video page should mark the video as watched, the same way that the it does on other pages.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> At the very least, I think that the "Open in [External Player]" button on the video page should mark the video as watched, the same way that the it does on other pages.

It does that now and will be available in v0.24.0
