### ISSUE TITLE
FreeTube Doesn't Register it's Protocol Correctly on Mac

### ISSUE THREAD

**Issue by 360fun** [FreeTubeApp/FreeTube#618]
Since I love **FreeTube** very much, I would like to use it to open automagically YT links in any kind of situation. I use Mac OS but I think can be applied to Linux and Windows as well.

**ANALYSIS**
I can identify 3 kinds of "open a link" situations:
1. **inside the browser in the address bar**
2. **inside the browser when I click on a link**
3. **outside the browser**

**CHALLENGES/PROBLEMS**
1. needs an extension to stop loading the video and ask me what I want to do or get the option to always convert the link to freetube:// (like https://github.com/SimonBrazell/privacy-redirect)
2. needs an extension like https://github.com/FreeTubeApp/freetube-redirect (currently I get the "_TypeError: Cannot read property 'simpleText' of undefined_" error)
3. needs an app like https://github.com/will-stone/browserosaurus or https://github.com/johnste/finicky to catch the interaction and manage it. Currently **FreeTube** doesn't seems to **manage the http protocol in the first place**, so I cannot see the App in browserosaurus menu.

![image](https://user-images.githubusercontent.com/844090/95446623-d3cefc00-0960-11eb-97a0-96c71c74c9f4.png)

Any solution/fix?

Thank you! 🙏

**Comment by GilgusMaximus** [comment]
Hi. Thanks that you identified the situations so closely.

1) This could probably be implemented into the freetube-redirect as well, although I did not take a single look into it yet
2) As far as I am aware, the rewrite does not handle it correctly at the moment, that is why the addon is not working. However there were already discussions over at the Matrix channel to fix it.
3) That is something that was mentioned in an older issue #474 . So thanks for bringing it up again. This should then be implemented correctly. However neither PrestoN nor I own a Apple devices, so testing for Mac is not possible for us at the moment. So any contributions from an Apple device owner are more than welcomed.

I think overall these are some good first issues for new contributors. In regards to the contribution guideline take a look here #566. I hope we can add it back soon

**Comment by 360fun** [comment]
Thank you for the quick response! :)

1. 2. Exactly what I imagined ;)
3. I'm not sure if they are correlated. I often click on YT links in Telegram and I would like them to open in FreeTube. If FreeTube could support the http/s protocol as well, would be very easy to use **Browserosaurus** or a similar app to handle the link.

I'm your "Mac tester" then! ;)

**Comment by GilgusMaximus** [comment]
So in the next release, or if you want to use the automated releases that are under the actions tab, the plugin is already fixed.
So you can download that and install it and then the plugin should run again

**Comment by 360fun** [comment]
> So in the next release, or if you want to use the automated releases that are under the actions tab, the plugin is already fixed.
> So you can download that and install it and then the plugin should run again

I'm sorry, I went to Action but I don't understand what I should do... 🤔
I'm more into web dev so I'm kinda lost without a compiled App to download 😛 
maybe you mean I've to switch the FreeTube Helper (Plugin).app ? anyway that's a compiled file... 🙄

**Comment by PrestonN** [comment]
If you follow [this](https://github.com/FreeTubeApp/FreeTube/actions?query=workflow%3ABuild) link and click on the first build, you'll see downloadable binaries for your device.

Assuming FreeTube is installed on your machine, it should enable the `freetube://` protocol to properly handle opening of links.  You should be able to add `freetube://` in front of any YouTube URL to have it open into FreeTube.

This is already working and enabled in the latest dev builds, so I'll go ahead and close this issue.

**Comment by 360fun** [comment]
I don't see any build...are you sure they are public?

this is what I see:
![image](https://user-images.githubusercontent.com/844090/95499209-406bea00-09a5-11eb-821b-657c22241e79.png)

**Comment by PrestonN** [comment]
Each commit message you see is a new build.  For example, the first build in that picture is the build with the message "Update README.md"

Click on that and you'll find the download links.

**Comment by 360fun** [comment]
I did it but links were not active, now they are, no idea what happened... 🤔

Anyway I downloaded the 0.9.0 and I tested it with the Chrome extension: the FreeTube app is called but shows the same "TypeError: Cannot read property 'simpleText' of undefined" problem as before. 😞 
![image](https://user-images.githubusercontent.com/844090/95508721-bc6d2e80-09b3-11eb-8c57-5b8f97208b88.png)

**Comment by PrestonN** [comment]
That sounds like a different issue.  I'd need to know what video you're trying to open that's causing that error.  If FreeTube is opening properly, then it's not a problem with the extension and needs to be a new issue.

**Comment by 360fun** [comment]
> That sounds like a different issue. I'd need to know what video you're trying to open that's causing that error. If FreeTube is opening properly, then it's not a problem with the extension and needs to be a new issue.

Actually is the same error I put in my first message, but you're right it's something else: I get that error **every time I open the App**! I mistakenly associated the error with the video opening, but they are probably not correlated.

The behaviour I see when I click on a YT link (whatever) is:
- the FreeTube app opens or gets the focus
- that's it...no video starts playing, no errors, nothing happens at all!

**Comment by 360fun** [comment]
I found the real problem and opened another issue: #622

**Comment by 360fun** [comment]
I tried to open freetube://www.youtube.com/watch?v=WHATEVER, I get the request to choose the FreeTube app but the behaviour is the same described: app opens or in focus but no video loaded.

**Comment by PrestonN** [comment]
Can you confirm that when FreeTube automatically opens up that it's using v0.9.0?  If I had to guess, your Mac might still be using v0.8.0 to open the link, which wouldn't have the logic in it.

**Comment by rebelcode-xr** [comment]
I tested this: https://github.com/FreeTubeApp/FreeTube/actions/runs/296126752

![image](https://user-images.githubusercontent.com/63522951/95552979-f703b500-0a0d-11eb-8e8a-d3b1dd16ff2c.png)

**Comment by 360fun** [comment]
I tested this: https://github.com/FreeTubeApp/FreeTube/actions/runs/296126752

![image](https://user-images.githubusercontent.com/844090/95553052-113d9300-0a0e-11eb-9f93-cf0b36f56f3c.png)

**Comment by PrestonN** [comment]
Alright.  This is starting to be strange.

If you have the app opened up before you click on a link, does it redirect properly?  I'm curious if it's maybe a timing issue with how the app is setup.  If this works then this should help narrow it down.

**Comment by 360fun** [comment]
No, in no case the video is loaded, the app just opens or switch focus but nothing else. 😢  It loads the default view with recent videos.
I've tested the latest build...same. 👐

**Comment by timharek** [comment]
Same case for me as well, on macOS.

**Comment by PrestonN** [comment]
Going to re-purpose this issue since there's still a problem going on.  Please know that I don't have access to a Mac and it's much harder for me to test for one, so this may be a while before I can get a proper look at it.

**Comment by PrestonN** [comment]
Could one of you please try out [this](https://github.com/FreeTubeApp/FreeTube/actions/runs/298509854) build and see if this fixes the issue?  I haven't tested this so it might not work, but after some reading up the change I made should have done something.  Let me know if anything is different.

**Comment by 360fun** [comment]
> Could one of you please try out [this](https://github.com/FreeTubeApp/FreeTube/actions/runs/298509854) build and see if this fixes the issue? I haven't tested this so it might not work, but after some reading up the change I made should have done something. Let me know if anything is different.

It looks the same behaviour to me 😞 
FreeTube is called but nothing is loaded, the content remains the same whatever it is. I tried to play a video and see if it gets at least interrupted...nope. All I get is the switch of focus from Brave to FreeTube. 👐

**Comment by cmf** [comment]
I've implemented a fix for this in the linked PR. The custom protocol handling in macOS is different to Win/Linux. Those flows also changed a bit but I don't have a Win/Linux machine to test them on, so if someone could do a sanity check on those too that would be much appreciated.

**Comment by 360fun** [comment]
> I've implemented a fix for this in the linked PR. The custom protocol handling in macOS is different to Win/Linux. Those flows also changed a bit but I don't have a Win/Linux machine to test them on, so if someone could do a sanity check on those too that would be much appreciated.

waiting the build to test it! 😄

**Comment by timharek** [comment]
@cmf , can confirm that this works on my MBP 16". Good job!
