### ISSUE TITLE
[Feature Request]: User's 'watching' statistics

### ISSUE THREAD

**Issue by enrrari** [FreeTubeApp/FreeTube#6181]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Not really a problem. Just a proposal. Seeing as FreeTube already has the user data locally (if enabled), such as history and subscriptions, one interesting possible feature could be statistics regarding what the user watches most, perhaps akin to Spotify's “Your Sound Capsule”, maybe an end-of-year function akin to Spotify's “Wrapped”.

### Proposed Solution

One proposed implementation could be checking history for the videos and channels that show up most for a given time period, such as a given month or year (for something akin to Wrapped). Then, a page could be displayed to the user with information such as their Top 5 Channels and Top 5 Videos (or however many you see fit) for the time period, and maybe even how long they spent watching. If an end-of-year “Wrapped”-like feature were to be made, such could be made to show up when the date is that of December of a given year.

### Alternatives Considered

An alternative is for the user to create a script that does something similar with the same history and subscription files. I myself have developed a Bash script that uses Freetube's history and subscription files, along with Invidious API, to craft CSV files that can be analysed in a LibreOffice Calc sheet, but not exactly with the aforementioned purposes in mind.

### Issue Labels

new feature

**Comment by absidue** [comment]
FreeTube wouldn't be able to provide something as detailed as one of those wrapped things from music services, considering that it saves minimal information about the watched videos and if you watch a video multiple times FreeTube only remembers the most recent time.

**Comment by absidue** [comment]
Additionally please do not abuse the Invidious API with that many requests, as you will be directly contributing to the instance getting blocked by YouTube. Unless it is your own Invidious instance.

**Comment by enrrari** [comment]
Apologies. I shall take more care regarding the Invidious API. I'll look into the docs, see if there's any way to optimise its use (or I'll just drop the use altogether. Not a must-have in my life, I reckon).

As for the wrapped suggestion, yeah. Didn't occur to me the fact that history "bumps up" older videos when rewatched (i.e. only "remembers" a video once). Can always add a "most watched channels", based on the channels behind videos in history (i.e. group history by channel, count by channel). But it's mainly just a silly idea I had. Nothing mind-blowing or a must-have. Just thought, if the info is there, you could infer something from it. But I forgot the minimal storage of information.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It is a nice idea but from reading the arguments stated here its clear to me that this is definitely a wont implemented
