### ISSUE TITLE
[Bug]: Picture-in-picture mode in not preserved when playing a playlist or when next video is started in autoplay.

### ISSUE THREAD

**Issue by amal-sajeev** [FreeTubeApp/FreeTube#6202]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1) Play any video in picture-in-picture mode, make sure auto-play is turned on or the video is in a playlist.
2) Wait for the video to finish and autoplay to engage.j

### Expected Behavior

The picture-in-picture mode is disengaged and the next video plays in the freetube window.
![opera_RrOzbGB7uf](https://github.com/user-attachments/assets/1ecacd8c-86b6-49f8-bafb-2cf8c0b1be66)

### Issue Labels

usability issue

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Windows 11 23H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
As explained on other issues this is working as expected and is not a bug: https://github.com/FreeTubeApp/FreeTube/issues/5701#issuecomment-2350991840

**Comment by 20cent-hk** [comment]
"it's not a bug it's a feature"
