### ISSUE TITLE
[Bug]: local  api error

### ISSUE THREAD

**Issue by smith78342** [FreeTubeApp/FreeTube#6203]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

api error

### Expected Behavior

loacal api error  youtube banning ip

### Issue Labels

API issue

### FreeTube Version

0.22.0 

### Operating System Version

debian

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Please provide a lot more details such as the error messages you are getting or screenshots or screen recordings.

**Comment by Hulttio0x0** [comment]
> Please provide a lot more details such as the error messages you are getting or screenshots or screen recordings.

![screenshot-2024-11-21-18-03-10](https://github.com/user-attachments/assets/63ae2669-d092-4206-b047-4791248c1ff1)

This will happen with video from xbox channel and video "S.T.A.L.K.E.R 2: Heart of Chornobyl Launch Trailer"

**Comment by absidue** [comment]
That's because the video is age-restricted and age-restricted videos cannot be watched in FreeTube because they require an age-verified YouTube account.
