### ISSUE TITLE
"All channels" profile does not aggregate all profiles subscriptions anymore

### ISSUE THREAD

**Issue by Kallys** [FreeTubeApp/FreeTube#621]
**Behavior of the program**
After an erratic update (I loose all my configurations without any warning about it), I succeeded to re-import my subscriptions by importing `~/.config/FreeTube/subscriptions.db` file via GUI. This operation did not work for history, I gave up.  
And now, I don't know if this is an issue or a new behaviour but, with profile "All channels", if I go to the "Subscription" tab, it tells me that my subscription list is empty (while I have few profiles with working subscriptions).

**Expected behavior**
In previous version of FreeTube (did not check which version, the latest one before UI got reworked, lets says I updated a week or two ago), the "Subscription" tab with profile "All channels" use to aggregate every subscriptions of all my profiles.

**To Reproduce**
Already explained.

**Screenshots**
No relevant screenshot.
I check the javascript console, few warnings and no error.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - OS Version: 20
 - FreeTube version: v0.8.0 Beta

**Additional context**
FreeTube is a nice app :)

**Comment by PrestonN** [comment]
Is this only on startup?  Does this happen even if you go to a different page and come back?  I think for some people it's only happening on startup but if you go to a different page and come back, your subscriptions will load.

I've been having a hard time replicating this, I believe it happens on slower systems but I need to get some more information about it.

**Comment by Kallys** [comment]
No, it happens all the time, whatever is my navigation history.
And for additional informations, I have a recent gaming laptop so I don't think my system is slow.

**Comment by PrestonN** [comment]
Could you please email me your subscription file? I'm having trouble figuring out what the problem could be.

And I'll ask again, if you navigate to the About section for example, and navigate back to your subscriptions, nothing shows up at all? I'm finding that very hard to believe. A gif / video of you doing this would help a lot actually.

Something is still telling me that it only doesn't show on boot, which is already logged somewhere to look more into.

**Comment by Kallys** [comment]
![Peek 09-10-2020 01-12](https://user-images.githubusercontent.com/1195845/95522498-91430900-09cc-11eb-97f0-7d832d305fc9.gif)

By the way, I don't know if it's normal by the way but in "All channels" profile, there is actually no channel images list on bottom of left panel (unlink in other profiles).

**Comment by PrestonN** [comment]
Alright.  Thanks for this.  This helps a lot.

Can you please export your subscriptions and send the file to me?  It looks like something in your database got messed up.  Not sure how though.

**Comment by Kallys** [comment]
Just sent you raw db file by mail.

**Comment by PrestonN** [comment]
Hey thanks for sending me that file.  I've reworked how the import functions and it should handle your file just fine now.  You should be able to try out [this](https://github.com/FreeTubeApp/FreeTube/actions/runs/296588005) build to properly import your subscriptions.  At the time of writing this it's still building and may take ~20 minutes before it's ready.

I'll consider this as fixed now.

**Comment by Kallys** [comment]
Thanks @PrestonN , after clicking on the "Vérifier les abonnements Legacy" button, everything is now working as expected!
