### ISSUE TITLE
[Bug]: Cannot set property duplex of #<Request> which has only a getter

### ISSUE THREAD

**Issue by ivan-pugach-sprinterra** [FreeTubeApp/FreeTube#6210]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Implement integration with the FreeTubeApp
2. Open the page with the video that is integrated
3. Open the browser's console
<img width="1718" alt="Screenshot at Nov 21 22-19-37" src="https://github.com/user-attachments/assets/57b6125c-5f16-4b2d-ab3e-5bdafe70861e">
<img width="1501" alt="Screenshot at Nov 21 22-19-59" src="https://github.com/user-attachments/assets/2c753881-58b6-44cd-8888-b41f8fe6abcf">

### Expected Behavior

1. Integrated video should show on the page

### Issue Labels

API issue, causes crash, content not loading, feature stopped working

### FreeTube Version

v0.22.0-beta, 30c3978

### Operating System Version

Windows, macOS

### Installation Method

other

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.3

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Could you please explain in more detail what you mean by "implement integration with FreeTubeApp"?

FreeTube is a desktop app for YouTube, so I'm not sure why you are trying to "integrate it" into anything.

**Comment by ivan-pugach-sprinterra** [comment]
Hi @absidue, 
The integration was done via LuanRT/YouTube.js library
