### ISSUE TITLE
TypeError: Cannot read property 'simpleText' of undefined

### ISSUE THREAD

**Issue by 360fun** [FreeTubeApp/FreeTube#622]
Every time I open the Mac version of FreeTube (0.8.0 and also the latest build 0.9.0) I get the error "TypeError: Cannot read property 'simpleText' of undefined".

I finally found what is causing it: [this channel](https://www.youtube.com/c/AndreaCiraolo/)

![image](https://user-images.githubusercontent.com/844090/95522271-f0ece480-09cb-11eb-8be2-44010334de33.png)

If I stop following it, the error at beginning is gone!

**Comment by PrestonN** [comment]
Confirmed.  Right now our channel grabber isn't handling Premiere videos properly.  I'll try to get this fixed soon.

**Comment by PrestonN** [comment]
I've fixed this in dev.  Builds will be available soon.

**Comment by 360fun** [comment]
Great! I'll try it as soon as I can! 🙏

**Comment by 360fun** [comment]
Fixed! 🥳
