### ISSUE TITLE
Sharing Subscriptions and History between machines on my home network?

### ISSUE THREAD

**Issue by therealrobster** [FreeTubeApp/FreeTube#623]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ x ] Setup
- [ ] Other. Please specify:

**Question**
Hi there,

I have a home setup with multiple machines all having access to my home server.  I'd like to run something like syncthing and share the history and subscriptions between my machines.

To do this what folder/s file/s should I be looking for?  I'm running on Linux if that helps.

Thank you.

**Comment by PrestonN** [comment]
You can find the appropriate locations over at #151.

I'm hoping to eventually allow you to better pick where these files are stored to add better compatibility with apps like Syncthing.  I don't know when it'll be available but it's definitely planned.
