### ISSUE TITLE
[Bug]: Unable to play age-restricted video

### ISSUE THREAD

**Issue by neuroflare** [FreeTubeApp/FreeTube#6243]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. open freetube
2. search or attempt to open an age-restricted video.  e.g., [https://www.youtube.com/watch?v=fETc77XokxE](https://www.youtube.com/watch?v=fETc77XokxE)
3. receives local API error or invidious API error, depending on which one is selected
![local api error](https://github.com/user-attachments/assets/6b783d73-8c2c-4969-b0de-9363d2781a38)
![invidious api error](https://github.com/user-attachments/assets/214f41ea-a180-4ade-808c-ef64fb980452)

### Expected Behavior

Video should play normally

### Issue Labels

content not loading

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Windows 10 22h2 19045.5011

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.22.0 Beta

### Additional Information

I was not receiving this error prior to today, 11/30/2024.  

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
As mentioned in many other places e.g. https://github.com/FreeTubeApp/FreeTube/issues/6203#issuecomment-2491935230, https://github.com/FreeTubeApp/FreeTube/issues/6127#issuecomment-2466799881 and https://github.com/FreeTubeApp/FreeTube/discussions/5940#discussioncomment-11059015 (next time please actually follow the instructions in the template and search through both open and closed issues), age-restricted videos not working is entirely expected as YouTube patched the only age-restriction bypass over a while back and now the only way to watch them is is with an age-verified YouTube account.

**Comment by AlfaScarlate** [comment]
04/jan/2026: 
Age-restricted videos cannot be watched with FreeTube as they require Google login and using an age-verified YouTube account.

<img width="1440" height="866" alt="Image" src="https://github.com/user-attachments/assets/f7865be8-36fb-42cb-8aef-83f63177a0a7" />

**Comment by absidue** [comment]
@AlfaScarlate Not sure what the point of your message is, the message in FreeTube is quite clear.
