### ISSUE TITLE
[Feature Request]: see playlist on watch page without exiting fulscreenl

### ISSUE THREAD

**Issue by sergioEB** [FreeTubeApp/FreeTube#6249]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Non exit Fullscreen on a playlist.

### Proposed Solution

Hello! 
I have been using this software for a short time and I would like to know if it is possible to see a list of saved videos to watch later without leaving the full screen and having to re-activate the full screen mode again every time a video starts.

### Alternatives Considered

It would be nice if you could see a complete list without having to press the F- key again.

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is a non standard way of showing the contents of the playlist while watching a video. Therefore i will be closing this as this wont be implemented
