### ISSUE TITLE
[Bug]: Won't play any videos, requires me to sign-in

### ISSUE THREAD

**Issue by Sessh22** [FreeTubeApp/FreeTube#6250]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

With Flathub version, trying to load any video for me gives me an error:
Local API Error: [UNPLAYABLE] Please Sign In
Invidious API Error: This content isn't available. Legacy formats are not available for this video.

With linux portable version from this site, I get the same error plus the video thumbnail loads up in the player with message:
[VIDEO ERROR] Youtube watch session expired. Please reopen video.

Reopening video does not change the result.

### Expected Behavior

Clicking a video should play the video without being required to sign in or producing any errors.

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Linux Mint 22

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

I am moving over from Windows 7 to Mint 22. The last version that supported Windows 7 still works though a bit tempermental at times, but I've never been asked to sign in to view any videos using Freetube. I tried the 0.21.3 Linux version as well which had the same result. I just tried the Linux portables for 0.20 and 0.21. They don't play anything either though with different error messages. However as I type this, v0.19.2 Beta is still working on my Windows 7 PC.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

EDIT:
It seems this is a regional issue. It just occurred to me to try to switch my VPN connection to another country and that seems to have fixed it. Connected to Finland, these issues are present. Connected to Poland now and they're not present, videos play fine now. If this is not something Freetube can fix and therefore not a bug, please close this issue.

**Comment by absidue** [comment]
As you already figured out in the edit, you are using VPN servers that are blocked by YouTube, the next release will show a better error message that explains it better. All we can suggest is that you use one that isn't blocked.
