### ISSUE TITLE
[Bug]: Subscription page never loads

### ISSUE THREAD

**Issue by ocean-haiyang** [FreeTubeApp/FreeTube#6259]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

On RSS or API, it never loads.

### Expected Behavior

I expect to see my subscriptions.

### Issue Labels

content not loading

### FreeTube Version

0.22.0 beter

### Operating System Version

linux

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by wcarss** [comment]
👋 also having this consistently in freetube 0.22.0_amd64.deb on ubuntu 22.04; about 21 subscriptions

**Comment by wcarss** [comment]
We also had [this issue](https://github.com/FreeTubeApp/FreeTube/issues/4762), which led [here](https://github.com/FreeTubeApp/FreeTube/issues/5553), and I resolved those _and_ this issue after finding and removing a malformed subscriptions-cache.db from ~/.config/FreeTube (or whever [your local freetube data is stored](https://docs.freetubeapp.io/usage/data-location/) for your OS)

**Comment by ocean-haiyang** [comment]
> @ocean-haiyang did you by any chance used another installation methode before using Flathub?

I also tried rpm as I’m on fedora. Same thing sadly

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please try https://docs.freetubeapp.io/usage/importing-subscriptions/#troubleshooting-issues and report back

**Comment by ocean-haiyang** [comment]
> Please try https://docs.freetubeapp.io/usage/importing-subscriptions/#troubleshooting-issues and report back

I deleted all my subscriptions then sub-ed one by one and it works fine. The way I imported them must have not been supported. They showed as sub-ed and listed on the sidebar but would not show up in subscriptions.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@ocean-haiyang would you be willing to provide the file you tried to import? Maybe this can help us find the issue and fix it for other future users.

**Comment by ocean-haiyang** [comment]
> @ocean-haiyang im glad you got it working. would you be willing to provide the file you tried to import? Maybe this can help us find the issue and fix it for other future users.

[youtube.opml.xml.zip](https://github.com/user-attachments/files/18089592/youtube.opml.xml.zip)

Here you go! It was from my freshrss feed.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
From looking at the file it seems like this line is the culprit:    

`<outline text="https://m.youtube.com/@Seth.Hughes/videos" type="rss" xmlUrl="https://m.youtube.com/@Seth.Hughes/videos" htmlUrl="https://m.youtube.com/@Seth.Hughes/videos"/>`

More specifically:
`type="rss" xmlUrl="https://m.youtube.com/@Seth.Hughes/videos"`

All other xmlUrl links in the file look more like:
`xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCxj38S7nvhpdJD9lD1m4HGQ"`

So it seemed like there that link was saved incorrectly and thats why FT couldnt parse it.

**Comment by ocean-haiyang** [comment]
Thanks! I may try this with that deleted as a test. Can’t believe you caught that
