### ISSUE TITLE
Localized plural forms

### ISSUE THREAD

**Issue by milotype** [FreeTubeApp/FreeTube#626]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
If possible, please use correct localized plural forms for strings (at Weblate). Many languages need more than just 2 forms.
I'm not a programmer, so I can't really help to solve this issue. :-(

I found the following strings which need such a change (Croatian uses "one", "fiew", "many". Other languages need other forms.):
Channel->Channel has been removed from your subscriptions: Removed subscription from $ other channel(s)
Video->Published->Hour/Hours
Video->Published->Minute/Minutes
Video->Published->Month/Months
Video->Published->Second/Seconds
Video->Published->Week/Weeks
Video->Published->Year/Years
Video->View->View/Views

**Describe the solution you'd like to see implemented**
Implement correct plural forms.

**Comment by GilgusMaximus** [comment]
Hi no problem that you are not a developer. Just contributing with feature requests and bug reports helps us a lot :)

This is a valid feature request, however one that is probably very low on our list, as we would need a complete guide for all available languages, which forms are used when and how many are available.

I'll think about how we could croudsource that information :)

**Comment by milotype** [comment]
@GilgusMaximus I think it's not too complicated for a programmer ... my two cents: https://docs.weblate.org/en/weblate-3.9.1/user/translating.html#plurals.

But I'm also aware, that it's a case of priority and time ... ;.) It would be great to have this issue solved before version 1.0!

**Comment by GilgusMaximus** [comment]
Ah okay, that is very useful. Thank you.
The thing is, we still need to incorporate that into code, so checking for one, few or multiple would be required.
If someone really wants to do that, a PR is appreciated. 👍

**Comment by milotype** [comment]
Closing ... will be worked on in #673
