### ISSUE TITLE
[Bug]: High GPU / CPU Usage Latest Update (laptop warm and throttled - potential hardware accelerated issue)

### ISSUE THREAD

**Issue by powline99** [FreeTubeApp/FreeTube#6264]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

GPU and CPU usage high :hardware acceleration on Windows 10.

### Expected Behavior

Running Freetube v0.22.0-nightly-5095 Beta - GPU and CPU usage high on Windows 10. Possible from GPU hardware acceleration. Did not seem to do this on prior versions. attached GPU log. Laptop is overly warm, intel HD Graphics 4600. CPU at above 50% usage. I cannot figure out how to use Electron to turn off hardware acceleration. 
I tried just pasting the section for turn off acceleration (any idea how to do this for a noob) app.disableHardwareAcceleration()
Disables hardware acceleration for current app. This method can only be called before app is ready.

### Issue Labels

API issue, usability issue

### FreeTube Version

v0.22.0-nightly-5095 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

[about-gpu-2024-12-03T02-40-36-096Z.txt](https://github.com/user-attachments/files/17986545/about-gpu-2024-12-03T02-40-36-096Z.txt)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Thank you for the GPU details. Could you please provide more details about when it happens e.g. is it just during video playback or all the time?

**Comment by powline99** [comment]
> Thank you for the GPU details. Could you please provide more details about when it happens does it just happen while playing a video or all the time?

When I leave it open "Freetube." Close it and the CPU/GPU goes down. For context. ...Lots of memory is you leave multiple windows open. 

IS there a way without playlists or watch lists to have multiple windows / tabs. Out of site out of mind I suppose with saved playlists. As the player has some cross over with chrome can the tabs be freezed until clicked on or played. I know chrome uses a pluggin "The Marvelous Suspender" to take the tab / window instance out of memory.  

Have about 10 windows open FYI as I don't have a way to utilize tabs like chrome and don't find add to favorites as helpful for my use case when doing research. 

How does one turn off Hardware acceleration?

**Comment by absidue** [comment]
> Lots of memory is you leave multiple windows open.
> Have about 10 windows open FYI as I don't have a way to utilize tabs like chrome and don't find add to favorites as helpful for my use case when doing research.

Using lots of memory when you have lots of windows open is entirely expected, it would be the same situation if FreeTube had tabs. Each window/tab is somewhat independent so each one needs to keep a copy of your data in memory otherwise performance would be dreadful. The most sensible thing to do is close the windows you don't need.

> How does one turn off Hardware acceleration?

Pass the `--disable-gpu` flag on the command line every time you start FreeTube. Although that will likely just make it even worse.

**Comment by powline99** [comment]
> > Lots of memory is you leave multiple windows open.
> > Have about 10 windows open FYI as I don't have a way to utilize tabs like chrome and don't find add to favorites as helpful for my use case when doing research.
> 
> Using lots of memory when you have lots of windows open is entirely expected, it would be the same situation if FreeTube had tabs. Each window/tab is somewhat independent so each one needs to keep a copy of your data in memory otherwise performance would be dreadful. The most sensible thing to do is close the windows you don't need.

There has to be a better way to utilize windows or tabs instead of a single instance or using "favorites" as a playlist with massive amounts of videos. Hard to compare / Group videos without several open. Even a way to visually see videos in groups instead of lists would be helpful (besides making more playlists) - some browsers have thumbnails of tabs open or favorites in a page without memory. [feature] Perhaps a side button that has grouped current visual thumbnail grouping of videos and a way to save those together for reference. Any ideas on this. 

> > How does one turn off Hardware acceleration?
> 
> Pass the `--disable-gpu` flag on the command line every time you start FreeTube. Although that will likely just make it even worse.

I put it in the console right? I get this error...

--disable-gpu
VM193:1 Uncaught ReferenceError: disable is not defined
    at <anonymous>:1:1
