### ISSUE TITLE
[Feature Request]: Filter old videos from subscriptions

### ISSUE THREAD

**Issue by benasraudys** [FreeTubeApp/FreeTube#6269]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

My subscription page shows videos up to several years old that I've already watched. I prefer an empty subscriptions page, but there are too many videos to manually mark as watched.

### Proposed Solution

Perhaps add a dropdown in settings to limit displayed videos in subscriptions to a specific age (e.g., 1 month, 3 months, or 1 year).
Alternative solution would be a button to mark all unwatched videos as watched.

### Alternatives Considered

The most closely related option is the "Only Show Latest Video for Each Channel", but it's not what I'm looking for.

### Issue Labels

new optional setting, visual improvement

### Additional Information

#1955 had a similar issue, but it seems like it was assumed to be a duplicate of another post, so the actual issue didn't get addressed.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/5265
