### ISSUE TITLE
[Bug]: audio is faint / modulating when played via bluetooth

### ISSUE THREAD

**Issue by pravi** [FreeTubeApp/FreeTube#6275]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. open any video / choose audio only format
2. connect to bluetooth
3. audio is modulating

### Expected Behavior

audio should not modulate. Same video played from firefox works well with any issues.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.22.0 beta

### Operating System Version

FuriOS (Debian GNU/Linux) testing/trixie) - default on Furiphone FLX1

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

Possibly related to https://github.com/FreeTubeApp/FreeTube/issues/5600

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @pravi could you try out the stable volume option and report back if this fixes it


https://github.com/user-attachments/assets/900e84ac-8cfd-4116-b5f5-ab1eabb297eb

If this doesnt fix it i would like you to try to play a YouTube video in a Chromium based browser.
