### ISSUE TITLE
Download subtitles locally

### ISSUE THREAD

**Issue by nullbasis** [FreeTubeApp/FreeTube#628]
Love the new option to download videos locally. Only problem is that if I download a video with toggleable subtitles, the subtitles get left behind because they aren't part of the video file. Is there any chance an option could be added to fetch and download the subtitles?

**Comment by PrestonN** [comment]
Yeah this should be fairly simple to do.  I can get this setup in the dev builds in the next day or so.

**Comment by PrestonN** [comment]
So "next day or so" turned into a week, but it's done.  Should be available in the dev builds now.
