### ISSUE TITLE
[Bug]: Playback speed resets after pausing and resuming the video

### ISSUE THREAD

**Issue by An-anonymous-coder** [FreeTubeApp/FreeTube#6281]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open any video
2. Change the playback speed from "1x" to something else
Side note: This will immediately resume video playback if the video is paused. It could be related, otherwise it might be worth changing this. 
3. Pause the video
4. Resume the video
The playback speed will be reset back to "1x"

### Expected Behavior

The playback speed should remain the same. 

### Issue Labels

feature stopped working, usability issue

### FreeTube Version

v0.22.0-nightly-5233 Beta (a7f738a)

### Operating System Version

Debian GNU/Linux 12 (bookworm) x86_64 6.1.0-28-amd64

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

Unknown

### Additional Information

I have "Max Video Playback Rate" set to "10x", and "Video Playback Rate Interval" set to "0.1".

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by kommunarr** [comment]
Can't replicate either issue on OpenSUSE TW (Wayland, x86_64 RPM download), even with same settings set you mentioned in Additional Information.

**Comment by jspast** [comment]
This bug happens for me as well, but only when resuming the video by pressing with the mouse button. It does not reset the playback speed when resuming by pressing 'space' or 'K'.

**Comment by absidue** [comment]
@jspast @An-anonymous-coder Do either of you have the scroll to change playback rate turned on?

**Comment by jspast** [comment]
> @jspast @An-anonymous-coder Do either of you have the scroll to change playback rate turned on?

No, I don't have that enabled. Interestingly, though, with that turned on, changes to the playback rate with the scroll are not reset. Changes through the selector still reset when resuming by pressing with the mouse button.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
can reproduce 

https://github.com/user-attachments/assets/4508657f-f61e-449c-8dbe-c8f36b5c9c36

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah this also happens on the shaka nightly demo player, definitely an upstream issue.

**Comment by Janaue** [comment]
also i cannot select the speed x1 during a video playing. My default setting is speed x1.5

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
fixed by https://github.com/FreeTubeApp/FreeTube/pull/6392
