### ISSUE TITLE
[Feature Request]: Add buttons for frame stepping

### ISSUE THREAD

**Issue by An-anonymous-coder** [FreeTubeApp/FreeTube#6282]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There is no way to seek through a video frame-by-frame using the UI. Sometimes you want to pause a video on a specific frame, potentially for a screenshot. The only way to achieve this through the UI is by slowing down the video to 0.1x and precisely it. However, this is difficult because of issue https://github.com/FreeTubeApp/FreeTube/issues/6281. You are able to frame step using the "," and "." keys, but there is no UI option for this. 

### Proposed Solution

Create UI buttons for frame stepping, so that you can seek through a video frame-by-frame while it is paused, without using keyboard shortcuts. 

### Alternatives Considered

The screenshot tool may have a full UI to allow selecting frames manually. 

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by kommunarr** [comment]
If I may ask, do you know of a similar app that has this feature? What does it look like?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> However, this is difficult because of issue https://github.com/FreeTubeApp/FreeTube/issues/6281.

It seems like you are just requesting this because of the bug. The bug should be solved so this should be made easier for users. We should introduce UI buttons as an alternative solution to the bug.

More essential control are going to be added and its already overcrowded as it stand. Adding this is definitely a niche feature. Im unfamiliar with any players that have implemented something like this.

Closing for the arguments stated above.
