### ISSUE TITLE
[Bug]: Audio is auto-dubbed to foreign language by default.

### ISSUE THREAD

**Issue by the-rocinante** [FreeTubeApp/FreeTube#6286]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Enable a VPN connection via a country who's primary official language is different from the YT video's spoken audio.
2. Open a video (try several as it happens somewhat intermittently).
3. The audio is autodubbed with a foreign language, and often there is no UI option to hear the original undubbed version.

### Expected Behavior

When clicking a video, the audio should not be dubbed into an alternative language by default.

If it is, it should be governed by a settings option (eg. autodub=boolean; locale=language;) which determines which target language it is dubbed into.

Pasting the same YT link into a browser or yt-dlp from the same VPN exit node yields the undubbed version. So there is likely something being passed to YT uniquely as part of the headers sent by FreetubeApp which is causing this audio language dubbing to occur.

### Issue Labels

content not loading, inconsistent behavior, usability issue

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Linux Mint 21.3

### Installation Method

.deb

### Primary API used

Local API

### Additional Information

Occasionally there is a menu option at the base of the video allowing selection of the unaltered/undubbed audio. However this option is not consistently available and still requires manually resetting it to the original language after each video loads. In the case the option is not present the only alternative is to download or otherwise play the video using a different application (eg. web-browser, yt-dlp, etc).

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Please read: https://github.com/FreeTubeApp/FreeTube/issues/4291#issuecomment-2452527942
