### ISSUE TITLE
De-Mainstream YouTube

### ISSUE THREAD

**Issue by wildcard-f8** [FreeTubeApp/FreeTube#630]
There's this browser extension called De-Mainstream YouTube. It basically allows you to select channels to exclude from your searches. It would be great to have a feature like this or be able to install it as an extension.

**Comment by GilgusMaximus** [comment]
Okay this is something that could be implemented as a setting, but is currently not planned.
So if someone is confident enough to implement this, we are open for pull requests.

However if the videos from certain channels are excluded from a search, the search should not be empty if one channel fills up a whole page.

**Comment by PrestonN** [comment]
This is a duplicate of #95
