### ISSUE TITLE
[Bug]: on all videos with multiple audio tracks, the first one in the list is selected, not the original one, which is usually the last one. 

### ISSUE THREAD

**Issue by lcfm1** [FreeTubeApp/FreeTube#6301]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

example https://youtu.be/hTErlzG-2uk

### Expected Behavior

is expected to be set in the program to select the original track depending on the country, or to include the original track by default

### Issue Labels

usability issue

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Windows 10 Pro for working stations 22H2  19045.5131

### Installation Method

.zip

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Please read: https://github.com/FreeTubeApp/FreeTube/issues/4291#issuecomment-2452527942
