### ISSUE TITLE
[Bug]: When certain actions are performed, the subscriptions page displays videos that have already been watched

### ISSUE THREAD

**Issue by lcfm1** [FreeTubeApp/FreeTube#6302]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. go to history
2. click on the first video
3. click on the channel name
4. return to the subscription feed
5. old videos added to the feed

### Expected Behavior

a normal list is expected

### Issue Labels

usability issue

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Win 10 Pro for Working stations 22h2 19045.5131

### Installation Method

.zip

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could you provide a screenrecording of this behavior. I cant seem to reproduce this.

**Comment by lcfm1** [comment]
https://gyazo.com/16955b2599bcaec947a62cba7571d40b

The problem is reproduced if there are videos on the channel that are marked as unviewed.
Actually, strangely, they are not in the main subscription list, but they show up as unviewed in the channel. I took the time to click on each video and mark them as watched to have a clean subscription list.
The screenshot below shows the unviewed videos on this channel.

![image](https://github.com/user-attachments/assets/ccd9d56a-6924-414c-9821-69f6fd0d54fb)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please upload the video straight into GitHub instead of an third party site.

**Comment by lcfm1** [comment]
https://github.com/user-attachments/assets/9bb7abb5-ba3b-442e-81b1-9e010ece9157

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isnt a bug. Those videos arent marked watched within the channel and thats why FT caches it and popup in the subscriptions view.
