### ISSUE TITLE
[Bug]: No 1080p (clearly blurry quality) and no setting below the video to change quality

### ISSUE THREAD

**Issue by respoda777** [FreeTubeApp/FreeTube#6303]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Despite having settings set at 1080p default play quality, all videos clearly are below 1080p and even 720p despite the same videos having both on youtube directly. I can remember that before, the quality was as it should so I do not know if it was an update or another bug.

### Expected Behavior

Expected behavior is that videos supporting 720p and 1080p are actually played at that setting when it is set in the main player settings.

### Issue Labels

feature stopped working

### FreeTube Version

0.20.4 beta

### Operating System Version

win7 sp1

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

unknown

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
We only support the latest version of FreeTube, however as you are using Windows 7 and we no longer support Windows 7, you can either tolerate the issue (which has been fixed in newer versions) or switch to a newer operating system such as Windows 10+ or Linux if you want to keep using FreeTube.

**Comment by respoda777** [comment]
Hi mate,



Yes I had noticed that by heading to the github and doing some reading up.



However, if I setup a virtual machine with win10 and use the newer version from there, it should/could also work, right?

If it doesn’t though, it be helpful if you told me so I can save the effort trying it out.



Kind regards.
