### ISSUE TITLE
[Bug]: All videos without preview image

### ISSUE THREAD

**Issue by lcfm1** [FreeTubeApp/FreeTube#6307]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

 all the lists look like this
![preview](https://github.com/user-attachments/assets/de8cd7c7-585d-4f08-b590-067b5014f845)

### Expected Behavior

is expected to look normal.

### Issue Labels

visual bug

### FreeTube Version

0.22.0 beta

### Operating System Version

win 10 for working station 1904.5131

### Installation Method

.zip

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
It looks like you chose `Hidden` in the `Thumbnail Preference` dropdown in the `General` settings.

**Comment by lcfm1** [comment]
sure. my fault.
