### ISSUE TITLE
[Bug]: Wrong Audio Track

### ISSUE THREAD

**Issue by Nickleaton** [FreeTubeApp/FreeTube#6311]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Settings have a locale preference of English (US)
Select a video in the playlist
Audio comes out as non English. 
Doesn't seem to be any pattern as to which is selected. I can get Spanish, German, ... 
If there are no alternative tracks, it selects the original 

### Expected Behavior

The track should be selected from your preferences. 

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Invidious API

### Additional Information

.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please read https://github.com/FreeTubeApp/FreeTube/issues/4291#issuecomment-2452527942
