### ISSUE TITLE
[Feature Request]: Translate comment button to translate comments to English (or any configured language if possible)

### ISSUE THREAD

**Issue by ReEnMikki** [FreeTubeApp/FreeTube#6315]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Right now there is no way to translate foreign language comments like on YouTube. We need a button under each non-English comment to do that.

### Proposed Solution

Add a translate comment button just like YouTube. Or maybe one button to translate all comments if possible.

### Alternatives Considered

Add a translate comment button just like YouTube. Or maybe one button to translate all comments if possible.

### Issue Labels

new feature

**Comment by absidue** [comment]
Please provide a screenshot of what that looks like on YouTube website.

**Comment by ReEnMikki** [comment]
> Please provide a screenshot of what that looks like on YouTube website.

![image](https://github.com/user-attachments/assets/5374103e-a67e-4243-8481-da25b27b61f7)

First and third comment: non-English comments, with translate button under them

Second comment: translated comment, with see-original button under it

**Comment by absidue** [comment]
I asked for the YouTube website, that looks like the mobile app, also make sure you are signed out of YouTube, as FreeTube talks to the YouTube website logged out.

**Comment by ReEnMikki** [comment]
> I asked for the YouTube website, that looks like the mobile app, also make sure you are signed out of YouTube, as FreeTube talks to the YouTube website logged out.

It's actually on browser of Windows, I just have an extension to make comments appear on the right of the video so I can read comments while watching video, so they appear vertical like that.

When I log out, the translate button is gone.

![image](https://github.com/user-attachments/assets/77966f8a-dbc3-4f36-bbaa-15e0fd0bff0a)

**Comment by absidue** [comment]
In that case we won't be able to add support for it to FreeTube as it requires being logged into YouTube.

**Comment by ReEnMikki** [comment]
> In that case we won't be able to add support for it to FreeTube as it requires being logged into YouTube.

So there is no external way that doesn't rely on YouTube ? How come browsers can translate websites without needing API or logged into Google ?

**Comment by absidue** [comment]
> > In that case we won't be able to add support for it to FreeTube as it requires being logged into YouTube.
> 
> 
> 
> So there is no external way that doesn't rely on YouTube ? How come browsers can translate websites without needing API or logged into Google ?

Chrome uses the Google Translate servers. Firefox downloads machine learning models onto your computer and translates the text with those, which is also why it supports a much smaller number of languages compared to Chrome.
