### ISSUE TITLE
Alignment and typography

### ISSUE THREAD

**Issue by milotype** [FreeTubeApp/FreeTube#632]
Please check PR #631

**Behavior of the program**

- The div for **Duration** (Trajanje) does not align correctly. (Screenshot Alignment)
- Percentage and multiplication characters are not preceded by a non-breaking space. (Screenshot Typography)
- Multiplication character is not correct – you are using the _Latin Small Letter X_  (Screenshot Typography)
- `Space-Hyphen-Space` is used as separator.  (Screenshot Typography)

**Expected behavior**

- The div **Duration** should align correctly with other divs.
- Percentage and multiplication characters should be separated from the values by a non-breaking space.
- Correct the multiplication character
- I'd suggest to simply use `Collon-Space`, instead of `Space-Hyphen-Space` (I couldn't find out where this is specified, so please correct it accordingly … The hyphen makes it look as if it where a negative value …)

**To Reproduce**
1. Go to Filter/Settings

**Screenshot Alignment**

![Alignement](https://user-images.githubusercontent.com/43657314/95657372-80051400-0b14-11eb-96e0-2393fb84ddf7.png)

**Screenshot Typography**
![HyphenNobreakSpace](https://user-images.githubusercontent.com/43657314/95657376-885d4f00-0b14-11eb-93ec-85beabc7be07.png)

**Comment by PrestonN** [comment]
Should be fixed with #653

**Comment by milotype** [comment]
@PrestonN Just to inform you, 1st, 3rd and 4th item of this issue look good in the Build #174 on my MacOS 10.11.6
