### ISSUE TITLE
[Bug]: App Breaks When Loading Any Video in Legacy Format

### ISSUE THREAD

**Issue by DagothUrTheFalse** [FreeTubeApp/FreeTube#6334]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [x] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

click on a video
it loads the first frame/thumbnail and the play button appears with the loading circle around it
the video loads no further and no buttons work besides DE provided window controls

### Expected Behavior

Expected behaviour is for the video to play as normal.

### Issue Labels

content not loading, feature stopped working, usability issue

### FreeTube Version

v0.22.0

### Operating System Version

Pop!_OS 22.04 LTS x86_64

### Installation Method

.deb

### Primary API used

Local API

### Additional Information

It worked fine up until today, not sure why, cant flick on anything once I open a video, only able to close Freetube by the window controlls once it happens.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Do you see the error from #6238

**Comment by rollandm** [comment]
> Do you see the error from #6328

Unless I missed something in that error, this issue goes deeper than the video simply not loading. The entire application locks up - even attempting to click on, eg, settings does nothing. Nothing happens when mouse-overing any component either.

The window itself is not frozen however: scrolling still works, the application can be closed without having to resort to CAD, and the spinny-thingie around the play button still animates.

[This is on Windows 10, FWIW]

**Comment by DagothUrTheFalse** [comment]
Didn't see any error messages no, nor does his entire app lock up. I cant seem to find any logs, partly because tha pp is never crashing, just becoming entirely impossible to interact with.

**Comment by Honu2070** [comment]
I have the exact same issue (on Windows 11 23H2).

Until yesterday everything was fine, but today every window used to read a stream locks itself.

**Comment by Chrisb1888** [comment]
same issue on windows 11. about 10 am it started for me.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please do the following:

1. Open FreeTube
2. Open dev console, ctrl + shift + i
3. Go to a video
4. There should be red errors popping up in the console (ignore the yellow warnings)
5. Create a screenshot of the red errors
6. Post the screenshot here

**Comment by Joduai** [comment]
Isn't it also caused by problems with access to invidious.io along with its api?

**Comment by DagothUrTheFalse** [comment]
> Please do the following:
> 
>     1. Open FreeTube
> 
>     2. Open dev console, ctrl + shift + i
> 
>     3. Go to a video
> 
>     4. There should be red errors popping up in the console (ignore the yellow warnings)
> 
>     5. Create a screenshot of the red errors
> 
>     6. Post the screenshot here

![image](https://github.com/user-attachments/assets/bf359b7b-da67-4e20-8a19-fa4b18d50205)


Noticing the error i found a solution for the time being, legacy formats are broken is the root problem it seems, the errors are piling up so fast that electron is cooking itself, in only the time it took to write this reply the error count passed 30,000!

**Comment by DagothUrTheFalse** [comment]
![image](https://github.com/user-attachments/assets/18ad2633-5e56-41b2-bb3b-e25525e6b03e)

**Comment by DagothUrTheFalse** [comment]
> > Do you see the error from #6328
> 
> Unless I missed something in that error, this issue goes deeper than the video simply not loading. The entire application locks up - even attempting to click on, eg, settings does nothing. Nothing happens when mouse-overing any component either.
> 
> The window itself is not frozen however: scrolling still works, the application can be closed without having to resort to CAD, and the spinny-thingie around the play button still animates.
> 
> [This is on Windows 10, FWIW]

and this is correct!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This issue was solved some time ago in https://github.com/FreeTubeApp/FreeTube/pull/6180 but moat users face it now due to #6328

**Comment by Chrisb1888** [comment]
okay yeah the problem with Legacy format turn it to dash formats under player. thx.
