### ISSUE TITLE
Pressing ← 'back' does not restore same 'Sort By' option

### ISSUE THREAD

**Issue by computeristic** [FreeTubeApp/FreeTube#634]
To reproduce:

1. Go to any channel
2. Sort by 'Most Popular'
3. Press on any video
4. Press the ← back button

Expected behavior: go back to channel view with the same sort option
Actual behavior: goes back to default sort by 'Newest'

FreeTube v0.9.0Beta on macOS Mojave 10.14.6.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2446
