### ISSUE TITLE
[Bug]: YouTube Movies cannot be played

### ISSUE THREAD

**Issue by An-anonymous-coder** [FreeTubeApp/FreeTube#6346]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Find and open a YouTube Movie ([here](https://youtu.be/3fE5uTeBGUM) is one)
2. Depending on how you got there, different bugs will happen. If you used a direct link, you will get the "Legacy formats are not available for this video" error. 

Trying to view the YouTube Movies account also has errors, not sure if that's related.

### Expected Behavior

You should be able to view and watch the video.

### Issue Labels

content not loading

### FreeTube Version

v0.22.0-nightly-5291 Beta (e9aac86)

### Operating System Version

Debian GNU/Linux 12 (bookworm) x86_64 6.1.0-28-amd64

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

None

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
> Depending on how you got there, different bugs will happen

Please take a screenshot of the exact error messages. Usually other errors occur before that specific legacy formats one and the original error is much more important as that is also what triggered the other ones.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Im getting this

![image](https://github.com/user-attachments/assets/981b251c-9d6d-4d87-8aee-a4c6d82c6d9c)

**Comment by absidue** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Please expand the `Shaka-player data:` array, the object inside of it should have more detailed information.

**Comment by absidue** [comment]
Okay so the fact that it is using an `app://` URL means that there was no URL passed to the player.

Without looking into it too much myself it's possible that it is a movie without a trailer which isn't getting caught during the extraction process. So there is nothing for FreeTube to play (the movies themselves are DRM protected, just like with every streaming service).

**Comment by TheOracle22** [comment]
This just isn't movies. It's all my Christmas music too. This worked yesterday. For example, this song plays fine in the browser: https://www.youtube.com/watch?v=t_xq3Bj_tas

However, in FreeTube I get the following message:
![image](https://github.com/user-attachments/assets/b16ad52a-6a92-43ce-b6eb-7378dbd6bcd9)
