### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by milotype** [FreeTubeApp/FreeTube#635]
**Behavior of the program**
Some english strings do not translate:

1. **Profile Name** (the string does not seem to exist in Weblate)
![FilterName](https://user-images.githubusercontent.com/43657314/95660475-7be2f180-0b28-11eb-8a91-f0e0b413ca1f.png)

2. **All Channels** (the string does not seem to exist in Weblate)
![AllChannels](https://user-images.githubusercontent.com/43657314/95660486-8309ff80-0b28-11eb-9a9f-dbec2aa766a0.png)
![AllChannels2](https://user-images.githubusercontent.com/43657314/95660489-88674a00-0b28-11eb-86d8-4b462ec46a94.png)

3. **Windows name**
![WindowTitle](https://user-images.githubusercontent.com/43657314/95660494-90bf8500-0b28-11eb-9b7e-ec7ab2e46a8e.png)

4. **About page**
![About](https://user-images.githubusercontent.com/43657314/95660532-d1b79980-0b28-11eb-80d8-0bb59d678ba2.png)

**Expected behavior**
All english strings should get translated

**Comment by GilgusMaximus** [comment]
Thank you very much. These strings are hard coded but I'll fix them later so they should be up for translation on Weblate later today. 
These strings are hard to spot for us as we mostly use English, so they are not obvious.

The about page will be reworked completely so it will stay in English until that rework tho

**Comment by milotype** [comment]
Closing ... will be worked on in #673

**Comment by milotype** [comment]
@GilgusMaximus Just as a reminder to my above mentioned bugs:

1. `Profile Name` still does not exist in Weblate's origin strings. It cannot be translated and it doesn't translate in the app. Applies to all languages ...
2. `All Channels` exists in Weblate's strings, but still does not translate in the app. Applies to all languages ...
3. `Windows name` seems solved. It translates as expected.
4. `About page` seems solved. It translates as expected.
