### ISSUE TITLE
Channel Icons Suddenly All Disappeared

### ISSUE THREAD

**Issue by faxotherapy** [FreeTubeApp/FreeTube#6357]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

There are no specific steps to reproduce. All I can say is that, as a sudden, all my channel icons are gone. Yesterday, icons as usual, today no longer channel thumbnails.

<img width="192" alt="freetube-gone-icons" src="https://github.com/user-attachments/assets/40cfaffc-f436-40b8-a5ff-bf2ba710a9df" />

### Expected Behavior

I'd like to see channel thumbnails.

### Issue Labels

visual bug

### FreeTube Version

0.22.0 Beta

### Operating System Version

macOS 12.7.1

### Installation Method

Homebrew (Unofficial)

Issue still the same with the DMG downloaded from the FreeTube site.

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.22.0

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could you update to v0.22.1 and see if that resolves it for you

**Comment by faxotherapy** [comment]
Thanks a lot. Solved with this update.
