### ISSUE TITLE
A couple of feature requests

### ISSUE THREAD

**Issue by Brier1104** [FreeTubeApp/FreeTube#636]
1.  An option to remember the filter settings between sessions.

2.  An option to always play videos in full screen mode.

3.  An option to show the full name of the profile in the top right corner - instead of the first letter of the profile name.

FreeTube is already perfect.  Now it will be even more perfect 😄

**Comment by PrestonN** [comment]
Please create separate issues for each feature.  We can't keep ourselves organized when multiple features are in one issue.
