### ISSUE TITLE
[Bug]: Video inexplicably plays in German

### ISSUE THREAD

**Issue by johntisdale2** [FreeTubeApp/FreeTube#6364]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1) Go to https://inv.nadeko.net/watch?v=CHozRTwHInE see that the video plays in English
2) Find the same video in Freetube.
3) Video plays in German

### Expected Behavior

1) Go to https://inv.nadeko.net/watch?v=CHozRTwHInE see that the video plays in English
2) Find the same video in Freetube.
3) Video plays in English

### Issue Labels

usability issue

### FreeTube Version

freetube-0.22.0-win-x64-portable.

### Operating System Version

Windows 11 v 10.0.26100

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

unknown

### Additional Information

Problem has affected all videos published on Numberphile channel since at least December 5. German, really, German?

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please read https://github.com/FreeTubeApp/FreeTube/issues/4291#issuecomment-2452527942
