### ISSUE TITLE
[Bug]: Latest version of installer crashes

### ISSUE THREAD

**Issue by Shugabush** [FreeTubeApp/FreeTube#6368]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Download the latest version of freetube, open it up, and it crashes.

### Expected Behavior

Download the latest version of freetube, open it up, and I should be able to install it.

### Issue Labels

causes crash

### FreeTube Version

0.22.1

### Operating System Version

Windows 11, version 24H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You should provide way more details than this in order for us to investigate

**Comment by lcfm1** [comment]
In my case freetube installer x64 deleted everything from app folder, left only Uninstall FreeTube.exe
2h22 x64 for workstation ru

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@lcfm1 thats sad to hear but this is not possible the FreeTube installer never touches the database files. This sounds more like a database corruption that occurred before install.

**Comment by lcfm1** [comment]
https://github.com/user-attachments/assets/c0b50b2e-2cf0-4a96-b97a-af8b77f9f6eb

**Comment by Shugabush** [comment]
> You should provide way more details than this in order for us to investigate

I don't know what else you need besides a couple things:

Latest working version is 21.3. 22.0 and 22.1 installers just crash immediately when opened.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
What does crash mean for you? Does it not throw and error? Please provide a screenrecording as that would provide more visual insight in the situation

**Comment by Shugabush** [comment]
https://github.com/user-attachments/assets/128ac738-4099-4148-9c7c-65764cfbdcad

This is the problem I'm having.

**Comment by Shugabush** [comment]
I just figured out a workaround. I ran the program with command explorer and that worked!
