### ISSUE TITLE
[Feature Request]: Use Custom Speed Settings for Smaller Incremental Adjustments and Control

### ISSUE THREAD

**Issue by Wajinn** [FreeTubeApp/FreeTube#6371]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Presently, YouTube allows custom speed settings, than gives the user small increment adjustments from 0 to 100. The jump from 75% to normal speed (100%) is too big.

### Proposed Solution

 Let the user make smaller adjustments, regarding playback speed. YouTube already has this ability. 

### Alternatives Considered

Other ways, outside of updating code, not available for the player.

### Issue Labels

improvement to existing feature

### Additional Information

N/A

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is already possible. Look in the Player settings

**Comment by absidue** [comment]
You can already configure the default playback rate, maximum playback rate and playback rate interval in the player section of the settings page.
