### ISSUE TITLE
[Bug]: RPM Error in POSTUN scriptlet in rpm package freetube

### ISSUE THREAD

**Issue by Cyborgscode** [FreeTubeApp/FreeTube#6373]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

# dnf update freetube-0.22.1-1.amd64.rpm 
...
  Vorbereitung läuft    :                                                                                                     1/1 
  Aktualisieren         : freetube-0.22.1-1.x86_64                                                                            1/2 
  Ausgeführtes Scriptlet: freetube-0.22.1-1.x86_64                                                                            1/2 
update-alternatives ist /sbin/update-alternatives

  Aufräumen             : freetube-0.22.0-1.x86_64                                                                            2/2 
  Ausgeführtes Scriptlet: freetube-0.22.0-1.x86_64                                                                            2/2 
/usr/bin/freetube wurde nicht als eine Alternative für freetube konfiguriert
Warnung: %postun(freetube-0.22.0-1.x86_64) Scriptlet fehlgeschlagen, Beenden-Status 2

Error in POSTUN scriptlet in rpm package freetube

Aktualisiert:
  freetube-0.22.1-1.x86_64                                                                                                        

Fertig!

### Expected Behavior

does not apply in this case

### Issue Labels

inconsistent behavior

### FreeTube Version

0.22.1-1

### Operating System Version

Fedora 40

### Installation Method

.rpm

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

unkown

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Preparation in progress : 1/1

Update : freetube-0.22.1-1.x86_64 1/2

Executed scriptlet: freetube-0.22.1-1.x86_64 1/2

update-alternatives is /sbin/update-alternatives

Cleanup : freetube-0.22.0-1.x86_64 2/2

Executed scriptlet: freetube-0.22.0-1.x86_64 2/2

/usr/bin/freetube was not configured as an alternative for freetube

Warning: %postun(freetube-0.22.0-1.x86_64) scriptlet failed, exit status 2

Error in POSTUN scriptlet in rpm package freetube

Updated:

freetube-0.22.1-1.x86_64

Done!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The RPM system logged the error and issued a warning, but since the main goal of updating the package to `0.22.1-1` was achieved, it did not abort the transaction. To resolve this, you might want to manually check and configure the alternatives if necessary. However, if FreeTube is working correctly after the update, you can generally ignore this warning.
