### ISSUE TITLE
[Bug]: Won't play age restricted Videos

### ISSUE THREAD

**Issue by tls188** [FreeTubeApp/FreeTube#6374]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click on any age restricted Video
2. it fails to play the video
3. It says I need to login at Invidious, which I am
4. can't play the video in Invodious either.

This issue is still in every new version that comes out, is this not possible for Freetube anymore?

### Expected Behavior

Playing the video like it used to

### Issue Labels

API issue

### FreeTube Version

v0.22.1

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

something like 0.18

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
https://github.com/FreeTubeApp/FreeTube/issues/6243#issuecomment-2509479808
