### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gibghost** [FreeTubeApp/FreeTube#6377]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

No hardware acceleration in latest version.

### Expected Behavior

I have been running freetube Setup 0.22.0-nightly-5082.exe to enable hardware acceleration in FreeTube. The latest version, Release v0.22.1 Beta, breaks hardware acceleration on my machine.

### Issue Labels

usability issue

### FreeTube Version

Release v0.22.1 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

Setup 0.22.0-nightly-5082.exe

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This is working as expected you downgraded from a nightly version that had the changes that you wanted to 0.22.1 which doesn't have the changes that you want, as it is just 0.22.0 + a few changes to the code that gets information from YouTube. In other words you didn't read the changelogs properly, downgraded and are now surprised that something that is not mentioned in the 0.22.1 changelog is not included in 0.22.1.

In the future if you want to use the nightlies stay on the nightlies and update to the lastest nightly regularly and read the changelogs properly before switching back to the release versions.

**Comment by gibghost** [comment]
Terribly sorry! I didn't realize that there were feature releases that were so far behind the nightly versions. The nightly I'm on is a month or so old. I'll just stay on nightlies until the change makes it to live as suggested.

**Comment by absidue** [comment]
0.22.1 is not a feature release (0.22.0 was) it was a hotfix release because of YouTube changes, so it only fixed that one specific thing.

They release versions are not far behind per-se, just like with most software projects, we don't do a release for every single pull request  that gets merged, as doing a release is a lot of work. We are volunteers that work on FreeTube in our spare time, if we wasted our time constantly doing releases, nothing would ever get done.

**Comment by gibghost** [comment]
Thanks for taking the time to respond. I wasn't meaning to waste your time (eventhough I inadvertently have!) I'll keep an eye out for the change I'm looking for. I appreciate what you all are doing. Keep up the good work!
