### ISSUE TITLE
[Bug]: MESA-INTEL: warning: cannot initialize blitter engine

### ISSUE THREAD

**Issue by TabKat** [FreeTubeApp/FreeTube#6378]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I am facing next issue

`$ freetube 
MESA-INTEL: warning: cannot initialize blitter engine
[23774:1214/045448.199182:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[23774:1214/045454.416604:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!`

My system

`$ uname -a
Linux tabkat-laptop 6.8.0-50-generic #51-Ubuntu SMP PREEMPT_DYNAMIC Sat Nov  9 17:58:29 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Expected Behavior

FreeTube is working in background.

### Issue Labels

causes crash

### FreeTube Version

freetube_0.22.1_amd64

### Operating System Version

Ubuntu 24.0.1 LTS

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Could you please clarify which version(s) of FreeTube you tested and experienced this issue with? In the FreeTube version section you put 0.22.1 but also ticked the latest nightly box. As those two things are very different, did you test both or only one of them, if it was one of them which one was it?

**Comment by TabKat** [comment]
Unchecked it. ;) I use last official build.

**Comment by absidue** [comment]
Can you please try passing `--enable-features=''` when launching FreeTube and see if that helps?

**Comment by TabKat** [comment]
Still have same issue:

`$ freetube --enable-features=''
MESA-INTEL: warning: cannot initialize blitter engine
[19657:1214/133436.014290:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[19657:1214/133439.793988:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!`

**Comment by zhfj1124** [comment]
From 0.22.0 to 0.22.1, some youtube videos cannot be played
 For example:https://youtu.be/oFz7tKjy-Ys
 This link is below https://www.youtube.com/channel/UCa6ERCDt3GzkvLye32ar89w
 All videos cannot be played, and they crash when they are played. Version 21.13 can be played.

**Comment by zhfj1124** [comment]
From 0.22.0 to 0.22.1, some youtube videos cannot be played
 For example:https://youtu.be/oFz7tKjy-Ys
 This link is below https://www.youtube.com/channel/UCa6ERCDt3GzkvLye32ar89w
 All videos cannot be played, and they crash when they are played. Version 21.13 can be played.

**Comment by warioishere** [comment]
@TabKat can you let us know what you did, I have the same issue

**Comment by absidue** [comment]
@warioishere Downgrade your graphics drivers.

**Comment by TabKat** [comment]
Hi @warioishere 
This is my current freetube.desktop config. Maybe it will help you.

`[Desktop Entry]
Name=FreeTube
Exec=/opt/FreeTube/freetube && sleep 2 && wmctrl -a "FreeTube" --disable-gpu --disable-software-rasterizer 
Terminal=false
Type=Application
Icon=freetube
StartupWMClass=FreeTube
Comment=A private YouTube client
MimeType=x-scheme-handler/freetube;
Categories=Network;
`

**Comment by absidue** [comment]
Love how your solution for broken GPU drivers is to just tell FreeTube to not use the GPU, instead going back to working GPU drivers.

**Comment by warioishere** [comment]
> Love how your solution for broken GPU drivers is to just tell FreeTube to not use the GPU, instead going back to working GPU drivers.

going back to the previous gpu drivers, which worked, didnt work for me...

I also have to start freetube with disable gpu now
