### ISSUE TITLE
[Feature Request]: video playback

### ISSUE THREAD

**Issue by billykd4dpb** [FreeTubeApp/FreeTube#6386]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

can you add the disappearing play and pause aka the arrow/ pause symbol as it is on YouTube. I use freetube for learning and loose content under the circles

### Proposed Solution

unknown

### Alternatives Considered

unknown

### Issue Labels

new feature

**Comment by absidue** [comment]
That is already possible with the existing settings: Settings -> Player -> Display Play Button in Video Player
