### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pycoed** [FreeTubeApp/FreeTube#6387]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I'm on Ubuntu 22.04 With Freetube 0.22. Every video  opens with a German language commentary. This doesnt happen in Youtube. My language preference is English (UK) my locale is UK. If I change the audio to English then all is OK, but I have to do this every time. Daughter on Windows 10 also reports the same...

### Expected Behavior

I expect the audio track to be in my preferred language.

### Issue Labels

usability issue

### FreeTube Version

0.22

### Operating System Version

Ubuntu 22.04

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.21

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Please read https://github.com/FreeTubeApp/FreeTube/issues/4291#issuecomment-2452527942
