### ISSUE TITLE
Use shorter youtu.be links instead of youtube.com for YouTube share links

### ISSUE THREAD

**Issue by dennis1248** [FreeTubeApp/FreeTube#639]
Currently when copying the link of a YouTube video you will be provided with the longer `https://youtube.com/watch?v=abcdefgh` URL which is less visually pleasing then the shorter `https://youtu.be/abcdefgh`. 

The reasons for me to suggest these changes are that the shorter URL is more visually pleasing as I already mentioned and it is to remain consistent with what YouTube does, when on YouTube you copy a video URL it will provide you with the shortened version. These shorter URLs are also easier to work with when copying them to for example a document or blog post.

**Comment by fatpowaranga** [comment]
I think I'll try to work on this

**Comment by GilgusMaximus** [comment]
> 
> 
> I think I'll try to work on this

Okay then I will assign you to this for the moment. If you have any questions, you can ask them here, or for a faster reply in our [Matrix](https://riot.im/app/#/room/#freetube:matrix.org) channel

**Comment by PrestonN** [comment]
Closed with #671
