### ISSUE TITLE
Remove the big "playing" and/or "paused" button at the middle of the screen

### ISSUE THREAD

**Issue by NomadVibes88** [FreeTubeApp/FreeTube#6407]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When hovering over a video, a big "playing" white button appears. This can make it hard to focus on the content. This also happens when a video is paused, then, a big "paused" white button appears, which also leads to the same issue.

### Proposed Solution

Remove the buttons but keep the functionality. That means, if hovered over a video, the buttons should not appear but the user can still click on it to pause/play the video.

### Alternatives Considered

None.

### Issue Labels

ease of use improvement, visual improvement

### Additional Information

![2024-12-18 09_55_58-Ludwig Situation Is Sad - FreeTube](https://github.com/user-attachments/assets/73bcb8b8-da50-4a95-abc0-ba8d8ca35950)

![2024-12-18 09_52_44-Ludwig Situation Is Sad - FreeTube](https://github.com/user-attachments/assets/304ae5ee-3e13-4a22-b7ad-72323d9e6d4e)

**Comment by onegladiator4u** [comment]
This is a duplicate . Search the closed issues also next time. 

Change Settings in Player -> Display Play Button in Video Player

**Comment by onegladiator4u** [comment]
This is a duplicate . Search the closed issues also next time. 

Change Settings in Player -> Display Play Button in Video Player

**Comment by Mumpfi3k** [comment]
There is no such Option in 0.22.1
