### ISSUE TITLE
New Languages Added: Hungarian

### ISSUE THREAD

**Issue by ovari** [FreeTubeApp/FreeTube#641]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [x] Languages
- [ ] Setup
- [ ] Other. Please specify:

**Question**
>* New Languages Added: Bulgarian, Greek, Hebrew, Portuguese, Slovenian
https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.9.0-beta

Should `Hungarian` be added to the list of `New Languages Added`?

Or is there something else that needs to be updated so that Hungarian is available?

Thank you

**Comment by lucanomax** [comment]
I'm not sure but i guess Weblate (https://github.com/FreeTubeApp/FreeTube/commits?author=weblate) merges automatically languages when they hit 100%

**Comment by ovari** [comment]
Hungarian is at 100% yet version 0.9.0 does not show in Hungarian. Is there another file that `hu` needs to be added to? Thank you

**Comment by ovari** [comment]
The file with all the `hu` translations is located at:
https://github.com/FreeTubeApp/FreeTube/blob/development/static/locales/hu.yaml

**Comment by lucanomax** [comment]
@ovari I see it at 99%, I think weblate is triggered at 100% (i'm not sure).

**Comment by PrestonN** [comment]
New languages need to be enabled manually, which is why you don't see it within the app itself.  I've gone ahead and enabled it within out dev builds.  You can either download one of those builds or wait for the next release.

**Comment by ovari** [comment]
Thank you for activating at https://github.com/FreeTubeApp/FreeTube/commit/41144135fcf057d159b409863e83c400b6dd1a13.

**Comment by ovari** [comment]
> wait for the next release

@PrestonN do you have an ETA for the next release?

It will enable those who enjoy the version from [Flathub](https://flathub.org/apps/details/io.freetubeapp.FreeTube) to receive your program.

Thank you
