### ISSUE TITLE
[Bug]: Can't open FreeTube link when windows are closed

### ISSUE THREAD

**Issue by MStankiewiczOfficial** [FreeTubeApp/FreeTube#6410]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open FreeTube
2. Close FreeTube window (but do not quit the app)
3. Open any YT link with `freetube://` protocol
4. The following error appears on the screen:
<img width="372" alt="Error" src="https://github.com/user-attachments/assets/0bb2e468-9639-4d6f-93d4-207247b021dd" />

The error occurs only when no FreeTube windows are open.

### Expected Behavior

A FreeTube window should open with the content of the link.

### Issue Labels

causes crash, inconsistent behavior, usability issue

### FreeTube Version

0.22.1

### Operating System Version

macOS Sequoia 15.1.1 (24B91)

### Installation Method

.dmg

### Primary API used

Local API

### Additional Information

This problem was already mentioned by @srolandmarshall in https://github.com/FreeTubeApp/FreeTube/issues/4762#issuecomment-2464673877

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by srolandmarshall** [comment]
@MStankiewiczOfficial I believe this has been addressed here: https://github.com/FreeTubeApp/FreeTube/pull/6278#event-15586582363 and is set for future release

**Comment by absidue** [comment]
Yes, this has already been solved in the development branch, so I'll close this bug report.
