### ISSUE TITLE
Resolution button fix

### ISSUE THREAD

**Issue by NomadVibes88** [FreeTubeApp/FreeTube#6412]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When I want to change the resolution, I have to click on the gear icon, which is a bit weird since it's typically associated with settings and not resolution. 

### Proposed Solution

Change the gear icon to something else or move a couple of options into it. I think the playback speed and audio track options can be moved since they aren't required all of the time.

### Alternatives Considered

None.

### Issue Labels

ease of use improvement, improvement to existing feature, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is a non issue and we have other plans for the gear icon anyway
