### ISSUE TITLE
[Bug]: Audio Language will default to random foreign language

### ISSUE THREAD

**Issue by signmeuptwice** [FreeTubeApp/FreeTube#6428]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1 - watch video (english)
2 - next video on playlist will change its language to something other than english

### Expected Behavior

keep default english language

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

0.22.0 (0.22.0)

### Operating System Version

mac os sequoia

### Installation Method

.dmg

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

don't remember

### Additional Information

I can't reproduce the bug reliably. Not sure if this is a bug. Would be solved by https://github.com/FreeTubeApp/FreeTube/issues/4291

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Please read: https://github.com/FreeTubeApp/FreeTube/issues/4291#issuecomment-2452527942
