### ISSUE TITLE
[Feature Request] Downloading Playlists

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#643]
**Describe the solution you'd like to see implemented**
Button for downloading all videos of a playlist with numbering in a folder named by playlist title

**Describe alternatives you've considered**
Like using youtube-dl to download videos/playlist

**Comment by GilgusMaximus** [comment]
This will come at a later point int time probably.
At the moment basic downloading was implemented by PrestoN to allow it. But a more feature rich way is planned like he explained in #582

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2374
