### ISSUE TITLE
[Bug]: Window becomes unresponsive with spotty internet connection

### ISSUE THREAD

**Issue by wd40chug** [FreeTubeApp/FreeTube#6434]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Have video actively playing
2. Have intermittent internet sever connection

https://github.com/user-attachments/assets/4631e263-6c8e-4906-bb22-38c4b2bf44bb

### Expected Behavior

Window becomes unresponsive to all UI elements, resizing window
Does not revert to invidious api, throw up standard error messages, or resume playback after connection is restored
Manually disconnecting from wifi/unplugging ethernet cable does not reproduce bug
Resolved by closing, rebooting Freetube 
Bug did not appear in earlier versions (0.20.0, 0.19.2)

### Issue Labels

feature stopped working

### FreeTube Version

v0.22.1

### Operating System Version

Windows 10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.20.0 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please try the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds) to check if that resolves the issue.

**Comment by wd40chug** [comment]
So far unable to replicate bug with v0.22.1-nightly-5342. Great!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I will be closing this. Dont hesitate to reach out if the reoccurs

**Comment by Hello-World-Traveler** [comment]
Updated to 22.1, still happens using app image.
