### ISSUE TITLE
[Feature Request]: Default Landing Page Options: Search

### ISSUE THREAD

**Issue by misterhackerman** [FreeTubeApp/FreeTube#6435]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Default landing page options doesn't have Search page option.
when you launch the application ( usually with a shortcut ) and start typing it would type in the search bar, until you click on it or alt+d 

### Proposed Solution

Adding a "Search Page" option to Default Landing Page in General Settings.
A page with a central search bar. that is ready to type in once the application has started.

### Alternatives Considered

Default Landing Page : Blank, with a page nothing on it with the same search / go to url bar, already active and ready to type in on startup.

### Issue Labels

ease of use improvement

### Additional Information

This will help for a distraction free environment, as it will only show you the search bar, so that you search for what you need only.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
There is no search page so it cant be the default.

**Comment by misterhackerman** [comment]
at least could the search bar be active on start
