### ISSUE TITLE
[Bug]: Random thumnails even without DeArrow

### ISSUE THREAD

**Issue by Magikh42** [FreeTubeApp/FreeTube#6447]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Disable DeArrow thumbnail and go to a channel or use the search

### Expected Behavior

Video use custom thumbnails
Current behaviour: DeArrow like (random) thumnails

### Issue Labels

visual bug

### FreeTube Version

0.22.1 beta

### Operating System Version

EndeavourOS

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Im unable to reproduce this. Please upload a screenrecording of this behavior:

1. Enable DeArrow
2. Go channel or use search
3. Go to settings to disable DeArrow
4. Do the same as 2

**Comment by Magikh42** [comment]
https://github.com/user-attachments/assets/36aec7a4-c63a-4d49-b9ae-43767ba965c1

**Comment by Magikh42** [comment]
I found the reason
There is a setting called thumbnail preference that I changed by mistake
![image](https://github.com/user-attachments/assets/9c7a23a2-ab9c-4867-9e88-c97a4cbae03a)
Sorry for creating an issue
