### ISSUE TITLE
[Feature Request] API customization for searching and playing videos

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#645]
**Describe the solution you'd like to see implemented**
There should be a switch for API customization. Like searching videos with Invidious API & playing with Local API or vice versa

**Additional context**
I think it will a great privacy feature & will help reducing rate limiting and searching more faster or fetching RSS feeds or to fix subscribers counter bugs (still showing 0 on automated builds)

**Comment by PrestonN** [comment]
It's something to keep in mind, but doing this will likely require a lot of work to put together to account for every function that uses the API.  We can limit this change for only major parts of the app but 

With v0.9.0, I included a change to force RSS if you have a lot of subscriptions, so we'll see how common the rate limiting is in the next week or so.  If users are still having issues we can decide on what needs to be done to further prevent it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/3048
