### ISSUE TITLE
Auto expand comments

### ISSUE THREAD

**Issue by NomadVibes88** [FreeTubeApp/FreeTube#6451]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

(Not an issue.) On YouTube, the comments are expanded automatically. This should be on FreeTube as well.

### Proposed Solution

Expand the comments automatically instead of making it a button or add it as a setting.

### Alternatives Considered

None.

### Issue Labels

display more information to user, ease of use improvement, improvement to existing feature, new optional setting, visual improvement

### Additional Information

YouTube:
![2024-12-24 22_30_37-STOP CONSUMING SLOP!!! Play These Indie Games Instead  - YouTube - Brave](https://github.com/user-attachments/assets/b1cda052-9e29-4278-8e08-a493987aedb9)
FreeTube:
![2024-12-24 22_30_15-I followed a bunch of tutorials on how to get taller - FreeTube](https://github.com/user-attachments/assets/380f6df4-de15-4699-a151-8a4dac2b6ce2)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Settings -> General -> Auto Load Next Page
