### ISSUE TITLE
[Bug]: Videos freeze immediately when played

### ISSUE THREAD

**Issue by max-lab-641** [FreeTubeApp/FreeTube#6452]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I launch FreeTube from the command line.  This is what results:

[2:1224/203236.947411:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 20:32:37.125: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:32:37.125: Failed to load module "pk-gtk-module"
Gtk-Message: 20:32:37.126: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:32:37.126: Failed to load module "pk-gtk-module"
[2:1224/203237.143659:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1224/203237.143716:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[46:1224/203310.572901:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[46:1224/203310.585554:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!

### Expected Behavior

I expect the video to play, instead of simply stopping at the first frame.  It seems as if it's not buffering properly, but I am not an expert in this.

### Issue Labels

feature stopped working

### FreeTube Version

0.22.1 Beta

### Operating System Version

Fedora 41, Gnome 47

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

Not sure

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
should be fixed by https://github.com/FreeTubeApp/FreeTube/pull/6180

**Comment by max-lab-641** [comment]
I don't understand #6180, so this is not completed.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This isnt platform related.

**Comment by max-lab-641** [comment]
OK, thanks.  How is it fixed?
