### ISSUE TITLE
[Feature Request]: Disable search bar autocomplete

### ISSUE THREAD

**Issue by Magikh42** [FreeTubeApp/FreeTube#6453]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I think a setting in distraction free to disable autocomplete in search bar could be useful

### Proposed Solution

Add this setting in distraction free settings

### Alternatives Considered

Using other frontends

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Go to Settings -> General -> Enable Search Suggestions to disable this

**Comment by Magikh42** [comment]
Thank you, I was looking in the wrong section
