### ISSUE TITLE
[Bug]: Dizzy video playing

### ISSUE THREAD

**Issue by iFabse** [FreeTubeApp/FreeTube#6457]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

![Screen Picture of Error](https://github.com/user-attachments/assets/8fc6cefd-3479-483e-ba80-262aa02b3f8f)

Hey y'all I wonder if anybody else has this problem of viewing a video with these strokes. Sound is working but the video not :(

Is this a settings issue ?
It's no hardware issue because it is working under windows with the same versions

### Expected Behavior

Should display a normal moving image - a video. And not these strokes.

### Issue Labels

visual bug

### FreeTube Version

v0.22.1 Beta and testet with v0.22.0 Beta

### Operating System Version

Fedora 41 with GNOME (wayland)

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please check the following:
1. Is this issue also occurring on a Chromium based browser when playing a video on YT?
2. Try updating the graphics drivers 
3. Check the graphics settings and turning some dials to see if that improves the situation 
4. This could also be caused by certain monitor settings so check the settings van turn some settings off/on

**Comment by iFabse** [comment]
1. Same video is playing without any problems at youtube.com with the ungoogled chromium browser.

2. There was an intel media driver update but it didn't resolve the problem.

3. I have no graphics setting - I have the Intel Core Ultra 7 155H.

4. I have an 14 inch monitor (I use a converible) and played with the screen resolutions and scales. But no luck.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
could you please try running FreeTube with --enable-features=''

**Comment by iFabse** [comment]
Jup that worked. What is --enable-features doing? Thanks :)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Good to hear that its working for you. This flag overrides freetube turning on VA-API
