### ISSUE TITLE
[Bug]:  [BAD_HTTP_STATUS: 403] Potential causes: IP block or streaming URL deciphering failed

### ISSUE THREAD

**Issue by EvilGremlin** [FreeTubeApp/FreeTube#6458]
### Describe the bug
We have another iteration of youtube's war on 3rd party clients.
Any video, through local and invidious, direct and VPN throws out `[BAD_HTTP_STATUS: 403] Potential causes: IP block or streaming URL deciphering failed`
yt-dlp fails with 403 as well.
Funnily enough, Youtube's own embeds also fail to load now.

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

v0.22.1 Beta

### Operating System Version

Ubuntu 24.04

### Installation Method

.deb

**Comment by absidue** [comment]
Duplicate of #6385
