### ISSUE TITLE
Add setting to always play videos in fullscreen

### ISSUE THREAD

**Issue by Brier1104** [FreeTubeApp/FreeTube#647]
A setting to always play videos in full screen mode would be great.

**Comment by saideepesh000** [comment]
@PrestonN, Hi, I would want to work on this, just let me know, from where(file) can I start working on this, should we use [BrowserWindow](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions) for this. Thanks

**Comment by PrestonN** [comment]
Hi @saideepesh000 we would be more than happy to have a PR for this feature.  To help you get started, I'll let you know what needs to be done in order for us to accept a PR for this.

1. A new setting will need to be create in the player settings.  Follow the syntax of the other toggle switches to create this setting.  A suggested label should be "Full Screen Video on Start" for the toggle switch.  This string will need to be included in the English translation file within your PR.
2. All of the logic you'll need is already located in the [ft-video-player](https://github.com/FreeTubeApp/FreeTube/blob/development/src/renderer/components/ft-video-player/ft-video-player.js) component.  The component should check the setting within the `initializePlayer` function and full screen the player.  You can call `this.player.requestFullscreen()` to enable full screen.

Feel free to ask here or submit a draft PR if you have any questions with this.

**Comment by saideepesh000** [comment]
@PrestonN, It's so nice of you to help others by explaining the details to get started, definitely I would want to solve this issue, but I need some time, thanks.

**Comment by saideepesh000** [comment]
Hey @PrestonN, Should I add the translation of the string "Enable FullScreen Mode by Default" for every locale file.

**Comment by PrestonN** [comment]
For adding new locale strings, you only have to add the new strings to the en_US file. Weblate will automatically add the string to the rest of the files for you.

**Comment by saideepesh000** [comment]
> For adding new locale strings, you only have to add the new strings to the en_US file. Weblate will automatically add the string to the rest of the files for you.

Oh I didn't know that, so is that string (Enable FullScreen Mode by Default) OK for you.

**Comment by PrestonN** [comment]
Yes, that's a good string for the new option. Apologies for not answering that as well.

**Comment by saideepesh000** [comment]
Hey @PrestonN @GilgusMaximus , you could add this to in-progess column of 0.12.0 roadmap.

**Comment by PrestonN** [comment]
Done!

**Comment by jasonhenriquez** [comment]
Consider #1629 when implementing this to account for the case when this future setting is disabled.

**Comment by Gevaarlijk** [comment]
I would love to see this feature implemented.

**Comment by lazyb5** [comment]
Any movement on this feature?

**Comment by azurusnova** [comment]
Just signal boosting here because this feature would be amazing to have. 
Is there any updates?

**Comment by jasonhenriquez** [comment]
We are currently putting player-related changes on hold due to the ongoing player migration. We'll do our best to mark these accordingly and revisit / boost them for newer contributors once we're complete.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/5427
