### ISSUE TITLE
[Feature Request]: Add Right-Click Action from a browser to Open YouTube Videos in FreeTube

### ISSUE THREAD

**Issue by Helloben231** [FreeTubeApp/FreeTube#6474]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently, users who want to watch YouTube videos in FreeTube must manually copy the video title/URL, open FreeTube, and paste the title, and search to find the video to play. This process is inconvenient and detracts from the seamless user experience.

### Proposed Solution

Introduce a browser plugin (e.g., for Chrome, Edge) that adds a "View in FreeTube" option to the context menu when right-clicking on a YouTube video or link. Selecting this action would automatically open the video in FreeTube, streamlining the process.

Youtube already has a good algorithm to suggest new videos, so its easier to find new content to watch on FreeTube.

### Alternatives Considered

- A browser extension that automatically redirects all YouTube links to FreeTube by default. However, this could disrupt user workflows if they occasionally prefer to watch on YouTube.

- A clipboard integration within FreeTube that detects copied YouTube URLs and prompts the user to open them. This still requires manual copy-pasting and isn’t as convenient as a right-click action.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
https://github.com/FreeTubeApp/FreeTube?tab=readme-ov-file#browser-extensions
