### ISSUE TITLE
[Bug]: Remove previous pasted search title/url when "right arrow" or video thumbnail is clicked

### ISSUE THREAD

**Issue by Helloben231** [FreeTubeApp/FreeTube#6475]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Video tltle/url is pasted
2. User clicks on right arrow to "search"
3. Video is playing
4. Old title/URL still remains in search bar

### Expected Behavior

- Search bar needs to clear the old search title/url when a video is selected to play.
- Search bar filled content title/url should remain only when the user is still searching for a video

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.22.1 Beta

### Operating System Version

Windows 11 Pro - Version 24H2 - OS Build 26100.2605

### Installation Method

.apk (Alpine Linux Package)

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
this isnt a bug and is working like expected.
