### ISSUE TITLE
[Feature Request]: Volume interval

### ISSUE THREAD

**Issue by KaKi87** [FreeTubeApp/FreeTube#6477]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The amount of steps that audio volume increments/decrements by when using the scroll wheel or arrow buttons is not customizable.

### Proposed Solution

Add a *volume increment/decrement interval* option next to the *fast-forward/rewind interval* option.

### Alternatives Considered

None

### Issue Labels

new feature, new optional setting

### Additional Information

None

---
Thanks

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
What increments do you propose. Its currently doing 5%. I dont see a reason to do increments lower than that or higher than 10%

**Comment by KaKi87** [comment]
1%. That's what I use on youtube.com with the ImprovedTube extension.

Thanks

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
What is the max that it provides?

**Comment by KaKi87** [comment]
10.

But, as power users, none of us see why anyone would want any value different from ours, that's how we are.

With that in mind, I would like to suggest not putting any limitation, as letting the user do whatever they want costs nothing in this case.

So, I would like to suggest 100.

Thank you

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Tbh i have a hard time seeing the justification for this one compared to video playback rate interval or fast forward/rewind interval. I think its best to leave this to the OS

**Comment by KaKi87** [comment]
> I think its best to leave this to the OS

If this reasoning was followed, then volume control would be removed from the player altogether :sweat_smile:
