### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by maboroshin** [FreeTubeApp/FreeTube#648]
Hi! Developper. What does it mean?
* Forcing RSS to avoid rate limiting

It has been changed to "bypass connection limit" on Japanese.

I've been translating for a year. kyotaro has rewritten hundreds of strings.
His quality is not bad.

But, Practices not found in the Japanese translation guidelines of Wordpress (Or other, Wikipedia etc), for example
* Use two-byte characters in space / brackets. (strange rule)
* Or the insertion of an space. (strange rule)

Strange notations have increased greatly.

* Some of the Japanese language is changed back to English.
* But in some cases, the Chinese characters have been changed to numbers

What should I do? I think we might as well discuss it here. What do the developers think?

**Comment by PrestonN** [comment]
Hello!  I'll try to help however I can.

At the end of the day, I have to rely on the translators of their respective language to make the right calls as I won't be able to check their work.  So if there are problems with the translation itself feel free to take advantage of the features within Weblate to discuss changes with other translators.

As for your question, changing it to "Bypass connection limit" should still make sense.  YouTube can sometimes block you if you make too many connections, and sometimes this block can occur depending on how you use FreeTube.  Grabbing subscriptions is one of the main reasons that this block happens, so we'll enable RSS automatically if you have a lot of subscriptions, hence why RSS is "forced".  In this context, "Bypass connection limit" should still work.

Hope that answers your question.

**Comment by maboroshin** [comment]
Thank you for the answer to my first question. I understand.

In a metaphor, he changed the code notation to his rules.  The weblate commenting feature is poor for discussing this issue. 

There are nearly 200 changes. So many to discuss individually.  Also, weblate comments are difficult to use. We have to open them all individually.

**Comment by maboroshin** [comment]
@PrestonN I'm in trouble. These are more than constructive arguments.

Kyotaro is reverting back to a mistranslated version without checking the UI. This is after I explained it.

e.g.
* My work: Switch to Cinema Mode シネマモードの切替 (switch on/off)
* Kyotaro : Change into Cinema Mode シネマモードに変更 (one way)

Most of the discussion is about things like code notation and personal preference. He doesn't define right.

**Comment by maboroshin** [comment]
@PrestonN Kyotaro rpeated misinterpretations of the above. Also discussions like code notation.

He changes "distraction" to "eyesore" over and over again. https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=4f31aa2fe6ba3241 I don't think that was your intention.

You can read my arguments in English.

**Comment by maboroshin** [comment]
@GilgusMaximus

It means we will have a discussion on Weblate. But it's been massively popular from the start.

Rules like code notation will need to be discussed collectively. We've should view all each comments, so the discussions are scattered.

The explanations can also reflect, in part, the intentions of the developers: they can change the access rights of Weblate.

**Comment by PrestonN** [comment]
I've taken some time to look into this, and unfortunately it isn't looking too good.

Long story short, there isn't really anything I can do to prevent these changes from happening.  Weblate does not offer any method to prevent select users from making changes to translations.  The only limiting that I can do would be to lock out every single translation at once, which would obviously punish the other languages that don't have a similar issue.

I don't really have a good solution for this.  Even if I leave a comment saying to take your suggestions over their own, there isn't anything I can do to them if they ignore my request.

The only thing we can do is ask Weblate themselves to add some better protections with their service, as it doesn't seem like they provide anything in it's current state.

Unfortunately I'm going to have to close this, as I won't be able to help.  Really sorry for the inconvenience.

**Comment by maboroshin** [comment]
@PrestonN : Thank you for your research. I understand.

There are currently dozens of issues to discuss, and it will take several hours of response to discuss this. Weblate is not suitable for mass discussion; you need 10 windows for 10 comments. A github to integrate this has been closed by the developers. I've probably spent 10 hours on this discussion.

For example, On Wordpress.org we can only do translation suggestions at first, but then we will be granted direct editing rights. If there are no problems, we will then be granted direct editing rights.

Finally, I have attempted to report a decline in translation quality. The developer has closed this too.

Ultimately I also decided it was unproductive to spend a lot of time on it. Thank you.

**Comment by maboroshin** [comment]
In https://github.com/FreeTubeApp/FreeTube/issues/714#issuecomment-1286745418 : @absidue said: 
>  we can't do anything to stop specific people translating.
> There is nothing we can do from our side. Please complain to weblate directly, not us. We can't fix the problem from our side.

I understand. I also understand some reasons.
* Weblate's free plan (libre plan) has no access control. This is because Weblate is selected. Will it change by contacting Weblate? This is Weblate's means of income. [Access controll](https://docs.weblate.org/en/latest/admin/access.html#access-control) (Weblate) Transifex has this. Crowdin is unknown, but at least the admin can be a reviewer.
* FreeTube says to ask to Weblate. But, Weblate says to ask to FreeTube.
>For questions about a specific translation project, contact its maintainers directly, not by this form. :  [Contact](https://hosted.weblate.org/contact/) (Weblate)
* Weblate doesn't have a code of conduct. [GitHub](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#c-acceptable-use), [Transifex](https://community.transifex.com/faq#improve), and [Crowdin](https://support.crowdin.com/terms/) have this.

On Weblate, only 10 logs are displayed, including comments and changelogs. I have issued an issue. https://github.com/WeblateOrg/weblate/issues/8254

**Comment by maboroshin** [comment]
In https://github.com/FreeTubeApp/FreeTube/issues/714#issuecomment-1286807262, @absidue said :

> Talking about guidelines, you've clearly not read [our contributing guidelines](https://github.com/FreeTubeApp/FreeTube/blob/development/CONTRIBUTING.md):
>
> > Do not include non-free software or modules with your code.
>
> We will not be switching to closed source proprietary translation platforms.

The purpose of this is to protect the free license. For example, using Transifex does not include code. It does not violate the free license. [Transifex is the world's largest localization community for open source projects](https://explore.transifex.com/)

**Comment by absidue** [comment]
As clearly stated in our contributing guidelines, we will not be using proprietary software for or in FreeTube. Please respect our projects guidelines. Please stop using multiple issues for the same thing, the other issue was closed because it's for the same thing.

Transifex is closed source, if you can come up with a good platform that is open source we could consider it, until you do we will be sticking with weblate.

**Comment by maboroshin** [comment]
@absidue It is not the same issue. 
 
Can you include code of Transifex? Many open source software use Transifex or Crowdin. This is because the code does not include them.

**Comment by ChunkyProgrammer** [comment]
Using something that is closed source would be a deterrent to a lot of FreeTube contributors (as we're a privacy respecting application). If you can find another open-source alternative to weblate, feel free to share it and we can look into migrating to it if it's a viable option but I think opening an issue for better moderation tools on the weblate repo and linking to your issues would probably be your best bet. Weblate repo: https://github.com/WeblateOrg/weblate/

**Comment by maboroshin** [comment]
What is Weblate doing about contributors' privacy? Have you ever investigated this issue?

I was most concerned Weblate about privacy . So I using a Weblate-only email address. Not explicitly stated. but this leads to the publication of the e-mail address (At 2019): https://github.com/WeblateOrg/weblate/issues/3105

Open source is not about security. [Transifex](https://www.transifex.com/legal/security/) and [Crowdin](https://crowdin.com/page/security) are committed to security measures, both physical and virtual.

**Comment by maboroshin** [comment]
> but I think opening an issue for better...

I have already created an editorial problem on Weblate. Including not being able to see old comments. https://github.com/FreeTubeApp/FreeTube/issues/648#issuecomment-1286768296

Weblate is a business. So access control is a paid feature. Did you request Weblate to make this free?

**Comment by maboroshin** [comment]
Open https://liberapay.com/FreeTube/ at https://archive.org/ . We can see "open" "transparent" donation amounts. However, the use of excess donations is "closed". Donations via cryptocurrency are unknown. 

In most months since 2021, PrestonN has received around $40 in donations. 40 * 52 (Weeks, 1 year) = $2080 . And he says he needs about $400 per year. So the remaining donation is $1,600 per year by liberapay only. All cryptocurrencies are surplus donations.

For some reason, the FreeTube developers are sticking with the open source Weblate. One developer incorrectly stated that open source tools should be used. It appears so. But, They do not make feature requests to Weblate. Access control will remain paid.

Other translation sites offer free access control. But, Weblate's access control appears to be a paid feature. However, there does't seem to be a problem with donations.

Now is the time to charge Weblate to give back to donors.

**Comment by maboroshin** [comment]
Open https://liberapay.com/FreeTube/ at https://archive.org/ . We can see "open" "transparent" donation amounts. However, the use of excess donations is "closed". Donations via cryptocurrency are unknown.

In most months since 2021, PrestonN has received around $40 in donations. 40 * 52 (Weeks, 1 year) = $2080 . And he says he needs about $400 per year. So the remaining donation is $1,600 per year by liberapay only. All cryptocurrencies are surplus donations.

For some reason, the FreeTube developers are sticking with the open source Weblate. I don't recommend Weblate because of the privacy information disclosure. The developer has chosen Weblate. One developer incorrectly stated that open source tools should be used. It appears so. But, They do not make feature requests to Weblate. Access control will remain paid.

Other translation sites offer free access control. But, Weblate's access control appears to be a paid feature. However, there does't seem to be a problem with donations. The developer gets five times the required annual donation. There is a big surplus of money.

Now is the time to charge Weblate to give back to donors.

**Comment by maboroshin** [comment]
@FreeTubeApp I will report you to GitHub for the destructive removal of serious comments. Please do not repeat.
