### ISSUE TITLE
[Feature Request]: Refresh Automatically With a Timer

### ISSUE THREAD

**Issue by crisjolliff** [FreeTubeApp/FreeTube#6486]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Requesting a switch or slider to refresh/reload videos in feed automatically on a period set by user, or on a small selection of preset time periods.

### Proposed Solution

- Add a slider to Settings page, forcing refresh of subscriptions page based on slider position with 1- or 5-minute increments.
- If 0 (zero) minutes is selected, this should turn OFF automated refresh. 
- This will complement the following feature request: https://github.com/FreeTubeApp/FreeTube/issues/5140
- This will require the "feed last updated" message to ALSO be updated, just as when you hit the refresh button manually.

### Alternatives Considered

This could be achieved with an on/off switch and a fixed refresh rate (I suggest 15 minutes or less, but not more) if a simpler solution is desired.

### Issue Labels

improvement to existing feature

### Additional Information

This is hardly necessary, but would be a nice-to-have feature enhancement.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I think its best to not implement this because we dont want users to get rate limited
