### ISSUE TITLE
Subscription categories?

### ISSUE THREAD

**Issue by maharg** [FreeTubeApp/FreeTube#654]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Having many subscriptions in one long list is annoying to scroll through and channel names often don't tell you what the channel is about making a subscription list less useful.

**Describe the solution you'd like to see implemented**
I would like a way to sort subscriptions into categories so I can look at all my channels for a particular topic I'm interested in at once. So, for instance, if I were looking for updates to any channels that cover VR, I could look in the VR category and see if there are any new videos in those channels. This also lets me know that the channel "DavesUberShow" in the VR category is about VR. If it's in one long list and I don't watch that channel often or videos are updated infrequently, I don't necessarily remember what it is and so have to click the channel to see.

**Describe alternatives you've considered**
Currently, I am stuck looking through a long list of subscriptions every morning to find any updates, click the channel, find the latest video and add it to my watch later playlist if I'm interested. Maybe an alternative would be to push a button to make a playlist automatically of all videos within the last 24 hours that I haven't watched from all my subscriptions. That may be easier.

**Screenshots**
Sometimes people have screenshots from mock-ups or other projects. Add them here.

**Additional context**
Add any other context about the feature request here.

**Comment by PrestonN** [comment]
Create a profile then?  Click the top right icon and hit the settings button that shows up.  We already offer this.

**Comment by maharg** [comment]
Oh, thanks!
