### ISSUE TITLE
Show creator-liked badge on comments

### ISSUE THREAD

**Issue by thansk** [FreeTubeApp/FreeTube#655]
Some comments are liked by the uploader of the video and the comment has an icon next to it on YouTube and Invidious. It would be useful to add it to FreeTube too.

**Comment by GilgusMaximus** [comment]
If someone wants to implement that, please head over to the module's [repository](https://github.com/GilgusMaximus/yt-comment-scraper) and add the information to the returned values as well as here a display for that is needed.

I saw that it is possible to get the information whether something was given a heart, but I didn't bother trying to get it out of the HTML.
