### ISSUE TITLE
Download Links aren't opening up properly in Linux

### ISSUE THREAD

**Issue by boistordu** [FreeTubeApp/FreeTube#659]
in which kind of program we should use the download link? The browser on linux doesn't work apparently so what is your advices about that?

**Comment by PrestonN** [comment]
Sounds like you need to set your default browser.  If a browser isn't set then FreeTube won't know where to send the link to.

If we really needed to, we could add a toggle to add the link to your clipboard instead of opening in the browser.  Wouldn't be too big of a change.

**Comment by PrestonN** [comment]
In Firefox you'll have to right click and "save page as". That should give you the prompt to download the video.

**Comment by boistordu** [comment]
not really working no. The file is 0 byts. So maybe it's my private settings or maybe it's just the fedora version of firefox

**Comment by thansk** [comment]
On Ubuntu 20 with Firefox, it just opens the googlevideo mp4 link in Firefox and I can easily press Ctrl+S or Right Click and `Save Video As...`

**Comment by GilgusMaximus** [comment]
This in the end is not really a FreeTube related problem, but a problem with your browser. Unfortunately there is nothing we can do here. 

My advice would be to install the same fedora in a vm, use the default Firefox with default settings and test whether it works. If not, a bug report over at the Firefox repo would be appropriate
