### ISSUE TITLE
Live videos in the recommmended section show up as undefined

### ISSUE THREAD

**Issue by thansk** [FreeTubeApp/FreeTube#660]
Expected behaviour is to show up as "LIVE" as they do on the search page.
![image](https://user-images.githubusercontent.com/53181514/95893832-bf7f6a80-0d77-11eb-96b6-bc2d25fdd87f.png)

**Comment by PrestonN** [comment]
This is an upstream issue, I'll create the issue to the appropriate repository and link back here.  When the fix has been made, I will update the module on my end and we should be good.

**Comment by Synkky** [comment]
What do intend to suggest upstream? A boolean "isLive" field for each recommended video?

**Comment by PrestonN** [comment]
That' pretty likely.  I imagine it might not be a priority to include though.
