### ISSUE TITLE
A lot of warnings in output ot Freetube

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube#663]
I see a lot of warnings like this

WARNING in ./src/renderer/components/ft-icon-button/ft-icon-button.sass?vue&type=style&index=0&id=78e93bce&scoped=true&lang=sass& 1:364-367
"export 'default' (imported as 'mod') was not found in '-!../../../../node_modules/mini-css-extract-plugin/dist/loader.js??ref--3-0!../../../../node_modules/css-loader/dist/cjs.js!../../../../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../../../../node_modules/sass-loader/dist/cjs.js??ref--3-2!./ft-icon-button.sass?vue&type=style&index=0&id=78e93bce&scoped=true&lang=sass&'
 @ ./src/renderer/components/ft-icon-button/ft-icon-button.vue
 @ ./node_modules/babel-loader/lib!./src/renderer/views/Popular/Popular.js?vue&type=script&lang=js&
 @ ./src/renderer/views/Popular/Popular.js?vue&type=script&lang=js&
 @ ./src/renderer/views/Popular/Popular.vue
 @ ./src/renderer/router/index.js
 @ ./src/renderer/main.js

**Comment by GilgusMaximus** [comment]
The warnings should not hinder the normal usage of the application, also we fixed a lot of things that might be related. If something doesn't work please open a corresponding issue for that
