### ISSUE TITLE
Can't import youtube subscriptions

### ISSUE THREAD

**Issue by Stormcloakbloke** [FreeTubeApp/FreeTube#664]
I am trying to import my youtube subscriptions to freetube on manjaro linux. I go to the youtube subscription manager and download the opml file. When I try to import the file onto freetube the file doesn't appear in my downloads even though it's definitely there in the file manager. Any ideas on why this is happening and how to fix would be greatly appreciated.

**Comment by Synkky** [comment]
Are you sure you're choosing the correct option?
There's both an "Import Subscriptions" and an "Import History" button. You'll obviously want the "Import Subscriptions" button.
Also, there's three distinct formats for importing subscriptions: FreeTube (.db extension), Youtube (which is what you want, .opml extension) and NewPipe (.json extension).

**Comment by GilgusMaximus** [comment]
It might be the solution of https://github.com/FreeTubeApp/FreeTube/issues/577

**Comment by Synkky** [comment]
I'm confused.
I don't have a Youtube account anymore, but does the subscriptions file exported from YouTube not have the .opml extension?
Is it .json? That's the only way I can see someone having a problem with this.

**Comment by alidan** [comment]
import the xml, it may fail so import it again.

**Comment by GilgusMaximus** [comment]
> 
> 
> I'm confused.
> I don't have a Youtube account anymore, but does the subscriptions file exported from YouTube not have the .opml extension?
> Is it .json? Or does it not have an extension at all? That's the only way I can see someone having a problem with this.

There seems to be no extension to the file. So adding that will make it appear in the file searcher

**Comment by alidan** [comment]
click the opml import, it will have the xml as an import option, it may fail to import form that but it does work so re try

**Comment by chardo137** [comment]
Free Tube 0.9.1 (latest version available in the AUR) will not import an .opml subscription file from youtube. Pretty easy to figure out to append the .opml to the file to be able to find it, but although there is a progress bar that seems to get to about 99% before stopping, the import process never completes.

**Comment by ThisNekoGuy** [comment]
Has YouTube disabled exporting...?
I went to the bottom of the subscriptions manager and saw that there wasn't an export button at all... >_>

**Comment by GilgusMaximus** [comment]
@ThisNekoGuy please take a look at the FAQ regarding this

**Comment by ThisNekoGuy** [comment]
@GilgusMaximus Where is the FAQ? I haven't seen one literally anywhere

**Comment by ThisNekoGuy** [comment]
Nevermind, I managed to find the FAQ but found that YouTube returns my subscriptions as JSON instead of OPML, so the import process doesn't work.

**Comment by PrestonN** [comment]
As mentioned in our import instructions, the current v0.9.2 release of FreeTube does not support the recent changes for importing that was made to YouTube.  The nightly builds have already added support for them and will need to be downloaded if you'd like to import subscriptions before the next release.
