### ISSUE TITLE
Black/Blank window on win 7

### ISSUE THREAD

**Issue by DraZtiK** [FreeTubeApp/FreeTube#666]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify:

**Question**
Black/Blank window on win 7. possibly missing required files?

**Comment by GilgusMaximus** [comment]
Do you use the portable or installed version?

**Comment by DraZtiK** [comment]
I tried both, same issue with portable or installer.

**Comment by PrestonN** [comment]
Unfortunately with Microsoft not supporting Windows 7 any more I also cannot promise any fixes for the operating system. If you still have this issue on Windows 10, I can take a look into it.
