### ISSUE TITLE
Windowed FullScreen

### ISSUE THREAD

**Issue by galfwender** [FreeTubeApp/FreeTube#667]
Please add a button similar to the Chrome extension "Windowed FullScreen" to fully maximize playback within the application's window.

https://chrome.google.com/webstore/detail/youtube-windowed-fullscre/gkkmiofalnjagdcjheckamobghglpdpm

**Comment by CristianMartin** [comment]
Hi,
I have a little knowledge with videojs and I would like to contribute to the project by adding this functionality.
thanks.

**Comment by PrestonN** [comment]
Hello!  Feel free to work on this if you'd like.  I will review your pull request once it is ready.  Let me know if you have any questions.

Thanks!

**Comment by CristianMartin** [comment]
HI,
Thanks for letting me contribute, and uploaded the pull request. I hope you can see it soon.

Thanks!!

**Comment by PrestonN** [comment]
Closing as this has been implemented
