### ISSUE TITLE
starting FreeTube a second time results in nothing but a white screen

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#67]
OS: Debian 9 (appVM in qubes)
FreeTube 0.2.0 beta

Issue:
I am installing FreeTube onto Debian 9 with `dpkg -i FreeTube_0.2.0_amd64.deb`  followed by `apt-get -f install` to install missing dependencies.

This allows me to start `FreeTube` once, when I get the expected interface, can search youtube and subscribe to channels,  if I quit FreeTube and reopen it I get nothing but a white screen.

I have also attempted to reset FreeTube, by deleting `~/config/FreeTube` and `~/.config/FreeTubesettings.db` but it still remains white on startup

**Comment by PrestonN** [comment]
Hey there.  I installed a Debian VM and tried to reproduce the issue but I was unable to do so.  Do you have any more information about the issue or your system that you can provide?

I've seen the issue before when I tried to support the Raspberry Pi, but it wouldn't even boot once like your system did.  Part of me thinks it has to do with the system being low spec, but even if I drop all of the specs on my VM, FreeTube was still running as expected.

I don't know if it's related, but I did find [this](https://github.com/electron/electron/issues/4513) issue over at the Electron repository.  FreeTube uses Font Awesome as well which could be the source of the issue.  Some of the comments on this issue may be helpful.  I'll try to do some testing and see if Font Awesome is the issue.

**Comment by grrrrr** [comment]
Is there a way to get any debug info to submit?

System details are: 

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch

```

    $ uname -a
    Linux test 4.9.56-21.pvops.qubes.x86_64 #1 SMP Tue Oct 17 23:58:50 UTC 2017 x86_64 GNU/Linux

The App VM is set to start with 2GB available and grow to 4GB,  on starting FreeTube it uses about 680mb and stay there while the screen is white

**Comment by grrrrr** [comment]
based on initial testing with 0.3.0 beta this problem is resolved

**Comment by PrestonN** [comment]
That's good to hear.  If I had to be honest, I don't believe much was done to specifically fix this problem.  Either way, seeing the problem get fixed is always good.  If you see the issue pop up again feel free to re-open this issue or create a new one.
