### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by therealrobster** [FreeTubeApp/FreeTube#676]
**Behavior of the program**
The error SyntaxError: Unexpected token < in JSON at position 0 occurs when I try and search.

**Expected behavior**
It should return search results

**To Reproduce**
click in search bar, search with ENTER as the submit driver.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04 LTS
 - FreeTube version: v0.9.0 Beta

**Additional context**
I hope that helps.  It's highly regular on this machine at least.

**Comment by PrestonN** [comment]
Duplicate of #662

**Comment by therealrobster** [comment]
My bad, sorry I did not see the other.
