### ISSUE TITLE
Feature request: back button and ability to search for channels  

### ISSUE THREAD

**Issue by ricardotd** [FreeTubeApp/FreeTube#68]
I installed free tube on mac, and these are the missing features that would make me switch to this instead of the actual youtube website.
I cannot search for channels, 
and there is no back button if you are on a channel.

**Comment by aproposnix** [comment]
Duplicate of #3 
Duplicate of #15

**Comment by PrestonN** [comment]
What @aproposnix said.  These are planned in the future.
