### ISSUE TITLE
API not working for search

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#687]
**Important note**
Please check other open and closed issues for a similar bug before reporting a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Behavior of the program**
The results are empty when i'm performing a search and i have error messages for both of the APIs.

Local API: `SyntaxError: Unexpected token < in JSON at position 0`
iv API: `[object Object]`

**Expected behavior**
Search results

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Search something

**Screenshots**
![Screenshot_20201018_001510](https://user-images.githubusercontent.com/22192600/96354448-617bbb80-10c6-11eb-9153-642cf7bab235.png)

**Desktop (please complete the following information):**
 - OS: Debian
 - OS Version: 10.6
 - FreeTube version: 0.9

**Comment by PrestonN** [comment]
Going to keep #662 as the main issue for this.  This is known and affecting both APIs due to a change in YouTube.  I'll push out an update once we can get it fixed.
