### ISSUE TITLE
Bring back the tor connection option

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#689]
**Important note**
Please check other open and closed issues for a similar feature request before proposing a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Is your feature request related to a usage problem (not a bug)? Please describe.**
Before the rewrite, we had the possibility to use a connection through tor, and i used it myself frequently, but It's not available anymore.

**Describe the solution you'd like to see implemented**
Reimplement it in the rewrite.

**Describe alternatives you've considered**
Nothing, i'm not into technical details, so i can't really looking for alternatives.

**Additional context**
Add any other context about the feature request here.

**Comment by GilgusMaximus** [comment]
Hi, so this is planned for the future and already in the roadmap for [0.10](https://github.com/FreeTubeApp/FreeTube/projects/4)

**Comment by Vetgans** [comment]
I suppose the normal (i.e. non-TOR) proxy connection will be brought back with this as well?

**Comment by PrestonN** [comment]
Functionality will be similar to how it was before the rewrite.  So Tor / Socks5 proxies will be supported.

**Comment by Frick-David** [comment]
2nd!

**Comment by PrestonN** [comment]
This has been finished and will be included in the next release.
