### ISSUE TITLE
Dynamically adapt theme to system preference

### ISSUE THREAD

**Issue by Mynacol** [FreeTubeApp/FreeTube#691]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Most of the applications on my (Linux) system can switch between a light and dark theme. FreeTube bugs me, as it doesn't change the theme if I toggle the system-wide theme.

**Describe the solution you'd like to see implemented**
FreeTube should add a theme option, `System`, which selects a light theme if the system-wide theme is a light one and a dark theme (if dark or black could be another option) if the system has a dark theme.
This should ideally work during usage, so no restart is required to "automatically" change the theme.

**Describe alternatives you've considered**
I see no way to change the theme with a command line tool.
Editing `theme` in `settings.db` in the configuration directory seems to change nothing.

**Screenshots**
(No screenshots by me)

**Additional context**
I think [this](https://www.electronjs.org/docs/api/native-theme) is the related electron manual.

**Comment by gracjankn** [comment]
I hope it'll be implemented. Same applies to macOS and Windows.

**Comment by Mennaruuk** [comment]
Agreed! Switching based on system theme would be awesome.

**Comment by julianfairfax** [comment]
I'd also appreciate this feature being added. If it would follow the system theme and change to the light theme or the dark theme automatically based on what the system theme is, it would improve the integration with the system, and it would be a welcome change for me. Thanks for all the work you've put into this wonderful app!

**Comment by lothar-cell** [comment]
I'd like to see this one on MacOS too!

**Comment by f-x1-1** [comment]
Additionally, You can add light/dark mode theme option, allowing users to choose built in themes for light/dark mode.

https://file.coffee/u/7yF7-eNKkGvZDa461OrY0.png
