### ISSUE TITLE
Ios & Android support?

### ISSUE THREAD

**Issue by pheonixfirewingz** [FreeTubeApp/FreeTube#697]
**Topic**
- [x] Other. Please specify: platform 
**Question**
Is freetube going to be ported to ios and Android for mobile use?

**Comment by PrestonN** [comment]
Nope.  Use NewPipe if you want an Android equivalent.  iOS isn't happening because Apple is a walled garden and would bloke FreeTube or similar apps from being added to the App Store

**Comment by exekutive** [comment]
> Apple is a walled garden and would bloke FreeTube or similar apps from being added to the App Store

why?
