### ISSUE TITLE
Support for PocketTube for Suscription Folders

### ISSUE THREAD

**Issue by Zhiro90** [FreeTubeApp/FreeTube#698]
PocketTube is a web broser extension that allows to group suscriptions and tag them. It allows data export which comes in a  a simple xml. I believe it would be relatively simple to add a way to import your PocketTube Groups Exported xml (Specially useful for users with a huge suscription list)

https://yousub.info/

**Comment by PrestonN** [comment]
We already support grouping subscriptions together.

**Comment by Zhiro90** [comment]
I was aware, I meant using their exported format, or is it compatible already?
