### ISSUE TITLE
Import "Watched" history from "Youtube Watchmarker"

### ISSUE THREAD

**Issue by Agych** [FreeTubeApp/FreeTube#700]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
During several years I've been having the "Watched" history disabled in the YT account to stop having it saved at Google and using the "Youtube Watchmarker" FF extension to have it locally in the browser profile.
https://addons.mozilla.org/en-US/firefox/addon/youtube-watchmarker
https://github.com/sniklaus/youtube-watchmarker
After all these years my Youtube Watchmarker watched history has around 30000 videos.
My final point for YT would be to completely ungoogle from YT: switch over from my FF youtube-browser to FreeTube completely, remove my YT account for good, and have only the local FreeTube profile with all the subs, watched history and stuff.
However, the issue of losing the watched history remains and is the only stopping factor.

**Describe the solution you'd like to see implemented**
Pls implement the ability to import the watched history file that is exported from the "Youtube Watchmarker" extension.

**Describe alternatives you've considered**
.

**Screenshots**
.

**Additional context**
.

**Comment by GilgusMaximus** [comment]
What kind of format is the extension exporting?

**Comment by Agych** [comment]
Hard to say. "Random" collection of digits and latin letters, and finishes with "==".
An encrypted file or an encrypted database probably.
Could try to contact the developer for more info / cooperation

**Comment by GilgusMaximus** [comment]
If you would create an issue over at his repository and ask how the export data could be parsed by another program, that would be great. https://github.com/sniklaus/youtube-watchmarker/

I couldn't use the extension in my Firefox version for some reason, so the export feature was not available for me?

**Comment by Synkky** [comment]
@Agych 
It seems like it's encoded in Base64.
If decoded, it'll probably give us a better picture of the format.
Copy the collection of digits, go to your browser console, type this and press enter (leave the two `'`):
`console.log(atob('<insert copied content here>'))`
then paste the content in a comment

**Comment by Agych** [comment]
@Synkky ,

I did what you recommended, this is what I saw:

`
[{"strIdent":"e-P5IFTqB98","longTimestamp":1486310050074,"strTitle":"Black Holes Explained – From Birth to Death","intCount":2},{"strIdent":"I GUESS THIS IS THE VIDEO ID THAT FOLLOWS AFTER www.youtube.com/watch?v=","longTimestamp":1486310050074,"strTitle":"TITLE OF THE VIDEO","intCount":<I THINK THIS COUNTS HOW MANY TIMES THE LINK TO THE VIDEO WAS OPENED>},{"strIdent":"ABCDEFGHIJK","longTimestamp":999999999999,"strTitle":"Rick Roll 100 hours challenge","intCount":9000}]
`

Looks like a simple JSON-like array of records with the info about the watched videos

**Comment by GilgusMaximus** [comment]
Thanks @Synkky . My internet was down for most of the day yesterday, so I missed that when quickly trying to look into the code. 

I mean in the end, it should be rather easy to allow them to import. I would like to move the conversation over to the legacy converter [here](https://github.com/GilgusMaximus/FreeTube-Legacy-Converter). Because up to now, no one has mentioned this add-on, so it wouldn't make sense to add that to the main project. However implementing it into the converter project, shouldn't be that difficult. Just a new method which handles the json data differently than the old FreeTube data

**Comment by Synkky** [comment]
@GilgusMaximus, you think far to highly of me, I didn't even open any links. I just saw this:
> Hard to say. "Random" collection of digits and latin letters, and ***finishes with "==".***

And took a wild guess.

**Comment by GilgusMaximus** [comment]
Yeah I'm not so good with encodings from just a plain file. But seeing it in the code would have made it clear :D
