### ISSUE TITLE
Application freeze while loading comments

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#701]
**Behavior of the program**
Application freezes when trying to load comments

**Expected behavior**
Application does not freeze when loading comments

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to https://www.youtube.com/watch?v=NUsoVlDFqZg
2. Click on **'Click to view comments'**
3. Application freezes after a few seconds. First u start to notice the application is not responding to clicks but the music video is still playing and u can still scroll. Then u cant scroll anymore and after that the music video also stops

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - OS Version: [1909]
 - FreeTube version: [0.9beta]

**Additional context**

**Comment by PrestonN** [comment]
We're aware of this issue and are currently working on fixing this.  The problem has to do with the comment scraper trying to grab too much information at once.  So when there are comments with a lot of replies for example, it causes the app to freeze.

**Comment by GilgusMaximus** [comment]
Yes. The draft for the fix is already up as #674 .
However we are currently stuck in getting the module to load in a child process, because it cannot find the modules.

So any help here would be appreciated

**Comment by GilgusMaximus** [comment]
Fix has been merged yesterday
