### ISSUE TITLE
Video name instead of "watch" in the title bar

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#702]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
It may be a detail, but on the title bar, instead of the expected video name, is "watch".

**Describe the solution you'd like to see implemented**
The name of the actual video instead of "watch".

**Screenshots**
![Screenshot_20201020_181402](https://user-images.githubusercontent.com/22192600/96614141-4c35a580-12ef-11eb-8329-39eb0b56d6cb.png)

**Comment by TDDR** [comment]
Hey PrestonN, I have been looking into this issue and think I might be able to fix it. If you could assign me that would be appreciated.

**Comment by PrestonN** [comment]
Can do :)

**Comment by TDDR** [comment]
Thanks! Would you be alright if I added https://github.com/nuxt/vue-meta as a dependency to help with this? I'm having a hard time figuring out how to change the title in the router otherwise.

**Comment by PrestonN** [comment]
The extra dependency shouldn't be needed.  Changing the title is the same as it would be without Vue.

```js
document.title = `${videoName} - FreeTube`
```

Let me know if you have any other questions with this.
