### ISSUE TITLE
Add description snippet to list view

### ISSUE THREAD

**Issue by trostboot** [FreeTubeApp/FreeTube#703]
It would be very helpful to display a snippet of the video description (if it exists) in the empty space below the statistics in list view.
This is basically how YouTube's old (and now very definitely no longer accessible) design used to work.

If the description is too long to fit in the space, it should of course be truncated.

Optionally, the ability to expand and collapse the description directly from the list view would be even more helpful.

Quick and dirty mock-up:
![mockup](https://user-images.githubusercontent.com/17594477/96741606-4361d400-13c2-11eb-90fa-b730c5a8d5b7.png)

**Comment by GilgusMaximus** [comment]
For the history this is already available, although I admit that it can become overwhelming because it isn't cut off after a few lines.

But adding this to all other's shouldn't be that difficult. Also a good first issue.

**Comment by PrestonN** [comment]
I think the problem here is that not all endpoints that we're using is providing a description.  We already provide the description here whenever possible so I'm not sure what could be changed.

Fixing the sizing for very large descriptions can still be something to look at though.

**Comment by PrestonN** [comment]
As mentioned before, we're already grabbing descriptions where possible, so anywhere without it there's nothing we can do. I've also made a fix to hide longer portions of a description in list view. Going to close now.
