### ISSUE TITLE
No watching history on live videos

### ISSUE THREAD

**Issue by Mech0z** [FreeTubeApp/FreeTube#704]
**Behavior of the program**
If I watch a video that was broadcasted as a live video, but is now finished https://www.youtube.com/watch?v=-3jzyOpb2F0 and watch 10 minutes, the next time I start the video, it will start at 0:00

**Expected behavior**
I would expect it to remember that I watched 10:00 already and start there

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to https://www.youtube.com/watch?v=-3jzyOpb2F0
2. Jump 10:00 in
3. Close video
4. Watch video again
5. Video starts at 0:00

**Desktop (please complete the following information):**
 - OS: Win10
 - OS Version:1809
 - FreeTube version: v0.9.0Beta

**Comment by DuaneJaspers** [comment]
I've played around with this,
currently live broadcasts are checked like this: 
`this.isLive = result.player_response.videoDetails.isLiveContent || result.player_response.videoDetails.isLive`

past live broadcasts are considered live by `result.player_response.videoDetails.isLiveContent`.

In my quick testing I used a different check
`this.isLive = player_response.microformat.playerMicroformatRenderer.liveBroadcastDetails.isLiveNow`

This resulted in past live broadcasts being considered as normal videos and current live broadcasts being considered live. 
This fixed the watch history as well. I'm not 100% this broke anything though, but it seemed fine.

**Comment by DuaneJaspers** [comment]
I've looked at this.

Currently the way a live video is determined is by `this.isLive = result.player_response.videoDetails.isLiveContent || result.player_response.videoDetails.isLive` 

what happens for a past broadcast is that `result.player_response.videoDetails.isLiveContent` returns true so it's handled like a live video.
I've tried to use a different check: 
`this.isLive = result.videoDetails.liveBroadcastDetails ? result.videoDetails.liveBroadcastDetails.isLiveNow : false`
This check only returns true if the broadcast is currently live. 
I'm not 100% this wouldn't break anything but I've quickly tested it for current live broadcasts, past broadcasts, and normal uploads. I haven't encountered any issues.

**Comment by GilgusMaximus** [comment]
Thanks for looking into it. If you create a PR with that change, more people can test it and it is easier to verify whether it works correctly 👍

**Comment by PrestonN** [comment]
The problem with doing this is that we won't know where to bring you back to when you come back to that live video as a non-live video.  YouTube doesn't provide the entire live stream any more and only provides you the latest "chunk" of that live video.  When you watch a live video, you may be able to only rewind ~20 seconds from when you started watching, but you can't rewind to where the stream started.  You have to wait for the stream to be over in order to do this.

The change that @DuaneJaspers mentioned may help, but I need to test it a little bit before I know for sure that the change will help.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
this was fixed in https://github.com/FreeTubeApp/FreeTube/pull/728
