### ISSUE TITLE
Location of settings

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube#705]
Where are settings/cache etc for Freetube? I mean settings/cache at disk.

**Comment by PrestonN** [comment]
Check #151 to find the location for your operating system.

**Comment by pawlosck** [comment]
Are you sure? I removed dirs FreeTube and FreeTube-legacy from " ~/.config" and still I see my subscriptions, history etc in FreeTube.

There is dir ~/.config/Electron and inside this dir there are files which looks like config files for FreeTube.

**Comment by PrestonN** [comment]
Do you use Flatpak by chance?  Flatpak keeps their information stored somewhere else.

**Comment by pawlosck** [comment]
No, I am using FreeTube from github.

**Comment by PrestonN** [comment]
If you are running FreeTube via Github (Ex. You're running `npm run dev` to start the application), then you are correct that the data will be installed in `~/.config/Electron` instead of `~/.config/FreeTube`.
