### ISSUE TITLE
Allow Copy / Open Channel URL from video dropdown

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#706]
**Behavior of the program**
I wanted to copy-paste a channel link, but instead of the actual channel link, it gave me a link like this: `file:///opt/FreeTube/resources/app.asar/dist/index.html#/channel/[channel ID]` instead of `https://youtube.com/channel/[channel ID]`

**Expected behavior**
Being able to copy actual channel URL.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to someone's channel
2. Right click on the channel link mentionned at bottom of every video
3. Click on "copy link"
4. Paste it 

**Desktop (please complete the following information):**
 - OS: Debian
 - OS Version: 10.6
 - FreeTube version: 0.9.1

**Comment by PrestonN** [comment]
This is something that will have to be added to the side menu of the video, because the link you're getting is for navigating within FreeTube itself, and cannot provide the correct URL for opening into YouTube.  This is a very easy fix and we can include this in a future update.

**Comment by DuaneJaspers** [comment]
I'd like to try this
