### ISSUE TITLE
Some search results don't show up

### ISSUE THREAD

**Issue by Arnab771** [FreeTubeApp/FreeTube#708]
**Behavior of the program**
I searched for a couple of things. Most do show up. But I was just searching "jordan b peterson" and it showed `TypeError: Cannot read property 'runs' of undefined` . Then a below that `falling back to Invidious API` and then nothing.

**Expected behavior**
It should have showed the Jordan B Peterson channel and all related content.

**To Reproduce**
Search for "jordan b peterson" from the search bar.

**Screenshot**
![Screenshot](https://i.postimg.cc/SRk4VVby/Screenshot-from-2020-10-22-20-58-09.png)

**Desktop (please complete the following information):**
 - OS: Linux, Pop OS
 - OS Version: 20.04
 - FreeTube version: 0.9.1

**Comment by PrestonN** [comment]
Duplicate of #662
