### ISSUE TITLE
FreeTube doesn't remember window position and size

### ISSUE THREAD

**Issue by aproposnix** [FreeTubeApp/FreeTube#71]
This is a papercut issue - Every time I start FreeTube I always have to manually maximize the window. It's a minor issue but it's quite annoying. It would be great if window size/position were remembered on close. 

I'm running Linux (Ubuntu) so I'm not sure if Windows users have the same issue.

**Comment by PrestonN** [comment]
I've seen this requested a couple of times so it's definitely something I need to take a look at.  I don't know exactly when I'll be able to look at doing this but it's on the radar for the future.

**Comment by Sojiro84** [comment]
I was about to make a issue until I saw this. I might as well add my niggle to this. FreeTube doesn't remember window position/doesn't listen to window placement on my Manjaro Cinnamon based on Arch.

It always open's top-left even-though I have my system configured to open windows in the center.

I hope you can get around to fixing this!

**Comment by PrestonN** [comment]
This has been implemented and will be available in the next release.  Closing...
