### ISSUE TITLE
Japanese translation issue

### ISSUE THREAD

**Issue by maboroshin** [FreeTubeApp/FreeTube#714]
**White space notation in number** 
This space is normal in Japanese without it. Some software will include spaces.

* Translation by Kyotaro: 公開日 10 月 12, 2020
* Means: Publish date 10 month 12, 2020

* maboroshin translation means: Publish date 10month 12, 2020

Reduced confusion. There is no problem with the notation of "10month" in Japanese.

The gap between the month and the day brings confusion. Other whitespace may be removed if consistency is an issue.

https://hosted.weblate.org/translate/free-tube/translations/ja/?&offset=306#comments

**Comment by maboroshin** [comment]
**Different translations**

Invidious Instance

インスタンス (Kyotaro): The dictionary describes an object-oriented programmer. https://kotobank.jp/word/%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9-824

実体 (maboroshin): Japanese in the ordinary dictionary https://kotobank.jp/word/%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9-824

**Comment by maboroshin** [comment]
**Misuse tolerance**

Kyotaro misuses the word "の".

construction work

Trying to fix the "の" on the other hand.

https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=82adb27863a1488c#comments

**Comment by maboroshin** [comment]
**White space notation in English word separator**


https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=9f26fdcee0041a9f

**Comment by maboroshin** [comment]
**Different from the actual UI**

"SOON" in both the original English and the actual UI, but Kyotaro tries to translate to "immediately". https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=b56b3cad0b091ae

**Comment by maboroshin** [comment]
**Color Translation**

Accent colors (強調色) mean that they are emphasized over other colors. But you can choose the color. https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=896e564fa24b7d0c

**Comment by maboroshin** [comment]
**Full-width and half-width brackets**

Normal Japanese is Full-width. But in software, it's usually half-width characters.

Kyotaro tries to make it full-width. https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=e82c3749833bf1c7#comments

**Comment by maboroshin** [comment]
**Different translations**

* maboroshin's : [Current Microsoft doccument](https://support.microsoft.com/ja-jp/help/4052043/surface-precision-mouse) [CHrome](https://livedoor.blogimg.jp/e5dtfa2drci97hbjds4e/imgs/4/c/4c4e5c11.jpg)'s
* kyotaro's : Firefox, logicool's

https://hosted.weblate.org/translate/free-tube/translations/ja/?&offset=93#comments

**Comment by maboroshin** [comment]
I explained about half of it. I'll add more later.

**Comment by GilgusMaximus** [comment]
I'm just gonna link to #673. 
Most people here do not know Japanese, so moving the discussion to Weblate, if it is not a stylizing issue like mentioned in the linked issue, would be a more useful way to discuss that, as there might be more people who also speak Japanese.

**Comment by shima-office** [comment]
I hate to hop into this situation,but I want to say one word.
 
I think if one wants to translate English into Japanese,
one should be a native Japanse speaker.
The reason is that if one is not a native Japanese speaker,
it is difficult for him or her to choose the right word.
For instance, "I" in English is translated into various words in Japanese,
such as "watashi","watakushi","ore","boku","uchi","wate","atai",and so on.
One has to choose the most suitable word from such words.
If one use many dictionaries , it is difficult to choose the most suitable word
unless one can understand subtle difference among the meaning of those words.
I respect Mr. or Ms. maboroshin's effort to translate into Japanse ,
but weblate is not a learning space but a practical space to localise softwear.
 
In addition to it ,
I think when one is to dispute how to translate into Japanese,
one should use Japanese.
 
It is not good manner to delete people’s suggestions.
I would suggest to have good time to translate.

**Comment by PrestonN** [comment]
Please don't make several issues for the same thing.  You already made #648 which I'm well aware of, and I'd like all discussions for translation problems to be in #673 so that they don't muddy up discussions about issues that I can properly address.

I'm aware that there's a problem going on about the Japanese translations and I'll be getting on Weblate later today to figure out what to do about the issue.

**Comment by maboroshin** [comment]
@shima-office : Thanks for your comment. I'm native Japanese.

@PrestonN : At weblate, we comment on each string. So the discussion will be scattered.

I want to use this place for the purpose of summarizing the weblate discussion.

For example, a single translation rule will change several weblate strings.But we can only comment on a single string on the weblate.

**Comment by maboroshin** [comment]
One of Kyotaro's mis-translation that lasted for two years has been corrected. ( About "Toggle" :https://github.com/FreeTubeApp/FreeTube/issues/714#issuecomment-715185948) The new translator ntsboiuekjv has reverted to my translation. His comment:
> 切替 (toggle) can mean to switch in either direction, as opposed to 変更 (Change)
https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=be8d8ac157fddf4d
> の切替 (toggle of...) allows ambiguity for switching "to" or "from" dev tools, as opposed to に切替 which is only switching "to"
https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=01284598bfc9620a#comments

There are more new problems.
*Kyotaro assigns different Japanese words to the same term.
*The Destruction of Meaning
**Original : Scroll Playback Rate Over Video Player
**Kyotaro : Adjust video Playback Rate (動画の再生速度の調整) https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=b00aed3022929501
*Strange
**Original: starting video at offset
**Kyotaro: starting video by offset (オフセットで動画の再生)

**Comment by absidue** [comment]
@maboroshin As discussed previously, we can't do anything to stop specific people translating. If there are issues with translations please either fix them yourself or talk directly to the people that made the changes. Mentioning stuff here, where none of the other japanese translators will see it, won't change anything.

**Comment by maboroshin** [comment]
@absidue It is important to share the problem with the authority's administrator. The problem is that it is ongoing.

Two years ago Kyotaro erased dozens of my translations. So, I have stopped editing Weblate for FreeTube.

**Comment by absidue** [comment]
There is nothing we can do from our side. Please complain to weblate directly, not us. We can't fix the problem from our side.

**Comment by maboroshin** [comment]
Please goto https://github.com/FreeTubeApp/FreeTube/issues/648

**Comment by maboroshin** [comment]
@absidue Please goto https://github.com/FreeTubeApp/FreeTube/issues/648 

I would like to use this issue for translation discussions.

**Comment by absidue** [comment]
Preston already told you there that the only potential solutions will hurt all other languages, so they are not good solutions.

You need to contact weblate and ask them to implement better moderation features.

**Comment by maboroshin** [comment]
@absidue Please stop change title.

**Comment by absidue** [comment]
Talking about guidelines, you've clearly not read out contributing guidelines:
> Do not include non-free software or modules with your code.

We will not be switching to closed source proprietary translation platforms.

**Comment by maboroshin** [comment]
@absidue I recommend here for discussions other than translation quality. : https://github.com/FreeTubeApp/FreeTube/issues/648

**Comment by maboroshin** [comment]
Kyotaro Iijima continues his unserious translation work.

Kyotaro assigns different Japanese words to the same term. There is no consistency. This has been ongoing since the beginning.

* Most translation are "動画" for string of "video". Kyotaro inadvertently applied a different translation, "ビデオ" (Transliteration of "video").
https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=edad223219573d01
* He assigned ```PlayList``` and ```VideoList``` to translate the "Playlist". This is a terrible case. PlayList (再生リスト) used 20 times, VideoList (動画リスト) used 8 times. Users of the app will be confused. It is fortunate that there was no audio-like "ビデオリスト".
https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=962a4c17847e25a6
* Kyotaro uses "フルスクリーン". (Transliteration of "full-screen") https://hosted.weblate.org/translate/free-tube/translations/ja/?q=full+screen&sort_by=-priority%2Cposition&offset=2
* * But it already used "全画面" for full-screen. https://hosted.weblate.org/zen/free-tube/translations/ja/?offset=1&q=full+screen&sort_by=-priority%2Cposition&checksum=

**Comment by maboroshin** [comment]
@PrestonN Don't Close ongoing issues.

**Comment by maboroshin** [comment]
Many mistranslations remain.

"Please read the room rules" is split into two sentences.
There is evidence that Kyotaro has not seen the actual app UI. The same is true for this text. The 2 year old translation has not yet been corrected.
Kyotaro translates this separately.

* Kyotaro's Translation: "Please check. Room rules." (確認してください ルームの規則) 

Japanese grammar is the reverse of English. In fact, it would be something like this.

"Room rules. Please check." 

Kyotaro will not have seen the app's UI for over two years. Other two sentences are a similar trend. It is at the level of poor quality machine translation.

![image](https://github.com/FreeTubeApp/FreeTube/assets/41102508/5b5bcc6a-fed5-4832-9db0-958aac3728a7)

----
The new translation string is also a mistranslation.

* English: Joined
* Kyotaro: 登録済み (Already registered)

It's a complete misinterpretation.

----

 * Kyotaro: 2 か月 前 ( for "2 months ago")
 * Common Japanese 2か月前 (No space. Please search "か月 前")

A search with blanks will return results with no blanks. Because, In natural Japanese, there is no need for a space here.
