### ISSUE TITLE
Youtube-dl DMCA takedown : is Freetube endangered ?

### ISSUE THREAD

**Issue by ThatIsAPseudo** [FreeTubeApp/FreeTube#717]
**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify: Copyright issues

**Discussion**
Following [the DMCA takedown youtube-dl faced recently](https://github.com/ytdl-org/youtube-dl), projects such as Newpipe started to discuss the possibility that they could be taken down as well ([_Youtube-dl disabled due to a DMCA takedown. We are next._](https://github.com/TeamNewPipe/NewPipe/issues/4618)).

Is Freetube endangered too since it enables users to download videos, or is it different enough from youtube-dl to not be taken down ?

![](https://user-images.githubusercontent.com/4913196/97054501-8f14a900-158d-11eb-8ec3-f218e2b5d7c2.png)

**Comment by Synkky** [comment]
There's not enough info to make an accurate statement about that yet. We'll have to wait for youtube-dl's statement on this.
Quoting Preston's statement on the Matrix server
> I'll be keeping a close eye on how this turns out, though if anyone is worried, I do keep mirrors of all of our repos in a private Gitea instance, so all of our code / history will still be available in case something like this happens to our repos.

**Comment by GilgusMaximus** [comment]
At the moment we do not see why we would be hit by a dmca flag similar to youtube-dl. And with youtube-dl-core not being hit, we believe that everything should be fine.

**Comment by PrestonN** [comment]
Yeah, as was mentioned, let's not speculate on what may happen.  If anyone would like to discuss it more, feel free to talk about it in our Matrix room.
