### ISSUE TITLE
Error messages every time I load a page in FreeTube

### ISSUE THREAD

**Issue by nullbasis** [FreeTubeApp/FreeTube#718]
This happens basically every time I open FreeTube, search for anything, navigate to a channel or my subscriptions page, etc. An error pops up reading "TypeError: Cannot read property 'simpleText' of undefined" and then "Falling back to Invidious API". The page usually still loads, but this seems like it shouldn't be happening.

**Desktop:**
 - OS: Ubuntu 20.04.1
 - FreeTube version: 0.9.1

**Comment by jorigel** [comment]
The same happens here, but search results don't show up at all. Same version Ubuntu (running under ltsp) same version FreeTube . . .

**Comment by jorigel** [comment]
Btw. I'm using AppImage to start FreeTube . . .

**Comment by GilgusMaximus** [comment]
This error doesn't happen on Windows at all. Could you please open the Developer Console (Ctrl + Shift + i) and copy it's output of this error over here. 

This error happened on Windows a while back but since then I didn't have it at all. Also, did you try to run another version instead of AppImage?

**Comment by jorigel** [comment]
@Gilgus: What did You mean by "try to run another version"? Try a different way of  installation or really installing an older version?

regards jori

**Comment by nullbasis** [comment]
For the record, I'm using the .deb version.

The console shows all these errors upon simply opening FreeTube and refreshing my subscriptions page:

`renderer.js:14 /home/phi/.config/FreeTube/settings.db
renderer.js:14 Object
renderer.js:14 User is using Electron
renderer.js:14 Array(7)
index.html#/:1 A cookie associated with a cross-site resource at http://youtube.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
renderer.js:14 TypeError: Cannot read property 'simpleText' of undefined
    at Function.parseVideo (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/helper.js:99)
    at /opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/helper.js:55
    at Array.map (<anonymous>)
    at Function.parseChannelVideoResponse (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/helper.js:54)
    at Function.getChannelVideosNewest (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/fetchers/channel.js:23)
    at async Function.getChannelVideos (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/youtube-grabber.js:128)
renderer.js:14 TypeError: Cannot read property 'simpleText' of undefined
    at Function.parseVideo (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/helper.js:99)
    at /opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/helper.js:55
    at Array.map (<anonymous>)
    at Function.parseChannelVideoResponse (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/helper.js:54)
    at Function.getChannelVideosNewest (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/fetchers/channel.js:23)
    at async Function.getChannelVideos (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/youtube-grabber.js:128)
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/autolinker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/utils.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/anchor-tag-builder.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/html-tag.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/truncate/truncate-smart.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/truncate/truncate-middle.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/truncate/truncate-end.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/match.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/email-match.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/hashtag-match.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/mention-match.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/phone-match.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/url-match.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/matcher.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/email-matcher.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/regex-lib.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/tld-regex.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/url-matcher.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/url-match-validator.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/hashtag-matcher.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/phone-matcher.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/mention-matcher.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/htmlParser/parse-html.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/miniget/dist/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/m3u8stream/dist/parse-time.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/m3u8stream/dist/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/m3u8stream/node_modules/miniget/dist/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/m3u8stream/dist/m3u8-parser.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/m3u8stream/dist/dash-mpd-parser.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/m3u8stream/dist/queue.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/youtube-chat/dist/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/youtube-chat/dist/live-chat.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/FreeTube/resources/app.asar/node_modules/youtube-chat/dist/parser.js.map: `

**Comment by Synkky** [comment]
First of all, those "errors" that nullbasis has presented on the latest comment **are not errors, they are warnings and can be safely ignored.** They also have nothing to do with this issue's original topic.
Now, about the original topic, this is a problem with the ytsr module, which means it's an upstream problem and not directly related with FreeTube.
That being said, I've just opened a PR to that project that will solve the problem (it's not a permanent fix, some videos will be missing a publish date on the search results).

**Comment by nullbasis** [comment]
Excuse me, but I *started* this original topic. I don't know what else you want me to do; I loaded a page that presented the errors I mentioned in the original post, then opened the console as Gilgus asked and provided what appeared there.

**Comment by Synkky** [comment]
No one is saying you did something wrong and I'm not criticizing anyone, I'm simply clarifying things: those warnings messages appear every time you start FreeTube and they're not errors, that's all I'm saying.
The `TypeError: Cannot read property 'simpleText' of undefined` error will only appear after searching for something, so I was only making it clear that they are not related to the warnings you pasted.

**Comment by GilgusMaximus** [comment]
@jorigel I mean using a different package like the .deb instead of AppImage. The portable versions sometimes have problems a complete installation does not. 
But as @Synkky mentioned, the issue is an issue with modules we cannot control and often do not have time to fix ourselves. Luckily Synkky had some time to do a fix

**Comment by jorigel** [comment]
ok thank You for the reply. But here are the newbie's next questions: What is a PR, where can I find it and what am I supposed to do to use it to fix the problem?

Even if I still don't know what's going on, Thank You for helping us
regards 
jori

**Comment by Synkky** [comment]
Right above my last comment is a link to my PR.
PR stands for pull request. You can google it to get a better picture but it's basically a suggestion someone makes to modify the code of someone else's project, by providing modified code or new code to said project.

**Comment by jorigel** [comment]
:-( well, I admit that was looking unthinking . . . I was blended by this huge list even missing the bold headline of Yours underneath,
sorry for that, thanX for Your help and time

regards jori

**Comment by jorigel** [comment]
doing everything described in the PR the error persists. Either the space between the search terms or the amount of them triggers the error. In this case I used "sidewinder x1 upgrade" and the list keeps empty. For a single term -> no problem

regards jori

**Comment by 132ikl** [comment]
This is still an issue for me despite the PR (well, the PR merged in favor of the PR referenced by the PR linked above) being merged.

**Comment by jorigel** [comment]
@132ikl 
Hi, sorry, but I did not understand. Do You only want to express that this is obviously an error? Does this has any consequences for me? Anything I can do about it? I don't want to put pressure on anybody. I'm just new to this soft, helpless and wondering what to do while looking for help.

Basically I love the idea behind this software, so I'm really interested in making it work for my needs.

So at least thank You for Your attention.
jori

**Comment by GilgusMaximus** [comment]
This error message has not been reported anymore, so therefore I am closing this issue

**Comment by buddybuilder** [comment]
I'm still seeing the error code every time I open FreeTube: "TypeError: Cannot read property 'simpleText' of undefined".

OS: Zorin OS 15.3
Freetube version: v0.12.0 Beta

Console output:

<details>
  <summary>Click to expand</summary>
  DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/opml-to-json/lib/opml-to-json.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/autolinker.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/utils.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/anchor-tag-builder.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/html-tag.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/truncate/truncate-smart.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/truncate/truncate-middle.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/truncate/truncate-end.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/match.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/email-match.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/hashtag-match.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/mention-match.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/phone-match.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/match/url-match.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/matcher.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/email-matcher.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/regex-lib.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/url-matcher.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/url-match-validator.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/hashtag-matcher.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/phone-matcher.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/matcher/mention-matcher.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/autolinker/dist/commonjs/htmlParser/parse-html.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/miniget/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/m3u8stream/dist/parse-time.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/m3u8stream/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/m3u8stream/node_modules/miniget/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/m3u8stream/dist/m3u8-parser.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/m3u8stream/dist/dash-mpd-parser.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/m3u8stream/dist/queue.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/youtube-chat/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/youtube-chat/dist/live-chat.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/youtube-chat/dist/parser.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/ytdl-core/node_modules/miniget/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/ytdl-core/node_modules/m3u8stream/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/ytdl-core/node_modules/m3u8stream/dist/m3u8-parser.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/ytdl-core/node_modules/m3u8stream/dist/dash-mpd-parser.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/ytdl-core/node_modules/m3u8stream/dist/parse-time.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/ytdl-core/node_modules/m3u8stream/dist/queue.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/ytsr/node_modules/miniget/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/ytpl/node_modules/miniget/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/socks-proxy-agent/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/socks-proxy-agent/dist/agent.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/agent-base/dist/src/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/agent-base/dist/src/promisify.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/socks/build/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/socks/build/client/socksclient.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/smart-buffer/build/smartbuffer.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/smart-buffer/build/utils.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/socks/build/common/constants.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/socks/build/common/helpers.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/socks/build/common/util.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/socks/build/common/receivebuffer.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/https-proxy-agent/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/https-proxy-agent/dist/agent.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/https-proxy-agent/dist/parse-proxy-response.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/http-proxy-agent/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/http-proxy-agent/dist/agent.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///opt/FreeTube/resources/app.asar/node_modules/@tootallnate/once/dist/index.js.map: Unexpected end of JSON input
</details>

**Comment by jorigel** [comment]
Hi,
not the error disappeared the help dried up. As I said I would have been interested to use this software, but this way it is unusable for me. I already gave up to try it anymore,
thanks for all the above
bye

**Comment by GilgusMaximus** [comment]
> Hi,
not the error disappeared the help dried up. As I said I would have been interested to use this software, but this way it is unusable for me. I already gave up to try it anymore,
thanks for all the above
bye

Well we had this error before. We resolved bugs and no new issues were created by other people. Therefore the error disappeared. If this is still happening then there is something else going wrong. But it is difficult to trace it back when only a very small percentage of people have it.

@buddybuilder Unfortunately your error log is the error log which always appears due to some problem with the dev tools. I'd need the log which contains the actual error. These warning cannot be put to use.

**Comment by VictoriousFan** [comment]
I just downloaded the app from flathub and I'm getting these errors now, even after uninstalling and reinstalling, this has happened since I opened it up the first time, I'm on Pop!_OS.

Every time I load a channel page
`TypeError: Cannot read properties of undefined (reading 'response')` 
`Falling back to indivious API`
both appear twice. This also happened 

And every time I open the app up after closing it
`TypeError: Cannot read properties of undefined (reading 'response')`
appears five times.

**Comment by qkiel** [comment]
Same here on Ubuntu 20.04. I've been using flatpak version of FreeTube for a while and two days ago I've started to see errors:
`freetube TypeError: Cannot read properties of undefined (reading 'response')`

**Comment by ramonpin** [comment]
> I just downloaded the app from flathub and I'm getting these errors now, even after uninstalling and reinstalling, this has happened since I opened it up the first time, I'm on Pop!_OS.
> 
> Every time I load a channel page `TypeError: Cannot read properties of undefined (reading 'response')` `Falling back to indivious API` both appear twice. This also happened
> 
> And every time I open the app up after closing it `TypeError: Cannot read properties of undefined (reading 'response')` appears five times.

I'm getting th same errors. I'm using an AppImage that work before with no issues.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
thats is already patched in the latest nightly build
