### ISSUE TITLE
Add ability to see Version # & if an Update is available

### ISSUE THREAD

**Issue by big610** [FreeTubeApp/FreeTube#72]
Add ability to see Version # & if an Update is available

**Comment by big610** [comment]
Could you let us know what it would involve to, Add ability to see Version # & to see if an Update is available?

**Comment by PrestonN** [comment]
Hey there.  You can see the version number by clicking on the "About" tab in FreeTube.  Auto updates as well as checking for new updates is planned for the next major release.

**Comment by PrestonN** [comment]
This has been implemented in the new / current release.
