### ISSUE TITLE
Black lines appear over text

### ISSUE THREAD

**Issue by 18fadly-anthony** [FreeTubeApp/FreeTube#723]
**Black lines appear over text**
![screenshot-1603663859](https://user-images.githubusercontent.com/31709415/97120551-c27f4100-170f-11eb-9f51-978794e5ba0f.png)

**Expected behavior**
No black lines

**To Reproduce**
1. Install FreeTube from flatpak on NixOS with an AMD Radeon graphics card
2. Open FreeTube

**Desktop:**
 - OS: NixOS
 - OS Version: 20.03
 - FreeTube version: 0.9.1 Beta

**Additional context**
I haven't had this problem with Windows on the same hardware, nor have I had it on my laptop where it was also installed from flatpak on NixOS, I feel like I've isolated every variable and still can't solve the problem

**Comment by 18fadly-anthony** [comment]
Update: videos are messed up too, just tried watching one
![screenshot-1603664927](https://user-images.githubusercontent.com/31709415/97120775-7e8d3b80-1711-11eb-823e-a15b24af5b4e.png)

**Comment by Synkky** [comment]
Can you go to the Actions tab (top of the page) and download a portable version of the latest build, in order to check if the problem exists with that version?

**Mini guide (ignore if you already know)**
After selecting a result, there should be an `Artifacts` subsection
If there isn't, go back and choose the next result and so on
You should choose one of the following links:
- freetube_0.9.1_linux_portable_x64
- freetube_0.9.1_**amd**64.AppImage (if you prefer an AppImage type)

**Comment by 18fadly-anthony** [comment]
@Synkky I had a different problem when attempting to run the portable version:
```
$ ls
chrome_100_percent.pak  chrome-sandbox*  icudtl.dat  libffmpeg.so*  libvk_swiftshader.so*  LICENSE.electron.txt    locales/    resources.pak      swiftshader/             vk_swiftshader_icd.json
chrome_200_percent.pak  freetube*        libEGL.so*  libGLESv2.so*  libvulkan.so*          LICENSES.chromium.html  resources/  snapshot_blob.bin  v8_context_snapshot.bin

$ ./freetube
Failed to execute process './freetube'. Reason:
The file './freetube' does not exist or could not be executed.```

**Comment by Synkky** [comment]
I downloaded `freetube_0.9.1_linux_portable_x64`, did the exact same command and it worked, not really sure what the problem might be.
Make sure you have permissions to execute the file.
Type this:
`chmod +x freetube`
and try again.

**Comment by 18fadly-anthony** [comment]
```
$ chmod +x freetube 

$ ls -l freetube 
-rwxr-xr-x 1 tony users 127548536 Oct 27 17:50 freetube*

$ ./freetube
Failed to execute process './freetube'. Reason:
The file './freetube' does not exist or could not be executed.
```

I don't know what to tell, maybe it's a NixOS thing? the flatpak version worked on NixOS on my laptop however

**Comment by Synkky** [comment]
It could be, but since you said it worked on your laptop (with the same distro and everything), probably not...
Can you try out the AppImage instead, to see if the same error occurs?
You might need an AppImage launcher though.

**Comment by 18fadly-anthony** [comment]
@Synkky I have not tried removing the config files, I will do that next time, I won't be able to test anything on my desktop until Sunday though, can you recommend me an Appimage launcher to use when I test it? Happy Halloween by the way

**Comment by Synkky** [comment]
Try out the latest release first instead. It should updated on Flatpak.
(Move your config files elsewhere and uninstall the version you have right now before installing the new one just to reset every variable I can think of)

**Comment by Synkky** [comment]
I have no idea what's going on with your rig.
Sorry, I really wish I could help you.
The closest thing I could find similar to this problem was [this](https://stackoverflow.com/questions/23569364/pip-does-not-exist-or-could-not-be-executed-within-virtualenv), but I don't think it's related.

Stupidest and most nonsensical thing I can come is... try to run without `./` attached???
Maybe add the folder `freetube` is on to PATH and then try to just run `freetube` (or whatever the name of the file is) on a new terminal???
I honestly have no idea...

**Comment by 18fadly-anthony** [comment]
@Synkky Tried adding it to PATH and that didn't work either, at this point I'm using freetube just to manage my subscriptions and using [streamlink](https://github.com/streamlink/streamlink) to watch videos

**Comment by 18fadly-anthony** [comment]
Hello, I finally fixed the issue on my end, turns out I was missing a GPU driver, fixed it by following code to my `/etc/nixos/configuration.nix`:
```
  hardware.opengl.extraPackages = with pkgs; [
    amdvlk
  ];
```
The explanation can be found here: https://nixos.org/manual/nixos/stable/#sec-gpu-accel-vulkan-amd
>Modern AMD Graphics Core Next (GCN) GPUs are supported through either radv, which is part of mesa, or the amdvlk package. Adding the amdvlk package to hardware.opengl.extraPackages makes both drivers available for applications and lets them choose.

**Comment by 18fadly-anthony** [comment]
Update, just in case anyone follows this advice, when I rebooted it caused a blank screen. Fixed by adding the following:
```
services.xserver.videoDrivers = [ "amdgpu" ];
```
