### ISSUE TITLE
Use format string for published Date.

### ISSUE THREAD

**Issue by kyotaro** [FreeTubeApp/FreeTube#725]
Use format string for the date of the published date on the playback screen.
The current date format is American.
I would like to match the Japanese format, so could you use the format strings?
It would be nice to have a format string like C#.
### sample: 
0=year, 1=month, 2=day
Current "Oct 25, 2020" = "{1} {2}, {0}"
British "25th Oct 2020" = "{2}th {1} {0}"
Japanese & Chinese "2020 年 10 月 25 日" = "{0} 年 {1} 月 {2} 日"
simple "2020/10/25" = "{0}/{1}/{2}"

**Comment by GilgusMaximus** [comment]
Yeah that should be rather easy to implement. I'll leave it open as a good first issue for new contributors.
