### ISSUE TITLE
Values in Caption Settings not displaying properly

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#729]
**Behavior of the program**
The moment u go into the caption settings the values of all the fields are not displayed. When u try to see what other values there are it's only displaying blank fields, but when u hover on it the value will appear. See Screenshots

**Expected behavior**
Values should be displayed

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go watch a video
2. Click on 'CC button'
3. Click on 'Caption Settings'

**Screenshots**
![Capture_thumb](https://user-images.githubusercontent.com/73130443/97200782-8ef0f500-17a9-11eb-826e-17325db0da5c.PNG)
![Screenshot (16)](https://user-images.githubusercontent.com/73130443/97200795-91ebe580-17a9-11eb-9ee8-25ba4c615b5a.png)

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - OS Version: [1909]
 - FreeTube version: [0.9.2beta]

**Additional context**
Edit: It still persists in the current version. Updated the FreeTube version in the description.

**Comment by GilgusMaximus** [comment]
Th
