### ISSUE TITLE
Frame by frame advance

### ISSUE THREAD

**Issue by squinonescolon** [FreeTubeApp/FreeTube#730]
Would like to have frame by frame advance like in the Youtube player.
In the Youtube player you can advance frame by frame by pressing the , and . keys. I'm an animator and I use that feature everyday when looking at reference.

**Comment by GilgusMaximus** [comment]
There are already a lot of speeds available, so implementing a frame by frame speed should be relatively easy to do.
Adding speed would be enough for the moment, as we do not have any hotkeys available for it, and might need to revamp them a bit in order to make them fully customizable.

**Comment by PrestonN** [comment]
This wouldn't really be a speed and more so be something that can be done while the video is paused.  I'm assuming video.js has a plugin to allow this and if that's the case then it should be a pretty simple feature to include.

**Comment by PrestonN** [comment]
This has been implemented in the latest release, closing...
