### ISSUE TITLE
Errors on opening application and refreshing subscriptions

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#731]
**Behavior of the program**
When starting the application it gives me immediately 4 messages and 3 of them are errors. This also happens when u try to refresh ur subscriptions.

**Expected behavior**
Dont give any errors.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to 'Subscriptions'
2. Click on 'Refresh button'
3. See error messages in Screenshot below

**Screenshots**
![Screenshot (17)](https://user-images.githubusercontent.com/73130443/97290176-1d17ba80-1840-11eb-95ce-daaf08af67f2.png)

![Screenshot (22)](https://user-images.githubusercontent.com/73130443/97322656-ebb2e500-1867-11eb-8724-44c9a62121b9.png)
![Screenshot (25)](https://user-images.githubusercontent.com/73130443/97353265-bd470100-188b-11eb-9acc-eb4a49f7235d.png)

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - OS Version: [1909]
 - FreeTube version: [0.9.2]

**Additional context**
_edit:_ added more screens of errors
It still persists in the current version. Updated the FreeTube version in the description.

**Comment by linuxgirl22** [comment]
Just to add feedback that this is happening on Linux, Anarchy/Mate, too, with latest Freetube build.

**Comment by lucanomax** [comment]
Lately I'm having issues too.
Basically local API doesn't load vids but loads feed (with rss); invidious API doesn't load feed but loads videos.

I solved loading my feed with local API and switch to invidious when clicking on videos.
For some reason it doesn't automatically fall-back to secondary back-end when the main fails (yes, i have the setting on).

**Comment by linuxgirl22** [comment]
Just to add, incase it's useful. Errors were happening before one of subbed channels went dead. I decided to remove the channel and edited the db file. When I reloaded subs, the now-dead channel was listed with an empty placeholder image, with the ability to press the 'unsubscribe' button. But, interestingly, no more errors popping up! Very fast loading of subs too. :-)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
All the errors are gone. This seems to be fixed can somebody else confirm.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
i only get allot of errors when using the Invidious API

![Screenshot (29)](https://user-images.githubusercontent.com/73130443/98481547-ef912080-21f2-11eb-8b2b-0343ced45c43.png)
![Screenshot (27)](https://user-images.githubusercontent.com/73130443/98481548-f029b700-21f2-11eb-872f-f586c8206cc7.png)

**Comment by GilgusMaximus** [comment]
That is a problem with the Invidious API, so we are unfortunately unable to do something about this.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can someone else confirm that the errors are gone so i can close this issue
