### ISSUE TITLE
Video quality label

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#735]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
All the buttons on the videoplayer will show labels when u hover above them. So when u hover with ur mouse on the play button a label will appear with Play. All the buttons have this except for the videoquality button. 

**Describe the solution you'd like to see implemented**
Make a label for the button so when u hover above it is shows u the label.

**Comment by GilgusMaximus** [comment]
This is a problem in the module we use, so an update over there would be required. This is also visible when you change the language of the program, these do not get updated

**Comment by GilgusMaximus** [comment]
This has been implemented and also now the currently selected quality is displayed. So I'll close this issue
