### ISSUE TITLE
Not all video quality's are displayed

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#736]
**Behavior of the program**
While watching this vid: 
https://youtu.be/j7QwJ-M_GAI
i noticed when going into the video quality setting that there are only 2 options (720p and 480p).
So i went to YT and found out that the vid quality there is from 144p all the way to 2160p.
I know u guys cant do higher than 1080p yet but where did the other vid quality's go?

**Expected behavior**
All vid qualitys should be displayed

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to https://youtu.be/j7QwJ-M_GAI
2. Click on 'Video quality button'
3. Only 2 quality's are displayed

**Screenshots**
![Screenshot (19)](https://user-images.githubusercontent.com/73130443/97301579-d631c100-184f-11eb-961e-42b9f486d3d6.png)
![Screenshot (20)](https://user-images.githubusercontent.com/73130443/97301591-d92cb180-184f-11eb-85b2-cf832167a26d.png)

**Desktop (please complete the following information):**
 - OS: [win10]
 - OS Version: [1909]
 - FreeTube version: [0.9.1]

**Additional context**

**Comment by PrestonN** [comment]
The example you gave tells me that FreeTube had to fallback to the legacy formats in order to play that video, which can only max out at 720p.  There isn't anything we can do in this case.
