### ISSUE TITLE
FreeTube in Web Browser

### ISSUE THREAD

**Issue by dimqua** [FreeTubeApp/FreeTube#74]
Is it possible to launch the app as daemon, and open it in the browser? Just like a normal website. :-)

**Comment by wUFr** [comment]
well, if you look into `src` folder it certainly looks like a normal website. If that would be the case, i could even contribute some nice html/css to it (:

**Comment by LexHimself** [comment]
This is not possible, unless your browser has the required depencies. Launcing it as a daemon sure, but would it not just be easier to just open the app?

**Comment by PrestonN** [comment]
I guess the idea behind this is that we wouldn't have to rely on Electron and the user could use their preferred browser.  The other idea with it is that I wouldn't have to bake in features like back / forward navigation as well as redirecting YouTube videos to FreeTube.  While making this easier for me is appealing, I don't see it as user friendly as it currently is if we went this route.  Installing an application is easier than setting up a local server for the user.  While everything seems possible, I'd rather stick with our current approach.

I'm going to go ahead and close the issue to clear up the open section, but feel free to continue discussion if you'd like.
