### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Abricoms** [FreeTubeApp/FreeTube#741]
**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x ] Other. Please specify: Question

**Discussion**
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined

Is it normal that this keeps happening when I click on a video?

Thanks a lot for your time and have a nice day

**Comment by GilgusMaximus** [comment]
Please see whether installing the nightly builds solves this issue for you. Detailed explanation from Synkky can be seen here: #733

**Comment by delboy711** [comment]
I see the same thing, but only when I have a VPN enabled, and only for some videos.
Running FreeTube 0.9.1 Beta

**Comment by Mech0z** [comment]
> 
> 
> Please see whether installing the nightly builds solves this issue for you. Detailed explanation from Synkky can be seen here: #733

I just installed the portable latest build from Actions and it seems to work now on Win10! So I vote for a 0.9.2 beta 👍

**Comment by delboy711** [comment]
I just built FreeTube from git and am pleased to say it worked for me too.

Thanks

**Comment by PrestonN** [comment]
Closing since this is fixed in the nightly builds.  New patch release will be out this weekend
