### ISSUE TITLE
Suggestions for 1080p -- 1440p + 2160p -- Playback

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#75]
@PrestonN 

hi thank you for your work so far on this project its really good and i only found it yesterday, i usually develop for Linux and gtk on a casual basis, but i have a suggestion that maybe will help this project, i haven't tried to develop using electron yet but i think the following may help you to solve 2 issues in one try.
##
1 - using [MPV](https://mpv.io/) player for a back-end client player [(source code)](https://github.com/mpv-player/mpv)

2 - using YouTube viewer's [(source code)](https://github.com/trizen/youtube-viewer) for ideas and code hints
##
as i say this is just a suggestion and it may give you some ideas as YouTube viewer has successfully been able to display **1080p** and **4k** at **60fps** using MPV and other players as back-ends, all suggestions are open source and as such should conform with your privacy and GPLv3 license and also MPV player is cross platform.

take a look at the links above and i hope this may give you some ideas or maybe help implement this feature, i think the above options should help you to find a way to introduce hi resolutions into FreeTube also MPV can be also used to stream YouTube and embed in other applications, anyway thank you very much for taking the time and effort to develop this project.
##
kind regards - LinxGem33

**Comment by DanielJenkyn** [comment]
Hi, See issue #60 and the latest beta #100 discussion :)

**Comment by PrestonN** [comment]
Closing this issue as 1080p+ has been finished and will be included in the next release.
