### ISSUE TITLE
Can't play videos with Local API

### ISSUE THREAD

**Issue by 12323464** [FreeTubeApp/FreeTube#750]
Everything works except playing videos through local API, or rarely works, i have to reload the video a couple of times, but works with Invidious API. This is the error I receive when clicking on a video: "TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined", W10 user.

**Comment by Synkky** [comment]
Duplicate of #733

**Comment by uuuu1234** [comment]
Same here. Unfortunately this makes the app nearly unusable using the local API at this point.

OS: Arch
Freetube v 0.9.1

**Comment by Synkky** [comment]
@uuuu1234
I know you didn't read it because that's not **at all** what was stated there. Please try actually reading it.

**Comment by GilgusMaximus** [comment]
@Synkky is right here. Please read the issue completely and download the newest Github Action build to fix this.
