### ISSUE TITLE
 Local API Error: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by wdawgnc** [FreeTubeApp/FreeTube#751]
I've just recently been getting this error consistently with every video I try to watch.

 - OS: MacOS Catalina
 - OS Version: 10.15.7
 - FreeTube version: Version 0.9.1
 - FreeTube build: Release

**Comment by PrestonN** [comment]
Duplicate of #733
