### ISSUE TITLE
Unable to load video pages using local api

### ISSUE THREAD

**Issue by nib9888** [FreeTubeApp/FreeTube#752]
**Behavior of the program**
Whenever I try to load a page from Subscriptions, an error appears in its usual black bubble: 
```TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined```
The page then is stuck on loading. The dev options reveal another error: 
`Uncaught (in promise) TypeError: e.includes is not a function
    at renderer.js:14`
Some json occasionally pops up in the dev console stating (among other details about the video), `error: "Video unavaliable." `
Invidious works fine.

**Expected behavior**
The page loads.

**To Reproduce**
I just open a video from subscriptions and this happens. I'm not sure how to reproduce.

**Desktop:**
 - OS: Arch Linux x64
 - OS Version: up-to-date
 - FreeTube version: 0.9.1-1
 - FreeTube build: Built through the AUR `freetube-bin` package if it helps

**Additional context**
I don't proxy Freetube through Invidious, and I don't proxy it through anything else outside of the app. I _can_ load videos through Youtube in a web browser.

**Comment by j13m126** [comment]
I just wanted to report the same bug. 
I tried Flatpak and AppImage on Fedora 33.

**Comment by nib9888** [comment]
Sorry, I've just discovered that this is a duplicate of #733, and that the newest release solves this. Closing
