### ISSUE TITLE
TypeError: Cannot read property 'channelMetadataRenderer' of undefined

### ISSUE THREAD

**Issue by thansk** [FreeTubeApp/FreeTube#756]
I get this error when I refresh my subscriptions. This has happened in the previous version and happens now too.
`TypeError: Cannot read property 'channelMetadataRenderer' of undefined`

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 20
 - FreeTube version: 0.9.2
 - FreeTube build: Release

**Comment by GilgusMaximus** [comment]
Closing because this is a problem with a channel in your subscriptions.
See #668
