### ISSUE TITLE
Don't zip the installers made available for download

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#759]
**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify:

**Discussion**

Prior to the release of freetube vue,  the installers made available for download were not zipped.  With the release of the new version the installers are now being zipped but with little benefit, the downloads are already optimized for size so zipping them is negligible and adds an unnecessary step for anyone who wants to install or update FreeTube.    

In general it's very rare in this day and are to find an installer any software that is zipped Can we go back to non zipped downloads?

**Comment by arrowgent** [comment]
agreed zip dont really do anything.

for windows base the main options are zip and rar, other OS are more common to use tar.gz or 7z

https://itsfoss.com/tar-vs-zip-vs-gz/

if your goal is to improve compression for bandwidth and storage then use better compression formats

as for being a waste requiring twice the size when uncompressed:  lots of github use zip/tar/7z/rar for their releases
others willingly release .exe or .deb without a compression container

**Comment by GilgusMaximus** [comment]
The main argument from PrestoN was that users previously suggested the zipping in order to contain the date of file creation.
The data compression is not really a factor in here.

And to be honest, from my point of view, the argument with the timestamp is quite a good one to zip it. Because you get this advantage, and unzipping a file takes literally one command and a few seconds.

**Comment by grrrrr** [comment]
> the argument with the timestamp is quite a good one to zip it. Because you get this advantage, 

What argument, I might be missing them but I can not find any tickets discussing that zipping be done for reasons good bad or indifferent?

> and unzipping a file takes literally one command and a few seconds.

Just because it's quick doesn't mean it should be done.

**Comment by GilgusMaximus** [comment]
> 
> What argument, I might be missing them but I can not find any tickets discussing that zipping be done for reasons good bad or indifferent?

>The reason I was given for zipping them in the first place had something to do with the last updated timestamps on the files. They mentioned it being useful that the file in the zip file would always have the timestamp of when I released instead of it always being the timestamp of when the user downloaded it. I don't know the full use of it but that's the reason I was given. I figured there was no harm in the change so I went ahead and did it.

Quote from PrestoN's answer. And I agree. There is no harm in having users to click two buttons on their keyboard to unzip something. People go lengths to get more privacy and then getting tangled up in having to unzip a zip file is a bit odd to me.

If you _really_ want to avoid ZIP files you can use one of the repositories available for Linux, start to maintain something like Chocolatey for Windows or simply build from source.

**Comment by grrrrr** [comment]
> The reason I was given for zipping them in the first place **had something to do** with the last updated timestamps on the files. 

Right, so it seems like no one knows exactly the reason it's being done and instead of making less steps to install the program for the majority of users it's "tough, we don't know the exact reason why we are doing with it but deal with it or become a repo maintainer".

You could also digitally sign the releases binaries which would keep both the non zip wanting people and the time stamp wanting people happy.

**Comment by GilgusMaximus** [comment]
Yes that is the ultimate target. But that is Prestons are because he wanted to get the right certificates, e.g. for Windows with the money people donate towards the application, because they cost quite some money apparently

**Comment by PrestonN** [comment]
Releases are no longer zipped any more, so this can be closed. Nightly builds are required to be zipped however, so we can't change that.
