### ISSUE TITLE
Error HTTP 403 when toggle the comments

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#760]
**Behavior of the program**
I wanted to see the comments of a video, but instead, i got this message:

```
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Expected behavior**
Ability to see the comments

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to a random video
2. Click on 'see the comments'

**Desktop (please complete the following information):**
 - OS: Debian 10.6
 - FreeTube version: 0.9.2 beta
 - FreeTube build:  Release

**Comment by GilgusMaximus** [comment]
what kind of video did you test?
When I go to a video, it loads the comments normally.

Can you test this video: https://youtu.be/LMfdYX-krX4

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
i also get this sometimes running the latest version of FreeTube

Win 10
1909

**Comment by GilgusMaximus** [comment]
My best guess without more detailed information on which video is that the comments are disabled for the video.

**Comment by stemy2** [comment]
I tried multiple times on the same video, sometimes it works, sometimes i get the error message. So i'm sure it's not about disabled comments.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> 
> 
> My best guess without more detailed information on which video is that the comments are disabled for the video.

i can confirm that when i load comments when they are disabled for that vid i get this error.

But i still get this randomly like @stemy2

**Comment by GilgusMaximus** [comment]
This issue does not occur in the newer versions and was solved along the way. Therefore I am closing this issue. If it occurs again feel free to reopen
