### ISSUE TITLE
Captions dont always work

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#763]
**Behavior of the program**
Sometimes when playing a video with captions (not auto generated captions) the captions simply does not appear

**Expected behavior**
Captions must appear when watching a vid

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any vid with captions
2. Turn on Captions in any language 
3. Captions dont appear

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.

**Desktop (please complete the following information):**
 - OS: [Win 10 home]
 - OS Version: [1909]
 - FreeTube version: [0.9.2]
 - FreeTube build: [Release]

**Additional context**
none

**Comment by xeleven11** [comment]
Yeah and only the first listed captions work on any video.

**Comment by DuaneJaspers** [comment]
Seems fine for me when using Local API.

When using Invidious API around half of the captions don't work. 
![429 error](https://user-images.githubusercontent.com/37299563/97965267-61640700-1dba-11eb-9291-99f94a1f4f48.png)

So it looks like there is some rate-limiting happening.

I've used this video testing:
https://youtu.be/Ek3aeUhHaFY

**Comment by GilgusMaximus** [comment]
For the local API try to switch to legacy formats and then to dash formats again. It is a weird problem having to do with files not being available fast enough and the player not waiting for the files to load. We could easily implement a delay for the whole player initialization, although this is a pretty bad idea at the moment, because it means that loading the video will take even more time

**Comment by junglized** [comment]
Same for me. When using Invidious captions don't show up. I haven't had an issue with Local Ai so far. 
I'm on Linux Mint 21.2, installed .deb package.

**Comment by ApurvR20** [comment]
Captions are not working for me. I'm using v0.23.5 beta, with Local API enabled. Videos show options for selecting captions, but none of them appear, unfortunately.
