### ISSUE TITLE
Verified checksums?

### ISSUE THREAD

**Issue by herokunt** [FreeTubeApp/FreeTube#765]
**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [X] Other. Please specify: checksums to verify authenticity of the installer before we run it.

**Question**
I was just wondering if there is a page with all the checksums for the released assets available to download. I was just notified that should update to 0.9.2 and realized this before running the installer (.deb in my case).

Thank you!

**Comment by herokunt** [comment]
I guess my question is related to this, it would solve the issue of having to verify each download although I'd still like to have that option regardless i.e., installing from a new machine [ Update via app [stable, beta(pre-relese), edge] #767 ](https://github.com/FreeTubeApp/FreeTube/issues/767)

**Comment by GilgusMaximus** [comment]
At the moment we do not have checksums, probably because this is still seen as a Beta.
However providing them is probably not that much work to do and should at leas be available when the program has it's full release

**Comment by herokunt** [comment]
Thank you for clearing this up, looking forward to full release :+1:
