### ISSUE TITLE
TypeError since version 0.8

### ISSUE THREAD

**Issue by Cyborgscode** [FreeTubeApp/FreeTube#768]
Version: 0.8+
Source: RH RPM

Messages of this kind:  ( Lokal API )

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type object

popping up since 0.8 with next to any video played. 

Many vids do not play on first try, possibly because of the this bugs.

**Comment by GilgusMaximus** [comment]
Please update to 0.9.2.
Although this error sometimes occurs on the newest version as well, it is not as bad as it was, because a hot fix for the module used was implemented.

However a proper update with a more stable fix is planned, and also depends on the module creator updating his releases
