### ISSUE TITLE
Enhancement: Looping of video

### ISSUE THREAD

**Issue by aeroaks** [FreeTubeApp/FreeTube#77]
I am interested in having a automatic looping option for the video I am playing.

**Comment by aeroaks** [comment]
Thanks!

**Comment by aeroaks** [comment]
I am willing to try and implement it.

**Comment by PrestonN** [comment]
This has been finished.  Expect to see this in the next release.

**Comment by FireFace30** [comment]
I know this is already closed, but I've found that if you go to "%userprofile%\AppData\Local\freetube\app-0.3.2\resources\app\src\templates" and add "loop" after autoplay in the video tag in player.html, you now have looping videos.
