### ISSUE TITLE
FreeTube plugin for Chrome

### ISSUE THREAD

**Issue by kyotaro-iijima** [FreeTubeApp/FreeTube#773]
FreeTube plugin for Chrome.

When user click on a youtube link in user browser, it will play on Freetube.
No need to copy and paste URLs.
The number of users is expected to increase dramatically.

Key Points
Launch freetube using a custom URL scheme.
On windows, they need to write to the registry, but it should be possible on electorn.

**Comment by PrestonN** [comment]
Privacy Redirect just recently added support for opening links into FreeTube and also supports Chrome based browsers. I would recommend giving that a try as I will not be publishing any extension myself for any Chrome browser.
