### ISSUE TITLE
History.db import

### ISSUE THREAD

**Issue by AmandaONeilll** [FreeTubeApp/FreeTube#776]
Frankly im not sure if i should put this under a bug or not.

**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [* ] Other. Please specify:

**Discussion**
A while ago i had a problem with the new history.db import feature, at first it seems to have been solved with the handy converter i was provided, but there seems to have been a problem that it had skipped some items and still imported the history.
at first it gave me the impression that it was just a false positive. However i have noticed that it was not the case after all, it indeed misses some items, converter or not, i tried to see if this is because some items have been marked instead of watched but it was all the same result.

My question here is what may cause this or is there a yet a solution to find to this? is there perhaps something wrong with the way the exporting is handled? as i tried multiple exported files and its all the same result.

I have not put this under an issue since i think this isnt really that big of a problem yet still something id like to see if there is a solution for it.

**Comment by GilgusMaximus** [comment]
So the converter skips over any video that is duplicate in the history (this seems to have happened for some reason?) and all videos that you already have watched in the new FreeTube version, because adding videos twice would also result in duplicates.

**Comment by AmandaONeilll** [comment]
i se,e while this explains this beahviour partly im curious to know why this is not the case for a video that has been marked was watched but has never been added twice.

Like if i get rid of everything and start fresh, this skipping thing still happens and videos are missing, almot sure its the ones that have been passivly marked once but not watched, the oens that have bene directly watched are all there.

**Comment by GilgusMaximus** [comment]
If they are not added correctly to the file, or important data is missing, it can happen that the app skips it. There is not much I can do about that. The project works in a way that it works on the syntax I had in my history file and that is it. And I probably didn't have that in there.

**Comment by AmandaONeilll** [comment]
Sorry i ddnt mean to sound like im trying to get this fixed as this far to minor of an issue, it was mroe just my interested to see how this could happen.

thank you for this answer.
