### ISSUE TITLE
Comment count

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#780]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Is it possible to add a counter for the comment section so people can see how many comments are a vid has 

**Describe the solution you'd like to see implemented**
Right next to the comments header a comment count. 

There are also two different ways how to handle this.

1. Just display the total of comments the vid has (203 comments)

2. Display the total of comments the vid had and the total comments loaded atm (20 / 203)

**Describe alternatives you've considered**
-

**Screenshots**
-

**Additional context**
-

**Comment by GilgusMaximus** [comment]
I tried that already. YouTube doesn't provide that information via Ajax.
So there is not really something we can do here
