### ISSUE TITLE
View account page through comment section

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#782]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
When u click on the profile picture or name in the comment section go to the channel of that account

**Describe the solution you'd like to see implemented**
Click on account name or profilepicture to go to the account page

**Describe alternatives you've considered**
-

**Screenshots**
-

**Additional context**
-

**Comment by eunbeek** [comment]
Hello,
May I work on these additional changes? 
My suggestion is adding edit button next to profile name in the selection.

![image](https://user-images.githubusercontent.com/50673489/100515630-7f1f5480-314b-11eb-9a11-aa01ccf93c0c.png)

Thanks!

**Comment by PrestonN** [comment]
@eunbeek Your PR in unrelated to the feature that was requested here.  It was requested to allow the ability to view a channel that has commented on a video.  If you'd like to work on the feature requested here, feel free to do so.

**Comment by eunbeek** [comment]
Thank you for letting me know it! 
I will try it and pull the request later.. 

:)

**Comment by eunbeek** [comment]
Hello @PrestonN 
I do not want to make it messed up so could you check this screenshot? 
Is it right and do you need to add this feature ;)?
=================================================================================
Process 
Recording Video : https://youtu.be/FHSUa8OfgTw

1. Click the comment thumbnail. 
![image](https://user-images.githubusercontent.com/50673489/101588022-6e74a700-39b3-11eb-9dac-ab7d4f084d27.png)

2. Redirect to the comment author's channel
![image](https://user-images.githubusercontent.com/50673489/101588139-b267ac00-39b3-11eb-919a-e1849d46d821.png)
=================================================================================
If you do not want to merge it, I am okay. 
I will pull the request soon after testing it more. 

Thanks

Eunbee Kim

**Comment by ChunkyProgrammer** [comment]
Added in #1126
