### ISSUE TITLE
Watch Later List

### ISSUE THREAD

**Issue by snakyjake1** [FreeTubeApp/FreeTube#788]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
No.

**Describe the solution you'd like to see implemented**

I would like to add videos to a Watch Later list, to watch the video in the future.

Click the "Watch Later" icon on the video , or right click, to add a video to a "Watch Later" list.
or
From the web browser extension, send the video link to a Watch Later list.

Then after watching the video, automatically remove it from the Watch Later list.

I also watch an easy to view/manage/organize Watch Later list.

**Describe alternatives you've considered**
None that I know of.

**Screenshots**

**Additional context**

**Comment by GilgusMaximus** [comment]
Closing because this will be part of the playlist feature. See e.g. #591
