### ISSUE TITLE
Allow Copy Paste inside Freetube

### ISSUE THREAD

**Issue by smh020** [FreeTubeApp/FreeTube#79]
Would it be possible to copy paste the text inside Freetube? I'd like to be able to copy things from the description or video titles.

**Comment by LexHimself** [comment]
The function keys do not seem to work somehow. (CTRL+C etc..)
As a workaround you can press the alt key to show the menu bar, then edit > copy.

**Comment by PrestonN** [comment]
This has been fixed for the next release.
