### ISSUE TITLE
Prevent Screen Suspension When A video is playing

### ISSUE THREAD

**Issue by PrestonN** [FreeTubeApp/FreeTube#790]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
At this time, FreeTube will only prevent screen suspension when a video is full screen on certain machines.  On some machines, FreeTube will not prevent suspension even if the video is full screen.  It has been requested that this should be changed to prevent suspension when a video is playing, regardless of if the video is full screen or not.

**Describe the solution you'd like to see implemented**
Ideally, any time a video is playing, FreeTube should automatically prevent screen suspension.  This should be disabled again if a video is paused or if the video player is destroyed.

**Additional context**
Using the `prevent-display-sleep` option within the [powerSaveBlocker](https://www.electronjs.org/docs/api/power-save-blocker#powersaveblockerstarttype) object should likely be used to accomplish this.

**Comment by jxhn** [comment]
Looks like this can be closed thanks to https://github.com/FreeTubeApp/FreeTube/commit/6c9e176249b35eb2ceb23504b5b6a43b5caba87a

**Comment by PrestonN** [comment]
Yep. I agree.
