### ISSUE TITLE
Open link in FreeTube via command line?

### ISSUE THREAD

**Issue by snakyjake1** [FreeTubeApp/FreeTube#792]
**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify:

**Question**

How do I open a YouTube video link into FreeTube from the command line?

I get my YouTube subscriptions from a RSS reader.  From the RSS reader there's an option to open the YouTube URL/Link in an external browser.  This accepts a command line option.

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: 7
 - FreeTube version: 0.9.2
 - Installation Method (If applicable): Portable
 - Primary API Used: Local API

**Comment by PrestonN** [comment]
Portable installations of FreeTube are not supported with command line options.  You must use a version that installs FreeTube to your system (In your case, the .exe build) in order to use the command line.

Once installed, you can use the command line to open videos with `freetube [VIDEO URL]`.
