### ISSUE TITLE
Menu does not translate

### ISSUE THREAD

**Issue by milotype** [FreeTubeApp/FreeTube#793]
**Behavior of the program**
Menu at the bottom does not translate when having narrow window.

**Expected behavior**
Menu should translate.

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/43657314/99198553-bed45c80-2799-11eb-96bc-973d4418a3b5.png)

![screenshot2](https://user-images.githubusercontent.com/43657314/99198556-c3007a00-2799-11eb-9456-ea582f64fbdc.png)

**Environment Information (please complete the following information):**
 - OS: Mac
 - OS Version: 10.11.6
 - FreeTube version: 0.9.2
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment]
Wow. Good catch. Never used the app in such a small window. Should be easy to do tho

**Comment by saideepesh000** [comment]
@GilgusMaximus @PrestonN , can I work on this

**Comment by PrestonN** [comment]
Sure thing. Not a problem.

**Comment by milotype** [comment]
@PrestonN, @saideepesh000: The main menu item "More" still does not translate (submenu items do translate) in Croatian.

    OS: Mac
    OS Version: 10.11.6
    FreeTube version: 0.12.0
    Primary API Used: Local API

**Comment by GilgusMaximus** [comment]
Please update to the newest nightly build and also check that the field is translated over at Weblate. I fixed an issue yesterday, but e.g. for German the text was not yet translated as well

**Comment by milotype** [comment]
@GilgusMaximus Great! LGTM!
