### ISSUE TITLE
Tooltip positioning

### ISSUE THREAD

**Issue by milotype** [FreeTubeApp/FreeTube#794]
**Behavior of the program**

1. A tooltip does not use the same css as other tooltips.
2. Toolips get cut off when window is narrow.

**Expected behavior**

1. Tooltips should use identical css.
2. Tooltips shouldn't get cut off.

**To Reproduce**
1. Go to 'Settings' and place mouse over the questionmark icon

**Screenshots**
![screenshot3](https://user-images.githubusercontent.com/43657314/99198810-42427d80-279b-11eb-9a4d-8179616dfc6b.png)

![screenshot4](https://user-images.githubusercontent.com/43657314/99198814-48385e80-279b-11eb-8595-23a65b04775f.png)

**Environment Information:**
 - OS: Mac
 - OS Version: 10.11.6
 - FreeTube version: 0.9.2
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment]
Hi, so this issue is not directly a problem, as most users can make the window bigger. However if someone wants to implement a future proof fix, we are open for PRs. Therefore I am also adding the good first issue label, as someone without knowledge of the code base, but with knowledge of CSS could fix this :)

**Comment by Murciegalo** [comment]
Hi everyone ,
I would like to start contributing to freeTube solving this issue,
Upon confirmation I will fork and start ;)

**Comment by GilgusMaximus** [comment]
Hi @Murciegalo , so as you can see right above your comment, @saideepesh000 has already create a PR for this and it is pretty much finished at this point. So unfortunately there is nothing to be done here anymore. This issue will be closed with the merge of the PR.
I'm sorry about that. But if you want to contribute anything else ,feel free to search through the open issues and also filter for good first issue. Thanks for you willingness to contribute, nonetheless :)

**Comment by PrestonN** [comment]
Closing as this should be fixed in the v0.11.0 release.
