### ISSUE TITLE
Playists not loading correctly

### ISSUE THREAD

**Issue by Kazcade** [FreeTubeApp/FreeTube#796]
**Behavior of the program**
Channel playlists do not load correctly. They always display as "0 Videos - 0 Views - Last Updated On". Freetube links to https://youtube.com/playlist?list=undefined instead of the expected playlist, regardless of backend.

**Expected behavior**
Channel playlists should work as expected (as in earlier versions).

**To Reproduce**
Go to random channel, select "Playlists", click on any playlist.

**Environment Information (please complete the following information):**
Windows 7 64-bit
Freetube 0.9.2 nightly portable
Local API/Insidious

**Comment by GilgusMaximus** [comment]
This seems to be a module issue which we are unable to fix. However PrestoN mentioned that there might be a fix in development already. So we are waiting for that at the moment

**Comment by PrestonN** [comment]
Should be fixed now as of v0.10.0
