### ISSUE TITLE
SponsorBlock FR

### ISSUE THREAD

**Issue by kubo6472** [FreeTubeApp/FreeTube#798]
**Important note**
This is #471 filled as a FR, since the OA doesn't seem to care to update his.

**Is your feature request related to a usage problem (not a bug)? Please describe.**
Annoying to skip in-video sponsors manually.

**Describe the solution you'd like to see implemented**
Integrate [SponsorBlock](https://sponsor.ajay.app/about).

**Describe alternatives you've considered**
Building a whole plugin/extension system, to let Users install/uninstall features themselves.

**Screenshots**
Implementation inspired by this NewPipe version: https://github.com/polymorphicshade/NewPipe

**Comment by catalin560** [comment]
+1 for the idea to implement SponsorBlock into FreeTube!
Youtube Vanced also did the same recently: https://vancedapp.com/
If you guys somehow manage to incorporate it into FreeTube, it will make it the ultimate Youtube experience!

**Comment by random29** [comment]
+1, Nice idea

**Comment by GilgusMaximus** [comment]
We are always open for PRs ^^

But the sponsorblock implementation is currently lower priority. Other things like playlists and finishing of v0.10.0 are higher on our priority list after we start developing more intensely again :)

**Comment by ToughGuyKunio** [comment]
Ping @polymorphicshade if you're interested in making a PR :smile:

**Comment by jordanbmoore** [comment]
I want this feature so bad

**Comment by Tenome** [comment]
+!
