### ISSUE TITLE
System sound dies after playing video for a minute or two in Freetube

### ISSUE THREAD

**Issue by RanTrycl** [FreeTubeApp/FreeTube#799]
Using 0.9.2 .deb on linux mint bionic, the system sound will die across the board after you play a video in Freetube for a minute or so. Restarting restores the sound -- until a video is next played in Freetube. This is pretty new behavior even though 9.2 has been installed for a while. I believe the local API is called first.

in case this is useful:
https://bin.disroot.org/?a11d77c89c9a411d#6F6hZRtRYzwxCvVtnqXdsD8EJFWcYvEetMA4yYgyU3z

**Comment by GilgusMaximus** [comment]
Hi, so thanks for sharing the logs. However I cannot see anything untypical in there. No errors relating to video playback or anything.

Could you please tell me, whether you use the nightly builds over at the actions tab or the builds on the releases page?

**Comment by RanTrycl** [comment]
thanks for the reply! I mainly posted this in case others had the problem. It could be a one-off. 

I use the .deb builds on the releases page. Let me know if there's anything I could post that might have more info.

**Comment by GilgusMaximus** [comment]
Could you try the .deb file from the newest build in the Github actions tab? These are built after every commit and usually contain most fixes for problems. Although your problem might not be directly fixed through a implemented fix, it might be fixed due to just having a new function version 👍 

If it doesn't work, we'll need to investigate further.

**Comment by RanTrycl** [comment]
Thank you so much for looking into it, GilgusM. Since no one else has this problem, and it looks more like a pulseaudio problem which is now showing up with other apps, I'm closing this as "not a Freetube issue." Much obliged!
