### ISSUE TITLE
Video is not available in your country

### ISSUE THREAD

**Issue by LexHimself** [FreeTubeApp/FreeTube#80]
Hi,

I do not know if the herokuapp is under your control, but the latest release gave me a lot of "video is not available in your country". 
These video's play fine when i visit them directly, so i would have to embed them every time, which gives youtube information.

I have set up my own youtubedl server and pointed the application to it, and the video's play fine in the app. 
My location is the Netherlands, and an example url which does not work with heroku: https://mannenpap.ga/api/info?url=https://youtube.com/watch?v=_va88w_KTxo (Please only use it for testing purpose, since it points to my home server. )

Instead of https://youtube.com/watch?v= the replacement hooktube can also be used in the youtubeApi.js. 

I see heroku supports multiple regions, would it be possible to set up a server for every continent, check the region the video can be visited from, and apply it, so direct links can be played instead of embed as fallback? 

On a sidenote, the youtubedl server also supports just the id: `let url = 'https://mannenpap.ga/api/info?url=' + videoId;` But this would default to youtube instead of hooktube.

**Comment by PrestonN** [comment]
Hey there. The next release will fix this as it will remove the dependency of the Heroku server and use your computer's IP to determine region availability.  I believe the functionality is already available in the development branch if you'd like to test it out.  If it isn't then I will do a code push later tonight.

**Comment by LexHimself** [comment]
Hi,

Thank you for the fast reply.
Awesome implementation! Probably the best way to handle the issue. 

Please do a push, since i am unable to get the current development code to work. New to electron, but: `electron-forge import, electron-forge start, electron-forge package` allow me to run, execute and use the release. 
The development version does start, but upon clicking anything except the hide/show sidebar, i will be presented with an infinite frozen loading  screen. Also the enter key on search does not work, i have to click the search icon to be presented with the above. 
It might just be my setup (Arch-Linux) or the cache, but the latter has been cleared several times.

A screenshot of the issue when clicking settings: https://mannenpap.ga/2018-05-01-090457_1200x827_scrot.png

**Comment by LexHimself** [comment]
The new push resolved the issue, no idea what went wrong before. I like the new improvements, video playback is a lot faster now! 
Thanks for the help, will start with translation tomorrow.
