### ISSUE TITLE
Importing subscriptions from a .json file

### ISSUE THREAD

**Issue by jallubaba** [FreeTubeApp/FreeTube#803]
**Behavior of the program**
When using the Import NewPipe function, program says "invalid subsciption file"

**Expected behavior**
Please describe clear and concise what you expected to happen.

**To Reproduce**
Please add all steps to reproduce the behavior:
1.https://takeout.google.com/settings/takeout
2. Click on https://i.postimg.cc/5tVdJ6wm/Capture.gif
3. Download
4. Import

**Environment Information (please complete the following information):**
 - OS: Win10 x64
 - FreeTube version: 0.9.2
 - Installation Method (If applicable): Portable

**Additional context**
Is this function even supposed to work like this

**Comment by GilgusMaximus** [comment]
Hi, I am not so sure I understand how the NewPipe format is related to your Google export function.

The NewPipe format is specifically tailored towards the Android app NewPipe. So only this .json will work. For importing subscriptions from YouTube, please refer to the [wiki](https://github.com/FreeTubeApp/FreeTube/wiki/Importing-Your-YouTube-Subscriptions)

**Comment by jallubaba** [comment]
Indeed, thanks it works.

**Comment by GilgusMaximus** [comment]
Great to hear :)
