### ISSUE TITLE
Hidden likes/dislikes but icon still showing

### ISSUE THREAD

**Issue by lucanomax** [FreeTubeApp/FreeTube#805]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
When video votes are disabled, the icon is still present.

**Describe the solution you'd like to see implemented**
Remove the like/dislike icon when votes are disabled.

**Describe alternatives you've considered**
I guess keep like/dislikes switched ON is the only way to not have that ugly icon without numbers.

**Screenshots**
![image](https://i.imgur.com/dh7ruyt.png)

**Comment by PrestonN** [comment]
This is an over site and is easy to fix.  I'll get this fixed before the next release.

**Comment by PrestonN** [comment]
Should be fixed in the development branch / nightly builds now.  Expect to see it in the new release.
