### ISSUE TITLE
Error: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#810]
**Behavior of the program**
I can't watch any video because of this error, it loads indefinitely.

**Expected behavior**
The video page loads.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Click on a random video.

**Environment Information (please complete the following information):**
 - OS: Debian
 - OS Version: 10.6
 - FreeTube version: 0.9.2 beta
 - Primary API Used: Local API, but jump to Invidious API if not working

**Comment by zvkfhapjg** [comment]
I'm having the same issue

**Comment by MattRGX** [comment]
The same for me ! unable to see any video at all !

**Comment by PrestonN** [comment]
This should already be fixed in the nightly builds.  If you're still having issues in the nightly builds then we can re-open.  This fix will also be included in the next release.

**Comment by MattRGX** [comment]
where can we finds the nightly builds ?
