### ISSUE TITLE
YouTube links in e.g. descriptions open in external browser instead of FreeTube

### ISSUE THREAD

**Issue by mbirth** [FreeTubeApp/FreeTube#811]
**Behavior of the program**
When clicking a link to a different YT video inside e.g. a description within FreeTube, the clicked link opens in the external browser.

Example video: https://youtu.be/UlJB3t55u_c - see description box.

**Expected behavior**
I'd expect links to other videos clicked from within FreeTube to open in FreeTube.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open https://youtu.be/UlJB3t55u_c in FreeTube
2. Click on the youtube.com link in the description
3. Notice how it opens in the external browser

**Environment Information (please complete the following information):**
 - OS: Mac M1/ARM
 - OS Version: macOS Big Sur 11.0.1
 - FreeTube version: 0.9.2 Beta
 - Primary API Used: Local API

**Comment by MLJBrackett** [comment]
Could I take a shot at this? If so, please assign me and I'll get to work!

**Comment by GilgusMaximus** [comment]
Sure, if you need any help let us know ! Thanks for your interest in contributing 👍 
If you got a bit of code already, it is easiest to create a draft pull request and then discuss any problems there,

**Comment by lfom** [comment]
Up, because it was redirected from #1117. FreeTube is awesome, the only thing I found missing so far is how it handles YT links inside the app. All related links shown in this issue and #1117 should open transparently in FreeTube itself. Ideally, known shortened URLs like bit.ly and goo.gl should be parsed and the redirected as needed.

**Comment by Svallinn** [comment]
![do_it_myself](https://user-images.githubusercontent.com/41585298/112862357-36e65380-90a5-11eb-9a31-abd402ce945a.jpg)
