### ISSUE TITLE
Scheduled Live Streams Aren't Listed & No Notify Button for Them

### ISSUE THREAD

**Issue by ThisNekoGuy** [FreeTubeApp/FreeTube#812]
**Behavior of the program**
Scheduled live streams aren't listed like on YouTube until after said schedule stream has already started.

**Expected behavior**
Streams announced on YouTube even days in advance should be listed as such in channel view and not suddenly become visible without warning only the moment it starts. (A button to be notified of when a stream starts would also help with this.)

**To Reproduce**
1. Go to a channel with a known scheduled live stream
2. See that the scheduled stream is not visible

**Environment Information (please complete the following information):**
 - OS: EndeavorOS (Arch Linux)
 - OS Version: (Rolling-release distro)
 - FreeTube version: 0.9.2
 - Installation Method (If applicable): AUR
 - Primary API Used: Local API selected

**Comment by GilgusMaximus** [comment]
Can anyone using Arch confirm this?
On Windows I get scheduled streams.
E.g. the one from MishCatt seen below:
![image](https://user-images.githubusercontent.com/34301369/100618810-98c3c600-331c-11eb-9aa3-e3d5a28df9d7.png)

**Comment by Airradda** [comment]
Can confirm that on Arch the timestamp of the placeholder/announcement video is the posted time and not the premiere time:
![2020-12-09_13-02](https://user-images.githubusercontent.com/3744856/101675019-1e4c2200-3a51-11eb-806d-19d1061d4521.png)

**Comment by ThisNekoGuy** [comment]
I managed to take a link from a currently pre-scheduled livestream (at the moment of typing) and entered it into the FreeTube bar to see if I can even access it and arrived at this blank slate of a screen:

![image](https://user-images.githubusercontent.com/28468662/101876112-82560f80-3b51-11eb-8828-562c6b7b6df3.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi there i'm just checking in to make sure that this is still an issue. Can somebody confirm for me if this is still the case?

**Comment by ThisNekoGuy** [comment]
I'd need an example to test that with; I'm not personally aware of a live stream to re-test that for at the moment

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
here is a list with upcoming steams https://www.youtube.com/playlist?list=PLU12uITxBEPF4xItAsx_NSe0fVva1IIku

**Comment by ThisNekoGuy** [comment]
I take it that the playlist of scheduled streams not being viewable is a good example?
![Screenshot_20220516_135705](https://user-images.githubusercontent.com/28468662/168662964-0a6bd02f-ac66-4cda-aeae-70eabe4bffe7.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Oh well thats my bad i just provided the list and thought u pick one scheduled stream out of it. 

take this one https://www.youtube.com/watch?v=l05omJtjXDc&list=PLU12uITxBEPF4xItAsx_NSe0fVva1IIku&index=9

**Comment by ThisNekoGuy** [comment]
That does load, although there's no notify function
But that is an improvement over not being able to view them at all; although, subscribing to the channel doesn't make the upcoming scream appear in the subscription feed

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hmm thats weird. It does pop up in my feed.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Just to clarify i have upcoming stream listed very often in my feed with the correct timestamp. @Airradda do you still have this issue?

**Comment by Airradda** [comment]
Yes I do, the timestamp of an upcoming stream at 12pm is showing the posted time of 4:38am instead.

**Comment by absidue** [comment]
@Airradda Are you using RSS for your subscriptions? If yes, this is unfortunately not something we can currently solve as YouTube's RSS feeds don't include the premiere date, only the date that the video was published/announced.
See https://github.com/FreeTubeApp/FreeTube/issues/3356 for more details

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing, converted to a feature request in #4157 because the original bug is solved and the adding of the notify button is definitely a feature request
