### ISSUE TITLE
Key input T for theater mode

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#814]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
When u press 'T' in the YT player it enables theater mode. It would be nice to have for FreeTube to also have this feature.

**Describe the solution you'd like to see implemented**
Press 'T' to go in/out Theater mode

**Describe alternatives you've considered**
-

**Screenshots**
-

**Additional context**
Edited: some typos

BTW when u hover over the theater button the label says theatre instead of theater

**Comment by GilgusMaximus** [comment]
Hi, so as I mentioned for some other hotkey wishes, there will be a major rewrite for custom hotkeys anyways. But adding this now makes sure it will be covered later on. : )
