### ISSUE TITLE
Does freetube really need libcups ?

### ISSUE THREAD

**Issue by canoine** [FreeTubeApp/FreeTube#816]
Hello,

Trying to run freetube 0.9.2 portable x64 on gentoo linux amd64 stable, I meet a dependency problem :

```
$ ./freetube
./freetube: error while loading shared libraries: libcups.so.2: cannot open shared object file: No such file or directory
```

Indeed, cups libraries aren't installed on my computer, as I don't need cups at all. And I wonder if freetube really needs this library. Does it ?

**Comment by PrestonN** [comment]
Since FreeTube is built on top of Electron, I have no control over what libraries are required or not.  Because of this, I can't guess on what the library in question is used for or how to remove it if it wasn't being used.  Unfortunately there is nothing that can be done about this dependency.

**Comment by arrowgent** [comment]
cups is the base for printers and pdf printing

dependencies are sad... but we live with them...

99% of people will have cups installed just because everything requires it.

nice find though
