### ISSUE TITLE
toast-holder blocks clicks to UI items underneath

### ISSUE THREAD

**Issue by mbirth** [FreeTubeApp/FreeTube#821]
**Behavior of the program**
On opening the comments to some video, I got various error messages which spanned over half of the window.

After they vanished, I couldn't click the seekbar, the share buttons or basically anything that's under where the error messages were. It's like the messages just turned invisible but are still there.

**Expected behavior**
Once the errors disappear, the areas underneath should become clickable again.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to some video, e.g. open comments to have some errors popping up
2. Resize the window so that the errors pop up over e.g. the "Click to View Comments" link
3. After the error messages disappear, try clicking the "Click to View Comments" link
4. See how you can't click it

**Screenshots**
After this error:

![Screenshot 2020-11-30 at 22 22 53](https://user-images.githubusercontent.com/130302/100667361-b44dc180-335a-11eb-9831-2a4183ba0867.png)

This is the area where I can't click anything:

![Screenshot 2020-11-30 at 22 23 25](https://user-images.githubusercontent.com/130302/100667432-ca5b8200-335a-11eb-87e5-ff9b16eea491.png)

**Environment Information (please complete the following information):**
 - OS: Mac with M1 chip
 - OS Version: macOS Big Sur 11.0.1
 - FreeTube version: 0.9.2
 - Installation Method (If applicable): DMG
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment]
Hi, thanks for catching this.
I'm gonna go ahead and say that this is a nice first issue to get anyone's toes into the water.
So if anyone wants to try this let me know and I'll assign you. PrestoN and I are also happy to provide some assistance if needed :)

**Comment by PrestonN** [comment]
This has been fixed.  It was a simple CSS class change.  Will be included in the next release.
