### ISSUE TITLE
Can I theoretically make a GTK frontend for this?

### ISSUE THREAD

**Issue by overlisted** [FreeTubeApp/FreeTube#823]
**Topic**
- [ ] Coding
- [-] Contribution
- [ ] Languages
- [ ] Setup
- [ ] Other. Please specify:

**Discussion**
Is it possible to make an alternative frontend for this app? If so, I would start making a GTK one very soon.

**Comment by PrestonN** [comment]
We're FOSS, so there isn't much stopping you from doing anything as long as you abide to the license.

Having said that, there's probably not a whole lot here in this repository that would help you with a GTK app, considering the code base / libraries available will be vastly different.  You'll likely get more luck starting from scratch and taking advantage of the [Invidious API](https://github.com/iv-org/documentation/blob/master/API.md) to handle your requests to YouTube.

You're welcome to ask any basic questions over in our Matrix room if you'd like.  I think there's even one or two GTK apps that you may be able to help out instead so you don't have to start from scratch, I don't have any links to them unfortunately.

Good luck if you do end up making a GTK app.  I'd be interested in seeing it once it's in a working state.
