### ISSUE TITLE
Wish to have an rpm package for OpenSuSe

### ISSUE THREAD

**Issue by LambLeeg** [FreeTubeApp/FreeTube#824]
**Describe the solution you'd like to see implemented**
So, the OpenSuse is a popular distro but there is no official rpm package, although, there is an rpm for Fedora. And I just want to claim that we need to have rpm for OpenSuse.

**Comment by PrestonN** [comment]
From my understanding, if a system is using RPM or whatever for a package manager, then the binary will install.  Just because I label the RPM file as a Fedora file on the website doesn't mean that the file won't work for OpenSUSE.  Unless I'm missing something, you shouldn't have any problems with the build already available.

**Comment by PrestonN** [comment]
Unfortunately I'm not seeing anything in the [build configuration documentation](https://www.electron.build/configuration/linux#LinuxConfiguration-target) for making an RPM binary specifically for openSUSE.  Even if it's possible, I'll also need to update our CI workflow to incorporate this change, which means that it needs to be buildable on an Ubuntu based system.

I can only suggest that you try a different build such as the AppImage or the Flatpak version, as I'm not seeing much available to me for making this happen.

**Comment by LambLeeg** [comment]
> Unfortunately I'm not seeing anything in the [build configuration documentation](https://www.electron.build/configuration/linux#LinuxConfiguration-target) for making an RPM binary specifically for openSUSE. Even if it's possible, I'll also need to update our CI workflow to incorporate this change, which means that it needs to be buildable on an Ubuntu based system.
> 
> I can only suggest that you try a different build such as the AppImage or the Flatpak version, as I'm not seeing much available to me for making this happen.

![image](https://user-images.githubusercontent.com/59935189/100993455-7c1ace80-3566-11eb-8d75-6caf258b7b8e.png)
When I use rpm command then it's the same

**Comment by PrestonN** [comment]
I was able to get the rpm build to install on an OpenSUSE VM. In the GUI installer, I told it to ignore the `libuuid` installation and continue without it. The app installs fine after that.

If you're still having issues, consider installing the app via [Flatpak](https://flatpak.org/setup/openSUSE/).

**Comment by llomellamomario** [comment]
A comment on the libuuid error. By the looks of it, it seems that it depends on libuuid, it searches the package name and fails. What opensuse ships with is libuuid1 for whatever reason. From what I understand from searching a bit, ideally you'd want to depend on a package providing libuuid.so.1 more than on the package itself. Or, if that ain't possible, at least specify you need either libuuid or libuuid1.
