### ISSUE TITLE
Search does not return results

### ISSUE THREAD

**Issue by uuuu1234** [FreeTubeApp/FreeTube#830]
**Behavior of the program**
Searching using the search box does not return results nor an error message.

**Expected behavior**
Searching  using the search box should return results.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Add any search term in the search box

**Environment Information (please complete the following information):**
 - OS: Arch
 - FreeTube version: 0.9.2
 - Installation Method (If applicable): AUR
 - Primary API Used: Local API

**Additional context**
I think it is not the same bug as #662 since I do not get any error message.

**Comment by GilgusMaximus** [comment]
I'm closing this issue because the search issues have been cleared in the newest nightly builds.
Please go to the Actions tab and download the newest version.
