### ISSUE TITLE
Local API Error + Glitches after trying to view comments

### ISSUE THREAD

**Issue by dorianvalerian** [FreeTubeApp/FreeTube#832]
**Behavior of the program**
Whenever I open a new video, it flashes a `Local API Error: Error: Unable to retrieve video metadata` OR `Error: url must be valid string`, and `falls back to invidious`. Video plays normally after this. Now, when I click on Click to View Comments, it flashes an error `[object Object]`, and comments do not open. After this, while the video still plays and I can pause it, I notice some issues when trying to control the video's progress bar (it doesn't always pop up when I hover above the video and when it does I cannot slide on it).

**Expected behavior**
Since I have set Local API preferred, it should ideally be using that (not that I mind invidious being used, but I read that its creator had left so I'm not sure how long invidious will be up). I should be able to view the comments, and it should also not break features of the video.

**To Reproduce**
1. Go to 'Most Popular' or any search result, really.
2. Click on any video on the page.
3. You should see the first error.
4. Click on `View Comments`. You should see the second error, and features of the video (Above described) should be broken.

**Screenshots**
When I click on a video (first error)
![image](https://user-images.githubusercontent.com/75203903/101258095-3288da00-3746-11eb-8298-804059e707f4.png)

After I click on View Comments
![image](https://user-images.githubusercontent.com/75203903/101258128-606e1e80-3746-11eb-932e-53bc8d63a651.png)
![image](https://user-images.githubusercontent.com/75203903/101258130-6237e200-3746-11eb-81f2-3239d42d084e.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 2004
 - FreeTube version: 0.9.2
 - Installation Method (If applicable): .exe from the freetubeapp.io website
 - Primary API Used: Local API (set preferred)

**Additional context**
This one time, the invidious API also failed, however I have not been able to reproduce it (therefore I don't have a screenshot).

**Comment by PrestonN** [comment]
We can't fix Invidious errors and those will need to be reported to their repository.

The other errors you mentioned _should_ be fixed in the nightly builds.  I'll likely be doing a release tomorrow and if that release fixes this then we can close this issue.

**Comment by dorianvalerian** [comment]
Just to update: the latest nightly build does seem to have fixed the Local API Error: Error: Unable to retrieve video metadata and Error: url must be valid string which would appear while opening a video, but I have encountered the comments error on most videos I tested right now (previously, every video without exception gave this error). Also, the video media controls are now not broken after I encounter the comment error.

**Comment by GilgusMaximus** [comment]
The local api comments were revamped lately. This issue has been resolved
