### ISSUE TITLE
Time slider not fully working when player width is high (Linux)

### ISSUE THREAD

**Issue by nikolayhg** [FreeTubeApp/FreeTube#834]
**Behavior of the program**
When the the player width is high enough and the user tries to navigate the video with the time slider, the time slider doesn't show up in the middle of the video navigation.

**Expected behavior**
The time slider should show up always when the cursor is at the desired position to show it.

**To Reproduce**

1. Set a big width of the window, maybe >1500px
2. Start a video
3. Try to show the time slider of the video in the middle
4. Bug: the time slider will not show up

**Screenshots**
Here is a gif file: https://gifyu.com/image/jevE
You can see that when the cursor is :
- at the beginning of the time slider, the slider shows up
- in the middle of the time slider, the slider does not show up
- at the end of the time slider, the slider shows up.

Another shorter gif:
![freetube2](https://user-images.githubusercontent.com/14300004/101277680-d4e4a400-37be-11eb-848b-6ec4b84ff7ab.gif)

**Environment Information (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 20.04
 - FreeTube version: v0.9.2 Beta
 - Installation Method (If applicable): deb
 - Primary API Used: Local API

**NOTE**
The issue is not reproducible if the window with is small enough (e.g. <900px)

**Comment by Airradda** [comment]
Is this still an issue in v0.9.3 Beta? I can't seem to reproduce the problem on Arch.

**Comment by nikolayhg** [comment]
Haven't tested the beta, I can check on the next stable release though.
