### ISSUE TITLE
Importing 562 Youtube Channels

### ISSUE THREAD

**Issue by jpalcantara** [FreeTubeApp/FreeTube#835]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ X ] Setup
- [ ] Other. Please specify:

**Question**
Please write down your question.
Hello,

  I am missing over 200 Subs from Youtube and this is because of the recent change from Google that ended the export of of Youtube subscription and the Google take out had all the channels but failed to import.  So I extracted all the channel from the Google take out and now I have a list of 562 Channels sitting in a text file.  Is there a a trick to import all these channel to either Freepipe or Freetube.
The text file has this type of listing "https://www.youtube.com/channel/UCczrL-2b-gYK3l4dfgdfgdfgQ"  562 of them. 

Any pointers would greatly appreciated.

**Comment by GilgusMaximus** [comment]
Hi, so please checkout our [YouTube import](https://github.com/FreeTubeApp/FreeTube/wiki/Importing-Your-YouTube-Subscriptions) section in the Wiki.

Also your link does not work. If the linked solution does not work, it'd be easiest if you could post a few channels as code in here to take a look on what the format looks like.

**Comment by jpalcantara** [comment]
I have an update! It turns out that the Google Take out had 294 Duplicates and I used Notepad++ to remove Consecutive Duplicate Lines and gave me exactly 394 Subs that Freepipe had imported to begin with.

Problem resolved!

**Comment by GilgusMaximus** [comment]
Okay that is a valuable information. Thanks a lot :)
