### ISSUE TITLE
Invite translators in About page

### ISSUE THREAD

**Issue by milotype** [FreeTubeApp/FreeTube#837]
**Describe the solution you'd like to see implemented**
Add a new string to invite translators (maybe after "Found a bug? …") on the "About" page of the app ("#& About" in the .yaml file). The new string could be similar to what is used on the GitHub page in the section about localization.

My suggestion:
_We are actively looking for translations! We use Weblate to make it easy for translators to get involved._

The word "Weblate" should have a link to "https://hosted.weblate.org/engage/free-tube/", which is the same link used on the FreeTube's wesite.

**Comment by PrestonN** [comment]
This is already planned for our v0.10.0 release.  The about page will be revamped to include new information and include new links for the newer channels available such as Weblate.  This is why the About page currently doesn't have translation strings, as they have yet to be created for the new page.

**Comment by PrestonN** [comment]
The about page has been updated within the dev branch and will be included in the next release. A link to Weblate has been included.
