### ISSUE TITLE
New subscription in one profile is shown also in another profile

### ISSUE THREAD

**Issue by nikolayhg** [FreeTubeApp/FreeTube#839]
**Behavior of the program**
When I create a subscription in one profile, sometimes it is shown also in another profile. When exactly, I don't know yet.

**Expected behavior**
A new subscription should appear only in the profile in which it was created. 

**To Reproduce**
Not sure what the exact steps to reproduce are. Currently It is reproducible on my setup as following:
1. Have multiple profiles
2. Enter the last profile
3. Make a new channel subscription
4. Switch to the first profile
5. The new channel subscription is shown in the first profile
6. Delete the subscription from the first profile (aka Unsubscribe)
7. Switch to last profile
8. The subscription is deleted also from the last profile

**Environment Information (please complete the following information):**
- OS: Ubuntu
- OS Version: 20.04
- FreeTube version: v0.9.2 Beta
- Installation Method (If applicable): deb
- Primary API Used: Local API

**Additional notes:**
It seems like all new subscriptions created in any profile are added also to the first profile.

**Comment by GilgusMaximus** [comment]
This is not a bug but a feature. When you add a subscription to a profile it gets added to the All Channels profile as well. This allows users to have one profile with all their subscriptions active at once.

**Comment by nikolayhg** [comment]
ok, good to know that. There was no information in the UI about this fact and I lost many subscriptions because I was deleting them from the first profile. Would be useful to explain this in the UI. In the app it is not called "All Channels" profile - I am able to rename and actually have renamed it. Maybe set the name to "All Channels" and make it impossible to rename.

**Comment by pqhf5kd** [comment]
> ok, good to know that. There was no information in the UI about this fact and I lost many subscriptions because I was deleting them from the first profile. Would be useful to explain this in the UI. In the app it is not called "All Channels" profile - I am able to rename and actually have renamed it. Maybe set the name to "All Channels" and make it impossible to rename.

I was doing the same thing for a few minutes, came here looking to submit a bug and found this :D
