### ISSUE TITLE
autofill searchbar

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#840]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
It would be nice to auto fill the search bar when ur navigating with the arrow keys. 
So that u don't have to type it yourself and u can see what suggestions it returns on the auto filled words when u press the space bar.

**Describe the solution you'd like to see implemented**
screenshot 1: type in a word
screenshot 2: navigate with the arrow keys to one of the words and it gets auto filled in the search bar
screenshot 3: when u press the space bar it begins the search for the new words

**Describe alternatives you've considered**
-

**Screenshots**
![Screenshot (6)](https://user-images.githubusercontent.com/73130443/101339472-66fbb380-3876-11eb-9751-475764c4136f.png)
![Screenshot (7)](https://user-images.githubusercontent.com/73130443/101339475-67944a00-3876-11eb-9f77-8e00a913c065.png)
![Screenshot (8)](https://user-images.githubusercontent.com/73130443/101339477-67944a00-3876-11eb-85b3-05b43a01e664.png)

**Additional context**

**Comment by GilgusMaximus** [comment]
Hi, we are open for any PRs here.
With a bit more effort this could be done by a new contributor as well. If anyone is interested to do so, we are happy to provide help where necessary.

**Comment by Imperial-Dragon** [comment]
I would like to add this.

**Comment by GilgusMaximus** [comment]
Okay thanks for the effort. I'll assign you to this issue and would like you to create a Draft PR once you have a bit of code done. Then we can discuss any issues and problems there. But if you have any questions before, feel free to add them here :)

**Comment by Imperial-Dragon** [comment]
Hi, after going through the code, I saw that we are using HTML 5 `<datalist>` for showing the search options. but the `<option>` in datalist does not emit any DOM events. So we have option of implementing our own `<datalist>` component using unordered lists.
Now my question is do we really need the autocomplete feature of `datalist` ? because anyway we are updating our list of options after every input stroke by calling the api.

**Comment by Imperial-Dragon** [comment]
Hey @GilgusMaximus, check out my pull request. Do let me know if you are expecting any changes or improvements :)

**Comment by GilgusMaximus** [comment]
Thanks for creating a PR. I'll have to take a look myself. I'm usually not working on the front-end, because of Vue-JS. But I'll check it anyway :)
