### ISSUE TITLE
Link to FreeTube site @about page

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#842]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
In about page from the app there are allot of links, but none of the links directs u to the official FreeTube site. I think it is important that there is a link to official site, because then they can look up the info they're searching for or send the link to a friend to check it out. A minor change like this can lead to a big impact in ur marketing. 

**Describe the solution you'd like to see implemented**
Link in the about section to the official site. 

**Describe alternatives you've considered**
-

**Screenshots**
-

**Additional context**
-

**Comment by PrestonN** [comment]
The about page is planned to have a revamp in v0.10.0 where we will add more links and information in place of what's currently available.

We already have this logged in our projects board, so I'll close this as to not flood our issues list.
