### ISSUE TITLE
flatpak version of FreeTube won't start

### ISSUE THREAD

**Issue by RagglenLove** [FreeTubeApp/FreeTube#843]
I'm running the [flatpak version of FreeTube](https://flathub.org/apps/details/io.freetubeapp.FreeTube) on Xubuntu 20.04. I just received an update to FreeTube and now, FreeTube won't start:

```
flatpak run io.freetubeapp.FreeTube
/app/bin/zypak-wrapper: line 24: /app/freetube/freetube: No such file or directory
```

**Comment by PrestonN** [comment]
Update the app again. I've already made the fix.

**Comment by RagglenLove** [comment]
> Update the app again. I've already made the fix.

Works now, thanks.
