### ISSUE TITLE
Duplicates in subscription import (new import v0.9.3 beta)

### ISSUE THREAD

**Issue by ToughGuyKunio** [FreeTubeApp/FreeTube#844]
**Behavior of the program**
I used the new .json import function to import my (many) subscriptions from YouTube in the new FreeTube v0.9.3. beta. Several of my subscriptions became duplicates, some became duplicated one time and a few up to four times. If I use the unsubscribe button, all subscriptions from that channel are deleted.

**Expected behavior**
FreeTube could check and prevent duplicates.

**Environment Information (please complete the following information):**
 - OS: PopOS
 - OS Version: 20.10
 - FreeTube version: 0.9.3 beta
 - Installation Method (If applicable): Flatpak
 - Primary API Used:

**Comment by ToughGuyKunio** [comment]
I've check some more and the duplicates are both in the left panel and in the subscription view.

**Comment by GilgusMaximus** [comment]
So just to make this more clear, did you import the file a second time?

**Comment by ToughGuyKunio** [comment]
No. Only one import.

**Comment by GilgusMaximus** [comment]
Could you please do the same as #835 and check whether the file itself contains duplicates?

**Comment by ToughGuyKunio** [comment]
I've checked and the json file contains duplicates

**Comment by GilgusMaximus** [comment]
Okay thanks for checking.
It is annoying that YouTube now does it that way.

We'll try to fix that

**Comment by ToughGuyKunio** [comment]
Thanks! Is there a way I can manually fix this in the meantime?

**Comment by GilgusMaximus** [comment]
I mean manually, you can always go ahead and delete the duplicates from the YouTube file. I'm also not sure how NewPipe handles the new export format. But you could try to import it to NewPipe and see whether they filter out duplicates. And then exporting from NewPipe and importing into FreeTube might solve it. 

Although this is just speculation

**Comment by quentinDupont** [comment]
Do you have a trick to remove duplicates easily? (when you have 600 subscriptions...) :smile:

**Comment by GilgusMaximus** [comment]
I mean, personally: Do not have 600 subscriptions. :D 

It would be easier if this is implemented rather quickly. I might be able to take a look into this, but don't hold me feet to the fire.

**Comment by GilgusMaximus** [comment]
Okay I have fixed this with the newest nightly build.
Please let me know whether it works for you as well

**Comment by quentinDupont** [comment]
> Okay I have fixed this with the newest nightly build.
> Please let me know whether it works for you as well

I would really like to test it but i don't know how to download builds on github.. can't find the way..
