### ISSUE TITLE
Consider Tauri instead of Electron

### ISSUE THREAD

**Issue by PopeRigby** [FreeTubeApp/FreeTube#846]
## Topic
- [x] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [ ] Other. Please specify:

## Discussion
It’s still fairly early along, but [Tauri](https://tauri.studio) is shaping up to be a very strong contender to Electron.

Tauri is written in Rust, and based on and increasingly collaborating directly with [webview](https://github.com/zserge/webview).

### Comparisons
|Feature|Tauri|Electron|
| --- | --- | --- |
|Binary Size MacOS|0.6 MB|47.7 MB|
|Memory Consumption MacOS|13 MB|34.1 MB|
|Interface Service Provider|Varies|Chromium|
|Backend Binding|Rust|Node.js (ECMAScript)|
|Underlying Engine|C/C++|V8 (C/C++)|
|FLOSS|Yes|Yes|
|Multithreading|Yes|Kind of|
|Bytecode Delivery|Yes|No|
|Can Render PDF|Yes|No|
|Multiple Windows|Soon|Yes|
|GPU Access|Yes|Yes|
|Auto Updater|Soon|Yes*|
|Cross Platform|Yes|Yes|
|Custom App Icon|Yes|Yes|
|Windows Binary|Yes|Yes|
|MacOS Binary|Yes|Yes|
|Linux Binary|Yes|Yes|
|iOS Binary|Soon|No|
|Android Binary|Soon|No|
|Localhost Server|Yes|Yes|
|No localhost option|Yes|No|
|Desktop Tray|Soon|No|

\* Electron has no native auto updater on Linux, but is offered by electron-packager

**Comment by PrestonN** [comment]
I haven't heard of Tauri before so this is my first time hearing about it. I will say that it _does_ look interesting.

As you mentioned though, it looks like it's still in an early stage. There's a lot that would have to be done to do such a transition and it's probably something I don't want to tackle at the moment. Once FreeTube has slowed down on updates and ourselves, as well as Tauri, are in a more stable position, we can look into considering this again. I will however start keeping an eye on their progress as I do like the idea.

I'll close this for now, however we can re-open this once it's time to discuss it again.

**Comment by kubo6472** [comment]
Hey, I'm just casually mentioning another project similar to Tauri, that is using default web browsers instead of WebView: https://github.com/gluon-framework/gluon#internals this might be a conversation sooner rather than later. There are lots of apps for mobile, each with very different approaches, I like what FreeTube's doing on desktop, and would love similar UI/UX on mobile. I know it's probably a lot to ask, but I hope it will only get easier over time. With tools like capacitor.js, it might get even semi-auto.

**Comment by farfromrefug** [comment]
@PrestonN it might be time to look again at tauri. It is production ready for desktop (I did many apps with it) and in alpha for mobile.
It would be really awesome for the freetube app to be like 10mb(guess).

**Comment by Tensorect** [comment]
Yes I agree with @4NUB1S-0N-0P10M . 
I think tauri can be very nice for a project like freetube. 
I was really thinking of creating a fork of freetube written in tauri but that seems like a lot of effort for a non experienced dev like me.

Please consider tauri again :)

**Comment by moriel5** [comment]
I hope that this is being considered, as Electron makes FreeTube impractical on weaker devices.

Also, is there a way to launch FreeTube headless, with a local (same-device, not on a different device on the same LAN) WebUI in the browser of the user's choice? Do to the current situation with GPU offload, I believe that running FreeTube headless with the interface on Firefox will bring a better experience than running FreeTube as-is, for now.

**Comment by proJM-Coding** [comment]
From the FreeTube matrix room, sent by absidue.

> It's not so much that Tauri isn't ready now, more that the fact it will never be ready for something like FreeTube because it uses the system webview. One good example is that with Electron because it patches Chromium and we ship it, we can just disable web security features like CORS, so that we can make API requests to YouTube and load audio and video data from their servers despite the requests not coming from youtube.com, in Tauri however because it uses the standard system webviews disabling CORS is not possible, so we would have to come up with some way of proxying every single request through the rust layer including the requests made by the video and image html elements. It's the same problem that means making a client side only YouTube client that runs in a normal web browser isn't possible and is why Invidious and Piped etc all require a server that handles all the requests for them.

> There is also the fact that because the webviews and other native dependencies are provided by the OS which are are very different on different OSes and can by very out of date on some LTS Linux distros, we would be going from only needing to support one Electron version that we control, to having to support all these different things, with wildly different versions. Right now the only OS dependent code in FreeTube is the keyboard shortcuts, all other OS differences are covered by Electron, so we have the guarantee that code that we write and test on a Windows machine will work on macOS and Linux too, whereas with Tauri we would be in charge of handling those OS specific differences. So changing to Tauri would undoubtedly permanently increase the maintenance burden. One way to reduce it a bit would be to always require the latest version of all dependencies but then that would mean that on Linux, anyone using an LTS distro wouldn't be able to use FreeTube. Keep in mind we are just a small group of volunteers that work on FreeTube in our spare, not some company with infinite resources.

> So yes switching to Tauri would make it harder for us developers, users would also be worse off, please stop asking to making everyone's lives worse.

**Comment by quazar-omega** [comment]
That sounds like a good argument (aside from the unnecessary, but I guess understandable, ranty line at end), why not post it directly?  
No reason it should have been a "secret" until someone else decided to put it here on their behalf.  
It would also be better to close this as not planned if the idea has changed from the previous comments that said they were waiting to see more stability
