### ISSUE TITLE
Rich Subtitles

### ISSUE THREAD

**Issue by EmeraldSnorlax** [FreeTubeApp/FreeTube#847]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Some videos have fancy / rich / coloured / special subtitles (I don't really know what they are called, sorry) and they don't get rendered properly (at all) like normal subtitles do

**Describe the solution you'd like to see implemented**
A way to display these fancy subtitles; if its too much time to have the full colour and positional data, falling back and drawing them as normal subtitles is fine?

**Describe alternatives you've considered**
Not using subtitles for that video, just displaying them as plaintext, generic subtitles as like the majority of videos

**Screenshots**
Here is an example video: https://youtu.be/L-MVk5I6wjo (Seems to be for all languages)
https://t89.s3-us-west-1.amazonaws.com/2020/11/MrzFzkFW/unknown.mp4 (expected output -- please note the video has audio)

**Comment by EmeraldSnorlax** [comment]
The subtitle data seems to be here: 
http://video.google.com/timedtext?lang=en&v=L-MVk5I6wjo

**Comment by GilgusMaximus** [comment]
Wow okay. First time I see something like this. Looks interesting.
To implement that either VideoJS has to support it natively (I'll have to check whether it does), or we would need a VideoJS plugin for that.

**Comment by EmeraldSnorlax** [comment]
Apologies for the necro, but it now seems to be in a mostly usable state for videos like this -- while it could be be improved (sometimes the text is duplicated) its currently usable enough so feel free to close this issue if you want to (i suppose the duplication still counts as a bug?)
![image](https://user-images.githubusercontent.com/43452521/121518753-5f14fb80-c9e0-11eb-9ddf-2a7e87ce4c0b.png)

**Comment by ghost** [comment]
https://github.com/FreeTubeApp/FreeTube/issues/2073 was created for the duplication issue. I will close this issue in favor of that one

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Reopened as we never implemented the custom subtitle format.

More info: https://github.com/FreeTubeApp/FreeTube/issues/8405#issuecomment-3640793276
