### ISSUE TITLE
Display a persistent notification that allows users to interact with media via built-in media keys.

### ISSUE THREAD

**Issue by ACodingGenie** [FreeTubeApp/FreeTube#848]
**Description of issue**
I've seen some closed issues relating to keyboard shortcuts which can be used while the app is in foreground to play/pause and do all sorts of actions. But I would like to see a way of playing or pausing, skipping to next video, going back to previous video via media keys which are built into most laptops/PC keyboards nowadays while the app is in the background. Seems like currently you have to switch to the app which can be buried beneath other apps to able to perform such actions, and this can be slower than simply hitting the media hotkeys already build into the keyboard for the same purpose.

**Describe the solution you'd like to see implemented**
Chrome, Spotify and numerous other applications generally display a persistent notification in the notification drop-down menu regarding the current video/song that is being played and the user is able to play/pause, skip next or previous, via the media keys. From what I see when a YouTube video is playing in Chrome, you can only play/pause, but this application can make it to where you can switch to the next or previous video when autoplay is turned on, or when the user has a queue enabled.

**Describe alternatives you've considered**
I don't believe there is one at the moment, user has to switch to the app and perform actions there.

**Screenshots**
Example media keys (can be built into F keys above the keyboard also):
![image](https://user-images.githubusercontent.com/68975831/101545137-d061ec00-3974-11eb-8e19-f38ddc0ec9b9.png)
Persistent notification in Pop!_OS (fork of Ubuntu) from Chrome:
![image](https://user-images.githubusercontent.com/68975831/101545357-220a7680-3975-11eb-8041-2da2032d10eb.png)

**Miscellaneous Comments**
Absolutely amazing app so far, thanks for contributing to the already thriving open-source community!

**Comment by PrestonN** [comment]
I'm not sure what OS you use, though FreeTube already does this on my machines, which run GNOME. It's been a while since I've tried on Windows though I'm fairly certain it's the same over there.

If there is nothing that needs to be done, then this issue can be closed.

**Comment by ACodingGenie** [comment]
The media keys just won't do anything on Pop!_OS (fork of Ubuntu) with FreeTube which was installed as a flatpak from Flathub. Doesn't matter if the app is in foreground or background. Nothing and I have no idea why :(

**Comment by tanandry** [comment]
I have the same issue with flatpak. I'm not using media keys, but a shortcut key that I configured myself. Before when I installed using AUR, it worked fine. But because it has problems with the inability to open externally using Privacy Redirect, so I installed the flatpak. I'm in Manjaro.

**Comment by rafael-ferro** [comment]
> The media keys just won't do anything on Pop!_OS

Same here with Pop!_OS 20.04. It would be an important feature.

**Comment by Etrit1** [comment]
Play/Pause works fine on Windows when FreeTube is in the background.
Sadly though, Next/Back doesn't do anything in a playlist.

**Comment by PrestonN** [comment]
So I think I've figured out the problem with this. The Flatpak version of FreeTube has MPRIS blocked because of Flatpak's sandboxing feature. I can however allow this so that the notification shows up for this build. If you install FreeTube using another method, you likely won't have noticed this problem.

I'll get this resolved here shortly.

**Comment by ACodingGenie** [comment]
For Pop!_OS users (temporary workaround allowing playing/pausing with Preston's idea, haven't figured out next/previous yet or may not be possible yet):

1. Download "Flatseal" from Pop!_Shop.
2. Go to Freetube inside of Flatseal
3. Allow the following permission: 
![image](https://user-images.githubusercontent.com/68975831/104513494-bf347c80-55bd-11eb-8bba-ede2f33998e5.png)
4. Add `org.mpris.MediaPlayer2.freetube` under "Session Bus" like so:
![image](https://user-images.githubusercontent.com/68975831/104513626-ec812a80-55bd-11eb-98a0-d9a629816629.png)
5. Relaunch Freetube is you have it opened or open it otherwise.
6. You should be able to play/pause now and see a notification like so: 
![image](https://user-images.githubusercontent.com/68975831/104513677-0458ae80-55be-11eb-9305-3983e22678ce.png)

Note: Flatpak docs do discourage from allowing access to ` --socket=system-bus` or `--socket=session-bus` but they also say it may be necessary for media controls to work properly. See here: https://docs.flatpak.org/en/latest/sandbox-permissions.html 
![image](https://user-images.githubusercontent.com/68975831/104513854-54377580-55be-11eb-8114-d256e4440ea3.png)

PS: If you use other Flatpak's also like I do and sometimes you'll run into ones where they don't have permission to user's files or whatever it maybe can be fixed via Flatseal.

**Comment by PrestonN** [comment]
I've made the above change to the Flatpak file for v0.11.0 which should enable the media player for those installs. Let me know if that doesn't work and I'll look into it again.

**Comment by tanandry** [comment]
@PrestonN I want to try it, but it seems there is an error when trying to install the flatpak version.

> Error: Error deploying: While trying to checkout 31ced8a890c02024e2c7b0d7510223afce3dce47a3d934f52871b71b3ff575ca into /var/lib/flatpak/app/io.freetubeapp.FreeTube/x86_64/stable/.31ced8a890c02024e2c7b0d7510223afce3dce47a3d934f52871b71b3ff575ca-9BS8W0: Opening content object 5b8cf44c3be3571a41ad332be5a9b09461590840c3ec0eabcc7f91f0f0118253: Couldn't find file object '5b8cf44c3be3571a41ad332be5a9b09461590840c3ec0eabcc7f91f0f0118253'
> error: Failed to install io.freetubeapp.FreeTube: Error deploying: While trying to checkout 31ced8a890c02024e2c7b0d7510223afce3dce47a3d934f52871b71b3ff575ca into /var/lib/flatpak/app/io.freetubeapp.FreeTube/x86_64/stable/.31ced8a890c02024e2c7b0d7510223afce3dce47a3d934f52871b71b3ff575ca-9BS8W0: Opening content object 5b8cf44c3be3571a41ad332be5a9b09461590840c3ec0eabcc7f91f0f0118253: Couldn't find file object '5b8cf44c3be3571a41ad332be5a9b09461590840c3ec0eabcc7f91f0f0118253'

**Comment by tanandry** [comment]
@PrestonN Have tested the flatpak version and all working nicely. The media keys / shortcuts work, it even shows up in KDE Connect on my phone.
