### ISSUE TITLE
Video Pop-Out

### ISSUE THREAD

**Issue by dorianvalerian** [FreeTubeApp/FreeTube#849]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
N.A.

**Describe the solution you'd like to see implemented**
It would be great if FreeTube could have a feature like what Opera and Vivaldi have (not sure about Chrome) in which you can click on this icon that appears over all videos to 'pop' them out — essentially the webpage will be as it was but the video will now be disassociated and be hovering on top of all windows (resizable, pause-play control, etc.).

**Describe alternatives you've considered**
N.A.

**Screenshots**
N.A.

**Additional context**
I understand if this isn't a priority, but thought I'd put this in so its there for you to see once the more urgent tasks are done.

**Comment by PrestonN** [comment]
This is already implemented. Click on the "Picture in Picture" button next to the quality options of a video.
