### ISSUE TITLE
Unify display of dates across the app

### ISSUE THREAD

**Issue by milotype** [FreeTubeApp/FreeTube#853]
MacOSX 10.11.6, FreeTube 0.9.3 Beta

If possible, please unify the display of dates across the app. Currently, in the case of Croatian, two different date formats are used:

`span.uploadedTime` => 30. 07. 2015.
`div.datePublished` => srp 30, 2015 (See screenshot below.)

Ideally, only one date format per language/locale should be used. 

In the case of Croatian, **span.uploadedTime** would be correct, while **div.datePublished** is completely unusable/wrong.

![DateFormat](https://user-images.githubusercontent.com/43657314/101683288-0aaab680-3a65-11eb-9c98-bca194a47854.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing, converted to a feature request in #4156 because this isnt a bug
