### ISSUE TITLE
Downloading build

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#858]
**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify: Downloading portable nightly builds for windows

**Question**
Downloading the portable nightly build for windows gives me a zip within a zip (im downloading the largest portable build for windows. I saw that there are 2 so im just mentioning it to be sure).
So i have to extract 2 zip files before i can execute the application, is it possible to just make it 1 zip instead of 2?

**Comment by PrestonN** [comment]
Unfortunately with the way that GitHub handles uploading artifacts, this can't be done. GitHub automatically zips anything uploaded to the nightly builds, regardless if they are already zipped or not. If I play around with it for a while I can maybe fix it but there would still be a folder within a zip file that has everything, so I don't feel like it's worth the effort.

I do make sure that this doesn't happen on full releases, which is where is really matters.
