### ISSUE TITLE
Channel 'Sort By' not working reliably

### ISSUE THREAD

**Issue by computeristic** [FreeTubeApp/FreeTube#859]
### Current behavior:
There are two bugs:

1. Changing 'Sort By' to 'Most Popular' doesn't load list of videos on some channels. It returns a local API error (TypeError: Cannot read property 'simpleText' of undefined), falls back to Invidious API, and then keeps loading indefinitely.
2. After changing the 'Sort By' to 'Most Popular' for a channel, this option persists when viewing other channels until it is changed back to 'Newest'.

### Expected behavior:
Changing 'Sort By' works for all channels and reverts to 'Newest' when navigating to other channels.

#### Bug 1: 

- Go to the channel 'Marques Brownlee'
- Change 'Sort By' to 'Most Popular'

#### Bug 2:
- Go to any channel and change the 'Sort By' option to 'Most Popular'
- Navigate to any other channel and notice the 'Sort By' option

### Environment:
- OS: macOS Mojave 10.14.6
- FreeTube: latest nightly build as of December, 10.

**Comment by GilgusMaximus** [comment]
Thanks for the report.
For the second bug, I want to add that the sort display actually changes to 'Newest' but the sorting is still the same

**Comment by GilgusMaximus** [comment]
This has been resolved through changes on the corresponding module a while back.
