### ISSUE TITLE
unexpected token '<EOF>' at 1:1 

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#861]
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**
Sometimes, when i'm trying to open the comments, i have this message.

**Expected behavior**
Please describe clear and concise what you expected to happen.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to a random video
2. Click on "see the comments"

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.

**Environment Information (please complete the following information):**
 - OS: Debian
 - OS Version: 10.6
 - FreeTube version: 0.9.3
 - Installation Method (If applicable): .deb
 - Primary API Used: invidious

**Additional context**

**Comment by PrestonN** [comment]
Can I ask what Invidious instance you use? This sounds like an issue with Invidious which we cannot fix here and needs to be logged over on their repository. Tagging @TheFrenchGhosty for visibility, though if I had to guess we'll need to find an instance to replicate the issue or get more information about the problem.

**Comment by TheFrenchGhosty** [comment]
Related: https://github.com/iv-org/invidious/issues/1535

Maybe?

**Comment by PrestonN** [comment]
I'll go ahead and close this since I believe it's an Invidious issue. If this ends up not being the case, then we can reopen

**Comment by etiennebacher** [comment]
As said in the [issue mentioned above](https://github.com/iv-org/invidious/issues/1535), this issue was fixed for the Invidious side [here](https://github.com/iv-org/invidious/pull/1633). However, I have a very similar error message:
```
{"error":"unexpected token '<EOF>' at line 1, column 1","errorBacktrace":"unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)\n  from /usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'\n  from /usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'\n  from /usr/share/crystal/src/json/parser.cr:37:7 in 'parse_value'\n  from /usr/share/crystal/src/json/parser.cr:13:12 in 'parse'\n  from /usr/share/crystal/src/json.cr:131:5 in 'parse'\n  from src/invidious/comments.cr:92:14 in 'fetch_youtube_comments'\n  from src/invidious.cr:2057:18 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'\n  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:212:5 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:94:12 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:158:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:70:5 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/logger.cr:17:35 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'\n  from /usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'\n  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'\n  from /usr/share/crystal/src/http/server.cr:468:13 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'\n  from /usr/share/crystal/src/fiber.cr:92:34 in '->'\n  from ???\n"}
```
**Environment:**
OS: Ubuntu
Version: 18.04.5 LTS
FreeTube version: v0.11.3 Beta
Installation method: .deb
Primary API Used: https://invidious.snopyta.org

This happens every time I click on "Click to View Comments" below the videos. Should I open a separate issue for this?
