### ISSUE TITLE
RPM spec file

### ISSUE THREAD

**Issue by rma-x** [FreeTubeApp/FreeTube#863]
**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify: Packaging

**Question**
Hi,

is the spec file available somewhere that is being used for building the Fedora RPMs of FreeTube? I would like to use it as a starting point for packaging FreeTube for openSUSE, but couldn't find it in the repository.

Thanks,
rma-x

**Comment by PrestonN** [comment]
There's nothing different that can be done in the build to make the RPM binaries behave differently on OpenSUSE. If you want to try, instructions for building FreeTube are [here](https://github.com/FreeTubeApp/FreeTube/wiki/Environment-Setup-and-Building-from-Source) and Electron builder configuration options are [here](https://www.electron.build/configuration/linux#LinuxConfiguration-target).

I've left some information over at #824 where I got the current RPM release to install on an OpenSUSE VM. You should also be able to install the app via Flatpak as well.

I'll go ahead and close this, however feel free to ask further questions here if you have any.

**Comment by rma-x** [comment]
I think you got me wrong, but maybe I didn't explain my intentions clear enough.

I neither want your RPM for Fedora to behave differently on openSUSE, nor do I want to install the Fedora RPM or a Flatpak on openSUSE.

Instead, I'd like to add FreeTube as a package to the [openSUSE Buld Service](https://build.opensuse.org/), so that it gets built there and is available through openSUSE's own package management. For that I would prefer using the presumably existing .spec file for Fedora as a starting point, so that I don't have to write that spec file from scratch.

**Comment by PrestonN** [comment]
Sorry about that, you're right that I wasn't fully understanding the question here.

As you alluded, electron-builder doesn't need a spec file to create the RPM file. If I had to guess it takes information about the project and creates that file internally.

I'm not 100% sure on what your next steps would be for making this happen, though I'm available for questions if you have any.
