### ISSUE TITLE
How to build from sources and avoid downloading electron (using system electron)

### ISSUE THREAD

**Issue by je-vv** [FreeTubeApp/FreeTube#865]
On AUR (Arch) there's a package which build freetube from sources, but it still downloads electron, and uses the electron downloaded.  It would be much better, since the package is built, that it would use the electron from the system.  How can one do such thing?  Is there a configuration or build option?  If not, how can it be done?

**Comment by PrestonN** [comment]
The only real way of doing so would be to clone down the repository and update the `package.json` to use the Electron version that's installed on your system and then build it yourself. Instructions for doing so are [here](https://github.com/FreeTubeApp/FreeTube/wiki/Environment-Setup-and-Building-from-Source).

If this doesn't work, then I unfortunately don't have any other suggestions for you. I don't maintain the AUR version so I cannot make changes to it to do something specific.

**Comment by je-vv** [comment]
But that sounds like a great start...  Thanks !
