### ISSUE TITLE
Request: Mention system requirements on website

### ISSUE THREAD

**Issue by jayrope** [FreeTubeApp/FreeTube#867]
Minimum system requirements (in my case for OSX) can't be found on website.
Stating them helps users in sticking to working software & hardware without a big need for upgrades.
Especially for OSX this is a permanent issue, as computers and software are very stable, however Apple forces users to rebuy software & hardware every few years, while same basic functionality remains.
Thank you.

**Comment by GilgusMaximus** [comment]
There aren't any real system requirements required. If you can run OSX, your PC should be able to run the application.

For building from source, you can find it in the wiki.

**Comment by jayrope** [comment]
Trying to install freetube on OSX 10.9.5 states it needs a minimum of 10.10. So there _is_ a system requirement.

**Comment by PrestonN** [comment]
FreeTube is built off of Electron, and is restricted by the requirements of Electron itself, as well as Chrome.

Electron requirements can be found [here](https://www.electronjs.org/docs/tutorial/support#supported-platforms). Chrome requirements can be found [here](https://support.google.com/chrome/answer/95346?hl=en) at the bottom of the page.

As was mentioned though, the requirements are lax enough where we usually don't need to put the requirements out there. I can add these links to the README though if we feel it's necessary.
