### ISSUE TITLE
Problem load video and Feed

### ISSUE THREAD

**Issue by dasaferi** [FreeTubeApp/FreeTube#872]
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**
Please write a clear and concise description of what the bug is.

**Expected behavior**
Please describe clear and concise what you expected to happen.

**To Reproduce**
Please add all steps to reproduce the behavior:

**Screenshots**
![Screenshot_20201214_150128](https://user-images.githubusercontent.com/71762370/102090808-38557e00-3e1e-11eb-8614-1eee3ce89ebe.png)

**Environment Information (please complete the following information):**
 - OS: [Kubuntu/KDE Neon]
 - OS Version: [Ubuntu 20.04]
 - FreeTube version: [e.g. 0.9.3, Nightly build? NO]
 - Installation Method (If applicable): [.deb and .AppImage]
 - Primary API Used: [Local API, Invidious API]

**Additional context**
FreeTube not load video and content of feed reader and Trending from local api and invidios api.

**Comment by PrestonN** [comment]
Is this still happening? YouTube has been down for the past few hours and obviously FreeTube won't be working either in that case. They should be back up now so I want to check if this is still happening before I look into this any more.

**Comment by dasaferi** [comment]
I've waited 22 hours and the problem still exists, I guess it's not a youtube or google problem because I can view the normal site correctly.

**Comment by PrestonN** [comment]
Could you please email me at freetubeapp@protonmail.com with an attachment of your subscriptions file? I won't be able to assist any further unless I know which channel is causing the problem.

Alternatively, if you know which channel is causing the issue, you can remove that channel from your subscriptions which should fix the issue.
