### ISSUE TITLE
High CPU load and video lag

### ISSUE THREAD

**Issue by coldspark29** [FreeTubeApp/FreeTube#875]
**Behavior of the program**
The video lags or slows down regularly while the audio stays normal. This happens on 1080p and with higher resolutions it gets even worse. 

**Expected behavior**
No lag

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Play a video
2. See the lag

**Screenshots**
![image](https://user-images.githubusercontent.com/19779511/102117456-9db96700-3e3e-11eb-893b-a16f5d312b66.png)

**Environment Information (please complete the following information):**
 - OS: Manjaro Linux
 - FreeTube version: 0.9.3-2
 - Installation Method: Compiled from Github
 - Primary API Used: Local API

**Comment by PrestonN** [comment]
Electron / Chromium on Linux does not have any video acceleration support, which can lead to poor playback or high resource usage depending on the device specs. There isn't much that I can do to help with this without any updates from Electron / Chromuim.

There's been a few requests to allow videos to be sent to other players such as VLC / MPV, which do have video acceleration. Videos played in these players would play much better than the built in player within FreeTube could. This would be the only real solution with the tools available to us at this time.

Apologies for the inconvenience.

**Comment by loui1024** [comment]
Just wanted to add that this is a problem for me on my Windows 10 machine, which has a good CPU and recent graphics card. It appears to be a problem specifically with the built-in player as I do not experience this issue on Invidious
