### ISSUE TITLE
Video gets pixeld or blurry when changing the resolution

### ISSUE THREAD

**Issue by coldspark29** [FreeTubeApp/FreeTube#876]
**Behavior of the program**
When changing the video resolution, the video resolution seems to change super low 

**Expected behavior**
Normal resolution change

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Play a video
2. See the screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/19779511/102118254-baa26a00-3e3f-11eb-9b9b-eda8e820929a.png)

**Environment Information (please complete the following information):**
 - OS: Manjaro Linux
 - FreeTube version: 0.9.3-2
 - Installation Method: Compiled from Github
 - Primary API Used: Local API

**Comment by PrestonN** [comment]
This is a duplicate of #595
