### ISSUE TITLE
Freetube Failing to Play/Fallback with Invidious API enabled

### ISSUE THREAD

**Issue by MetalNeo** [FreeTubeApp/FreeTube#877]
**Behavior of the program**
When I attempt to load [this video](https://invidious.snopyta.org/watch?v=dMRH96Ew5G4) with Invidious API set to default, I get 403 errors trying to load it. If I force reload (with ctrl + R), the video plays fine. If I set my default API to local, the video also plays fine.

**Expected behavior**
I expect the video to play under the Invidious API or automatically fall back to the local API.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Enable "Invidious API" under "Preferred API Backend."
2. Load the video linked above.
3. Observe the 403 errors in the console.
4. Ctrl + R or switch back to Local API and observe how video plays now.

**Environment Information (please complete the following information):**
 - OS: Arch
 - OS Version: Rolling
 - FreeTube version: v0.9.3-nightly-365 Beta
 - Installation Method (If applicable): Portable
 - Primary API Used: Invidious API

**Additional context**
There was a warning that stated: `WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".` Not sure if related.

**Comment by PrestonN** [comment]
Can you confirm that Fallback is enabled in your settings? FreeTube won't fallback to the other API if that isn't enabled. The ytdl-core message can be safely ignored and has nothing to do with this issue.

If you're getting 403 errors, that means permission denied, and that the Invidious instance might be blocking you. Could you please also try a different Invidious instance and see if that works instead?

**Comment by MetalNeo** [comment]
Yes, I forgot to mention that I had it toggled on.

I tested every other Invidious instance and all but two failed immediately and fell back to the Local API successfully. `invidious.tube` would time out on everything and (eventually) fall back to the Local API. `invidious.site` actually loaded the player and other video metadata, but also ran into 403 errors as well when trying to play it. Using Ctrl + R to refresh the video fixed the video when using `invidious.site` as well.

**Comment by PrestonN** [comment]
Doing some testing on my own, the same video directly on [https://invidious.site](https://invidious.site/watch?v=dMRH96Ew5G4) isn't working, so naturally it won't work on FreeTube either. There's nothing I can do about this situation.

The [https://invidious.tube](https://invidious.tube/watch?v=dMRH96Ew5G4) example you posted works both on the site directly as well as within FreeTube for me. The same goes for the [https://invidious.snopyta.org](https://invidious.snopyta.org/watch?v=dMRH96Ew5G4) instance.

I'm not able to replicate any 403 errors on my end. Are there any firewalls setup on your network? Have you tried a VPN to see if it behaves any differently? I'm inclined to believe that right now this seems to be an issue outside of FreeTube, though if it's possible to replicate then I can look into it further.

**Comment by MetalNeo** [comment]
I do not have a firewall (other than the default system one), but I do use a custom DNS to block ads and malware domains.

After doing some more testing, I have some odd results. I was still consistently getting 403 errors for that video, then tried temporarily changing to a VPN and changing my DNS (at separate times). In each case, the video started to work again. After switching back to my usual settings, the video was still working without errors. I am not sure what caused the issue before, but it appears to be fixed now. For now, I will close this issue unless I encounter another video with the same consistent behavior.
