### ISSUE TITLE
On closing freetube it doesnt save video position

### ISSUE THREAD

**Issue by koenradar** [FreeTubeApp/FreeTube#878]
**Behavior of the program**
Please write a clear and concise description of what the bug is.

When clicking on the close/exit button (default windows exit alt+f4 also works) it doesn't save the time in the current video.

**Expected behavior**
Please describe clear and concise what you expected to happen.

When i click on the close/exit button i would expect it to just save the position.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any video
2. watch any amount of time
3. and exit the player without first clicking away to another screen

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: 0.9.4 beta
 - Installation Method .exe,
 - Primary API Used: Local API

**Additional context**

**Comment by PrestonN** [comment]
This is a known issue. I'll try to get this fixed soon.

**Comment by koenradar** [comment]
Thanks for your swift reply i did search the issues and didnt find anything when this is fixed freetube will become even better thanks.
