### ISSUE TITLE
Linux (Debian/Mint) -  Full screen capability broken in v.093

### ISSUE THREAD

**Issue by linuxdevman** [FreeTubeApp/FreeTube#879]
When going to full-screen, which worked on the previous version now hangs the FreeTube application.

It appears that the window frame and root window "expand" but fail to repaint leaving audio playing, and the unsized video frozen.  I have discovered that the app believes it has expanded, but never finishes repainting and handing back control to the window.  If you understand where the application controls should be, you can move your mouse in the general vicinity and return the video to non-full screen mode by moving the mouse until you see the "hover text".  Then selecting it.

However all that does is allow you to use the window controls to shut the app, since it is still frozen and unstable.

Linux Debian Jessie (Mint 17.3 Kernel v4.4.0-119
Mate Desktop
AMD64 (Athlon)

Please contact if more info needed or testing/trouble shooting desired.

**Comment by salahmak** [comment]
I have the same bug on Debian Buster 10.7, and with xfce desktop. Hope it gets fixed soon

**Comment by urgemerge** [comment]
Same here on Ubuntu 20.04 with Intel HD Graphics 530 and the i965-va-driver package installed.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @linuxdevman is this still an issue for u?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @linuxdevman is this still an issue for u?
