### ISSUE TITLE
Videos in autoplay does not load

### ISSUE THREAD

**Issue by voiceofvraja** [FreeTubeApp/FreeTube#881]
**Behavior of the program**
No videos in autoplay

**Expected behavior**
It should show next videos which are upcoming but it just shows a void section under autoplay

**To Reproduce**
Play any video and see the right side under autoplay, it shows void

**Screenshots**
![image](https://user-images.githubusercontent.com/50140643/102461397-51ed0480-406e-11eb-8248-23c67b14036c.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: 0.9.3 from website
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment]
This was due to a bug in a module. We created a fallback system that makes this empty, but allows you to watch the video.

This is fixed in the newest nightly builds over in the Github actions tab.

**Comment by voiceofvraja** [comment]
> This was due to a bug in a module. We created a fallback system that makes this empty, but allows you to watch the video.
> 
> This is fixed in the newest nightly builds over in the Github actions tab.

So I have to use the nightly build?

**Comment by voiceofvraja** [comment]
How do I get that then? I am no geek or someone familliar with using actions @GilgusMaximus

**Comment by GilgusMaximus** [comment]
No problem. We are open for everyone and happy to help anyone. 
Yes, you can download it via the Actions tab of the repository. Or download the new release 0.10.0 which was released yesterday :)
