### ISSUE TITLE
Allow Controling the volume with the scroll wheel on the entire video window

### ISSUE THREAD

**Issue by shivasagarrao** [FreeTubeApp/FreeTube#882]
Add a feature to Control the volume level with the mouse wheel when hovering the video player with the mouse cursor.
This feature is not natively available in YouTube but I use [Enhancer extension](https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle) to get this feature.

**Comment by PrestonN** [comment]
This is already implemented and in the latest release.

**Comment by shivasagarrao** [comment]
I'm currently using v0.9.3, am unable to control volume with mouse. Is there any setting that I need to change?

**Comment by PrestonN** [comment]
You need to hover over the volume slider. It currently doesn't work if you hover over the video itself.

**Comment by shivasagarrao** [comment]
My feature request was controlling the volume when you hover over the video. May I open another issue?

**Comment by PrestonN** [comment]
That's fair. I'll just reopen this issue.

**Comment by Albinexotech** [comment]
Hey @PrestonN , I was wondering if I would be able to take on this issue?

**Comment by GilgusMaximus** [comment]
Sure, if you need some help feel free to ask here or once you opened a PR in the PR :)
