### ISSUE TITLE
Downloading and viewing profile pics and thumbnails

### ISSUE THREAD

**Issue by tiwarys** [FreeTubeApp/FreeTube#884]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Add an option to view the thumbnail and profile picture of a channel. Also allow downloading thumbnail and profile picture.

**Describe the solution you'd like to see implemented**
Downloading and viewing profile pics and thumbnails is needed.

**Describe alternatives you've considered**
Currently I use youtube-dl to download a video thumbnail.

**Comment by PrestonN** [comment]
As in adding them to the list of download links? You can currently right click on any image in the app to download it.

**Comment by shivasagarrao** [comment]
Actually I don't know that I could right click on any thumbnail or profile to Save image. Thanks for it. 
What about viewing a profile picture/ thumbnail large so that information inside a thumbnail can be read properly?

**Comment by GilgusMaximus** [comment]
You can always view channel pictures in a larger form on the channel page.
In regards to the thumbnails, a setting that changes the size of one video element could be implemented. Then the thumbnails become larger as well.

**Comment by shivasagarrao** [comment]
![Screenshot from 2020-12-19 18-45-33](https://user-images.githubusercontent.com/46630255/102690308-84436100-422a-11eb-80e1-ea8621ab6ba4.png)

> You can always view channel pictures in a larger form on the channel page.

I can't find an option to only view not download the image/thumbnail. Add an option to only view image.

![Freetube 2](https://user-images.githubusercontent.com/46630255/102690362-e43a0780-422a-11eb-9fa6-691f52aea665.png)

You can add one additional option to view thumbnail when we click three dots.

**Comment by GilgusMaximus** [comment]
> I can't find an option to only view not download the image/thumbnail. Add an option to only view image.

I meant that the image is larger in this view than on the Watch page.
But adding the possibility to enlarge the profile picture on the channel is probably a viable idea.

> You can add one additional option to view thumbnail when we click three dots.

I'm not really seeing any benefit to this when we add the option to enlarge the video item in the view as I suggested before. You can simply download the image if you really want to zoom in further

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Like mentioned before downloading is already available and i dont see a reason why we have to also have an image viewer. Use whats provided by the OS for that
