### ISSUE TITLE
Add video to current playlist button

### ISSUE THREAD

**Issue by imezzat** [FreeTubeApp/FreeTube#886]
**Important note**
Please check other open and closed issues for a similar feature request before proposing a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Is your feature request related to a usage problem (not a bug)? Please describe.**
Please describe clear and concise of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like to see implemented**
Please give a clear and concise description of what you want to happen.

**Describe alternatives you've considered**
Are there other ways to solve the problem? Please give a clear and concise description of any alternative solutions or features you might have considered.

**Screenshots**
Sometimes people have screenshots from mock-ups or other projects. Add them here.

**Additional context**
Add any other context about the feature request here.

**Comment by imezzat** [comment]
On searching for videos,sometimes I'd like to watch more than video without having to go back after watching each video to open the other one.Please consider adding an add to queue button.

**Comment by GilgusMaximus** [comment]
This is already described in multiple other issues. E.g. in the pinned issue #539 
Therefore closing due to being a duplicate.
