### ISSUE TITLE
Search option in watch history

### ISSUE THREAD

**Issue by GilgusMaximus** [FreeTubeApp/FreeTube#888]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Searching for one video in the watch history is quite tedious, especially if it was watched a while back and a lot of other videos filled up the history since then. A search comes in handy when you watched a video that is not easily searchable via normal search. E.g. when you only know the vague theme of the video and the search is filled with a lot of videos about the topic

**Describe the solution you'd like to see implemented**
A search field which allows to search for keywords in titles as well as the channel name of the video. The extend to which data fields can be searched depends on the amount of data that is stored in the history.db file.

**Comment by constraintAutomaton** [comment]
I'm interested in tackling it

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Go for it!
