### ISSUE TITLE
Make right click functional after opening any video

### ISSUE THREAD

**Issue by tiwarys** [FreeTubeApp/FreeTube#889]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Currently, if I click right click after opening any video nothing is happening. You could implement something like loop, screenshot, copy video URL etc similar to YouTube.

**Describe the solution you'd like to see implemented**
Make right click functional.

**Screenshots**

![Screenshot from 2020-12-19 18-58-50](https://user-images.githubusercontent.com/46630255/102690594-7e4e7f80-422c-11eb-98ee-a82ebfebdd2f.png)

**Comment by GilgusMaximus** [comment]
Hi, so for the moment this is probably not gonna happen. As seen in the pull request #656 we already have some struggles adding a simple loop button to the video player. VideoJS uses a plugin system to add content to it and we are not really proficient in writing plugins for it.

But if someone know how to program plugins for VideoJS, we are open for any help on #656 as well as adding such an overlay

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as right click is functional. Brings up the stats for nerds button. All the other things can be done within or just outside the player. No need to duplicate the behavior
