### ISSUE TITLE
Logo/Icon Proposals

### ISSUE THREAD

**Issue by jbeguna04** [FreeTubeApp/FreeTube#89]
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by PrestonN** [comment]
Hey there.  I would actually really like to have a new icon for the app.  To be honest, the current icon was something I did pretty quickly before I released the app.  It seems to be fine enough, but I believe it would be better.  Looking forward to seeing the designs you come up with.  Let me know if you need anything from me.

**Comment by jbeguna04** [comment]
Thank you for your response. Allow me to post the designs here later

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/39960049-f2c2231c-564d-11e8-9488-753030e1ad13.png)
Sorry for the wait, Here are my proposal. Im open to your suggestions
Thank You!

**Comment by MegaArthur** [comment]
### That's some amazing work

@PrestonN That's just my suggestion, but wouldn't it be prettier if it was red-blue instead of blue-red? 

You are the dev, so it is your decision, but I've tried to make a preview on my phone and for me it seems prettier.

**Comment by jbeguna04** [comment]
Thanks. Where will i put the the red and blue colors. 
I will try to have some changes on the color for you

**Comment by jbeguna04** [comment]
I would like to ask your thoughts dear PO

**Comment by PrestonN** [comment]
This is AWESOME! I love it.  I'd really like to use this moving forward.  As @MegaArthur mentioned, I'd like to see the red and blue swapped just to have as a comparison.  While I like the blue in the logo, it feels slightly out of place from the rest of the app since FreeTube doesn't use much blue in it's current design.  Having it as a secondary color might be better in this case.

Either way, amazing work, and thank you very much for making this. :)

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/40005380-5e7ea7b0-57ca-11e8-8b9e-8bdc1ea8becf.png)
Thank you for your response.

**Comment by jbeguna04** [comment]
If it is alright with you, can i make any pull request for this design so that you can use it, the files are ready to use
Thank you 
Best regards,
Jibbie eguna

**Comment by jbeguna04** [comment]
@PrestonN , Greetings, I made your suggestions. Hope that you like all of those.

**Comment by jbeguna04** [comment]
Thank you again. I make a pull request of the logos and the logotypes as well. Im glad to help you.

**Comment by jbeguna04** [comment]
[freetube.zip](https://github.com/FreeTubeApp/FreeTube/files/2012053/freetube.zip)
Greeting!
Here the files that all you need sir, I put it on a zip file.

**Comment by PrestonN** [comment]
Thanks again for everything. The logos have been merged into the project.  I will be implementing the designs with the application in the near future.  I will go ahead and close the issue now.
