### ISSUE TITLE
[Linux] v0.10.0 - mouse back from any (s) fit to screen video breaks scrolling requires restart

### ISSUE THREAD

**Issue by arrowgent** [FreeTubeApp/FreeTube#890]
pretty straight forward
while watching any video in (S) fit to screen mode and clicking back (mouse button 5)
then all scrolling in the main window is destroyed

arrow keys/pgup&pgdown/mousewheel:  nothing works

```
Features
You can now expand the video player to fit the entire application window. You can find the toggle within the video player. You can also use the s key to toggle it
```

requires closing freetube and restarting.

**Comment by arrowgent** [comment]
https://github.com/FreeTubeApp/FreeTube/commit/f7c1392059fae30c1b1ac3c3ae61d3d8a0b63ee9

https://github.com/FreeTubeApp/FreeTube/commit/ad8ed9fdb0fddbddf7de708ded3684c7a7e76982

**Comment by PrestonN** [comment]
Thanks for the report. I've pushed a fix up to the development branch. Will be fixed in the next release / latest nightly builds.

**Comment by arrowgent** [comment]
awesome thank you for figuring it out.
