### ISSUE TITLE
What is dash format, legacy format?

### ISSUE THREAD

**Issue by shivasagarrao** [FreeTubeApp/FreeTube#893]
**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify: Formats

**Question**
What is dash format and legacy format? What are the differences between them? Explain in simple manner.

**Comment by kubo6472** [comment]
DASH is an adaptive bit rate streaming, that works by breaking content into a sequence of small segments available in a variety of different bit rates. That means depending on your network speed, the system will swap the individual segments, so your experience is as smooth and as buffer-free as possible. [Source](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP). Legacy lacks this feature. YouTube also uses HLS, which is something like an ancestor of DASH, they are very similar.

**Comment by shivasagarrao** [comment]
If I currently use dash format in FreeTube then all resolutions are available. Whereas if I use Legacy format then only 360p and 720p resolutions are available. What does this mean?

**Comment by kubo6472** [comment]
Use DASH :)


The original Legacy encoded files are in that resolutions only. Youtube 
encodes the additional resolutions in DASH only. Somewhere you may see 
the 720p interpreted as HQ and 360p as MQ.

**Comment by PrestonN** [comment]
DASH is the standard method of delivering videos. Videos will have separate streams for video and audio as well as separate video streams for each quality. This process allows a video player to easily change qualities based on a user's network connection without disrupting audio. This is the same standard that YouTube uses. The streams provided by YouTube are primarily used for this method and are organized as such. These means that most quality options are only available via DASH.

The legacy formats is more of an in-house term that we use for FreeTube. These are streams that YouTube provide that are more similar to what you'd expect a local file to be like. It's a basic stream of an MP4 file and as such has the video and audio combined into one file. These formats are more suited for downloading however as you've seen, the quality options that are available are much fewer than what you see with DASH. These formats are maxed out at 720p. These formats are also typically easier to stream and can possibly save some bandwidth on your end if you're having issues with video playback.

FreeTube makes it easy to choose which format you'd like to use. If you're unsure on which one you should use, then you should probably stay with the default DASH option. If DASH gives you problems, switching to legacy may help.
