### ISSUE TITLE
Make freetube be recognized as mediaplayer by the OS

### ISSUE THREAD

**Issue by RedAscendant** [FreeTubeApp/FreeTube#894]
For some functionality purposes it will be nice to have the operating system recognize freetube vids playing as media.
This keeps the PC from shutting down because of idle mode and allow play/pause/volume usage in other areas or apps like KDE connect.

**Comment by Etrit1** [comment]
It looks like it already is on Windows 10.

I just paused a video using the media pause keyboard shortcut while FreeTube is in the background.

It worked! Wowo!!

As for the PC shutting down, hrm, idk about that one.

**Comment by GilgusMaximus** [comment]
Hi, so this seems to be an Linux issue again, similar to another issue, which I really cannot find at the moment for some reason.
There it worked for @PrestonN on his Linux but for some other people with a different distribution it did not work.

@Etrit1 on Windows the media buttons usually work well.

I'm not so sure about the system recognizing it as media player. This could be related to the missing recognition of the media buttons.

**Comment by PrestonN** [comment]
I'm going to assume you downloaded the Flatpak release as that was the build where the media player was being blocked. This should be the case any more and it should be working now on the Flatpak build.
