### ISSUE TITLE
[Feature Request] Add Hong Kong as one of the "Region of Trending"

### ISSUE THREAD

**Issue by IAmNotAJerk** [FreeTubeApp/FreeTube#895]
Not sure why it is not included in the list. Youtube by default had set Hong Kong as a separate region (a completely different dialect from China and Taiwan). Please consider.

**Comment by GilgusMaximus** [comment]
As I mentioned in the Matrix channel, when someone requested Taiwan, we used [this](https://github.com/stefangabos/world_countries) project as basis for out region of trending selection. So they chose one way of organizing the different countries and this of course does not correlate to the list YouTube used.

So adding this should be simple. We are open for PR's. Just refer to my addition of Taiwan in #808

**Comment by saideepesh000** [comment]
@GilgusMaximus, adding the id is random and unique?

**Comment by GilgusMaximus** [comment]
Yes, the id is unique, although not random (Although we are not using anywhere except for indexing, so as long as it would stay unique it would be good). It can be found in the ISO Standard 3166 - numeric, which you can find on [here](https://en.wikipedia.org/wiki/ISO_3166-1_numeric). Hong Kong has the id 344

**Comment by PrestonN** [comment]
Added with #925
