### ISSUE TITLE
Default profile changes back to All profile after closing app

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#898]
What determines which profile is loaded on startup? I have a profile set as default, but despite this, the "All Channels" will sometimes load instead.

**Comment by GilgusMaximus** [comment]
Your default profile usually. But just as you said it, it seems that this does not always stay between sessions and reverts to the All profile for some reason.

I'm gonna change this into a bug issue in order to fix this

**Comment by saideepesh000** [comment]
@PrestonN , I think the [updateActiveProfile ](https://github.com/FreeTubeApp/FreeTube/blob/9e73c5be8e81e0c8c82a84481a39be091995ce61/src/renderer/store/modules/profile.js#L138)is not commiting to database, Am I right, can I try this

**Comment by saideepesh000** [comment]
@PrestonN, And also we need to be able to differentiate the UI of the default Profile from the rest of the profiles.

**Comment by saideepesh000** [comment]
@PrestonN, just realized we need to tweak the profiledb a little bit, currently, it's only storing the profile data, activeprofile data should be separately stored, so how should I approach it ?.

**Comment by PrestonN** [comment]
Apologies for taking so long in this. The `updateActiveProfile` function isn't meant to save data permanently and it's only used for the active session. The part that saves the default profile is in [settings.js](https://github.com/FreeTubeApp/FreeTube/blob/development/src/renderer/store/modules/settings.js#L44).

I do agree that both the default profile as well as the "All Channels" profile needs to have some differentiation in the UI. That'd be a separate discussion from this issue however.

For fixing this, my only guess is that there's a runtime issue where the default profile is being set before FreeTube loads all profiles that have been created. We need to make sure that the profiles are loaded before it sets the default profile.

You're still welcome to tackle this if you'd like, feel free to contact me if you need any help.
