### ISSUE TITLE
How to install this beta version on Ubuntu Linux?

### ISSUE THREAD

**Issue by raghavgururajan** [FreeTubeApp/FreeTube#9]
I could not able to find any package, app image or binaries.

**Comment by aproposnix** [comment]
You have to go to the releases page: https://github.com/FreeTubeApp/FreeTube/releases

For AMD64 download this: https://github.com/FreeTubeApp/FreeTube/releases/download/v0.1.0-beta/FreeTube_0.1.0_amd64.deb

**Comment by raghavgururajan** [comment]
@aproposnix Thank you very much. By the way, is there a ppa repository where the app can update automatically on my system?

**Comment by aproposnix** [comment]
@raghavgururajan As far as I am aware there's no PPA.

**Comment by PrestonN** [comment]
Hey there!  As of now there isn't a PPA for FreeTube.  This is something I'd like to explore in the future though.  It looks like your question was answered so I'm going to close this issue.  If you ever have more questions then feel free to open up a new issue.

**Comment by dimqua** [comment]
@PrestonN, I just want to let you know that [the app is now available on Chocolatey](https://chocolatey.org/packages/freetube) (a Windows package manager).

**Comment by PrestonN** [comment]
Hey @dimqua is that something that you have control of or is it something that you've found? I'm working on a solution for auto updates and I'd like to have control over whatever the solution is.

**Comment by dimqua** [comment]
Yes, I'll upload the next version automatically after six hours (or less) after it will be released on GitHub.
