### ISSUE TITLE
Please provide an AppImage for download

### ISSUE THREAD

**Issue by probonopd** [FreeTubeApp/FreeTube#90]
Please provide an [AppImage](http://appimage.org/) for download on GitHub Releases.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

electron-builder has native support to produce AppImages.

**Comment by PrestonN** [comment]
Up to this point, I have been using [Electron Forge](https://github.com/electron-userland/electron-forge) to build and package up FreeTube.  Electron Forge did not have support for AppImage as far as I'm aware.  I've seen AppImage get requested a lot though so I took a look at switching over to Electron Builder.  My tests last night seems to have worked well, including the AppImage version, so I think it is fine to use this moving forward.  Expect to see an AppImage in the next release. :)

**Comment by probonopd** [comment]
If someone can be so kind to ping me once the AppImage download is available, I can include it in the AppImageHub central directory of available AppImages.

**Comment by probonopd** [comment]
https://github.com/FreeTubeApp/FreeTube/releases/download/v0.3.1-beta/FreeTube-0.3.1-x86_64.AppImage is now available. Thank you very much.

**Comment by probonopd** [comment]
But getting `AppRun: line 50: /run/firejail/appimage/.appimage-7162/app/freetube: No such file or directory`. Please see https://github.com/AppImage/appimage.github.io/pull/629.
