### ISSUE TITLE
ESCape key "fullwindow" program focus

### ISSUE THREAD

**Issue by jawa64** [FreeTubeApp/FreeTube#900]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
not a bug per say more of an oversight. Thanks for taking the time to even read this as minor as it is.
**Describe the solution you'd like to see implemented**
escape key seems to only exit from "fullwindow" mode when the player itself has focus and not when the program just has focus.
when you click escape with the window focused in "fullwindow" mode <ie not fullscreen> 

**Describe alternatives you've considered**
**Screenshots**
**Additional context**
it should go back to regular mode but it currently doesn't you have to click the actual player to be able to do that.

**Comment by GilgusMaximus** [comment]
Hi, so thanks for sharing this. It seems like this is mentioned in #766 
Therefore I am closing this issue in favor of the other
