### ISSUE TITLE
Subs Import dead

### ISSUE THREAD

**Issue by voiceofvraja** [FreeTubeApp/FreeTube#906]
**Behavior of the program**
Trying to import subscriptions and history using the db newpipe file and it just does not do anything

**To Reproduce**
Please add all steps to reproduce the behavior:
Settings>Import Subs or History using NewPipe db

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Win10
 - FreeTube version: v0.10.0 Beta
 - Installation Method (If applicable): Portable exe
 - Primary API Used: LocalAPI

**Additional context**

**Comment by GilgusMaximus** [comment]
Closing this. The import button for .db states that it is for FreeTube, not NewPipe. Please take a look at the solution over at #534 to export your subscriptions from Newpipe in the correct format.
