### ISSUE TITLE
User having the ability to modify the side bar (Subscriptions) and a new tab for the same

### ISSUE THREAD

**Issue by voiceofvraja** [FreeTubeApp/FreeTube#908]
**Describe the solution you'd like to see implemented**
Ability to remove the side bar of subscriptions channel icons. It would be good if the user can choose to see those or not because we already have the single area dedicated to subscriptions. So we can just add another tab just like NewPipe for instance
 which says "Whats New" and in there user can see what they can currently see in their subscriptions tab and in the place of subscriptions they can actually see all their subs ready to be managed lilke bulk unsubscribe.

![image](https://user-images.githubusercontent.com/50140643/103444067-29c6ed80-4c8b-11eb-8549-426cd37d4647.png)

**Comment by PrestonN** [comment]
This would be fairly simple to add to the "Distraction Free Settings" of the app. I'll label this as a good first issue in case someone would like to make a PR for it.

I've also considered adding more links to the subscriptions manager page around the app as it seems that some users are having difficulty finding it.

**Comment by voiceofvraja** [comment]
Wow, thanks a lot @PrestonN really!

**Comment by PrestonN** [comment]
Added as of #918
