### ISSUE TITLE
Weird alignment of video information sections when the setting "Hide Recommended Videos" is enabled.

### ISSUE THREAD

**Issue by Aiz0** [FreeTubeApp/FreeTube#909]
**Behavior of the program**
When the "Hide Recommended Videos" setting in "Distraction Free settings" is enabled there is a lot of empty space below the video to the right where the recommended videos used to be. Despite this empty space being there, the video info section, video description section, and comments section are offset to the left as if the recommended videos section is still there. This make the interface look a little awkward in my opinion.

**Expected behavior**
When "Hide Recommended Videos is enabled" the video info section, video description section, and comments section should be aligned with the video and be at least as wide as the video. This would remove a lot of empty space and make it look a bit nicer.

**To Reproduce**
1. Go to settings.
2. Scroll down to "Distraction Free Settings".
3. Enable "Hide Recommended Videos".
4. Click on a video. It should be in "theatre mode".
5. Scroll down to the comments section
6. The video information sections are aligned as if the recommended videos section was still there, even though it's not.

**Screenshots**
Here is a screenshot of what it currently looks like. When the recommended videos section isn't there the interface looks awkward
![screenshot of video](https://user-images.githubusercontent.com/66974576/103446623-a51fa380-4c79-11eb-9089-4af4fea3cb28.png)

**Environment Information:**
 - OS: Arch Linux
 - OS Version: Kernel 5.10.3-arch1-1
 - FreeTube version: v0.10.0 Beta
 - Primary API Used: Local API

**Additional context**
When viewing a live stream in "theatre" mode the live chat takes up the place where the recommended videos section usually is. Because of that it should not be necessary for any changes to the interface when viewing a live stream with live chat.

**Comment by cloudrac3r** [comment]
Also working on a patch for this.
