### ISSUE TITLE
Live chat can't be displayed next to video when the setting "Hide Recommended Videos" is enabled.

### ISSUE THREAD

**Issue by Aiz0** [FreeTubeApp/FreeTube#910]
**Behavior of the program**
When the setting "Hide Recommended Videos" is enabled you can't disable "theatre mode". This becomes a problem when you want to view a live stream with live chat. When "theatre mode" is off, the livechat is displayed right next to the video so that you can view the video and the live chat at the same time. When "theatre mode" is on, the top of live chat is barely visible because it's pushed down next to the video information section. In "theatre mode" you can't view the video and the live chat at the same time on a 1080p 16:9 screen. When the setting "Hide Recommended Videos" is enabled it forces "theatre mode" to always be on. This means you can't view a live stream with the live chat next to it.

**Expected behavior**
When viewing a live stream I also want to view the live chat. This means the button to toggle "theatre mode" should be available when viewing a live stream with live chat even when the setting "Hide Recommended Videos" is enabled.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to settings.
2. Scroll down to "Distraction Free Settings".
3. Enable "Hide Recommended Videos".
4. Click on a live stream with live chat. A 24/7 lofi stream for example.
5. You should see that the button to toggle "theatre mode" is not available.

**Screenshots**
Here is what it currently looks like.
![screenshot](https://user-images.githubusercontent.com/66974576/103446430-77395f80-4c77-11eb-97b8-f15082bd8b86.png)

**Environment Information:**
 - OS: Arch Linux
 - OS Version: Kernel 5.10.3-arch1-1
 - FreeTube version: v0.10.0 Beta
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment]
Thanks for sharing these layout bugs. They are usually hard to spot for us when we ourselves do not use these features. The way the layout works definitely requires an update to fix these issues

**Comment by cloudrac3r** [comment]
Working on a patch for this.

**Comment by nhathoang24** [comment]
I have the same question!
