### ISSUE TITLE
Flickering when entering full screen

### ISSUE THREAD

**Issue by palikacska** [FreeTubeApp/FreeTube#912]
Since FreeTube uses Electron, it's also affected by this bug on Linux.
https://bugs.chromium.org/p/chromium/issues/detail?id=1140606

Could reproduce on **Debian Stretch**, **Debian Buster** and **Ubuntu Bionic**.

You would probably want to fall back to an older version of Electron which isn't broken.

Meanwhile, billionaire Google is spending its billions of dollars on working hard on fixing this problem. No, just kidding. The bug is still around for more than 2 months and survived at least 3 major versions and as you can see in the bug tracker, no damn is given about it.

**Comment by Svallinn** [comment]
Hey. That issue seems to have been solved a while ago. Is this still relevant?
If I don't get a confirmation about this until the next 7 days, I'll be closing this issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
respond to the previous comment please
