### ISSUE TITLE
Upcoming live video trying to load

### ISSUE THREAD

**Issue by Mech0z** [FreeTubeApp/FreeTube#921]
**Behavior of the program**
This video is scheduled to go live tomorrow https://youtu.be/sxTjfX9v8M0 but its showing in my feed and if I click it I get 
Cannot read "playerErrorMessageRedererer" of undefined

**Expected behavior**
If the info is available I would maybe just give an error when clicking it saying it wont go live for another X timeunit and maybe even have a countdown on the subscriptions page icon

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to https://youtu.be/sxTjfX9v8M0 or any other live video event scheduled in the future on a page your subscribing to
2. See error

**Screenshots**
[![AMD-page-error.png](https://i.postimg.cc/MGbB1WP7/AMD-page-error.png)](https://postimg.cc/7Chbkyyh)

**Environment Information (please complete the following information):**
 - OS: Win 10
 - FreeTube version: v0.1.0 beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Comment by PrestonN** [comment]
This is already fixed in the dev branch and will be included in the next release.

**Comment by Mech0z** [comment]
Well that was a quick fix :) but did try to search for an existing issue beforehand, so probably just missed that, but thanks!
