### ISSUE TITLE
Don't darken video details in the history tab, as it makes it unreadable

### ISSUE THREAD

**Issue by Lurux** [FreeTubeApp/FreeTube#926]
- [x]  I checked and didn't find any open issue for this problem

**Is your feature request related to a usage problem ? Please describe.**
The thumbnails and titles of watched videos are darkened to tell them appart from new content in video listings, which seems reasonable. However, this happens in all sections of the app, including the history, which makes it unreadable.

**Describe the solution you'd like to see implemented**
Don't darken the watched videos in the history tab.

**Describe alternatives you've considered**
I've seen in another issue that the current opacity for watched videos is 0.3. I think this could be bumped to 0.5, as the current value seems a bit extreme to me.

**Screenshots**
This is only a small portion of the page, but on a large screen it gets really annoying to distinguish without hovering them...

![history](https://user-images.githubusercontent.com/35870988/104370011-8c877700-551e-11eb-99ba-593467a2365e.png)

**Additional context**
I often rely on history to find music I want to listen to, and some videos are very hard to distinguish without hovering them currently.

I also find it annoying that watched videos are "hidden" that much, even outside of the history.

**Comment by PrestonN** [comment]
I've been thinking about doing this myself actually. It's a fairly easy change to do so I went ahead and made the change. Expect to see it in the next release.

**Comment by Lurux** [comment]
Great, thanks ! :smile:
