### ISSUE TITLE
Error in translation file

### ISSUE THREAD

**Issue by LexHimself** [FreeTubeApp/FreeTube#93]
`We need to package your application before we can make it
✔ Preparing to Package Application for arch: x64
⠴ Compiling ApplicationFailed to compile file: /tmp/electron-packager/linux-x64/FreeTube-linux-x64/resources/app/src/js/translations/en.js
/tmp/electron-packager/linux-x64/FreeTube-linux-x64/resources/app/src/js/translations/en.js: Unexpected token, expected ; (2:7)
`

Best to address this early :)

Development branch.

**Comment by LexHimself** [comment]
Hi,

So the problem lies on line 2, the 7th character, which is `:`, and with all of them following. 

Perhaps this might offer a solution: https://github.com/electron/i18n
It is however, a little over my head.

**Comment by PrestonN** [comment]
The problem actually ended up being much simpler than expected.  The files were JavaScript files and needed to be converted to JSON.  A quick file name change solves this and builds run as normal.  You can see this change in the `electron-builder` branch or in the `development` branch when I merge the two later today.
