### ISSUE TITLE
White screeen after clicking video's hashtag 

### ISSUE THREAD

**Issue by abulenok** [FreeTubeApp/FreeTube#932]
**Behavior of the program**
White screen after clicking on video's hashtag, without option of returning back

**To Reproduce**
1. Open any video with a hashtag in description (for example: https://youtu.be/YJnlOofcf04)
2. Click on hashtag

![obraz](https://user-images.githubusercontent.com/63914185/104808115-5844dc80-57e4-11eb-86a7-bcd86a0d25d3.png)

https://user-images.githubusercontent.com/63914185/104807893-9e993c00-57e2-11eb-9960-7751d9cfcb4c.mp4

Environment Information:
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: v0.11.1
 - Installation Method (If applicable): .exe
 - Primary API Used: Invidious API

**Additional context**
Our team (@Vovany4, @kgr0) has experienced this bug.

**Comment by GilgusMaximus** [comment]
Okay, so the problem seems to be that the link parser sees this as a link and then makes it clickable. So a distinction will be required here
