### ISSUE TITLE
Likes on comment's replies are not visible

### ISSUE THREAD

**Issue by kgr0** [FreeTubeApp/FreeTube#933]
**Behavior of the program**
Likes on comment's replies are not visible

**Expected behavior**
Likes on comment's replies are shown correctly

**To Reproduce**
1. Go to any video
2. Click on "Click to View Comments"
3. Click on "View replies"
4. See that number of likes on comment's replies is not visible

**Screenshots**
![image](https://user-images.githubusercontent.com/50838031/104808321-19b41f80-57ee-11eb-95e6-fea0b98f422a.png)

**Environment Information:**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: v0.11.1 Beta
 - Installation Method:  .exe
 - Primary API Used: Local API

**Additional context**
When using Individuos API this is working correctly
Our team (@Vovany4, @abulenok) has experienced this bug.

**Comment by GilgusMaximus** [comment]
Yeah, this needs some checks over at the comment scraper

It's mostly about finding the correct path within the JSON object that we are working on. If someone wants to take over this, there are some previous PR's that added new fields

**Comment by PrestonN** [comment]
This should be fixed in the latest release.
