### ISSUE TITLE
Import history after removing

### ISSUE THREAD

**Issue by Vovany4** [FreeTubeApp/FreeTube#934]
**Behavior of the program**
Import history after removing

**Expected behavior**
History is empty

**To Reproduce**
1. Watch several videos
2. Go to 'Settings'
3. Click on 'Remove Watch History'
4. Click on 'Yes'  for confirming
5. Click on 'Export History'
6. Save file at computer
7. Click on 'Import History'
8. Import saved file from export
9. Check history

**Environment Information (please complete the following information):**
- OS: Windows
- OS Version: Windows 10
- FreeTube version: v0.11.1 Beta
- Installation Method: .exe
- Primary API Used: Local API, Invidious API

https://user-images.githubusercontent.com/61869173/104809233-1029b800-57ec-11eb-888a-ac31a2198049.mp4

Additional context
Our team (@kgr0, @abulenok) has experienced this bug.

**Comment by GilgusMaximus** [comment]
Thanks for finding this edge case. Could you try and delete the history, then close the program and then import it again. I suspect that the database does not commit right after you deleted the history but when you close FT

**Comment by abulenok** [comment]
It seems, this is the case. If the history was exported after remowing Watch History and before closing the app, then it is possible to import removed Watch History back. 
Exported history file looks like this:
![obraz](https://user-images.githubusercontent.com/63914185/104898932-83613480-597a-11eb-90c1-364460886229.png)

If the history was exported after remowing Watch History and after closing and opening again the app, then the Exported history file is empty

**Comment by GilgusMaximus** [comment]
This should be easy to fix, although probably not that high in priority.
When I'm coming back from my hiatus, then I'll do something about that if no one else does until then :)
