### ISSUE TITLE
A number of views on Most Popular doesn't shown correctly

### ISSUE THREAD

**Issue by kgr0** [FreeTubeApp/FreeTube#936]
**Behavior of the program**
A number of views on Most Popular doesn't shown correctly

**Expected behavior**
A correct number of views on Most Popular videos

**To Reproduce**
1. Go to 'Most Popular' section
2. See that numbers of views are too small (0, 1, 2, etc)
3. Click on video
4. See that number of views is much more than previously seen. 

**Screenshots**
![image](https://user-images.githubusercontent.com/50838031/104809113-93024100-57f3-11eb-9457-6d3a8597aca0.png)
![image](https://user-images.githubusercontent.com/50838031/104809158-db216380-57f3-11eb-956b-62a09c046bf3.png)

**Environment Information (please complete the following information):**
 - OS:  Windows
 - OS Version: Windows 10
 - FreeTube version: v0.11.1 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API, Invidious API

**Additional context**
Our team (@Vovany4, @abulenok) has experienced this bug.

**Comment by GilgusMaximus** [comment]
So the most popular section actually comes from Invidious, not from the local API. So there is nothing we can do on our end here
