### ISSUE TITLE
Import subscriptions after removing

### ISSUE THREAD

**Issue by Vovany4** [FreeTubeApp/FreeTube#937]
**Behavior of the program**
Import subscriptions after removing

**Expected behavior**
 List of subscriptions is empty

**To Reproduce**
1. Subscribe several channels
2. Go to 'Settings'
3. Click on 'Remove All Subscribtions/ Profiles'
4. Select 'Yes' for confirming
5. Click on 'Export Subscriptions'
6. Select 'Export FreeTube (.db)'
7. Save file on computer
8. Click on 'Import Subscriptions'
9. Select 'Import FreeTube (.db)'
10. Import saved file from export
11. Check list of subscriptions

https://user-images.githubusercontent.com/61869173/104809844-95af6700-57f0-11eb-9d62-cb731630919a.mp4

**Environment Information :**
- OS: Windows
- OS Version: Windows 10
- FreeTube version: v0.11.1 Beta
- Installation Method: .exe
- Primary API Used: Local API, Invidious API

**Additional context**
Our team (@kgr0, @abulenok) has experienced this bug.

**Comment by GilgusMaximus** [comment]
Probably same problem as on #934

**Comment by Svallinn** [comment]
The commit above solves this issue. Closing...
