### ISSUE TITLE
UI Search box

### ISSUE THREAD

**Issue by kgr0** [FreeTubeApp/FreeTube#938]
**Topic**
UI

**Question**
We're not sure if it is correct behavior of search box. A part of text is overlapped by arrow icon.
![image](https://user-images.githubusercontent.com/50838031/104810151-8d105e00-57fb-11eb-8fb7-6a7061203b5d.png)

While hovering on arrow:
![image](https://user-images.githubusercontent.com/50838031/104810158-9699c600-57fb-11eb-8a83-4957e2199e3a.png)

_Maybe the length of textbox should be shorter?_

****

Environment Information :
- OS: Windows
- OS Version: Windows 10
- FreeTube version: v0.11.1 Beta

@Vovany4, @abulenok

**Comment by PikachuEXE** [comment]
Seems fixed already in #1392
https://github.com/FreeTubeApp/FreeTube/blame/development/src/renderer/components/ft-input/ft-input.css#L105-L112
![image](https://user-images.githubusercontent.com/1018543/133014739-c0f50408-fd7f-4b38-bcf3-e50caf010241.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@kgr0 is this fixed for u?
