### ISSUE TITLE
Loading comments leads to random search page

### ISSUE THREAD

**Issue by Lurux** [FreeTubeApp/FreeTube#943]
- [x] I checked and didn't find any open issue for this problem

**Behavior of the program**
Since the last update, clicking the "load comments" button kicks me out of the current video and leads to a search page, with results that correspond to the "args" search term. I think I see what type of shenanigans happened there :smile:

**Expected behavior**
Load comments, don't kick the user out of the current video

**To Reproduce**
1. Go to any video
2. Click on load comments
3. Enjoy the search results :smile:

**Environment Information (please complete the following information):**
 - OS: Linux Mint 20.1 (Ubuntu 20.04)
 - FreeTube Version: 0.11.1, via Flatpak (Flathub)
 - Primary API: Local API

**Additional context**
The issue only appeared in the latest version, as far as I'm aware.

**Comment by GilgusMaximus** [comment]
Hi, could you provide me with a video where this happens?
For a few videos I tested, the problem does not occur

**Comment by PrestonN** [comment]
I can confirm that this is happening. For some reason it's only affecting the Flatpak builds for now. The other thing is that I'm having a difficult time understanding why this is happening.

I'll be looking into this more and hopefully get a fix out for it soon. It's possible that pushing another update for the Flatpak builds may fix it but I'm not too sure yet. It's very strange how it's only happening with Flatpak.

**Comment by RagglenLove** [comment]
> Hi, could you provide me with a video where this happens?
> For a few videos I tested, the problem does not occur

**Steps to reproduce:**

Choose a video to play.

![Screenshot_2021-01-18_05-29-51](https://user-images.githubusercontent.com/45503845/104856839-9f9bac00-594f-11eb-8749-4d9755279410.png)

Scroll down and click on "Click to View Comments".

![Screenshot_2021-01-18_05-31-00](https://user-images.githubusercontent.com/45503845/104856879-d1ad0e00-594f-11eb-88ac-d64f63f65419.png)
![Screenshot_2021-01-18_05-31-16](https://user-images.githubusercontent.com/45503845/104856890-e38eb100-594f-11eb-97d9-c45ccf4532b3.png)

However, clicking on "Click to View Comments" takes me here instead.

![Screenshot_2021-01-18_05-31-28](https://user-images.githubusercontent.com/45503845/104856901-f5705400-594f-11eb-9662-39538a4a9839.png)

**Comment by PrestonN** [comment]
The comments module has been rewritten specifically to fix this issue. I've tested the fix with Flatpak builds as well and was no longer able to replicate this problem with the new builds. I will be releasing v0.11.2 sometime tomorrow which will fix this issue.

**Comment by Lurux** [comment]
Thank you very much, awesome :smile:
