### ISSUE TITLE
Allow local comments pinning in comments section

### ISSUE THREAD

**Issue by shivasagarrao** [FreeTubeApp/FreeTube#945]
**Is your feature request related to a usage problem (not a bug)? Please describe.**

Sometimes we might see some useful comments in the comments section. If a video has many comments then it is difficult to scroll down and find our required comment.

**Describe the solution you'd like to see implemented**

I think it would be nice if you allow local comments pinning in comments section like local subscribe.

**Describe alternatives you've considered**

No alternatives.

**Screenshots**

Screenshot from YouTube website

![Pinned Comments](https://user-images.githubusercontent.com/46630255/104821840-b3b6af00-5864-11eb-9e1d-4bb55b0b13e1.png)

There is Pinned by The Hated One in the screenshot. In that place we can add something like Pinned by yourself or just Pinned Comments.

**Additional context**

It would be very easy to track useful comments in comments section of a video.

**Comment by GilgusMaximus** [comment]
Hi, so this was already suggested a while back. Therefore I'm closing this in favor of the original #783
