### ISSUE TITLE
Remember scroll position

### ISSUE THREAD

**Issue by Nutomic** [FreeTubeApp/FreeTube#946]
**To Reproduce**
1. go to a channel
2. scroll down
3. click on a video result
4. click the back button

Result, it scrolls all the way back to the top of the channel page. Although sometimes it goes back to the correct position, but that seems to happen randomly. Most of the time I end up at the top.

**Expected behavior**
Freetube should always scroll back to the last position on a page that was previously visited.

**Environment Information (please complete the following information):**
 - OS: [e.g. Windows, Mac, Ubuntu, Fedora, Arch, etc.] Manjaro
 - OS Version: [e.g. Windows 10, Ubuntu 20.04] latest
 - FreeTube version: [e.g. 0.9.0, Nightly build?] v0.10.0 Beta
 - Installation Method (If applicable): [e.g. Portable, .exe, .deb, .AppImage, FlatHub] AUR
 - Primary API Used: [Local API, Invidious API] local

**Additional context**

By the way, why does `freetube-bin --version` start Freetube, instead of printing the version and exiting?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2446
