### ISSUE TITLE
Screen tearing when Fullscreen in Freetube v 0.11.1 Lubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by githubaudit** [FreeTubeApp/FreeTube#947]
**Screen tears** when playing a video in **fullscreen** in Freetube however it doesn't show the tearing when I play youtube videos in fullscreen mode from browsers like Firefox and Chrome.

I'm using **Lubuntu 18.04.5 LTS**, **Intel graphics**. I even tried adding the configuration file " /etc/X11/xorg.conf.d/20-intel.conf
" but it didnot help. I have even diabled Smooth Scrolling but it doesn't help as well.

Please help fix the issue.

**Comment by GilgusMaximus** [comment]
Hi, could this be the same issue as for #912.
If so, I'd close this in favor of the other, to discuss it at one centralized place

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @githubaudit does this issue still occur?
