### ISSUE TITLE
app identifies itself as version v0.11.0 Beta in the "About" (installed is 0.11.1 )

### ISSUE THREAD

**Issue by alium** [FreeTubeApp/FreeTube#948]
I applied the recent update, but the app identifies itself as version v0.11.0 Beta in the "About" section and I get a notification on the starting page that I should update to v 0.11.1 Beta.

`Erstelle freetube...
==> Erstelle Paket: freetube 0.11.1-1 (So 17 Jan 2021 17:34:27 CET)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> v0.11.1-beta.tar.gz gefunden
  -> package-only-necessary.diff gefunden
  -> freetube.desktop gefunden
  -> freetube.sh gefunden
==> Überprüfe source Dateien mit sha256sums...
    v0.11.1-beta.tar.gz ... Durchgelaufen
    package-only-necessary.diff ... Übersprungen
    freetube.desktop ... Übersprungen
    freetube.sh ... Übersprungen
==> Entferne existierendes $srcdir/ Verzeichnis...
==> Entpacke Quellen...
  -> Entpacke v0.11.1-beta.tar.gz mit bsdtar
==> Beginne prepare()...
patching file /var/tmp/[snip]/freetube/src/FreeTube-0.11.1-beta/_scripts/build.js
==> Beginne build()...
[snip]
==> Betrete fakeroot Umgebung...
==> Beginne package()...
==> Säubere Installation...
  -> Entferne libtool Dateien...
  -> Bereinige ungewollte Dateien...
  -> Entferne statische Bibliotheken...
  -> Entferne unnötige Symbole aus Binär-Dateien und Bibliotheken...
  -> Komprimiere Man-Pages und Info-Seiten...
==> Prüfe auf Paketierungsprobleme...
==> WARNUNG: Paket enthält einen Verweis auf $srcdir
usr/lib/freetube/app.asar
==> Erstelle Paket "freetube"...
  -> Erstelle .PKGINFO Datei...
  -> Erstelle .BUILDINFO Datei...
  -> Erstelle .MTREE-Datei...
  -> Komprimiere Paket... 
==> Verlasse fakeroot Umgebung.
==> Beendete Erstellung: freetube 0.11.1-1 (So 17 Jan 2021 17:38:57 CET)
==> Räume auf...

Überprüfe Schlüsselring...
Integrität wird überprüft...
Paketdateien werden geladen...
Dateikonflikte werden überprüft...
Überprüfe verfügbaren Speicherplatz...
Reinstalliere freetube (0.11.1-1)...
Starte Post-Transaction-Hooks...
Arming ConditionNeedsUpdate...
Updating the desktop file MIME type cache...
Vorgang erfolgreich abgeschlossen.`

I think you forgot to change 0.11.0 to 0.11.1 in https://github.com/FreeTubeApp/FreeTube/blob/83cfb8b70ed812332518994251ed5bd004dffc2d/package.json

because it show 
  "version": "0.11.0"

**Comment by PrestonN** [comment]
This was a side effect of rushing to get v0.11.1 released. I forgot to make the appropriate change to update the version number and it looks like some builds show v0.11.0 even if it isn't.

Instead of properly fixing this, I will be releasing v0.11.2 very soon to address a number of issues and this issue should be fixed along with it.
