### ISSUE TITLE
Not getting any sound from a downloaded video

### ISSUE THREAD

**Issue by tg1489** [FreeTubeApp/FreeTube#950]
The video still works after its downloaded and I can watch videos with the sound working on the application itself, but downloading videos always results in no sound whether I click webM or mp4.

(For the record I can download mp3s with sound working.)

Heres an example that I get with no sound: 

https://r4---sn-5uaeznks.googlevideo.com/videoplayback?expire=1610948495&ei=L8sEYIqdC8mE8wSKqY_gCg&ip=73.199.155.85&id=o-ACcbXYXzUjuXhcZ0xS21BueZYLtLNMvgpLxCtWSFz5Mj&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=gS&mm=31%2C29&mn=sn-5uaeznks%2Csn-ab5l6n6s&ms=au%2Crdu&mv=m&mvi=1&pl=22&initcwndbps=2660000&vprv=1&mime=video%2Fwebm&ns=5iWUmnMM53r1WzmYqCUCFQoF&gir=yes&clen=9766077&dur=250.750&lmt=1610864606672892&mt=1610926595&fvip=1&keepalive=yes&c=WEB&txp=5516222&n=NckhfIo8o_z34o&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgEbs4hzlsdrdYk_PbxtExPxI6yXm0EE9HS1GAwCGpgekCIQDRmPndsj-xFKF-Y4Jf-bAY6lRkhG_ZZ8aFDLCL2xmSMQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgIqQjHp_Q5wSG2d4AqLi9IwrvoclwFVYu6nF7oBeqL98CIQDzgGG4wL2qUaUWlpaYmXVNPFYg334dAx_ZsHDRM5TQCA%3D%3D&ratebypass=yes&ir=1&rr=12

**Comment by PrestonN** [comment]
Hello! This is intended.

YouTube does not provide videos with audio for a majority of their formats. This is mentioned in app and these download links are labeled as "video only" which means that audio isn't included. You will have to combine the video and audio yourself if you want one usable file.

Alternatively, there are download links that provide both video and audio, however the quality maxes out at 720p. If this is okay, you could download these files instead. These downloads do not have a label next to them.

There's nothing I can do about the other video links. Apologies for the inconvenience.

**Comment by tg1489** [comment]
> 
> 
> Hello! This is intended.
> 
> YouTube does not provide videos with audio for a majority of their formats. This is mentioned in app and these download links are labeled as "video only" which means that audio isn't included. You will have to combine the video and audio yourself if you want one usable file.
> 
> Alternatively, there are download links that provide both video and audio, however the quality maxes out at 720p. If this is okay, you could download these files instead. These downloads do not have a label next to them.
> 
> There's nothing I can do about the other video links. Apologies for the inconvenience.

Thanks for the reply. I dont get it though, it worked fine in earlier versions not too long ago. Is this something youtube has done recently? And do you think there would be a way around this in the future?

I guess 720 would be fine since downloading a 1080p video, combining the audio, and rendering that again would most likely lose some quality anyway so I feel it would be easier to just do that.

**Comment by PrestonN** [comment]
YouTube has structured their videos like this for as long as I can remember. It's why early on in development it was difficult getting feeds to display at 1080p.

You can likely use something like youtube-dl in combination with ffmpeg to seamlessly combine the video and audio. They have instructions for doing so in various places, so I'd search for that. We can maybe incorporate ffmpeg into FreeTube at some point to handle muxing though we're ways away from looking into that.
