### ISSUE TITLE
Is it possible to enable resoltions greather than 1080p?

### ISSUE THREAD

**Issue by gpioneer90** [FreeTubeApp/FreeTube#957]
I know Invidious has this limitation too for some reason. But the client maxes out at 1080p even though videos definitely have 1440p+ options available on the YouTube website. Is there anything I can do on my end to allow for resolutions greater than 1080p?

Thank you for this very nice app!

**Comment by PrestonN** [comment]
This is a limitation of the video player that we are using and is currently outside of our control to enable the higher resolutions. This goes for Invidious as well, since they use the same player.

Video.js doesn't have full support for WebM video files (Which is what YouTube provides for higher resolutions) which means that it can't play these files. So when the player decides to parse the DASH file, it ignores any resolutions that provide a WebM URL.

Whenever this issue is fixed upstream, I will make sure to update the player on my end and they should be enabled at that point.

**Comment by SySx-Dragonfire** [comment]
Hi @PrestonN,
I tested the [getting started](https://videojs.com/getting-started/#videojs-cdn) of videojs with a 4k webm link and it works!
So is it now possible to update freetube to watch 4k videos???

**Comment by Zedroid** [comment]
@SySx-Dragonfire unfortunately I saw this on another thread:

 > Hi, so thanks for keeping an eye out. Unfortunately it is not VideoJS which prevents us from implementing wide spread 4k support, but instead the [vhs plugin,](https://github.com/videojs/http-streaming/tree/v2.6.4) which we need in order to stream the video rather than download it, to support this. So as it seems, this is not yet implemented. So unfortunately we cannot provide it at the moment
https://github.com/FreeTubeApp/FreeTube/issues/1140#issuecomment-807019658

**Comment by treker7** [comment]
Hi @Zedroid. So I took a look at the supported features list of the [VHS Plugin](https://github.com/videojs/http-streaming/blob/main/docs/supported-features.md#general-notable-features) and under the "General Notable Features" section it says it supports:

 - Any browser supported resolution (e.g., 4k)
 - Any browser supported framerate (e.g., 60fps)
 
 I'm not sure if these features were added before or after your comment, but it definitely seems like it should be possible to add support for these resolutions into FreeTube now. Or is there something else I'm missing here? Thanks!

**Comment by treker7** [comment]
Under [Notable Missing Features](https://github.com/videojs/http-streaming/blob/main/docs/supported-features.md#notable-missing-features) the WebM video format is listed. Is this the problem? Do we need the plugin to support this particular format?

**Comment by Zedroid** [comment]
I hope the devs update the app to integrate this new update from the plugin

**Comment by treker7** [comment]
@PrestonN Could you please weight in on this? If you need any development help I am also happy to pitch in. You would just need to point me in the right direction to help me get started.
