### ISSUE TITLE
Enhancement: MPRIS support

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#97]
https://specifications.freedesktop.org/mpris-spec/latest/
It'd be really nice to have this, even if it's just basic play/pause support.

I've been looking for a way to pause youtube via KDE connect and so far as i understand it would be possible if freetube had MPRIS support.

**Comment by PrestonN** [comment]
I'll definitely take a look at this as I think it would be interesting to include as well.  I'll keep you updated on it but I don't know when I'll be able to take a look at it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as this is baked into Electron
