### ISSUE TITLE
Ability to block/hide channels.

### ISSUE THREAD

**Issue by dudeamax99** [FreeTubeApp/FreeTube#970]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
There are a few I dislike channels that will show up in "Up Next".

**Describe the solution you'd like to see implemented**
Ability to block/hide specified channels.

**Describe alternatives you've considered**
No good alternatives I can think of. 

**Additional context**
Don't show the channel anywhere unless it is directly opened by url or similar.

**Comment by PrestonN** [comment]
Duplicate of #95
