### ISSUE TITLE
Add feature to reduce or remove 5 second gap in-between videos in playlists

### ISSUE THREAD

**Issue by Pretuer** [FreeTubeApp/FreeTube#971]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I use this platform for my Church and I love that it's very quick and responsive one issue I have is the 5 second pause in-between videos (on OSX)

**Describe the solution you'd like to see implemented**
I'd like a way to either reduce the time or remove the time in-between completely

**Describe alternatives you've considered**
We could remove the code for the time in-between

**Screenshots**
N/A

**Additional context**
Add any other context about the feature request here.

**Comment by saideepesh000** [comment]
Hey @PrestonN, if you can say the design and placement of this settings, I might start working on it.

**Comment by PrestonN** [comment]
Sure thing! Here's what I'd expect from a PR for this. What I'd expect is a little more than what's being asked for in this issue, as it's been requested in the past to be able to configure this interval.

In the player settings, I'd like to see a slider (`ft-slider`) that allows the user to pick the "Next Video Interval". This new setting would default at 5 but go anywhere from 0 to 60. Setting it to 0 would play the next video immediately. The logic that handles the next video is the `handleVideoEnded` function in `views/Watch/Watch.js`. The toast message allowing you to cancel the next video playback should persist for however long the user has set their interval, which can be set using the `time` parameter in the toast function. The locale for "Playing next video in 5 seconds..." will need to be updated to handle both singular and plural wording for second(s).

If you need any more information, please feel free to ask.

**Comment by PrestonN** [comment]
Added with #1006
