### ISSUE TITLE
Local api does not use proxy

### ISSUE THREAD

**Issue by schoolprivacy** [FreeTubeApp/FreeTube#976]
Hello

I am not sure if this is intended, but with proxy enabled, local api does not use the proxy, it tries to connect without it.
If i change it to invidious api, the proxy works fine.

**Comment by Svallinn** [comment]
Are you sure you clicked the toggle on?
I just tested the latest version and it works fine for me with the local API
![image](https://user-images.githubusercontent.com/41585298/110225590-f7ca4580-7ede-11eb-8e73-0fc2e3f5510b.png)

**Comment by Svallinn** [comment]
I'll be considering this issue as stale and closing it.
If you believe this problem is still occurring, do not comment on this thread and open a new issue instead.
