### ISSUE TITLE
.zip vs .exe

### ISSUE THREAD

**Issue by harryray33** [FreeTubeApp/FreeTube#981]
Thanks for your quick replies...

Is there any advantage to installing Freetube rather than using it from the zip file? I prefer not to install but it would be nice to be able to choose where the config and history files are written to.

Great programme btw...helluva lot better than using Youtube directly...

**Comment by PrestonN** [comment]
The .zip file allows you to run FreeTube without installing it. It still saves your data in the same place however. Being able to choose where it's saved is a planned feature for a future update.

The other disadvantage is that the browser extension will not work for opening videos directly into FreeTube.

Besides these changes, there are no differences.
