### ISSUE TITLE
[Feature Request] Keyboard shortcut '/' to go to search box

### ISSUE THREAD

**Issue by cyclonejet** [FreeTubeApp/FreeTube#985]

**Comment by GilgusMaximus** [comment]
So while this looks good on paper, it will not work that easily. For example the shortcut is completely out of scope for all European keyboard users. We'd have to settle for a hotkey that works for more than US keyboards. Or wait for the hotkey revamp

**Comment by cyclonejet** [comment]
What do the Europeans have for this particular hotkey? Like in DDG? Something of that sort would be nice.

**Comment by attila-lendvai** [comment]
please add `ctrl + l` also. i keep pressing it just like in the browser before copy-pasting the link...

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing this in favor of https://github.com/FreeTubeApp/FreeTube/issues/2138
