### ISSUE TITLE
Retain Caption Settings Between Videos

### ISSUE THREAD

**Issue by Tamnac** [FreeTubeApp/FreeTube#989]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
 Caption Settings reset to the default options for every video. I don't *think* this is a bug, but I can't be sure.

**Describe the solution you'd like to see implemented**
  Caption Settings are retained between videos

**Describe alternatives you've considered**
  Manually changing the settings for each video. Doable but somewhat frustrating.

**Screenshots**
This is more of a behavior than a design element, so I can't really show examples.

Thank you for your time, and a great app!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2295
