### ISSUE TITLE
Ability to hide Channel information when loading subscription.

### ISSUE THREAD

**Issue by JonnyCodewalker** [FreeTubeApp/FreeTube#99]
Currently when opening a channel you subscribed to you see the entire information about the channel. It would be really awesome to have an option to just directly show the videofeed, so you don't have to scroll down. When subbing to a channel chances are high you do not need to read the channel information.

**Comment by PrestonN** [comment]
I new channel view will be included in the next release, which will put the channel description over to it's own "About" tab.  I'll assume that this is sufficient for this request and close this issue.
