### ISSUE TITLE
Default quality setting not working

### ISSUE THREAD

**Issue by Sir-Voe** [FreeTubeApp/FreeTube#990]
**Behavior of the program:**
Selecting the default quality in player settings does not change the default quality of videos when they start playing

**Expected behavior**
In the settings menu, when I change the player settings to "default quality: 360p", I expect videos to always start playing at that quality.

**To Reproduce**
1. Go to 'settings'
2. Scroll down to 'player settings'
3. Select "default quality: 360p"
4. Play a video

**Environment Information:**
 - OS: Linux mint
 - OS Version: Linux mint 19.3
 - FreeTube version: 0.11.2 beta
 - Installation Method: .deb
 - Primary API Used: Local API

**Comment by PrestonN** [comment]
Please search for duplicate issues before creating new ones. #595 Already exists.
