### ISSUE TITLE
[Feature Request] Match FreeTube's Logo with MacOS' new Application Icon Theme

### ISSUE THREAD

**Issue by JPyke3** [FreeTubeApp/FreeTube#991]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
No, this is not a usage problem

**Describe the solution you'd like to see implemented**
Match FreeTube's logo with MacOS' new theme. As of current it looks really out of place compared to other system icons

**Describe alternatives you've considered**
N/A

**Screenshots**
<img width="476" alt="Screen Shot 2021-01-27 at 5 59 32 pm" src="https://user-images.githubusercontent.com/13283054/106025823-6ab6f400-60c9-11eb-914c-17b8e4ebecb7.png">

**Additional context**
Presumably this would be a really quick change, make the logo smaller, put it in a box with a white background and call it a day.

**Comment by da9idokp** [comment]
@JPyke3 I've made the new icon for Big Sur. You can open the Applications folder, "Get Info" on FreeTube.app and drag in onto the old icon in the upper-left corner to apply. 


[freetube.icns.zip](https://github.com/FreeTubeApp/FreeTube/files/5996695/freetube.icns.zip)

**Comment by PrestonN** [comment]
Someone in our Matrix chat referenced the https://macosicons.com/ site and that there is a pretty nice FreeTube icon there that could possibly be used. The icon appears to be created by @creepertron95 and I'd be willing to make this the new icon for Mac.

@creepertron95 if you do not want me to use your icon with the project then please let me know. I will happily add you to our [Credits Page](https://github.com/FreeTubeApp/FreeTube/wiki/Credits) with this process.

**Comment by creepertron95** [comment]
@PrestonN You can use the icon for FreeTube for Mac. :+1:

**Comment by PrestonN** [comment]
@creepertron95 Thank you very much! It is greatly appreciated! I'll get it included for the new release. I'll update the credits page as well.

Thanks again!

**Comment by GilgusMaximus** [comment]
Closing this as this has been implemented
